### ISSUE TITLE
Create a fusesoc hook for FPGA splice script

### ISSUE THREAD

**Issue by rpenugo** [lowRISC/opentitan#1]
On top of PR lowRISC/stwg-base#847  there is a need to hook this script to fusesoc just like extended run after bitfile generation is complete

@imphil  has offered to help on this.. once the original PR lowRISC/stwg-base#847 merges in.

Creating a tracker for the same

**Comment by imphil** [comment]
That's unnecessary, since we build the bootrom into the bitstream at synthesis time using Vivado directly. The splice script is optional and only used in special cases.
