### ISSUE TITLE
Update flash_ctrl.EXEC value for unlocking execution

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#10022]
Hi @tjaychen, this is related to the signature verification hardening idea that I mentioned earlier. Could you please update the value that unlocks execution to `0xa26a38f7`?

It looks like three lines of source code will also need to be updated: 
* [sw/device/lib/flash_ctrl.c](https://github.com/lowRISC/opentitan/blob/ee1634b6b26f59b40e35e5c6e310c783b267db5e/sw/device/lib/flash_ctrl.c#L300)
* [sw/device/silicon_creator/mask_rom/mask_rom.c](https://github.com/lowRISC/opentitan/blob/ee1634b6b26f59b40e35e5c6e310c783b267db5e/sw/device/silicon_creator/mask_rom/mask_rom.c#L152)
* [sw/device/silicon_creator/mask_rom/mask_rom_epmp_test.c](https://github.com/lowRISC/opentitan/blob/ee1634b6b26f59b40e35e5c6e310c783b267db5e/sw/device/silicon_creator/mask_rom/mask_rom_epmp_test.c#L386)

**Comment by alphan** [comment]
@tjaychen, not sure if you've already seen this but can you wait a little bit before creating a PR for this? I think we want to update the value. I will update the description and add a new comment when we have it. Thanks!

**Comment by tjaychen** [comment]
@alphan right now the value is still `Mubi`, so just let me know when you've settled on something and we can update as needed.

**Comment by alphan** [comment]
> @alphan right now the value is still `Mubi`, so just let me know when you've settled on something and we can update as needed.

Thanks @tjaychen, just to confirm, we can use any 32-bit value, right?

**Comment by tjaychen** [comment]
yes. just to confirm, is there any reason this value needs to be hidden from open source? my understanding is that it does not need to be right?

**Comment by alphan** [comment]
No, there is no reason to hide it. It would also be nice to have it as a
define in the generated flash_ctrl_regs.h if possible (for tests mostly).
Thanks @tjaychen!

**Comment by tjaychen** [comment]
yeah we can do that.
Let me get some of the prep work ready for this and then we can make the
change whenever you're ready.

**Comment by alphan** [comment]
@tjaychen we can define this value to be `0xa26a38f7` (unless I receive other comments in #10024 that require me to change it to something else).

**Comment by alphan** [comment]
Done in #10061, thanks @tjaychen!
