### ISSUE TITLE
[dv] Create clock and reset connectivity test for all IPs in top-level

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#10039]
Use FPV connectivity framework, so that we can eliminate this kind of SW tests.

@sriyerg @cindychip

**Comment by weicaiyang** [comment]
@matutem this sounds like a P1 task. WDYT?

**Comment by matutem** [comment]
An update: the global clock and alert_handler cg_en connectivity was instrumented in formal a few weeks ago in https://github.com/lowRISC/opentitan/pull/10965. The reset and alert_handler enable connectivity is yet to be done.

**Comment by moidx** [comment]
At this point is this a DV enhancement or part of the M2 plan? Have we implemented the sw connectivity tests yet?

Marking as M2 assuming this will reduce the number of software tests.

**Comment by tjaychen** [comment]
yeah i think this is indeed part of the M2.
And there is a testplan for this [here](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/chip_conn_testplan.hjson)

There are also additional items related to `ast` that fall into this category, so definitely something we need to complete.
