### ISSUE TITLE
[spi_device] Recoverable last_read_addr

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#10038]
## Last read Address

The last_read_address is for SW to check which address the host system accessed. It is reset when the IP is in reset. Considering the power down and up scenario, it is better to be recoverable by SW (writable).

**Comment by tjaychen** [comment]
ah i'm pretty sure this one is future release.

**Comment by weicaiyang** [comment]
We may want to re-evaluate this as it affects some base usage.

Case1:
Assume upstream SPI host reads a 1k data from read buffer, and realizes there are some errors, then there is no way to re-read this 1k data again, as there is no way to reset last_read_addr unless we issue an reset, and SW probably already overwrites this 1k due to the flip interrupt.
Hence, we need to assume SPI data loss rate is extremely low, given we may use this mode to pass an image to upstream SPI.

Case2:
In flash mode, SW updates date based on watermark or flip interrupt, in the meanwhile, SPI host reads the data in SPI memory. If CPU is interrupted and it can't have data ready for SPI to read, SPI host may read back wrong data. If it occurs, there is no way to re-read the correct data, unless we reset SPI device.
Hence, we need to assume SW can always prepare data quick enough. Perhaps interrupt routine needs to be turned off while we're using this mode?

If this really matters, we'd better have a timeline for this feature.

@tjaychen

**Comment by tjaychen** [comment]
yeah these are good points. 
I didn't really consider this when the mode was created. 

@a-will any thoughts? I feel like in the worst case, if the host encounters an error, it probably would signal the device in a sideband manner. I don't think we necessarily need to be able to read back the last 1KB buffer, but the device should be able to "start" again from scratch.

@weicaiyang just to confirm, we can do restart by resetting `SPI_DEVICE` right? This might not be evident at the block level, but i think SPI device does have a dedicated software reset.

**Comment by a-will** [comment]
> @a-will any thoughts? I feel like in the worst case, if the host encounters an error, it probably would signal the device in a sideband manner. I don't think we necessarily need to be able to read back the last 1KB buffer, but the device should be able to "start" again from scratch.

You know me: I prefer not to take risks with correctness by putting software in the loop for feed-forward I/O protocols, so I would never create a system that does (pretend flash array) reads to spi_device in flash mode, myself ;)

In any case, the intended application was for loading pre-validated initial firmware to the host, where the host is doing a straight block read. I don't think there is really any soft means of recovering from failures there. If the host stops reading sequentially, we'd likely need to reset the host and start over, as the mode's requirements have been violated.

**Comment by tjaychen** [comment]
hahah...i will admit that this kind of feed forward read is kind of scary...but is slightly less scary than some of the "predictive reads" i heard about ... i think we also planned for actual flash read at some point, but there didn't seem to very solid use cases for that.  Do you think that's still the case? 

Ah i see, i guess if the host needs to restart..would we be notified somehow to know to restart spi_device in this case?

**Comment by a-will** [comment]
> i think we also planned for actual flash read at some point, but there didn't seem to very solid use cases for that. Do you think that's still the case?

There is a use case (the same one that this streaming mode attempts to address), but that mechanism comes with security implications we had previously decided to avoid.

> Ah i see, i guess if the host needs to restart..would we be notified somehow to know to restart spi_device in this case?

This really depends on the error responses of the host, so it's hard to say. We can always detect out-of-sequence reads, though.

**Comment by tjaychen** [comment]
ah, so it's as simple as tying a gpio to a device's reset line or something? (or a gpio that is flipped after reset)

**Comment by a-will** [comment]
> ah, so it's as simple as tying a gpio to a device's reset line or something? (or a gpio that is flipped after reset)

Assuming the RoT has such powers, yes. That may not always be the case, as it depends on the system architecture.

**Comment by tjaychen** [comment]
sorry that was a typo.. i meant to type "ah so it **ISN'T** as simple as.."

**Comment by weicaiyang** [comment]
Based the discussion and we have a dedicate reset to spi_device, I guess it's fine to leave it as is for now

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2 because we should confirm with the product team that our current implementation suffices.

**Comment by hcallahan-lowrisc** [comment]
Conclusion from product-team feedback: we can and should assume last_read_addr is reset to zero on power cycle / sleep i.e. is non-recoverable.
Moving back to FutureRelease for now.

**Comment by a-will** [comment]
This feature was only intended for scenarios where OpenTitan never resets without the upstream SPI host also resetting. In that case, there should be no need to recover LAST_READ_ADDR.

Closing as not planned.
