### ISSUE TITLE
example code for spi host

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#10042]
Hi 
Is there any spi host code example for reference.
I can't find it in
:~/mcqueen/opentitan/sw/device/lib/dif$ ls 
autogen                        dif_clkmgr.h            dif_entropy_src.md           dif_keymgr.h             dif_otp_ctrl.c            dif_rstmgr.c              dif_spi_device_unittest.cc
dif_aes.c                      dif_clkmgr.md           dif_entropy_src_unittest.cc  dif_keymgr.md            dif_otp_ctrl.h            dif_rstmgr.h              dif_sram_ctrl.c
dif_aes.h                      dif_clkmgr_unittest.cc  dif_entropy_unittest.cc      dif_keymgr_unittest.cc   dif_otp_ctrl.md           dif_rstmgr.md             dif_sram_ctrl.h
dif_aes.md                     dif_csrng.c             dif_gpio.c                   dif_kmac.c               dif_otp_ctrl_unittest.cc  dif_rstmgr_unittest.cc    dif_sram_ctrl.md
dif_aes_unittest.cc            dif_csrng.h             dif_gpio.h                   dif_kmac.h               dif_pinmux.c              dif_rv_plic.c             dif_uart.c
dif_alert_handler.c            dif_csrng.md            dif_gpio.md                  dif_kmac.md              dif_pinmux.h              dif_rv_plic.h             dif_uart.h
dif_alert_handler.h            dif_csrng_unittest.cc   dif_gpio_unittest.cc         dif_kmac_unittest.cc     dif_pinmux.md             dif_rv_plic.md            dif_uart.md
dif_alert_handler.md           dif_edn.c               dif_hmac.c                   dif_lc_ctrl.c            dif_plic.c                dif_rv_plic_unittest.cc   dif_uart_unittest.cc
dif_alert_handler_unittest.cc  dif_edn.h               dif_hmac.h                   dif_lc_ctrl.h            dif_plic.h                dif_rv_timer.c            dif_uart_unittest.h
dif_aon_timer.c                dif_edn.md              dif_hmac.md                  dif_lc_ctrl.md           dif_plic.md               dif_rv_timer.h            dif_usbdev.c
dif_aon_timer.h                dif_entropy.c           dif_i2c.c                    dif_lc_ctrl_unittest.cc  dif_plic_unittest.cc      dif_rv_timer.md           dif_usbdev.h
dif_aon_timer.md               dif_entropy.h           dif_i2c.h                    dif_otbn.c               dif_pwrmgr.c              dif_rv_timer_unittest.cc  dif_usbdev.md
dif_aon_timer_unittest.cc      dif_entropy.md          dif_i2c.md                   dif_otbn.h               dif_pwrmgr.h              dif_spi_device.c          _index.md
dif_base.h                     dif_entropy_src.c       dif_i2c_unittest.cc          dif_otbn.md              dif_pwrmgr.md             dif_spi_device.h          meson.build
dif_clkmgr.c                   dif_entropy_src.h       dif_keymgr.c                 dif_otbn_unittest.cc     dif_pwrmgr_unittest.cc    dif_spi_device.md         README.md

Thanks a lot.

**Comment by martin-lueker** [comment]
It looks like its still lingering in review in #8872.   (@cfrantz, @mcy: Is there any think else that is needed for the SPI_HOST DIF?)  @nicolast0604, in the meantime you can pull #8872.

**Comment by tjaychen** [comment]
we'll close this issue for now since there is example host code. 
If you find any issues, feel free to open another ticket to track.
