### ISSUE TITLE
[spi_device] Check if CSb deasserted in the middle of byte transfer in Generic Mode

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#10058]
Current FwMode(GenericMode) ties `fwm_rxerr` to 0. The signal intended to catch the receiver error in FwMode, which is to catch the CSb de-assertion without completing the byte transfer.

I decided to icebox the feature and implement in next revisions (or removing Generic mode entirely).

This issue is to track the item.

[Effort estimate](https://github.com/lowRISC/opentitan/issues/10058#issuecomment-1481384114_) by @hcallahan-lowrisc:
> Note that there is a number of open issues about CSB behaviour and robustness to errors, so some estimated effort (if deemed necessary) may overlap between those issues. (https://github.com/lowRISC/opentitan/issues/10058 https://github.com/lowRISC/opentitan/issues/12747 https://github.com/lowRISC/opentitan/issues/15517 https://github.com/lowRISC/opentitan/issues/15721)
> 
> estimate 20
> remaining 2023-03-23 20

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2 because even though this is about robustness in an environment with errors, we should check with the product team if the behavior of `spi_device` is acceptable.  If yes, we can defer this to https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease.

**Comment by hcallahan-lowrisc** [comment]
Note that there is a number of open issues about CSB behaviour and robustness to errors, so some estimated effort (if deemed necessary) may overlap between those issues. (https://github.com/lowRISC/opentitan/issues/10058 https://github.com/lowRISC/opentitan/issues/12747 https://github.com/lowRISC/opentitan/issues/15517 https://github.com/lowRISC/opentitan/issues/15721)

> estimate 20
> remaining 2023-03-23 20

**Comment by moidx** [comment]
We'll evaluate the behavior in silicon and determine if there are any changes needed. Adding FutureRelease for now.

**Comment by msfschaffner** [comment]
Since we plan to deprecate generic mode, this will no longer be necessary.

CC @a-will
