### ISSUE TITLE
[spi_device] Guard SW access to DPSRAM while in SPI transaction w/ Flash / Passthrough mode

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#10065]
If upload function is active, there's chance that the upload module tries to push entries to fetch from DPSRAM and SW to access the DPSRAM. 

This condition should be handled.

1. upload module to use grant.
2. SW to lower the priority in the sram arbiter (prim_sram_arbiter to have Fixed Priority)

**Comment by tjaychen** [comment]
> 

number 2 could be easy and hacky to do :)
you could just silence the software request whenever there is another non-software request hehe.

**Comment by eunchan** [comment]
> number 2 could be easy and hacky to do :) you could just silence the software request whenever there is another non-software request hehe.


Sounds good :) I should do that until `prim_sram_arbiter` implements Fixed Priority

**Comment by eunchan** [comment]
Implemented in #10068 Thanks! I will also work on Hw Grant too.

**Comment by tjaychen** [comment]
@eunchan i'm pretty sure this one has already been handled. 
I'll close for now, please re-open if you disagree.
