### ISSUE TITLE
CSRNG D2S Review AIs

### ISSUE THREAD

**Issue by mwbranstad** [lowRISC/opentitan#10095]
Action Items:

- [x] [mark, chris] discuss offline how to rename LOGIC.INTEGRITY -> ref: https://github.com/lowRISC/opentitan/pull/10118
- [x] [mark, chris] need to align standardized names with terminology in comportability spec ->  ref: https://github.com/lowRISC/opentitan/pull/10118
- [x] [chris] align countermeasure spreadsheet 
- [x] [miguel] to follow up on {Key,v} register issue with labs -> https://github.com/lowRISC/opentitan/issues/10477 (issue opened so checking this as completed)
- [x] [mark] add MUBI protection for “flag0” -> https://github.com/lowRISC/opentitan/pull/10132
- [x] [mark] add comment describing that repetition checks are done in EDN. same thing for the repetition check, comment on why only 64bits are checked. -> https://github.com/lowRISC/opentitan/pull/10132
- [x] [mark, chris] do not decode MUBI at the top and route single bit, but use a non-flopped sync and consume multiple MUBI where used in RTL -> https://github.com/lowRISC/opentitan/pull/10132
- [x] [mark] remove csrng_track_sm FSM, add observation points to existing sparse FSMs. ->  not changing
- [x] [mark] csrng_cmd_stage counter error: feed this signal into FSM to locally escalate. -> https://github.com/lowRISC/opentitan/pull/10132
- [x] [mark] csrng_ctr_drbg_gen counters: this would be a good one to harden. Decision is to add prim_count to 32bit counter. Need to check whether 96bit counter should be duplicated as well. -> https://github.com/lowRISC/opentitan/pull/10132
- [x] [mark] Bus Consistency: would make sense to wire up the alerts with the main FSM. Local escalation. -> Not doing, statistically possible, so a recov, not fatal alert. Confirm with Chris.
- [x] [mark, chris, vogelpi] u_prim_fifo_genbits: This should probably be changed to OutputZeroIfEmpty = 0. -> https://github.com/lowRISC/opentitan/pull/10132
- [x] [mark] list LC gate for debug as a CM in Hjson. -> ref: https://github.com/lowRISC/opentitan/pull/10118
- [x] [mark] Add a prim_mubi4_sync block to buffer the flag0 field. -> https://github.com/lowRISC/opentitan/pull/10132

**Comment by tjaychen** [comment]
just curious, is this item "remove csrng_track_sm FSM, add observation points to existing sparse FSMs." a security item? Just want to be cognizant to not turn D2S review into a whole module code review..

**Comment by tjaychen** [comment]
hmmm... good catch on the `prim_count` and local escalation. I'm not entirely sure in some of my blocks i have a local reaction to that either.

**Comment by mwbranstad** [comment]
@tjaychen agree that scope should only be security. In this specific case, the "lifecyce_debug" signal was attached to these tracking state machines. Instead of questioning the security mechanism, I questioned the usefulness of the the state machine for debug based on priori use. So although it appears like a functional review item, it was truly related to security.

**Comment by mwbranstad** [comment]
@cdgori Chris, one checklist item for you, and @moidx Miguel, one for you. Can we get these checked off?

**Comment by cdgori** [comment]
> @cdgori Chris, one checklist item for you, and @moidx Miguel, one for you. Can we get these checked off?

Done, but you will have to check the box as I cannot edit your comment.  

For anyone else doing this work, I decided to align the order in the spreadsheet with the order in the hjson for easier maintenance in the future at the expense of a little tedium now.

**Comment by mwbranstad** [comment]
@msfschaffner all the boxes are checked now. Should we close this issue, or are there some additional steps to do before that happens in the security review flow?

**Comment by msfschaffner** [comment]
@mwbranstad same comments as on https://github.com/lowRISC/opentitan/issues/10096#issuecomment-1026162205, number 3).

We'll close the issue automatically with the prj.hjson update.

**Comment by mwbranstad** [comment]
Links added where needed.

**Comment by msfschaffner** [comment]
OK the last thing missing now is is the AES label cleanup, see this comment: https://github.com/lowRISC/opentitan/pull/10132#discussion_r793137647
