### ISSUE TITLE
[entropy_src, CI]: More stable health checks for entropy_src_smoketest.c

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#10092]
In CI, `entropy_src_smoketest.c` seems prone to failure. It performs a complete binary check of a 384-bit seed, that it pulls from the ENTROPY_DATA register.   The numeric value [is listed as a constant in entropy_src_smoketest.c](https://github.com/lowRISC/opentitan/blob/7dbbbd5410f3aecf120d5d0ec1cbb3b3fd508feb/sw/device/tests/entropy_src_smoketest.c#L18)

   The output of this register is intended to _appear_ completely non-deterministic, and even if the input RNG data is known completely, it is challenging to predict the output values.   
- The IP can drop excess values once its internal FIFOs are filled.  
- Health check failures stall the output and force more RNG inputs to be absorbed into the seed. 
- Finally this output is shared with the other CSRNG configurations, and thus changes in timing could force this value to require updating due to race conditions.  

DV gets around these concerns by predicting the healthcheck results in scoreboarding, and then otherwise _assuming_ that some seeds will be dropped, and so the DV test environment keeps a list of trial seeds to check. 

We are now seeing that even minor changes in the BOOT_ROM have been observed to change the entropy_src output, and the reason for these changes is hard to explain.  As we get to closer the final configuration such hard to explain collisions may become more frequent.

Such changes have already been applied in several commits, such as https://github.com/lowRISC/opentitan/commit/36ebb51dbee52b34e515f69d84c7759b98c2c561, https://github.com/lowRISC/opentitan/commit/36e741e6cdc18ace050185b46c284b02b20eaccc, and  https://github.com/lowRISC/opentitan/commit/8961a8026331fcf39899d73e10a9e5a3c69193b2.  

In each case it is not clear whether any analysis of the expected result was performed, or whether the value has just been updated to pass the CI test.

Do we want to relax the pass condition for this test?  
- We could, for instance, check to see that _something_ is coming out (other than all 1's or all 0's).  

- Alternatively we could broaden the scope of this CI test to check whether the CSRNG software instance is giving the predicted value.   This would be far more deterministic, as it would not require any toggling between the CSRNG_BUS HW output vs. the ENTROPY_SRC register.

**Comment by tjaychen** [comment]
@martin-lueker the test was definitely just done to pass the CI test (no expected result performed).
If there's a place in the entropy complex path where this makes more sense to do (for example CSRNG), that definitely makes sense. 

At that point I guess it should be expanded to entropy complex smoketest? 

One thing I don't follow though, if the entropy source read out isn't deterministic, wouldn't the csrng, which depends on entropy source output, also be non-deterministic?

**Comment by martin-lueker** [comment]
I see, well we can keep editing it as needed, and I'll stop trying to get to the bottom of this test.

> One thing I don't follow though, if the entropy source read out isn't deterministic, wouldn't the csrng, which depends on entropy source output, also be non-deterministic?

It's a good question.  There is a small buffer in the entropy_src that can hold four seeds.  (And ow that I think about it, this should be enough for CI tests, so I am very perplexed)   Using the SW port on the CSRNG would have the advantage that it grabs the seed from the hardware port.  However it would still need to be configured, so if there were somehow a deficit of seeds and some started getting dropped you are right, there would be another timing dependency.  Maybe there is nothing to be done, though it is worth discussing.

All the same, I put a comment point to this issue in the test.  If others get frustrated at having to update the test in their PR's we can discuss it here.

**Comment by tjaychen** [comment]
sounds good. Thank you Martin.

**Comment by a-will** [comment]
Consider me among the frustrated. I think we ought to not keep such flaky tests in CI and instead, find a different strategy for this block.

**Comment by tjaychen** [comment]
see #13981 for how the test should work going forward.
