### ISSUE TITLE
[dv,chip] Missing OTP_EXT_VOLT connection in top_earlgrey/dv/tb

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#10116]
This port was added to `chip_earlgrey_asic` in d13f442539 last April(!) and not connected up to the chip top-level testbench. This causes warnings when building the VCS simulation.

@msfschaffner (since you added the port!); @sriyerg (for visibility, since this is a little worrying! Hopefully toggle coverage would have caught it eventually).

**Comment by sriyerg** [comment]
Aah, seems like you beat me to this @msfschaffner. I was about to address it. THanks.
