### ISSUE TITLE
[SYSRST_CTRL] Clear the stored_value when ultra low power feature is disabled

### ISSUE THREAD

**Issue by patel-madhuri** [lowRISC/opentitan#10138]
We need to clear the update_stored_value and stored_value_q once the ultra low power feature is disable. If this is not clear the det_pulse is triggered again before the timer starts for the next iteration. 
![ulp_issue](https://user-images.githubusercontent.com/92722737/149911014-6065aff8-77ad-4c19-8d45-2710ceb3cfa0.PNG)
From the waveform we can see the ac_present_det_pulse is triggered again before the timer starts as soon as the ultra low power feature is enabled. 

Draft PR https://github.com/lowRISC/opentitan/pull/9962 can be used to regenerate the issue.

Command to run the test: 
./util/dvsim/dvsim.py hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson -i sysrst_ctrl_ultra_low_pwr --waves --tool xcelium --fixed-seed 2122159512

**Comment by msfschaffner** [comment]
@patel-madhuri #10636 updates the debounce behavior, so we should reassess whether this bug with that fix applied.

**Comment by patel-madhuri** [comment]
As the bug is resolved and test is merged, I am closing this issue. Thanks!
