### ISSUE TITLE
[SYSRST_CTRL] key_intr_status detects the wrong edge transition of input pin and before the debounce timer starts

### ISSUE THREAD

**Issue by patel-madhuri** [lowRISC/opentitan#10144]
The l2h event is triggered before the key intr debouncer timer starts for h2l edge transition of ec_rst_l_in input pin. This is because the reset value of update_stored_value variable is 'h1 which generates l2h_detected_pulse_o. 
![edge_detect_bug](https://user-images.githubusercontent.com/92722737/149959303-4cbfb486-e9e3-4317-868c-d4425f37f62c.PNG)
The waveform at timeA marker shows the key_intr_status register indicates the interrupt before the timer starts and at h2l edge transition of ec_rst_l_i input pin.

Command to run the test: 
./util/dvsim/dvsim.py hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson -i sysrst_ctrl_edge_detect --waves --tool xcelium --fixed-seed 3501254490

**Comment by patel-madhuri** [comment]
Draft PR #9962 can be used to regenerate the issue.

**Comment by msfschaffner** [comment]
@patel-madhuri #10636 updates the debounce behavior, so we should reassess whether this bug with that fix applied.

**Comment by patel-madhuri** [comment]
As the bug is resolved, I am closing this issue. Thanks!
