### ISSUE TITLE
[rv_dm] Spi_host does not have connect through rv_dm sba?

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#10153]
Hi Tim,

I do not think RV_DM sba bus via JTAG has access to spi_host0 and spi_host1 CSRs. Looks like in top-level their TL buses are not connected to RV_DM sba. Just want to confirm if this is intended? 

Thanks,
Cindy

**Comment by tjaychen** [comment]
thanks for the catch @cindychip. This is a bug, I forgot to add `spi_host` to the sba bus when I moved `spi_host` outside ofd the peripherals. I will fix.

**Comment by sriyerg** [comment]
A little late, but nice catch! Thank you for your efforts in setting up the CSR suite of tests via JTAG DMI (SBCS) at the chip level. The CSR suite of tests may seem simplistic, but sometimes they do catch critical issues like this.
