### ISSUE TITLE
[flash_ctrl] Questions On Secret Seeds (Creator and Owner) and OTP Seed Functionality

### ISSUE THREAD

**Issue by TimEwins** [lowRISC/opentitan#10188]
The Spec says: -

Secret Information Partitions

Two information partition pages (one for creator and one for owner) in the design hold secret seeds for the key manager. These pages, when enabled by life cycle and otp, are read upon flash controller initialization (no software configuration is required). The read values are then fed to the key manager for later processing. There is a page for creator and a page for the owner.

This may be true for the secret seeds via Life Cycle Controller, but is does not seem to be the case for the OTP Interface …

**SECRET SEEDS**

During Power Up Initialisation, the secret seeds are output from the Flash Ctrl into the Key Manager, these keys reflect what is programmed into 

    // Secret partition 0 (used for creator): Bank 0, information partition 0, page 1 (Addr 0x0800, 8 Words)
    // Secret partition 1 (used for owner):   Bank 0, information partition 0, page 2 (Addr 0x1000, 8 Words)

Question 1: Using Default CSR values, these secret seeds are NOT read out during INIT.  They are only output during INIT if FLASH_CTRL.INIT (0x18) is set to 1.  However, its default reset value is 0.  

The description for this bit says: -

“Initializes the flash controller. During the initialization process, the flash controller reads out the root seeds before allowing other usage of the flash controller”

Just checking the wording, as this implies the bit controls the Initialization period, which it seems it does not?  This bit controls whether the seeds are read out or not during the initialization period?

Is this the intended functionality? Or is the Reset Value incorrect?

Question 2: It has been observed that FLASH_CTRL.INIT does not exclusively enable the Secret Seeds for output, it also enables the OTP Seed Interface and the RMA Seed interface.

Question 3: To get the Seeds to work, we have to set FLASH_CTRL.INIT to 1 as soon as we start a test (via SW), to get the Seed features to work.

Question 4: It is also noticed that the parameter KEYMGR_FLASH_DEFAULT as defined in both RTL and DV, is unused (maybe left over from a previous version of the TB)

parameter keymgr_flash_t KEYMGR_FLASH_DEFAULT = '{
    seeds: '{
     256'h9152e32c9380a4bcc3e0ab263581e6b0e8825186e1e445631646e8bef8c45d47,
     256'hfa365df52da48cd752fb3a026a8e608f0098cfe5fa9810494829d0cd9479eb78
    }
  };
      Observation 5:  When an RMA Ack has been sent, the RMA State Machine remains in its ‘final’state, until the                device is reset.  I suspect this because after an RMA the DUT is effectively inoperable.

**OTP Seeds**

During Flash Initialisation, the Flash Controller REQUESTS two seeds from the OTP (which makes it different to the Secret Seeds which are output, not input)

These two seeds, Address and Data are sent onto the Scramble Feature in the Flash PHY.

There is little or no information on this in the spec.  I have arrived at this functionality being ‘true’ by investigating the design and waveforms.

Question 6: Is this the functionality as you see it?  The OTP Seeds seem to have no dependence on any Info Partitions.

Question 7: As previously discussed in a meeting, the SCRAMBLE feature will be thoroughly tested at V3, so for V2, we just need to confirm that a seed read from OTP makes it to the SCRAMBLE block.  I am considering probing into the DUT for this test.  Although not ideal, it is quicker, and the full feature will be tested at V3.  What is your opinion?

**Comment by tjaychen** [comment]
> 



> The Spec says: -
> 
> Secret Information Partitions
> 
> Two information partition pages (one for creator and one for owner) in the design hold secret seeds for the key manager. These pages, when enabled by life cycle and otp, are read upon flash controller initialization (no software configuration is required). The read values are then fed to the key manager for later processing. There is a page for creator and a page for the owner.
> 
> This may be true for the secret seeds via Life Cycle Controller, but is does not seem to be the case for the OTP Interface …
> 
> **SECRET SEEDS**
> 
> During Power Up Initialisation, the secret seeds are output from the Flash Ctrl into the Key Manager, these keys reflect what is programmed into
> 
> ```
> // Secret partition 0 (used for creator): Bank 0, information partition 0, page 1 (Addr 0x0800, 8 Words)
> // Secret partition 1 (used for owner):   Bank 0, information partition 0, page 2 (Addr 0x1000, 8 Words)
> ```
> 
> Question 1: Using Default CSR values, these secret seeds are NOT read out during INIT. They are only output during INIT if FLASH_CTRL.INIT (0x18) is set to 1. However, its default reset value is 0.
> 
> The description for this bit says: -
> 
> “Initializes the flash controller. During the initialization process, the flash controller reads out the root seeds before allowing other usage of the flash controller”
> 
> Just checking the wording, as this implies the bit controls the Initialization period, which it seems it does not? This bit controls whether the seeds are read out or not during the initialization period?
> 
> Is this the intended functionality? Or is the Reset Value incorrect?

I can update the language here. The init bit does 2 things:
1. it requests the address / data scramble keys from otp
2. it reads out the root seeds from flash and sends them to keymgr. 

So this bit does control the initialization period.  Does that answer your question
The init is meant to be started by ROM.
> 
> Question 2: It has been observed that FLASH_CTRL.INIT does not exclusively enable the Secret Seeds for output, it also enables the OTP Seed Interface and the RMA Seed interface.

yes that's right.  This actually seems like a bug I need to fix.
The INIT should gate the otp and flash seeds, but it should not gate RMA entry.  I will file a separate issue for this. 

> 
> Question 3: To get the Seeds to work, we have to set FLASH_CTRL.INIT to 1 as soon as we start a test (via SW), to get the Seed features to work.

that is correct. 
> 
> Question 4: It is also noticed that the parameter KEYMGR_FLASH_DEFAULT as defined in both RTL and DV, is unused (maybe left over from a previous version of the TB)
> 
> parameter keymgr_flash_t KEYMGR_FLASH_DEFAULT = '{ seeds: '{ 256'h9152e32c9380a4bcc3e0ab263581e6b0e8825186e1e445631646e8bef8c45d47, 256'hfa365df52da48cd752fb3a026a8e608f0098cfe5fa9810494829d0cd9479eb78 } }; 

let me explain this part.  The intermodule connection of the design is automated. The `keymgr_flash_default` will be automatically used IF for a particular integration there was no flash and keymgr needed a default value on its input.   However, in this integration, since there is both a flash / keymgr, there is no need for this parameter to be used. 

Observation 5: When an RMA Ack has been sent, the RMA State Machine remains in its ‘final’state, until the device is reset. I suspect this because after an RMA the DUT is effectively inoperable.

that is correct. 

> 
> **OTP Seeds**
> 
> During Flash Initialisation, the Flash Controller REQUESTS two seeds from the OTP (which makes it different to the Secret Seeds which are output, not input)
> 
> These two seeds, Address and Data are sent onto the Scramble Feature in the Flash PHY.
> 
> There is little or no information on this in the spec. I have arrived at this functionality being ‘true’ by investigating the design and waveforms.

yes i will update the spec to explain this. 

> 
> Question 6: Is this the functionality as you see it? The OTP Seeds seem to have no dependence on any Info Partitions.

that is correct, these are meant purely for flash scrambling. 

> 
> Question 7: As previously discussed in a meeting, the SCRAMBLE feature will be thoroughly tested at V3, so for V2, we just need to confirm that a seed read from OTP makes it to the SCRAMBLE block. I am considering probing into the DUT for this test. Although not ideal, it is quicker, and the full feature will be tested at V3. What is your opinion?

Actually let's sync up on this with Anka.  Something occurred to me today about the schedule and we probably cannot delay scramble until V3.  I will start a thread with Anka about this.

**Comment by TimEwins** [comment]
As the documentation updates ahve been marked as fixed, we can close thie Ticket.
