### ISSUE TITLE
[flash_ctrl] Flash CONTROL Register General

### ISSUE THREAD

**Issue by TimEwins** [lowRISC/opentitan#10189]
This is just a Spec clarification Issue

Register FLASH_CTRL.CONTROL (0x20).  This is the main Flash Operation Control register.  

The Description of the START bit in the specification reads: -

START	Start flash transaction. This bit shall only be set after the other fields of the CONTROL register and ADDR have been programmed

The verification environment does not do this as such.  Currently the START bit is set ‘at the same time’ as the other fields in the CONTROL register, but after the ADDR has been programmed.

There seem to be no issues with this.  Just checking that there is no underlying hidden requirement here.

**Comment by tjaychen** [comment]
ah yes.  Same time or later is fine. I will update the language of the spec.

**Comment by TimEwins** [comment]
Spec updated .. close
