### ISSUE TITLE
[rv_core_ibex] Random instruction reseeding

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#10194]
The ibex instruction randomization must be reseeded by software via CSR.
Since there is no hardware mechanism for this reseed, it is important that software periodically obtains a new random value from its [local random register](https://docs.opentitan.org/hw/ip/rv_core_ibex/doc/index.html#Reg_rnd_data) and program it into the CSR.

For example, this can be done on every entry into an "idle" loop by the software.

**Comment by cdgori** [comment]
My immediate gut reaction was "well that means we have to trust the software to do this" - but I guess if the software image has been subverted, disabling the instruction randomization is the least of our worries ...

**Comment by tjaychen** [comment]
yeah..i think ideally we do hardware, but it's more of a lack of time at this point..

**Comment by cdgori** [comment]
understood and seems reasonable.  Should we leave hardware as future proposed enhancement?

**Comment by tjaychen** [comment]
yes definitely, i will file an issue.

**Comment by tjaychen** [comment]
@alphan it just occurred to me, should ROM be doing this..?

**Comment by moidx** [comment]
Added PR #13367 to add support for this in the ROM init sequence.
