### ISSUE TITLE
[sram_ctrl] D2S review opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10195]
- [x] [tim/msf] to double check what is returned upon an invalid instruction fetch. Check whether we can return an invalid instruction value in that case.
- [ ] [tim/msf] make sure standardized countermeasures are listed explicitly for each block (redun count, fsm, bus integrity)
- [x] [msf] Add recommended assets: 
  - Add SRAM_CTRL.CTRL.REGWEN
  - Add SRAM_CTRL.EXEC.REGWEN
  - Add SRAM_CTRL.EXEC.MUBI (?)
  - Add life cycle MUBI (DFT_EN, ESCALATE_EN)
- [x] [msf] Update docs: replace “new” with “updated”, reword part about S&P architecture

**Comment by tjaychen** [comment]
@GregAC do you have a suggestion for what the return value should be on an error?

**Comment by msfschaffner** [comment]
Maybe we can check wheter an all-zero value works?
That would be the simplest option - otherwise we have to add an RV specific value into the tlul adapter primitive,,,

**Comment by tjaychen** [comment]
i honestly wonder if i checked this at some point and just don't remember.
I'll have a quick look at the riscv spec.

**Comment by cdgori** [comment]
Just a comment, you all probably won't forget, but we agreed to make this invalid instruction value a param.

**Comment by GregAC** [comment]
> @GregAC do you have a suggestion for what the return value should be on an error?

The RISC-V spec defines all 0s as a permanently reserved illegal instruction. So 0 should do the job nicely.

**Comment by tjaychen** [comment]
thanks Greg, I will try to have a look today and fix.

**Comment by msfschaffner** [comment]
I took a stab at the rdata blanking in #10274 as well.
