### ISSUE TITLE
[rom_ctrl] Align ROM width to 40bit

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10209]
We currently are experiencing issues in closed-source sims due to an SVA that fires due to width mismatches (the closed source uses an aligned ROM macro width of 40bit due to memory compiler limitations, whereas the open-source uses 39bit).

We determined that the easiest way to fix this would be to align the ROM to 40bit in opensource as well.

Implementation wise there are multiple options: only make the physical width 40bit, but keep the logical width that the ROM controller operates on at 39bit, or align both to 40bit. I would say we do whatever is more convenient.

@tjaychen do you remember where that issue was filed initially for reference?

**Comment by tjaychen** [comment]
the issues of interest are ..
#7033 (the original issue where we said screw it, let's keep it at 39) and #9766 where the closed source db reported the issue.

I think unfortunately in this case we just need to align to the closed source case, OR, make the checking slightly smarter only for ROM.  What do you think @rswarbrick

**Comment by rswarbrick** [comment]
I'm pretty strongly against hacking stuff to get the closed source version working. We could just loosen the check that's failing in the linked issue: it's only there as a sanity check.

**Comment by tjaychen** [comment]
that sounds good too. I guess whoever has the time the next couple of days can have a look. I admittedly have not checked to see exactly which check is failing and why.

**Comment by msfschaffner** [comment]
I should probably correct myself above (since I was also the person who pointed out in #7033 that this could be a security risk). If possible we should find a fix on the DV side for this.

**Comment by tjaychen** [comment]
turns out @rswarbrick already had a mechanism to address this in `mem_bkdr_util`.
After adding the "extra" bits to ROM, everything now works fine.

**Comment by rswarbrick** [comment]
Tada! :-D
