### ISSUE TITLE
[rom] Determine appropriate value for initial watchdog bite timer

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#10215]
The watchdog bite timer will be set in assembly prior to entropy complex setup and SRAM scrambling. The value is set early in assembly and so cannot easily depend on lifecycle state or an OTP configuration value which means it needs to be relatively conservative. Once the mask ROM C runtime is initialized the watchdog bite timer value can be updated to a more aggressive value.

**Comment by alphan** [comment]
#13082
