### ISSUE TITLE
[hw] MEPC cannot be set

### ISSUE THREAD

**Issue by alistair23** [lowRISC/opentitan#1021]
The RISC-V spec states that `mepc` is a WARL (Write Any Values, Reads Legal Values). In the current release (snapshot-20191101-2) the `mepc` field cannot be written to.

## Steps to reproduce

Get the OpenTitan board running and clone the Git repo. Apply the following diff to the OT repo and rebuild the software:

```diff
diff --git a/sw/device/examples/hello_world/hello_world.c b/sw/device/examples/hello_world/hello_world.c
index bd9aecf..6746536 100644
--- a/sw/device/examples/hello_world/hello_world.c
+++ b/sw/device/examples/hello_world/hello_world.c
@@ -54,6 +54,11 @@ void trap_handler(uint32_t mepc, char c) {
 int main(int argc, char **argv) {
   uart_init(UART_BAUD_RATE);
 
+  asm ("ebreak");
+
+  asm ("lui  t0, 0x1000");
+  asm ("csrw 0x341, t0");
+
   pinmux_init();
   // Enable GPIO: 0-7 and 16 is input, 8-15 is output
   gpio_init(0xFF00);

```

Flash the demo application onto the board:

```bash
./sw/host/spiflash/spiflash --input=./build-fpga/sw/device/examples/hello_world/hello_world.bin
```

Then start `OpenOCD`

```bash
openocd -s util/openocd -f ./board/lowrisc-earlgrey-nexysvideo.c
```

In another terminal start GDB:

```bash
riscv32-oe-elf-gdb /home/alistair/opentitan-snapshot-20191101-2/sw/device/fpga/boot_rom/rom.elf
```

Connect to OpenOCD and restart the board:

```bash
target extended-remote :3333
monitor reset halt
```

Run until we hit the break point

```bash
c
```

You should now be stopped somewhere around here:

```
0x20000226 ? ebreak
```

with these instructions waiting to be executed

```
0x20000226 ? ebreak
0x20000228 ? lui	t0,0x1000
0x2000022c ? csrw	mepc,t0
0x20000230 ? lui	s0,0x10
0x20000232 ? jal	0x2000044a
0x20000234 ? addi	a0,s0,-256
0x20000238 ? jal	0x20000466
```

Print the `mepc` CSR

```
info registers mepc
```

You will see something like this

```
mepc           0x1a110360	437322592
```

Single step GDB past the following instruction

```
0x2000022c ? csrw	mepc,t0
```

Now print `mepc` again

```
info registers mepc
```

You should see that `mepc` is set to `0x01000000` as that was the value in `t0`. Instead it didn't change.

I have tried other values but nothing seems to change mepc.

**Comment by asb** [comment]
Hi @alistair23 - I just wanted to say a big thank you for providing such a clear and easily reproducible bug report - this is definitely one we can link back to as an exemplar! Either @vogelpi or @tomroberts-lowrisc should be able to investigate this today.

**Comment by alistair23** [comment]
No worries, I have worked with HW enough to create bug reports. Thanks for looking into it so quickly

**Comment by tomroberts-lowrisc** [comment]
Managed to reproduce with Verilator. The mepc update happens, but gets wiped by the many exceptions taken during the debugger execution.
This relates to lowrisc/ibex#168 and was fixed recently by @vogelpi. I applied that fix, reran and confirmed that the mepc shows the correct value.
I'll vendor in the latest version of Ibex then resolve.

**Comment by alistair23** [comment]
Is it possible to get a new bitstream after this is applied?

**Comment by asb** [comment]
@alistair23 even before it's merged, you can get the bitstream from CI run on #1025. See opentitan-dist on https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=5845&view=artifacts

**Comment by alistair23** [comment]
Ah, I didn't realise that. That is super useful. Thanks for pointing that out.

**Comment by alistair23** [comment]
I have tested https://github.com/lowRISC/opentitan/pull/1025 and can confirm that it fixes this bug.
