### ISSUE TITLE
[spi_device] Write Enable instruction not handled in hardware for flash emulation

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#10235]
SPI flash devices typically have an immediate response to Write Enable / Write Disable instructions. Currently, this command must be uploaded to firmware, so subsequent Read Status commands may not see the effects of Write Enable, due to the latency of firmware's response.

We're not aware of flows in the wild that check the Write Enable Latch (WEL) after a WREN instruction, so the impact of this OT-specific quirk may not be significant. However, it is a deviation from the flash parts we're trying to emulate. If time allows, recommend having this opcode detected in hardware and update WEL.

Note: The de facto standard for the write-enable latch (WEL) is bit 1 of the status register.

CC @eunchan @tjaychen @alphan

**Comment by a-will** [comment]
Note that the lower severity comes from an assumption that multiple commands can queue up in the FIFO. If this is not the case, it may become critical to handle these instructions in hardware, else there will be a race with firmware.

**Comment by tjaychen** [comment]
This will be handled as part of #12137 and #12145

**Comment by eunchan** [comment]
Closing now as features are baked in to SPI Device IP
