### ISSUE TITLE
[fpga] Default boot rom file

### ISSUE THREAD

**Issue by towoe** [lowRISC/opentitan#1024]
I am not sure what the correct path should be now with the changes in the sw build system, but the following path should be updated:
https://github.com/lowRISC/opentitan/blob/dff8e653726f200dfcc4f256ec4d1d6399bfdad9/hw/top_earlgrey/top_earlgrey_nexysvideo.core#L40

Maybe `../../../../../build-out/sw/fpga/sw/device/boot_rom/boot_rom.vmem`?
@imphil I guess there is no way to make use of `util/build_const.sh` in the core file?

**Comment by imphil** [comment]
> I guess there is no way to make use of util/build_const.sh in the core file?

Not really. It's also the wrong place to read such a file. If a higher-level build system wants to modify the path, it can call fusesoc with appropriate command line options or environment variables.

**Comment by towoe** [comment]
I think the build system already does that, I was just wondering if it is possible to use a centralized definition.
So the path has then to be update along changes in the build system.

**Comment by imphil** [comment]
@mcy can you update the path of the bootrom in the *.core files of top_earlgrey?

**Comment by mcy** [comment]
Is there a reason we have a default at all? The two comments above it make me doubt that having a default is a good idea.

**Comment by towoe** [comment]
That's actually a fair point @mcy. I think the default makes sense as the boot ROM does not really change between invocations (at least the file path) and would have to be specified at each call. This makes the invocation cumbersome. But I would be okay with removing it and maybe use (as in ibex) another short hand to execute the required command.

**Comment by towoe** [comment]
Maybe we correct the path for now to the one give by the default software build system as this currently breaks our instructions given in the documentation and leave the issue open for further discussions.

**Comment by mcy** [comment]
I'm hoping to get to a point where Meson simply calls fusesoc directly, so we can avoid this completely.

Is this currently broken when using Make? If not, I think we should leave it as-is and we can add it to #1032.

**Comment by towoe** [comment]
Yes, I think this is true for all, as the output is not in the same directory as the sources.

**Comment by imphil** [comment]
We now had at least three people stumble across this by following our guides. More permanent solutions can come later, it's important to get this fixed now to make the user guide correct again.

**Comment by mcy** [comment]
What's the guide people are following, anyway? Have Meson instructions already made their way into the UG?

**Comment by olofk** [comment]
Have you looked at my patch to build the boot ROM as part of the FuseSoC flow? https://github.com/lowRISC/opentitan/pull/1020 I believe that would solve this reliably too

**Comment by tjaychen** [comment]
sorry i'm a bit late to this issue, but what's the resolution exactly? 
The original hardcoding path isn't entirely right...and it does feel like the better solution is to pass it on the fly based on where ROM was actually compiled to.

**Comment by tjaychen** [comment]
o nvm, i see the related fix.
