### ISSUE TITLE
[dv/pwrmgr] Check pwrmgr handling of rom inputs

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#10241]
The transition to active state will be blocked depending on rom_ctrl_i and lc inputs. Consider adding a covergroup for this logic.
The logic is described at [ROM Integrity Checks](https://docs.opentitan.org/hw/ip/pwrmgr/doc/#fast-clock-domain-fsm).

**Comment by tjaychen** [comment]
yeah i think this one can be deferred. It isn't related to any of the reset domain change stuff.
Let's go ahead with it.
