### ISSUE TITLE
[dv/cip] Fix and document mubi randomization

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#10257]
The weights of true, false, and others should treat others as a group and be uniform.
The current scheme is flawed since it under-samples true and false.

**Comment by matutem** [comment]
Running 1000 randomizations with the current code and weights False=4, True=2, Others=2 gives the following per value frequency:
mubi 00000000 count 0.016638
mubi 00000001 count 0.016647
mubi 00000002 count 0.016696
mubi 00000003 count 0.016588
mubi 00000004 count 0.016559
mubi 00000005 count 0.499670
mubi 00000006 count 0.020759
mubi 00000007 count 0.021234
mubi 00000008 count 0.020884
mubi 00000009 count 0.020863
mubi 0000000a count 0.250557
mubi 0000000b count 0.016607
mubi 0000000c count 0.016592
mubi 0000000d count 0.016563
mubi 0000000e count 0.016489
mubi 0000000f count 0.016654

Notice the values between False and True get a higher frequency than those above True and below False. This is because there are 5 for each of the latter, and only 4 of the former.

**Comment by matutem** [comment]
Sri, I found xcelium was failing and perhaps this is why it was reopened? I have a fix for it.

**Comment by sriyerg** [comment]
Yes, thats right. IMO the distribution will need to be an autogenerated piece of code.

**Comment by msfschaffner** [comment]
@matutem @sriyerg has this been fixed in the meantime?

**Comment by matutem** [comment]
I am not aware of pending issues, and I just run an xcelium test that exercises the randomization code.

Closing this issue again, but reopen if I missed something.
