### ISSUE TITLE
[adc_ctrl] np_sample_cnt semantics differ from spec.

### ISSUE THREAD

**Issue by NigelScales** [lowRISC/opentitan#10252]
It appears that np_sample_cnt_q[15:0] is not being reset when the set of matching filters changes as required by the design spec.

> All pairs of filters that are enabled in adc_chn0_filter_ctl[7:0] and adc_chn1_filter_ctl[7:0] are evaluated after each pair of samples has been taken. The filter result is passed to the periodic scan counter if enabled and not at its limit otherwise the result is passed to the debounce counter. The list below describes how the counters interpret the filter results:
If no filters are hit then the counter will reset to zero.
**If one or more filters are hit but the set hit differs from the previous evaluation the counter resets to zero.**
If one or more filters are hit and either none was hit in the previous evaluation or the same set was hit in the previous evaluation and the counter is not at its limit then the counter will increment.

To reproduce:
gh pr checkout 10147
./util/dvsim/dvsim.py hw/ip/adc_ctrl/dv/adc_ctrl_sim_cfg.hjson -i adc_ctrl_filters_polled --fixed-seed 1 --tool xcelium --waves

![image](https://user-images.githubusercontent.com/78102677/150572591-449750f7-7bfd-4f4b-b42a-f88327406cfd.png)

**Comment by tjaychen** [comment]
@NigelScales just making sure, this is meant for `adc_ctrl` and not `lc_ctrl` right?

**Comment by NigelScales** [comment]
> @NigelScales just making sure, this is meant for `adc_ctrl` and not `lc_ctrl` right?

@tjaychen Yes title was a typo.

**Comment by tjaychen** [comment]
just a note that @NigelScales and I have been debugging this in the background. I believe #10603 should finally address these issues.

**Comment by NigelScales** [comment]
Looks good now.
