### ISSUE TITLE
[hw] Lower bits of MTVEC can't be set

### ISSUE THREAD

**Issue by alistair23** [lowRISC/opentitan#1029]
The lower 16 bits of the `mtvec` register can't be set, except for the lowest bit which is hard coded to 1.

## Steps to reproduce

Get the OpenTitan board running and clone the Git repo. Apply the following diff to the OT repo and rebuild the software:

```diff
diff --git a/sw/device/examples/hello_world/hello_world.c b/sw/device/examples/hello_world/hello_world.c
index bd9aecf..a7d2524 100644
--- a/sw/device/examples/hello_world/hello_world.c
+++ b/sw/device/examples/hello_world/hello_world.c
@@ -54,6 +54,12 @@ void trap_handler(uint32_t mepc, char c) {
 int main(int argc, char **argv) {
   uart_init(UART_BAUD_RATE);
 
+  asm ("ebreak");
+
+  asm ("lui t0,0x20000");
+  asm ("addi  t0,t0,64");
+  asm ("csrw mtvec, t0");
+
   pinmux_init();
   // Enable GPIO: 0-7 and 16 is input, 8-15 is output
   gpio_init(0xFF00);
```

Flash the demo application onto the board:

```shell
./sw/host/spiflash/spiflash --input=./build-fpga/sw/device/examples/hello_world/hello_world.bin
```

Then start `OpenOCD`

```shell
openocd -s util/openocd -f ./board/lowrisc-earlgrey-nexysvideo.c
```

In another terminal start GDB:

```shell
riscv32-oe-elf-gdb /home/alistair/opentitan-snapshot-20191101-2/sw/device/fpga/boot_rom/rom.elf
```

Connect to OpenOCD and restart the board:

```shell
target extended-remote :3333
monitor reset halt
```

Run until we hit the break point

```shell
c
```

You should now be stopped somewhere around here:

```
0x20000226 ? ebreak
```

with these instructions waiting to be executed

```
0x20000226 ? ebreak
0x20000228 ? lui	t0,0x20000
0x2000022c ? addi	t0,t0,64
0x20000230 ? csrw	mtvec,t0
0x20000234 ? lui	s0,0x10
0x20000236 ? jal	0x2000044e
0x20000238 ? addi	a0,s0,-256
```

Print the `mtvec` CSR

```
info registers mtvec
```

You will see something like this

```
mtvec          0x20000101	536871169
```

Single step GDB past the following instruction

```
0x20000230 ? csrw	mtvec,t0
```

Now print `mtvec` again

```
info registers mtvec
```

Instead of `mtvec` being set to `0x20000040` it is incorrectly set to `0x20000001`.

It looks like the lower two bytes (0xFF) cannot be changed, and the lowest bit is always set.

## Extra info

I also tried with this diff

```diff
diff --git a/sw/device/examples/hello_world/hello_world.c b/sw/device/examples/hello_world/hello_world.c
index bd9aecf..e5cacc4 100644
--- a/sw/device/examples/hello_world/hello_world.c
+++ b/sw/device/examples/hello_world/hello_world.c
@@ -54,6 +54,11 @@ void trap_handler(uint32_t mepc, char c) {
 int main(int argc, char **argv) {
   uart_init(UART_BAUD_RATE);
 
+  asm ("ebreak");
+
+  asm ("li t0,0xFFFF");
+  asm ("csrw mtvec, t0");
+
   pinmux_init();
   // Enable GPIO: 0-7 and 16 is input, 8-15 is output
   gpio_init(0xFF00);
```

which resulted in this value for `mtvec`

```
mtvec          0xff01	65281
```

which leads me to believe that the lower two bytes are not working while the other bytes all are.

NOTE: It appears that when setting the PC to the value in `mtvec` on an `ecall` the lower bit is zeroed out.

**Comment by asb** [comment]
Hi Alistair - this is documented behaviour of Ibex. See [the Ibex docs on mtvec](https://ibex-core.readthedocs.io/en/latest/cs_registers.html#machine-trap-vector-base-address-mtvec). Per the RISC-V privileged spec, it's legal for `mtvec` not to accept every value. In our case, we have a 256 byte alignment requirement.

**Comment by alistair23** [comment]
Ah, I didn't realise that their is a `MODE` section in mtvec. I'm not sure how I have never noticed that before.

Ah, I also didn't realise you can have a custom alignment. That is a bit of a hassle, but it seems correct. Thanks for correcting my mistake so quickly.
