### ISSUE TITLE
Reset in stress_all vseqs

### ISSUE THREAD

**Issue by senelson7** [lowRISC/opentitan#10296]
While reviewing my PR#10264, @rswarbrick suggested I never assert reset between vseqs. Since I inherited the stress_all vseq from other IP blocks, this might be a more global issue that pertains to all IP blocks, not just edn/entropy_src. Anyways, it seems to me that asserting reset between vseqs is really no different than running a vseq individually and doesn't buy us anything. Thoughts one way or the other?

**Comment by rswarbrick** [comment]
My take is that it's worth resetting in the middle of sequences, but we should have a sequence that resets in the *middle* of operations, when signals are most likely to be in their "non reset state". Since we need that test either way, I think that adding resets between operations in the stress sequence will just have the effect of making that sequence less likely to find errors.

**Comment by martin-lueker** [comment]
@rswarbrick: You have a point. This behavior would be a somewhat complicated change. However you could imagine updating the cip_base_virtual_sequencer to configurably & randomly reset in the middle and restart any vseq as part of all the tests.   That could be slick, but it would take a couple rounds of debugging, and I wouldn't want this feature enabled in the smoke tests.

**Comment by rswarbrick** [comment]
Yep, that's why I assumed every block would be adding an explicit "reset" test. See `otbn_reset`, for example.

**Comment by weicaiyang** [comment]
> Since we need that test either way, I think that adding resets between operations in the stress sequence will just have the effect of making that sequence less likely to find errors.

This is exactly the propose to let reset between vseq find most of the bugs and let reset in the middle of operations find less errors.
Most of block has the stress_all and stress_all_with_rand_reset tests. stress_all_with_rand_reset will test reset in the middle of operations

**Comment by rswarbrick** [comment]
Ah, I see. Right, makes sense I guess, and you can just run the stress_all test for twice as long to get the same (non-testbench) coverage as you'd get without the resets.
