### ISSUE TITLE
[ip/spi_device] data missing and mis-aligned when SPI fifo underflow/overflow

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#103]
When TX is underflow and keep sending last byte d9, I program 2 words cff4_6edd and bb53_5b79. From SPI TX interface, design didn't send 1st byte. It sends 79cf_f46e (first 3 bytes are from 1st word, last byte from 2nd word) and 1st byte (dd) of 1st word data is missing, then all data are mis-aligned.

Similar to TX, when RX is overflow and we release some space, the design may just drop some bytes of data and causes data-misaligned.
For example, assume sending 4433_2211 and ddcc_bbaa, one byte may be dropped due to overflow, then design writes aa44_3322 to memory. 

As discussed, one approach is to provide SCB for SW and SW never updates SRAM pointer when SCB is low and under/overflow is happening.

**Comment by sjgitty** [comment]
@eunchan @weicaiyang is this still open?

**Comment by weicaiyang** [comment]
Resolution is to provide CSB for SW and SW never updates SRAM pointer when CSB is low and under/overflow is happening.

Verified at #1221

**Comment by eunchan** [comment]
Closing the issue. Thanks for heads up
