### ISSUE TITLE
Build failed for master 

### ISSUE THREAD

**Issue by Avani8** [lowRISC/opentitan#1030]
![Screenshot from 2019-11-20 15-33-55](https://user-images.githubusercontent.com/12041484/69275845-32558500-0bab-11ea-8814-811470be5b15.png)

**Comment by imphil** [comment]
Thanks for reporting this bug @Avani8. This is a duplicate of #1024. Please ensure that you have set the right bootrom file by passing `--ROM_INIT_FILE path/to/rom.vmem` to fusesoc.

**Comment by towoe** [comment]
Just as an addition, be sure to follow the rule for the file path given in https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/top_earlgrey_nexysvideo.core#L31

**Comment by Avani8** [comment]
Thanks, @imphil for the quick response...that helped.

**Comment by towoe** [comment]
Fixed by #1034
