### ISSUE TITLE
[otp_ctrl] V2 UNR review TODOs

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#10313]
- [ ] Add assertions to ensure partition 0 (vendor test partition) even though found a ECC uncorrectable error, it still won't fire fatal alerts.

These TODOs are for post-v2 UNR rewiews:
The following UNRs that need review during V2S:

- [ ] partition_buf.....u_prim_count
- [ ] u_otp_ctrl_dai.u_prim_count
- [ ] u_otp_ctrl_kdi.u_prim_count_entropy
- [ ] u_otp_ctrl_kdi.u_prim_count_seed
- [ ] u_otp_ctrl_lci.u_prim_count
- [ ] u_otp_ctrl_scrmbl.u_prim_count

The following URNs that pending for reggen tool optimization:
- [ ] prim_tl_o

**Comment by msfschaffner** [comment]
Cindy, does this have to be updated? Also, at what stage should this issue be resolved? V2S or V3?

**Comment by cindychip** [comment]
Actually this issue is resolved! We updated the UNR in V2 to exclude all V2S items in this PR: https://github.com/lowRISC/opentitan/pull/10614
