### ISSUE TITLE
[doc] How to document TODOs deferred to a future IP revision

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10318]
There are certain TODOs that we decide to not fix anymore in a current IP revision.
The corresponding labels in the code are then typically changed to something like `ICEBOX` , with an attached issue link describing the future enhancement:
```
TODO(<issue nr>): fix this
```
->
```
ICEBOX(<issue nr>): <description >
```

I think we have not formally agreed to guidance around this matter, so the format above forms the proposal.
We can discuss this some more at one of the upcoming silicon meetings, if needed.

**Comment by rswarbrick** [comment]
Sounds like a reasonable plan to me.

**Comment by tjaychen** [comment]
fine with anything.

**Comment by msfschaffner** [comment]
We've discussed this in the silicon meeting and agreed that deferred TODOs should be renamed to ICEBOX. Also, an issue should be added to the ICEBOX comment as explained above. We added an extra ICEBOX issue type so that these issue can be filtered.
