### ISSUE TITLE
[build] Make deletion burndown.

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#1032]
Once I get #1026 reviewed and merged, I *believe* all dependencies on Software Make should be gone.

At this point, to fully get around to deleting Make from SW, we need to do the following:

- [x] Merge #1026 
- [x] Cut over all documentation to reference Meson, exclusively.
- [x] Make sure that [DV Make](https://github.com/lowRISC/opentitan/blob/master/hw/dv/tools/rules.mk) invokes Meson, rather than Make, to build SW targets.
- [x] Delete the Make build Azure job.
- [x] Delete all Make files under `sw/`.

If I've missed anything, please let me know on this issue so I don't break you.

**Comment by mcy** [comment]
@imphil @sriyerg @gkelly @moidx

**Comment by sriyerg** [comment]
@mcy, The DV flow does need to invoke the meson to generate the images for DV tests. This in done in hw/dv/tools/rules.mk. That needs to be added to your list here as well.

**Comment by imphil** [comment]
@mcy Can you ensure that you're keeping track of the items in https://github.com/lowRISC/opentitan/issues/8 here, and close the other issue (or this one)?

**Comment by mcy** [comment]
@imphil I don't believe any of those tasks are in addition to that one:
- The Docker container already pulls in the dependencies for the new build system.
- All of the other requirements are documentation tasks, or tasks I completed before filing this bug.

So I'm gonna go ahead and close it out.

**Comment by imphil** [comment]
This one can be closed now @mcy?

**Comment by mcy** [comment]
Yep. I thought it was marked as fixed by #1154.
