### ISSUE TITLE
OTP/flash registers’ structure change 

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#10324]
for better compatibility between open source and close source.

**Comment by msfschaffner** [comment]
Thanks for filing this one.
This is related to https://github.com/lowRISC/opentitan/issues/7688

**Comment by msfschaffner** [comment]
OTP structure change has been done here: https://github.com/lowRISC/opentitan/pull/12824
Flash is still outstanding.

**Comment by msfschaffner** [comment]
The flash controller has been updated to use alias registers as well now: https://github.com/lowRISC/opentitan/pull/13917
Also, the foundry chip-level simulation has been updated to use both OTP and Flash aliases.

Hence, we can close this issue.

**Comment by msfschaffner** [comment]
CC @arnonsha
