### ISSUE TITLE
[rom_ext] Possibly check ROM digest against a known value?

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#10323]
The `rom_ctrl` block computes a cSHAKE digest of the ROM contents when we come out of reset. This is used three ways:
- It is compared with an expected value (also burned into ROM) and `pwrmgr` might not boot if they don't match.
- It flows into [`CreatorRootKey`](https://docs.opentitan.org/doc/security/specs/identities_and_root_keys/#creator-root-key).
- It is exposed as the [DIGEST](https://docs.opentitan.org/hw/ip/rom_ctrl/doc/#Reg_digest_0) multi-reg.

Maybe ROM_EXT should contain its own copy of the expected value and check DIGEST again as part of *its* start-up sequence. This would help if an attacker somehow managed to get past the `pwrmgr` check (either by glitching there, or by managing to edit the expected checksum in the ROM) but still wanted to run our ROM_EXT and didn't care that `CreatorRootKey` doesn't have the expected value.

It's not completely clear whether this is worth it. After all, an attacker that has managed to take control of the ROM can presumably also edit the flash image for ROM_EXT! But the question came up in the D2S review meeting and it seemed worth discussing further.

@moidx: Perhaps you could shepherd this from here? I don't really feel I'm qualified :-)

**Comment by tjaychen** [comment]
this seems like a good idea to "look back" just in case to make sure we are where are intentionally.
@cdgori

**Comment by johannheyszl** [comment]
IMHO, if the attacker is successful to execute a modified ROM, such that the digest which is computed before actual execution by rom_ctrl is different, everything after this will be sufficiently compromised, and this additional check is more on the nice to have side but would introduce complexity . Suggest to skip this and resolve

**Comment by tjaychen** [comment]
I think this came up much later after the original discussion.
But @moidx is considering adding a kind of keymgr known answer test early in the flow.

This would effectively check that all the diversification constants, digests etc done early in flow are smoke checked before the device continues normal operation, and i think would cover the suggestion that @rswarbrick made here indirectly.

**Comment by johannheyszl** [comment]
Thanks @tjaychen. I believe the respective issue could be [#6546](https://github.com/lowRISC/opentitan/issues/6546)?
I agreea known answer test for keymgr would serve the same purpose. 
However, compromised SW could circumvent the check similarly.
Nonetheless the known answer seems very useful to me since it would not only protect against compromised SW but also against some physical attacks, with the SW uncompromised.

**Comment by alphan** [comment]
@tjaychen I think I need more context on this one. Would you mind pinging me when you have a free moment to chat about this offline?

**Comment by alphan** [comment]
Thanks for explaining the KAT idea @tjaychen. Adding the link to the [doc](https://docs.google.com/document/d/1J9gHd5Cb1xoauAp_JbyETdSF6EcECoFY7XtcLo_INQk/edit?resourcekey=0-pS5I-HJawffYP6A9SUr_dA) that I shared earlier in case we want to pursue it further.

**Comment by andreaskurth** [comment]
Came across this while triaging `pwrmgr`. @johannheyszl: Do you think this is relevant for M2.5?

**Comment by johannheyszl** [comment]
Thx. We had discussed this issue in the Security WG on 29th Sept and the summary was: "Planning to add this to the ROM_EXT to check integrity of the ROM and the internal state of the keymgr."

IMHO it is labeled correctly.

**Comment by moidx** [comment]
Resolving based on feedback from @johannheyszl. Penetration testing should surface any gaps here.
