### ISSUE TITLE
[hw] s0/fp/x8 register is cleared when single step debugging

### ISSUE THREAD

**Issue by alistair23** [lowRISC/opentitan#1035]
This is a strange one.

The `s0/fp/x8` register must be working for pretty much any function call to work, so it clearly mostly works. When single step debugging the instruction is zeroed out though.

## Steps to reproduce

Get the OpenTitan board running and clone the Git repo. Apply the following diff to the OT repo and rebuild the software:

```diff
diff --git a/sw/device/examples/hello_world/hello_world.c b/sw/device/examples/hello_world/hello_world.c
index bd9aecf..0e1a393 100644
--- a/sw/device/examples/hello_world/hello_world.c
+++ b/sw/device/examples/hello_world/hello_world.c
@@ -54,6 +54,13 @@ void trap_handler(uint32_t mepc, char c) {
 int main(int argc, char **argv) {
   uart_init(UART_BAUD_RATE);
 
+  asm ("ebreak");
+
+  asm ("li t0,0xFFFF");
+  asm ("add  s0, t0, zero");
+  asm ("nop");
+  asm ("nop");
+
   pinmux_init();
   // Enable GPIO: 0-7 and 16 is input, 8-15 is output
   gpio_init(0xFF00);
```

Flash the demo application onto the board:

```shell
./sw/host/spiflash/spiflash --input=./build-fpga/sw/device/examples/hello_world/hello_world.bin
```

Then start `OpenOCD`

```shell
openocd -s util/openocd -f ./board/lowrisc-earlgrey-nexysvideo.c
```

In another terminal start GDB:

```shell
riscv32-oe-elf-gdb /home/alistair/opentitan-snapshot-20191101-2/sw/device/fpga/boot_rom/rom.elf
```

Connect to OpenOCD and restart the board:

```shell
target extended-remote :3333
monitor reset halt
```

Run until we hit the break point

```shell
c
```

You should now be stopped somewhere around here:

```
0x20000226 ? ebreak
```

with these instructions waiting to be executed

```
0x20000226 ? ebreak
0x20000228 ? lui	t0,0x10
0x2000022c ? addi	t0,t0,-1
0x20000230 ? add	s0,t0,zero
0x20000234 ? nop
0x20000236 ? nop
0x20000238 ? lui	s0,0x10
```

NOTE: We are saving a value to `s0/fp/x8` but then assembly generate by the c compiler is also saving a value to `s0` after our two `nop`s.

Print the value of `x8` and `fp` (both the same register).

```
info register x8
info register fp
```

You will see something like this

```
x8             0x0                 0x0
```

Single step GDB past the next three instructions. This should result in `s0/fp/x8` being `0x0000ffff`.

You can check with the following commands:

```
info register x8
info register fp
```

Which should give you something like:

```
x8             0xffff              0xffff
```

The next instruction waiting to be executed is now our **first** `nop` :

```
0x20000234 ? nop
```

Now take one more step. This will execute a `nop` instruction.

Now check `s0/fp/x8`

```
info register x8
info register fp
```

Notice that it is now 0

```
x8             0x0                 0x0
```

Somehow the `nop` zeroed it out!

Take two more steps until after the execution of

```
0x20000238 ? lui	s0,0x10
```

Now `s0/fp/x8` is correctly set to `0x00010000`

Take one more step, following the following jump:

```
0x2000023a ? jal	0x20000452
```

and notice that `s0/fp/x8` is back to 0!

Somehow when single step executing instructions the `s0/fp/x8` register is zeroed out after the next instruction is executed.

**Comment by imphil** [comment]
@tomroberts-lowrisc can you have a look, given that you probably have the setup ready? Otherwise let me know.

**Comment by tomroberts-lowrisc** [comment]
Sure, I'll have a look.
The debug rom itself uses s0 for various things. It could be that a debug print shows the current working version of s0 used by the debug module rather than the stored version that gets restored before jumping back to application code.

**Comment by alistair23** [comment]
Thanks for looking into it. It seems like it isn't just cleared when printed to the debugger as the execution fails after seeing it cleared.

**Comment by tomroberts-lowrisc** [comment]
Tried to reproduce with verilator but I read the correct value for x8 all the way through. I'll see if I can reproduce with FPGA.

**Comment by tomroberts-lowrisc** [comment]
Just re-read your instructions again and noted that you pass the boot ROM elf to GDB. I was passing the hello_world elf. When I tried it with the boot ROM elf I also see the behaviour you describe.

I had a look at the debug output of openOCD and it is throwing a lot of errors back to GDB but I can't say for sure what exactly is going wrong. Given that it works ok with the correct elf passed, I think the hardware is probably doing the right thing and the error lies somewhere in GDB/OpenOCD.

Can you try using the hello_world elf instead? (the GDB output is more useful too!)

**Comment by tomroberts-lowrisc** [comment]
Did a bit more digging in a verilator run. OpenOCD loads some bogus values into the debug progbuf which results in a load executed to memory address 0x0, which results in a memory error exception. The exception handler / debug re-entry ends up overwriting the stored value of x8 with zero such that when we restore it and return to application code, we restore zero and the original value is lost.

I think in theory the debug module could recover from exception a bit more gracefully (without losing register values).

**Comment by alistair23** [comment]
> I had a look at the debug output of openOCD and it is throwing a lot of errors back to GDB but I can't say for sure what exactly is going wrong. Given that it works ok with the correct elf passed, I think the hardware is probably doing the right thing and the error lies somewhere in GDB/OpenOCD.

In this case the boot ROM is the correct elf. I start debugging with the boot ROM (hence using that as the ELF when starting GDB). When I get to the next executable I use `add-symbol-file` to load the next file.

I'm not at my desk today so I can't check if using the next elf fixes the issue, but it still seems like something that needs to be fixed (either in GDB/OpenOCD or HW).

**Comment by tomroberts-lowrisc** [comment]
Agreed, we'll keep this open and hopefully find a fix

**Comment by imphil** [comment]
@alistair23 this should now be fixed in master, please re-open if that's not the case. Thanks @tomroberts-lowrisc for working on this fix!
