### ISSUE TITLE
[aon_timer] Exceeding threshold with register write causes no effect

### ISSUE THREAD

**Issue by ctopal** [lowRISC/opentitan#10367]
If we are jumping above the threshold for both WDOG and WKUP timers, the expected behaviour is a level interrupt to be generator to the processor.

**For WDOG:**
When the first threshold is met or exceeded, a level wakeup signal (if enabled) is sent to the power manager. Simultaneously, a level IRQ signal is also generated to the processor.

**For WKUP:**
When it reaches / exceeds the wake threshold, a level wakeup signal is sent to the power manager and a level IRQ is sent to the processor

Stress test writes a random COUNT value and expects an immediate bark/bite or wkup request if we are setting the respective COUNT register above the threshold. Currently, it fails due to not getting any response from the module. Can we clarify if this is the wanted behaviour or not?

**Comment by GregAC** [comment]
Jumping the count above the threshold (or moving the threshold below the count) will trigger the interrupt on the next clock tick rather than immediately. See Interrupt Handling in the documentation: https://docs.opentitan.org/hw/ip/aon_timer/doc/index.html#interrupt-handling

**Comment by ctopal** [comment]
![Screenshot from 2022-01-27 07-46-32](https://user-images.githubusercontent.com/87007427/151314163-f3080462-6e11-46b6-b065-2a17aecf1db8.png)

Hi Greg, 

I have relaxed the check on the scoreboard to test if we get the interrupt after some clock cycles but couldn't see it. Looking at the RTL it looks like we only raise the flag when we hit `==` condition. I believe we are not hitting that condition if we are making the COUNT jump to a higher value so it wouldn't get set at the first place.

**Comment by GregAC** [comment]
Ah turns out I haven't merged the PR that fixes this yet! PR is here https://github.com/lowRISC/opentitan/pull/10221

You could try running the tests with those changes applied.

**Comment by ctopal** [comment]
Hi Greg, that PR fixes the problem. Thanks!
