### ISSUE TITLE
[AES] missing output

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#10387]
@vogelpi 
I am seeing some wierd behavior which happens quite seldom.
but every now and then when I reset the DUT and restart - the DUT seems to start correctly but then after a while goes to IDLE with no output having been produced.
which the ENV detects as an error and clears the registers and tries again. 
but it seems the AES is stuck in this mode where the output is never produced.
the light blue blocks on the address bus are status reads - you can see both status, and the actual idle_o going high after being busy for a while.
but the output_valid never goes high
![image](https://user-images.githubusercontent.com/53917183/151259007-a9357aed-ba1e-477f-b0e3-e80ef6765002.png)

unfortunately I have not found a failing seed on VCS 
so I suggest we spend a little time thursday figuring out what is happening.

**Comment by vogelpi** [comment]
Thanks @rasmus-madsen for reporting the issue. We've just discussed this. What happens is that after writing the last key register, the module is reseeding the internal PRNGs. It becomes busy and while being busy, updates to the key and IV registers are ignored. So the module never actually starts encryption as it just has a partial IV.

What should be done:
1. The environment should track when the last key register is updated and then poll the status register before providing further IV values.
2. The automatic reseeding upon key write can be disabled by changing the corresponding bit in the AUX_CTRL_SHADOWED register.

**Comment by vogelpi** [comment]
Hey @rasmus-madsen ,
Is this still an issue or did this get fixed by #10578 as well?

**Comment by rasmus-madsen** [comment]
it is fixed I will close this one - we currently only have bugs in the CSRs
