### ISSUE TITLE
[dv/pwrmgr] Disable coverage exclusions

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#10395]
Disable exclusions for CSR CONTROL.USB_CLK_EN_ACTIVE, RESET_EN in IP level.

**Comment by msfschaffner** [comment]
@matutem has this been addressed? Can it be closed?

**Comment by matutem** [comment]
Yes, this was fixed in #11444, 8 months ago. Thanks @msfschaffner. Closing it.
