### ISSUE TITLE
[pwrmgr] V2 Review Action Items

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#10393]
Original Google doc:
https://docs.google.com/document/d/1AtEiXPjxzaStOj6xR5gPsceaiL9op8dN481ukiE9XaY/edit?resourcekey=0-yQvzdv7n76tHx1Xn_riS9g#

### PWRMGR V2 Review
**Attendees: Matute, Cindy, Tim, Weicai, Sri**

#### Status for review

1. Main design updates
  a. Splitting `ip_clk_en` and `clk_status` into per clock signals for `io`, `main`, and `usb`.
  b. Add direct software reset from rstmgr.
  c. Handle main power glitch.
2. RTL issues pending
  a. https://github.com/lowRISC/opentitan/issues/7215 has had no further development, so we need to close on it.It’s for future enhancements, not needed for V2.
3. Main DV updates
  a. Added more SVAs
  b. Added more reset causes: escalation, main power glitch, software reset from rstmgr.
  c. Added test that sends wakeup and reset in close proximity while in low power.
  d. Check wakeup interrupts.
4. DV updates pending
  a. Add stress test
5. Testplan
6. [Exclusions](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/ip/pwrmgr/data/autogen/pwrmgr.hjson)
  a. CSR CTRL_CFG_REGWEN is SW ro
  b. CSR CONTROL.LOW_POWER_HINT excluded since it is controlled by CTRL_CFG_REGWEN, but is disabled only in low power, when SW cannot issue CSR accesses. Should we exclude it?
  c. CSR CONTROL.USB_CLK_EN_ACTIVE is for full chip only.
  d. CSR.WAKE_STATUS is not-predictable at full chip.
  e. CSR.RESET_EN excluded for full chip only, why?
  f. CSR.WAKE_INFO, exclusion is unclear, as it refers to regwen, which doesn’t exist, and WAKE_INFO_CAPTURE_DIS controls it and is SW rw.
  g. [V2 checklist](https://github.com/lowRISC/opentitan/blob/master/hw/ip/pwrmgr/doc/checklist.md#v2)

### Meeting notes

- [x] Add stress_all test: [Done] https://github.com/lowRISC/opentitan/pull/10357
- [x] “reset” testpoint:
- [x] Update to mention that we also do a SW reset. [Done] https://github.com/lowRISC/opentitan/pull/10304
- [x] Fix “waits for fast fsm to become active reading `ctrl_cfg_regwen` until it becomes 1” -> it only happens when entering low-power. [Done] We actually don’t use ctrl_cfg_regwen, https://github.com/lowRISC/opentitan/pull/10304
- [x] Exclusions:
- [x] Disable exclusions for CSR CONTROL.USB_CLK_EN_ACTIVE, RESET_EN in IP level: [Postponed to V3] Tracked on https://github.com/lowRISC/opentitan/issues/10395.
- [x] Checklist: Update “all interfaces exercises” item: [Done] https://github.com/lowRISC/opentitan/pull/10304
- [x] Missing toggle coverage:
- [x] lc_idle and flash_idle: [Done] https://github.com/lowRISC/opentitan/pull/10212
- [x] rom_ctrl_i.good/donep: [Done] https://github.com/lowRISC/opentitan/pull/10242
- [x] Functional coverage:
- [x] Turn off escalation ping test cov: [Done] https://github.com/lowRISC/opentitan/pull/10304
- [x] Cross reset and sleep both ON are not captured, check covergroups: [Done] https://github.com/lowRISC/opentitan/pull/10211
- [x] Tl_err and tl_int_err coverages are not 100%, should be covered by common seqs
- [x] Improve wakeup_sensor functional coverage: Done https://github.com/lowRISC/opentitan/pull/10211
- [x] Clean up doc: https://docs.opentitan.org/hw/ip/pwrmgr/doc/#life-cycle-and-debug

**Comment by matutem** [comment]
All items ready, one postponed to V2 and tracked in a separate issue.
