### ISSUE TITLE
[dv/ci] Run DV/Make in CI

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#1041]
Right now, as far as I can tell, *none* of DV's stuff runs as part of CI. In other words, since I don't touch any of that stuff, I can't tell stuff will break when I move stuff around.

Since I will almost certainly break something by mistake inevitably, I'd like DV's stuff build in CI. However, I don't really know what this entails, or what can even be built in CI at all; hopefully we can use this issue to figure that out.

**Comment by mcy** [comment]
@sriyerg I figure you can tell me something about this.

**Comment by imphil** [comment]
There are nightly DV runs (cronjobs) as sanity tests with reports sent to a mailing list. @weicaiyang is responsible for those.

The primary issue here is licensing and software usage. None of our simulators can run in cloud instances, and sharing of output data is typically not allowed.

Azure Pipelines gives us the option to run private builders as part of the CI setup that don't publicly show their output, but there are still many legal questions to be answered first.

So the current policy is: if you think you might break a DV flow, please ask a DV person to manually give a PR a try. Beyond that, go ahead and commit, and we will need to sort breakage out after the fact.

**Comment by mcy** [comment]
Yeah, I figured this would be an issue. I'm mostly interested in *build* rather than *execution* breakages, because I figure that:
- Whatever is necessary to *build* stuff *is* kosher for Azure.
- If not, we can mock out the proprietary bits to simply check that all their inputs are valid (like, at a bare bare bare minimum, all the files that get passed to them still exist).

If this is impossible, we should come up with some documented strategy for dealing with DV breakages (even if it really is just the current policy of "push first, ask questions later").

**Comment by imphil** [comment]
While a DV simulation has separate build and run stages, they are performed by the same tool and have the same licensing problems.

Mocking calls to simulators and doing basic sanity checking might be possible (that's how fusesoc does its CI), but I wouldn't expect a gain in quality that is in proportion to the effort to implement and especially maintain such a check.

**Comment by tjaychen** [comment]
sorry if i'm a bit late to this, but has there been any thought to have
lowrisc host specific licenses for DV sanity?

**Comment by asb** [comment]
lowRISC can run DV using the licenses it has, though sharing full tool output is typically not possible and the runs can't necessarily be as fully automatic as current per-PR CI. Probably easiest to discuss in a call at some point.

**Comment by tjaychen** [comment]
sounds good, i think this is something we'll discuss in person.

**Comment by sriyerg** [comment]
DV sims are now being run in CI, including the chip level tests which require sw tests to be cross-compiled. Closing this issue (please reopen if something more needs to be discussed).
