### ISSUE TITLE
[lc_ctrl] How to structure RndCnst multiplexors

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10445]
This has been spun out from #10360.

------------------------------------------------------------------------------

This still has a 1-bit signal to poke (`test_tokens_valid[i] == On`). What I was suggesting in the meeting was that we'd use the four bits of `test_tokens_valid[i]` to control the four 64-bit chunks of the signal. That way, a single-bit fault can't flip the token to zero.

_Originally posted by @rswarbrick in https://github.com/lowRISC/opentitan/pull/10360#discussion_r792470067_

**Comment by msfschaffner** [comment]
We could slice them, but I am not sure it's needed, and I wanted to avoid introducing another way of consuming the LC signals (after all, we ask that they be consumed with a "strict" comparison in each place where they are needed).
The single bit signal is only combinational at this point, which is difficult to attack with just a glitch.
@cdgori WDYT? Is it worth splitting this into 4 slices that are muxed independently?

Btwy, one thing we could do is make more copies of this valid signal and consume the entire 4bits of the copies to steer, e.g., 2 x 64bit or 4 x 32bit slices of the mux (instead of using the individual bits).

_Originally posted by @msfschaffner in https://github.com/lowRISC/opentitan/pull/10360#discussion_r793022820_

**Comment by tjaychen** [comment]
I think it's okay to leave this one as is.  If someone glitched the valid signal, as you say, they would need to get it to an exact value to have an effect.  If someone were to glitch the mux, they'd still have to attack a few hundred muxes to get the values right.

Even if they did ALL of that, they would still need to find a pre-image value that would then match the new token value.  This all seems very difficult and layered. 

let me know if i missed anything.

**Comment by rswarbrick** [comment]
The thing I'm worried about is that we've got a 1-bit signal that controls 128 1-bit muxes and one input to these muxes is the values that came from OTP. But that's going to be `'0` when things haven't been provisioned yet (if I understood Michael correctly). So the attack would be to flip that one bit somehow and then find a SHA-3 pre-image of a single known vector. I don't know how difficult that is, but it doesn't sound completely crazy to me.

**Comment by msfschaffner** [comment]
Note that the comparison of the token is done three times in different cycles. 
Since this is a combo signal, it would therefore have to be glitched in 3 different cycles AND you would have to make sure the glitch propagates to all 128 individual mux cells as @tjaychen pointed out.

However, @rswarbrick is right that the unprovisioned token value is all-zero, which may (?) be easier to find a collision for?

I guess this is a bit of a judgement call. One thing I could do relatively easily is to use two lc signal copies to steer two mux halves separately, for instance.

**Comment by msfschaffner** [comment]
Ok, in that case, let me add the steering. It should be a minor fix without DV impact.

**Comment by msfschaffner** [comment]
This issue has been addressed in #10496.

**Comment by cdgori** [comment]
> However, @rswarbrick is right that the unprovisioned token value is all-zero, which may (?) be easier to find a collision for?

To my knowledge, I don't think all-zero is easier to collide, though it's possible that more rainbow-table type of things might be available for all-zero output.

**Comment by msfschaffner** [comment]
Yes what you mentioned is what I was thinking about. 
It's probably good to avoid a token value with a `nicely` aligned value of some sort (all-zero in this case).

**Comment by tjaychen** [comment]
i can't completely remember now, but are we running sha3 or kmac when generating the tokens?
I thought it was the latter for some reason...which would mean there's another key to break.
I'm guessing this is only sha3?

**Comment by msfschaffner** [comment]
We're running cSHAKE128 with a custom function string ('lc_ctrl'). so it is a sha3 variant and does not do any additional authentication. were you referring to the authentication part above?

**Comment by tjaychen** [comment]
ah... okay. That's too bad, if we were running kmac I think the collision would be less of a concern since there is yet another constant to break. 

If it's actually just cshake it's probably better to not have 0's then.. since i assume the string will be clearly visible in open source.

**Comment by msfschaffner** [comment]
Yeah right. With the patch above, we're switching the all-zero constant to a `RndCnst` instead to mitigate that.

**Comment by cdgori** [comment]
Ah, the custom function string basically means no rainbow tables should be pre-generated.  But it's fine to use a `RndCnst` here to be very safe.
