### ISSUE TITLE
[usbdev] Wake from deep sleep gaps (for D2 waiver for M1)

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#10457]
- [x] Detect all three possible state transitions in the AON domain, and report back to usbdev, so it may begin in the correct state from Suspended. From highest to lowest priority, those three are (1) VBUS power interruption, (2) bus reset, (3) bus resume.
- [x] Add software-directed change of link state for wake from deep sleep to handle . From discussion on #7950

**Comment by tjaychen** [comment]
cc @tjaychen

**Comment by a-will** [comment]
Complete with #10527 and #10605
