### ISSUE TITLE
[csrng/security] Access to key and v register issue - security lab feedback

### ISSUE THREAD

**Issue by mwbranstad** [lowRISC/opentitan#10477]
An issue was brought in the CSRNG D2S review about how access should be allow for the key and v register fields in the internal state registers. More details to be supplied by @moidx.

@tjaychen 
@msfschaffner

**Comment by tjaychen** [comment]
o damn seriously? @moidx is this related to one of the FIPs test?
@mwbranstad was there any discussion on whether this read feature needs to be software and/or otp qualified?

**Comment by mwbranstad** [comment]
@tjaychen I honestly do not recall what the real issue is here - I just created the issue to track, hoping that @moidx would add in the specific details. Maybe we can drop this issue as it may not be a problem, but let's see what the response is.

**Comment by tjaychen** [comment]
sounds good.
if we do need access to these internal states, it would be good know if we need otp / software qualification like we do with the entropy_src internal state override.

**Comment by moidx** [comment]
We will need access to the internal state for compliance testing. This is something we can do now with the right OTP config settings. I am not sure if it will be required for KAT tests as well, but it seems that should work as well. 

We have a chip level test that exercises this interface:

https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/tests/csrng_smoketest.c?q=check_internal_state

**Comment by mwbranstad** [comment]
From a controls point of view, CSRNG internal state access is the same as ES register access to entropy right now. It seems that if the KAT is to verify the NIST vectors, it would need access to the internal state, which it does when controls are set properly. Is there still an issue here, or can this issue be closed?

**Comment by tjaychen** [comment]
it sounds like the original issue was more about whether storing the internal state without integrity is okay with labs. So probably no need to change anything until we hear back.

**Comment by mwbranstad** [comment]
ah yes, that now sounds familiar, makes sense.

**Comment by mwbranstad** [comment]
@moidx can you create an issue that replaces this issue with more specifics? Then I will close this one.

**Comment by moidx** [comment]
We'll use #10738 to track the internal integrity open brought up by @tjaychen.
