### ISSUE TITLE
[hmac] Indicate in the docs that the design is not a hardened implementation

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10470]
This came up in #10362. We should probably align the HMAC docs accordingly.

---------------------------------------------------------

Sorry for post-merge comment.  This is fine in general for me.  I think it feels a little weird to have HMAC considered a non-security IP, I get why it is marked so, but I'm not sure how we indicate to potential consumers very very strongly that it's not hardened and they should use KMAC instead if they need a hardened MAC/HMAC.

I looked at the HMAC documentation page and it doesn't say anything about this - should it?

_Originally posted by @cdgori in https://github.com/lowRISC/opentitan/issues/10362#issuecomment-1024757866_

**Comment by tjaychen** [comment]
yeah we can certainly add it. I can throw something in.
Its' certainly worth pointing out there are no sca / fi countermeasures.
