### ISSUE TITLE
[sw/dif] DIF milestone requirements / checklists are outdated

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#10504]
The [DIF milestones listed on the website](https://docs.opentitan.org/hw/) are outdated. While some DIFs are still missing implementations, most are complete, and being used by chip-level tests already. We probably should do one of the following:
1. update the milestones to reflect the actual state of of the DIFs, or
2. remove this tracking information from the website.

Given that the DIF milestones are still applicable (as [defined here](https://docs.opentitan.org/doc/project/checklist/#s1)), I think it makes more sense just to update them, since they may be useful to chip-level test developers to gauge whether or not they will need to do some DIF development as a part of implementing there tests. Thoughts?

**Comment by timothytrippel** [comment]
As we discussed during the SW WG, it is OK to keep the DIF milestones on the website, provided we do the following:
1. keep the various DIF milestones (S1, S2, S3) lean, specifically many of the milestone requirements are not necessary anymore and can be removed, including, but not limited to: 
    - DIF_TEST_SMOKE
    - DIF_HW_USAGE_REVIEWED
    - DIF_HW_PARAMS
    - DIF_CODE_STYLE
    - DIF_REVIEW_C_STABLE
    - DIF_TODO_COMPLETE
2. keep informal review process, meaning, updating the DIF milestones will remain the responsibility of updating these milestones will fall onto the DIF developers (SW and chip-level test developers), and will be done an a best-effort basis.

CC: @arunthomas, @msfschaffner, @alphan

Please let me know if I missed anything. I will soon capture the above into a task burndown list and start submitting PR(s) to address this issue.

**Comment by msfschaffner** [comment]
CC: @sriyerg @tjaychen

**Comment by sriyerg** [comment]
Possibly controversial opinion here ;)
I would get rid of unit testing requirements given the amount of work left for chip V2. I don't think there is a need to verify that the verification code works. Or, postpone to S3 if we must.

**Comment by timothytrippel** [comment]
I think we definitely move to S3 at the least.

**Comment by moidx** [comment]
These changes seem reasonable to me.

**Comment by arunthomas** [comment]
SGTM too

**Comment by msfschaffner** [comment]
That SGTM as well.

**Comment by alphan** [comment]
SGTM

**Comment by timothytrippel** [comment]
Tasks:

- [ ] Update DIF milestones, and milestone requirements as described above.
- [ ] Go through each IP, audit DIF library, and update DIF milestone label and checklist.
    - [ ] adc_ctrl
    - [ ] aes
    - [ ] alert_handler
    - [ ] aon_timer
    - [ ] ast
    - [ ] clkmgr
    - [ ] csrng
    - [ ] edn
    - [ ] entropy_src
    - [ ] flash_ctrl
    - [ ] gpio
    - [ ] hmac
    - [ ] i2c
    - [ ] keymgr
    - [ ] kmac
    - [ ] lc_ctrl
    - [ ] otbn
    - [ ] otp_ctrl
    - [ ] pattgen
    - [ ] pinmux
    - [ ] pwm
    - [ ] pwrmgr
    - [ ] rom_ctrl
    - [ ] rstmgr
    - [ ] rv_core_ibex
    - [ ] rv_dm
    - [ ] rv_plic
    - [ ] rv_timer
    - [ ] sensor_ctrl
    - [ ] spi_device
    - [ ] spi_host
    - [ ] sram_ctrl
    - [ ] sysrst_ctrl
    - [ ] uart
    - [ ] usbdev
