### ISSUE TITLE
[util] REPO_TOP definition by git

### ISSUE THREAD

**Issue by towoe** [lowRISC/opentitan#1051]
My use case here is a little bit special, so instead of a PR I wanted to get feedback first.
I use a git worktree of opentitan. And I build the software with meson inside of a container.
At this point git is no longer able to identify the mounted volume as a git directory, so the following is not working:
https://github.com/lowRISC/opentitan/blob/b192e6b08960b96a76a05e8ac404787f210c05a6/util/build_consts.sh#L22

Previously I used something like
```sh
readonly REPO_TOP="$( cd -P "$( dirname $0 )" && pwd )"
```
to get the required path.
@mcy Do you see any problem with this approach?

**Comment by mcy** [comment]
I originally had used something in terms of `$0` myself, but unfortunately that does not work: build_consts.sh is intended to be sourced in, so `$0` is actually the name of the calling script.

Are you executing ./meson_init.sh outside of the tree? That might be your issue. Unfortunately, just about every script in the repo is written on the assumption that it is called at or relative to $REPO_TOP. I'd really like to have some discipline about this, but that requires having a way to consistently compute $REPO_TOP...

If you want the Meson artifacts out of tree, you should be doing `export BUILD_ROOT=blah`, anyway.

**Comment by imphil** [comment]
Our scripts are bash-only anyways, so we can use something along those lines if we detect bash:

```sh
REPO_TOP="`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd `"
```

**Comment by towoe** [comment]
Git worktree is like a copy of the complete directory at a different location, so one can have another branch checkouted without the need to clone the repo.
So this is not really an execution outside of the tree.
Its just that with containers and references the original `.git` folder can not be found and now I can't rely on git to find the repo top.

**Comment by asb** [comment]
There's probably a more fundamental question here - do we expect our scripts and tooling to work seamlessly if people are operating on an extracted tarball rather than a copy of the git repo? I think as much as possible, yes.

It would also be nice if you didn't have to explicitly give `BUILD_ROOT` when doing out-of-tree builds.

**Comment by mcy** [comment]
I did not know about `$BASH_SOURCE`, that's awesome! I'll file a change to switch over to that.

@asb: I mean, that's a reasonable thing to want. However, this is not the only place that depends on git (I know that chip_info.h really really really really wants to look up the current git repo and dump the current commit hash). If we want to have this property, it needs to be written down as policy.

(In general, I feel like most of our scripts are really brittle, so making a point of writing down rules for them is probably a good idea...)

**Comment by towoe** [comment]
I was thinking about this as well Alex, and I agree that we should aim to support this as well, but then I was thinking `git` is a requirement. But I guess, having `git` and having a git clone is something different.

**Comment by towoe** [comment]
The only place I had an additional problem with git, was the chip info part, for my testing I just used "undefined". So we might not have so many place for now which rely on git.

**Comment by imphil** [comment]
> The only place I had an additional problem with git, was the chip info part, for my testing I just used "undefined".

Please file a bug for that. We should have a single script/file in the tree that gives the version when building; this version can come from git if we're operating out of a git tree, but we also must be able to set it manually to a release version.
