### ISSUE TITLE
[meson] Some build artifacts missing in meson builds

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1052]
That's how build-bin looks in [this](https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=5925&view=logs&j=924ff16e-cbb4-544c-ec55-782cc11682e2&t=5f421ada-e94c-5c26-2e38-f7572553c9a8) pipeline run:

```
|-- build-bin
|   |-- hw
|   |   `-- top_earlgrey
|   |       `-- Vtop_earlgrey_verilator
|       |   `-- sim-verilator
|       |       |-- boot_rom
|       |       |   |-- boot_rom.elf
|       |       |   `-- chip_info.h
|       |       |-- examples
|       |       |   |-- hello_usbdev
|       |       |   |   `-- hello_usbdev.elf
|       |       |   `-- hello_world
|       |       |       `-- hello_world.elf
|       |       |-- exts
|       |       |   `-- common
|       |       |       `-- libriscv_crt.a
|       |       |-- lib
|       |       |   |-- libflash_ctrl_ot.a
|       |       |   |-- libgpio_ot.a
|       |       |   |-- libhmac_ot.a
|       |       |   |-- libirq_ot.a
|       |       |   |-- liblog_ot.a
|       |       |   |-- libmem_ot.a
|       |       |   |-- libpinmux_ot.a
|       |       |   |-- librv_timer_ot.a
|       |       |   |-- libspid_ot.a
|       |       |   |-- libuart_ot.a
|       |       |   `-- libusb_ot.a
|       |       `-- tests
|       |           |-- flash_ctrl
|       |           |   `-- flash_test.elf
|       |           |-- hmac
|       |           |   `-- sha256_test.elf
|       |           `-- rv_timer
|       |               `-- rv_timer_test.elf
|       `-- host
|           |-- spiflash
|           |   `-- spiflash
|           `-- vendor
|               `-- libmpsse.a
```

The tree looks strange as vmem and bin files are missing, but some "useless" binaries are there (like libmpsse.a). The "too many files" is a cosmetic problem, the "vmem and bin files missing" is critical.

**Comment by imphil** [comment]
So the problem is actually a bit more than that.

- Since https://github.com/lowRISC/opentitan/pull/1031 vmem and bin files are not generated or copied into build-bin any more. CI didn't catch that since meson build outputs were not used.
- Since https://github.com/lowRISC/opentitan/pull/1026 meson build outputs are used. CI on master did catch that, but the PR CI didn't (since the branch was based on an old master).

This leads to all CI jobs failing at the moment.


@mcy if you can come up with a quick solution that's appreciated, otherwise I'll back out #1026 to unbreak CI.

**Comment by mcy** [comment]
I've filed #1055 to fix the issue with the missing bin and vmem files. The issue with the .a and .h files is entirely cosmetic, and does not affect the distribution (this is a big reason why I wanted an explicit whitelist of files to export in the distribution). Hopefully they will go away once the make_build_bin step is contained within Meson.
