### ISSUE TITLE
[hw/aes] Support IV save/restore flows

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#10532]
The software implementation of the crypto library that wraps the AES interface expects the IV register to be readable and updated after each block operation. This is to support AES context switching for long running operations at the API level, as well as to facilitate the implementation of additional decoy operations which may be needed to meet our hardening goals of the crypto library.

Currently the IV registers are not readable to software, so this issue is to request required changes to enable this use case.

**Comment by moidx** [comment]
CC: @vogelpi, @jadephilipoom

**Comment by vogelpi** [comment]
Thanks @moidx for creating the issue. Making the IV register readable can certainly be done but it might have security implications. I thus suggest to protect it with a `regren` bit. Does this sound reasonable to you?

**Comment by tjaychen** [comment]
@vogelpi would this regren imply that when it is set to '0', we will not be able to do IV save / restore as mentioned?

**Comment by vogelpi** [comment]
Yes. I just thought we could ask software to first set the read enable before reading the IV and then disable it again in order to continue encryption/decryption. Just to make a little bit harder to extract the IV at any given point because the IV should actually be treated as a secret as well. But it depends on the thread model whether we want to add the `regren`.

**Comment by tjaychen** [comment]
@cdgori 
that sounds okay to me. My understanding of IVs in general is that they are not secrets. 

Could we file an issue to enhance this later?

**Comment by rasmus-madsen** [comment]
@martin-lueker

**Comment by martin-lueker** [comment]
Hi Everyone, is the P1 priority accurate for this?

**Comment by moidx** [comment]
Hi @martin-lueker, yes, this is something we definitely need to support the crypto library use cases.

**Comment by martin-lueker** [comment]
Okay, thanks for confirming.

**Comment by vogelpi** [comment]
Closing as the corresponding PR #10996  has been merged.

**Comment by cdgori** [comment]
> @cdgori that sounds okay to me. My understanding of IVs in general is that they are not secrets.
> 
> Could we file an issue to enhance this later?

Sorry for late comment - this is my understanding as well.

It is also not surprising to me that we need to support these flows given the way data is processed in some of the AES modes.
