### ISSUE TITLE
AES Fails Decryption using Nist vector examples

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#10544]
This is a directed test that used to work in sha 02e982f3b357340ab49e2d8c2580c77253480b65
there has been quite a lot of changes since then, but none that should affect the test.

the first encryption goes well - but the decryption fails.
the output from the DUT does not match expected. (all seeds fail with same issue since the test pattern is static)

I have verified that the correct key and data is supplied in both cases and DUT is running - but the produced output is incorrect.

reproduce
/util/dvsim/dvsim.py hw/ip/aes/dv/aes_sim_cfg.hjson -i aes_nist_vectors -r 1 -t vcs --verbosity=m -s=1

the error message

> DEcrypted Result does not match NIST for vector[          0][          0], 
>  nist: 6bc1bee22e409f96e93d7e117393172a 
>  output: 2249a2638c6f1c755a84f9681a9f08c1

**Comment by vogelpi** [comment]
Thanks @rasmus-madsen for opening the issue. There have been several problems causing this test to fail. Two problems I've introduced recently. Sorry for that.

I've now filed a PR here to get this solved: https://github.com/lowRISC/opentitan/pull/10581
