### ISSUE TITLE
[otp_ctrl/flash] Determine how to proceed with wrapper signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10541]
As it stands now, the open-source review and sign-off processes for `otp_ctrl` and `flash_ctrl` do not take into account any closed-source wrapper aspects.

To that end, I believe we had started to follow the OpenTitan checklist for the closed-source wrappers some time ago, and they should be somewhere around D1-D2 now if I remember correctly.

As we're working towards our next milestone, we should probably discuss how to proceed further on this front.

**Comment by tjaychen** [comment]
I think we need to view this as a "per" technology / vendor milestone process.
So we can still proceed with Dx / Vx as we know it, but that should probably be defined to mean the open source implementation. 

To me it makes sense to probably have a separate set of tracking for whichever technology node we are targeting (so if we had multiple, we would also need to target multiple). 

This makes things a bit dicey because memory technically comes into the picture as well.

**Comment by ankasol** [comment]
My recommendation is to discuss this as a team and with Dom and see what we can do. But linking the open source with Nuvoton I don't believe is the right approach, as well linking Nuvoton code to D2x/Vx milestones. Soon we'll have a 2nd source so we need to come with a solution to differentiate between open source and close source and have "per technology / vendor milestone process.

**Comment by domrizz0** [comment]
let's chat about this next week? I see what @tjaychen is getting at and think that's the right approach. hopefully it survives contact with tactical concerns w/o too many bruises. ;-)

**Comment by tjaychen** [comment]
@msfschaffner 
@cdgori 
do you guys want to update this a bit based on your recent discussions?

**Comment by msfschaffner** [comment]
We've presented our D2S process to Nuvoton last week, and plan to discuss the logistics this week. Will update this once that part has become clear.

**Comment by msfschaffner** [comment]
Nuvoton is going to do their own version of a D2S review and present their findings to us so that we can sign off at D2S. As for the other D/V milestones, this is something we plan to discuss at our next f2f meeting with Nuvoton.

**Comment by msfschaffner** [comment]
@moidx @tjaychen I am moving this to M3, since this only affects foundry.

**Comment by tjaychen** [comment]
this has already been done for both flash and otp.
The flash one still has some items that need to be addressed, but the spirit of this issue has already been resolved.
I'm closing for now.
