### ISSUE TITLE
[flash_ctrl,pwrmgr] Flash low power entry problem?

### ISSUE THREAD

**Issue by davebwil** [lowRISC/opentitan#10589]
For the test "flash_ctrl_idle_low_power" 

desc: '''Verify flash_idle signaling to pwrmgr.
            - Initiate flash program or erase over the controller.
            - Program the pwrmgr to go into deep sleep.
            - Issue a WFI.
            - Ensure that the low power entry is gated until the flash operation completes.
            '''

I am attempting to set the low power entry mode while a flash_ctrl operation is in progress.
I have set up "enable low power" then I started a page erase and issue wait_for_interrupt before the erase operation has completed.

I have captured waves of some of the signals. I can see low_power_hint is set in pwrmgr, flash_idle is low while the
flash operation takes place. When core_sleeping  goes high the pwrmgr_fsm.state_q transitions through some states
immediately gating the flash_ctrl input clock, this then becomes ungated before the end of the flash transaction. When
flash_idle is high again no further gating takes place.

Not sure if this is a bug or if there is something specific in the setup I might have missed.
Should the flash clock be gated at all while flash_idle is low and should the gating be then enabled once flash_idle is high?

![flash_idle_low_power](https://user-images.githubusercontent.com/93609351/152410501-2478db8e-940f-472d-bba3-77b94a02518d.png)

Zoomed in on the state transitions.

![flash_idle_low_power_2](https://user-images.githubusercontent.com/93609351/152410552-670764aa-b857-4f63-9e35-00913cefb3c8.png)

**Comment by tjaychen** [comment]
ah yes this is intended.
What the `pwrmgr` does is when it receives the entry hint is it first gates all clocks.
That allows it to observe a "snapshop" of the device in that moment (and it can also be guaranteed if it decides to proceed to low power nothing will change).

So during that snapshot it looks at the flash idle.  If it is indeed idle (meaning it will be not become non-idle later), it is safe to enter. If it is not idle (like you have shown here), then the pwrmgr knows that someone attempted to enter low power while a non-volatile transaction is ongoing.  It should then "abort" the low power entry and resume the clocks.  

I think that's what you are seeing here, can you confirm? 

@matutem please let us know if this is different from your block level expectations.

**Comment by tjaychen** [comment]
@davebwil let me know if this is all clear.
We can close this issue if it makes sense.

**Comment by davebwil** [comment]
@tjaychen, many thanks, yes I think it is clear now. Closing.
