### ISSUE TITLE
[spi_device] Determine how internal/external boundary crossings should be handled for passthrough mode

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#10586]
From discussion at https://github.com/lowRISC/opentitan/pull/10245#discussion_r794751570

A host connected to the spi_device is able to make reads of any size in a single command--There are no limitations on the start and end addresses. However, a spi_device may have some portions of the address space mapped to the internal SRAM (mailbox, emulated flash) in addition to the pass-through to an external SPI flash. We should nail down what the IP must do when crossing the boundaries. A couple options have been identified:

1. (ideal, but a significant change) Handle crossings seamlessly. Track the current read address for the output (including the dummy cycles for latency of the specific command). Always issue read commands to the external SPI flash and internal SRAM, then select the correct source via a mux.
2. Only return data from the source identified by the initial address. Do not drop commands when crossing a boundary. For the external flash case, continue reading from the external flash. For the internal SRAM sources, either wrap the address around through the same area, or return some known garbage data when going past the end of the region.

(2) should be fine for the mailbox case, but it might have undesirable effects for emulated flash, which might contain code intended to be integrated into an initial firmware load.

**Comment by a-will** [comment]
CC @tjaychen @eunchan

**Comment by eunchan** [comment]
I think wrapping the address in the mailbox space is simple. Crossing the boundary is somewhat corner case I assume.

The current design is:

- mailbox_assumed signal is set when address hits the mailbox space. it stays high until reset (/CS release) comes.
- If the address crosses from normal buffer to mailbox, the HW assumes the request and returns Mailbox data.

So, when passthrough mode is selected, and the address starts from mailbox and crosses the boundary, the HW returns data from internal read buffer space (offset 0x000). It could cause problems.

I may revise the HW to wrap the address if the address ever falls into the mailbox space, so that the case above always returns mailbox address (or returns 0 is preferrable?)

Also, the consensus (assumption) should be noted in the tech spec, which mailbox usually is placed at the end of the memory space. The reason is, the flash mode assumes the host system reads sequentially. If mailbox address is placed in the middle of the usable flash space, the buffer management logic may be confused.

**Comment by a-will** [comment]
> I think wrapping the address in the mailbox space is simple. Crossing the boundary is somewhat corner case I assume.

Being a "corner case" does not mean it should be ignored, as it is not necessarily uncommon. There are various chips that perform a bulk load of initial firmware, and there is no guarantee that it doesn't happen in inconvenient bursts that would cause issues if spi_device can't seamlessly transition between data sources.

**Comment by a-will** [comment]
@eunchan After talking offline, I think I have a better understanding of the difficulties with the different modes. So the concern in this issue is mostly about passthrough mode and transitions between the mailbox and external flash.

For the flash mode use case, we're typically talking about a small firmware that is bulk loaded into memory. By the mode's design, anything that uses flash mode must simply load the firmware in one go. In that case, the mailbox would never be placed in the middle, and transitions between the mailbox and emulated flash do not need to be handled. And since passthrough is off in this mode, transitions between mailbox and external flash are impossible.

For passthrough mode, it's a different story. We could see larger burst reads, and we'd at least want to see the external SPI flash wherever it is supposed to appear in the address map. The mailbox contents are likely less important when boundary changes happen.

Would it be more feasible to only handle this for passthrough data? In other words, for any read command, send the command to the external flash even if the first address is in the mailbox, and if it continues past the mailbox's boundary, switch to the data from the external flash.

**Comment by eunchan** [comment]
https://docs.google.com/document/d/1ZMb_8UyO2zTnQkWtMseRoliybKeacXisbXOhRAyrPmE/edit?usp=sharing

I am putting the background and suggested design changes in the doc above.

The feedback I want to get is if we proceed this or not prior to the current M2 milestone.

CC: @tjaychen @a-will @cfrantz @alphan @domrizz0

**Comment by a-will** [comment]
> https://docs.google.com/document/d/1ZMb_8UyO2zTnQkWtMseRoliybKeacXisbXOhRAyrPmE/edit?usp=sharing
> 
> I am putting the background and suggested design changes in the doc above.
> 
> The feedback I want to get is if we proceed this or not prior to the current M2 milestone.
> 
> CC: @tjaychen @a-will @cfrantz @alphan @domrizz0

I think that this is a bug that should be fixed, but it isn't critical enough to block ES. If we have limited time and better things to do, we can defer this fix to after ES tape-out. But that's just my take :)

**Comment by eunchan** [comment]
This has been fixed (not thoroughly verified yet). Let me lower the priority and update when DV catches up.

**Comment by weicaiyang** [comment]
This has been verified and covered as follows for passthrough mode.

>             Cover command starting outside mailbox and crossing into mailbox space.
>             Cover command starting in mailbox comming outside mailbox space.
>             Cover command starting outside mailbox and crossing the entire mailbox space and coming
>             outside mailbox.
>             Cross above with filter on and off.

But I assume mailbox crossing doesn't happen in flash mode. DV doesn't test it either.
If this looks good, we could close this issue.
@a-will @eunchan

**Comment by eunchan** [comment]
Agree.
