### ISSUE TITLE
[sw] sha256_test and rv_timer_test failing at HEAD

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#1058]
I broke CI some time last night, and since then two SW tests have started failing. Two SystemVerilog changes went by since I broke CI, so I suspect one of them broke it.

@tjaychen Can you take a look (or delegate to another hadware person who knows what's up?).

**Comment by aytong** [comment]
@mcy, is your PR that broke CI #1026?  The RTL change since then is #1027 AES by @vogelpi.  @tjaychen is OoO this and next week.  @vogelpi, can you PTAL?  Thanks.

**Comment by mcy** [comment]
@aytong That's correct, I should have included that in the OP.

**Comment by vogelpi** [comment]
Is there really any problem in the RTL? As pointed out by @imphil [here](https://github.com/lowRISC/opentitan/issues/1052#issuecomment-557499176), the problematic PRs are #1031, and #1026. These changes broke CI, my AES PR did not touch anything related to the sha256_test and rv_timer_test. Moreover, CI ran successfully through for my PR when I created it but before I merged it.

**Comment by imphil** [comment]
There were a couple other things going on in that timeframe, including the use of meson-generated software binaries instead of make-generated ones. So the list of changes might be misleading, someone needs to run the test and see what's actually going on.

**Comment by vogelpi** [comment]
Alright, I am looking into it.

**Comment by mcy** [comment]
@vogelpi #1031 is not relevant, because our changes were passing at that point.

**Comment by vogelpi** [comment]
Alright, I was able to track down the problem with the timer, it is not in the hardware but in the software or more precisely the build system. Namely, when using meson, the handler for the timer interrupt `handler_irq_timer()` in `device/tests/rv_timer/rv_timer_test.c` is not properly linked. The handler is linked at `0x20000050` but the core expects the handler inside the boot ROM at `0x801C`. When handling the timer interrupt, the core jumps into the boot ROM and stays in a loop, i.e., it keeps jumping to the `default_irq_handler`.

I am not sure how this was handled before/with the Makefile approach. Either the boot ROM would let the core jump into a dummy timer interrupt handler inside the SRAM (to be overwritten by the actual application), or the linker would place the `handler_irq_timer` at a proper offset (`0x1C`) from a base address in the SRAM and the application would reconfigure then `mtvec` to point to this base address.

**Comment by vogelpi** [comment]
Also the failure of `sha256_test` is a software/build system issue: The static test data `test.digest` and `test.data` are placed at `0x10000000` in SRAM but this section is never initialized. Even if the this memory section would be initialized at simulation start, the core erases it in the boot ROM (as part of `zero_loop` starting at `0x831a`).

I am not sure but I think this section should be placed in FLASH as well instead of SRAM. PTAL @mcy.

**Comment by mcy** [comment]
I did a quick glance and my current working theory is some silliness with `__attribute__((weak))`... I'm going to take a closer look.

**Comment by tjaychen** [comment]
> Alright, I was able to track down the problem with the timer, it is not in the hardware but in the software or more precisely the build system. Namely, when using meson, the handler for the timer interrupt `handler_irq_timer()` in `device/tests/rv_timer/rv_timer_test.c` is not properly linked. The handler is linked at `0x20000050` but the core expects the handler inside the boot ROM at `0x801C`. When handling the timer interrupt, the core jumps into the boot ROM and stays in a loop, i.e., it keeps jumping to the `default_irq_handler`.
> 
> I am not sure how this was handled before/with the Makefile approach. Either the boot ROM would let the core jump into a dummy timer interrupt handler inside the SRAM (to be overwritten by the actual application), or the linker would place the `handler_irq_timer` at a proper offset (`0x1C`) from a base address in the SRAM and the application would reconfigure then `mtvec` to point to this base address.

i'm a bit late to the party, but i did experience this issue some time ago as well. See #726 
I made some hack fix at the time, but looks like this issue points to something else?
