### ISSUE TITLE
[usbdev,sw] Unused function warning in usbdev.c

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#10585]
With commit 0127dd14 (current HEAD), compiling the device software spits out the following warning:
```
$ ninja -C "$OBJ_DIR" sw/device/lib/e287d45@@usb_ot@sta/usbdev.c.o
ninja: Entering directory `/home/rjs/work/opentitan/build-out'
[1/1] Compiling C object 'sw/device/lib/e287d45@@usb_ot@sta/usbdev.c.o'
../sw/device/lib/usbdev.c:21:16: warning: 'endpoint_number' defined but not used [-Wunused-function]
   21 | static uint8_t endpoint_number(uint8_t endpoint) { return endpoint & 0x7F; }
      |                ^~~~~~~~~~~~~~~
../sw/device/lib/usbdev.c:19:13: warning: 'endpoint_is_in' defined but not used [-Wunused-function]
   19 | static bool endpoint_is_in(uint8_t endpoint) { return endpoint & 0x80; }
      |             ^~~~~~~~~~~~~~
```
The code was added in e18d88b: is it left over from a previous approach, maybe? (@a-will: I think this is yours?)

**Comment by a-will** [comment]
Yeah, I need to clean that stuff up... I left the FIXME in usbdev_halt() to handle the IN and OUT endpoints independently, and it looks like I didn't get around to finishing that API tweak.

What's unclear is whether much of the code in usbdev.c should be removed and replaced with the DIFs.
