### ISSUE TITLE
[ip/spi_device] doc update needed

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#106]
Please update doc of spi_device for below items

1. what frequencies are supported
2. define the timing width for gray period in [diagram](https://en.wikipedia.org/wiki/Serial_Peripheral_Interface#/media/File:SPI_timing_diagram2.svg)
 - when CPHA=0, from last clock change to the rising of SCB
 - when CPHA=1, from falling of SCB to first clock change
3. inaccurate statement "If RX SRAM FIFO level **exceeds** this value, it triggers interrupt", and it should be "exceeds or equals".
4. Need more description about the ABORT and ABORT_DONE
5. "It is recommended for the software to update the write pointer at the SRAM data width granularity if it has more than 1 DWord data to send out." Can we change to mandatory?
6. "Reset Async TX_FIFO. This only resets asynchronous fifo. **If firmware wants to reset SRAM FIFO, it should write 0 into read/write pointers**." the statement of reseting SRAM FIFO isn't correct.
7. For FIFO_LEVEL.txlvl and ASYNC_FIFO_LEVEL.txlvl, both field names are the same, but the actual functions are so different. Should we change the name?

add following at 1/15/20
- rst_txfifo and rst_rxfifo is RW. Currently, these require write 0 and write 1 to generate a pulse to reset the fifo. Seems better to change to WO and automatically change value back to 0 after write.

add following at 1/17/20
- the max speed of spi clock is 4 times of core clock frequency rather than 8 times we thought at the beginning, as the state machine (at txf_ctrl.st) needs 8 cycles to update 4 bytes data.

**Comment by sjgitty** [comment]
@eunchan is this still open?

**Comment by msfschaffner** [comment]
@eunchan may have addressed this by now. Can we close this issue?

**Comment by eunchan** [comment]
Yep
