### ISSUE TITLE
[otp] read otp when there is error

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#10611]
Continue the discussion here:
https://github.com/lowRISC/opentitan/pull/10590

Do we need to standardize OTP error output value? DV can handle current behavior, so it is not a need for DV.
But I thought would be good to summarize it here and let designer confirm if it is the desired behavior:

1). Partitions errors that moves the FSM to terminated states. Then read out OTP via CSR or TLUL interface, the readout value is 0.
2). Partition access error due to read lock. Then read out OTP via CSR or TLUL interface, the readout value is 0.
3). TLUL integrity error, for memory the readout value is 32'hFFFF_FFFF. For CSR, I am not sure, will run a sequence to check.

**Comment by msfschaffner** [comment]
@cindychip, just to clarify, when you say readout via CSR, you are referring to a normal register read that does not have a TL-UL error condition, right?

**Comment by cindychip** [comment]
Correct! Sorry about the confusion! Only item 3) are TLUL bus integrity error.

**Comment by msfschaffner** [comment]
Ok, but for 1) and 2) we have two access paths: 
a) indirect reads / writes through CSRs (DAI) and b) reads through TL-UL windows.

I think that we should not change the behavior of regular CSR reads (a), since the error condition itself does not pertain to the TL-UL protocol . i.e., the accesses complete normally and return valid data. if there is an access error during such indirect accesses, it should be reported via the error register in the controller and not via the TL-UL protocol.

However, for case b) where the reads are forwarded directly to the partitions without going via CSRs, we can align this behavio, because in those cases the reads technically go to locked memory segments. WDYT?

**Comment by cindychip** [comment]
Thanks Michael, what you mentioned totally makes sense, I agree on the CSR (DAI) access part.
For case b), if we align, I only have one concern - 
say if user is trying to access a read locked sw partition, then reading via CSR will return all zeros, but reading via TLUL will return all ones. Will that create any confusion for the user?

So I am okay with the current implementation without any change, but can be convinced :)

**Comment by msfschaffner** [comment]
Well, the TLUL transaction will return with an error.
So the user can't rely on the value being returned in that case.

For b), the current design should already return a TL-UL bus error if a read locked SW partition is accessed, right? 
Does the design currently return 0 or all ones in that case?

**Comment by cindychip** [comment]
Yes, for b). the TLUL bus will return an error if user is trying to read a locked SW partition.
And yes currently it will return 0.

Agree on the proposal to align the behavior on TLUL bus. One more thing to clarify - we are going to align on TLUL bus SW read to return all ones on any fatal error states (including: FSM state error, access error, and ECC uncorrectable error).

Thanks for your inputs and explanation!

**Comment by msfschaffner** [comment]
OK, sounds good thanks for bearing with me, @cindy

> Agree on the proposal to align the behavior on TLUL bus. One more thing to clarify - we are going to align on TLUL bus SW read to return all ones on any fatal error states (including: FSM state error, access error, and ECC uncorrectable error), because they are results in TLUL bus to return value with a d_error.

Yes, as far as I understand that was the proposal. 
However, I believe what @weicaiyang mentioned [here](https://github.com/lowRISC/opentitan/pull/10590#issuecomment-1029424251) is only true for errors internal to the `tlul_adapter_sram`. 
I.e. for all errors detected inside the adapter, we will return all-ones.
However, if an uncorrectable error by the memory via `rerror_i[1]` that is currently not yet the case.

Let me align this.

**Comment by weicaiyang** [comment]
> However, I believe what @weicaiyang mentioned https://github.com/lowRISC/opentitan/pull/10590#issuecomment-1029424251 is only true for errors internal to the tlul_adapter_sram.
I.e. for all errors detected inside the adapter, we will return all-ones.

Thanks @msfschaffner for correcting me. So far we haven't checked the d_data when there is an error in TLUL.
Looks like with the design update, we align all the error to return all 1s, except DataWhenInstrError which returns 0, right? Should we make DataWhenInstrError return all 1s as well?

**Comment by msfschaffner** [comment]
> Thanks @msfschaffner for correcting me. So far we haven't checked the d_data when there is an error in TLUL. Looks like with the design update, we align all the error to return all 1s, except DataWhenInstrError which returns 0, right? 

Indeed, that is correct. 

> Should we make DataWhenInstrError return all 1s as well?

`DataWhenInstrError` has intentionally been set to all zero since that produces an illegal instruction error in the RISC-V instruction decoder (@GregAC please correct me if I am wrong). So I suggest to leave the behavior of instruction fetch errors unchanged.

**Comment by weicaiyang** [comment]
> DataWhenInstrError has intentionally been set to all zero since that produces an illegal instruction error in the RISC-V instruction decoder in Ibex (@GregAC please correct me if I am wrong). So I suggest to leave the behavior of instruction fetch errors unchanged.

Sure, sounds good.
