### ISSUE TITLE
[sw] Structure of sw/device/lib

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#1063]
At this point sw/device/lib has taken on a kitchen-sink aspect to it, and I'm worried about the "dumping ground"-ness of it getting worse over time. For example, right now it contains (in a flat structure):
- A bunch of proto-DIFs for the current HW design.
- Not-quite-DIF-ey stuff, like `usbdev`.
- Some libc-replacement stuff.
- `common.h`, which itself is a kitchen sink.
- Logging stuff.

As we continue to evolve sw/device, I think we should be more judicious about where stuff lives. For example, @gkelly is proposing putting our shiny new DIFs in sw/device/lib/dif. I'd really like to get to a point where we can toss everything into subdirectories of sw/device/lib, rather than the top level, to avoid confusion.

Thoughts? Is most of the stuff in sw/device/lib going away? I'd at the very least like to move the libc-replacement stuff into sw/device/lib/libc or similar, since I expect our fake libc to only grow; I also think we should do something about `common.h` but that might be a separate issue.

**Comment by mcy** [comment]
On a related note re: our fake libc (which is absolutely *not* a libc and which I'm going to call libbase until we come up with a better name) implements libc symbols, so that `#include`ing standard headers "just works".

I think we should consider banning standard headers altogether, for two reasons:
- We do not plan to fully implement any standard header, just the stuff out of them we like.
- Simply `#include`ing a standard header automatically binds us to requirements of the C standard that we might want to otherwise violate (in other words, any function pulled in through a standard header is bound to behave "as if" it were a libc function, which I think we 100% want to avoid). This holds even if we don't link in a libc (the C standard doesn't know what "linking" is).

The above is the absolute most conservative read of the standard, so we can probably relax it a little... I'd still rather we wrote our own stddef.h, though. It's also not clear to me if it's kosher to use libc symbols like, at all? LLVM, at least, will 100% assume memcpy() is the libc version and perform all sorts of "as if" transformations to calls thereof.

**Comment by lenary** [comment]
It would be good to talk about this more. Can we add it to the software agenda?

**Comment by asb** [comment]
For header files: I agree that partially implementing a standard header seems like a bad idea.

Libc functions: If a function is implemented with libc semantics, I don't see a good reason not to use the standard libc symbol name (as is done with memcpy, memset, strlen, abort). If we deviate in some way then we absolutely should not use the same symbol name.

**Comment by silvestrst** [comment]
I imagine we probably would want to also implement elements from stdbool.h and stdint.h.

**Comment by mcy** [comment]
@silvestrst Check out #1073 for an idea of what that would look like. There's *so* many caveats though.

@asb I would lean towards using our own names, and providing e.g. `memcpy` as a linker alias. That way we can deviate from exact ISO standard semantics (I do not want us to be in the business of having to exactly implement ISO-specified functions).

**Comment by lenary** [comment]
More structure (and more clarity around the structure) is more better, definitely.

Revisiting this issue:
- We're slowly splitting out a `libbase` which contains our freestanding libc headers, and some other useful things we think will be used in lots of places
- It makes sense to have the DIFs in their own directory.
- We are slowly slimming down `common.h`

It makes sense to parcel some of this stuff up more, but I think it's good for that to happen gradually as we move more functionality into DIFs, and then we see what's left in the main sw/device directory.

**Comment by tjaychen** [comment]
can we close this issue now? I feel like this has already been resolved some time ago with the creating of testing subdir, dif, test_rom so on and so forth.

@timothytrippel 
@mcy
