### ISSUE TITLE
[rom] Enable watchdog timer during bootstrap

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#10631]
Watchdog timer will be disabled when the ROM enters bootstrap. It might be more desirable to keep it enabled but we then need to figure out when to pet the watchdog.

**Comment by moidx** [comment]
Discussed offline and recommended to leave the watchdog disabled during bootstrap. @cfrantz can you close this issue if you are ok with this approach? Thanks

**Comment by alphan** [comment]
#13082
