### ISSUE TITLE
[sysrst_ctrl] Clarification regarding debounce method used

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10663]
Before proceeding with any RTL fixes, I quickly want to clarify a few things related to debouncing.
@toshaq @a-pronin can you PTAL and confirm whether this is implemented as intended?

## Debounce scheme

`sysrst_ctrl` uses debouncer FSMs with a configurable debounce timer that runs on the AON clock (see Hjson description [here](https://docs.opentitan.org/hw/ip/sysrst_ctrl/doc/index.html#Reg_key_intr_debounce_ctl) for example). The FSM performs the debouncing as follows.

1. detect low-to-high / high-to-low transition, or a high / low level (depending on the configuration and signal that is being looked at)
2. back off for the amount of debounce cycles configured 
3. once the debounce timer has expired, the input is sampled again to check whether it is still at the right level (e.g. high if we were looking for a low-to-high transition)
4. if it is, the signal is considered debounced and the associated action will be triggered
5. if not, the FSM falls back to idle mode, where it looks for signal changes

This debounce method is used for all features that trigger some sort of action based on `sysrst_ctrl` input signals, namely:
- autoblock
- combo detection
- key interrupts
- ulp wakeup

## Combo Detection

The combination detection feature is the only one that uses a second timer in addition to the debounce timer above. In particular:
1. Once the signal has been deemed stable using the method described above, the FSM moves into a "detection" state where it counts the number of cycles the input signal (combination detected) remains stable.
2. If the signal remains stable for the configured amount of cycles, the combo is considered "detected" and the associated action will be triggered.
3. If at any point that signal is deasserted, the FSM falls back into the idle state where it looks for signal changes to debounce. 

## Key Interrupts
 
For the [key interrupts](https://docs.opentitan.org/hw/ip/sysrst_ctrl/doc/index.html#Reg_key_intr_ctl), the debouncer logic can simultaneously look for low-to-high and high-to-low edges.
Note that in hardware this is implemented with two separate debouncers that currently have no relation to each other (i.e., the logic does not check whether we first get a high-to-low transition and then a low-to-high transition).

**Comment by toshaq** [comment]
LGTM @msfschaffner

**Comment by msfschaffner** [comment]
Thanks for double checking!

FYI @tjaychen @weicaiyang @patel-madhuri
