### ISSUE TITLE
Determine the degree of official support for macOS as a build platform

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#10679]
#10164 adds support for Meson on macOS. This poses a potential testing concern unless we chose one of two paths:
* If it breaks you get to keep both pieces: we won't prioritize keeping this working but will review changes to unbreak it.
* We run this in CI to prevent breakage.

Seeing as we have long only supported Linux, this seems like a place where applying the [Beyoncé Rule](https://nilendu-misra.medium.com/beyonc%C3%A9-rule-a-b-c-test-and-other-software-at-scale-lessons-from-google-1e79fb920347#:~:text=The%20Beyonc%C3%A9%20rule%3A%20%E2%80%9CIf%20you,of%20code%20per%20unit%20time.) is prudent.

**Comment by mcy** [comment]
Drew, assigning you as you're the current build czar; feel free to do what you wish with this issue.

**Comment by drewmacrae** [comment]
We're going to discuss this during the SW/WG meeting.

**Comment by drewmacrae** [comment]
For now, no one's blocked and we don't claim macOS support. In the future we anticipate resolving this issue by either standing up some tests or clarifying our stance on macOS support.
