### ISSUE TITLE
spiflash for FT4232h of ZCU104

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#10739]
As I always encountered errors when loading firmeare like. 
"Error transferring frame: 0x00000000, try pressing the “USB RST” button before loading the bitstream.". with CW310 even though I did press the “USB RST” button before loading the bitstream.
and Nexys Video is too small and no longer supported by opentitan.

I would like to migrate to ZCU104. However, I noticed that ZCU104 is with FT4232h not FT2232h as nexys video.
What do I need to modify in order to make it work for UART to display information of hello world.
spiflash? or more firmware or even the RTL code.

Any suggestion is welcome.

**Comment by vogelpi** [comment]
I am closing this as we've stopped supporting the NexysVideo board and also the spiflash tool used on that board exclusively quite a while ago already. Also the mechanism used for loading the binaries on the CW boards has changed.
