### ISSUE TITLE
[flash_ctrl] ERASE SUSPEND REQ BIT IS NOT WORKING AS EXPECTED

### ISSUE THREAD

**Issue by nikola-miladinovic** [lowRISC/opentitan#10748]
it is noticed that when erase is not in progress and erase suspend req is set to 1, it remains on 1. Spec says following:
"0 | rw | 0x0 | REQ | When 1, request erase suspend. If no erase ongoing, the request is immediately cleared by hardware ... "
Branch for reproducing failure (any seed can be used):
https://github.com/nikola-miladinovic/opentitan/tree/flash_ctrl_erase_suspend

**Comment by tjaychen** [comment]
sounds good, let me have a look. 
This maybe an issue on the modeling side.

**Comment by nikola-miladinovic** [comment]
@tjaychen : I have just tested and it seems that it does not work also when erase is in progress.
