### ISSUE TITLE
[DIF] Implement prototype UART DIF

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#1076]
OpenTitan DIF specification [document](https://docs.google.com/document/d/1rMDHLQXSDH8CaUg0cID5ARGxdbflV61uk4crKWjhxs0/edit?pli=1#heading=h.jg2hzytlw6rq), although is not final, contains enough information to get started on the DIF implementation.

Providing that the specification doesn't change dramatically, the prototype potentially could turn into the production implementation with some amount of refactoring. Even if the document evolves too much, or changes completely, the main goals of this activity are:
- Potentially uncover useful things to complement the existing DIF specification
- Potentially uncover any shortcomings of the DIF specification
- Have code in place as basis for implementing the final specification

Breakdown:
- [x] Assess which parts of UART driver can be factored out into UART DIF with minimal effort, and which need to reside and refactored appropriately in a higher level driver
- [x] Implement DIF functions one at the time (init, write, read...), refactoring the consumers to utilise the new functionality to test out the implementation
- [x] Make appropriate changes to the build system and the directory layout
- [x] Develop a set of tests verify the API

**Comment by silvestrst** [comment]
I guess there is no reason not to use regtool.py for DIFs, however I think the format of the produced <device>_regs.h has to change because of the following:

["DIFs must not intrinsically know the location of the hardware blocks"](https://docs.google.com/document/d/1rMDHLQXSDH8CaUg0cID5ARGxdbflV61uk4crKWjhxs0/edit?pli=1#)
Generated register define headers currently expect "<DEVICEn>_BASE_ADDR" to be defined before <device>_regs.h inclusion, which if used in DIFs contradicts the above restriction.

**Comment by silvestrst** [comment]
I think it might be useful to calculate all absolute addresses (base_address + specific register offset) in uart_t (dif dependent) in uart_init function. This would expose the registers for use in DV and the higher level drivers, and also would allow to calculate register addresses once and use then in other DIF routines.

**Comment by lenary** [comment]
@silvestrst I propose closing this issue, now that the UART DIF has landed, and using #1386 to track further work on the UART DIF (which is no longer a prototype!)
