### ISSUE TITLE
out_2019-11-26/asm_tests/riscv_arithmetic_basic_test_0.S: not generating in the out directory.

### ISSUE THREAD

**Issue by madhava-sahu** [lowRISC/opentitan#1077]
Hi all,

Here I am getting an issue that the assembly files not getting generated in the out/... directory generated by the run.py.
 command: python3 run.py --test riscv_arithmetic_basic_test --simulator questa
![Lowrisc](https://user-images.githubusercontent.com/55076352/69638516-da25f380-1080-11ea-85ae-76bb6ab968ec.png)
please help me.

**Comment by udinator** [comment]
Hi @madhava-sahu - Can you check the generator compilation log? It should be located at out_2019-11-26/compile.log

**Comment by imphil** [comment]
Closing for getting no feedback in 3 months. Please re-open if the issue persists.

**Comment by imphil** [comment]
closing.
