### ISSUE TITLE
[tlul] socket_1n error responder incorrect integrity

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#10778]
the socket elements typically do not contain any integrity generation, this is because the end points are expected to generate them.
The only exception is the error responder, which acts on behalf of a non-existent end point.

When a transaction is directed towards the error responder, the received integrity is incorrect because the module just hardwires it to '0.

There is technically nothing wrong with this behavior, since either way it ends up as an error at the processor.  We'd need to check if the process actually differentiates between the integrity error and an address error. 

The DV environment however, is unhappy about this, because it checks integrity of every transaction.

We should just fix this to ensure the correct behavior (it will be a hard coded value anyways).

**Comment by tjaychen** [comment]
@weicaiyang FYI.
Maybe the bad address case is missed or just not checked for integrity during xbar tests?

**Comment by weicaiyang** [comment]
> @weicaiyang FYI. Maybe the bad address case is missed or just not checked for integrity during xbar tests?

We don't check integrity in xbar test since a/d_user are just passed through. We check a/d_user are passed through correctly

It's a good point. OOB in XBAR will also lead to an integrity error.
