### ISSUE TITLE
[adc_ctrl] Clarify semantics for filter_status and adc_intr_status register.

### ISSUE THREAD

**Issue by NigelScales** [lowRISC/opentitan#10779]
It seems bits in adc_intr_status are set when there is a rising edge of the corresponding bit of filter_status rather than a rising edge in the corresponding bit of the match vector directly.
So to clear an interrupt for a bit and have another subsequently detected the corresponding filter_status bit must be cleared too.

Is this the intended behaviour?

**Comment by tjaychen** [comment]
sorry i'm out for a couple of days, so i'll make sure to have a look when i'm back.
It does sound a little redundant based on your description here, so i'll take a look.
