### ISSUE TITLE
[sysrst_ctrl] Change request: add input path for flash_wp_l

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10773]
It has been determined that for added system security, the dedicated `flash_wp_l` output should have a read-back path so that firmware can determine whether the write protect signal has been overridden by an external driver.

The simplest way to implement this is to add an input path for `flash_wp_l` to `sysrst_ctrl` so that firmware can sample its value and configure edge detectors with interrupt request functionality.
The design change does touch the CSRs - but added complexity is minimal, since the functionality can be replicated (there are other inputs with exactly the same functionality).

In terms of added DV work, the impact should therefore also be small since the functionality is not new per se, and can be replicated.

I drafted the changes in [this PR](#10774).
This also includes updates to the documentation and DV environment.
In particular, the DV test `sysrst_ctrl_pin_access` has already been aligned.

The only DV test that still needs to be aligned is the key interrupt test, which is still under development for V2.

@tjaychen and @weicaiyang can you take a look in order to determine whether it is ok to move on with this test at this point? The IP is currently at D2S / V1 - hence the change request issue.

**Comment by tjaychen** [comment]
this looks very reasonable to me. Correct me if I am wrong, but essentially you've given the `flash_wp_l` pin a lot of the same interrupt / observability function that `ec_rst_l` already has right?

**Comment by msfschaffner** [comment]
indeed, yes. it has exactly the same input path as `ec_rst_l` (that signal also does not have an input inverter).

the only difference is that `ec_rst_l` has a bypass path with reset stretching functionality, whereas `flash_wp_l` does not have a bypass path.

**Comment by tjaychen** [comment]
that sounds good to me honestly. So whatever testing is to be applied to `ec_rst_l` for those functions, we apply it to `flash_wp_l` also.

**Comment by weicaiyang** [comment]
sounds reasonable to add this feature and not a big impact to DV.

**Comment by msfschaffner** [comment]
Great, thanks for the feedback!
In that case let's move forward with #10774.
