### ISSUE TITLE
[spi_device] BUSY to block passthrough interface

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#10785]
Discussed in #5134 

- Add BUSY_CTRL_EN CSR to CONTROL (or CFG?)
- BUSY_CTRL_EN and BUSY (in peripheral domain) to clear the `passthrough_en` when BUSY is set and CTRL_EN is set.

CC: @tjaychen @a-will @martin-lueker

**Comment by a-will** [comment]
`BUSY` changes in the peripheral domain leave open the potential for corruption. `passthrough_en` needs to change on command boundaries only, else partial commands could get through. There is nothing firmware can do to guarantee the timing.

**Comment by eunchan** [comment]
Adding the idea of splitting the BUSY process and Passthrough interface process here (initial discussion at #11418 )

The intention is for SW to not read check the BUSY (assuming SW can't control CSb assertion)

## BUSY cases

1. SW clears BUSY when CSb = 1. When next SPI transaction begins, HW updates the BUSY @ SCK (clearing the BUSY @ SCK)
2. SW clears BUSY when CSb = 0. Keep the event somewhere else (queue maybe) as the HW updates the BUSY @ SYS from BUSY @ SCK when SPI transaction is completed. Then the BUSY @ SYS should be updated from the pending event. The value will be updated to BUSY @ SCK when next transaction begins.

Then, the BUSY @ SYS can be used to block/unblock the passthrough.

Storing the SW update event requires additional logic in SPI IP. 1 depth Q, or event flag bit might be enough.

The PR #11418 did not revise the previous SPI_DEVICE HWIP behavior, which only accepts SW clearing of BUSY @ SCK when CSb = 1. It ignores the writing event if CSb = 0.

@a-will let me know if you think current version causes much trouble in SW. Then, I will revise the SPI_DEVICE HW to behave like above.

**Comment by a-will** [comment]
> @a-will let me know if you think current version causes much trouble in SW. Then, I will revise the SPI_DEVICE HW to behave like above.

I think we just got our wires crossed. We read the documentation a little differently, and then we started talking about two different subjects at the same time, haha.

**Comment by tjaychen** [comment]
@a-will @eunchan is it okay to close this issue now? I think this is implemented already isn't it?

**Comment by a-will** [comment]
Fixed by #11456 

What may remain is atomically updating all the status bits to a consistent state (one side or the other of a register write horizon).
