### ISSUE TITLE
[mask_rom/e2e_tests] Testing across LC states

### ISSUE THREAD

**Issue by milesdai** [lowRISC/opentitan#10791]
#10548 does not currently contain testing across lifecycle states. Tests should be added to exercise functionality that is present in some states but not in others.

**Comment by weicaiyang** [comment]
@timothytrippel can you add a priority tag for this?

**Comment by alphan** [comment]
Updated test points [here](https://github.com/lowRISC/opentitan/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3ARomE2eTest%22) cover multiple life cycle states.
