### ISSUE TITLE
[kmac] status is idle while in `KeyNotValid` error mode

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#10835]
Hi Eunchan,

I think we mentioned this in D2S review, but just file an issue for tracking.
When the APP interface has a request from keymgr, but keymgr's key is not valid, we will fire an `KeyNotValid` error.
However, during the entire time, the `sha3_fsm` is in `StIdle` state, which means if SW polls `status` register, it will return `Sha3Idle` even though internally it is processing keymgr app interface error data.

Maybe we can return `sha3_idle = 0` when sha3 has `KeyNotValid` until the `app_intf.st_d` goes to idle?

![image](https://user-images.githubusercontent.com/11466553/153976942-844b383d-9b14-4d2e-bed6-98998abb41d7.png)

Thanks,
Cindy

**Comment by eunchan** [comment]
I am not sure it is worth to revise `sha3_idle` in case of error. As error has been reported, SW error handling process may assume the Sha3 state stays in Idle but App FSM needs the attention.

**Comment by cindychip** [comment]
Okay that sounds good. Just want to raise this up to double check.
