### ISSUE TITLE
[rv_dm] Injecting accesses into unmapped regions of the debug memory space does not return an error response

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#10837]
The debug mem is the 'second' TL interface into `rv_dm` where the debug memory (rom) resides, which has a bunch of CSRs, program buffer and ROM. Its specification can be found here:
https://github.com/lowRISC/opentitan/blob/master/hw/vendor/pulp_riscv_dbg/doc/debug-system.md#debug-memory

The `dm_mem` implementation from PULP does not seem to implement a an error response for accesses made to unmapped regions of this address space. 

![image](https://user-images.githubusercontent.com/46467186/153997143-4bc0b67a-4aeb-4a6e-ac8a-7610ad0c09f5.png)

In the example above, an access is made to address 0x190 where nothing exists (based on the debug mem address map above). Our automated TL error test sequence expects an error response, but `dm_mem` doesn't. 

This behavior is probably fine, but 'fixing' the test is problematic. Seeking thoughts and opinions on how to fix this.

**Comment by msfschaffner** [comment]
Yeah, the bus errors are not well handled in that module.

If we need to fix this so that our test automation works, we can always make a patch in the lowRISC hosted fork of that repo.
The patch would then be applied as part of the vendor-in process.

Would that work?

**Comment by tjaychen** [comment]
if you are willing to accept the decreased dv coverage, i honestly don't think we need the dm stuff to perfectly respond based on memory attribute. 

@msfschaffner correct me if i'm wrong, but during production functional mode, the entire adapter_sram won't allow access to start with (or should not).  So really we're talking about whether this stuff will behave correctly during debug time only. If we are short on time, proving that the positive direction will work correctly (we can get into debug) is enough.  Whether we correctly generate errors from that window...can be a polishing item for later.

Of course, if we were to fix, I agree with @msfschaffner suggestion.

**Comment by msfschaffner** [comment]
Yes indeed, the DM should not be accessible in production mode, so I definitely see this as a polishing item for later (from the design side).

I guess the question is a bit how easy it would be to add an exception for this on the DVside?

**Comment by sriyerg** [comment]
The workaround in DV turned out to be trivial. Done in https://github.com/lowRISC/opentitan/pull/10858. 
I added special knobs in our DV CSR modeling classes to treat accesses to unmapped space as RAZ/WI instead of an error, which the scoreboard looks up to know whether to expect an error response or not.

**Comment by msfschaffner** [comment]
Cool, should we keep this bug open and relabel it as P3 / enhancement?

**Comment by sriyerg** [comment]
The debug mem does not have an output port to indicate an erroneous access, so this would end up being a bigger change. Re-labeled to P3 / future enhancement.

**Comment by msfschaffner** [comment]
This should be addressed by #15737, hence we can close this issue.
