### ISSUE TITLE
[regtool] change register definitions to satisfy DIF requirements

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#1083]
regtool.py generates register definitions with assumed knowledge of base_address, for example:
#define SPI_DEVICE_INTR_STATE(id) (SPI_DEVICE##id##_BASE_ADDR + 0x0)

This format is convenient in present setup, as there is no need to calculate all the peripheral registers absolute address. Instead it is enough to define base address  in the same header, together with device_regs.h file. Example from uart.h:
#define UART0_BASE_ADDR 0x40000000
#include "uart_regs.h"  // Generated.

However the [DIF](https://docs.google.com/document/d/1rMDHLQXSDH8CaUg0cID5ARGxdbflV61uk4crKWjhxs0/edit?pli=1#) specification mandates that "DIFs must not intrinsically know the location of the hardware blocks", as such the current register definitions format is unfortunately not acceptable (providing we want to use the generated register definitions in DIFs directly).

This issue is related to #1043 and #1076

**Comment by silvestrst** [comment]
I have some local changes, and will submit a pull request later today.

**Comment by lenary** [comment]
This was closed by #1118.
