### ISSUE TITLE
[adc_ctrl] Normal power debounce counter mismatch to spec.

### ISSUE THREAD

**Issue by NigelScales** [lowRISC/opentitan#10843]
To reproduce:
./util/dvsim/dvsim.py hw/ip/adc_ctrl/dv/adc_ctrl_sim_cfg.hjson -i adc_ctrl_filters_polled --fixed-seed 1 --tool xcelium --run-opts  "+pwrup_time_chk=0" --waves

From the spec (https://docs.opentitan.org/hw/ip/adc_ctrl/doc/index.html):

If the counter is the debounce counter and it reaches its limit then:
If an interrupt is not already being raised then the current sample values are latched into [adc_chn_val[0].adc_chn_value_intr](https://docs.opentitan.org/hw/ip/adc_ctrl/doc/index.html#Reg_adc_chn_val%5b0%5d) and [adc_chn_val[1].adc_chn_value_intr](https://docs.opentitan.org/hw/ip/adc_ctrl/doc/index.html#Reg_adc_chn_val%5b1%5d). i.e. these registers only record the value of the first debounced hit.
The [adc_intr_status](https://docs.opentitan.org/hw/ip/adc_ctrl/doc/index.html#Reg_adc_intr_status) register is updated by setting the bits corresponding to filters that are hit (note that bits that are already set will not be cleared). This will cause the block to raise an interrupt if it was not already doing so.
If any filters are hit that are enabled in [adc_wakeup_ctl](https://docs.opentitan.org/hw/ip/adc_ctrl/doc/index.html#Reg_adc_wakeup_ctl) the corresponding bits in the [adc_wakeup_status](https://docs.opentitan.org/hw/ip/adc_ctrl/doc/index.html#Reg_adc_wakeup_status) register are set which may initiate a wakeup.
**Note that the debounce counter will remain at its limit until the set of filters that are set changes when it will be reset to zero and start to debounce the next event.**

This is not the observed behaviour.
The counter does not stop at terminal count and instead repeats multiple times.

![image](https://user-images.githubusercontent.com/78102677/154047980-809f9f9d-ae66-4b44-a54c-b4a0c254d28d.png)

**Comment by tjaychen** [comment]
let me study this a bit. It is unclear to me why the counter needs to freeze in place, because i think all the status / wakeup etc are all automatically latched upon match.  So it should not really matter.  There might be more to this though, I will have a look.

**Comment by tjaychen** [comment]
yeah i have a fix for this, but am unable to test it right now due to environment issues with all adc_ctrl tests (for some reason).
