### ISSUE TITLE
[flash_ctrl] Wrong page size in flash_ctrl C test 

### ISSUE THREAD

**Issue by eshapira** [lowRISC/opentitan#10848]
The chip's test **chip_sw_flash_access** is running the method **test_basic_io** in the file **sw/device/tests/flash_ctrl_test.c** https://github.com/lowRISC/opentitan/blob/b1e181b4ff83e60f4ee3a567bf358721d5336ad8/sw/device/tests/flash_ctrl_test.c#L37
In this test, the **input page** and **output page** variables declared as arrays that should be in the size of 1 full page of the flash. 
The flash pages actual size is **256 64bits** words, however this arrays defined as arrays of **32bits** integers which means their size should be **512**, while in fact is defined as **FLASH_WORDS_PER_PAGE** which is **256**.
This in turn causes the flash to only do the programs and reads in this test on the 1st half of the pages.

The definition of the array as arrays in the size of **FLASH_WORDS_PER_PAGE** of 32bits integers:
https://github.com/lowRISC/opentitan/blob/b1e181b4ff83e60f4ee3a567bf358721d5336ad8/sw/device/tests/flash_ctrl_test.c#L81-L82

The definition of the **FLASH_WORDS_PER_PAGE** parameter in the test:
https://github.com/lowRISC/opentitan/blob/b1e181b4ff83e60f4ee3a567bf358721d5336ad8/sw/device/tests/flash_ctrl_test.c#L27

The definition of the **flash_get_words_per_page** method in the file **sw/device/lib/flash_ctrl.c**
https://github.com/lowRISC/opentitan/blob/b1e181b4ff83e60f4ee3a567bf358721d5336ad8/sw/device/lib/flash_ctrl.c#L270-L272

The definition of the **FLASH_CTRL_PARAM_WORDS_PER_PAGE** parameter to be 256 in the **flash_ctrl_regs.h**
(I'm not sure where this file is actually defined in the environment)
![image](https://user-images.githubusercontent.com/78012616/154062768-51044810-85f0-43e1-bd0e-4f3fd24b82e8.png)

**Comment by moidx** [comment]
Taking a look at this now.
