### ISSUE TITLE
[sw/dif] Flash_ctrl DIF, change word count check for erase operations

### ISSUE THREAD

**Issue by davebwil** [lowRISC/opentitan#10847]
When doing an erase operation the transaction is setup to use a word_count of 0 as the erase does not read/write data to/from the FIFOs. The current code checks that word_count is not zero in "dif_flash_ctrl_start" and fails with kDifBadArg if that is the case.
Setting the word_count for the erase operation to >0 does not provide a solution as the subsequent call to "dif_flash_ctrl_end" never sees the count decrease to zero and will never end.

I propose a possible solution in "dif_flash_ctrl_start":

dif_flash_ctrl.c line 389

```
  const uint32_t max_word_count = FLASH_CTRL_CONTROL_NUM_MASK;
  if ((transaction.op != kDifFlashCtrlOpPageErase) &&
      (transaction.op != kDifFlashCtrlOpBankErase)) {
    if (transaction.word_count - 1 > max_word_count ||
        transaction.word_count == 0)
      return kDifBadArg;
  }
```

this checks if the operation is an erase and if so skips the word_count checks.

Does this seem like a good solution?

**Comment by a-will** [comment]
Yes, that behavior totally makes sense, and the solution you proposed is perfect. Thanks for finding the bug.

It looks like we don't describe how to do erase operations in the doc, so we might want to add that too

**Comment by a-will** [comment]
Actually, small tweak: We'd probably want to force word_count to be zero when the operation is an erase, so the check would have an "else" clause.
