### ISSUE TITLE
[top] Extending the open source SW mode tests in the close source 

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#10852]
Even though we already have an initial solution, I am opening this issue for visibility and tracking, 
The purpose is to run open source tests on the close source database with additional configurations and checks (without duplicating the open source tests).
This will require adding some hooks to the open source code that will be extended in the close source tests.

**Comment by timothytrippel** [comment]
Adding a task list to track what needs to be done / is already done:

_Addressed in #11188:_
- [ ] add weak hooks to OTTF
- [ ] add meson build configurations

_Addressed in TBD_
- [ ] add bazel build configurations
