### ISSUE TITLE
[flash_ctrl] RMA Cycle Time Taking Too Long To Simulate Using VCS

### ISSUE THREAD

**Issue by TimEwins** [lowRISC/opentitan#10857]
Just before raising the PR https://github.com/lowRISC/opentitan/pull/10854 I ran the RMA test through VCS.

The actual time (real time) spent in the RMA cycle (as in Request to Acknowledge) is enormous, for some reason.

Each test run does 4 RMA cycles (seperated by Resets)

Using Xcellium this takes approx 30mins
Using VCS this takes in excess 0f 15 Hours !

The test issues an RMA Request, and then sits polling the RMA Acknowledge (with a timeout).

During the RMA every Flash location is bulk erased, then written, then verified.

Obviously with such internal DUT activity, there are a lot of signals to trace.  I have tried both with the gui, and batch, and they are both just as long to complete (real time)

I have viewed the gui, to prove to myself that the RTL was advancing, and not stuck in a loop.

Perhaps VCS is logging too much data ?

Also, note that with so many cycles within the RMA cycle, the delay between Req and Ack can vary a lot, when clock frequency changes are taken into account (observed)

Has anyone seen this sort of slow down before?

**Comment by weicaiyang** [comment]
@TimEwins you can try to run VCS profiling which will tell which part takes most of the time. 
> dvsim.py *sim_cfg* -i the_test -t vcs -r 1 --profile time

perhaps reduce some iterations, otherwise, it may take too long.

**Comment by TimEwins** [comment]
@weicaiyang Thanks ... I'll try that (profiling), but I haven't seen the test end in VCS yet .. we only have one VCS license .. our main simulator is Xcelium....... I have reduced the polling interval to save cycle time, but I think there is more to look at.

The polling loop is ...

    done = 0;
    rma_ack_seen = 0;
    fork
      begin
        fork
          begin  // Poll RMA ACK
            do begin
              `uvm_info(`gfn, "Polling RMA ACK ...", UVM_LOW)
              #10ms;  // Jump Ahead (Not Sampling Clocks)
              @(posedge cfg.clk_rst_vif.clk);  // Align to Clock
              if (cfg.flash_ctrl_vif.rma_ack == lc_ctrl_pkg::On) done = 1;
            end while (done == 0);
          end
          begin  // Timeout - Unexpected
            `uvm_info(`gfn, "Starting RMA Timeout Check ...", UVM_LOW)
            #(timeout_ns);
            `uvm_error(`gfn, {
                       "RMA ACK NOT seen within the expected time frame, Timeout - FAIL",
                       $sformatf("FAIL (%0t)", timeout_ns)
                       })
          end
        join_any
        disable fork;
      end
    join

**Comment by weicaiyang** [comment]
>        #10ms;  // Jump Ahead (Not Sampling Clocks)

oh, looks like it takes really long sim time for each RMA. perhaps we can consider to force the internal timer to shorten the sim time, or configure to small value if it's configurable.

**Comment by tjaychen** [comment]
yeah this is feature that wipes all of flash, and that is the intent of the test, skipping anything is probably a bad idea.

**Comment by TimEwins** [comment]
I locally reduced the iteration count to 1, and ran one test with a seed of 1 using both simulators (obviously the seed does not reproduce the same reuslts across simulators)

Both simulations ran to the end, and for VCS I had profiling ON.

VCS - 4.5 Hours (Profiling On)
Xcelium - 12 Mins

Here are snippets from each sim transcript ...

VCS - 4.5 Hours

UVM_INFO @ 5734714343   ps: RMA REQUEST
UVM_INFO @ 5734714343   ps: RMA Seed : 0x26466af5
UVM_INFO @ 5734737070   ps: Waiting for RMA to complete ... 
UVM_INFO @ 5734737070   ps: Polling RMA ACK ...
UVM_INFO @ 5734737070   ps: Starting RMA Timeout Check ...
UVM_INFO @ 15734753432  ps: Polling RMA ACK ...
UVM_INFO @ 25734769794  ps: Polling RMA ACK ...
UVM_INFO @ 35734786156  ps: Polling RMA ACK ...
UVM_INFO @ 45734802518  ps: Polling RMA ACK ...
UVM_INFO @ 55734818880  ps: Polling RMA ACK ...
UVM_INFO @ 65734835242  ps: Polling RMA ACK ...
UVM_INFO @ 75734851604  ps: Polling RMA ACK ...
UVM_INFO @ 85734867966  ps: Polling RMA ACK ...
UVM_INFO @ 95734884328  ps: Polling RMA ACK ...
UVM_INFO @ 105734900690 ps: Polling RMA ACK ...
UVM_INFO @ 115734917052 ps: Polling RMA ACK ...
UVM_INFO @ 125734933414 ps: Polling RMA ACK ...
UVM_INFO @ 135734949776 ps: Polling RMA ACK ...
UVM_INFO @ 145734966138 ps: Polling RMA ACK ...
UVM_INFO @ 155734982500 ps: Polling RMA ACK ...
UVM_INFO @ 165734998862 ps: Polling RMA ACK ...
UVM_INFO @ 175735015224 ps: Polling RMA ACK ...
UVM_INFO @ 185735031586 ps: Polling RMA ACK ...
UVM_INFO @ 195735047948 ps: Polling RMA ACK ...
UVM_INFO @ 205735064310 ps: Polling RMA ACK ...
UVM_INFO @ 215735080672 ps: Polling RMA ACK ...
UVM_INFO @ 225735097034 ps: Polling RMA ACK ...
UVM_INFO @ 235735113396 ps: Polling RMA ACK ...
UVM_INFO @ 245735129758 ps: RMA complete
UVM_INFO @ 245735129758 ps: RMA Duration : 240000393000 ps

XCELIUM - 12 Mins

UVM_INFO @ 2415545691   ps: RMA REQUEST
UVM_INFO @ 2415545691   ps: RMA Seed : 0xfccef0a2
UVM_INFO @ 2415555895   ps: Waiting for RMA to complete ... 
UVM_INFO @ 2415555895   ps: Polling RMA ACK ...
UVM_INFO @ 2415555895   ps: Starting RMA Timeout Check ...
UVM_INFO @ 12415557527  ps: Polling RMA ACK ...
UVM_INFO @ 22415559159  ps: Polling RMA ACK ...
UVM_INFO @ 32415560791  ps: Polling RMA ACK ...
UVM_INFO @ 42415562423  ps: Polling RMA ACK ...
UVM_INFO @ 52415564055  ps: Polling RMA ACK ...
UVM_INFO @ 62415565687  ps: Polling RMA ACK ...
UVM_INFO @ 72415567319  ps: Polling RMA ACK ...
UVM_INFO @ 82415568951  ps: Polling RMA ACK ...
UVM_INFO @ 92415570583  ps: Polling RMA ACK ...
UVM_INFO @ 102415572215 ps: Polling RMA ACK ...
UVM_INFO @ 112415573847 ps: RMA complete
UVM_INFO @ 112415573847 ps: RMA Duration : 110000018000 ps

I have had a quick look at the VCS profiling, and I cannot see anything of interest.  If anyone would like it posted on this thread, please let me know.

**Comment by weicaiyang** [comment]
@TimEwins 
Can you attach the the profiling log and the command to reproduce it as well as push your change to a draft PR? I will ping Synopsys AE to take a look.

**Comment by TimEwins** [comment]
Working on this ....

**Comment by sriyerg** [comment]
110ms vs 240ms simtime could be attributed to randomization. Could we reproduce this on a different machine too, just to eliminate other variables?
Also, what are the VCS and Xcelium tool versions used?
