### ISSUE TITLE
[sw/opentitantool] Add bitstream ROM splicing capabilities to `load_bitstream` command

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#10865]
# Problem
The opentitantool `load_bitstream` command loads the FPGA bitstream into the FPGA. By default the FPGA bitstreams contain the test ROM. Unfortunately, in order to run mask ROM E2E tests, the bitstream must contain the mask ROM, not the test ROM. Fortunately, a [utility script](https://github.com/lowRISC/opentitan/blob/master/util/fpga/splice_rom.sh) exists to splice either the test or mask ROM into the bitstream, before it is loaded to the FPGA. However, opentitantool is not aware of this tooling, and therefore the splicing script must be run manually, prior to invoking opentitantool to load the bitstream.

# Solution
To make address this issue, the opentitantool `load_bitstream` command can be expanded to include options for splicing the correct ROM image into the bitstream, before it is loaded on the FPGA.

**Comment by rswarbrick** [comment]
I'm not completely against this, but don't really understand it. Naively, I'd have thought that "produce a bitstream with the stuff you want" is part of the build step and "now load that bitstream onto the FPGA" is part of the run step. This seems like we're slightly conflating the two?

**Comment by timothytrippel** [comment]
Ultimately, we want to use opentitantool's `load_bitstream` command to flash FPGA bitstreams. Currently, you can provide this command with a file path to the bitstream you want to load (it is just minorly inconvenient to run the splicing script manually and then load, I actually have aliases to do so that I would like to replace). So there really are two options here:

1) embed the splicing functionality as a sub-command to the `load_bitstream` command to splice the most up to date test/mask ROM images into an existing bitstream (whose path you provide to the command), or

2) bring bitstream building under bazel control (like Verilator, by having bazel just kick off the right fusesoc command), and have bazel kick off the splicing to produce two bitstreams (one each with test and mask ROM images), then just provide the correct bitstream to the opentitantool `load_bitstream` command.

Either are ok with me, and I definitely see your point regarding separation of build and load phases. In either case, I think it is important we provide a mechanism to kick off the splicing (through bazel or opentitantool, to keep things centralized) without forcing an entire bitstream re-build, so we can enable fast ROM SW iteration. That is, providing a mechanism to just build and splice ROM images into old bitstreams.

**Comment by rswarbrick** [comment]
Right, that makes sense. For my 2 cents, I'd probably choose option (2). And it's probably actually easier to implement :-)

**Comment by alphan** [comment]
I think this is better handled by the build system/bazel. Closing this in favor of #13804. Please reopen if you think otherwise. Thanks!
