### ISSUE TITLE
[rv_dm] D2S review opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10860]
- [x] Add comment for bust host integrity error (https://github.com/lowRISC/opentitan/pull/10866)
- [x] Add an LC gate on the JTAG signals (https://github.com/lowRISC/opentitan/pull/10866)
- [x] Add the EN_IFETCH.CTRL.MUBI (https://github.com/lowRISC/opentitan/pull/10866)
- [x] Double-check why countermeasures are not rendered in public docs (auto generate tags are probably missing) (https://github.com/lowRISC/opentitan/pull/10866)
- [x] Clean up LC comparisons with LC functions (https://github.com/lowRISC/opentitan/pull/10866)
- [x] Sync spreadsheet to CMs

**Comment by tjaychen** [comment]
Before you guys add any logic on the jtag signals, make sure to check in with @arnonsha and others.
It may not matter for this particular dft strategy, but there are definitely cases where placing logic on the jtag pins (especially tck and trst_n) can make certain tools in certain situations unhappy. 

I don't really think it matters in this case, but it would be good to double check.

**Comment by tjaychen** [comment]
@GregAC let me know if you want me to help look at this. I put in the initial hardening a long time ago, not sure if those need to be reverted or not.

**Comment by msfschaffner** [comment]
> @GregAC let me know if you want me to help look at this. I put in the initial hardening a long time ago, not sure if those need to be reverted or not.

The existing hardening all looked good - the only thing that came up was the additional LC gate on the JTAG signal.

**Comment by msfschaffner** [comment]
> Before you guys add any logic on the jtag signals, make sure to check in with @arnonsha and others. It may not matter for this particular dft strategy, but there are definitely cases where placing logic on the jtag pins (especially tck and trst_n) can make certain tools in certain situations unhappy.
> 
> I don't really think it matters in this case, but it would be good to double check.

Good point, let's double check.

**Comment by msfschaffner** [comment]
Sorry for the late reply

If I understand correctly the gating is on the ibex core jtag only. LC and DFT taps are not impacted because of this. am I right ?

Anyhow, I just checked. My DFT related runs were not impacted.

_Originally posted by @arnonsha in https://github.com/lowRISC/opentitan/issues/10866#issuecomment-1042095373_
