### ISSUE TITLE
DFT - In usbdev_aon_wake block aon_usb_events_active reset should be controlled in scan-mode

### ISSUE THREAD

**Issue by NoamGottlieb** [lowRISC/opentitan#10879]
aon_usb_events_active affecting ~12 FFs. In scan mode it is not controlled, hence these FFs are removed from scan.
SpyGlass-DFT message:
'chip_earlgrey_asic.top_earlgrey.u_pinmux_aon.u_usbdev_aon_wake.aon_usb_events_active' is not disabled for 12 flip-flop(s)
![image](https://user-images.githubusercontent.com/79256454/154251277-b0de3246-0801-4d7f-b859-89836aa0aa46.png)

**Comment by NoamGottlieb** [comment]
@arnonsha

**Comment by arnonsha** [comment]
Since all the uncontrolled FFs are in the 2 prim_filters inserted in MR  #10527

### Suggested solution
Mux the reset in the filter input with the existing rst_aon_ni (which is controlled in scan)
```
  prim_filter #(
    .AsyncOn(1),
    .Cycles(3)
  ) filter_bus_reset (
    .clk_i    (clk_aon_i),
                  // MUX with scan mode       <-------------------------
    .rst_ni   (scan_mode ? rst_aon_ni : aon_usb_events_active),
    .enable_i (1'b1),
    .filter_i (se0_async),
    .filter_o (event_bus_reset)
  );
```

Need to do the same for the 2nd filter as well.

**Comment by tjaychen** [comment]
@a-will let me add a clear port to `prim_filter` here, that way we can use the `aon_usb_events_active` to achieve the same effect synchronously. I would prefer to not add the bypass mux if possible.

**Comment by arnonsha** [comment]
Yes, synchronous reset would be the best option:
From ATPG point of view, every clock or reset mux bypass just lowers the coverage because the mux is fixed on one path only. All the other path's faults are not checked.

thanks @tjaychen
