### ISSUE TITLE
[flash_ctrl] Clarification Of Arbitration Functionality (Arbiter FSM) In The Flash Protocol Controller

### ISSUE THREAD

**Issue by TimEwins** [lowRISC/opentitan#10886]
Hi

I have a clarification question on the function of the Arbiter FSM in the Flash Protocol Controller (to the left-hand side of this Block Diagram)

The Life Cycle Controller can be used to control the output of secret seeds, the otp keys and the RMA.

In all the functions except the RMA, the LC controls hardware signals that either enable or disable access to certain info partitions, but the data programmed, or read always passes out of the DUT via the TLUL fabric (the core SW interface).

The LC has no provision for writing, or reading the Flash itself, it controls the RMA cycle.

We see the spec says: -

“When an RMA entry request is received from the life cycle manager, the flash controller waits for any pending flash transaction to complete, then switches priority to the hardware interface. The flash controller then initiates RMA entry process and notifies the life cycle controller when it is complete. The RMA entry process wipes out all data, creator, owner and isolated partitions.”

When the LC requests an RMA, the Flash Ctrl accesses all locations sequentially, so basically the arbiter here is to allow any activity on the core SW to complete, before switching to the RMA cycle.  After the RMA cycle, the Flash Ctrl awaits a reset.

I believe this is the functionality we need to verify here, if there are any others please let us know.

![Screen Shot 02-16-22 at 04 03 PM](https://user-images.githubusercontent.com/92723163/154315402-c42c3431-ebdb-453e-bf94-bf2ea5a49c74.PNG)

**Comment by tjaychen** [comment]
yes this is all correct. Is there any language in the spec you would like me to enhance to make all of this clearer?

**Comment by TimEwins** [comment]
@tjaychen I think the documentation is OK, I was just checking to make sure I had this requirement clear.  Thanks.

**Comment by tjaychen** [comment]
sounds good. Please feel free to close the issue.

**Comment by TimEwins** [comment]
This issue can be closed
