### ISSUE TITLE
[adc_ctrl] Register adc_wakeup_status does not exist

### ISSUE THREAD

**Issue by NigelScales** [lowRISC/opentitan#10884]
Register adc_wakeup_status is mentioned a number of times in the design specification.
This register does not appear to exist in the RTL or adc_ctrl.hjson and thus UVM register model.

It seems that in the current RTL filter_status is masked by adc_wakeup_ctl to generate the wakeup signal.

**Comment by tjaychen** [comment]
that is correct, let me fix the documentation.
