### ISSUE TITLE
[sw/opentitantool] move `ROM_EXT` image signer to opentitantool

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#10895]
# Overview
Currently, a stand-alone Rust tool exists (in [`sw/host/rom_ext_image_tools/signer/`](https://github.com/lowRISC/opentitan/tree/master/sw/host/rom_ext_image_tools/signer)) to sign and prepare the manifest of a `ROM_EXT` image so that it may be successfully booted by the mask ROM. This  tooling is in the process of being migrated to `opentitantool`, in line with the long term goals of `opentitantool`. This issue is to track the progress of this development of this `opentitantool` feature.

# Task Burndown
TDB

**Comment by alphan** [comment]
@jon-flatley took care of this in #13021
