### ISSUE TITLE
[rstmgr] D2S review opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10899]
- [x] make another copy of scanmode for shadow usage.
- [x] clean up alert indexing nit
- [x] check whether it makes sense to pull this out as a parameter (maybe a Sec parameter?) - but this is a low-prio cleanup.
- [x] add a terminal error state where the checker FSM should move to upon detecting a fatal error condition.
- [x] split FSM alert from consistency checker alert (i.e. make two channels) so that they can be classified separately in the alert handler - but keep both conditions as fatal.
- [x] It would be good to detect a transition into and out of scanmode and assert POR as an atomic operation. This likely incurs addition of non-scannable sequential elements (due to edge detection and due to the delay needed in order to assert the resets before letting scanmode propagate to the system and steer all the muxes). Need to double check with DFT guys from Nuvoton.
- [x] Chris to sync spreadsheet to CMs
- [x] Take a look at documentation comments and check what can be fixed.

**Comment by msfschaffner** [comment]
@tjaychen should we split out the POR on scan entry/exit into a separate issue so that we can mark this done and close it?

**Comment by tjaychen** [comment]
yeah we can do that. Although that particular feature won't show up in open source though, so maybe we should file it as a closed source issue.

**Comment by msfschaffner** [comment]
Done.

**Comment by tjaychen** [comment]
spreadsheet sync'd.
