### ISSUE TITLE
[debug] Disable access to debug memory when not in debug mode

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#109]
For security reasons (and probably many other reasons), we don't want to give software running on our CPU the ability to access the memory in the debug module, except when in debug mode. We can enter debug mode through a core-initiated action (an EBREAK), or an interrupt from the debug mode (debug_req).

This clarification is currently discussed in the debug spec tracker at https://github.com/riscv/riscv-debug-spec/pull/482.

What's less clear: how we want to implement this checking. In general, we only have the information "core is in debug mode" in the core itself. So either we need to export this information, or do the checking in the core.

1. In the core: use a PMP-like mechanism to filter out accesses to the debug memory regions if not in debug mode. The core currently doesn't know exactly where the debug memory starts and ends, so we need to make that available to the core.
2. In the interconnect.
3. In the debug module

Options 2 and 3 need to make use of a new debug_mode signal from the core to switch their behavior.

@eunchan @tomroberts-lowrisc @tjaychen which option sounds most reasonable to you?

**Comment by msfschaffner** [comment]
@tjaychen I believe we took care of this via debug life cycle gating is that correct?

**Comment by tjaychen** [comment]
yep, and this should go through rv_dm review.

**Comment by msfschaffner** [comment]
FYI @rswarbrick @GregAC

**Comment by msfschaffner** [comment]
@cdgori
