### ISSUE TITLE
[usbdev] Differential receiver may turn off without changing the RX mode

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#10901]
Currently, the differential receiver is turned off when usbdev gets into a suspended state. However, `usb_fs_rx` does not get informed that the single-ended `usb_d_i` is going inactive, and this could lead to undefined behavior for detecting resume.

We'll need to either dynamically switch modes in `usb_fs_rx`, or we'll need to leave the differential receiver on as long as usbdev is receiving power. The AON module only looks at the separate signals that make up the diff pair, so the differential receiver can be turned off whenever the chip is in light sleep / deep sleep.

**Comment by mdhayter** [comment]
Turning the differential rx off should  give power savings (depending on the PHY) so probably best to park the signal or have the usb_fx_rx understand this state.

**Comment by tjaychen** [comment]
> Turning the differential rx off should give power savings (depending on the PHY) so probably best to park the signal or have the usb_fx_rx understand this state.

@a-will discussed this a bit yesterday. 

In any of the low power states, the `usbdev` clock is turned off.  So the module is not able to interpret any of the signal anyways, `usbdev_aon_wake` has to take over.

In any of the non-low-power states where the `usbdev` is in suspend, the system power (at least right now) would likely dwarf any consumption from the differential receiver.  I will double check this.
