### ISSUE TITLE
[mask_rom/e2e_tests] Testing both A and B partitions in flash

### ISSUE THREAD

**Issue by milesdai** [lowRISC/opentitan#10929]
The E2E testplan (#10548) implicitly runs all tests in slot A of the flash. We should add some tests under the bootup and upgrade categories that load ROM_EXTs into slot B.

**Comment by weicaiyang** [comment]
@timothytrippel can you add a priority tag for this?

**Comment by alphan** [comment]
#14488 #14469 #14474 and possibly others cover this case.
