### ISSUE TITLE
[entropy_src, csrng, edn, dv] Avoid full path references in the test sequences

### ISSUE THREAD

**Issue by Muqing-Liu** [lowRISC/opentitan#10932]
There are some full path references in the entropy_src, csrng and edn interrupt, alert and error tests, as suggested by @sriyerg in #9896, it's better to make them partial hierarchies within the DUT.

**Comment by msfschaffner** [comment]
@martin-lueker is this something that still needs to be addressed?

**Comment by martin-lueker** [comment]
IIRC: This was opened in regard to this comment: https://github.com/lowRISC/opentitan/pull/9896#discussion_r799737476

There is now an `entropy_src_assert_if` to capture these.  So I believe this can be closed.  @Muqing-Liu can you confirm?

**Comment by msfschaffner** [comment]
@Muqing-Liu @martin-lueker friendly ping to check and close, if possible.

**Comment by Muqing-Liu** [comment]
Sorry I missed this comment, yes, I think this can be closed.

**Comment by msfschaffner** [comment]
Thanks @Muqing-Liu - closing!
