### ISSUE TITLE
[kmac] Report entropy error on app interface

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#10933]
Hi KMAC experts,

I would like to confirm a current design behavior:
1). EDN related error occurs (for example: entropy timeout, entropy configured wrong mode etc)
2). The error is reflected to `err_code` register and interrupt `kmac_err_o` will fire
3). However, if the kmac operations is in APP interface, the behavior is different:
    a). If it is keymgr interface, the error bit is set to 1.
    b). If it is rom_ctrl or lc_ctrl interface, the error bit is NOT set.  -> Is this okay? Shall we still fire an error?

We would like to check if the application interface behavior is expected.

Thanks,
Cindy

**Comment by tjaychen** [comment]
ah it kind of feels like the behavior should probably be consistent.
