### ISSUE TITLE
[usb] remove inline lint comments

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/opentitan#1093]
refers to #1066 

the inherited USB code has inline lint waivers. We're using a waiver-file approach
that is currently not yet in-repo. In a separate PR we should remove the
inline `// lint` waivers and create replacement ones that inherit the intent.

@vogelpi @stefanlippuner @msfschaffner

**Comment by vogelpi** [comment]
I am closing this issue as the PR containing the required changes has been merged.
