### ISSUE TITLE
[dv/kmac] cycle-accurate scb

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#10966]
Consider not support app interface for cycle accurate check.
I think it could be simpler as this:
1) SCB receive data_in,
2) SCB waits for design ack with a timeout check to ensure nothing stuck,
3). SCB check digest data when received done signal, and check intr_state.
In the meantime, check sha3_status Idle is set to 0.

Then we do not need this `app_with_partial_data_vseq` anymore.

**Comment by moidx** [comment]
Hi @cindychip, marking as M2, but please update if needed.

**Comment by cindychip** [comment]
Done in RPs:
https://github.com/lowRISC/opentitan/pull/14519
https://github.com/lowRISC/opentitan/pull/14374
https://github.com/lowRISC/opentitan/pull/14295
