### ISSUE TITLE
[dv] Common exclusions don't work for Xcelium

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#10962]
@rasmus-madsen 

We have these 2 exclusions for toggle, but they don't work. Can you take a look?
https://github.com/lowRISC/opentitan/blob/92173aa54ac2fba4c68b2362eb0bf7b563b09cfb/hw/dv/tools/xcelium/common_cov_excl.tcl#L9-L10

EDN still shows them uncovered.
https://reports.opentitan.org/hw/ip/edn/dv/latest/cov_report/index.html

FYI @sriyerg @senelson7

**Comment by rasmus-madsen** [comment]
@weicaiyang sure - I will do this first thing Monday morning as everyone in WD will need these

**Comment by rasmus-madsen** [comment]
@weicaiyang the issue is the [6] is not escaped - but for some reason I cannot get it to escape it correctly
which causes the following exclusions to be ignored.

I tried really fast to exclude it, but then I get a signal cannot be found issue.
I will look close monday.

**Comment by weicaiyang** [comment]
> @weicaiyang the issue is the [6] is not escaped - but for some reason I cannot get it to escape it correctly which causes the following exclusions to be ignored.
> 
> I tried really fast to exclude it, but then I get a signal cannot be found issue. I will look close monday.

Thanks for looking into this.
rsp_intg[6] is truly unreachable. If we can't exclude it in a common file, we can rely on the exclusion from UNR.

It will be nice if we can exclude `*alert_rx_*.ping_*` in common exclusion, otherwise, we have to manually add it in each IP.

**Comment by rasmus-madsen** [comment]
@weicaiyang  I have reached out to cadence for the rsp_intg[6].

the others work fine if we remove the failing ones. 
I will create a PR to update once I hear back from Cadence

**Comment by rasmus-madsen** [comment]
@weicaiyang update
I know have Cadence trying to reproduce this, as their solutions does not work:
I expect to hear more by tomorrow

**Comment by weicaiyang** [comment]
> @weicaiyang update I know have Cadence trying to reproduce this, as their solutions does not work: I expect to hear more by tomorrow

sounds good. Thanks for the update.

**Comment by rasmus-madsen** [comment]
@weicai so I figured it out .
for some weird reason the [6] needs to go outside the the ''
