### ISSUE TITLE
[entropy_complex] Corner case tests at the chip level

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10970]
This issue captures recommended tests and associated questions that came up in the [V2 meeting for EDN](https://docs.google.com/document/d/1K1f6Q4hb7tkd3vP7dyO6-xLqGz-kH5_cKzgVOs4HUNs/edit#):

- [x] There is probably a need for an entropy stress test at the system level. Current list of entropy consumers in the system:
  - AES
  - KMAC
  - OTBN
  - Keymgr
  - Ibex
  - Alert Handler (ping timer)
  - OTP Ctrl (background check timer)
  
  This test may end up looking very similar to parts of the power virus workload (maybe we can make this part of the same test?) https://github.com/lowRISC/opentitan/issues/9297

- [ ] Do we need to cover special corner cases around sleep entry to assess EDN interfaces crossing CDCs? I.e., enter / exit low power state while an EDN fetch is ongoing in one or more entropy consumers? (Note: since there are no entropy consumers on the AON domain, deep sleep scenarios where power is turned off may be less interesting than light sleep where clocks are gated).

- [ ] Is there a need for a max latency test accross the individual entropy blocks / the entire entropy subsystem? For the latter, would it even be possible to bound the req -> ack latency accross the entire subsystem? If the answer is yes to any of these questions, how do we derive the thresholds? 

If we decide to add any of the tests above, need to make sure these are reflected in the testplan.

> estimate 16

**Comment by martin-lueker** [comment]
Hi Everyone, I'm reviewing Entropy_complex issues.   This one has not seen much traffic since it was opened.  Are there any updates?

**Comment by cdgori** [comment]
Just looking at those, I think the stress test will be needed for sure.  

The CDC/sleep-wake part might be handled by some of the other ongoing CDC testing, not sure.  If not then it seems like general cross-module testing of clock gating behavior is desirable.  (Maybe this is more a "full chip" test than an "entropy complex" test though?)

I can argue that the max latency could be deferred (substantially or indefinitely) as long as we are doing boot entropy tests at the full-chip level.  But I don't remember the context of why we considered/wanted that test?

**Comment by msfschaffner** [comment]
Agreed that the CDC/sleep-wake part may already be handled as part of the existing tests and CDC tooling.

For the stress test, the max load test may actually suffice, since it exercises the entropy complex quite heavily: https://github.com/lowRISC/opentitan/issues/14814#issuecomment-1295498573

As for the max latency test - this came up as a question, but as you say this may not be needed if we have tests for critical functionality such as a boot entropy test. @moidx @tjaychen @alphan @WDYT?

**Comment by tjaychen** [comment]
@cindychip @eunchan 
For the max latency, we should double check whether kmac enforces that check in hardware.
I think it does, which is why we had a kmac timeout test I believe.  That's the primary case to worry about here I think.

**Comment by alphan** [comment]
> As for the max latency test - this came up as a question, but as you say this may not be needed if we have tests for critical functionality such as a boot entropy test. @moidx @tjaychen @alphan WDYT?

We have something in our todo list to make sure the boot mode entropy will be enough for ROM. Is this what you are referring to?

**Comment by tjaychen** [comment]
@alphan do you know if such tests are time bound?
The real check in the end, I think will have to be in Nuvoton's closed environment with the real AST (@sha-ron / @zi-v ).
Ie, we simulate that given AST start-up conditions we still are able to get entropy into sram_ctrl for scrambling setup in a timely manner. 

We can't really do this testing very well in open source since we only have a model of the rng.

**Comment by cindychip** [comment]
> @cindychip @eunchan For the max latency, we should double check whether kmac enforces that check in hardware. I think it does, which is why we had a kmac timeout test I believe. That's the primary case to worry about here I think.

Hey Tim, sorry for the late reply. For kmac, SW can configure a timeout value in CSR. If timeout reached, KMAC will return an interrupt and SW will need to reset the IP to get entropy working again.

**Comment by tjaychen** [comment]
> > @cindychip @eunchan For the max latency, we should double check whether kmac enforces that check in hardware. I think it does, which is why we had a kmac timeout test I believe. That's the primary case to worry about here I think.
> 
> Hey Tim, sorry for the late reply. For kmac, SW can configure a timeout value in CSR. If timeout reached, KMAC will return an interrupt and SW will need to reset the IP to get entropy working again.

ah sounds good. Thanks for reminding me, I always forget it's software configurable. Then maybe the max latency stuff is something we should just table to M3.  Kmac isn't used by ROM, so we don't really need to figure out how to configure this value early on.  The only thing where entropy latency matters a ton very early during boot is just sram_ctrl scrambling and memory initialization. 

Let me know if everyone agrees, but I believe the entropy complex across power domain / clock domain case will in some sense be covered by our concurrency tests (@timothytrippel ).   The only wildcard is again the ast, since the ast has a mix of always on and non-always on domains. (@zi-v / @sha-ron ).

**Comment by msfschaffner** [comment]
I agree, and think the max latency test can be deferred. 
The other aspects should be mostly covered by the concurrency test and existing CDC infrastructure.
Do we want to reassess this entire issue as part of M3, or do you think anything needs to be done for M2?

**Comment by tjaychen** [comment]
I think most of this is okay to defer to M3, especially since the power virus is M2 already.
The only thing I think we want to check is the AST stuff and if Sha-ron / Ziv think that should land. 

Because looking at the entropy consumers, AST is the only one that has the potential to be always on, meaning they could for example leave their request high when the edn gets reset.  This might be covered by their `ast_clk_rst_inputs` test, but we should probably double check.

**Comment by msfschaffner** [comment]
OK sounds good!

**Comment by sha-ron** [comment]
@tjaychen All the chip level tests will run also with the real AST so if the tests check for latency I think we are covered. Is there additional configuration or check you think we should add only in the closed-source?

**Comment by alphan** [comment]
> @alphan do you know if such tests are time bound? The real check in the end, I think will have to be in Nuvoton's closed environment with the real AST (@sha-ron / @zi-v ). Ie, we simulate that given AST start-up conditions we still are able to get entropy into sram_ctrl for scrambling setup in a timely manner.
> 
> We can't really do this testing very well in open source since we only have a model of the rng.

No, the ones on our list are not time-bound. We just need to make sure the amount of entropy we consume during boot can be supplied with the initial configuration.

**Comment by alphan** [comment]
> @alphan / @sriyerg what do you guys think? I don't think we have an explicit check for this or anything, so if the sram scramble setup takes extra long, unless it causes the test to timeout, we wouldn't actually notice it.

I think so. As long as it's under 1 s, the hardcoded initial watchdog bit threshold that we use pre-CRT [here](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom/rom_start.S;drc=ff6f87515d0fac569fb32534b8fe78a329689ec4;l=164), we should be OK.

**Comment by zi-v** [comment]
I think there should be at least one test that checks that the boot timing is reasonable. IMO, there's no need to write a generic model that cover all configuration options or something like that, just one, or a few, tests with specific configuration that makes sense. We should run it in both open- and close-source environment. Running it with slowest possible uncalibrated clocks would be a good idea.

**Comment by tjaychen** [comment]
@msfschaffner and i talked through this today.
We believe the major points in this test can be covered by the `power virus` test and Nuvoton tests.
We do need to add one test in M3 to check the upper limit of secure boot, but we don't believe that needs to be M2 gating. 

Let me know if anyone objects, otherwise we will drop this to M3 at the end of day tomorrow.

**Comment by zi-v** [comment]
I agree

**Comment by alphan** [comment]
> @msfschaffner and i talked through this today. We believe the major points in this test can be covered by the `power virus` test and Nuvoton tests. We do need to add one test in M3 to check the upper limit of secure boot, but we don't believe that needs to be M2 gating.
> 
> Let me know if anyone objects, otherwise we will drop this to M3 at the end of day tomorrow.

SGTM

**Comment by GregAC** [comment]
I think it's worth considering an entropy stress test for M2.5

**Comment by vogelpi** [comment]
Triaged for `entropy_src`. I agree that we want this for M2.5.

**Comment by GregAC** [comment]
Triaged for `rv_core_ibex` same conclusion as above

**Comment by andreaskurth** [comment]
Triaged for `edn` and `csrng`, agree.

For the system-level entropy stress test, maybe parts of the `chip_sw_power_max_load` test could be reused (see https://github.com/lowRISC/opentitan/issues/14814 for the state of its implementation).

**Comment by marnovandermaas** [comment]
I will track the effort of this for M2.5 in the EDN block:
> estimate 16

**Comment by msfschaffner** [comment]
Discussed with @moidx. We are closing this issue since profiling the boot times can be done more accurately with real silicon samples using existing ROM E2E tests that have already been developed. The same tests could be inspected in simulation as well.
