### ISSUE TITLE
aes lowering EDN req  on error

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#10991]
the case where an error is detected and an alert is raised while and pending request to EDN is active the dut will lover the request.
this violates an assertion in the push_pull module.

The question is what is correct behavior for the DUT in the case of an alert - it seems completely reasonable that it lowers its request. 
if this is the case we need to remove the assertion from the push pull - and everybody using it needs to verify they can handle the case where a request goes away before being completed.

if the current behavior the AES is violating the spec upon raising alert.
there are two ways to go here.
1. we don't care - if an alert happens it is ok for things to break down. I can disable the assertion in the testcase.
2. update the dut to complete the transaction even when an alert has happened

![image](https://user-images.githubusercontent.com/53917183/154957717-a6d69659-89e6-428b-bb59-64c56443b78d.png)

**Comment by vogelpi** [comment]
Hi @rasmus-madsen ,
thanks for reporting this. As you say, it is reasonable to lower the request in the case of a fatal alert. When this happens, the SVA needs to be switched off. However, this must happen dynamically. We have an input on the primitive for this and use this already for LC escalation. I will file a PR to also do that upon a fatal alert detected internally.

**Comment by vogelpi** [comment]
Re-opening as my PR only addressed the part in the RTL, there remains a second part to be addressed inside the push-pull agent.

**Comment by vogelpi** [comment]
I see the second half is tracked here: #10998

**Comment by vogelpi** [comment]
Thanks @rasmus-madsen for explaining the situation. This can certainly be done. I'll do a PR to make the required change.

**Comment by vogelpi** [comment]
I am again closing the issue as the PR fixing this for good has been merged.
