### ISSUE TITLE
SPI_HOST : SW_reset impact on CMD queue

### ISSUE THREAD

**Issue by visbaz** [lowRISC/opentitan#11000]
SW reset happening while ongoing commands doesnt clear the command queue. - Test fails

**Is this the expected functionality ?**

SW_RST as per spec:
SW_RST | Clears the entire IP to the reset state when set to 1, including the FIFOs, the CDC's, the core state machine and the shift register. In the current implementation, the CDC FIFOs are drained not reset. Therefore software must confirm that both FIFO's empty before releasing the IP from reset.

PR: https://github.com/lowRISC/opentitan/pull/10913

Reproduce Issue:
util/dvsim/dvsim.py hw/ip/spi_host/dv/spi_host_sim_cfg.hjson -i spi_host_sw_reset --waves --fixed-seed 2381543438

**Comment by martin-lueker** [comment]
Hi Viswa,  
   Thanks for finding this.  This is not expected.   It may come about because the CMD FIFO was a late addition.  I'll take a look.

-Martin

**Comment by martin-lueker** [comment]
Hi @visbaz,
    So looking more closely I can say the following.  
1. The cmd FIFO is clearly properly, so we have to dig more to understand the root of the problem
2. The sentence you've quoted from the specification is out of date.  It shouldn't harm anything to to assert sw_rst, but it's not necessary as there is no longer a CDC inside this block and all the FIFOs in here are synchronous.

**Comment by visbaz** [comment]
This issue is closed as the clarification from designer is that registers will not be effected by sw_rst.
Test has been modified to check only TX RX fifo empty and not register default values.
@martin-lueker thanks for your clarification and kindly update the information in SPI_HOST specification
