### ISSUE TITLE
[meson] Document minimum supported meson version

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1101]
We should add a `meson_version: '>= xxx',` in `meson.build` to document the minimum supported meson version. We can be fairly aggressive there and update whenever needed, since we install meson from pip and users have easy access to newer versions. But it would be good to bail out if we know that meson is too old.

**Comment by lenary** [comment]
I think I want to be using some functionality relating to static libraries that has been present since 0.51.0, from June 16 2019.

**Comment by lenary** [comment]
In the end, I didn't use that functionality because it wasn't quite doing the right thing anyway.

**Comment by lenary** [comment]
I had to use some Meson 0.51.0 features in #1106, so I have added a minimum meson version based on that to `meson.build` and `python-requirements.txt`.
