### ISSUE TITLE
[pwm] clarification of 'pulse mode' in pwm_testplan.hjson

### ISSUE THREAD

**Issue by jason-hoddinett** [lowRISC/opentitan#11012]
The testplan includes multiple references to a 'pulse mode'.  However, this is not a mode defined within the HWIP technical specification. It is ambiguous as to whether it is supposed to be interpreted as;
- a feature such as heartbeart mode or blink mode
- as reference to any pulses regardless of mode
- iff heartbeat mode and blink mode are both disabled
Thanks,
Jason

**Comment by mwbranstad** [comment]
Hi @cindychip I think this one goes to @martin-lueker.

**Comment by rasmus-madsen** [comment]
@cindychip one could argue it is in the name ;) "PWM"
Anyway
the basic behavior in a PWM is to generate a pulse with a specific duty cycle.
this is referenced as pulse mode in the verification plan, you are correct this mode is not actively named in the hardware spec
but at least there are hints as to what a pulse mode could be where the 3 modes are describes

> - The PWM can be programmed to generate pulses at a firmware-defined duty cycle.
> - The duty cycle can be programmed to toggle (or “blink”) between two duty cycles at a programmable rate. In the tri-color LED use-case, this would have the visual effect of making the LED blink between two colors.
> - The duty cycle can linearly sweep in time, gradually shifting back-and-forth between two endpoints.
