### ISSUE TITLE
[sysrst_ctrl/dv] Verify design change on flash_wp_l

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#11018]
@patel-madhuri 
The design change for #10773 has been added. We should add a test or update existing test to verify it before signing off V2.

Creating this issue for tracking it.

FYI @msfschaffner

**Comment by msfschaffner** [comment]
FYI I did align some of the tests (`pin access test` that is part of the smoke check) in https://github.com/lowRISC/opentitan/pull/10774 - but that does not cover the entire functionality that has been added.

**Comment by patel-madhuri** [comment]
To verify this added functionality, we have 3 tests:
1. Pin access test (which is already aligned)
2. Flash write protect test (which is already implemented and running in regression)
3. Key triggered and interrupt test (i.e edge detect test which is under review)

**Comment by weicaiyang** [comment]
> To verify this added functionality, we have 3 tests:
> 
> 1. Pin access test (which is already aligned)
> 2. Flash write protect test (which is already implemented and running in regression)
> 3. Key triggered and interrupt test (i.e edge detect test which is under review)

If I understand correctly, the flash_wp_l_i shouldn't affect the flash_wp_l_o. Do we have a test for this?

**Comment by msfschaffner** [comment]
Indeed, `flash_wp_l_i` can only be read out via the CSRs, but it does not have an effect on `flash_wp_l_o`.

**Comment by patel-madhuri** [comment]
In our current tests we have always checked flash_wp_l_o for either 0 or 1

**Comment by weicaiyang** [comment]
> In our current tests we have always checked flash_wp_l_o for either 0 or 1

that's nice. just want to confirm, in the test we check flash_wp_l_o, do we toggle flash_wp_l_i? This is because we need to know if input affects output or not.

**Comment by patel-madhuri** [comment]
We have updated the smoke test where we randomize the flash_wp_l_i and check flash_wp_l_o stays low to make sure input pin does not affect output pin. Here is the pull request
https://github.com/lowRISC/opentitan/pull/11527

**Comment by weicaiyang** [comment]
> We have updated the smoke test where we randomize the flash_wp_l_i and check flash_wp_l_o stays low to make sure input pin does not affect output pin. Here is the pull request #11527

That looks good. Thanks
Can you also randomize the `flash_wp_l_i` in test `sysrst_ctrl_flash_wr_prot_vseq`? That test also checks both cases -flash_wp_l_o = 1 and flash_wp_l_o = 0.

**Comment by patel-madhuri** [comment]
The sysrst_ctrl_flash_wr_prot test is updated and merged where we randomize the flash_wp_l_in and check both cases flash_wp_l_o = 1 and flash_wp_l_o = 0. Here is the PR https://github.com/lowRISC/opentitan/pull/11599

**Comment by weicaiyang** [comment]
Thanks @patel-madhuri  for addressing this issue. Closing it now.
