### ISSUE TITLE
[rstmgr] V2 review action items

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#11038]
FYI, these are the AIs that are captured in V2 review meeting.

- [x] Add missing covergroups: https://github.com/lowRISC/opentitan/issues/10687
- [x] Review UNR exclusions with Tim
- [x] The PR of rstmgr_cnsty TB is blocked due to a CI failure. Work with Sri to resolve it.
- [x] Add this at the end of hw/ip/rstmgr/dv/cov/rstmgr_cover.cfg to enable toggle coverage for rstmgr_cnsty_chk: 
```
begin tgl
  +module rstmgr_cnsty_chk
end
```
- [x] review the rstmgr CSR exclusion and look into the issue that disabling exclusion in block-level didn’t work
- [x] Update the description of covergroup - alert_info_capture_cg.
- [ ] double check if pwrmgr issues multiple wakeups at the same time for one low-power exit.
- [x] unmapped tests in rstmgr regression report.
  - Remove mem_test in testplan

**Comment by matutem** [comment]
Missing item is double check if pwrmgr issues multiple wakeups at the same time for one low-power exit: issue https://github.com/lowRISC/opentitan/issues/11161.
