### ISSUE TITLE
[tlul/xbar] Add blanking based on address 

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#11036]
This has been spun out from the D2S review notes here https://github.com/lowRISC/opentitan/issues/10926.

We should look into whether we can add blanking based on address in reggen (reg_top). Consider putting the gating into the XBAR. Also need to think whether gating to zero is the right thing to do for all critical registers (e.g. invalid MUBI nibble pattern). Make a separate issue that tracks this (so that it does not gate clkmgr D2S).

**Comment by eunchan** [comment]
So, What I said in the meeting(3/8/2022) was:

the peripheral xbar has only one requester (TL Host) if I remember correctly. So, if socket_1n broadcast the data (I am not sure), then all peripherals can see the data.

If we can add one more TL host (requester), then we can cover the peripheral to the default requester always unless it is selected. So, from the attacker point of view, they need to tackle two points (valid for socket_m1, valid inside register module) or three points (+ attenuate the response d_valid to avoid alert).

The thing I want to check is:

the secret information always remains in the main crossbar (crypto). If it is main crossbar, we can re-order dm_sba port to be the 0 index and cover the value without changing peripheral xbar.

**Comment by tjaychen** [comment]
@eunchan, can you take a look at the PR? In your mind, what's the difference between doing this blanking on the `socket_1n` vs `socket_m1`?

I'm doing it on the former right now.

**Comment by eunchan** [comment]
> @eunchan, can you take a look at the PR? In your mind, what's the difference between doing this blanking on the `socket_1n` vs `socket_m1`?
> 
> I'm doing it on the former right now.
>
Oh, changing socket_1n is also fine. I misunderstood that socket_1n broadcasts the signal to every downstream ports.

**Comment by msfschaffner** [comment]
Address-based blanking has now been implemented in the xbar in https://github.com/lowRISC/opentitan/pull/11045.

However, we still plan to add spurious WE monitoring to the register nodes as discussed in this comment thread https://github.com/lowRISC/opentitan/pull/11045#discussion_r814145132.

**Comment by msfschaffner** [comment]
Spurious WE monitoring has now been implemented as well so I think we can close this.

**Comment by tjaychen** [comment]
yep that's right. Still on my radar, i got half way through something and
had to drop it to focus on other things.
