### ISSUE TITLE
[CSRNG] V2 Review items

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#11041]
Here are the action items from CSRNG V2 review

- [x] crosses for csrng_cmds_cq covergroup in testplan
- [x] Clean up broken links in   “Global types & methods”
- [x] csrng_cmd_o[0/1].csrng_rsp_sts needs a directed test to exercise -> add force bit case to error testing code.
- [x] SIM_ALL_TESTS_PASSING   
  - Still waiting for results from intr/err/alert #11006
- [ ] SIM_CODE_COVERAGE_V2              
  - Block, branch and expression all below 90%
- [x] Follow up with Rasmus/Sri on Xcelium UNR status (we have used xcelium UNR in other blocks)
- [x] CSRNG contains sub-module AES. Pending AES Follow-up with Rasmus 
- [x] Follow up these issues:
  - #7505: Pinged @moidx 
  - #5580: @mwbranstad to follow up -> reviewed issue, this can be closed now
  - #2652 can be closed @martin-lueker 
  - Review documentation Issue #3512 @martin-lueker 
- [x] Update CSR exclusion @mwbranstad : -> https://github.com/lowRISC/opentitan/pull/11040
  - Remove CSR excl on ERROR_CODE, but added to ERROR_CODE_TEST (fixes issue with item below)
  - Remove CSR excl on DEBUG_STATUS (now called MAIN_SM_STATE), and update default value

**Comment by marnovandermaas** [comment]
We have been able to get the coverage above 90%. The check off of V2 is tracked here: https://github.com/lowRISC/opentitan/pull/16517
