### ISSUE TITLE
[rom_ctrl] Post-V2S meeting action items

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#11072]
We had a V2S review meeting on 24th Feb 2022. For OpenTitan members, the meeting notes are [here](https://docs.google.com/document/d/1Hivxbhz1MaHgJ7z7gM89kLdmLbfILb9tv1ZHSXKwM3U).

Action items:
- [x] (@prajwalaputtappa) Sparse FSM checks
- [x] (@rswarbrick) Add a MEM.INTEGRITY countermeasure
- [x] (@prajwalaputtappa) Add an assertion for bus.local_esc
- [x] (@cindychip) Add rom_ctrl to FPV block list
- [x] (@prajwalaputtappa) Get rid of v2 exclusions file
- [x] (@prajwalaputtappa) Expand entries in sec_cm testplan to explain stimulus

**Comment by cindychip** [comment]
FPV is done with this PR: https://github.com/lowRISC/opentitan/pull/11129
