### ISSUE TITLE
RFC: OpenTitan V2S Milestone - Sign-off Process

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#11090]
Please see this [docs](https://docs.google.com/document/d/150V62yLZPwyPYgPIzpIPYsId3-TrhPK86i-9oAtRcjA/edit#) for the proposal.

**Comment by msfschaffner** [comment]
We discussed and approved this RFC in the TC meeting today.

**Comment by weicaiyang** [comment]
Thanks @msfschaffner. Closing this issue
