### ISSUE TITLE
[kmac] Add per Application-based use of entropy

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#11116]
ROM_CTRL app.intf needs to run KMAC prior to any SW configuration. To support this, KMAC entropy module generates garbage entropy at the Reset state.

Other app interfaces strictly need the uniformly distributed entropies. KMAC should support a way to not run other app. interfaces  (KeyMgr, LC_CTRL) while in the Reset state. The value should be written down to the compile-time parameter (inside `AppCfg`).

Plan is to add `EnWithoutEntropy` field in the `app_config_t` and only allow to run the interface with the value set.

CC: @tjaychen @vogelpi @cdgori @vrozic @cindychip

**Comment by vogelpi** [comment]
Yes, I think we should handle this somehow. Your approach @eunchan sounds good to me. Maybe one could also change the design to only run in this ROM_CTRL mode before the first register write through software happens.

**Comment by eunchan** [comment]
I am working on this issue.

**Comment by tjaychen** [comment]
wait actually i just realized, we probably cannot place `lc_ctrl` into that same cateogry.
One of the first token checks for `lc_ctrl` happens before the device is provisioned in any way (the ROM won't even be running).  `lc_ctrl` probably needs to be allowed in `ResetState` also. 

`keymgr` may be the only one that can require uniform entropy. 

@msfschaffner 
@cindychip

**Comment by eunchan** [comment]
Thanks for the info @tjaychen . Then, probably, `EnUniformEntropy` and set to `KeyMgr` app interface only would be better and raises an error (or alert) if KeyMgr AppIntf anyhow requests KMAC operation without proper entropy configurations.

**Comment by eunchan** [comment]
Hum, then, KMAC has three kinds of applications. KeyMgr, which shall run only with uniformly distributed random variables. LC_CTRL, which may run at reset state + with entropy after config. ROM_CTRL, which runs only at reset state.

Then, we may define three modes and check if the application interface requests any time other than their expected config.

**Comment by tjaychen** [comment]
i think it may be simpler to just say that lc_ctrl / rom_ctrl are allowed to run at reset state, but keymgr is not.
The issue with lc_ctrl is that it needs to support rma transition, so there's no good rule to say when it can be guaranteed to have good entropy.
