### ISSUE TITLE
[entropy_src] Issues with Observe FIFO interface

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#11134]
There are two minor usability issues with the Observe FIFO Interface have been observed in the course of verification.

1. It is currently unclear what happens when `OBSERVE_FIFO_THRESH` is set to 0.   From the RTL it appears that if this is set, then the Observe FIFO will always fire an interrupt.  
_Recommendation:_ Disable this interrupt when this register is set to zero.  
_SW Workaround_: Don't use zero as the level for this interface

2. There is no way to check that the Observe FIFO is not empty, only that it's value exceeds some threshold.   This may be fine if SW reads are the only way of removing or clearing this FIFO.     However disabling the IP also clears the Observe FIFO.  This can cause some confusion when SW is trying to clear it.  
_Recommendation:_ Add a depth register.
_Workaround:_ Clear the Observe FIFO interrupt when disabling the IP, and whenever finishing an Observe read.
Example scenario:
   - SW requests a OBSERVE_FIFO_THRESH of 16, and polls for data.   
   - Polling completes and SW reads the data.  (Usual procedure: read OBSERVE_FIFO_THRESH words, and clear the interrupt)
   - A health check interrupt fires, SW clears the interrupt and re-enables the IP, clearing the Observe FIFO in the process.
   - Interrupt controller exits and control returns to reading Observe FIFO data.  SW has no way of knowing that the Observe FIFO has been cleared.  Continued reading of the Observe FIFO triggers an underflow and a fatal error

**Comment by martin-lueker** [comment]
FYI: @cfrantz @mcy @tjaychen @moidx @zi-v

**Comment by martin-lueker** [comment]
Note: The workaround to problem 1 has already been merged as part of the test bench flow.  The DV workaround for the problem 2 will be added in an upcoming PR.  (No changes have been made to the DIFs for either of these cases)

**Comment by zi-v** [comment]
Re 2: Can we handle the FIFO clearing part of "health check interrupt" at main?
E.g.: Disable CSRNG/EDN inside the interrupt and flag the main SW that it needs to gracefully clean the FIFO and re-enable the RNG subsystem.

**Comment by martin-lueker** [comment]
There are lots of ways to work with problem 2 in Software. I just recommend we add a depth register at some point to let SW know what is happening for troubleshooting.

**Comment by mwbranstad** [comment]
After digesting the two problems, here is my conclusion:
Problem 1: Agreed that zero is not useful, and interrupt should be gated with a zero depth status. Also, update doc to say that zero is reserved.
Problem 2: At construction, considered a depth register, but aim was to limit extra registers if possible (area, testing,etc). But there is no doubt it may be useful in both operation and debug modes. Also, other surrounding logic has now changed that added this register is now required when it was not before. Adding a depth reg.
