### ISSUE TITLE
[bazel] add support for building closed source test hooks

### ISSUE THREAD

**Issue by MaayanKashani** [lowRISC/opentitan#11133]
After the accomplishment of closed source IPs integration into chip-level testing using Meson (see #11188), we will need to support this solution in Bazel as well. Please refer to issue #10852 and relevant Meson PR #11188.

**Comment by msfschaffner** [comment]
Please feel free to re-label and re-assign if this does seem correct.

**Comment by timothytrippel** [comment]
@MaayanKashani #12631, should resolve this issue. @cfrantz  was kind enough to provide an example setup in the aforementioned PR that was extensively commented too. Lmk if you have any issues!
