### ISSUE TITLE
[sw/silicon_creator] Consider adding `sec_mmio_write32_untracked()`

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#11146]
[context](https://github.com/lowRISC/opentitan/pull/11015#discussion_r814129107)

This function would be basically `sec_mmio_write32()` without the `upsert_register()` call, to be used in places where we want to perform a write-read-comparison but don't want to track the last written value, e.g. flash_ctrl ADDR and CONTROL registers. The latter would also require a mask parameter since the HW updates the START bit.

**Comment by msfschaffner** [comment]
@arunthomas

**Comment by msfschaffner** [comment]
@moidx @timothytrippel @cfrantz

**Comment by timothytrippel** [comment]
I think this might make using these functions more complex to reason about if there are special call we need to look out for. Closing for now, we can revisit later if needed.
