### ISSUE TITLE
[rtl/rstmgr] Capture all resets

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#11143]
The rstmgr logic excludes capture in reset_info, alert_info, and cpu_info until the CPU has completed its reset and notified rstmgr via its rst_cpu_n input.

I suppose the intention was to block recording from the time of POR till the cpu is active... but I don't see a strong reason for that, and it may block diagnosing weird issues during reboot.

**Comment by tjaychen** [comment]
i think you are right. I wonder how the code was different before and this was necessary... maybe I didn't have `pwr_i.reset_cause` fully fleshed out. 

If I remove `first_reset`, I also end up removing the cpu reset input, that's what we're getting at right? :)

**Comment by matutem** [comment]
Yes, you would also remove the rst_cpu_n input.
