### ISSUE TITLE
[topgen] Need to automatically generate SW mappings from indices to signal names

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#1115]
For parametric modules such as the PLIC, pinmux, padctrl and alert_handler, topgen should generate headers with a SW mapping from signal names to indices such that firmware can appropriately initialize these modules.

There has been initial work on this for the pinmux by @eunchan in order to provide a default mapping at startup, but this should be extended.

**Comment by lenary** [comment]
I've looked at this for PLIC, and I know I need to extend that code for the other instantiated peripherals, but I haven't had time to get to it yet.

**Comment by lenary** [comment]
@silvestrst can you keep this on your radar?

**Comment by msfschaffner** [comment]
The pinmux constants should be available now, and auto-generated documentation tables for this are available [here](https://docs.opentitan.org/hw/ip/pinmux/doc/index.html#pinout-and-pinmux-mapping).

I am not 100% sure whether the pwrmgr resets to ids constants have been added tough... @tjaychen @matutem do you mind giving this a quick look? If that has been addressed as well we can probably close down this issue.

**Comment by moidx** [comment]
CC: @mundaym

**Comment by tjaychen** [comment]
no i dont think this has been added.
At least I didn't add it.  I'll look into it.

**Comment by tjaychen** [comment]
the pwrmgr reset mapping ID was added some time ago, finally closing this issue.
