### ISSUE TITLE
[aes] trigger.start - stays until it can be executed

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#11166]
Currently in manual - if the trigger.start is set to 1 without providing a valid configuration
the trigger will stay until a valid configuration has been provided and then start.

Another example is if in auto mode - and the trigger.start register is set 
the start will be ignored. but if then the mode is changed from auto to manual the start will trigger an operation with the current key/IV and mode.
even before any of these has been updated.

I think this behavior is counter-intuitive, I presume that users expect to be able to provide a configuration then asserting start before something happens. 

I suggest we change the design to clear trigger.start if the start cannot be executed due to an invalid configuration.

it is ok that the start is delayed in the case of a reseed or if new data is provided (on input_ready and then triggered immediately after)

if needed we could add a status register that indicate that start was cleared do to invalid configuration - but personally I don't think this is required

**Comment by vogelpi** [comment]
Thanks for filing the issue @rasmus-madsen . I completely agree that this behavior is counter intuitive and that the design should be changed to clear the trigger if it cannot be executed. I've filed a PR here #11254.
