### ISSUE TITLE
[dv/rstmgr] Check recording of multiple resets

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#11161]
Send multiple resets for each rst_cpu_n active cycle to check all are recorded.

**Comment by msfschaffner** [comment]
@matutem is this still pending?

**Comment by matutem** [comment]
I think it is still pending. Feel free to increase the priority if needed.

**Comment by msfschaffner** [comment]
Ack, will do.

**Comment by matutem** [comment]
Note only hardware resets and software reset can occur simultaneously, since pwrmgr will not mix those with a low power exit reset, and POR supersedes either of them.

Hardware resets are simply expressed as a bit vector to rstmgr, so the test makes the various bits arrive at different times while rst_lc_req is active. A sw reset can also cause rst_lc_req to rise, and rstmgr itself completes the processing.
