### ISSUE TITLE
Opantitan AES-128 clock cycles 

### ISSUE THREAD

**Issue by zliu1Charlotte** [lowRISC/opentitan#11185]
Hi,
I wonder why there are 12 cycles in the LUT AES-128, ~1 cycle per round. 
How are these 12 clock cycles distributed when there is only 10 rounds/cycles for AES-128 encryption? 
For DOM masked AES-128, it has 56 cycles, ~5 cycles per round. 
How How are these 56 clock cycles distributed when there is only 10x5 cycles for AES-128 encryption? 
Thanks for elaborating this more.

**Comment by rswarbrick** [comment]
@vogelpi, who knows the most about the AES design.

**Comment by vogelpi** [comment]
Hi @zliu1Charlotte ,
the exact cycle counts are related to our cipher core architecture. In both cases (unmasked and DOM) the first cycle is used to load the input data and initial key into the internal registers (please refer to the [block diagram](https://docs.opentitan.org/hw/ip/aes/doc/#block-diagram) and the [detailed description, Step 4](https://docs.opentitan.org/hw/ip/aes/doc/#datapath-architecture-and-operation)). In the second clock cycle the initial round is executed which consists of adding the initial key to the state. Then follow the 10 regular rounds. So we have 1 (loading) + 1 (initial round) + 10*1 (regular rounds) = 12 clock cycles.

When using DOM, the first cycle is the same: we just load the input data and initial key. The rounds themselves now all take 5 clock cycles, so it's 1 (loading) + 5 (initial round) + 10*5 (regular rounds) = 56 clock cycles. Note that adding the initial key to the state itself can be done in a single clock cycle. The reason for the initial round to still take 5 clock cycles is that in every round, the key expand module generates the round key for the next round. And this also takes DOM S-Boxes with a latency of 5 clock cycles. One exemption is AES-256 which has two round keys available right from the start. In this case the execution with DOM takes 1 (loading) + 1 (initial round) + 14*5 (regular rounds) = 72 clock cycles.

**Comment by msfschaffner** [comment]
Closing this for now. Please reopen if the question has not been fully addressed.
