### ISSUE TITLE
[bazel] cleanup bazel transition to host platform in `sign_bin` rule 

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#11199]
PR #11136 and #10864 restructured OpenTitan bazel rules to build and sign test images for flash. Part of this introduced a bazel transition from the `OPENTITAN_PLATFORM` config to the host platform config, in order to build the ROM_EXT signer tool, which is a dependency of the `sign_bin` rule. We should investigate other ways to enforce this configuration requirement, perhaps using the [`exec_compatible_with`](https://docs.bazel.build/versions/main/be/common-definitions.html) attribute.

CC: @cfrantz

**Comment by timothytrippel** [comment]
Do you have the PR that closed this issue? Because, it looks like this should not be closed yet: https://github.com/lowRISC/opentitan/blob/81513e9ce92dfad11f374481f15a7db3659126ca/rules/opentitan.bzl#L118

**Comment by drewmacrae** [comment]
I was wrong

**Comment by pamaury** [comment]
I just noticed this in the code, cannot this be solved in the standard way using `cfg` on the label?
```diff
diff --git a/rules/signing.bzl b/rules/signing.bzl
index 4900d829f..a6dd8b623 100644
--- a/rules/signing.bzl
+++ b/rules/signing.bzl
@@ -385,12 +385,10 @@ sign_bin = rv_rule(
             doc = "SPX public key to validate this image",
         ),
         "manifest": attr.label(allow_single_file = True, mandatory = True),
-        # TODO(lowRISC/opentitan:#11199): explore other options to side-step the
-        # need for this transition, in order to build the ROM_EXT signer tool.
-        "platform": attr.string(default = "@local_config_platform//:host"),
         "_tool": attr.label(
             default = "//sw/host/opentitantool:opentitantool",
             allow_single_file = True,
+            executable = True,
+            cfg = "exec",
         ),
     },
 )
```
I added an `executable = True`  as recommended in https://bazel.build/rules/lib/toplevel/attr#label. In fact when set, bazel requires the cfg attributes to guard against errors such as build tools with the target toolchain.

**Comment by msfschaffner** [comment]
Can this issue be closed?

**Comment by timothytrippel** [comment]
We can close this b/c with the new rules, this won't be a problem anymore.
