### ISSUE TITLE
[doc] Hugo printable format

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#1123]
For all the documents in Hugo, if I try to print them or save as PDF, there are weird line break and "skip to main content" signs. 
Anybody has any idea on how to get a better printable doc?

**Comment by imphil** [comment]
This is something can can be fixed in CSS. 

@gkelly can you fix that? Otherwise let me know and I'll have a look.

**Comment by gkelly** [comment]
> This is something can can be fixed in CSS.
> 
> @gkelly can you fix that? Otherwise let me know and I'll have a look.

Can do, I know where that's coming from.

**Comment by sjgitty** [comment]
I believe there are other print artifacts that are odd that @cindychip and I noticed. So there might be more coming. One other she noticed had to do with clipped table widths, for instance in the HMAC dv plan `https://docs.opentitan.org/hw/ip/hmac/doc/dv_plan/`. @cindychip can you file a new issue for the ones you notice?

**Comment by cindychip** [comment]
Thanks for the reminder Scott, filed an issue with some other DV minor issues #1133 .
