### ISSUE TITLE
[dv] VCS option -xprop=mmsopt doesn't work in some tests

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#11245]
This error occurs in some tests. It's fine when `-xprop=mmsopt` is removed

> Assertion failed "0" at line 815 in file assignmentpattern.cc
> 
> An unexpected termination has occurred in /workspace/default/simv due to an assertion failure in the tool
> Hostname smart-432347cc-0134-4cb8-93bf-57433b908794
> 
> 
> Command line: /workspace/default/simv +sw_test_timeout_ns=8000000 +sw_build_bin_dir=/workspace/build-bin +sw_build_device=sim_dv +sw_images=sw/device/tests/pwrmgr_smoketest:1,sw/device/lib/testing/test_rom/test_rom:0 +UVM_NO_RELNOTES +UVM_VERBOSITY=UVM_LOW -licqueue -ucli -do /workspace/mnt/repo_top/hw/dv/tools/sim.tcl +ntb_random_seed=1 -assert nopostproc +UVM_TESTNAME=chip_base_test +UVM_TEST_SEQ=chip_sw_base_vseq
> 
> --- Stack trace follows:
> 
> Dumping VCS Annotated Stack:
> #\ 0  0x000015553c196a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
> #\ 1  0x000015552dac7953 in ndpBIMTBuf_list_dequeue_all.constprop.0 () from /workspace/mnt/verdi/share/PLI/lib/LINUXAMD64/libsscore_vcs202109.so
> #\ 2  0x000015552dac8d38 in ndpBIMT_ConsumerMain () from /workspace/mnt/verdi/share/PLI/lib/LINUXAMD64/libsscore_vcs202109.so
> #\ 3  0x000015553c192ea5 in start_thread () from /lib64/libpthread.so.0
> #\ 4  0x000015553b8b1b0d in clone () from /lib64/libc.so.6
> #\ 0  0x000015553c196a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
> #\ 1  0x000015553cab946f in SNPSle_95c894712e6f9118bc51d0bbc485432a () from /workspace/mnt/vcs/linux64/lib/libuclinative.so
> #\ 2  0x000015553cab9696 in SNPSle_de8e8fbcd7ecf84c9ae14573df0a2ec6 () from /workspace/mnt/vcs/linux64/lib/libuclinative.so
> #\ 3  0x000015553cb69aac in SNPSle_57415c5b07ec5e8b8118f96e6212a2c42c69fd3f49376c0d () from /workspace/mnt/vcs/linux64/lib/libuclinative.so
> #\ 4  0x000015553cb6e8c7 in SNPSle_1ac40924fdff8310f5184d6eb67c5798036a89169a27d790 () from /workspace/mnt/vcs/linux64/lib/libuclinative.so
> #\ 5  0x000015553cb706ff in SNPSle_a00aeeb47fd325df3eff4946e57739a1 () from /workspace/mnt/vcs/linux64/lib/libuclinative.so
> #\ 6  0x000015553cb70e67 in SNPSle_8aaad5c586c7296aafc380368752bb09 () from /workspace/mnt/vcs/linux64/lib/libuclinative.so
> #\ 7  0x000015553cb70e87 in SNPSle_8aaad5c586c7296a () from /workspace/mnt/vcs/linux64/lib/libuclinative.so
> #\ 8  0x000015553cabac5b in SNPSle_94a979f2a5637ee494a8dd1225b7e6c6 () from /workspace/mnt/vcs/linux64/lib/libuclinative.so
> #\ 9  0x000015553c192ea5 in start_thread () from /lib64/libpthread.so.0
> #\ 10 0x000015553b8b1b0d in clone () from /lib64/libc.so.6
> #\ 0  0x000015553b878659 in waitpid () from /lib64/libc.so.6
> #\ 1  0x000015553b7f5f62 in do_system () from /lib64/libc.so.6
> #\ 2  0x000015553b7f6311 in system () from /lib64/libc.so.6
> #\ 3  0x0000155545276fec in SNPSle_10ee25eff68cd8461c9146fa1d0b35e87067f3c8015b313e639d2928478c79b3f673f99203bcf8be64600612100082236bffb2007f1e0ef9 () from /workspace/mnt/vcs/linux64/lib/liberrorinf.so
> #\ 4  0x00001555452789e8 in SNPSle_10ee25eff68cd8461c9146fa1d0b35e87067f3c8015b313efba706aab251478fa49e66610e453774633a6c152e7ef778f2202cda681f3d4e () from /workspace/mnt/vcs/linux64/lib/liberrorinf.so
> #\ 5  0x0000155545270822 in SNPSle_d35ca1ff70d465c2b9b1a72eee90a50630165806651fae96c1bbda5b5d02066c () from /workspace/mnt/vcs/linux64/lib/liberrorinf.so
> #\ 6  0x0000155545270ee8 in SNPSle_b99eb917516be923fc05e2a3c06e04c8 () from /workspace/mnt/vcs/linux64/lib/liberrorinf.so
> #\ 7  0x0000155545270f84 in SNPSle_b99eb917516be9239434618208845a0ee01bf61ea4fd0e30 () from /workspace/mnt/vcs/linux64/lib/liberrorinf.so
> #\ 8  0x0000155542b69af5 in SNPSle_68a2920116cfe3675277508869bbf41d1e7e823570a4e024165e204bdeb1fb5b7e682ccf8a2e834994f1a3fc9ef1ce1a680b302dddeae9efc8cd2d50cf57d6d1b3ad16d6982c91d1 () from /workspace/mnt/vcs/linux64/lib/libvcsnew.so
> #\ 9  0x0000155542b6d16c in SNPSle_68a2920116cfe3675277508869bbf41d1e7e823570a4e02444e7583aa80903e89f5ecf4e1af2a132b6cd797406c2196c83b17ac813888baf020ea3a5bdda8c9ff810f9d33b74ace5 () from /workspace/mnt/vcs/linux64/lib/libvcsnew.so
> #\ 10 0x0000155542b6d0fb in SNPSle_68a2920116cfe3675277508869bbf41d1e7e823570a4e02444e7583aa80903e89f5ecf4e1af2a132b6cd797406c2196c83b17ac813888baf020ea3a5bdda8c9ff810f9d33b74ace5 () from /workspace/mnt/vcs/linux64/lib/libvcsnew.so
> #\ 11 0x0000155542b6d91d in SNPSle_68a2920116cfe3675277508869bbf41d1e7e823570a4e0247b3eb0fd170a9b5a83b610e005dde3eee35987accc43897e69620faf47120bc2 () from /workspace/mnt/vcs/linux64/lib/libvcsnew.so
> #\ 12 0x0000155542b6db4b in SNPSle_217b54a4fd79459801d29acbc1c64a4019c148b895e6cf94 () from /workspace/mnt/vcs/linux64/lib/libvcsnew.so
> #\ 13 0x000015554ee5f73c in N_VCSgd_IzxFE () from /workspace/mnt/input/default/simv.daidir/_2324_archive_1.so
> #\ 14 0x000015554ee5f14d in N_VCSgd_IzxFE () from /workspace/mnt/input/default/simv.daidir/_2324_archive_1.so
> #\ 15 0x0000155540a64eb5 in SNPSle_63c7abb936d47b0787bcc066faceb6081f288c247f8a3aba () from /workspace/mnt/vcs/linux64/lib/libvcsnew.so
> #\ 16 0x0000155540bffc5f in SNPSle_490598bfebcc8e81efcf3d1815066cc9 () from /workspace/mnt/vcs/linux64/lib/libvcsnew.so
> #\ 17 0x0000155540c19405 in SNPSle_490598bfebcc8e81 () from /workspace/mnt/vcs/linux64/lib/libvcsnew.so
> #\ 18 0x0000000000480217 in main ()
> 
> Process VmPeak: 1050528 kb, VmSize: 1050524 kb
> System Free Memory: 204370004 kb, System Free Swap: 0 kb
Edit: backslack after #\ has been inserted to avoid linking to many existing unrelated GitHub issues.

Thanks @tjaychen for finding this issue and the root cause.

**Comment by weicaiyang** [comment]
To reproduce this case, get the PR https://github.com/lowRISC/opentitan/pull/11154 and use this command:
> ./util/dvsim/dvsim.py -t vcs hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_pwrmgr_smoketest -s 1  -r 1

**Comment by msfschaffner** [comment]
The fix has been merged - but we are keeping the bug open to track any related tool fixes.

**Comment by weicaiyang** [comment]
> The fix has been merged - but we are keeping the bug open to track any related tool fixes.
> 
> We may want to revisit this issue once newer tools versions are available.

Already ping Synopsys AE to look at this issue. Will keep this posted if I receive any update from them.

**Comment by weicaiyang** [comment]
Update: Synopsys AE can reproduce this issue and created an issue (STAR 4148879) on their side.

**Comment by weicaiyang** [comment]
Fixed at version S-2021.09-SP2-1, which will be released later this month

**Comment by weicaiyang** [comment]
already fixed
