### ISSUE TITLE
[adc_ctrl] ADC_CTRL does not signal power down to ADC in low power mode

### ISSUE THREAD

**Issue by NigelScales** [lowRISC/opentitan#11256]
ADC_CTRL does not signal power down to ADC in low power mode.
The adc_o.pd port doesn't reflect the low power states of the state machine.

To reproduce:
```
gh pr co 11034
./util/dvsim/dvsim.py hw/ip/adc_ctrl/dv/adc_ctrl_sim_cfg.hjson -i adc_ctrl_lowpower_counter --fixed-seed 1 --tool vcs  --waves --run-opts "+max_quit_count=3"
```
![image](https://user-images.githubusercontent.com/78102677/156793352-11fc3530-33a3-4f70-8ed4-3c0b571eb3e7.png)

**Comment by tjaychen** [comment]
great catch, let me have a look.
