### ISSUE TITLE
[dv] RISC-V build error

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#1127]
@imphil 
Will Chen (from Synopsys) met below error when running top-level simulation.
I don't see this error from my side but their OS isn't the same as ours.
Do you know how to solve this problem? Thanks
> 
> /opt/riscv/bin/riscv32-unknown-elf-gcc -march=rv32imc -mabi=ilp32 -static -mcmodel=medany -Wall -g -Os -fvisibility=hidden -nostdlib -nostartfiles  -DDV_SIM -MMD -c -I/global/gtsna_corpac_prj/gtsna_corpac_prj2/haihui/opentitan.cloned_1106_2019/opentitan/sw/device/../vendor -I/global/gtsna_corpac_prj/gtsna_corpac_prj2/haihui/opentitan.cloned_1106_2019/opentitan/sw/device/../device/exts/common -I/global/gtsna_corpac_prj/gtsna_corpac_prj2/haihui/opentitan.cloned_1106_2019/opentitan/sw/device/../device/lib -I/global/gtsna_corpac_prj/gtsna_corpac_prj2/haihui/opentitan.cloned_1106_2019/opentitan -I/global/gtsna_corpac_prj/gtsna_corpac_prj2/haihui/opentitan.cloned_1106_2019/opentitan/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/12.02.19_17.12.59/sw_build/rom -I/global/gtsna_corpac_prj/gtsna_corpac_prj2/haihui/opentitan.cloned_1106_2019/opentitan/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/12.02.19_17.12.59/sw_build/rom/lib -o /global/gtsna_corpac_prj/gtsna_corpac_prj2/haihui/opentitan.cloned_1106_2019/opentitan/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/12.02.19_17.12.59/sw_build/rom/crt0.o boot_rom/crt0.S
> 
> /opt/riscv/bin/riscv32-unknown-elf-gcc -march=rv32imc -mabi=ilp32 -static -mcmodel=medany -Wall -g -Os -fvisibility=hidden -nostdlib -nostartfiles  -DDV_SIM -T boot_rom/rom_link.ld /global/gtsna_corpac_prj/gtsna_corpac_prj2/haihui/opentitan.cloned_1106_2019/opentitan/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/12.02.19_17.12.59/sw_build/rom/bootstrap.o /global/gtsna_corpac_prj/gtsna_corpac_prj2/haihui/opentitan.cloned_1106_2019/opentitan/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/12.02.19_17.12.59/sw_build/rom/boot_rom.o /global/gtsna_corpac_prj/gtsna_corpac_prj2/haihui/opentitan.cloned_1106_2019/opentitan/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/12.02.19_17.12.59/sw_build/rom/hw_sha256.o /global/gtsna_corpac_prj/gtsna_corpac_prj2/haihui/opentitan.cloned_1106_2019/opentitan/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/12.02.19_17.12.59/sw_build/rom/crt0.o -L/global/gtsna_corpac_prj/gtsna_corpac_prj2/haihui/opentitan.cloned_1106_2019/opentitan/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/12.02.19_17.12.59/sw_build/rom/lib -lot -Xlinker -Map=/global/gtsna_corpac_prj/gtsna_corpac_prj2/haihui/opentitan.cloned_1106_2019/opentitan/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/12.02.19_17.12.59/sw_build/rom/rom.map -Wl,--build-id=none -o /global/gtsna_corpac_prj/gtsna_corpac_prj2/haihui/opentitan.cloned_1106_2019/opentitan/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/12.02.19_17.12.59/sw_build/rom/rom.elf
> 
> /opt/riscv/lib/gcc/riscv32-unknown-elf/9.2.0/../../../../riscv32-unknown-elf/bin/ld: **/opt/riscv/lib/gcc/riscv32-unknown-elf/9.2.0/libgcc.a(_divdi3.o): can't link double-float modules with soft-float modules**
> 
> /opt/riscv/lib/gcc/riscv32-unknown-elf/9.2.0/../../../../riscv32-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/lib/gcc/riscv32-unknown-elf/9.2.0/libgcc.a(_divdi3.o)

**Comment by towoe** [comment]
My first idea would be to check the toolchain as the error message shows that a double-float `_divdi3.o` is used while linking and soft-float is the one needed.
Best option would be to try install and use https://github.com/lowRISC/lowrisc-toolchains/releases/tag/20191101-1

**Comment by imphil** [comment]
Yes, this looks like a toolchain issue (mixing a toolchain built with double-precision hardfloat support (D) with software built with softfloat). Please install the pre-built toolchain that we're providing, you can find instructions at https://docs.opentitan.org/doc/ug/install_instructions/#device-compiler-toolchain-rv32imc, which boils down to a single command:

```sh
cd $REPO_TOP
./util/get-toolchain.py
```

If you still have problems after that, please
1. Run `riscv32-unknown-elf-gcc --version` and let me know the output.
2. Run `riscv32-unknown-elf-readelf -h /global/gtsna_corpac_prj/gtsna_corpac_prj2/haihui/opentitan.cloned_1106_2019/opentitan/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/12.02.19_17.12.59/sw_build/rom/rom.elf` and paste the output here.
3. Record the whole compilation log and attach it to this bug report.
```

**Comment by snpsverif** [comment]
Downloading and untarring the pre-built one works. Thanks for the detailed instructions.

**Comment by weicaiyang** [comment]
Thanks @towoe and @imphil It's solved.
