### ISSUE TITLE
[util] make_distribution.sh CI dependency for hw

### ISSUE THREAD

**Issue by towoe** [lowRISC/opentitan#1128]
`util/make_distribution.sh` depends on "binary" output files to be available in `build-bin`.
In the CI flow the hw files are copied "manually" to the location so they are later available, but for a local build this is not automated.

For build artifacts the discussion started in #650 and for intermediate hw artifacts this is specified in #995
For sw meson takes care of intermediate and binary outputs with #978 and #1045 

Should FuseSoC take care of moving the files? Not sure if this is even possible right now.

As can be seen by the referenced issues/PRs and by @imphil proposal there is already discussion for organizing the output folders.
This issue mainly addresses the problem that the script in `util` does not work as the required files are only moved to the correct location in the CI flow.

**Comment by imphil** [comment]
Fusesoc can do that (as a post-build script). It's not clear, however, if that's the path we want to take, or if fusesoc will be called through meson instead, and then meson takes over that part.

@mcy can you outline your plans there, and a rough ETA? (Depending on that, we might want to look into intermediate solutions.)

**Comment by msfschaffner** [comment]
Is this still relevant?

**Comment by msfschaffner** [comment]
@timothytrippel @cfrantz how relevant is this issue still?
