### ISSUE TITLE
[rv_core_ibex, security] ICache ECC errors and cache memory initialization

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#11291]
I've just implemented a minor alert from Ibex if the ICache encounters an ECC error and ran into an issue.

We instantly hit a minor alert when we enable the ICache, this is due to two reasons

1. We only initialise the tag ram (so it's all invalid tags with valid ECC) at reset
2. We mux data ram read data based upon hit/miss and then do our ECC check on the way we hit on

So when we do our first access it obviously misses, which triggers an ECC error due to 2 and even if we ECCed across all data we read we'd still see an ECC error due to 1

Previously this hasn't been an issue as the action on ECC is to just invalidate the line (which is already invalid). I think it'll end up generating some pointless write cycles to data/tag RAM after reset until we've filled up the ICache. This is odd behaviour but not disastrous.

Though if we have an alert hooked up to the ECC error we need to choose a more sensible behaviour. I can see two possibilities

1. Do ECC checking across the whole of the data RAM read data, indicate an ECC error (resulting in alert and cache line invalidation) regardless of hit. This will require initialising the data RAM to all 0s or other fixed value with correct ECC after reset (which we already have to do with tags and it would be done in parallel)
2. Only care about ECC errors when we have a cache hit
3. A half-way house, indicate ECC error if we see any in the tag RAM regardless of hit and only check data ECC if we hit.

I'm tempted by 3. We want to catch scenarios where an attacker faults a valid tag to an invalid tag (so only check if we see hit is a bad idea). However if an attacker faults data RAM and the matching tag is invalid there's no change to the microarchitectural behaviour.

I'm not sure what 1. gives us above 3 other than maybe being slightly simpler.

@tjaychen @msfschaffner @moidx @cdgori thoughts?

**Comment by rswarbrick** [comment]
I'm obviously missing something but... can't we just squash ECC failures in the data ram on a cache miss?

**Comment by GregAC** [comment]
Yes, that's option 3

**Comment by msfschaffner** [comment]
So in general I would say we sould check whenever we know that data or tags are valid. Hence I am inclined to go with option 3 as well.

**Comment by tjaychen** [comment]
What happens if the tag ram is valid, but it's still a cache miss?

In that scenario, if the data ram contents have actually faulted, wouldn't we still want to generate an alert? Otherwise it's kind of like bad data just sitting in the data ram.

**Comment by msfschaffner** [comment]
I guess that depends on whether data readout is predicated on the access being a hit or not. if we read data unconditionally and select/forward it later in the pipeline, we could always check it (if it is valid).

**Comment by tjaychen** [comment]
yeah my assumption was that the tag and data are read around the same time for the look-up case. 
Just double checked the ibex code, it "looks" like that? But I could be wrong.

**Comment by GregAC** [comment]
> What happens if the tag ram is valid, but it's still a cache miss?

If tags have the valid bit set but none of them match the lookup address then whilst we've done a data RAM read we just totally ignore its results.

>  Otherwise it's kind of like bad data just sitting in the data ram.

This is true but when we actually attempt to use that data we'll see fault.

It would be possible to do an ECC check on data where the tag is valid regardless of hit/miss.

**Comment by tjaychen** [comment]
i think it is a LITTLE better to check the data ram correctness whenever tag ram is valid.
However, I do not think the gains are big enough that you should go out of your way to do that. 
So my suggestion is to go with 3, and make the checks on valid instead of hit if it is convenient.

**Comment by rswarbrick** [comment]
The only awkward bit here is that the ways get OR'd together, after ANDing with the "hit" bits. So you can do ECC checks for the way that hits with a single decoder. To do ECC checks for each valid way, each would need a decoder.

**Comment by GregAC** [comment]
I've merged the version that implements 3. and have a PR to vendor that across to OpenTItan here: https://github.com/lowRISC/opentitan/pull/11330

Happy to switch to ECC checks in parallel across all data ways but as @rswarbrick it is a little bit of extra work so if we cannot think of a good reason 3. won't suffice I'd be keen to go for that so we can get D2S closed.

**Comment by tjaychen** [comment]
ah thanks for clarifying. 
Shall we close this issue now?

**Comment by cdgori** [comment]
Late to the discussion but option 3 looks quite reasonable to me.

I'd be preferential to @tjaychen 's idea of checking data-ECC for any valid tag, BUT if it means adding all those parallel-ECC checks it seems a little wasteful, given @GregAC 's comment that we would ultimately do the ECC check IF the data were to hit/be-consumed at a later point.

For me, it comes down to if we think the "distributed fault detector" of the parallel ECCs is beneficial for the area it adds.  We'll get slightly more fault-detection coverage by having them (so we should in theory learn about injected faults sooner, even if they aren't successfully faulting instructions we are consuming at the moment), but in any case we would detect such a fault were it to end up on the execution path.  Feels pretty marginal in terms of cost-benefit (in absolute benefit, it's for-sure more secure though).

Since you've already coded it up, I'd stick with what you have for 3 presently (ECC check on hit & valid) and maybe leave an enhancement for ECC check on any valid (Tim's suggestion), depending on sample evaluations.
