### ISSUE TITLE
Snapshot release cycle

### ISSUE THREAD

**Issue by towoe** [lowRISC/opentitan#1130]
I was in the process of updating some documentation when I realized this (`quickstart.md`) is based on a snapshot. `getting_started_verilator.md` on the other hand should reflect the current state of the repo. So these documents might contain different instructions, which could be confusing.

Do we have a plan of how frequently the snapshot should be released? Or is this more on the basis of a need.

**Comment by imphil** [comment]
Good that you bring that up. A regular snapshot release is something we should aim for; given that it is a snapshot release, ~1 a month sounds like a good cadence. We should however make sure that we can release such a release with minimal or no manual work/testing.

**Comment by towoe** [comment]
Once a month sounds like a reasonable suggestion.
The release creation should be automated by adding a tag.
One part which should be updated with this is `doc/ug/quickstart.md`.
Other than that the only manual task would be to test the release? Or do I miss something @imphil?

**Comment by asb** [comment]
A snapshot release does have some advantages, but I think it might be worth considering instead beefing up testing of bitstreams in CI, and pointing people to artifacts from master instead.

**Comment by towoe** [comment]
Actually I was not aware of the artifacts until Philipp pointed that out to me.
So making this more obvious would indeed help.
But I also think it makes sense to keep the `quickstart.md` together with the release reasonably up to date in order to minimize the difference to the development progress.

**Comment by towoe** [comment]
Closing in favor of #1928 as it seems like we do the snapshot if it is needed. Please reopen if there is still a need to discuss a more structured approach to release cycles.
