### ISSUE TITLE
[ast,clkmgr] The aon clock slows down with extclk

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#11301]
When clkmgr's extclk_ctrl.sel is True and extclk_ctrl.hi_speed_sel is True the aon clock frequency is reduced to about 100 kHz. This is unexpected. Keeping sel True and setting hi_speed_sel to False brings the aon clock frequency to its nominal value.

A side-effect of this is that when the clkmgr is programmed with extclk and high speed select enabled the io_div2 and io_div4 measurement modules (prim_clock_meas) hit the MaxWidth_A assertion.

**Comment by matutem** [comment]
Assigned to @tjaychen, but please reassign as needed.

**Comment by matutem** [comment]
Here are some waves: 
![image](https://user-images.githubusercontent.com/80294896/157146920-72d6d353-b407-49b3-a2ed-c8dee2562730.png)

**Comment by tjaychen** [comment]
@matutem thanks!
do you know what's the external clock frequency in this test? I can't see it from the waves.

**Comment by matutem** [comment]
Should be 100 MHz. Tim, https://github.com/lowRISC/opentitan/pull/11327 was rebased and is ready for review.

**Comment by tjaychen** [comment]
Related to #11561, closing this one for now.
