### ISSUE TITLE
[doc] Proper rendering of HTML escape sequences

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#11313]
When rendering hjson files ([particularly for the testplan, case in point]( https://github.com/lowRISC/opentitan/blob/master/hw/ip/entropy_src/data/entropy_src_testplan.hjson)) there is no way to create a '>' symbol in the descriptions.   Using a literal `>` or an html escape `&gt;` both get rendered as `&amp;gt;`, and thus appear as `&gt;` in the rendered documentation.   It seems that both Hugo and the preprocessor documentation are taking it upon themselves to perform escape sequence substitution.

**Comment by johngt** [comment]
@HU90m for reference, however I think this issue is now obsolete.
If still relevant please re-open this.
