### ISSUE TITLE
[pwm/dv] Testplan includes TBD for clock_domain test case.

### ISSUE THREAD

**Issue by jason-hoddinett** [lowRISC/opentitan#11310]
Requires clarification/completion in the testplan in order to proceed with sequence creation.

**Comment by martin-lueker** [comment]
Thanks for bringing this up.
@weicaiyang, @cindychip, @sriyerg: Can you recommend what should happen for this?   What is being done for similar blocks?

**Comment by weicaiyang** [comment]
IIUC, there are 2 clocks in PWM. The clk_i is for register access and the clk_core_i is for core functionality. After register program is done, we can turn off the clk_i (which means we enter low power mode) and PWM can still generate output. We did this in other blocks as well.
@martin-lueker does this sound a right sequence to test this?

**Comment by tjaychen** [comment]
btw, just to add one thing. Once the software configuration is done, we need to make sure (and this is true of other blocks) that `clk_i` can disappear / reappear at effectively random times and the core logic needs to behave correctly.

Once the wakeup requests are asserted, the `clk_i` must resume, but until that happens, everything should work as expected.

**Comment by martin-lueker** [comment]
That is correct Weicai. That sounds like a good test.  Note:This also doesn't need to be a dedicated test sequence. The main test vsequence can randomly enable/disable `clk_i` during testing to satisfy this test point. (We don't need to have explicit vseqs for every test point).

**Comment by weicaiyang** [comment]
Agree. We don't need to write a new test. 
It's a good idea to randomly enable/disable `clk_i` in the main sequence.

**Comment by jason-hoddinett** [comment]
This behaviour is also duplicated for the testpoint pwm_lowpower, I will remove the duplicate and implement this behaviour. Thank you for the clarification.

**Comment by martin-lueker** [comment]
Sounds good.  Thank you @jason-hoddinett
