### ISSUE TITLE
[flash_ctrl] Clarification Of Software Control of Flash Code Fetch

### ISSUE THREAD

**Issue by TimEwins** [lowRISC/opentitan#11333]
The Specification indicates ……

----------------------------------------------------------------------------------------------------------------------------------
Software control of flash code fetch.

Flash Code Execution Handling

Flash can be used to store both data and code. To support separate access priviledges between
data and code, the flash protocol controller provides EXEC for software control.

If software programs EXEC to 0xa26a38f7, code fetch from flash is allowed. If software programs
EXEC to any other value, code fetch from flash results in an error.

The flash protocol controller distinguishes code / data transactions through the instruction
type attribute of the TL-UL interface.

FLASH_CTRL.EXEC @ 0x14
Controls whether flash can be used for code execution fetches
Bits	Type	Reset	Name	Description
31:0	rw	0x0	EN
A value of 0xa26a38f7 allows flash to be used for code execution. Any other value prevents code
execution.

SUMMARY
EXEC != 0xa26a38f7, Read Data (MuBi4False-Data) - Allowed, Read Data (MuBi4True-Code) - Denied
EXEC == 0xa26a38f7, Read Data (MuBi4False-Data) - Allowed, Read Data (MuBi4True-Code) - Allowed
----------------------------------------------------------------------------------------------------------------------------------

There are three TL Interfaces in the DUT, as I understand it, these are used for the following purposes

core_tl – Used to configure the Flash, Initialise, set up, erase, program, read 
mem_tl – Used by Host for Code and Data
prim_tl – Vendor Specific Interface – Not Tested Here

QUESTION 1
The Flash Code Execution Handling (FLASH_CTRL.EXEC) feature is therefore only applicable to Host reads using the mem_tl interface?

QUESTION 2
The Spec indicates that

“If software programs EXEC to 0xa26a38f7, code fetch from flash is allowed. If software programs
EXEC to any other value, code fetch from flash results in an error.”

What I have observed in testing so far, is that if a Code Fetch is disallowed, there appears to be no ‘error’ generated.  But what I do see is that the data that is returned under this scenario is ZERO.

Is this the expected behaviour?

At the moment my test is failing because the current Scoreboard is expecting a data match on read, and it is not getting one.

I will continue to investigate this and will post any updates that I have.

**Comment by TimEwins** [comment]
Ok .. I think I am mistaken about the missing error, the TL/UL interface has an error flag 'd_error', and in my simulation I see this going high when there is an error.  I was looking at the error status flags in the DUT, but it is built into TL/UL.

The problem here is that the TB does not handle this at the moment.

**Comment by tjaychen** [comment]
sounds good! looks like you got it!
hmmm.. .good point that there is no status flag inside the DUT, we could consider adding one.

**Comment by tjaychen** [comment]
@TimEwins is it okay to close this issue now? or is there anything still open from your end?

**Comment by TimEwins** [comment]
@tjaychen We can close this issue now

**Comment by TimEwins** [comment]
Closed
