### ISSUE TITLE
[rv_core_ibex] Bus errors on integrity check failure

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#11336]
Currently when Ibex sees an integrity check failure on incoming memory request responses it triggers a major alert but the core still accepts the data and will continue executing until the major alert causes some action.

The integrity check occur one cycle after the response is received. We could move it to the same cycle the response is received so it could generate an error response if the check fails. This seems like better behaviour. There's a chance it'll cause timing issues but I don't think it's a worry as the ECC error check is a handful of logic levels.

**Comment by rswarbrick** [comment]
I like this idea and think that it makes things much less mysterious. Otherwise, SW won't necessarily know if it has been given bogus data.

**Comment by tjaychen** [comment]
o good catch, what you're proposing to do is actually what I assumed was already done.
So this definitely sounds good to me.

**Comment by cdgori** [comment]
> o good catch, what you're proposing to do is actually what I assumed was already done. So this definitely sounds good to me.

Likewise, I assumed this was how it worked.  Good catch & thumbs-up on the change to same-cycle from me.

**Comment by msfschaffner** [comment]
Same comment as @cdgori and @tjaychen ;).

**Comment by GregAC** [comment]
I've opened an PR for this in Ibex: https://github.com/lowRISC/ibex/pull/1556

It also moves the ECC checks and generation into the core itself. This means it all gets replicated as part of the lockstep setup.

**Comment by GregAC** [comment]
The PR has been merged in Ibex and is vendored in here: https://github.com/lowRISC/opentitan/pull/11464

**Comment by GregAC** [comment]
Vendoring PR is merged

**Comment by tjaychen** [comment]
I think this change led to the timing issues @GregAC was worried about, see #11571 
The main culprit is that the data read path (from memory into ibex) now becomes part of the error timing. 
Coupled with the fact that load / store errors are precise, this leads to some pretty big negative slacks. 

I wonder if this was part of the reason this was handled differently to start with.  This is something we'll have to address in some way.

**Comment by vogelpi** [comment]
> I wonder if this was part of the reason this was handled differently to start with. This is something we'll have to address in some way. Maybe we could live with integrity errors being imprecise (perhaps jumping to an exception one cycle after the data is accepted).

Sorry for being late, but yes, this is exactly why Tom moved the ECC decoding into the shadow core/after the delay flops. Our thinking was that an integrity error on the bus is anyway fatal and that the core is not able to recover from that.

**Comment by GregAC** [comment]
> I'm not sure how best to implement something like that on the Ibex side though: it would be nice to avoid having too many OpenTitan-specific decisions baked into the core. Maybe some parameterised number of flops (default = 0; OpenTitan = 1) between LSU error and core error? @GregAC: Would something like that make sense?

Given the ECC is currently billed as a security feature (indeed for those wanting it for reliability/safety reasons they probably want correction which we don't do) and a feedthrough from data to a request out feels a bit weird (somehow seems better if it's only via control signals) I'm happy with just making it an imprecise exception on the Ibex side without configurability. I'd like to keep the number of possible configurations down and one which alters exception behaviour isn't great from a verification standpoint.

The easiest way to do this would be to wire it into the NMI as that's an existing, tested, feature. I guess we could expose a top-level `ecc_error_o` and leave it to users to wire that into NMI but I think we're better off doing it internally, in particular we can get mtval set to the address of the failed access and mcause set to something more useful than 'NMI'

**Comment by rswarbrick** [comment]
Sounds good to me!

**Comment by tjaychen** [comment]
yeah, making it an imprecise exception on ibex side sounds good to me as well.
Would you mind officially documenting the rationale somewhere in the ibex specification? That way we can ensure that we don't look at this in 6 months and think.."hey this looks weird", and end up going through this exercise again.

**Comment by rswarbrick** [comment]
@GregAC: I think this is all done now, right?

**Comment by GregAC** [comment]
Yes, this is implemented via the 'internal interrupt' concept.
