### ISSUE TITLE
[signoff] add security review to checklist for signoff

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/opentitan#1136]
In light of #367 we should add signoff checklist items for having reviewed code from a security-coding as well as security-testing perspective. WDYT, D2 and V2 items?

**Comment by aytong** [comment]
Agreed.  RTL code review for security should be a D2 item.  As for security testing, isn't that already part of the test plan?  But I do think there's benefit to explicitily call out security DV in verification checklist.  We probably should flesh out what "security testing" in more details, and capture them as a set of checklist items for V2, and some maybe V3 (e.g. glitch attack simulation).
@cdgori @tjaychen, your thoughts?

**Comment by vogelpi** [comment]
I agree that:
- These review items should be added to the checklists. Given that in D3/V3, only bug fixes and improvements for coverage should happen, adding them to D2/V2 seems.
- We should in more detail describe what security testing means.

On the design side, I think we also also add a couple of security-related items (D2) such as:
- SEC_CM_IMPLEMENTED: Countermeasures implemented.
- SEC_NON_RESET_FLOPS: Non-Reset flops should be used where appropriate and in consideration of all countermeasures.
- SEC_SHADOW_REGS: Shadow registers should be used where appropriate.

**Comment by msfschaffner** [comment]
We've addressed this by adding explicit security development and verification stages (D2S/V2S).
