### ISSUE TITLE
[bazel] keep the map files

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#11381]
Pending resolution of this issue https://github.com/bazelbuild/bazel/issues/6718 Bazel doesn't natively support preservation of .map files in sandboxed builds. There are useful for assessment of binaries after they're built for size and location in either automated or manual settings.

The linked issue mentions a hack that smuggles the map files out of the sandbox by renaming it,, which should work for our purposes, but reflects a bit of a compromise.

**Comment by msfschaffner** [comment]
@drewmacrae can you assign labels to an issue whenever you open up a new one (component, but also priority and milestones, if possible)? otherwise we have to go back and manually label many issues every week.

**Comment by drewmacrae** [comment]
> @drewmacrae can you assign labels to an issue whenever you open up a new one (component, but also priority and milestones, if possible)? otherwise we have to go back and manually label many issues every week.

Yep, sorry about that

**Comment by mcy** [comment]
Something I'd like to do (separately) is have cc rules emit .ll files when building with Clang. Being able to study the pre-LLVM output is helpful.
