### ISSUE TITLE
[rv_core_ibex] Consider implementing ECC check across all ways of data RAM in ICache

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#11403]
As described here: https://github.com/lowRISC/opentitan/issues/11291 checking the ECC from data RAM in the icache is only done when a hit is seen and then only on the way that was hit (tags are always checks across both ways regardless of hit/valid).

It would be possible to extend this check so each way with the data RAM is checked factoring in the tag valid so the pass/fail of the check is only consider if the tags indicate the failing way is valid.

**Comment by msfschaffner** [comment]
Beyond the fact that we would be checking words more often, I do not think this adds much value (it also might actually add to critical paths).

Suggesting to close this.

CC @GregAC @cdgori
