### ISSUE TITLE
[util] Codeowner

### ISSUE THREAD

**Issue by towoe** [lowRISC/opentitan#1140]
We do not have a code owner for not specified `util` contents.
In #1139 only `*.sh` files are changed, but they are not listed in the CODEOWNERS file.
Any suggestion who that should be?

**Comment by mcy** [comment]
I think we should just kill `util` altogether. It's a kitchen sink of tools owned by hardware, software, and infrastructure people.

**Comment by towoe** [comment]
While its true that `util` is used by different parts, what would be the suggestion for an improvement? I think it would be hard to organize a `util` for each subsection as there are shared components.

**Comment by tjaychen** [comment]
would it make sense to create subdirectories under util that better
indicate their function?
For example there are hw design and dv specific ones..stuff like vendor
might be more general?

**Comment by eunchan** [comment]
I think we don't need CODEOWNERS for `util/`, frankly it is quite hard to determine who should be default reviewers. For instance, `regtool` is designed by Mark (validate/ doc), Sri(gen_dv), Michael(Multireg array), Scott(Multireg, regwen), me (gen_rtl/ data).

**Comment by tjaychen** [comment]
it would still be good to have someone be the default reviewr though.. so
that person can tag others in as needed.

**Comment by towoe** [comment]
I think it would be beneficial to have one as a code owner as we already use this structure.
And my understanding would be that everybody is encouraged to do a code review but if there is no progress its at least clear who to ping for further guidance.

**Comment by sjgitty** [comment]
I'll take `util/` as default, if needed, and parcel out tags where
appropriate. I'm usually watching
all of the `util/` activity anyway. Generally everyone is awesome at
jumping in and solving problems
so not a tough role.
