### ISSUE TITLE
[flash_ctrl] General Interrupt Based Queries

### ISSUE THREAD

**Issue by TimEwins** [lowRISC/opentitan#11412]
Hi

I have just started looking at the Flash Ctrl Interrupts.

I have initially looked at the Interrupt Test Feature.  I am using registers: -

FLASH_CTRL.INTR_ENABLE
FLASH_CTRL.INTR_TEST
and
FLASH_CTRL.INTR_STATE

The functionality I see, is that INTR_TEST causes INTR_STATE to become set, but there appears to be no reliance on INTR_ENABLE.

The Spec doesn't specifically say that the INTR_TEST does, or does not depend on the value of INTR_ENABLE.

Just checking that this is the expected functionality.

**Comment by TimEwins** [comment]
Just to clarify .... I also see that INTR_ENABLE controls the output HW Interrupt, and does not blocl the setting of the INTR_STATE register.

I expect this functionality is as expected

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/tim/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/tim/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



INTR_ENABLE | INTR_TEST | INTR_STATUS |   | HW Interrupt Pin
-- | -- | -- | -- | --
0 | 0 | 0 | Pass | 0
0 | 0 | 1 | Fail | 0
0 | 1 | 0 | Fail | 0
0 | 1 | 1 | Pass | 0
1 | 0 | 0 | Pass | 0
1 | 0 | 1 | Fail | 1
1 | 1 | 0 | Fail | 0
1 | 1 | 1 | Pass | 1



</body>

</html>

**Comment by tjaychen** [comment]
yes that is correct (sorry for not responding sooner).
In all of opentitan, this is the general interrupt behavior.

The interrupt state is always set, and the interrupt enable is really like an interrupt mask.

**Comment by TimEwins** [comment]
Just to clarify .... I also see that INTR_ENABLE controls the output HW Interrupt, and does not blocl the setting of the INTR_STATE register.

I expect this functionality is as expected

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/tim/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/tim/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



INTR_ENABLE | INTR_TEST | INTR_STATUS |   | HW Interrupt Pin
-- | -- | -- | -- | --
0 | 0 | 0 | Pass | 0
0 | 0 | 1 | Fail | 0
0 | 1 | 0 | Fail | 0
0 | 1 | 1 | Pass | 0
1 | 0 | 0 | Pass | 0
1 | 0 | 1 | Fail | 1
1 | 1 | 0 | Fail | 0
1 | 1 | 1 | Pass | 1



</body>

</html>

**Comment by TimEwins** [comment]
@tjaychen Thanks for clariyting ... yes this all makes sense now .... I have been observing behaviour, and making sense of it before tackling the details of the test, and the test modelling.

**Comment by tjaychen** [comment]
@TimEwins is it okay to close this issue now?

**Comment by TimEwins** [comment]
@tjaychen Closing this issue

**Comment by TimEwins** [comment]
Closed
