### ISSUE TITLE
[sw] Naked functions act as an inlining barrier in Clang.

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#1142]
https://godbolt.org/z/Btr-mt is a very simple naked function that loads a byte. Unfortunately, LLVM chooses not to inline it and turns it into a tail call (because, of course, LLVM is forbidden from peaking inside the asm string).

If, instead, you let the register allocator participate, you get inlining: https://godbolt.org/z/rj3d2R.

My question: I think this suggest we might want to just ban naked functions, since it can be surprising to folks who don't write compilers that this optimization behavior is correct.

@lenary @asb what are your thoughts?

**Comment by lenary** [comment]
I think naked functions are only for when using the calling convention would make your function incorrect. A good example is where you need a custom, hand-coded function prologue/epilogue that you cannot get from either a normal function or a function annotated with `__attribute((interrupt))`.

If we can use inline functions to avoid the overhead of the calling convention for small assembly snippets, then inline functions are the correct way to go about implementing these functions.

Note: Be wary of claiming that LLVM is not allowed to peek inside the ASM string. LLVM can and definitely does so in the x86 backend (see `X86TargetLowering::ExpandInlineAsm`, the code is *yikes*, and we have no plans to replicate this functionality in the RISC-V backend).

**Comment by mcy** [comment]
> LLVM can and definitely does so in the x86 backend
That's awful. That's so, so awful. This is why I keep yelling at the Rust people that they need to guarantee they will never do this.

What sort of function prologue do you want that interrupt can't give you, anyway? If we really really really really need to allow them, I think some guidance on when they're the right hammer is in order.

**Comment by lenary** [comment]
We don't have any right now, so I almost certainly meant `interrupt` functions when writing the C11 style guide. I will remove explicit allow of `naked`, which means it is now only recommended against, not banned.
