### ISSUE TITLE
[rv_core_ibex] Don't cache instructions whilst in debug mode

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#11447]
Linking an existing Ibex issue here for visibility: https://github.com/lowRISC/ibex/issues/1472

The instruction cache will cache from the debug module memory area, leading to issues running the debugger as the module uses dynamically changing instruction memory to function.

**Comment by tjaychen** [comment]
@GregAC we're trying to decide now if this should apply to the M2/M3 milestones.
M2 is technically supposed to be D2/D2S/V2/V2S.

Do you think this one still makes sense under D3? It kind of sounds like the debug may not be useable otherwise.

**Comment by GregAC** [comment]
Well Ibex D2 has been closed out so this would count as a post D2 bug.

I do have a fix, just haven't had a chance to run it through a regression (though have tested debug functionality with it). I'll open an Ibex PR for it and we can get this fixed.

**Comment by msfschaffner** [comment]
@GregAC to re-vendor Ibex. That should fix this issue.
