### ISSUE TITLE
[dv/clkmgr] Enable shadow reg sec_cm automation

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#11450]
The clkmgr has 5 different shadow registers, one per clock measurement block, and each one sets a separate bit in the fatal_err_code CSR. Apparently the DV infrastructure for shadow registers doesn't support separate bits per shadow register error.

We can either enhance the DV infra for this, or collapse the shadow register errors to a single bit in fatal_err_code.

**Comment by tjaychen** [comment]
it's probably faster to change on the design side.

**Comment by tjaychen** [comment]
i do think we should add this support in the future though on dv side.
But probably not worth doing at this point.

**Comment by weicaiyang** [comment]
> i do think we should add this support in the future though on dv side. But probably not worth doing at this point.

yeah, we could extract this from hjson file and put this info in RAL model.
