### ISSUE TITLE
[lint, doc] Document for linting tool

### ISSUE THREAD

**Issue by tunghoang290780** [lowRISC/opentitan#1146]
Do we have the document for linting (tool vendor, script)?

**Comment by tunghoang290780** [comment]
Add: @martin-lueker @mwbranstad @rasmus-madsen @senelson7 @igk8 @smcmaster66

**Comment by msfschaffner** [comment]
Hey @tunghoang290780, we have an internal lint flow, yes, but that one is not yet ready to be published openly due to some restrictions from the vendor side.

**Comment by rasmus-madsen** [comment]
@msfschaffner is there a status on this?
if we cannot publish the lint flow - maybe just a small guide would be helpful for new contributers?
either way I think this issue can be closed once a decision to provide documentation or not.

**Comment by msfschaffner** [comment]
Yes, the documentation is located here:

https://docs.opentitan.org/doc/ug/design/
https://docs.opentitan.org/hw/lint/doc/README/

I think I also sent out an announcement about 2 months ago, but forgot to close this issue.

**Comment by rasmus-madsen** [comment]
@msfschaffner thank you - sorry I must have missed that email. 
thank you for the work and for closing the issue
