### ISSUE TITLE
[CDC] AST_BYPASS_CLK tracking

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#11492]
PR #10706 removes the clock bypass inside AST design. It somehow confuses the CDC tool so that CDC run-time has been increased significantly from 20min to 6~7hours.

Temporary workaround will be adding the definition back only for CDC. But should keep tracking if it is resolved prior to the release.

Should be fixed by #16245

**Comment by msfschaffner** [comment]
Great, thanks @arnonsha!

**Comment by tjaychen** [comment]
This is related to #12834

**Comment by tjaychen** [comment]
@jeoongp , i'm assigning this to you for now so we can look a bit at how we might absorb the ast cdc model into our flow, and how much similarity there is to the sign-off tool we're using.

**Comment by tjaychen** [comment]
let's not close this yet until @jeoongp confirms that the conversion is well and working.
If that does not, we will still have to figure out how to deal with this.

**Comment by tjaychen** [comment]
@jeoongp feel free to close this issue down when you think the ast cdc flow is solid and we no longer need to rely on the bypass_clk :)

**Comment by jeoongp** [comment]
Thanks @tjaychen. I will close this ticket once new AST CDC flow is committed on GitHub.

**Comment by tjaychen** [comment]
@msfschaffner @jeoongp i think it would be good to work on getting #16245 merged.
Even if not all the waivers are complete, merging it will allow this issue to be closed and others to have a common part to help with the waiver process.

**Comment by msfschaffner** [comment]
Indeed, we should get that one merged. Looks like the only outstanding issue is that hardcoded path.
CI failures seem intermittent.

**Comment by tjaychen** [comment]
closing since #16245 is merged.
