### ISSUE TITLE
[tool/gcc/vcs] c files listed as Filetype: systemverilog in fusesoc

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#1150]
in the Fusesoc 
we list all .c/.h files as  `file_type: systemVerilogSource`

this makes xcelium gcc choke on aes_model_dpi.c
particularly it chokes on the include of cstring
![image](https://user-images.githubusercontent.com/53917183/70220381-c5afbe00-1746-11ea-89e2-1f23a365de37.png)

Why are we defining c files as systemverilog type?

I seem to remember seeing something about this being a VCS problem. but I cannot find the issue describing this problem.

If I remove the file_type: systemverilog
both vcs and xcelium seem to compile just fine?

do we need to keep this pragma, and if so we need a workaround to get this working for xcelium

**Comment by vogelpi** [comment]
Hi Rasmus,
the original issue is here: #953

Could you please state which core files exactly you had to modify to make it compile? Is it just `hw/ip/aes/dv/aes_model_dpi/aes_model_dpi.core` or also `hw/ip/aes/model/aes_model/aes_model.core`?

If I understand it correctly, you are saying that we should again declare those files as `cSource`. Correct?

Since I cannot test this locally (I do not have access to any of those tools), I would be happy if @sriyerg and @weicaiyang could help out here.

**Comment by rasmus-madsen** [comment]
@vogelpi 
the only file causing problem is the aes_model_dpi.c
but from reading #953
I realize I didn't solve the issue I just remove the file from the compile list..
and as I didn't call any of the functions in side yet I did not any issues.

so the problem seem to be a compile issue.  and not a file_type issue...

@weicaiyang  or @sriyerg 
can you try to compile the aes module on my aes_dev using VCS or Xcelium

**Comment by weicaiyang** [comment]
@rasmus-madsen 
Looks like aes_model_dpi isn't yet included in aes TB. I added it as a depend lib in aes_env.core.
Then, I saw below error from Xcelium.
```
/edascratch/weicai-opentitan/ot/aes/default/build/lowrisc_dv_aes_sim_0.1/sim-vcs/../../../../../../../../usr/local/google/home/weicai/ot/spi/hw/ip/aes/dv/aes_model_dpi/aes_model_dpi.c:7:10: fatal error: 'cstring' file not found
#include <cstring>
         ^~~~~~~~~
1 error generated.
make[1]: *** [/edascratch/weicai-opentitan/ot//aes/default/build/lowrisc_dv_aes_sim_0.1/sim-vcs/xcelium.d/run.lnx8664.18.09.d/xmsc_run/Makefile.xmsc:179: /edascratch/weicai-opentitan/ot//aes/default/build/lowrisc_dv_aes_sim_0.1/sim-vcs/xcelium.d/run.lnx8664.18.09.d/xmsc_run/xmsc_obj/aes_model_dpi_0.o] Error 1
make[1]: Leaving directory '/edascratch/weicai-opentitan/ot/aes/default/build/lowrisc_dv_aes_sim_0.1/sim-vcs'
xmsc_run: *E,TBBLDF: Failed to build test library
          /edascratch/weicai-opentitan/ot//aes/default/build/lowrisc_dv_aes_sim_0.1/sim-vcs/xcelium.d/run.lnx8664.18.09.d/librun.so

xrun: *E,CCERR: Error during cc compilation (status 1), exiting.
make: *** [/usr/local/google/home/weicai/ot/spi/hw/dv/tools/rules.mk:32: compile] Error 1
```

And following error from VCS.
```
aes_model_dpi.c:9:10: fatal error: aes.h: No such file or directory
 #include "aes.h"
          ^~~~~~~
compilation terminated.
make[2]: *** [filelist:25: aes_model_dpi.d] Error 1
make[1]: *** [Makefile:104: product_clean_order] Error 2
make[1]: Leaving directory '/edascratch/weicai-opentitan/ot/aes/default/simv.csrc'
```

Is this the issue you found?

**Comment by rasmus-madsen** [comment]
@weicaiyang 

its almost the same issue, VCS gives the same error, for xcelium I an error inside the cstring.c file.
I wonder why I have a cstring file and you guys don't - I didn't download it. but since our tools are shared between different groups somebody might have added it.

@pirming any suggestion why including cstring is causing issues?
is this a special package that we need to download?

**Comment by weicaiyang** [comment]
> @weicaiyang
> 
> its almost the same issue, VCS gives the same error, for xcelium I an error inside the cstring.c file.
> I wonder why I have a cstring file and you guys don't - I didn't download it. but since our tools are shared between different groups somebody might have added it.
> 
> @pirming any suggestion why including cstring is causing issues?
> is this a special package that we need to download?

I did some experiment with below changes. Then xcelium is passing while VCS has errors `crypto.c:(.text+0x23): undefined reference to EVP_CIPHER_CTX_new`
1. Comment out `#include <cstring>`, not sure if we need cstring?
2. move files from aes/model/ to aes/dv/aes_model_dpi to solve the issue - missing "aes.h". Seems like *.h file need to be same directory of the file that includes it.

**Comment by rasmus-madsen** [comment]
@weicai
ohh thank you for taking a stab at this.


@vogelpi it kinda makes sense to move the aes/model to dv anyway right?
would it be ok to just move all the aes files to aes/dv/aes_model_dpi/ ?

**Comment by vogelpi** [comment]
Thanks @weicaiyang for your support!

Regarding the use of `<cstring>`: We need this for `memset()`, `memcpy()` etc. but I accidentally included the C++ variant instead of `<string.h>`. I am sorry, this is my fault. I will create a patch and PR.

Regarding moving the model files from `aes/model/` to `aes/dv/aes_model_dpi`: This is not the right thing to do. The model is independent from the DPI model (I remember discussing this before). The problem we are facing looks like a wrong setup of the `.core` files. I have been using the DPI calls and the model with this directory structure and Verilator for months now. I am now looking into Rasmus' `.core` files and will report back.

**Comment by vogelpi** [comment]
Alrighty, I think I found the issue. VCS cannot set up the include paths for the C compilation correctly. When building the simulation environment, the missing sources end up in the wrong folder (together with the other SystemVerilog sources) as they are declared as `systemVerilogSource`.

To fix the problem: Inside `aes/dv/aes_model_dpi/aes_model_dpi.core` the sv files only need to be specified as `systemVerilogSource`, c/h files need to be specified as `cSource`. For `aes/model/aes_model.core` the same holds. I tested it. The testbench is generated and VCS can compile the DPI calls as well as the C model. The simulation passes.

I created a PR into the development branch of @rasmus-madsen . PTAL and let me know if it works or not at your end. @sriyerg, @weicaiyang, this is probably also relevant for you as you had similar issues for the HMAC module.

**Comment by vogelpi** [comment]
What I forgot: the PR I made into the dev branch of Rasmus also contains the fix for the wrong header.

**Comment by weicaiyang** [comment]
> Alrighty, I think I found the issue. VCS cannot set up the include paths for the C compilation correctly. When building the simulation environment, the missing sources end up in the wrong folder (together with the other SystemVerilog sources) as they are declared as `systemVerilogSource`.
> 
> To fix the problem: Inside `aes/dv/aes_model_dpi/aes_model_dpi.core` the sv files only need to be specified as `systemVerilogSource`, c/h files need to be specified as `cSource`. For `aes/model/aes_model.core` the same holds. I tested it. The testbench is generated and VCS can compile the DPI calls as well as the C model. The simulation passes.
> 
> I created a PR into the development branch of @rasmus-madsen . PTAL and let me know if it works or not at your end. @sriyerg, @weicaiyang, this is probably also relevant for you as you had similar issues for the HMAC module.

Thanks @vogelpi for figuring this out. 
+ @cindychip

**Comment by vogelpi** [comment]
This issue is solved now. The filetype stuff also required an upstream modification in edalize (see #953 for more info). I am closing it now.
