### ISSUE TITLE
[bazel] Add rules for sw/device/examples/hello_usbdev

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#11501]

**Comment by drewmacrae** [comment]
Currently this depends on many drivers from before we had the difs so we should port this to get it working and then probably enforce some CI to keep it working.

**Comment by a-will** [comment]
We may want to rebase the usbdev library on top of the DIFs, but that library can still exist and provide the verbs we might expect in a synchronous USB API.

**Comment by a-will** [comment]
This issue was apparently completed when it was created. The move to rebase on top of the DIFs is a known task, but it's only tangential to the bazel rules (which are already working). So I'll go ahead and close this issue.
