### ISSUE TITLE
[spi_device] ReadSFDP needs to wait 8 dummy cycles before outputting data

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#11517]
spi_device currently has no gap between the address and data portions for the ReadSFDP command. The spec says there should be 8 dummy cycles between those two phases.

@alphan pointed this out. CC @eunchan

**Comment by eunchan** [comment]
If I understand the design correctly, just set dummy_en and dummy count correctly for SFDP command slot. Then, the read command module will handle it.

**Comment by a-will** [comment]
Ahh, I see what is in the RTL now. Then perhaps we should change this to... "Document which cmd_info registers have hard-coded opcodes (and what those are)" :smile:

**Comment by eunchan** [comment]
Yep. That is in the doc already.

**Comment by eunchan** [comment]
https://docs.opentitan.org/hw/ip/spi_device/doc/index.html#spi-flash-and-passthrough-modes

**Comment by a-will** [comment]
Ah, thanks, sorry I missed that part! It's not clear from the register table nor the programmer's guide what is going on. But I'll close this, then.

**Comment by alphan** [comment]
Reopening this to share the output of spi_device in response to `READ_SFDP` (0x5a) (currently working on top of [63c4132d4](https://github.com/lowRISC/opentitan/commit/63c4132d4cab8cd34afc239c8111f25187816b9a), apologies for the noise if this has already been fixed):

Note: `OPCODE = 0x5a` and `VALID = true` for all cases below.

* `DUMMY_EN = false`:
 
![image](https://user-images.githubusercontent.com/57949550/160213343-85d25323-ba95-4b35-8e04-29b886c2d6e4.png)

*  `DUMMY_EN = true`, `DUMMY_SIZE = 7` (dummy cycles - 1 as in the spec):

![image](https://user-images.githubusercontent.com/57949550/160213666-e4d1baa7-af86-4d5f-8fcf-0689616cce3f.png)

It looks the first bytes of the SFDP table, e.g. the SFDP header (`0x50444653`), are not sent correctly even if I enable dummy cycles. @eunchan, PLMK if I need to set any additional fields of `CMD_INFO_4` other than `OPCODE`, `DUMMY_EN`, `DUMMY_SIZE`, and `VALID`. Thanks!

I also tried setting `ADDR_MODE = ADDR3B` just to see if it has any effect but got the same output as above.

**Comment by eunchan** [comment]
Thanks @alphan Read SFDP and Read Commands are not verified yet. Let me quickly create a direct test case for those paths.

**Comment by alphan** [comment]
just a small update: I captured the traces above before filling the unused area in the SFDP buffer space with `0xff`s. After doing that the first five bytes on CIPO became `0x00`, `0xff`, `0xff`, `0xff`, `0x53`.

**Comment by eunchan** [comment]
@alphan As #11780 was merged, Could you try again? I think the incorrect address issue is gone. I can see the first byte of read can return the correct address.

**Comment by alphan** [comment]
Thanks for the update @eunchan! Sure, but probably I won't be able to do it before tomorrow (need to rebuild the bitstream with debug signals).
