### ISSUE TITLE
[otbn,dv] Trigger integrity checks that we're adding to the call stack

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#11545]
The plan of record is currently to
1. add some sort of redundancy to the read and write pointers in the call stack 
2. add redundant decode to check push/pop signals

Once the RTL is written, figure out how to cause these checks to fail, add coverage for seeing them fail, and generate test sequences that cause them to fail.

**Comment by johngt** [comment]
@prajwalaputtappa : waiting on PR https://github.com/lowRISC/opentitan/pull/13956
