### ISSUE TITLE
[otbn,dv] Write coverage and trigger cross-checks between pre-decode and decode

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#11544]
original estimate 4
> estimate 8
> remaining 2022-08-09 2

**Comment by johngt** [comment]
Redundancy checks.
Checks for blanking. Check against decode.
@prajwalaputtappa has written a test for this case.
If fatal alert doesn't get triggered then checks in place.

Coverage missing.

**Comment by ctopal** [comment]
> remaining 2022-08-08 2

**Comment by ctopal** [comment]
> remaining 2022-09-08 2
