### ISSUE TITLE
[otbn,dv] Trigger a fault to cause the IMEM/DMEM grant signal to be false

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#11540]
This should cause an alert in the design.

**Comment by johngt** [comment]
@prajwalaputtappa : Test case exists that injects a fault into IMEM / DMEM

**Comment by GregAC** [comment]
Signals to target here are `dmem_gnt` and `imem_gnt`within the top-level `otbn` module.

To trigger the fault the same cycle you see a `dmem_req` force the `dmem_gnt` signal low and similarly for imem. This in turn should cause `dmem_missed_gnt`/`imem_missed_gnt` to get asserted resulting in a fatal alert (a `bad_internal_state` fatal error).

**Comment by johngt** [comment]
https://github.com/lowRISC/opentitan/pull/14319 - merged.
