### ISSUE TITLE
[bazel] add support for sw/host/rom_ext_image_tools/signer

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#11548]

**Comment by drewmacrae** [comment]
I created an issue to track this work. I think you're both already doing/have already done some of it, I'm just trying to write up the list of things to do as github issues.

**Comment by timothytrippel** [comment]
This already builds with Bazel (I added this a while back: https://github.com/lowRISC/opentitan/blob/master/sw/host/rom_ext_image_tools/signer/BUILD). And @jon-flatley is integrating the next-gen signing tool directly into opentitantool, which also already builds with bazel, so I think we can close this issue. Is that OK if I close this?

**Comment by timothytrippel** [comment]
Specifically, this was done in #10896. I apologize, the name of that PR was not very clear it contained this build already.
