### ISSUE TITLE
[bazel] cw310 gets bitstream to run tests without manual intervention

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#11550]

**Comment by a-will** [comment]
Can you elaborate a little on what this means? What sort of manual intervention were you looking to avoid?

**Comment by drewmacrae** [comment]
Currently running cw310 tests with bazel requires that you load a bitstream to the device before starting the tests. Ideally bazel would load the best available bitstream to run a test, either building it with vivado or using one downloaded from the GCP bucket or CI

**Comment by arunthomas** [comment]
I think @cfrantz was planning to look at this.

**Comment by cfrantz** [comment]
The following PRs address this issue:
#12013 
#12116 

I'm investigating how to make bazel know about bitstreams emitted by vivado as well.

**Comment by a-will** [comment]
This can be closed now, right?
