### ISSUE TITLE
[dv/full_chip,clkmgr] Fix clkmgr_external_clk_src_for_sw

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#11561]
The clkmgr_external_clk_src_for_sw test needs to be split in two: one with the external clock frequency set to 96 MHz, and another with it set to 48 MHz. In the 48 MHz, you can configure hi_speed_sel to true or non-true, but in the 96 MHz, setting hi_speed_sel to true is unspecified. This can reuse most of the code in the existing test. The external frequency is controlled from the SV side, perhaps just via a plusarg.

By the way, it seems to me splitting it in two is simpler than changing the external clock frequency while the test is running, since sw and sv would need to somehow synchronize.

**Comment by tjaychen** [comment]
sorry @matutem i don't think any progress has been made on this one yet.

**Comment by matutem** [comment]
Fixed by https://github.com/lowRISC/opentitan/pull/12208
