### ISSUE TITLE
[dif/adc_ctrl] cleanup `dif_adc_ctrl_irq_cause_t` enum to use autogenerated macros

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#11567]
Due to a [meson issue](kDifAdcCtrlIrqCauseOneshot), in #11483 I could not include the autogenerated register header in the manually implemented ADC controller DIF header in order to more cleanly define, IRQ causes, such as `kDifAdcCtrlIrqCauseOneshot`. Once we transition all of the `sw/` build to Bazel, this will no longer be an issue and can be cleaned up.

**Comment by cindychip** [comment]
@timothytrippel Can we close this issue now?

**Comment by timothytrippel** [comment]
@cindychip #17207 will fix and close this
