### ISSUE TITLE
[Sysrst_ctrl] Clarification regarding keyintr feature

### ISSUE THREAD

**Issue by patel-madhuri** [lowRISC/opentitan#11595]
Should we except interrupt if there is a edge change before the debounce and detect timer ends? 
![edge_change](https://user-images.githubusercontent.com/92722737/159486648-07e60d45-ec8f-4fc1-9e89-15d6e4ae5278.PNG)

In this above waveform screenshot, the timer starts when the L2H edge is detected but before the timer ends there is edge change again(marker 1). The interrupt is still generated (Time A). Is this an acceptable scenario?

As far as I understand from https://github.com/lowRISC/opentitan/issues/10663, this edge change would be considered as a glitch but it would be great if you could confirm it. If not please correct me.

**Comment by weicaiyang** [comment]
> 1. detect low-to-high / high-to-low transition, or a high / low level (depending on the configuration and signal that is being looked at)
> 2. back off for the amount of debounce cycles configured
> 3. once the debounce timer has expired, the input is sampled again to check whether it is still at the right level (e.g. high if we were looking for a low-to-high transition)

IIUC, from above description, the debounce logic only samples the pin when the timer expires, after detecting the event.
So the design won't see this glitch. It detects L->H, and after timer expires, sample the pin which is still high, hence, the interrupt occurs.

**Comment by msfschaffner** [comment]
Thanks for filing the but @patel-madhuri.
@weicaiyang's understanding is correct.

**Comment by patel-madhuri** [comment]
Thank you @weicaiyang and @msfschaffner for clarifying this question. We have updated the testcase accordingly and merged to the master. I am closing this issue now.
