### ISSUE TITLE
[mask_rom/e2e_tests] Bootstrap tests

### ISSUE THREAD

**Issue by milesdai** [lowRISC/opentitan#11609]
The following end-to-end tests verify the bootstrap functionality off the mask ROM. Details for each test are tracked in the test plan from #10548.
- [ ] Entering bootstrap mode
  - [ ] `mask_rom_e2e_bootstrap_success`
  - [ ] `mask_rom_e2e_bootstrap_bad_pin_config`
  - [ ] `mask_rom_e2e_bootstrap_disabled`
- [ ] Bootstrap functionality
  - [ ] `mask_rom_e2e_bootstrap_config`
  - [ ] `mask_rom_e2e_bootstrap_phase1_reset_op`
  - [ ] `mask_rom_e2e_bootstrap_phase1_read_op`
  - [ ] `mask_rom_e2e_bootstrap_phase1_page_program_op`
  - [ ] `mask_rom_e2e_bootstrap_phase1_erase_op`
  - [ ] `mask_rom_e2e_bootstrap_phase2_reset_op`
  - [ ] `mask_rom_e2e_phase2_page_program_op`
  - [ ] `mask_rom_e2e_phase2_erase_op`
  - [ ] `mask_rom_e2e_phase2_read_op`

**Comment by alphan** [comment]
#14402 updates these tests in the plan, also see corresponding [issues](https://github.com/lowRISC/opentitan/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3ARomE2eTest%22+bootstrap+in%3Atitle).
