### ISSUE TITLE
Idea: Rename meson_init.sh to configure

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1160]
The title says it all; in order to help people get started and feel more "at home", can we rename `meson_init.sh` to `configure`? That would give us a sequence of calls rather similar to what we'd have with autotools/make, e.g.

```
./configure
ninja -C build-out/sw/sim-verilator all
```

@mcy @gkelly @asb

**Comment by asb** [comment]
No strong views on this one. Although a `configure` script isn't _always_ an autoconf script, it very frequently is - so there's a chance this is also seen as misleading.

**Comment by towoe** [comment]
Depending on the plan what meson should do, `bootstram` or `setup` might be an option.

**Comment by mcy** [comment]
Yeah, I agree with @asb, I don't feel excited by the idea of trying to make our project look, on the surface, like a "traditionally" built project, because it absolutely is not once you look past the surface, in a very real way that I think will confuse people.
