### ISSUE TITLE
[flash_ctrl] Test flash_ctrl_host_ctrl_arb Failing with certain seeds - Question

### ISSUE THREAD

**Issue by TimEwins** [lowRISC/opentitan#11601]
The test flash_ctrl_host_ctrl_arb is failing with certain random seeds.  In a run of 10 tests, I have seen 1 failure.

I think I see WHY this test is failing, the question is whether it is the correct behaviour or not?

When we do a fifo read, we start the op, then wait for the status done (by polling in this test), at which point the fifo is filled and we can read the data out.  

If an RMA occurs during that start op -> op done, then it is held off (arbitrated) until done.  Great, that works.  

But after that the test tries to read the data from the FIFO, and as the RMA has started, the whole controller now seems blocked, and we get timeouts from reading the Flash Ctrlr fifo.

This is probably expected, and I can change the test to allow this (at the moment it allows the read back to happen, which is failing)

I remember some discussion on this previously?

The Issue is occuring randomly due to what op the test chooses, and when it throws the RMA

Please can this functionality be clarified? Should the fifos lock (access timeout) after the RMA starts ?

**Comment by tjaychen** [comment]
I'm sorry I completely forgot to respond. 
Yes your description is correct, and I will add to the documentation to explain that after RMA normal flash operations are locked out (although registers can still be accessed)

**Comment by tjaychen** [comment]
actually this is described in https://docs.opentitan.org/hw/ip/flash_ctrl/doc/index.html#flash-protocol-controller.
I will try to highlight it more.

**Comment by TimEwins** [comment]
Thanks ... I will make the necessary test changes
