### ISSUE TITLE
[mask_rom/e2e_tests] Bootup tests

### ISSUE THREAD

**Issue by milesdai** [lowRISC/opentitan#11608]
The following end-to-end tests verify the bootup process of the mask ROM. Details for each test are tracked in the test plan from #10548.

- [ ] `mask_rom_e2e_bootup_no_rom_ext`
- [ ] `mask_rom_e2e_bootup_success`
- [ ] `mask_rom_e2e_bootup_bad_rom_ext_signature`
- [ ] `mask_rom_e2e_bootup_bad_manifest_usage_constraint`
- [ ] `mask_rom_e2e_bootup_rom_ext_invalidated_key`
- [ ] `mask_rom_e2e_bootup_bad_rom_ext_version`

**Comment by alphan** [comment]
#14474 #14478 #14479 #14480 #14468 #14473 #14474
