### ISSUE TITLE
[JTAG] Determine correct ID codes for LC and RV_DM JTAG TAPs

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#11616]
We currently have this in the top-level:
```systemverilog
  // JTAG IDCODE for development versions of this code.
  // Manufacturers of OpenTitan chips must replace this code with one of their
  // own IDs.
  // Field structure as defined in the IEEE 1149.1 (JTAG) specification,
  // section 12.1.1.
  localparam logic [31:0] JTAG_IDCODE = {
    4'h0,     // Version
    16'h4F54, // Part Number: "OT"
    11'h426,  // Manufacturer Identity: Google
    1'b1      // (fixed)
  };
``` 
However, this is currently not connected to the RV_DM, nor to the LC TAP.

In order to make this somewhat more parametric, a suggestion would be to move these into the the toplevel hjson using the `param_decl` feature.

Also, I believe we still have to determine what the correct JTAG codes for both RV_DM and LC should be,

**Comment by tjaychen** [comment]
hmmm... it occurs to me, this is probably something that needs to be populated by Nuvoton specific values right? Especially the Manufacturer identity? It feels like this is something that probably needs to be input from outside of top_earlgrey, or possibly controlled via something inside AST.

**Comment by msfschaffner** [comment]
Yeah that is right. That was the reason I wanted to pull these things out as top-level params (I believe RV_DM is already pulled out - but it is assigned a bogus value of 1).

**Comment by tjaychen** [comment]
so i'm wondering if instead of params, we should pull these all the way as AST outputs.
I think our top level params, outside of the random values, don't have a good way of separating between open and closed right?

**Comment by msfschaffner** [comment]
Yes, that is correct.
The silicon creator would have to override these values in the Hjson and rerun `make -C hw top`.

However, if I recall correctly, such an override and generate flow has already been put in place for the `RndCnst` (it's something like a script that SED's the Hjson and reruns `make -C hw top`, @arnonsha can provide more info). 
So maybe changing this parameter in the Hjson could use the same mechanism?

**Comment by tjaychen** [comment]
Ah okay, so you're suggesting in the same sed script that replaces the seed to also replace the parameter value? That would work too.  I personally prefer an output from ast though :) , but both should work.

**Comment by msfschaffner** [comment]
> Ah okay, so you're suggesting in the same sed script that replaces the seed to also replace the parameter value? That would work too. I personally prefer an output from ast though :) , but both should work.

Oh the signals would work also. I just wanted to avoid port changes in `rv_dm`, `lc_ctrl` and `ast` ;)...

**Comment by arnonsha** [comment]
I think it would be easier to have these values in a **dedicated** package file.
Any vendor can then replace it with its own package using the "-partner" flag ?

**Comment by GregAC** [comment]
I'd note lowRISC does have a JEDEC ID, might be good for a default value?

**Comment by GregAC** [comment]
Yeah I mean the ID we give within this repository. As for the eventual chip I don't know enough about JTAG IDCODEs to know what would be most appropriate.

**Comment by tjaychen** [comment]
sounds good, yeah the ID for this repo i think definitely makes sense to be lowrisc. 
Is this something we need to run by the TC? or okay to just proceed?

**Comment by tjaychen** [comment]
> I think it would be easier to have these values in a **dedicated** package file. Any vendor can then replace it with its own package using the "-partner" flag. What do you think ?

@arnonsha do you mean something like this?
https://github.com/lowRISC/opentitan/blob/master/hw/ip/flash_ctrl/flash_ctrl_pkg.core#L17

That would certainly work too. If this is what you had in mind, let me know and I can place it in. 
To Michael's point though, if you DO have a sed script that is replacing things already in `top_earlgrey.hjson`, we can take that route too.  Although I'd agree that your option here is probably a bit more explicit and more resistant to hjson/tooling changes in the long run.

**Comment by arnonsha** [comment]
Yes, This is what I had in mind. Something like this in chip_earlgrey_asic.core

      - "fileset_partner  ? (partner:systems:jtag_id_pkg)"
      - "!fileset_partner ? (lowrisc:systems:jtag_id_pkg)"

The jtag_id_pkg will only contain the JTAG_IDCODE parameter.

**Comment by arnonsha** [comment]
By the way, Nuvoton DV would need to check the actual Nuvoton values on the original design. We can't wait till we replace all seeds with the mentioned scripts. Alternative packages seems the right approach.

**Comment by tjaychen** [comment]
sounds good, i'll try to add this today/tomorrow.

**Comment by arnonsha** [comment]
Thanks @tjaychen 
Once PR is pushed, I would need to create the "vendor" pkg file on our side. I'll let you know when it is ready and then you can merge. 
Sounds good ?

**Comment by tjaychen** [comment]
so we've made all the necessary changes for the packaging, @GregAC do you want to plug in lowrisc ID for the open source version? it makes more sense than using the Google one. Or if you let me know what it is, I can update and close.

**Comment by tjaychen** [comment]
yeah i think that's fine.

**Comment by msfschaffner** [comment]
Promoting to P1 since this incurs an RTL change.

**Comment by johngt** [comment]
Believe that this is resolved by https://github.com/lowRISC/opentitan/commit/284ad0658493f7bf2a93018ebc96bec78a1b67bf
@GregAC / @msfschaffner
