### ISSUE TITLE
[dv/lc_ctrl] design changes post V2 that needs verification support

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#11619]
1). hardware revision register check
 https://github.com/lowRISC/opentitan/pull/11617

**Comment by msfschaffner** [comment]
@cindychip can this be closed?

**Comment by cindychip** [comment]
Opps, I do not think I did this. I can finish it soon!

**Comment by cindychip** [comment]
https://github.com/lowRISC/opentitan/commit/428c6833c16b454fd7961e53bba62180438ca310 Actually finished here.

**Comment by msfschaffner** [comment]
Thanks for checking!
