### ISSUE TITLE
[mask_rom/e2e_tests] Upgrade tests

### ISSUE THREAD

**Issue by milesdai** [lowRISC/opentitan#11612]
The following end-to-end tests verify the firmware upgrade process. Details for each test are tracked in the test plan from https://github.com/lowRISC/opentitan/pull/10548.

- [ ] `mask_rom_e2e_upgradable`
- [ ] `mask_rom_e2e_upgrade_min_sec_version`
- [ ] `mask_rom_e2e_upgrade_power_loss`

**Comment by alphan** [comment]
#14488 #14489
