### ISSUE TITLE
[mask_rom/e2e_tests] Chip-specific startup

### ISSUE THREAD

**Issue by milesdai** [lowRISC/opentitan#11610]
The following end-to-end tests verify that chip-specific startup processes are performed correctly. Details for each test are tracked in the test plan from https://github.com/lowRISC/opentitan/pull/10548.

- [ ] `mask_rom_e2e_startup_ast_main_sram_init`
- [ ] `mask_rom_e2e_startup_retention_sram_init`
- [ ] `mask_rom_e2e_startup_retention_sram_saved`
- [ ] `mask_rom_e2e_startup_retention_sram_wiped`

**Comment by alphan** [comment]
See [these issues](https://github.com/lowRISC/opentitan/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3ARomE2eTest%22+ret+in%3Atitle+OR+asm+in%3Atitle+)
