### ISSUE TITLE
[mask_rom/e2e_tests] Shutdown tests

### ISSUE THREAD

**Issue by milesdai** [lowRISC/opentitan#11611]
The following end-to-end tests verify the shutdown process of the mask ROM. Details for each test are tracked in the test plan from https://github.com/lowRISC/opentitan/pull/10548.

- [ ] `mask_rom_e2e_shutdown_boot_failure`
- [ ] `mask_rom_e2e_shutdown_alert_configuration`
- [ ] `mask_rom_e2e_shutdown_mask_rom_alert_shutdown`
- [ ] `mask_rom_e2e_shutdown_interrupts`

**Comment by alphan** [comment]
see [these issues](https://github.com/lowRISC/opentitan/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3ARomE2eTest%22+shutdown+in%3Atitle)
