### ISSUE TITLE
[dv] Nightly test links to old dates are broken

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#11629]
All of the "previous version" links on the CHIP-level [test page](https://reports.opentitan.org/hw/top_earlgrey/dv/latest/results.html) result in 404s.

@cindychip: I think you are usually in charge of "care and feeding of the nightlies"?

**Comment by msfschaffner** [comment]
This may have been due to a change how we produce and upload these results.
The links seem to work again now, so I'll close this issue.

**Comment by cindychip** [comment]
oh sorry for the late reply, yes this is fixed! Thanks Rupert and Michael.
