### ISSUE TITLE
I2C: hw/ip/i2c/data/i2c_testplan.hjson

### ISSUE THREAD

**Issue by visbaz** [lowRISC/opentitan#11633]
Below are my understandings on test plan.

•	Test names are i2c_testname whereas they have to be i2c_host/target_testname
•	I2c_smoke for target version of test is marked V1 which is still due as DUT was never in target mode.
•	All tests should be renamed with host or target category of tests.

please add your comments as i need to continue to work with I2C DUT in Target mode

This will need changes to i2c_agent and i2c environment.

Kindly add any relevant stake holders.

**Comment by sriyerg** [comment]
The entries in the testplan (`i2c_testplan.hjson`) are called "testpoints". A "testpoint" is what you intend to test. An "implemented" test is what you actually end up writing and running with `dvsim` (i.e. the entries in `i2c_sim_cfg.hjson`). The point of the testplan is to capture discrete-enough aspects of the design separately to book-keep everything that is planned to be tested. 

The testplan is written in the very early stage, so the implementation details are not clear during that stage. When you actually start implementing the test, you may adequately exercise constrained randomization to hit large portions of the design state space. So an implemented test can address multiple testpoints. The converse is also true - multiple implemented tests may be needed to satisfy a single testpoint. The entry in the testplan and the entry in the `*_sim_cfg.hjson` need not have a 1:1. Which implemented test(s) satisfies the testpoint is indicated with the `tests` key in the testpoint entry.

In case of I2C, the testpoint intentionally lists `host_smoke` and `device_smoke` separately, but the same implemented test `i2c_smoke` is mapped to both - which suggests that it caters to both modes. **If not, then thank you for raising this issue - it would mean that the `i2c_smoke` test is incomplete and needs to be updated.** 

The onus is of course, on the DV engineer to identify and create / enhance ALL of the necessary DV components to achieve the end goal (tb, agents, components, tests, sequences, etc), which is V3 closure on the block.

**Comment by visbaz** [comment]
@sriyerg thanks for the clarification and as you mentioned i shall move forward and still fix any legacy implementations if necessary.
