### ISSUE TITLE
[lc_ctrl/rtl] replace u_state_regs and u_cnt_regs with prim_sparse_fsm_flop

### ISSUE THREAD

**Issue by NigelScales** [lowRISC/opentitan#11630]
On investigation of the implementation of the [security countermeasure verification framework](https://docs.opentitan.org/doc/ug/sec_cm_dv_framework/) it seems that the LC State and LC Count registers can be implemented using prim_sparse_fsm_flop which should enable the pre-defined security countermeasure tests for those registers.

Currently they are implemented using prim_flop:

```
 logic [LcStateWidth-1:0] lc_state_raw_q;
  assign lc_state_q = lc_state_e'(lc_state_raw_q);
  prim_flop #(
    .Width(LcStateWidth),
    .ResetValue(LcStateWidth'(LcStScrap))
  ) u_state_regs (
    .clk_i,
    .rst_ni,
    .d_i ( lc_state_d     ),
    .q_o ( lc_state_raw_q )
  );

  logic [LcCountWidth-1:0] lc_cnt_raw_q;
  assign lc_cnt_q = lc_cnt_e'(lc_cnt_raw_q);
  prim_flop #(
    .Width(LcCountWidth),
    .ResetValue(LcCountWidth'(LcCnt24))
  ) u_cnt_regs (
    .clk_i,
    .rst_ni,
    .d_i ( lc_cnt_d     ),
    .q_o ( lc_cnt_raw_q )
  );
```
This is different from LC FSM registers which use prim_sparse_fsm_flop, the interface appears to be the same except for the type parameter (StateEnumT).
```
  logic [FsmStateWidth-1:0] fsm_state_raw_q;
  assign fsm_state_q = fsm_state_e'(fsm_state_raw_q);
  prim_sparse_fsm_flop #(
    .StateEnumT(fsm_state_e),
    .Width(FsmStateWidth),
    .ResetValue(FsmStateWidth'(ResetSt))
  ) u_fsm_state_regs (
    .clk_i,
    .rst_ni,
    .state_i ( fsm_state_d     ),
    .state_o ( fsm_state_raw_q )
  );

```

**Comment by weicaiyang** [comment]
@msfschaffner should we use `prim_sparse_fsm_flop` for lc_state as well?

**Comment by msfschaffner** [comment]
This sounds like a good idea - I'll look into it shortly.
