### ISSUE TITLE
[adc_ctrl/rtl] Assertion NpCntCheckClr_A does not trigger

### ISSUE THREAD

**Issue by NigelScales** [lowRISC/opentitan#11666]
On reviewing the coverage data it seems assertion tb.dut.u_adc_ctrl_core.u_adc_ctrl_fsm.NpCntCheckClr_A never triggers.
The assertion is defined thus:
```
`ASSERT(NpCntCheckClr_A, ld_match & $rose(stay_match) |-> (np_sample_cnt_q == '0), clk_aon_i, !rst_aon_ni)
```
The predicate never matches as can be seen in the waves below.
![image](https://user-images.githubusercontent.com/78102677/159935867-d2f949f8-974d-42a7-870b-e8dd88b281ef.png)

Suggest:
```
`ASSERT(NpCntCheckClr_A, $rose(ld_match) ##1 $rose(stay_match) |-> (np_sample_cnt_q == '0), clk_aon_i, !rst_aon_ni)
```
Gives waves:
![image](https://user-images.githubusercontent.com/78102677/159938214-c2d1a2b6-7f3b-46f1-8d33-4be4fe0c959a.png)

To reproduce:
./util/dvsim/dvsim.py hw/ip/adc_ctrl/dv/adc_ctrl_sim_cfg.hjson -i adc_ctrl_filters_polled --tool xcelium --fixed-seed 1 -v l --waves

**Comment by tjaychen** [comment]
thanks for catching Nigel. Maybe this assertion became stale after some of the previous changes.
I will have a look.

**Comment by NigelScales** [comment]
> thanks for catching Nigel. Maybe this assertion became stale after some of the previous changes. I will have a look.

Probably the timing changed. I only spotted it looking at the coverage data.
