### ISSUE TITLE
[opentitantool] add DV sim bootstrap flash image prep and update bootstrap implementation

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#11678]
# Overview
To support adding bazel rules to prep flash images for bootstrap in DV sim, bazel rules for building the [spiflash utility](https://github.com/lowRISC/opentitan/tree/master/sw/host/spiflash) were added in #11640. The [spiflash utility] requires `libftdi1-dev` and `libusb-1.0-0` as a dependencies. Preliminarily, related bazel rules just indicated these deps using linkopts, as noted in this [review comment](https://github.com/lowRISC/opentitan/pull/11640/files#r834365838). Normally, these dependencies should also be built by bazel, however, there are two things to note that answer why this will be unnecessary in the long term:

1. Since opentitantool and this [CW310 python script](https://github.com/lowRISC/opentitan/blob/master/util/fpga/cw310_loader.py) now handle bootstrapping, from the host perspective, the only functionality from the [spiflash utility](https://github.com/lowRISC/opentitan/tree/master/sw/host/spiflash)  that is still required is the component that preps a flash image for bootstrapping in DV sim. **_This functionality should also probably be moved into opentitantool, and the spi_flash utility can be deleted (removing the bazel rules and deps with it)._**

2. The bootstrap protocol is currently being re-designed for the mask ROM (and test ROM). **_Once it is completed in the near future, the [opentitanlib bootstrap implementation](https://github.com/lowRISC/opentitan/tree/master/sw/host/opentitanlib/src/bootstrap) may need to be updated._**

# Tasks
- [ ] update  [opentitanlib bootstrap implementation] with new bootstrap protocol (if changes are required)
- [ ] add DV sim bootstrap flash image prep to opentitantool/lib

**Comment by timothytrippel** [comment]
CC: @alphan @cfrantz

**Comment by moidx** [comment]
Hi @timothytrippel, is this issue now used to track integration of ROM bootstrap into DV tests? If so, can you assign this to M2? Thanks

**Comment by alphan** [comment]
I'm not sure how smart those uvm functions can be but if they can send a few bytes before each chunk, we can use the signed flash binaries as is since frames don't have a digest anymore.

**Comment by timothytrippel** [comment]
Good idea @alphan, let me check with the DV folks, doing as you say would certainly simplify things on the Bazel/opentitantool front.

**Comment by timothytrippel** [comment]
reassigning to @a-will as he is working on top-level test that will use the bootstrap path in DV

**Comment by a-will** [comment]
It uses the unscrambled version and sends it over SPI, so there's no additional image prep needed.
