### ISSUE TITLE
Break up the WORKSPACE file

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#11699]
It makes editing, review and reading more complicated and it will keep growing as we add more things.
Content can be loaded from other .bzl files and registered as appropriate to keep things reasonable, like we do with `//third/party/cargo:crates.bzl` here https://cs.opensource.google/opentitan/opentitan/+/master:WORKSPACE;drc=aa91c773d6a787c9776d51392ad6475dfad2bb6c;l=116

**Comment by mcy** [comment]
I've upgraded this to a P1 because merge conflicts in the WORKSPACE file are only going to get worse.
