### ISSUE TITLE
Designcheck 2-3 error check fires for top_earlgrey_nexysvideo

### ISSUE THREAD

**Issue by satnam6502** [lowRISC/opentitan#1169]
When trying to follow the instructions at https://docs.opentitan.org/doc/ug/getting_started_fpga for building the bitstream for the Earlgrey design for the Nexys Video FPGA board:

```
$ . /tools/xilinx/Vivado/2018.3/settings64.sh
$ cd $REPO_TOP
$ make -C sw/device SW_DIR=boot_rom clean all
$ fusesoc --cores-root . run --target=synth lowrisc:systems:top_earlgrey_nexysvideo
```

I get the error:

```
ERROR: [Designcheck 2-3] BRAM implementation not found for ROM memory.
ERROR: [runtcl-1] ERROR: [Common 17-39] 'send_msg_id' failed due to earlier errors.
ERROR: [Common 17-39] 'send_msg_id' failed due to earlier errors.

INFO: [Common 17-206] Exiting Vivado at Fri Dec  6 15:55:19 2019...
[Fri Dec  6 15:55:19 2019] impl_1 finished
wait_on_run: Time (s): cpu = 00:03:42 ; elapsed = 00:06:36 . Memory (MB): peak = 1376.055 ; gain = 0.000 ; free physical = 4815 ; free virtual = 108295
Bitstream generation completed
ERROR: Implementation and bitstream generation step failed.
INFO: [Common 17-206] Exiting Vivado at Fri Dec  6 15:55:19 2019...
make: *** [Makefile:8: lowrisc_systems_top_earlgrey_nexysvideo_0.1.bit] Error 1
ERROR: Failed to run lowrisc:systems:top_earlgrey_nexysvideo:0.1 : 'make' exited with an error code
```

I changed `ERROR` to `INFO` in `vivado_hook_opt_design_post.tcl` and managed to produce a bitstream that runs the boot loader on my FPGA board so perhaps this is a false error?

**Comment by tjaychen** [comment]
Ah I am sorry, you're catching all of this at a bad time when documents are
mid-transition and updates.
The fusesoc core instruction has been updated to expect the rom files
somewhere else.

Instead of using make -C ...
Please do the following instead,
./meson_init.sh -f
ninja -C build-out/sw/fpga sw/device/boot_rom/boot_rom.bin

you can see this PR (https://github.com/lowRISC/opentitan/pull/1070/files)
for the updates.
We are switching build systems, so the docs and implementations may be
somewhat out of sync temporarily.

**Comment by satnam6502** [comment]
Ah, yes, indeed! I was going to file some more PRs to say the instructions for building the ROM images are wrong. OK: thank you! I shall sit tight and wait it out...
In the meantime I have managed to understand and clobber together enough stuff to get the boot image running on my [Xilinx ZC104 board](https://www.xilinx.com/products/boards-and-kits/zcu104.html) and the UART displaying the correct output! And I've *just* taken delivery of the Nexys Video board and plugged it in!

**Comment by tjaychen** [comment]
great to hear!

**Comment by satnam6502** [comment]
I wired up the 125MHz LVDS differential clock inputs to the PLL and changed the multiplication and division to get 50MHz and I wired up the UART pins and a push-button for reset so that much works. The JTAG/SPI stuff I have not dealt with yet, but I was doing this while waiting for the  Nexys Video board so perhaps I shall not continue with the porting work on focus instead on the "official board". Thank you kindly.

**Comment by satnam6502** [comment]
Ah, following the *new* instructions in that PR I got the hello world program to run!

```
            Version:    opentitan-snapshot-20191101-1-331-g8a4c043
Build Date: 2019-12-06, 16:33:55
INFO: Boot ROM initialisation has completed, jump into flash!
Version:    opentitan-snapshot-20191101-1-331-g8a4c043
Build Date: 2019-12-06, 16:33:55
Bootstrap requested, initialising HW...
                                       HW initialisation completed, waiting for SPI input...
            Processing frame no: 00000000 exp no: 00000000
Processing frame no: 00000001 exp no: 00000001
Processing frame no: 00000002 exp no: 00000002
Processing frame no: 00000003 exp no: 00000003
Processing frame no: 00000004 exp no: 00000004
Processing frame no: 80000005 exp no: 00000005
bootstrap: DONE!
INFO: Boot ROM initialisation has completed, jump into flash!
Hello World! Dec  6 2019 16:55:29
Watch the LEDs!
Try out the switches on the board
or type anything into the console window.
The LEDs show the ASCII code of the last character.
GPIO: Switch 7 changed to 1
FTDI control changed. Enable JTAG
```

**Comment by chrisrauer** [comment]
Thanks for filing this.  I got stuck on this on friday.  The new instructions worked for me too.

**Comment by nicolast0604** [comment]
@satnam6502 
Hi 
Do you mean that you migrate the opentitan from nexysvideo to ZCU104?
It's exciting as I am trying to do the same thing. 
Could you please give me guidance for how to do it as I am a very beginner?

Thanks a million.

**Comment by satnam6502** [comment]
Hello @nicolast0604 . Sadly this was so long ago that I forgot exactly what I did! I think I used the ZCU104 board for a while, but then switched over to using the nexysvideo for the rest of the project since it was properly supported by the OpenTitan project. I've left that project and Google and work elsewhere on very different things so sadly I have lost the thread on this :-(
