### ISSUE TITLE
[sw,tests] chip_sw_flash_prim_tl_access test questions

### ISSUE THREAD

**Issue by davebwil** [lowRISC/opentitan#11700]
Hi, for this toplevel software flash_ctrl test the description is as follows:

desc: 
'''Verify that the SW can read / write the dummy memory in flash phy.
            - The dummy memory is a open source placeholder for the closed source CSRs that will be
              implemented in a translation 'shim'.
            - Verify that this region can be read / written to by the SW.
            - TODO: the existing CSR / mem tests may already handle this.
            '''

Is this test required based on the TODO?

If it is, how is the dummy memory accessed, is there some documentation for this?

Thanks

**Comment by msfschaffner** [comment]
We're working on a reggen tooling update for that particular part (see https://github.com/lowRISC/opentitan/pull/10982). 
So this may indeed be coverable with standard tests.
I would therefore recommend to wait implementing this test.

**Comment by tjaychen** [comment]
@msfschaffner once your prim_csr lands, do we even need to have a specific top level test for this?
the prim_flash registers will just become a part of `chip_csr_rw` right?

**Comment by msfschaffner** [comment]
Yeah most of the functionlity will be covered by the automatic CSR tests.
However, there is going to be a custom component here, and this is the life cycle based TL-UL gating.
I.e., in some LC states, all these accesses are going to error back via the tlul error responder in `tlul_lc_gate`, and I think this would have to be modelled (@cindychip is going to look into that).

But to your point, I think we do not need an explicit, hand crafted access test for this anymore in the open source.

**Comment by tjaychen** [comment]
yeah i think the `tlul_lc_gate` should probably be a separate test at the block level.
@cindychip does this mean we should fill in `chip_csr_rw` for this particular test in the testplan?

**Comment by cindychip** [comment]
Thanks Tim and Michael. 

This is what we discussed in the meeting:
1). This registers should be included in csr_rw tests when access is allowed. (I can take this task)
2). Write another SW test to access thess regs not allowed, we should be able to see output d_error. (I can take this task)
3). The above behavior should also be tested in IP level block, both open source and close source.

In summary, there is nothing need to be done in open source top-level test for now. I will update the chip-level testplan and implement SW/DV tests for top-level if needed.

**Comment by weicaiyang** [comment]
> 2). Write another SW test to access thess regs not allowed, we should be able to see output d_error. (I can take this task)

Since the item 1 is using stub mode and it doesn't cover the entire data path, we'd better update this item to also test accessing a prim reg correctly in the LC state that allows accessing prim reg.

**Comment by tjaychen** [comment]
> > 2). Write another SW test to access thess regs not allowed, we should be able to see output d_error. (I can take this task)
> 
> Since the item 1 is using stub mode and it doesn't cover the entire data path, we'd better update this item to also test accessing a prim reg correctly in the LC state that allows accessing prim reg.

actually unlike `otp_ctrl`, the flash tlul interface isn't qualified by LC state, since it is needed during production.

**Comment by cindychip** [comment]
Thanks Tim, I guess for the second point:
2). While checking other IP (OTP etc)'s prim_tl_access being blocked, we will also check flash_ctrl's prim_tl_access is not blocked. Does that meet your need?

**Comment by tjaychen** [comment]
> Thanks Tim, I guess for the second point: 2). While checking other IP (OTP etc)'s prim_tl_access being blocked, we will also check flash_ctrl's prim_tl_access is not blocked. Does that meet your need?

actually what i was trying to say is..do we need a separate test for this? Since the flash prim won't be blocked in any specific way, and @msfschaffner's prim_csr will make it compatible with generic csr test, wouldn't that be enough?

**Comment by cindychip** [comment]
I guess the second test is more for OTP or AST prim_tl_access where they will be blocked by lc gating. Since we have this test already, we could also double(maybe triple haha?) check that flash is not blocked.
Also in current CSR test, we only load one OTP image, so it will always use one lc_state as current state.

**Comment by tjaychen** [comment]
ah sounds good.
I see what you mean.

Makes sense to me.

**Comment by tjaychen** [comment]
@cindychip sorry can we close this now? Or maybe we need to make some updates after the prim alert merge?

**Comment by cindychip** [comment]
Oh thank you for pinging me, this test is fully covered in chip_prim_tl_access. I think it is safe to close it.
