### ISSUE TITLE
[sw,tests] chip_sw_flash_ctrl_clock_freqs test questions

### ISSUE THREAD

**Issue by davebwil** [lowRISC/opentitan#11701]
For this toplevel software flash_ctrl test the description is as follows:

desc: '''Verify flash program and erase operations over the ctrl over a range of clock freqs.
            - The range of clock freqs to test is TBD.
            - Reuse chip_flash_ctrl_ops to also enable jitter on the clock as well as run with
              randomized clock frequencies.
            - This sets the test for closed source where the flash access timing matters.
            '''
            
Has the TBD been decided, what are the range of frequencies?

What would be the methodology for setting the frequencies in a top level test?

Thanks.

**Comment by tjaychen** [comment]
@zi-v 
@eshapira 
@sha-ron 

can Nuvoton specify the range of frequencies desired? I think specifically this refers to the jitter range.

**Comment by zi-v** [comment]
When setting the main (aka sys) clock frequency to 100 MHz (design target) with jitter, its output is expected to be within 80 MHz to 103 MHz range (this can be tuned post tapeout).
In addition, we have a fallback option to run in lower frequency down to 70 MHz (before jitter).
The latter requires different close source settings if run with the real IP vendor models (not part of the open source).

**Comment by Jacob-Levy** [comment]
For the open source when jitter is enabled:

```
assign CLK_PERIOD = (SysClkPeriod + jitter)/1000;

always begin
  // 0-2000ps is upto +20% Jitter
  jitter = sys_jen ? $itor($urandom_range(2000, 0)) : 0.0;
  #(CLK_PERIOD/2) clk_osc = ~clk_osc;
end

```

**Comment by tjaychen** [comment]
thanks all. Since this is something that's enabled as part of the open source ast already, it sounds like we really just need a test that does flash operations (program / erase / read) while enabling jitter, is that correct?

**Comment by zi-v** [comment]
yes

**Comment by davebwil** [comment]
Closing now. Thanks all.
