### ISSUE TITLE
[otbn, dv] Illegal mem access when otbn is busy is not resulting in fatal error

### ISSUE THREAD

**Issue by prajwalaputtappa** [lowRISC/opentitan#11709]
@GregAC , @rswarbrick ,
I'm trying to make bus accesses to imem and dmem when the otbn is busy. I'm seeing that the bus accesses are being ignored, but a fatal error is not raised. 
![Screenshot from 2022-03-25 16-54-59](https://user-images.githubusercontent.com/91126414/160166274-42ff49a3-c1de-413a-b5ef-c77a6df4fde3.png)

**Comment by johngt** [comment]
@prajwalaputtappa believes that this has now been resolved.
100% passing as of check 2 Aug 2022
@GregAC - it looks like we can close out this issue. Unsure of the PR that fixed this. Might want to tag PR before closing out.

**Comment by ctopal** [comment]
This functionality is checked with `otbn_illegal_mem_acc` test which passes in our nightlies
