### ISSUE TITLE
Write demo software exercising U-mode

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1171]
We currently have no in-tree software that utilizes U-mode. Write a simple application showing that/how how U-mode works.

Things to do/show:

- Entering/exiting U-mode.
- ~~Read time(h). Requires emulation in a trap handler, see #78~~ - No `time` implementation in Ibex or OT firmware.
- Read U-mode specific registers.

> estimate 4

**Comment by asb** [comment]
I'd say this is more of a P3 at best. Having demo applications for all functionality isn't going to scale, and arguably this is more of an Ibex showcase than an OpenTitan one. The best path for demonstrating U-mode support in OpenTitan might be for something such as the Tock port to make use of it.

**Comment by GregAC** [comment]
We don't feel the need for a specific example for this in OT. However a chip-level test that brings us to U mode and demonstrates use of OT peripherals from U mode may be useful.

**Comment by GregAC** [comment]
Exercising U mode as described above in a chip-level test could be a sensible thing to do pre M2.5 but low priority.

**Comment by GregAC** [comment]
estimate range: 2 - 4

**Comment by GregAC** [comment]
I don't think this is relevant any more, certainly not a test we'd seek to write for M5 or earlgrey prod (as it provides limited/no value above existing tests) so closing.
