### ISSUE TITLE
[clkmgr] `ref_valid` keeps high

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#11721]
With PR #11676 the pulse_sync catched the input keeps high in clkmgr.

I've checked the design (`prim_clock_meas`). It may happen if `RefCnt` is 1.
If RefCnt is one, it never reaches the last `else if` state at line 72.

<img width="790" alt="image" src="https://user-images.githubusercontent.com/1192814/160209070-d34ba498-64b7-454a-9566-01b540e5a082.png">

**Comment by tjaychen** [comment]
this was addressed by an assertion update in #11676
