### ISSUE TITLE
[spi_device] Address of flash command

### ISSUE THREAD

**Issue by kosta-kojdic** [lowRISC/opentitan#11735]
@eunchan Can you confirm if address given in flash commands (after opcode) is offset within SPI device buffer. SPI device buffer is at 0x1000 offset inside memory space according to spec.
So if we give command address 0x0 will it target first word location within SPI buffer? (at offset 0x1000)

**Comment by eunchan** [comment]
Read buffer starts from `SPI_BASE_ADDR + 0x1000` and ends at `0x17FF` (2kB). So, yes 0x0 reads 0x1000

**Comment by kosta-kojdic** [comment]
Thanks, clarified, closing this now
