### ISSUE TITLE
[sw/silicon_creator] Typical and max times for flash operations for the SFDP table

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#11747]
@tjaychen creating this to track the update to the time values in the SFDP table definition. Could you please reply to this issue when you get the chance? Please see the [spreadsheet](https://docs.google.com/spreadsheets/d/1cioU3HgsWZXD4-eoUiH9TuVLZeFpucSdjyq5HND-FpQ/edit#gid=0) for actual definitions and layout of these fields.

- Erase typical time (4 KiB, I think we can extrapolate from 2 KiB page erase time),
- Chip erase typical time,
- Max erase time multiplier,
- First byte program typical time, 
- Additional byte program typical time,
- Page program time (256 bytes as defined in the SFDP table not the actual page size of the flash_ctrl), and
- Max program time multiplier.

Thanks!

cc @a-will @cfrantz

**Comment by tjaychen** [comment]
thanks for filing the issue @alphan .
i'll try to dig up the info and fill it in.

**Comment by alphan** [comment]
Friendly ping @tjaychen.

**Comment by tjaychen** [comment]
thanks for the reminder.
I'm dealing with an ongoing flash bug, i'll have a look once that is completed.
