### ISSUE TITLE
[otbn, dv] Fatal alert not asserted when the error is raised before OTBN starts executing instructions

### ISSUE THREAD

**Issue by prajwalaputtappa** [lowRISC/opentitan#11768]
@GregAC and @rswarbrick ,

In this testcase, I've tried to inject state zero URND error before OTBN starts running and I don't see the fatal alert coming up. Please find screenshot attached. 
![Screenshot from 2022-03-29 15-44-02](https://user-images.githubusercontent.com/91126414/160638306-964b4ba5-acf4-45d2-8f93-f955bc656697.png)

**Comment by rswarbrick** [comment]
I think this should be fixed by #11950 (but we should check again once that's merged to make sure I got it right)

**Comment by rswarbrick** [comment]
Pretty certain this is fixed (based on some otbn_escalate tests I ran today)
