### ISSUE TITLE
Question: Create a Python package for the regtool?

### ISSUE THREAD

**Issue by oholimoli** [lowRISC/opentitan#11765]
I have a question regarding the regtool. Since a lot of work has been put into it: Have you discussed the option to move it to a Python package that it can also be used by other projects and where the maintenance would take place?

I was looking for an open source tool like the regtool and the only one in found that looked suitable was https://github.com/esynr3z/corsair but it seems like there is currently not too much happening anymore.

**Comment by rswarbrick** [comment]
Hi there! I don't think we've thought about this seriously, but I don't see any strong reason not to (especially if we could continue to use it "in-tree" with no ill effect). I don't think we're likely to put engineering effort into this in the near future, though: maybe you'd like to try?

**Comment by oholimoli** [comment]
Currently it seems like Corsair will be the choice. Have you considered to use Corsair?

**Comment by rswarbrick** [comment]
It looks like it started a lot more recently than our register tooling. Maybe we'll switch to it one day, but that's not going to happen soon. If you've found a better match for your needs, that's great. I'm going to close this issue now: please feel free to open another if you need help or find an issue with OpenTitan.
