### ISSUE TITLE
[spi_device] Read command wrong Address

### ISSUE THREAD

**Issue by kosta-kojdic** [lowRISC/opentitan#11764]
In dual mode test in flash mode we have read command with intended address 0x1. Looking through waves I see that actual accessed memory address is 0x100.

@eunchan can you please check.

To recreate, in PR #11762 you can run:
./util/dvsim/dvsim.py hw/ip/spi_device/dv/spi_device_sim_cfg.hjson -i spi_device_dual_mode --fixed-seed 10 --tool xcelium --waves --xprop-off -v h --max-parallel 1

**Comment by weicaiyang** [comment]
the data width is 32. address 0x1 is at the same word of 0x0.

**Comment by kosta-kojdic** [comment]
> the data width is 32. address 0x1 is at the same word of 0x0.

Yes, but address we get inside readcmd block is 0x100. For address 0x4 we get address 0x400.

**Comment by eunchan** [comment]
Thanks. I will reproduce on my side and review. As read command / upload functions are not verified at all I am expecting many bugs arose.

**Comment by eunchan** [comment]
<img width="2165" alt="image" src="https://user-images.githubusercontent.com/1192814/160706126-a3c5fe12-ab90-4bf3-ba59-b2dc4a8a02fe.png">
The received address is 0x0100. The MSB of address field should come first.

**Comment by eunchan** [comment]
sorry. received address is `0x01_0000`.

**Comment by eunchan** [comment]
Anyway, I found other issues regardless of this. While you are revising the test sequence, I will also try to revise the design for IO mode change.

**Comment by kosta-kojdic** [comment]
Fixed in #11780
