### ISSUE TITLE
[ci] CI intermittently fails to report status from Azure

### ISSUE THREAD

**Issue by milesdai** [lowRISC/opentitan#11772]
On March 24, 2022, Azure failed to report test status back to Github on at least two PRs (#11664 and #11667). The CI still ran and tested correctly, but something failed in the final reporting step. #11667 actually [failed CI](https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=73940&view=results) but because the status was not returned, this was not noticed and the PR was merged, breaking master. This behavior was also noted and caught manually in #11664.

At the moment, this bug cannot be reproduced, and there do not appear to be any other recent PRs where this happened. For now, we'll attribute this to some flakiness on the Azure side. Opening this issue to track any future occurrences.

**Comment by milesdai** [comment]
Agreed that this seems less likely to happen with native Github Actions integration. It might also be worth noting that Github appears to have been having some problems in March: 
[Github incident history](https://www.githubstatus.com/history?page=1)

**Comment by moidx** [comment]
@milesdai should we close as obsolete?

**Comment by milesdai** [comment]
Yes, we have not seen any additional problems like this recently.
