### ISSUE TITLE
[bazel] Check sha256s for all external repositories

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#11792]
Because of the potential for an engineered Sha1 collision, we should check the sha256 of external repos when they're downloaded.

**Comment by drewmacrae** [comment]
We should prefer http_archives that have support for sha256 checks, and use git_repository rules for components that are underdevelopment and not yet reproducible.

A git_repository rule that uses http_archive to carry this out isn't a big list but would require some legwork to find all the expected checksums and lock down all the dependencies.

**Comment by timothytrippel** [comment]
Require http_archive (with shas) rules over git_repository rules is also important/required to support air-gapped bazel builds.
