### ISSUE TITLE
Possible false CI check failure for vendoring

### ISSUE THREAD

**Issue by hcindyl** [lowRISC/opentitan#11811]
See https://github.com/lowRISC/opentitan/pull/11810/checks?check_run_id=5764658340

The failure is caused by the change in `util/lowrisc_misc-linters/licence-checker/licence-checker.py` in https://github.com/lowRISC/opentitan/pull/11810, but I am not sure this path should be included in git diff.

cc @rswarbrick

**Comment by rswarbrick** [comment]
The check that's failing is one that ensures vendored directories match their sources and the CI check is correct to fail on that PR :-D.

If you want to change vendored-in code, you have to do it in two stages:
- File a PR to update the source repository (the [misc-linters](https://github.com/lowRISC/misc-linters) repo, in this case)
- Once it's merged, use the vendor tool to grab the changes (something like `../opentitan/util/vendor.py -U -c -v util/lowrisc_misc-linters.vendor.hjson`)
