### ISSUE TITLE
[test] RISC-V Compliance depends on deprecated SW/Make

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#1181]
RISC-V compliance depends on building SW artifacts using Make, which is going away very soon. This dependency is, by the nature of how compliance has been vendored in, time-consuming to remove.

Since deleting Make is a major blocker for several foundational tasks in SW, such as #1078 and #1143, which themselves are major blockers for other work, we will be disabling RISC-V compliance in CI in #1154 until it can be fixed to use Meson. This decision was reached during this week's OT Software meeting.

This bug tracks both fixing that dependency and consequently re-enabling the CI step.

**Comment by GregAC** [comment]
I wanted to give the riscv-compliance suite a run to test the new higher performing Ibex configuration before I did a PR to enable that configuration.

So I started working on getting it going with meson.

A lazy answer is do `ninja -C build-out all` to get the various libraries built then in the riscv compliance makefile for the OT target point it towards the libraries in build-out and link against them individually. However this is a lot of libraries and it's rather brittle as any change to the library setup in meson will break the makefile.

I had a go at producing a meson 'riscv_compliance_library' target that would give you a single .a with everything in you could then point towards in the riscv-compliance makefile. This can be done by something like the following

```
riscv_compliance = static_library(
  'ot_riscv_compliance',
  objects : [some_lib.extract_all_objects(), ...]
```

The issues most of the libraries within meson are wrapped up inside a dependency object (`extract_all_objects()` works on the object returned directly from `static_library()`) I couldn't work out how to reach into that dependency object and grab out all of the libraries/objects.

I could rewrite a bunch of meson.build files so the static libraries are given explicit variable names before being used within a `declare_dependency` but this is quite a messy change just to support riscv-compliance.

We could build each compliance test binary individually with meson but given riscv-compliance is wedded to its makefile system uncertain how easy that would be.

@mcy @imphil thoughts?

(FYI I'm on holiday Friday/Monday so probably won't look at this til Tuesday now).

**Comment by mcy** [comment]
I took a look at Meson's docs, and I can't help but wonder if we're using `declare_dependency` wrong... one one hand, the docs say that it's the right thing for stuffing a dependency into another target. But they contradict themselves and say that the "main use case is for subprojects". I suspect that Meson just doesn't understand how really complicated projects like to structure libraries...

I suspect that the right answer (which I don't like, but whatever) is to do exactly what you say: rewrite our Meson files to expose the static library objects, and to  declare_dependency() in dependency lists.

Alternatively, there's apparently this "link_whole" argument for libraries, maybe that will work on dependency objects correctly?

**Comment by GregAC** [comment]
Forgot to reference this issue but I have a PR open that gets riscv-compliance working again:https://github.com/lowRISC/opentitan/pull/1965

To build the library I used a bit of a hack but at least it's confined to one meson.build only. You create a static library with dependencies including everything you'd like to link which I called the 'inner' library. You then create another static library using link_whole to link the 'inner' library and it works :)
