### ISSUE TITLE
Allow multiple verilator simulations to run in parallel

### ISSUE THREAD

**Issue by asb** [lowRISC/opentitan#1183]
There are issues with this due to devpts and fixed TCP ports (see e.g. #1155). Although both can be worked around with application of isolation technology like Virtual Machines or containers, this is a far from ideal solution. It should be possible to run multiple OT verilator instances in parallel on a single user account without a container for each one.

This can be used as a tracking issue. Multiple solutions are possible, e.g. using Unix Domain Sockets rather than TCP, cycling through TCP ports until an available one is found etc etc.

**Comment by imphil** [comment]
Effectively the same issue is tracked in #562.

**Comment by asb** [comment]
Thanks Philipp, I thought we had something but I failed to find it somehow. Closing this as a dupe.
