### ISSUE TITLE
Possible CPU bug: fault during lb/sb to RAM

### ISSUE THREAD

**Issue by cfrantz** [lowRISC/opentitan#11854]
# Description
While working on enabling ROM builds with bazel and clang, I ran into a fault in the test ROM while trying to print the ROM title string.

During test_rom execution, `printf` has to process it's format specifiers.  When built with no- or low- optimization (-O0 or -O1), the compiler emits this sequence of code for `consume_format_specifier`:

```
def struct format_specifier {
  char type;
  size_t width;
  char padding;
  bool is_nonstd;
} format_specifier_t;

static bool consume_format_specifier(buffer_sink_t out, const char **format,
                                     size_t *bytes_written,
                                     format_specifier_t *spec) {
  *spec = (format_specifier_t){0};
  ...
}
```

Emits the following asm:
```
        add     s0, zero, a4
.Ltmp88:
        #DEBUG_VALUE: consume_format_specifier:spec <- $x8
        .loc    1 184 11 prologue_end   # sw/device/lib/runtime/print.c:184:11
        sb      zero, 0(a4)
        lb      a4, 9(sp)
        sb      a4, 1(s0)
        lb      a4, 10(sp)
        sb      a4, 2(s0)
        lb      a4, 11(sp)
        add     s6, zero, a2
.Ltmp89:
        #DEBUG_VALUE: consume_format_specifier:format <- $x22
        sb      a4, 3(s0)
        sw      zero, 4(s0)
        sh      zero, 8(s0)
```

If I run this in verilator, the CPU appears to fault on the instruction `lb a4, 9(sp)`:

```
00009a98   consume_format_specifier+01c: c.mv       x8,x14           x0:0x00000000 x14:0x1001ff20  x8=0x1001ff20
00009a9a   consume_format_specifier+01e: sb         x0,0(x14)        x14:0x1001ff20  x0:0x00000000 PA:0x1001ff20 store:0x00000000 load:0x00000000
00009a9e   consume_format_specifier+022: lb         x0,9(x2)         x2:0x1001fed0  x0=0x00000000 PA:0x1001fed9 store:0x000098f6
00008000 _test_rom_interrupt_vector+000: jal        x0,8218          x0=0x00000000
00008218      _test_rom_irq_handler+000: csrrs      x10,mcause,x0    x0:0x00000000 x10=0x00000005
0000821c      _test_rom_irq_handler+004: csrrs      x11,mepc,x0      x0:0x00000000 x11=0x00009a9e
00008220      _test_rom_irq_handler+008: csrrs      x12,mtval,x0     x0:0x00000000 x12=0x1001fed9
00008224      _test_rom_irq_handler+00c: wfi
```

NOTE: the destination register is corrupted in the verilator decoded printout of the trace.  The destination register _is not_ `x0`, it is `a4` (`x14`).  The load address (PA:0x101fed9) is on the stack and should be accessible.

# To duplicate

Clone my repo which configures the compiler to clang:
```
git clone git@github.com:cfrantz/opentitan.git -b ibex_byte_fault ibex_byte_fault
cd ibex_byte_fault

./bazelisk.sh build //hw:verilator //hw/ip/otp_ctrl/data:rma_image_verilator //sw/device/lib/testing/test_rom

./bazel-bin/hw/build.verilator/sim-verilator/Vchip_sim_tb --meminit=otp,bazel-bin/hw/ip/otp_ctrl/data/rma_image_verilator.vmem --meminit=rom,bazel-out/k8-fastbuild-ST-b8775c98f59c/bin/sw/device/lib/testing/test_rom/test_rom_sim_verilator.scr.39.vmem
```

Wait for the CPU to hang (`tail -f trace_core_00000000.log`).  Send verilator a `CTRL+C` to get it to flush its output.  Examine the trace.

If you want a slightly more readable trace:
```
./tracerama.py --elf bazel-out/k8-fastbuild-ST-b8775c98f59c/bin/sw/device/lib/testing/test_rom/test_rom_sim_verilator trace_core_00000000.log >trace-annotated.txt
```

**Comment by GregAC** [comment]
Do you know if the aligned 32-bit region the byte being loaded has previously been written to? If it hasn't its ECC may be corrupt so when Ibex loads it sees an integrity failure triggering the exception.

**Comment by cfrantz** [comment]
> Do you know if the aligned 32-bit region the byte being loaded is located in has previously been written to? If it hasn't its ECC may be corrupt so when Ibex loads it sees an integrity failure triggering the exception.

Thanks Greg, that was the problem.  At some point in the past, we eliminated SRAM init from the test_rom (but not the mask_rom), making it vulnerable to this condition.
