### ISSUE TITLE
Create common rules about usable error messages

### ISSUE THREAD

**Issue by rminnich** [lowRISC/opentitan#1185]
%Error: target/riscv32imc-unknown-none-elf/release/rom.vmem:2: $readmem file address beyond bounds of array

This is a bit ridiculous. What was the address and what is the limit? This would be so easy to provide and is so hard to figure out. I think across the tree we should adopt rules about error messages that provide useful information, as opposed to something like the one above.

**Comment by imphil** [comment]
That error message is coming from Verilator, it's nothing we can directly influence. The ROM size is 8kB, and the current SW is very close to it last time I looked.

**Comment by imphil** [comment]
Memory loading has evolved a fair bit in the meantime and there's nothing directly actionable here, so let's close it for now.
