### ISSUE TITLE
[fpga] Manage bootrom as Vivado-managed file

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1186]
We currently include the bootrom vmem file without having it managed through Vivado. This needs a edalize update (https://github.com/olofk/edalize/pull/86), and https://github.com/imphil/opentitan/commit/75c644b7aec2888e33db4fdb0a8b9bc115d8be20. Let's wait for a couple more weeks to people pick up the edalize updates, and then move over.

**Comment by msfschaffner** [comment]
Is there more to do here or can this be closed?

**Comment by tjaychen** [comment]
i was actually meaning to try this out, but i don't think whatever @imphil mentioned here has been done.

**Comment by rswarbrick** [comment]
Well, we've definitely got the Edalize updates :-) See https://github.com/lowRISC/opentitan/pull/6426 for an attempt at using them.

**Comment by msfschaffner** [comment]
@timothytrippel is this still relevant in the way we build things today?

**Comment by a-will** [comment]
No, this is actually more of a burden than a feature. fusesoc's dependency tracking is inferior to bazel's (it was simply meant for a much more limited scope), and it would be harmful for maintenance of software builds if the location of the software output were hard-coded in a core file.

I'd be in favor of closing and electing not to implement.
