### ISSUE TITLE
[bazel] Teach Bazel how to vendor-in the remaining third-party software dependencies

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#11877]
Bazel has robust support for vendoring hermetic dependencies (as well as a mechanism for pre-downloading them through `bazel sync`). Most of our deps are already in this form, with some legacy ones left over using the unmaintained vendor script; this is just a matter of porting the ones that remain. `third_party` contains examples of how to do this.

This issue mostly exists to track the fact that this may or may not happen eventually and isn't really a judgement about it actually happening; if we choose not to it may require rolling back significant portions of the repository (esp. Rust crates vendored in through cargo raze).

**Comment by mcy** [comment]
My understanding is no one explicitly owns it, which therefore means it is unmaintained. The only person who ever worked on it has left the project afaik.

**Comment by GregAC** [comment]
It remains a crucial part of the HW side of things. There's no new features required and it's working fine for current purposes. So whilst there's no named maintainer it does get worked on as and what it's required.

Is your intent to retire it entirely from use in the SW side? That's fine but as there was a project wide decision to use that vendoring method we should properly revisit that decision and confirm we're happy with Bazel handling it for SW (which sounds like a good idea).

**Comment by cfrantz** [comment]
Unowned or unmaintained tools eventually suffer from bit rot.

Our intention is to fully convert software dependency management to bazel.  This will be part of the bazel conversion proposal given to the TC.

Longer terrm, we'll eventually place both HW and SW builds under the direction of bazel.  At that time, we'll also convert management of hardware vendoring to bazel (and as with sw, it will be part of the proposal to the TC).

**Comment by msfschaffner** [comment]
@timothytrippel @cfrantz has there been any update on this?

**Comment by timothytrippel** [comment]
This has been done now.
