### ISSUE TITLE
[LC_CTRL/rtl] FSM state FlashRmaSt doesn't detect bad MUBI value.

### ISSUE THREAD

**Issue by NigelScales** [lowRISC/opentitan#11874]
I see the rtl gets stuck in FlashRmaSt state when a bad value is seen on lc_flash_rma_ack_i
I think the FSM should enter invalid state.

```
      ///////////////////////////////////////////////////////////////////
      // Flash RMA state. Note that we check the flash response again
      // two times later below.
      FlashRmaSt: begin
        if (trans_target_i == {DecLcStateNumRep{DecLcStRma}}) begin
          lc_flash_rma_req = On;
          if (lc_flash_rma_ack[0] == On) begin
            fsm_state_d = TokenCheck0St;
          end
        end else begin
          fsm_state_d = TokenCheck0St;
        end
      end
```
![image](https://user-images.githubusercontent.com/78102677/161570171-cd0063e8-72f5-4e52-8704-2fa9df508e97.png)

**Comment by msfschaffner** [comment]
Ineed, this currently just checks for ON and will otherwise hang indefinitely (so this is the intended behavior in case of flash RMA req).

@tjaychen what is your view on this? 

We could check for invalid values - but if we did that we would have to change the synchronization scheme since this currently only synchronizes each individual bit separately (and I think for all the life cycle signals the plan was not to do that since we only ever distinguish between `== On` and `!= On`, or `==Off` and `!= Off`).

**Comment by NigelScales** [comment]
> One of the reasons for that is the CDC synchronization behavior of the life cycle multibit signals: The bits are all synchronized individually for reduced synchronizer complexity - so there could be stagger when the signals change. This is fine as long as you only ever check for an `ON` value here - but it also means that you could technically see invalid values for a cycle.

 @msfschaffner The CDC checker isn't going to like this method - it will be flagged as a CDC re-convergence error.
 I suggest you consider using a request/acknowledge synchroniser for each dynamic MUBI bus.

**Comment by NigelScales** [comment]
@msfschaffner I've fixed the error inject to wait for the FSM to get past FlashRmaSt but there is no error generated.

![image](https://user-images.githubusercontent.com/78102677/162463951-7ec91921-6a0e-4ba1-85d8-6e15a99be1a1.png)

**Comment by msfschaffner** [comment]
Ok it looks like the ACK synchronization delay of 2 cycles causes this to go unnoticed.

I have made the check more robust in #12031 by extending the token check window from 2 to 4 cycles, and by introducing an additional crosscheck during the programming phase.

**Comment by tjaychen** [comment]
> > One of the reasons for that is the CDC synchronization behavior of the life cycle multibit signals: The bits are all synchronized individually for reduced synchronizer complexity - so there could be stagger when the signals change. This is fine as long as you only ever check for an `ON` value here - but it also means that you could technically see invalid values for a cycle.
> 
> @msfschaffner The CDC checker isn't going to like this method - it will be flagged as a CDC re-convergence error. I suggest you consider using a request/acknowledge synchroniser for each dynamic MUBI bus that crosses clock domains.

@NigelScales this is definitely true.
But part of our principles for secure design is to minimize the number of single bit nets that are critical to security. The reason we don't usually use req/ack is because if the req/ack were attacked / severed in some way (for example tied to a fixed value) it would completely defeat our downstream security.

The idea of using multi-bits here of course is to make that kind of attack harder, but it also creates a lot of CDC unfriendly situations we have to deal with.

**Comment by NigelScales** [comment]
> > > One of the reasons for that is the CDC synchronization behavior of the life cycle multibit signals: The bits are all synchronized individually for reduced synchronizer complexity - so there could be stagger when the signals change. This is fine as long as you only ever check for an `ON` value here - but it also means that you could technically see invalid values for a cycle.
> > 
> > 
> > @msfschaffner The CDC checker isn't going to like this method - it will be flagged as a CDC re-convergence error. I suggest you consider using a request/acknowledge synchroniser for each dynamic MUBI bus that crosses clock domains.
> 
> @NigelScales this is definitely true. But part of our principles for secure design is to minimize the number of single bit nets that are critical to security. The reason we don't usually use req/ack is because if the req/ack were attacked / severed in some way (for example tied to a fixed value) it would completely defeat our downstream security.
> 
> The idea of using multi-bits here of course is to make that kind of attack harder, but it also creates a lot of CDC unfriendly situations we have to deal with.

@msfschaffner You can still keep the bus multi-bit but you synchronise it is as a whole.
The request/ack protocol controls the transfer of the bus - not the request/ack for the clock bypass say - this is controlled by the bus value so still multi-bit.

It works something like this:
- The control sees that the source clock version of the bus is different to the destination clock version.
- The source clock version is held stable and a request signal is sent to the destination clock side via double or triple FFs.
- When the request reaches the destination side the new bus value is copied into the destination FFs.
- An acknowledge is signal is sent back to the source side via 2/3 more FFs and this releases the latching for the source side.

This scheme is understood by CDC formal tools.
It adds a little latency but I don't think that's an issue for these busses.

**Comment by tjaychen** [comment]
@NigelScales your fix looks good to me. But I'm trying to figure out why this "any_fst_lp_match" was there to start with.
Let me dig through some old docs to make sure we've not removed some intended use case.
