### ISSUE TITLE
[sram] Investigate the SRAM issue - partial write followed by read

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#11892]
The issue should be caught by this sequence - partial write -> b2b read with the same address.
Let me reproduce this case and take a closer look.

cc: @GregAC @tjaychen @msfschaffner

**Comment by weicaiyang** [comment]
This is probably the case that should reproduce this issue.
However, the `wmask_q` is always all 1s, so that the issue won't really fail anything in SRAM_CTRL.

![Screen Shot 2022-04-04 at 2 40 29 PM](https://user-images.githubusercontent.com/49293026/161637247-8a78011d-d151-4b04-b536-d155b7f1aa84.png)

@msfschaffner can you please confirm this?

In case that you want to check the waves, here it is. The partial write followed by read happens at 58746523ps.
ot_debug -J smart:02b245de-3e49-4845-a441-267350e4bf71

**Comment by tjaychen** [comment]
ah.. i wonder if this is because of the byte handling.
So if you do a byte write, it ends up being stalled for that. If you do a
full word write, it won't matter anyways.

**Comment by weicaiyang** [comment]
> ah.. i wonder if this is because of the byte handling. So if you do a byte write, it ends up being stalled for that. If you do a full word write, it won't matter anyways.

I guess so. I wonder where @GregAC found this issue. Did it cause some failures in other block or top-level?

**Comment by tjaychen** [comment]
i'm guessing this was found in otbn maybe?

**Comment by GregAC** [comment]
> ah.. i wonder if this is because of the byte handling.
So if you do a byte write, it ends up being stalled for that. If you do a
full word write, it won't matter anyways.

Yup a byte write followed by a read won't trigger the issue

> i'm guessing this was found in otbn maybe?

It was. It's a 256-bit memory we do 32-bit partial writes to. We scramble on a 32-bit granularity so the 32-bit write doesn't need a RMW cycle.

**Comment by weicaiyang** [comment]
@GregAC Thanks for the clarification, so sram_ctrl is fine. Closing this issue.
