### ISSUE TITLE
[lc_ctrl/dv] Define testing required for security countermeasures

### ISSUE THREAD

**Issue by NigelScales** [lowRISC/opentitan#11919]
The descriptions in file lc_ctrl_sec_cm_testplan.hjson are very terse.
e.g. desc: "Verify the countermeasure(s) MAIN.FSM.LOCAL_ESC." 

We need to agree on what testing is required to verify these testpoints.
They may already be covered by tests which are written and just require some whitebox coverage to ensure they are being comprehensively tested.

I'll add each vague testpoint RTL as a comment and then we can discuss what's needed to fulfil the verification requirement.

**Comment by NigelScales** [comment]
```
    // If at any time the life cycle state encoding or any other FSM state within this module
    // is not valid, we jump into the terminal error state right away.
    // Note that state_invalid_error is a multibit error signal
    // with different error sources - need to reduce this to one bit here.
    // SEC_CM: MAIN.FSM.LOCAL_ESC
    if (|state_invalid_error | token_if_fsm_err_i) begin
      fsm_state_d = InvalidSt;
      state_invalid_error_o = 1'b1;
    // SEC_CM: MAIN.FSM.GLOBAL_ESC
    end else if (esc_scrap_state0_i || esc_scrap_state1_i) begin
      fsm_state_d = EscalateSt;
    end
```

**Comment by msfschaffner** [comment]
Thanks for filing this issue, @NigelScales.
I have updated the description of the testplan items here: #11969
Let me know if more detail is needed.

**Comment by NigelScales** [comment]
> Thanks for filing this issue, @NigelScales. I have updated the description of the testplan items here: #11969 Let me know if more detail is needed.

I think the only testpoint which is unclear how to test is sec_cm_main_ctrl_flow_consistency.
I can't think of a way to fully positively test that.
I think what you probably need is a property to be used with a formal tool that demonstrates that no state can be transitioned to twice between resets.

**Comment by msfschaffner** [comment]
@NigelScales indeed, this is what I have been thinking as well. FPV is likely the better route for this than a simulation-based test.
