### ISSUE TITLE
[ci] DO NOT MERGE and other premerge checks

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#1191]
A few people (mostly me, but still) like to use comments of the form "DO NOT MERGE" and "DO NOT SUBMIT" to indicate that a change should not be merged. This is primarily useful for marking a pending change as a "draft" at code locations that are still unresolved in some manner.

I think it would be useful to have a CI job that looks for this line in added lines and slams the breaks if it finds any. Better yet, it might be useful to have this job do a more general "if this regex was added, or removed, in such and such file, slam the breaks". You could also imagine novel uses, like guarding against variants of printf debugging.

What do folks think of this idea?

**Comment by mcy** [comment]
@imphil what do you think?

**Comment by imphil** [comment]
Hm, I did comment a couple days ago, but apparently this comment never got submitted or disappeared... So let's try again.

GitHub has a feature which allows you to mark PRs as draft. This is probably what you're looking for. 

If you prefer you can also use textual markers like DO NOT MERGE. I don't see the need to enforce this in CI: it's the job of the committers and reviewers to take care of that and not merge things which clearly are not intended for it.

**Comment by mcy** [comment]
> it's the job of the committers and reviewers to take care of that and not merge things which clearly are not intended for it.

I'm not sure I agree with this, insofar that we should have as many things enforced by the computer as possible. Humans make mistakes, computers generally don't.

**Comment by imphil** [comment]
That's why the draft functionality exists and prevents merging. How does that not work for you?

**Comment by mcy** [comment]
Not really, no. I'm interested in marking parts of the change as being incomplete or unresolved, without having to fuss around with keeping the PR description in sync.

**Comment by imphil** [comment]
I'm not sure we're talking about the same thing. The draft feature, as described in https://github.blog/2019-02-14-introducing-draft-pull-requests/, allows you to mark a whole PR as draft. There's no modification of the description or the commits needed.

A PR is always merged as a whole, so if any change is incomplete or a draft, then the whole PR is in that status.

**Comment by msfschaffner** [comment]
AFAIK there is also a "WIP" blocker app that blocks when your PR has "WIP" in the title:

https://github.com/wip/app

Maybe that could be useful...

**Comment by rswarbrick** [comment]
@mcy: Is this still worth tracking? We seem to be using draft PRs happily and I don't *think* anyone has merged a "DO NOT MERGE" commit in the two years I've been on the project.

Personally, I think it looks like our social conventions (committers are expected to know what they are doing) are working just fine.

**Comment by msfschaffner** [comment]
@moidx WDYT about this one?
