### ISSUE TITLE
[Sysrst_ctrl] V2 Review items

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#11928]
This issue captures AIs from Sysrst_ctrl V2 review [notes](https://docs.google.com/document/d/1hH7gABLqXkuCIDdRcmf-mLlbqgBF8eFwe_2is_Q2-Ak/edit#)

- [x] [Madhuri] update testplan and covergroup #[11820](https://github.com/lowRISC/opentitan/pull/11820)
  - Update the testpoint `sysrst_ctrl_flash_wr_prot_out` to include checking the input.
  - Change the sample point of combo detect to sample it after the event occurs
  - Combo detect covergroup - need to cover all input combinations on all possible outcomes, so that the full matrix of input combinations to outcomes is covered. Simply covering the programmed combinations alone may not be sufficient. 
      - One strategy is to sample the covergroup in the scoreboard on the outcome (i.e. output triggering). You can use the 
    - knowledge of the CSRs programmed via mirrored value in the RAL and you can lookup the IO input / output values via the cfg handle. 
  - ULP wakeup - treat similar to combo detect covergroup 
  - More notes in PR [11820](https://github.com/lowRISC/opentitan/pull/11820)
- [x] [Madhuri] Ensure fcov over 70% after all fcov are implemented
- [x] [Madhuri] Cover toggle coverage for Aon_sysrst_ctrl_rst_req_o
- [x] [Madhuri] Cond and FSM coverage are below 90%, which may be due to the failure of combo_detect test. Fix the combo detect test, then we can consider running UNR to bump the coverage.
- [x] [Michael] Add assertion check for all output enables which are tied to 1 #11936
- [x] [Madhuri] Remove CSR exclusion at KEY_INTR_STATUS
- [x] [Madhuri] Resolve this issue #12029

**Comment by patel-madhuri** [comment]
> This issue captures AIs from Sysrst_ctrl V2 review [notes](https://docs.google.com/document/d/1hH7gABLqXkuCIDdRcmf-mLlbqgBF8eFwe_2is_Q2-Ak/edit#)
> 
> * [x]  [Madhuri] update testplan and covergroup #[11820](https://github.com/lowRISC/opentitan/pull/11820)
>   
>   * Update the testpoint `sysrst_ctrl_flash_wr_prot_out` to include checking the input.
>   * Change the sample point of combo detect to sample it after the event occurs
>   * Combo detect covergroup - need to cover all input combinations on all possible outcomes, so that the full matrix of input combinations to outcomes is covered. Simply covering the programmed combinations alone may not be sufficient.
>     
>     * One strategy is to sample the covergroup in the scoreboard on the outcome (i.e. output triggering). You can use the
>     * knowledge of the CSRs programmed via mirrored value in the RAL and you can lookup the IO input / output values via the cfg handle.
>   * ULP wakeup - treat similar to combo detect covergroup
>   * More notes in PR [11820](https://github.com/lowRISC/opentitan/pull/11820)
> * [ ]  [Madhuri] Ensure fcov over 70% after all fcov are implemented
> * [x]  [Madhuri] Cover toggle coverage for Aon_sysrst_ctrl_rst_req_o
> * [ ]  [Madhuri] Cond and FSM coverage are below 90%, which may be due to the failure of combo_detect test. Fix the combo detect test, then we can consider running UNR to bump the coverage.
> * [x]  [Michael] Add assertion check for all output enables which are tied to 1 [[all] Add assertions for constant output enables  #11936](https://github.com/lowRISC/opentitan/pull/11936)
> * [x]  [Madhuri] Remove CSR exclusion at KEY_INTR_STATUS
> * [x]  [Madhuri] Resolve this issue [[sysrst_ctrl, dv] Trigger multiple interrupt events when the core clock is off  #12029](https://github.com/lowRISC/opentitan/issues/12029)
