### ISSUE TITLE
[cleanup] Add assertion check for all output enables which are tied to 1

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#11929]
This is an item from Sysrst_Ctrl review.

We can consider updating the checklist as well. 
In this [ASSERT_KNOWN_ADDED](https://github.com/lowRISC/opentitan/blob/master/doc/project/checklist.md#assert_known_added), if it's tied to a fixed value, instead of checking it's a known value, we can check it with the actual value.

**Comment by msfschaffner** [comment]
I went through the IPs and fixed the ovious ones: #11936
