### ISSUE TITLE
[spi_device] Does `generic_rx_overflow` reflect whether an overflow occurred in the payload segment?  If not, can we add a payload  overflow status bit?

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#11935]
Does `generic_rx_overflow` reflect whether an overflow occurred in the payload segment?  If not, can we add a payload  overflow status bit?

_Originally posted by @cfrantz in https://github.com/lowRISC/opentitan/pull/11884#discussion_r842984786_

**Comment by eunchan** [comment]
It does not cover the case unfortunately.

Yes, as in previous github issue, I think it is good to have. I think, on top of this, SPI_DEVICE should report the last written address (or write pointer in the payload buffer) so that SW is able to know the first valid byte position.

**Comment by eunchan** [comment]
@alphan Recent PRs addressed this. Can we close the issue?
