### ISSUE TITLE
Clang complains about unknown flag.

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#11946]
Seen when building with Bazel:
```
clang-11: warning: argument unused during compilation: '-nostdinc++' [-Wunused-command-line-argument]
```

Presumably bazel-embedded is doing something rude.

**Comment by alphan** [comment]
I don't think so. I checked the log [here](https://dev.azure.com/lowrisc/4c50229e-f6cb-4f39-8522-585bb3841438/_apis/build/builds/92428/logs/132) and couldn't find any related lines.
