### ISSUE TITLE
[entropy_src] Detailed timing of Observe FIFO Clear pulses

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#11951]
The `entropy_src` scoreboard anticipates that _all internal state_ is cleared one cycle after the `module_enable` register is set to false.

It has however been observed that the Observe FIFO is not cleared for three cycles after the `module_enable` signal is cleared.

![image](https://user-images.githubusercontent.com/47870387/162019594-f33a939f-8ca1-4d4b-b7d5-281085472257.png)

As this is causing failing seeds, either the scoreboard timing or the DUT need to be changed to properly predict these edge cases.

For instance, the simplest solution may be to return `'0` whenever this FIFO is read and the device is disabled.

**Comment by mwbranstad** [comment]
The two delays from setting the bit and setting the observed FIFO clear input can be explained by the tlul reg block (1 delay) and the re-flop for the module enable ( part legacy and part fanout help). Seems like the scoreboard needs some adjustment to handle this delay.

**Comment by martin-lueker** [comment]
Two questions:

1. Will there be any variation in this? (is it always three cycles?)  
2. Should an alert be expected if we read after this time?

**Comment by mwbranstad** [comment]
it appears to be a simple propagation (no gating) so yes, 3 clocks. 
I would not expect an alert based on reading the observe FIFO, or any other one that I can think of.

**Comment by tjaychen** [comment]
should we add a clarification note into the spec on when we can expect the entire to be cleared after de-assertion of enable?
