### ISSUE TITLE
[top] Move tb "simulated" memory to scratch registers

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#11965]
to address #10863 and eventually facilitate gate level simulation, @sriyerg suggested that we move the testbench simulated memory (which uses a fake address) to real scratch registers within a module (fewer than 32 bytes are needed)

This will avoid situations where a pmp entry needs to be created for a memory that isn't actually there, but also allow these tb functions to be reused during gate level sims.

As a part of this, anywhere that dv might tap during gate level sims should also be tagged with primitive buffers to ensure a particular signal persists in both rtl and netlist world. 

@sriyerg let me know if i missed anything.

**Comment by timothytrippel** [comment]
If this gets implemented, then we no longer need #10863 (which would be wonderful :) ).

**Comment by tjaychen** [comment]
please re-open if #12148 does not work for any reason.
