### ISSUE TITLE
[flash_ctrl/dv] Clean up replicated constraints and resolve unaddressed comments

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#11967]
@nikola-miladinovic @TimEwins 

Some constraints like `mp_regions_c`, `flash_op_c` are replicated in many sequences. This is not a good practice as they're hard to maintain in the future. The better approach is to put those generic constraints in base sequence, then in sub-sequence, add more constraint on top of that or override it if needed.

Also address these 2 comments from @rswarbrick 
1. https://github.com/lowRISC/opentitan/pull/11411/files#r828977881
2. https://github.com/lowRISC/opentitan/pull/11411/files#r828980856

Let's address this before V2

cc: @jdonjdon

**Comment by jdonjdon** [comment]
> @nikola-miladinovic @TimEwins
> 
> Some constraints like `mp_regions_c`, `flash_op_c` are replicated in many sequences. This is not a good practice as they're hard to maintain in the future. The better approach is to put those generic constraints in base sequence, then in sub-sequence, add more constraint on top of that or override it if needed.
> 
> Also address these 2 comments from @rswarbrick
> 
> 1. https://github.com/lowRISC/opentitan/pull/11411/files#r828977881
> 2. https://github.com/lowRISC/opentitan/pull/11411/files#r828980856
> 
> Let's address this before V2
> 
> cc: @jdonjdon

This issues are addressed in #14411

**Comment by jdonjdon** [comment]
This issues are addressed in https://github.com/lowRISC/opentitan/pull/14411
