### ISSUE TITLE
[fpga] Make USR_ACCESS available for software read

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#11964]
The fpga bitstream information should be made available for software read.
See https://docs.xilinx.com/v/u/en-US/xapp1232-bitstream-id-with-usr_access

We can do this by adding another prim module that instantiates the primitive for fpga and 0 otherwise.

Currently I'm thinking about adding this register into `rv_core_ibex`, but it could go elsewhere also.
`lc_ctrl` isn't really necessary in this case since this is not a feature we really ever expect to make use of in silicon.

**Comment by tjaychen** [comment]
@cfrantz 
@a-will 
@timothytrippel

**Comment by a-will** [comment]
That sounds like a good place and plan to me. If I were thinking about it generically, it looks like some sort of extended chip ID.

**Comment by tjaychen** [comment]
yeah the chip ID actually goes into `lc_ctrl`, since it can be reached even if the device is dead.
The only reason I'm not placing this there is because...there's really no situation in real silicon where we might need that.
Plus `lc_ctrl` is at d2s and i really don't want to re-open it :)
