### ISSUE TITLE
[ci] uses Python 3.6 which has gone EOL

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#11984]
https://endoflife.date/python shows python 3.6 as EOL. We should upgrade CI and our minimum requirements to a supported version of Python or avoid the requirement

**Comment by drewmacrae** [comment]
Preferred resolution would be to use python from the Bazel workspace and just not worry about what version of python runs on the CI machines.

**Comment by msfschaffner** [comment]
This will be handled implicitly once we move to Ubuntu 20 LTS. This is planned but may slip into M3.

**Comment by moidx** [comment]
This task is now complete.
