### ISSUE TITLE
[opentitantool] move the `LoadBitstream` command under an `fpga` command

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#11995]
Currently there is a top-level `LoadBitstream` command within opentitantool. However, as we add more FPGA-related commands, it makes sense to move this command under a new top-level `fpga` command.

**Comment by timothytrippel** [comment]
CC: @cfrantz, @arunthomas

As we discussed earlier today.

**Comment by msfschaffner** [comment]
Any updates?

**Comment by timothytrippel** [comment]
This is done.
