### ISSUE TITLE
Incorrect behaviour of base_printf 

### ISSUE THREAD

**Issue by sub-Shodan** [lowRISC/opentitan#12011]
#### Issue description
The function base_printf when used with modifier %d does not produce any output after first "0" is encountered.

#### Steps to reproduce the issue

1.   Calling base_printf().
2.   using %d as modifier.
3.  Example:  base_printf("test %d: text after zero", 0,); 

#### What's the expected result?
- The result should be:  
- ```test 0: text after zero```

#### What's the actual result?
- The result:  
- ```test```

#### Additional details
base_printf() function as defined in /sw/device/lib/runtime/print.c 
Reference pull request: https://github.com/lowRISC/opentitan/pull/11257
@mcy

**Comment by drewmacrae** [comment]
This has been fixed and is now covered by a unittest: https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/lib/runtime/print_unittest.cc;drc=32355ad9c593d2b323a5c7e5ecaa975919ab9ae3;l=153
