### ISSUE TITLE
[ip/spi_device] there are 4 cycles window where we can't know a word data in FIFOs

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#1203]
@eunchan I found an interesting case.
There are 4 cycles between RX async FIFO level changing to 0 (empty to 1) and RX sram FIFO wptr being updated. Within this window, if we read async_fifo level and sram FIFO pointers, we will find both FIFOs are empty but there are a word of data in transfer between 2 FIFOs.

Should we either update async FIFO ptr later, or update sram FIFO earlier to fill this gap?

In simulation, I try to wait for RX async fifo empty to change from 0 to 1 (expect some data have been received), then read sram FIFO pointer, but the pointer value indicates nothing in sram FIFO.

Here is the waveform
/edascratch/weicai-opentitan/ot/spi_device/spi_device_fifo_underflow_overflow/test
verdi -ssr Verdi.ses &

**Comment by eunchan** [comment]
That is expected behavior. We cannot delay updating async FIFO pointer as SCK can be shut off. And cannot update SRAM FIFO pointer earlier as it has to read from FIFO and request send to arbiter then update the pointer.

**Comment by tjaychen** [comment]
@eunchan @weicaiyang 
we might want to be a bit careful here, especially on guidance to software.

Is software in general supposed to be reading the async fifo level? Because if they do as Weicai suggested, and actually find sram to be empty, I can see this causing a lot of confusion for software.

The way I had viewed this is that software would primarily be using the SRAM pointers / levels to figure out number of entries, and the async fifo read is more of a debug feature, especially since there can be ambiguity between clock domains.

**Comment by eunchan** [comment]
On Mon, Dec 16, 2019 at 10:26:58AM -0800, tjaychen wrote:
>@eunchan @weicaiyang
>we might want to be a bit careful here, especially on guidance to software.
>
>Is software in general supposed to be reading the async fifo level? 
>
No. SW suffices to read SRAM FIFO, any data inside RX ASYNC FIFO goes into SRAM 
eventually, and TX ASYNC FIFO will be sent out when SCK is active.

> Because if they do as Weicai suggested, and actually find sram to be empty, I can see this causing a lot of confusion for software.
>
>The way I had viewed this is that software would primarily be using the SRAM pointers / levels to figure out number of entries, and the async fifo read is more of a debug feature, especially since there can be ambiguity between clock domains.
>

Your understand is correct. Initial design doesn't have async fifo levels and 
they were added for debugging purpose (to check whether any pending items when 
hang)

**Comment by tjaychen** [comment]
sounds good. It might be good to clarify this in the programmers guide.
Just to make sure a user doesn't end confusing one for the other.  I can
definitely imagine someone getting confused and checking the async level,
and then reading the SRAM directly, and occasionally reading wrong data
(this language might already be in the spec, sorry I can't completely
remember).

**Comment by weicaiyang** [comment]
Agree that async fifo level is used for debug purpose as well as async fifo empty/full. And it's good to clarify it in document.
