### ISSUE TITLE
[dv/ast] Recreate vc main power glitch

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#12048]
The full chip testpoint chip_sw_pwrmgr_main_power_glitch_reset needs to cause the ast to trigger a main power glitch in order to verify the chip response. In order to trigger this condition the test toggled u_ast.vcmain_supp_i. Apparently some AST change must have caused this to stop working.

We need to know what mechanism can be used in order to cause this condition again.

**Comment by matutem** [comment]
We need it for ASIC, but I cannot say if the other platforms need it as well.

**Comment by Jacob-Levy** [comment]
@matutem For now in ASIC, you can bypass the use of the `vcmain_supp_i/vcaon_supp_i` by force/release the regulators
`vcmain_pok_h_o/vcaon_pok_h_o` local signals to emulate the power spike.:

  ` u_ast.u_rglts_pdm_3p3v.vcmain_pok_h_o`    for VCMAIN and
  ` u_ast.u_rglts_pdm_3p3v.vcaon_pok_h_o`      for VCAON

**Comment by tjaychen** [comment]
sounds good, thanks @Jacob-Levy , forcing an internal node works for purposes too i think.

**Comment by matutem** [comment]
Thanks Jacob. This works, and after #12120 a few related tests should pass.
