### ISSUE TITLE
[prim] prim_flop_2sync depends on non-synthesizable code

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#12046]
Commit 43a24e6 added `lowrisc:prim:cdc_rand_delay` as a dependency of `prim_flop_2sync.core`. This causes lots of lint messages and I suspect will be an issue for the synthesis flow as well.

Would it make sense to depend on this from some DV base class instead?

@sriyerg, @weicaiyang, @cindychip: What do you think?

**Comment by rswarbrick** [comment]
Ohh. I think we just need an `ifndef VERILATOR` in the file: the module contents are already stubbed out for synthesis.

**Comment by weicaiyang** [comment]
> Ohh. I think we just need an `ifndef VERILATOR` in the file: the module contents are already stubbed out for synthesis.

this sounds good.

**Comment by tjaychen** [comment]
sounds good to me as well.
I have another PR parallel to this that adds the missing waiver file (which
breaks ascentlint runs).

**Comment by sriyerg** [comment]
Suggest adding +define+DISABLE_PRIM_CDC_RAND_DELAY to verilator instead.

**Comment by rswarbrick** [comment]
Sorry, Sri! I just realised that I hadn't replied to this. Yes, I agree: it's in my queue of tidy-ups to do!

**Comment by rswarbrick** [comment]
Oh, again! It turns out that that's what I'd done in https://github.com/lowRISC/opentitan/pull/12047: apparently I'd come to the same conclusion as you, @sriyerg :-D
