### ISSUE TITLE
[spi_device] fifo2sram_adapter enhancement

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#12054]
#12053 revises the `spid_upload` module to create an overflow event and to track the pointer of the FIFO.

It would be easier if `spid_fifo2sram_adapter` (eventually `prim_fifo2sram_adapter`) provides the overflow event at the same cycle when the producer side pushes an entry when the FIFO is full.

Issue here is:

- fifo2sram only writes data to SRAM no way to track the consumer side.
- SPI_DEVICE upload logic requires to keep update the data in SRAM even in full case.

Plan:

- At lease, for now, adds clear port to reset the pointer (currently `rst_ni` does that)
- Make the module configurable to be able to write when full (currently this is the default behavior)

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. I think this is not relevant for this release because we have a mechanism that *works*, though this issue proposes a cleaner implementation IIUC. Thus keeping https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease.

**Comment by msfschaffner** [comment]
CC @a-will

**Comment by a-will** [comment]
Currently, `spid_fifo2sram_adapter` is only used in contexts where SPI-side overflow is not possible. For flash, wrapping is the correct behavior, and for TPM, we stop writing once the requested amount of data has been received.

For the TPM Read FIFO, overflow would cause bizarre behavior, but software has an explicit length that only lasts for the current command. We probably don't need to go the extra mile to protect software from this specific case.

Closing, as there is no planned use case. Please re-open if I've made an error.
