### ISSUE TITLE
Entropy Source - health checks  (NIST SP800-90b + Bucket and Markov tests)

### ISSUE THREAD

**Issue by lfrojasm** [lowRISC/opentitan#12058]
I am currently working on an FPGA implementation of an RNG. At the moment I am performing its validation using the standard tests published in the NIST SP800-22 (R1a) and the results are quite promising, however, the NIST SP800-90b includes 2 health checks for entropy sources that I would like to perform as well.

I was reading the OpenTitan documentation, focused on the entropy source section, and I saw that 4 health checks are applied (NIST SP800-90b + Bucket and Markov tests).

I've been looking for an official NIST website with a software implementation of these tests, but my search so far has been fruitless, so I was wondering if you happen to have information on an official NIST website where these codes are available or if you located them from a different source.

Grateful for your attention, I remain attentive to any information you can share with me regarding this topic.

**Comment by rswarbrick** [comment]
@martin-lueker: I suspect you're the best person to point in the right direction?

**Comment by martin-lueker** [comment]
Hi @lfrojasm, 
   I'm not aware of any implementation of these, though they are fairly trivial to implement.  The pseudo-code in SP 800-90B is often a bit opaque, however these two are relatively straightforward.  You can find them in sections 4.4.1 and 4.4.2 of [SP 800-90B](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-90B.pdf).
   The Repetition count test, simply counts the length of uninterrupted 1's or 0's or zeros and compares them to a threshold value to determine whether or not the bits are "stuck". 
   The general intent for adaptive proportion is to count the number of 1's or 0's in a window, and signal an error if they get too far from the expected 50%.    
   The exact value of the thresholds for both tests (how do you define "too far"?) is a question all unto itself.   The question requires an understanding of the expected weaknesses (e.g. any fundamental bias in the design of the physical noise source, acceptable variability in manufacturing processes, etc).  From this you can generate tolerances for the statistical bias of the raw noise source, and from there you can assess the likelihood of false positives for a given noise source.   The NIST SP gives a formula for calculating "one in a million" false positive rates (assuming an idealized noise source).   
   For us, the thresholds are completely controllable by firmware, which gives us some flexibility to adjust them in response to the observed properties of our analog noise source.  Issue https://github.com/lowRISC/opentitan/issues/2111 has been notably open for a long time, though I hope to close that soon.

**Comment by msfschaffner** [comment]
Closing since I assume the question has been answered.
Please re-open if that is not the case.
