### ISSUE TITLE
[otbn] Spurious WE strobe check on both regfiles

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#12055]
We have reason to believe that WE strobes on regfiles are prone to glitch attacks, hence we decided to augment the Ibex register file and the peripheral CSR nodes with additional checks that trigger alerts in case a spurious WE is seen:
- https://github.com/lowRISC/ibex/pull/1605
- https://github.com/lowRISC/opentitan/issues/11036#issuecomment-1076939473.

Should we do the same on the OTBN register files?

This check would leverage `prim_onehot_check` which has been optimized to have minimal area and delay overhead - see https://github.com/lowRISC/opentitan/pull/11994.

**Comment by tjaychen** [comment]
i think for otbn it is not quite as critical due to the fact that there is always a host processor controlled redundancy.
However, if it is cheap to add, I think it would be worth it.

**Comment by msfschaffner** [comment]
Adding these checks should be straightforward and they are pretty lightweight. 
Let me take a look.

**Comment by GregAC** [comment]
I think it's worth doing, still a reasonable chunk of D2S to close out so shouldn't prove disruptive to that, especially if @msfschaffner can do the RTL work.

**Comment by tjaychen** [comment]
should we close this issue now? as it relates to otbn, i think all the work is done?
