### ISSUE TITLE
[spi_device] Upload Command Payload Buffer Address

### ISSUE THREAD

**Issue by kosta-kojdic** [lowRISC/opentitan#12059]
@eunchan What is the starting offset in the spi_device buffer for 256B of Upload buffer data?

**Comment by kosta-kojdic** [comment]
@eunchan how configurable Mailbox address impacts the offset of Upload buffer?

**Comment by eunchan** [comment]
the Mailbox Address CSR is for the host address. the upload buffer offset is for the internal memory mapped address. So, changing mailbox address CSR will divert the read command address to the mailbox space when the address is in mailbox space.

**Comment by kosta-kojdic** [comment]
Just one more question, if we configure MAILBOX_ADDR_CSR to some value, any host issued address between:
MAILBOX_ADDR_CSR:MAILBOX_ADDR_CSR+1kB will read from fixed Mailbox space inside buffer?
So if host address is MAILBOX_ADDR_CSR+4 will it read from offset 0x804 from buffer?

**Comment by eunchan** [comment]
Yes. That is what I expect.
