### ISSUE TITLE
[bazel] Support multiple sets of compilation configurations for device binaries and their dependencies

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#12065]
Binaries (targets) that will run on the device, such as the ROM, ROM_EXT and test binaries, will likely need to be compiled with different sets of compiler/linker options . For example:

- Enabling the compiler's hardening features in the ROM/ROM_EXT but not in test code
- Enabling position independent code (PIC) generation in the ROM_EXT but not the ROM

These compiler options need to be applied to all of the dependencies of the target and dependencies may be shared between different targets. This means that some targets will need to be compiled more than once with different options. For example, both the ROM and ROM_EXT depend on the UART driver and so it will need to be compiled at least twice if we have PIC enabled in the ROM_EXT.

**Comment by mundaym** [comment]
We discussed this in the Software WG meeting today (2022-04-12):

The consensus was that we will try and use the same approach (i.e. adding new target platforms) that we are currently taking to do separate host and device builds. This work will be done once the transition from meson to bazel is complete. We will need to put some thought into how we specify platforms since triples alone may not be appropriate.

**Comment by timothytrippel** [comment]
This should be handled as part of #19493, closing this now, but feel free to reopen if needed.
