### ISSUE TITLE
[otbn,rtl] Multi-bit encode secure wipe signals

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#12061]
At the moment, we pass around signals like `sec_wipe_zero_i` and `sec_wipe_acc_urnd_i`. It's probably a better idea to make a sparse enum to represent the different secure wipe stages (and generate errors if we see an invalid value).

The problem is that at the moment, an attacker could poke e.g. `sec_wipe_zero_i` to zero out the result of an arbitrary calculation.

As a side effect, it might also make the code a bit cleaner.

@GregAC, @vogelpi: Thoughts?

**Comment by vogelpi** [comment]
This sounds like a good idea to me. Especially with the blanking in place, these signals are additionally flopped (glitching the flops is considered easier). However, I think this should have lower priority than the other outstanding D2S tasks.

**Comment by rswarbrick** [comment]
I think we've de-scoped this. Removing D2S milestone accordingly.

@GregAC: Please put it back if I'm wrong :-)

**Comment by GregAC** [comment]
I've tagged with FutureRelease as it's probably a good thing to do but not essential now.

**Comment by johannheyszl** [comment]
Thx @vogelpi so let's have it as candidate for M3 with P2?

**Comment by vogelpi** [comment]
> Thx @vogelpi so let's have it as candidate for M3 with P2?

Yes, this sounds right to me @johannheyszl , thanks for taking a look!

**Comment by andreaskurth** [comment]
@GregAC will hand over the current state of his work to @vogelpi, expected completion early next week.

**Comment by GregAC** [comment]
@vogelpi work so far is here: https://github.com/lowRISC/opentitan/pull/22862
