### ISSUE TITLE
[pwrmgr] v2s required fixes on design

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#12072]
- [ ] allow main_pd glitch to also cause an alert
- [ ] clarify in the documentation / countermeasure naming the difference between local_esc and terminal
- [ ] clarify in documentation (if not already) how local escalation resets are different from normal reset requests. 

The result of these changes is the following:
esc_rx timeout and main_pd glitch both will cause alerts and local escalation. Local escalation behavior is identical to global escalation which causes the pwrmgr to enter a reset sequence.

sparse fsm countermeasure does not cause a local escalation, but instead freezes the system in a terminal state until user or host intervention.

**Comment by tjaychen** [comment]
hey all, let me know if this is about right.

**Comment by jdonjdon** [comment]
LGTM
