### ISSUE TITLE
RFC: Crypto Library Specification

### ISSUE THREAD

**Issue by y-srini** [lowRISC/opentitan#12071]
## Objective

The objective of this RFC is to collect feedback on the Crypto library specification for OpenTitan. 

The RFC is currently in open for comments. We are aiming to finalize the specification before presenting it to the Technical Committee for a review and subsequently publishing it. 

### What is Crypto library specification?
(Need OpenTitan account to access the spec. Kindly request access if blocked). 

This [Crypto library specification](https://docs.google.com/document/d/1bbEaRCejPLvlipztXCd3HSBRxCxlV_Wdiv0d9yBw_Uc) is intended for users of the OpenTitan crypto library. It defines the C interfaces (APIs), data structures and several implementation specific details for the required cryptographic services. 

The inputs for required cryptographic support was collected from multiple stakeholders using a [cryptographic use case document](https://docs.google.com/document/d/1fHUUL4i39FJXk-lbVNDizVZSWObizGE2pTWVhQKb41c). Based on the inputs, the following are the crypto algorithm and modes that are intended to be supported.  

- Symmetric crypto
   - AES {ECB, CBC, CFB, OFB, CTR}
   
- AEAD
   - AES {GCM, KWP}
 
- HASH
   - SHA2 {256, 384, 512}
   - SHA3 {224, 256, 384, 512}

- HASH-XOF
   - SHAKE {128, 256}
   - cSHAKE {128, 256}

- MAC
   - HMAC-SAH256
   - KMAC {128, 256}
  
- Asymmetric crypto (Supports asynchronous APIs)
   - Keygen: {RSA Keygen, ECDSA Keygen, ECDH Keygen, Ed25519 Keygen, X25519 Keygen}
   - Signature: {RSA Sign, ECDSA, Ed25519}
   - Key Agreement: {ECDH, X25519}

- DRBG 
   - DRBG Mechanisms {CTR_DRBG, HMAC_DRBG}

- KDF
   - KDF-CTR with {HMAC, KMAC} as PRF

The latest checkpoint of the specification has also been converted to a [header file](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/lib/crypto/api.h). Please see the [proposal document](https://docs.google.com/document/d/1bbEaRCejPLvlipztXCd3HSBRxCxlV_Wdiv0d9yBw_Uc) for more details.

**Comment by msfschaffner** [comment]
This RFC has been approved by the TC on 2022-05-13.

**Comment by moidx** [comment]
Closing as approved.
