### ISSUE TITLE
verilator segv with no indication of cause.

### ISSUE THREAD

**Issue by rminnich** [lowRISC/opentitan#1209]
Vtop_earlgrey_verilator -t --rominit=target/riscv32imc-unknown-none-elf/release/rom.vmem "--flashinit=target/riscv32imc-unknown-none-elf/release/oreboot.vmem"
Simulation of OpenTitan Earl Grey
=================================

Tracing can be toggled by sending SIGUSR1 to this process:
$ kill -USR1 5242

Rom initialized with program at target/riscv32imc-unknown-none-elf/release/rom.vmem

Flash initialized with program at target/riscv32imc-unknown-none-elf/release/oreboot.vmem
GPIO: Unable to create FIFO at /home/rminnich/projects/oreboot/oreboot/src/mainboard/opentitan/crb/gpio0: File exists
jtag0: Failed to bind socket: Address already in use (98)
jtag0: Unable to create TCP server on port 44853

SPI: Created /dev/pts/6 for spi0. Connect to it with any terminal program, e.g.
$ screen /dev/pts/6
NOTE: a SPI transaction is run for every 4 characters entered.
SPI: Monitor output file created at /home/rminnich/projects/oreboot/oreboot/src/mainboard/opentitan/crb/spi0.log. Works well with tail:
$ tail -f /home/rminnich/projects/oreboot/oreboot/src/mainboard/opentitan/crb/spi0.log

UART: Created /dev/pts/7 for uart0. Connect to it with any terminal program, e.g.
$ screen /dev/pts/7

Simulation running, end by pressing CTRL-c.
Tracing enabled.
Writing simulation traces to sim.fst
Segmentation fault (core dumped)

Files available on request -- I could not attach them.
it's not the gpio error --  I remove that, same result. Verilator does not clean up its files.

**Comment by tjaychen** [comment]
Do you have multiple verilator instances running at the same time? We can
only do 1 at a time right now, it is a known issue we are going to address

**Comment by rminnich** [comment]
yeah that was it. Should I close this issue? Or is it useful for tracking.

**Comment by tjaychen** [comment]
I think it's okay to close, there is already a tracking issue. I'll find it
and link it here.

**Comment by towoe** [comment]
Tracking in #562
