### ISSUE TITLE
[docs] The new dark purple style for the documentation renders console text too faintly

### ISSUE THREAD

**Issue by satnam6502** [lowRISC/opentitan#1211]
Perhaps my eyes are just getting too old, but I find the console text on the documentation pages too faint to read with the new dark purple background.

![toofaint](https://user-images.githubusercontent.com/6164339/70936840-0f768f00-1ff8-11ea-913d-6c9b7d67acdb.png)

**Comment by asb** [comment]
Thanks Satnam for the report - this is tracked in #867. As @rminnich suggests in that issue, we should probably disable dark mode if we don't have time to fix it up...

I'll close this issue so we can continue discussion in #867.
