### ISSUE TITLE
[dvsim] Improve build_seed input

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#12114]
- [ ] Debug IBEX TL integrity ECC error: https://github.com/lowRISC/opentitan/pull/12157/files#r851526417
      and re-enable the commented out code

- [x] Randomize lc_ctrl_state.hjson 

- [ ] Make all the build-seeds slightly different instead of using the same "build_seed" value.

**Comment by msfschaffner** [comment]
Superseded by https://github.com/lowRISC/opentitan/issues/16719
