### ISSUE TITLE
[reg_top] Add common test for spurious WE checks

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#12113]
See https://github.com/lowRISC/opentitan/pull/12106 for context.

**Comment by weicaiyang** [comment]
- [ ] Add common test for reg write enable check #13049
- [ ] Enable reg_wr_check test for all blocks #13101
- [ ] Add assertion to check this error leads to a fatal alert
- [ ] Enable FPV for prim_onehot_check and FPV for the block that contains this prim.

**Comment by weicaiyang** [comment]
closing this since all items are done.
