### ISSUE TITLE
[top, dv] Symbol is optimized in ROM image

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#12128]
@timothytrippel 

When we write a variable like this, 
```
static volatile const uint8_t kLcRmaUnlockToken[LC_TOKEN_SIZE] = {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
};
```
we could find a symbol with the name we defined, after using readelf to read the image. When we find this symbol, we get the address so that we can backdoor override the design to modify this variable.

>   1035: 0000a6b8    16 OBJECT  LOCAL  DEFAULT    4 kLcRmaUnlockToken

I think some SW infrastructure has been changed in the past 2 weeks. So this symbol is disappeared. Do you know if we can get it back. I hope this won't happen to flash image later when we switch everything to Bazel, as this backdoor override mechanism is used in many SW tests.

This can be reproduced by pulling the PR #11826, then run this command. `kLcRmaUnlockToken` can be found in log, but if we update the PR to the top of the tree, `kLcRmaUnlockToken` will be gone.
> /usr/bin/readelf -s --wide build-out/sw/device/tests/flash_rma_unlocked_test_sim_dv.elf > log

**Comment by mcy** [comment]
I have no idea why the Meson build is broken, but the Bazel build is fine.

```rust
$ nm bazel-out/k8-fastbuild-ST-b8775c98f59c/bin/sw/device/tests/sim_dv/flash_rma_unlocked_test_rom_prog_sim_verilator.elf | grep kLcRma
0000bed8 r kLcRmaUnlockToken
```

Debugging this is probably going to take longer than it will take us to shut off Meson; Tim says he'll loop back with you later today.

**Comment by timothytrippel** [comment]
Turns out it was a super simple fix to meson... see linked PR.
