### ISSUE TITLE
[ip/spi_device] confusing names on register status.txf_empty/full, rxf_empty/full

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#1212]
@eunchan 
as discussed, status.txf_empty/full and status.rxf_empty/full indicate status of async fifo, it's better to add prefix "async_fifo" since TXF/RXF is used for SRAM FIFO in the document.

**Comment by weicaiyang** [comment]
@eunchan this is a very old issue. Do you think if it's still valid to rename the CSR?

**Comment by eunchan** [comment]
yep. I think it should be. Let's ICEBOX this.

**Comment by weicaiyang** [comment]
> yep. I think it should be. Let's ICEBOX this.

sounds good, Thanks @eunchan

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. I think this is relevant for this release but not M2.5, so correctly labeled https://github.com/lowRISC/opentitan/labels/Type%3AIcebox.

**Comment by msfschaffner** [comment]
CC @a-will

**Comment by a-will** [comment]
Generic mode is being removed, so this issue becomes moot.
