### ISSUE TITLE
[spi_device] Mailbox Command SRAM Address

### ISSUE THREAD

**Issue by kosta-kojdic** [lowRISC/opentitan#12122]
@eunchan in PR #12094 you can reproduce this potential mailbox issue:
./util/dvsim/dvsim.py hw/ip/spi_device/dv/spi_device_sim_cfg.hjson -i spi_device_cmd_mailbox --fixed-seed 20 --waves --xprop-off -v h --max-parallel 1

We configure normal read, issue it, configure mailbox host address CSR, we hit that address, but address to SRAM is not what host issued - we had for example address 0x38BE29 and configured host mailbox address in CSR is 0x38BC00 (10 bits are 0 according to spec here). 
sram address bits are here 0x28A instead of what I expect 0x229. In the RTL logic address is taken 31:2, if this is correct how can we access mailbox locations inbetween?

**Comment by eunchan** [comment]
Sorry for late response. I found `addr_d` logic is wrong.
I made a fix #12234 .

Please apply this patch to your dv to run on the latest.
Unzip the file and
git am 0001-Fix-CSR-UPLOAD_STATUS2.patch
[0001-Fix-CSR-UPLOAD_STATUS2.patch.zip](https://github.com/lowRISC/opentitan/files/8525186/0001-Fix-CSR-UPLOAD_STATUS2.patch.zip)

**Comment by tjaychen** [comment]
@kosta-kojdic i'm going to close this issue for now since it seems @eunchan has already merged the fix.
If you continue to have problems, please feel free to re-open.
