### ISSUE TITLE
[usbuart] State of usbuart

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#12141]
There are several lint errors in `usbuart` due to recent port changes in `usb_fs_nb_pe`.
Is `usbuart` still maintained, and can these breakages be fixed easily?
If not we will have to remove this from lint checks when we make the AscentLint checks blocking.

**Comment by a-will** [comment]
`usbuart` is unused in any implementation and has no discernible tests that I could find. Sounds like it isn't maintained anymore.

**Comment by tjaychen** [comment]
if that's the case let's just remove it. It's not part of the real design anyhow.

**Comment by msfschaffner** [comment]
Ack!
