### ISSUE TITLE
[clkmgr, top] Test case for frequency measurement / timeout through low power 

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#12151]
The frequency measurement / timeout features in `clkmgr` typically do not work with dynamic clock gating or clock switches.
The only exception is when the measured clocks are specifically requested by `pwrmgr` via the enable inputs to shut-off.

In these cases, the measurement / timeout modules should automatically disable since one of the clocks is about to go offline.
We should create either a chip level or a block level test case to target this scenario and ensure that the measurement / timeout features can be turned on and left in place. 

There may already be a test for this, it should be double checked.

**Comment by tjaychen** [comment]
@jeoongp FYI

**Comment by matutem** [comment]
The chip_sw_ast_clk_outputs, chip_sw_clkmgr_sleep_frequency, and chip_sw_clkmgr_reset_frequency tests check this.

Tim, are you okay if I close this?

**Comment by matutem** [comment]
Closed after consultation with Tim.
