### ISSUE TITLE
[ast, clkmgr]Add status register to inform SW that ext clk switch is done

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#12152]
@tjaychen 
As discussed, when we switch to use ext clock with low speed, there is a 12.5 us period that aon_clk is off and div4 clock is unstable (switching from 24->12->24mhz), it's good to let SW know when the clock switching is done. Otherwise, if uart transfer starts at that period, the baud rate will be wrong.
![Screen Shot 2022-04-15 at 1 06 43 PM](https://user-images.githubusercontent.com/49293026/163627114-1076ff4b-1e13-403b-bb8c-af6b0db0cac7.png)

waveform: ot_debug -j smart:e38bbaa7-3a04-4e46-bca6-7856522b2e9b

cc: @matutem @jdonjdon

**Comment by tjaychen** [comment]
thanks weicai, i'll add this as soon as i finish debugging some flash stuff.
