### ISSUE TITLE
[LC_CTRL, FPV] LC transitions in one direction

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#12186]
@NigelScales 

As you suggested, it's good to have FPV to ensure LC state transitions in one direction
can you add assertions in the design to check that? Adding these assertions in design is preferred, as they can be reused in chip-level and they're easier to be enabled in FPV. And Cindy will enable those assertion to run in FPV.

cc: @msfschaffner

**Comment by NigelScales** [comment]
@weicaiyang 
This is included in the RTL by https://github.com/lowRISC/opentitan/pull/12244.
Please ensure this works with the formal tool by temporally adding a loop to the FSM RTL and check this is 
detected by the tool.
I have done this for simulation.

```
`ifdef INC_ASSERT
    //verilog_format: off
    property sec_cm_cfi_linear_p;
      fsm_state_e initial_state;
      // Trigger whenever state changes and stores initial state as initial_state
      // Then thereafter we must never see that state again until reset
      (!$stable(fsm_state_q), initial_state = $past(fsm_state_q)) |->
          always (fsm_state_q != initial_state);
    endproperty
    //verilog_format: on

  `ASSERT(SecCmCFILinear_A, sec_cm_cfi_linear_p)
```

**Comment by weicaiyang** [comment]
That's really thoughtful. Thanks @NigelScales
