### ISSUE TITLE
[bazel] Investigate how to avoid spurious builds of //hw:verilator when sim_verilator tests are not requested

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#12259]
To address latency problems, https://github.com/lowRISC/opentitan/pull/12237 adds a hack to `//hw/BUILD` that completely disables the Verilator model build, even when a test depends on it. This is intended to address build latency issues in the short-term but should be replaced with a more robust solution.

Known issues:
- The prior `bazel query rdeps(..., //hw:verilator)` was not generating the name of every target that needed to be excluded, so //hw:verilator was getting built anyways.
- `--test_tag_filters=-verilator` is also not sufficient even when combined with the above query.

**Comment by drewmacrae** [comment]
I know what's going on here now... I think and I think we can close it, but keeping the workaround from #12237 is still useful to let us build software for verilated tests without building the verilated model.

We don't rely on rdeps in our CI at present and that's an issue with Bazel, not OpenTitan even if we could reproduce it.

Here's what I understand about filtering, why it appeared problematic and what has happened to fix it:

When building with wildcards bazel would match all targets in a directory including macros like `sw/device/test:uart_smoketest`
(I've added the manual tag to that macro so it should no longer match that one)

`--test_tag_filters` simply instruct bazel not to run the other tests in this macro. bazel still tried to build the whole macro including all the dependencies like verilator.

The manual tag should prevent these macros from matching so bazel tries to build `sw/device/tests:uart_smoketest_fpga_cw310` and similar targets instead. 

using targets like `sw/device/tests:uart_smoketest` is instructing bazel to build `sw/device/tests:uart_smoketest_sim_dv`, `sw/device/tests:uart_smoketest_sim_verilator` and `sw/device/tests:uart_smoketest_fpga_cw310` and filtering wont change this.
