### ISSUE TITLE
spi host cpha1 bug

### ISSUE THREAD

**Issue by visbaz** [lowRISC/opentitan#12262]
Last bit of last segment not sampled properly

Branch name : **spi_host_cpha1_bug**

Commented scoreboard lines 141-143 to run further and see the exact mismatch bit.
Attached is the snapshot and simulation time of bug.
Command:
**util/dvsim/dvsim.py hw/ip/spi_host/dv/spi_host_sim_cfg.hjson -i spi_host_speed --fixed-seed 3577238519 --waves**
![cpha1](https://user-images.githubusercontent.com/98454159/164549772-3e97a21a-4830-4248-82c8-e01ebf14f03c.JPG)
s

**Comment by martin-lueker** [comment]
Thanks @visbaz for this issue, this seed is now passing with the changes from:  #12539
