### ISSUE TITLE
[sysrst_ctrl] Questions on main reset and aon_reset

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#12288]
@msfschaffner 

I have 2 questions
1. if bat_disable or rst_req occurs, we need to reset the sysrst_ctrl. Should we reset both main reset and aon_reset, or one of them?
2. If only one of main reset and aon_reset is issued, it will cause an interrupt. In the wave below, the intr_event_pulse is generated when only one reset is triggered. Is that expected? Or should we always drive both resets?

```
prim_sync_reqack u_prim_sync_reqack (
    .clk_src_i(clk_aon_i),
    .rst_src_ni(rst_aon_ni),
    .clk_dst_i(clk_i),
    .rst_dst_ni(rst_ni),
    .req_chk_i(1'b1),
    .src_req_i(aon_intr_req),
    .src_ack_o(aon_intr_ack),
    .dst_req_o(intr_event_pulse),
    .dst_ack_i(intr_event_pulse)
  );
```
![Screen Shot 2022-04-22 at 10 15 36 AM](https://user-images.githubusercontent.com/49293026/164762984-2b54eeae-4f94-4e4d-8ee7-8ba56edb81e2.png)

cc: @patel-madhuri

**Comment by msfschaffner** [comment]
Hey @weicaiyang, 
Afaik, it is expected that the entire OpenTitan chip is reset when either of the two conditions occur.
So this includes both the main and the AON reset.

@toshaq is my understanding correct?

CC @tjaychen

**Comment by weicaiyang** [comment]
> afaik, it is expected that the entire OpenTitan chip is reset when either of the two conditions occur.
So this includes both the main and the AON reset.

This sounds good. and this assumption actually makes DV much easier

**Comment by tjaychen** [comment]
just to chime in a bit.. when the reset request comes in, all resets except for the POR driven modules (pwrmgr, and parts of rstmgr/clkmgr) should be reset.

@jeoongp FYI

**Comment by weicaiyang** [comment]
Make sense. Thanks @tjaychen. Closing this issue
