### ISSUE TITLE
[pwrmgr/rstmgr] Permanence of fault registers

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#12284]
One thing that just came up during discussions.

For most modules, an escalation reset also clears the local error bits.
However, for pwrmgr/clkmgr/rstmgr this is not the case. These modules use a derived version of the POR, which means an escalated reset does not actually reset them. 

This also means if the `fault_status` is set, it remains permanently set until user intervention.
This is not ideal behavior, we need to have a mechanism to clear the fault status at the appropriate time. 

The larger issue is that parts of pwrmgr/rstmgr are in the wrong reset domain.
There is no reason really for fault registers, or alert senders to be in the `POR` domain.  These should be moved to the `lc` domain, while other functions such as reset reason, fsm should be in the `POR` domain.

**Comment by tjaychen** [comment]
related to #12285

**Comment by tjaychen** [comment]
see discussion [here](https://github.com/lowRISC/opentitan/issues/12523#issuecomment-1129412489)

**Comment by jeoongp** [comment]
@tjaychen, can we consider the same approach for pwrmgr as rstmgr in https://github.com/lowRISC/opentitan/pull/12901?

**Comment by tjaychen** [comment]
we will need to look a bit more closely. Becuase there are some things in rstmgr/pwrmgr (the reset info for example) that really does need to survive an escalated reset.

**Comment by tjaychen** [comment]
@jeoongp i've assigned this issue to you.

**Comment by tjaychen** [comment]
this issue has been addressed by #13950 .
@jeoongp if you agree, can you close this issue?

**Comment by jeoongp** [comment]
Yes, this issue has been addressed by #13950.
