### ISSUE TITLE
[ES] Docs Clarification 

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#12295]
The [entropy source documentation](https://docs.opentitan.org/hw/ip/entropy_src/doc/) currently contains this paragraph:
```
The hardware conditioning can also be bypassed and replaced in normal operation with a firmware-defined conditioning algorithm. 
This firmware conditioning algorithm, can be disabled on boot for security purposes. 
The exact mechanism for this functionality will be described in a future update to this document (TBD).
```
Is this still TBD, or has this been resolved (i.e., should it be removed from the docs, or should it be expanded)?

**Comment by martin-lueker** [comment]
Hi Micheal, 
  This is now defined and verified in DV.   @mwbranstad do you have time to write a paragraph on the procedure here?  It should include the procedures for doing this with or without HW conditioning 

-Martin

**Comment by msfschaffner** [comment]
That would be great, thanks!
