### ISSUE TITLE
[dv, xcelium] code coverage for DUT Only

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#12292]
@rasmus-madsen 

Do you know how we can only enable code coverage for DUT?
I added below in #12219, but seems not working. It even shows code coverage for uvm_pkg in the report.
```
deselect_coverage -betfs -module tb...
select_coverage -befs -module ${DUT_TOP}...
```

![Screen Shot 2022-04-22 at 12 28 16 PM](https://user-images.githubusercontent.com/49293026/164781475-aa2c14b5-6dd5-442a-8227-2f93b1722482.png)

https://reports.opentitan.org/hw/ip/aes_masking/dv/latest/cov_report/index.html

cc: @cindychip @jdonjdon

**Comment by rasmus-madsen** [comment]
@weicaiyang hmm let me look into it should be easy to fix

**Comment by weicaiyang** [comment]
> @weicaiyang hmm let me look into it should be easy to fix

Thanks @rasmus-madsen

**Comment by rasmus-madsen** [comment]
@weicaiyang there was some cleaning up needed. but even after the clean up the problem seem to stay.
I have asked the Cadence  FAE for some support.

will get back once I have an update from him

**Comment by weicaiyang** [comment]
> @weicaiyang there was some cleaning up needed. but even after the clean up the problem seem to stay. I have asked the Cadence FAE for some support.
> 
> will get back once I have an update from him

Sounds good. Thanks

**Comment by weicaiyang** [comment]
fixed via https://github.com/lowRISC/opentitan/pull/12400
