### ISSUE TITLE
[dv] Set up xprop flow with Xcelium

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#1234]
@rasmus-madsen @tunghoang290780 
Xprop is one of the items for DV sign-off. I have made a PR #1134 to add xprop with VCS. Since you guys may be more familiar with Cadence tool, can you help to set up xprop flow with Xcelium?

**Comment by rasmus-madsen** [comment]
@weicaiyang 
I think it might already be enabled at least this is the TLUL interface.
![image](https://user-images.githubusercontent.com/53917183/71160038-1e06b580-2247-11ea-86a1-9d96b8cc3eaa.png)

but I look into the settings and get back to you!

**Comment by rasmus-madsen** [comment]
@weicaiyang I checked and we need to add either -xprop or xfile (depending on what we need) to the build_opts
 and we need to decide between forward only X
and Compute as ternary 

do you have any suggestions on what is the better choice.
I ahve tried both and they seem to work

**Comment by weicaiyang** [comment]
> @weicaiyang I checked and we need to add either -xprop or xfile (depending on what we need) to the build_opts
> and we need to decide between forward only X
> and Compute as ternary
> 
> do you have any suggestions on what is the better choice.
> I ahve tried both and they seem to work

@rasmus-madsen 
I'm not sure how "forward only X" and "Compute as ternary" behave in Xcelium.
For VCS, we use `tmerge` which behaves closer to actual hardware and also the default xprop mode. In below code, a will be 1 even c==x.
```
if (c)
  a = 1;
else
  a = 1;
```

There is another mode in VCS which is more pessimistic and a will become x when c==x in above code.

**Comment by rasmus-madsen** [comment]
@weicaiyang 
I think that is FOX mode I will do some testing tomorrow.
I assume we want to run with xprop always on?

do you want me to make a separate PR for updating xcelium.mk?

**Comment by weicaiyang** [comment]
> @weicaiyang
> I think that is FOX mode I will do some testing tomorrow.
> I assume we want to run with xprop always on?

yes, prefer to have it enabled by default unless you see it have much simulation performance impact with Xcelium.

> 
> do you want me to make a separate PR for updating xcelium.mk?

Yes, please make a separate PR. Thanks

**Comment by weicaiyang** [comment]
Done
