### ISSUE TITLE
common security countermeasures

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#12345]
@weicaiyang thank you for pointing out these exist!

after reading the documentation I still have questions:

1. how do I run the sec_cm tests  they are not listed in the lists of tests when use the --list option with dvsim. (yes I did import the testsplan)
2. how can we be sure this approach is sufficient as the injection won't happen during real operation?
3. why are the assertions not automatically disabled since the bind should now the path there is no reason for me to go lookup the path and manually turn them off. (also I think there is an error in the documentation 

> Fault injection may trigger unexpected SVA errors. Override the sec_cm_fi_ctrl_svas function to disable them. sec_cm_fi_ctrl_svas(.enable(1)) will be invoked before injecting fault. After reset, sec_cm_fi_ctrl_svas(.enable(0)) will be called to re-enable the SVA checks.
I think you want to change the texts so that .enable(1) enables SVAs again based on the code listed

**Comment by rswarbrick** [comment]
For (2), I completely agree! And it gets worse: at the moment, these tests also (partially) disable the scoreboard with a plusarg.

Probably, we need some hook (maybe just `pre_run_sec_cm_fi_vseq`?) where we can start an operation so that the dut isn't completely quiescent. Otherwise we're only ever going to see what happens if you inject a fault when e.g. a sparse FSM is in the halted state.

**Comment by rasmus-madsen** [comment]
> For (2), I completely agree! And it gets worse: at the moment, these tests also (partially) disable the scoreboard with a plusarg.
> 
> Probably, we need some hook (maybe just `pre_run_sec_cm_fi_vseq`?) where we can start an operation so that the dut isn't completely quiescent. Otherwise we're only ever going to see what happens if you inject a fault when e.g. a sparse FSM is in the halted state.

good point @rswarbrick I didn't even thing about the disabled scoreboard

**Comment by weicaiyang** [comment]
> how do I run the sec_cm tests they are not listed in the lists of tests when use the --list option with dvsim. (yes I did import the testsplan)

need to import the test in the IP hjson file. See step 2 in https://github.com/lowRISC/opentitan/blob/master/hw/dv/sv/cip_lib/doc/index.md

> how can we be sure this approach is sufficient as the injection won't happen during real operation?

you could certainly override `pre_run_sec_cm_fi_vseq` to do this. But it could be a lot of work if you want to have FI happen at every state. Hence, we use FPV to ensure when FI happens, a fatal alert will be triggered unconditionally, no matter what state it is. For details, refer to this methodology [doc](https://docs.opentitan.org/doc/ug/sec_cm_dv_framework/).

The DV portion (sec_cm_test) is constructed as a semi-auto sequence. It allows you to add checks after FI, such as checking the corresponding CSR is set, subsequent operation won't be processed etc

> why are the assertions not automatically disabled since the bind should now the path there is no reason for me to go lookup the path and manually turn them off. (also I think there is an error in the documentation.

the interface may be bound to dut.a.b.fsm, but we may need to disable assertion at dut.a. Forcing the FSM to invalid value may cause many things to go south. automatically disabling assertion seems not easy to add. Or, let me know how we could do that.
BTW, Where is the error in the doc?

**Comment by weicaiyang** [comment]
Closing this issue since most of the AES sec_cm tests have been added. 
@rasmus-madsen Feel free to re-open this if you have more to discuss
