### ISSUE TITLE
[spi_device] Read Threshold/ Flip event should not occur when boundary crossed (buffer -> mailbox)

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#12388]
Two issues here:

1. If a host issues a read request crosses Mailbox lower boundary (Read -> Mbx) and issuing more than threshold (or entire mailbox to trigger flip), the logic raises threshold and/or flip events even if the read access to the mailbox space.
2. If a host issues a read request crosses the Mailbox upper boundary (Mbx -> Read) and issuing more than the threshold or flip size, the logic does not raise events.

CC: @weicaiyang

**Comment by eunchan** [comment]
Lowering the priority as this occurrence is rare (need to read more than 1kB size or up to threshold size at once)

**Comment by weicaiyang** [comment]
@eunchan do you plan to fix this for M2?

**Comment by eunchan** [comment]
> @eunchan do you plan to fix this for M2?

Yep. I will.

**Comment by eunchan** [comment]
Addressed.
