### ISSUE TITLE
[crypto, doc] Write an explainer about Solinas reduction for otbn/crypto.

### ISSUE THREAD

**Issue by jadephilipoom** [lowRISC/opentitan#12403]
See discussion in https://github.com/lowRISC/opentitan/pull/11778

Current implementations of modular reduction for P-384 and {X,Ed}25519 use an algorithm called Solinas (aka generalized Mersenne) reduction for which there aren't good existing explanations. We should have an explaner markdown document that's referenced from both implementations so the code is easier to understand. I feel like I have a good idea for how to write this document.

cc @mcy @felixmiller

**Comment by msfschaffner** [comment]
@jadephilipoom is this one still relevant?

**Comment by jadephilipoom** [comment]
Technically I could still write it, but realistically I think it's not a priority. The code has a lot of comments to explain what's going on. Happy to close.
