### ISSUE TITLE
[rom_ctrl] CDC between KMAC and ROM_CTRL

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#12414]
Although ROM_CTRL and KMAC are operating on the same clock / reset:
https://github.com/lowRISC/opentitan/blob/1d12d0232dfc6515c6f3f889296763d217322ea2/hw/top_earlgrey/data/top_earlgrey.hjson#L684-L688
https://github.com/lowRISC/opentitan/blob/1d12d0232dfc6515c6f3f889296763d217322ea2/hw/top_earlgrey/data/top_earlgrey.hjson#L602-L604
they are in different clock domains (`infra` and `trans`) which means that the clock trees have different insertion delays in RTL sims with the ASIC view enabled. The delays appear to be due to glock gating and buffer cells that are hand-instantiated in RTL (@arnonsha to confirm whether that is correct). This gives rise to a very short glitch on the KMAC error input signal as can be seen below.

![image](https://user-images.githubusercontent.com/41358501/166080550-f1ab9a10-0c81-4941-9acc-56c2c9a608cf.png)

Zooming out a bit, we can see that this moves the ROM checker FSM into "Invalid", and that the FSM alert is asserted:

![image](https://user-images.githubusercontent.com/41358501/166080624-c6ce6470-82ac-490b-9fde-3cb12f9b0ffa.png)

How should we go about fixing this? 
I would assume that our clock constraints would ensure both clock domains connected to the same root clock are properly analyzed and optimized to met timing in synthesis?
If that is the case, should we maybe disable the standard cell propagation delays in RTL simulations?

Another possibility would be to make this a fully async interface (such as between LC_CTRL and KMAC) - but that feels a bit heavy. Also, we may run into similar issues in other RTL sims with the ASIC view enabled.

**Comment by eunchan** [comment]
I think it is safer to put ASYNC FIFO unless ROM_CTRL uses `trans`. But as the clock inputs for both IPs use same `main` clock, Seems to be OK to me.

**Comment by arnonsha** [comment]
kmac_error is driven by combinational logic depending also by FSM state. As such it is prone to glitches (especially during state transitions). 
Let's assume the rom_check FSM clock is a bit delayed (relative to the kmac fsm). Theoretically it can sample this glitch.
I believe the simplest solution would be to sample the kmac_err signal (and other outputs) before sending them to the rom check fsm.

**Comment by arnonsha** [comment]
@msfschaffner 
The delays seen in the RTL simulation are indeed due to instantiated prim bufs

**Comment by arnonsha** [comment]
There's no real CDC issue here, assuming the kmac_error signal propagates **only to D pins** and not to CLK/RST (@msfschaffner please approve). Since both rom_ctrl and kmac branches originating from the same root, the P&R tool will make sure the branches are balanced and add the necessary delay on the data path.

In RTL however the branches are not balanced due to the std cell internal delay. @msfschaffner already suggested removing this delay completely. However I think we should try making the design more robust by eliminating the glitches of the FSM outputs (it's always a good practice to sample outputs). It can be done easily, and without changing the FSM timing (i.e not add sampling stages), by making the output a function of next_state, rather than a function of state.
@msfschaffner, do you agree ?

**Comment by msfschaffner** [comment]
@arnonsha this is not so straightforward to do on the KMAC side, due to the internal organization of the IP. Also, we want to avoid to flop the entire interface due to the large width of the two KMAC hash shares (2x 256bit). So we need to think about this some more...

Do you know whether there is an easy way to disable propagation delay modeling of the standard cells in simulation (i.e., is there like a common macro than can be set to disable that)? There may be other places in the design where similar issues may occur - so a KMAC-specific RTL fix alone will not solve this issue in its entirety.

**Comment by arnonsha** [comment]
I see, although we can only limit the sampling for control signals. It is cleaner but not a must.

The std cell lib has a single define which adds a default internal delay. Need to make sure it **is not set** (both RTL and GL sims).

@sha-ron

**Comment by msfschaffner** [comment]
Yes that is exactly what I was looking for. For GL sims it probably depends whether you use annotated timing and where it has been extracted from (post synth or post P&R), right? I.e. for post P&R (with clock tree inserted) we probably want to have the accurate delays there...

**Comment by arnonsha** [comment]
Yes,
The clock path of both rom_ctrl and kmac only deffers by 1 clock gating cell.

@msfschaffner, to your question in GL this will be solved using timing annotation (from P&R).

I think we can close this issue if we all agree.

**Comment by tjaychen** [comment]
yeah i think removing the delay for rtl sims is best. Otherwise we will definitely run into similar types of hold time violations in other parts of the design. 

@arnonsha does removing the delay solve your original issue though? Sorry I am a bit behind.

**Comment by arnonsha** [comment]
oh, yes it does

**Comment by msfschaffner** [comment]
Ok, sounds good! Let's close the issue then.
