### ISSUE TITLE
[dv,top] chip_sw_pwrmgr_main_power_glitch_reset test is failing

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#12421]
The test is marked as done on the "DV test deliverables" list but is failing on the dashboard from May 1st.

**Comment by tjaychen** [comment]
i've spoken to @matutem about this, and it is related to the recent addition of alerts to this block.
I'll have a separate look also since he's out right now.

**Comment by tjaychen** [comment]
this is now passing again
