### ISSUE TITLE
[verilator] Add Verilator lint support

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1243]
Verilator has a built-in lint tool. It's not as powerful as proprietary solutions, but gives a good starting point for developers without the need for commercial licenses.

Steps:
- [x] Add Verilator lint support to our fusesoc core files. (FuseSoC supports Verilator lint.)
- [ ] Create waiver files for existing errors, mirroring existing waivers for proprietary tools. Verilator only supports file/line waivers. 
- [ ] Decide what to do with lint errors in generated files.
- [ ] Enable Verilator lint in CI
- [ ] Update documentation

We already do that in Ibex, see 

* https://github.com/lowRISC/ibex/blob/master/lint/verilator_waiver.vlt
* https://github.com/lowRISC/ibex/blob/347b80f631fa49ad80bc2f87f46e76602b0c69ac/ibex_core.core#L70-L87

In the future, we might want to use waivers which don't match the file/line, but the error message. There's a enhancement request for Verilator open at https://github.com/verilator/verilator/issues/1649.

**Comment by msfschaffner** [comment]
I can look into this, since I am also about to add the flow for AscentLint...

**Comment by msfschaffner** [comment]
Ok, initial support for Verilator lint is there, but we still have to populate the lint waivers...

**Comment by imphil** [comment]
Note: Future versions of Verilator will have regex waivers (https://github.com/verilator/verilator/issues/1649), it might be good to use them instead of the old-style waivers with line/file, which are hard to maintain.

**Comment by imphil** [comment]
We have all infrastructure setup and continually add waivers and fixes.
