### ISSUE TITLE
[meson] delete meson.build files in favor of bazel

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#12449]
Once the following issues have been addressed, all `meson.build` files can be removed (with minimal regressions):

- [x] #12447
- [x] #11563
- [x] #11133
- [ ] #12445
- [x] #12446
- [x] #12455
- [x] #12515 
- [x] #12531
- [x] #11792
- [x] #12562 to ensure lowRISC/misc-linters caches Python wheels (partially address #12538)
- [x] #12494 
- [x] #12069
- [x] #12696
- [x] #12655
- [x] #12953

Additionally the following items will need to be fixed after the meson deletion to cleanup some minor regressions:
- [ ] #12448 (temporary solution will work for the time being)
- [ ] #12504 
- [ ] #12497

**Comment by timothytrippel** [comment]
This is partially accomplished in #12394, but it was determined it would be easier to remove all meson.build files at once, than to stage them (i.e., ROM build files first, then all sw/ after).

**Comment by milesdai** [comment]
Adding the following issues (since I can't edit the post above):
- #12494 
- #12497

**Comment by timothytrippel** [comment]
CC: @cfrantz @arunthomas As I mentioned earlier this week, this issue contains the list of items that must be addressed to delete meson from the repository. CCing you both for visibility.

**Comment by drewmacrae** [comment]
See also: https://github.com/lowRISC/opentitan/issues/12696 and https://github.com/lowRISC/opentitan/issues/12655
