### ISSUE TITLE
[otbn] locking signal is not staying asserted as long as the otbn is in locked state

### ISSUE THREAD

**Issue by prajwalaputtappa** [lowRISC/opentitan#12440]
@GregAC and @rswarbrick,
The locking signal is just pulsing for one clock cycle when the otbn moves in to locked state and not staying high until secure wipe finishes. 

![Screenshot from 2022-05-03 17-56-21](https://user-images.githubusercontent.com/91126414/166502130-b8d33c2b-9594-40b6-9f27-5baab669154d.png)

**Comment by rswarbrick** [comment]
Oh dear! That's not what I thought should happen! Does this happen for all tests where OTBN gets locked, or only in certain situations? The locking signal is computed as:
```systemverilog
  assign locking_o = (state_d == OtbnStateLocked) & ~secure_wipe_running_i;
```
My guess is that we're seeing a single cycle where `state_d` is `OtbnStateLocked` but before the `secure_wipe_running_i` signal gets set. I suspect I just messed this up when I rejigged the timing of the signals (and really want a "secure_wipe_running_d").

**Comment by prajwalaputtappa** [comment]
> Oh dear! That's not what I thought should happen! Does this happen for all tests where OTBN gets locked, or only in certain situations? The locking signal is computed as:
> 
> ```systemverilog
>   assign locking_o = (state_d == OtbnStateLocked) & ~secure_wipe_running_i;
> ```
> 
> My guess is that we're seeing a single cycle where `state_d` is `OtbnStateLocked` but before the `secure_wipe_running_i` signal gets set. I suspect I just messed this up when I rejigged the timing of the signals (and really want a "secure_wipe_running_d").

Rupert, this most likely happens in every testcase where otbn is going to locked state. I've not checked the waves for all testcases, but looking at the code it is most likely so. 
@GregAC and I had a long chat on this last evening and agreed that locking signal should remain asserted as long as otbn is in locked state. He said he would fix this bug.

**Comment by GregAC** [comment]
> My guess is that we're seeing a single cycle where state_d is OtbnStateLocked but before the secure_wipe_running_i signal gets set.

Yes, that's what's happening as when we first transition to the `OtbnStateLocked` state `secure_wipe_running_i` isn't yet set. We could add in the start secure wipe signal but given that will always be set when we first transition to locked `(state_q == OtbnStateLocked) & ~secure_wipe_running_i` may work fine given any time `state_d == OtbnStateLocked != state_q` we're about to start a secure wipe and don't want to set `locking_o`.

**Comment by rswarbrick** [comment]
I don't think it's always set: the problem is that we don't do a secure wipe if we lock when we weren't previously running. I think we'll probably have to plumb the "start secure wipe" signal through too.
