### ISSUE TITLE
[bazel] update CI to run chip-level tests using bazel (over system test)

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#12445]
Currently CI only builds and runs host-side tests (e.g., DIF and mask ROM unit tests). CI should run all applicable (on-device) chip-level tests on FPGA and Verilator. This **_may_** include:

- [x] update test tags to define set of "fast" verilator chip-level tests (e.g. smoke tests) that match what is run with the current system test framework
    - [x] earlgrey tests
    - [x] englishbreakfast tests
        - [x] add to CI (#12783)
        - [x] remove old systemtest job from CI once above  is stable with bazel  (#12925)
- [x] run all (non-broken) chip-level tests in CI on FPGA and all (non-broken) fast chip-level tests on Verilator

**Comment by drewmacrae** [comment]
I think there's a PR to do this here: https://github.com/lowRISC/opentitan/pull/12131

**Comment by milesdai** [comment]
The tests in question are
- `sw/silicon_creator/lib/driver:retention_sram_functest`
- `sw/silicon_creator/lib/driver:alert_functest`
- `sw/silicon_creator/lib/driver:watchdog_functest`

**Comment by drewmacrae** [comment]
I just filed https://github.com/lowRISC/opentitan/issues/12486 to record tests that are failing when built and conducted by bazel. It looks like some of them have been failing on the cw310 as well, but like they aren't failing for systemtest. I'll try to complete the list while I go through the cw310 test results

**Comment by drewmacrae** [comment]
I think I'll try to dump the bitstream into the bitstream cache after fetching it from azure so bazel can find it and run the right bitstream for the cw310 tests in CI.

**Comment by drewmacrae** [comment]
> > Admittedly,we should also probably come up with a plan for which tests are allowed to run in CI.
> 
> I'm sorting through the tests right now to ensure that Bazel covers a superset of the previous systemtest framework, and while most test are fine, there are a few issues. Currently, I'm using a combination of `verilator` and `-failing_verilator` tags and `short` and `moderate` timeout filters to get the set of tests that we run. However, there are a few tests in systemtest whose Bazel counterparts are categorized as `long` tests that get skipped using this approach.
We should really keep the marking of tests as broken uniform and replace this with "broken" to make tag filtering and querying more concise.

> How should we handle this?
If the timeouts and an understanding of what currently works isn't enough to select the tests for CI we should probably try to capture the other consideration that drives the decision: how much value the tests provide to the suite of tests we're running. IDK what other work has been done to this effect in bazel.
