### ISSUE TITLE
[csrng] Auto-generated macros for CSRNG application interface command header

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#12453]
#12352 writes to the BOOT_GEN_CMD register of EDN but without auto-generated macros we need to use a hardcoded value which is error-prone.

It would be great if we had auto-generated macros for the fields of the 32-bit command header.

Please also see this [comment](https://github.com/lowRISC/opentitan/pull/12352#discussion_r862104592) for context.

**Comment by mwbranstad** [comment]
The point of the BOOT_GEN_CMD is not to write it, but to use the default for boot. If this is a test to make sure this field can be written, that would be a different case.
Also, not sure what process supports auto-generated macros.

**Comment by alphan** [comment]
The change in #12352 is not a test, we want to make sure we have enough random bits at boot time by setting glen to max.

@moidx

**Comment by martin-lueker** [comment]
Hi Alphan, 
   For clarification, these are macros for use in the BOOTROM?  Do you mean in the assembly portion, or for the later C-stages?

**Comment by alphan** [comment]
After the doc fix in #12466, I removed the code that writes to `BOOT_GEN_CMD` in #12352 since we don't need that any more, so the priority of this is lower now.

These macros would be useful for any code (assembly or c). For example, the following macros in `flash_ctrl_regs.h`

```
 // Control register
 #define FLASH_CTRL_CONTROL_REG_OFFSET 0x20
 #define FLASH_CTRL_CONTROL_REG_RESVAL 0x0
 #define FLASH_CTRL_CONTROL_START_BIT 0
 #define FLASH_CTRL_CONTROL_OP_MASK 0x3
 #define FLASH_CTRL_CONTROL_OP_OFFSET 4
 #define FLASH_CTRL_CONTROL_OP_FIELD \
   ((bitfield_field32_t) { .mask = FLASH_CTRL_CONTROL_OP_MASK, .index = FLASH_CTRL_CONTROL_OP_OFFSET })
 #define FLASH_CTRL_CONTROL_OP_VALUE_READ 0x0
 #define FLASH_CTRL_CONTROL_OP_VALUE_PROG 0x1
 #define FLASH_CTRL_CONTROL_OP_VALUE_ERASE 0x2
 #define FLASH_CTRL_CONTROL_PROG_SEL_BIT 6
 #define FLASH_CTRL_CONTROL_ERASE_SEL_BIT 7
 #define FLASH_CTRL_CONTROL_PARTITION_SEL_BIT 8
 #define FLASH_CTRL_CONTROL_INFO_SEL_MASK 0x3
 #define FLASH_CTRL_CONTROL_INFO_SEL_OFFSET 9
 #define FLASH_CTRL_CONTROL_INFO_SEL_FIELD \
   ((bitfield_field32_t) { .mask = FLASH_CTRL_CONTROL_INFO_SEL_MASK, .index = FLASH_CTRL_CONTROL_INFO_SEL_OFFSET })
 #define FLASH_CTRL_CONTROL_NUM_MASK 0xfff
 #define FLASH_CTRL_CONTROL_NUM_OFFSET 16
 #define FLASH_CTRL_CONTROL_NUM_FIELD \
   ((bitfield_field32_t) { .mask = FLASH_CTRL_CONTROL_NUM_MASK, .index = FLASH_CTRL_CONTROL_NUM_OFFSET })
```
make it pretty easy to work with the bitfields in the control register of flash_ctrl.

I'm not sure how exactly these are generated but @tjaychen would probably know.

**Comment by andreaskurth** [comment]
Triaged for `csrng`. IIUC, this is a SW / tooling enhancement without RTL or DV impact, so not a priority for M2.5 --> https://github.com/lowRISC/opentitan/labels/Type%3AIcebox for now.

**Comment by msfschaffner** [comment]
Closing as this does not seem to be relevant anymore.
