### ISSUE TITLE
[lc_ctrl] Question about hardware revision register value

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#12478]
@msfschaffner apologies for missing this in #11617 but I was wondering if we can set the current values of the revision and generation fields to 0 instead of 1.

We have only a few of bits reserved for these in the LSB of the JEDEC device ID ([here](https://github.com/lowRISC/opentitan/blob/b2fed682d4b0617078c16527c69f72fca7f895f8/sw/device/silicon_creator/lib/drivers/spi_device.h#L22)) and starting from 0 would give us one more rev and gen before we worry about overflowing those bits.

cc @cfrantz

**Comment by msfschaffner** [comment]
We can certainly do that, yes. See https://github.com/lowRISC/opentitan/pull/12479.
