### ISSUE TITLE
[bazel] Bazelify OpenOCD systemtest

### ISSUE THREAD

**Issue by milesdai** [lowRISC/opentitan#12497]
`tests/systemtest/earlgrey/test_sim_verilator.py` contains an [additional test](https://github.com/lowRISC/opentitan/blob/master/test/systemtest/earlgrey/test_sim_verilator.py#L206) to check that OpenOCD connects correctly. This test needs to be converted into a `py_binary` Bazel rule and moved into `sw/host/tests`.

**Comment by dmcardle** [comment]
Looks like `test_sim_verilator.py` was deleted in #12929. Actually, I think the referenced test was removed earlier in #12482. @milesdai, could you confirm whether [test_openocd_basic_connectivity](https://github.com/lowRISC/opentitan/pull/12482/files#diff-3c555d8427448e4827e4f9cee6362bcecac06ed98b35ecf144006adc2ab74ed8L206-L258) need to be recreated?

**Comment by dmcardle** [comment]
@milesdai, can you help me with the archaeology on this one?

**Comment by milesdai** [comment]
Ah yes, this test written in python that made sure that openocd could connect to the FPGA, and that was about it. Given #14343, when we start running SRAM tests, this will probably be unnecessary since each test will be exercising the openocd connectivity.

**Comment by dmcardle** [comment]
Thanks for confirming, Miles! I'll close this as "won't-fix".
