### ISSUE TITLE
[bazel] bazelify `sw/device/benchmarks/coremark`

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#12504]
The coremark benchmark needs bazel rules before meson can be deleted, as it is run in the [DV simulation nightly regression](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/dv/chip_sim_cfg.hjson;drc=0fedd4278fcfdf6ba02e8e64f168f9af327e2ab6;l=647).

**Comment by moidx** [comment]
Targeting M2 to be able to track performance requirements wrt benchmarks.
