### ISSUE TITLE
[dv] alert connection in GLS

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#12507]
Top level alert connections might break GLS.
Need to think of a better solution.

**Comment by jdonjdon** [comment]
> @jdonjdon I think we have a workaround for this right? I am closing this for now, but please reopen if you think we should still track this.

Description is too simplified to identify what the issue referring to but FWIW,
we don't have open alert connection issue in our current GLS.

**Comment by msfschaffner** [comment]
Ok thanks - if this is not an issue let's just leave it closed.
