### ISSUE TITLE
[rv_dm] write and read pointer are reset differently

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#12500]
If LC is in RMA or TEST_UNLOCKED, it's allowed to switch taps without issuing reset.

When we switch taps from RV_DM to LC, trst_n is driven to 0, which resets write pointer, while the reset of write pointer isn't asserted as it's from internal reset. Hence, these 2 pointers are different which causes RV_DM to fetch the fifo and start a transaction.
Then, when switching back to RV_DM tap again, jtag access doesn't work correctly.

related to #12461

cc: @cindychip

**Comment by tjaychen** [comment]
@weicaiyang this issue should be fixed now.
let me know if you still run into problems. If not, feel free to close this.

**Comment by weicaiyang** [comment]
Thanks @tjaychen 
close via https://github.com/lowRISC/opentitan/pull/12613
