### ISSUE TITLE
[dv] Regression reproducing issue

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#12512]
as @tjaychen pointed out, some regression failures can't be reproduced after we run nightly regression in kokoro.
It may be due to different env setup in kokoro. I tried to address this issue:

1. found the parameter order in generated RTL may be changed if python version is different. Fixed at #12511.
2. Tried to install python virtual env (pyenv) to downgrade python version to the one we use in nightly, but pyenv doesn't work with
dvsim. So, I can't confirm if above fix solves the issue or not. If this issue comes up again, will contact AE to further investigate.

**Comment by rswarbrick** [comment]
About dvsim reproducibility: that's a bit odd - I would have expected `pyenv` to work. But you might also be able to figure out what's going on by looking at the logs: the Python shouldn't affect much that isn't visible in the command lines that dvsim runs.

**Comment by msfschaffner** [comment]
Did we run into this problem recently? Otherwise, can we close this? 

CC @matutem @jdonjdon
