### ISSUE TITLE
[clkmgr] Persistence of measurement controls

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#12523]
It has been discovered in #12305 that the permanence of the clock manager measure controls become an issue across low power boundaries.

Specifically, the measurement control settings are enabled and locked prior to the device going into low power.
However, the act of going into low power actually resets the AST's clock calibration settings, which means upon resume, before software has a chance to run, the measurement settings are completely mismatched to uncalibrated clocks.

This causes false recoverable issues immediately, before ROM even has a chance to run. 

The measurement controls need to auto disable if the clock calibration is lost.  Similar clock calibration lost probably needs to become an interrupt in sensor_ctrl so software can be aware that something has happened.

**Comment by tjaychen** [comment]
@Jacob-Levy 
@zi-v 

let me know if the behavior of AST in this place sounds correct to you. I believe it is, so the surrounding system just needs to adjust for it.

**Comment by Jacob-Levy** [comment]
@tjaychen  All the clock generated by the AST are uncalibrated on cold power-up.
When entering to deep sleep, the AON stay calibrated while the other clocks are reset to the uncalibrated (USB, SYS & IO). 
When entering deep sleep the measurement for those clocks need to be disable.
Resume measurement need to be done at the same time as in after cold power-up.

**Comment by tjaychen** [comment]
@jeoongp are you okay with having a look at this issue?

**Comment by jeoongp** [comment]
I was not able to generate this issue on a chip level test but did not work.
As discussed with @tjaychen, we need a new test as follows. 

Timothy Chen, 46 min
there is no test that creates this issue yet
you basically need a top level test
that creates a fault
inside clkmgr/rstmgr/pwrmgr
then you will see that the fault never goes away
even if the system fully escalates
you can probably talk to Cindy / Jaedon about which test most closely resembles this at the moment

**Comment by tjaychen** [comment]
o sorry, i completely mixed up issues.
The discussion i was having with @jeoongp was actually meant to apply to #12284, although this is related. 
let me close this down for now. 

This all related to #12865
