### ISSUE TITLE
[bazel] lowRISC/misc-linters does not cache Python wheels

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#12538]
The lowRISC/misc-linters repository currently makes use of the default `rules_python` repository to register a hermetic Python toolchain and packages. Like #12091, the Python wheels in this dependency must be cached so that this (opentitan) repo can be built in an air-gapped environment. To accomplish this:

**_Addressed in: [lowRISC/misc-linters:#28](https://github.com/lowRISC/misc-linters/pull/28)_**
- [x] the [`lowRISC/misc-linters`](https://github.com/lowRISC/misc-linters) repository must be updated to
    - [x] use the patched [`rules_python`](https://github.com/lowRISC/rules_python) repository (that allows passing the `pip_install` rule a local directory to look for packages before going to the network), and
    - [x] cache the Python wheels downloaded by the `pip_install` rule (similar to #12091) 

**_Addressed in: #12562_**
- [x] the commit and sha of the `lowRISC/misc-linters` dependency (in this Bazel workspace) must be updated to include the above updates

**_Addressed in: TBD_**
- [ ] determine what is causing the lint rules to be a dep of the chip-level test (`opentitan_functest`) targets

**Comment by rswarbrick** [comment]
As a meta-question: do we care? It seems a bit bizarre to be hot on running a licence check linting flow in an air-gapped environment! Can't we just not bother running it?

**Comment by timothytrippel** [comment]
That's a great question, and one I asked myself before I endeavored down this path,  and the answer I still believe is that we shouldn't need to! However, reality set in, and I had to side line my idealist approach in the interim. 

Specifically when I run a `bazel build --distdir=$BAZEL_DISTDIR --repository_cache=$BAZEL_CACHE //sw/device/tests:aes_smoketest` on the air-gapped machine, it hangs, trying to fetch the  `@lowrisc_linter` repository, see below screen shot:

<img width="640" alt="Screen Shot 2022-05-09 at 9 52 07 PM" src="https://user-images.githubusercontent.com/5633066/167545202-bc06ef34-a635-425f-8fae-4236d40d4434.png">

But this was puzzling to me because the bazel documentation clearly states "_By default, external dependencies are fetched as needed during `bazel build`_", and when I run a `bazel query "deps(//sw/device/tests:aes_smoketest)"` to see if the lint rules are indeed a dep of a chip-level test target, I do not see that they are. See below screenshot:
<img width="343" alt="Screen Shot 2022-05-09 at 9 50 14 PM" src="https://user-images.githubusercontent.com/5633066/167545592-b11eea01-80e0-4de9-a0f6-5b4f740137e8.png">

So something odd is happening that I need to track down, but until then I did not want to hold up the Bazel transition on something I know how to fix in the iterim. Specifically, [I already learned how to cache Python wheels](https://github.com/lowRISC/opentitan/pull/12091) that are downloaded/installed with the `pip_install` Bazel rule, so I used this same approach here (which works).

I will keep this issue open, and had added a task (see above) to track down this issue to eventually simplify the need to this work around.

**Comment by rswarbrick** [comment]
Ah, I see. I guess I was asking something even stupider: why are we running the licence checker in Bazel, which I thought was supposed to be for building our software? It's not clear to me that compiling a bunch of C and assembly code requires a linting script that looks at the first few lines of each file...

**Comment by timothytrippel** [comment]
It is for two reasons: 1) provide developers with a simple `bazel run quality`-like command that allows them to run all necessary linter scripts/programs on all altered files in the repo locally (before submitting a PR), and 2) to enable CI to eventually (one day) consist of three simple steps (obviously simplifying here):
    a) `bazel run quality`
    b) `bazel build //...`
    c) `bazel test //...`
