### ISSUE TITLE
[flash_ctrl]: XCELIUM COVERAGE NOT COLLECTED

### ISSUE THREAD

**Issue by nikola-miladinovic** [lowRISC/opentitan#12544]
Seems like some CCF files are missing. If I try to run Xcelium with switch "--cov", I am getting following:

## Failure Buckets
* `xmelab: *E,C58DUT: "-COVDUT flash_ctrl_wrapper", specified on command line, module "flash_ctrl_wrapper" not found in the design.` has 1 failures:
    * Test default has 1 failures.
        * default\
          Line 1226, in log /scratch/google/goo_opentitan/nikolam/flash_ctrl_func_cov_evict/flash_ctrl_wrapper-sim-xcelium/default/build.log

                xmelab: *E,C58DUT: "-COVDUT flash_ctrl_wrapper", specified on command line, module "flash_ctrl_wrapper" not found in the design.
                xmelab: *W,ICFNFR: Module "flash_ctrl_wrapper", specified on line 10 of file "/projects/google/goo_opentitan/nikolam/commit_dir/opentitan/hw/dv/tools/xcelium/cover.ccf", not found in the design.
                xmelab: *W,ICFNFR: Module "prim_alert_receiver", specified on line 16 of file "/projects/google/goo_opentitan/nikolam/commit_dir/opentitan/hw/dv/tools/xcelium/cover.ccf", not found in the design.
                xmelab: *W,ICFNFR: Module "prim_esc_sender", specified on line 17 of file "/projects/google/goo_opentitan/nikolam/commit_dir/opentitan/hw/dv/tools/xcelium/cover.ccf", not found in the design.
                xmelab: *W,ICFNFR: Module "prim_esc_receiver", specified on line 18 of file "/projects/google/goo_opentitan/nikolam/commit_dir/opentitan/hw/dv/tools/xcelium/cover.ccf", not found in the design.

**Comment by nikola-miladinovic** [comment]
@weicaiyang : Same messages can be seen on https://reports.opentitan.org/hw/ip/flash_ctrl/dv/latest/results.html

**Comment by nikola-miladinovic** [comment]
@cindychip the workaround is: remove set_fsm_arc_scoring from the CCF. I tried it and it worked. It might affect FSM transition coverage.

**Comment by cindychip** [comment]
Like @nikola-miladinovic mentioned, this is only a workaround, we will keep this issue open until we have a real solution from Xcelium.

**Comment by nikola-miladinovic** [comment]
I am seeing some FSM issues - same state has different coding and that is causing false coverage
![example_wrong_fsm_cov](https://user-images.githubusercontent.com/93394800/170091395-1e77a7a3-eb3f-4417-9268-de8658c3c228.JPG)
.

**Comment by weicaiyang** [comment]
closing this as we change to use VCS
