### ISSUE TITLE
Adding sysrst_ctrl exclusions

### ISSUE THREAD

**Issue by patel-madhuri** [lowRISC/opentitan#12543]
As discussed in the sysrst_ctrl V2 review meeting can we add the sysrst_ctrl exclusions needed from the sysrst_ctrl_detect module and from others if there are any?

**Comment by msfschaffner** [comment]
@cindychip, @weicaiyang what procedure should we follow here to generate the exclusion file?

**Comment by weicaiyang** [comment]
@patel-madhuri 

We may not need to add coverage exclusion. COND and FSM coverage is close to 90%.
sysrst_ctrl_edge_detect and sysrst_ctrl_combo_detect are failing in some seeds. Please fix them, then we may see COND and FSM over 90%.
Please also try to bring group coverage to 90%. You may add some GC but didn't sample correctly.
We can ignore the assert coverage for now as it's due to prim_sync_cdc_delay. The module is added but random delay hasn't been enabled.

SCORE | LINE | COND | TOGGLE | FSM | BRANCH | ASSERT | GROUP
-- | -- | -- | -- | -- | -- | -- | --
81.48 | 98.22 | 87.32 | 100.00 | 86.36 | 92.77 | 85.94 | 19.77

**Comment by weicaiyang** [comment]
This https://github.com/lowRISC/opentitan/pull/12559 will remove the CDC assertions.

**Comment by patel-madhuri** [comment]
I think fixing sysrst_ctrl_edge_detect and combo_detect test will not improve the condition coverage as there are few condition which will not be covered by the test. Below are the few conditions which we might need to exclude to improve the condition coverage
<html>
<body>
<pre class="code" style="font-size: larger; font-weight: bold; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">LINE       92
 SUB-EXPRESSION (cnt_en ? ((cnt_q + 1'b1)) : cnt_q)
                 ---1--
</pre><div class="JCLRgrips" style="height: 0px; position: relative; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; width: 216px;"><div class="JCLRgrip" style="margin-left: -5px; position: absolute; z-index: 5; left: 41px; height: 74px;"><div class="JColResizer" style="table-layout: fixed; position: absolute; background-color: red; opacity: 0; width: 10px; height: 74px; cursor: e-resize; top: 0px;"></div></div><div class="JCLRgrip" style="margin-left: -5px; position: absolute; z-index: 5; left: 132px; height: 74px;"><div class="JColResizer" style="table-layout: fixed; position: absolute; background-color: red; opacity: 0; width: 10px; height: 74px; cursor: e-resize; top: 0px;"></div></div><div class="JCLRgrip JCLRLastGrip" style="margin-left: -5px; position: absolute; z-index: 5; width: 1px; left: 217px; height: 74px;"></div></div>

-1- | Status | Tests
-- | -- | --
0 | Not Covered |  
1 | Covered | T15,T21,T28

<br class="Apple-interchange-newline">
</body>
</html>

<html>
<body>
<pre class="code" style="font-size: larger; font-weight: bold; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">LINE       187
 EXPRESSION (((!cfg_enable_i)) || ((!trigger_active)))
             --------1--------    ---------2---------
</pre><div class="JCLRgrips" style="height: 0px; position: relative; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; width: 256px;"><div class="JCLRgrip" style="margin-left: -5px; position: absolute; z-index: 5; left: 41px; height: 98px;"><div class="JColResizer" style="table-layout: fixed; position: absolute; background-color: red; opacity: 0; width: 10px; height: 98px; cursor: e-resize; top: 0px;"></div></div><div class="JCLRgrip" style="margin-left: -5px; position: absolute; z-index: 5; left: 81px; height: 98px;"><div class="JColResizer" style="table-layout: fixed; position: absolute; background-color: red; opacity: 0; width: 10px; height: 98px; cursor: e-resize; top: 0px;"></div></div><div class="JCLRgrip" style="margin-left: -5px; position: absolute; z-index: 5; left: 172px; height: 98px;"><div class="JColResizer" style="table-layout: fixed; position: absolute; background-color: red; opacity: 0; width: 10px; height: 98px; cursor: e-resize; top: 0px;"></div></div><div class="JCLRgrip JCLRLastGrip" style="margin-left: -5px; position: absolute; z-index: 5; width: 1px; left: 257px; height: 98px;"></div></div>

-1- | -2- | Status | Tests
-- | -- | -- | --
0 | 0 | Covered | T15,T21,T38
0 | 1 | Covered | T19,T20
1 | 0 | Not Covered |  

<br class="Apple-interchange-newline">
</body>
</html>

<html>
<body>
<pre class="code" style="font-size: larger; font-weight: bold; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">LINE       208
 EXPRESSION (((!cfg_enable_i)) || (((!trigger_active)) &amp;&amp; ((!Sticky))))
             --------1--------    ------------------2-----------------
</pre><div class="JCLRgrips" style="height: 0px; position: relative; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; width: 256px;"><div class="JCLRgrip" style="margin-left: -5px; position: absolute; z-index: 5; left: 41px; height: 98px;"><div class="JColResizer" style="table-layout: fixed; position: absolute; background-color: red; opacity: 0; width: 10px; height: 98px; cursor: e-resize; top: 0px;"></div></div><div class="JCLRgrip" style="margin-left: -5px; position: absolute; z-index: 5; left: 81px; height: 98px;"><div class="JColResizer" style="table-layout: fixed; position: absolute; background-color: red; opacity: 0; width: 10px; height: 98px; cursor: e-resize; top: 0px;"></div></div><div class="JCLRgrip" style="margin-left: -5px; position: absolute; z-index: 5; left: 172px; height: 98px;"><div class="JColResizer" style="table-layout: fixed; position: absolute; background-color: red; opacity: 0; width: 10px; height: 98px; cursor: e-resize; top: 0px;"></div></div><div class="JCLRgrip JCLRLastGrip" style="margin-left: -5px; position: absolute; z-index: 5; width: 1px; left: 257px; height: 98px;"></div></div>

-1- | -2- | Status | Tests
-- | -- | -- | --
0 | 0 | Covered | T15,T21,T38
0 | 1 | Covered | T15,T21,T38
1 | 0 | Not Covered |  

<br class="Apple-interchange-newline">
</body>
</html>

One of the branch coverage as well:
<html>
<body>
<pre class="code" style="font-size: larger; font-weight: bold;">LineNo.	Expression
-1-:	92	(cnt_clr) ? 
-2-:	92	(cnt_en) ? 
</pre><br clear="all"><span class="repname" style="position: relative; font-weight: bold;">Branches:</span><br clear="all"><div class="JCLRgrips" style="height: 0px; position: relative; width: 325px;"><div class="JCLRgrip" style="margin-left: -5px; position: absolute; z-index: 5; left: 81px; height: 120px;"><div class="JColResizer" style="table-layout: fixed; position: absolute; background-color: red; opacity: 0; width: 10px; height: 120px; cursor: e-resize; top: 0px;"></div></div><div class="JCLRgrip" style="margin-left: -5px; position: absolute; z-index: 5; left: 161px; height: 120px;"><div class="JColResizer" style="table-layout: fixed; position: absolute; background-color: red; opacity: 0; width: 10px; height: 120px; cursor: e-resize; top: 0px;"></div></div><div class="JCLRgrip" style="margin-left: -5px; position: absolute; z-index: 5; left: 241px; height: 120px;"><div class="JColResizer" style="table-layout: fixed; position: absolute; background-color: red; opacity: 0; width: 10px; height: 120px; cursor: e-resize; top: 0px;"></div></div><div class="JCLRgrip JCLRLastGrip" style="margin-left: -5px; position: absolute; z-index: 5; width: 1px; left: 326px; height: 120px;"></div></div><table align="left" class="noborder JColResizer" id="JColResizer359" style="empty-cells: show; border-spacing: 0px; border: none; border-collapse: collapse; table-layout: fixed;"><tbody><tr><th nowrap="" style="text-align: center; overflow: hidden; padding-left: 0px !important; padding-right: 0px !important; width: 80px;">-1-</th><th nowrap="" style="text-align: center; overflow: hidden; padding-left: 0px !important; padding-right: 0px !important; width: 80px;">-2-</th><th nowrap="" style="text-align: center; overflow: hidden; padding-left: 0px !important; padding-right: 0px !important; width: 80px;">Status</th><th nowrap="" style="text-align: center; overflow: hidden; padding-left: 0px !important; padding-right: 0px !important; width: 85px;">Tests</th></tr><tr class="uGreen" style="color: rgb(0, 255, 0);"><td align="center" style="border: 1px solid rgb(170, 170, 170); overflow: hidden; padding-left: 0px !important; padding-right: 0px !important;">1</td><td align="center" nowrap="" style="border: 1px solid rgb(170, 170, 170); overflow: hidden; padding-left: 0px !important; padding-right: 0px !important;">-</td><td style="border: 1px solid rgb(170, 170, 170); overflow: hidden; padding-left: 0px !important; padding-right: 0px !important;">Covered</td><td style="border: 1px solid rgb(170, 170, 170); overflow: hidden; padding-left: 0px !important; padding-right: 0px !important;"><span title="/workspace/coverage/default/8.sysrst_ctrl_auto_blk_key_output.1374163344">T15</span>,<span title="/workspace/coverage/default/3.sysrst_ctrl_in_out_inverted.1424373369">T17</span>,<span title="/workspace/coverage/default/40.sysrst_ctrl_flash_wr_prot_out.1938784458">T18</span></td></tr><tr class="uGreen" style="color: rgb(0, 255, 0);"><td align="center" style="border: 1px solid rgb(170, 170, 170); overflow: hidden; padding-left: 0px !important; padding-right: 0px !important;">0</td><td align="center" style="border: 1px solid rgb(170, 170, 170); overflow: hidden; padding-left: 0px !important; padding-right: 0px !important;">1</td><td style="border: 1px solid rgb(170, 170, 170); overflow: hidden; padding-left: 0px !important; padding-right: 0px !important;">Covered</td><td style="border: 1px solid rgb(170, 170, 170); overflow: hidden; padding-left: 0px !important; padding-right: 0px !important;"><span title="/workspace/coverage/default/9.sysrst_ctrl_edge_detect.3890496850">T16</span>,<span title="/workspace/coverage/default/41.sysrst_ctrl_edge_detect.177162000">T94</span>,<span title="/workspace/coverage/default/30.sysrst_ctrl_edge_detect.1169395399">T82</span></td></tr><tr class="uRed" style="color: rgb(255, 0, 0);"><td align="center" style="border: 1px solid rgb(170, 170, 170); overflow: hidden; padding-left: 0px !important; padding-right: 0px !important; color: rgb(255, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">0</td><td align="center" style="border: 1px solid rgb(170, 170, 170); overflow: hidden; padding-left: 0px !important; padding-right: 0px !important; color: rgb(255, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">0</td><td style="border: 1px solid rgb(170, 170, 170); overflow: hidden; padding-left: 0px !important; padding-right: 0px !important; color: rgb(255, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Not Covered</td><br class="Apple-interchange-newline">
</body>
</html>

As these are from the sysrst_ctrl_detect, they are common across all the modules and affect the total coverage.

**Comment by patel-madhuri** [comment]
The ultra low power test is only 1 seed failing out of 50 but the condition coverage is only 78.57 and branch coverage is only 76.19. The coverage holes are the above conditions, thus we need to exclude them.

**Comment by weicaiyang** [comment]
@patel-madhuri I will work with Michael to look into these COND and FSM coverage. In the meanwhile, please fix the regression failures and improve the functional coverage.

**Comment by patel-madhuri** [comment]
The condition coverage is now at 96.45% and new V3 test is identified to fill in the FSM coverage. The required exclusions are in place for sysrst_ctrl. I am closing this issue.
