### ISSUE TITLE
Add pattgen exclusions

### ISSUE THREAD

**Issue by patel-madhuri** [lowRISC/opentitan#12545]
As discussed in the V2 review meeting can we add the pattgen exclusions to meet the V2 milestone coverage goals?

**Comment by cindychip** [comment]
Hi Madhuri,

Thanks for the issue, I commented it here:
https://github.com/lowRISC/opentitan/issues/12117#issuecomment-1121637322

**Comment by patel-madhuri** [comment]
@cindychip The toggle coverage and expression coverage after adding exclusion have below holes:
1. The pin **cio_pda0_tx_o** is excluded from the toggle coverage which I don't think we should do it as it is data signal for channel 0. 
2. The pins **tl_i.a_param, tl_i.a_user, tl_o.d_param, tl_o.d_sink, devmode_i** from **pattgen** are excluded but they are not excluded from **pattgen.u_reg**. Do we need to exclude from pattgen.u_reg entity as well?
3. Similar signals are in **pattgen.tlul_assert_device**	entity as well. Do we need to exclude these as well?

**Comment by cindychip** [comment]
Thanks for the message @patel-madhuri!
1). I can add back cio_pda0_tx_o
2). This is already done by Weicai's fix. You should see it from today's PR.
3). Agree the condition coverage is not really needed there. Let me make a PR to remove it.

**Comment by patel-madhuri** [comment]
Thank you Cindy for adding the exclusions. 
Since all the exclusions are in place and pattgen is now signed off for V2S, I am closing this issue.
