### ISSUE TITLE
[bazel] Symbol visibility

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#12551]
Visibility of global symbols in the ELF file built with bazel is DEFAULT, vs. HIDDEN when built with meson.

See this [line](https://github.com/lowRISC/opentitan/blob/a7b30e63694cdf92ca70ba61f15492d6039a8e95/meson.build#L91) and the `readelf` outputs [here](https://docs.google.com/document/d/1p3Yqj4-iupAnJGPCzI_P3Pbc8X3hcCJl56D5MvbBJIo/edit#heading=h.pelu664rrre5).

**Comment by msfschaffner** [comment]
@alphan is this still relevant?

**Comment by a-will** [comment]
And thank goodness for that! It's much easier to debug on the FPGA when we can load the ELF w/ symbols in gdb.

**Comment by msfschaffner** [comment]
Ok to close this?

**Comment by a-will** [comment]
Yup, we build the ELF with debug symbols in bazel now.
