### ISSUE TITLE
[dv, top] Top level tests run time on the foundry database 

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#12564]
Run time is very big in the foundry database is very big, makes debug very hard.
For example lc_ctrl_transition run time in the foundry is x20/x30 compared to open source.
Is there some VCS compiler available?

**Comment by tjaychen** [comment]
@sha-ron is there any way for you to profile if the simulator is stuck spending time on the proprietary models? or is the problem elsewhere?

**Comment by sha-ron** [comment]
@tjaychen I thought maybe VCS has a profiler that can help to determine that.

**Comment by weicaiyang** [comment]
@sha-ron 
to enable VCS profiling, just add `--profile time` for dvsim.py when you run the test

**Comment by weicaiyang** [comment]
The foundry test lc_ctrl_transition indeed takes a very long time. it's 23+hour now, but still not finished yet
Will contact AE to take a look.

**Comment by sha-ron** [comment]
Thanks weicai.

**Comment by sha-ron** [comment]
Closed by PR 12540 in foundry.
