### ISSUE TITLE
Xbar generation example cannot run in latest version 

### ISSUE THREAD

**Issue by nono0210** [lowRISC/opentitan#1258]
when i do the following cmd, the code can be gen Ok but now with lastest version, it cannot 
./util/tlgen.py  -t util/example/tlgen/xbar_main.hjson -o ~/tmp/

Traceback (most recent call last):
  File "./util/tlgen.py", line 101, in <module>
    main()
  File "./util/tlgen.py", line 68, in main
    xbar = tlgen.validate(obj)
  File "/home/jiazhu/opentitan/util/tlgen/validate.py", line 198, in validate
    xbar.reset = obj["reset"].lower()
KeyError: 'reset'

**Comment by eunchan** [comment]
Thanks. example hjson isn't updated. @tjaychen for visibility.

**Comment by eunchan** [comment]
The fix is merged now. Can we close this issue?

**Comment by nono0210** [comment]
I can run example to gen the xbar successfully

**Comment by nono0210** [comment]
i have close the ticket




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Eunchan Kim"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月9日(星期四) 上午7:12
收件人:&nbsp;"lowRISC/opentitan"<opentitan@noreply.github.com&gt;;
抄送:&nbsp;"misanthrope"<691460028@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lowRISC/opentitan] Xbar generation example cannot run in latest version  (#1258)




The fix is merged now. Can we close this issue?

**Comment by nono0210** [comment]
Have already close the ticket



---Original---
