### ISSUE TITLE
[sw/silicon_creator] update rom_ext_virtual length in top_earlgrey_memory.ld

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#12596]
We need to revisit this definition since it currently assigns the entire half of the eFlash to ROM_EXT.

Maybe we can use the value of `MANIFEST_LENGTH_FIELD_ROM_EXT_MAX` (should be 64 KiB) here.

_Originally posted by @alphan in https://github.com/lowRISC/opentitan/pull/11761#discussion_r865046342_

**Comment by engdoreis** [comment]
@alphan can I consider the rom_ext size as 64kb?

**Comment by alphan** [comment]
> @alphan can I consider the rom_ext size as 64kb?

Yes, the current value for max ROM_EXT size is 64 KiB.

**Comment by engdoreis** [comment]
Closing as it was addressed by #11761
