### ISSUE TITLE
[flash_ctrl] mp_error Status - Potential Issue

### ISSUE THREAD

**Issue by TimEwins** [lowRISC/opentitan#12600]
Hi @tjaychen 

I have been working on the error_mp test, which looks to trap mp violations, and deal with them.

I see some behaviour which may be incorrect.  I will explain what I am doing and seeing here.

The test does this: -

// Pseudo Code
// Initialize Random Flash MP Regions, Enable Default Regions
// Loop (x)
//   Randomize a Flash Program Operation (any Partition)
//   Predict if the selected operation will cause an MP violation, or not
//   Set scoreboard to accept alert, if predicted
//   Perform selected Flash Operation
//   If no violation is expected, check data integrity (via backdoor)
//   Check Status Registers
// End

I am seeing some issues with 'Check Status Registers'.

I have simplified the randomization, using only the data patitions and Read Ops.  Also rather than 'handle' the status bits individually, after every cycle, violation expected or not, I reset all the status registers.  This is to see what the RTL is actually doing, with minimal TB interaction.  

Here is a problem transaction: -

UVM_INFO @  56758439 ps: Iteration : 26 : 194
UVM_INFO @  56758439 ps: MP REGION INFORMATION (DATA PARTITIONS)
UVM_INFO @  56758439 ps: flash_op : '{partition:FlashPartData, erase_type:FlashErasePage, op:FlashOpRead, num_words:'ha, addr:'h69817}
UVM_INFO @  56758439 ps: MPR0 : From : 0x122, To : 0x123 : From : 0x00091000, To : 0x00091800
UVM_INFO @  56758439 ps: MPR1 : From : 0x03b, To : 0x050 : From : 0x0001d800, To : 0x00028000
UVM_INFO @  56758439 ps: MPR2 : From : 0x1b4, To : 0x1c9 : From : 0x000da000, To : 0x000e4800
UVM_INFO @  56758439 ps: MPR3 : From : 0x15c, To : 0x175 : From : 0x000ae000, To : 0x000ba800
UVM_INFO @  56758439 ps: MPR4 : From : 0x0d1, To : 0x0f1 : From : 0x00068800, To : 0x00078800
UVM_INFO @  56758439 ps: MPR5 : From : 0x064, To : 0x065 : From : 0x00032000, To : 0x00032800
UVM_INFO @  56758439 ps: MPR6 : From : 0x059, To : 0x060 : From : 0x0002c800, To : 0x00030000
UVM_INFO @  56758439 ps: MPR7 : From : 0x1e7, To : 0x1e8 : From : 0x000f3800, To : 0x000f4000
UVM_INFO @  56758439 ps: Read : MP Region : Address : MISS : MPR0
UVM_INFO @  56758439 ps: Read : MP Region : Address : MISS : MPR1
UVM_INFO @  56758439 ps: Read : MP Region : Address : MISS : MPR2
UVM_INFO @  56758439 ps: Read : MP Region : Address : MISS : MPR3
UVM_INFO @  56758439 ps: Read : MP Region : Address :  HIT : MPR4
UVM_INFO @  56758439 ps: Read : MP Region : Address : MISS : MPR5
UVM_INFO @  56758439 ps: Read : MP Region : Address : MISS : MPR6
UVM_INFO @  56758439 ps: Read : MP Region : Address : MISS : MPR7
UVM_INFO @  56758439 ps: Expect : VIOLATION

The MPR0-7 lines show the chosen mp address regions from the randomization of the mp regions.  Which are set at the start of the test.

The MISS/HIT shows if the given flash op, HITs or MISSes an mp area. 

In this instance .. flash op is address 'h69817, which its the address range of MPR4.

Ok the next thing we need to look at is the settings for this region.  This is randomly set at the start of the test, and with this seed is: -

UVM_INFO @   2075204 ps: TEST : error_mp
UVM_INFO @   2422139 ps: MP DATA Region [0] : '{en:MuBi4False, read_en:MuBi4True, program_en:MuBi4False, erase_en:MuBi4True, scramble_en:MuBi4False, ecc_en:MuBi4False, he_en:MuBi4True, num_pages:'h1, start_page:'h122}
UVM_INFO @   2554791 ps: MP DATA Region [1] : '{en:MuBi4True, read_en:MuBi4True, program_en:MuBi4True, erase_en:MuBi4False, scramble_en:MuBi4False, ecc_en:MuBi4False, he_en:MuBi4False, num_pages:'h15, start_page:'h3b}
UVM_INFO @   2728259 ps: MP DATA Region [2] : '{en:MuBi4False, read_en:MuBi4False, program_en:MuBi4False, erase_en:MuBi4False, scramble_en:MuBi4False, ecc_en:MuBi4False, he_en:MuBi4True, num_pages:'h15, start_page:'h1b4}
UVM_INFO @   2840503 ps: MP DATA Region [3] : '{en:MuBi4True, read_en:MuBi4False, program_en:MuBi4False, erase_en:MuBi4False, scramble_en:MuBi4False, ecc_en:MuBi4False, he_en:MuBi4True, num_pages:'h19, start_page:'h15c}

UVM_INFO @   2922135 ps: MP DATA Region [4] : '{en:MuBi4False, read_en:MuBi4True, program_en:MuBi4False, erase_en:MuBi4False, scramble_en:MuBi4False, ecc_en:MuBi4False, he_en:MuBi4False, num_pages:'h20, start_page:'hd1}

UVM_INFO @   3064991 ps: MP DATA Region [5] : '{en:MuBi4True, read_en:MuBi4True, program_en:MuBi4False, erase_en:MuBi4True, scramble_en:MuBi4False, ecc_en:MuBi4False, he_en:MuBi4True, num_pages:'h1, start_page:'h64}
UVM_INFO @   3116011 ps: MP DATA Region [6] : '{en:MuBi4True, read_en:MuBi4True, program_en:MuBi4False, erase_en:MuBi4True, scramble_en:MuBi4False, ecc_en:MuBi4False, he_en:MuBi4False, num_pages:'h7, start_page:'h59}
UVM_INFO @   3279275 ps: MP DATA Region [7] : '{en:MuBi4True, read_en:MuBi4False, program_en:MuBi4True, erase_en:MuBi4True, scramble_en:MuBi4False, ecc_en:MuBi4False, he_en:MuBi4False, num_pages:'h1, start_page:'h1e7}

MP Region 4 has en:MuBi4False, so this area is disabled, so we would expect an mp violation, and the TB predicts this (above)

BUT if we look at the waves, the DUT has not registered an error.  So the Status bits are not set as predicted? (look at timestamp, and TimeD.

![Screen Shot 05-11-22 at 05 46 PM](https://user-images.githubusercontent.com/92723163/167907656-be5d642f-77fb-4792-84ac-269ee686b77a.PNG)

This gives problems, and looks incorrect.

Interestingly othe areas are correctly handled, as can be seen in the waves.

I have pushed branch that recreates this ..

https://github.com/TimEwins/opentitan/tree/flash_ctrl_error_mp

If you have time to look the run command is

./util/dvsim/dvsim.py hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson -i flash_ctrl_error_mp --tool xcelium -v h --verbosity m --purge --max-parallel 1 --fixed-seed 1 --gui

Note the test passes, because the TB is not checking the Status bits at the moment, to show the potential issue.

What do you think, or have we missed something here?

Regards
TimE

Note there are quite a few TB file changes in this branch, which are all temporary and for debug.  I was trying to see if the Status Reg issues were TB related, but now I think it might be elsewhere.

**Comment by tjaychen** [comment]
@TimEwins let me pull this and have a look.
Based on your description, this sounds like a bug, but I'll have to see the waves to be sure. 

So you're saying it's not just the status, you're not getting an error at all?

**Comment by tjaychen** [comment]
hmmm... when i pull down the test and run, it actually fails. But I can start debugging from there.

**Comment by tjaychen** [comment]
@TimEwins i took a look at this, and I know what the issue is. 
This part isn't described very clearly in the spec, so I'll make sure to do that.

The way your `predict` is written, is that it first matches the region by address, then it matches the enables. So in the failing case, the address falls into the region, then discovers read is not allowed.

However, this is not how the hardware behaves. The enable really tells the hardware whether that region should even be matched.  So if en is 0, it does not matter if the address falls into the region, it is NOT matched. So what happens is that the address actually matches no region, and falls into "default", which in case allows all access.  That's why the hardware doesn't generate an error.

**Comment by TimEwins** [comment]
@tjaychen Hi, That makes sense then.  Nikola has done this check in the scoreboard already, but I was looking at the issue from an independant viewpoint, which is always a good idea.

Thanks for clarifying ...... I will amend the code, and retest.

Then I will close this issue.

**Comment by TimEwins** [comment]
This test issue is resolved.  The Test is now working as expected.

**Comment by TimEwins** [comment]
Closed
