### ISSUE TITLE
[ci] New bazel-controlled Verilator chip-level tests are unreliable

### ISSUE THREAD

**Issue by milesdai** [lowRISC/opentitan#12603]
#12482 adds a set of Verilator chip-level tests to CI and replaces system test. After merging, it is now apparent that these tests are flaky.

Currently, there are two major classes of problems observed:
1. Timeouts: some of the "fast" tests simply take longer than 1200s. In the UART output, it is clear that the test was cut off midway through printing out a message.
2. Opentitantool errors: currently, the prevalent error observed is that upon creating the backend, OTT times out scanning for output before Verilator starts up. To address this, we plan to add additional printouts to show what's printed at Verilator's stdout and allow the timeout to be configurable.

To address the problems in the meanwhile, I will take the following temporary actions:
- Mark all verilator tests as flaky. This will be done by modifying the opentitan_functest rule to make Verilator tests flaky by default
- Make the verilator tests non-blocking
- Increase the timeout even more for the fast tests

These actions need to be reverted when this issue is addressed.

**Comment by rswarbrick** [comment]
As part of working out how we broke CI here: why did the previous pytest+Meson approach work? Were we just lucky? Or have we changed our timing constraints to be tighter? Or something else?

**Comment by milesdai** [comment]
The key differences are
- Bazel's test runner uses Opentitantool which had a timeout issue when Verilator starts up too slowly (see point 2 above). pytest uses 
- The new set of tests is significantly larger than the previous set (about twice as many tests). This is straining the ci-public machines that run our CI pipeline. This contributed to issue 1 and to some extent issue 2 above.

To get this set of tests running within a reasonable timeframe and within the lower core-count ci-public runners, I needed to build the Verilator model to run single-threaded and then run 4 tests in parallel since each ci-public runner has 4 vCPUs. Turns out 1200s was not quite enough for some of the tests.

We're considering maybe reducing the number of Verilator tests. For instance, tests that are already run on the FPGA may not need to be duplicated on Verilator.

**Comment by rswarbrick** [comment]
Thanks for the explanation. Sounds like the OTT fix should be easy enough (and is a hard requirement if anyone is going to use it with Verilator, I'd have thought).

About reducing the number of Verilator tests: definitely, yes! Are we currently running all our chip-level tests in CI? That's... very different from what the HW team are doing (smoke tests in CI; everything else in nightlies). I'd suggest moving to a similar approach.

**Comment by milesdai** [comment]
It looks like the CI pipeline is getting bogged down with all these additional tests, so I've filed #12611 to cut it back down to the original set of tests being run by systemtest.

**Comment by milesdai** [comment]
#12609 addresses the opentitantool problem. I'll file a PR after that gets merged to take advantage of the new timeout setting and clean up any remaining mess.
