### ISSUE TITLE
Reggen  genrated HTML file fails whitespace check.

### ISSUE THREAD

**Issue by Jacob-Levy** [lowRISC/opentitan#12643]
```
% util/fix_trailing_whitespace.py hw/top_earlgrey/ip/ast/doc/ast_regs.html
Fixing file: "hw/top_earlgrey/ip/ast/doc/ast_regs.html"
Fixed 1 files.

% git diff hw/top_earlgrey/ip/ast/doc/ast_regs.html
diff --git a/hw/top_earlgrey/ip/ast/doc/ast_regs.html b/hw/top_earlgrey/ip/ast/doc/ast_regs.html
index 8ef38e7d2..2153f1ad4 100644
--- a/hw/top_earlgrey/ip/ast/doc/ast_regs.html
+++ b/hw/top_earlgrey/ip/ast/doc/ast_regs.html
@@ -2,7 +2,7 @@
  table.regpic {
   width: 95%;
   border-collapse: collapse;
-  margin-left:auto; 
+  margin-left:auto;
   margin-right:auto;
   table-layout:fixed;
  }
@@ -10,7 +10,7 @@
   border: 1px solid black;
   width: 80%;
   border-collapse: collapse;
-  margin-left:auto; 
+  margin-left:auto;
   margin-right:auto;
   table-layout:auto;
  }
```

**Comment by rswarbrick** [comment]
I don't think I understand this issue. We're not checking in the generated HTML, are we? Why do we care about the formatting of generated files?

**Comment by rswarbrick** [comment]
Hmm. Possibly stupid question, but what command are you using to generate this HTML file?

**Comment by Jacob-Levy** [comment]
The check of trailing whitespace check every text file that is Pared.

**Comment by Jacob-Levy** [comment]
I need to check if our post processing of the  HTML to make it look nicer is not adding the offending lines.

**Comment by Jacob-Levy** [comment]
It is our addition of 'style.html' that has the trailinrg whitespace. Closing issue!

**Comment by Jacob-Levy** [comment]
> Hmm. Possibly stupid question, but what command are you using to generate this HTML file?

`  ${WA_ROOT}/opentitan/util/regtool.py -d -o ./ntil_doc/ast_regs.html ./data/ast_ntiil.hjson`
