### ISSUE TITLE
Changing the address translation flag in the manifest during the signing

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#12641]
# Introduction
The address translation [PR](https://github.com/lowRISC/opentitan/pull/12592) has introduced a new `ROM_EXT` binary type. The `rom_ext_virtual_addr` requires the `address_translation` field of the manifest to be true, on the other hand it must be false for the `rom_ext_slot_a` and `rom_ext_slot_b`.

# Problem
The current signer is hardcoding the `address_translation` field to `kHardenedBoolTrue`, which is fine as far as we intend to use the `rom_ext_virtual_addr` for now on. However it prevents easily running the legacy binaries for a test purpose or any other reason.

# What should be done
- Change the signer to accept an argument specifying the type of binary or even the desired value of the `address_translation` field.
- Change the build system (bazel files) to enable address translation only for the `rom_ext_virtual_addr`.

**Comment by engdoreis** [comment]
@alphan for visibility.

**Comment by msfschaffner** [comment]
@alphan is this still relevant? can you recategorize the milestone / prio as needed?

**Comment by alphan** [comment]
Nope, this is handled properly by `bazel` and `opentitantool` now. Thanks @jon-flatley!
