### ISSUE TITLE
Running meson_init.sh complains about runtime dependency libftdi1 not found, though it is installed

### ISSUE THREAD

**Issue by aloke-tortuga** [lowRISC/opentitan#1266]
I am trying to build 'top_earlgrey' using the Makefile in hw/top_earlgrey/Makefile

I noticed that while executing the following command:

cd $REPO_TOP/hw/dv/tools/../../.. && \
BUILD_ROOT=$REPO_TOP/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/latest/sw_build/meson $REPO_TOP/hw/dv/tools/../../../meson_init.sh -f

it reports:
Program python3 found: YES (/usr/bin/python3)
Program srec_cat found: YES (/usr/bin/srec_cat)
Program git found: YES (/usr/bin/git)
Found pkg-config: /usr/bin/pkg-config (0.28)
Found CMake: /usr/bin/cmake (3.10.2)
Build-time dependency libftdi1 found: NO (tried pkgconfig and cmake)

sw/host/vendor/meson.build:5:0: ERROR: Dependency "libftdi1" not found, tried pkgconfig and cmake

However, I have this installed on the build machine:

apt-file search libftdi1.so
libftdi1-2: /usr/lib/x86_64-linux-gnu/libftdi1.so.2
libftdi1-2: /usr/lib/x86_64-linux-gnu/libftdi1.so.2.4.0
libftdi1-dev: /usr/lib/x86_64-linux-gnu/libftdi1.so

Is there something I am missing?

Also, the following lines in 'meson_init.sh' seem to be causing to silently ignore all the error messages (I needed to comment them out to find any issues with my run):
   set -o errexit
   set -o pipefail
   set -o nounset

**Comment by imphil** [comment]
- Have you installed all packages listed in https://docs.opentitan.org/doc/ug/install_instructions/#system-preparation? In this case, it could be that libftdi1-dev is missing.
- About the ignored errors: @mcy could you have a look?

**Comment by aloke-tortuga** [comment]
Many thanks! It was that libftd1-dev was indeed missing. The build was successful after installing this one. Appreciate your help!

**Comment by mcy** [comment]
I'm confused about "ignoring error messages". `set -o errexit` (aka `set -e`) should be causing the script to halt immediately if any command within it produces a non-zero exit.

**Comment by aloke-tortuga** [comment]
The script, indeed, halted immediately when an error condition occurred (e.g. meson was not installed). However, it did not produce any error message on the stdout. I started seeing the error messages only after commenting out these lines.  At that point it started becoming easier to debug the build failure. But, I understand that I did not install some essential components.
