### ISSUE TITLE
[sysrst_ctrl, dv] Add a test to improve code coverage

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#12673]
After reviewed sysrst_ctrl coverage with @msfschaffner , we found cfg_enable has never been set to 0 during detecting an event.

![Screen Shot 2022-05-13 at 1 55 36 PM](https://user-images.githubusercontent.com/49293026/168388736-cff68c6d-ce76-4320-a2ce-aed28e93f064.png)

To cover this, we can add this test
1. enable and start the event detecting
2. set the enable to off
3. no need to check if the event is triggered or not, as we should not care the event in this case and it needs a very cycle accurate model to predict the result. 
4. re-enable and start the event detecting seq again, then check the event happens correctly.
5. apply this to tests - pin edge detect, combo detect, auto block and ulp detect

This will be V3 test for final coverage closure. No need for V2 as we can achieve V2 coverage criteria without this test.

cc: @msfschaffner @patel-madhuri

**Comment by cindychip** [comment]
@cindychip check with SW if this use-case exists.

**Comment by johngt** [comment]
@engdoreis / @luismarques - could you check to see if this is now being tested and can be closed, or state what still needs to be done here?

**Comment by engdoreis** [comment]
I'll take a look when working on the issue https://github.com/lowRISC/opentitan/issues/17548

**Comment by marnovandermaas** [comment]
@engdoreis I think this issue can be closed because https://github.com/lowRISC/opentitan/pull/17371 is merged.

**Comment by marnovandermaas** [comment]
Estimates based on efforts by @crteja and me
> estimate 16
> remaining 2023-03-06 1
> remaining 2023-03-15 0
