### ISSUE TITLE
Consider removing `eflash_virtual` from toplevel_memory.ld.tpl if unused

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#12670]
it looks like `eflash_virtual` is not used anywhere (please confirm). If so, we can remove that to avoid confusion down the line.

_Originally posted by @alphan in https://github.com/lowRISC/opentitan/pull/11761#discussion_r870415579_

**Comment by tjaychen** [comment]
hmmm... i actually thought the current tests used it as part of address translation testing. 
I originally added it as part of #7147.  Is that not used anymore?

**Comment by timothytrippel** [comment]
I had to remove it (see [here](https://github.com/lowRISC/opentitan/commit/610b263796030b80a8ee1f218127deedbe22dc33)) to make OTTF launched tests work with both the test ROM and mask ROM (for mask ROM E2E testing) as the mask ROM did not yet use address translation features and needed the manifest to be at a specific offset. Now that mask ROM uses address translation we can add it back. It looks like there is a separate memory region now called [`rom_ext_virtual`](https://github.com/lowRISC/opentitan/blob/e4fbb47a43882aec395773e5f8f1ea07cae29804/hw/top_earlgrey/sw/autogen/top_earlgrey_memory.ld#L16) so we should just use that in the test ROM to match the mask ROM.

**Comment by timothytrippel** [comment]
so to answer the question of this thread, I believe we can remove the `eflash_virtual` region and just use the `rom_ext_virtual` region, no?

**Comment by tjaychen** [comment]
sounds good!

**Comment by timothytrippel** [comment]
no problem, I have not started working on this. @engdoreis thanks for taking care of this :)

**Comment by timothytrippel** [comment]
@engdoreis, in addition to removing this unused memory region, are you going to be updating the test ROM to use address translation as well? (probably best to keep this in sync with the mask ROM)

**Comment by engdoreis** [comment]
Yes, The test rom is the first boot stage and it would be responsable for configuring the address translation right?
In that case I'll start that as soon the `rv_core_ibex` dif PR https://github.com/lowRISC/opentitan/pull/12662 get merged

**Comment by timothytrippel** [comment]
yeah thats correct, the test ROM is the first to boot for tests, and is responsible for booting the OTTF. Ideally, we want the translation setup to be the same as the mask ROM, since we need OTTF-launched tests (i.e., chip-level tests and mask ROM E2E tests) to be bootable by either test or mask ROMs
