### ISSUE TITLE
[bazel/ci] spliced mask_rom depends on meson built software

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#12696]
This will also include a structured release artifact, with https://github.com/bazelbuild/rules_pkg/releases

**Comment by a-will** [comment]
Hm... I'm not sure what you mean by "wildcards for artifacts." What are you looking to do with a wildcard?

**Comment by drewmacrae** [comment]
meson seems to wrap up all the products of sw/... that it knows how to build. It doesn't look to me like there's a way to do that without dropping an entry into each of 300 BUILD files.

**Comment by a-will** [comment]
> meson seems to wrap up all the products of sw/... that it knows how to build. It doesn't look to me like there's a way to do that without dropping an entry into each of 300 BUILD files.

Mostly, meson allows us to distinguish between an OBJ_DIR and a BIN_DIR, and it happens to be convenient that the contents of the BIN_DIR is what you'd want in this case.

By contrast, bazel does not have that separation, so there isn't that convenient directory to simply copy over (without a lot of extra baggage, that is).

For what it's worth, we likely could get a representative list of targets with a bazel query, followed by some quick processing to extract the base directories and output those as prefixes to `pkg_files` rules. These don't need to be spread out across the BUILD files -- From any given BUILD file, we can grab any target from the workspace with the path (assuming the target doesn't restrict visibility... but we probably haven't paid close attention to that).
