### ISSUE TITLE
[ci,nightly] OTBN nightly tests are broken

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#12707]
Looking at the [recent results page](https://reports.opentitan.org/hw/ip/otbn/dv/uvm/2022.05.15_22.01.11/results.html), it seems that OTBN tests are running on a machine that can't access the internet.

This presumably broke as part of switching dvsim over to using Bazel (maybe 6134eb9?). Tagging @timothytrippel accordingly, but it might also need someone from the Google DV team, who I understand are in charge of running things. @cindychip, would you mind taking a look?

At the moment, there are no meaningful OTBN tests running in the nightly regression tests.

**Comment by timothytrippel** [comment]
Ah I think I know what the issue is. @cindychip I can take care of this.

**Comment by timothytrippel** [comment]
This has been fixed now I think, see the [latest regression results](https://reports.opentitan.org/hw/ip/otbn/dv/uvm/latest/results.html).

**Comment by rswarbrick** [comment]
Brilliant, thanks!
