### ISSUE TITLE
Clarification on FLASH_CTRL.ADDR register definition

### ISSUE THREAD

**Issue by ChiaweiW** [lowRISC/opentitan#12706]
Hi All, I am new to OpenTitan SW development and I have a question regarding the FLASH_CTRL.ADDR register.
The document says the address is relative to the requested partition.

`Start address of a flash transaction. This is a byte address relative to the flash only. Ie, an address of 0 will access address 0 of the requested partition.`

However, the code snipets from `info_page_addr()` in `flash_ctrl.c`, the address is calculated in the flash absolute addressing scenario using the bank, page, and offset. The final address is then passed to `transaction_start()` to be written to FLASH_CTRL.ADDR without further modifications.

Could you help me to clarity this?
Thanks.

**Comment by ChiaweiW** [comment]
I think I got the idea now.
Each partition is addressed only by bank, page, and offset. 
So it is not conflicted with the partition selection located at FLASH_CTRL.CONTROL.
Please correct me if any misunderstanding. I shall close this now. Thanks.

**Comment by tjaychen** [comment]
yes that's right!

**Comment by ChiaweiW** [comment]
> yes that's right!

Thanks for double confirming this!
