### ISSUE TITLE
[dv/formal] FPV & connectivity tests support for foundry DB

### ISSUE THREAD

**Issue by dkabely-ot** [lowRISC/opentitan#12711]
Currently, only OS implementation is supported for formal (FPV & connectivity).
Support for foundry implementation formal connectivity tests is needed.

**Comment by cindychip** [comment]
Thanks Dror for the issue. I will work on this and get a proposal about file locations and settings etc this week.

**Comment by dkabely-ot** [comment]
Thanks Cindy!

**Comment by cindychip** [comment]
Hey @dkabely-ot I added a cfg.hjson file to run connectivity test for close source, but I think currently there are some compile errors. Could you give it a try and maybe we can see how to bypass/fix these issues.

**Comment by dkabely-ot** [comment]
Sure, thanks!

**Comment by cindychip** [comment]
@dkabely-ot do you need more support on this issue?
