### ISSUE TITLE
[EDN] Add common tests for common CMs

### ISSUE THREAD

**Issue by mwbranstad** [lowRISC/opentitan#12736]
Steve/Weicai: Add common tests for: EDN.CONFIG.MUBI, EDN.MAIN_SM.FSM.SPARSE, EDN.ACK_SM.FSM.SPARSE, EDN.CTR.REDUN, EDN.TILE_LINK.BUS.INTEGRITY V2S Item

**Comment by mwbranstad** [comment]
@msfschaffner thanks for cleaning this up. I thought the function to convert a list item to an issue was very useful, but it works best if the list item looks like the issue format.

**Comment by msfschaffner** [comment]
Oh that's why this looked this way ;). No worries - some manual steps for applying the labels are required anyways...

**Comment by cindychip** [comment]
Done with PR: https://github.com/lowRISC/opentitan/pull/15849
