### ISSUE TITLE
[bazel/ci] Execute tests on CW310 failing with bitstream not found in some commits

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#12755]
TLDR: I have a low confidence the correct bitstreams are running on the CW310

[Here we see a failing CI test that doesn't make a lot of sense to me](https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=80645&view=logs&j=be0b5a13-ded6-5a2a-3e48-80a10e7eef12&t=2aaa9e8b-9b00-5802-e0c1-7bc55418740f&l=79)
```
++ git rev-parse HEAD
+ SHA=e519772fafd50bd63916b1da5aef53b8c9210b37
+ BITCACHE_DIR=/root/.cache/opentitan-bitstreams/cache/e519772fafd50bd63916b1da5aef53b8c9210b37
+ mkdir -p /root/.cache/opentitan-bitstreams/cache/e519772fafd50bd63916b1da5aef53b8c9210b37
+ BITCACHE_FILE=/root/.cache/opentitan-bitstreams/cache/e519772fafd50bd63916b1da5aef53b8c9210b37/lowrisc_systems_chip_earlgrey_cw310_0.1.bit.orig
+ cp /azp/agent/_work/1/a/build-bin/hw/top_earlgrey/lowrisc_systems_chip_earlgrey_cw310_0.1.bit /root/.cache/opentitan-bitstreams/cache/e519772fafd50bd63916b1da5aef53b8c9210b37/lowrisc_systems_chip_earlgrey_cw310_0.1.bit.orig
+ echo ''
[...]
+ BITSTREAM='e519772fafd50bd63916b1da5aef53b8c9210b37 --offline'
+ ci/bazelisk.sh test --define DISABLE_VERILATOR_BUILD=true --test_tag_filters=cw310,-broken --test_output=errors --build_tests_only --flaky_test_attempts=4 --define cw310=lowrisc //hw/bitstream:test_rom [...]
Running bazelisk in /azp/agent/_work/1/s.
No key/invalid path to key. Download from cache only.
(00:10:32) INFO: Invocation ID: 2aa01663-9c47-40c0-b5e1-705f6b627267
(00:10:33) INFO: Current date is 2022-05-19
(00:10:33) Loading: loading...

(00:10:33) Loading: 

(00:10:33) Loading: 0 packages loaded

ERROR:root:Could not find the bitstreams to generate a BUILD file:BUILD.bazel
in params:{'datetime': '2022-05-19T00:10:34.276359', 'key': 'f770f3ff2349dbd917a2b032b02d2b8485145952'}
using key:f770f3ff2349dbd917a2b032b02d2b8485145952
```

**Comment by drewmacrae** [comment]
I think the bitstream is properly placed and specified in the commandline at e519772, I'm not quite sure why bazel's using f770f3 as a key yet

**Comment by drewmacrae** [comment]
Should we roll-back #12493?

**Comment by drewmacrae** [comment]
f770f3 appears to be latest and/or a parent commit.

**Comment by drewmacrae** [comment]
Affects 3/9 tests run since merging that weren't broken by running old scripts. Rerunning it may have fixed it in one instance.

**Comment by drewmacrae** [comment]
This is generating some churn and some delay (~ten more minutes to approve some passing PRs during the workday, longer if someone can't rerun the failing test) now but it shouldn't have a large impact. I've marked it as a P1 but I'm investigating further.

**Comment by drewmacrae** [comment]
I've set up a draft PR to help investigate #12766

**Comment by drewmacrae** [comment]
...soo, #12493 and the testing I did of it implicitly trusted the `--offline` argument to restrict access to unhandled bitstreams in [bitstreams_workspace.py](https://cs.opensource.google/opentitan/opentitan/+/master:rules/scripts/bitstreams_workspace.py;l=27?q=bitstream&ss=opentitan%2Fopentitan). I'm worried because `--list` shows that the available bitstreams include a large number of bitstreams including the latest, but don't include the one generated for the test and placed in the cache that I expect to be running. In case the list isn't reflective of what's generally available I'm not reverting #12493 until I understand a little better.

**Comment by drewmacrae** [comment]
This could be causing the failure here: https://github.com/lowRISC/opentitan/pull/12754/checks?check_run_id=6500036645

**Comment by drewmacrae** [comment]
That commit doesn't seem to do anything that would change the bitstream so I don't think it's causing the issue.

**Comment by drewmacrae** [comment]
I'm seeing other failures which suggest this may be allowing breaking PRs to reach master by validating previous versions of a bitstream.

**Comment by drewmacrae** [comment]
I'll keep an eye on batched CI runs, failures should appear there.

**Comment by drewmacrae** [comment]
I'm also seeing checkouts of master fail on my local cw310, which has me nervous.

**Comment by eunchan** [comment]
#12782 also experiences this issue.
