### ISSUE TITLE
[dv/dbg] End to end test for debug

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#12764]
We should have a full end to end test for debug that uses OpenOCD and GDB connected to an OT target (ideally we'd have this run against both the verilator simulation and the FPGA, though FPGA should take priority).

The test would load some binary, start OpenOCD and GDB, checking it all connects successfully. Then test the following features:

1. Breakpoints, set some breakpoints and check GDB breaks on them as expected
2. Interrupting execution
3. Single stepping
4. Reading and writing registers
5. Reading and writing memory (both SRAM and device)

Software should be written specifically for this test (to ensure stability e.g. so a breakpoint targeting a specific file and line always does the same thing).

This will require some scripting to coordinate everything and do the checking, it is not just another chip-level test.

**Comment by sriyerg** [comment]
This is planned for DV also.

**Comment by tjaychen** [comment]
i think @dmcardle was exploring this for FPGA already.

**Comment by GregAC** [comment]
PR to add this to the testplan here: https://github.com/lowRISC/opentitan/pull/15233

**Comment by GregAC** [comment]
Closing this now it has been added to the ROM e2e testplan and this work is tracked by https://github.com/lowRISC/opentitan/issues/14484
