### ISSUE TITLE
[hmac] Add tx FIFO empty interrupt

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#1276]
Philip Levis suggested to have TX fifo empty interrupt in HMAC which is also being added to UART for the software to push the message data with ease. This issue is to follow up the suggestion. The design change Pull-Request will follow.

```c
push_data() {
    while (!fifo_full() && have_more_data()) {
        push_word_into_fifo();
    }
}

start_hmac() {push_data();}

watermark_interrupt() {push_data();}

empty_interrupt() { 
  if (have_more_data()) {
    push_data();
  } else {
    /* done with hmac */ 
  }
}
```

And, FIFO Full condition doesn't have to be an interrupt. Status register is sufficient.

CC: @tjaychen @sjgitty @cindychip

**Comment by alistair23** [comment]
Any update on this? I completely agree

**Comment by tjaychen** [comment]
o we have added this.
Please have a look at let us know if you see any issues with the behavior.

**Comment by alistair23** [comment]
I don't see any documentation describing how to use it. Do you have more details?

**Comment by tjaychen** [comment]
there should be descriptions for it in the opentitan documentation.
It's really just an interrupt you enable, and when the fifo crosses from
non-empty to empty, and event fires.

**Comment by alistair23** [comment]
I think I'm going to need some more help finding that documentation. All I see is the [FIFO full interrupt](https://github.com/lowRISC/opentitan/blob/master/hw/ip/hmac/doc/_index.md#interrupt-handling).

**Comment by tjaychen** [comment]
oops i am sorry. I thought we were talking about uart :)
I am so sorry!

**Comment by alistair23** [comment]
Ah ok. So it's not implemented then?

**Comment by eunchan** [comment]
This is good time to implement this! Thanks for the ping. I will work on this.

**Comment by alistair23** [comment]
Great!

**Comment by jon-flatley** [comment]
@eunchan I noticed that `INTR_STATE.fifo_full` was replaced with `INTR_STATE.fifo_empty`, has this been resolved?

**Comment by eunchan** [comment]
Yes.  Thanks for the reminder. Closing this issue.

**Comment by alistair23** [comment]
I can't get the interrupt to trigger, I opened an issue here: https://github.com/lowRISC/opentitan/issues/2166
