### ISSUE TITLE
[otbn,rtl] Potential control flow hardening

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#12768]
We could add some extra hardening to OTBN to detect glitching on control signals related to program flow.

Already we have a pre-decode stage that pre-decodes control related to the bignum data path. This pre-coded control is cross checked against what the actual decoder produces and a fatal error raised if they do not match.

We could extend this checking to some aspects of the control flow:

- Whether we are pushing/popping the call stack
- Whether we are executing a loop an instruction
- Whether we are executing a branch or jump instruction

This is easy within the RTL with minimal area impact but does impact DV. Do we want to implement this?

This could be extended so predecode also calculates jump/branch/loop end addresses and these cross checked in a similar manner. Again area impact is minimal but the RTL work is slightly move involved.

**Comment by tjaychen** [comment]
Adding Bilgiday for comments.

**Comment by rswarbrick** [comment]
To me, this seems like a reasonable thing to do. Honestly, it's only going to add a small fraction of what we're going to have to do for V2S testing anyway. But (obviously) this needs specifying and implementing before we declare D2S, or it shouldn't go in at all.

**Comment by vogelpi** [comment]
This sounds very reasonable to me assuming the DV overhead is acceptable.

**Comment by msfschaffner** [comment]
For the already existing pre-decode control signals I think this sounds reasonable since most of the pieces are already in place to support this.

For the address decoding extensions it depends a bit whether we think the effort is justified (because it sounds like this would be more work). Should we discuss this in the next silicon or security WG meetings (we might have to take it to the next silicon WG since the security WG meeting is blocked by a talk this week).

**Comment by johannheyszl** [comment]
summary after discussing with jade, bilgiday, miguel, tim, greg and rupert:
- implementation effort low and DV impact minimal.
- hardening does address relevant control flow issues from creating suppressing jumps/branches, suppressing loops, or manipulating the stack pointer through creating/suppressing push/pops.
- this is particularly helpful for OTBN asymm crypto to protect control flow in final stages of check routines which verify mathematical properties of crypto results (such check routines cover FIs into the datapath/control flow during extensive crypto computations).

**Comment by GregAC** [comment]
The first half of this (bullet points from the original issue) is implemented in https://github.com/lowRISC/opentitan/pull/13069

Calculating jump targets in predecode to cross check against jump targets calculated in the execute stage is being worked on. If testing demonstrates there's some tricky corner cases I hadn't anticipated I think we'll drop it.

**Comment by vogelpi** [comment]
The additional control flow hardening discussed here has all been implemented. The PRs of Greg have been merged. Thus closing.
