### ISSUE TITLE
[opentitantool] Do hjson files really have octal fields?

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#12770]
This came up during our 1:1 with @jon-flatley. It's not clear to us if the hjson files that opentitantool parses really have octal encoded fields or this was just a oversight, e.g. padding with zeros.

**Comment by msfschaffner** [comment]
@cfrantz @timothytrippel

**Comment by timothytrippel** [comment]
I'm not sure the issue here of if this just a question, so closing for now, feel free to re-open/further describe the issue at hand in the future.

**Comment by cfrantz** [comment]
The serde-annotate "relax" parser is maximally permissive.  Although octal fields (or hex) are not part of the hjson or json specs, the default configuration of the relax parser is to accept them.
