### ISSUE TITLE
[ibex] Software Interrupt is not synchronous interrupt

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#12787]
CC: @tjaychen @GregAC @a-will 

Not sure who should I assign.

The software interrupt in `ottf_isrs.S` is [assumed as a synchronous interrupt](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/lib/testing/test_framework/ottf_isrs.S;l=167?q=ottf_isrs.S&ss=opentitan%2Fopentitan). However, RV_PLIC raises the interrupt one cycle later it gets the write request. The write request from the Core D-port is [latched inside the Xbar](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/data/xbar_main.hjson;l=153?q=rv_plic%20xbar_main.hjson&ss=opentitan%2Fopentitan) too.

So, after write, it took 2 cycles to get the interrupt. The instruction moves.

`ottf_isrs.S` *handler_software_isr* assumes it as synchronous and manipulates `MEPC` pointing to the next instruction. It results the second from the `sw` is skipped.

**Comment by eunchan** [comment]
I revised #12754 by adding two `NOP`s after write to `MSIP`. But this should be temporary.

**Comment by eunchan** [comment]
@GregAC I think Ibex would be better to have MSIP internally to reduce the latency. WDYT?

**Comment by a-will** [comment]
It looks like we misunderstood, and the software interrupts are asynchronous traps. Shall we close?

**Comment by GregAC** [comment]
> It looks like we misunderstood, and the software interrupts are asynchronous traps. Shall we close?

Just to add a bit of background I believe the software interrupt is intended as a simple inter core signalling mechanism. One core interrupts another to let it know some event has happened for instance. Note that while the observed latency measured by instructions executed between interrupt raised and interrupt taken may be 2 in this instance Ibex does not make any latency guarantees and all interrupts are asynchronous. `ecall` should be used to produce a synchronous exception.
