### ISSUE TITLE
[tlul,reg,otbn] Something's not wired up correctly for TLUL errors...

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#12792]
... but I can't work out what!

The nightly tests are currently failing `otbn_csr_mem_rw_with_rand_reset` with quite a few seeds. The problem turns out to be that a TL error sequence writes something that's expected to cause an error to some register. We then expect OTBN's `STATUS` register to switch to `0xff`. It doesn't, and the test fails when we read the register.

The weird bit is that I can't understand how this is *supposed* to work. For example, I just ran a test where the TL transaction signalled a write with `tl_i.a_user.instr_type` set to true. Deep inside the register top, the `tlul_err` instance inside the `tlul_adapter_reg` signals an error. This gets registered in an `error` signal in the `tlul_adapter_reg` and squashes the TL transaction. But that error signal never actually makes it out of the adapter, so there's no way for OTBN to react to it.

@tjaychen, @msfschaffner: I know that you guys designed this infrastructure. Is this a silly bug? Or am I missing something subtle about how the code is supposed to work?

To reproduce, run something like:
```
util/dvsim/dvsim.py hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson -i otbn_csr_mem_rw_with_rand_reset --reseed 10
```
You should get a couple of seeds that give errors.

**Comment by tjaychen** [comment]
sounds good @rswarbrick let me have a look.
Silly bug seems very likely.

**Comment by tjaychen** [comment]
wait sorry, could you explain a bit more on the otbn `STATUS` part? do you mean you expect the tlul error to be exposed inside otbn? I probably need to have a closer look at the expectation there.

**Comment by tjaychen** [comment]
ah sounds good!
