### ISSUE TITLE
[spi_device] Default to Flash Mode

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#12808]
As BootROM moves to SPI Flash mode to download the images, Generic Mode(a.k.a FwMode) has no usage as of now.

The change to Flash mode needs a few cautious steps due to the clock switch between Generic and Flash/PassThrough mode.

It would be better to have Flash mode by default and SW can skip the clock change sequence from their codes.

**Comment by tjaychen** [comment]
sounds good to me!

**Comment by alphan** [comment]
SGTM, this would eliminate 3 writes at the end of `spi_device_init()` ([here](https://github.com/lowRISC/opentitan/blob/421b9a95536da34e9efcc5b84ec6fbd555e02e39/sw/device/silicon_creator/lib/drivers/spi_device.c#L621)).

**Comment by a-will** [comment]
For clarity for future readers: "has no usage" and "SW can skip" are only in the context of the boot ROM. Generic mode is supported for post-ROM firmware, and their drivers should take care with power-on defaults. :smile:

**Comment by weicaiyang** [comment]
quickly checked. Probably no need to change DV sequence as the SPI mode can be updated automatically (DV knows the design default value and the mode sequences want to use)

**Comment by eunchan** [comment]
OK. I will revise the default value. As SPI_DEVICE IP has TPM, Flash modes, I think usage cases of Generic Mode are rare. So, to lessen the burden of back end team, it would be good to remove the feature.

Generic mode creates hassles of maintaining two distinct clocks for the DPSRAM that create many CDC issues to be reviewed.
