### ISSUE TITLE
Error: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#1281]
@imphil 
Cadence AE got below error when running the top_earlgrey.
Do you know how to solve this problem? Thanks

> /tools/riscv/bin/riscv32-unknown-elf-gcc -march=rv32imc -mabi=ilp32 -static -mcmodel=medany -Wall -g -Os -fvisibility=hidden -nostdlib -nostartfiles  -DDV_SIM -MMD -c -I/dv/scratch/users/gauravd/2185077/opentitan-master/sw/device/../vendor -I/dv/scratch/users/gauravd/2185077/opentitan-master/sw/device/../device/exts/common -I/dv/scratch/users/gauravd/2185077/opentitan-master/sw/device/../device/lib -I/dv/scratch/users/gauravd/2185077/opentitan-master -I/dv/scratch/users/gauravd/2185077/opentitan-master/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/12.19.19_17.43.00/sw_build/rom -I/dv/scratch/users/gauravd/2185077/opentitan-master/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/12.19.19_17.43.00/sw_build/rom/lib -o /dv/scratch/users/gauravd/2185077/opentitan-master/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/12.19.19_17.43.00/sw_build/rom/lib/uart.o /dv/scratch/users/gauravd/2185077/opentitan-master/sw/device/../device/lib/uart.c                                                                                                                     
> 
> /tools/riscv/bin/riscv32-unknown-elf-gcc: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tools/riscv/bin/riscv32-unknown-elf-gcc)
> 
> make[1]: *** [rules.mk:75: /dv/scratch/users/gauravd/2185077/opentitan-master/hw/top_earlgrey/dv/scratch/top_earlgrey/chip_sanity/12.19.19_17.43.00/sw_build/rom/lib/uart.o] Error 1
> 
> make[1]: Leaving directory '/dv/scratch/users/gauravd/2185077/opentitan-master/sw/device'
> 
> make: *** [/dv/scratch/users/gauravd/2185077/opentitan-master/hw/dv/tools/rules.mk:54: sw_build] Error 2
> 
> [gauravd@noi-gauravd1 /dv/scratch/users/gauravd/2185077/opentitan-master/hw/top_earlgrey/dv]$ ldd /tools/riscv/bin/riscv32-unknown-elf-gcc
> 
> /tools/riscv/bin/riscv32-unknown-elf-gcc: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tools/riscv/bin/riscv32-unknown-elf-gcc)
> 
>         linux-vdso.so.1 =>  (0x00007fff7b3ff000)
> 
>         libc.so.6 => /lib64/libc.so.6 (0x0000003333a00000)
> 
>         /lib64/ld-linux-x86-64.so.2 (0x0000003333200000)
>

**Comment by imphil** [comment]
The prebuilt toolchain requires glibc 2.14+, which doesn't seem to be present in this case. Are they using RHEL6? That's not supported, RHEL7+ should work. If using a operating system with a recent-enough glibc is not an option, they can compile the toolchain themselves. All necessary source code is available at https://github.com/lowRISC/lowrisc-toolchains.

**Comment by weicaiyang** [comment]
> The prebuilt toolchain requires glibc 2.14+, which doesn't seem to be present in this case. Are they using RHEL6? That's not supported, RHEL7+ should work. If using a operating system with a recent-enough glibc is not an option, they can compile the toolchain themselves. All necessary source code is available at https://github.com/lowRISC/lowrisc-toolchains.

Thanks @imphil
