### ISSUE TITLE
[dv/top] pwrmgr low power signal coverage

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#12816]
while debugging #12815 , it occurred to me that we may not have good chip level coverage for pwrmgr's `low_power` output.
This signal is used to inform various blocks (currently `pinmux` and `aon_timer`) that a low power event is in progress and they should respond appropriately. We need to make sure that this behavior works correctly across modules.

More importantly, we need to test this across all the power modes to make sure there are no gaps.

**Comment by tjaychen** [comment]
@cindychip 
@weicaiyang 
FYI

**Comment by cindychip** [comment]
More importantly, we need to test this across all the power modes to make sure there are no gaps.
-> Should we enhance the testplan to cover these testcase? Maybe talk about it in weekly DV meeting?

**Comment by tjaychen** [comment]
yeah i think it would be good to discuss to see if we feel this is already covered.

**Comment by cindychip** [comment]
Thanks Tim, added to the meeting note.

**Comment by sriyerg** [comment]
For pinmux, low_power triggers the retention register. The AI here is to add a testplan entry to verify this logic. There are several tests the exist which could be updated to get this logic verified. 

For aon_timer: `chip_sw_aon_timer_sleep_wdog_sleep_pause` is already in the tesplan.

**Comment by sriyerg** [comment]
@tjaychen, please let me know if the new PR (and previous response) adequately satisfy this issue. Thanks!

**Comment by tjaychen** [comment]
lgtm. i'll close this one first.
