### ISSUE TITLE
[opentitantool] Investigate the use cases and flexibility of the opentitantool config files

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#12828]
#12825 changes the mode of the `RESET` pin to PushPull because OpenDrain is not supported on cw310 and I wasn't successful in overriding it both here in "strappings" and opentitan_cw310.json.

_Originally posted by @alphan in https://github.com/lowRISC/opentitan/pull/12825#discussion_r879764755_

**Comment by msfschaffner** [comment]
- [ ]
