### ISSUE TITLE
[bazel,dvsim] increased private CI times since switching build system to Bazel

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#12840]
Since #12761 merged, it seems we have been getting close to the private CI job timeout (of [90min](https://github.com/lowRISC/opentitan/pull/12761)). My guess is the bazel builds are taking a bit longer to download deps into the workspace, since the CI run starts from a clean slate every time. 

In the interim, we have [bumped up the private CI job time limit to 2 hrs](https://github.com/lowRISC/opentitan-private-ci/pull/14). However, we need to investigate the root cause of this and bring down the runtime to where it was before, or better.

**Comment by weicaiyang** [comment]
I took a bit closer look at the run time (real time) on the smoke tests
I reran smoke for 2 PRs in my local and the run time doesn't look too much difference for PRs with or without the bazel update. They both took ~20 mins to finish.

I grep `CPU Time` in the log and only the test took 10+ seconds are listed below.

#12819 without recent bazel update. In this PR, private CI finished within 20 mins

> alert_handler_smoke/out/run.log:CPU Time:     33.130 seconds
> chip_csr_hw_reset/out/run.log:CPU Time:    216.860 seconds
> chip_csr_rw/out/run.log:CPU Time:    213.530 seconds
> chip_plic_all_irqs/out/run.log:CPU Time:    364.040 seconds
> chip_sw_pwrmgr_smoketest/out/run.log:CPU Time:    310.320 seconds
> chip_sw_uart_tx_rx/out/run.log:CPU Time:    311.850 seconds

#12790 with the bazel update. Private CI timed out. But run time in local is similar to the case above.

> alert_handler_smoke/out/run.log:CPU Time:     33.150 seconds
> chip_csr_hw_reset/out/run.log:CPU Time:    210.370 seconds
> chip_csr_rw/out/run.log:CPU Time:    213.730 seconds
> chip_plic_all_irqs/out/run.log:CPU Time:    518.070 seconds
> chip_sw_pwrmgr_smoketest/out/run.log:CPU Time:    325.110 seconds
> chip_sw_uart_tx_rx/out/run.log:CPU Time:    355.230 seconds

I think the test run time looks fine. We may need to investigate why bazel build takes so long in the CI server or some other place gets stuck.

@GregAC @rswarbrick

**Comment by timothytrippel** [comment]
I am seeing similar results as @weicaiyang, however, one thing to note is our machines use a pre-populated Bazel repository cache (note, this is different from the Bazel **build** cache) so they can run in air-gapped environment, where as the private CI machines are downloading bazel dep from network. However, barring exceptionally slow network speeds these downloads shouldn't take more than a minute or two.

**Comment by timothytrippel** [comment]
I opened #12852 to test if reverting to using meson to build SW in private CI was the issue, but it seems this did not help. So it looks like bazel is **not** the culprit. There must be something else going on?

**Comment by timothytrippel** [comment]
closing this as we have reverted dvsim.py to use meson again to build SW
