### ISSUE TITLE
[flash_ctrl] change simulation time resolution from 1ps to 100ps

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#12851]
to improve our sim turn around time, I am testing a new timescale
1ns/100ps. Please let me know by the end of Wednesday (5/25) if you think
we have to keep 1ns/1ps.
@tjaychen @eshapira @nikola-miladinovic @TimEwins

**Comment by tjaychen** [comment]
i don't see why not. 
I took a quick look at the flash timing in their docs, and i don't see anything that needs more than 100ps of precision.

**Comment by tjaychen** [comment]
@jdonjdon can this be closed now? I seem to remember you already made the change.

**Comment by jdonjdon** [comment]
done with #12888
