### ISSUE TITLE
[lint] Add AscentLint linting flow

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#1286]
This issue is related to #1243 and tracks the progress of adding a flow for the AscentLint Tool from RealIntent.

- [x] Add AscentLint waiver files
- [x] Add AscentLint target to fusesoc core files
- [x] Add runscripts / makefile
- [ ] Decide what to do with lint errors in generated files.
- [x] Enable low risc linting policy in AscentLint (requires an upcoming release of the Tool)
- [ ] Update documentation

**Comment by msfschaffner** [comment]
Initial support is there, but we still have to wait for the upcoming release of AscentLint 2019.A.p3 for final integration.

**Comment by msfschaffner** [comment]
Ok, AscentLint 2019.A.p3 has been released and support for AscentLint is now functional - see https://github.com/lowRISC/opentitan/pull/1494

**Comment by imphil** [comment]
All of that is set up now and we create nightly reports on it.
