### ISSUE TITLE
[opentitanlib] Find out the meaning of CDCE906 related constants

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#12872]
Any idea what these constants mean?
If yes, can we add them as impl-level constants and refer to them by `Self::CONSTANT_NAME`?
If no, can we leave a TODO to learn their meanings?

_Originally posted by @cfrantz in https://github.com/lowRISC/opentitan/pull/12870#discussion_r882052240_

**Comment by a-will** [comment]
Data sheet: https://www.ti.com/lit/gpn/cdce906
