### ISSUE TITLE
[clkmgr] V2S review TODOs

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#12899]
- [x] [Jaedon] Please check if external clk sw control is covered in any test?

- [x] [Jaedon] Please check if the spelling of `FATA_`?

- [x] [Jaedon] Move coverage to 90% for V2S.

- [x] [TimC, Jaedon, Matute] [Clock manager reset selection](https://github.com/lowRISC/opentitan/issues/12865): gating issue until we came up with a solution.

**Comment by matutem** [comment]
The coverage of all metrics is over 90% now, so I will create a PR to move clkmgr to V2S.

**Comment by jdonjdon** [comment]
thanks @matutem please create sign off PR.
