### ISSUE TITLE
[dv common] sec_cm test macro cannot address multi clock entries

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#12921]
It is observed from one of clkmgr regression test,
./util/dvsim/dvsim.py hw/ip/clkmgr/dv/clkmgr_sim_cfg.hjson -i clkmgr_sec_cm -v m -r 1 -s 2353277567 --waves -ro "+max_quit_count=5"

Test forces one of SecCmPrimCount entries (tb.dut.u_clk_main_aes_trans.u_idle_cnt.up_cnt_q[0])
to create count error 1 cycle (of tb.dut.clk_main_i).
However, register samples 'de' at slower clock (tb.dut.u_reg.clk_i) and miss 'hw2reg.fatal_err_code.idle_cnt.de'
then test fails.

If this happens only clkmgr block, I will add directed test case to replace SecCmPrimCount test and disable it from generic test.
Just share this with other DVs' for your reference.

**Comment by cindychip** [comment]
Good point, I can add a clk and rst input to this test.

**Comment by tjaychen** [comment]
hmmm.. .this sounds a bit more like a design issue.
I need to relate the assertion to the right clock. 
I also just noticed that there are probably cdc issues anyways on this that i need to address.

**Comment by tjaychen** [comment]
@cindychip 
@weicaiyang 
there still is an issue that the alert and the original prim_count events are on different domains though, so that might still cause a problem unless in the assertion we extend the window of checking.

**Comment by jdonjdon** [comment]
![image](https://user-images.githubusercontent.com/99843637/170789952-85e0ba3f-0e04-412a-957f-2ea36cbef85e.png)
Attached figure to clarify issue. single pulse error from clk_main can be missed in clk_reg_fatal

**Comment by tjaychen** [comment]
yeah that's the problem i'm seeing now.
There's some legacy stuff here i need to clean-up along with the assertion clock hook-up.

**Comment by tjaychen** [comment]
@jdonjdon can you let me which test you ran to reproduce this?

**Comment by jdonjdon** [comment]
> @jdonjdon can you let me which test you ran to reproduce this?

From PR12920(https://github.com/lowRISC/opentitan/pull/12920)
run this command
./util/dvsim/dvsim.py hw/ip/clkmgr/dv/clkmgr_sim_cfg.hjson -i clkmgr_sec_cm -v m -r 1 -s 2353277567 --waves -ro "+max_quit_count=5"

**Comment by weicaiyang** [comment]
@jdonjdon Thanks for catching this bug. perhaps we can close this issue if the design is fixed.

**Comment by jdonjdon** [comment]
fixed with #12932
