### ISSUE TITLE
RFC: Device Life Cycle - State Definitions

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#1294]
Request for comments for proposed [Device Life Cycle State Definitions](https://docs.google.com/document/d/15QYEZ1kkAs9qG3yCPj3J8frPmpfOvwdWRRB2Z5YVFJw/edit). 

Device life cycle states are used to track the operational state of the device during manufacturing, provisioning, regular operation, as well as [RMA](https://en.wikipedia.org/wiki/Return_merchandise_authorization). 

An additional set of states are proposed to support Ownership Transfer.

**Comment by tjaychen** [comment]
Please the updated link [here](https://docs.google.com/document/d/15QYEZ1kkAs9qG3yCPj3J8frPmpfOvwdWRRB2Z5YVFJw/edit?usp=sharing)

**Comment by sjgitty** [comment]
To all team: the Technical Committee (which has recently spun up, more news later) will be reviewing this RFC on 2020-06-03. Please refresh and record your thoughts on the proposal so that your opinions are registered in advance of that meeting.

**Comment by sjgitty** [comment]
An update from the Technical Committee. This RFC was deemed not quite ready to move to the "approved" status, and has been postponed for the next TC meeting (2020-06-17). There are a few minor issues that the TC wants to track down before approving. This will be updated in two weeks, but remains in `RFC:Proposal` mode for now.

**Comment by tjaychen** [comment]
i responded to a couple of comments.
It would be great if the TC can let us know if the clarifications make
sense.

**Comment by asb** [comment]
The Technical Committee voted yesterday to approve this RFC - thank you for all your work on this. There some discussion about presentational changes that we felt were non-blocking, as that can be discussed if and when this moves to a PR in the form of project documentation.

I'll leave this issue open as I think the plan would be to follow-up with a PR that adds a form of this content to docs.opentitan.org  - but let me know if that's not the case.

**Comment by tjaychen** [comment]
thanks Alex!
There are some open questions for one of the committee members regarding
clarity of specific points.
If you can look at those points and let us know if the latest updates
addresses those concerns, we can probably move forward to markdown.

**Comment by moidx** [comment]
Updated PR to address comments provided by TC.  The initial version of the document has been merged in lowrisc/opentitan#3070
