### ISSUE TITLE
[top,dv] make random available over multiple platform

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#12984]
Current top tests use SV random to over write variables in c tests.
It works well in simulation platform. But to increase reusability of test suites 
over multiple platform (fpga , veerilator etc), we need to create mechanism
to generate random values in those platform.

**Comment by tjaychen** [comment]
@sriyerg it would be good to get your opinion on this issue.

My basic idea is that [this function](https://github.com/lowRISC/opentitan/blob/master/sw/device/lib/testing/rand_testutils.c#L18) can be different per platform. For verilator / fpga we get randomness from entropy directly, but for DV we can use a backdoor path where the SV side can directly supply the entropy.  This for DV nightly at least, this will give us better random coverage for the chip level tests while also keeping the test themselves portable. 

it's essentially the reverse of the sw logging implementation.

**Comment by sriyerg** [comment]
Yes, that is what I had in mind too. We could add `rand_testutils_init(uint32_t *lfsr)` which can be called by OTTF before entering `test_main()`. It will set the initial `lfsr` value from the entropy source for non-DV platforms. For DV, It could read the initial value from one of the scratch registers we added to `rv_core_ibex` (SV side will need backdoor-force it).

**Comment by sriyerg** [comment]
This is related to an issue that was already filed: https://github.com/lowRISC/opentitan/issues/667. Fix coming soon.

**Comment by tjaychen** [comment]
@sriyerg do you want to announce this at the team meetings next week (and week after?)
I really think this is useful for a lot of the chip level tests (especially the super long ones), to break up into smaller ones with more seeds.

**Comment by sriyerg** [comment]
sure. sg.
