### ISSUE TITLE
[pwrmgr] cdc failure in esc_rst_req

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#12981]
From PR (https://github.com/lowRISC/opentitan/pull/12758)
cmd:
./util/dvsim/dvsim.py ./hw/ip/pwrmgr/dv/pwrmgr_sim_cfg.hjson -i pwrmgr_sec_cm_lc_ctrl_intersig_mubi -s 1932707886 --waves -r 1
If esc_rst_tx_i comes less than 2 cycles of slow_clock,
our dut.u_cdc will miss esc_rst_req pass to slow clock domain
and reset signal is lost.

![image](https://user-images.githubusercontent.com/99843637/171487156-923975e4-9cd4-4aab-b3a8-2825a2e2eb35.png)

**Comment by jeoongp** [comment]
esc_req is generated from alert_handler as a pulse in the fast clock domain.
two flop synchronizer is supposed to work in slow-to-fast CDC. 
Thanks @jdonjdon.

**Comment by tjaychen** [comment]
@jdonjdon can you have a look to see if the fix introduced fixes the problem?
if yes we can close this issue down.

**Comment by jdonjdon** [comment]
Issue closed with
rtl update (#12988)
tb update (#12758)
