### ISSUE TITLE
[reg] clarify and extend `hwre` key usage

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#130]
The [register tool documentation](https://bubble.servers.lowrisc.org/doc/rm/register_tool.html) just says the following about the `hwre` key:

`true` if hardware uses `re` signal, which is latched signal of software read pulse.

This sounds very useful to implement a back-pressure feature for output registers of a HW module (the HW should only overwrite the register, if SW has read it).

When using this feature, I encountered the following two issues:

1. The register tool only allows `hwre` to be set if also `hwext` is set. If `hwext` is not set, it outputs the following erroneous warning:
   "WARNING: DATA_OUT: hwre cannot be used with hwext. Changing it to false."
   This warning should at least be fixed to "cannot be used WITHOUT hwext". However, it would actually be useful to also propagate the read-enable signal to the HW if `hwext` is not set. Is there a particular reason why this is not enabled?

2. Even if `hwext` is set, the read-enable signal is not included in the `reg2hw` struct unless the hardware has read access, i.e., `hwaccess` is set to `hrw`. Is there a reason why this is needed or is it just a bug?

Would it be possible to extend the register tool to allow:
1. `hwre` without `hwext`?
2. `hwre` with `hwo`?

**Comment by sjgitty** [comment]
@vogelpi we'll try and discuss this one in silicon tomorrow. please refresh your thoughts to see if they are still in line with the conversation captured here.

**Comment by vogelpi** [comment]
I understand the concerns about side-effecting reads. We should not encourage people to do this lightly.

IMO, it would help reviewers to spot potentially problematic cases if:
- This features was more easily accessible (i.e. a register would not need to be `hwext` and readable by the hardware just to get the `hwre` signal). Requiring `hwext` and `hrw` just to get `hwre` can hide the side-effecting reads in something much more complex. 
- We would rename the signals as suggested here #144  to `swrdhint` or similar.

Anyway, since having filed this issue, some more AES registers have become `hwext` because they need special handling for security reasons (e.g. the hardware must be able to ignore software writes during operation). Changing the implementation of `hwre` would not make a big difference there, and I would not feel too sad if we decided not to do it.

**Comment by vogelpi** [comment]
The majority of developers including me seems to be fine with the current capabilities. I am thus closing this issue. We can always re-discuss.
