### ISSUE TITLE
Remove Nexysvideo from SW tree

### ISSUE THREAD

**Issue by milesdai** [lowRISC/opentitan#13008]
The CW305 bitstream is currently built using the Nexysvideo board target. Nexysvideo was originally removed from Bazel in #12239, but was reverted in #12976 to allow the CW305 bitstream to be built using only Bazel.

Per the discussion [here](https://github.com/lowRISC/opentitan/pull/12976#issuecomment-1144484469), we should either use the CW310 bitstream or create a `device_fpga_cw305.c` if we plan to support this board long term.

This change is slated to take place after the removal of meson.

**Comment by vogelpi** [comment]
This is also tracked in #12221 and I think @jprendes wanted to look into this task.
