### ISSUE TITLE
[flash_ctrl/dv] tests flash_ctrl_error_* failing due to a mem issue

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#13023]
There are 3 error tests in flash_ctrl and they all failed with Xcelium when mem is set to 4G (default)
After increasing to mem to 16G, now some of these tests are still failing. We need to think of a way to solve it

1. investigate the code and see if we can reduce the memory use or simplify constraint (don't know what place needs so large memory) it will be great if @TimEwins knows any place that we can optimize to reduce memory usage
2. according to @jdonjdon, this can be fixed when increasing memory to 32G. But dvsim can only set mem for all tests. It may be too much to set 32G for all tests. We can consider enhancing dvsim to allow us to set memory for some particular tests

cc: @jdonjdon @cindychip

**Comment by jdonjdon** [comment]
After switch to vcs (#13186), this is no longer concurrent issue.

**Comment by weicaiyang** [comment]
Closing this as we switched to VCS
