### ISSUE TITLE
[bazel] add option to enable waveform tracing for verilator 

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#13042]
Running the verilator sim binary with the `--trace` flag produces a waveform file. Currently there is no way to have bazel pipe this through when you issue `bazel test ...`. This would be a useful debugging feature as we can now run verilator sims with `bazel test ...`

**Comment by timothytrippel** [comment]
CC: @tjaychen

**Comment by drewmacrae** [comment]
By the way, it's not a solution, but I've been working around this for a while now and I have two ways of doing it.

Within the rule for the opentitan_functest I can use verilator_params to pass `--trace`
```
 verilator = verilator_params(
    args = [
            "--verilator-args=--trace",
            "console",
            "--timeout=3600",
            "--exit-failure=FAIL",
            "--exit-success=PASS",
        ],
```

**Comment by timothytrippel** [comment]
Ah great so its just a matter of piping it through from the bazel side

**Comment by drewmacrae** [comment]
With https://github.com/lowRISC/opentitan/pull/12985 you can now see the invocation of opentitantool to repeat the test as invoked by Bazel. 
Run: ```bazel test <your test label> --test_output=all```
to have bazel prepare and invoke the test and echo the invocation to the log.

It's then clunky to look up the items outside a sandbox, but `ci/scripts/target-locations.sh` makes it a little easier.
```INFO: From Testing //sw/device/tests:hmac_enc_test_sim_verilator:                                                                                                           
==================== Test output for //sw/device/tests:hmac_enc_test_sim_verilator:                                                                                         
Invoking: sw/host/opentitantool/opentitantool --rcfile= --logging=info --interface=verilator --conf=sw/host/opentitantool/config/opentitan_verilator.json --verilator-bin=hw
/build.verilator_real/sim-verilator/Vchip_sim_tb --verilator-rom=sw/device/lib/testing/test_rom/test_rom_sim_verilator.scr.39.vmem --verilator-flash=sw/device/tests/hmac_enc_test_prog_sim_verilator.64.scr.vmem --verilator-otp=hw/ip/otp_ctrl/data/img_rma.vmem console --exit-failure=(FAIL|FAULT).*\n --exit-success=PASS.*\n --timeout=3600s      
```

The paths exist in the sandbox but we can help rewrite them. That invocation can then be rewritten as
```
$(ci/scripts/target-location.sh //sw/host/opentitantool) \
--logging=info --interface=verilator --conf=sw/host/opentitantool/config/opentitan_verilator.json \
--verilator-bin=$(ci/scripts/target-location.sh //hw:verilator)/sim-verilator/Vchip_sim_tb \
--verilator-rom=$(ci/scripts/target-location.sh //sw/device/lib/testing/test_rom:test_rom_sim_verilator_scr_vmem) \
--verilator-flash=$(ci/scripts/target-location.sh //sw/device/tests:hmac_enc_test_prog_sim_verilator_scr_vmem64) \
--verilator-otp=$(ci/scripts/target-location.sh //hw/ip/otp_ctrl/data:img_rma)  --verilator-args=--trace \
console "--exit-failure=(FAIL|FAULT).*\n" "--exit-success=PASS.*\n" --timeout=3600s
```
I've done something like that for the cw310 debugging. It doesn't take bazel out of the equation, but it uses it for building and file tracking only which can be useful to get all the flags worked out before trying to get them implemented in bazel.
Bazel has a built in --test_args, but opentitan-tool needs arguments to be passed in specific orders

**Comment by drewmacrae** [comment]
```ci/scripts/target-location.sh -v //sw/host/opentitantool``` will view the output from bazel with https://github.com/lowRISC/opentitan/pull/12970 if you want to debug a query.

**Comment by timothytrippel** [comment]
instead of `$(ci/scripts/target-location.sh //sw/host/opentitantool) ...` you could also just use `bazel run //sw/host/opentitantool -- ...`

**Comment by drewmacrae** [comment]
> instead of `$(ci/scripts/target-location.sh //sw/host/opentitantool) ...` you could also just use `bazel run //sw/host/opentitantool -- ...`

I tried that and couldn't make it work, I think there may have been something to do with sandboxing, or maybe I made a typo

**Comment by timothytrippel** [comment]
ah its probably b/c you have to pass all the paths to the SW images too... thats why I think it would be much easier if we just had something like `bazel test //sw/device/tests:uart_smoketest_sim_verilator --trace` using a command line argument alias and a custom build setting like here: https://www.grahambrooks.com/software-development/2021/08/30/user-defined-bazel-arguments.html

**Comment by drewmacrae** [comment]
The args can also be temporarily edited in `rules/opentitan_test.bzl` where there's already enough of them being used that you can see what's going on.

**Comment by GregAC** [comment]
Note the timeout may need increasing also as wave dumping greatly slows things down.

**Comment by drewmacrae** [comment]
You can modify the definitons of the timeouts at the command-line
From https://bazel.build/reference/test-encyclopedia:
"The test timeout can be overridden with the --test_timeout bazel flag when manually running under conditions that are known to be slow. The --test_timeout values are in seconds. For example, --test_timeout=120 sets the test timeout to two minutes."

**Comment by tjaychen** [comment]
> You can modify the definitons of the timeouts at the command-line From https://bazel.build/reference/test-encyclopedia: "The test timeout can be overridden with the `--test_timeout` bazel flag when manually running under conditions that are known to be slow. The `--test_timeout` values are in seconds. For example, `--test_timeout=120` sets the test timeout to two minutes."

could we add this last bit to the [opentitan cheatsheet](https://docs.google.com/document/d/1Ab4AWJAuCmtBZMQFZAq6fDB70lLrumIXLG1PKx4GXx0/edit?usp=sharing)?

**Comment by a-will** [comment]
Reopening so that I add docs on how to do it. Adding the argument is easy enough:
```
--test_arg=--verilator-args=--trace
```

plus fiddling with the timeout, if necessary.

But it'll take a little thought to describe a good process for _finding_ the waveform. We might just want to make the waveform file path be configurable--It's hard-coded in the software right now.

**Comment by drewmacrae** [comment]
Does #15151 get us close enough we're comfortable finding the waveform, repeating the test under the shell's control etc?
