### ISSUE TITLE
Opentitan on other FPGAs

### ISSUE THREAD

**Issue by gtelzur** [lowRISC/opentitan#13053]
Hi,
The recommended reference FPGA board is quite expensive. Are there any cheap FPGAs (such as ecp5, ice40, Tang nano, …) known to work with Opentitan?
I will appreciate any assistance.

Guy

**Comment by tjaychen** [comment]
there are two overall
the cw310 - top_earlgrey, and cw305 - top_englishbreakfast

The latter runs a much reduced version of the former. We moved to cw310 due to utilization and the fact that it can support SCA.

**Comment by moidx** [comment]
Closing. For now. Please reopen if you have follow up comments. Thanks

**Comment by moidx** [comment]
Hi @gtelzur, just one small clarification. We are able to use the cw305 board based on the Artix7, and we integrate some of our SCA measurements for AES using scripts located in our https://github.com/lowrisc/ot-sca repository. The measurements can be taken with a Chipwhisperer Lite or Husky board.
