### ISSUE TITLE
[ci] Make run-fpga-cw310-tests.sh locally runnable

### ISSUE THREAD

**Issue by milesdai** [lowRISC/opentitan#13070]
`ci/scripts/run-fpga-cw310-tests.sh` is used in CI to run the top Earlgrey tests on the CW310. This script is hard to reproduce locally, however, for two reasons:
1. It starts by setting some environment variables and backdoor populating the bitstream cache.
2. It uses a special `--define cw310=lowrisc` flag that looks for specific USB ports to find the FPGA. 

We should refactor this script to make it easier to duplicate tests locally to help reproduce CI failures. Running this script should require no additional modifications or flags.

**Comment by moidx** [comment]
Cross referencing: https://github.com/lowRISC/opentitan/issues/13103

**Comment by milesdai** [comment]
Closing this in favor of the resolution in #14550. The `run-fpga-cw310-tests.sh` currently just performs some backdoor configuration of the bitstream cache and runs a bazel test command on all FPGA tests. This is unlikely to be useful to someone debugging a particular test. These users should just defer to the instructions in the [online docs](https://docs.opentitan.org/doc/getting_started/setup_fpga/#reproducing-fpga-ci-failures-locally).
