### ISSUE TITLE
[hmac] Clearing INTR_STATE.hmac_done

### ISSUE THREAD

**Issue by jon-flatley** [lowRISC/opentitan#1308]
It's possible I'm missing something in the documentation, but I can't find a way to clear the `INTR_STATE.hmac_done` bit short of a restart. This is manifesting as a bug in the HMAC DIF I'm working on; after the first run of HMAC my `dif_hmac_done()` function always returns true and the digest gets read early.

I've tried writing 0 to `INTR_STATE.hmac_done`, clearing `CFG`, clearing `CMD`, writing to `WIPE_SECRET`, and even writing 0 to `INTR_TEST.hmac_done`. None of these seem to clear the `INTR_STATE.hmac_done` bit.

**Comment by GregAC** [comment]
If you take a look at the register table https://docs.opentitan.org/hw/ip/hmac/doc/#register-table INTR_STATE.hmac_done has a type of 'rw1c', which is read, write 1 to clear.

So writing 1 to INTR_STATE.hmac_done should clear it.

Types can be found in the regtool documentation: https://docs.opentitan.org/doc/rm/register_tool/#configuration-and-register-definition-file-format

**Comment by jon-flatley** [comment]
Yep that does it. I'll refer to my disclaimer about missing something in the documentation. Thanks!
