### ISSUE TITLE
[cdc] clean-up cdc constraints

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#13091]
with #13016. cdc constraints are now being introduced to the flow.
These constraints are separate from sdc constraints and need their own mechanism of sourcing (right now I am temporarily including it into `run-cdc.tcl`, which is not right).

Further, some of the cdc constraints should be made more specific, as it is too broad from async_fifo rdata output to ibex rvalid.

**Comment by msfschaffner** [comment]
@tjaychen it sounds like this is mainly a cleanup item - can we potentially move this into M3?

**Comment by tjaychen** [comment]
yes let's move this to M3.

**Comment by moidx** [comment]
@cindychip does this need to be part of M2.5 or should we move it to Backlog?

**Comment by msfschaffner** [comment]
I don't think we have time to clean up the constraints locations for M2.5. since this is mostly cleanup, I think I am ok with postponing this.

**Comment by moidx** [comment]
Remaining CDC/RDC work is carried over to M5.

**Comment by johngt** [comment]
@andreaskurth - when you get back could you sync with @rswarbrick and see what remains. If it can be done in the scope of M5 then that's good - otherwise we need to consider whether this makes sense to do as a later cleanup vs putting it in the backlog.

**Comment by rswarbrick** [comment]
I do not know much about the tooling that the constraint files control. Removing the assignment from myself because I'm not sure I'd be much help!

**Comment by andreaskurth** [comment]
Just discussed in triage: Carrying CDC work over to M6

**Comment by vogelpi** [comment]
We discussed in the triage meeting to give higher priority to this to ramp up a new resource asap.
