### ISSUE TITLE
[test_rom, doc] Update reset handling and test methodology

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#13096]
Some chip-level tests currently rely on there being a POR immediately before running a test, and they check the RESET_INFO register from the rstmgr to determine if it occurred. This runs into various issues:

1. The SPI flash bootstrap method typically involves issuing a software reset before booting into flash. In the test ROM, the RESET_INFO register may contain both a POR and a software reset reason, with current practices. This confuses tests and causes failures.
2. The mask ROM itself uses POR from the RESET_INFO register to determine whether to perform certain initialization functions, and it saves the reasons in the retention SRAM and clears the RESET_INFO register.

Consequently, tests should not use the RESET_INFO register directly for determining whether this was the first run. A possible solution could be found with the following tasks:

- [x] #13265 
- [ ] Document the mask ROM's usage of the retention SRAM (or at least freeze the location of the reset reasons and document this).
- [x] Update the test methodology to always issue a POR after bootstrap. Alternatively, make this an option in the test definition in bazel, so we get coverage of cases without it. #13098 

Additionally, for stability of test output:

- [x] Flush the host-side UART RX buffer while the POR is held asserted (as part of the test setup sequence). Resolved by #13277

**Comment by a-will** [comment]
cc @tjaychen @drewmacrae @alphan

**Comment by drewmacrae** [comment]
> Known affected tests:
> 
> * //sw/device/tests:clkmgr_off_peri_test_fpga_cw310
> * //sw/device/tests:pwrmgr_wdog_reset_reqs_test_fpga_cw310

Doesn't this affect any test that works across a reboot? Those two tests are the only ones that are failing because they haven't yet been modified to work with both a POR and a software reset (which they see after bootstrapping).

Should we have a function
bool first_boot_in_test()
somewhere in a testing library to standardize how this is evaluated  and better let us perform customization of platform dependent test behavior?

**Comment by drewmacrae** [comment]
> [ ] Update the test ROM to handle reset reasons the same way as the mask ROM. Write the reset reason to the retention SRAM, then clear the RESET_INFO register.

As this is sufficient and working around this issue for broken tests feels counter-productive, I think I'll create an issue to work on it.

**Comment by a-will** [comment]
Closing this, as most tasks are done. Issue #5760 can continue to track the documentation portion.
