### ISSUE TITLE
[bazel] Allow bazel to run FPGA tests with a path to a local bitstream

### ISSUE THREAD

**Issue by milesdai** [lowRISC/opentitan#13115]
The bitstream cache mechanism in Bazel currently allows the user to run with three possible configurations:
1. Fetch a bitstream from the cache (`--define bitstream=gcp`)
2. Skip loading a bitstream and just use whatever's already on the FPGA (`--define bitstream=skip`)
3. Build a bitstream with Vivado and load that (`--define bitstream=vivado`)

To make debugging FPGA tests easier, we should add an option to load a local bitstream file (such as one downloaded as an Azure pipelines artifact).

**Comment by a-will** [comment]
Would it make sense to make these be arguments to a test runner instead of build config flags?

What's the blast radius of bitstream configuration flag changes? Does the whole workspace get invalidated? Or is it only a small number of targets?

**Comment by milesdai** [comment]
My understanding is that these flags need to be defined at the top-level bazel command since we need to tell Bazel what files to bring into the sandbox and the `vivado` option needs to be able to kick off a Vivado build. Of course, if you're manually invoking opentitantool or any other utility script, you could just point it to whatever bitstream you want. This is just to make the `bazel test` command work.

The bazel configurable attributes act kind of like a case expression on the `srcs` of the `test_rom` and `mask_rom` rules in `hw/bitstream/BUILD`. The documentation mentions that these configurations are applied during the analysis phase which suggests to me that using different configurations is the equivalent of modifying the source file. Thus it should only need to rebuild what depends on the bitstream. I did some quick testing (e.g. switching between the gcp and skip options), and I wasn't seeing any rebuilding.

@cfrantz Do you have any other thoughts on this (or this issue as a whole)?

**Comment by a-will** [comment]
> The bazel configurable attributes act kind of like a case expression on the `srcs` of the `test_rom` and `mask_rom` rules in `hw/bitstream/BUILD`. The documentation mentions that these configurations are applied during the analysis phase which suggests to me that using different configurations is the equivalent of modifying the source file. Thus it should only need to rebuild what depends on the bitstream. I did some quick testing (e.g. switching between the gcp and skip options), and I wasn't seeing any rebuilding.

If you tested it and no rebuilding was needed, then it's all good! :)

I've just been annoyed that the compilation_mode seems to affect _everything_ in the workspace, even though host tools and device code have very different needs. I wasn't sure what what the scope was for our custom attributes.

**Comment by milesdai** [comment]
The online docs now describe a process to [manually load a bitstream](https://docs.opentitan.org/doc/getting_started/setup_fpga/#reproducing-fpga-ci-failures-locally) onto the FPGA using opentitantool, so we no longer need this functionality.
