### ISSUE TITLE
[ci] use bazel managed version of clang-format

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#13163]
Bazel is using the [clang-format provided with the lowrisc tools chain](https://github.com/lowRISC/opentitan/blob/058344a4fc2a27460060718315407f4675fd5f00/rules/quality.bzl#L101), which is what we want since bazel manages the version for everyone, but CI [still uses the system installed clang-format](https://github.com/lowRISC/opentitan/blob/058344a4fc2a27460060718315407f4675fd5f00/ci/scripts/clang-format.sh#L33) (version 6.0).

We should update CI to use `bazel run //:clang_format_check` instead of the `clang-formatl.sh` script.

**Comment by drewmacrae** [comment]
Duplicate #13405 which is tracking the fix
