### ISSUE TITLE
[lc_ctrl] Change request for clock switching mechanism

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#13175]
We identified an issue in the life cycle external clock request logic. 

In particular, the OTP vendor test procedure (controllable/observable via the [VENDOR_TEST_CTRL](https://docs.opentitan.org/hw/ip/lc_ctrl/doc/index.html#Reg_otp_vendor_test_ctrl) and [VENDOR_TEST_STATUS](https://docs.opentitan.org/hw/ip/lc_ctrl/doc/index.html#Reg_otp_vendor_test_status) registers in `lc_ctrl`) needs to be able to run and program the [VENDOR_TEST](https://docs.opentitan.org/hw/ip/otp_ctrl/doc/index.html#direct-access-memory-map) partition in OTP while the device is still in RAW or in a TEST_LOCKED* life cycle state.

In these life cycle states, the clocks are not calibrated and therefore an external clock is required to program OTP. While this problem has been addressed for life cycle transitions with the external clock functionality that can be enabled via [TRANSITION_CTRL.EXT_CLOCK_EN](https://docs.opentitan.org/hw/ip/lc_ctrl/doc/index.html#Reg_transition_ctrl), it still poses an issue for vendor test operations, since there is currently no way to switch to an external clock without entering a life cycle transition, which could interfere with the vendor test operations.

One solution would be to change the behavior of TRANSITION_CTRL.EXT_CLOCK_EN so that the clock is switched whenever EXT_CLOCK_EN is set to 1, with the following restrictions:
1) Afaik, the clock mux mechanism is only glitch free and handshaked when transitioning from internal -> external clock. So the restriction would be that the CSR can only be set from 0 -> 1 (and then the device has to be reset to get back to 0).
2) The clock mux can only be switched in non-PROD/DEV life cycle states (same restriction as we currently have).

This will have a DV impact due to the different signal timing that needs to be modelled in the scoreboard. I don't think it's a major operation, but we may need 1-2 days of @cindychip time to adjust it.

Given that the IP is at D3 / V2S such a change would need leadership approval.

**Comment by tjaychen** [comment]
this change sounds good to me. 
@zi-v , could you re-iterate, for the purpose of this issue, the importance for such a feature?

**Comment by tjaychen** [comment]
shouldn't this be part of M2..?

**Comment by msfschaffner** [comment]
It should be yes, let me change that.

**Comment by msfschaffner** [comment]
This has now been implemented - closing.
