### ISSUE TITLE
[rv_dm] dmi interface lock up after asserting ndm reset

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#13179]
I found this issue while I am writing ndm reset request test.
In the test, rv_dm sent ndm reset request initiated by TB jtag agent through jtag_dmi interface.
![image](https://user-images.githubusercontent.com/99843637/173212917-bef68fd6-adfa-4056-a282-aa1f13b31630.png)
After asserting reset, test sent reset de-assert but de-assert command from TB jtag agent can't reach rv_dm because u_pinmux_strap_sampling is under reset (ndm reset triggerred all sys_reset), which makes
jtag_dmi interface locks up.

**Comment by tjaychen** [comment]
@jdonjdon thanks for identifying this.
The basic problem is that `pinmux` is in the wrong reset domain (sound familiar?)

I think we need to move pinmux over to the `lc` reset domain. @msfschaffner what do you think? I think I start most blocks in `sys` and move them to `lc` only if needed.

**Comment by tjaychen** [comment]
@jdonjdon i'm closing this down.
Let me know if you think anything is lingering and we can re-open.
