### ISSUE TITLE
[bazel] cleanup `export_files` in `sw/device/tests/BUILD`

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#13181]
#13180 added a temporary solution to enable writing closed source tests in the `manufacturer_test_hooks` repository that use open source test code. Specifically, it enabled defining an `opentitan_functest` in the closed source (`manufacturer_test_hooks`) repository without the need to specify the corresponding test hooks that should be used with the test on the command line. This provided a better usability experience for manufacturers as they could run `bazel test @manufacturer_test_hooks//...` to run all tests as opposed to running several invocations of `bazel test ...` for running tests with each set of test hooks. This came at the expense of improperly exposing the visibility of source code files outside of the `sw/device/tests/` package. 

This feature should be cleaned up to not improperly expose the visibility of source code files outside of their home package.

**Comment by msfschaffner** [comment]
Has this been cleaned up in the meantime?

CC @cfrantz
