### ISSUE TITLE
[DV/PWM] when DUTY_CYCLE_0.B_0 < DUTY_CYCLE_0.A_0,duty cycle decrement is not correct

### ISSUE THREAD

**Issue by dharanendrak** [lowRISC/opentitan#13200]
Martin,
when DUTY_CYCLE_0.B_0 < DUTY_CYCLE_0.A_0, duty cycle decrement is not correct

**Feature understanding  :**

   When DUTY_CYCLE_0.B_0 < DUTY_CYCLE_0.A_0, 
    the duty cycle should pulse BLINK_PARAM_0.x+1 pulses and then the duty cycle should be decreased by BLINK_PARAM_0.Y+1 units.

**Observation :**

    the duty cycle is pulsing 2 times the BLINK_PARAM_0.x+1 pulses and then the duty cycle is decreased by BLINK_PARAM_0.Y+1

**Configuration :**

This issue seen on channel 0.

DUTY_CYCLE_0.B_0 = 0x2BA4
DUTY_CYCLE_0.A_0 = 0x849A

BLINK_PARAM_0.X_0 = 0x08B6
BLINK_PARAM_0.Y_0 = 0x6C72

 

**More detailed observation in the RTL :**

  @ time = 12,419,975,846 ps i see that htbt_ctr_q is going zero. Meaning PWM_O pulse for BLINK_PARAM_0.X_0 unit cycles.
  I expect in the next cycle the transition to state B ( cycle B 0x849A - ( 0x6C72 + 1 ) = 0x1872 ) to happen, but that did not happen, instead.

  @ time = 24,835,901,350 ps I see that again the PWM_O seein pulsing for another BLINK_PARAM_0.X_0 unit cycles. Then seeing the transition to CYCLE B.

This is not correct behaviour as per the feature understanding.

**PR # 13164**
https://github.com/lowRISC/opentitan/pull/13164

**reproducing the issue :**

run the command > ./util/dvsim/dvsim.py hw/ip/pwm/dv/pwm_sim_cfg.hjson -i pwm_rand_output --fixed-seed 4276875110 --waves --purge --run-opts "+max_quit_count=100"

thanks
Dharanendra
![PWM](https://user-images.githubusercontent.com/105635983/173555597-3775badd-01e9-44c6-b9d1-cc5a0afe3e5f.GIF)

**Comment by martin-lueker** [comment]
Thanks for the issue: Is this for heartbeat or not heartbeat mode.

**Comment by dharanendrak** [comment]
Hi,
This is heart beat enabled mode.
Please take a look at the attachment in the issue for reference.

Thanks
Dharan
________________________________

**Comment by martin-lueker** [comment]
FYI: @Muqing-Liu 

Hey Dharan, could you please try rebasing on #13295?  This fixes the 12us delay that you mention above, however the test still does not pass, as the test does not like the pulses at and the new duty-cycle.  I'd appreciate your input as to what is going wrong now.

**Comment by dharanendrak** [comment]
The RTL fix is verified. So closing the issue.
