### ISSUE TITLE
[otbn] Check seed_valid bit of OTP scrambling interface

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#13201]
@ctopal noted that inside OTBN, the `seed_valid` bit of [the OTP scrambling interface](https://opentitan.org/book/hw/ip/otp_ctrl/doc/interfaces.html#interfaces-to-sram-and-otbn-scramblers) is currently not used. We register the bit received from OTP but then don't do anything with it.

If that bit isn't set, it means OTP has used an all-zero constant to derive the scrambling key. Meaning the key is not really safe to use. My understanding is that the first OTBN secure wipe requesting new scrambling keys is anyway initialized after setting up the entropy complex, so this bit should always be set unless something fishy is going on. I suggest to change the OTBN design such that a recoverable error is triggered when receiving a scrambling key with `seed_valid` low.

Any thoughts @mundaym , @GregAC , @msfschaffner ?

**Comment by tjaychen** [comment]
I thought the seed valid was more related to whether a particular seed was burned and locked in the otp. 
If that's the case, I don't necessarily think it has to be an error, because maybe during testing we have yet to setup otps yet. 

it would make sense to indicate this as a status though, and perhaps instead of the default 0, some kind of random fixed constant that can be parameterized.

**Comment by GregAC** [comment]
I think what @tjaychen suggests is most sensible. We may want to trigger the dmem/imem secure wipe when the bit is 0 for some testing/bring-up reason. Also all recoverable errors currently only occur during software execution. So a recoverable error during execution adds new error behaviour which adds more DV work which I'd rather avoid if at all possible.

**Comment by GregAC** [comment]
I think the conclusion here it's there's no major security concern though exposing the seed valid to SW for OTBN could be useful, though I think we should only consider this for a future release @vogelpi any thoughts?

**Comment by jadephilipoom** [comment]
As currently written, OTBN drivers (for both silicon creator and cryptolib) always wipe IMEM/DMEM before loading any application to OTBN, so they would refresh the scrambling key before use anyway. I also don't see a security issue here.

**Comment by vogelpi** [comment]
Okay, thanks for your input everybody (and sorry for my ultra late response). I agree that there are no security concerns then. I agree that it's not necessary to change the RTL of either OTBN or OTP. In both cases it wouldn't add much.

But I do think we should add some notes to the OTP documentation on this (similar to what we have in the SRAM controller, namely that keys are still ephemeral). I'll take care of this.

**Comment by vogelpi** [comment]
I just filed a PR to update the otp_ctrl documentation with the outcome of this discussion. See #20688.
