### ISSUE TITLE
[sw/silicon_creator] Names of OTP entries in the creator and owner partitions

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#13205]
It looks like all entries in the creator partition start with the `CREATOR_SW_CFG_` prefix while most items in the owner partition do not start with `OWNER_SW_CFG_`. I think this is something we should fix, right?

**Comment by moidx** [comment]
I think the change will make it easier to audit the system by making it easier to map config options to OTP logical partitions.

**Comment by tjaychen** [comment]
this sounds good to me, but i think we should only do this if there isn't much impact to design / dv. 

@msfschaffner 
@cindychip 
can probably best comment on that.
