### ISSUE TITLE
[chip-test] - rv_core_Ibex_fault_dump_test

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#13218]
### Test point name

[chip_sw_rv_core_ibex_fault_dump](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/chip_testplan.hjson?q=chip_sw_rv_core_ibex_fault_dump)

### Host side component

TBD

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

gac

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

# Verify the functionality of the ibex fault dump.
 - Purposely create an ibex exception during execution through reads to an ummapped address.
 - Ensure the rstmgr fault dump correctly captures the related addresses to the exception.

**Comment by tjaychen** [comment]
could you guys check this one against the rstmgr_cpu_info_test? 
I think they're pretty similar in nature, so maybe we should enhance a single test to do both?

**Comment by engdoreis** [comment]
See my comment [here](https://github.com/lowRISC/opentitan/issues/13219#issuecomment-1223702313)

**Comment by HU90m** [comment]
Passed three nightly regressions.
