### ISSUE TITLE
rv_core_Ibex - Address translation test

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#13215]
# Verify the simple address translation functionality.
 - Setup address translation for both slots on the the I and D
   side and check correct translation for I and D accesses.
 - Switch address translation to use different regions that
   overlap for both slots and check translation again. Ensure some
   test accesses match both regions, where the lowest indexed one
   takes priority.
 - Turn off address translation and confirm regions are no longer
   being remapped.

**Comment by HU90m** [comment]
Added in https://github.com/lowRISC/opentitan/pull/13729
