### ISSUE TITLE
[chip-test] - chip_sw_entropy_src_ast_fips

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#13225]
### Test point name

[chip_sw_entropy_src_ast_fips](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/data/chip_testplan.hjson?q=chip_sw_entropy_src_ast_fips)

### Host side component

N/A

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

martin-lueker

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

# Verify the connectivity of rng_fips_o feedback signal to RNG.
The test should be defined!

**Comment by engdoreis** [comment]
I can not find the test in the testplan anymore, should we close this issue?

**Comment by tjaychen** [comment]
yeah i believe this test is being moved to the [connectivity testplan](https://github.com/lowRISC/opentitan/blob/7e957e13d1c1829545b5646af9b1c4a2b8146725/hw/top_earlgrey/data/chip_conn_testplan.hjson#L588).

So it does still need to be implemented.

**Comment by vrozic** [comment]
It looks like this issue was already solved in https://github.com/lowRISC/opentitan/pull/14751/commits/266e54f415a409e1313e8d179959f726c56813eb

@msfschaffner Can you confirm?

**Comment by msfschaffner** [comment]
Yes this connectivity test has been implemented, hence we can close the issue.
