### ISSUE TITLE
[chip-test] chip_sw_entropy_src_fuse_en_fw_read

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#13229]
### Test point name

[chip_sw_entropy_src_fuse_en_fw_read](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/data/chip_testplan.hjson?q=chip_sw_entropy_src_fuse_en_fw_read)

### Host side component

N/A

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

martin-lueker

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

# Verify the fuse input entropy_src.
- Initialize the OTP with this fuse bit set to 1.
- Perform an entropy request operation.
- Read the entropy_data_fifo via SW; verify that it reads valid Values.
- Reset the chip, but this time, initialize the OTP with this fuse bit set to 0.
- Perform an entropy request operation.
- Read the internal state via SW; verify that it reads all zeros this time.

**Comment by johngt** [comment]
Needs the Bazel test point merged in the testplan. @engdoreis

**Comment by engdoreis** [comment]
This test was removed from the testplan by this [PR](https://github.com/lowRISC/opentitan/commit/3f447cc12b6299ae6bc134644fdf6e89b807946d#diff-5046cf8e62cd2acdbb85d934b21848284f66e2cd2e6e79485b0b1bd527b0e420)
