### ISSUE TITLE
[chip-test] - chip_sw_csrng_lc_hw_debug_en

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#13222]
### Test point name

[chip_sw_csrng_lc_hw_debug_en](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/data/chip_testplan.hjson?q=chip_sw_csrng_lc_hw_debug_en)

### Host side component

N/A

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

@mwbranstad 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)
## Verify the effect of LC HW debug enable on CSRNG.

TODO: This is pending SCA security review and might be removed.

**Comment by engdoreis** [comment]
Unfortunately it didn't pass in the latest nightly:


  | Tests | latest | 2022.10.10 | 2022.10.08/1 | 2022.10.08/2 | 2022.10.06 | 2022.10.05/1 | 2022.10.05/2 | 2022.10.03/1 | 2022.10.03/2 | ... | 2022.09.30 | 2022.09.29 | 2022.09.28 | 2022.09.27 | 2022.09.26/1 | 2022.09.26/2 | 2022.09.26 | 2022.09.24 | 2022.09.23 | Suite
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
chip_sw_csrng_lc_hw_debug_en_test | 33.33 | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | ... | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A | Unmapped tests

**Comment by tjaychen** [comment]
@moidx let me know if you want me to help take a look.

**Comment by moidx** [comment]
Fixed in https://github.com/lowRISC/opentitan/pull/15468.  There was an issue with how we were comparing the CSRNG output in DEV mode.
