### ISSUE TITLE
[chip-test] - chip_sw_csrng_edn_cmd

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#13220]
### Test point name

[chip_sw_csrng_edn_cmd](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/data/chip_testplan.hjson?q=chip_sw_csrng_edn_cmd)

### Host side component

N/A

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

martin-lueker

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

## Test Description

 Verify incoming command interface from EDN.
- Have each EDN instance issue an instantiate command to CSRNG.
- When done, verify the reception of cmd req done interrupt.
- Check the data returned to EDN via connectivity assertion checks.

**Comment by vogelpi** [comment]
FYI, I've now added  a top-level test for the AES masking off feature (see https://github.com/lowRISC/opentitan/pull/15732). This will run instantiate (through the SW interface) and reseed (through reseed cmd FIFO) commands with 12 additional words of data (the maximum), the generated commands (through generate cmd FIFO) don't use additional data in this test.

**Comment by moidx** [comment]
Started implementation of this test in https://github.com/lowRISC/opentitan/pull/15830.

So far seeing some issues: 


1. OTBN throws `rnd_fips_chk_fail` when the EDN1 generate len is set to 1, and reseed interval to 1. 
2. If the reseed interval on EDN1 is greater than 1, the test seems to hang on the FPGA. 
3. The test fails on the FPGA with the default `kEntropyFetchTimeoutMicros = 1000` value in `rand_testutils.c` when initializing the test parameters. The issue goes away when `kEntropyFetchTimeoutMicros = 100000`.

**Comment by moidx** [comment]
@tjaychen is working on a couple of fixes to get the test to work in DV: 

* [ ] https://github.com/lowRISC/opentitan/pull/15848
* [ ] https://github.com/lowRISC/opentitan/pull/15847

**Comment by moidx** [comment]
Closed by https://github.com/lowRISC/opentitan/pull/15913. I will open additional issues to capture remaining debug work derived from https://github.com/lowRISC/opentitan/pull/15830.
