### ISSUE TITLE
[cdc] CDC between clk_spi_out_buf and sys_clk 

### ISSUE THREAD

**Issue by jeoongp** [lowRISC/opentitan#13286]
![image](https://user-images.githubusercontent.com/103145460/174386738-d816aee4-903b-45dd-9e81-9f84e9170abb.png)

Data come from u_reg sys_clk domain are captured in spi clk directly. 
I think we need to add async FIFO in the same way as other signals.
![Screen Shot 2022-06-17 at 12 04 06 PM](https://user-images.githubusercontent.com/103145460/174386980-5028ee06-376e-48fc-8469-9f7162c2687a.png)

**Comment by tjaychen** [comment]
hmmm... this is an interesting find.
I think the intent here was that when the transaction begins, the `sys_clk` content is latched into the `tpm` domain.
Although I am not sure how we can guarantee whether the `sys_clk` contents aren't changing while the latch is happening. 

It almost seems like the enable signal needs to move to `sys_clk` domain sampling of `csb` to ensure the contents don't change during the transactions.

**Comment by jeoongp** [comment]
You mean csb_edge detector and the flip flop need to be moved to sys_clk domain?

**Comment by tjaychen** [comment]
i THINK so. let me know if that makes sense.
When Csb drops, the transaction begins, so we need to capture the sys_clk domain values.
From Csb dropping, to data actually being returned to the host, there is something like....32 SPI clock cycles.

So if we detect csb dropping on sys_clk, we can capture and hold something that we know will not change for the duration of the transaction. We also know that while capture, it cannot be changing, since the capturing is also done on the sys_clk.

**Comment by a-will** [comment]
This is the same situation as the status register in flash mode, right? Detecting the CSB drop in sys_clk can cause a "transit register" to sample the current value in the sys_clk domain, and that would hold for the spi_clk to capture and use during the transaction. As long as spi_clk isn't radically faster than sys_clk (such that the round-trip time is less than the time to use the value), that'd work.

If spi_clk actually were too fast, then I think we'd have to stage it in the spi_clk domain before using it for a response.

**Comment by jeoongp** [comment]
@a-will @tjaychen thanks for explanation. This approach makes sense!

**Comment by tjaychen** [comment]
> This is the same situation as the status register in flash mode, right? Detecting the CSB drop in sys_clk can cause a "transit register" to sample the current value in the sys_clk domain, and that would hold for the spi_clk to capture and use during the transaction. As long as spi_clk isn't radically faster than sys_clk (such that the round-trip time is less than the time to use the value), that'd work.
> 
> If spi_clk actually were too fast, then I think we'd have to stage it in the spi_clk domain before using it for a response.

to that point, it might make sense to add an assertion to roughly check for the clock ratios between sys_clk and spi_clk. So if spi_clk ever runs too fast we'll immediately register an error.

**Comment by jeoongp** [comment]
spi_clk is 62.5 MHz while sys_clk runs on 24 MHz? If we assume the data will not change during the pulse generation in the slow clock (sys_clk), the data is supposed to keep the same data during the pulse generation in fast (spi_clk). 
That is, the pulse is generated faster in spi_clk. It sounds like we don't need to worry about data changing while capturing in the original code.
If I missed anything, let me know.

**Comment by tjaychen** [comment]
ah i don't think we can assume `spi_clk` will always be a certain speed. It certainly can be slower.
Further though, it's possible that when a `spi_clk` transition starts, software tries to make a chance to the registers at the same time right?

**Comment by jeoongp** [comment]
RTL update is committed in https://github.com/lowRISC/opentitan/pull/13398.

**Comment by eunchan** [comment]
The assumption was that the TPM registers are changed while SPI is idle. So the latching here is more like committing the change into SPI clock domain.

But, as @a-will pointed in the Read Status module (in Flash mode) and @tjaychen said, it is unpredictable for SW to check if SPI is idle or not. So, Tim's suggestion looks good (latching @ SYS_CLK first). And #13398 and #13586 addressed that. ( @jeoongp please confirm )

However, using the latched signal directly in SPI will be caught by the CDC tool. 2FF may resolve W_DATA but will raise RECONVERGENCE issue. We could waive that as it is guaranteed the SPI TPM uses those values way later than the CSb assert pulse (if SYS_CLK isn't like 100 times slower than SPI_CLK).

Let me sync with @jeoongp and make the PRs more self-contained. SPI_DEVICE top is already inter-twined with Generic, Flash, Passthrough modes signals + logics. So I tried to make TPM as a separate module.

**Comment by jeoongp** [comment]
> The assumption was that the TPM registers are changed while SPI is idle. So the latching here is more like committing the change into SPI clock domain.
> 
> But, as @a-will pointed in the Read Status module (in Flash mode) and @tjaychen said, it is unpredictable for SW to check if SPI is idle or not. So, Tim's suggestion looks good (latching @ SYS_CLK first). And #13398 and #13586 addressed that. ( @jeoongp please confirm )
> 
> However, using the latched signal directly in SPI will be caught by the CDC tool. 2FF may resolve W_DATA but will raise RECONVERGENCE issue. We could waive that as it is guaranteed the SPI TPM uses those values way later than the CSb assert pulse (if SYS_CLK isn't like 100 times slower than SPI_CLK).
> 
> Let me sync with @jeoongp and make the PRs more self-contained. SPI_DEVICE top is already inter-twined with Generic, Flash, Passthrough modes signals + logics. So I tried to make TPM as a separate module.

Yes @eunchan. both PRs (https://github.com/lowRISC/opentitan/pull/13398 and https://github.com/lowRISC/opentitan/pull/13586) addressed latching data @sys_clk using csb input. 1) https://github.com/lowRISC/opentitan/pull/13398 generates the edge using 2FFs @sys_clk + glitch protection filter. 2) https://github.com/lowRISC/opentitan/pull/13586 generates the edge @spi_clk and it's converted to the edge @sys_clk through a pulse stretcher. 

As I mentioned in https://github.com/lowRISC/opentitan/pull/13586, I will move data capture logic into spi_tpm to be aligned with your original code.

**Comment by eunchan** [comment]
So, the safest option is to use 2FF @ SYS_CLK -> latch TPM registers with CSb pulse -> 2FF to SPI_CLK then latch the latched TPM register @ SPI_CLK
These operation should be finished within 32 SPI_CLK cycles to use the value safely. (should have assertion that 3 SYS_CLK < 28 SPI_CLKs)

Other thing is to move the logic inside TPM to be more maintainable. I think #13398 is closer implementation than #13586

**Comment by jeoongp** [comment]
Can you explain why we need 2FF to SPI_CLK before latching TPM regs @ SPI_CLK? If it is to generate a new csb_pulse onto spi_clk after latching TPM regs @sys_clk, I agree. 

For #13398, some downstream registers can have unnecessary values after the SPI transaction but they will be flushed and updated with new values at the beginning of the next SPI transaction. @tjaychen and @a-will, what do you think of it?

**Comment by eunchan** [comment]
OK. I [summarized my idea](https://docs.google.com/document/d/1YDo6wJHQRo-FAxER62Rqcwq44IlonWQSLkoEBY1uIgY/edit) and the implementation done in #13586. I think #13586 is good.

**Comment by tjaychen** [comment]
@jeoongp is this okay to close now? i believe the tpm reg issue has been resolved some time ago.

**Comment by jeoongp** [comment]
Yes ^_^
