### ISSUE TITLE
Link to Ibex's DV methodology is broken 

### ISSUE THREAD

**Issue by michael-etzkorn** [lowRISC/opentitan#13280]
https://docs.opentitan.org/doc/ug/dv_methodology/#core-ibex-level-dv has a broken link to Ibex's DV methodology. 

I'm assuming it's the same link that lives here https://ibex-core.readthedocs.io/en/latest/03_reference/verification.html

**Comment by michael-etzkorn** [comment]
The link to `build_docs` also seems broken under testplan. 
https://docs.opentitan.org/doc/ug/dv_methodology/#testplan 

It leads to https://docs.opentitan.org/README/#documentation

**Comment by vogelpi** [comment]
Thanks for reporting these broken links @michael-etzkorn . The `build_docs` link seems to have been fixed in the meantime. I've filed a PR to fix the Ibex DV link.
