### ISSUE TITLE
[opentitanlib] `clear_rx_buffer()` implementation for `UltraDebugUart` is affected by libftdi version

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#13290]
I ran into this issue while working on #13277 which adds the `clear_rx_buffer()` function to the `Uart` trait and implements this for all transports. I wasn't able to implement it for `UltraDebugUart` though because I got the following linker error:

``` 
safe_ftdi::Device::purge_usb_buffers: error: undefined reference to 'ftdi_tcioflush'
          collect2: error: ld returned 1 exit status
```

The gist of the problem is the version of `libftdi`. The buffer clearing interface of`libftdi` was updated on 2020-07-07 (see [here](https://www.intra2net.com/en/developer/libftdi/index.php) and [here](https://www.intra2net.com/en/developer/libftdi/documentation/ftdi_8h_source.html#l00184) for more details). Our rust dependencies were updated to call the new methods but the version of the `libftdi` available on the `opentitan` docker image (ubuntu 18.04 based, like the images we used in the CI) is too old. ~Instead of assuming that everyone can obtain the newer version of `libftdi` on their systems and risking building peoples builds I added an `unimplemented!()` to `UltraDebugUart::clear_rx_buffer()`.~

Update: I did a quick search and it looks like the first version where v1.5 is available is [ubuntu-21.10](https://launchpad.net/ubuntu/impish/+package/libftdi1-2).

Update: Replaced `unimplemented!` with a `read_timeout()` loop which should work for now.

**Comment by msfschaffner** [comment]
CC @a-will @cfrantz @timothytrippel

**Comment by timothytrippel** [comment]
Not sure this is still an issue, closing for now and we can re-open in the future if needed.
