### ISSUE TITLE
[sw,dv,pinmux] Dif error for pinmux output select function

### ISSUE THREAD

**Issue by davebwil** [lowRISC/opentitan#13302]
For a test in development for sw_chip_sw_sysrst_ctrl_outputs I am using the function
dif_pinmux_output_select to assign a pad to kTopEarlgreyPinmuxOutselSysrstCtrlAonZ3Wakeup.

The function is failing with a bad arg error.
I believe the problem is that in top_earlgrey.h the value for the pin is

`kTopEarlgreyPinmuxOutselSysrstCtrlAonZ3Wakeup = 77.`

The DIF function (dif_pinmux.c line 175) checks this argument against 

` outsel >= (2 + PINMUX_PARAM_N_MIO_PERIPH_OUT)`

where PINMUX_PARAM_N_MIO_PERIPH_OUT is defined as 75 in pinmux_regs.h therefore 77 fails this test.

**Comment by a-will** [comment]
Oops, I goofed and used the wrong starting offset (probably copied over from dif_pinmux_input_select, but the output version has one more possible fixed value, so it should start at 3 instead of 2). I'll fix that up.
