### ISSUE TITLE
[testing] Review/audit tests that rely on resets

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#13307]
This came up while discussing #13293 offline with @tjaychen and we thought we should do a quick audit of the existing chip-level tests to make sure we don't have similar issues.

**Comment by msfschaffner** [comment]
Is this still relevant or can we close this?

**Comment by tjaychen** [comment]
I think we haven't actually looked through all the tests yet.

**Comment by tjaychen** [comment]
if it comes to it, i think this is something we can punt to M3.
Our goal for M2 is really just to get all the tests written now..

**Comment by tjaychen** [comment]
fixed by #16324
