### ISSUE TITLE
[usbdev] Add some basic event counters

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#13316]
Add some saturating counters to track events that might otherwise be invisible to software, such as...
- Number of NAKs due to missing AV buffer
- Number of NAKs due to full RX buffer
- Number of dropped packets with bad token / CRC
- Number of attempted IN packets that didn't get a handshake

These can be useful for detecting marginal cables / boards and performance issues.

It would also be nice to detect the number of IN requests that don't get a response when we _expect_ to keep up, but it's harder to distinguish between "Oops, we were too slow" and "There was no data right now, and that's fine."

**Comment by a-will** [comment]
I am realizing that only the device side knows what happens to isochronous OUT transactions. Do we need endpoint-specific information or is the device-wide counter enough?

There is a similar situation for isochronous IN transactions, but this still has the problem of unknown intentions, as above. We don't currently require users to write to usbdev to indicate whether they intentionally want to NAK / drop an IN request.

**Comment by msfschaffner** [comment]
CC @alees24

**Comment by msfschaffner** [comment]
@alees24 @a-will how easy would it be to add this?
@jesultra is this something you'd consider a must for the production chip or not?

**Comment by johngt** [comment]
@moidx / @jesultra - could you please confirm if this is a req for production chip.

**Comment by a-will** [comment]
FYI, this was merely a nice-to-have idea when I wrote this issue. It'd be a new, late-breaking requirement if it escalated. :smile:

**Comment by jesultra** [comment]
These are not strict requirements from ChromeOS. Nice to have for sure, but we can certainly use the production chips without this feature.

**Comment by alees24** [comment]
Fixed by  #22118
