### ISSUE TITLE
[doc,hw] Entropy source IP initialization documentation

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/opentitan#13336]
The [initialization documentation of the entropy source](https://docs.opentitan.org/hw/ip/entropy_src/doc/#initialization-1) has an argument `rate` which is not used. How do we use this properly?

More generally, how can I check that these initialization functions for other IP blocks are correct? For example, [the initialization function of the CSRNG](https://docs.opentitan.org/hw/ip/csrng/doc/#initialization) mentions `CTRL_REG`, where can I find this back in the code?

**Comment by ctopal** [comment]
For the sceond part, I believe the name of the register comes before `_REG` part always. So if I would see anything that ends with `_REG`, I would copy the first part of it and search it throughout the register table in the documentation.

**Comment by marnovandermaas** [comment]
That clears up the second part, the only thing left to figure out is what to change in the entropy source initialization function.

**Comment by marnovandermaas** [comment]
For what it's worth, there are these two functions:
- `dif_entropy_src_init` defined at https://github.com/lowRISC/opentitan/blob/master/sw/device/lib/dif/autogen/dif_entropy_src_autogen.c#L14
- `dif_entropy_src_configure`defined at https://github.com/lowRISC/opentitan/blob/master/sw/device/lib/dif/dif_entropy_src.c#L16

We could refer to those in the documentation?
