### ISSUE TITLE
[otbn,dv] Verify OTBN redundancy countermeasures

### ISSUE THREAD

**Issue by prajwalaputtappa** [lowRISC/opentitan#13330]

**Comment by johngt** [comment]
In open discussion with @GregAC and @vogelpi about this.
Specifically the countermeasure in discussion is OTBN.TLUL_FIFO.CTR.REDUN

**Comment by prajwalaputtappa** [comment]
Nothing needs to be done for verifying OTBN.TLUL_FIFO.CTR.REDUN as it is a feature of TLUL module. 
This task will be closed once https://github.com/lowRISC/opentitan/pull/13867 can be closed.
