### ISSUE TITLE
[rtl/csrng] CSRNG SW Generate output

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#13342]
As shown in PR #13341, when issuing a DRBG generate command for 16 words, the returned words are in the following order with respect to the NIST test vector: 

```c++
  // Expected result: d1c07cd95af8a7f11012c84ce48bb8cb87189e99d40fccb1771c619bdf82ab2280b1dc2f2581f39164f7ac0c510494b3a43c41b7db17514c87b107ae793e01c5

  const uint32_t kExpectedOutput[kExpectedOutputLen] = {
      // word offsets: 12,13,14,15
      0xe48bb8cb, 0x1012c84c, 0x5af8a7f1, 0xd1c07cd9, 
      // word offsets:  8,9,10,11
      0xdf82ab22, 0x771c619b, 0xd40fccb1, 0x87189e99, 
      // word offsets: 4,5,6,7
      0x510494b3, 0x64f7ac0c, 0x2581f391, 0x80b1dc2f,
      // word offsets: 0,1,2,3
      0x793e01c5, 0x87b107ae, 0xdb17514c, 0xa43c41b7,
  };
```

A more natural order would be to swap the word order on each 128 bit chunk so that the result word offset sequence is [15...0].

This issue is to check whether this is a possible change on the RTL side.

**Comment by matutem** [comment]
If the RTL cannot change, write a function that returns the data reordered.

**Comment by moidx** [comment]
I will capture this in software documentation.

**Comment by johngt** [comment]
@moidx - given that this was tagged as M3, I'm changing the dev stage to V3.
If though we want an RTL change late into the day then we will need to make it a P0/P1 issue. Based on the discussion though it looks like it will be a document only approach.

**Comment by vogelpi** [comment]
I have also come across this and spent quite some time to reverse engineer the order in which bytes need to be fed to CSRNG and in which order they can be retrieved from the GENBITS and INT_STATE_VAL registers. The information in this issue and in the CSRNG testutils were useful. I've now filed a PR to add a section about this to the CSRNG documentation: #16568
