### ISSUE TITLE
[xbar] xbar reset connection issue

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#13354]
in order to handle async transactions, the xbar takes as its inputs resets related to different clock domains.
Currently, the reset hooked up for connections to blocks like usb/spi_host/ are using the end points reset.

This is a problem because if the end point is reset by software, it may trigger unintentional request / responses due to one side of an asynchronous fifo being reset.  Instead of taking the end point's reset, it should just take the reset related to the appropriate clock domain.

**Comment by matutem** [comment]
If I understand correctly, a SW triggered reset for some peripheral was also resetting some part of the xbar... which I assume had undesirable side-effects.
