### ISSUE TITLE
Improve ergonomics of formatters: buildifier, clang-format, license_check, and util/lintpy.py

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#13362]
Per @cfrantz's comment[^0], these are some useful formatters/checkers.

* `//:buildifier_check`
* `//:clang_format_check`
* `//:license_check` (I think I already saw a presubmit fail on this, but I can't find any code in //ci/ to back that up.)
* `util/lintpy.py`

Proposed improvements:

* Check the include/exclude lists for clang-format rules
* Add Bazel target to run `util/lintpy.py`
* Add meta-targets `//:quality_{check,fix}` that will run all of the above formatters/checkers.
  * I'm new to Bazel, and I'm kind of stumped on this. In Make, we would want a `.PHONY` target that depends on the other targets. I think `genrule` is the closest we can get, but it's tricky to run a command in the repo root — Bazel run the given command from one of its build directories.

@drewmacrae Any thoughts on this?

[^0]: https://github.com/lowRISC/opentitan/pull/13338#discussion_r905257724

**Comment by drewmacrae** [comment]
https://cs.opensource.google/opentitan/opentitan/+/master:ci/jobs/quick-lint.sh;l=6?q=quick&sq=&ss=opentitan%2Fopentitan

Does a lot of this, I think some steps could be ported to the bazel version and the vendored versions could be removed.

azure-pipelines.yml duplicates functionality in that shell script

**Comment by drewmacrae** [comment]
I'm updating CI to use `./ci/bazelisk.sh run //:clang_format_check` and `./ci/bazelisk.sh run //:clang_format_fix` in preference to `clang-format` in the local environment.

**Comment by drewmacrae** [comment]
The version of clang-format in CI is old and out of sync with your machine and the lowrisc toolchain. I've updated that here: https://github.com/lowRISC/opentitan/pull/13339

The formatters and checkers are all being run as a part of CI. The proposed improvements seem valid to me.

**Comment by msfschaffner** [comment]
@cfrantz @drewmacrae @dmcardle can this be closed or are there any outstanding tasks?

**Comment by dmcardle** [comment]
I'd still like for us to have something like `//:quality_{check,fix}`, this has just been on the back burner.

**Comment by drewmacrae** [comment]
There will be '//quality/...' soon

**Comment by cfrantz** [comment]
All of the quality checkers and fixers have been migrated to`//quality` in #15044.  The checkers have been converted to tests, so you can now unconditionally run all of them with:
```
bazel test //quality/... [--test_output=streamed]
```

The fixers are still executables and require you to run them (e.g. `bazel run //quality:clang_format_fix`)

**Comment by dmcardle** [comment]
Awesome! I'll go ahead and close this.

**Comment by cfrantz** [comment]
Yes, we should.

What I'd like is to gang them all together under a single rule (e.g.
"//:quality_check") and make that the thing presubmit invokes.
