### ISSUE TITLE
The file starting with xil.default cannot be found when FPGA is built

### ISSUE THREAD

**Issue by trrrraum** [lowRISC/opentitan#13377]
When building opentitan with FPGA, bitstream is successfully generated, but looking at Hierarchy, I found that xil_defaultlib.xxxxxx are instantiated under many header files, but they are not added to the project. Could anyone tell me which step is the problem? Thanks!

**Comment by trrrraum** [comment]
I didn't use bazel to build the FPGA, I used:
**./meson_init.sh
ninja -C build-out all
fusesoc --verbose --cores-root . run --flag=fileset_top --target=synth lowrisc:systems:chip_earlgrey_cw310**

**Comment by msfschaffner** [comment]
The meson build flow has been deprecated and is not supported anymore.
Please try again with the bazel build flow and reopen if the warnings still persist.
