### ISSUE TITLE
[ci] Skip FPGA build if there are no hardware or `test_rom`|`mask_rom` changes.

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#13374]
This is to optimize the CI iteration time. Alternative as a workaround, we should be able to skip FPGA builds if changes reside in any of the following build paths: 

```console
# Skip on test plan updates.
**testplan.hjson

# Skip on test updates.
//sw/device/tests/...

# Safe to skip. 
//site/...
//doc/...
COMMITTERS
CLA
**.md
```

**Comment by arunthomas** [comment]
CCing @milesdai since we talked about this today

**Comment by arunthomas** [comment]
Updating assignee: @a-will offered to take this over; @milesdai was happy to pass the baton
