### ISSUE TITLE
Run the test entropy src end reqs in continuous mode

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#13393]
Run the test entropy src end reqs  in continuous mode and configure the EDN to force a CSRNG trigger a couple of times.

**Comment by engdoreis** [comment]
Tagging @moidx for visibility

**Comment by andreaskurth** [comment]
With continuous mode you mean the [*Auto Request Mode*](https://docs.opentitan.org/hw/ip/edn/doc/index.html#auto-request-mode), right? If so, code for that will be added to solve #7424.

**Comment by tjaychen** [comment]
do we feel like this test is already accomplished by `entropy_src_edn_req_test`? I feel like it is.

**Comment by engdoreis** [comment]
I opened this issue motivated by this [comment](https://github.com/lowRISC/opentitan/pull/12966#discussion_r888507880) from @moidx.
@moidx can we close this issue?

**Comment by tjaychen** [comment]
> I think this issue can be closed now.
> 
> nit: We should change the name of [entropy_testutils_boot_mode_init](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/lib/testing/entropy_testutils.h?q=entropy_testutils_boot_mode_init&ss=opentitan%2Fopentitan) as it sets `fips_mode = true`, which means that we are running in continuous mode and not boot mode.

i have a PR where i'm cleaning up `entropy_testutils`. 
And yeah, the boot mode terminology is a bit weird...but boot mode has meaning in both `edn` and `entropy_src`, so it's a little annoying. Right now entropy_src is in fips mode, but `edn` is not.

**Comment by johngt** [comment]
@tjaychen - unless you feel otherwise, from lowRISC side we believe this issue to be closed.
Could you add the related PR for entropy_testutils and close out if nothing else is to be done. Otherwise please comment and let @doreis-lowrisc what is still needed. Thanks!

**Comment by tjaychen** [comment]
let's keep it open for a a bit more.
There are still a fair number of tests that directly use `boot_mode` instead of `auto_mode`.
We can't quite make the switch yet until #14571 is merged, otherwise those tests will likely just hang.

**Comment by tjaychen** [comment]
@vogelpi do you want to close this issue?
I know your latest PR of changing RND to URND also came with switching from boot to auto.  So I think that satisfies the spirit of this issue.

**Comment by vogelpi** [comment]
Yes, let's close this issue. It's pretty cool that we have are now using auto/continuous mode more widely. Thanks for the effort you've put into this @tjaychen and @andreaskurth !
