### ISSUE TITLE
[util] clangd complaining about unknown argument '-fno-canonical-system-headers'

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#13406]
I see this on the first line of .c sources, but I'm not exactly sure why.

I have a sneaking suspicion that compile_commands.json is using the wrong gcc, but I'm not sure how that would work; the `bazel aquery` results explicitly call /usr/bin/gcc.

@drewmacrae IIRC, you mentioned something about "gcc" being a lie for host-targeted builds. Could you point me to where that misdirection occurs?

The error:

```
Unknown argument: '-fno-canonical-system-headers' [drv_unknown_argument]
```

**Comment by drewmacrae** [comment]
https://github.com/lowRISC/bazel-embedded/tree/riscv32/toolchains/lowrisc_toolchain_rv32imc/clang_wrappers There's a set of symlinks in here

**Comment by dmcardle** [comment]
Oh, I think I got it backwards! It looks like this only affects cross-compiles for riscv — I'm guessing executing `gcc` causes `clang_wrappers/gcc` to run, which just execs the riscv `clang` binary.

**Comment by msfschaffner** [comment]
@a-will @cfrantz @timothytrippel @mundaym is this still relevant?
