### ISSUE TITLE
[dv/common] tl_errors_vseq runs very slow on hmac and spi_device

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#1341]
Running profiling to check why tl_errors_vseq runs slow on hmac and spi_device.
Potentially could related to large memory inside the two devices.

**Comment by cindychip** [comment]
Running VCS profiling on hmac and gpio for `tl_errors_vseq`, the results are:

---- hmac -----------------------------------
Constraints: 99.53%
---- gpio -------------------------------------
Constraints: 16.88%

Seems like in `tl_errors`, calculating memory constraints consumed too much time. I will work with Weicai to see if there are any potential fixes.

**Comment by weicaiyang** [comment]
Fixed this at #1425

**Comment by cindychip** [comment]
PR #1425 is merged.
