### ISSUE TITLE
[dv] usb clk measurement fails

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#13411]
@matutem 

I enabled the clock measurement in chip-level tests.  Looks like 1/3 usb clk measurement fails. We expect the cnt range to be ee-f0, but it may get to f1. Should we relax the max threshold a bit?
![Screen Shot 2022-06-24 at 4 08 08 PM](https://user-images.githubusercontent.com/49293026/175721447-215680d8-f0bc-427a-a6b4-2cb40a17c806.png)

Here is the waveform:
> ot_debug -j smart:d1419ead-09b6-4024-980d-5790feb4aa2e

**Comment by matutem** [comment]
Hmm, are you running with calibrated usb clock? Background: the AST starts up with uncalibrated USB, so it will be off. Rather than relaxing the measurement requirements we pass a runtime plusargs to simv so the AST will run with calibrated clocks, which is done with
  run_opts: ["+calibrate_usb_clk=1"]
in your test's json entry.

**Comment by weicaiyang** [comment]
> Hmm, are you running with calibrated usb clock? Background: the AST starts up with uncalibrated USB, so it will be off. Rather than relaxing the measurement requirements we pass a runtime plusargs to simv so the AST will run with calibrated clocks, which is done with run_opts: ["+calibrate_usb_clk=1"] in your test's json entry.

I see. Thanks. Let me have a try

**Comment by matutem** [comment]
By the way, setting the clock to be calibrated may seem too aggressive, but USB calibration is a very specific step and involves the vendor. It is best to run specific tests for calibration separately, and assume it has already been done for the bulk of tests.

**Comment by weicaiyang** [comment]
Thanks @matutem. `+calibrate_usb_clk` works.

Looks like you and Tim have discussed the usb calibration test offline. Closing this issue now
