### ISSUE TITLE
[sw,tests,dv] Top level tests running from ROM do not build/run

### ISSUE THREAD

**Issue by davebwil** [lowRISC/opentitan#13415]
The tests that run directly from ROM rather than flash fail to run in the current build environment.
The example ROM test (chip_sw_example_rom) shows this. It also affects some top level tests for flash_ctrl.

**Comment by davebwil** [comment]
Hi @timothytrippel, we discussed this verbally but I have added an issue for visibility, thanks.

**Comment by timothytrippel** [comment]
I believe this was fixed by #13898.
