### ISSUE TITLE
[flash_ctrl/doc] clarify the access resolution limit of scramble and ecc

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#13429]
Minimum resolution in host/cotroller interface is 32 bit while flash device is 64 bit.
To mitigate this discrepancy, rtl put all f's to invalid 4byte word when 4byte aligned access
is issued from host/controller.
However, when scramble / ecc are enabled, it requires 64bit per cycle of data. So all invalid 
segment become part of scambling / ecc calulation and invalid data cannot be remained as all f's.
Therefore, user has to issue 8byte aligned access when scamble / ecc is enabled. 
We need to put this limitation on design spec.

> estimate 1

**Comment by johngt** [comment]
@vogelpi / @GregAC - I know that @GregAC has been working on related items recently and that @vogelpi is taking responsibility for flash_ctrl. Can one of you please self-assign this task.

**Comment by vogelpi** [comment]
Thanks @johngt , I'll take care of this.

**Comment by vogelpi** [comment]
I have to once more punt this. In the end it's documentation and we really have more urgent problems right now.

**Comment by vogelpi** [comment]
The PR to close this issue is here: #23974
