### ISSUE TITLE
Add a connectivity check to the test `chip_sw_entropy_src_ast_rng_req`

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#13460]
The software part of the test `chip_sw_entropy_src_ast_rng_req` is done by the PR #13456.
But a assertion based on connectivity check to verify the correctness of the received data is still required by a DV engineer.

**Comment by matutem** [comment]
I suppose we need to check the enrtropy_src entropy_src_rng_i input is tied to rng_b_o and rng_val_o outputs of the AST. Could you confirm?

**Comment by engdoreis** [comment]
@ctopal
