### ISSUE TITLE
[dvsim] Make the html root filename configurable

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#13465]
In some CI configurations, there are multiple `dvsim` invocations from a single scratch directory. Since the `email.html` report is always placed at the root of the scratch folder, it will get overwritten on each `dvsim` run. This issue is to propose to make the `email` report filename configurable, so that CI scripts can aggregate the reports.  

e.g. `--email-report-filename=invocation_foo_bar.html`

**Comment by sriyerg** [comment]
This should be fixed by PR #13730.

**Comment by tjaychen** [comment]
seems like this one can be closed! feel free to re-open if you don't agree.
