### ISSUE TITLE
[dvsim] Implement configurable URL paths in html reports

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#13463]
CI Presubmit jobs relying on dvsim html reports require the ability to support relative url links given that in some cases the URL prefix is not known in advance. 

Current URL example: 

`[AES](https://reports.opentitan.org/hw/ip/aes/lint/ascentlint/latest/results.html)`

Expected URL for CI environment:

`[AES](${BRANCH_NAME}/reports/hw/ip/aes/lint/ascentlint/${TS_FORMAT}/results.html)` 

[`TS_FORMAT`](https://cs.opensource.google/opentitan/opentitan/+/master:util/dvsim/utils.py?q=TS_FORMAT) is required because Kokoro seems to detect that latest is just a symlink to the timestamp folder, and skips the copy. 

We don't use the `--publish` flag in dvsim either, because of the same reason of not knowing the publish location in advance. 

Proposed changes: 

- [ ] Add `--stage-results-url-prefix` flag to instruct dvsim to use a different URL prefix. 
- [ ] Add `--stage-results` flag to instruct dvsim to call a method similar to `publish_results()` that stages the html results without
   calling gsutils. 
- [ ] Add FlowCfg method to generate URLs. This function should support the ability to switch from `/latest/` to `/${TS_FORMAT}/`
   folders, and should also be able to handle updates to the URL prefix.

**Comment by moidx** [comment]
Hi @sriyerg, does this make sense to you, or is there a better or easier way to achieve this? Thanks!

**Comment by weicaiyang** [comment]
@msfschaffner Is this fully addressed by your PR #14054?

**Comment by msfschaffner** [comment]
This has been addressed now, yes. Let's close it.
