### ISSUE TITLE
[rtl,clkmgr] cycle measurement trigger errors

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#13489]
If the clock measurements are disabled and then re-enabled right away we get spurious errors due to counter overflows. This can be reproduced with the chip level chip_sw_clkmgr_sleep_frequency test if the busy_wait_cycles around line 129 is commented out:

  // Wait some time for counts to clear.
  busy_spin_micros(10);

In addition, it may be good to examine the behavior of the counters when we disable any of the clocks in shallow sleep, which this test does for the three io clocks and usb.

**Comment by tjaychen** [comment]
this should be handled by #13490 
@matutem turns out I already handled the shallow sleep case (at least in theory), let me know if you observe otherwise during testing.
