### ISSUE TITLE
[bazel] cw310=lowrisc implies noudev containery flag isn't generally useful and should be renamed noudev

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#13495]
https://github.com/lowRISC/opentitan/pull/13419#discussion_r911921562 Dan has found a thing I promised to clean up and then it fell off my radar for a month and a half so here's an issue.

Lowrisc's CI doesn't allow the test-runner access to udev, so we have a method to use serial ports at specific paths in /dev in order to properly command a cw310 to conduct tests.

**Comment by msfschaffner** [comment]
CC @timothytrippel @cfrantz @redpig
