### ISSUE TITLE
[ci] check-gen runs too slowly and should be moved to slow-lint

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#13496]
This makes check-gen run too slowly to be appropriately left in quick-lint, but reordering the lints will make them fail until #13483 is merged.

_Originally posted by @drewmacrae in https://github.com/lowRISC/opentitan/issues/13482#issuecomment-1172360334_

**Comment by msfschaffner** [comment]
@cfrantz @timothytrippel is this still relevant?

**Comment by timothytrippel** [comment]
I don't think this is an issue any more. Please reopen if it is.
