### ISSUE TITLE
[hmac] D3 opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#13497]
- [ ] ~Clarify in the programming model whether the system / bus locks up when the FIFO gets full. Also mention what the guaranteed drain rate is.~
- [x] Update the MSG_FIFO description to make it more clear.
- [x] Add links to ROM driver and DIF for reference.
- [ ] Update the out-of-date constant names in the pseudo-code examples.
- [x] Update the interrupt handling section of the programmers manual.
- [x] File an issue to track the “save and restore” feature as a future enhancement.
- [x] Check whether the endianness settings can be aligned to avoid confusion by inverting the meaning of one of the two CSRs. E.g.: 1: big endian 0: little endian

**Comment by msfschaffner** [comment]
@rswarbrick @jadephilipoom @tjaychen @cindychip 
This has been transcribed from the review notes. Please correct or add more items if I missed something.

**Comment by tjaychen** [comment]
this issue on kmac save/restore is related (https://github.com/lowRISC/opentitan/issues/3479), it probably should be done for hmac also.

**Comment by eunchan** [comment]
> this issue on kmac save/restore is related (#3479), it probably should be done for hmac also.
>
And also https://github.com/lowRISC/opentitan/issues/49

**Comment by eunchan** [comment]
> Clarify in the programming model whether the system / bus locks up when the FIFO gets full. Also mention what the guaranteed drain rate is.
>
It is well described in "Performance in SHA-256 mode and HMAC mode" section.

**Comment by eunchan** [comment]
> Update the out-of-date constant names in the pseudo-code examples.
>
I don't see any old constant in the pseudo-code examples. Let me skip this

**Comment by eunchan** [comment]
> Update the interrupt handling section of the programmers manual.
>
PR is updated. **Error* section is added and **Interrupt Handling** section is removed. Other interrupts (`hmac_done` and `fifo_empty`) are well described in the register spec. So no need of recite in the doc.

**Comment by eunchan** [comment]
#13870 addresses "Check whether the endianness settings can be aligned to avoid confusion by inverting the meaning of one of the two CSRs. E.g.: 1: big endian 0: little endian"

**Comment by eunchan** [comment]
It is worth to mention that with the change #13870 , SW needs to set endian_swap to 1 and digest_swap to 0 to pour the SHA2 test vectors from NIST.

**Comment by eunchan** [comment]
HMAC has been reached to D3. Let me close this
