### ISSUE TITLE
[sw/silicon_creator] Add ePMP state checks to rom_ext.c

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#13507]
We currently cannot check ePMP states in `rom_ext.c` since we don't initialize the in-memory copy of the ePMP state.

- [ ] Either initialize the in-memory copy of the ePMP state or move it to `.static_critical`.
- [ ] Add ePMP state checks where appropriate (we typically do these before and after touching ePMP and before handing the execution over to the next stage, see `mask_rom.c`).

@moidx @cfrantz @mundaym @engdoreis

**Comment by engdoreis** [comment]
Starting to work on this issue.
