### ISSUE TITLE
[sw] End of standard support for Ubuntu 18.04 is April 2023

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#13521]
The operating system we currently use in CI (and therefore recommend) is Ubuntu 18.04 LTS. This OS is now 4 years old and standard support comes to an end in April 2023. I think we should therefore begin the process of updating CI to a newer OS.

Ubuntu 20.04 LTS is potentially a natural choice and already has good support (I daily drive this and only rarely run into issues when working on OpenTItan). I am unsure if every EDA tool we use supports it, however it has been out long enough now that I believe they most likely do. Standard support for Ubuntu 20.04 LTS comes to an end in April 2025.

Alternatively we could jump straight to Ubuntu 22.04 LTS. This would buy us an extra two years (April 2027) before we were next forced to update and would give us access to more up to date tools out of the box. I suspect we would run into problems with some EDA tools however.

Does anyone have strong opinions?

**Comment by cdgori** [comment]
I'm not sure any of the EDA tools "officially" support it:
https://www.synopsys.com/support/licensing-installation-computeplatforms/compute-platforms/compute-platforms-roadmap.html
https://www.cadence.com/content/dam/cadence-www/global/en_US/documents/support/cadence-platform-support-plan.pdf

I can't find the similar collateral for Siemens EDA/Mentor.

I have no current data to support this, but past experience has been that the EDA vendor support for Linux platforms is lagging not leading so 20.04 LTS would be more likely to work.

**Comment by marnovandermaas** [comment]
Yes, I think this is a good idea, since OpenTitan now also requires packages like GCC-9+ that are not available on Ubuntu 18.04 by default. I can have a go at converting the CI docker scripts to Ubuntu 20.04 to see if things still work well. If that doesn't go too badly then it can be discussed in the technical committee.

**Comment by mundaym** [comment]
This issue was discussed in the software working group meeting (2022-07-19). No objections were raised with regards to updating to 20.04 LTS in the near future.

**Comment by dmcardle** [comment]
Apparently, Ubuntu 18.04 will be "fully unsupported" on GitHub Actions as of 12/1/22. https://github.com/actions/runner-images/issues/6002

Has the timeline changed, or is this distinct from the support schedule on Azure Pipelines?

**Comment by marnovandermaas** [comment]
> Apparently, Ubuntu 18.04 will be "fully unsupported" on GitHub Actions as of 12/1/22. [actions/runner-images#6002](https://github.com/actions/runner-images/issues/6002)
> 
> Has the timeline changed, or is this distinct from the support schedule on Azure Pipelines?

I think this is separate from our CI tasks. The GitHub Actions workflow files all use the latest Ubuntu:
https://github.com/lowRISC/opentitan/tree/master/.github/workflows

**Comment by mundaym** [comment]
This message does seem to be appearing in our CI logs a lot, so I think we are affected:

```
##[warning]The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
```

**Comment by marnovandermaas** [comment]
> This message does seem to be appearing in our CI logs a lot, so I think we are affected:
> 
> ```
> ##[warning]The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
> ```

Ok, I will make this issue higher on my priority list then.

**Comment by marnovandermaas** [comment]
Azure seems to run GitHub Actions through this YAML file:
https://github.com/lowRISC/opentitan/blob/master/azure-pipelines.yml
My current idea is that I can bump the Ubuntu version to 20.04 in the above file and then test the change locally with:
https://github.com/nektos/act

**Comment by milesdai** [comment]
It seems like the consensus is to move to Ubuntu 20.04. From the CI side, the remaining tasks for this (please lmk if there are more):
- [ ] Transition all Azure runners to 20.04
- [ ] Transition all GCP runners to 20.04
- [ ] Update docs

**Comment by marnovandermaas** [comment]
Fixed by: https://github.com/lowRISC/opentitan/pull/14432

**Comment by marnovandermaas** [comment]
We still need to upgrade the GCP agents, so I'll reopen this issue.

**Comment by msfschaffner** [comment]
Is this still relevant?

**Comment by dmcardle** [comment]
I think this is more or less complete, but there are a few (stale) references to Ubuntu 18.04 in docs/comments.

```console
$ git rev-parse HEAD
1744c2e1e9a37bfdcec11c0d900fcce050736bc1
$ git grep -Ei 'ubuntu.?18\.04'
azure-pipelines.yml:      # The latest version of shellcheck available to ubuntu-18.04 is 0.4.6-1.
doc/guides/getting_started/src/README.md:We recommend installing the latest version of `pip` and `setuptools` (especially if on older systems such as Ubuntu 18.04) using:
doc/guides/getting_started/src/README.md:If you are using Ubuntu 18.04 then instead use:
doc/guides/getting_started/src/README.md:wget https://github.com/google/verible/releases/download/${VERIBLE_VERSION}/verible-${VERIBLE_VERSION}-Ubuntu-18.04-bionic-x86_64.tar.gz
doc/guides/getting_started/src/README.md:tar -xf verible-${VERIBLE_VERSION}-Ubuntu-18.04-bionic-x86_64.tar.gz
hw/ip/usbdev/pmod/dualpmod-kicad/dualpmod.kicad_pcb:(kicad_pcb (version 20171130) (host pcbnew 5.0.2-bee76a0~70~ubuntu18.04.1)
hw/ip/usbdev/pmod/dualpmod-kicad/dualpmod.net:    (tool "Eeschema 5.0.2-bee76a0~70~ubuntu18.04.1")
util/container/Dockerfile:        https://github.com/chipsalliance/verible/releases/download/${VERIBLE_VERSION}/verible-${VERIBLE_VERSION}-Ubuntu-18.04-bionic-x86_64.tar.gz \
util/container/README.md:Docker container based on Ubuntu 18.04 LTS containing various hardware and
```

**Comment by dmcardle** [comment]
Based on the `git grep` report above, I've created PRs for the actionable changes.

I left a few files alone:

* `doc/guides/getting_started/src/README.md` discusses how to get started on Ubuntu 18.04. I don't see any reason to remove it right now.
* `hw/ip/usbdev/pmod/dualpmod-kicad/dualpmod.*` appears to be a generated CAD file, so I see no reason to edit it by hand.

**Comment by dmcardle** [comment]
Ah, there's one more straggling reference. I think we can just delete the logic specific to Ubuntu 18.04 from `ci/install-package-dependencies.sh`.

https://github.com/lowRISC/opentitan/blob/b88730477774040577e688418291821ebcb65688/ci/install-package-dependencies.sh#L121C1-L124

**Comment by engdoreis** [comment]
Is this still relevant? @jwnrt @nbdd0121

**Comment by jwnrt** [comment]
We're not using 18.04 for any of our machines.

There are a couple of references to 18.04 left in the repo:

* [ci/install-package-dependencies.sh](https://github.com/lowRISC/opentitan/blob/39211701b5d2d8af1d52ab243b5b079bec36535f/ci/install-package-dependencies.sh#L112)
* [third_party/rust/repos.bzl](https://github.com/lowRISC/opentitan/blob/39211701b5d2d8af1d52ab243b5b079bec36535f/third_party/rust/repos.bzl#L77) (this is a very old LLVM, maybe we can update it).

These aren't really important, just cleanup.

**Comment by jwnrt** [comment]
On a related note, I think Ubuntu 20.04 is going out of standard support in one year so we might need to open another issue for that.

**Comment by jwnrt** [comment]
Superseded by https://github.com/lowRISC/opentitan/issues/24039
