### ISSUE TITLE
[fpga] Determine plan for JTAG on CW310

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#13552]
There are two mechanisms that have been explored for connecting JTAG to OpenTitan:
  - via the SAM3X (ideal for a single-cable setup)
  - via an external debugger connected to the user debug headers

PR #13464 connects JTAG up via an external debugger for now. The MPSSE emulation currently offered by the SAM3X firmware has not successfully communicated with OpenTitan's JTAG core, so there is some debugging to do.

In addition, there are some usability issues with the SAM3X as a JTAG debugger right now: With the current firmware, we cannot simultaneously use the UARTs and JTAG through the SAM3X. The SAM3X has a limited number of USB endpoints (9 for non-default endpoints altogether), and the CDC-ACM UARTs are expensive at 3 endpoints each. With the two UART interfaces and the command interface, 8 endpoints are consumed, leaving an insufficient number for an MPSSE interface.

The SAM3X firmware's naeusb creates an alternate setup (where the device actually disconnects and connects as a different device), and we're left with only the command interface, an MPSSE interface, and no UARTs.

Where do we go from here?

(First mentioned in https://github.com/lowRISC/opentitan/issues/13464#issuecomment-1172770172 )

**Comment by a-will** [comment]
Is a solution with SAM3X possible?

- On the firmware side, it's plausible to remove the CDC-ACM interrupt endpoints and replace them with an MPSSE interface.
- Alternatively, perhaps a single CDC-ACM UART could be added alongside the MPSSE interface.

However, a path to that point may be awkward. We likely would want to make use of the external debugger while things are in flux. But debugging the SAM3X path needs an FPGA image to test against. Do we build one-off images for such testing? Or attempt to do chip-level muxes so both the external and SAM3X paths are present? (Note: The JTAG signals run atop MIOs, and the top-level generation tools are ill-equipped to handle muxing ports at the chip level for MIOs.)

In addition, CI's runs have shown that the SAM3X firmware can crash under some extended sessions (possibly related to the number and timing of commands). With it potentially performing UART and SPI duties at the same time, does the firmware have too much going on to provide a solid, stable debugger experience at this point? Is pursuing the SAM3X route valuable right now?

**Comment by a-will** [comment]
CC @tjaychen @msfschaffner

**Comment by msfschaffner** [comment]
Related: #8739

**Comment by tjaychen** [comment]
"assuming" the external debug can also be handled by hyperdebug long term, it feels a bit like getting it to work harmoniously through sam3x might not be worth it.  From what i understand of our current usage, it's mostly the sca stuff using cw305 that does things exclusively through sam3x, and i don't believe they've really found a need for gdb/openocd there. (@vogelpi / @msfschaffner please correct me if i'm wrong).

**Comment by a-will** [comment]
From the silicon meeting, we've decided to proceed with the external debugger and at least push off debugging the SAM3X path. Having the SAM3X as a single-cable solution may be nice to have in the future, but at least for now, we are not planning to pursue it.

**Comment by colinoflynn** [comment]
I missed the notification this week - but approach sounds reasonable. If you have specific trouble with SAM3X ping @alex-dewar as well. But the SAM3X USB limitations remain awkward no matter how you do it because of the endpoint limitations, so if long-term hyperdebug will be an external tool I would think merging that into SAM3X may have a lot of work with minimal gain.
