### ISSUE TITLE
[dvsim] How to specifying user defined --cores-root instead of the default {proj_root}

### ISSUE THREAD

**Issue by abhishek-elastics** [lowRISC/opentitan#13566]
Currently in hw/dv/tools/dvsim/fusesoc.hjson, the cores root provided to fusesoc is fixed.

```
fusesoc_cores_root_dirs: ["--cores-root {proj_root}"]
```
Is there a way this can be updated?

**Comment by abhishek-elastics** [comment]
@sriyerg Tagging Srikrishna for visibility

**Comment by sriyerg** [comment]
This dvsim HJSON variable is a list. So you can "append" additional paths that contain sources to it in other HJSON files (for instance, your main 'DUT' HJSON file):

```json
  fusesoc_cores_root_dirs: ["--cores-root path/to/foo", "--cores-root path/to/bar"]
```

dvsim appends them all together, regardless of where the HJSON file is in the `import_cfgs` tree. 

If you want to not include the `proj_root` dir (not recommended), then dvsim supports an override mechanism (with the limitation of only one override per HJSON variable). 
```
  overrides: [
    {
        name: fusesoc_cores_root_dirs
        value: ["--cores-root path/to/foo", "--cores-root path/to/bar"]
    }
  ]
```

**Comment by abhishek-elastics** [comment]
Thank you Srikrishna! This is exactly what I was looking for and it's working as expected.
