### ISSUE TITLE
[csrng] Uninstantiate does not abort running Generate

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#13561]
When CSRNG is producing the entropy blocks requested by a Generate command, an Uninstantiate command does not abort the production of those blocks. Instead, the Uninstantiate command is pushed to the command queue, from which it will be popped only after the Generate command has completed.

This is problematic in conjunction with EDN's Boot Mode: Disabling Boot Mode, which is required to enter the cryptographically more secure Auto Mode, requires to send an Uninstantiate command. However, the reset configuration for EDN Boot Mode, which is activated by the start sequence in the Mask ROM (and the Test ROM), generates the maximum of 4095 * 128 bit of entropy on EDN0. This is a sensible choice: as the amount of entropy consumed during boot is not known a-priori, EDN0 provides as much entropy as it can in Boot Mode. However, once boot is complete, software will want to enable Auto Mode. Currently, SW has to make sure all entropy produced by the Generate command that was issued by EDN Boot Mode is consumed before it can enter Auto Mode.

I think this implies that currently
- SW has to ensure the excess entropy produced from boot is consumed before it can set up Auto Mode and start an application that needs high-quality entropy. This requires a block such as AES or OTBN to consume that entropy with dummy operations.
- Tests that rely on EDN Auto Mode take an infeasibly long time to simulate (it takes multiple hours to simulate the consumption of 4095 * 128 bit entropy blocks).

To solve this issue, should we let the Uninstantiate command abort a Generate command? Or am I missing something?

**Comment by vogelpi** [comment]
Thanks for opening this issue @andreaskurth. I think letting the Uninstantiate command abort the preceeding Generate command is the thing to do here. Fine tuning the amount of entropy delivered in boot mode (and tracking that in software somehow) or setting up dummy operation doesn't sound right to me.

@mwbranstad and @martin-lueker , do you have maybe a better alternative in mind?

**Comment by mwbranstad** [comment]
Thanks for a clear description of the problem observed. Indeed, the uninstantiate command will take effect only after the prior generate terminates. @senelson7 simulated this as the proper behavior.
The scenario to "reset" the entropy blocks operation after the initial boot phase has always been considered. It has been assumed that after boot, all entropy blocks will be "disabled" by turning off the enable field. This will terminate the current operation and return all internal logic to a known state. Then SW will re-enable by setting all of the configuration registers to "mission mode". These were the discussions with @moidx at one time, but that was a while ago so maybe the sequences have changed.

**Comment by tjaychen** [comment]
let us know if you have issues with disabling.  @mwbranstad and I have observed a few scenarios (they have been fixed) where the `disable` doesn't "stick". It would be good to know if there are others.

**Comment by andreaskurth** [comment]
Thanks for your feedback, @mwbranstad. As you described, disabling the CSRNG aborts the generate command from EDN's boot mode, and it can then be used together with EDN's auto mode. This is now implemented in #13569.
