### ISSUE TITLE
[reggen] ip_template sec_cm testplan error

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#13560]
In this PR we have an CI failure: https://github.com/lowRISC/opentitan/pull/13446
I directly edited the sec_cm_testplan to match the actual test.

I think when I use `make hw`, the sec_cm_testplan will be override to original template again.
Maybe a better solution is to auto-generate the testplan under `ip_template/alert_handler/data`, then use topgen.py to copy this file over to `top_earlgrey/ip_autogen/alert_handler/data`.

**Comment by sriyerg** [comment]
Yeah - that would be the right way to fix the CI failure.

**Comment by cindychip** [comment]
great! Thanks for confirming! PR should be out soon!
