### ISSUE TITLE
[ci] Enforcing D3 RTL Freeze

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#13581]
Do we want to introduce something to CI that would help enforce an RTL freeze for D3 IP? You can use the existing hjson to determine what IP is at D3 and then the CI check would fail if there were any changes under the `rtl/` directory for that IP. We could allow an override if the PR was labelled with something like `FreezeOverride:IpName` (there's a simple github API to get PR labels as json via http).

It wouldn't be perfect but better than an entirely manual enforcement mechanism?

**Comment by GregAC** [comment]
@msfschaffner @tjaychen I'll add this to the silicon agenda. A bit last minute but doesn't need a big discussion to start with, just a quick check to see if people favour the idea.

**Comment by GregAC** [comment]
RFC for this is here: https://docs.google.com/document/d/1hl-btL5d165U2O9Ec94ayDBFLkfju8pUrq5rYZVYZxU

**Comment by msfschaffner** [comment]
We discussed this in the TC today. The RFC has been conditionally approved, meaning that implementation and testing can proceed. However, please report back to the TC before activating this as a blocking step in CI.

**Comment by msfschaffner** [comment]
CC @alphan

**Comment by msfschaffner** [comment]
The blocker script has been implemented, hence I think we can close this (please reopen otherwise).
