### ISSUE TITLE
[spi_host/dv] post V2 items

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#13582]
- [ ] test spi enable feature. Related to https://github.com/lowRISC/opentitan/issues/5158
  - Fix the scoreboard so it can at least tolerate en_i going low without flushing the segment prediction queue. 
  - Update the testplan to say that we need to make a coverpoint in V3 that will catch en_i going low in all SPI_HOST FSM states. And implement the test.
- [ ] Integrate windbond model into the TB and test that spi_host can issue flash commands to the model correctly. Related to https://github.com/lowRISC/opentitan/issues/11292

cc: @martin-lueker

**Comment by andreaskurth** [comment]
Closing with rationale:
- Test SPI enable feature: tracked in #15076, completed in #16466.
- Integrate (Winbond) BFM: tracked in #15072 and #15073 (block-level test), so duplicate.
