### ISSUE TITLE
[kmac] should we check the PREFIX has correct function name for keymgr requesting KDF

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#13595]
We check it for SW requesting KMAC operation, and report an error with err_code.IncorrectFunctionName=1 if prefix function name isn't "KMAC", but we didn't check for HW requesting KMAC operation. Should we also do that?

cc: @tjaychen

**Comment by tjaychen** [comment]
yeah i think so. I think the prefix even in keymgr mode is controlled by by software CSR is that right?

**Comment by weicaiyang** [comment]
> yeah i think so. I think the prefix even in keymgr mode is controlled by by software CSR is that right?

yes, user needs to configure KMAC prefix before doing any keymgr operation. Currently, there is no error reported from design if the prefix is wrong.

**Comment by tjaychen** [comment]
i don't think there's a golden value for the prefix though, isn't that something software can decide on?

**Comment by weicaiyang** [comment]
To be more clear, we have this check (copied the spec to below) for SW requesting kmac operation, but this check doesn't apply to HW requesting operation.

> If [CFG.kmac_en](https://docs.opentitan.org/hw/ip/kmac/doc/index.html#Reg_cfg) is set and the SW issues the Start command, the KMAC_ERRCHK checks if the [PREFIX](https://docs.opentitan.org/hw/ip/kmac/doc/index.html#Reg_prefix) has correct function name, encode_string("KMAC"). If the value does not match to the byte form of encode_string("KMAC") (0x4341_4D4B_2001), it reports the IncorrectFunctionName error.

**Comment by tjaychen** [comment]
hmm... this is a bit tricky. 
@eunchan i think the prefix checks only apply to software initialized transactions.
But HW doesn't get the same. I think ideally we probably should check also.  For the purpose of this issue, we could just hardwire the keymgr usage to `KMAC`, we don't have to take it from the register value.

**Comment by eunchan** [comment]
> hmm... this is a bit tricky. @eunchan i think the prefix checks only apply to software initialized transactions. But HW doesn't get the same. I think ideally we probably should check also. For the purpose of this issue, we could just hardwire the keymgr usage to `KMAC`, we don't have to take it from the register value.
>
Sure, we can do that. Just changing a parameter in `kmac_pkg` is enough.

The checking @weicaiyang raises here is to check the first 6 bytes are same with `encoded_string("KMAC")` if an application interface uses KMAC operation and **PREFIX** registers rather than a parameter.

**Comment by eunchan** [comment]
@tjaychen will there be a chance that KeyMgr uses Custom String along with Function Name (`encoded_string("KMAC")`)? If an empty custom string is OK, I can modify KMAC to use hard-wired prefix for KeyMgr app intf.

**Comment by tjaychen** [comment]
@jadephilipoom 
@moidx 

Adding Jade and Miguel to comment here.
I don't personally think it's necessary. The keymgr already provides lots of routes to diversify the creation of its internal keys from KMAC.  So I don't feel like we would need more.

**Comment by jadephilipoom** [comment]
I agree, I don't see any reason why it would be necessary to use the customization string for key manager. The documentation specifies that it includes all of the diversification information as input data, and that will produce unrelated keys.

**Comment by eunchan** [comment]
OK. Let me revise the design to use hard-coded PREFIX (`encoded_string("KMAC") || encoded_string("")`) In this case the PREFIX value would be...

```
01 02 4B 4D 41 43 01 00
```

Not sure it should be `01 02 4B 4D 41 43` then padded with `00`. :( let me double check cSHAKE spec.

**Comment by cdgori** [comment]
> I agree, I don't see any reason why it would be necessary to use the customization string for key manager. The documentation specifies that it includes all of the diversification information as input data, and that will produce unrelated keys.

Replying late, but agree with @jadephilipoom so the change proposed by @eunchan is good for me.

**Comment by eunchan** [comment]
As the design change has been merged, I will close this issue.
