### ISSUE TITLE
[lc_ctrl] Device cannot scrap when transition count saturated

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#13617]
While writing a top level test I noticed that scrap transition fails when the transition count is saturated.
This is probably a corner case we did not specify very well early on.  In hindsight, scrapping is meant to be an unconditional arc, and probably should be allowed to happen even if transition count has saturated. 

An attacker can't gain "more" information by scrapping the part (or we hope).

Probably no reason to change now, but it would be nice as a future enhancement.

**Comment by msfschaffner** [comment]
Ah that is a fair point! Looks like a corner case we did not think about before...

But I agree, it's probably ok to defer this change to a future version.

**Comment by cindychip** [comment]
Yeah that is a good point! Thanks for bringing this up. I think it is a reasonable enhancement.

**Comment by msfschaffner** [comment]
@cdgori @zi-v @johannheyszl @vogelpi @moidx 
What is your view on this? It sounds like we should always be able to scrap a device, no matter whether the transition count has saturated or not...

**Comment by zi-v** [comment]
I agree. If it is a simpler change, I would consider mapping "saturated count" into scrapped state. We lose one count, but IMO better than not being able to logically scrap.

**Comment by johannheyszl** [comment]
Thx. We should definitely be able to scrap always please, agree.

re @zi-v 's suggestion: sounds like a good idea. probably not a mandatory change though if we support SCRAP transition always.

**Comment by msfschaffner** [comment]
I will check which change is easier to make.
