### ISSUE TITLE
[dv,chip] Wrong register alignment when using process_tl_access  

### ISSUE THREAD

**Issue by ariel9678** [lowRISC/opentitan#13648]
When using process_tl_access inside the scoreboard, and calling  uvm_reg_addr_t csr_addr = ral.get_word_aligned_addr(item.a_addr);
When accessing address 0x4 the ral.get_word_aligned_addr(item.a_addr) returns csr_addr=0x0 (instead of 0x4).
In chip_sim_cfg.hjson defined tl_dbw=8  because RV_DM reg is 64 bits wide, (but other CSRs are all 32-bits).

**Comment by weicaiyang** [comment]
If I remember correctly, @sriyerg already fixed this issue.

**Comment by cindychip** [comment]
@ariel9678 Do you mind helping us check if it fixed already?

**Comment by andreaskurth** [comment]
I came across this while triaging `rv_dm`. Assigning to M2.5 for now because it seems relevant for it.

@cindychip: Is this a problem with `rv_dm`, with comportable DV infrastructure, or with the top-level-specific configuration?

**Comment by cindychip** [comment]
> I came across this while triaging `rv_dm`. Assigning to M2.5 for now because it seems relevant for it.
> 
> @cindychip: Is this a problem with `rv_dm`, with comportable DV infrastructure, or with the top-level-specific configuration?

Thanks Andreas for following up on this, I was wonder the assumption that Sri already fixed it. Is there an issue or specific failure related to this?

**Comment by jonmichelson** [comment]
Removing @sriyerg and @weicaiyang since no longer on this project.
@cindychip (the only remaining assignee). Please reassign if necessary.

**Comment by andreaskurth** [comment]
> Thanks @andreaskurth for following up on this, I was wonder the assumption that Sri already fixed it. Is there an issue or specific failure related to this that I can take a look?

I don't have more information than posted here, sorry

**Comment by msfschaffner** [comment]
@jdonjdon let's double check with Nuvoton whether this is still an issue.

**Comment by msfschaffner** [comment]
Discussed with @sha-ron and decided to move to the M2.5 backlog as this does not seem to bother anyone in TLTs right now.

**Comment by msfschaffner** [comment]
CC @moidx

**Comment by msfschaffner** [comment]
This seems obsolete - closing.
