### ISSUE TITLE
[otbn] `BAD_DATA_ADDR` unknown when taking memory address from empty call stack

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#13641]
The last instruction in the `bnlid-1.s` test
https://github.com/lowRISC/opentitan/blob/0f7566f207657f39cb045ca18c97c3caef94c22c/hw/ip/otbn/dv/otbnsim/test/simple/multi/bnlid-1.s#L4-L8
intentionally raises multiple errors: a `CALL_STACK` error because the load address is taken from the call stack, which is empty, and an `ILLEGAL_INSN` error because the destination register index is greater than the number of WDRs. It *could* also raise a `BAD_DATA_ADDR` error if whatever address is popped from the empty call stack is not a valid aligned DMEM address. However, the call stack value can be unknown in simulation (the call stack storage registers have no reset, so they will be unknown in most RTL simulators until the first write), which means the `BAD_DATA_ADDR` error becomes unknown.

This is problematic because the unknown bit gets latched into the `ERR_BITS` register, which is accessible via TLUL. At the latest when this register is read via TLUL, a fatal assertion on the unknown data return value will abort simulation. (I found this problem with the `otbn_multi_err` test with seed `1765714938` on my dev branch. The root of this problem also exists on `master`, but it is not observed with this test-seed combination because the mentioned TLUL read does not happen before the `BAD_DATA_ADDR` bit is set in a subsequent test -- I did not debug this further, it might well be observable with a different seed.)

To remove this problem, I think we have to set the `BAD_DATA_ADDR` independent of the value read from the register file if the read targets the call stack and there is a call stack error. I suggest setting `BAD_DATA_ADDR` to `1` in this case, since the value read from an empty stack is, by definition, invalid and thus the address can be considered *bad*.

To catch such problems closer to the source in the future, I additionally suggest adding assert-knowns on all bits of the `ERR_BITS` register.

**Comment by andreaskurth** [comment]
What do you think, @GregAC @ctopal @vogelpi ?

**Comment by vogelpi** [comment]
Thanks for reporting this issue @andreaskurth . Both your proposals sound sensible to me. I think we should look into this after D2S.

As discussed yesterday, this behavior has been there for a while already but we didn't observe it. The modifications Andreas has been doing for D2S (removing resets from GPRs and WDR, initiating secure wipe after reset etc.) don't change the core's behavior regarding this issue but it led to uncovering it. So in my view, we don't need to fix this immediately and should prioritize reaching D2S, but then fix it afterwards.

**Comment by GregAC** [comment]
Why does that program raise a call stack error? It doesn't touch the `x1` register.

Were `BN.LID` to be reading from an empty call stack I believe it should just raise an illegal instruction error. As the instruction is illegal execution should never be attempted and thus no call stack error should occur. Were the instruction legal we'd just get a call stack error as the load would be attempted as the call stack pop would have failed. See the psuedo code at https://docs.opentitan.org/hw/ip/otbn/doc/isa/#bnlid which is the architectural definition of the instruction execution. We can alter these if we wish but I don't think it's warranted in this case. This has been the subject of long discussions in the past, I'll see if I can find anything more about this case but I'd prefer to match the ISS behaviour unless we have a strong reason not to.

**Comment by andreaskurth** [comment]
> Why does that program raise a call stack error? It doesn't touch the `x1` register.

You are right of course. I made two mistakes here: I misunderstood that the load of `bn.lid` was also indirect, and I mixed the binaries up when reading the log file (`bnlid-1` instead of `bnlid-8`). Sorry about that. I have update the description. The underlying issue is the same, though.

> Were `BN.LID` to be reading from an empty call stack I believe it should just raise an illegal instruction error. As the instruction is illegal execution should never be attempted and thus no call stack error should occur. Were the instruction legal we'd just get a call stack error as the load would be attempted as the call stack pop would have failed. See the psuedo code at https://docs.opentitan.org/hw/ip/otbn/doc/isa/#bnlid which is the architectural definition of the instruction execution. We can alter these if we wish but I don't think it's warranted in this case. This has been the subject of long discussions in the past, I'll see if I can find anything more about this case but I'd prefer to match the ISS behaviour unless we have a strong reason not to.

Why should `BN.LID` raise `ILLEGAL_INSN` when reading from an empty call stack? As far as I understand the current specification, there are two cases in which `BN.LID` would raise `ILLEGAL_INSN`: `grd` > 31 or both increments set. Am I misunderstanding it? Or do you suggest the specification should be changed?

I think the behavior w.r.t. `ILLEGAL_INSN` is according to spec, so I don't see a need for any change there. But I think we should make sure the `BAD_DATA_ADDR` register bit does not become `x`.

**Comment by GregAC** [comment]
> Why should BN.LID raise ILLEGAL_INSN when reading from an empty call stack? As far as I understand the current specification, there are two cases in which BN.LID would raise ILLEGAL_INSN: grd > 31 or both increments set. Am I misunderstanding it? Or do you suggest the specification should be changed?

I could have explained that better, I was referring to the `BN.LID` that had both increments set, so the `ILLEGAL_INSN` would take precedence over the call stack error.

> I think the behavior w.r.t. ILLEGAL_INSN is according to spec, so I don't see a need for any change there. But I think we should make sure the BAD_DATA_ADDR register bit does not become x.

Ok great
