### ISSUE TITLE
[dvsim] List CPU runtimes and longest ones in the report

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#13685]
Current regression user has to go to each individual file to find the CPU time.

Proposing supporting the following feature:
Support searching and abstracting all CPU runtimes, and list the longest ones in the report.

Proposed steps are:
1). Parse the job log file 
2). Read out tool-generated statistics representing CPU time (wall clock) and the simulated time (ns)
3). Maintain this on per job basis
4). Each DUT (sim cfg) reads out this info from each test run and creates a HJSON / XML for future purposes
5). Report needs to list 10 slowest tests 
6). Add 2 columns to the regression table in the report to represent those two times

**Comment by cindychip** [comment]
https://github.com/lowRISC/opentitan/issues/13685 duplicate issue :)

**Comment by sriyerg** [comment]
> #13756 duplicate issue :)

Whoops, sorry!
