### ISSUE TITLE
[aon_timer, rtl] Potential missed wakeup bug in aon_timer

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#13701]
https://github.com/lowRISC/opentitan/pull/7201 fixed a missed wakeup bug in aon_timer and the fix may have been undone by https://github.com/lowRISC/opentitan/pull/7701/files

Investigate and fix if needed

**Comment by msfschaffner** [comment]
I believe the answer to whether it has been undone by the fix in #7701 can be found on the corresponding review comment thread https://github.com/lowRISC/opentitan/pull/7701/files#r688059275:
> If I understand the motivation of #7201 correctly, the main issue was actually the latching of the wakeup request. I.e., previously we only latched it if we already were in sleep mode, and #7201 changed that to always latch it, not matter whether we are in sleep mode or not. This behavior should remain unchanged with this change (it just removes a redundant output flop).

So I believe we are good here and no further action is needed.

WDYT @tjaychen?

**Comment by tjaychen** [comment]
yeah this looks like it should be fine. Okay to close.
