### ISSUE TITLE
[bazel] Closed source sw build fails due to a missing file 

### ISSUE THREAD

**Issue by ariel9678** [lowRISC/opentitan#13723]
When running the following bazelisk command to build the closed source test:
**./bazelisk.sh build @manufacturer_test_hooks//:closed_chip_sw_alert_test_sim_dv --action_env=MANUFACTURER_HOOKS_DIR=/tanap1/proj_cd14/opentitan/arcohen/ast_ver_71_check_bazel/nuvoton/verification/sw/device/tests/closed_source**

We get the error below, (the baselisk command above worked fine in the past):
 
**$TEST_TMPDIR defined: output root default is '/home/users/arcohen' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
ERROR: /home/users/arcohen/_bazel_arcohen/bb82eee8a4f441bbbe3c6bbcafce7b3d/external/manufacturer_test_hooks/BUILD.bazel:169:19: no such package '@manufacturer_test_hooks//sw/host/opentitantool': BUILD file not found in directory 'sw/host/opentitantool' of external repository @manufacturer_test_hooks. Add a BUILD file to a directory to mark it as a package. and referenced by '@manufacturer_test_hooks//:closed_chip_sw_alert_test_sim_dv'
ERROR: Analysis of target '@manufacturer_test_hooks//:closed_chip_sw_alert_test_sim_dv' failed; build aborted: Analysis failed**

**Comment by timothytrippel** [comment]
This was fixed in #13786.
