### ISSUE TITLE
[adc_ctrl] Enhance adc_ctrl low power scan to automatically return to low power

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#13725]
adc_ctrl's low power could benefit a bit from smarts from scanning.
Currently, the low power scan is just a low duty cycle version of the one used in normal mode.

However, it would make more sense to make the low power scan conditions looser.  When any match is seen, it then wakes up normal scan to confirm whether there is an actual hit. If normal scan timeouts, it should then return to low power scan.

**Comment by andreaskurth** [comment]
Triaged for `adc_ctrl`. IIUC, this is a power optimization that is not required for the current release, so keeping https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease.
