### ISSUE TITLE
[dvsim] Implement wall clock timeout per test

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#13759]
This is somewhat related to #13756.

Each test specification in dvsim has the following fields: `uvm_test`, `uvm_test_seq`, `run_opts`, `sw_images`, `build_mode`. 

We could add `job_timeout` as an integer parameter to it, so that we can start maintaining a wall clock timeout for each simulation. `dvsim` will automatically kill the job if the job exceeded this timeout value.

**Comment by tjaychen** [comment]
that would be great!
