### ISSUE TITLE
[otbn] Signal completion of initial secure wipe with `done` signal

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#13753]
After #13321 is merged, OTBN will perform a secure wipe after reset. During this time, it will not handle commands. This status is exposed as `BUSY_SEC_WIPE_INT` in the `STATUS` register. After the initial secure wipe is complete, `STATUS` will become `IDLE`, but the `done` signal, which can be turned into an interrupt, is not asserted.

The rationale for the current behavior is symmetry with respect to commands: OTBN signals `done` iff it has completed a command triggered by a write to the `CMD` register.

A drawback of this behavior is that the processor controlling OTBN has to poll the `STATUS` register to wait for completion of the initial secure wipe and cannot use the `done` interrupt for that.

Are we happy with this behavior? Or should OTBN signal `done` also after the initial secure wipe? What fits the programming model better?

**Comment by GregAC** [comment]
An alternative would be to introduce a second interrupt. I just felt a single interrupt would be neater for software. There's just a single interrupt to worry about if you want to wait for OTBN to be available.

**Comment by GregAC** [comment]
I have just realised this behaviour may have an immediate impact on the mask ROM as it may not check if OTBN is idle before attempting to run a program (from a quick look at the source this appears to be the case).

@jadephilipoom @alphan any comments?

**Comment by jadephilipoom** [comment]
If [this comment](https://github.com/lowRISC/opentitan/blob/fc9528c6775c9f568a1a341e0efeab33127f588d/sw/device/silicon_creator/lib/drivers/otbn.c#L89) is accurate, then Mask ROM blocks until idle before loading applications (or writing any command) and we should be safe. However, I don't see where the blocking mentioned there actually happens! @alphan , do you know? If not, I think we should add a spin-until-idle to the `otbn_cmd_run` function.

**Comment by GregAC** [comment]
The busy wait loop in that looks to be spinning on the interrupt status rather than the OTBN status, plus the wait occurs after the command is issued and it will be ignored if OTBN is busy. I guess that's meant to be the wait until done after the command has started?

**Comment by jadephilipoom** [comment]
Ah, you're right, I misinterpreted the comment. Anyway, I think it would make sense for this routine to spin until idle both before and after the command; I'll go through the documentation again, but I don't think we would ever want to run a command starting from a non-idle state.

**Comment by alphan** [comment]
> If [this comment](https://github.com/lowRISC/opentitan/blob/fc9528c6775c9f568a1a341e0efeab33127f588d/sw/device/silicon_creator/lib/drivers/otbn.c#L89) is accurate, then Mask ROM blocks until idle before loading applications (or writing any command) and we should be safe. However, I don't see where the blocking mentioned there actually happens! @alphan , do you know? If not, I think we should add a spin-until-idle to the `otbn_cmd_run` function.

Yes, [here](https://github.com/lowRISC/opentitan/blob/fc9528c6775c9f568a1a341e0efeab33127f588d/sw/device/silicon_creator/lib/drivers/otbn.c#L110).

> I don't think we would ever want to run a command starting from a non-idle state.

Yeah, but we assume that the HW will be at the idle state. We should be able to handle this by calling `otbn_is_busy()` before using OTBN.

**Comment by mundaym** [comment]
This issue was discussed in the software working group (2022-08-02). The consensus was that the current interface is sufficient.

**Comment by andreaskurth** [comment]
Thanks for the feedback! I am closing this as *not planned*.
