### ISSUE TITLE
RFC: OpenTitan V1 Dev Stage - Sign-off Process

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#13758]
[This](https://docs.google.com/document/d/1Fpm6HvenvrUKp7v48iDXb_S4qrzQIlXxEhepnk-DAok/edit#heading=h.1qmc39dhqd9f) is the doc

**Comment by msfschaffner** [comment]
This RFC has been approved today.

**Comment by weicaiyang** [comment]
Thanks @msfschaffner
