### ISSUE TITLE
[sw] Enable ASAN and UBSAN for local unit tests

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#13754]
I'd like to enable various LLVM sanitizers for unit test binaries that run on the host.

If this goes smoothly, maybe we could also enable ASAN for test runs on CI. @milesdai WDYT?

**Comment by milesdai** [comment]
I don't see a problem with this, but I'm not sure I understand the sanitizers well enough to say for sure. I'll add some more people to #13761.
