### ISSUE TITLE
[spi_device] JEDEC ID questions

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#13783]
> The actual JEDEC ID consists of **one byte device ID and two bytes manufacturer ID**. The HW sends the device ID first, then [7:0] of manufacturer ID then [15:8] byte.

The spec says "one byte device ID and two bytes manufacturer ID", while the device ID is 2 bytes and manufacturer ID is one byte in the reg table.

15:0 | rw | 0x0 | id | Device ID
-- | -- | -- | -- | --
23:16 | rw | 0x0 | mf | Manufacturer ID

I also checked the winbond spec. Their JEDEC data consists of these bytes in order. Ours seems not aligned with them
1. one Manufacturer ID
2. 2 bytes device ID
3. one byte memory type
4. one byte Capacity

**Comment by eunchan** [comment]
Yep.. That's typo. Manufacturer ID is one byte (JEDEC ID)

**Comment by weicaiyang** [comment]
Thanks @eunchan 
This could be another typo. The size of AddrFIFO and CmdFIFO is 32B in the graphic.

https://github.com/lowRISC/opentitan/blob/aaa96c532401e30201f80d0f032f60962578f5b2/hw/ip/spi_device/data/spi_device.hjson#L1318-L1319
