### ISSUE TITLE
[prim] Add Reset Synchronizer to the library

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#13796]
For the RDC flow, it would be easier to define reset synchronizer. The logic could be same as `prim_flop_2sync` or slightly modified.

**Comment by msfschaffner** [comment]
CC @jdonjdon @tjaychen @msfschaffner

**Comment by tjaychen** [comment]
i think this is okay to close, @eunchan already added `prim_rst_sync`.
