### ISSUE TITLE
[bazel] Rework cached bitstream naming scheme

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#13807]
Currently, our cached bitstreams have names ending with `.bit.splice` and `.bit.orig`. This makes splicing into a pre-spliced bitstream tricky because Vivado's `updatemem` command only accepts bitstreams ending with `.bit` — it's trivially solved by renaming the file, but we're planning on uploading caching {test_rom, mask_rom} cross {dev, rma, etc} in #13603 and that's a bit verbose.

I propose that we define a parseable filename scheme that ends with `.bit`, to appease `updatemem`.

Instead of caching `lowrisc_systems_chip_earlgrey_cw310_0.1.bit.splice`, we could say something like `lowrisc_systems+chip=earlgrey_cw310+rom=mask+otp=dev.bit`. The parseability is important because it will make the code in [bitstreams_workspace.py](https://cs.opensource.google/opentitan/opentitan/+/master:rules/scripts/bitstreams_workspace.py;l=246;drc=13baddf15c1520df1b569acec49c540fac12d8e8) simpler.

**Comment by a-will** [comment]
Can we avoid file names with characters that must be escaped in bash, though? (i.e. avoid `=` :smile: )

**Comment by dmcardle** [comment]
Oh, I intentionally chose those characters because I thought they wouldn't cause trouble!

The script below produces the expected name (`lowrisc_systems+chip=earlgrey_cw310+rom=mask+otp=dev.bit`) and `shellcheck` seems happy.

```bash
#!/bin/bash

CHIP=earlgrey_cw310
ROM=mask
OTP=dev

filename="lowrisc_systems+chip=$CHIP+rom=$ROM+otp=$OTP.bit"

echo "Constructed filename: $filename"
```

Did I miss your point?

I'm also totally open to style suggestions — I think that replacing `+` with `:` might be easier to scan visually, e.g. `lowrisc_systems:chip=earlgrey_cw310:rom=mask:otp=dev.bit`.

**Comment by a-will** [comment]
Ah, it looks like it's bash-completion that does weird things with `=` (and `:`), but that is what makes it annoying for interactive use. Hm... I wonder if those scripts need some bug fixes...

**Comment by dmcardle** [comment]
I guess this is a dupe of #13203. I'll close the other one because we've already had some discussion here.

**Comment by dmcardle** [comment]
> Do you know if `updatemem` complains if the filename has more than one `.`? 

The `updatemem` command doesn't seem to care, as long as the filename ends with ".bit". We already give it filenames ending with "0.1.splice.bit".

> `lowrisc_systems_chip_earlgrey_cw310_0.1.mask_rom.rma.bit` would also be more consistent with other outputs that we produce during build.

I'm of two minds about the explicit tagging `a=b` style. It's easier to parse mechanically, and it gives the reader a hint about what other values might be possible. On the other hand, it's more verbose and may be harder for humans to scan visually. If other folks don't like the explicit tagging style, I don't care strongly.

> Including different OTP images in the artifacts would be convenient but we should probably have just one bitstream per life cycle state and rely on bazel (#13804) to splice different OTP images for other cases (we won't have a single RMA OTP image after adding e2e tests but we should probably make the _offical_ RMA bitstream available for convenience). WDYT?

Ah, when I filed this issue, I was imagining each OTP image would have a unique name that I could just shove into the cached bitstream's filename, e.g. `otp=dev`. If we're sure that the only OTP parameter that will vary between the cached bitstreams is the lifecycle, maybe we can just say `otp_lc=$X` instead of `otp=$OTP_NAME`.

@jon-flatley and I chatted about defining OTP images in Bazel, and we are generally positive on it, but moving away from named hjson files means we'll need to come up with an *injective* mapping from our Bazel OTP definitions to short, human-readable strings.

**Question:** How important is backwards compatibility? If we ever need to `git bisect` and want to rely on the bitstream cache, it might be painful dealing with changes to the naming scheme. (Or maybe it wouldn't be painful since the cache is tied to a commit? Check out $COMMIT and the bitstream cache code will know how to interpret the cached filenames at that exact commit hash?)

As for official RMA bitstreams, do you think they would be uploaded to the bitstream cache? If so, it seems simple enough to differentiate from the regular cached bitstreams with yet another field: `release=(official|test)`.

**Comment by a-will** [comment]
Another idea: Include a manifest.json file at the top level that describes all the files, and don't rely on file names for meaning. Such a description file could be versioned and include as many fields as we think are useful, and that could inform bitstreams_workspace.py for creation of bazel targets.

With the hyperdebug variants and future bitstreams and integrations, a description file might be more scalable than file names.

**Comment by alphan** [comment]
> Another idea: Include a manifest.json file at the top level that describes all the files, and don't rely on file names for meaning. Such a description file could be versioned and include as many fields as we think are useful, and that could inform bitstreams_workspace.py for creation of bazel targets.
> 
> With the hyperdebug variants and future bitstreams and integrations, a description file might be more scalable than file names.

SGTM. If we go with this approach, I'd probably prefer a _mechanical_ name for the files (uuid, sha256, etc.) so that we don't solve the same problem twice, i.e. (1) for the contents of the JSON file and (2) for the names of the actual files. Manual debugging will require looking at the JSON but that will be the source of truth anyway. WDYT?

**Comment by a-will** [comment]
> > Another idea: Include a manifest.json file at the top level that describes all the files, and don't rely on file names for meaning. Such a description file could be versioned and include as many fields as we think are useful, and that could inform bitstreams_workspace.py for creation of bazel targets.
> > With the hyperdebug variants and future bitstreams and integrations, a description file might be more scalable than file names.
> 
> SGTM. If we go with this approach, I'd probably prefer a _mechanical_ name for the files (uuid, sha256, etc.) so that we don't solve the same problem twice, i.e. (1) for the contents of the JSON file and (2) for the names of the actual files. Manual debugging will require looking at the JSON but that will be the source of truth anyway. WDYT?

That's probably fine, but maybe let's put the files that share a "core" in the same folder (and name the folder after either the VLNV or a possibly-mangled bazel target name). Then the directory structure won't be totally opaque. bitstreams_workspace.py shouldn't care about the paths in any case, since it'll get what it needs from the manifest, but the grouping is a bit more human-friendly than a bunch of `<hexadecimal>.<extension>` files in a flat directory. ;)

Does that sound good?

**Comment by alphan** [comment]
SGTM.

> , but the grouping is a bit more human-friendly than a bunch of <hexadecimal>.<extension> files in a flat directory. ;)

I was actually hoping for <hex> (no ext) hehe just to forget about the names.

I should probably give more context for my preference for including some sort of a hash in the name: IIRC this is the recommended naming scheme for better sharding and therefore performance. See [here](https://cloud.google.com/blog/products/gcp/optimizing-your-cloud-storage-performance-google-cloud-performance-atlas#:~:text=Avoid%20the%20sequential%20naming%20bottleneck).

**Comment by a-will** [comment]
> SGTM.
> 
> > , but the grouping is a bit more human-friendly than a bunch of . files in a flat directory. ;)
> 
> I was actually hoping for just `<hex>` (no extension, hehe) just to forget about the names.
> 
> I should probably give more context for my preference for including some sort of a hash in the name: This is the recommended naming scheme for improved sharding and performance. See [here](https://cloud.google.com/blog/products/gcp/optimizing-your-cloud-storage-performance-google-cloud-performance-atlas#:~:text=Avoid%20the%20sequential%20naming%20bottleneck).

Eliminating the extension isn't necessary for that, though. It'd be nice if we don't totally require looking at the json to make sense of files--That's not very friendly when we need to look at the files and debug the scripts, right?

```
For example, prepending a uniformly distributed hash (over a fixed range) to the filenames breaks the linearity and allows the load balancers to do a better job at partitioning the connections.
```

It only asks for "prepending a... hash" :)

**Comment by alphan** [comment]
> > SGTM.
> > > , but the grouping is a bit more human-friendly than a bunch of . files in a flat directory. ;)
> > 
> > 
> > I was actually hoping for just `<hex>` (no extension, hehe) just to forget about the names.
> > I should probably give more context for my preference for including some sort of a hash in the name: This is the recommended naming scheme for improved sharding and performance. See [here](https://cloud.google.com/blog/products/gcp/optimizing-your-cloud-storage-performance-google-cloud-performance-atlas#:~:text=Avoid%20the%20sequential%20naming%20bottleneck).
> 
> Eliminating the extension isn't necessary for that, though. It'd be nice if we don't totally require looking at the json to make sense of files--That's not very friendly when we need to look at the files and debug the scripts, right?
> 
> ```
> For example, prepending a uniformly distributed hash (over a fixed range) to the filenames breaks the linearity and allows the load balancers to do a better job at partitioning the connections.
> ```
> 
> It only asks for "prepending a... hash" :)

I didn't say that the guidance asks for a hash-only filename (hence I said "including"), using only a hash is just my preference for naming given that we are considering having a JSON file (single source of truth). I have a feeling that naming files according to some format (either with some directory structure, or longer names) will end up being similar to what the JSON file is trying to accomplish so we may want to go back to encoding things in the filename. This of course depends on how many files we expect per job. This probably deserves a doc, maybe a one-pager.

**Comment by dmcardle** [comment]
I'll throw in that updatemem is quite opinionated and refuses to believe a file is a bitstream unless it ends with `.bit`.

I agree that this probably deserves a design doc given that it simultaneously touches the `@bitstream` workspace, CI, and Bazel!
