### ISSUE TITLE
[CDC][SPI_DEVICE] W_MASYNC errors which come from IO PAD 

### ISSUE THREAD

**Issue by jeoongp** [lowRISC/opentitan#13806]
SPI Input PAD is XORed with u_pinmux_aon.dio_pad_attr_q.invert driven by io_div4_clk.

 assign.in_o.=.attr_i.invert.^.in_raw_o;

![Screen Shot 2022-07-22 at 9 59 02 AM](https://user-images.githubusercontent.com/103145460/180488290-2eaa2816-4e8c-4c21-b275-b038d75547b2.png)

Then, this W_MASYNC is propagated to readcmd/u_readsram.u_sram_fifo. 
![Screen Shot 2022-07-22 at 10 00 36 AM](https://user-images.githubusercontent.com/103145460/180488538-906da8b4-4e78-4897-91d5-20b2c2a3092c.png)

Just want to make sure if these errors can be waived.

**Comment by tjaychen** [comment]
yes I believe this one should be okay.
The attribute bits should definitely be semi-static. It should be something we determine very early in the operation of the device.

@msfschaffner do you agree?

**Comment by tjaychen** [comment]
@jeoongp instead of waivers, is there a way to set a signal as static in verixcdc land?

**Comment by jeoongp** [comment]
@tjaychen yes we can use set_stable_value.

**Comment by msfschaffner** [comment]
Yeah I can confirm that this is a semi-static signal. Should be ok to use `set_stable_value`.

**Comment by tjaychen** [comment]
if the waiver / constraint change was merged, let's close this one as well.

**Comment by tjaychen** [comment]
@jeoongp i'm sure you're doing this already, but for the things that are waived or set as semi-static etc, could you just add a comment explaining why? You could even link to these issues where the full rationale was explained.

**Comment by jeoongp** [comment]
This semi-static signal was already waived by another waiver.

set_rule_status -rule {W_MASYNC} -status {Waived}        \
  -expression {(Driver=~"*u_pinmux_aon.dio_pad_attr_*")} \
  -comment {PAD Attributes are static signals.}

These errors somehow showed up as a tool glitch but are not shown anymore now.
I've added a comment and this issue # in https://github.com/lowRISC/opentitan/pull/13739.
