### ISSUE TITLE
[spi_device] TPM read/write frequency and TPM FIFO size

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#13816]
For TPM read, host sends a CMD with an address to request data. SPI device starts to return data once it receives one byte of data from SW. But SPI device may send faster than SW input. If that's the case, host will receive 0 instead.

The TPM fifo is only 4 bytes. TPM could support up to 64 bytes data per transaction. If our use case may support more than 4 bytes, we need SW to keep polling the FIFO available depth and provide data in time.

Similar to TPM Write, if host may send more than 4 bytes per transaction, SW needs to read faster enough since the FIFO size for write data is also 4 bytes.

Will be great if we can check what the real use cases we may have for TPM mode.

cc: @tjaychen

**Comment by tjaychen** [comment]
I think @eunchan and I actually had this discussion before (somewhere in the PR), and I thought Eunchan's conclusion was that 4B was sufficient for what we knew.

Is that right Eunchan?

Although looking at this again, it might make sense to future proof a bit, I completely forgot until now that it is possible for people to re-use the TPM interface for other purposes, and for those they may indeed go beyond 4B.

**Comment by tjaychen** [comment]
see [here](https://screenshot.googleplex.com/9JxqtVCRPpqRRY4)

**Comment by eunchan** [comment]
> I thought Eunchan's conclusion was that 4B was sufficient for what we knew.
>
Yes. It is as of now. But the TPM protocol supports up to 64B max transfer size.

>  I completely forgot until now that it is possible for people to re-use the TPM interface for other purposes, and for those they may indeed go beyond 4B.
>
I remember others wanted to re-use TPM to receive more than 4B for other purposes (e.g: firmware download). I nudged them to use the generic mode in that case.

anyhow, As the FIFO width is one byte, I think SW struggles a little bit to keep it up to speed if SYS_CLK is much slower than TPM clock speed.
What I want to confirm from SW folks is the upper limitation of the TPM speed. As I know TPM frequency is much slower than normal SPI frequency.

**Comment by tjaychen** [comment]
i'll confirm with the Nuvoton folks, but I believe the TPM interface is "usually" 1.8v, which means ~24MHz or so is our top speed. 
It would be nice to future proof this area a little bit, just in case someone comes with a creative usage.

The TPM interface is kind of nice for host -> device communication because it has built in back-pressure, which the spi-flash interface does not have.

**Comment by eunchan** [comment]
I will revise SPI_TPM design to make 64B support easier:

- Increase WrFIFO to 64B (Additional 480-bit FF) It will cover the full TPM transaction.
- Widen the RdFIFO to 32-bit (full word) and increase the size to 16B (96-bit): If the FIFO is wide enough, SW has enough time to keep up the TPM CLK. (32-to-1 ratio)

Total 576-bit (~4.8k gates) will be increased. It is complex to widen the WrFIFO width to 32-bit. So, it could be a future enhancement.

**Comment by eunchan** [comment]
As the changes have been merged, let me close this issue. Please re-open if hit the same issue.

**Comment by weicaiyang** [comment]
Thanks @eunchan

**Comment by andreaskurth** [comment]
> I will revise SPI_TPM design to make 64B support easier:

For reference, the PRs are:

>     * Increase WrFIFO to 64B (Additional 480-bit FF) It will cover the full TPM transaction.

[[spi_device] Increase TPM Write FIFO to 64B (#14000)](https://github.com/lowRISC/opentitan/pull/14000)

>     * Widen the RdFIFO to 32-bit (full word) and increase the size to 16B (96-bit): If the FIFO is wide enough, SW has enough time to keep up the TPM CLK. (32-to-1 ratio)

[[spi_device] 4B wide TPM Read FIFO (#14016)](https://github.com/lowRISC/opentitan/pull/14016)
