### ISSUE TITLE
[entropy_src] prim_cntr failing assertions

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#13820]
The entropy_src core has a number of instances of `prim_count` in which it seems to use the `clr_i` and `set_i` assertions interchangeably, where the `set_cnt_i` value is set to '0.  This is a problem if a scenario is encountered where `clr_i` and `set_i` ports are asserted simultaneously.  

In this case the DUT fails on an assertion check, as `prim_count` does not allow the counters to be set and cleared simultaneously.

To reproduce this bug checkout branch `failing_SimClrSet_A` from [my fork](https://github.com/martin-lueker/opentitan/) and run the command: 

```
util/dvsim/dvsim.py hw/ip/entropy_src/dv/entropy_src_sim_cfg.hjson -i entropy_src_rng -r 1 -s 2116647549 --job-prefix="nc run -C ncsim_interactive -Il" --run-modes set_verbosity_comp_a_uvm_debug set_verbosity_comp_b_uvm_debug short_run
```

**Comment by msfschaffner** [comment]
Just a quick heads up that we are re-structuring that counter primitive in https://github.com/lowRISC/opentitan/pull/13591.
The assertion should not fail anymore after that has landed.

**Comment by martin-lueker** [comment]
Ah!  And here I already made a fix. 

Still it is confusing that both clear and set are used interchangeably isn't it?

**Comment by msfschaffner** [comment]
Yeah the assertions are going to be updated in the new version.

In the mean time, if you need to make progress locally, it probably makes sense to just apply your fix or comment out the SVA.

**Comment by martin-lueker** [comment]
So, no need to PR it then? Alright, will I'll just set the fix aside then when I'm done

**Comment by msfschaffner** [comment]
Yeah that should be fine.
