### ISSUE TITLE
[test, ibex] Unable to disable address translation

### ISSUE THREAD

**Issue by HU90m** [lowRISC/opentitan#13848]
Found when writing a chip level test for address translation (https://github.com/lowRISC/opentitan/issues/13215) that the address translation would never be disabled.

Writing 0 to the enable registers (e.g. [RV_CORE_IBEX.DBUS_ADDR_EN_0](https://docs.opentitan.org/hw/ip/rv_core_ibex/doc/index.html#Reg_dbus_addr_en_0)) seems to have no effect. I have checked that at no point the write protection registers (e.g. [RV_CORE_IBEX.DBUS_REGWEN_1](https://docs.opentitan.org/hw/ip/rv_core_ibex/doc/index.html#Reg_dbus_regwen_0)) are active, i.e. the write protection should not be prohibiting writing at any point.

To reproduce, clone https://github.com/HU90m/opentitan/tree/rv_core_ibex_address_translation_with_disable and run the `//sw/device/tests:rv_core_ibex_address_translation_test` chip level test.

To run using verilator, I used the following commands.

```sh
./bazelisk.sh build //sw/device/tests:rv_core_ibex_address_translation_test
bazel-out/k8-fastbuild/bin/sw/device/tests/rv_core_ibex_address_translation_test_sim_verilator.runfiles/lowrisc_opentitan/hw/build.verilator_real/sim-verilator/Vchip_sim_tb --meminit=otp,bazel-out/k8-fastbuild/bin/sw/device/tests/rv_core_ibex_address_translation_test_sim_verilator.runfiles/lowrisc_opentitan/hw/ip/otp_ctrl/data/img_rma.24.vmem --meminit=rom,bazel-out/k8-fastbuild/bin/sw/device/tests/rv_core_ibex_address_translation_test_sim_verilator.runfiles/lowrisc_opentitan/sw/device/lib/testing/test_rom/test_rom_sim_verilator.scr.39.vmem --meminit=flash,bazel-out/k8-fastbuild/bin/sw/device/tests/rv_core_ibex_address_translation_test_sim_verilator.runfiles/lowrisc_opentitan/sw/device/tests/rv_core_ibex_address_translation_test_prog_sim_verilator.64.scr.vmem
```

The test expects to get an access fault once the address translation is disabled. No such fault is encountered, so the test fails.

See lines 229 to 248 of `sw/device/tests/rv_core_ibex_address_translation_test.c`.

**Comment by tjaychen** [comment]
looks like the issue is here

```  // Disable all address translation.
  for (size_t slot_i; slot_i < 2; ++slot_i) {
    for (size_t bus_i; bus_i < 2; ++bus_i) {
      CHECK_DIF_OK(dif_rv_core_ibex_disable_addr_translation(
          &ibex_core, kSlots[slot_i], kBuses[bus_i]));
    }
  }```

since the `slot_i` and `bus_i` variables aren't initialized, it seems like code is just optimized out.
In my local disassembly i dont even see the disable functions. Once i add back a 0, everything appears to be fine.

**Comment by HU90m** [comment]
Well that's embarrassing.

Thank you @tjaychen! And sorry for wasting your time.

(I'll just check that's the only problem before closing this.)

**Comment by tjaychen** [comment]
no worries, happy to help.

**Comment by tjaychen** [comment]
btw, i still don't know why having no initial values didn't just cause a break during compilation... it feels like to me it should have..hopefully there's a flag we can turn on somewhere.
