### ISSUE TITLE
[util] Removing mypy tool

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#13841]
Currently, a few python scripts are [being checked by mypy in CI](https://cs.opensource.google/opentitan/opentitan/+/master:ci/scripts/mypy.sh;l=1?q=mypy.sh).

Unless `mypy` becomes mandatory type checker in OpenTitan project, this confuses contributors. For instance, importing 3rd party library may or may not cause errors depending on which python file the contributor revises.

**Comment by GregAC** [comment]
mypy is utilised extensively within the OTBN python tooling where the type checking it provides is valuable. I would strongly prefer we continue to run those checks in CI.

**Comment by msfschaffner** [comment]
CC @rswarbrick 

Are we ok closing this issue for now?
It seems like we'd want to keep the mypy checks in place.

**Comment by mundaym** [comment]
Yes, let's close this.
