### ISSUE TITLE
[opentitantool] Complete support for OTP tooling

### ISSUE THREAD

**Issue by jon-flatley** [lowRISC/opentitan#13869]
The directory `util/design` currently holds a number of python tools for working with OTP memory maps. These tools are responsible for generating OTP images for preloading onto a device as well as generating the documentation tables in `hw/ip/otp_ctrl`. This bug will serve as a tracker as the OTP tools in opentitantool move towards feature parity with their python counterparts, as well as track the progress of additional features unique to  the opentitantool implementation.

### General Support

- [x] Hardware cipher support 
- [x] ECC support
- [ ] HJSON serialization / deserialization. This is made a bit more complicated due to how the HJSON config files are structured. Many fields use strings to wrap hex constants (since (H)JSON doesn't support hex literals), and there are certain meta fields that need to be handled differently, such as `val: "<random>"`
- [ ] Life cycle state configuration support
- [ ] Add support for the CRC32 checks in alert_handler register configuration as described in #14038 
- [ ] Add support for named constants in config files

### Image Generation

- [x] Generate image binary from `otp_ctrl_mmap.hjson` and `otp_ctrl_img_dev.hjson`
- [x] Add support for emitting mem files that can be spliced into bitstreams / loaded into simulations
- [ ] Add support for image deserialization for reading existing OTP images

### Documentation

- [ ] Generate OTP documentation

### Integration

- [ ] Complete bazel transition to invoke opentitantool rather than `gen-otp-*.py`
- [ ] Look into writing a bazel rule for specifying OTP configuration

**Comment by msfschaffner** [comment]
Moving to M3 as the remaining work is not blocking P1 M2 test cases.

**Comment by jon-flatley** [comment]
Migrated to #14808
