### ISSUE TITLE
profiling bazel compile time

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#13891]
Found bazel run takes about 9~10 minutes of 14 minutes of the total simulation run time.

INFO: Elapsed time: 444.182s, Critical Path: 286.44s
...
INFO: Elapsed time: 126.192s, Critical Path: 102.18s

This is run.log before any vcs activity starts.
Please review bazel compile process to see if there is anything that can be improved this.

**Comment by jdonjdon** [comment]
It is for @timothytrippel , I added others just for the reference.

**Comment by tjaychen** [comment]
hmmm that seems really long. When I run it locally or on the airgapped setups I don't recall it taking that long..
It could be that since i'm using the airgapped setup none of the dependencies need to be resolved

**Comment by timothytrippel** [comment]
IIUC, @jdonjdon this only occured for you on the airgapped setup correct? and for more context, what do those above build times correspond to? I assume one is the test ROM? and the other is a chip-level test you were trying to build? Do you know what the build times for each are on your workstation?

**Comment by jdonjdon** [comment]
> IIUC, @jdonjdon this only occured for you on the airgapped setup correct? and for more context, what do those above build times correspond to? I assume one is the test ROM? and the other is a chip-level test you were trying to build? Do you know what the build times for each are on your workstation?

Let me put the log file here(#13929) you can grep 'Elapsed time' to get the same out and
the context where the output is created.

**Comment by jdonjdon** [comment]
With the latest update, I don't see this issue anymore.
Close for now.
