### ISSUE TITLE
 [otbn/sca] Follow-up tasks to adding capture support

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#13905]
With #13845 @bilgiday is adding initial support for OTBN SCA captures. The idea of this issue is to track follow-up tasks.

- [x] Remove URND reseed at application start and add a `Sec` parameter to add a deterministic and constant delay the start trigger. This gives Ibex time to go to sleep before the capture is started. This will allows us to better distinguish the start of OTBN. Note, unlike for AES (short execution time) and KMAC (Ibex needs to feed message after triggering start) this is not that important for OTBN as OTBN usually starts by reseeding URND which is not interesting from an SCA perspective. See #17223
- [x] Disable auto-advancing of URND during execution on FPGA, only advance it if the current value is read. This should help to reduce noise during pre-silicon SCA. See #17195
- [ ] Implement hardware support for skipping/deterministic RND/URND reseeds. This 1) avoids the need for dedicated assembly apps where reads from RND/URND are skipped, and 2) it leads to fully deterministic execution times which simplifies the analysis side. By enabling these changes only if a `Sec` parameter is used, we can ensure this "feature" isn't enabled on the ASIC. See for example the `Sec` parameters inside AES and KMAC.

Feels free to edit and extend this.

**Comment by bilgiday** [comment]
Thanks @vogelpi :) I will update the list if needed

**Comment by msfschaffner** [comment]
@vogelpi @bilgiday is this something that we need in ES silicon? If so, we should get this in for M2.

**Comment by vogelpi** [comment]
It would be great to do more FPGA experiments before ES but the focus of various people including @bilgiday and @vrozic has now shifted to other tasks more critical for M2. So this is not going to happen before M2.

In general, the changes suggested in this issue would only matter for FPGA anyway, similar to what we do for AES and KMAC. We will have to figure out the process of making FPGA-only RTL changes post RTL freeze but it's better not to do this right now and focus on M2 instead.

**Comment by vogelpi** [comment]
Update: the first two and most important items have been implemented by @vrozic , I've linked the corresponding PRs. The third one is not really required and it's easy to work around that by changing the binary. I am now closing this issue.
