### ISSUE TITLE
[dvsim] How to pass --flag=<xyz> to fusesoc? 

### ISSUE THREAD

**Issue by abhishek-elastics** [lowRISC/opentitan#13924]
From my understanding of dvsim.py, I don't see a straight forward way of providing --flag=<xyz> to fusesoc. Can you help me in figuring out how to do that?

@sriyerg

**Comment by sriyerg** [comment]
See: 
https://github.com/lowRISC/opentitan/blob/880d289d97d1ecced9a3b9af9e2c3100e10a97c5/hw/dv/tools/dvsim/fusesoc.hjson#L16

The `sv_flist_gen_flags` is a list, to which new flags can be appended to from any hjson config in the import tree. This list gets expanded into `sv_flist_gen_opts` which is the list of command-line switches passed to `fusesoc`. Please try adding this in your DUT hjson entry:
```
  sv_flist_gen_flags: ["--flag=<my_flag>"]
```

**Comment by abhishek-elastics** [comment]
Thank you Sri for the pointer. I did notice that list but I want to be able to pass an argument via command line to dvsim to update that list. How do I do that?

**Comment by abhishek-elastics** [comment]
One option that I thought could work is to make use of --select-cfgs. Create a hjson file which imports the primary hjson file and add the specific sv_flist_gen_flag to it. But looks like --select-cfgs only accepts primary hjson files. So may be I need to create multiple primary config hjson files each containing the specific sv_flist_gen_flags that I want to pass. That's a lot of code to be duplicated in each of the primary hjson files.

**Comment by sriyerg** [comment]
Dvsim command line update of individual hjson variables is not supported. If you could explain your usecase, maybe I can help better. Seems like you have a DUT configuration, but you need an alternate DUT configuration that has a different set of fusesoc flags enabled, but reuse all existing tests? You can do something like this:
```
// chip_sim_cfg.hjson
<put your usual stuff> 
```

```
// chip_alt_sim_cfg.hjson (this won't be a primary cfg)
{
  // Import the vanilla chip sim cfg to leverage the original settings. 
  import_cfgs: ["path/to/chip_sim_cfg.hjson"]

  // Extend the sv_flist_gen_flags for this cfg with additional flags. 
  // Note that this will ADD new flags to the ones already set in the
  // imported hjson cfgs tree.
  sv_flist_gen_flags: ["--flag=<my_flag>"]

  // OR 

  // If you want to purge the previous fusesoc flags completely and
  // add a new set of flags, do it as an override. 
  overrides: [
    {
      name: sv_flist_gen_flags
      value: ["--flag=<my_flag1>", "--flag=<my_flag2>"]
    }
  ]

  // You can add new build_opts or even test specifications that 
  // only pertain to this configuration. 
  build_opts: ["+define+FOO"]
  
  tests: [
    ...
  ]
}
```

Yes you can then pass `chip_alt_sim_cfg.hjson` as input to dvsim as usual.

**Comment by abhishek-elastics** [comment]
Ah! this is exactly what I needed. I, for some reason, was trying to forcefully use --select-cfg

```
dvsim.py chip_sim_cfg.hjson -i sanity --select-cfgs chip_alt_sim_cfg.hjson
```

Thank you Sri for the quick reply! using alt_sim_cfg did the trick
