### ISSUE TITLE
[spi_device] Assertion update needed

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#13934]
This assume doesn't work for mailbox read, when it reads across mailbox boundary.
```
  // intercept_en shall not be de-asserted except reset
   `ASSUME(InterceptLevel_M,
     $rose(intercept_en) |=> $stable(intercept_en) until !rst_spi_n,
     clk_spi_out_buf, !rst_spi_n)
```

Sounds like it's ok to issue a transaction that sends over 4k bits (512 bytes)
```
  // Bitcnd shall not exceed 2**12
   `ASSERT(BitcountOverflow_A, bitcnt != '1)
```

**Comment by eunchan** [comment]
Both fixes have been merged. Let me close the issue. Thanks for the report!

**Comment by weicaiyang** [comment]
@eunchan 
reopen this, as the intercept assertion may need some more tuning. 

intercept.status, intercept.jedec, intercept.sfdp raises 1 cycles earlier than `intercept_en`. `intercept_en` 
and ` $stable(intercept_en)` means ` $past(intercept_en) == intercept_en`


adding `##1` can fix it
```
  `ASSUME(InterceptLevel_M,
    $rose(|{intercept.status, intercept.jedec, intercept.sfdp}) |=> ##1
      $stable(intercept_en) until !rst_spi_n,
    clk_spi_out_buf, !rst_spi_n)
```

![Screen Shot 2022-08-08 at 2 13 54 PM](https://user-images.githubusercontent.com/49293026/183515948-678a9499-7734-4951-951c-a0614efcc2d3.png)

/mnt/disks/filestores/opentitan-shared/users/weicai/scratch/spi_upload/spi_device-sim-vcs/0.spi_device_pass_all/out
verdi -ssr Verdi.ses
