### ISSUE TITLE
[dvsim] How to enable the rerun feature?

### ISSUE THREAD

**Issue by abhishek-elastics** [lowRISC/opentitan#13951]
I see that there is a flag "--no-rerun" with the following description

    rung.add_argument("--no-rerun",
                      action='store_true',
                      help=("Disable the default behaviour, where failing "
                            "tests are automatically rerun with waves "
                            "enabled."))

I'm not seeing the default behavior of the tests being rerun with waves when failing. How do I enable the rerun feature?
@sriyerg

**Comment by sriyerg** [comment]
The auto-rerun on failure feature does not exist (and there is no ETA on its enablement at this time). This switch is a stub for future enhancement. Please rerun failures with waves manually.

**Comment by abhishek-elastics** [comment]
Gotcha! Thanks.
