### ISSUE TITLE
[entropy_src] question on window count

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#13959]
This came up while I was debugging a test.
Basically, the test incorrectly set the window_count to '0' instead of a sensible value. 

This created a situation where the healthtest stuff was basically constantly bypassed.  I just wanted to double check that this is intended behavior and it's something software could do to effectively bypass the health tests.  Because if so, the software probably should pay extra attention to these counts.

**Comment by tjaychen** [comment]
@johannheyszl 
@moidx 
@timothytrippel

**Comment by mwbranstad** [comment]
The answer is that this was not intended way to bypass health tests. At one time, there were explicit control bits to disable each test on an individual basis, but these were removed. Instead, it was deeded that the threshold values for a certain test would be increased to a very large value that, in effect, the test would be disabled.
This seems like a basic programming error. There are too many registers in ES to know how all values and combinations will work with each other.
One other note: the rep count test does not rely on a window, so this test should never be disabled.

**Comment by tjaychen** [comment]
sounds good. I should say that it wasn't exactly disabled, the logic just behaved like it was always working constantly. 
But that sounds good, I just wanted to double check.  This is probably something software needs to pay extra attention.
