### ISSUE TITLE
[ibex, sw] Clarification of ePMP behaviour

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#13958]
I wish to draw attention to the following rules in the Smepmp specification (https://github.com/riscv/riscv-tee/blob/main/Smepmp/Smepmp.pdf)

When `mseccfg.MML` is set:

> Adding a rule with executable privileges that either is M-mode-only or a locked Shared-Region is not possible and such pmpcfg writes are ignored, leaving pmpcfg unchanged. This restriction can be temporarily lifted e.g. during the boot process, by setting mseccfg.RLB.

> Executing code with Machine mode privileges is only possible from memory regions with a matching M-mode-only rule or a locked Shared-Region rule with executable privileges. Executing code from a region without a matching rule or with a matching S/U-mode-only rule is denied.

These behaviors are not yet implemented in Ibex, an oversight on my part when I did the original implementation, see Ibex issues: https://github.com/lowRISC/ibex/issues/1740 and https://github.com/lowRISC/ibex/issues/1736

This was specified in the original draft spec we based our initial ePMP discussions around so people may already be aware but I wanted to flag them up in case others made the same mistake I did.

I think the major takeaway is once you've cleared 'mseccfg.RLB' you need to have all the executable regions you want for M mode set up with no future need for more. 

@alphan @cfrantz @mundaym please take note.

**Comment by msfschaffner** [comment]
This has been addressed already.
