### ISSUE TITLE
[otbn, dv] Add testcase to verify OTBN.LOOP_STACK.ADDR.INTEGRITY

### ISSUE THREAD

**Issue by prajwalaputtappa** [lowRISC/opentitan#13961]
Original effort estimate: 32
> estimate 16
> remaining 2022-08-30 2

**Comment by prajwalaputtappa** [comment]
Things to do in the testcase:
1. Wait for top_valid_o to be asserted. 
2. Wait for a reasonable random number of clocks. 
3. Check if the top_valid_o is still asserted. 
4. If yes, read the value of stack_wr_idx. 
5. Corrupt the data in stack_storage at the stack_wr_idx value. 
6. Wait for a pop. 
7. Expect a fatal alert from otbn.

**Comment by ctopal** [comment]
Closed with https://github.com/lowRISC/opentitan/pull/14656

> remaining 2022-09-13 0
