### ISSUE TITLE
[otbn, dv] Verify OTBN.DATA.MEM.SW_NOACCESS

### ISSUE THREAD

**Issue by prajwalaputtappa** [lowRISC/opentitan#13965]
Figure out what needs to be done for verifying OTBN.DATA.MEM.SW_NOACCESS and add necessary checks and TC. 
Original effort estimate:
> estimate 8
> remaining 2022-08-12 2

**Comment by johngt** [comment]
Issue some r/w to areas of DMEM that IBex side of interface not able to access.
Address range needed from @GregAC

**Comment by prajwalaputtappa** [comment]
Waiting for https://github.com/lowRISC/opentitan/pull/14242 to be merged

**Comment by GregAC** [comment]
Closing as #14242 has been merged
