### ISSUE TITLE
[otp/testing] device_id being set randomly makes testing difficult

### ISSUE THREAD

**Issue by milesdai** [lowRISC/opentitan#13960]
I'm working on writing a test that ensures the MaskROM is checking the manifest usage constraints correctly against the hardware. This involves toggling the 4 selector bits in the manifest and testing each of the constraints. One of these usage constraints is the DEVICE_ID which is currently being set randomly in the OTP (e.g. https://github.com/lowRISC/opentitan/blob/master/hw/ip/otp_ctrl/data/otp_ctrl_img_rma.hjson#L268). This makes testing it somewhat difficult. Can this value be set to a constant?

**Comment by milesdai** [comment]
@cfrantz @msfschaffner

**Comment by sriyerg** [comment]
> yeah i dont see why not. For DV purposes, we have other ways of overriding this to be a random value for our purposes.
> 
> @cindychip @sriyerg

Fine with me - though lets keep this open until we re-randomize it in DV.

**Comment by msfschaffner** [comment]
@milesdai is this addressed? can we close the issue?

**Comment by milesdai** [comment]
Not yet -- I'm returning to this test soon and will deal with this issue then.

**Comment by msfschaffner** [comment]
Ok sounds good, thanks!

**Comment by milesdai** [comment]
This problem is solved by creating an overlay that overwrites the the device ID in Bazel.
