### ISSUE TITLE
Automate early manufacturing steps to execute programs from SRAM

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#13968]
In early manufacturing, we won't be read or write to flash yet. We need to define the steps to copy a program into SRAM and execute it.

PR #13383 adds an example SRAM program: `sw/device/examples/sram_program/sram_program.c`.

We need some machinery (Bazel, shell script, and/or opentitantool command?) to spin up Verilator or VCS, start OpenOCD, and then attach GDB. Then, we can use GDB commands to copy the program binary and eventually jump to it. 

@alphan has started this ([design doc](https://docs.google.com/document/d/1i6V3tFTv0UhWeM-IGCxgxkC07Bo_zpbgr6u1KE1Rehs/edit?usp=sharing&resourcekey=0-L-XaP9QeLAkEsp8najVkUQ)), but he observed that copying the program to SRAM is sometimes flaky.

* [ ] Automate the setup steps for Verilator and/or VCS
* [ ] Work out flakiness in the step that copies the binary to SRAM
* [ ] Add command to opentitantool to orchestrate OpenOCD, GDB, and optionally verilator

**Comment by a-will** [comment]
FYI: If you'd like to skip the gdb dependency, sending Tcl commands to OpenOCD likely could effect the same outcome.

**Comment by dmcardle** [comment]
Now that we've merged #14343, the next big step is to use ROM instead of the Test ROM. (I'd also like to set the `pmpcfgx` registers with OpenOCD, without reusing code baked into the ROM, but that's another story.)

After replacing the test ROM with the production ROM, `//sw/device/examples/sram_program:sram_program_fpga_cw310_test` has a hard time resetting and halting the device. It just repeatedly prints to ROM, BFV, etc. to the console followed by a message that hart 0 unexpectedly reset (see below). 

```
[OPENOCD] Info : Hart 0 unexpectedly reset!
[CONSOLE] ROM:3cac3907
[CONSOLE] BFV:0142500d
[CONSOLE] LCV:2739ce73
[CONSOLE] ROM:3cac3907
[CONSOLE] BFV:0142500d
[CONSOLE] LCV:2739ce73
[CONSOLE] ROM:3cac3907
[CONSOLE] BFV:0142500d
[CONSOLE] LCV:2739ce73
[CONSOLE] ROM:3cac3907
```

I tried splicing in the RMA OTP image to ensure debugging is enabled, but that didn't solve the looping-reset problem. Specifically, I wanted to make sure [`HW_DEBUG_EN`](https://docs.opentitan.org/hw/ip/lc_ctrl/doc/#hw_debug_en) is set correctly.

If I take the place of GDB by telnetting into OpenOCD, I can request `reset halt`, but it has no effect. However, plain `halt` does work with a probability of ~25%. I'm not exactly sure what to make of that, nor what OpenOCD's `reset halt`/`halt` means in terms of Ibex's debug module.

```console
% telnet localhost 4444
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Open On-Chip Debugger
Hart 0 unexpectedly reset!
Hart 0 unexpectedly reset!
  --- snip ---
Hart 0 unexpectedly reset!
Hart 0 unexpectedly reset!
> reset halt
Hart 0 unexpectedly reset!
JTAG scan chain interrogation failed: all ones
Check JTAG interface, timings, target power, etc.
Trying to use configured scan chain anyway...
Bypassing JTAG setup events due to errors
Hart 0 unexpectedly reset!
Hart 0 unexpectedly reset!
  --- snip ---
Hart 0 unexpectedly reset!
OpenOCD only supports Debug Module version 2 (0.13) and 3 (0.14), not 0 (dmstatus=0x0). This error might be caused by a JTAG signal issue. Try reducing the JTAG clock speed.
Hart 0 unexpectedly reset!
Hart 0 unexpectedly reset!
  --- snip ---
Hart 0 unexpectedly reset!
> halt
Hart 0 unexpectedly reset!
```

I think the message about reducing JTAG clock speed is a red herring. According to the ARM-USB-TINY-H [manual](https://www.olimex.com/Products/ARM/JTAG/_resources/ARM-USB-TINY_and_TINY_H_manual.pdf), the JTAG adapter should support 1000 kHz and it's running at 500 because we invoked OpenOCD with `-c "adapter speed 500"`. I tried lowering it down to 200 with no success.  

I have this hunch that there's a race between the OpenOCD-generated reset signal and some unrelated interrupt firing, possibly the watchdog timer? When I insert an infinite loop into [`rom_start.S`](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom/rom_start.S;l=164-176;drc=6b0d4ddebf7d1468d998ea8836679a834286e06c), right before setting up the watchdog timer, I have no problem halting the device.

**Comment by a-will** [comment]
> I have this hunch that there's a race between the OpenOCD-generated reset signal and some unrelated interrupt firing, possibly the watchdog timer? When I insert an infinite loop into [`rom_start.S`](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom/rom_start.S;l=164-176;drc=6b0d4ddebf7d1468d998ea8836679a834286e06c), right before setting up the watchdog timer, I have no problem halting the device.

I suspect you're right that it's the watchdog timer. The ROM initially sets up the watchdog bite for early boot, then disables it for test and rma lc states when it reaches here: https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom/rom.c;l=148;drc=f70e784824a22be2c8485153d170940bff152d9b

During that window, halting the CPU with the watchdog bite enabled risks having it trigger a reset. A halt in that section would require a quick follow-up to disable the bite.

**Comment by alphan** [comment]
`0142500d` is `kErrorBootPolicyBadIdentifier`, which means ROM cannot find the ROM_EXT identifier in either of the slots.

Can you try setting `CREATOR_SW_CFG_ROM_EXEC_EN` to `0`? This should make the ROM halt very early in `rom_start.S`.

**Comment by alphan** [comment]
> I tried splicing in the RMA OTP image to ensure debugging is enabled, but that didn't solve the looping-reset problem. Specifically, I wanted to make sure [`HW_DEBUG_EN`](https://docs.opentitan.org/hw/ip/lc_ctrl/doc/#hw_debug_en) is set correctly.

I thought that's the image we normally use in CI. Also, `2739ce73` corresponds to the RMA state (this is the life cycle state value as reported by hardware not the one defined in the life cycle driver) so the bitstream looks OK so far.

**Comment by dmcardle** [comment]
Thanks for the context on the watchdog timer, @a-will!

> `0142500d` is `kErrorBootPolicyBadIdentifier`, which means ROM cannot find the ROM_EXT identifier in either of the slots. This triggers a shutdown, which ends in a SW requested reset.

@alphan, how do you know that 0142500d is `kErrorBootPolicyBadIdentifier`? Also, where the "BFV" line printed? I only got as far as finding [where the "ROM" line is printed](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/lib/arch/device_fpga_cw310.c;l=52;drc=776d2abdfa22b2df0de8d70dadc1962811b9b301).

Should I be flashing ROM_EXT to the device in addition to the bitstream? My test performs an `opentitantool load-bitstream` operation in in [`opentitan_gdb_fpga_cw310_test`](https://cs.opensource.google/opentitan/opentitan/+/master:rules/opentitan_gdb_test.bzl;l=27;drc=411c7741ad9175844d7aeeaaf7e0efd40eccce57), but I noticed that [`cw310_params`](https://cs.opensource.google/opentitan/opentitan/+/master:rules/opentitan_test.bzl;l=183;drc=3e3f460a20d367e840fbff2bee80a73db435cd30) follows up the `load-bitstream` with a `bootstrap` operation for the flash.

> Can you try setting `CREATOR_SW_CFG_ROM_EXEC_EN` to `0`? This should make the ROM halt very early in `rom_start.S`.

Great, this does seem to stop the UART output and allow me to halt the device.

Is this modified OTP image "real" enough to support the manufacturing tests?

> I thought that's the image we normally use in CI. Also, `2739ce73` corresponds to the RMA state (this is the life cycle state value as reported by hardware not the one defined in the life cycle driver) so the bitstream looks OK so far.

Ah, you're right, I guess it's unsurprising that re-splicing the RMA OTP image had no effect. Kind of accidentally, this re-splicing was necessary for my new value of CREATOR_SW_CFG_ROM_EXEC_EN in `hw/ip/otp_ctrl/data/otp_ctrl_img_rma.hjson` to trickle down to the device.
