### ISSUE TITLE
[otbn, dv] Verify OTBN.START_STOP_CTRL.STATE.CONSISTENCY

### ISSUE THREAD

**Issue by prajwalaputtappa** [lowRISC/opentitan#13963]
Figure out what is OTBN.START_STOP_CTRL.STATE.CONSISTENCY and add necessary checkers and tests or stimulus generation for verifying it. 
Original time estimate: 32
> estimate 8

**Comment by johngt** [comment]
URND / RND ret ack. 
Ack interface between start / stop controller.

Same sort of check on two different signals.
Internal signalling for wipe.
2 failure modes.
1) False ACK
2) Killing ret before ACK, whilst Ret held high

**Comment by andreaskurth** [comment]
> remaining 2022-08-09 2
