### ISSUE TITLE
[dif, flash_ctrl] DIFs missing implementation

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#14029]
The folowing functions are missing implementation in the `dif_flash_ctrl`:
- [ ] dif_flash_ctrl_set_phy_configuration
- [ ] dif_flash_ctrl_get_phy_configuration
- [ ] dif_flash_ctrl_phy_configuration_is_locked
- [ ] dif_flash_ctrl_lock_phy_configuration

**Comment by engdoreis** [comment]
@timothytrippel

**Comment by a-will** [comment]
Heh, looks like @tjaychen removed the functionality in hw and sw, but the skeletons remain. They can be deleted now.

**Comment by tjaychen** [comment]
oops my bad.
