### ISSUE TITLE
[TEST, IRQ] Test to ensure Earl Grey IRQ integrity 

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#1402]
It is useful to have a simple test that is ran by CI that checks the integrity of the IRQ flow in Earl Grey. The purpose of this test is not to validate entire PLIC or the peripherals, but to ensure that two different IRQs can interrupt the FPGA and be processed. For the purpose of this test, the UART peripheral will be used, and the target interrupted will be Ibex (the only target in present Earl Grey implementation).

This test will ensure that:
* PLIC getaway can receive an IRQ
* IRQ is handled correctly within the PLIC
* IRQ can interrupt a target
* IRQ can be cleared and the new IRQ can be processed

The reason for introducing this test is the issues we had previously with the IRQ delivery on the FPGA, see issue #1355 .

**Comment by silvestrst** [comment]
@lenary @msfschaffner @alistair23 @GregAC @tjaychen @eunchan 

Added the people that were directly affected by the mentioned issue. Please feel free to add other people.

**Comment by tjaychen** [comment]
do you think it makes sense in the same test to test not only the PLIC, but also other interrupt sources that connect directly to the hart but not through the PLIC? (such as timer).

**Comment by lenary** [comment]
The intention is that this should be a small smoke test that quickly tells you if interrupts are working, and is short enough that grabbing a trace of the hardware (either from FPGA or verilator) during the test is also doable. This suggests keeping it to two interrupts should be enough to tell us "something is wrong", but not "everything is right", and I would suggest comprehensive testing of the PLIC is a separate issue.

The intention is this ends up in `sw/device/tests/plic` so, like the other peripheral tests in that directory, it will not be a comprehensive test.

**Comment by silvestrst** [comment]
> do you think it makes sense in the same test to test not only the PLIC, but also other interrupt sources that connect directly to the hart but not through the PLIC? (such as timer).

@tjaychen I agree with what @lenary said, and I think the other IRQ sources that connect directly to HART should/could be a subject of a separate test.
