### ISSUE TITLE
[opentitantool] Alert handler configuration digests for different life cycle states

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#14038]
#13468 adds a check that compares the crc32 of the alert handler configuration with the expected value in OTP before jumping to ROM_EXT. `opentitantool` should be enhanced to produce this value as described in this [doc](https://docs.google.com/document/d/1exWkL6VBt7qBRcbaIbZCvcRTRnuyZkTn-kQslHf7xY4/edit?resourcekey=0-6sqWIiKEUEoh01xb4upXww).

cc @cfrantz @arunthomas @moidx

**Comment by jon-flatley** [comment]
Thanks @alphan! I'll add this to the OTP checklist for opentitantool integration: #13869

**Comment by cdgori** [comment]
This may be (probably is) coming from left-field, but what is the intent of the CRC32 here?  (I can't access the document due to permissions)

If we are protecting the configuration from tampering by a malicious adversary, should we consider using a SHA2 instead?

**Comment by alphan** [comment]
> This may be (probably is) coming from left-field, but what is the intent of the CRC32 here? (I can't access the document due to permissions)
> 
> If we are protecting the configuration from tampering by a malicious adversary, should we consider using a SHA2 instead?

Hi Chris, just wanted to follow up to make sure that you received my email and the doc. PLMK if you have any questions.

**Comment by alphan** [comment]
@jon-flatley just needs to create a PR for exposing this in the CLI. Closing this since he implemented the actual logic in #14368
