### ISSUE TITLE
Check timer behavior for Tock

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1404]
@pfmooney commented in the PR to get Tock support for OpenTitan merged:

> In our branch, we're using a chip-specific timer driver, since OpenTitan offers an interface that differs slightly from the RISC-V machine timer. (Although they share the same names for the mtime and mtimecmp registers.) That said, I don't have enough rust experience to know if there's an easy way to vary the Frequency trait type on a per-board basis, other than with the #[cfg()] ifdefs.

https://github.com/tock/tock/pull/1460#issuecomment-575834609

@pfmooney We don't intend to implement non-standard behavior here. Can you let us know what behavior is non-standard?

**Comment by imphil** [comment]
CC @lenary

**Comment by pfmooney** [comment]
From the spec (2019-06-08):
>  The interrupt remains posted until it is cleared by writing the `mtimecmp` register.  The interrupt will only be taken if interrupts are enabled and the `MTIE` bit is set in the `mie` register.

As it stands, the `rv_timer` peripheral is using the `prim_intr_hw` module and associated register interfacing, requiring a `1` be written to that position in `INTR_STATE0` to clear the interrupt.  I haven't directly tested it, but I don't believe a write to `mtimecmp` will accomplish the same once the interrupt has latched. (The existing opentitan code seems to [suggest the same](https://github.com/lowRISC/opentitan/blob/3d93afbe25200089f60e6e6c0ff2a315a882c97e/sw/device/lib/rv_timer.c#L43-L45))

**Comment by imphil** [comment]
Good point, that's something we should fix if possible. 

@eunchan is this something you can have a look at? If you're busy let us know, and we'll have a look.

**Comment by eunchan** [comment]
Thanks for the issue. I think we can change rv_timer interrupt behavior to meet the spec (writing to mtimecmp to clear the interrupts).

**Comment by pfmooney** [comment]
This is exacerbated by lowRISC/ibex#567 as well.  It forces the top half of the interrupt handler to store the fact that the time fired, rather than relying on the bit on `mip` to carry that state to the bottom half handler.

**Comment by eunchan** [comment]
The design is revised now. :) Thanks for the issue report.

**Comment by pfmooney** [comment]
> The design is revised now. :) Thanks for the issue report.

Thanks for addressing it!
