### ISSUE TITLE
[spi_device] TPM FIFOs in DPSRAM

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#14045]
Related Issue #13816 

Increasing Wr/Rd FIFOs in TPM affect the overall area by 8k~10k gates. If the FIFOs are moved to DPSRAM space, most of the increment could be remedied. 

The SRAM FIFO interface should have a signal to reset the pointer. Read FIFO should be reset every time new TPM transaction begins.

**Comment by eunchan** [comment]
CC: @tjaychen

**Comment by eunchan** [comment]
@weicaiyang pointed that if Generic mode and TPM can be active together. With the suggested change (moving TPM FIFOs into DPSRAM), I assume generic and tpm are mutually exclusive. Need to clarify this with the users.

CC: @tjaychen

**Comment by tjaychen** [comment]
ahhhhhh..... thanks for the reminder.
Generic mode and TPM mode at the same time... probably not likely. 

However, we did plan for [parallel TPM function](https://docs.google.com/document/d/1krNr5lZDjpVFtp3iT-rCkRU4oQc9lXtHsZrBJuCInZ4/edit#bookmark=id.2glqu8vuyfwc) at the same time.. so I don't think we can actually merge this.

**Comment by eunchan** [comment]
> ahhhhhh..... thanks for the reminder. Generic mode and TPM mode at the same time... probably not likely.
> 
> However, we did plan for [parallel TPM function](https://docs.google.com/document/d/1krNr5lZDjpVFtp3iT-rCkRU4oQc9lXtHsZrBJuCInZ4/edit#bookmark=id.2glqu8vuyfwc) at the same time.. so I don't think we can actually merge this.
>
So, the current TPM function behaves as "parallel TPM function". The section describes "the SPI device will be able to run TPM and flash functions (described in the sections above) in parallel". Even if generic mode and TPM mode are mutually exclusive, this still satisfy. Is it OK to revise the tech spec to clarify even in the current version of IP (which do not move the FIFOs into DPSRAM yet).

**Comment by tjaychen** [comment]
yeah that sounds good.

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. Since this is an area optimization (replacing FFs with DPSRAMs), I think it's not relevant for this release and thus correctly labeled https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease.

Regarding the simultaneous activity of TPM mode and Generic mode (which we don't support) or TPM mode and Flash or Passthru modes (which we do support), I'll quickly confirm with the product team.

**Comment by msfschaffner** [comment]
CC @a-will
