### ISSUE TITLE
[fpv] Write assertions to check EDN output valid data

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14049]
From discussion here:
https://github.com/lowRISC/opentitan/pull/14046/files#r939445233

To make sure EDN always provide valid (non-zero, non-all-ones, unique) data, we can add assertions to EDN data output.

CC: @sriyerg @msfschaffner @martin-lueker

**Comment by martin-lueker** [comment]
@mwbranstad

**Comment by msfschaffner** [comment]
Has this assertion been added yet?

**Comment by cindychip** [comment]
Sorry @msfschaffner @tjaychen I just saw this comment and about to clean up all the M2 Issues.
The #15919 only checks if the data is stable, but did not check the data is valid. I will add some assertion to `prim_edn_req` module soon today.
