### ISSUE TITLE
[spi_device] payload upload ignores dummy cycles 

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#14051]
@eunchan 

Looks like payload upload ignores dummy cycles. We starts to upload payload when all addresses are collected regardless of the value of dummy_size, right?

Perhaps I can assume dummy cycle is 0 when it's not a read, right?

**Comment by eunchan** [comment]
Yes. It assumes no dummy cycle between the address and payload. 
Still, I think supporting the dummy cycle is a good idea.

Let me change this ticket to Future Release Thanks!

**Comment by weicaiyang** [comment]
@eunchan Thanks for the confirmation

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2 for the moment. I think this is according to our current spec, but I'd like to mention this to the product team before we definitely defer this to https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease.

**Comment by a-will** [comment]
For what it's worth, for the type of device we are modeling, I believe writes are buffered in low-latency storage, then executed upon the completion of the SPI transaction. Dummy cycles are used for reads to accommodate the high-latency arrays where data originates.

Most likely, there is no use for dummy cycle support on writes. However, it doesn't hurt to ask the product team to be sure.

**Comment by hcallahan-lowrisc** [comment]
Checked as part of the product-team review process, believe that all relevant devices **do not** have opcodes that have dummy cycles for writes.
Hence, defer to FutureRelease.

**Comment by a-will** [comment]
Closing, since the set of SPI flash operations we support does not include dummy cycles for write commands.
