### ISSUE TITLE
[otbn] DMEM and IMEM read blanking during secure wipe

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#14066]
We have assertions in place to ensure that reads from DMEM and IMEM are blanked when OTBN is not in the IDLE state. They currently fail because reads are not blanked during secure wipe. We have two options to resolve this:
1. Allow DMEM and IMEM reads to be non-blank during secure wipe.
2. Blank DMEM and IMEM reads also during secure wipe.

A secure wipe happens on two occasions: after reset and after execution.
- After reset, the scrambling key to DMEM and IMEM has changed, so blanking is not strictly required.
- After execution, IMEM and DMEM usually contain data. This data could be read during secure wipe. It could also be read if OTBN becomes idle after secure wipe, but this is not always the case; OTBN can also become locked after secure wipe. DMEM and IMEM data is protected once OTBN is locked but not during the secure wipe of the internal state before.

I thus think we:
- (A) should at least blank DMEM and IMEM reads while OTBN is performing a secure wipe after execution that will end in the locked state -- This has been implemented in #14388;
- (B) could, but do not have to, blank DMEM and IMEM reads during the initial secure wipe and during a wipe after which OTBN becomes idle again -- As discussed below, this could be implemented later.

I suggest we do (A) now to prevent reads from DMEM and IMEM after a fatal error and postpone (B) for later because it provides some additional protection (against descrambling) but also has wider DV implications (tests have to wait for OTBN to become idle after reset before they can read DMEM or IMEM).

> estimate 8
> remaining 2022-08-23 0

**Comment by andreaskurth** [comment]
DMEM and IMEM reads are already blanked while `locking` is asserted, so implementing (A) would boil down to
- ensuring that there is no time gap between `busy_execute_d` and `locking`
- adapting the assertion to allow this case.

**Comment by andreaskurth** [comment]
WDYT, @GregAC @vogelpi?

**Comment by vogelpi** [comment]
Thanks for looking into this @andreaskurth . Option A sounds very reasonable. I think also B should be done but as it requires some DV changes as well, it's probably better to postpone this at the moment. Your proposal sounds good to me.

**Comment by GregAC** [comment]
Option A sounds reasonable to me, though I'm unclear why Option B has a DV impact? The blanking just means outputs end up being held to 0 at points they couldn't have been used anyway.

**Comment by andreaskurth** [comment]
> Option A sounds reasonable to me, though I'm unclear why Option B has a DV impact? The blanking just means outputs end up being held to 0 at points they couldn't have been used anyway.

That is correct, but some tests read IMEM or DMEM when OTBN is not idle; e.g., `chip_jtag_mem_access` currently fails on an assertion for this reason. Such tests will have to be changed. I estimate the DV impact to be not deep/complex but potentially wide (all test code accessing OTBN IMEM or DMEM should be checked).

**Comment by andreaskurth** [comment]
Update: Option A has been implemented in #14388; Option B is deferred as discussed. Changed priority to P3 as Option B is not considered urgent.

**Comment by engdoreis** [comment]
@andreaskurth @johngt, this is a kind reminder, is this issue still relevant or can we close it?

**Comment by andreaskurth** [comment]
I think it's out of scope for this revision (due to DV implications) but may be reconsidered for future revisions. Is _Backlog_ the appropriate milestone for this?

**Comment by johannheyszl** [comment]
The above described option (A) has been implemented, additional measures can be considered defense in depth. Suggest moving to backlog.

**Comment by vogelpi** [comment]
I am closing this issue as not planned.

> * (A) should at least blank DMEM and IMEM reads while OTBN is performing a secure wipe after execution that will end in the locked state

This has been implemented already.
> * (B) could, but do not have to, blank DMEM and IMEM reads during the initial secure wipe and during a wipe after which OTBN becomes idle again.

Secrets should anyway never end up in internal memory regions of OTBN readable by Ibex. Reading those readable memory regions before the secure wipe finishes thus is of limited usefulness only. Preventing this would help against descrambling but it's potential defense in depth and not considered urgent.
