### ISSUE TITLE
[tlul, rtl] Use of devmode_i 

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#14063]
On reviewing some OTBN RTL I realised the `devmode_i` input of the autogenerated `otbn_reg_top` is hard-wired to 1.

The documentation for register tool (here: https://docs.opentitan.org/doc/rm/register_tool/#error-responses) explains that the `devmode_i` input is meant to indicate if the device is in development or production mode. The idea being in production mode, for security critical blocks, rather than returning error messages on invalid accesses writes are silently ignored and reads return dummy data.

Looking at other blocks it appears all of them have `devmode_i` hard-wired to 1.

Is this an oversight? Should we have `devmode_i` suitably connected up to the life cycle controller or is this an old proposed feature we decided not to do?

**Comment by msfschaffner** [comment]
Hey @GregAC! This has been discussed in the security WG here: https://github.com/lowRISC/opentitan/issues/10311 and deemed ok to leave as is (i.e. `devmode_i` hardwired to 1) for the current OpenTitan iteration.

**Comment by GregAC** [comment]
Ah great, we should review the register tool documentation to make it clear we're not planning on using `devmode_i` set to 0 for the current iteration of OpenTitan but it's a considering for future work. There may be a few TODOs to clean up here as well. I'm happy to take this on. I'll leave this issue open to track.

**Comment by msfschaffner** [comment]
Deferring this into M3 since it is documentation only.

**Comment by matutem** [comment]
This issue is a must have for all subsequent chip incarnations after 2.5, so it must be properly tracked.
