### ISSUE TITLE
[aes/rtl/reg] Status register not returning expected reset value

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#1407]
replicate
 make TEST_NAME=aes_csr_hw_reset WAVES=1  (any seed)

Register is returning 0x9 according to spec should return 0x8
![image](https://user-images.githubusercontent.com/53917183/73077211-09f64980-3ec0-11ea-8534-6a1979fbffca.png)

![image](https://user-images.githubusercontent.com/53917183/73078210-0794ef00-3ec2-11ea-86f9-619297810e2a.png)

Let me know if you need a waveform

**Comment by rasmus-madsen** [comment]
this might be a timing issue where the test is trying to read the register to soon?

**Comment by sriyerg** [comment]
Bit [0] of the status register is 'idle'. I would assume that unless AES is operational, it would indeed be in the 'idle' state. Either change the reset value of that field in the hjson to 0x1 (preferred, assuming this assessment is correct), or manually 'fix' it in `aes_env_cfg::apply_ral_fixes()` function:

```systemverilog
  // ral flow is limited in terms of setting correct field access policies and reset values
  // We apply those fixes here - please note these fixes need to be reflected in the scoreboard
  protected virtual function void apply_ral_fixes();
    // fix access policies
    // fix reset values for fields with "hwext" attribute
    ral.status.idle.set_reset(1'b1);
  endfunction
```

**Comment by vogelpi** [comment]
Thanks for opening the issue @rasmus-madsen and for your input @sriyerg . I think the documentation + reset value are wrong/confusing here. The documentation says that that Bit 0 (called IDLE) is indicating if the unit is idle (value 0) or busy (value 1). The reset value is 0.

It should rather be idle (value 1), busy (value 0) and reset value 1. I am preparing a PR to change this.
