### ISSUE TITLE
[entropy_src] Confusion when handling Continuous vs. Windowed HT's

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#14078]
The REPCNT & REPCNTS differ from the other health tests in that they look at the RNG data stream as a continuous time series, as opposed to the other health tests which break the data into windows.  These tests can detect statistical anomalies at any time during an HT window, or can even detect multiple anomalous time regions during a window.
    
Unfortunately, this leads to some potential points of confusion when handling the continuous tests in the broader design. If these tests detect multiple error events during a single window the reaction of the `entropy_src` module will vary depending on whether the module is currently in Boot, StartUp, or Continuous Phase. Under boot or continuous phases, the `entropy_src` signals an alert if the total number of errors exceeds threshold (regardless of whether the alerts appear in one window or in separate windows.)  Though on the other hand, the logic for the StartUp phase is explicitly created to evaluate two separate Health test windows, with the assumption that it is the number of failing windows that matters, not the number of failure events.
    
Meanwhile, as written now, the number of failure pulses generated by the repcnt and repcnts tests are less an indication of the number of failure events, and more an indication of the _magnitude_ of the failures.  For instance, if there is a coincidental string of 13 identical RNG words, and the REPCNTS threshold is set to 10, the REPCNTS HT will emit 4 failure pulses, (not one) as the repeat count crosses 10, 11, 12, and 13.  Larger failures get counted in the Alert and Total counters as multiple events.
    
This all makes statistics generated by the the REPCNT and REPCNTS tests confusing to interpret, and makes it very  hard to verify them, especially in the transition between the StartUp and Continuous phases

***Proposal***    
It would be much simpler if we could aggregate many REPCNT or REPCNTS "events" into one pulse if they appear in the same window, as shown in following waveform.  This pulse could then be emitted at the same time as the other windowed tests allowing for some simplifications in verifying the Total and Alert counts.  (The scoreboarding of these statistics is extremely sensitive to the timing of events, which makes this IP the bane of my existence) What are people's thoughts?

![image](https://user-images.githubusercontent.com/47870387/183533792-29099ac7-8984-4f76-bc65-f8a7aa24e094.png)

**Comment by martin-lueker** [comment]
Note: The proposed change has been implemented and verified with good results (See #14083 and #14084)

**Comment by zi-v** [comment]
Sounds good to me. Alternatively you could have considered zeroizing the repetition counter upon reaching the threshold, this might have given a slightly more accurate statistical view.
However, since you have already implemented and checked this, I don't think you should change.

**Comment by tjaychen** [comment]
this sounds good to me. 
I'll leave any other comments in #14083

**Comment by martin-lueker** [comment]
Thanks everyone.   This proposed fix does have one issue in that it complicates the processing of the REPCNT outputs, and by putting an extra flop to mask them in there, which I don't think is a great. Idea, I've closed #14083, in favor of the simpler #14238, which just shifts to outputs of the REPCNT and REPCNTS health tests to make them easier to predict.
