### ISSUE TITLE
Which combinations of GPIO interrupt types should be allowed?

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#1409]
GPIO device supports detecting four events for reporting interrupts:
- Rising-edge
- Falling-edge
- Level-high
- Level-low

However, some combinations of these interrupts may not be very useful. Consider a pin that is currently high. The next time it goes low could be detected by enabling either falling-edge or level-low, so it is not necessary and does not seem to be useful to enable both falling-edge and level-low detection. This issue was raised by @silvestrst and @lenary in #1254. I had a quick chat with @tjaychen and he also seems to agree that some of these combinations may not be useful at all. #1254 currently supports only certain cases (none, rising, falling, high, low, rising and falling, low and rising, high and falling, please see the PR for details).

I'm creating this issue to try to answer the following questions:
- Would not supporting some combinations block any use-cases?
- If not, is the current set of supported combinations complete? Do we need to add/remove any cases?
- Is there an opportunity here to simplify the HW (assuming that some of these cases will indeed not be supported)?

@gkelly @asb @imphil

**Comment by silvestrst** [comment]
> Is there an opportunity here to simplify the HW (assuming that some of these cases will indeed not be supported)?

I guess one solution would be to have one register type that uses more than one bit for every GPIO. However then dependent on how many mutually exclusive variants there are, it could become awkward, as you would need n bits per a variant. With 32 gpios that could span across several registers.

I think it is easier to implement these restrictions in software, and DIF would be the most fitting place.

> If not, is the current set of unsupported combinations complete? Do we need to add/remove any cases?

I agree, that would be useful to know.

**Comment by alphan** [comment]
> I guess one solution would be to have one register type that uses more than one bit for every GPIO. However then dependent on how many mutually exclusive variants there are, it could become awkward, as you would need n bits per a variant. With 32 gpios that could span across several registers.

Yes, that is what I was thinking, similar to how pinmux is implemented. While it would not be as trivial to configure from the software side, this may be worth doing if it results in considerable simplifications in hw.

**Comment by lenary** [comment]
At the moment we have enumerated the combinations we think are reasonable (in #1254). Should we need other specific combinations later, we could add enum variants for this, so long as we know the hardware will do something reasonable.
