### ISSUE TITLE
[top] Track system level test cases

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#14095]
There are a few system level test cases that need to be written but are currently not tracked in any of nightly collateral.
For now, track them in this issue here until a more suitable home is found. 

- [ ] [Power virus test](https://docs.google.com/document/d/1OMnxqSZ0OGNzHkWH8Le6utW6llyIR1QgrUnbZpOkwYU/edit?usp=sharing)
- [x] [Sram manufacturing test](https://docs.google.com/document/d/1i6V3tFTv0UhWeM-IGCxgxkC07Bo_zpbgr6u1KE1Rehs/edit?usp=sharing&resourcekey=0-L-XaP9QeLAkEsp8najVkUQ)

**Comment by msfschaffner** [comment]
@alphan The SRAM manufacturing test has been added to the testplan, right?

**Comment by alphan** [comment]
> @alphan The SRAM manufacturing test has been added to the testplan, right?

Correct

**Comment by timothytrippel** [comment]
since #14814 is already tracking what is left (the power virus test), I am closing this.
