### ISSUE TITLE
[dvsim] run_timeout_mins can't be overridden

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#14092]
I got this error when I added `run_timeout_mins: 120` in chip_sim_cfg at https://github.com/lowRISC/opentitan/pull/14075

> ERROR: [Modes] Mode sw_test_mode_test_rom cannot be merged into chip_sw_uart_rand_baudrate due to a conflict (unable to pick one from different values): run_timeout_mins: {120, 60}

this works for block-level like uart, but chip-level fails.

cc: @matutem @cindychip @jdonjdon

**Comment by jdonjdon** [comment]
it doesn't work for flash_ctrl either.

**Comment by matutem** [comment]
A workaround is created in https://github.com/lowRISC/opentitan/issues/14092. A better solution needs to be implemented once Sri has had a chance to provide feedback.

**Comment by sriyerg** [comment]
I have a fix in mind for this. PR coming soon.

**Comment by sriyerg** [comment]
Fixed in #14236. Please reopen if still not working.
