### ISSUE TITLE
[chip-test] chip_sw_i2c_host_tx_rx

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#14104]
### Test point name

[chip_sw_i2c_host_tx_rx](https://github.com/lowRISC/opentitan/blob/07ece748876891301ac6eaba354541d4a57d39c6/hw/top_earlgrey/data/chip_testplan.hjson#L225)

### Host side component

SystemVerilog+Rust

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

@Martin-Lueker

### Checklist
Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.

- [x]  Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x]  Device-side (C) component developed
- [x]  Bazel build rules developed
- [x]  Host-side component developed
- [x]  HJSON test plan updated with test name (so it shows up in the dashboard)
- [x]  Test added to dvsim nightly regression (and passing at time of checking)

>estimate 8

**Comment by martin-lueker** [comment]
Thanks for the heads up.  This may be a bit challenging until we get this to V2.

**Comment by weicaiyang** [comment]
> Thanks for the heads up. This may be a bit challenging until we get this to V2.

Sorry for accidentally tagging you. This is a chip-level V2 test. We're moving the tracking of these tests to github and create an issue for each test.

**Comment by martin-lueker** [comment]
Oh, I see. Thanks for the explanation.

**Comment by tjaychen** [comment]
test can be further enhanced, but for now, the basics are done.

**Comment by tjaychen** [comment]
even though the test is done, it should be enhanced for a couple of things.
- [ ] allow randomization of which i2c unit / agent in each test
- [ ] enhance the i2c test to check change of direction in a single transaction. See #14949 for a problem observed in target mode. We should check that host mode does not have similar issues.

**Comment by drewmacrae** [comment]
By the way, this is also addressed in #14797

**Comment by sriyerg** [comment]
Reopening this issue to track the work on missing work items highlighed in https://github.com/lowRISC/opentitan/issues/14104#issuecomment-1248921924.

**Comment by sriyerg** [comment]
@rnongie, FYI

**Comment by engdoreis** [comment]
Closing as passing:
|     | Tests                       |   2022-11-21 08:11:59 |   2022-11-20 08:10:00 |   2022-11-19 08:10:46 | 2022-11-18 08:16:52   | 2022-11-17 08:11:05   | 2022-11-16 08:14:00   | 2022-11-15 08:11:58   | 2022-11-14 08:10:42   | 2022-11-13 08:12:54   | 2022-11-12 08:04:45   | 2022-11-11 08:07:48   | 2022-11-10 08:10:06   | 2022-11-09 08:04:06   | 2022-11-08 08:03:42   | Suite                  |
|----:|:----------------------------|----------------------:|----------------------:|----------------------:|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:-----------------------|
| 102 | chip_sw_i2c_host_tx_rx      |                   100 |                   100 |                   100 | 66.67                 | 100.00                | 100.00                | 100.00                | 100.00                | 100.00                | 100.00                | 100.00                | 100.00                | 100.00                | 100.00                | chip_sw_i2c_host_tx_rx |
| 103 | chip_sw_i2c_host_tx_rx_idx1 |                   100 |                   100 |                   100 | --                    | --                    | --                    | --                    | --                    | --                    | --                    | --                    | --                    | --                    | --                    | chip_sw_i2c_host_tx_rx |
| 104 | chip_sw_i2c_host_tx_rx_idx2 |                   100 |                   100 |                   100 | --                    | --                    | --                    | --                    | --                    | --                    | --                    | --                    | --                    | --                    | --                    | chip_sw_i2c_host_tx_rx |

**Comment by weicaiyang** [comment]
> allow randomization of which i2c unit / agent in each test
> enhance the i2c test to check change of direction in a single transaction. See https://github.com/lowRISC/opentitan/issues/14949 for a problem observed in target mode. We should check that host mode does not have similar issues.

I addressed the 1st item but I'm not sure if the 2nd item is done or not. Let me reopen this. Will check with @tjaychen when he is back.
Also changed this to M3, as it doesn't seem critical.

**Comment by tjaychen** [comment]
sorry what's the issue? i'm a bit out of the loop.

**Comment by weicaiyang** [comment]
> even though the test is done, it could be enhanced for a couple of things.
> 
> * [x]  allow randomization of which i2c unit / agent in each test
> * [ ]  enhance the i2c test to check change of direction in a single transaction. See [I2C may not respond properly to a repeated start condition #14949](https://github.com/lowRISC/opentitan/issues/14949) for a problem observed in target mode. We should check that host mode does not have similar issues.

@tjaychen I was asking the 2nd item above. Has it been addressed?

**Comment by tjaychen** [comment]
uhhh....i'm really not sure. It probably has not been added.

**Comment by crteja** [comment]
Estimate for M2.5
> estimate 14

**Comment by moidx** [comment]
After taking a close look, it seems this issue is to cover a test enhancement. Assuming it does not have much impact on coverage, it is ok to defer post M2.5
