### ISSUE TITLE
[chip-test] chip_sw_spi_host_tx_rx

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#14114]
### Test point name

[chip_sw_spi_host_tx_rx](https://github.com/lowRISC/opentitan/blob/ec2c5dee719b65882057e57ce815af238f926b96/hw/top_earlgrey/data/chip_testplan.hjson#L206)

### Host side component

SystemVerilog+Rust

### OpenTitanTool infrastructure implemented

No

### Contact person

martin-lueker

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] Enable randomization of spi_host interface to ensure all instances are exercised

**Comment by tjaychen** [comment]
this test was previously assigned to P3 by accident, it really should be a P1 test.

**Comment by tjaychen** [comment]
i've taken over this test for now to add some basic top level spi host testing.
This is a top level smoke test to ensure spi_host can communicate with the outside world, it does not replace more detailed testing of the spi host (for example, interaction with a spi flash module).

**Comment by tjaychen** [comment]
i have something that is almost ready for this one. I'll just assign this issue to myself exclusively for now.

**Comment by tjaychen** [comment]
test can be further enhanced, but for now the basics are done.

**Comment by sriyerg** [comment]
I was reviewing chip level coverage, and indeed the SPI HOST1 interface appears to not be covered, which means the connection of SPI_HOST1 to pinmux is untested. Could we address the randomization of the SPI_HOST interface in M2? Seems like the hooks are all there - just need some tweaks.

**Comment by sriyerg** [comment]
I am reopening this issue, since the testplan intent is not fully covered. We could tag it to M3 if deemed lower priority than other things.

**Comment by sriyerg** [comment]
I stumbled upon https://github.com/lowRISC/opentitan/issues/15483 which appears to track the enhancement to randomize the instance. I will close this issue in that case.
