### ISSUE TITLE
[chip-test] chip_sw_sysrst_ctrl_ec_rst_l

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#14116]
### Test point name

[chip_sw_sysrst_ctrl_ec_rst_l](https://github.com/lowRISC/opentitan/blob/ad1905ff86ab2ba171b156a4db8717508227a043/hw/top_earlgrey/data/chip_testplan.hjson#L1641)

### Host side component

SystemVerilog+Rust

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

msfschaffner

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by jeoongp** [comment]
This test was developed and is under review in https://github.com/lowRISC/opentitan/pull/14970.
