### ISSUE TITLE
[chip-test] chip_sw_sysrst_ctrl_ulp_z3_wakeup

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14110]
### Test point name

[chip_sw_sysrst_ctrl_ulp_z3_wakeup](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/chip_testplan.hjson#L1614)

### Host side component

SystemVerilog

### Contact person

@msfschaffner

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [ ] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by ballifatih** [comment]
@cindychip This is merged in #15403, I would appreciate if you could check the boxes accordingly (since I am not a committer). Thank you.

**Comment by msfschaffner** [comment]
This test is passing in the nightlies - closing!
