### ISSUE TITLE
[chip-test] chip_sw_sysrst_ctrl_in_irq

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#14115]
### Test point name

[chip_sw_sysrst_ctrl_in_irq](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/chip_testplan.hjson#L1507)

### Host side component

SystemVerilog+Rust

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

msfschaffner

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by abdullahvarici** [comment]
I've started to develop the test. For progress please check: https://github.com/lowRISC/opentitan/pull/15594

**Comment by abdullahvarici** [comment]
I have completed the PR: https://github.com/lowRISC/opentitan/pull/15594 and now waiting for reviews. After merging I will check nightly regressions and close this issue.

**Comment by engdoreis** [comment]
PR merged, waiting for the nightly reports to close this Issue in case the test passes.

**Comment by engdoreis** [comment]
This test passing in the regression
|     | Tests                      |   latest |   2022.10.26 |   2022.10.25 | 2022.10.24   | 2022.10.23   | 2022.10.22   | 2022.10.21   | 2022.10.17/12   | 2022.10.17/1   | 2022.10.17   | Suite                      |
|----:|:---------------------------|---------:|-------------:|-------------:|:-------------|:-------------|:-------------|:-------------|:----------------|:---------------|:-------------|:---------------------------|
| 196 | chip_sw_sysrst_ctrl_in_irq |      100 |          100 |          100 | --           | --           | --           | --           | --              | --             | --           | chip_sw_sysrst_ctrl_in_irq |
