### ISSUE TITLE
[chip-test] chip_sw_usb_vbus

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14121]
### Test point name

[chip_sw_usb_vbus](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/chip_testplan.hjson#L273)

### Host side component

SystemVerilog

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

@a-will

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by GregAC** [comment]
@alees24 (a new starter at lowRISC) is taking a look at USB device TLT, I've put him in planned assignee for now as he's ramping up currently rather than actively working on any particular test.
