### ISSUE TITLE
[chip-test] chip_sw_sram_nmi_wipe

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#14125]
### Test point name

[chip_sw_sram_nmi_wipe](https://github.com/lowRISC/opentitan/blob/c7cb30c201ff855c9f24a142ead16f29200db80f/hw/top_earlgrey/data/chip_testplan.hjson#L2881)

### Host side component

None Required

### OpenTitanTool infrastructure implemented

No

### Contact person

msfschaffner

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by tjaychen** [comment]
@moidx 
@alphan 

I believe this item is duplicated from e2e mask rom, can you guys confirm? 
See description [here](https://github.com/lowRISC/opentitan/blob/83f86fa8959de62cc344e90cb4eba604c93417e2/hw/top_earlgrey/data/chip_testplan.hjson#L2881)

**Comment by alphan** [comment]
I think so. We have two relevant items in the e2e tesplan: [rom_e2e_asm_init](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom/data/rom_testplan.hjson?q=rom_e2e_asm_init) that covers the main SRAM scrambling and init + [rom_e2e_ret_ram_init](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom/data/rom_testplan.hjson?q=rom_e2e_ret_ram_init) that covers the retention SRAM.

**Comment by tjaychen** [comment]
thanks @alphan ! Miguel just wanted to make sure that we do in fact check the memory is wiped.

**Comment by alphan** [comment]
I'll assign this test to me. FYI, if we also care about NMI/escalation + retention RAM in addition to main SRAM, this becomes a slightly different test than the current definition of `rom_e2e_ret_ram_init` (#14494) but we should probably extend it to cover that case as well.

**Comment by tjaychen** [comment]
sounds good. So should we close this one down @alphan ? since it is more or less covered in #14494?

**Comment by alphan** [comment]
SGTM @tjaychen! Closing since this will be covered in #14494.
