### ISSUE TITLE
[flash_ctrl] regwen splits into different regs

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#1412]
Hi Tim,

As we discussed, I think it would be better to split regwen into different regs rather than fields.
Current regwen is `FLASH_CTRL.REGION_CFG_REGWEN` and 8 regions are 8 fields.
I think it would be better to split them into eight registers:
1. Easier for users to write and control individual regions
2. Easier to generate DV automation.

Thanks!

**Comment by cindychip** [comment]
This issue is related to PR: https://github.com/lowRISC/opentitan/pull/1384

**Comment by cindychip** [comment]
This will be a temp solution until multi-reg supports `compact` functionality.

**Comment by cindychip** [comment]
PR Merged.

**Comment by tjaychen** [comment]
@cindychip , do you mind if i keep this open?
Mostly because the "fix" i put it is meant to be temporary until i make all of flash_ctrl  generated, or multireg / parameters becomes fully ready.

**Comment by cindychip** [comment]
Oh sure, sounds good.

**Comment by tjaychen** [comment]
i'm most likely going to template the `flash_ctrl`, so this issue is moot.
