### ISSUE TITLE
[chip-test] chip_sw_kmac_entropy

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#14123]
### Test point name

[chip_sw_kmac_entropy](https://github.com/lowRISC/opentitan/blob/07ece748876891301ac6eaba354541d4a57d39c6/hw/top_earlgrey/data/chip_testplan.hjson#L1840)

### Host side component

None required

### OpenTitanTool infrastructure implemented

unknown

### Contact person

@eunchan 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [x] Bazel build rules developed
- [ ] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by johannheyszl** [comment]
quick question pls: testplan says milestone: V3 instead of V2 for this test. is that correct?

**Comment by cindychip** [comment]
Good question! I think it should be V2, but I will confirm with @sriyerg @eunchan.

**Comment by eunchan** [comment]
Revised to V2.

**Comment by ballifatih** [comment]
The test implementation is recently merged #14637, should we update the checklist above to reflect its progress?

**Comment by cindychip** [comment]
> The test implementation is recently merged #14637, should we update the checklist above to reflect its progress?

Yes please @ballifatih! I think you can update them and close this issue;
