### ISSUE TITLE
[chip-test] chip_sw_flash_prim_tl_access

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#14120]
### Test point name

[chip_sw_flash_prim_tl_access](https://github.com/lowRISC/opentitan/blob/ec2c5dee719b65882057e57ce815af238f926b96/hw/top_earlgrey/data/chip_testplan.hjson#L2541)

### Contact person

tjaychen

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by cindychip** [comment]
PR is merged : https://github.com/lowRISC/opentitan/pull/14255
Waiting for nightly regression result.

**Comment by cindychip** [comment]
Done and passed in regression.
