### ISSUE TITLE
[chip-test] chip_usb_wake_debug

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14133]
### Test point name

[chip_usb_wake_debug](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/chip_testplan.hjson#L330)

### Host side component

SystemVerilog+Rust

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

@a-will

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by GregAC** [comment]
@alees24 (a new starter at lowRISC) is taking a look at USB device TLT, I've put him in planned assignee for now as he's ramping up currently rather than actively working on any particular test.

**Comment by andreaskurth** [comment]
This testpoint got removed in PR #24008 because it is no longer valid.
