### ISSUE TITLE
[chip-test] chip_sw_padctrl_attributes

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#14142]
### Test point name

[chip_sw_padctrl_attributes](https://github.com/lowRISC/opentitan/blob/b65e2705eb4ee814b46939d44f84d1adfee133c3/hw/top_earlgrey/data/chip_testplan.hjson#L406)

### Host side component

SystemVerilog

### Contact person

@msfschaffner

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by weicaiyang** [comment]
@sriyerg suggested doing this in stub_cpu mode

Also related to https://github.com/lowRISC/opentitan/issues/12103

**Comment by sriyerg** [comment]
Test written and passing with #15908.
