### ISSUE TITLE
[chip-test] chip_rv_dm_perform_debug

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#14145]
### Test point name

[chip_rv_dm_perform_debug](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/chip_testplan.hjson#L517)

### Host side component

SystemVerilog+Rust

### OpenTitanTool infrastructure implemented

Yes

### Contact person

msfschaffner, gregac

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by tjaychen** [comment]
As discussed, this issue will be postponed to post M2.

**Comment by sriyerg** [comment]
The tests are implemented in https://github.com/lowRISC/opentitan/pull/16486.
