### ISSUE TITLE
[chip-test] chip_sw_rv_dm_lc_disabled

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14147]
### Test point name

[chip_sw_rv_dm_lc_disabled](https://github.com/lowRISC/opentitan/blob/8365ac4e97ca340e441ff3355fa07862449b9c8d/hw/top_earlgrey/data/chip_testplan.hjson#L592)

### Host side component

SystemVerilog+Rust

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

@msfschaffner

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by tjaychen** [comment]
since cpu access to the rv_dm device is covered [here](https://github.com/lowRISC/opentitan/blob/8365ac4e97ca340e441ff3355fa07862449b9c8d/hw/top_earlgrey/data/chip_testplan.hjson#L527), should this test only check the JTAG access side?

Or maybe we just need to update the testplan to x-ref the other.

**Comment by msfschaffner** [comment]
I think we can cross reference this.

Note: if we touch the testplan we should also fix this typo: `chip_tap_strap_sampling` -> `chip_sw_tap_strap_sampling`:
https://github.com/lowRISC/opentitan/blob/8365ac4e97ca340e441ff3355fa07862449b9c8d/hw/top_earlgrey/data/chip_testplan.hjson#L599

**Comment by msfschaffner** [comment]
Note: once this test exists, it should be ref'd with `chip_sw_lc_ctrl_broadcast` also.

**Comment by msfschaffner** [comment]
I assigned myself to this test since it is related to other LC signal tests I am already working on, e.g. #14169.
@sriyerg @cindychip let me know if you already have something in flight for this.

**Comment by engdoreis** [comment]
Repening the issue as the test never passed on the nightly

Tests | latest | 2022.10.22 | 2022.10.21 | 2022.10.17/2 | 2022.10.17/1 | 2022.10.15 | 2022.10.14 | 2022.10.12/2 | 2022.10.12/1 | 2022.10.11 | 2022.10.10/2 | 2022.10.10/1 | 2022.10.08/2 | 2022.10.08/1 | 2022.10.06 | Suite
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
chip_rv_dm_lc_disabled | 66.67 | 33.33 | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | chip_rv_dm_lc_disabled, chip_sw_lc_ctrl_broadcast

**Comment by msfschaffner** [comment]
Thanks @engdoreis - will take a look to see what's going on.

**Comment by msfschaffner** [comment]
It looks like I made a rebase mistake before merging the PR and accidentally merged an outdated version. https://github.com/lowRISC/opentitan/pull/15692 fixes that.

**Comment by msfschaffner** [comment]
This has been passing for three nightlies now - closing!
