### ISSUE TITLE
[chip-test] chip_sw_alert_handler_crashdump

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14140]
### Test point name

[chip_sw_alert_handler_crashdump](https://github.com/lowRISC/opentitan/blob/8365ac4e97ca340e441ff3355fa07862449b9c8d/hw/top_earlgrey/data/chip_testplan.hjson#L1264)

### Host side component

None Required

### Contact person

@msfschaffner

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by tjaychen** [comment]
is this test duplicated by https://github.com/lowRISC/opentitan/blob/8365ac4e97ca340e441ff3355fa07862449b9c8d/hw/top_earlgrey/data/chip_testplan.hjson#L1175?

**Comment by msfschaffner** [comment]
Yeah it looks like this is already covered by `chip_sw_rstmgr_alert_info`. Should we just cross ref the test-point, or do you want to remove it entirely?

**Comment by tjaychen** [comment]
Feels like `X-ref` is what we usually do, but wanted to confirm that the existing test covers the spirit of the test point.

**Comment by msfschaffner** [comment]
I think so yes. @cindychip to confirm.

**Comment by jdonjdon** [comment]
Closed by #14894

**Comment by jdonjdon** [comment]
@engdoreis 
When you have a chance, can you checkout the [alert_info_test](https://github.com/lowRISC/opentitan/pull/14903)
I heard you might want to add more feature(https://github.com/lowRISC/opentitan/pull/14903#discussion_r969976669)

**Comment by engdoreis** [comment]
@HU90m is working on it to add more feature from the point of view of `rv_core_ibex`, the issue #13218 and #13219 are tracking that.

**Comment by jdonjdon** [comment]
> @HU90m is working on it to add more feature from the point of view of `rv_core_ibex`, the issues #13218 and #13219 are tracking that.

@engdoreis @tjaychen , that's good. Just to clarify, you are referring to crashdump from ibex, is that correct?

**Comment by engdoreis** [comment]
> > @HU90m is working on it to add more feature from the point of view of `rv_core_ibex`, the issues #13218 and #13219 are tracking that.
> 
> @engdoreis @tjaychen , that's good. Just to clarify, you are referring to crashdump from ibex, is that correct?

Yes, but it would also affect the test reffered in the [comment]( https://github.com/lowRISC/opentitan/pull/14903#discussion_r969976669). Thats why @tjaychen tagged me there.
