### ISSUE TITLE
[chip-test] chip_rv_dm_ndm_reset_req_when_cpu_halted

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#14149]
### Test point name

[chip_rv_dm_ndm_reset_req_when_cpu_halted](https://github.com/lowRISC/opentitan/blob/8365ac4e97ca340e441ff3355fa07862449b9c8d/hw/top_earlgrey/data/chip_testplan.hjson#L558)

### Contact person

msfchaffner, gregac

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by johngt** [comment]
@tjaychen - I see you are working on chip_rv_dm_ndm_reset_req https://github.com/lowRISC/opentitan/issues/15795

**Comment by tjaychen** [comment]
hmm... it is very similar. I think @sriyerg will be able to say better whether this should be a separate test or we can roll it into the existing. The current ndm test does not do the specific things this test is looking for, but it would not be hard to roll in (i think).

**Comment by sriyerg** [comment]
I am working on this test now. I will consider merging the intent of this test into the existing `chip_rv_dm_ndm_reset_req` test.

**Comment by johngt** [comment]
Referencing in https://github.com/lowRISC/opentitan/issues/14145#issuecomment-1314565971 that @tjaychen highlighted. Based on the discussion there about rv_dm work being post M2, this is not an immediate M2 essential task, but @sriyerg is already working on it.
