### ISSUE TITLE
[chip-test] chip_sw_random_sleep_pin_mio_dio_val

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#14157]
### Test point name

chip_sw_random_sleep_pin_mio_dio_val

### Host side component

None Required

### Contact person

@msfschaffner

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by msfschaffner** [comment]
This test still needs to be added to the chip-level testplan.

**Comment by eunchan** [comment]
@msfschaffner `chip_sw_sleep_pin_mio_dio_val` may covers this. Do you still think we should create a separate testplan for random sleep?

**Comment by msfschaffner** [comment]
Is sleep entry / exit already randomized in `chip_sw_sleep_pin_mio_dio_val`?

In any case, I believe this is the only difference between `chip_sw_random_sleep_pin_mio_dio_val` and `chip_sw_sleep_pin_mio_dio_val` so I think I am fine with just updating the existing test point to include randomization...

**Comment by eunchan** [comment]
yep. `chip_sw_sleep_pin_mio_dio_val` chooses normal / deep sleep randomly.
Let me close this.

**Comment by msfschaffner** [comment]
Ok, great!

Can you expand the description of `chip_sw_sleep_pin_mio_dio_val` so that this is captured correctly.

**Comment by eunchan** [comment]
> Ok, great!
> 
> Can you expand the description of `chip_sw_sleep_pin_mio_dio_val` so that this is captured correctly?
>
OK.
