### ISSUE TITLE
[chip-test] chip_sw_secure_boot

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#14156]
### Test point name

[chip_sw_secure_boot](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/chip_testplan.hjson#L2813)

### Host side component

None Required

### OpenTitanTool infrastructure implemented

No

### Contact person

alphan

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by tjaychen** [comment]
i'm sorry @alphan i'm kind lost. Are you saying the secure boot function will be covered by other tests already that need to run in DV, therefore there's no reason to specifically call this one out?

**Comment by tjaychen** [comment]
ah yes then i totally agree. i guess in fact, since we don't have a way to bypass verification, ANY `rom` test would satisfy the secure boot requirement here right?

**Comment by jadephilipoom** [comment]
Yeah, it seems pretty unclear to me what we could cover here that's not covered in the ROM e2e tests.

**Comment by jadephilipoom** [comment]
Should we close this as the easiest `chip-test` issue ever solved?

**Comment by tjaychen** [comment]
yes please do. I just remembered that on our end we went through a scrubbing of the testplan, and this was one of the items to remove or x-ref. But I completely forgot to do it. I'll submit a PR for that today.

**Comment by tjaychen** [comment]
actually jade let me re-open this and assign it to me.
Otherwise i might just forget again :)

**Comment by tjaychen** [comment]
updated in #15994 
we can close now!
