### ISSUE TITLE
[chip-test] chip_sw_pwrmgr_debug_sleep

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14153]
### Test point name

[chip_sw_pwrmgr_debug_sleep](https://github.com/lowRISC/opentitan/blob/8365ac4e97ca340e441ff3355fa07862449b9c8d/hw/top_earlgrey/data/chip_testplan.hjson#L1082)

### Host side component

SystemVerilog+Rust

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

@msfschaffner

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by tjaychen** [comment]
I don't think this test is actually required anymore.
@matutem could you help confirm? It's just going to be not setting the hint, there's no related hardware feature here.

**Comment by sriyerg** [comment]
There is no connection from rv_dm to the pwrmgr to prevent pwrmgr from going into low power state. 
The associated bug on this is still open: https://github.com/lowRISC/opentitan/issues/7215

**Comment by tjaychen** [comment]
that's right, and there's not going to be for this iteration. #7215 should be marked as future release. 
If I mark that one as such, then this one can be closed right?

**Comment by tjaychen** [comment]
> that's right, and there's not going to be for this iteration. #7215 should be marked as future release. If I mark that one as such, then this one can be closed right?

o wait it's already marked future release.

**Comment by msfschaffner** [comment]
I think so, yes. We should also remove it from the testplan then...

**Comment by sriyerg** [comment]
Done in #14508. Thanks!
