### ISSUE TITLE
[chip-test] chip_sw_pwrmgr_random_sleep_all_wake_ups

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#14166]
### Test point name

chip_sw_pwrmgr_random_sleep_all_wake_ups

### Host side component

None Required

### Contact person

@msfschaffner

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by msfschaffner** [comment]
This still needs to be added to the chip-level testplan.

**Comment by tjaychen** [comment]
testplan added in #14440
