### ISSUE TITLE
[chip-test] chip_sw_nmi_irq

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#14168]
### Test point name

[chip_sw_nmi_irq](https://github.com/lowRISC/opentitan/blob/b65e2705eb4ee814b46939d44f84d1adfee133c3/hw/top_earlgrey/data/chip_testplan.hjson#L2662)

### Host side component

None Required

### Contact person

@msfschaffner 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by engdoreis** [comment]
I started the test and I'm not able to acknowledge the alert handler nmi. Once it fires for the first time it never stops again.
This is the snippet from my `nmi_handler`.
```c

void ottf_external_nmi_handler(void) {
   isr_testutils_alert_handler_isr(
        plic_ctx, alert_handler_ctx,
        (top_earlgrey_plic_peripheral_t *)&expected_peripheral,
        (dif_alert_handler_irq_t *)&irq);

    CHECK_DIF_OK(dif_alert_handler_alert_acknowledge(
        alert_handler_ctx.alert_handler,
        kTopEarlgreyAlertIdPwrmgrAonFatalFault));
 
  dif_rv_core_ibex_nmi_state_t nmi_state = {0};
  CHECK_DIF_OK(dif_rv_core_ibex_get_nmi_state(&rv_core_ibex, &nmi_state));

  LOG_INFO(
      "%s:\n\t"
      "alert_enable:%x\n\talert_raised:%x\n\twdog_enable:%x\n\twdog_raised:%"
      "x\n\t",
      __func__, nmi_state.alert_enabled, nmi_state.alert_raised,
      nmi_state.wdog_enabled, nmi_state.wdog_barked);

  CHECK_DIF_OK(dif_rv_core_ibex_clear_nmi_state(&rv_core_ibex,
                                                kDifRvCoreIbexNmiSourceAll));
  }
```
These are the steps:
- Acknowledge the irq on the alert_handler.
- Acknowledge the irq on the plic.
- Clear nmi state on the rv_core_ibex.

Am I missing something or could that be a bug?

**Comment by tjaychen** [comment]
NMI's are technically considered an escalation phase.
So to stop `alert_handler` from emitting them, you actually need to clear alert escalation (prevent it from continuing escalation). 

@cindychip and @msfschaffner know the protocol better than I do, but there should be an associated DIF function for that.

**Comment by engdoreis** [comment]
Yeah, clear the escalation worked, I thought that calling `dif_alert_handler_alert_acknowledge` would be enough.
Thanks @tjaychen !!

**Comment by msfschaffner** [comment]
Yeah the `dif_alert_handler_alert_acknowledge` function just clears the cause register, it does not actually abort the escalation protocol.
