### ISSUE TITLE
[chip-test] chip_sw_random_sleep_pin_wake

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#14163]
### Test point name

chip_sw_random_sleep_pin_wake

### Host side component

None Required

### Contact person

@msfschaffner

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by msfschaffner** [comment]
This still needs to be added to the chip-level testplan.

**Comment by tjaychen** [comment]
This item can potentially be addressed by chip connectivity tests.
@cindychip

**Comment by msfschaffner** [comment]
@sriyerg we will have to update this issue once the testplan alignments have been merged.

**Comment by tjaychen** [comment]
it's really the same thing. The only difference is that we wanted random transition in and out of different sleep states.

**Comment by eunchan** [comment]
> it's really the same thing. The only difference is that we wanted random transition in and out of different sleep states.
>
Hum, then I can modify prev. test to enter in/out from low/ deep power down states randomly (it is already TODO in the code)

**Comment by tjaychen** [comment]
> > it's really the same thing. The only difference is that we wanted random transition in and out of different sleep states.
> 
> Hum, then I can modify prev. test to enter in/out from low/ deep power down states randomly (it is already TODO in the code)

yeah definitely. Then a single test can cover both test points.

**Comment by eunchan** [comment]
https://github.com/lowRISC/opentitan/pull/15062 now covers random sleep too. Let me close this ticket. `chip_sw_sleep_pin_wake` covers both cases.
