### ISSUE TITLE
[chip-test] chip_sw_sleep_pin_wake

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#14160]
### Test point name

[chip_sw_sleep_pin_wake](https://github.com/lowRISC/opentitan/blob/b65e2705eb4ee814b46939d44f84d1adfee133c3/hw/top_earlgrey/data/chip_testplan.hjson#L375)

### Host side component

None Required

### Contact person

@msfschaffner

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [x] Bazel build rules developed
- [ ] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by eunchan** [comment]
I am looking at this if I can code the test.

**Comment by eunchan** [comment]
`pwrmgr` can wake up the chip by `slow_peri_reqs.wakeups` (after masked by `reg2hw.wakeup_en`). `*_peri_reqs` type is `pwr_peri_t`. The *top_earlgrey* assigns 6 wakeup events as below:


| Index | Instance         |
|-------|------------------|
| 0     | sysrst_ctrl_aon  |
| 1     | adc_ctrl_aon     |
| 2     | pinmux_aon (pin) |
| 3     | pinmux_aon (usb) |
| 4     | aon_timer_aon    |
| 5     | sensor_ctrl      |

Need to enable bit 2 of wakeup_en and configure pinmux

**Comment by eunchan** [comment]
PR has been updated. The test is ready to be merged. However https://github.com/lowRISC/opentitan/pull/14776 needs to be merged then this PR needs revision based on that. I will hold the PR open until the thing is sorted out.
