### ISSUE TITLE
[test-triage] chip_sw_rv_core_ibex_rnd

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#14206]
### Hierarchy of regression failure

Chip Level

### Failure Description

  ERROR: Skipping 'sw/device/tests/rv_core_ibex_rnd_test:1_sim_dv': no such package 'sw/device/tests/rv_core_ibex_rnd_test': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.

### Steps to Reproduce

- GH revision: [9c0b24ddb](https://github.com/lowrisc/opentitan/tree/9c0b24ddbeb5616bd8db661ec1395f2d4f326bc4)
- util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_rv_core_ibex_rnd --build-seed 2483310614 --fixed-seed  2617385083

**Comment by moidx** [comment]
Closed by #14229
