### ISSUE TITLE
[test-triage] mask_rom_e2e_bootup_success

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#14209]
### Hierarchy of regression failure

Chip Level

### Failure Description

Test mask_rom_e2e_bootup_success has 1 failures.

0.mask_rom_e2e_bootup_success.3436865675
Log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.mask_rom_e2e_bootup_success/out/run.log

  Loading: 0 packages loaded
  Loading: 0 packages loaded
  ERROR: Skipping '//sw/device/silicon_creator/mask_rom:e2e_bootup_success_sim_dv': no such target '//sw/device/silicon_creator/mask_rom:e2e_bootup_success_sim_dv': target 'e2e_bootup_success_sim_dv' not declared in package 'sw/device/silicon_creator/mask_rom' defined by /workspace/mnt/repo_top/sw/device/silicon_creator/mask_rom/BUILD
  WARNING: Target pattern parsing failed.
  ERROR: no such target '//sw/device/silicon_creator/mask_rom:e2e_bootup_success_sim_dv': target 'e2e_bootup_success_sim_dv' not declared in package 'sw/device/silicon_creator/mask_rom' defined by /workspace/mnt/repo_top/sw/device/silicon_creator/mask_rom/BUILD
  INFO: Elapsed time: 23.264s
  INFO: 0 processes.
  FAILED: Build did NOT complete successfully (1 packages loaded)
  FAILED: Build did NOT complete successfully (1 packages loaded)
  make: *** [/workspace/mnt/repo_top/hw/dv/tools/dvsim/sim.mk:73: sw_build] Error 1

### Steps to Reproduce

- GH revision: [9c0b24ddb](https://github.com/lowrisc/opentitan/tree/9c0b24ddbeb5616bd8db661ec1395f2d4f326bc4)
- util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i mask_rom_e2e_bootup_success --build-seed 2483310614 --fixed-seed 3436865675

**Comment by johngt** [comment]
Note per change announced on 16 August, mask_rom is now known as rom.
Same issue from 16 August but under a new name
https://reports.opentitan.org/hw/top_earlgrey/dv/2022.08.16_16.23.56/results.html
