### ISSUE TITLE
[fpv] Add a testbench for prim_double_lfsr

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14232]
Add a FPV testbench for prim_double_lfsr, please remember to add assertions to check `err_o` goes out of sync.

**Comment by msfschaffner** [comment]
Deferring this to M3 as part of V3 coverage closure. Related: #14847

**Comment by cindychip** [comment]
This is already checked in individual IPs:
if the IP has double_LFSR, the design will have assertions: `ASSERT_PRIM_DOUBLE_LFSR_ERROR_TRIGGER_ALERT`,
Then in sec_cm FPV testbench, we will blackbox both `prim_lfsr `, and trigger `err_o` output.
So this is already covered in security IPs FPV bench.

Please feel free to re-open the issue if you have any questions.
