### ISSUE TITLE
[dvsim] "-i all" doesn't work when running all the sim_cfgs

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#14245]
> util/dvsim/dvsim.py hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson -i **all** -n

When I run the command above, I got these errors. The first 2 errors are fine, although we'd better fix them, but the 3rd error kills the regression.
> ERROR: [Modes] Test "chip_sec_cm" added to regression "V2S" not found!
> ERROR: [Modes] Test "chip_tl_intg_err" added to regression "V2S" not found!
> **ERROR: [SimCfg] "primary_build_mode: default" in prim_lfsr cfg is invalid. Please pick from {'prim_lfsr_dw_24', 'prim_lfsr_dw_8'}**.

-----

When I changed to "nightly", it's fine, so it doesn't affect our nightly regression.
> util/dvsim/dvsim.py hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson -i **nightly** -n 

It doesn't have the third error, and the regression starts normally.

> ERROR: [Modes] Test "chip_sec_cm" added to regression "V2S" not found!
> ERROR: [Modes] Test "chip_tl_intg_err" added to regression "V2S" not found!
> INFO: [ot_common] [prep_vm]: [tar]: Creating /usr/local/google/home/weicai/ot/repo_chip/scratch/repo_top.tar.gz for /usr/local/google/home/weicai/ot/repo_chip.
> INFO: [ot_common] [prep_vm]: [gcs]: Uploading /usr/local/google/home/weicai/ot/repo_chip/scratch/repo_top.tar.gz to opentitan.
> INFO: [ot_common] [prep_vm]: [gcs]: Upload of /usr/local/google/home/weicai/ot/repo_chip/scratch/repo_top.tar.gz complete.
> 
>   [   legend    ]: [Q: queued, D: dispatched, P: passed, F: failed, K: killed, T: total]                                                                
> 00:00:32  [    build    ]: [Q: 0000, D: 0080, P: 0000, F: 0000, K: 0000, T: 0080]   0%  i2c:default, i2c:cover_reg_t..                                          
>           [     run     ]: [Q: 0000, D: 0000, P: 0000, F: 0000, K: 0000, T: 1055]   0%   

BTW, this isn't related to the recent update on run_timeout_mins. The issue occurs regardless of that patch.

**Comment by sriyerg** [comment]
Yes - this is due to the fix https://github.com/lowRISC/opentitan/pull/14055/commits/51000a8bebdd0d89219dde371f02e66c29316699 that was made to resolve the incorrect chip level coverage issue. 

`prim_lfsr` config lists 2 tests - one for smoke and the other for nightly. Both use a different build mode, which are mutually exclusive. This is an unexpected usage model. We can fix this by renaming the `prim_lfsr_dw_24` build mode to `default`.
