### ISSUE TITLE
[ci] Deprecation warning: ubuntu-18.04 environment

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#14260]
I saw the following warnings on the azure pipelines page. It looks like we should start thinking about moving to a newer version.

![image](https://user-images.githubusercontent.com/57949550/184512043-04064f23-a33c-4520-8d60-29faabf64028.png)

cc @arunthomas @moidx @timothytrippel @cfrantz

**Comment by moidx** [comment]
See also #13521

**Comment by alphan** [comment]
Closing as a dup of #13251, thanks @moidx
