### ISSUE TITLE
[prim] cdc cross reset issue

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#14287]
most of our prim cdc modules take two resets and two clocks. 
we occasionally get into a weird situation where only one side of these modules reset, and that causes creation of fake events, for example in #14086 

we could deal with this natively in the cdc module, ie, any time one side resets the other side must reset as well.
To do so we would need to pass both the scan reset and scan mode indication to these prim modules, since the cross reset logic would otherwise not be controllable by DFT. 

the other option is that we leave the handling of such a scenario to the instantiator of the module, and add some simple logic that checks to ensure both sides are reset before proceeding. 

Are there any preferences? The cross reset control impact would be pretty big at this point, so my preference is generally to leave this to the instantiator.  The other reason I tend to prefer the instantiator is just because the cross module reset, it doesn't mean the source / destination modules have stopped doing whatever they're doing. So the impact is likely going to be larger than a single point.  Still, it can be very convenient. 

There are not that many cases in our design where resets cross roots, so most of the time special handling is pretty minimal.

**Comment by GregAC** [comment]
I feel at this stage we should drive all decisions based upon impact, so unless we have strong reasons to implement this natively to the CDC module we should go for asking the instantiator to deal with it. Perhaps we should do a quick review of uses of this module to check the assumption this option has lesser impact?

**Comment by vogelpi** [comment]
Thanks @tjaychen for summarizing the situation and outlining options. I agree with you that this is probably better left to instantiators. Getting the reset of CDCs right is tricky and tends to get more involved, especially as one wants to cover all possible use and corner cases. I think there are cases where it's potentially worth doing (see e.g. debug module) but I have seen quite some cores (on FPGA) where it's not handled either and instead core designers ask instantiators to take care of it. To me it sounds reasonable to do the same here.

What we should do is adding some assertions to check if the CDC isn't properly reset to explicitly flag the "incorrect" usage to instantiators.

**Comment by Jacob-Levy** [comment]
This prim cell has two issues. The first that you call CDC is not just CDC it is also functional. The second is functional too and involve getting a new pulse when the current one is still active. Both can be address with-in the prim cell with very low involvemenet of the instantiator.  See issue #14282.

**Comment by tjaychen** [comment]
@Jacob-Levy to me having an active pulse while handshaking is ongoing is yet another instantiator issue. The fact that there's a busy push back on a new pulse potentially means a new event could be ignored, depending on how the module is used. 

That's also why I prefer erroring out (via assertion) in that case and asking the instantiator to deal with it.  For example we have had cases in `adc_ctrl` where this situation comes up and we needed extra logic to hold events until handshake is complete.

**Comment by tjaychen** [comment]
although i agree with @Jacob-Levy , adding a `busy_o` indication would be kind of nice.

**Comment by eunchan** [comment]
+1 to initiator. I always assume that the both side resets in CDC modules come from _a single source_, whether adding reset synchronizer to other side clock domain or not. If we decide the initiator to deal with the issue. Will we mandate reset synchronizer?

**Comment by Jacob-Levy** [comment]
This assumption that the both side resets is not correct and that how this issue was found a year ago in the RNG logic.
The fix to the issue inside the cell is simple and only requies one more input, scanmode, for DFT.

```
// Reset all flops by both resets
////////////////////////////////////////
logic rst_src_n, rst_dst_da_n;
logic rst_dst_n, rst_src_da_n;

prim_flop_2sync #(
  .Width ( 1 ),
  .ResetValue ( 1'b0 )
) u_rst_dst_da (
  .clk_i ( clk_src_i),
  .rst_ni ( rst_dst_ni ),
  .d_i ( 1'b1 ),
  .q_o ( rst_dst_da_n )
);

prim_flop_2sync #(
  .Width ( 1 ),
  .ResetValue ( 1'b0 )
) u_rst_src_da (
  .clk_i ( clk_dst_i),
  .rst_ni ( rst_src_ni ),
  .d_i ( 1'b1 ),
  .q_o ( rst_src_da_n )
);

assign rst_src_n = scan_mode_i ? rst_src_ni : rst_src_ni && rst_dst_da_n;
assign rst_dst_n = scan_mode_i ? rst_dst_ni : rst_dst_ni && rst_src_da_n;
```

**Comment by eunchan** [comment]
If I instantiate Async FIFOs (for instance inside the TL-UL), I will create a reset signal for TL-UL then sync to other clocks. This guarantees single reset source resets entire logic fully.

There're some cases I can't put synchronizers. For instance SPI_DEVICE has no SPI_CLK when sys reset signal is asserted. So in SPI_DEVICE I directly use sys_rst_ni for async FIFOs or logics crossing both clock domains (sys->spi_clk). It is safe, as there will be no SPI_CLK when releasing sys_rst_n.

Anyhow, I always vote for moving reset mux and clock mux / gates to top most level as possible. So, +1 to initiator.

**Comment by Jacob-Levy** [comment]
SPI is a special case and pulse_syncronizer were developed for traditional clock domain data clrossing.

**Comment by jeoongp** [comment]
Sorry for late comment. 
I agree with the baseline idea that we need to minimize 1. any potential risk 2. RTL-QA/DV efforts. I think option 1 (handing in initiator) is to follow both requirements if this cross-reset handling is needed in the minimum cases. At least, we don't need to touch the existing cdc modules which were already verified. 

Option 2 (handling in cdc module) looks simple and good. If we have this new common module in the prim lib, we can also save RTL work effort for cross-reset spots. 

I recommend to combine option 1 and 2 to get both advantages. That is, we can create another prim library as described in https://github.com/lowRISC/opentitan/issues/14282. Since the number of cross-reset spots are minimum, each designer can check if we can cover the cross-reset issue by this new prim module or similar logics in the initiator. It depends on designers who are responsible. 

I also worked for CDC issues in SPI_DEVICE with @eunchan. I strongly recommend to keep the existing prim instances (prim_reg_cdc) instead of renaming it to a new one which may need unnecessary RTL-QA efforts.

**Comment by tjaychen** [comment]
this is now part of #15317.
When that issue is addressed, this should automatically be resolved.

**Comment by tjaychen** [comment]
unassigning everyone since it is now part of another issue.
