### ISSUE TITLE
[AES] csr bitbash test fail - cannot update bit in mode_reg

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#1428]
TEST_NAME=aes_csr_bitbash
SEED = any
The bit bash test fails to set mode reg[0] to 1 and fails.
VCD is 28Mb and has been shared through box link email
![image](https://user-images.githubusercontent.com/53917183/73252089-745a0300-41ba-11ea-8802-0694c3cc0769.png)

**Comment by vogelpi** [comment]
Hi @rasmus-madsen and thanks for opening the issue. I cannot access the box as I don't have paid account. Please consider sharing the VCD via our team drive or upload it here. You can just drag the file into the message window. You might need to zip it though.

**Comment by eunchan** [comment]
> One might say that a `hro` register should not feed a `d`-signal into the register file but having `hwext` basically means to give full control to the hardware anyway (so even if the `d`-input of the `prim_subreg_ext` is tied to 0, the hardware can overwrite `hro` fields, software just does not see it). Maybe @eunchan can share his opinion here

Personally, I like the approach of #1435 . If HW wants to give the feedback to the register interface, it should be `hrw` type. the intention of `hwext` is to give the full control to the HW. So, it is wise to generate warning in case of `hwext: true` and `hwaccess: hro`.

**Comment by vogelpi** [comment]
Thanks for your feedback @eunchan. A warning sounds like a good idea. I will create a PR to let reggen produce a warning for combinations of `hwext: true`, `hwaccess: hro` and `rw`.

**Comment by rasmus-madsen** [comment]
@senelson7 adding for interest :D
