### ISSUE TITLE
[kmac] Status register question

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14286]
Hi Eunchan,

When I am trying remove the cycle accurate scb in status register, I wanted to clarify this question.
This is related to change: https://github.com/lowRISC/opentitan/pull/9276/files

With this change, when KMAC starts to writes input data, there is one clock cycle where status register has the following output:
1). FifoEmpty  -> 0
2). FifoFull      -> 0
3). Fifo Depth -> 0
I think 1) and 3) cannot be 0 at the same time. But this output only last for one clock cycle.
Please let me know if I misunderstand anything :)

![image](https://user-images.githubusercontent.com/11466553/184736475-8e6fa1b4-d443-4cf9-8aa0-c8886b8881c3.png)

Thanks,
Cindy

**Comment by eunchan** [comment]
As described in #9276, The logic intentionally lowers the empty signal even if the FIFO does not have to store the data internally (`Pass` parameter is `1'b1`). However, the `depth` represents how many entries the FIFO currently stores.

We could change the logic to show the # of entries + current outgoing entry. It affects timing though.

**Comment by cindychip** [comment]
> As described in #9276, The logic intentionally lowers the empty signal even if the FIFO does not have to store the data internally (`Pass` parameter is `1'b1`). However, the `depth` represents how many entries the FIFO currently stores.
> 
> We could change the logic to show the # of entries + current outgoing entry. It affects timing though.

Thanks for explaining! 
Oh I see what you mean by lowers the empty fifo signal now.
I do not mind keeping the current design if sw is fine with it and maybe we can mention that in the register description?
If we plan to change the logic, that is fine too. I am working on removing the cycle-accurate scb.
So up to you in terms of what is the best design approach :)

Thanks,
Cindy

**Comment by eunchan** [comment]
Let's keep the design as is and update the doc. If this really bothers SW folks, then we can update in the next version.

**Comment by cindychip** [comment]
Sounds good, thanks Eunchan!

**Comment by eunchan** [comment]
Let me close this as the change has been merged.
