### ISSUE TITLE
[sw/silicon_creator] Add doc describing OTP settings

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#14303]
We should add a doc describing where to find the list of OTP settings and the policy for deciding what goes in the creator versus owner partitions. 

Maybe here? `sw/device/silicon_creator/rom/docs/otp.md`

_Originally posted by @moidx in https://github.com/lowRISC/opentitan/pull/14289#pullrequestreview-1074442109_

**Comment by msfschaffner** [comment]
CC @timothytrippel @cfrantz

**Comment by timothytrippel** [comment]
Moved to manufacturing board as this will be completed soon.
