### ISSUE TITLE
[otbn] `WDR[31] == ACC ISPR` when doing internal secure wipe

### ISSUE THREAD

**Issue by ctopal** [lowRISC/opentitan#14324]
While I was working on writing assertions for secure wipe countermeasure, I saw that our last WDR has the same value as ACC ISPR while doing an internal secure wipe. I think that happens because we are writing them at the same cycle with the value from URND. Not exactly sure if that's a big problem. @andreaskurth @vogelpi  WDYT?

**Comment by andreaskurth** [comment]
While I don't think it's a big or critical problem, it's not ideal. We should be able to fix this relatively easily. Each round of secure wipe will take a cycle longer, though, but that should not be critical either.

Do you agree, @vogelpi?

**Comment by vogelpi** [comment]
Yes, I agree that this is not ideal and that also one additional secure wipe clock cycle isn't critical. Thanks for flagging this.
