### ISSUE TITLE
[csr/doc] csr tests could use better documentation

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#1432]
I have not been able to find a good explanation of what the different CSR tests actually do.
I think to help improve debug time I think adding some more comments beside
![image](https://user-images.githubusercontent.com/53917183/73276069-64f1ae80-41e8-11ea-99a7-218a7f67cc6d.png)
 would make it easier for Designers to debug what is happening and therefor why it is failing.

it would also make designers able to recognize if a given CSR test is supported or not.
I realise one can find all this information by digging through the code but I don't think that is what we want.

This documentation might exist somewhere I but I wasn't able to find it.

**Comment by cindychip** [comment]
Hi Rasmus, 

1). There are some brief descriptions about CSR sequences in [README.md](https://github.com/lowRISC/opentitan/blob/master/hw/dv/sv/csr_utils/README.md).

2). I believe supported CSRs tests can be found in DV plan testsplans.

Hope it helps

**Comment by rasmus-madsen** [comment]
thank you @cindychip  that was helpfull. the format in the opentitan online doc is a bit strange so I missed that when reading the documentation. I still think it would make sense to add the explanation to the RTL.

**Comment by weicaiyang** [comment]
> thank you @cindychip that was helpfull. the format in the opentitan online doc is a bit strange so I missed that when reading the documentation. I still think it would make sense to add the explanation to the RTL.

@rasmus-madsen most of the documents are markdown format (.md). I think it's good to add description for each CSR seq in the sv file.

**Comment by rasmus-madsen** [comment]
@weicaiyang the comment about the format was not about markdown but that the list is not formatted in a way that I would expect.
I would have like the testname to be bold, the bullets to be indented or some added space between testname and explanation.

all I was trying to say was that during my scan of the document I missed this section do to the formatting.

![image](https://user-images.githubusercontent.com/53917183/73400078-b4b79f00-42e8-11ea-9378-12fdad9bb85d.png)

anyway I think I can close this issue?

**Comment by weicaiyang** [comment]
> @weicaiyang the comment about the format was not about markdown but that the list is not formatted in a way that I would expect.
> I would have like the testname to be bold, the bullets to be indented or some added space between testname and explanation.
> 
> all I was trying to say was that during my scan of the document I missed this section do to the formatting.
> 
> ![image](https://user-images.githubusercontent.com/53917183/73400078-b4b79f00-42e8-11ea-9378-12fdad9bb85d.png)
> 
> anyway I think I can close this issue?

I see. Thanks for the explanation. we can close this issue now.
