### ISSUE TITLE
[chip-test] chip_sw_sleep_pin_retention

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#14352]
### Test point name

[chip_sw_sleep_pin_retention](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/chip_testplan.hjson#L387)

### Host side component

SystemVerilog

### Contact person

@tjaychen 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)  _Yes - `chip_sw_sleep_pin_wake`_
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by sriyerg** [comment]
Note that for this test, it will be preferred to reuse the `chip_sw_sleep_pin_wake` test which does not appear to be developed yet.

**Comment by eunchan** [comment]
`chip_sw_sleep_pin_mio_dio_val` covers this test. Let me assign this to me and revise testplan to point to the `sleep_pin_mio_dio_val` test after it is implemented.

**Comment by eunchan** [comment]
One thing `chip_sw_sleep_pin_mio_dio_val` misses is to check the active output value after wake-up. I think adding the output value checking logic to `chip_sw_sleep_pin_wake` makes sense.

**Comment by eunchan** [comment]
I am working on this.
