### ISSUE TITLE
[dv/flash_ctrl] shorten open source RMA time

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#14395]
#14365 showed that because of flash rma, the test run time is VERY long.
This is due to the fact that the rma entry process has a combination of erase, program and reads.

In the open source modeling, the program is just blindly set to take 50 cycles, a lot of time is wasted just waiting for something that really only takes 1 or 2 cycles. We should allow this to be an exposed build time option such that for specific tests we can shorten the overall run-time.

**Comment by tjaychen** [comment]
could folks on the dv side let me know if this is a bad idea? We do something similar for interrupts, where sometimes we slow down the read latency to hit different corner cases. 

This obviously has no impact on the "real" model, it only impacts the open versions.

**Comment by weicaiyang** [comment]
I think it's a good idea. This will be very useful to DV.

**Comment by sriyerg** [comment]
SGTM.

**Comment by cindychip** [comment]
I like this idea too!
