### ISSUE TITLE
[reg] consider naming of regtool keys `hwre` and `hwqe`

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/opentitan#144]
The definitions of `hwre` and `hwqe` and named to indicate that they are needed by the hardware (implicitly created by effects of software). Consider switching to something that indicates that they are software effects. Unfortunately we already have `swrdaccess` and `swwraccess` so we would need to be a little careful here.

**Comment by vogelpi** [comment]
I like "hint" as well.

As for the actual names: `swaccess` and `hwaccess` are the key names indicating the permission for SW and HW, respectively. They can be `(h)rw`, `(h)ro` and `(h)wo`. Maybe to follow a similar scheme, the key for the hint could be `swhint` and the values `none`, `rw`, `ro`, `wo`? Maybe just `none` and `rw` would be enough.

**Comment by vogelpi** [comment]
Shall we close this issue? I think most people are totally okay withe the current naming of these signals.

**Comment by tjaychen** [comment]
fine with me to close.

**Comment by vogelpi** [comment]
Alright, thanks for the feedback @tjaychen . We can always reopen this if needed.
