### ISSUE TITLE
IWYU for memcpy, memset, etc.

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#14401]
It looks like there are a number of places that we call memcpy() and friends without including the declaration.

We should add `#include "sw/device/lib/base/memory.h"` to any files that need it.

This query is far from a full audit, but it's a start: https://cs.opensource.google/search?q=file:c$%20memcpy%20-memory%5C.h%20-file:vendor&ss=opentitan&start=1

**Comment by msfschaffner** [comment]
CC @mundaym @timothytrippel @cfrantz
