### ISSUE TITLE
[ci] CI linked past results no longer accessible NoSuchKey

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#14424]
Likely due to the changes being worked on in CI currently.

When looking at past results linked from https://reports.opentitan.org/hw/top_earlgrey/dv/latest/results.html the older entries are showing NoSuchKey errors.
Accessing a past result such as https://reports.opentitan.org/hw/top_earlgrey/dv/2022.08.16_16.23.56/results.html will cause an error.

Error when looking at a past result:
```
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
</Error>
```

**Comment by ctopal** [comment]
I believe it's related with the fix here: https://github.com/lowRISC/opentitan/pull/14423

**Comment by ctopal** [comment]
We also don't have visibility to the summary: https://reports.opentitan.org/hw/top_earlgrey/dv/summary/latest/report.html

**Comment by moidx** [comment]
We are working on enabling the reports again. Will provide an update once they are available.

**Comment by moidx** [comment]
This is now resolved. Links have been updated in the hw dashboard.

**Comment by HU90m** [comment]
The reports are not working again. 

Looks to be the same problem again although now [even block specific links](https://github.com/lowRISC/opentitan/issues/14424#issuecomment-1222319024) are not working.

**Comment by HU90m** [comment]
Very sorry just re-read the [last comment](https://github.com/lowRISC/opentitan/issues/14424#issuecomment-1228672704). I was trying to use an old link.
