### ISSUE TITLE
Pin Python dependencies to a specific version

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1444]
We currently have a `python_requirements.txt` file, which lists Python packages we need. But except in some cases, we don't specify a specific version to use. There are multiple approaches to add a lock or freeze file to ensure that developers use the exact same version of the dependencies as we use.

Find a suitable approach, implement it, and update the documentation accordingly (including mechanisms/processes how and when to update the frozen dependencies).

**Comment by towoe** [comment]
Just for clarification, should we also include indirect dependencies?
Not sure how the Python package management works, but assuming we have the current state:
ot.py:v1 -> direct.py:v1 -> indirect.py:v2
and this is updated to
direct.py:v1 -> indirect.py:v2.1 (which does not break anything for direct.py) we now have indirect.py:v2.1 which could break something in our system. (Not sure if those version bumps are allowed.)

In essence, should we list all python packages in `python_requirements.txt`?

**Comment by imphil** [comment]
Yes, indirect dependencies need to be captured as well. 

The goal would be not to have that in python_requirements.txt, but instead have a separate lock or freeze file. There are multiple approaches to do that in the Python packaging world, and I forgot which one is currently en vogue.

**Comment by towoe** [comment]
Okay, thanks Philipp!
Sounds like we need a go.mod and go.sum ;)

**Comment by msfschaffner** [comment]
@timothytrippel is addressed by now with the hermetic build support from bazel?

**Comment by timothytrippel** [comment]
This has already been completed.
