### ISSUE TITLE
[sw/silicon_creator] Move bootstrap docs to md

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#14443]
We should move these docs to markdown. Ok if it is under a bootstrap section under ROM docs.

_Originally posted by @moidx in https://github.com/lowRISC/opentitan/pull/14402#discussion_r951901387_

**Comment by alphan** [comment]
Also [this](https://docs.google.com/document/d/1i6V3tFTv0UhWeM-IGCxgxkC07Bo_zpbgr6u1KE1Rehs/edit?resourcekey=0-L-XaP9QeLAkEsp8najVkUQ)

**Comment by cfrantz** [comment]
Done by #17960
