### ISSUE TITLE
[kmac] err_chk state not consistent with the sha3 pad state

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14470]
Hi Eunchan,

I want to confirm with behavior with you regarding the `en_unsupported_modestrength` usage.

Here is my sequence:
1). Set the `en_unsupported_modestrength` to 0 and set incorrect mode strength.
2). Issue `start` command -> SW err_code gives `ErrUnexpectedModeStrength`. (This is what we expect)
     And we expect the sha3 engine to ignore this cmd `start`, and this is correct as well.
     But in `u_errchk`, the state machines accept the cmd `start` and goes to `MsgFeed`state.
     ===> This is NOT what I expect.
3). Continue to stream in kmac message -> SW err_code gives `ErrSwPushMsgFifo`. (This is what we expect as well)
4). Issue `process` cmd -> Here design does not return an error.
     ===> This is not what I expect.

I think it would make more sense to align the `u_errchk/st` with the sha3 engine state.

Please let me know what you think!

![image](https://user-images.githubusercontent.com/11466553/186052458-050b976e-cf0f-441f-95a5-d0f878f2d336.png)

**Comment by eunchan** [comment]
Thanks! I will check the design and fix the behavior
