### ISSUE TITLE
[prim] Make alert outputs from primitives compatible with comportable IPs

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#14472]
Alerts output from `prim_flash` and `prim_otp` are currently handled in a very custom way which is not compatible with the common DV infrastructure for common alert sources like sparse FSMs, bus integrity and the like. I.e., the alerts are currently sent over to AST, and then back into `sensor_ctrl` to feed them into the comportable alert subsystem.

In order to leverage the common DV infrastructure and increase the level of standardization at the prim* interface (for ease of future integrations), we have decided to change this and feed alert events emanating from primitives into the alert sender infrastructure of the instantiating IP.

Task burndown list:

- [x] Align `otp_ctrl` and `prim_otp` in both open and closed source repositories https://github.com/lowRISC/opentitan/pull/14487
- [x] Align open-source DV environment for `otp_ctrl` https://github.com/lowRISC/opentitan/pull/14487
- [x] Align `flash_ctrl` and `prim_flash` in both open and closed source repositories https://github.com/lowRISC/opentitan/pull/14639
- [x] Align open-source DV environment for `flash_ctrl` https://github.com/lowRISC/opentitan/pull/14639
- [x] Update documentation #14720
- [x] Remove corresponding alert signals and logic from `sensor_ctrl` #14721 #14763
- [x] Remove corresponding alert signals and logic from `ast` #14721 #14763

While the change is technically on the RTL side, this will unblock some DV work needed for M2.

**Comment by msfschaffner** [comment]
CC @tjaychen @jdonjdon @cindychip @arnonsha

**Comment by arnonsha** [comment]
@danaagur

**Comment by msfschaffner** [comment]
Closing since all the open-source adjustments are now complete.
