### ISSUE TITLE
[hmac] Received Message Length doesn't account for byte granularity writes

### ISSUE THREAD

**Issue by jon-flatley** [lowRISC/opentitan#1449]
In a test on jon-flatley/opentitan@b9b6fd5a3ff2550ff0b746af01ba333f40928f89 I'm seeing an issue where the the `mac.MSG_LENGTH_LOWER` and `mac.MSG_LENGTH_UPPER` registers are not reflecting the trailing 2 bytes written to the FIFO.

The written message is 142 bytes (1136 bits) passed by writing 35 32-bit words to the FIFO making up the first 140 bytes of the message, followed by 2 8-bit writes to the FIFO.

The resulting digest in with `hmac_en = 0` correctly matches the SHA256 hash of the 142-byte message, but a decimal value of 1120 is read from `mac.MSG_LENGTH_LOWER`, not reflecting the last 2 bytes.

Steps to reproduce:
1. Checkout b9b6fd5a3ff2550ff0b746af01ba333f40928f89
2. Build and load the HMAC DIF test:
```
ninja -C build-out/sw/fpga && build-bin/sw/host/spiflash/spiflash \
--input build-bin/sw/device/fpga/tests/hmac/dif_hmac_test.bin`
```
3. Observe the UART output:
```
Running HMAC DIF test
Testing SHA256 mode...
Message length mismatch. Expected 1136 bits but got 1120 bits.
PASS!

Testing HMAC mode...
Message length mismatch. Expected 1136 bits but got 1120 bits.
PASS!
```

**Comment by sjgitty** [comment]
@eunchan @cindychip

**Comment by cindychip** [comment]
Hi Jon, I saw you are:
1). set `hash_start`
2). steam in 142 bytes
3). read out msg length (it is 140 bytes because HW do not know if you are going to keep streaming in)
4). set `hash_process` -> I think if you check message length here, should be 142.

Please let me know if I misunderstand the code :)

**Comment by jon-flatley** [comment]
I see, when done in that order the message length is correct. It's confusing to me; I'm reading `fifo_depth` as 0 before reading the message length. Does this mean there's no way to check the message length before kicking off the HMAC run?

Maybe the docs should be more specific about this. The language "The HMAC IP will calculate the length of the message received between 1 being written to CMD.hash_start and 1 being written to CMD.hash_process" says to me that the message length should be computed before 1 is written to `CMD.hash_process`.

**Comment by cindychip** [comment]
I do not think the current implementation has a way to check accurate msg
length before kicking off HMAC run. That is a good point. Do you think it
is needed to support this feature? @eunchan

**Comment by eunchan** [comment]
The message length was right in front of the MSG_FIFO when HMAC didn't have the 
triger -> process feature (streaming). And prim_packer module is added to 
support the byte packing later. Apparently, the the message length calculation 
logic should've moved in front of the packer not as it was.

It is doable to move the message length cal logic to match with what the SW 
expects.

Thanks for the issue. I will create a PR to change the behavior in HMAC.

**Comment by eunchan** [comment]
The design change has just been merged. Thanks for the report!

**Comment by jon-flatley** [comment]
Thanks for the quick turn around on this!
