### ISSUE TITLE
[edn] prim_fifo_sync_gencmd

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#14506]
prim_fifo_sync_gencmd inside `edn` does not appear to be cleared automatically when `edn` is disabled.
As a result, whatever generate command that happens to be sitting in the FIFO is sent out as part of the next intsantiation.

In the wave below, you can see the fifo depth does not go to 0 even though enable becomes false.
![image](https://user-images.githubusercontent.com/1026250/186070135-a9db8fcd-7224-4199-863e-e863cc9ea634.png)

In the wave below, you can see 2 back to back generate commands being sent out, although these are part of two separate instantiations with a disable in the middle.
![image](https://user-images.githubusercontent.com/1026250/186070048-e4444c39-ed83-4f3b-a31e-d586cc0f90ca.png)

This seems to be because the generate fifo's clear is hardwired to 0 when enable is 0.  
I'm not sure if this was intentional or just a typo.

We could get around this issue by always resetting the FIFO's when disabling `edn`, but it would be good to know what the correct procedure is.

**Comment by tjaychen** [comment]
@moidx 
@timothytrippel

**Comment by mwbranstad** [comment]
@senelson7 can we re-create this in unit sim?

**Comment by tjaychen** [comment]
i think for now, when we issue an `edn` disable, i'm also going to explicitly clear FIFOs. I think that should also do the trick.

**Comment by tjaychen** [comment]
I'm going to move this to future release. This issue can be managed by software right now, but it would be nice to have this natively handled in the future.

**Comment by mwbranstad** [comment]
@tjaychen didn't this issue get fixed after @senelson7 put in a hw fix for state coverage?

**Comment by tjaychen** [comment]
uhhh... it is possible, but i will need to double check.
I can't completely remember this issue. I've moved it to future release anyways, so no need to worry about it for now :)
