### ISSUE TITLE
[ci,dv] scale up number of chip-level tests run in DV sim in presubmit

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#14532]
Only 2 chip-level tests are currently in private CI as presubmit checks using two different simulators. These include:
- two tests on VCS (`chip_sw_uart_tx_rx` and `chip_plic_all_irqs`)
- one test on Xcelium (`chip_plic_all_irqs`)

With our current SW license constraints, we have plenty of room to significantly scale up presubmit testing using Xcelium.

(After discussions with @mundaym this week at CHES) to do so will require:

- [x] determining which chip-level tests have short enough runtimes such that they can be run in presubmit
- [x] creating more regressions targets in [`chip_sim_cfg.hjson`](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/dv/chip_sim_cfg.hjson;drc=b1895e1ce74c9b791759a3df85467283a1ce902e;l=1263) to launch specific sets of tests on each VM used in the private CI (#15281); ensure tests are commented out to start with so they can be slowly activated to not overwhelm private CI VMs
- [x] add more jobs to the private CI YAML config file to spread load across multiple VMs (https://github.com/lowRISC/opentitan-private-ci/pull/21)
- [x] uncomment tests in the public `chip_sim_cfg.hjson` file:
    - #15454
    - #15466
    - #15578 
- [x] scale up private CI compute resources (if needed) so that we can handle running additional tests in parallel
    - completed by @mundaym on 10/29/2022

**Comment by sriyerg** [comment]
See related: https://github.com/lowRISC/opentitan/pull/14535
