### ISSUE TITLE
[otbn, rtl] One-hot write enable check in base RF should produce bad_internal_state error

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#14540]
Within the base register file we have a check that ensures the onehot write enable signal is actually onehot. If it fails it triggers a fatal error but it's a register integrity error. I think triggering a bad_internal_state error makes more sense.

Either way we need to ensure we have coverage for this scenario (should be a quick extension to https://github.com/lowRISC/opentitan/pull/14068 if we make it trigger a bad_internal_state).

@andreaskurth @vogelpi @ctopal what are your thoughts?

> estimate 2

**Comment by vogelpi** [comment]
I agree that a bad_internal_state error is the better choice here. I will look into this.

**Comment by andreaskurth** [comment]
I also agree.

@ctopal: Could you add this to the `bad_internal_state_cg` (which you added in #14068), if necessary with a new RTL probe, once the write enable check produces a `bad_internal_state` error?

**Comment by ctopal** [comment]
Would something like https://github.com/lowRISC/opentitan/pull/14573 work?

**Comment by matutem** [comment]
Notice https://github.com/lowRISC/opentitan/pull/14449 triggers this scenario. It currently expects alert 43 to be fired but it doesn't check the specific CSR bit to be set because of issue #14518.

**Comment by ctopal** [comment]
Implementation is completed with https://github.com/lowRISC/opentitan/pull/14575, and coverage work is done with https://github.com/lowRISC/opentitan/pull/14573. So, I think this is already completed, @GregAC WDYT?

**Comment by GregAC** [comment]
Yup looks good
