### ISSUE TITLE
[cryptolib] Error reporting

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#14549]
This issue is to capture error handling notes for the crypto library. 

Some notes on `status_t` provided by @cfrantz. 

**hardened checks**

> 1. `TRY` and `status_ok` (and friends) are not hardened. If they need to be, we might want to write an alternate 
>      implementation of those macros/functions that are hardened.
>  Also, `status_t` uses one bit to differentiate between good/bad status codes (the sign bit). The "bit hardness" of the status codes needs to be considered as well. In the mask ROM, the legacy `kErrorOk` is `0x739`; my PR to change the ROM over to `status_t` preserves this Ok value and all of the flow-control helpers (like `RETURN_IF_ERROR`) still depend on it. In pseudo-code, they are:
> 
> ```
> let result = some_operation();
> if (!(status_ok(result) && result.value == 0x739)) {
>     // error case
>     return result;
> }
> // good case, execution continues here
> ```

**Usage notes**

> All of the error macros (`INTERNAL()`, `INVALID_ARGUMENT()`, etc) encode the first three letters of the source file and the line number where the macro was invoked. This particular error code can be thought of as:
> 
> ```
> return {error: true, module: "ENT", arg: 168, code: kInternal};
> ```
> 
> You may want to set the module_id at the top of every C file to control the name. For, example, it _might_ be better for this file to:
> 
> ```
> DECLARE_MODULE_ID('K', 'A', 'T');
> ```
> 
> Additionally, if you want the `arg` to be something other than the line number in the source file, you can use any value in the range `0..2047` as an optional argument to the error macros:
> 
> ```
> // Think of this as {error: true, module: "KAT", arg: 13, code: kInternal}
> return INTERNAL(13);  // An extremely unlucky internal error.
> ```
> 
> For the `OK_STATUS()` macro, you may use any positive value in the range `0..INT_MAX`, hardening arguments notwithstanding.
> 
> ```
> // Think of this as {error: false, value: 777}
> return OK_STATUS(777); // Vegas baby!
> ```

**Comment by moidx** [comment]
CC @jadephilipoom @alphan

**Comment by alphan** [comment]
Also relevant: #14052
