### ISSUE TITLE
[csrng/edn] Add redundancy to EDN-to-CSRNG cmd interface

### ISSUE THREAD

**Issue by bilgiday** [lowRISC/opentitan#14542]
The `flag0` field of the CSRNG command header is represented as a single bit inside the EDN IP as well as between the EDN IP and the CSRNG IP. Inside the CSRNG IP, the `flag0` is converted to a MUBI4 signal to improve the resistance against glitching.

We can further improve the fault resistance by extending the protection to cover the `flag0's` transfer from EDNs to CSRNG (for the reseed and instantiate commands). This can be achieved by

- representing the `flag0` field as a MUBI signal inside the EDN (at the cmd registers and reseed cmd FIFO), and/or
- adding a simple error-detection/integrity-protection mechanism to the cmd interface between the EDNs and CSRNG

**Comment by moidx** [comment]
This issue also applies to all single bit encodings in the command interface (e.g. command ID). The Gen bits interface also has a single bit point of failure: 

`CSRNG_SW_CMD_STS_CMD_RDY_BIT`

**Comment by tjaychen** [comment]
There are two action items from the discussion

- [ ] Investigate the hardware path. How hard / possible is it to mubify the control path from edn all the way into csrng. Need to make sure we consider everything on the datapath
- [ ] If the above is not feasible, investigate how we should add a status register to capture the variables involved during instantiation. That status itself needs to be somewhat hardened (as explained by @bilgiday) to either reduce or eliminate the attack window or reduce the detection latency.

**Comment by bilgiday** [comment]
@johannheyszl and I are wondering if we can use some of the reserved bits [31:25] in the CSRNG command header to implement a hardware/firmware detection mechanism. The main idea is as follows:

-  Use some of the reserved bits to store redundant information for the `flag0` bit. 

- The redundancy mechanism can be  triple-modular redundancy, multi-bit encoding, differential encoding, or a checksum over the whole flag/command bits.

- The CSRNG hardware implements the logic to check the consistency between the `flag0` bit and the redundant bits before processing the command. If there is a mismatch, it generates an alert signal. 

Potential hardware/firmware changes:
- **Hardware**: Add the detection logic in the CSRNG IP, and connect it to CSRNG's alert generation logic.
- **Firmware**: Encode the CSRNG commands in accordance with the chosen redundancy scheme. 

@tjaychen, @moidx, @mwbranstad, what do you think? Would it be feasible to implement such a mechanism?

**Comment by mwbranstad** [comment]
We talked about this topic at the last OT security meeting. I looked that the RTL for CSRNG and saw that flag0 was a single bit in the command, but once processed, it was converted into a mubi4 value. Hardware-wise, it would be easiest to convert the flag0 single bit in the command into a mubi4, and then simply assign it to the flopped version within CSRNG as is. Currently there are no alerts assigned to this mubi4. Would it be recov or fatal? EDN would also require a matching change. As I said in the meeting, hardware-wise this is not that big of a change, but I suspect it will be a larger impact for DV unit test, firmware, and any c code tests.

**Comment by johannheyszl** [comment]
thx, the idea is to not change EDN and use RFU bits in the command for redundancy that are pass through for EDN.
IMHO this would be a fatal alert.

**Comment by tjaychen** [comment]
i agree with @mwbranstad, that seems like the best approach.
Are flags1/2/3 actually being used now? If not, we could just consume all of them for flag0, and make flag0 a mubi control.  That way we don't even need to change anything inside `EDN` or any storage elements along the way, we just need to change the interpretation on `CSRNG`.  If we do that, then hopefully the downstream changes won't be too bad.

For the alert, normally I would agree that fatal is better. However, since the command can actually be generated by software, it means an error could be generated on software mistake. We've typically left things that could have been caused by software as recoverable.

**Comment by johannheyszl** [comment]
thx @tjaychen, it seems we are all on the same page. I agree it's simpler to use the other 3 flag bits instead of RFU bits for mubi since those other flag bits aren't used atm.

**Comment by bilgiday** [comment]
Thanks for the feedback, that sounds good to me.

@tjaychen, afaik, the `flag 1/2/3` bits are currently not being used; they are RFU. We can consume them for `flag0`.

**Comment by tjaychen** [comment]
@mwbranstad any objections? This does mean we'll need to do some minor documentation update. 
But I feel like it feels a bit more streamlined than tacking on later bits.

**Comment by mwbranstad** [comment]
@senelson7 what do you think of this proposal? will require DV changes.
FYI, I will be out next week so have time to think about this one.

**Comment by tjaychen** [comment]
just wanted to circle back on this one. I can help take a look too if we've decided go this direction.
I can help with the dif changes etc as they are needed.

**Comment by mwbranstad** [comment]
haven't forgotten about this one. Is it a go? If so, Steve and I need to work together for the first pass of this PR. The soonest that can happen is next week. So if all are agreed, please indicate so here. thanks.

**Comment by tjaychen** [comment]
it looks good to me, but @bilgiday has looked at this more and should probably give the final go ahead.

**Comment by bilgiday** [comment]
It looks good to me, we can move forward with this. It seems everyone agrees with the proposal outlined in this comment: https://github.com/lowRISC/opentitan/issues/14542#issuecomment-1241334593

**Comment by tjaychen** [comment]
sounds good to me.
@bilgiday / @mwbranstad do you want to go ahead with the change? or do you want me to help take a look?
let me know what you prefer.

**Comment by mwbranstad** [comment]
@senelson7 and I are working on the RTL/DV changes for csrng and edn at the unit level. Then will need help on any firmware/software changes as the chip level.

**Comment by mwbranstad** [comment]
PR #15165 has passed 19 tests, but still fails some tests (as expected).
@tjaychen can you take a look?

**Comment by tjaychen** [comment]
yes i will have a look, i've assigned myself on the PR already.
@bilgiday if you have time to have a look also, please feel free.

**Comment by tjaychen** [comment]
i'm going to close this now since #15165 has been merged. Please re-open if there are objections.
