### ISSUE TITLE
[otbn, dv] Coverage for MUBI checks and potential addition to bad_internal_state

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#14541]
We have a few MUBI signals within OpenTitan where we check the MUBI is valid. For some of these an invalid MUBI triggers a bad_internal_state error and coverage for these checks is included in https://github.com/lowRISC/opentitan/pull/14068.

For some others they don't directly factor into bad_internal_state because they themselves are raised when some error condition is occurring to cause escalation etc. The checks factor into `fatal_err`/`recoverable_err` in `otbn_controller` so will cause an error if triggered but may not set error cause.

In case where there is no other error and the MUBI itself is being glitched we won't get a sensible value out of error cause. Perhaps we don't care but we may we want to factor this into bad_internal_state also (note this requires care to avoid circular logic).

We need coverage for this checks either way, two can be found in `otbn_controller`. Signals being checked are

- `fatal_escalate_en`
- `recoverable_err`

`start_stop_controller` also uses a MUBI value `start_stop_escalate_en` but doesn't have a check. It doesn't need one as it uses a loose comparison (so either there's no escalate with one specific bit pattern and all other bit patterns escalate so anyone glitching a single bit can't prevent an escalation). Still some coverage and testing of corrupting this MUBI would make sense.

@andreaskurth @vogelpi @ctopal what are your thoughts?

> estimate 4
> remaining 2022-09-14 2

**Comment by vogelpi** [comment]
I also think that in general invalid MUBI signals should trigger a bad_internal_state error. What I sometimes did (e.g. for the rma_req_i/ack_o) signal inside `start_stop_controller` is to move the local FSM into an error state directly. IIRC, this also triggers a bad_internal_state error.

**Comment by andreaskurth** [comment]
> What I sometimes did (e.g. for the rma_req_i/ack_o) signal inside `start_stop_controller` is to move the local FSM into an error state directly. IIRC, this also triggers a bad_internal_state error.

I don't think the locked state always signals an error. For instance in `otbn_start_stop_control`, the `OtbnStartStopStateLocked` state does not set `fatal_error_o`, and not all transitions into `OtbnStartStopStateLocked` set `fatal_error_o`. If we consistently set `fatal_error_o` (or similar in other modules) when we are in the terminal error state, your solution sounds good to me.

**Comment by vogelpi** [comment]
I've now created a PR to address the design side of this here: #14626

**Comment by johngt** [comment]
Coverage - for V2S
@prajwalaputtappa

**Comment by andreaskurth** [comment]
Verification (except coverage) goes to V3, so after coverage is completed we should set this to P3, V3, and M3.

**Comment by GregAC** [comment]
#1419 merged so closing
