### ISSUE TITLE
 [chip dv] Investigate the large runtime of the tap_strap_* tests

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#14582]
Comment reference:
https://github.com/lowRISC/opentitan/pull/14557#pullrequestreview-1085864774

These tests take close to an hour on average: 
```
### Test Results
|  Milestone  |            Name             | Tests                |  Max Job Runtime  |  Simulated Time  |  Passing  |  Total  |  Pass Rate  |
|:-----------:|:---------------------------:|:---------------------|:-----------------:|:----------------:|:---------:|:-------:|:-----------:|
|     V2      | chip_sw_tap_strap_sampling  | chip_tap_straps_dev  |      1.046h       |     14.227ms     |    91     |   100   |   91.00 %   |
|             |                             | chip_tap_straps_rma  |      39.990m      |     8.966ms      |    100    |   100   |  100.00 %   |
|             |                             | chip_tap_straps_prod |      1.069h       |     13.302ms     |    88     |   100   |   88.00 %   |
|     V2      | chip_sw_lc_ctrl_jtag_access | chip_tap_straps_dev  |      1.046h       |     14.227ms     |    91     |   100   |   91.00 %   |
|             |                             | chip_tap_straps_rma  |      39.990m      |     8.966ms      |    100    |   100   |  100.00 %   |
|             |                             | chip_tap_straps_prod |      1.069h       |     13.302ms     |    88     |   100   |   88.00 %   |
|     V2      |                             | **TOTAL**            |                   |                  |    279    |   300   |   93.00 %   |
|             |                             | **TOTAL**            |                   |                  |    279    |   300   |   93.00 %   |
```

This seems a little excessive. The likely reason is the use of `uvm_hdl_force` which is known to hurt the runtime performance. It will be great to profile and speed up the tests if possible.

**Comment by engdoreis** [comment]
The tests are now passing:
|     | Tests                |   latest |   2022.10.24 |   2022.10.23 |   2022.10.22 |   2022.10.21 |   2022.10.17/12 |   2022.10.17/1 |   2022.10.15/12 |   2022.10.15/1 |   2022.10.14 | Suite                                                                                                          |
|----:|:---------------------|---------:|-------------:|-------------:|-------------:|-------------:|----------------:|---------------:|----------------:|---------------:|-------------:|:---------------------------------------------------------------------------------------------------------------|
| 211 | chip_tap_straps_dev  |      100 |          100 |          100 |          100 |            0 |              20 |              0 |               0 |              0 |            0 | chip_sw_tap_strap_sampling, chip_sw_lc_ctrl_jtag_access, chip_sw_lc_ctrl_broadcast                             |
| 212 | chip_tap_straps_prod |      100 |          100 |          100 |          100 |           20 |              20 |              0 |              40 |             40 |           20 | chip_sw_tap_strap_sampling, chip_sw_lc_ctrl_jtag_access, chip_sw_lc_ctrl_broadcast                             |
| 213 | chip_tap_straps_rma  |      100 |          100 |          100 |          100 |           20 |               0 |              0 |               0 |              0 |           20 | chip_sw_tap_strap_sampling, chip_sw_rv_dm_jtag_tap_sel, chip_sw_lc_ctrl_jtag_access, chip_sw_lc_ctrl_broadcast |
