### ISSUE TITLE
[ALL/DV] Compile broken by commit 7f559d90d521cb9ea7fea8061c58b1e3f3d08350 for xcelium

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#1462]
the listed commit breaks compile for xcelium
VCS is less restrictive and will allow constructs that is not approved by the spec

![image](https://user-images.githubusercontent.com/53917183/73539545-e71ee480-442d-11ea-9c30-b7b0d4b0b71b.png)

I have tested compile with 
uart/hmac/aes all failes with the same error for Xcelium but pass for vcs

**Comment by rasmus-madsen** [comment]
Should be start a discussion on a more extensive PR check? I guess it should check compile and propably all sanity tests for both tools ?

**Comment by imphil** [comment]
@rasmus-madsen we're currently working on more extensive checks, expect minimal regression runs in CI soon.

**Comment by rasmus-madsen** [comment]
> @rasmus-madsen we're currently working on more extensive checks, expect minimal regression runs in CI soon.

Great

**Comment by weicaiyang** [comment]
@rasmus-madsen 
Sorry for the inconvenience. I just made a PR #1465 to fix it.

**Comment by rasmus-madsen** [comment]
> @rasmus-madsen
> Sorry for the inconvenience. I just made a PR #1465 to fix it.

dont worry about it weicai - just remember it next time I break the repo ;)
anyways these things happen. glad we resolved it quick.

**Comment by weicaiyang** [comment]
> > @rasmus-madsen
> > Sorry for the inconvenience. I just made a PR #1465 to fix it.
> 
> dont worry about it weicai - just remember it next time I break the repo ;)
> anyways these things happen. glad we resolved it quick.

thanks @rasmus-madsen. Close this issue
