### ISSUE TITLE
[dif] remove `DIF_TEST_SMOKE` S1 requirement

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#14632]
Barring any bug fixes or minor enhancements, core DIF development is complete. However, some DIFs (see below) are still marked at `S0`. If we look closely, we find that all of these DIF libraries meet the [`S2` requirements](https://docs.opentitan.org/doc/project/checklist/#s2), however they are missing a single [`S1` requirement](https://docs.opentitan.org/doc/project/checklist/#s1). Specifically, they are missing a SW smoketest. However, when we look closely, SW smoke tests are redundant for some IPs, as many other tests (smoke or chip-level) already test these components.

Therefore, it may be wise to waive this requirement for specific IPs so as to avoid redundant work.

Below, I describe why a waiver may make sense for DIF libraries stuck at `S0`.

DIFs still at `S0`:
1. adc_ctrl - covered by `adc_ctrl_sleep_debug_cable_wakeup_test`
2. edn - covered by `entropy_src_edn_reqs_test`
3. flash_ctrl - exercised by test ROM, and therefore every test
4. **i2c - none**
5. keymgr - covered by `keymgr_key_derivation_test`
6. lc_ctrl - covered by  several tests including `lc_ctrl_otp_hw_cfg_test`
7. pattgen - covered by `lc_ctrl_otp_hw_cfg_test`
8. pinmux - exercised by test ROM, and therefore every test
9. pwm - covered by `sleep_pwm_pulses_test`
10. rom_ctrl - covered in `rom_ctrl_integrity_check_test`
11. sensor_ctrl - covered in `sensor_ctrl_wakeup_test`
12. spi_device - covered in `spi_tx_rx_test` and bootstrap (which isn't really tested in DV but tested on FPGA)
13. sysrst_ctrl - covered by several tests including `sysrst_ctrl_reset_test`

Perhaps on the i2c DIF lib needs a smoktest? Thoughts?

**Comment by timothytrippel** [comment]
On second thought, it might be better to: 
1. simply remove the [`DIF_TEST_SMOKE`](https://docs.opentitan.org/doc/project/checklist/#dif_test_smoke) from the S1 requirements altogether, 
2. add a `DIF_TEST_UNIT_STARTED` requirement back to the list of S1 requirements in its place, and change the name of the [`DIF_TEST_UNIT`](https://docs.opentitan.org/doc/project/checklist/#dif_test_unit) requirement to `DIF_TEST_UNIT_COMPLETE`.
 
The rationale for this is that the [`DIF_DV_TESTS`](https://docs.opentitan.org/doc/project/checklist/#dif_dv_tests) already covers the [`DIF_TEST_SMOKE`](https://docs.opentitan.org/doc/project/checklist/#dif_test_smoke) requirement and the [`DIF_TEST_UNIT_STARTED`](https://docs.opentitan.org/doc/project/checklist/#dif_test_unit) requirement would give some confidence that the DIFs that are implemented at S1 do roughly what we think they do.

In my experience implementing many of the DIFs to unblock top-level DV, this is the workflow that has worked best for us.

**Comment by arunthomas** [comment]
I've added this to the Software WG meeting agenda.

This approach makes sense to me. The DV tests provide adequate coverage.

**Comment by timothytrippel** [comment]
From our discussion during the SW WG, we agreed to:

1. rename DIF_TEST_SMOKE to DIF_TEST_ON_TARGET in S1, and
2. remove DIF_DV_TESTS from S2

I will update all checklists / documentation to reflect this change.
