### ISSUE TITLE
[test] extract_sw_logs_db requires .rodata section

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#14636]
I ran into this while working on #14627. The test program added in that PR is very minimal and does not have a `.rodata` section because it doesn't need it. We, however, call `extract_sw_logs_db` for the `.rodata` section when building for `sim_dv` unconditionally which causes the following error:

```
Error: .rodata section not found in bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/silicon_creator/rom/e2e/rom_e2e_shutdown_exception_c_prog_sim_dv.elf
```

To work around this for now, I added the following at the end of the`.rodata` section definition in `rom_ext_common.ld` so that the linker emits an empty `.rodata` section.
```
. = ALIGN(4);
_rodata_end = .;
```

**Comment by alphan** [comment]
@sriyerg, assigning to you as we discussed offline. Thanks a lot!

As I mentioned, part of this issue is the `_gen_sim_dv_logs_db_impl` that passes the `--rodata-sections .rodata` [here](https://cs.opensource.google/opentitan/opentitan/+/master:rules/opentitan.bzl;drc=e77043f96a92a4185ed40b975a0cc6eb46707d10;l=486) unconditionally.

In order to test this in DV with an elf file that doesn't have the `.rodata` section you can remove [this part](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom_ext/rom_ext_common.ld;drc=2c3bfae3e7ab3491aacffafc7e2dd2cdc6af4e0f;l=121) from `rom_ext_common.ld` that was added in #14627.

**Comment by timothytrippel** [comment]
FYI, the empty `.rodata` section was moved to the `ottf_common.ld` linker script as part of #14521.

**Comment by timothytrippel** [comment]
Once #14743 merges, we will no longer need the dummy symbol in the `ottf_common.ld` script that creates an empty `.rodata` section, as we will no longer build SW for device that the test does not target. I.e., since the test @alphan added in #14627 only targets Verilator and CW310, the issue will no longer be encountered. However we should probably still keep this issue open, and fix the root cause when convenient.
