### ISSUE TITLE
[entropy_src/dv] Use the internal reset monitor to know a mid-test reset occurred

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#14649]
- [ ] Change `chip_sw_entropy_src_fuse_vseq` use the internal reset monitor to know a mid-test reset occurred.
- [ ] The tests `chip_sw_entropy_src_fuse_en_fw_read_test` and `chip_sw_csrng_fuse_en_sw_app_read_test` depend on this file and needs changes as well.

Refer to [comment](https://github.com/lowRISC/opentitan/pull/14293#discussion_r956328634)

**Comment by engdoreis** [comment]
assigning to @sriyerg for visibility.

**Comment by engdoreis** [comment]
Should be done by a dv engineer, so I'm unassigning myself.

**Comment by msfschaffner** [comment]
In an attempt to reduce churn, marking as not planned since the current mechanism works fine and is used by multiple tests.
