### ISSUE TITLE
[spi_device] Make the command filter default to deny all?

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#14666]
For spi_device, shall we change the CSR default to filter all commands?

Currently, the defaults out of reset are to allow all commands. Because configuration does not happen atomically, the sequence of CSR changes must be ordered to prevent disallowed commands from passing through to the SPI flash (i.e. don't turn on passthrough mode until the filter is configured).

We may want to at least document that CSR sequence, but it might also be good to start with "deny all".

**Comment by a-will** [comment]
CC @tjaychen @eunchan @jeoongp

**Comment by tjaychen** [comment]
yeah i think we might have to do deny_all..otherwise it would imply by default if a host just blasted us with transactions they might be able to alter the state of the flash behind the passthrough.

**Comment by eunchan** [comment]
In the current design, filter CSRs are almost useless. The passthrough logic filters commands if they are not in the CMD_INFO entries. So, filtering only affects if the command is in CMD_INFO and valid bit is set AND filter bit in FILTER CSR is set.

I think it is better to move the filter into CMD_INFO entry and remove 256 bit CSR.

**Comment by a-will** [comment]
@eunchan If the absence of a CMD_INFO entry would imply filtering the command, is there any need for the filtering bits at all?

**Comment by eunchan** [comment]
> @eunchan If the absence of a CMD_INFO entry would imply filtering the command, is there any need for the filtering bits at all?
>
One possible case is the command is being processed in flash mode but filtered out on passthrough.

**Comment by eunchan** [comment]
> > In the current design, filter CSRs are almost useless. The passthrough logic filters commands if they are not in the CMD_INFO entries. So, filtering only affects if the command is in CMD_INFO and valid bit is set AND filter bit in FILTER CSR is set.
> > I think it is better to move the filter into CMD_INFO entry and remove 256 bit CSR.
> 
> Just to expand a little on that: To complete a given pass-through command, it turns out spi_device needs more information than merely whether to allow it through. spi_device doesn't know how a given command wants to use the I/Os, and it _needs_ to know which are outputs and which are inputs at the various phases.
> 
> You could argue that CMD_INFO is only necessary for commands that need to be uploaded, need address translation or payload swaps, or don't do the typical MISO / MOSI config. And in that case, having the 256-bit CSR could make sense. However, it's probably nicer to have more CMD_INFO entries (or to save the gates altogether) than to have the bigger filtering CSR. 🙂
>
I checked multiple times with teams. They were OK with 16 command slots. 8 more entries are for safe margin in any cases more than 16 commands are needed.

**Comment by weicaiyang** [comment]
Looks like this is not an issue and we have filed an issue #14831 to move the filter bit to cmd_info.
Perhaps we can close this issue now.

**Comment by a-will** [comment]
Yup, agreed. Since CMD_INFO entries are required, the default behavior effectively _is_ to filter.
