### ISSUE TITLE
[spi_device] Add an enable bit for the IP to prevent partial configuration?

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#14665]
For the spi_device IP, should we add an IP-wide enable bit in a CSR? Currently, the spi_device IP is never actually off (power / clock / reset inputs notwithstanding). This means that the spi_device could respond to transactions before the full configuration is ready. Should we gate responses to the host, events on CSRs / interrupts, and the filling of FIFOs until software has a chance to complete configuration?

On the spi_host clock side, this would likely mean sampling the enable bit at the beginning of a transaction and discarding the data if the enable was low.

**Comment by a-will** [comment]
CC @tjaychen @eunchan @jeoongp

**Comment by tjaychen** [comment]
ah i like this idea...i think it's better than whatever CSb edge hunting idea I had. 
To summarize, would it effectively be that when csb goes low and spi_clock starts, everything behaves "as expected" for a couple of cycles.  On the second cycle, you will have discovered whether things are enabled vs not, and then perhaps cycle things back from there?

**Comment by tjaychen** [comment]
@weicaiyang

**Comment by tjaychen** [comment]
> ah i like this idea...i think it's better than whatever CSb edge hunting idea I had. To summarize, would it effectively be that when csb goes low and spi_clock starts, everything behaves "as expected" for a couple of cycles. On the second cycle, you will have discovered whether things are enabled vs not, and then perhaps cycle things back from there?

A number of FSMs and stuff would probably need to be "reset" etc.

**Comment by eunchan** [comment]
Should we assign this to "Future Release"? I don't think we have enough time changing the design and review CDC.

**Comment by tjaychen** [comment]
we might have to quantify the host impact a bit.
Let me ruminate a bit on this offline, since I probably can't put it all in the open.

**Comment by eunchan** [comment]
I will add an enable bit to CSR (rather than adding CG to SPI_CLK or OR gate on CSb) that blocks cmdparse to activate any datapaths. It would take less effect to the timing.

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP1 because we should clarify with the product team if this is a requirement.

**Comment by andreaskurth** [comment]
We have to add this enable bit. The proposal is as follows:

Add an `enable` register field that:
- resets to `1’b0`;
- gets 2FF-synced to the SPI clock and there resets with `rst_ni & ~csb_i` (active low) to `1’b0` (The rationale for the reset condition is that the two modules into which the enable signal in the SPI clock domain gets passed, `spi_cmdparse` and `spi_passthrough`, are also reset based on CSb. Using the same reset signal avoids CDC issues.);
- when `1’b0` in the SPI clock domain, causes a transition to `StWait` in `spi_cmdparse` at the end of the command phase (i.e., when the 8th bit is valid);
- when `1’b0` in the SPI clock domain, causes a transition to `StFilter` in `spi_passthrough` at the end of the command phase (i.e., when the 8th bit is valid).

Keeping https://github.com/lowRISC/opentitan/labels/Priority%3AP1 because this requires an RTL change and subsequent DV changes and functional coverage.

**Comment by msfschaffner** [comment]
It looks like we can reset both `spi_device` and `spi_host` via the system reset controls: 
https://github.com/lowRISC/opentitan/blob/00b056842175ad3fcdad7a47e4f5c83fb53fb9bc/hw/top_earlgrey/data/top_earlgrey.hjson#L155-L157
Hence, even if it would be convenient to implement this in the blocks themselves, there is a workaround for this available, hence I think we can deprioritize this to after M2.5.

**Comment by andreaskurth** [comment]
> It looks like we can reset both `spi_device` and `spi_host` via the system reset controls

This also resets `spi_device`'s configuration, right? So when you bring it out of reset, how do you prevent it from doing unintended things until it's fully configured? The `enable` register field was meant to do that

**Comment by hcallahan-lowrisc** [comment]
Related comment : https://github.com/lowRISC/opentitan/pull/14861#pullrequestreview-1102844736

**Comment by a-will** [comment]
This is likely not necessary. The data sheet will always have a spec requirement to wait some amount of time before transactions are allowed. The response to such activity is considered undefined behavior.

We can sweep this sort of behavior into that time requirement.

**Comment by a-will** [comment]
I'm going to close this, since that time requirement is always present. However, if someone wants to implement this to improve robustness in the future, then we do have a "Disabled" mode now that generic mode is gone. It would need to be held steady and sampled at the right moment to allow the transition to the SPI domain, in addition to ensuring the atomicity of SPI transactions.
