### ISSUE TITLE
[ci] CW310 test failures are ignored - false positive

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#14668]
Please see the [cw310 tests log](https://dev.azure.com/lowrisc/4c50229e-f6cb-4f39-8522-585bb3841438/_apis/build/builds/92369/logs/200) of fe8a53a299d244d254b4a80eb83d8747d4c046a4:

```
2022-08-31T00:26:31.2909692Z Executed 179 out of 179 tests: 172 tests pass and 7 fail locally.
2022-08-31T00:26:31.2943205Z 
2022-08-31T00:26:31.2944353Z (00:26:31) INFO: Build completed, 7 tests FAILED, 3570 total actions
2022-08-31T00:26:31.3021220Z + python3 ./util/fpga/cw310_reboot.py
2022-08-31T00:26:31.4598862Z Found CW310 with FW Version: 0.40.1
2022-08-31T00:26:31.4752410Z To reproduce failures locally, follow the instructions at https://docs.opentitan.org/doc/getting_started/setup_fpga/#reproducing-fpga-ci-failures-locally
2022-08-31T00:26:31.4815181Z ##[section]Finishing: Execute tests
```

![image](https://user-images.githubusercontent.com/57949550/187578939-7260703f-c178-4c82-af9c-7ab20c66694e.png)

**Comment by alphan** [comment]
update: test failures are caused by alert config check failures.

**Comment by alphan** [comment]
update: it looks like 621b69ea0c35c5d30373755f65fc4108fbceb0dc adds additional alerts without updating the digest value in the RMA OTP image. Log excerpt:
```
2022-08-30T01:08:16.3671724Z Starting interactive console
2022-08-30T01:08:16.3672106Z [CTRL+C] to exit.
2022-08-30T01:08:16.3672286Z 
2022-08-30T01:08:16.3672642Z ROM:f42c059a
2022-08-30T01:08:16.3672923Z 
2022-08-30T01:08:16.3673357Z ROM:f42c059a
2022-08-30T01:08:16.3673610Z 
2022-08-30T01:08:16.3673921Z BFV:05414803
2022-08-30T01:08:16.3674102Z 
2022-08-30T01:08:16.3674423Z Exiting interactive console.
```
`05414803` is `kErrorAlertBadCrc32`.

**Comment by alphan** [comment]
update: It looks like ba0e3530c3b075c8b551bee36c59b9e209cd742e introduced the false positive problem: `... || echo "..."` always succeeds.

**Comment by alphan** [comment]
update: Created draft #14669. This PR does not include test fixes to verify that CI can catch failures in CW310 tests.

**Comment by alphan** [comment]
update: Created #14670 (CI fix + OWNER_SW_CFG_ROM_ALERT_DIGEST_RMA update)

**Comment by alphan** [comment]
next: 
* verify that #14669 fails due to CW310 test failures, 
* verify that #14670 passes, 
* close #14669, 
* merge #14670.

**Comment by milesdai** [comment]
Yikes! Thanks for catching and fixing this! Should we revert ba0e3530c3b075c8b551bee36c59b9e209cd742e for now while we wait for your draft PRs to pass to prevent anyone else from creating branches from the bad code?

**Comment by alphan** [comment]
> Yikes! Thanks for catching and fixing this! Should we revert [ba0e353](https://github.com/lowRISC/opentitan/commit/ba0e3530c3b075c8b551bee36c59b9e209cd742e) for now while we wait for your draft PRs to pass to prevent anyone else from creating branches from the bad code?

Summarizing our chat offline: Reverting that commit would cause cw310 tests to fail immediately. Let's wait for #14670 (a single line change for the digest value) instead of reverting 621b69ea0c35c5d30373755f65fc4108fbceb0dc.

**Comment by alphan** [comment]
[Executed 179 out of 179 tests: 179 tests pass.](https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=92398&view=logs&j=be0b5a13-ded6-5a2a-3e48-80a10e7eef12&t=08da8d7b-39e7-587c-6104-066a15914f8d&l=20393)

**Comment by dmcardle** [comment]
Nice job, @alphan! I wonder how we could avoid accidentally clobbering the exit code in the future. We should probably do an audit of other instances of `|| echo` in our CI scripts and Yaml files.

**Comment by alphan** [comment]
> Nice job, @alphan! I wonder how we could avoid accidentally clobbering the exit code in the future. We should probably do an audit of other instances of `|| echo` in our CI scripts and Yaml files.

Yeah, we encountered a similar issue when were using meson (all unittests skipped 💯 ) and an AI was to add some sort of a test, like a meta-check that checks the check, for this step to make sure we don't run into this again. We can consider moving all code to some shell script to keep the job definition minimal and somehow test that script.

**Comment by alphan** [comment]
Also, the real solution to this problem would me coverage measurement and checks, but that work is still in progress.
