### ISSUE TITLE
[DV] Progress towards CI flow setup for DV

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#1467]
At this point, we have the necessary regression tool in place to start running DV simulations in CI when PRs are made. However, there are a few IPs whose sanity tests are still not passing since they are actively under debug. This issue serves as a tracker to get them resolved and added to the CI flow. 

- [x] AES CSR tests failing - under debug

- [x] I2C tests not yet available - PR from @tunghoang290780 under review

- [x] UART sanity not passing - change in the way some interrupts behave

- [x] Chip level CSR tests not passing - under debug

- [ ] USBDEV sanity test not constructed - considering at least all CSR tests in the sanity bucket are passing, only the sanity test needs to be constructed

- [x] XBAR main and peri - this is not yet setup to run with dvsim flow (Done in #1504)

- [x] Work with LR to deploy the flow

**Comment by sriyerg** [comment]
In PR #1468, I added `hw/top_earlgrey/data/top_earlgrey_sim_cfgs_list.hjson` which will be used to run {CI/sanity, nightly} regressions on the IPs used in `top_earlgrey` and the full chip. I have commented out the blocks that are not yet passing from the list for now. As the sanity for those blocks start passing, we can mark them done in this list.

**Comment by weicaiyang** [comment]
working on updating uart for interrupt change.
Will set up xbar to run with dvsim

**Comment by sriyerg** [comment]
@asb, @imphil,

The regression script for running all DV sanity sims in one shot is now available. Would someone from LR please give the following command a try:

```console
 ./util/dvsim.py hw/top_earlgrey/data/top_earlgrey_sim_cfgs_list.hjson -i sanity --max-parallel 3
```

The goal of this exercise is to work out any kinks in running this before we deploy it as a CI check. The `--max_parallel` switch puts a limit on how many sims can be run in parallel - I'd guess the # of licenses is a limiting factor so you can adjust that number accordingly. 

We will work on adding a 'lite' results mode where it exits with error if even a single failure is encountered; and also display results in a smaller and more concise table. I will work on documentation for this tool as well (there isn't any at the moment, just the `--help` switch).

**Comment by sriyerg** [comment]
Now that AES sanity is passing, I have added it into the regression list in #1495.

**Comment by imphil** [comment]
The sanity regression now runs in the "CI (private)" job you see under all pull requests and takes between 5 and 10 min to complete.

**Comment by sriyerg** [comment]
Chip level testing is now enabled with dvsim in #1689. They will now get run as a part of private CI as well as nightly.

**Comment by sriyerg** [comment]
Work on i2c and usbdev sanity tests are underway, but they are not blocking the DV CI, which has now been effectively setup. Closing this issue.
