### ISSUE TITLE
[test-triage] rom_e2e_bootup_success

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#14679]
### Hierarchy of regression failure

Chip Level

### Failure Description

Job chip_earlgrey_asic-sim-vcs_run_default killed due to: Exit reason: User job exceeded runlimit: User job timed out has 2 failures:

Test rom_e2e_bootup_success has 1 failures.

0.rom_e2e_bootup_success.4002847607
Log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.rom_e2e_bootup_success/latest/run.log

  Job ID: smart:bb6c6f94-eb14-40d3-ac60-60e9619a436f

### Steps to Reproduce

Tuesday August 30 2022 07:08:49 UTC
GH Revision: https://github.com/lowrisc/opentitan/tree/6be5b88705e3e48dc9e3de7bca93313528f1274e
Build seed: 2532933437

### Tests with similar or related failures

- [ ] Unmapped tests (Just a single test failing)

**Comment by johngt** [comment]
Assigning @engdoreis 
Looks like a timeout issue.
Need to test locally and see if there is still an issue. Then consider increasing timeout length.
Status: Observe/track over the next couple of days

**Comment by weicaiyang** [comment]
This test has been passing on many nightly.
But it's an unmapped test. Can @alphan or @timothytrippel add a testplan for this test? Then, we can close this issue.

**Comment by timothytrippel** [comment]
#15113 should fix.

**Comment by weicaiyang** [comment]
Thanks @timothytrippel
