### ISSUE TITLE
[ibex, nmi] Ibex nmi is not fired without enabling plic irq

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#14673]
The test `chip_sw_rv_core_ibex_nmi_irq` (#14609 ) is enabling the plic irq for both wdog and alert_handler in order to have the nmi handler being called.
It's also acknowledging the irq in the plic in order to stop it from being called.
Acording to @tjaychen this behaviour doesn't look right and needs investigaiton as the nmi path and the plic path are technically supposed to be different.

**Comment by msfschaffner** [comment]
I'll take a look at this.

**Comment by tjaychen** [comment]
thanks @msfschaffner
