### ISSUE TITLE
[opentitantool] Implement fpga reset command for CW310

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#14686]
For reference:
* [Notes on CW310 PLL config](https://docs.google.com/document/d/1CSbwGzuCb_pRCIOh__6Hac7p0iVSaG-Vadd0H8cmrRM/edit#heading=h.l2ztj9bgn7wc)
* [PR that adds the set-pll command](https://github.com/lowRISC/opentitan/pull/12870)

@cfrantz @arunthomas

**Comment by jrvanwhy** [comment]
Question: Is this command going to be used in automation? If so, do we need it to wait for the CW310's USB device to become available again before returning?

**Comment by arunthomas** [comment]
Yup, we'd like to transition CI to using this opentitan-tool command

CC @drewmacrae @milesdai

**Comment by drewmacrae** [comment]
Currently we are issuing this command with the python libraries to the CI FPGAs at the end of a test. It's not ideal but works to let setup proceed as normal with a freshly rebooted FPGA.
https://cs.opensource.google/opentitan/opentitan/+/master:ci/scripts/run-fpga-cw310-tests.sh;drc=838afcd5d8f73da7c62f6eb355ceb861c6fca96b;l=33

**Comment by jrvanwhy** [comment]
> Currently we are issuing this command with the python libraries to the CI FPGAs at the end of a test. It's not ideal but works to let setup proceed as normal with a freshly rebooted FPGA. https://cs.opensource.google/opentitan/opentitan/+/master:ci/scripts/run-fpga-cw310-tests.sh;drc=838afcd5d8f73da7c62f6eb355ceb861c6fca96b;l=33 After the reboot, the VM looses contact with the FPGA

Does "loses contact" mean the VM doesn't automatically get a USB reconnect? If so, waiting for the USB reconnect would cause `opentitantool` to hang.

**Comment by drewmacrae** [comment]
@GregAC:
"When starting up docker [the] USB devices are passed through to the container"
This matches my empirical findings that had me reboot at the end of CI execution instead of the start: after rebooting, the CI containers on the FPGA runners don't have access to the entries in /dev that provide access to the SAM3 or the OT UART.

**Comment by a-will** [comment]
> @GregAC: "When starting up docker [the] USB devices are passed through to the container" This matches my empirical findings that had me reboot at the end of CI execution instead of the start: after rebooting, the CI containers on the FPGA runners don't have access to the entries in /dev that provide access to the SAM3 or the OT UART.

When the SAM3X reboots, the USB device disconnects. From the perspective of the host system, any new connection is an entirely new device, so it gets new entries in /dev (different USB device address and different minor device number in the kernel's device node). So the entry that was passed through is effectively null.

Unprivileged containers don't have the ability to do any setup of new devices, and handling them is a bit complex. We'll need to figure this out eventually, though, else we'll not be able to test OT's USB device in CI.

**Comment by jrvanwhy** [comment]
So it sounds like there is no need for me to implement wait-for-reconnect *now*, but we will likely need to do similar work down the road for testing OT's USB device.

**Comment by jrvanwhy** [comment]
Implemented in https://github.com/lowRISC/opentitan/pull/15263
