### ISSUE TITLE
[dv,cdc] Add random phase delay in clock dividers

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#14693]
In order to trigger more interesting CDC cases we would want to avoid clocks at fixed phase relations. Specifically, the divided clocks generated by clkmgr are always locked, meaning a transition on a div4 clock always happens on a transition of both div2 and non-div clocks.

Adding a random phase delay means a small CDC delay can probabilistically result in more interesting behavior.

**Comment by matutem** [comment]
We discussed this some more, and there is a suggestion to change the CDC instrumentation so it randomly adds a full cycle delay in the destination side instead of adding some time delay on the source side. That seems like an overall better approach.

**Comment by sriyerg** [comment]
See related issue #10432 which tracks the CDC enablement effort in simulations.

**Comment by msfschaffner** [comment]
I think this can be closed since we have moved to inserting random clock cycles instead of delays.
Please reopen if there is still something left to do here.
