### ISSUE TITLE
[spi_device] Add an enable/active CSR

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#14717]
@eunchan 

As @a-will suggested, we could add an enable/active CSR. When it's off, spi_device is in reset state and it stops the cmd parser and passthrough path, so that any incoming SPI transaction will be ignored.
SW can turn it on after finishing the spi_device configuration.

**Comment by eunchan** [comment]
related (or duplicated) #14665

**Comment by eunchan** [comment]
CDC may be a concern. EN in CSR needs to be propagated to SPI correctly.

I think more safer approach is to block SPI CLK until configuration is done as suggested in https://github.com/lowRISC/opentitan/pull/9503 .

If not, I don't know how I can hand over the en signal to SPI_CLK domain safely and not lose the first SPI transaction.

CC: @tjaychen @a-will

**Comment by weicaiyang** [comment]
closing as duplicated of https://github.com/lowRISC/opentitan/issues/14665
