### ISSUE TITLE
[UART/DV]  sanity test fails for excelium

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#1472]
reproduce 
make SEED=1243649678 SIMULATOR=xcelium

log included
[run.log](https://github.com/lowRISC/opentitan/files/4148939/run.log)
wave is massive so I am leaving that out for now

**Comment by weicaiyang** [comment]
@rasmus-madsen we had some design change on UART recently. I'm updating the TB now. Please uart failure for now. Thanks

**Comment by rasmus-madsen** [comment]
@weicaiyang  are you asking me to close the issue? I think you may have forgotten a word or two?

**Comment by weicaiyang** [comment]
This PR #1482 will fix it.
