### ISSUE TITLE
[dv] enable running SRAM injection tests in DV

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#14746]
ROM E2E tests such as #14484 and #14486, require injecting programs in SRAM over JTAG. While we have support for such on the FPGA, using OpenOCD + some GDB scripting, we need to add support for running such tests in DV (to address #14634). Specifically, we need to investigate how to generate the proper JTAG transactions to inject a program in SRAM in DV.

CC: @sriyerg @dmcardle

**Comment by sriyerg** [comment]
Does OpenOCD use the SBA to get to SRAM, or some other way?

**Comment by tjaychen** [comment]
I think it's going to have to be the path directly to the core.. otherwise we wouldn't be able to do things like set breakpoints or jump the PC

**Comment by moidx** [comment]
Cross-referencing to #15028

**Comment by tjaychen** [comment]
related to #14145.
I think we can actually close this one down, since it's already duplicated as a chip level test.
@sriyerg what do you think? I'll leave it to you to decide.

**Comment by tjaychen** [comment]
postponed to post M2, see #14145
