### ISSUE TITLE
[PWRMGR|RST domains] ESC domain in the future chip

### ISSUE THREAD

**Issue by jeoongp** [lowRISC/opentitan#14785]
escalation modules are currently driven by LC rst/clk. However, we will need to keep ESC domain async from LC domain in the future if a tracking issue occurs as discussed in #13950. Fault status regs will also be moved to ESC domain accordingly.

**Comment by matutem** [comment]
The fault_status register needs to be cleared on reset though.

**Comment by tjaychen** [comment]
@jeoongp i don't think you need to move the fault registers to escalation domain.  The escalation domain only has to talk to the  escalation receiver right? So we can consider the escalation domain async from the lc domain.

**Comment by jeoongp** [comment]
@tjaychen thanks for suggestion. Yes, it's better to move only escalation receiver to ESC domain async from LC domain where the fault registers are.

**Comment by msfschaffner** [comment]
@msfschaffner

**Comment by matutem** [comment]
Closed by https://github.com/lowRISC/opentitan/pull/15183
