### ISSUE TITLE
[chip-test] chip_sw_power_idle_load

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#14815]
### Test point name

[chip_sw_power_idle_load](https://github.com/lowRISC/opentitan/blob/954f0de3bef19ee3080e9dd71dfc647a9c93c779/hw/top_earlgrey/data/chip_testplan.hjson#L3055)

### Host side component

SystemVerilog+Rust

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

@tjaychen and @msfschaffner for HW, @timothytrippel @sriyerg for DV and concurrency framework

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by johngt** [comment]
@tjaychen / @msfschaffner - based on comment https://github.com/lowRISC/opentitan/issues/14814#issuecomment-1312852161 should this also be moved to post M2?
Otherwise we will need an update on the status of this from @yehuda-bejar

**Comment by tjaychen** [comment]
i think the one that was lowered is the max power concurrency test, but the not the idle load one.

**Comment by msfschaffner** [comment]
Yeah this idle test should be ready soon, see https://github.com/lowRISC/opentitan/pull/15923.

**Comment by msfschaffner** [comment]
Closing this as it is passing in nightlies. Any further FPGA debugging will be tracked in a test triage issue.

**Comment by moidx** [comment]
Created https://github.com/lowRISC/opentitan/issues/16506 to track FPGA issue.
