### ISSUE TITLE
[test] flash_ctrl_testutils_increment_counter performs multiple writes to the same address

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#14828]
_Noticed while working on #14503_

@tjaychen, as you may also remember, we discussed this earlier in the context of invalidating previously written `boot_data` entries in info pages (#9729). IIRC writing to the same address multiple times without erasing first doesn't work if ecc or scrambling is enabled, and is not recommended otherwise.

Please review and update the assignees and labels, thanks!

**Comment by tjaychen** [comment]
@jdonjdon 
yes that is right, if `ecc` or `scrambled` are enabled, writing to the same address does not work.
With just ecc enabled, we can "technically" write 0 to the same location again, but that's about it. 

The purpose of the `flash_ctrl_testutils_increment` though, was to create a bit-strike counter that DV can use for non-volatile tracking across escalation resets (because everything else is wiped).

**Comment by tjaychen** [comment]
i should add that the DV usage of this assumes that the region in question has neither ecc nor scramble enabled.
So we probably actually need to align this with what mask_rom does, otherwise these tests are not going to work in silicon.

**Comment by alphan** [comment]
@timothytrippel

**Comment by alphan** [comment]
@tjaychen I agree, since this is just for tests, I'd suggest allocating a huge chunk of space and treat flash words as bits.

**Comment by timothytrippel** [comment]
After further discussion with @alphan, there are actually two problems with our current setup:

1. consecutive writes to the same flash address (as you describe above), and
2. (as alphan pointed out) the nonvolatile scratch region currently resides in the signed code region, so if a test runs with ROM (as opposed to test ROM) and it writes to this region before issuing a reset, then the next signature verification won't work.

There are two things we can do to address both problems:

1. create two (large) nonvolatile scratch regions at the end of flash, out of the signed code region
    a. one region be a generic storage region for writing an arbitrary chunk of bits to once and reading it back
    b. one region can back an OTTF non-volatile counter primitive (which a lot of tests currently use this region for) that be incremented by tests using specific OTTF functions that under the hood treat each word as a bit (as @alphan describes above; so we don't write to the same address twice) 
2. mark them both as NOLOAD sections (we then don't need to initialize these to all 1s in the test code, and they wont be included in the signature computation)

If this sounds good, I can convert this to a task list.

**Comment by tjaychen** [comment]
this sounds good to me.
Although , the two scratch regions, is that something that mask_rom will need to add also? Because our bare metal tests on silicon will jump from mask_rom directly into the test right?

**Comment by timothytrippel** [comment]
The two scratch regions will be reserved in the [`ottf_common.ld`](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/lib/testing/test_framework/ottf_common.ld?q=ottf_common.ld&ss=opentitan%2Fopentitan), which sets aside space in flash, so it won't matter what boots the test, test ROM or (mask) ROM, right?

**Comment by tjaychen** [comment]
sorry, i meant in terms of region setup in the flash memory protect.
but I guess we could do that in ottf also?

**Comment by timothytrippel** [comment]
Oh yeah, we can handle that in OTTF initializations, right @alphan?

**Comment by tjaychen** [comment]
@tjaychen

**Comment by alphan** [comment]
> sorry, i meant in terms of region setup in the flash memory protect. but I guess we could do that in ottf also?

ROM leaves things disabled but unlocked so that the next stage can adjust as needed. IIRC this is also needed when running these with test_rom since the reset values for the default data region permissions are disabled:

![image](https://user-images.githubusercontent.com/57949550/189243726-ad52936c-0862-42c1-8a66-8d38f6bbc98c.png)
