### ISSUE TITLE
[plic] Review latest PLIC spec (1.0.0-rc5)

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#14839]
https://github.com/riscv/riscv-plic-spec/releases/tag/1.0.0_rc5

would be a candidate for the V1.0. Need to check the spec and may suggest changes to the `rv_plic` design.

> estimate 4

**Comment by andreaskurth** [comment]
Triaged for `rv_plic`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2 because I think we should review this for M2.5, though we may not want to make RTL changes unless necessary at this point.

**Comment by msfschaffner** [comment]
I gave the updated spec a quick look, especially the memory map and block diagram.
It seems unlikely that this requires any change from an RTL perspective, hence I am moving this to after M2.5.
We should at some point document that the `rv_plic` is compliant with v1.0 once it has been released officially.

**Comment by msfschaffner** [comment]
I had a look at the ratified [PLIC specification 1.0.0](https://github.com/riscv/riscv-plic-spec/releases/tag/1.0.0) and compared the interrupt flow and memory map with our implementation. I do not see anything that needs to be aligned, and it looks like our current implementation is fully compliant with that spec.
