### ISSUE TITLE
Meson build broken after googletest changes

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#1484]
A recent change to the meson build setup relating to googletest seems to have broken it, starting from a fresh respository:

```
> ./meson_init.sh
> ninja -C build-out/sw/sim-verilator all
```

Fails with the following

```
ninja: Entering directory `build-out/sw/sim-verilator'
[0/148] Generating googletest with a meson_exe.py custom command.
make: *** No targets specified and no makefile found. Stop.
Building googletest...
[43/148] Generating 'sw/device/lib/e287d45@@usb_ot@sta/usbdev_regs.h'.
WARNING: usbdev contains extra key reset_primary
WARNING: usbdev contains extra key other_reset_list
[68/148] Generating 'sw/device/examples/hello_usbdev/3468fca@@hello_usbdev@exe/usbdev_regs.h'.
WARNING: usbdev contains extra key reset_primary
WARNING: usbdev contains extra key other_reset_list
[143/148] Generating spiflash_export with a custom command.
FAILED: sw/device/lib/testing/empty_file_for_googletest_dependency.cc
/home/greg/.local/bin/meson --internal exe --unpickle /home/greg/work/opentitan_area3/opentitan/build-out/sw/sim-verilator/meson-private/meson_exe_bash_daf5a905982b98dd562a53de1673b00722bc367c.dat
ninja: build stopped: subcommand failed.
```

**Comment by GregAC** [comment]
A simple workaround is to remove the inclusion of the sw/device/lib/testing subdir from the meson build. 

Alter sw/device/lib/meson.build:

https://github.com/lowRISC/opentitan/blob/d9b0c733d47932ecef1cc832e19d73702f9efc28/sw/device/lib/meson.build#L4-L9

comment out the `subdir('testing')` line

**Comment by lenary** [comment]
@mcy please can you take a look at this?

**Comment by mcy** [comment]
Works on my machine with a fresh checkout. Googletest requires cmake (which has already propagated to the relevant lists of required packages), so maybe that's your issue?

**Comment by tjaychen** [comment]
weicai i think ran into a similar issue the other day..on our end at least,
it was missing cmake.  Could that be your issue also?

**Comment by imphil** [comment]
Can we improve meson to ... ?
- Check for the cmake dependency
- Show the output of the script it executes (at least in the error case)

**Comment by GregAC** [comment]
I did check that cmake was installed, also went and ensured I had installed all documented requirements listed at https://docs.opentitan.org/doc/ug/install_instructions/ to no effect.

@lenary and I have just done a bit of debugging and it appears we rely on have a version of cmake that is newer than what is currently supplied on Ubuntu 18.04 LTS (3.10.2), the culprit is this line:

https://github.com/lowRISC/opentitan/blob/d9b0c733d47932ecef1cc832e19d73702f9efc28/sw/device/lib/testing/meson.build#L21

the -B and -S options do not exist in 3.10.2 looks like they first appear in 3.13.5 

@lenary will take a look at things from here

**Comment by alphan** [comment]
@GregAC, sorry for this problem! @lenary, thank you for removing `cmake` dependency in #1493.
