### ISSUE TITLE
[escalation / rma entry] Better cross handling in the future

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#14867]
This came up during a discussion with @alphan.
Right now, rma_entry and escalation do not talk to one another.

This means in the worst case scenario, if the software (realistically rom or rom_ext, a piece of code that is either hard or impossible to update) gets into some kind of bad loop that constantly escalates / shuts down the chip, we may not be able to issue the rma entry instructions to debug why this is happening.

The rma entry process (because of flash) is quite long, so if an escalation is raised to the `pwrmgr` during that time and the device is reset, we will have just burned another life cycle transition opportunity.   The `pwrmgr` right now purposefully DOES NOT check if there is life cycle or flash activity ongoing, because the assumption was that the reset needs to take priority. 

For now, this will need to be mitigated by extensive testing of the rom / rom_ext stages to ensure that these kind of scenarios (outside of an attack) do not occur.   In the future, we could perhaps extend the escalation handshake protocols.

Specifically, alert handler could avoid blindly moving on to the next phase. Instead, it could handshake with the life cycle controller to better understand if there is a large ongoing event (basically extending the escalation clear function to all end points). Similarly the escalation targets could communicate with each other to better understand if something is higher priority than reset and needs to wait. 

These are just some rough ideas. I don't recommend changing anything now, but just filing this away as something for the future.

**Comment by tjaychen** [comment]
@cindychip 
@msfschaffner 
@moidx 

let me know if there's an issue already. I couldn't immediately find out.
I also can't remember if this is something we already discussed and deemed okay.

**Comment by tjaychen** [comment]
one thing i forgot about.  For now, as long as boot-strap isnt' disabled, we can also use it as a mechanism to halt ROM execution from getting too far.  We would then have more time to issue an RMA entry command.  This isn't a full proof solution, but would probably be sufficient in most cases.

**Comment by alphan** [comment]
Correct, flagged something similar [here](https://github.com/lowRISC/opentitan/pull/14577/files#r971919012) in the manufacturing test plan. bootstrap happens somewhat early in `rom.c` but still after `rom_start.S` so we will have limited capability to debug the ROM.

**Comment by andreaskurth** [comment]
Triaged for `pwrmgr`. https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease seems still appropriate.

**Comment by gdessouky** [comment]
Triaged for `lc_ctrl`: this issue has been derisked by implementing dedicated RMA strapping early on in rom_start.S and adding OTP and lc_ctrl checks to limit the duration of the busy loop here [#15613](https://github.com/lowRISC/opentitan/issues/15613). This works so long as the ability to ROM bootstrap by an external actor is not disabled through OTP.

I think we should close this issue now?

**Comment by msfschaffner** [comment]
Indeed I think we can close this now.
