### ISSUE TITLE
[bazel, opentitantool] Bitstream USR_ACCESS value remains the same after splicing a new ROM

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#14865]
Ran into this while working on #14460 and fixing some bootstrap issues.

`opentitantool` can detect if the FPGA is already programmed by the correct bitstream by comparing the `USR_ACCESS` value in the bitstream with the value transmitted over UART.
The `USR_ACCESS` value, however, remains the same after splicing the bitstream with a new ROM causing `opentitantool` to skip programming while running tests with `bazel test ...`.

@dmcardle @cfrantz @moidx @milesdai @timothytrippel Do you remember running into this issue or did I make a mistake somewhere?

**Comment by a-will** [comment]
The value for `USR_ACCESS` is currently the default, which is a timestamp of when Vivado built the original bitstream, so the current splicing tools won't change it. We might want to add that feature to the tool.

**Comment by timothytrippel** [comment]
by to "the tool", I assume you mean to the splicing tool? :)

**Comment by alphan** [comment]
> by to "the tool", I assume you mean to the splicing tool? :)

I thought @a-will meant the OT side of things not `updatemem`, right? I wonder if it has a flag for this or we could _splice_ that too maybe? Is that what you meant @a-will ?

**Comment by a-will** [comment]
Right, we can just adjust the value in the file. It's a pretty straightforward register write command in the beginning of the bitstream.

**Comment by alphan** [comment]
> Right, we can just adjust the value in the file. It's a pretty straightforward register write command in the beginning of the bitstream.

Great, I assume there is no integrity protection that we need to worry about, right?

**Comment by a-will** [comment]
> > Right, we can just adjust the value in the file. It's a pretty straightforward register write command in the beginning of the bitstream.
> 
> Great, I assume there is no integrity protection that we need to worry about, right?

Nope!

**Comment by alphan** [comment]
> > > Right, we can just adjust the value in the file. It's a pretty straightforward register write command in the beginning of the bitstream.
> > 
> > 
> > Great, I assume there is no integrity protection that we need to worry about, right?
> 
> Nope! No integrity protection.

Thanks for confirming. Started working on this.

**Comment by alphan** [comment]
Hmm, I tried modifying the bytes that [`scan_usr_access`](https://github.com/lowRISC/opentitan/blob/master/sw/host/opentitanlib/src/util/rom_detect.rs#L53-L62) reads but I got:

`Error: FPGA programming failed: unknown error`

I seem to be touching the correct bytes because I can program the FPGA if I set them to the original value.

**Comment by alphan** [comment]
![Screenshot_20220911-081821.png](https://user-images.githubusercontent.com/57949550/189527135-66860117-e2ec-4722-a5cb-20a8b9684d29.png)

**Comment by alphan** [comment]
I can confirm that the FPGA checks the CRC of the bitstream during configuration whenever it encounters a sequence like this (see table 5.19 in https://docs.xilinx.com/v/u/en-US/ug470_7Series_Config):

```
...
0x30000001 (write the following word to the CRC register and check)
0xe3ad7ea5 (value to write to the CRC register)
0x20000000 (NOOP)
0x20000000 (NOOP)
...
```

Searching for this pattern and replacing the command and the expected CRC value with NOOP removes the CRC check and makes the bitstream usable again.

Ideally I would like to keep this protection but since 
* `--define bitstream=gcp_splice` is intended for local development workflows,
* I'm not familiar with the bitstream format, and
* Handling this with updatemem (if possible) would be better in terms of maintenance,

I'll add a new `opentitantool` command that updates the `USR_ACCESS` value and removes the CRC check. This new command will move under the `fpga` command when #14830 is done. This should unblock local ROM development without additional hacks. We can add the CRC check back when we have more bandwidth. SG?

**Comment by a-will** [comment]
Ah, I made a bad assumption that USR_ACCESS was similar to the values I've played with before for multiboot and Master SPI configuration. Sorry, I should've checked!

**Comment by alphan** [comment]
> Ah, I made a bad assumption that USR_ACCESS was similar to the values I've played with before for multiboot and Master SPI configuration. Sorry, I should've checked!
> 
> Edit: I see now. The RCRC command resets the CRC register, effectively chosing what is covered by the CRC. It just so happens that multiboot and master SPI config are pretty much the only bits ordered before that command, and I wasn't aware. Oops!

No worries at all, your assumption actually encouraged me to give it a try :) I'll create a PR that adds this capability to opentitantool (but by removing the CRC check along the way) tomorrow - I already have some local changes. 

By the way, we don't have to limit this to local workflows because IIRC the USR_ACCESS values of the test_rom and rom bitstreams are the same, which is probably not what we want.
