### ISSUE TITLE
[sw/silicon_creator] Wrong address increment behavior in bootstrap

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#14874]
**Discovery**
Ran into this while working on #14461 and its fix (issue: #14873, pr: #14824). I decided to try a PAGE_PROGRAM command that starts at a page-misaligned address and has a large enough payload such that the next page is also modified. I noticed that the next page was not modified.

**Reproduction steps**
* A PAGE_PROGRAM command with
  * An address that is not page (256 bytes) aligned, and
  * a payload large enough such that the next page is modified.

**Description**
The way `addr` is updated in the snippet below is wrong. Instead of masking, this should have been an addition.

https://github.com/lowRISC/opentitan/blob/b6eaecc488c5384194ca8a2b4397377350d517d2/sw/device/silicon_creator/rom/bootstrap.c#L182-L192

**Workarounds**
Splitting such PAGE_PROGRAM operations into two: (1) write until the next page, (2) write starting at the start of the next page.

**Fix**
`addr += word_count * sizeof(uint32_t)`. See #14824.

**Could we catch this earlier?**
Not realistically. We already have a unit test but it covers the _wrong_ behavior. This is most likely due to writing the unit test very soon after the implementation so that the same mistake was made. Code reviews could potentially catch this but this is an easy to miss mistake.

**Next steps**
Prioritize e2e tests and try to maximize coverage even if we have unit or functional tests. Each type of test means a new opportunity to catch bugs.

**Comment by a-will** [comment]
> **Discovery** Ran into this while working on #14461 and its fix (issue: #14873, pr: #14824). I decided to try a PAGE_PROGRAM command that starts at a page-misaligned address and has a large enough payload such that the next page is also modified. I noticed that the next page was not modified.

The next page should _not_ be modified. PAGE_PROGRAM fills a page-sized buffer that wraps. Only one page is ever changed.

**Comment by alphan** [comment]
> > **Discovery** Ran into this while working on #14461 and its fix (issue: #14873, pr: #14824). I decided to try a PAGE_PROGRAM command that starts at a page-misaligned address and has a large enough payload such that the next page is also modified. I noticed that the next page was not modified.
> 
> The next page should _not_ be modified (We're talking about SPI flash pages here, right?). PAGE_PROGRAM fills a page-sized buffer that wraps. Only one page is ever changed. The comment in the code was correct.

Correct, the code was correct, I was wrong. For some reason I still find this behavior a little bit odd and keep forgetting it. Added a comment right above that line in #14824. Thanks for catching this!
