### ISSUE TITLE
[chip/prim_esc_receiver] check if prim_esc_receiver is out-of-sync

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14887]
This discussion comes from PR: https://github.com/lowRISC/opentitan/pull/14663#issuecomment-1244540532

We would like some checking between `prim_esc_receiver` and `alert_handler`, and `pwrmgr` to make sure they are not out-of-sync.

For example - When alert_handler/pwrmgr reset, will `prim_esc_receiver` counters clear to 0?
Currently if the `prim_esc_receiver` did not reset, and we configured the alert_handler to ping after reset, it is hard to find this error.

So the current suggestions are:
- [ ] probing some internal signals, or write assertions.
- [x] have some long FPGA test to re-iterate this sequence, or wait for longer time after wake up, just to catch if any modules are out-of-sync.

@moidx @tjaychen @msfschaffner 

> estimate 12
> remaining 2023-05-04 8

**Comment by andreaskurth** [comment]
Triaged for `pwrmgr`. May be relevant for M2.5, so assigning it there with existing https://github.com/lowRISC/opentitan/labels/Priority%3AP2.

**Comment by msfschaffner** [comment]
Regarding the assertion, I think adding a check that makes sure that the alert handler and escalation receiver are both reset together (with some small margin) should do the trick here.

**Comment by msfschaffner** [comment]
> estimate update
> FPGA update: 2
> assertion: 2

**Comment by msfschaffner** [comment]
Discussed with @matutem - this does not seem to be very important, given existing escalations test, hence moving this to backlog.

**Comment by matutem** [comment]
My preference would be to add SVA to check the alert handler escalation request and pwrmgr detecting it happen no more than a few cycles apart. As for pwrmgr triggering escalation when a ping timeout occurs, we could add the following assertions:
- the escalation receiver timeout counter never gets past half its range (i.e., the top bit is never set)
- the alert handler stops ping requests to the escalation receivers when escalation  reset is active
- the escalation receivers reset the timeout counters when escalation reset is active

The assertions should run in both unit and top level tests. I think we have enough stimulus to verify this.

**Comment by matutem** [comment]
More about this: it seems much of this is addressed if we assert each individual esc_sender/receiver pair is connected to the same clk and rst_n signals. That can be run as a connectivity test.

**Comment by matutem** [comment]
The proposal is to create a connectivity config that checks all prim_esc_sender for the clk_i and rst_ni. The check is expected to fail because pwrmgr's esc_receiver rst_i is NOT connected to the same signal as alert_handler's esc_sender rst_i, which is captured in https://github.com/lowRISC/opentitan/issues/23888.

**Comment by andreaskurth** [comment]
Discussed in the triage meeting: postponing this to M7 because the problem described in https://github.com/lowRISC/opentitan/issues/23888 is well understood but won't be changed for Earlgrey-PROD (because it doesn't have a significant impact). Thus the test in PR #23894, which currently fails because it tests the _eventual_ behavior, needs to be adapted to test the _current_ behavior and pass.

**Comment by vogelpi** [comment]
I've merged PR #23894 which closed this issue (adding connectivity checks) as the checks indeed pass with the current design.

Note that issue https://github.com/lowRISC/opentitan/issues/23888 tracking the fixing of the reset connections is still open.
