### ISSUE TITLE
[tlul_adapter_sram] assertion issue

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#1489]
Hi Eunchan, 

When I run fpv on spi_device and flash_ctrl, I found the assertion violation:
```
  `ASSERT(rvalidHighWhenRspFifoFull, rvalid_i |-> rspfifo_wready)
```
My sequence is to trigger a back to back read, and in the TL interface, set the `tl_i.a_valid` signal to low. So in `tlul_adapater_sram`, the `weady` signal is low.
However, `rvalid_i` signal seems to stay high for one more cycle, and triggers the assertion fail. 
In `u_memory_2p`:
```
 a_rvalid_sram <= a_req_q & ~a_write_q;
```
Could you help check if there is any potential protocol concerns? If not, maybe we can consider relax this assertion?

![waveform](https://user-images.githubusercontent.com/11466553/73890016-d43d5300-4825-11ea-8b00-57989b93deaa.png)

**Comment by eunchan** [comment]
Thanks @cindychip .

@tjaychen Looks like this is related to the increase of `Outstanding` by 1 in the request FIFO but not in the response FIFO inside `tlul_adapter_sram` to support back-to-back write. Should we increase the response FIFO also? or revise flash_phy to allow two Outstanding?

**Comment by tjaychen** [comment]
hmmm it does sound like maybe matching the rsp and reqfifo is the right thing to do. 

@eunchan i didn't quite get your point about flashy_phy though, can you elaborate?

**Comment by cindychip** [comment]
Close this issue as the PR merged and assertion error fixed.
