### ISSUE TITLE
[sw,tooling] optimize the `gen-flash-img.py` script

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#14891]

**Comment by timothytrippel** [comment]
As [identified](https://github.com/lowRISC/opentitan/pull/14533#discussion_r961127508) in #14533, the the [`gen-flash-img.py`](https://cs.opensource.google/opentitan/opentitan/+/master:util/design/BUILD;drc=74f9095ab484c27197d232a23a01e10786df8392;l=19) script takes a long time to run.

We should:
- [ ] optimize this, and
- [ ] remove/hardcode the `opentitan_multislot_flash_binary` `image_size` parameter to the size of the flash

**Comment by msfschaffner** [comment]
CC @a-will
