### ISSUE TITLE
[sw/silicon_creator] ROM digest and chip_info

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#14892]
Noticed while working on #14884

From the [rom_ctrl spec](https://docs.opentitan.org/hw/ip/rom_ctrl/doc/#:~:text=The%20top%20eight%20words%20in%20ROM%20(by%20logical%20address)%20are%20interpreted%20as%20a%20256%2Dbit%20expected%20hash.%20Unlike%20the%20rest%20of%20ROM%2C%20their%20data%20is%20not%20stored%20scrambled%2C%20so%20the%20expected%20hash%20can%20be%20read%20directly.):
> The top eight words in ROM (by logical address) are interpreted as a 256-bit expected hash. Unlike the rest of ROM, their data is not stored scrambled, so the expected hash can be read directly.

- [ ] Do we need to store `chip_info` in ROM?
- [ ] If yes, we need to reserve 256 bits at the top of ROM for its digest. See `test_rom.ld`.

@moidx @cfrantz @tjaychen

**Comment by timothytrippel** [comment]
Noticed this as well while working on #14890 :) ... was just about to file an issue thanks @alphan !

**Comment by tjaychen** [comment]
sorry i think i'm a little confused. So are we saying today during build, we insert chip_info into the top 128B, but during the `rom_ctrl` scramble we end up overriding it with the digest..? does that mean chip info doesn't print out correctly today at all?

**Comment by alphan** [comment]
From ROM sync: Remove chip_info, 3-/4-part version, print during shutdown. Use `VER:` for the prefix.
