### ISSUE TITLE
[kmac] entropy sw_mode with incorrect configuration

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14902]
Hey Eunchan, I have an error case below from SW user error and it potentially hangs the block:

1). Configures masked version of the kmac to SW entropy mode.
2). Set `cfg.entropy_ready` bit to 1 and configure the rest of the `cfg_shadowed` register.
3). Set `cfg.regwen` to 1  ---> Here is a user error, because we did not write the `entropy_seeds`
4). Send cmd: `start` and `process` and send keys and data
5). Wait for `kmac_done`, but never received

A few concerns about this sequence:
1). The whole sequence did not flag any error, I think if this case hangs, it is hard to debug.
2). I believe we cannot get out of this sequence unless reset kmac.

Suggestions:
1). Maybe we can use `err_process`? Or allow `entropy_seeds` to not gate by `cfg_regwen`, and gives user a chance to re-enter entropy_seeds?
2). Maybe we can output some error message if we did not input `entropy_seeds` or issue `entropy_ready` when we lock the `cfg_regwen`?

Please let me know what you think :)
Thanks,
Cindy

**Comment by eunchan** [comment]
I think `2)` was what I intended. Somehow it was changed later? Let me check the history.

**Comment by eunchan** [comment]
Hum, the FSM accept seeds at first then never update the seeds at all. Anyhow, removing `regwen` from `ENTROPY_SEED[i]` seems fine to me as still it only accepts once.

**Comment by eunchan** [comment]
We can close this.
