### ISSUE TITLE
[dv] spi_host_driver squashes end of flash transaction

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#14914]
With back-to-back SPI flash transactions using the new chip_if interface, the spi_host_driver can squash the end of the first transaction. While stepping through the simulation, CSB went high to end the first transaction, then immediately went low at the beginning of the next one. There was zero simulation time in the middle, causing the two transactions to merge into one.

In addition, it seems the check for X on I/Os is also incompatible with the spi_host_driver's current behavior, since it ends transactions by setting sio[0] to 1'bx, not 1'bz. Is this desired?

CC @tjaychen @weicaiyang

**Comment by tjaychen** [comment]
o yeah.. driving CSb to `x` probably isn't desired in this case. It's a bit like driving `rst_n` or `a_valid` to `x`.

**Comment by weicaiyang** [comment]
Thanks @a-will for raising this.

> With back-to-back SPI flash transactions using the new chip_if interface, the spi_host_driver can squash the end of the first transaction. While stepping through the simulation, CSB went high to end the first transaction, then immediately went low at the beginning of the next one. There was zero simulation time in the middle, causing the two transactions to merge into one.

I plan to add a minimum delay between 2 b2b flash transactions in the driver. Default is randomized between 1-100 cycles.

> In addition, it seems the check for X on I/Os is also incompatible with the spi_host_driver's current behavior, since it ends transactions by setting sio[0] to 1'bx, not 1'bz. Is this desired?

As discussed, since these are dedicated pins, we could exempt them from checking X. There is some value to have X when it's inactive, in case chip samples the X at that time. 
Perhaps I can also add an assertion to check sio_en is 0 when CSB is inactive.

**Comment by weicaiyang** [comment]
@a-will perhaps we can close this issue if https://github.com/lowRISC/opentitan/pull/14942 solves the problem

**Comment by a-will** [comment]
It does. Thanks!
