### ISSUE TITLE
Generated documentation doesn't match up to the actually-instantiated hardware

### ISSUE THREAD

**Issue by gkelly** [lowRISC/opentitan#1496]
I can't remember if this has been filed already, but I want to make sure it's captured.  This is getting bumped into by other devs: https://github.com/tock/tock/pull/1592.  IIRC it's because the peripherals are being instantiated with parameters from the toplevel, while the documentation is being generated with the default values from the IP block.

@tjaychen @eunchan for visibility.

**Comment by silvestrst** [comment]
I have opened an issue regarding this a while ago #1068 . I agree this has caught me out when I first started working on PLIC, I think @alistair23 had similar experience.

**Comment by lenary** [comment]
This has been solved by #1526 (for the moment).
