### ISSUE TITLE
[i2c/dv] i2c_rx_tx_vseq lockup

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#14990]
the `i2c_rx_tx_vseq` forks two threads. One thread issues i2c host transactions, while the other thread reads back expected data. 
The two threads can get out of sync (specifically, the receive FIFO is not empty, but somehow the expected_item queue maintained on the host side is empty. likely there is a bug in the read data count or the queue creation). 

When that happens the `rdata` handling blocks the `i2c_scoreboard` from completing `tlul` transaction handling. This blockage stops `csr` writes from updating mirror values, and causes a lot of the downstream programming to go haywire and program invalid values.  Sometimes these invalid values cause the i2c_host controller to wait essentially an infinite amount of time for clock pulses, therefore timing out the tests in the end.

I'm filing this issue as a reference since it will take some detail digging to find out exactly what has gone out of sync, this is just a general description. 

These failures will lead to the `i2c_host_smoke_test` to fail from time to time.

**Comment by sriyerg** [comment]
Do you mean the `i2c_base_seq` in the I2C agent area?

**Comment by tjaychen** [comment]
no, it's the scoreboard itself. There's a section handling the format byte that sets the expected data, and a section handling read data that has a wait statement in there.  When this thing dies, the wait statement is just stuck, so no further tlul elements are processed.  That eventually causes the mirror values to go off the rails. 

The read is preceded by an empty check, so it's doing what it's supposed to, so my assumption is the expected data gets out of sync somehow.

**Comment by tjaychen** [comment]
after studying this more..it looks like the issue is on both the `fdata` and `rdata` handling.
In `fdata`, only the stop transaction is pushed an expected pending item. This means when a chain read is issued (no stop), the `rdata` gets stuck forever because there is no pending item. 

If we let `fdata` push on all transactions, then there is a problem in `rdata` handling because right now it doesn't understand to concatenate the number of transactions, and thus scoreboard comparison will later fail.

The fix should be fairly simple, I'll have a look.
