### ISSUE TITLE
[dvsim] Dashboard Includes Testpoints Without "dv" Tag

### ISSUE THREAD

**Issue by rnongie** [lowRISC/opentitan#15009]
Expected behavior was that dashboard [CHIP Simulation Results](https://reports.opentitan.org/hw/top_earlgrey/dv/latest/report.html) **_only_ includes testpoints**, in testplan HJSON file, **with "dv" tag**.  This does not appear to be the case (see example below)

Please help to investigate and debug this issue - accurate tracking of the M2 top-level test progress relies on this dashboard.

<br>

**Example Issue**

[rom_e2e_testplan.hjson](https://github.com/lowRISC/opentitan/blob/master/sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson) - contains a number of testpoints without "dv" tag (merged on Friday, 9/16 [PR#14980](https://github.com/lowRISC/opentitan/pull/14980))

e.g. 
```
   {
      name: rom_e2e_shutdown_redact
      . . . 
      tags: ["rom", "fpga", "silicon"]
      stage: V2
      tests: []
    }
    {
      name: rom_e2e_shutdown_watchdog
      . . .
      tags: ["rom", "fpga", "silicon"]
      stage: V2
      tests: ["rom_e2e_shutdown_watchdog"]
    }

```

However, [CHIP Simulation Results](https://reports.opentitan.org/hw/top_earlgrey/dv/latest/report.html) (as of Sunday, 9/18) lists these as "Unwritten" testpoints

STAGE | NAME | TESTS | MAX JOB RUNTIME | SIMULATED TIME | PASSING | TOTAL | PASS RATE
-- | -- | -- | -- | -- | -- | -- | --
V2 | rom_e2e_shutdown_redact | rom_e2e_shutdown_redact |   |   | 0 | 0 | --
V2 | rom_e2e_shutdown_watchdog | rom_e2e_shutdown_watchdog |   |   | 0 | 0 | --

The expectation was that because these testpoints do not include the "dv" tag, that they would not show up on this dashboard at all.  (they will be tracked separately as FPGA tests)

**Comment by sriyerg** [comment]
To achieve this, we need to:

- [ ] Explicitly tag testpoints with "dv" 
- [ ] Update `chip_sim_cfg.hjson` to include only the tests with `dv` tag

We were not explicitly tagging tests with dv because the motivation was for dv to be a superset. We also need to be careful when adding new testpoints to the testplan - if we miss adding the `dv` tag, it wont show up anywhere.

**Comment by rnongie** [comment]
Hello Sri, through my discussions with TimT and TimC, we had assumed the regression _intended to_ filter for `dv` tag (but missed doing so).  However, it seems from your comment that this was _not the original intention_ as [chip_testplan.hjson](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/chip_testplan.hjson) does not currently contain the `dv` tag

So before asking you to go make all these changes, I'd like to take a step back and ask **what is the best approach to the issue we are trying to solve?**

The challenge is that **[rom_e2e_testplan.hjson](https://github.com/lowRISC/opentitan/blob/master/sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson) contains a mix of `V2` testpoints - some are FPGA-only, some are FPGA + DVSim** (we don't want to track the ~50 FPGA-only tests on [CHIP Simulation Results](https://reports.opentitan.org/hw/top_earlgrey/dv/latest/report.html) dashboard; they are not meant to run in this regression)

Here are a few approaches I can think of:

- **Include only testpoints with `dv` tag** (all testplan files)
   - _As you noted above_, requires editing `chip_testplan.hjson`
   - New testpoints are at risk, if the user forgets the `dv` tag
- **Exclude testpoints with `no_dv` tag** (all testplan files)
   - Requires re-editing `rom_e2e_testplan.hjson`
   - New testpoints are not at risk; they are included by default
- **Include all testpoints in `chip_testplan.hjson` + Include only testpoints with `dv` tag in `rom_e2e_testplan.hjson`**
   - Probably a more complicated script
   - Neither testplan needs to be edited.  New testpoints are not at risk.

What are your thoughts?

**Comment by tjaychen** [comment]
yeah i think i agree with @rnongie on his last option.
I think it is safe for us to assume that everything under `top_earlgrey/dv/blah` should be natively opt-in, whereas tests in other hjsons (`rom_e2e`, potentially `manufacturing`) should be opt-out unless otherwise specified. 

Would that be more reasonable @sriyerg ?

**Comment by sriyerg** [comment]
I was under the impression that we would tag the remaining rom e2e tests as V3 so that we dont have to track them for m2. I dont know what you all decided, but choosing upfront to not run all rom e2e tests in dv sounds like a bad idea. 

In any case, the `nodv` tagging is currently already supported and will make the intent clear.

**Comment by rnongie** [comment]
_Alphan or TimT may be able to explain better, but this is what I understand -_ 

Alphan and team plan to **complete _all_ ROM E2E tests in `rom_e2e_testplan.hjson` for M2 _on the FPGA._**  Therefore the tests are appropriately labeled as `V2` in the file.  (it would be misleading to relabel them as `V3` simply for the dashboard; this labeling decision only came up on Friday 9/16)

**Only 7 of these ROM E2E tests plan to be added to DVSim for M2** (these are currently tagged `dv`, while the others do not include the `dv` tag).  The remaining will be FPGA-only for M2, with inclusion in DVSim as "best efforts after M2".  

Hope this makes sense?  Please let me know if any other questions.

-

**Please instruct TimT on what tag to use (is it `nodv` or `no_dv` or something else?) to exclude the FPGA-only tests for M2 from DVSim**

**Comment by timothytrippel** [comment]
Yeah that's right (@alphan, @cfrantz, @moidx can confirm) but I believe the intention was to **definitely** run 7 ROM E2E tests (labeled P1) in DV and **hopefully** run as many as possible remaining V2 ROM E2E tests as our infrastructure will tolerate in the short term, as @rnongie describes.

That said, IIUC, I just need to add the `no_dv` to the V2 ROM E2E tests that are considered P2, and we can remove this tag from P2 tests as we add them to DV? 

Does this sound good to everyone?

**Comment by sriyerg** [comment]
> Yeah that's right (@alphan, @cfrantz, @moidx can confirm) but I believe the intention was to **definitely** run 7 ROM E2E tests (labeled P1) in DV and **hopefully** run as many as possible remaining V2 ROM E2E tests as our infrastructure will tolerate in the short term, as @rnongie describes.
> 
> That said, IIUC, I just need to add the `no_dv` to the V2 ROM E2E tests that are considered P2, and we can remove this tag from P2 tests as we add them to DV?
> 
> Does this sound good to everyone?

You will also need to edit the `testplan` line in `chip_sim_cfg.hjson` to add `:-no_dv` tag at the end to instruct dvsim to not map those testpoints.

**Comment by alphan** [comment]
SGTM, thanks @timothytrippel!

**Comment by timothytrippel** [comment]
#15171 should clean this up.
