### ISSUE TITLE
[chip-test] chip_sw_inject_scramble_seed

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15035]
### Test point name

[chip_sw_inject_scramble_seed](https://github.com/lowRISC/opentitan/blob/1f3a24718d33c975f12f902994c39d2497b8623e/hw/top_earlgrey/data/chip_testplan.hjson#L3220)

### Host side component

SystemVerilog

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

@tjaychen, @moidx, @jdonjdon

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by engdoreis** [comment]
Reopening this issue as it never passed in the nightlies:




Tests | latest | 2022.10.10 | 2022.10.08/1 | 2022.10.08/2 | 2022.10.06 | 2022.10.05/1 | 2022.10.05/2 | 2022.10.03/1 | 2022.10.03/2 | ... | 2022.09.30 | 2022.09.29 | 2022.09.28 | 2022.09.27 | 2022.09.26/1 | 2022.09.26/2 | 2022.09.26 | 2022.09.24 | 2022.09.23 | Suite
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
chip_sw_inject_scramble_seed | 0.00 | 0.00 | 33.33 | -- | -- | -- | -- | -- | -- | ... | -- | -- | -- | -- | -- | -- | -- | -- | -- | chip_sw_inject_scramble_seed

**Comment by tjaychen** [comment]
this should have been fixed by #15362 
This was just merged yesterday, so likely has not been reflected in nightly results yet.
