### ISSUE TITLE
[rom] how to deal with scramble setup 

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15036]
This is a tracking issue related to #15035 and [this comment](https://github.com/lowRISC/opentitan/pull/14577/files/d7a59375d57a8a647ce22bb97737ccdc4eb6755f#r973591155)

The basic question is that if flash scramble is enabled, how does ROM figure out which regions it must setup as "scramble enabled"

**Comment by tjaychen** [comment]
@moidx 
@cfrantz

**Comment by msfschaffner** [comment]
CC @timothytrippel
