### ISSUE TITLE
[flash_ctrl] flash filesystem support

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15037]
To support a general flash file system, the flash must be able to support the following behavior:

Assume ECC on a region is enabled

1. The region can be written from an erased value (all 1's) to the desired value (for example 0xFFFF_FFFF_FFFF_FFFF -> 0xAB)
2. The region can be written, without an erase, from the desired value to all 0's (for example 0xAB -> 0x0). 

This test can be done at either block level or chip level, but block level would be faster.

**Comment by tjaychen** [comment]
@jdonjdon once you've reviewed the latest file system assumptions, can you close this if you think we are all good?

**Comment by jdonjdon** [comment]
Closed with #15214
