### ISSUE TITLE
[DIFs reset] Preserve/reset after jump from boot_rom to flash

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#1505]
Some of the peripherals are used and initialised in the `boot_rom` stage, which means that these peripherals will inherit the configuration from `boot_rom` unless reset.

@lenary had a point that perhaps for some peripherals (possibly `allert_handler`), would be desirable to minimise the time in which they cannot accept IRQs.

If this is a genuine concern, then one of the solutions could be to add a `reset/preserve` flag to DIF init routines. For example, default behaviour with reset flag `false` would be to only initialise state relevant data, without resetting and reconfiguring the peripheral.

It might be I am overthinking this, but decided to flag it up in case I am onto something here.

Relevant PR and some background discussion is in #1483 .

**Comment by silvestrst** [comment]
@gkelly @lenary @mcy @asb @alphan @jon-flatley

**Comment by silvestrst** [comment]
I went ahead and implemented what I think it could look like.

**Comment by alphan** [comment]
Please see my comments in #1510.
