### ISSUE TITLE
[rv_core, ibex] Address translation and instruction cache

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#15052]
Observed this while trying to run `rv_core_ibex_address_translation_test` with `rom` and instruction cache enabled (#14503 turned out to be a very beneficial exercise):

* Configure an address translation slot, e.g. map `0xa0000000` to the address of some function `fn0`.
* Call `0xa0000000`. `fn0` is executed
* Configure the same slot, this time map `0xa0000000` to the address of another function `fn1`.
* Call `0xa0000000`. `fn0` is executed instead of `fn1`. (I don't think this is the expected behavior, right?)

When I disable the instruction cache in `rom`, `fn1` is executed in the last step as expected and the test passes.

I can push a PR for reproduction but wanted to create the issue first since this looks like something we would like to fix.

Note: We could invalidate the cache in software, if possible, whenever address translation is configured but let's think about that option if a more proper fix is not feasible.

**Comment by GregAC** [comment]
This is an artifact of the address translation being invisible to the Ibex core. So from Ibex's perspective there is no bug here. In a way you could see it like dynamically altered code, after you've written instructions to memory you must do a `FENCE.I` to remove stale code from the ICache. We need to do the same here.

We could add an external ICache flush request to Ibex (itself a generally useful feature) and then had the address translation use it. It'd be simple to add though it does have a DV impact so I'd prefer not to unless we really don't like the software only fix.

**Comment by tjaychen** [comment]
ah @GregAC beat me to it, yeah this is because translation is unknown to ibex. It's "stupid translation" in nature.
I think like Greg said, maybe we need to require in software, any time we want to change the map, we have to require an icache disable / flush.

**Comment by alphan** [comment]
SGTM, but this should be clearly documented, right? I don't remember seeing this in the rv_core hwip spec.

**Comment by tjaychen** [comment]
ah you are right. It is not. Let me add a note.
To be fair i didnt even realize it until you pointed it out in this issue hehe.

**Comment by alphan** [comment]
I have a draft here: #15056

**Comment by msfschaffner** [comment]
Lowering priority since the main issue has been addressed. Documentation pending.

**Comment by tjaychen** [comment]
closing this now!
