### ISSUE TITLE
[SPI_Host] Coverage closure

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15078]
Need to improve functional coverage of SPI_Host above 90%.
Changes made by Weicai in SPI_Agent may bring the values down
- [x] spi_host_event: 60%
- [x] spi_host_sw_reset: 64%
- [x] spi_host_idlecsbactive: 76%
- [x] spi_host_overflow_underflow: 80%
- [x] spi_host_status_stall: 82%

spi_host_speed being worked on as part of https://github.com/lowRISC/opentitan/issues/15075
spi_host_stress_all being worked on as part of https://github.com/lowRISC/opentitan/issues/16014

> original estimate 12
> estimate 20

Increased effort estimate based on potential changes coming in from spi_agent that Weicai is working on
> Corresponds to SH:7 on internal tracking

**Comment by johngt** [comment]
Functional coverage
91% cover group
Review cover points
Identify if there are missing major cover points
Expression Coverage barely over the limit (>90%)

DV Code pulled into expression coverage? 
Sanity check.

**Comment by andreaskurth** [comment]
Update:
- Pass rate of `spi_host_speed` is back to 100% after the merge of #16015. `spi_host_stress_all` is currently at 64% pass rate; the resolution of this is tracked in https://github.com/lowRISC/opentitan/issues/16014.
- Coverage is >= 90% for all criteria.
- Reviewing cover points / checking for missing cover points: I think this is not necessary for M2 since this module has been signed off for V2 and V2S. If such an effort is necessary for V3, it should be tracked there.

**Comment by johngt** [comment]
@andreaskurth - I agree that given SPI_Host already passed V2S that getting back up to >90% coverage was the primary focus. 
Do we have the cover-point levels for the items above so that I can capture the current status? I'd like to update the checkmark points above with the current levels and then close this out.
We can then close out this issue and have a related V3 issue put in the backlog.

**Comment by andreaskurth** [comment]
> Do we have the cover-point levels for the items above so that I can capture the current status? I'd like to update the checkmark points above with the current levels and then close this out.

All tests listed in the checkmark points are at 100% pass rates.

**Comment by johngt** [comment]
Have created issue https://github.com/lowRISC/opentitan/issues/16317 for reviewing cover points of SPI_Host post M2.
As such believe we can close this out.
