### ISSUE TITLE
[SPI_Host] Regression fixing

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15075]
> original estimate 16
> estimate 12
> remaining 2022-11-10 4
> Corresponds to SH:4 on internal tracking

**Comment by abdullahvarici** [comment]
I am still working on this issue. Started with spi_host_speed test and created a PR increasing pass rate 0% to 50%: https://github.com/lowRISC/opentitan/pull/16015

**Comment by tjaychen** [comment]
thank you for taking this on!

**Comment by abdullahvarici** [comment]
With the last commit on PR #16015, I think most of the tests will pass. We are running a full regression test on spi_host and spi_device using that PR and will publish the results. When the discussions are over, and after seeing the test results, maybe we can merge the PR and close this issue.

estimate 4 

@johngt

**Comment by abdullahvarici** [comment]
With the PRs #16015 and #16253, the overall pass rate increased to 97% and the overall coverage score increased to 96%. Now I am working on fixing spi_host_stress_all test (pass rate = 64%). I hope it will be completed in 1 or 2 days. @johngt

**Comment by andreaskurth** [comment]
`spi_host_speed` has been fixed by @abdullahvarici in #16015, so that part is complete.

`spi_host_speed_test` is already being tracked in https://github.com/lowRISC/opentitan/issues/16014, so I suggest @johngt to move the remaining estimate of 4 over there and close this issue.

**Comment by johngt** [comment]
@andreaskurth / @abdullahvarici - I'm adjusting the effort to be 4 lower on this one, with the remaining effort shifted over to https://github.com/lowRISC/opentitan/issues/16014
Closing this issue out.
