### ISSUE TITLE
[bazel] fusesoc invocation is getting passed duplicate parameters 

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#15070]
It seems Bazel's incovation of fusesoc is passing the duplicate sets of parameters:

```
fusesoc '--cores-root=.' '--cores-root=.' '--cores-root=.' run '--flag=fileset_top' '--target=sim' --setup --build '--build-root=bazel-out/k8-fastbuild/bin/hw/build.verilator_real' lowrisc:dv:chip_verilator_sim '--verilator_options=--threads 1' '--verilator_options=--threads 4'
```

This might be impacting #14353.

**Comment by drewmacrae** [comment]
Adding @a-will because I think this relates to the "required_args" vs "default_args" handling. I'm not sure if anyone has made any intentional changes to the fusesoc logic recently, so this is likely just the first time someone looked at fusesoc's invocation.

**Comment by a-will** [comment]
> Adding @a-will because I think this relates to the "required_args" vs "default_args" handling. I'm not sure if anyone has made any intentional changes to the fusesoc logic recently, so this is likely just the first time someone looked at fusesoc's invocation.

This is an entirely separate rule, though, (completely unrelated to opentitan_functest) and the rules must be written to accommodate the argument processor in whatever program is being invoked. Were you just looking for guidance on how to handle the args for fusesoc?

**Comment by a-will** [comment]
I'll note that there are two places where the rules and targets create conflicting options.

cores-root doesn't eliminate duplicate directories:
https://cs.opensource.google/opentitan/opentitan/+/master:rules/fusesoc.bzl;l=45-47;drc=aa87069dcb5f8d9430f175f93341d9c50663dcc8

verilator options for threads is specified directly in the verilated core's target, while _also_ having a different value in the build setting in the same file:
https://cs.opensource.google/opentitan/opentitan/+/master:hw/BUILD;l=33

**Comment by drewmacrae** [comment]
> This is an entirely separate rule, though, (completely unrelated to opentitan_functest) and the rules must be written to accommodate the argument processor in whatever program is being invoked. Were you just looking for guidance on how to handle the args for fusesoc?

I misunderstood your stance on redefining arguments as it should be done this way and tools should support it (and it seems like fusesoc does, I've been building for the correct number of threads pretty reliably, but maybe that's specific to my system or version of fusesoc) and this is how we choose to invoke OTT in the functests. I don't find it particularly readable, but if you run a simulation built with these args I think you should see it use that many cores.

**Comment by drewmacrae** [comment]
> cores-root doesn't eliminate duplicate directories:
> https://cs.opensource.google/opentitan/opentitan/+/master:rules/fusesoc.bzl;l=45-47;drc=aa87069dcb5f8d9430f175f93341d9c50663dcc8

This might create issues, I'm not familiar with the usecase
