### ISSUE TITLE
[SPI_Host] SPI enable feature test

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15076]
> estimate 16
> Corresponds to SH:5 on internal tracking

**Comment by johngt** [comment]
@GregAC / @andreaskurth - wondering if you could help scope this out and detail a little bit more of what is needed to help @hcallahan-lowrisc commence this work. TIA

**Comment by hcallahan-lowrisc** [comment]
I think it may have come from https://github.com/lowRISC/opentitan/issues/13582

**Comment by andreaskurth** [comment]
> I think it may have come from #13582

I think so, too. #13582 originated from https://github.com/lowRISC/opentitan/issues/5158. Both issues say post V2, thus M3.

**Comment by johngt** [comment]
@tjaychen / @weicaiyang  there is a corner case as identified back at the time of the review.
See - https://github.com/lowRISC/opentitan/issues/5158#issuecomment-873458332
If we want to test for this corner case we could potentially do this on FPGA + EEPROM or without either BFM or FPGA+EEPROM.

If we don't need to address this corner case now, we can leave this as a V3 task. Otherwise I'll bring it back into V2.

**Comment by weicaiyang** [comment]
When we brought this last time, we were about to sign off V2 and the block maintainer was leaving the project (there were no time for them to do any more work). Also we didn't have a new maintainer for this block at that time. But the regression/coverage metrics were enough for V2.
Besides, it seemed some issues on the scb need to be fixed. Then @martin-lueker  and I agreed to push this to V3

I don't find the previous maintainer left a PR for this test. We may need to create a test and update scb for it.

Given we don't have too much time for M2, I would suggest bringing regression back 90%+ first before adding this test.

**Comment by tjaychen** [comment]
That sounds good to me. So prioritize 90% first, and if we can achieve that within schedule, then aim to resolve this in M2/V2?

**Comment by weicaiyang** [comment]
> That sounds good to me. So prioritize 90% first, and if we can achieve that within schedule, then aim to resolve this in M2/V2?

Agree. SGTM

**Comment by martin-lueker** [comment]
Agreed as well.

**Comment by msfschaffner** [comment]
@johngt do you still expect to resolve this by M2?

**Comment by johngt** [comment]
Effort is still ongoing here and we expect that this should be met for the milestone.
@hcallahan-lowrisc expects to have something by the end of the day

**Comment by hcallahan-lowrisc** [comment]
I've made some progress on this issue, but not quite done yet.
I'm optimistic to have this completed by end of tomorrow.
