### ISSUE TITLE
[i2c device] consider renaming "ack_stop" interrupt "ack_complete_fault"

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#15081]
the "ack_stop" interrupt is associated with the end of a transaction that is signaled by a STOP or a START condition. It's using the word stop in a way that's distinct from the I2C spec and therefore confusing. We should consider renaming it to avoid future confusion

**Comment by a-will** [comment]
Perhaps "target_transaction_complete" or "target_transaction_done"? (since it doesn't require an ACK)

**Comment by drewmacrae** [comment]
It's subtler than this I think... It used to be named "tx_ack_stop", but the name was changed in all but one place. I think it's only for the abnormal case where an I2C read transaction terminates with an aknowledged bit. That's why there wasn't one for "acq_ack_stop" (though I would like that name very much if there was a good reason to use it)

**Comment by drewmacrae** [comment]
I don't think I realized much of this when I wrote the title for this issue.

**Comment by drewmacrae** [comment]
We could also rename it:

- abnormal_rd_termination
- rd_terminated_before_nack

**Comment by tjaychen** [comment]
just to note a few things about current i2c

- trans_complete interrupt applies only to "host" mode, it does not apply to "target" mode.
- ack_stop is checking for a very specific case where the host is supposed to send a nak-stop during a read but sends ack stop instead.  This doesn't really seem important. We could just look for stop/start and call it a day. 

So I am tempted in this case to actually get rid of `ack_stop` altogether, and instead use the `trans_complete` to actually indicate completion.  

This is related to #15226

**Comment by drewmacrae** [comment]
> * trans_complete interrupt applies only to "host" mode, it does not apply to "target" mode.

This isn't clear in the documentation and I'll need to fix the DIF and the chip_sw_i2c_device_tx_rx entry in the testplan.

There's also a surprising assymetry between tx_empty and tx_nonempty (tx_nonempty occurs when a stop is encountered but there's remaining data to be transmitted, while tx_empty occurs when the transmit fifo is empty but the transaction is continuing.)

**Comment by tjaychen** [comment]
This has been done, a nd we have renamed this "unexpected stop"
