### ISSUE TITLE
[rtl] OTBN secure wipe on RMA entry or DFT enable?

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#15098]
https://github.com/lowRISC/opentitan/issues/14995 has highlighted to me that the new functionality we added to trigger secure wipe to ensure any sensitive information is wiped before scan entry is triggered on entry to the RMA lifecycle state.

As I understand it in the RMA lifecycle state CPU execution is still allowed and in particular debug is enabled. With the current setup once you enter RMA OTBN will be locked and be unusable so you won't be able to execute anything on Ibex that needs to use OTBN and hence cannot use sensibly use debug with anything that uses OTBN.

Was this intended? Or should this secure wipe only be triggered on entry to scan mode (which can be done from the RMA state)?

**Comment by GregAC** [comment]
@vogelpi @andreaskurth @cdgori @tjaychen @msfschaffner @cdgori From your recollection of the discussion here was this the intended behaviour? We should ensure this is explicitly documented as it may be surprising behaviour.

**Comment by vogelpi** [comment]
Hi @GregAC ,
AFAIK this is exactly the behavior we wanted. Only once the flash is completely wiped and OTBN has finished secure wipe, LC will enter the RMA state. Then the chip is reset and comes back up in RMA state in which scanmode can be entered.

I've done a PR #15086 to clarify in the documentation that OTBN needs to be reset after handling an RMA request.

**Comment by GregAC** [comment]
To put it another way, are we happy that any debugging that occurs in the RMA state cannot execute code that uses OTBN?

**Comment by vogelpi** [comment]
Just checked again with @msfschaffner , after receiving the RMA ack from OTBN, LC starts reprogramming OTP and then enters a virtual scrap state where everything inside the chip is disabled. Only after the next reset, the new OTP state becomes active and the chip is effectively in RMA state.

At this point, also OTBN is no longer in the locked state because the RMA req signal is again `Off` and code can use OTBN.

**Comment by GregAC** [comment]
Ok sounds good, I'll close this
