### ISSUE TITLE
[bazel] error out when sha256 is missing

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#15110]
To enable building targets in an airgapped environment, all external Bazel repos (typically imported via an `http_archive` rule) must contain a valid `sha256` field. Since the `sha256` field of the `http_archive` rule is [optional](https://bazel.build/rules/lib/repo/http#attributes), builds don't fail in CI, rather a message is printed to STDOUT that indicates a `sha256` field is missing. However, to prevent regressions, it would be beneficial if builds did fail if a `http_archive` rule is missing a `sha256`.

One thought to address is to create a wrapper repository rule around the `http_archive` rule that makes the `sha256` field mandatory.

Another thought is to make the [`download_bazel_dependencies`](https://cs.opensource.google/opentitan/opentitan/+/master:azure-pipelines.yml;drc=7e3bb0a70951a7542f13f7d7143c3f55acb0e8a1;l=143) CI job blocking again (which it probably should be since we are using this to autogenerate airgapped images now), and have this job fail if any missing sha messages are printed to STDOUT.

**Comment by a-will** [comment]
> Another thought is to make the [`download_bazel_dependencies`](https://cs.opensource.google/opentitan/opentitan/+/master:azure-pipelines.yml;drc=7e3bb0a70951a7542f13f7d7143c3f55acb0e8a1;l=143) CI job blocking again (which it probably should be since we are using this to autogenerate airgapped images now), and have this job fail if any missing sha messages are printed to STDOUT.

Is this job still flaky? Did we root cause and resolve it?

**Comment by timothytrippel** [comment]
For the most part it looks like original flakiness has subsided quite a bit (IIRC it used to fail ~50% of the time, now it seems to happen less frequently (e.g., [1 in 12 past jobs ran](https://dev.azure.com/lowrisc/opentitan/_dashboards/dashboard/0bdec629-d160-4aca-89a7-33efa67e1349)).

There is only one recent [error](https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=94968&view=logs&j=ff50edb1-eefa-5a33-ff7c-ba45909ca695&t=e5d5da18-9454-5cb0-2232-96acf750ae72) and it seems to be transient, originating from a failed repo download. Similar to failed package downloads we encounter from time to time in other jobs.

Perhaps we can gather better stats on the failure rate before we make it blocking.

**Comment by timothytrippel** [comment]
Closing this, as addressing #15136 will also resolve this issue.
