### ISSUE TITLE
[i2c/dv] Add option to control i2c agent verbosity

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15129]
instead of relying on `UVM_HIGH` which tends to bring in too much information while debugging, @martin-lueker suggested we follow `aes` and `entropy_src` example and do it with more granularity.

See [this example](https://github.com/lowRISC/opentitan/blob/master/hw/ip/entropy_src/dv/entropy_src_sim_cfg.hjson#L107-L128) for how it can be done.

**Comment by msfschaffner** [comment]
@jdonjdon up to you whether this is needed for V2 or not.

**Comment by jdonjdon** [comment]
> @jdonjdon up to you whether this is needed for V2 or not.

ack. I will update nextweek.

**Comment by tjaychen** [comment]
@jdonjdon i think this one really belongs in the `backlog` category, it serves no real DV purpose otherwise.
Let me know if you disagree, otherwise I'll drop it to P4 for now.

**Comment by jdonjdon** [comment]
> 

I agree with putting this to p4.

**Comment by andreaskurth** [comment]
Low prio DV ergonomics improvement --> M5 (may slip to backlog)

**Comment by moidx** [comment]
Discussed during triage meeting and decided to close as not planned.
