### ISSUE TITLE
[rv_dm,rtl] Fix acknowledgment of reset in `dmstatus.allhavereset`/`dmstatus.anyhavereset`

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#15123]
https://github.com/pulp-platform/riscv-dbg/issues/118:
> Currently the debug module seems to assume any assertion of `ndmreset_o` will instantly cause a reset. The `dmstatus.allhavereset`/`dmstatus.anyhavereset` bits are set purely on `ndmreset_o` being asserted rather than any acknowledgement a reset has occurred.

This is incorrect behavior and should be fixed, but it is currently not urgent for us, because the [`rstmgr` resets the system reset domain](https://docs.opentitan.org/hw/ip/rstmgr/doc/index.html#system-reset-tree) unconditionally whenever `ndmreset_req` is asserted (a few cycles after asserting this signal).

> estimate 12

**Comment by andreaskurth** [comment]
Triaged for `rv_dm`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP3 because there are only a few clock cycles (between the assertion of `ndmreset_o` and the instant `rstmgr` resets the system) during which those bits are not correct -- so I think this can be easily worked around in software without noticeable impact, whereas the RTL changes involved in proper reset acknowledgment are out of scope for this release IMHO.

**Comment by msfschaffner** [comment]
Depending on how we intend to implement the delayed debug unlock feature, this may be something that we have to fix as well.

CC @rswarbrick
