### ISSUE TITLE
[spi_device] race condition on TPM return-by-HW reg 

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#15134]
@a-will 

There are some return-by-HW registers on the SPI TPM. There is a chance that SW is updating one of those registers while SPI host is reading it at the same time. @eunchan CDC is properly handled in the design. But SPI host may get either the updated value or the old one. Does the SW have a protocol to avoid this case, or it's OK that SPI host reads either these 2 values in this case, since the next read will get the updated value?

cc: @eunchan @jeoongp @tjaychen

**Comment by tjaychen** [comment]
@a-pronin.

**Comment by tjaychen** [comment]
@weicaiyang, @jeoongp, @eunchan i'll probably need your help to remember, but do you know if the spec says anything about update latency? I think usually something like that is mentioned on how long the hardware has to update the value, or there is some kind of busy polling like with flash.

If neither exist and the updates / read both need to be instant, then this might need to look a lot more like the BUSY bit in flash mode.

**Comment by a-will** [comment]
I'd have to look at the function of these return-by-HW registers, but vaguely, I suspect if SW must get involved, it should disable the immediate return and force wait states. When I get a moment, I'll take a look at the TPM spec and compare against what we have. (Let me know if this needs higher priority, though.)

**Comment by tjaychen** [comment]
ah i was actually hoping either @a-pronin knew off the top of his head, or @eunchan / @weicaiyang / @jeoongp have already looked over the spec and knew the answer already.

**Comment by jeoongp** [comment]
In #13859 and #13586, we concluded there was no timing relation between SW write and CSB. So it's working like a sampling transaction as @weicaiyang mentioned "SPI host reads either these 2 values in this case, since the next read will get the updated value." But, we did not confirm it by checking a TPM spec. @a-will, if this assumption is different from the TPM spec, please let me know.

This topic is also related to https://github.com/lowRISC/opentitan/issues/14940.

**Comment by weicaiyang** [comment]
> I'd have to look at the function of these return-by-HW registers, but vaguely, I suspect if SW must get involved, it should disable the immediate return and force wait states. When I get a moment, I'll take a look at the TPM spec and compare against what we have. (Let me know if this needs higher priority, though.)

`disable the immediate return` could cause some other problems
1. another race condition - SPI is reading return-by-HW registers while this is happening
2. some return-by-HW registers is required to return with only 1 wait state.

**Comment by tjaychen** [comment]
@weicaiyang / @jeoongp since @a-will isn't really an expert on tpm, i think maybe we can look into the spec ourselves also and confirm with @a-pronin

**Comment by weicaiyang** [comment]
> @weicaiyang / @jeoongp since @a-will isn't really an expert on tpm, i think maybe we can look into the spec ourselves also and confirm with @a-pronin

sounds good. Will read the spec again.

**Comment by tjaychen** [comment]
> > @weicaiyang / @jeoongp since @a-will isn't really an expert on tpm, i think maybe we can look into the spec ourselves also and confirm with @a-pronin
> 
> sounds good. Will read the spec again.

yeah i'll help have a peek later also.

**Comment by weicaiyang** [comment]
> yeah i'll help have a peek later also.

Thanks Tim

**Comment by jeoongp** [comment]
@tjaychen @weicaiyang no problem. 
As you know, I am also not familiar with the TPM spec and SPI flash spec.. 
So, I think it's better for me to learn the timing relation required for busy bit in SPI flash (#14940). Once I understand it, I can also find similar contents from SPI TPM spec.  
If you don't mind, can you let me know where we can find the timing relation between SW write for busy-bit and SPI address phase for SPI_FLASH?

**Comment by tjaychen** [comment]
i think for that one we need to dig into the actual tpm spec a bit to see if they mention anything. 
I don't know off the top of my head at least. 

The main things I think we want to look for, is whether there is any protocol provisioning for "how long" after a reg update the host will issue a read.  The spec might give some minimum time, it might not.

You can also feel free to poke Andrey, i've cc'd you all on the email.  He's the real SPI-TPM expert.

**Comment by a-pronin** [comment]
There is no limitation on how quickly after a write to a register the host can issue a read. But there's little hw can do with it. The register contents after a write are not necessarily "<pre-write-value> OR <written-bit>", so hardware can't auto-set it on write. It's up to software to react to writes and set a new value.

Two notes:
1) The host is responsible for polling the register until it sees the state it needs after a write (e.g. write ready bit to STS then poll until you actually see ready there).
2) GSC firmware has additional tricks around this. E.g. GSC-specific SPI protocol includes a "ready" pulse on one of the gpio lines after handling a register access transaction, and the host is expected to wait for it (with a timeout of 750ms) before sending the next register access header. GSC firmware sometimes temporarily sets the register to 0 (not completely adhering to the spec) for extra resilience even if it can't back to updating it in the next 750ms. 

Bottomline: yes, the only thing that is expected from the hw is that if it sees the transaction while a new hw-backed TPM register value is being set by the s/w it either returns the old value or the new one, but never some combination of the two.

**Comment by jeoongp** [comment]
Thanks @a-pronin! 
TPM does not have a spec on Erase/Write In Progress (BUSY) in the same way as SPI_FLASH, does it?

**Comment by a-pronin** [comment]
Well, there is a spec that addresses how to know when TPM is ready to handle a command and when TPM has the response ready. But it's 2 levels up in the protocol stack, it is determined by reading these "registers" (hw-backed or not). 

There's also flow control for delaying the payload part of reads/writes from/to the "registers" until TPM is ready to handle them. The whole reason for having these hw-backed registers is that for some registers flow control ae allowed to delay reads for 1 cycle only during the flow control phase - and it can't be guaranteed in s/w. 

The TPM spec doesn't require that these regs are implemented in h/w. It generally doesn't prescribe implementation, just the behavior. But it does require responding after at max 1 delay cycle.

So, in this case to guarantee returning register contents on read within 1 cycle, HW should just return the current value. In addition it's important to make sure that the update to the register from the SW side is atomic. So, HW always returns either pre-update ot post-update value, never some mix of the two.

HW can't guarantee anything else - it just doesn't have enough info aboutt the state of the SW stack until SW updates the current contents of the hw-backed register(s) to reflect the changed state after a write to some "register".

**Comment by weicaiyang** [comment]
> Bottomline: yes, the only thing that is expected from the hw is that if it sees the transaction while a new hw-backed TPM register value is being set by the s/w it either returns the old value or the new one, but never some combination of the two.

Thanks @a-pronin. It makes sense. Will model the scoreboard as you describe here, as well as checking the mixing of 2 values shouldn't occur

**Comment by weicaiyang** [comment]
Closing this issue now. Thanks everyone
