### ISSUE TITLE
[spi_device] connect TPM CSB to the status CSR

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#15135]
@eunchan

as discussed, we want to update design to connect TPM CSB to the status CSR, so that SW can read it.

cc: @jeoongp

**Comment by a-will** [comment]
> as discussed, we want to update design to connect TPM CSB to the status CSR, so that SW can read it.

What was discussed? What is our driving use case for it? (Mostly, I'm asking so that we document it, since I suspect a single sentence is plenty of explanation. However, an offline conversation isn't inclusive.)

**Comment by weicaiyang** [comment]
solved via #15153
