### ISSUE TITLE
[spi_device] TPM HASH_START offset

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#15133]
@a-will 
As discussed with @eunchan, we found a typo on the latest TPM [spec](https://trustedcomputinggroup.org/wp-content/uploads/PC-Client-Specific-Platform-TPM-Profile-for-TPM-2p0-v1p05p_r14_pub.pdf).

2 offsets are used for TPM HASH_START in the spec. Do you know which the correct one is, 0x20 or 0x28?
![Screen Shot 2022-09-26 at 3 05 12 PM](https://user-images.githubusercontent.com/49293026/192389177-6c18d034-320d-45cd-bbba-2fdcd9947b94.png)
![Screen Shot 2022-09-26 at 3 05 47 PM](https://user-images.githubusercontent.com/49293026/192389178-be8e63fc-ba26-4022-b92a-7a766486842b.png)

cc: @jeoongp

**Comment by a-will** [comment]
For what it's worth, that one blurb is the only place where I see an offset ending in 0x20 for TPM_HASH_START. Everywhere else I've seen an offset, it's 0x28.

However, I'm not an expert on TPMs. We might want to find one.

Aside: The "before returning the contents of the register" part doesn't seem to apply to TPM_HASH_START, as it always returns 0xFF on reads. However, there are some PCRs that need to be reset, and I think the spec insists we not hold off data for hashing if it takes us a long time to perform that reset--That's why they point out that it can be done while performing completion of TPM_HASH_END.

**Comment by tjaychen** [comment]
@a-pronin.

**Comment by a-pronin** [comment]
disclaimer: we don't use HASH_START/_DATA/_END, so never looked at this part of the spec before.

if I were to judge: yes, as @weicaiyang and @a-will say above, it appears to be a bug in the spec (and it is already there in [rev 0.43](https://trustedcomputinggroup.org/wp-content/uploads/TCG_PC_Client_Platform_TPM_Profile_PTP_2.0_r43.pdf) from 2015). and it's not covered in the curent errata.
 
HASH_START is indeed 0x28 in all other tables. it's unclear why it is included as 0x20 in the list of registers with 1-wait-state-max restriction, but even more so why is it included in this list at all. HASH_START (as well as HASH_END, which is at 0x20) never needs to be read in practice, only written; and if read, always returns 0xFFs. so, a 1-wait-state restriction is not important for it.

there are multiple options of handling it: (a) not providing a hw-backed register for it, (b) providing a hw-backed register for 0x20, (c) same but for 0x28, (d) providing hw-regs for both 0x20 and 0x28. all should be ok in practice as of this version of the spec. (d) is the safest from the potential compliance point of view.

**Comment by weicaiyang** [comment]
@a-pronin These approaches sound reasonable to me.

@eunchan which option will you pick?

**Comment by tjaychen** [comment]
if we feel like all will be okay in practice, i would say let's just stick with 0x28. It seems like there is a 99% chance the singular 0x20 is a typo, so let's stick with that. Even if we are wrong, it doesn't appear it will really hurt.  When the spec is eventually clear and corrected, then we can move to whatever it wants.

**Comment by eunchan** [comment]
Current SPI TPM design has two issues:

1. TPM_HASH_START address is configured to *0x20*. Changing it is easy.
2. TPM_HASH_START, based on TPM spec, exists in Locality 4 only. In other localities, the address is reserved. So, HW may return 0xFF for locality 4 and upload if the request goes to other locality OR HW returns 0x00 for reserved OR HW always return 0xFF. I think second resolution is easiest among three.

**Comment by eunchan** [comment]
Ah, one thing to add is. `HASH_START` address is from 0x28 to **0x2F**. So, the reg occupies two DWORDs. I think this is also typo in the spec. @a-pronin

**Comment by a-pronin** [comment]
I asked the 0x20 vs 0x28 question in TCG WGs. if the response comes soon, we can act based on it.

**Comment by weicaiyang** [comment]
> I asked the 0x20 vs 0x28 question in TCG WGs. if the response comes soon, we can act based on it.

@a-pronin just want to follow up this issue. Have you gotten a response from the WGs?

**Comment by a-pronin** [comment]
From their response:
1) "HASH_START register is indeed offset 28, thank you for catching that."
2) "We are investigating whether the HASH_START needs to be removed from this list [the list in section 7.4.5] or a better reason defined for inclusion."

**Comment by weicaiyang** [comment]
> From their response:
> 
> 1. "HASH_START register is indeed offset 28, thank you for catching that."
> 2. "We are investigating whether the HASH_START needs to be removed from this list [the list in section 7.4.5] or a better reason defined for inclusion."

Thanks @a-pronin.

@eunchan Perhaps we can merge https://github.com/lowRISC/opentitan/pull/15175 now

**Comment by weicaiyang** [comment]
fixed via https://github.com/lowRISC/opentitan/pull/15175
