### ISSUE TITLE
[topgen] Improved RndCnst Mechanism

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#15144]
Topgen currently generates random netlist constants like LFSR seeds and OTP scrambling keys from a fixed seed and with random.py, which [uses Mersenne Twister underneath](https://docs.python.org/3/library/random.html).

It has thus been agreed to replace [random.py](https://docs.python.org/3/library/random.html) with a custom class supporting the loading of an entropy buffer file (e.g. generated from an HSM) and providing that entropy to consuming function calls. A full replacement including all member functions is not needed. What is absolutely required:
- [x] Constructor or member functions for loading the entropy buffer file.
- [x] getrandbits(k) member function to return a non-negative Python integer with the next k bits from the entropy buffer file.
- [x] shuffle(x) member function to shuffle the sequence x in place using the next bits from the entropy buffer file.
- [x] Bookkeeping functions to error out if no entropy buffer file has been loaded or if the entropy buffer file doesn’t contain enough bits to serve the current request.

For the open source domain, we further need:
- [x] An entropy buffer file generator script that generates the entropy file using random.py.

For further references, refer to the [one pager](https://docs.google.com/document/d/1USSnBKjmWlNvXKloQmhFJaSrmnSSeLKh2KDJBSMVcM4/edit?resourcekey=0-AqQ0qcdICL2_yRxfJ4fzTQ#) and the [meeting notes](https://docs.google.com/document/d/1HpMp1JS6YK0InjBfNN2c5pgwWz0aN_CIb1ItLdV8iik/edit#).

**Comment by vogelpi** [comment]
FYI @msfschaffner @tjaychen @moidx @johannheyszl

**Comment by vrozic** [comment]
Thanks @vogelpi for opening this issue.
I am currently working on the first version of this class.

**Comment by vogelpi** [comment]
> Not to bike-shed horribly, but are we fully committed to the name RndCnst (as opposed to RandCnst)? "Rnd" here can be an abbreviation for "Round" (as in round function or crypto round) or "Random", whereas "Rand" is unambiguous to me.
> 
> This could just be a "me" thing too, so if "Rnd" is fully obvious to everyone else then carry on.

Thanks for your input @cdgori . I think `RandCnst` would indeed be better than `RndCnst` for the same reason. However, there are now ~750 occurrences in the code base. Most of them are in auto-generated files but there are still many handwritten files affected, in particular module instantiations and DV code. I fear it's to late for changing this entirely.

**Comment by vogelpi** [comment]
@vrozic , can you please link the PR's you're working on related to this? This would give other the opportunity to have a look, too.

**Comment by vrozic** [comment]
This PR https://github.com/lowRISC/opentitan/issues/15144 adds a strong randomness class containing `getrandbits()`, `shuffle()` and a bookkeeping function `isempy()`. It also contains the script for generating the entropy file.

**Comment by cdgori** [comment]
> > Not to bike-shed horribly, but are we fully committed to the name RndCnst (as opposed to RandCnst)? "Rnd" here can be an abbreviation for "Round" (as in round function or crypto round) or "Random", whereas "Rand" is unambiguous to me.
> > This could just be a "me" thing too, so if "Rnd" is fully obvious to everyone else then carry on.
> 
> Thanks for your input @cdgori . I think `RandCnst` would indeed be better than `RndCnst` for the same reason. However, there are now ~750 occurrences in the code base. Most of them are in auto-generated files but there are still many handwritten files affected, in particular module instantiations and DV code. I fear it's to late for changing this entirely.

No problem then, it's not a huge issue for me.  If the fix was cheap I would have pushed for it.

**Comment by msfschaffner** [comment]
> > Not to bike-shed horribly, but are we fully committed to the name RndCnst (as opposed to RandCnst)? "Rnd" here can be an abbreviation for "Round" (as in round function or crypto round) or "Random", whereas "Rand" is unambiguous to me.
> > This could just be a "me" thing too, so if "Rnd" is fully obvious to everyone else then carry on.
> 
> Thanks for your input @cdgori . I think `RandCnst` would indeed be better than `RndCnst` for the same reason. However, there are now ~750 occurrences in the code base. Most of them are in auto-generated files but there are still many handwritten files affected, in particular module instantiations and DV code. I fear it's to late for changing this entirely.

Yeah I agree with @vogelpi, this would cause quite a bit of churn (and several IPs using this are already at D3).

**Comment by jadephilipoom** [comment]
> This PR #15178 adds a strong randomness class containing `getrandbits()`, `shuffle()` and a bookkeeping function `isempy()`. It also contains the script for generating the entropy file.

Is this issue safe to close now? It seems like #15178 has everything we needed.

**Comment by msfschaffner** [comment]
We still need to integrate the strong random class into the topgen, lifecycle and OTP scripts, but I think we can probably defer that to M3. WDYT, @tjaychen @moidx?

**Comment by tjaychen** [comment]
yeah that sounds good to me.
There's no immediate need for the strong randoms ...yet.

**Comment by vrozic** [comment]
#15401 integrates strong_random class into topgen.
The remaining tasks are to add strong_random calls to `gen-otp-img.py`, `gen-otp-mmap.py` and `LcStEnc.py`.

We need to come up with a strategy for this. 
Currently, each of these scripts contains a call to `random.seed( seed xor diversifier)`, where `seed` is the same for all three scripts and `diversifier` is unique for each script. This would be a good strategy if a secure PRNG was used instead of `random.py`.

I'm not sure what would be a good approach to change this. Should we use `strong_random` calls with three separate entropy buffer files?

**Comment by vogelpi** [comment]
Thanks @vrozic for working on this and updating the issue. I've brought this up with @moidx recently. We should discuss the remaining tasks either here or in a separate meeting call maybe sometime next week. @moidx what do you prefer?

**Comment by johngt** [comment]
@vogelpi / @vrozic - could you reference the latest efforts on this here and comment if this issue is redundant?

**Comment by vrozic** [comment]
Referencing recent changes made towards integrating strong_random class

- PR #18346, replaces all calls to `random.py` functions with `strong_random.py` functions in:

  - The life-cycle scripts (`gen-lc-lstate-enc.py`, `LCStEnc.py`)
  - OTP memory map infrastructure (`gen-otp-mmap.py`,`OtpMemMap.py`)
  - OTP image scripts (`gen-otp-img.py`, `OtpMemImg.py`)
 
-`strong_random.py` was modified in #18364 and #18431 to include functions:
  -`choice(X)` - to choose a random element from list X
  -`unsecure_generate_from_seed()` - to generate an entropy buffer directly from the seed. This was needed to avoid creating and deleting unnecessary entropy buffer files.

-`topgen.py` was modified in #18440 to use `strong_random.unsecure_generate_from_seed()` instead of `entropy_buffer_generator.py` module. This makes it consistent with the other scripts and avoids generating unnecessary files.

-PR #18412 modifies `hw\Makefile` to allow generation of netlist constants from an entropy file.

**Comment by vrozic** [comment]
As per [discussion](https://github.com/lowRISC/opentitan/pull/18412#issuecomment-1539074777) there are several more things to address in this issue:

- for OTP images that are generated by Bazel, the otp_image Bazel rule needs to be able to be made aware of the entropy buffer file paths
- for OTP images that are generated by this python script call in `chip_sim_cfg.hjson`, this script needs to be made aware of the entropy buffer file paths
- we need to generate different entropy buffer files based on the dvsim build / run seeds in the nightlies
- the rom scrambling script needs to be aware of the new netlist consts used to generate the correct scrambled ROM VMEM file

**Comment by moidx** [comment]
Moving to M2.5.2 to allow time to complete the tasks outlined by @vrozic.

**Comment by vogelpi** [comment]
Regarding @vrozic's question [here](https://github.com/lowRISC/opentitan/pull/18412#issuecomment-1540462945):
> I have one question regarding this point
>
>    3. we need to generate different entropy buffer files based on the dvsim build / run seeds in the nightlies to feed the above (so we can continue to run sims with different netlist consts / random OTP image values) both via a dvsim pre-run command (like is done for some of the OTP images) and via a bazel rule so that the Bazel-generated OTP images will have these files as a dep
>
> Do we want to use entropy buffers for the nightlies? My understanding was that the flow with entropy buffers will be used only once before the tapeout, and that the regular nightly regressions will continue to use unsecure_generate_from_seed()
Perhaps this is a question for @msfschaffner and @vogelpi

I think I agree with @vrozic here. AFAIK, we need to be able to also run dvsim with the random constants generated with the flow using buffers - whether the buffers are generated from a seed or from another source. My understanding is that this is already the case. Or this there something more needed to run simulation with the constants needed for synthesis @msfschaffner , @timothytrippel ?

**Comment by timothytrippel** [comment]
Yeah agreed wtih @vogelpi, I think if we structure it such that we always use the buffer files, even for the nightlies run with dvsim, but the buffer files can be generated from seeds, and bazel is made aware of the buffer files, then we should be good. Let me see if I can do some digging here to come up with a concrete plan how to finalize the dvsim/bazel integration bits and we can go from there if that sounds good?

**Comment by msfschaffner** [comment]
> Yeah agreed wtih @vogelpi, I think if we structure it such that we always use the buffer files, even for the nightlies run with dvsim, but the buffer files can be generated from seeds, and bazel is made aware of the buffer files, then we should be good. Let me see if I can do some digging here to come up with a concrete plan how to finalize the dvsim/bazel integration bits and we can go from there if that sounds good?

Sounds good.

I agree that we should eventually just use buffer files so that the flow (through Bazel) is tested.
In the meantime, it is totally ok to keep on using the transparent mechanism that uses `unsecure_generate_from_seed`.
This is not blocking for the shuttle since we do not plan to use the buffer file flow for that.

**Comment by vrozic** [comment]
Status update:
#18723 enables running toplevel tests when entropy_buffer was used
This is done using Environment variable USE_BUFFER, rather than input arguments for the entropy file paths.
So the flow is as follows:

1. Create entropy files in the correct locations
2. `export USE_BUFFER=1`
3. `cd hw/ && make all`
4. Run tests using `dvsim`

At this point I am not exactly sure what we would be testing by adding the entropy flow to the nightlies since there is no fundamental difference between currently used `unsecure_generate_from_seed()` and creating a buffer from seed + loading entropy from a file.

**Comment by timothytrippel** [comment]
The are two reasons for testing in nightlies:

1. there are currently two ways dvsim.py triggers the generation of OTP images for top-level tests:
    a. by invoking the `gen-otp-image.py` script directly
    b. by invoking bazel to build the OTP image (which under the hood, invokes `gen-otp-image.py` in the Bazel sandbox)
The mechanism / example you provide in #18723 will work when dvsim.py uses method (a), as the buffer files will be visible to the `gen-otp-image.py` script when it is not run in bazel sandbox as the tree will essentially be dirtied. It will not work with method (b), as these buffer files do not get copied to the Bazel sandbox, as Bazel will not be aware of them.

2. Ideally, only method (b) would be used, i.e., only Bazel would be used to gen these OTP images, but until then, both flows should be tested to ensure nothing breaks.

**Comment by vrozic** [comment]
Thanks @timothytrippel for clarifying this. I didn't know that dvsim.py can invoke bazel.

**Comment by vrozic** [comment]
Status update for visibility:

1. #18795 makes the entropy buffers the default source of randomness. My understanding is that once this change is in, it should close this issue
2. A concern was raised in the discussion https://github.com/lowRISC/opentitan/pull/18795#pullrequestreview-1463396080 , that this changes the way Nuvoton replaces the seeds for the tapeout. It needs to be decided whether we want to absorb this change in M2.5.2/
3. Optional non-critical update is provided in #18514 to test statistical quality of the numbers provided in the entropy buffer files.

**Comment by msfschaffner** [comment]
Thanks for summarizing this @vrozic - we'll discuss this in the next tapeout sync meeting.

**Comment by johngt** [comment]
@msfschaffner / @moidx / @timothytrippel - based on discussion yesterday - suggestion was to defer this work. Is my understanding correct? If so could we update the milestone and also tentatively mark which other milestone it might go into.

**Comment by timothytrippel** [comment]
yes that is correct. Once I have a chance to update PR #18795, it should close this, but we will not be doing that for the shuttle (after yesterdays discussion). I think this would make sense for M2.5.5 milestone. I updated the milestone label.
Feel free to adjust further @msfschaffner.

**Comment by msfschaffner** [comment]
Yes we can move that further down the road, but I am not quite sure in what milestone it should land (there might be some implications on integrated).

So I'll put it into the M2.5 Backlog for now.

**Comment by vrozic** [comment]
> (there might be some implications on integrated).

I'd like to put forward an alternative solution for integrated.
If we were to use a cryptographically strong PRNG, it would fit nicely with all the existing flows without the need to rely on the entropy buffers. So, it's not likely to cause any problems for integrated moving forward.
I've tested this idea in #18768 and it seems to work.

I can add more detail in the Slack discussion.

**Comment by vrozic** [comment]
An update from last week's security meeting;
I am developing a CTR-DRBG based pseudo-random number generator. The working version of the code is [here](https://github.com/vrozic/opentitan/tree/drg3-ctr).
One of the issues brought up at the meeting is switching from 128b seeds to 256b. This may be necessary to comply with CTR-DRBG specifications.
I plan to prepare the first version of  the RFC document this week.

**Comment by msfschaffner** [comment]
@vrozic @vogelpi Anything to update here? Can the issue be closed by now?

**Comment by vogelpi** [comment]
Thanks for the ping @msfschaffner . IIRC, everything has been implemented and we can close this. @vrozic can you confirm please?

**Comment by vrozic** [comment]
Yes, this issue is related to an outdated strong_random class which has since been replaced with secure_prng class.
This issue can be safely closed.
