### ISSUE TITLE
[fusesoc] installation challenge

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#1514]
Some user provides feedback about the installation challenge for Fusesoc (pip3 install --user -r python-requirements.txt), as it requires root permission on the machine. Is there a pre-build version that users can install without root permission?

**Comment by imphil** [comment]
If you run pip with `--user`, it installs into the home directory and does not need root permissions.

**Comment by cindychip** [comment]
I see, thanks Philipp. Let me confirm with the user and see if he still has the issue.

**Comment by snpsverif** [comment]
I'm getting 

which python
/global/freeware/Linux/2.6/python-3.6.3/bin/python

% pip3 install --user -r python-requirements.txt
Collecting git+https://github.com/olofk/ipyxact.git@master (from -r python-requirements.txt (line 26))
  Cloning https://github.com/olofk/ipyxact.git (to revision master) to /tmp/pip-req-build-4y6f049d
warning: templates not found $HOME/share/git-core/templates
fatal: Unable to find remote helper for 'https'
Command "git clone -q https://github.com/olofk/ipyxact.git /tmp/pip-req-build-4y6f049d" failed with error code 128 in None
You are using pip version 19.0.2, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by cindychip** [comment]
Thank you for the detailed information.
Seems like some ppl have the similar issue in stackoverflow: https://stackoverflow.com/questions/8329485/unable-to-find-remote-helper-for-https-during-git-clone
Wonder if the solution posted here is helpful.

**Comment by imphil** [comment]
The problem you're experiencing has nothing to do with fusesoc, something is broken in your git installation. Git is used to download some Python dependencies.

Please ensure that `git clone https://github.com/olofk/ipyxact.git` works on your machine works first before returning to the `pip3` step.

What distribution and `git` version are you using?

In general, please note that our scripts may work for RHEL6, but that this is a non-supported configuration. Using RHEL7+, Ubuntu 16.04 or 18.04, together with distribution-provided versions of tools (git and Python 3) should work. For self-compiled versions of these tools you're most likely run into various issues which typically only your IT department can sort out.

**Comment by snpsverif** [comment]
Very helpful instructions. I'm using git version 2.16.2 on RHEL6 and Python 3.6.3.
I have python-requirements.txt installed successfully now.
One thing was not very clear in the instruction is that I need to set my search path to $HOME/.local/bin to pick up those newly installed utilities.

Successfully built pyftdi ipyxact edalize
Installing collected packages: attrs, zipp, importlib-metadata, pluggy, wcwidth, py, more-itertools, pytest, Jinja2, edalize, zipfile2, okonomiyaki, simplesat, ipyxact, fusesoc, smmap2, gitdb2, gitpython, tornado, livereload, meson, mistletoe, pyusb, pyserial, pyftdi, pytest-timeout, yapf
Successfully installed Jinja2-2.10.3 attrs-19.3.0 edalize-0.1.7 fusesoc-1.9.3 gitdb2-3.0.0 gitpython-3.0.7 importlib-metadata-1.5.0 ipyxact-0.2.4 livereload-2.6.1 meson-0.52.1 mistletoe-0.7.2 more-itertools-8.2.0 okonomiyaki-1.2.0 pluggy-0.13.1 py-1.8.1 pyftdi-0.43.0 pyserial-3.4 pytest-5.3.5 pytest-timeout-1.3.4 pyusb-1.0.2 simplesat-0.8.2 smmap2-2.0.5 tornado-6.0.3 wcwidth-0.1.8 yapf-0.29.0 zipfile2-0.0.12 zipp-2.2.0
You are using pip version 19.0.2, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by imphil** [comment]
Good you figured it out. The PATH issue you ran into is documented at https://docs.opentitan.org/doc/ug/install_instructions/. Please let us know if there's something we can do to improve this piece of documentation.

**Comment by snpsverif** [comment]
I spoke too soon. I could run most of the blocks but ran into lots of problems due to required  toolchains when trying to run full-chip top_earlgrey. Is there any document or suggestion on how to install the needed toolchains. It appears to need ninja, srec_cat, libftdi1 … and I haven't been able to get it through.
