### ISSUE TITLE
[flash_ctrl] host read hang with spurious grant

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#15155]
use [REP_PR](https://github.com/lowRISC/opentitan/pull/15156)
cmd:
./util/dvsim/dvsim.py ./hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson -i flash_ctrl_phy_host_grant_err -r 1 -s 1 --waves
Test sends 2 host read (with mixed ctrl txns), and assert host_gnt_err by forcing
"tb.dut.u_eflash.gen_flash_cores[0].u_core.muxed_part" @tb.dut.u_eflash.gen_flash_cores[0].u_core.host_gnt;
or
"tb.dut.u_eflash.gen_flash_cores[0].u_core.ctrl_fsm_idle" @tb.dut.u_eflash.gen_flash_cores[0].u_core.host_gnt_q;

@4168.2ns, 2nd req out from
tb.dut.u_tl_adapter_eflash.req_o and granted but doesn't get read data back
and test hangs.

**Comment by jdonjdon** [comment]
![image](https://user-images.githubusercontent.com/99843637/192592140-61ab2eab-9778-4827-bd28-a48ffd591abe.png)

**Comment by tjaychen** [comment]
let me look at this again, i actually don't completely remember what host grant error even is..

**Comment by tjaychen** [comment]
@jdonjdon i just pushed an extra commit to the PR, can you have a look?
The definition is changed slightly, but I hope this helps with the hanging issue.
