### ISSUE TITLE
Fix OTP splicing with updatemem

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#15162]
I think OTP splicing might not be working properly. I changed the value of `CREATOR_SW_CFG_ROM_EXEC_EN` and modified the SRAM execution test to (1) use an OTP-spliced bitstream and (2) print the OTP value at the expected address. Bazel definitely ran the commands to splice the OTP image in, but when the GDB script ran, it printed the default value for `CREATOR_SW_CFG_ROM_EXEC_EN` rather than the value I chose.

I believe these local changes are sufficient to reproduce the result when running `./bazelisk.sh test --define bitstream=gcp_splice //sw/device/examples/sram_program:sram_program_fpga_cw310_test`. (The SRAM program test was just handy, but it should be irrelevant because GDB is printing the value before loading the SRAM program into memory.)

```diff
diff --git a/rules/otp.bzl b/rules/otp.bzl
index cfc36daca..0a16f4413 100644
--- a/rules/otp.bzl
+++ b/rules/otp.bzl
@@ -38,7 +38,8 @@ def _otp_json_impl(ctx):
                 "CREATOR_SW_CFG_RNG_EN": "0x739",
                 # ROM execution is enabled if this item is set to a non-zero
                 # value.
-                "CREATOR_SW_CFG_ROM_EXEC_EN": "0xffffffff",
+                #"CREATOR_SW_CFG_ROM_EXEC_EN": "0xffffffff",
+                "CREATOR_SW_CFG_ROM_EXEC_EN": "0x11235813",
                 # Value to write to the cpuctrl CSR in `rom_init()`.
                 # See:
                 # https://ibex-core.readthedocs.io/en/latest/03_reference/cs_registers.html#cpu-control-register-cpuctrl
diff --git a/sw/device/examples/sram_program/BUILD b/sw/device/examples/sram_program/BUILD
index bbe7f68a1..eb742fb03 100644
--- a/sw/device/examples/sram_program/BUILD
+++ b/sw/device/examples/sram_program/BUILD
@@ -106,6 +106,9 @@ opentitan_gdb_fpga_cw310_test(
         monitor reg pmpcfg0 0x9f9f9f9f
         monitor reg pmpaddr0 0x7fffffff

+        echo :::: Value of CREATOR_SW_CFG_ROM_EXEC_EN.\\n
+        monitor mdw 0x40131108
+
         echo :::: Load the SRAM program onto the device and check integrity.\\n
         file sram_program.elf
         load sram_program.elf
@@ -125,7 +128,7 @@ opentitan_gdb_fpga_cw310_test(
         ":sram_program_fpga_cw310.elf": "sram_program.elf",
         "//sw/device/silicon_creator/rom:rom_fpga_cw310.elf": "rom.elf",
     },
-    rom_bitstream = "//hw/bitstream:rom",
+    rom_bitstream = "//hw/bitstream:rom_otp_dev",
     rom_kind = "Rom",
     tags = [
```

Let's peek at the MMI files that we generated with [vivado_hook_write_bitstream_pre.tcl](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/util/vivado_hook_write_bitstream_pre.tcl;l=91;drc=099463e2af6fb9480bd99830851f1d37ff05833c).

I noticed a few things:

1. The DataWidth values in `rom.mmi` do not overlap, but the ones in `otp.mmi` do overlap. I think this is forbidden per the [Xilinx `updatemem` manual](https://www.xilinx.com/content/dam/xilinx/support/documents/sw_manuals/xilinx2022_1/ug1580-updatemem.pdf):
    > There cannot be any gaps or overlaps in bit-lane numbering. All bit-lanes in an Address Block must be the same number of bits wide.

    I wonder whether this has something to do with the TCL condition that adds 3 to the `slice_end` variable. [vivado_hook_write_bitstream_pre.tcl:66](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/util/vivado_hook_write_bitstream_pre.tcl;l=66;drc=099463e2af6fb9480bd99830851f1d37ff05833c)
1. The Placement values in `rom.mmi` are of the form "X{}Y{}" like the `updatemem` manual examples, but the values in `otp.mmi` are prefixed with `18_`.
    I have a suspicion that we're not trimming the right string from the left of the LOC property for OTP images. [vivado_hook_write_bitstream_pre.tcl:60](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/util/vivado_hook_write_bitstream_pre.tcl;l=60;drc=099463e2af6fb9480bd99830851f1d37ff05833c) 

### rom.mmi

```xml
<?xml version="1.0" encoding="UTF-8"?>
<MemInfo Version="1" Minor="0">
  <Processor Endianness="Little" InstPath="dummy">
  <AddressSpace Name="rom" Begin="0" End="81919">
      <BusBlock>
        <BitLane MemType="RAMB32" Placement="X6Y33">
          <DataWidth MSB="3" LSB="0"/>
          <AddressRange Begin="0" End="8191"/>
          <Parity ON="false" NumBits="0"/>
        </BitLane>
        <BitLane MemType="RAMB32" Placement="X5Y33">
          <DataWidth MSB="7" LSB="4"/>
          <AddressRange Begin="0" End="8191"/>
          <Parity ON="false" NumBits="0"/>
        </BitLane>
        <BitLane MemType="RAMB32" Placement="X5Y35">
          <DataWidth MSB="11" LSB="8"/>
          <AddressRange Begin="0" End="8191"/>
          <Parity ON="false" NumBits="0"/>
        </BitLane>
...
```

### otp.mmi

```xml
<?xml version="1.0" encoding="UTF-8"?>
<MemInfo Version="1" Minor="0">
  <Processor Endianness="Little" InstPath="dummy">
  <AddressSpace Name="rom" Begin="0" End="22527">
      <BusBlock>
        <BitLane MemType="RAMB32" Placement="18_X7Y112">
          <DataWidth MSB="3" LSB="0"/>
          <AddressRange Begin="0" End="1023"/>
          <Parity ON="false" NumBits="0"/>
        </BitLane>
        <BitLane MemType="RAMB32" Placement="18_X7Y120">
          <DataWidth MSB="4" LSB="1"/>
          <AddressRange Begin="0" End="1023"/>
          <Parity ON="false" NumBits="0"/>
        </BitLane>
        <BitLane MemType="RAMB32" Placement="18_X8Y123">
          <DataWidth MSB="5" LSB="2"/>
          <AddressRange Begin="0" End="1023"/>
          <Parity ON="false" NumBits="0"/>
        </BitLane>
```

**Comment by dmcardle** [comment]
I ran Vivado with a modified TCL script where I don't make modification to `slice_end`. At least superficially, rom.mmi looks unchanged, and otp.mmi doesn't appear to overlap anymore! (Still need to try the spliced bitstream on an FPGA.)

I opened the Vivado GUI and searched for cells of type BMEM.BRAM, and it's now very clear why the placement values have that strange prefix. For example, the OTP cell `mem_reg_9` has a LOC value of `RAMB18_X8Y126`, so of course trimming `RAMB36_` doesn't work quite right. I think I'll change the LOC trimming code to support both.

### rom.mmi

```xml
<?xml version="1.0" encoding="UTF-8"?>
<MemInfo Version="1" Minor="0">
  <Processor Endianness="Little" InstPath="dummy">
  <AddressSpace Name="rom" Begin="0" End="39935">
      <BusBlock>
        <BitLane MemType="RAMB32" Placement="X7Y35">
          <DataWidth MSB="3" LSB="0"/>
          <AddressRange Begin="0" End="8191"/>
          <Parity ON="false" NumBits="0"/>
        </BitLane>
        <BitLane MemType="RAMB32" Placement="X6Y37">
          <DataWidth MSB="7" LSB="4"/>
          <AddressRange Begin="0" End="8191"/>
          <Parity ON="false" NumBits="0"/>
        </BitLane>
        <BitLane MemType="RAMB32" Placement="X7Y39">
          <DataWidth MSB="11" LSB="8"/>
          <AddressRange Begin="0" End="8191"/>
          <Parity ON="false" NumBits="0"/>
        </BitLane>
```

### otp.mmi

```xml
<?xml version="1.0" encoding="UTF-8"?>
<MemInfo Version="1" Minor="0">
  <Processor Endianness="Little" InstPath="dummy">
  <AddressSpace Name="rom" Begin="0" End="2815">
      <BusBlock>
        <BitLane MemType="RAMB32" Placement="18_X8Y127">
          <DataWidth MSB="0" LSB="0"/>
          <AddressRange Begin="0" End="1023"/>
          <Parity ON="false" NumBits="0"/>
        </BitLane>
        <BitLane MemType="RAMB32" Placement="18_X7Y125">
          <DataWidth MSB="1" LSB="1"/>
          <AddressRange Begin="0" End="1023"/>
          <Parity ON="false" NumBits="0"/>
        </BitLane>
        <BitLane MemType="RAMB32" Placement="18_X7Y123">
          <DataWidth MSB="2" LSB="2"/>
          <AddressRange Begin="0" End="1023"/>
          <Parity ON="false" NumBits="0"/>
        </BitLane>
```

**Comment by dmcardle** [comment]
To summarize, I think the root of this issue is that the MMI file(s) we generate are probably incorrect, causing `updatemem` to do some unwanted edit to our bitstream file.

Ideally, I would just call [`write_mem_info`](https://docs.xilinx.com/r/2020.2-English/ug835-vivado-tcl-commands/write_mem_info) to generate an MMI file for the entire project. I've had no luck running the command in the Vivado GUI — it just says that the file could not be written. It's not a filesystem permission issue, and the `-verbose` flag didn't add any new messages. I tried `strace` which showed it was successfully opening the `mmi` file, then closing and deleting it.

I do wonder whether I was running `write_mem_info` in the appropriate environment. I opened the implemented design and went straight to the TCL console. I wonder whether it would be better if we actually ran it before writing the bitstream, at the step named `STEPS.WRITE_BITSTREAM.TCL.PRE`. (Aside: I noticed that our `vivado_hook_write_bitstream_pre.tcl` script is actually not running at this stage per [this comment](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/util/vivado_setup_hooks.tcl;l=17-20;drc=eb1eba3826e42d63563f799bedd9a47206563196).)

I have a few things to try:

* I'm currently running a build that will call manually invoke [`write_bitstream`](https://docs.xilinx.com/r/2020.2-English/ug835-vivado-tcl-commands/write_bitstream) with some new flags.
  * `-raw_bitfile` is supposed to generate an ASCII variant of the bitfile. I'm not holding my breath on this, though. I think it might just be a fixed-size header at the beginning of the file followed by a hexdump of the `.bit` file.
  * `-logic_location_file` says it generates a file containing bitstream positions of Block RAMs. This sounds promising — if all else fails, it might be worth trying to write our own `updatemem`.
* I'd like to try generating MMI files with `write_mem_info` in a newer version of Vivado, if possible.

**Comment by dmcardle** [comment]
One thing I don't quite understand is that the BRAMs for ROM appear to be "RAMB36", yet we write "RAMB32" into the MMI file. Our OTP BRAMs are "RAMB18", so it's not clear what memory type to claim in the MMI file. Some folks on a forum 5 years ago say that [updatemem does not support RAMB18](https://support.xilinx.com/s/question/0D52E00006hpgY4SAI/updatemem-for-ramb18?language=en_US), but it's not a conclusive answer from Xilinx. I briefly tried enabling RAMB18 support with the effectively undocumented [UPDATEMEM_ALLOW_RAMB18](https://support.xilinx.com/s/question/0D52E00006iHlJXSA0/updating-memories-containing-program-instructions-of-a-picoblaze-processor?language=en_US) environment variable but it didn't have the desired effect (sorry to be vague, I should have taken better notes.)

**Comment by a-will** [comment]
If you change the minor version of the file to 1, it looks like updatemem accepts the RAMB18:
```diff
<?xml version="1.0" encoding="UTF-8"?>
-<MemInfo Version="1" Minor="0">
+<MemInfo Version="1" Minor="1">
  <Processor Endianness="Little" InstPath="dummy">
```
