### ISSUE TITLE
[bazel,dv] support loading both flash slots and using different signing keys in DV

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#15209]
In order to support running some (P1) ROM E2E tests to DV, e.g., the [`rom_e2e_boot_policy_valid`](https://github.com/lowRISC/opentitan/issues/14474) test, we need some enhancements to our DV testbench infrastructure to support:

- [ ] loading different flash banks (i.e. slots); currently only flash bank 0 is loaded so only tests that run in slot A can be loaded
- [ ] support different signing keys (right now the DV test bench always assumes `test_key_0` is used, which does not work in DEV/PROD[_END] LC states

Note these tasks were split out of #13511.

**Comment by timothytrippel** [comment]
I think #14474  (a rom E2E test that we want to run in DV, see #14634) will need the second bullet point above in order to load both flash banks. Unless I am missing something?

**Comment by tjaychen** [comment]
ah thanks for clarifying.
