### ISSUE TITLE
[rv_core_ibex] Reintroduce assert that PC does not advance when Ibex is disabled

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/opentitan#15217]
An assert to add this was merged in this PR: https://github.com/lowRISC/opentitan/pull/15101
However, this caused multiple failures in the top level tests, which are tracked in this issue: https://github.com/lowRISC/opentitan/issues/15148
@engdoreis has created a PR to remove the assert temporarily with this PR: https://github.com/lowRISC/opentitan/pull/15218 (previously https://github.com/lowRISC/opentitan/pull/15216)
This issue is here to track that we need to reintroduce this assert when we figure out how to connect up the enable signal properly.

**Comment by GregAC** [comment]
The assertion doesn't match how the Ibex fetch enable behaves. We either need to adjust the Ibex behaviour or rewrite the assertion, see https://github.com/lowRISC/opentitan/issues/15217

**Comment by GregAC** [comment]
PR changing fetch enable behaviour and reintroducing a similar assertion is now available in the Ibex repository: https://github.com/lowRISC/ibex/pull/1844

In rv_core_ibex we need to add an assertion that the fetch enable is correctly connected up.
