### ISSUE TITLE
[i2c] acq_fifo has no level or full interrupt / done interrupt

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15226]
When i2c is in target mode, it currently does not have a "done" interrupt. 
It has a "ack_stop" interrupt, but that only applies when the host is doing a read, and does NOT send a nak->stop sequence (sends ack->start/stop instead). 

There is also no tx level interrupt, although there is a tx empty interrupt.

This means when the external host writes to the dut-target, the software actually has no idea when to actually retrieve the data.  There is no interrupt indicating "something" is there, and there is also no done interrupt.

When the external host reads the dut-target, the tx-empty interrupt will inform the software that more data is needed.  However, without a done interrupt, the host could choose to not read all the data and there would be no way for the device to actually know that.

**Comment by tjaychen** [comment]
@drewmacrae 
@a-will

**Comment by tjaychen** [comment]
there's actually no level interrupt either, do we think this is useful?
i guess it might be nice to support transactions > acq_fifo size right?

**Comment by tjaychen** [comment]
o so maybe it's relying on the overflow interrupt? i will need to double check. Let me confirm if that's the case and I will close.

**Comment by drewmacrae** [comment]
Ugh, I should have looked at the doc. There are status bits for stretching and for the acq fifo being full, but there aren't references to interrupts.

**Comment by tjaychen** [comment]
i dont know this for sure (need to read doc and code), but i'm assumign acq_overflow should do what you're thinking.
As in ...it represents "full" and us entering the stretch state. I'll let you know.

**Comment by drewmacrae** [comment]
I was wrong again (if the drawing of the state machine is correct, we can overflow the ACQ FIFO if we fill it with anything but the start of a transaction, I think @a-will may have mentioned or filed an issue on this but I'm very bad at searching github issues.) We can overflow the acq fifo and I've mentioned this in #16158.

**Comment by drewmacrae** [comment]
Instead of the acq_fifo_full interrupt, if the i2c_stretch_timeout were to work in both modes (the documentation was vague on this until recently though the RTL had it as host only) then it could be used to monitor for tx_fifo_empty and acq_fifo_full by setting to a short timeout. I've opened #16160 to track that possibility.
