### ISSUE TITLE
[test-triage] rom_e2e_shutdown_exception_c test runs over timelimit

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#15238]
### Hierarchy of regression failure

Chip Level

### Failure Description

Job chip_earlgrey_asic-sim-vcs_run_default killed due to: Exit reason: User job exceeded runlimit: User job timed out

### Steps to Reproduce

Commit hash :[67a41e3bc](https://github.com/lowrisc/opentitan/tree/67a41e3bc3ff025554a024cdb15fbf892c4752b3)
./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i rom_e2e_shutdown_exception_c --fixed-seed 4248791391 --build-seed 1603370106 -w fsdb -v m

**Comment by msfschaffner** [comment]
@cindychip did you have a chance to look at this one, or should we reassign this?

**Comment by johngt** [comment]
@engdoreis let's monitor this in the nightlies over the next three days and then close out if not an issue. If an issue let's ping the devs asap.

**Comment by timothytrippel** [comment]
This should be fixed in #16096. I tested it locally and it passed. But let's keep an eye on the dashboard today when it updates.

**Comment by engdoreis** [comment]
It passed in the latest regression, I'll keep watching and close this issue when it passes 3 times.

**Comment by engdoreis** [comment]
The test `rom_e2e_shutdown_exception_c` is failing again, but there's no log in the report. So I'm reopening this issue to track the investigation.

**Comment by engdoreis** [comment]
This issue was fixed by the PR #17198
