### ISSUE TITLE
[spi_device] read TPM HW reg with an unaligned address

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#15266]
@eunchan 

In this case, the address is 'hf05. Since TPM_RID is only 1 bytes, design should return 'hff.
Looks like the address latch point is half cycle earlier, so that it got 'hf04.
![Screen Shot 2022-10-04 at 1 41 46 PM](https://user-images.githubusercontent.com/49293026/193923306-21b56d0f-c677-4aa8-b425-2d03aba28dd8.png)

Waves and saved session:
/mnt/disks/filestores/opentitan-shared/users/weicai/scratch/fix/spi_device-sim-vcs/0.spi_device_tpm_read_hw_reg/latest

**Comment by eunchan** [comment]
`isck_fifoaddr` latches the signal a cycle earlier. Yep it is a bug. Thanks for finding it.

**Comment by weicaiyang** [comment]
fixed via #15269
