### ISSUE TITLE
[dv/pwrmgr] Disable additional escalation reset from tests expected to escalate

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#15262]
There are a number of sec_cm tests that trigger escalation, and some of them cause escalations on top of other sequences. For these other sequences it is best to prevent them from also triggering escalations,or we end up with inconsistent stimulus.

For example, pwrmgr_sec_cm_lc_ctrl_intersig_mubi triggers escalation while running pwrmgr_repeat_wakeup_reset_vseq.

**Comment by msfschaffner** [comment]
Since pwrmgr is already beyond V2, is this something we could potentially defer to V3?

**Comment by tjaychen** [comment]
i think pwrmgr hasn't closed v2/v2s yet because of the reset domain change.

**Comment by msfschaffner** [comment]
Ah yeah that's right - I was just going off the dashboard for this, where it currently says V2S.

**Comment by matutem** [comment]
We dealt with the tests that caused this problem, but I fail to remember how... sorry.
I will close this, and reopen or create a new one if this problem shows up again.
