### ISSUE TITLE
[test-triage] rom_e2e_static_critical test runs over timelimit

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#15276]
### Hierarchy of regression failure

Chip Level

### Failure Description

Job chip_earlgrey_asic-sim-vcs_run_default killed due to: Exit reason: User job exceeded runlimit: User job timed out 

### Steps to Reproduce

- Commit hash: [67a41e3bc](https://github.com/lowrisc/opentitan/tree/67a41e3bc3ff025554a024cdb15fbf892c4752b3)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i rom_e2e_static_critical --fixed-seed 2672947159 --build-seed 3413385032 --waves -v h

### Tests with similar or related failures

- [ ] rom_e2e_shutdown_exception_c #15238
- [ ] chip_sw_uart_rand_baudrate #15277

**Comment by engdoreis** [comment]
Closing this issue as the test has been passing for several days.
Tests | latest | 2022.10.10 | 2022.10.08/1 | 2022.10.08/2 | 2022.10.06 | 2022.10.05/1 | 2022.10.05/2 | 2022.10.03/1 | 2022.10.03/2 | ... | 2022.09.30 | 2022.09.29 | 2022.09.28 | 2022.09.27 | 2022.09.26/1 | 2022.09.26/2 | 2022.09.26 | 2022.09.24 | 2022.09.23 | Suite
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
rom_e2e_static_critical | 100.00 | 100.00 | 100.00 | 100.00 | 100.00 | 100.00 | 66.67 | 66.67 | 66.67 | ... | 100.00 | N/A | -- | -- | -- | -- | -- | -- | -- | rom_e2e_static_critical
