### ISSUE TITLE
[spi_device] design uploads TPM write when writing to an invalid locality

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#15270]
> If 1, TPM submodule returns the invalid data (0xFF) for the out of the max Locality request. If it is a write request, it discards the request.

It also triggers an interrupt.
According to the spec, we should drop this transaction since we use TPM FIFO mode and invalid_locality is set to 1.

Waves:
/mnt/disks/filestores/opentitan-shared/users/weicai/scratch/tpm_unalign/spi_device-sim-vcs/0.spi_device_tpm_write_hw_reg/latest

**Comment by eunchan** [comment]
Write case, always HW uploads. It is up to SW to drop the request.

**Comment by weicaiyang** [comment]
> Write case, always HW uploads. It is up to SW to drop the request.

SGTM, then let's update the spec to remove that statement.
