### ISSUE TITLE
[bazel] Add support for multiple bitstreams and metadata to the bitstream cache

### ISSUE THREAD

**Issue by milesdai** [lowRISC/opentitan#15284]
As we start building bitstreams for multiple platforms and creating multiple versions of bitstreams via splicing, we would like to store these bitstreams in the bitstream cache. This requires:
1. Creating a systematic naming scheme/adding metadata to the cache (e.g. a manifest file) to better identify different bitstream configurations (#13807)
2. Modify the bitstream caching code (`bitstream-workspace.py`) to understand and handle this new naming scheme
3. Invoking the existing bitstream uploading machinery in CI to upload these generated bitstreams to the cache.

**Comment by msfschaffner** [comment]
@a-will @timothytrippel @cfrantz I think there has been some progress on this in the meantime. can someone with more insight update this issue?

**Comment by a-will** [comment]
Done. We have a JSON manifest + schema now and support cw340, cw310, and hyper310
