### ISSUE TITLE
[test-triage] csr_tests_mode has a comment indicating it has 20 reseeds but it appears to run with 3

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#15305]
I'm looking into the incidence of a failure building opentitan-tool so I'm inspecting the reseed specifications in https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/dv/chip_sim_cfg.hjson;drc=5220e2275b3bae33225cc77dbc48b839ebd3ef29;l=233
```
    {
      // Append stub cpu mode to csr_tests_mode, run with 20 reseeds.
      name: csr_tests_mode
      en_run_modes: ["stub_cpu_mode"]
    }
```
seems to indicate a different number of reseeds in the code vs comments.

**Comment by sriyerg** [comment]
We used to run these tests with 20 reseeds. But then we decided thats too much, so we brought it down to 3 instead. Just need to update the comment.
