### ISSUE TITLE
[bazel] fix support for rust-analyzer

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#15300]
# Background

When #15193 was merged it broke our airgapped build environment (strangely, our blocking CI check did not catch this, though that is a separate issue). After further investigation, it was determined this was due to the fact that #15193 switched to the nightly rust toolchain. While using the nightly toolchain itself shouldn't break airgapped builds, making this change exposed a bug in the upstream `rules_rust` (the Bazel rust rules).

Specifically, the `load_arbitrary_tool` rule was using the wrong tool string to check its [`known_shas.bzl` dictionary](https://github.com/bazelbuild/rules_rust/blob/main/rust/known_shas.bzl). Therefore, it was never finding the SHA256 for the nightly rust toolchain tool tarballs, and therefore they were never being cached.

To temporarily fix this, I:
1. updated our forked `rules_rust` repo to use the current upstream tip of tree, which gave us a nice bazel fetch performance improvement since [this issue](https://github.com/bazelbuild/rules_rust/issues/1373) has also been addressed in upstream, and
2. [patched our forked repo to fix this bug](https://github.com/lowRISC/rules_rust/tree/upstream-with-sha-fix) (next step is to try to upstream this patch).
3. reimplemented #15193 and updated our `rules_rust` version in #15301.

# Problem
However, this only fixed the toolchain tool tarball caching issue. To support rust-analyzer, the `include_rustc_srcs` [parameter](http://bazelbuild.github.io/rules_rust/flatten.html#rust_register_toolchains-include_rustc_srcs) of the `rust_register_toolchains` repo rule needs to be set to `True`. Doing so triggers the download of the rust source code [here](https://github.com/bazelbuild/rules_rust/blob/d288ed634f9e149ceb0c81bda6cd93a810cf7e64/rust/private/repository_utils.bzl#L441). However, the SHAs for the nightly rust source code tarballs are not contained in the [`known_shas.bzl` dictionary](https://github.com/bazelbuild/rules_rust/blob/main/rust/known_shas.bzl), only the non-nightly versions are.

# Solution
For rust-analyzer to work again:
1.  the proper SHAs need to be added to the [`known_shas.bzl` dictionary](https://github.com/bazelbuild/rules_rust/blob/main/rust/known_shas.bzl) file in out patched `rules_rust` repo, and eventually in upstream `rules_rust`, and
2. the `include_rustc_srcs` [parameter](http://bazelbuild.github.io/rules_rust/flatten.html#rust_register_toolchains-include_rustc_srcs) of the `rust_register_toolchains` repo rule needs to be set to `True` again.

**Comment by dmcardle** [comment]
Curiously, I am using rust-analyzer in VSCode without issues. I just needed to run `./bazelisk.sh run //:gen_rust_project` and restart the rust-analyzer server in VSCode.

**Comment by andreaskurth** [comment]
> Curiously, I am using rust-analyzer in VSCode without issues. I just needed to run `./bazelisk.sh run //:gen_rust_project` and restart the rust-analyzer server in VSCode.

Does this still work for you? I see different errors when running `./bazelisk.sh run //:gen_rust_project`, sometimes
```
ERROR: Analysis of aspects '[@rules_rust//rust:defs.bzl%rust_analyzer_aspect] on //sw/device/silicon_creator/rom/e2e:rom_e2e_alert_config_test_rma_fpga_cw310_map' failed; build aborted: no matching toolchains found for types @rules_rust//rust:toolchain_type
```
sometimes
```
ERROR: Analysis of aspects '[@rules_rust//rust:defs.bzl%rust_analyzer_aspect] on //sw/otbn/crypto:div' failed; build aborted: no matching toolchains found for types @rules_rust//rust:toolchain_type
```
or others.

Given the existence of this issue I think we know that command is broken, but I wonder if there's a local workaround that would allow devs to keep generating a `rust-project.json` on their machines? (That workaround does not have to work in CI or in an airgapped environment, only on dev machines for now.)

**Comment by msfschaffner** [comment]
CC @nbdd0121

**Comment by nbdd0121** [comment]
I think this issue no longer exists? We used a rules_rust fork which adds the nightly toolchain that we use back, and I just tested that I can run gen_rust_project without issue.

We probably do want to have a tracking issue to ensure that we eventually move away from nightly compiler to stable ones.

**Comment by msfschaffner** [comment]
Great, thanks for checking. Can you open a new tracking issue for that and close this one?

**Comment by nbdd0121** [comment]
#21088
