### ISSUE TITLE
[reggen] RFC: support for block version registers

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#15333]
Placeholder for register version issues.

**Comment by msfschaffner** [comment]
- Register format proposal [doc](https://docs.google.com/document/d/1ItyPMpvtdb9gFIWLe-qVy5py6Qi8kA30r9it4uW6w4U/edit)
- Versioning conventions doc (TBD)

**Comment by msfschaffner** [comment]
Splitting this issue into two RFCs. The first one is the register region format, and that one is required for M2 (see [doc](https://docs.google.com/document/d/1ItyPMpvtdb9gFIWLe-qVy5py6Qi8kA30r9it4uW6w4U/edit)).
The second RFC is about the versioning rules, and that needs more time to converge, hence it is deferred to after M3, see: #15856

**Comment by tjaychen** [comment]
@msfschaffner i think we can officially postpone this to M3 given the state of things.
What do you think?

**Comment by msfschaffner** [comment]
Yes that sounds good to me.

CC @alphan @cfrantz

**Comment by moidx** [comment]
SGTM

**Comment by alphan** [comment]
SGTM, does this mean I have more time to look at the doc updates?

**Comment by msfschaffner** [comment]
That is correct, yes.

**Comment by msfschaffner** [comment]
This RFC has been approved by the TC today.
