### ISSUE TITLE
[otp/flash] Flash scrambling keys initialized in RAW?

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#15351]
Is there a particular reason why the flash scrambling key is initialized in the RAW OTP image?
https://github.com/lowRISC/opentitan/blob/760a0b635e060d1b7a2087aede139fca9bd6da98/hw/ip/otp_ctrl/data/otp_ctrl_img_raw.hjson#L16-L25

If no, we should probably remove it.

CC @cindychip @moidx @tjaychen

**Comment by moidx** [comment]
We should probably remove it and see if anything breaks?

**Comment by tjaychen** [comment]
Can you try it against [this test](https://github.com/lowRISC/opentitan/blob/760a0b635e060d1b7a2087aede139fca9bd6da98/hw/top_earlgrey/dv/chip_sim_cfg.hjson#L506-L510)?

I feel like it's the only one that might even be remotely impacted (but it shouldn't...).
