### ISSUE TITLE
[chip] Convert Edge-triggered status interrupt to Level

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#15378]
- [x] Revise the comportability spec
  * Define **event** and **status**. Event is one-time trigger, and status is the current HW status (e.g: FIFO empty)
  * Draw two waveforms (event: set -> SW clears) (status: asserted, HW condition alleviated then status drops)
- [ ] #16693 
- [x] #21207
- [x] #21206
- [x] #21049
- [ ] #21208
- [x] #21209
- [x] #21210
- [x] #21211

CC: @weicaiyang @a-will

**Comment by tjaychen** [comment]
i split the uart one to a separate issue since uart has already passed D3...

**Comment by eunchan** [comment]
Changing this to backlog as we decided not to change if the current interrupts work.

**Comment by GregAC** [comment]
Triaged for `flash_ctrl`, agreed that this isn't something we need to change.

**Comment by andreaskurth** [comment]
Triaged for `spi_device`, agreed

**Comment by GregAC** [comment]
Triaged for `uart`, same reasoning as above

**Comment by ballifatih** [comment]
Triaged for `kmac`, agreed, not necessary for M2.5.

**Comment by andreaskurth** [comment]
Thanks @ballifatih.

@cindychip: WDYT for `hmac` (since you've triaged that block)? If you agree this is not necessary for this release (none of the currently planned milestones), we can conclude the discussion

**Comment by msfschaffner** [comment]
Carried over from https://github.com/lowRISC/opentitan/issues/12989:

> Thanks for mentioning it, further wishes:
> 
> * UART: tx_watermark and rx_watermark would be better as status-type, tx_empty should remain event-type
> * USB: pkt_received, pkt_sent, av_empty, and rx_full all come with explanations that the underlying condition needs to be addressed, before the interrupt can be cleared, and that it will otherwise re-assert.  I would be more natural to make these status-type, as that is basically how they already work.



> Wishlist for status-type interrupts:
> 
> * `spi_device`: generic_rx_full, generic_rx_watermark, generic_tx_watermark, readbuf_watermark,
>   upload_cmdfifo_not_empty, upload_payload_not_empty
> * `i2c`: fmt_threshold and rx_threshold (as well as future tx_threshold and acq_threshold)
> * `spi_host`: It seems that six different sources are combined into one event-type interrupt, spi_event. Four of them are clearly status type (RXFULL, TXEMPTY, RXWM, TXWM), the other two READY and IDLE could also work as status-type, so I would like to ask that the entire spi_event interrupt become status-type.  (Already, the description of e.g. RXFULL makes it sound as if status-type logic applies, "To prevent the reassertion of this interrupt, read more data from the RX FIFO, or increase CONTROL.RX_WATERMARK.")

> Thanks for mentioning it, further wishes:
> 
> * UART: tx_watermark and rx_watermark would be better as status-type, tx_empty should remain event-type
> * USB: pkt_received, pkt_sent, av_empty, and rx_full all come with explanations that the underlying condition needs to be addressed, before the interrupt can be cleared, and that it will otherwise re-assert.  I would be more natural to make these status-type, as that is basically how they already work.

**Comment by vogelpi** [comment]
@msfschaffner , I am trying to assess whether we should make changes for KMAC as well and if yes [for which KMAC interrupts](https://opentitan.org/book/hw/ip/kmac/doc/interfaces.html#interrupts):
- kmac_done : signals when the absorption has completed, event seems fine for this.
- kmac_err: signals when an error has occured, event seems fine for this.
- fifo_empty: indicates if the message FIFO is empty, status seems more sensible for this one. It has also been proposed by Eli initially. However, in the list above there are cases where event seems for preferrerable (tx_empty for UART) and cases where status is preferred (TXEMPTY for SPI_HOST). Please let me know if I missed something. I am now factoring the DD/DV work KMAC out into a seperate issue.

**Comment by a-will** [comment]
I actually don't understand why UART's `tx_empty` would be an event type. What purpose does that have?

**Comment by vogelpi** [comment]
I thought the preference stated by others in previous comments might be relevant for UART only due to the much slower timing. But who knows. Thanks for sharing your opinion, I think we are both on the same page. :-)

**Comment by andreaskurth** [comment]
For [HMAC](https://github.com/lowRISC/opentitan/issues/15378#issuecomment-1910371405), I concur with [@vogelpi's suggestion for KMAC](https://github.com/lowRISC/opentitan/issues/15378#issuecomment-1910371405):
- `hmac_done`: event
- `fifo_empty`: status
- `hmac_err`: event

**Comment by jdonjdon** [comment]
@msfschaffner 
For flash_ctrl, interrupt based data transaction mechanism has never been used.
(Tested only in the block level and which works fine).
I don't see any reason we take the risk to modify this IP as @tjaychen commented earlier
(https://github.com/lowRISC/opentitan/issues/15378#issuecomment-1273670458).

**Comment by msfschaffner** [comment]
@jesultra was there a specific reason to keep the `tx_empty` interrupt for UART as event instead of converting to status?

**Comment by msfschaffner** [comment]
I have split the tasks out into individual issues that are associated with the individual blocks.
Hence I am closing this issue since the effort is now tracked elsewhere.

CC @johngt

**Comment by jettr** [comment]
I have another interrupt that I think should be status instead of event: [intr_state] on the System Reset Controller. This should be a status based on the state of the [combo_intr_status] and [key_intr_status] registers (which should remain event-based though). Otherwise there are race conditions trying to read/clear those three registers correctly. Thoughts?

[intr_state]:https://opentitan.org/book/hw/ip/sysrst_ctrl/doc/registers.html#intr_state
[combo_intr_status]:https://opentitan.org/book/hw/ip/sysrst_ctrl/doc/registers.html#combo_intr_status
[key_intr_status]:https://opentitan.org/book/hw/ip/sysrst_ctrl/doc/registers.html#key_intr_status

**Comment by msfschaffner** [comment]
I think that makes sense. There is a similar one in `adc_ctrl` which does not make any sense to keep edge-based, since it forwards a collated set of interrupts:
https://github.com/lowRISC/opentitan/blob/7e196e6f072791aa17817b7691aed6b258399eeb/hw/ip/adc_ctrl/data/adc_ctrl.hjson#L353-L371

I will convert these when I open up `adc_ctrl`.
Created an issue to track here: #21832
