### ISSUE TITLE
[entropy_src/dv] entropy_src environment cannot detect unnecessary drops

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#15381]
The `entropy_src` module drops output seeds frequently, because either the output is stalled and not pulling or occasionally because of certain exception conditions.   Since DV has little way of predicting many of these events, it is currently very lenient of missing seeds.  

This is however a problem if there is a bug that could cause seeds to drop indefinitely.  For example, consider the bug noticed in an attempted fix to #15257.  In the waveform below the  DUT ends up is supposed to suppress at most two bad seeds, on the grounds that their inputs are corrupted.   This version however has a bug in which all outputs are suppressed from the second this corruption condition is recognized, as the `fw_ov_corrupted` signal never clears.

![image](https://user-images.githubusercontent.com/47870387/194935134-b12c3873-61ca-4cae-82df-e5c207e9a362.png)

This bug itself is not hard to fix, however it is alarming fact that similar bugs may not be caught in simulation. The scoreboard needs to maintain a count of dropped seeds, and check the queue of remaining seeds during the `check_phase`.   

> original estimate 4
> estimate 20
> remaining 2023-04-19 2

**Comment by martin-lueker** [comment]
Once can reproduce this case running the following command from branch "issue_15381" in my (@martin-lueker) fork:
```
util/dvsim/dvsim.py hw/ip/entropy_src/dv/entropy_src_sim_cfg.hjson -i entropy_src_fw_ov -w shm -r 1 -s 83892382 --run-modes set_verbosity_comp_a_uvm_debug set_verbosity_comp_b_uvm_debug
```
A successful resolution to this issue would cause a test _failure_ with the seed above.

**Comment by msfschaffner** [comment]
CC @tjaychen @cdgori 

Is this a must fix for M2?

**Comment by tjaychen** [comment]
@martin-lueker  correct me if i'm wrong, but my understanding of this is that our DV is not currently able to catch errors where we drop seeds when we should not. The issue you found was already fixed, so this is more a DV probelm right?

If my understanding is right, I think whoever is taking over entropy_src v2/v2s should probably have a look to see if it's an enhancement that can be done. I don't think there's a design bug here though.

**Comment by andreaskurth** [comment]
From the description, I share the understanding that this currently is a DV concern and no known RTL bug.

Could we eliminate this concern by adding an assertion that ensures that the SHA-3 output is pushed into the `esfinal` FIFO unless
- bypass mode is active, or
- the SHA-3 block is being flushed, or
- the SHA-3 block has produced <= 2 outputs since the `es_fw_ov_disable_alert` has last happened?

**Comment by tjaychen** [comment]
that seems very reasonable to me, i suppose we can always try that and see if block level regression gets unhappy :)

**Comment by martin-lueker** [comment]
Well, my concern is that there is something we _don't_ understand.  Let me take a stab at this I have an idea, it's one more PR.

**Comment by martin-lueker** [comment]
To confirm this is a DV problem, yes.

**Comment by tjaychen** [comment]
sounds good. Thanks Martin. 
If we think it is a DV issue purely, outside of adding assertions, I think it is OKAY to move this issue to M3.
We will then make sure to complete the coverage story as part of D3 / V3 sign-off.

**Comment by vogelpi** [comment]
This is not a design bug but we should solve this for M2.5 because we expect this to further increase confidence in the DV environment and maybe even unveil real design issues.
