### ISSUE TITLE
KMAC is_locked inverse result

### ISSUE THREAD

**Issue by ballifatih** [lowRISC/opentitan#15405]
https://github.com/lowRISC/opentitan/blob/cc7d363b4eaf952dd08a79eeacaa4d4d7a58f35a/sw/device/lib/dif/dif_kmac.c#L769-L779

I seem to think that the result `is_locked` is the inverse of what it should be. What I expect is:

- KMAC is locked/busy -> `is_locked = True`
- KMAC is available -> `is_locked = False`

but the result is the other way around. I am not sure if I this is a bug or I am just thinking too literally about the interpretation of the function's name.

In any case, this is blocking PR #14637, because my update is breaking some KMAC dif unittests.

I attached an example for KMAC below, so that one can see the value of `KMAC_CFG_REGWEN_EN_BIT` when KMAC is idle.

![image](https://user-images.githubusercontent.com/7850700/195159490-57ca4e79-baca-4f84-bdca-63b7cbd42c9c.png)

**Comment by tjaychen** [comment]
i feel like your interpretation makes more sense. 

@jadephilipoom 
@eunchan 
@cindychip 

are you guys okay with making the change as @ballifatih suggested?

**Comment by eunchan** [comment]
So, IIUC, `is_locked` in DIF represents the CFG_REG_WEN directly and it should be the inverse of CFG_REG_WEN?

Maybe @jadephilipoom knows better, but I think so. (and waveform also shows CFG_REG_WEN being **0** while KMAC is running.)

**Comment by ballifatih** [comment]
> So, IIUC, `is_locked` in DIF represents the CFG_REG_WEN directly and it should be the inverse of CFG_REG_WEN?

Yes, exactly this. 

As a side note, I was able to find only these three unit tests calling `dif_kmac_config_is_locked`. I think these should also be updated because of this meaning change.

https://github.com/lowRISC/opentitan/blob/17a89ad860106aa5ad5d018c80eea27dc2f81c3a/sw/device/lib/dif/dif_kmac_unittest.cc#L590-L610

**Comment by jadephilipoom** [comment]
I also agree with Fatih's suggestion. :+1:

**Comment by ballifatih** [comment]
I suggested a fix in PR #15431, I can close this issue if someone can merge it.

**Comment by ballifatih** [comment]
Thank you @jadephilipoom, @eunchan, @tjaychen. Closing this because #15431 is merged.
