### ISSUE TITLE
[chip dv] Exclude functional coverage from interface agents

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#15422]
At the full chip, we instantiate UART, SPI device, I2C (and few other) interface agents, which all provide a suite of functional covergroups. At the chip level, our goal is to not exhaustively test these IO protocols, so several of these functional covergroups show up uncovered. We need to assess and exclude the covergroups which we dont plan to cover.

**Comment by weicaiyang** [comment]
@sriyerg all the fcov from interface agents are gone. perhaps we can close this now
