### ISSUE TITLE
[doc/flash_ctrl] program and rd fifo register diagram is not correct

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#1542]
Hi Tim,

A minor issue for the `FLASH_CTRL.prog_fifo` and `FLASH_CTRL.rd_fifo` register diagram. Please refer to the screenshot. The address should be `0x54` and `0x58` only.

![image](https://user-images.githubusercontent.com/11466553/74390349-d8cdb280-4db5-11ea-9429-f8c1046f89a7.png)

**Comment by tjaychen** [comment]
hmmm... does this mean it was a doc rendering error? Because i do only say the window is 1 item..
