### ISSUE TITLE
[chip, dv, cov] Unused reset signals from rstmgr 

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#15426]
The rstmgr emits resets for all power domains, but the consumers only use the reset corresponding to the power domain they are in. The rest of the reset flavors are unused at the chip level. This significantly dents the rstmgr coverage at the chip level. 
https://reports.opentitan.org/hw/top_earlgrey/dv/latest/cov_report/mod29.html#inst_tag_194

As of 10/11/2022, the rstmgr block at the full chip has 62% port toggle coverage. The low coverage on `resets_o.*[1]` signals is one of the contributors. These would have to be excluded. There may be a possibility to autogenerate the exclusion using our topgen machinery.

**Comment by tjaychen** [comment]
i'm a bit behind on this, but i'll hopefully take a look at this soon.
