### ISSUE TITLE
[dv] In-RTL exclusions for unused signals and SVA logic

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#15423]
RTL has several `unused` signals that are connected to tied off ports. These show up as uncovered. Also, there are pieces of logic that are not synthesized, but they exist to support in-RTL assertions. These helper pieces of code also show up as uncovered throughout the design. This impacts the coverage of block level as well as top level. These need to be effectively excluded from coverage collection. 

@matutem has made a PR to wrap these in coverage disable / enable pragmas, but they are yet to be applied throughout the design.

**Comment by sriyerg** [comment]
I believe there are a few more places (in full chip) where these are needed. So, leaving this issue open.

**Comment by matutem** [comment]
There are close to 500 unused* signals under hw *sv files. I imagine some automation for disabling toggle for these is doable.

As for the snippets of assertion-only code, some of it is under `ifdef INC_ASSERT, which could also be easy. Not sure how much such code is not under this ifdef.

**Comment by msfschaffner** [comment]
Ideally, helper logic for assertions should always be wrapped with `ifdef INC_ASSERT.

However, if we were to add inline coverage exclusion pragmas to `ifdef INC_ASSERT, would that have any adverse effect on assertions that are part of the affected code section in terms of assertion coverage collection?

**Comment by sriyerg** [comment]
No it wont - we would only be excluding the helper logic, not the assertions, so it should be safe. But that also means, each of these need to be carefully addressed (i.e this wouldn't be a quick search and replace thing). We could write a script that "finds" all instances of `ifdef INC_ASSERT`, then wraps all non-empty contiguous lines within that do not contain any `` `ASSERT_*`` statements in coverage off / on pragmas.

**Comment by sriyerg** [comment]
Moved to M3, since the block / chip level coverage requirements for M2 will be met without needing this.

**Comment by msfschaffner** [comment]
> No it wont - we would only be excluding the helper logic, not the assertions, so it should be safe. But that also means, each of these need to be carefully addressed (i.e this wouldn't be a quick search and replace thing). We could write a script that "finds" all instances of `ifdef INC_ASSERT`, then wraps all non-empty contiguous lines within that do not contain any `` `ASSERT_* `` statements in coverage off / on pragmas.

Ok but if we made it part of the `INC_ASSERT` macro itself (in order to avoid having to go through this search/replace exercise), that would have an effect on the assertions, right?

**Comment by sriyerg** [comment]
> Ok but if we made the pragmas part of the `INC_ASSERT` macro itself (in order to avoid having to go through this search/replace exercise), that would have an effect on the assertions, right?

I am not sure I understand how you are envisioning making this a part of the `INC_ASSERT` macro such that no search and replace would be needed. Could you elaborate more?

**Comment by msfschaffner** [comment]
Nevermind my last comment - I had this backwards in my head. We are using `INC_ASSERT` only as a define here, and not as a macro with arguments containing the code section. If it were the latter, we could potentially do something like this:

```systemverilog
`ASSERT_WRAP(__CODE) \
  // pragma     \
  __CODE        \
  // pragma                

`ASSERT_WRAP(
  // assertion helper logic goes here
  `ASSERT(...)
)
```

**Comment by vogelpi** [comment]
Applying these pragmas widely in the design to enable full coverage closure is a V3 item. However, the pragmas can already be very useful for V2(S) coverage goals.

**Comment by moidx** [comment]
Closing as obsolete. We'll reassess coverage closure based on latest results.
