### ISSUE TITLE
Enable rust clippy on the codebase

### ISSUE THREAD

**Issue by cfrantz** [lowRISC/opentitan#15443]
- Enable clippy on the whole codebase.
- Clean up the lint

**Comment by cfrantz** [comment]
TODO:
- [ ] Work out how to deal with version stamping and re-enable clippy for opentitantool.
- [ ] Fix `module_inception` in the `otp` and `image` modules.
- [ ] Investigate the `large_enum_variant` in the `rsa` command.
- [ ] Check and correct the commented line of code in `alert_handler.rs`.

**Comment by msfschaffner** [comment]
@cfrantz what is the status of this issue?
