### ISSUE TITLE
[spi_device] Remove Generic (a.k.a. FwMode) from SPI_DEVICE HWIP

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#15452]
This is a topic brought up multiple times. As TPM can behave almost identical but limited frame size (64B in TPM vs 1kB or more), it is OK to remove Generic mode. TPM protocol, however, has better flow control compared to Generic mode.

The benefit of removing Generic mode is to clean up the complex CDC path on SRAM B port in SPI_DEVICE. It raises many CDC warnings and errors, so that we waived many of them. By removing the Generic mode, SRAM b datapath sits in SPI_CLK always, which simplifies the clock domain and makes easier to verify CDC.

CC: @tjaychen @weicaiyang @jeoongp

**Comment by a-will** [comment]
> The benefit of removing Generic mode is to clean up the complex CDC path on SRAM B port in SPI_DEVICE. It raises many CDC warnings and errors, so that we waived many of them. By removing the Generic mode, SRAM b datapath sits in SPI_CLK always, which simplifies the clock domain and makes easier to verify CDC.

I'll point out that adjusting the generic mode logic so it doesn't use asynchronous FIFOs in front of the SRAM would also take care of that issue. Removing generic mode altogether may be the best choice, but it's not the _only_ way to get rid of the complex CDC.

**Comment by eunchan** [comment]
Yep. you are right. We can fix the issue as DPRPAM now supports byte enable (it wasn't when GenericMode was designed. That's why DPSRAM was in SYS_CLK and async fifo was there). But as I mentioned, it is not worth to have two almost identical modules in SPI_DEVICE.

**Comment by tjaychen** [comment]
if we remove generic mode, does that mean spi device would have no way of constructing a full duplex protocol if someone wanted to use it that way?

**Comment by tjaychen** [comment]
i've honestly only ever seen 2 use cases of someone doing that.
@a-will may have seen others.

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. Labeling https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease because removing Generic / FW mode seems out of scope for this release. Verification of the mentioned CDC path is tracked in #15457.

**Comment by msfschaffner** [comment]
Indeed, removing / changing generic mode is out of scope for M2.5.
CDC will be closed separately as noted above.
