### ISSUE TITLE
[spi_device] Document update needed for flash/passthrough mode

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#15463]
EDIT: make this a checklist to include other document update requests.

- [x] As @eunchan mentioned, we support {polarity, phase} to be 'b00 or 'b11 for flash/passthrough mode. Please document it in the spec.

- [ ] since https://github.com/lowRISC/opentitan/pull/15326 is merged, perhaps also document the minimum inactive time between transactions (2 tpm, 2 flash, 1 tpm and 1 flash).

- [x] document that SW can only update addr_4b at the beginning before host sends any commands, due to #15543

- [x] document mem parity in countermeasure section

**Comment by weicaiyang** [comment]
BTW, since [#15326](https://github.com/lowRISC/opentitan/pull/15326) is merged, perhaps also document the minimum inactive time between transactions (2 tpm, 2 flash, 1 tpm and 1 flash).

cc: @jeoongp

**Comment by msfschaffner** [comment]
Since this is mostly documentation cleanup in the spec, I will mark this as a D3 / M3 item.

**Comment by weicaiyang** [comment]
> Since this is mostly documentation cleanup in the spec, I will mark this as a D3 / M3 item.

SG, thanks @msfschaffner

**Comment by eunchan** [comment]
@jeoongp could you please address the second item? You most likely knows better than I am onto the logic.

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP3 because this is 'only' about documentation.
