### ISSUE TITLE
Aligning behavior on local caching of entropy for secure wipe

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#15473]
During the OTBN V2S review the idea was brought up to align our IPs regarding local entropy caching for secure wipe. At the moment, various IPs follow a different approach. To give some examples:
- OTBN:
  - In case of secure wipe first reseeds URND over EDN, then performs the secure wipe and reseeds again. If the reseed doesn't finish, OTBN will not finish the secure wipe. Further operations (coming out of reset, enabling RMA entry) are blocking on that.
  - There is a one-word cache for RND (high-quality entropy). Software can trigger filling of that cache with a CSR access and continue the processing while the cache is being filled.
- FLASH Ctrl, KeyMgr and maybe others (scrambled memories?) have little entropy caches in some places that are filled in the background. In case of an escalation, the content of this caches is used to reseed internal PRNGs and then to immediately wipe local regs/memories/scrambling key regs. The nice thing about this is that the secure wipe is not depending on EDN in this case and can be constant time.
- AES doesn't have local cache and just just doesn't come available to software until the initial PRNG reseed has happened. Then, PRNGs are periodically reseeded.

For future versions we should discuss whether we want to align IPs in this regard.

**Comment by vogelpi** [comment]
FYI @msfschaffner @andreaskurth @GregAC @ctopal

**Comment by msfschaffner** [comment]
Also adding @tjaychen @moidx.

**Comment by tjaychen** [comment]
@cdgori 

thanks for filing.
I do agree we'll need a general philosophy on this should be handled going forward, but to me it will still likely have a few flavors.

**Comment by GregAC** [comment]
Triaged for `otbn` https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease remains a sensible label

**Comment by ballifatih** [comment]
Triaged for `keymgr`, looking at alignment later sounds reasonable.

**Comment by GregAC** [comment]
Security working group will have he final say, but I can't see this being needed for PROD  but definitely something to consider for FutureRelease

**Comment by vogelpi** [comment]
I agree that we won't be able to align behavior of our blocks for production. But it's probably worth to formulate a recommendation e.g. as part of the comportability spec for future clean-sheet work. I think there are other, similarly suitable issues and I will create an new issue to collect those.
