### ISSUE TITLE
[dv/top] update spi_host to support multiple instances

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15483]
The spi_host top level tests right now only support 1 instance.
We need to upgrade the infrastructure here to be able to support any random instance. 

- [ ] add support for spi_host test.

**Comment by tjaychen** [comment]
@johngt

**Comment by johngt** [comment]
For I2C host component of this; Either @vrozic or @hcallahan-lowrisc could be assigned to work on this. @hcallahan-lowrisc has familiarity with SPI_Host now after having worked on this. Will coordinate with @engdoreis for assignment

**Comment by tjaychen** [comment]
thank you for taking this on!

**Comment by johngt** [comment]
@tjaychen / @weicaiyang - email discussion started on this due to this being potentially a very large task. Devs are working on other SPI_Host items for now but we will await your further description on this issue or in the email.

**Comment by johngt** [comment]
Based on the discussion via email and also on the thread https://github.com/lowRISC/opentitan/issues/14114 it looks like the majority of this work, at least for the SPI_Host sub-task is to ensure that the different SPI_Host interfaces are tested.

From Sri:
>I was reviewing chip level coverage, and indeed the SPI HOST1 interface appears to not be covered, which means the connection of SPI_HOST1 to pinmux is untested.
So this issue will look into the randomisation of SPI_Host interface

Tim has suggested that devs working on this look at UART to see how this is done there.
TimC:
>Our top level DV environment already has parameters for defining the number of DV agents and their related interfaces.
So then the work is really to update the related vseq and C files to take advantage of that by selecting a random interface to work with in the test.  Please see here for [an example](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/tests/sim_dv/uart_tx_rx_test.c;l=57-69).

For SPI_Host randomisation: Changes to the vseq, the corresponding C test, and possibly the chips_if to hook-up the appropriate pins.

**Comment by johngt** [comment]
@hcallahan-lowrisc will look into the SPI_Host part of this issue.

**Comment by tjaychen** [comment]
thank you!
should i spilt this into 2 issues?

**Comment by hcallahan-lowrisc** [comment]
@tjaychen Yes please, it's likely at this point that someone else will pick up the i2c_host part. Thanks!

**Comment by sriyerg** [comment]
I reopened #14114 since the test technically is not complete (as described in the testplan) and has this task pending. By reopening that issue, this pending work item will show up in the test development tracking views for M2.

**Comment by johngt** [comment]
Related PR https://github.com/lowRISC/opentitan/pull/16364
