### ISSUE TITLE
[rv_dm] Port vendoring patches to patch repository and clean up

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#15506]
Our vendoring currently applies patches to `pulp_riscv_dbg` that are not part of our [patch repository](https://github.com/lowRISC/riscv-dbg). At least the following PRs are involved: #12613, #12728, and #15436.

Those patches should be ported to the patch repository and then re-imported cleanly with the `--refresh-patches` flag; see https://github.com/lowRISC/opentitan/pull/15436#discussion_r994885260 and https://github.com/lowRISC/opentitan/pull/15436#discussion_r995102629.

On this occasion, excluding files that are unused in OT might be worth a look (see https://github.com/lowRISC/opentitan/pull/15436#discussion_r994874817).

**Comment by msfschaffner** [comment]
Fixed in #15737.
