### ISSUE TITLE
[RFC] Status Type Interrupt

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#15518]
This RFC proposes an additional interrupt type, _Status_ type interrupt. The idea started from the issue #15282 where we've talked about the benefits of status interrupt (keeping the interrupt line high until the cause disappears).

The details are in the [RFC: Interrupt Types document](https://docs.google.com/document/d/1aOS1GzvtV7UjIUtcn-gANefaoMFWwZub_biSFHJXM-c/edit) (Read / comment permission to @opentitan.org accounts)

**Comment by msfschaffner** [comment]
@msfschaffner

**Comment by msfschaffner** [comment]
This RFC has been approved by the TC today.

**Comment by eunchan** [comment]
Implemented in #15580 
Closing this issue.
