### ISSUE TITLE
Invalidate icache prior to running SRAM example program in GDB test

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#15595]
> > * This will be something to be aware of when execute from sram is used in the future, we should probably always invalidate prior to jumping.
> 
> @dmcardle can you update the relevant parts of the code execution from SRAM example and test? Thanks!

Will do. I may need to add an icache_invalidate() function to the SRAM example program because it's tricky to run arbitrary instructions from GDB. It's also possible that I can ask OpenOCD to do `fence.i` somehow.

_Originally posted by @dmcardle in https://github.com/lowRISC/opentitan/issues/15583#issuecomment-1284077470_

**Comment by tjaychen** [comment]
yeah i wouldnt say this is super high priority. If it's difficult to do for any reason, even just leaving a note as something to be aware of I think is good enough.

**Comment by dmcardle** [comment]
I actually think this is unnecessary because OpenOCD will execute `fence.i` on its own. When we tell GDB `print sram_main()`, OpenOCD eventually hits [`resume_prep()`](https://github.com/openocd-org/openocd/blob/master/src/target/riscv/riscv.c#L1398).

* `resume_prep` is a pointer to [`riscv013_resume_prep()`](https://github.com/openocd-org/openocd/blob/master/src/target/riscv/riscv-013.c#L4278), which calls...
* [`riscv013_on_step_or_resume()`](https://github.com/openocd-org/openocd/blob/master/src/target/riscv/riscv-013.c#L4781), which calls...
* `maybe_execute_fence_i()`, which calls...
* `execute_fence()`, which calls...
* [`riscv_program_fence_i()`](https://github.com/openocd-org/openocd/blob/master/src/target/riscv/program.c#L149)

That being said, it can't hurt to be explicit.

**Comment by tjaychen** [comment]
o sounds good! then maybe we're fine! why do more work unless it's necessary :)

**Comment by alphan** [comment]
Thanks for looking at the code @dmcardle! I agree with your decision #15617, this is an implementation detail of OpenOCD so it's a good idea to `fence.i` just in case.
