### ISSUE TITLE
Commit that uses bazel instead of bazelisk passes our CI when I don't think Bazel is installed in the containers

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#15615]
I saw something weird a few days ago and never came up with a good explanation:
The tests on this commit appear to have passed: https://github.com/lowRISC/opentitan/commit/8bd6f35829e5d079f01297276847075ebf5905b4

The commit has changed a python script to run bazel instead of ci/bazelisk.sh, which I'd expect to fail because we no longer install bazel. If a version of bazel is leaking into the CI containers it may create an issue when we update the requirements.

I recall that the PR passed, before it was changed not to use bazel, but I may be having trouble viewing the logs. The step that's been changed appears to be running bazelisk.sh when I view the logs.

**Comment by msfschaffner** [comment]
Is this still a problem?

CC @timothytrippel @cfrantz
