### ISSUE TITLE
[pwrmgr] Cleanup powerup sequence and strap sampling pulse

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#15624]
Due to the reset domain reorganization #15317, there are a couple of things that should be cleaned up and simplified in the power manager FSM:

- the strap sampling pulse can be issued earlier, before the ROM check is started.
- TBD cleanup staggered resets of the previously named `lc` and `sys` domains

We can discuss the exact details of the change in a quick meeting if needed.

**Comment by tjaychen** [comment]
it's probably worth pointing out that until we fix the strap sampling change, we could end up blocking entry into RMA in the worst case. @msfschaffner is there anything else you can see that might cause blockage? Outside of `otp_ctrl` and `lc_ctrl`.

**Comment by msfschaffner** [comment]
No I don't think so.

**Comment by tjaychen** [comment]
maybe you and i can find some time to brainstorm hehe. Counting the discussion with Alphan, I feel like we've identified 3 RMA blocking things recently... who knows what else is hidden.

**Comment by msfschaffner** [comment]
True, let me think a bit more. 
I only came across this issue because I ran into strap timing issues in the `rv_dm_lc_disable` test.

Is there anything around ext clock we should take a look at?

**Comment by tjaychen** [comment]
honestly i'm not sure... i feel like i need to get a cup of coffee, sit down and stare at the block diagram a bit hehe.

**Comment by msfschaffner** [comment]
Carried over from https://github.com/lowRISC/opentitan/pull/15602:

> @msfschaffner also pointed out some in areas in the `RomCheck` state we should look at. Right now, `lc_rst_req_d` is released at a different time fro m`sys_rst_req_d` to allow life cycle control to initialize ahead of process operation.
> 
> But we can tweak this area a bit to..
> 
> 1. release both resets at the same time, but use fetch_enable to hold cpu from executing
> 2. initialize lc controller
> 3. sample strap
> 4. perform rom checks
> 5. if rom checks succeed -> then finally go to active state.

**Comment by tjaychen** [comment]
@jeoongp and i sync'd up today and discussed the logic in this area.
We will probably need to follow up the exact mechanism for hardening next wednesday, but I believe we are on the same page now.

**Comment by tjaychen** [comment]
this issue i believe is now superseded by #15494, which documents all the intended fixes and final decision.
@msfschaffner should we close this one down?
