### ISSUE TITLE
[rtl/rstmgr] corner case on using rw1c to fatal alert

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#15654]
When @matutem and I debug the FPV rstmgr_sec_cm test, we found that design did not trigger fatal alert after invalid FSM value.

The reason is related to `err_code` is a `RW1C` register.
Seems like if user write to this `err_code` register right when HW sets the `fsm_err`, user might be able to clear this fatal alert.

**Comment by matutem** [comment]
And the expectation is that fatal errors should be Sw RO.

**Comment by tjaychen** [comment]
@tjaychen 

@jeoongp can you have a look at this one?

**Comment by jeoongp** [comment]
@cindychip can you give me the run command? If you have a waveform to be shared in mnt, it will be good.

**Comment by tjaychen** [comment]
@jeoongp this one is reproduced only in fpv, so that might be a bit difficult.
I think the request is basically to swap the attribute type on the rstmgr err_code register.

**Comment by cindychip** [comment]
We are not entirely sure if this will clean up all the failures, but if you want to try! 
Get the latest repo (because I just merged this PR: https://github.com/lowRISC/opentitan/pull/15655)
And run:
./util/dvsim/dvsim.py hw/top_earlgrey/formal/top_earlgrey_fpv_sec_cm_cfgs.hjson --select-cfgs rstmgr_sec_cm --gui

**Comment by jeoongp** [comment]
Thanks @cindychip and @tjaychen. I fixed this bug in #15682.

FYI, this failure did not occur in my run on the latest repo.
![Screen Shot 2022-10-24 at 10 02 27 AM](https://user-images.githubusercontent.com/103145460/197584644-be044eaa-b2c6-451f-b6bf-c0431759ef6a.png)

**Comment by cindychip** [comment]
> Thanks @cindychip and @tjaychen. I fixed this bug in #15682.
> 
> FYI, this failure did not occur in my run on the latest repo. ![Screen Shot 2022-10-24 at 10 02 27 AM](https://user-images.githubusercontent.com/103145460/197584644-be044eaa-b2c6-451f-b6bf-c0431759ef6a.png)

Thanks! Let me take a look and I will update you :)

**Comment by cindychip** [comment]
@jeoongp I rerun with the latest repo and got 100% passing rate. I think the fix is good!
