### ISSUE TITLE
[rv_dm,dv] Verify that the debugger can issue a non-debug reset to the rest of the system (`ndmreset_req` BLT)

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15666]
This issue tracks the implementation of the `ndmreset_req` block-level test, which is specified in the testplan for `rv_dm`.

>estimate 8

**Comment by andreaskurth** [comment]
As [discussed on December 15](https://docs.google.com/document/d/1Zqir5ju06JECiB_qwSH5-an200fIRbqd99T4nOvOLdA/edit), we still think we should have a block-level test for this, even though a TLT for `ndmreset_q` exists.

**Comment by andreaskurth** [comment]
Triaged for `rv_dm`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP3 because this is an open V2 test but we already have a TLT covering it.

**Comment by rswarbrick** [comment]
I see that @BasitMehmood implemented `rv_dm_ndmreset_req_vseq` at the end of last September. Is there anything left to do before this can be closed?

**Comment by andreaskurth** [comment]
@rswarbrick @BasitMehmood: Can this be closed?

**Comment by moidx** [comment]
rv_dm DV work carried over to M5.

**Comment by andreaskurth** [comment]
@rswarbrick to please check whether this is done

**Comment by rswarbrick** [comment]
Yep, this is done (and I essentially rewrote the test in question in feeed78af8882bfb98dfcbb4d57ec98537621551). Closing accordingly.
