### ISSUE TITLE
[rv_dm,dv] Verify that access to SBA interface is disabled if lc_hw_debug_en is set to not strict true value (`sba_debug_disabled` BLT)

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15668]
This issue tracks the implementation of the `sba_debug_disabled` block-level test, which is specified in the testplan for `rv_dm`.

>estimate 8

**Comment by andreaskurth** [comment]
As [discussed on December 15](https://docs.google.com/document/d/1Zqir5ju06JECiB_qwSH5-an200fIRbqd99T4nOvOLdA/edit), there is no TLT for this (and there is none planned), so this will have to be covered by a block-level test.

**Comment by andreaskurth** [comment]
Triaged for `rv_dm`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP1 because this IMO is a particularly important open V2 test.

**Comment by GregAC** [comment]
Priority reduction as JTAG access gating is tested at the top-level and that is the only way to access the SBA. A block-level test to specifically test the SBA gating would be useful but not critical.

**Comment by andreaskurth** [comment]
Discussed in triage, moving to M5 with the rationale above

**Comment by rswarbrick** [comment]
I'm bumping up the priority of this item to P1 because it's a requirement for completing V2 (since this is a V2 test that isn't actually written!).
