### ISSUE TITLE
[flash controller] default (reset) value of status register is 0xa 

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#1567]
The reset value of flash_ctrl::status register is 0xa. This is due to `prog_empty` and `rd_empty` fields which are 1 out of reset. 

A side effect of this is the `prog_empty` interrupt signal being active out of reset as well, causing the `intr_state.prog_empty` to be set to 1. 

This is causing chip level CSR tests to fail. 

First one is easily fixed in the RAL hjson spec. Second one can be fixed by manually "overriding" the reset value of the intr_state CSR in the chip level environment. I however wanted to confirm if we actually want this (interrupt will trigger the moment it is enabled, in case there are no flash operations).

**Comment by tjaychen** [comment]
this sounds like i either forgot to make those interrupts edge triggered (i
thought i did), or i made the default value wrong (probably more likely).
So yes, I agree we don't want these interrupts asserting by default, and
should make appropriate fixes.

**Comment by sriyerg** [comment]
Leaving this bug open for more appropriate fixes.

**Comment by tjaychen** [comment]
i'm sorry i completely read this issue wrong in the beginning.  I thought this said "interrupt", only now am i realizing it is status.

For status i think your fix is the right one in making the default 1, but for interrupts i should make it default to 0. 

I'll close this for now and fix the interrupt issue separately.
