### ISSUE TITLE
[rv_dm,dv] Verify that the debugger can cancel an on-going DMI transaction with a hard reset (`jtag_dtm_hard_reset` BLT)

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15670]
This issue tracks the implementation of the `jtag_dtm_hard_reset` block-level test, which is specified in the testplan for `rv_dm`.

>estimate 8

**Comment by andreaskurth** [comment]
Triaged for `rv_dm`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2 because this is an open V2 test.

**Comment by GregAC** [comment]
This scenario likely doesn't occur in practise as the transaction in the DM side completes in a single cycle once it crosses the CDC. The DM clock runs faster than the JTAG clock so in all likelihood that JTAG cannot action a hard reset before the transaction is complete. If there's a scenario where the DM clock is paused and the JTAG running this may be a useful thing to test but not high priority.

**Comment by jdonjdon** [comment]
@GregAC @andreaskurth @msfschaffner 
I tried if the scenario Greg suggest,
![image](https://github.com/lowRISC/opentitan/assets/99843637/0d4d16eb-420a-4412-abc4-912153b022ef)
Even though I can stop the dm clock and issue dmihardreset right after dmi write request,
the previous dmi write request (write 0x114c_8440 to progbuf[0]) stays at the data pipe line and dmihardreset only
clear tb.dut.u_dm_top.i_dm_csrs.i_fifo  and tb.dut.dap.state_q.
So as soon as dm clock gets back, target register is updated with a new value.

**Comment by jdonjdon** [comment]
cc: @BasitMehmood

**Comment by msfschaffner** [comment]
I wonder whether it is a useful requirement to be able to cancel an ongoing DMI transaction if we guarantee that it always completes within one cycle, once it made it through the CDC... On top of that, this feature will be increasingly difficult to implement once we move to a TL-UL interface for transporting requests from the TAP to the RV_DM.

CC @a-will

**Comment by msfschaffner** [comment]
@GregAC @a-will do you think this is useful to do? I don't think we have to focus on this test, since it cannot be used in practice.

**Comment by a-will** [comment]
> @GregAC @a-will do you think this is useful to do? I don't think we have to focus on this test, since it cannot really be used in practice.

Only the smallest utility, since it's testing a feature that won't practically be used.

**Comment by GregAC** [comment]
I agree I don't think this is a priority to test. Though we would want to ensure a hard reset doesn't leave things locked up (e.g. because there's a half-completed DMI transaction).

**Comment by msfschaffner** [comment]
OK in this case I suggest we simplify the test so that we check that nothing gets locked up (as @GregAC mentioned), plus we get some coverage:

1) issue a few DMI register read operations and make sure they return the correct data.
2) reset the DMI
3) redo 1) to make sure the debug module still responds correctly.

**Comment by msfschaffner** [comment]
@jdonjdon @BasitMehmood does this (simplified) test still have to be implemented?

**Comment by jdonjdon** [comment]
> @jdonjdon @BasitMehmood does this (simplified) test still have to be implemented?

IIUC, only [failed_op](https://github.com/lowRISC/opentitan/blob/143098eec598e92bd7dd20939d5c7587f4039705/hw/ip/rv_dm/data/rv_dm_testplan.hjson#L172) will be removed and everything else still in the list.
Let me update the desc section of "jtag_dtm_idle_hin" following your suggestion

**Comment by msfschaffner** [comment]
Closed as addressed in #20727
