### ISSUE TITLE
[aes] Verify DATA_REG.KEY.SCA and KEY.MASKING countermeasures

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15705]
Per AES close-out tasks described in more detail at https://docs.google.com/document/d/1Uzq6qSqOFqk0fDv0J1eUvnpGMR1wsF-03WhZUgIDKdw/edit#

- DATA_REG.KEY.SCA implement new assertions checking that in last cycle of last round, state register is overwritten with something different to cipher output
- KEY.MASKING: implement assertions described [here](https://github.com/lowRISC/opentitan/issues/15433#issuecomment-1277562429) and run them through existing tests
- Mention that SCA is verified on the FPGA and using formal

>estimate 8
>remaining 2022-10-28 4

**Comment by vogelpi** [comment]
I've written the assertions and created a PR here #15810.
