### ISSUE TITLE
[aes] Push/pull IF assertion violated after reset on fatal alert

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15707]
See related issue: https://github.com/lowRISC/opentitan/issues/13573

Tagged M2 and AES but really a more generic issue on reset sequencing. The problem is that the block-level test is not aware of the correct sequencing of resets (AES cannot be reset without also resetting EDN).

> estimate 2
> remaining 2022-10-27 0

**Comment by johngt** [comment]
Requires further discussion with Google.
@andreaskurth / @vogelpi - best to ping the specific Google Engineer's we want feedback from after we have had a first discussion with @rasmus-madsen

**Comment by johngt** [comment]
Further discussion needed between @vogelpi and @weicaiyang

**Comment by vogelpi** [comment]
Hi @johngt ,
I think I could solve this, I've filed a PR here #15791. I've also added an estimate (actually roughly based on how much time I've actually spent).

**Comment by vogelpi** [comment]
The PR has been merged. I am thus closing this issue.
