### ISSUE TITLE
[aes] Formal methods / Jasper on AES

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15708]
Per the AES closeout discussion document, with further details at https://docs.google.com/document/d/1Uzq6qSqOFqk0fDv0J1eUvnpGMR1wsF-03WhZUgIDKdw/edit#

Need to run Jasper Gold to check assertions related to standardised countermeasures prim_count/prim_fsm.

>estimate 4

**Comment by msfschaffner** [comment]
CC @cindychip

**Comment by vogelpi** [comment]
I wasn't aware but these tests are in the FPV dashboard as well: https://reports.opentitan.org/hw/top_earlgrey/formal/sec_cm/summary/latest/report.html

For AES, everything is passing. @cindychip is this sufficient? Or is there something we should check for V2S on top of this?

**Comment by msfschaffner** [comment]
If the FPV setup is correct and all assertions are written for AES, this should be sufficient, yes. I will let @cindychip confirm - then we should be able to close this bug.

**Comment by cindychip** [comment]
They are passing and all 100%, so I think we can close it. https://reports.opentitan.org/hw/top_earlgrey/formal/sec_cm/summary/latest/report.html

**Comment by vogelpi** [comment]
Great, thanks for confirming @cindychip and @msfschaffner !
