### ISSUE TITLE
[flash_ctrl] flash_macro_err leads to fatal alert although it can be triggered by SW misuse.

### ISSUE THREAD

**Issue by zi-v** [lowRISC/opentitan#15702]
Consider changing flash_macro_err assignment to non-fatal alert.

Reference lines:
https://github.com/lowRISC/opentitan/blob/7a7139c8af345f423ac27a0186febdda027f7127/hw/ip/flash_ctrl/data/flash_ctrl.hjson#L1883
https://github.com/lowRISC/opentitan/blob/7a7139c8af345f423ac27a0186febdda027f7127/hw/ip/flash_ctrl/data/flash_ctrl.hjson#L1931

**Comment by eshapira** [comment]
@eshapira
