### ISSUE TITLE
[spi_device] Dummy CSB may trigger an upload interrupt

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#15721]
We test 3 types of dummy SPI transaction and hope it doesn't affect anything.
1. active CSB without sck
2. toggling sck without CSB
3. send request/opcode less than 1 bytes (only for Flash or TPM mode)

However, in flash mode, we rely on CSB falling edge with sck to clear a flag - csb_cmdfifo_set.
In this case, we only have CSB drop without sck, so `csb_cmdfifo_set` isn't cleared. However, we do detect `sys_csb_deasserted_pulse_i`, so it triggers an upload interrupt. (`sys_cmdfifo_set` leads to an interrupt.)

We may have to constrain the dummy case 1 with FW mode only.

```
  always_ff @(posedge sys_clk_i or negedge sys_rst_ni) begin
    if (!sys_rst_ni) sys_cmdfifo_set <= 1'b 0;
    else if (sys_csb_deasserted_pulse_i && csb_cmdfifo_set) begin
      sys_cmdfifo_set <= 1'b 1;
    end else begin
      sys_cmdfifo_set <= 1'b 0;
    end
  end

```
![Screen Shot 2022-10-25 at 11 55 42 AM](https://user-images.githubusercontent.com/49293026/197858395-1549988c-2d1c-42b3-92c9-a46101edc48f.png)

waves:
/mnt/disks/filestores/opentitan-shared/users/weicai/scratch/min_idle/spi_device-sim-vcs/failed/1.spi_device_flash_and_tpm_min_idle.3189529232

LMK what you think. I'm fine to tag this one to M3

cc: @tjaychen

**Comment by weicaiyang** [comment]
Another related issue:

After SW updates addr4b to 1, this update could be cleared if the next transaction is a dummy item.
In this case, the dummy item has one spi_clk cycle which isn't enough to sync up the SW programmed value to the final `spi_cfg_addr_4b_en_o`, as `spi_csb_asserted_pulse_i` remains 0.

```
  always_ff @(posedge spi_clk_i or negedge sys_rst_ni) begin
    if (!sys_rst_ni) begin
      spi_cfg_addr_4b_en_o <= 1'b 0;
    end else if (spi_addr_4b_set_i) begin
      // This event occurs when EN4B command is received
      spi_cfg_addr_4b_en_o <= 1'b 1;
    end else if (spi_addr_4b_clr_i) begin
      // EX4B command raises the clear event
      spi_cfg_addr_4b_en_o <= 1'b 0;
    end else if (spi_csb_asserted_pulse_i & !addr_4b_en_locked &
                 addr_4b_en_sw_update_condition) begin
      // Update
      spi_cfg_addr_4b_en_o <= spi_reg_cfg_addr_4b_en_sync;
    end
  end
```

However, `sys_csb_deasserted_pulse_i` is set after CSR is released, so this clears the `reg2hw_cfg_addr_4b_en_q_i` flag and this CSR update is wiped completely.
```
  always_ff @(posedge sys_clk_i or negedge sys_rst_ni) begin
    if (!sys_rst_ni) begin
      hw2reg_cfg_addr_4b_en_de_o <= 1'b 0;
      hw2reg_cfg_addr_4b_en_d_o  <= 1'b 0;
    end else if (sys_csb_deasserted_pulse_i
      && (sys_cfg_addr_4b_en_sync != reg2hw_cfg_addr_4b_en_q_i)) begin
      // update!
      hw2reg_cfg_addr_4b_en_de_o <= 1'b 1;
      hw2reg_cfg_addr_4b_en_d_o  <= sys_cfg_addr_4b_en_sync;
    end else begin
      // Keep value 0 otherwise
      hw2reg_cfg_addr_4b_en_de_o <= 1'b 0;
      hw2reg_cfg_addr_4b_en_d_o  <= 1'b 0;
    end
  end
```

Looks like if we want to test flash mode with dummy items, we need to enforce a minimum spi_clk cycles. 

Waves:
/mnt/disks/filestores/opentitan-shared/users/weicai/scratch/min_idle/spi_device-sim-vcs/failed/3.spi_device_flash_and_tpm_min_idle.555308691

**Comment by weicaiyang** [comment]
Changed this to M3 and constrain sequence not to issue these dummy req for now

**Comment by jeoongp** [comment]
Sorry for late reply. I will take a look

**Comment by weicaiyang** [comment]
> Sorry for late reply. I will take a look

Thanks @jeoongp

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP1 because we need to check with the product team if this could be a problem.  If so, we need to fix this with high prio.

**Comment by andreaskurth** [comment]
There are two parts to this issue:

- A spurious CSb due to reset has to be prevented with a pull-up on the CSb wire on the PCB. No changes to `spi_device` are necessary in this regard. The PCB reference design guidelines need to include this pull up and specify a resistor value range that achieves the desired pull-up strength.
- It may be possible that CSb is active for less than 3 SCK cycles. `spi_device` has to behave in a well-defined way in this case. We have to remove the constraint that prevents this from happening in DV (see https://github.com/lowRISC/opentitan/commit/27a5beeb0622e0f1a5353bc3f426ef3a938f5337) and figure out what exactly happens in such cases and what may fail.

Keeping this as https://github.com/lowRISC/opentitan/labels/Priority%3AP1.

**Comment by hcallahan-lowrisc** [comment]
> * It may be possible that CSb is active for less than 3 SCK cycles. `spi_device` has to behave in a well-defined way in this case. We have to remove the constraint that prevents this from happening in DV (see [27a5bee](https://github.com/lowRISC/opentitan/commit/27a5beeb0622e0f1a5353bc3f426ef3a938f5337)) and figure out what exactly happens in such cases and what may fail.

While product team feedback is that this situation is unlikely due to external pullups on CSB, we should still amend the testbench to remove this restriction, and check that block returns to a usable state and record any interrupts generated or other side-effects.

> estimate 8
> remaining 2023-03-22 8

**Comment by hcallahan-lowrisc** [comment]
Note that there is a number of open issues about CSB behaviour and robustness to errors, so some estimated effort (if deemed necessary) may overlap between those issues. (https://github.com/lowRISC/opentitan/issues/10058 https://github.com/lowRISC/opentitan/issues/12747 https://github.com/lowRISC/opentitan/issues/15517 https://github.com/lowRISC/opentitan/issues/15721)

**Comment by moidx** [comment]
Hi @johngt, I believe this issue was left as P1 to scope a directed test case to ensure we can recover from an invalid scenario: e.g. remove 3SCK constraint and determine if we can recover in this case. 

Given where we are at wrt M2.5.1 I believe we can live without this test and rely on system level constraints. 

CC: @msfschaffner wdyt?

**Comment by moidx** [comment]
Discussed with @msfschaffner offline. Ok to move to M2.5.1 as this falls into the protocol checker category. No expected RTL changes.

**Comment by johngt** [comment]
Think you mean 2.5.2 - @moidx ?

**Comment by moidx** [comment]
Hi @hcallahan-lowrisc, are you planning to take a look at this as part of V2.5 sign-off, or is this falling into negative testing (lower priority). Thanks

**Comment by hcallahan-lowrisc** [comment]
Hey @moidx , work on this is issue is my main priority at the moment. Thanks

**Comment by moidx** [comment]
Triaged as part of M2.5.2 sign-off and decided to move to V3 to focus on coverage improvements.
