### ISSUE TITLE
[csrng] Extra cover plan work (if cover level <90%)

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15747]
CSRNG - If major issues encountered (e.g. needing new tests and coverpoints, in turn having a knock on effect on regression pass rate)

> original estimate 12
> estimate 16
> remaining 2022-11-15 12
> remaining 2022-11-16 8

**Comment by GregAC** [comment]
@ctopal is adding some further coverage, please update the remaining and estimate once you have a clear idea of the effort needed here.

**Comment by vogelpi** [comment]
I've now assigned @andreaskurth to this issue as he is doing a large chunk of work to bring FSM coverage up. This requires extending the DV infrastructure and thus best suits here. We need to test the disable/re-enable feature to hit all the transitions from any states into the Idle states of practically all FSM. Without this we can't get FSM coverage much beyond 60% (see #15743 for some more details). I think this is one of the most important tasks for reaching V2S.

**Comment by andreaskurth** [comment]
> original estimate 12
> estimate 16
> remaining 2022-11-15 12

**Comment by andreaskurth** [comment]
> remaining 2022-11-16 8

**Comment by andreaskurth** [comment]
I've created a separate issue for testing disable & re-enable: https://github.com/lowRISC/opentitan/issues/16430. I'll track the effort for that test there. I think there shouldn't be other work left here, but I'll leave it to @vogelpi to judge that and the estimated efforts.

**Comment by vogelpi** [comment]
Sounds good, let's close this then.
