### ISSUE TITLE
[csrng] New test cases (if cover level <90%)

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15746]
CSRNG - If major issues encountered (e.g. needing new tests and coverpoints, in turn having a knock on effect on regression pass rate)

>estimate 2
>original estimate 20

**Comment by GregAC** [comment]
From discussions and review believe no new test cases are required

**Comment by GregAC** [comment]
@marnovandermaas to comment once he's done some further review

**Comment by marnovandermaas** [comment]
I've made some changes to the test plan and coverage plan. I don't think they require any major changes or effort. The updated test plan as I see it is tracked in this PR: https://github.com/lowRISC/opentitan/pull/16116

**Comment by vogelpi** [comment]
Let's close this. All additional work has been done. The biggest item disable/re-enable testing was covered by a seperate issue.
