### ISSUE TITLE
[csrng] Err_test_cg implementation

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15742]
Coverage implementation needs to be finished
Err_test_cg implementation

>estimate 8
>remaining 2022-11-10 4
>remaining 2022-11-10 2

**Comment by andreaskurth** [comment]
Summarizing the discussion just held:

It's hard to get coverage with backdoor accesses because sampling happens in scoreboard on TL interface, but backdoor accesses don't go through TL interface. Sampling on alert or in vseq could be an alternative.

Impl of CG currently ready, sampling WIP.
