### ISSUE TITLE
[csrng] Regression fixing (if cover level <90%)

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15748]
If major issues encountered (e.g. needing new tests and coverpoints, in turn having a knock on effect on regression pass rate)

>estimate 8
>remaining 2022-11-14 4
>remaining 2022-11-15 2

**Comment by ctopal** [comment]
From 10th of November onwards almost all `csrng_cmds` tests fail with a mismatch between scoreboard prediction and actual generated bits. Needs further investigating.

**Comment by vogelpi** [comment]
This has top priority. I've now assigned @marnovandermaas , are you happy to take this one?

**Comment by marnovandermaas** [comment]
> From 10th of November onwards almost all `csrng_cmds` tests fail with a mismatch between scoreboard prediction and actual generated bits. Needs further investigating.

This specific comment has now been fixed with: https://github.com/lowRISC/opentitan/pull/16322

Next step is to check coverage level.

> spent 4
> remaining 2022-11-14 4

**Comment by vogelpi** [comment]
Nice work @marnovandermaas , now we should check the impact of this fix on coverage. I'll kick off a coverage in about 30min.

**Comment by marnovandermaas** [comment]
> Nice work @marnovandermaas , now we should check the impact of this fix on coverage. I'll kick off a coverage in about 30min.

I've started running one locally, but it's taking a while.

**Comment by vogelpi** [comment]
@andreaskurth was faster and posted the results in the coverage issue already: https://github.com/lowRISC/opentitan/issues/15743#issuecomment-1314097805

**Comment by marnovandermaas** [comment]
OK, shall we close this issue since the remaining coverage work is tracked in https://github.com/lowRISC/opentitan/issues/15743?

**Comment by vogelpi** [comment]
I've fixed the csrng_err and csrng_intr tests. With PR #16382 the pass rate should now be nearly 100%.

**Comment by marnovandermaas** [comment]
I think this work has been completed.
