### ISSUE TITLE
[chip-test] chip_lc_test_locked

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#15763]
### Test point name

[chip_lc_test_locked](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/data/chip_testplan.hjson;l=3124?q=chip_rv_dm_lc_disabled&ss=opentitan%2Fopentitan:hw%2F)

### Host side component

SystemVerilog

### Contact person

@msfschaffner 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by weicaiyang** [comment]
Create an issue for this test since it's not done in the chip_testplan.

@msfschaffner perhaps this test can be fully covered by `chip_rv_dm_lc_disabled`, which you added recently.
If so, we can just link this to that test.

**Comment by tjaychen** [comment]
Yeah this does feel like it's already been covered. Should we just remove it from the testplan? I'm not even sure how it's different right now. We probably added this to the testplan based on the manufacturing review, but I think this the spirit is already covered.

**Comment by msfschaffner** [comment]
Thanks for filing this @weicaiyang.
It looks like there are two aspects here: 1) availability of the RV_DM and 2) performing a transition from TEST_UNLOCKED to TEST_LOCKED. Both should be covered by `chip_sw_lc_walkthrough_testunlocks` and `chip_rv_dm_lc_disabled`.

The difference with other testpoints is really just that this ties 1) and 2) above together in one test point.
I am fine with removing, but xref would work as well in case we want to keep it for the manufacturing test plan.

**Comment by weicaiyang** [comment]
Thanks @tjaychen @msfschaffner.
Either removing it or linking those 2 tests LGTM

**Comment by msfschaffner** [comment]
let's just X'ref it then. that way we keep it around as "added documentation" for the manufacturing test plan.

**Comment by tjaychen** [comment]
yeah sounds good, i can x-ref it .

**Comment by msfschaffner** [comment]
Sorry about that :) saw your last msg too late.

**Comment by tjaychen** [comment]
no worries! thanks for submitting.
