### ISSUE TITLE
[chip-test] chip_sw_ast_sys_clk_jitter

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#15762]
### Test point name

[chip_sw_ast_sys_clk_jitter](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/data/chip_testplan.hjson?q=chip_sw_ast_sys_clk_jitter&ss=opentitan%2Fopentitan:hw%2F)

### Contact person

@tjaychen

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by weicaiyang** [comment]
Looks like we haven't filed an issue for this test. @tjaychen could you tag a priority for this?

**Comment by tjaychen** [comment]
hmmm... i believe this test is about verifying AST's jitter clock is actually fetching entropy and varying its frequency as expected.
So this would make it more of a closed source test than an open source test.

@sha-ron 
@msfschaffner 
can you guys confirm if this is what you remember?

**Comment by tjaychen** [comment]
actually this was added a long time ago, I think the spirit of this test may have already been satisfied by the clkmgr_jitter test, so maybe this is something we can remove. 

@sha-ron i think it's probably a valid question on how you guys want to verify the jitter is doing what it's supposed to on the closed source side thoughg.

**Comment by sha-ron** [comment]
Looks like clkmgr_jitter covers what it should in the open source and we will check the rest of the functionality in the closed source side so I think it can be closed.

**Comment by tjaychen** [comment]
sounds good. thanks Sha-ron.
@weicaiyang i'll remove this from the testplan and then we can close this issue.
