### ISSUE TITLE
[chip-test] chip_sw_alert_handler_lpg_sleep_mode_alerts

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#15764]
### Test point name

[chip_sw_alert_handler_lpg_sleep_mode_alerts](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/chip_testplan.hjson#L1486)

### OpenTitanTool infrastructure implemented

Yes

### Contact person

@cindychip

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by johngt** [comment]
@bilgiday - just a quick check to see how the work is going on writing this test?

**Comment by bilgiday** [comment]
@johngt This is a work in progress. I plan to submit an initial PR today to get initial feedbacks.

**Comment by bilgiday** [comment]
@johngt, @johannheyszl Finalizing a PR for this one.

**Comment by msfschaffner** [comment]
This has been implemented in https://github.com/lowRISC/opentitan/pull/16404. 
We are waiting for this to pass in the nightlies now.

**Comment by bilgiday** [comment]
Hi All, good news, the test passed the latest nightlies :) 

As I forget to add it into the chip_testplan.hjson yesterday, the result is shown under `unmapped tests`. @sriyerg just updated the hjson file with #16474. If it is okay for you, we can close the issue.

**Comment by msfschaffner** [comment]
Thanks for checking - in that case this is ok to close.

**Comment by bilgiday** [comment]
Thanks @msfschaffner
