### ISSUE TITLE
[flash_ctrl] Usability improvements

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15783]
- [x] The attributes for hardware access to creator/owner seed pages is different from software access. This does not really make sense since if the two sides do not agree, the contents in there would always be non-sense. We should consider streamlining this #16799
- [ ] The info pages currently do not have a "Default" config the way data pages do.  This may not make sense and deserves a second look.
- [x] The status register does not indicate when flash is actually initialized, just whether its busy. This means it is possible for software to interpret something that has never initialized with something that has finished initializing.  #16795

**Comment by tjaychen** [comment]
@jadephilipoom

**Comment by tjaychen** [comment]
Assign this to M3 for now...but it could just as likely be backlog...

**Comment by tjaychen** [comment]
The last remaining item (default for info) will be pushed to backlog and it is not a critical feature to add now. 
The other usability improvements may have real short term benefits and are added.

**Comment by msfschaffner** [comment]
@moidx @timothytrippel @cfrantz we need to double check whether we want this supported in ROM for PROD.

**Comment by timothytrippel** [comment]
by "this" do you mean having a default config for the info pages? If so, I think the reset defaults are fine, probably would just complicate setup if there was also a separate default config.

**Comment by moidx** [comment]
We should perform some testing as this may impact the attestation flow. I assume we can ensure the info page settings can be verified and lockdown before we crank the `keymgr`. If this is sufficient, then there is no need for hardware changes. 

@timothytrippel, should we put this in the `ROM_EXT` task list, or is it ok to just mark as obsolete?

**Comment by timothytrippel** [comment]
Yes I think we can make sure the info oages are locked down accordingly. Since this is already tracked in [#19593](https://github.com/lowRISC/opentitan/issues/19593), I think we can mark this obsolete and close.
