### ISSUE TITLE
[edn] sync edn/csrng/entropy_src disablement

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#15789]
If disable EDN in the `boot_req_mode` during EDN sending `GEN_BITS` command to CSRNG, if CSRNG is not being disabled in the same time, it will still keep this request.
Then when we enabled the EDN, EDN might receive CSRNG responses and store them in the FIFO, even though EDN did not requested it.
This might mis-align the EDN requests/FSMs.

For M2, we think the solution could be to request EDN/CSRGN/ENTROPY_SRC disablement to happen at the same time. But for future release, we might want to enhance this behavior.

@tjaychen @moidx 

![image](https://user-images.githubusercontent.com/11466553/198381163-40821a11-a4bf-44dc-9889-6e7c43bb2ee3.png)

Thanks
Cindy

**Comment by cindychip** [comment]
> My assumption for this shut down feature is that all 3 entropy blocks are disabled, as in three register writes are issued, one per block. It is not clear which order is best, but perhaps edn, csrng, then es. Is this the current sequence for all testing?

@tjaychen do you happen to know the chip level order?
Yeah that is the current assumption, but we just filing this issue in case other public user might not connect it to CSRNG :)

**Comment by tjaychen** [comment]
in our test code right now, we currently disable edn0/edn1/csrng/entropy_src in that order.

**Comment by vogelpi** [comment]
During the work for V2 and V2S @andreaskurth has updated the documentation of all three blocks to document how the disable/re-enable sequence is supposed to work.

In addition, issues to verify the disable/re-enable feature for EDN #16429 and entropy_src #16431 for V3 have been filed. For CSRNG, the feature has already been verified as part of V2/V2S (see #16430). I am thus closing the issue but feel free to re-open if you think we should do something in addition.
