### ISSUE TITLE
[chip-test] update chip_rv_dm_ndm_reset_req

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15795]
### Test point name

[chip_rv_dm_ndm_reset_req](https://github.com/lowRISC/opentitan/blob/b2df3d8c348364ae829b63f80a5a1b3e7ec5ba5c/hw/top_earlgrey/data/chip_testplan.hjson#L573)

### Host side component

SystemVerilog

### Contact person

@tjaychen, @msf, @jeoongp

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [ ] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

Update test based on updated testplan.

**Comment by msfschaffner** [comment]
This should be fixed after #15317, #15494, #15759 and #15624 have been addressed (all related to reset reorg).

**Comment by johngt** [comment]
https://github.com/lowRISC/opentitan/issues/15494 is the final item needing closing out.

**Comment by tjaychen** [comment]
yeah @msfschaffner and i each have PRs open that are fixing a part of this picture.
I'm hoping today we will be able to combine them.

**Comment by tjaychen** [comment]
@msfschaffner i changed the assignment for this for the time being.  Since this is related to the possible issue in rv_dm.
