### ISSUE TITLE
[chip-test] chip_rv_dm_access_after_hw_reset

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15796]
### Test point name

[chip_rv_dm_access_after_hw_reset](https://github.com/lowRISC/opentitan/blob/b2df3d8c348364ae829b63f80a5a1b3e7ec5ba5c/hw/top_earlgrey/data/chip_testplan.hjson#L640)

### Contact person

@tjaychen, @msf, @jeoongp

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by sriyerg** [comment]
Looks like this test is already developed: https://github.com/lowRISC/opentitan/pull/15725

**Comment by sriyerg** [comment]
I am sorry I got confused by the title of PR #15725, which actually addresses #14152. Reassigning it back to myself.

**Comment by sriyerg** [comment]
Test development is now complete. Waves with JTAG DMI accesses before and after escalation reset:

![image](https://user-images.githubusercontent.com/46467186/202075986-392ad8d3-024d-47c9-8e74-656200e4f500.png)

I am running the CSR RW test on the DMI register space via JTAG on a loop. I have reused the SW test from `chip_sw_alert_handler_escalation` test for this test.
