### ISSUE TITLE
[keymgr] Should we latch sideload_sel_err

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#15862]
@tjaychen 
Current DUT only latches the error at the last cycle of the operation when done is set. If the error occurs like a glitch and disappears before the last cycle, it won't be caught.
Should we latch the error once it occurs?
![Screen Shot 2022-10-31 at 5 15 18 PM](https://user-images.githubusercontent.com/49293026/199132378-27c19693-55be-4701-aff7-b5eba28ccb7f.png)

Waves:
/mnt/disks/filestores/opentitan-shared/users/weicai/scratch/t1/keymgr-sim-vcs/failed/0.keymgr_custom_cm.3753542906

**Comment by tjaychen** [comment]
If i remember right, i think this one is particular was meant to capture the moment the sideload key is actually updated.
So when we go through the key process and at the end we will update one of the key slots, at that moment, sideload_sel is also captured. So if you try to look at it prior, during normal operation, i think sideload_sel does not match dest_sel until the very end.  Can you confirm that's the case?

**Comment by weicaiyang** [comment]
> If i remember right, i think this one is particular was meant to capture the moment the sideload key is actually updated.
So when we go through the key process and at the end we will update one of the key slots, at that moment, sideload_sel is also captured. 

that's true, the sideload_sel is only used at the last cycle when `done` is set.

> So if you try to look at it prior, during normal operation, i think sideload_sel does not match dest_sel until the very end. Can you confirm that's the case?

These 2 signals are created with the same condition, so they're identical in this case until I force one of them.
![Screen Shot 2022-10-31 at 9 48 07 PM](https://user-images.githubusercontent.com/49293026/199161189-15b8af2c-330f-4a5e-96e3-49077f735a4e.png)

**Comment by tjaychen** [comment]
let me have a look at what i was intending to do here... something is weird.

**Comment by weicaiyang** [comment]
fixed via #15904
