### ISSUE TITLE
[test ROM] Dont configure the pinmux to connect the UART pins for DV

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#15889]
The test ROM currently programs the pinmux to connect IOC3 and 4 to the UART peripheral. It also enables a weak pull up on the RX port. 

https://github.com/lowRISC/opentitan/blob/8aff88ccc12afd90179361987c611f07409e8410/sw/device/lib/testing/pinmux_testutils.c#L49

For DV, we dont use UART for logging, so this is not needed. We end up consuming IOs for peripherals that are unused for 99% of the tests. Moreover, it interferes with the sleep tests that verify pinmux wake up / retention functionality (requires additional workarounds). Filing an issue to see if anyone has any objections to removing this code in `pinmux_testutils::pinmux_testutils_init()`.

**Comment by a-will** [comment]
For what it's worth, I'd disagree with that change (though the RX pin arguably ought to go away). Ultimately, the chip's ROM is going to connect this pin and use, so I think it should be considered reserved even in the DV environment. Am I missing an important use case?

**Comment by sriyerg** [comment]
> , I'd disagree with that change (though the RX pin arguably ought to go away). Ultimately, the chip's ROM is going to connect this pin and use, so I think it should be considered reserved even in the DV environment. Am I missing an important use case?

Sure, the ROM will connect and use these pins. But the tests that use ROM are also limited. For the tests that use the test ROM (which is almost all tests), these IOs get reserved but they are completely unused in DV (note that logging in DV uses a different mechanism). 

There are a few pinmux / sleep related tests that require all MIOs to be usable for the tests' intent. The tests in https://github.com/lowRISC/opentitan/issues/15680 for instance, are failing because of this issue and they require a slightly complicated workaround.

**Comment by a-will** [comment]
That issue is about IOC3, which is the RX pin, and I'd agree with that one being eliminated. Neither ROM uses UART RX. (The DIF should also get updated to allow selectively enabling TX and RX independently. :) )

Is there a particular issue with keeping the TX pin?

**Comment by sriyerg** [comment]
> That issue is about IOC3, which is the RX pin, and I'd agree with that one being eliminated. Neither ROM uses UART RX. (The DIF should also get updated to allow selectively enabling TX and RX independently. :) )
> 
> Is there a particular issue with keeping the TX pin?

Right - the issue is only with the UART RX port on IOC3. I am fine with leaving the TX (IOC4) as is.

**Comment by GregAC** [comment]
P2 as resolution of this issue may be required to fix some failing tests

**Comment by moidx** [comment]
Closing as we are planning to maintain the UART pin mapping for this release across boot stages.
