### ISSUE TITLE
[RDC] Check if CSb can be related to any generated clocks from SCK

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#15886]
`SPI_DEV_{IN/OUT}_CLK` are generated clocks from `SPI_DEV_CLK`. Somehow, RDC tool reports `E_RST_METASTABILITY` for the path from flops resetting by CSb to the flops in the same clock category (`SPI_DEV*CLK`).

- [ ] Contact the tool vendor if the setup is wrong (sdc, env)

CC: @tjaychen @jeoongp 

> estimate 4
> remaining 2023-03-22 4

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2.

**Comment by hcallahan-lowrisc** [comment]
> estimate 4
> remaining 2023-03-22 4

**Comment by johngt** [comment]
@cindychip - this is tagged as an RDC potential tooling error. Please suggest who might be able to look into this. TIA

**Comment by a-will** [comment]
Agreed that it's a tool limitation. Our timing constraints should be set up so CSB is never permitted to change near either SPI_DEV_CLK edge--The two are not active at the same time (not for modes we support).

**Comment by msfschaffner** [comment]
@moidx I think we can lower the priority on this one and defer it to M2.5.2.

**Comment by andreaskurth** [comment]
Confirmed again with @a-will that CSB can never change near either SPI_DEV_CLK edge, so suggest to move this to Backlog

**Comment by a-will** [comment]
It looks like I may have been more restrictive than the typical SPI flash datasheet. I'll post a PR that creates a reset synchronized for outclk domain usage. Then we might only need an exception for the reset assertion.

**Comment by andreaskurth** [comment]
Closing as completed in #23244
