### ISSUE TITLE
[chip-test] chip_sw_adc_ctrl_debug_cable_irq

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#15906]
### Test point name

chip_sw_adc_ctrl_debug_cable_irq

### Host side component

SystemVerilog

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by tjaychen** [comment]
doesn't this test already exist?
https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/dv/chip_sim_cfg.hjson;l=854-859?q=chip_sim_cfg.hjson&ss=opentitan%2Fopentitan

**Comment by tjaychen** [comment]
gah, this might have been my mistake. I i think i enhanced one of the tests to support irq and forgot to update all the relevant notes.

**Comment by sriyerg** [comment]
Aah, someone pointed out in the last DV meeting that this was undeveloped and untracked, so I created this issue. I looked at the C test and it adequately covers the IRQ path to PLIC.
