### ISSUE TITLE
[chip-test] chip_sw_flash_rma_unlocked

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15911]
### Test point name

[chip_sw_flash_rma_unlocked](https://github.com/lowRISC/opentitan/blob/f3e95c6d0bc66483c94bc07fed6aab8b9d38b25c/hw/top_earlgrey/data/chip_testplan.hjson#L2703)

### Host side component

SystemVerilog

### Contact person

@tjaychen, @cindychip

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

This test requires a minor update based on the manufacturing testplan sync.
The test needs to initiate an ID check from the host side.

**Comment by johngt** [comment]
Unassigning @engdoreis for now as he is OoO. If this is not picked up, I'll reassign to him on his return next week.

**Comment by msfschaffner** [comment]
The update for this is coming in #16456.

**Comment by msfschaffner** [comment]
The updates to this test have now been merged - let's check the nightlies tomorrow!

**Comment by msfschaffner** [comment]
This has passed in the nightlies - closing!
