### ISSUE TITLE
[CI] Update OpenOCD to version 0.12 in CI containers

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15921]
Per November 1 meeting notes in CI sync call;
Need to build OpenOCD 0.12.0-rc1 with Bazel: https://github.com/lowRISC/opentitan/pull/15853

Ref: https://openocd.org/pages/getting-openocd.html
Uses GPL v2.0 (see https://sourceforge.net/p/openocd/code/ci/master/tree/LICENSES/license-rules.txt)

@dmcardle  is working on building OpenOCD in such a way that it works with the environment there. Once completed Dan should ping @jprendes  to ensure that the repository is linked to the container and that the updated version of OpenOCD is used within CI.

This issue is for tracking the upgrade in the containers.

**Comment by dmcardle** [comment]
I think the only relevant container is the one that's used for running FPGA tests, right?

Once we merge #15853, nothing should be using the system's OpenOCD, so maybe you should just delete it from the container(s) entirely. WDYT, @jprendes?

**Comment by arunthomas** [comment]
@jprendes @dmcardle Can we got ahead and close this issue now?

**Comment by dmcardle** [comment]
I think we can close this. As of #15853, all tests defined with `opentitan_gdb_fpga_cw310_test()` are using the Bazel-built OpenOCD.

@jprendes You could delete OpenOCD from the container if you're so inclined.

**Comment by arunthomas** [comment]
Thanks, @dmcardle. Closing the issue.
