### ISSUE TITLE
[test-triage] chip_sw_clkmgr_sleep_frequency

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#15956]
### Hierarchy of regression failure

Chip Level

### Failure Description

Job chip_earlgrey_asic-sim-vcs_run_default killed due to: Exit reason: Pod abruptly killed. Check resource usage. has 3 failures:

Test chip_sw_clkmgr_sleep_frequency has 1 failures.

1.chip_sw_clkmgr_sleep_frequency.1597657190
Log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/1.chip_sw_clkmgr_sleep_frequency/latest/run.log

  Job ID: smart:2092502e-2dbb-4959-a141-06b637d2dd6d
Test chip_sw_sleep_pwm_pulses has 1 failures.

2.chip_sw_sleep_pwm_pulses.2205643193
Log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/2.chip_sw_sleep_pwm_pulses/latest/run.log

  Job ID: smart:8ab5652a-4ad7-4f1d-88c7-a74a0b9dc174
Test rom_e2e_shutdown_exception_c has 1 failures.

2.rom_e2e_shutdown_exception_c.3618016909
Log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/2.rom_e2e_shutdown_exception_c/latest/run.log

  Job ID: smart:c1b08fa3-c15f-40f5-8023-7bfcc5c39695

### Steps to Reproduce

- GitHub Revision: [e1671fddf](https://github.com/lowrisc/opentitan/tree/e1671fddf58976e5e11db41cd51fa17de54dea14)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_clkmgr_sleep_frequency --build-seed 600742595 --fixed-seed 1597657190 --waves fsdb

### Tests with similar or related failures

- [x] xbar_chip_stress_all_with_error
- [x] chip_sw_sleep_pwm_pulses
- [ ] rom_e2e_shutdown_exception_c see #15238
- [x] xbar_chip_access_same_device_slow_rsp

**Comment by msfschaffner** [comment]
CC @tjaychen @timothytrippel 

Is this maybe infrastructure related and intermittent?

**Comment by sriyerg** [comment]
Let me dig a little deeper, since we have their job IDs.

**Comment by sriyerg** [comment]
These are likely happening because we recently set the cpu/ram/disk settings globally for all jobs to higher values. I will followup internally to pinpoint which resource exceeded our project-wide limits. Looks like we will need dvsim to support per-test cpu/ram/disk requirements asap.

**Comment by timothytrippel** [comment]
Just a heads up, I took a look at `rom_e2e_shutdown_exception_c`, this is failing for other reasons too (it is not configured correct hehe, it need its own sequence which I am currently developing).

**Comment by sriyerg** [comment]
The job got killed because the machine running the job unexpectedly shut down. 
Except `rom_e2e_shutdown_exception_c`, others are now passing. This is indeed a transient issue and we can perhaps close it?

**Comment by msfschaffner** [comment]
We already have an open issue for #15238, so I think it is ok to close, since the other tests have been passing in the nightlies as you mentioned:
```
|     | Tests                           |   2022-11-06 07:11:02 |   2022-11-05 07:11:23 |   2022-11-04 07:12:05 |   2022-11-03 07:11:23 |   2022-11-02 07:03:26 |   2022-11-01 07:10:18 |   2022-10-31 07:08:35 |   2022-10-30 07:09:58 |   2022-10-29 07:10:41 | Suite           |
|----:|:--------------------------------|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|:----------------|
| 241 | xbar_chip_stress_all_with_error |                   100 |                   100 |                   100 |                   100 |                    99 |                   100 |                   100 |                   100 |                   100 | xbar_stress_all |

|     | Tests                    |   2022-11-06 07:11:02 |   2022-11-05 07:11:23 |   2022-11-04 07:12:05 |   2022-11-03 07:11:23 |   2022-11-02 07:03:26 |   2022-11-01 07:10:18 |   2022-10-31 07:08:35 |   2022-10-30 07:09:58 |   2022-10-29 07:10:41 | Suite                    |
|----:|:-------------------------|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|:-------------------------|
| 172 | chip_sw_sleep_pwm_pulses |                   100 |                   100 |                   100 |                   100 |                 66.67 |                   100 |                     0 |                     0 |                     0 | chip_sw_sleep_pwm_pulses |

|     | Tests                                 |   2022-11-06 07:11:02 |   2022-11-05 07:11:23 |   2022-11-04 07:12:05 |   2022-11-03 07:11:23 |   2022-11-02 07:03:26 |   2022-11-01 07:10:18 |   2022-10-31 07:08:35 |   2022-10-30 07:09:58 |   2022-10-29 07:10:41 | Suite                       |
|----:|:--------------------------------------|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|:----------------------------|
| 228 | xbar_chip_access_same_device_slow_rsp |                   100 |                   100 |                   100 |                   100 |                    98 |                   100 |                   100 |                   100 |                   100 | xbar_all_access_same_device |
```
