### ISSUE TITLE
[lc_ctrl] Life cycle controller status is not `ready` when in invalid or scrap state

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#15963]
This was discovered by @dkabely-ot in https://github.com/lowRISC/opentitan/pull/15938.

SW and JTAG sequences rely on the READY bit in the status register to determine whether the life cycle controller is ready to perform a transaction (via polling):

https://github.com/lowRISC/opentitan/blob/b77dc2319ba57106c7617b7931326088405e951e/hw/ip/lc_ctrl/data/lc_ctrl.hjson#L504-L509

For cases where we connect via JTAG, this is also used to check whether the life cycle controller has actually initialized and the state exposed is valid (we have no other way of knowing whether OTP and LC have booted or not from outside if the chip is otherwise unresponsive).

Since the READY bit is connected to the idle indication of the life cycle controller FSM, the bit will not be set to 1 whenever the life cycle controller detects an `InvalidSt` , e.g. if the OTP state is corrupted, or when it is in `ScrapSt`.

I wonder whether we should change this so that the READY bit indicates whether the life cycle controller has initialized, instead of whether it is idle. That would make status readout more reliable in cases where the life cycle state is SCRAP or invalid. This would also be more true to the description of the READY bit, see linked hjson snippet above.

**Comment by msfschaffner** [comment]
Ah shoot, you are right - @alphan's mechanism is relying on that one. The READY would stay high as you said.

Unfortunately we can't use the TRANSITION_REGWEN to read IDLE status, since that one is only connected to the idle indication once the mutex is claimed (and we do not want to snatch away the mutex from the JTAG side in the RMA case).

So if we would like to add both notions, this would need another status bit in the CSR...
Let me take a quickly check how complex the DV side update would be for this (design is trivial).
I believe this would be very useful for some top-level tests and manufacturing scenarios.

**Comment by msfschaffner** [comment]
The change is straightforward, I have added it in a second commit to https://github.com/lowRISC/opentitan/pull/15962 so you can take a look.

**Comment by alphan** [comment]
> Ah shoot, you are right - @alphan's mechanism is relying on that one. The READY would stay high as you said.
> 
> Unfortunately we can't use the TRANSITION_REGWEN to read IDLE status, since that one is only connected to the idle indication once the mutex is claimed (and we do not want to snatch away the mutex from the JTAG side in the RMA case).
> 
> So if we would like to add both notions, this would need another status bit in the CSR... Let me take a quickly check how complex the DV side update would be for this (design is trivial). I believe this would be very useful for some top-level tests and manufacturing scenarios.

commented on the PR, thanks for mentioning me @msfschaffner And @tjaychen!

**Comment by msfschaffner** [comment]
This is now fixed in https://github.com/lowRISC/opentitan/pull/15962 - closing!
