### ISSUE TITLE
[edn] data stable during edn disablement

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#16000]
Hey Tim and Mark,

Looks like there is some violation to the data stable assertion:
```
    `ASSERT(EdnDataStable_A, edn_o[i].edn_ack |=>
            $stable(edn_o[i].edn_bus) throughout edn_i[i].edn_req[->1])
```

Looking at the waves, edn_0 finished four requests and was disabled.
Then after enablement, the data line went to 0.

To reproduce:
 ../../../../util/dvsim/dvsim.py edn_sim_cfg.hjson -i edn_disable --reseed 1 --seeds 2889220990 

![image](https://user-images.githubusercontent.com/11466553/199860113-b13649cf-c252-46e3-acaa-f8ef6896734f.png)

Zoomed in the assertion violation point:
![image](https://user-images.githubusercontent.com/11466553/199860572-c15bc32d-0f01-4b8c-b1ee-479c19773fe1.png)

Thanks,
Cindy

**Comment by moidx** [comment]
CC @martin-lueker, @mwbranstad

**Comment by tjaychen** [comment]
hmm...shoot this probably is related to my change, it cleans on enable.. although i assume there shouldn't be an ack at that time.. i'll have to have a look.

**Comment by tjaychen** [comment]
okay thinking about this a bit more, i think i should move this assertion over to `prim_edn_req`. I can then narrow down the stable period from "forever" until next request to when module actually completes the handshake.  

That would get around this issue.

**Comment by cindychip** [comment]
> okay thinking about this a bit more, i think i should move this assertion over to `prim_edn_req`. I can then narrow down the stable period from "forever" until next request to when module actually completes the handshake.
> 
> That would get around this issue.

Yeah that should work. I can make a PR to move it over.
I guess in block level, I will try it change it to stable until next req or next enable? Does that sound reasonable?

**Comment by tjaychen** [comment]
actually cindy, could we change it to `throughout edn_req[->1] | enable[->1]`? assuming that means transition to positive edge?
would that solve this issue?

**Comment by cindychip** [comment]
Thanks!
I had a similar idea. I break it into two assertions.
Because enable is one when the assertion starts, so putting it in one assertion might be hard. Because we only want to disable it when: enable = 1 -> 0 -> 1
```
    `ASSERT(EdnDataStable_A, $rose(edn_o[i].edn_ack) |=>
            $stable(edn_o[i].edn_bus) throughout edn_i[i].edn_req[->1],
            clk_i, !rst_ni || !u_edn_core.edn_enable_q)

    `ASSERT(EdnDataStableDisable_A, u_edn_core.edn_enable_q == 0 |=> $stable(edn_o[i].edn_bus))
```

**Comment by tjaychen** [comment]
that looks good to me i think. But if you write those, i think you can keep them in `edn` right? although having the data stable until ack in `prim_edn_req` also seems good.

**Comment by cindychip** [comment]
> that looks good to me i think. But if you write those, i think you can keep them in `edn` right? although having the data stable until ack in `prim_edn_req` also seems good.

Yeah! Putting them in EDN will be super helpful for block level checks! I will leave them in EDN. And adding one for prim_edn_req :)
