### ISSUE TITLE
[chip dv] [cov] Improve chip_sw_rom_ctrl_integrity_check test

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#16013]
This test is supposed to verify that the chip is able to boot up with a ROM image that has bad integrity in non-PROD LC state, and is unable to boot up in PROD LC state. 

In the second phase of the test (post-reset), the test waits for 1ms before calling it a test-pass. As it turns out, that wait is insufficient - the rom check is still ongoing. The test has not progressed to the point where the rom check is completed. See waves below:

![image](https://user-images.githubusercontent.com/46467186/199899906-47a7b646-56bf-436f-a418-586cb5683b52.png)

We need to wait for the pwrmgr fast FSM to be in active power and then start our CPU-does-not-boot timer.

**Comment by tjaychen** [comment]
o wow good catch. 
Let me add the chip test label to this one.

What priority do you think this should be?
