### ISSUE TITLE
[test] Handle constants in ROM e2e tests in a platform agnostic way.

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#16016]
nit: Is there a way we can encode this in ms or us and convert to cycles based on the target (sim, fpga, silicon)?

_Originally posted by @moidx in https://github.com/lowRISC/opentitan/pull/16007#discussion_r1014095993_

**Comment by msfschaffner** [comment]
CC @cfrantz @timothytrippel

**Comment by timothytrippel** [comment]
This should be handled by the new Bazel test rules. Mobing to said project as these will refactored as part of the rule transition I believe.
