### ISSUE TITLE
SPI (seemingly broken) on Verilator at head

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#1606]
It appears that SPI does not work correctly under Verilator at head. Starting the Verilator model without a flash binary, and trying to use spiflash to flash a new binary does not work, and gets checksum errors on the device side.

I can reproduce this at head by running my recently (last week) build of the Verilator model. Has anyone else seen this issue?

**Comment by eunchan** [comment]
Did we have a way to run spiflash on verilator simulation model? I thought `spiflash` is only for the FPGA?

**Comment by eunchan** [comment]
OK. I ran with `--verilator=/dev/pts/N` option. Seeing the same issue. I will dump the waveform if I can find any clue.

**Comment by silvestrst** [comment]
@mcy just in case this might help with your investigation. Recently changes have been submitted that allow GDB debugging on verilator with minimal performance overhead (It used to be veeeeery slow, and now its n times faster).

**Comment by silvestrst** [comment]
@mcy I haven't tried reproducing the issue myself, but @eunchan has already confirmed it.

**Comment by eunchan** [comment]
Hum.. I've moved the repo back to 11 days ago, still spiflash is failing. Maybe I should dump the trace and analyze the waveform, which is really slow...

**Comment by eunchan** [comment]
Wait... my procedure may be wrong... 
After compiling the verilator I've ran with below command. Is this correct?

```console
$ build/lowrisc_systems_top_earlgrey_verilator_0.1/sim-verilator/Vtop_earlgrey_verilator \
  --meminit=rom,build-bin/sw/device/boot_rom/boot_rom_sim_verilator.elf \
  --meminit=flash,build-bin/sw/device/examples/hello_world/hello_world_sim_verilator.elf
```

Or, should I omit the flash memory load?

```console
$ ./build-bin/sw/host/spiflash/spiflash --input build-out/sw/sim-verilator/sw/device/examples/hello_world/hello_world.bin --verilator=/dev/pts/9
```

**Comment by mcy** [comment]
I've been omitting the flash part.

**Comment by eunchan** [comment]
![Screenshot from 2020-02-25 14-25-11](https://user-images.githubusercontent.com/1192814/75293403-f1d55b00-57da-11ea-890b-b83f02c8a9cd.png)

OK. :) Now I exactly reproduce. I will keep track which commit it begins failed.

**Comment by eunchan** [comment]
@mcy with the fix suggested in #1620, spiflash resends frame 0 if the hash is not matched. I can see it downloads the whole frame after the first frame is failed (hash mismatch). Still need to figure out why the first frame hash is not matched always.

**Comment by eunchan** [comment]
![Screenshot from 2020-02-25 14-49-53](https://user-images.githubusercontent.com/1192814/75294791-21d22d80-57de-11ea-9523-99eca118abaa.png)

**Comment by silvestrst** [comment]
Ping, has this been resolved and ready to be closed?

**Comment by mcy** [comment]
Yeah, this has been fixed for a while.
