### ISSUE TITLE
[entropy_src] Close coverage

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#16064]
Close coverage
- [ ] Improve functional coverage first, then toggle coverage.
- [ ] Confirm refine files.
- [ ] Review functional coverage code for holes.

>original estimate 20
>estimate 12
>remaining 2022-11-14 2

**Comment by andreaskurth** [comment]
> original estimate 20
> estimate 12
> remaining 2022-11-14 2

**Comment by andreaskurth** [comment]
What is left of this issue is already tracked in #16063; I'm thus closing this issue.
