### ISSUE TITLE
JTAG regression: "The target is either really slow or broken. "

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#16067]
CC: @a-will @alphan @arunthomas

Last week, I observed an issue with JTAG-based ROM e2e tests like [:sram_program_fpga_cw310_test_otp_dev](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom/e2e/BUILD;l=1475;drc=968977a1defaf3af826c5d71889f57be69061d61). OpenOCD connects, but when it tries to service the commands issued by GDB, it eventually prints out this fascinating error message:

> [OPENOCD] Error: DMI operation didn't complete in 2 seconds. The target is either really slow or broken. You could increase the timeout with riscv set_command_timeout_sec.

I've verified locally that the test **reliably fails on 2d3aa1765af8141675d8f3aee3b3a691d1a0db02** (PR #15602), but reliably succeeds on the parent commit, f3da3f66ef03e2485f51e7626d5dc46a93273ac5.

N.B.: 

* It seems like the FPGA needs to be power cycled after this failure or else subsequent tests will fail. I spent a few hours running an automated git bisect, but I think the results were garbage because of this.

* If anyone is trying to repro this themselves, you should patch this into your tree first. The test coordinator script has a bug that I will document and fix separately.

  ```diff
  diff --git a/rules/scripts/gdb_test_coordinator.py b/rules/scripts/gdb_test_coordinator.py
  index f02ace2c9..04bbe8f54 100644
  --- a/rules/scripts/gdb_test_coordinator.py
  +++ b/rules/scripts/gdb_test_coordinator.py
  @@ -149,7 +149,7 @@ def main(rom_kind: str = typer.Option(...),
       # to avoid a subtle race condition.
       background = BackgroundProcessGroup()
       openocd = background.run(openocd_command, "OPENOCD", COLOR_PURPLE)
  -    background.block_until_line_contains(openocd, "starting gdb server")
  +    #background.block_until_line_contains(openocd, "starting gdb server")
  ```

## Full output on 2d3aa1765af8141675d8f3aee3b3a691d1a0db02

```console
% ./bazelisk.sh test --define bitstream=vivado --test_output=streamed --cache_test_results=no //sw/device/silicon_creator/rom/e2e:sram_program_fpga_cw310_test_otp_dev
INFO: Invocation ID: 7f19afc9-68a3-4257-997d-bbbefe00e71c
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
INFO: Analyzed target //sw/device/silicon_creator/rom/e2e:sram_program_fpga_cw310_test_otp_dev (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
++ rules/scripts/gdb_test_coordinator --gdb-script-path=sw/device/silicon_creator/rom/e2e/sram_program_fpga_cw310_test_otp_dev.gdb --openocd-earlgrey-config=util/openocd/target/lowrisc-earlgrey.cfg --bitstream-path=sw/device/silicon_creator/rom/e2e/rom_otp_dev_exec_disabled.bit --rom-kind=Rom --opentitantool-path=sw/host/opentitantool/opentitantool '--exit-success-pattern=sram_program\.c:\d+\] PC: 0x100020e0, SRAM: \[0x10000000, 0x10020000\)'
[2022-11-07T16:25:23Z INFO  opentitantool::command::load_bitstream] Loading bitstream: "sw/device/silicon_creator/rom/e2e/rom_otp_dev_exec_disabled.bit"
[2022-11-07T16:25:23Z INFO  opentitanlib::util::usr_access] Bitstream file USR_ACCESS value: 0x50c29ba
[2022-11-07T16:25:25Z INFO  opentitanlib::util::rom_detect] Did not detect the ROM identification message.
[2022-11-07T16:25:25Z INFO  opentitanlib::transport::cw310] Programming the FPGA bitstream.
[2022-11-07T16:25:39Z INFO  opentitantool] Command result: success.
[OPENOCD] Open On-Chip Debugger 0.12.0-rc1
[OPENOCD] Licensed under GNU GPL v2
[GDB] /tools/riscv/bin/riscv32-unknown-elf-gdb: warning: Couldn't determine a path for the index cache directory.
[OPENOCD] For bug reports, read
[OPENOCD]       http://openocd.org/doc/doxygen/bugs.html
[OPENOCD] trst_and_srst separate srst_gates_jtag trst_push_pull srst_open_drain connect_deassert_srst
[OPENOCD]
[OPENOCD] Info : Hardware thread awareness created
[OPENOCD] Warn : `riscv set_prefer_sba` is deprecated. Please use `riscv set_mem_access` instead.
[OPENOCD] force hard breakpoints
[OPENOCD] Info : Listening on port 6666 for tcl connections
[OPENOCD] Info : Listening on port 4444 for telnet connections
[OPENOCD] Info : RCLK (adaptive clock speed)
[OPENOCD] Info : JTAG tap: riscv.tap tap/device found: 0x04f5484d (mfg: 0x426 (Google Inc), part: 0x4f54, ver: 0x0)
[CONSOLE] Starting interactive console
[OPENOCD] Info : datacount=2 progbufsize=8
[OPENOCD] Info : Examined RISC-V core; found 1 harts
[OPENOCD] Info :  hart 0: XLEN=32, misa=0x40901104
[OPENOCD] Info : starting gdb server for riscv.tap.0 on 3333
[OPENOCD] Info : Listening on port 3333 for gdb connections
[OPENOCD] Info : accepting 'gdb' connection on tcp/3333
[GDB] warning: No executable has been specified and target does not support
[GDB] determining executable automatically.  Try using the "file" command.
[GDB] 0x000081b8 in ?? ()
[OPENOCD] Error: JTAG scan chain interrogation failed: all ones
[OPENOCD] Error: Check JTAG interface, timings, target power, etc.
[GDB] :::: Send OpenOCD the 'reset halt' command.
[OPENOCD] Error: Trying to use configured scan chain anyway...
[GDB] JTAG scan chain interrogation failed: all ones
[OPENOCD] Warn : Bypassing JTAG setup events due to errors
[OPENOCD] Error: DMI operation didn't complete in 2 seconds. The target is either really slow or broken. You could increase the timeout with riscv set_command_timeout_sec.
[GDB] Check JTAG interface, timings, target power, etc.
[GDB] Trying to use configured scan chain anyway...
[GDB] Bypassing JTAG setup events due to errors
[GDB] DMI operation didn't complete in 2 seconds. The target is either really slow or broken. You could increase the timeout with riscv set_command_timeout_sec.
[CONSOLE] [CTRL+C] to exit.
[CONSOLE]
[CONSOLE]
[CONSOLE]
[CONSOLE] Exiting interactive console.
[CONSOLE] [2022-11-07T16:25:44Z INFO  opentitantool] Command result: Console timeout exceeded
CONSOLE exited with code 1
```

**Comment by dmcardle** [comment]
cc @jeoongp @msfschaffner

**Comment by tjaychen** [comment]
should be addressed by 
#15998 
#16012

**Comment by alphan** [comment]
> should be addressed by #15998 #16012

Thanks @tjaychen !

**Comment by dmcardle** [comment]
Yes, thank you @tjaychen! Closing this now.

**Comment by tjaychen** [comment]
wait, i thought the issue wasn't fixed yet? didn't we discover yesterday that there were still problems?

**Comment by dmcardle** [comment]
Update on this: I merged #15713 yesterday, which uses CI to help us keep an eye on potential flakiness of JTAG tests. The  tests passed on that PR, but later I saw 2/3 of the tests [fail](https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=101775&view=logs&j=421a2038-410f-5c10-767f-4482292362ca&t=fe805732-5e37-5249-8636-c69eaa5ddf8e&l=83955) on #16226.

Note that the tests are failing differently than the original "target is either really slow or broken" error. Instead, we're seeing `[OPENOCD] Error: timed out while waiting for target halted`. Perhaps we should merge #16179 first, before we think about this too hard.

**Comment by tjaychen** [comment]
sounds good to me!

**Comment by tjaychen** [comment]
@dmcardle / @alphan are we okay to move this to M3?
I think we've figured out there is no immediate breakage after the adapter delay, the rest I'm hoping is something we can clean up but doesn't have to be M2 blocking.

let me know what you think.

**Comment by dmcardle** [comment]
I think we can close this issue!

I checked the last ~15 CI runs since on master since merging #16179, none of them failed because of "Experimental CW310 JTAG Jobs".

@tjaychen I'm not actually sure what's left to clean up, but I'll move this issue to M3 and let you either close it or file a followup issue :)

**Comment by tjaychen** [comment]
@a-will has pointed out that the constraints for JTAG don't look great on fpga (and quite possibly asic), so that is still something to clean up.  Let me file that as a separate issue though since I don't want to hijack this one.

Then let's close this!
