### ISSUE TITLE
[mubi/lc] Switch to rectifying AND/OR functions for safety?

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#16075]
See https://github.com/lowRISC/opentitan/pull/15998#discussion_r1015769157 for context.

CC @tjaychen

**Comment by msfschaffner** [comment]
I am not sure we will be able to do this everywhere, and will likely have to evaluate this on a case-by-case basis.

Related issue for MUBIs commit out of CSRs: #9273

**Comment by msfschaffner** [comment]
As mentioned above, I believe we should handle this on a case-by-case basis.
Specifically, in some cases it may be desirable to have non-rectifying behavior since we do not want to mask errors on the signals.
The rectifying primitives are also more complex in terms of gates.

I am hence closing this issue.

@vogelpi @johannheyszl

**Comment by vogelpi** [comment]
Handling on a case-by-case basis sounds good to me. Specifically for CSRs, we could extend the `regtool` to optionally automatically sanitize the software input. I think this would acutally be valuable. I'll make a proposal in #9273.
