### ISSUE TITLE
[csrng] Formal / Jasper Gold

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#16112]
For V2S - need to improve coverage level from ~44% currently.

**Comment by vogelpi** [comment]
We discussed that maybe @andreaskurth could have a look at that. Because he already solved these issues for entropy_src and we expect the problems inside CSRNG are of very similar nature.

**Comment by andreaskurth** [comment]
Current status:

CEX:
- `gen_cnt_asserts[0].FpvSecCmDrbgCmdFsmCheck_A`
- `gen_cnt_asserts[1].FpvSecCmDrbgCmdFsmCheck_A`
- `gen_cnt_asserts[2].FpvSecCmDrbgCmdFsmCheck_A`
- `FpvSecCmCtrlMainFsmCheck_A`
- `FpvSecCmDrbgGenFsmCheck_A`
- `gen_aes_cipher_control_fsm_svas[0].gen_aes_cipher_control_fsm_svas_p.FpvSecCmAesCipherControlFsmCheck_A`
- `gen_aes_cipher_control_fsm_svas[1].gen_aes_cipher_control_fsm_svas_p.FpvSecCmAesCipherControlFsmCheck_A`
- `gen_aes_cipher_control_fsm_svas[2].gen_aes_cipher_control_fsm_svas_n.FpvSecCmAesCipherControlFsmCheck_A`

Unreachable:
- `FpvSecCmDrbgUpdBlkEncFsmCheck_A:precondition1`
- `FpvSecCmDrbgUpdOutBlkFsmCheck_A:precondition1`

**Comment by cindychip** [comment]
> Current status:
> 
> CEX:
> 
> * `gen_cnt_asserts[0].FpvSecCmDrbgCmdFsmCheck_A`
> * `gen_cnt_asserts[1].FpvSecCmDrbgCmdFsmCheck_A`
> * `gen_cnt_asserts[2].FpvSecCmDrbgCmdFsmCheck_A`
> * `FpvSecCmCtrlMainFsmCheck_A`
> * `FpvSecCmDrbgGenFsmCheck_A`
> * `gen_aes_cipher_control_fsm_svas[0].gen_aes_cipher_control_fsm_svas_p.FpvSecCmAesCipherControlFsmCheck_A`
> * `gen_aes_cipher_control_fsm_svas[1].gen_aes_cipher_control_fsm_svas_p.FpvSecCmAesCipherControlFsmCheck_A`
> * `gen_aes_cipher_control_fsm_svas[2].gen_aes_cipher_control_fsm_svas_n.FpvSecCmAesCipherControlFsmCheck_A`
> 
> Unreachable:
> 
> * `FpvSecCmDrbgUpdBlkEncFsmCheck_A:precondition1`
> * `FpvSecCmDrbgUpdOutBlkFsmCheck_A:precondition1`

Unreachables could be we did not add the `stopat` path. Please feel free to ping me on slack if you have any other questions. https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/formal/top_earlgrey_fpv_sec_cm_cfgs.hjson#L67

**Comment by andreaskurth** [comment]
> estimate 2
> remaining 2022-11-11 0
