### ISSUE TITLE
[entropy_src] Formal / Jasper Gold

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#16113]
Per other V2S tasks we will likely need Formal methods applied to entropy_src.

>estimate 4

**Comment by andreaskurth** [comment]
55/57 `entropy_src_sec_cm` assertions are currently proven, the following two are cex:
- `FpvSecCmCtrlMainFsmCheck_A`
- `FpvSecCmCtrlAckFsmCheck_A`

I'll investigate
