### ISSUE TITLE
[rv_core_ibex, fpv] Write assertion to check side loaded scramble key is correctly used

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#16117]
I think we need two assertions

1. Ensure that when a `FENCE.I` is executed we eventually (for simplicity this can probably be bounded to within a few cycles) see a request for a new scramble key at the rv_core_ibex top level if a request isn't already on going.
2. Ensure that when a scramble key is received at the rv_core_ibex top level it is correctly applied to the icache scrambled memory primitive.

**Comment by andreaskurth** [comment]
@johngt
> estimate 2
> remaining 2022-11-09 1

**Comment by johngt** [comment]
Thanks @andreaskurth - will need @GregAC to edit the issue as I don't have rights to edit others' issues.
