### ISSUE TITLE
[rv_core_ibex, fpv] Write assertions to check connection between OT side alert and various errors in Ibex

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#16118]
Various errors within ibex result in alerts being signaled at the `rv_core_ibex` top-level. This functionality is checked within the Ibex DV environment which doesn't include the `rv_core_ibex` outer wrapper. Write assertions to ensure that errors signaled from Ibex do result in the correct alerts.

**Comment by GregAC** [comment]
This is addressed by https://github.com/lowRISC/opentitan/pull/16156

**Comment by msfschaffner** [comment]
Looks like the associated PR has been merged, so I am closing this.
Please reopen if there is still some work pending.
