### ISSUE TITLE
[edn/doc] EDN generate_cmd description out of date?

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#16129]
Hey Mark and Tim,

I wonder if I misunderstand this part of the description in `generate_cmd`: https://docs.opentitan.org/hw/ip/edn/doc/index.html#Reg_reseed_cmd
"On overflow this FIFO pops the oldest word from the previous command. Updated commands can be inserted by pushing 13 command words into the FIFO, pushing the previous command out."

From what I understand, the FIFO depth is 13, and I thought by pushing more than 13 command, it will automatically pop out from the front of the queue.

But from the waves, seems like directly pushing 14 items will immediately trigger a fatal alert.
Is this part of the doc out of date or am I totally misunderstand it :)

![image](https://user-images.githubusercontent.com/11466553/200651231-c75a5505-61dd-4dee-90af-146ab01f315d.png)

**Comment by mwbranstad** [comment]
@cindychip i believe the intent of the text was to say when setting up the FIFO, a SW command write could write up to 13 words for a complete command. However, it is possible (but very unlikely) that if that same SW "changed it's mind", it could write another 13 words and push out the original command. When in operation mode, yes, the original command will recycle back into the same FIFO while the command is going out on the wire. To avoid confusion, perhaps the On overflow statement just be removed.

**Comment by tjaychen** [comment]
hmmmm... i think even if software pushes another 13 words right now, even if we are not in operational mode, wouldn't we still trigger an alert? @cindychip let me know if i'm reading this wrong.

**Comment by cindychip** [comment]
> hmmmm... i think even if software pushes another 13 words right now, even if we are not in operational mode, wouldn't we still trigger an alert? @cindychip let me know if i'm reading this wrong.

Sorry for the confusion, correct! Right now what I see is that:
If I just directly write 14 items to the FIFO (not in operation mode), it will trigger an alert :)

**Comment by tjaychen** [comment]
@mwbranstad looking at the rtl, i don't really see the "push-out" mechanism that was described. 
If that's really the case, should we drop this feature description from the text in this version??

**Comment by mwbranstad** [comment]
the push out behavior was originally that way it worked. i suspect the alert feature came later.
So let's document that. It simple, straight forward, and the alert makes sense in this case.

**Comment by tjaychen** [comment]
sounds good, should we remove the push-out feature description for now? I can file an issue for M3 and later to put this back in to coordinate alongside the alerts.

**Comment by cindychip** [comment]
Thanks great, thank you both!!

**Comment by mwbranstad** [comment]
yes, remove it completely.
