### ISSUE TITLE
[test-triage] Nightly runner issue with Xcelium licenses - e.g. AES

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#16124]
### Hierarchy of regression failure

Block level

### Failure Description

```
User terminated with CTRL-C has 1582 failures:
Test aes_wake_up has 1 failures.

0.aes_wake_up.2856553756
Log /container/opentitan-public/scratch/os_regression/aes_no_masking-sim-xcelium/0.aes_wake_up/latest/run.log
Test aes_nist_vectors has 1 failures.

0.aes_nist_vectors.2509222213
Log /container/opentitan-public/scratch/os_regression/aes_no_masking-sim-xcelium/0.aes_nist_vectors/latest/run.log
Test aes_smoke has 50 failures.

0.aes_smoke.2838674301
Log /container/opentitan-public/scratch/os_regression/aes_no_masking-sim-xcelium/0.aes_smoke/latest/run.log

1.aes_smoke.2512093669
Log /container/opentitan-public/scratch/os_regression/aes_no_masking-sim-xcelium/1.aes_smoke/latest/run.log

... and 48 more failures.

Test aes_config_error has 50 failures.

0.aes_config_error.56508644
Log /container/opentitan-public/scratch/os_regression/aes_no_masking-sim-xcelium/0.aes_config_error/latest/run.log

1.aes_config_error.1234882530
Log /container/opentitan-public/scratch/os_regression/aes_no_masking-sim-xcelium/1.aes_config_error/latest/run.log

... and 48 more failures.

Test aes_stress has 50 failures.

0.aes_stress.2213201232
Log /container/opentitan-public/scratch/os_regression/aes_no_masking-sim-xcelium/0.aes_stress/latest/run.log

1.aes_stress.3632151079
Log /container/opentitan-public/scratch/os_regression/aes_no_masking-sim-xcelium/1.aes_stress/latest/run.log

... and 48 more failures.

... and 25 more tests.

Job killed most likely because its dependent job failed. has 2 failures:
Test aes has 2 failures.
cov_merge
Log /container/opentitan-public/scratch/os_regression/aes_no_masking-sim-xcelium/cov_merge/merged/cov_merge.log

cov_report
Log /container/opentitan-public/scratch/os_regression/aes_no_masking-sim-xcelium/cov_report/cov_report.log
```

### Steps to Reproduce

- GitHub Revision: [a029fa5c6](https://github.com/lowrisc/opentitan/tree/a029fa5c6c48ddb5e23d473c793f1f279a943fe9)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i TEST_NAME --build-seed 710490551 --fixed-seed FAILING_SEED --waves fsdb

### Tests with similar or related failures

- [ ] All tests fail in the nightly report.

See - https://reports.opentitan.org/hw/ip/aes_no_masking/dv/latest/report.html on Nov 7
Monday November 07 2022 08:08:10 UTC

**Comment by johngt** [comment]
Pass rate was fairly high the night before - see https://reports.opentitan.org/hw/ip/aes_no_masking/dv/2022.11.07_03.35.37/report.html
This report then showed all 0s across the board.

**Comment by sriyerg** [comment]
The nightly regression runner killed all jobs after hitting the 24 hour limit. Investigating now why this happened.

**Comment by msfschaffner** [comment]
I assigned this to you @sriyerg for now (just so that the status is clear on the dashboard). Feel free to change that if needed.

**Comment by sriyerg** [comment]
This has been fixed for now.   I will closely monitor the performance in subsequent days and reopen if needed.
