### ISSUE TITLE
[entropy_src] Support for Different Bypass window sizes in M2

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#16146]
Looking at the last few coverpoints for `entropy_src` has revealed a (potentially unimportant) gap in the specification and documentation that bears some discussion for M2.

Currently the `entropy_src` when in bypass modes (e.g. Boot) implicitly only supports one window size.  This is not explicit in the documentation.  The register `HEALTH_TEST_WINDOWS.BYPASS_WINDOW` says that the default is 384, the seed size.   There is no mention however as to what precisely happens if some other value is chosen.

There is no obvious reason to support windows other than 384.  However we should decide how to handle this register in M2.

Options as I see them include: 
1. Update Documentation, DV and RTL to support some reasonable behavior.  (Likely 2 weeks minimum of discussion and review)
2. Document the register as supporting only one value, and waive any related auto generated coverpoints (e.g. `Lockable_field_cov_of_entropy_src_reg_block.health_test_windows.bypass_windows`).  Inform users that changing this value will lead to unexpected results.
3. Same as 2, but Hardcode the window size internally to prevent unexpected behavior

**Comment by johngt** [comment]
@tjaychen or @moidx - final decision on which approach(es) to go with?

**Comment by moidx** [comment]
I recall discussing the boot window size of 384 to optimize boot time. Overall, I prefer option 2. to leave the register in case we need to revisit this during M2.

**Comment by martin-lueker** [comment]
Thanks @tjaychen @moidx, By 3 I was thinking of leaving the register but just rendering it toothless in HW.
It really is a matter of priority, and goals for the ES chip.   Changing this register has unpredictable consequences.  If that is Okay, then 2 is fine.

**Comment by tjaychen** [comment]
sounds good to me. @martin-lueker since we've agreed on a resolution, are you okay with lowering the priority of this issue to P1/P2?

**Comment by johngt** [comment]
@martin-lueker - I think that based on @tjaychen and @moidx responses that just option 2 is the decision. I think you are working on documenting cases so I'll leave the assignment with just you and leave it as an M2 task but with a P1 priority.

**Comment by martin-lueker** [comment]
Acknowledged.  I'll put a doc & waiver PR together.

**Comment by johngt** [comment]
To close out V2S we will need this issue and the related https://github.com/lowRISC/opentitan/issues/11315 closed out @martin-lueker . Thanks for all the help so far. Just need these two and then we will be soon able to close out V2 and then V2S

**Comment by johngt** [comment]
@vogelpi highlighted that for V2 closeout we only need to root-cause the issue, which seems to be the case.
Given that the remaining task here is documentation related (window size is not going to be hard-coded) then I'm happy for it to go down to P2 and for it to be discussed in the V2S meeting as a post V2 task.

**Comment by tjaychen** [comment]
yeah i agree, let's do that.

**Comment by tjaychen** [comment]
@martin-lueker / @moidx do we have to have the option be configurable? Because I'm not entirely certain we even need to revisit this for M3 now.

**Comment by martin-lueker** [comment]
> @martin-lueker / @moidx do we have to have the option be configurable? Because I'm not entirely certain we even need to revisit this for M3 now.

That is the question, and if no, then the only thing to do is to reconfigure the register so that the module doesn't break (or breaks in predictable ways) if someone tries to change the config

**Comment by tjaychen** [comment]
so i think if 384 is the thing we have decided to stick with, then it probably needs to go into the software guidance.
We can probably add input checks on the dif side as well. 

I feel like the boot mode entropy especially, is going to be more or less hardwired by ROM, so there's not really a case where someone else is going to change it imo.

**Comment by moidx** [comment]
I prefer if we use wording that doesn't make this a transient issue. Agreed we can add checks to the dif and software implementation guidelines.

**Comment by msfschaffner** [comment]
I have added this to the `entropy_src` documentation here: https://github.com/lowRISC/opentitan/pull/16450.

**Comment by vogelpi** [comment]
Thanks @msfschaffner for taking care of this!
