### ISSUE TITLE
[i2c_device] i2c_stretch_timeout would be useful in device mode as well

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#16160]
i2c_stretch_timeout is described as host only, but would allow a device's i2c block to monitor it's code for a fault where it's the one performing the stretch. Setting a short timeout could even serve as a acq_full interrupt in this case mooting some of the problems in https://github.com/lowRISC/opentitan/issues/15226

**Comment by drewmacrae** [comment]
This is a nice-to-have, but could also be used in lieu of a acq_fifo_full event by setting the timeout very short and servicing the interrupt.

**Comment by jesultra** [comment]
This would allow detection of bugs in the firmware running on OpenTitan.  It is not a feature that we were looking for for TI50, but it would be nice to have.  I do not think it should be a priority.

**Comment by msfschaffner** [comment]
Discussed with @jesultra. Not needed for M2.5, hence deferring.

**Comment by msfschaffner** [comment]
This is nice to have and not a required feature.
Given our current priorities, I am closing this as not planned. 
Please reopen if you disagree.

CC @GregAC @moidx
