### ISSUE TITLE
[rdc] Option to dump waveform for all violations

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#16178]
RDC tool may dump waveforms for violations if a few config variables are set to true.

However, dumping waveforms at every run wastes resources.

This ticket is to track the enhancement of dvsim RDC flow:

- Give option to add waveform when dvsim is called.
- revise `run-rdc.tcl` to set the config variables when the given option is set.
-

**Comment by tjaychen** [comment]
@eunchan was this one resolved already?
if not, do we want to consider its completion for m3?

**Comment by eunchan** [comment]
Done. Let me close this.
