### ISSUE TITLE
[i2c] i2c_monitor overrides its super's run_phase

### ISSUE THREAD

**Issue by yehuda-bejar** [lowRISC/opentitan#16207]
The I2C Monitor (class i2c_monitor) extends the DV Base Monitoer (class dv_base_monitor).
However, the implementation of its run_phase, does not call super.run_phase() anywhere,
thus completely overriding the DV-Base implementation.

In addition to not complying with OT and UVM methodology, this is problematic in:
1. normal use, as i2c_monitor will not, automatically, get upgrades implemented in dv_base_monitor.
2. during debug, as i2c_monitor's run phase behaves differently than other UVM components.

Note: this may also be the case for some other IP's monitors...

**Comment by tjaychen** [comment]
@sriyerg 
@weicaiyang 
@cindychip

**Comment by tjaychen** [comment]
@yehuda-bejar is this actively blocking you right now? If not, I am inclined to bump this to after M2.

**Comment by sriyerg** [comment]
I think it is ok for the downstream agent monitors to not have to call `super.run_phase(phase)`, given the `dv_base_monitor::run_phase` could be restrictive (it only forks off 1 thread).  

I would actually propose `dv_base_monitor::run_phase()` to immediately throw a fatal error and force the actual agent monitors to implement the monitoring logic. The more important pieces are `watchdog_ready_to_end()` and the TLM ports, which the extended monitors will continue to benefit from. 

I will let others chime in as well.

**Comment by weicaiyang** [comment]
> I think it is ok for the downstream agent monitors to not have to call super.run_phase(phase), given the dv_base_monitor::run_phase could be restrictive (it only forks off 1 thread).

Agree. dv_base_monitor::run_phase doesn't contain any really useful function for extended monitors. We probably don't need to mandate how the extended monitors use it.

**Comment by jdonjdon** [comment]
@yehuda-bejar Do you have any further comment? or can we close this issue?

**Comment by johngt** [comment]
@marnovandermaas - can you check if this will need to be asked at next week I2C meeting?
If we don't need this we can lower priority down accordingly.
