### ISSUE TITLE
[csrng] csrng_internal_cg implementation

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/opentitan#16201]
Based on the changes to the test plan proposed in: https://github.com/lowRISC/opentitan/pull/16116

We need an extra cover group to create coverage on the internal state of the CSRNG block.

Old estimate before 2022-11-11 8
> estimate 16
> remaining 2022-11-11 8
> remaining 2022-11-12 2

**Comment by marnovandermaas** [comment]
I've added an initial implementation on the internal cover group, but am struggling with how to implement the sampling.

> spent 8
> remaining 2022-11-11

**Comment by vogelpi** [comment]
genbits (can see that from toggle coverage), genbits_v, sw_cmd_status, intr_state, intr_en - to sample on every clock edge, Andreas shared an example

**Comment by marnovandermaas** [comment]
We decided this issue can be roped into https://github.com/lowRISC/opentitan/issues/15742
I opened a draft PR (very incomplete) as a reference for what I did so far: https://github.com/lowRISC/opentitan/pull/16254

**Comment by vogelpi** [comment]
Thanks @marnovandermaas , this is helpful. I am un-assigning you for the moment to let you work on the V2S task as just discussed.

**Comment by ctopal** [comment]
Okay, I think I'll just use the scoreboard more effectively to sample interrupt related covergroups that gets generated from `cip_base_env_cov`. For other coverpoints, I believe adding them to err_cg would be sufficient.

**Comment by ctopal** [comment]
List of things written down in https://github.com/lowRISC/opentitan/pull/16116:
- [ ] genbits has had each bit set and unset at least once
  - We talked about this saying it'll show up in Toggle Coverage numbers (hence no need for FCOV implementation for V2) 
- [ ] genbits_vld has seen all 4 possibilities
  - We did not specified this one but this is also an I/O signal and can be observed through Toggle Coverage.
- [ ] sw_cmd_sts has seen all 4 possibilities
  - Added coverpoints in #16261
- [ ] regwen has been true and false
  - Added coverpoints in #16261 
- [ ] intr_state has had each bit set and unset at least once
  - Used existing intr_state/intr_enable functional coverage framework by doing some plumbing in the scoreboard in #16261
