### ISSUE TITLE
[keymgr] LC disable happens at the 1st advance

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#16234]
When LC disable happens at the 1st advance, the operation completes successfully. I expect op_status to fail because any other operation will fail if LC disable happens in the middle of the operation.

However, we wipe keys and move the state to StInvalid after that. So it's just a small inconsistency.
I'm fine to keep it as is if it's not easy to fix. I can update scb to align with it.

Wave session can be restored as follows

> cd /mnt/disks/filestores/opentitan-shared/users/weicai/scratch/t1/keymgr-sim-vcs/23.keymgr_lc_disable/latest && verdi -ssr Verdi.ses &

**Comment by tjaychen** [comment]
this is fixed in #16248
