### ISSUE TITLE
[CDC] Remove top specific config from `run-cdc-tcl`

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#16242]
[Current `run-cdc.tcl`](https://cs.opensource.google/opentitan/opentitan/+/2b989a42bad3aff373e024ce841b406eec1b3970:hw/cdc/tools/verixcdc/run-cdc.tcl;l=112-120;bpv=1;bpt=0) has **top_earlgrey** specific configs. It The part is better to be placed under `hw/top_earlgrey/cdc/` and source from `run-cdc.tcl` depending on the target top.

CC: @jeoongp @tjaychen @msfschaffner @eunchan

**Comment by moidx** [comment]
Moving to M5 as this is a cleanup item. @andreaskurth, maybe this is something we can consider moving to the backlog?
