### ISSUE TITLE
[edn/dv] V2S TODOs

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#16268]
- [x] [Steve]: Could you help check with Mark and see if we can unify the `local_escalate_i` and `edn_enable_i` at the end of the state machine case statement.

- [x] [Cindy]: Add assertions to check if local escalation can trigger fatal alerts. Currently file an issue

- [x]  [Cindy] Increase the length of genbits request. (Current max is 16/4?) 
https://github.com/lowRISC/opentitan/pull/16297

- [x] [Cindy] Randomly drives max_reqs_after_reseed when not in auto_req_mode.

**Comment by senelson7** [comment]
I checked with Mark, and we think we used to have it that way but changed it for some reason. Anyways, we can't think of any reason the local_escalate_i -> Error, edn_enable_i -> Idle can't be done outside of the State/case statement.

**Comment by cindychip** [comment]
> I checked with Mark, and we think we used to have it that way but changed it for some reason. Anyways, we can't think of any reason the local_escalate_i -> Error, edn_enable_i -> Idle can't be done outside of the State/case statement.

That is awesome, thank you Steve and Mark for confirming that. Do you want our side to make a PR for that, or do you want to do it. Either way is fine for me :)

**Comment by cindychip** [comment]
All items are done, just wait for coverage to reach 90%.
