### ISSUE TITLE
[rstmgr] Clarify reset_info bits

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#16281]
The documentation is pretty vague about most of the reset_info bits. This is an important CSR, so more clarity would be desirable, both about the meaning of each bit, and about their side-effects. Examples of side-effects is whether various resets clear captures, and whether they clear either capture enable bits.

Some possible changes involve moving all must-have bits to lower bit positions, thus being more vague about a smaller subset.

**Comment by matutem** [comment]
This could be moved to M3? Setting priority high just to decide if and how we intend to deal with this.

**Comment by tjaychen** [comment]
i'll have a quick look to see if there's something i can do, but unfortunately i think there might not be enough time before m2.
can you elaborate a bit on what you think makes sense? The power glitch and other hardware resets actually behave similarly..so is it mainly ndm reset that's a bit different?

**Comment by tjaychen** [comment]
okay, #16303 i think spiritually addresses the issue here, let me know.
It's mostly a documentation and enum update to better enable DV, so there's no "real" design change.
