### ISSUE TITLE
[csrng] Fix FIFO error testing

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/opentitan#16326]
Currently it is unclear whether the FIFO error tests are forcing a bit in the error code register instead of setting the FIFOs to full/empty/illegal and checking whether the error propagates correctly.

Besides this we need an assert that makes sure that if one of the SFIFO bits in the error code are set (15-0) that also one of the FIFO error types are set (30-28). Additionally, we need a cross between SFIFO errors and the FIFO error types.

- [x] Check FIFO error tests are working properly
- [x] Create assert (see discussion below)
- [x] Create cross

>estimate 6
>remaining 2022-11-17 2

**Comment by vogelpi** [comment]
This is currently being worked on by @ctopal.

**Comment by ctopal** [comment]
Currently working on implementing the coverage implementation part of this task.

**Comment by ctopal** [comment]
Opened up https://github.com/lowRISC/opentitan/pull/16426 for this task. 

> if one of the SFIFO bits in the error code are set (15-0) that also one of the FIFO error types are set (30-28).
I think illegal bins in the cross should be enough for this, WDYT @marnovandermaas?

**Comment by marnovandermaas** [comment]
> Opened up #16426 for this task.
> 
> > if one of the SFIFO bits in the error code are set (15-0) that also one of the FIFO error types are set (30-28).
> 
> I think illegal bins in the cross should be enough for this, WDYT @marnovandermaas?

Yes, I think we can check that task off as well and close this issue.
