### ISSUE TITLE
[i2c] Agent setup time check

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#16349]
@a-will pointed out a scenario in the current i2c stretch fixes that should have caused a setup violation.
The case is specifically when the device goes from address stretching into transmit directly.  We need to investigate a bit why the setup time violation wasn't caught.

The agent added an oversampling around the setup window to handle this, and it did catch some errors, so I don't know why this one was missed.

Filing as something to investigate.

**Comment by jdonjdon** [comment]
This has been added since #16304
