### ISSUE TITLE
[test] Add a ROM e2e test with default OTP values (all zeroes) in TEST_UNLOCK with execution enabled.

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#16352]
This reminds me: we should probably add a simple boot test with all default OTP values in TEST_UNLOCKED.

_Originally posted by @alphan in https://github.com/lowRISC/opentitan/issues/16192#issuecomment-1315136765_

**Comment by tjaychen** [comment]
does a priority of P1 make sense to you guys?

**Comment by milesdai** [comment]
> does a priority of P1 make sense to you guys?

Yes, I can take this as a P1
