### ISSUE TITLE
Improve dif_otp_ctrl_read_blocking()

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#16394]
This interface is non-ideal since our generated constants are relative to the start of the memory mapped window, not individual partitions. We should probably just remove the partition parameter from this function and perform the addition, if needed, at callsites.

_Originally posted by @alphan in https://github.com/lowRISC/opentitan/pull/16391#discussion_r1024260468_

**Comment by msfschaffner** [comment]
CC @timothytrippel @cfrantz @mundaym

**Comment by timothytrippel** [comment]
Closing this as we have testutils that abstract away most OTP operations now.
