### ISSUE TITLE
Proposal: Create bisect tool that is aware of bitstream cache

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#16406]
Given a pair of commits and a test command, [git bisect](https://git-scm.com/docs/git-bisect/) can find the first bad commit in logarithmic time. This is a generally useful capability for developers, and possibly worth automating for nightly regressions. However, there are a few gotchas surrounding the bitstream cache. Consider the following methods of obtaining bitstreams:

* Testing with [`--define bitstream=vivado`](https://cs.opensource.google/opentitan/opentitan/+/master:hw/bitstream/BUILD;l=23;drc=8175ae0e88dd1bebe98fcfd4eb68db524f5fa7c1) is correct, but *slow*. In the worst case (no Bazel cache hits), this will contribute roughly $\lg(n)$ hours to the bisecting session, where $n$ is the number of commits between the good and bad commits. If there are 32 commits, testing could take upwards of 5 hours!

* Splicing the ROM from HEAD into a recent bitstream with [`--define bitstream=gcp_splice`](https://cs.opensource.google/opentitan/opentitan/+/master:hw/bitstream/BUILD;l=27;drc=8175ae0e88dd1bebe98fcfd4eb68db524f5fa7c1) is faster, but it runs the risk of creating an inconsistent bitstream. Suppose that the HEAD commit makes a  tightly-coupled change to hardware and software, but we splice the ROM from HEAD into the bitstream from HEAD~1. In this scenario, the incomplete bitstream cache and our [nearest-bitstream selection](https://cs.opensource.google/opentitan/opentitan/+/master:rules/scripts/bitstreams_workspace.py;l=386;drc=0960021721ab7fab7ab2c59bd7afd8f2236a2e39) logic would break the atomicity of commits, effectively building a mutant bitstream that does not correspond to any commit in the repo. Setting `BITSTREAM=latest` would not solve the problem — that would just cause the test command to fail when there's no cached bitstream for HEAD. 

* If we naively lean on the bitstream cache (omitting the `--define bitstream` flag), the hardware and software will be in sync, but they won't necessarily be coming from HEAD due to nearest-bitstream selection. This could have strange results, such as claiming that commit K is the first bad commit when it's actually testing the bitstream from some predecessor of commit K. This would also unnecessarily repeat the test command on the same bitstream. (Just like the previous option, setting `BITSTREAM=latest` does not help.)

Ideally, the bitstream cached would have no gaps, and it would be synchronized with master. This is infeasible for a few reasons.  Gaps appear in the bitstream cache when CI cannot keep up with the commits being merged to master. If a few commits are merged too quickly, Azure Pipelines will do a [batched CI run](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#batching-ci-runs) for the most recent commit and upload the bitstream to the cache — it never goes back for the skipped commits. We could disable batching, but it would take longer to get results for the tip of master. Alternatively, we could make a separate worker that fills the bitstream cache sequentially, but we'd still run into situations where we want to bisect and the cache has not caught up to the tip of master yet.

## Proposal: `./bitstream-bisect [--exact] GOOD_COMMIT BAD_COMMIT COMMAND`

I think we should create a bisect tool that is aware of the bitstream cache. Just like `git bisect run`, the tool would take a good commit, a bad commit, and a command to evaluate. Unlike vanilla `git bisect`, this tool would only evaluate the test command on cached bitstreams. Eventually, it will hit a range of commits $C_1..C_n$ where $C_1$ is good and $C_n$ is bad. If $n = 2$, we have an exact answer: $C_2$ is the first bad commit.

Optionally, the tool could narrow down to an exact first bad commit when `--exact` is specified. To do this, it just needs to bisect *again* on the range of candidates, this time specifying `--define bitstream=vivado`. This way, we get an exact answer while minimizing the number of Vivado builds, without sacrificing correctness by splicing into an earlier commit's bitstream.

This tool could be implemented as a wrapper around git-bisect. In the cache-only stage, the tool would look at the candidate commit that git picked and determine whether it has an entry in the bitstream cache. If so, it would run the test command. Otherwise it would run `git bisect skip` to indicate the commit cannot be tested. In the optional Vivado-based stage, we know the commit has no cached bitstream. The tool may also need an overridable Vivado command to enable dispatching Vivado builds to a remote build service.

### Problems with automated bisecting

* Bisecting naturally involves hopping around the range of commits rather than testing sequentially. It requires that the test command is hermetic, and that no state persists between tests. Unfortunately, we've recently seen some spooky behavior with the CW310 FPGA where the board (or Olimex JTAG adapter?) gets stuck in a bad state and tests fail. If we can't completely reset the board between tests, bisecting may be misinformed and produce an incorrect result. In this scenario, starting from the good commit and testing sequentially towards the bad commit would correctly find the first bad commit, but it would take linear time rather than logarithmic.

* [Other shaky assumptions?]

**Comment by drewmacrae** [comment]
I like and want this.

Could it be simplified by making a wrapper or two for a bash run command that can be passed to it that returns 125 whenever bitstreams aren't available. This would let you run commands like:
`git bisect run ./util/fpga/if_bitstream_available bazel test //sw/device/tests:uart_smoketest_fpga_cw310 &&
git bisect run bazel test //sw/device/tests:uart_smoketest_fpga_cw310 --define bitstream=vivado`



Flakiness can also make it hard to bisect.

**Comment by drewmacrae** [comment]
if you let people write their own git bisect run commands you could let them use verilator to identify exact positions if they preferred that to vivado

**Comment by luismarques** [comment]
> Could it be simplified by making a wrapper or two for a bash run command that can be passed to it that returns 125 whenever bitstreams aren't available. This would let you run commands like: `git bisect run ./util/fpga/if_bitstream_available bazel test //sw/device/tests:uart_smoketest_fpga_cw310 && git bisect run bazel test //sw/device/tests:uart_smoketest_fpga_cw310 --define bitstream=vivado`

That was my thought as well.

Thanks for writing such a clear and detailed proposal @dmcardle. This will be quite useful.

Regarding the flakiness, a better reset would be the long-term solution but in the meanwhile would it help to introduce some kind of sanity check test tool? If it returned an exit code that stops the bisection it would prevent erroneous bisect results and end broken bisections earlier.

**Comment by drewmacrae** [comment]
> > Could it be simplified by making a wrapper or two for a bash run command that can be passed to it that returns 125 whenever bitstreams aren't available.
> 
> I don't think we can chain two `git bisect run` commands in the same bisect session because the second `bisect run` would not reconsider the commits that were already skipped (worth verifying this, though). The heavier-weight bisect tool has the opportunity to be more ergonomic — it could automatically plug the good/bad commits from the first bisect session into a second session.

I'm fairly certain that git bisect run updates good/bad ptrs as it goes except if you tell it to skip.

**Comment by dmcardle** [comment]
> I'm fairly certain that git bisect run updates good/bad ptrs as it goes except if you tell it to skip.

I believe that `skip` is sticky, just like `good` and `bad`. If you start a bisect session and run a script that skips all the commits it sees, a second `git bisect run` is doomed to fail because git won't retry the previously-skipped commits. This means users would have to do a bit more than `git bisect run $FAST_CMD && git bisect run $SLOW_CMD`.

I wrote a little script that seems to confirm this behavior [[gist](https://gist.github.com/d2eb2d9977695c66edfbe9cb80b18592)]. The first run skips every commit it encounters, fails because it didn't find the first bad commit. The second run tries the commit it's sitting on (indicated by the line beginning with `[bisect-script.sh]`), then refuses to retry the previously-skipped commit and fails.

```console
% rm -rf .git && ./main.sh
Initialized empty Git repository in /usr/local/google/home/dmcardle/REPOS/git-bisect-test/.git/
[main (root-commit) dd3e41b] First commit
 1 file changed, 1 insertion(+)
 create mode 100644 file.txt
[main e890dfa] Second commit
 1 file changed, 1 insertion(+)
[main d155bc7] Third commit
 1 file changed, 1 insertion(+)
[main 4bcb90f] Fourth commit
 1 file changed, 1 insertion(+)
4bcb90f5f9f66fd3c9676a0a2a998ffdb8a5ed6f (HEAD -> main) Fourth commit
d155bc74bbe51b9d6dacd4ce2e69d62b3674cda7 Third commit
e890dfa8ee9adcc6a54c083fa39824a0c37c899c Second commit
dd3e41b8219f44d5e9c63343b4e898b4828386c9 First commit
COMMITS: 4bcb90f5f9f66fd3c9676a0a2a998ffdb8a5ed6f d155bc74bbe51b9d6dacd4ce2e69d62b3674cda7 e890dfa8ee9adcc6a54c083fa39824a0c37c899c dd3e41b8219f44d5e9c63343b4e898b4828386c9
status: waiting for both good and bad commits
status: waiting for bad commit, 1 good commit known
Bisecting: 0 revisions left to test after this (roughly 1 step)
[d155bc74bbe51b9d6dacd4ce2e69d62b3674cda7] Third commit

---- FIRST BISECT RUN ----
4bcb90f5f9f66fd3c9676a0a2a998ffdb8a5ed6f (main) Fourth commit
d155bc74bbe51b9d6dacd4ce2e69d62b3674cda7 (HEAD) Third commit
e890dfa8ee9adcc6a54c083fa39824a0c37c899c Second commit
running 'bisect-script.sh'
[bisect-script.sh] d155bc74bbe51b9d6dacd4ce2e69d62b3674cda7
Bisecting: 0 revisions left to test after this (roughly 1 step)
[e890dfa8ee9adcc6a54c083fa39824a0c37c899c] Second commit
running 'bisect-script.sh'
[bisect-script.sh] e890dfa8ee9adcc6a54c083fa39824a0c37c899c
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
d155bc74bbe51b9d6dacd4ce2e69d62b3674cda7
e890dfa8ee9adcc6a54c083fa39824a0c37c899c
4bcb90f5f9f66fd3c9676a0a2a998ffdb8a5ed6f
We cannot bisect more!
error: bisect run cannot continue any more
4bcb90f5f9f66fd3c9676a0a2a998ffdb8a5ed6f (main) Fourth commit
d155bc74bbe51b9d6dacd4ce2e69d62b3674cda7 Third commit
e890dfa8ee9adcc6a54c083fa39824a0c37c899c (HEAD) Second commit

---- SECOND BISECT RUN ----
running 'bisect-script.sh'
[bisect-script.sh] e890dfa8ee9adcc6a54c083fa39824a0c37c899c
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
d155bc74bbe51b9d6dacd4ce2e69d62b3674cda7
4bcb90f5f9f66fd3c9676a0a2a998ffdb8a5ed6f
We cannot bisect more!
```

**Comment by drewmacrae** [comment]
huh, gross...

To avoid re-implementing bisection, could you write a log, edit it and replay it without the skips to establish only the goods and bads in preparation for a slow command?

**Comment by dmcardle** [comment]
That's certainly a strategy we could use! I think I'd prefer to keep the sessions separate, though, so the conditions under which each commit passed/failed are clear. (AFAIK, Vivado builds are not truly hermetic, so a cached bitstream at commit C is not necessarily equivalent to one built locally with `--define bitstream=vivado`.)

I'm imagining that the tool would execute `git bisect run $FAST_CMD`, extract the bad/good commits from `git bisect log`, then do `git bisect reset` and `git bisect run $SLOW_CMD`. Note that we do not need to reimplement the bisect algorithm; the tool I'm imagining just drives the git-bisect session.
