### ISSUE TITLE
[CDC|SPI_DEVICE] CDC violation in rv_dm

### ISSUE THREAD

**Issue by jeoongp** [lowRISC/opentitan#16412]
A CDC violation is detected in rv_dm by the tool as follows.
A signal from main_clk is used for mux select between io_div2_clk signal and io_div4_clk signal. 
I am not clear if it's a static path or actual violation. 
![Screen Shot 2022-11-16 at 5 01 03 PM](https://user-images.githubusercontent.com/103145460/202328676-c77fb597-ad8c-40d1-8af2-a886f4cb8aab.png)

![Screen Shot 2022-11-16 at 5 02 24 PM](https://user-images.githubusercontent.com/103145460/202328653-354afe92-5d54-4327-a82f-d9dcffa3d209.png)

**Comment by eunchan** [comment]
lc_en is mubi4 type. If `prim_mubi4_sync` module is used as the synchronizer, it is fine for reconvergence issue.

**Comment by msfschaffner** [comment]
This signal has similar functionality as the `lc_hw_debug_en_i` signal on this module.
I.e., this is the latched version coming from the pinmux strap sampling logic via `pinmux_hw_debug_en_i`.
This uses the `prim_lc_sync` synchronizer module and the signal should be quasi-static just as  `lc_hw_debug_en_i`.
Hence it should be ok to waive.

**Comment by jeoongp** [comment]
Thanks for confirmation
