### ISSUE TITLE
[csrng/dv] Test disable and re-enable of module

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#16430]
Verify that CSRNG can be disabled and re-enabled multiple times and at any time (thus covering many different states) through a write to the `ENABLE` field in the `CTRL` CSR. Ideally, this would work like the `stress_all_with_rand_reset` test, although with disable and re-enable instead of reset, to show that CSRNG behaves correctly when being disabled at any time of use.

The enabling and disabling conditions w.r.t. EDN and `entropy_src` have to be respected, though, and the agents need to behave accordingly.

#16461 extends one test (`csrng_cmds_test`) to disable and re-enable CSRNG randomly. After that PR is merged, the remaining work (i.e., the described "ideal" test) is V3 like for the other entropy complex modules.

> original estimate 16
> estimate 20
> remaining 2022-11-15 16
> remaining 2022-11-16 12
> remaining 2022-11-17 8
> remaining 2022-11-18 4
> remaining 2022-11-21 3
> remaining 2022-11-22 0

(These numbers include investigation and fixing of RTL bugs (#16460) that were uncovered by the test developed in #16461.)

**Comment by vogelpi** [comment]
I am now closing this. The corresponding PRs have been merged.
