### ISSUE TITLE
[CDC|JTAG] Output from tap_mux in strap sampling

### ISSUE THREAD

**Issue by jeoongp** [lowRISC/opentitan#16439]
![Screen Shot 2022-11-17 at 11 24 45 AM](https://user-images.githubusercontent.com/103145460/202540561-c5343cab-4eb0-4dbd-8a49-689b9167f4df.png)
![Screen Shot 2022-11-17 at 11 26 28 AM](https://user-images.githubusercontent.com/103145460/202540598-79e79969-1477-4351-8a03-efabb8e54dfe.png)

The result of above combinational logic goes to a FF in jtag_clk.
Tool recognizes it in io_div4_clk domain.
I would like to make sure if this path is OK.

**Comment by msfschaffner** [comment]
This is the JTAG mux, which is quasi-static. If we change the muxing index, this will affect all JTAG signals including TRST. But this is fine, since the mux selection stays constant while we are using the selected TAP.

**Comment by jeoongp** [comment]
OK. Thanks for clarifying
