### ISSUE TITLE
[CDC|AST] CDC in AST

### ISSUE THREAD

**Issue by jeoongp** [lowRISC/opentitan#16440]
rng_en_i comes from main_clk in top_earlgrey but is captured with another clock (io_div4_clk) in ast module as follows.

![Screen Shot 2022-11-17 at 11 41 25 AM](https://user-images.githubusercontent.com/103145460/202544090-6abfa519-9614-4260-91fa-5ff10069c9ea.png)

![Screen Shot 2022-11-17 at 11 40 27 AM](https://user-images.githubusercontent.com/103145460/202544062-31a1133d-974a-4da8-acbc-dccc21d5523a.png)

**Comment by msfschaffner** [comment]
For this one it would be good for @arnonsha to confirm whether this is intended.

**Comment by arnonsha** [comment]
Yes, the rng_en_i is synchronized to tlul_clk inside AST. This is intentional.
Since a synchronizer is not shown in the liberty file, I guess you should add a waiver in top level cdc run.

**Comment by arnonsha** [comment]
I guess there are no more, or otherwise the tool would have found them, right ?
Anyway I don't believe we can modify the lib file. It is generated by PT and describes IF only.

**Comment by tjaychen** [comment]
This should be resolved by #16596.
I'll close this for now. @jeoongp please reopen if you do not agree.

**Comment by jeoongp** [comment]
Thanks @tjaychen. Yes, this issue was resolved by #16596.
