### ISSUE TITLE
[i2c] Watermark on all four I2C FIFOs

### ISSUE THREAD

**Issue by jesultra** [lowRISC/opentitan#16444]
The I2C IP has a total of four FIFO buffers, two (FMT and RX) are used in host mode, the two other (ACQ and TX) used in target mode.

In order to improve performance, there is support for "watermark" interrupts on the FMT and RX fifos used in host mode, but no similar feature for the two fifos used in target mode.

I would like to request similar settings for the target mode FIFOs, that is 1/4/8/16/30 for the ACQ fifo and 1/4/8/16 for the TX fifo.

This would introduce two new interrupts.  In order to avoid re-numbering, we could at the same time retire the two interrupts FMT_OVERFLOW and TX_OVERFLOW, since they can only be triggered by the CPU stuffing bytes into one of these two outgoing fifos, and the status bits FMTFULL and TXFULL along with FIFO_STATUS register are more than adequate to allow the CPU to know when there is room in the outbound fifos.  (I cannot imagine when you would ever want an interrupt in response to the CPU over-filling an outgoing fifo.)

**Comment by a-will** [comment]
CC @tjaychen @jdonjdon

**Comment by msfschaffner** [comment]
CC @moidx

**Comment by msfschaffner** [comment]
Sorry for the noise here. I marked this as P0 for triage purposes only. We need to decide whether we can take this change or not (but likely we have to defer it).

**Comment by jesultra** [comment]
Related nice-to-have request:

The specification does not state a particular FIFO size, the watermark levels seem to be chosen for 31 or 32-byte fifos, but the FIFO_STATUS register sets aside 7 bits for the depth of each buffer, suggesting that implementations could have as much as 127 bytes fifos.

I think it is beneficial that the specification does not state any particular depth, but lets it be up to the implementation.  In that case, though, I think that the watermark levels should be re-phrased as "1 byte", "1/8 full", "1/4 full", "1/2 full", and "15/16 full".

Furthermore, we might want to change the specification to declare FIFO_STATUS to have 8-bit value, since I do not see any downside to firmware interpreting all 8 bits, even though the high two or three bits may always be zero.  The current specification runs the risk that software intentionally looks only at 7 bits, and do not work properly on an implementation that for some reason chooses 128 or 255 byte fifos.

**Comment by johngt** [comment]
@msfschaffner / @moidx this is currently tagged as an M2 task. Should this be moved to Post M2 / M3 for now?
If needed for M2 then we will need to address this promptly.

**Comment by jesultra** [comment]
In my opinion, this is a "nice-to-have" feature, not worth rushing through.  I would much rather have efforts towards e.g. issue #16579, as that one seriously impacts Ti50 development.

**Comment by msfschaffner** [comment]
This is something we need feedback from @tjaychen, since he did most of the design updates for M2 in I2C.

**Comment by tjaychen** [comment]
@jdonjdon

**Comment by tjaychen** [comment]
i would be happy to remove the overflow interrupts :)
I'm okay with adding level interrupts also, assuming its not hugely disruptive to DV.

@jdonjdon what do you think?

**Comment by jdonjdon** [comment]
> i would be happy to remove the overflow interrupts :) I'm okay with adding level interrupts also, assuming its not hugely disruptive to DV.
> 
> @jdonjdon what do you think?

Adding more interrupt is ok, but I prefer to keeping overflow interrupts, which tell us possible data loss.

**Comment by tjaychen** [comment]
that's fine with me. Are you sure adding more interrupts won't disrupt your existing tests @jdonjdon ? The watermark interrupts are nice to have, so we don't have to do them.

**Comment by jesultra** [comment]
> Adding more interrupt is ok, but I prefer to keeping overflow interrupts, which tell us possible data loss.

This is a minor point, but overflow interrupts on incoming queues, such as ACQ and RX makes a lot of sense, as they can detect.  (ACQ queue could overflow only if target clock stretching could somehow be disabled, which I do not believe we support.  RX queue can only overflow if the host keeps clocking despite fill FIFO, which I do not see a point in doing.)

However the two "outgoing" FIFOs FMT and TX can overflow only if mis-behaving software on the OT chip itself fails to honor the FMTFULL or TXFULL status flags, and keeps stuffing data into the FIFO anyway.  So I see absolutely no point in an overflow interrupt for those.

**Comment by jesultra** [comment]
The target mode FIFO watermark interrupts would be nice to have, but not critical for engineering silicon.

Chrome OS routinely transfer up to 63 bytes in a single I2C transaction.  How deep are the Earl Grey FIFOs?  If they are only 32 bytes, then each such 63-byte transaction will necessarily involve the FIFOs being "topped up" in the middle of the transaction.  Absent watermark interrupts, such topping up will only be triggered once the FIFO is completely empty, and thus always result in clock stretching to some extent.

What I am saying is that Chrome OS boot times will be impacted to some extent by the lack of watermark interrupts, and that is something that we do care about.  (Alternatively, if the FIFO are 64 bytes, then Chrome OS can avoid clock stretching even without watermark interrupts.)

**Comment by tjaychen** [comment]
the acq fifo is actually 64 bytes right now, however that does not allow you the full range because of the start / stop bytes. I've been meaning to go back and address this but I just keep on forgetting.

**Comment by jesultra** [comment]
If both ACQ fifo and the TX fifo is 64 bytes, I think we are good.  To work around having only space for 62 or 61 effective data bytes in the ACK fifo, we can fiddle with the how our TPM advertises its FIFO window size, and thereby avoid one or two bytes of each chunk being stuck waiting for an interrupt handler to clear the fifo.
Then watermark interrupts are not a priority for Ti50.

(Are the RX and FMT fifos 32 byte or 64 byte? The specification https://docs.opentitan.org/hw/ip/i2c/doc/ does not say either way.  It makes sense to leave buffer size up to the implementation, but in that case  I would like to re-state my suggestion that watermark levels should be re-phrased as "1 byte", "1/8 full", "1/4 full", "1/2 full", and "15/16 full", as the current watermark levels only make sense for a 32-byte fifo.)

**Comment by crteja** [comment]
Estimate for M2.5
> estimate 16

**Comment by johngt** [comment]
@GregAC / @marnovandermaas / @crteja . Question from @jesultra is
Are the RX and FMT fifos 32 byte or 64 byte? 
If 32 byte this might require an RTL change. Otherwise the comments seem to suggest watermarks would not be needed and the effort could be decreased.

**Comment by crteja** [comment]
@johngt, all four FIFOs in I2C are 64 Byte

**Comment by marnovandermaas** [comment]
As discussed for M2.5 this is a nice to have and so I'm lowering the priority.

**Comment by moidx** [comment]
Hi @jesultra, can you provide a priority assessment on this feature request for the next iteration? 

Thanks!

**Comment by jesultra** [comment]
This is not high priority for ChromeOS, we do not want other feature requests to be deprioritized due to this. Our higher level TPM protocol implementation will make sure that a single I2C transaction will stay within the bounds of the FIFOs. Having the watermarks requested here would merely open up the possibility of efficiently transferring larger blocks, if ChromeOS wanted to reduce the number of roundtrips (which could be a reasonable endeavor).

**Comment by msfschaffner** [comment]
We will attempt to include this for PROD, alongside the interrupt type conversions for FIFO watermarks.

**Comment by andreaskurth** [comment]
This will be resolved by https://github.com/lowRISC/opentitan/pull/21621.
