### ISSUE TITLE
[rstmgr] V2S review opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#16475]
- [x] Complete the reset background check testbench and improve the coverage https://github.com/lowRISC/opentitan/issues/9314
- [x] Need to add the SEC_CM FPV environment and check that WE onehot checker and sparse FSMs do indeed trigger an alert. checked with @cindychip -> this is done
- [x] Need to double check bound interfaces since some of the SVAs are uncovered: https://github.com/lowRISC/opentitan/pull/16503
- [x] Add a parameter or split `pwrmgr_rstmgr_sva_if` to remove uncovered SVAs: https://github.com/lowRISC/opentitan/pull/16503
- [x] https://github.com/lowRISC/opentitan/issues/11161

**Comment by matutem** [comment]
The fix for the SVA issues split some SVA rather than parameterizing.

**Comment by msfschaffner** [comment]
Awesome, thanks for taking care of this, @matutem!
