### ISSUE TITLE
[CDC|AST] CDC on ast_init_done in AST

### ISSUE THREAD

**Issue by jeoongp** [lowRISC/opentitan#16478]
This is similar to #16440.
rng_init_done comes from main_clk in ast but is captured with another clock (io_div4_clk) in top_earlgrey as follows.
![Screen Shot 2022-11-18 at 3 25 55 PM](https://user-images.githubusercontent.com/103145460/202819563-2a16a079-3b4b-4a15-b007-83653a8ee6de.png)
![Screen Shot 2022-11-18 at 3 24 42 PM](https://user-images.githubusercontent.com/103145460/202819571-ca5d2df0-786a-4718-98be-a69c3899bb94.png)
This error is deferred to post-M2 while waiting for Nuvoton to clarify.

**Comment by tjaychen** [comment]
could you help point out where ast_init_done is captured but isn't synchronized?

**Comment by tjaychen** [comment]
it's possible for this one the cdc tool does not understand the behavior of `prim_mubi4_sync`. That module will not look right to a cdc tool.

**Comment by arnonsha** [comment]
@jeoongp 
ast_init_done_o is defined as being tlul_clk related in [spec](https://docs.opentitan.org/hw/top_earlgrey/ip/ast/doc/).
Let me know what clarification you expect on our side

**Comment by jeoongp** [comment]
Ah @tjaychen you are right. CDC is handled through prim_mubi4_sync. 
@arnonsha sorry for false alarm.

**Comment by tjaychen** [comment]
@jeoongp we might need to consider the suggestions from RI later on instead of waiving this path.
I worry if long term we accidentally remove the `mubi_sync` module, we may not realize there is a real violation here.

**Comment by jeoongp** [comment]
Yeah I agree. I will take some experiments based on their suggestion. I will create a new ticket to track this.

**Comment by jeoongp** [comment]
I generated https://github.com/lowRISC/opentitan/issues/16595
