### ISSUE TITLE
[test-triage,spi_host] spi_host_sw_reset only asserts sw_reset after transaction has ended

### ISSUE THREAD

**Issue by hcallahan-lowrisc** [lowRISC/opentitan#16510]
### Hierarchy of regression failure

Block level

### Failure Description

`spi_host_sw_reset` test does not actually assert the sw_reset during the transaction, but only after a transaction has ended.
I checked a bunch of seeds and they were all the same.

[- Test description](https://github.com/lowRISC/opentitan/blob/4d991c505ad6f0bd9b03967652d722a9909fe6c6/hw/ip/spi_host/data/spi_host_testplan.hjson#L108-L123)
The testplan does not explicitly say 'within a transaction' but that is implied here.

### Steps to Reproduce

- GitHub Revision:  0986f40632
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
`util/dvsim/dvsim.py hw/ip/spi_host/dv/spi_host_sim_cfg.hjson -i spi_host_sw_reset --fixed-seed 1088210569`

### Tests with similar or related failures

![spi_host_sw_reset_waves](https://user-images.githubusercontent.com/102029880/203345208-9e40f191-3b83-4327-914c-9418fdb5a633.png)

> estimate 8

**Comment by andreaskurth** [comment]
Triaged for `spi_host`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2 because the `spi_host_sw_reset` test needs to be tweaked so that the software reset feature gets tested while transactions are ongoing.

**Comment by johngt** [comment]
From @hcallahan-lowrisc effort estimation
<0.5d .. 2d>
> estimate 8

**Comment by moidx** [comment]
Moving to M2.5.2. Lowering the priority to P2 as this is in the `spi_host` interface. The software should be aware of ongoing SPI transactions before requesting a sw_reset.
