### ISSUE TITLE
[sysrst] Inconsistent key interrupt bit assignment

### ISSUE THREAD

**Issue by jesultra** [lowRISC/opentitan#16519]
The register KEY_INTR_CTL lists bit 7 as reserved, with the result that the low byte controls the 7 falling edge triggers, and the high byte controls the 7 corresponding rising edge triggers.

The register KEY_INTR_STATUS also has one bit for each of the 14 possible transitions, but that one does not have bit 7 reserved, and instead packs the 14 values into the lowest 14 bits.

I would argue that the bit assignment between these two registers should be identical, as is almost always the case with pairs of "interrupt enable" and "interrupt status" registers.

**Comment by msfschaffner** [comment]
This appears to be a bug in the CSR layout, hence we can fix this right away as part of M3.
There should be no DV impact since it neither removes nor adds a new feature.
The DV environment and DIFs should pick up the bit index change automatically.
