### ISSUE TITLE
[lc_ctrl] lc_clk_byp_req alone can switch to extclk in some LC states

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#16529]
As discussed with @msfschaffner and @cindychip, we found a case that in RMA state,  we only need to set lc_clk_byp_req to make clkmgr switch to use the ext clk. (no need to issue a LC transition)

- [x] update this [table](https://docs.opentitan.org/hw/ip/clkmgr/doc/index.html#clock-frequency-summary) to clarify what LC states allows user to only set lc_clk_byp_req to switch to ext clk. #16687
- [x] enhance a chip-level test to verify this case. https://github.com/lowRISC/opentitan/pull/18279
- [x] check if lc_ctrl/clkmgr block-level TB verifies this. https://github.com/lowRISC/opentitan/pull/16706

cc: @matutem @tjaychen @cindychip

**Comment by tjaychen** [comment]
sounds good, thanks for the update. I think I keep on forgetting to include RMA in a ton of stuff.

**Comment by tjaychen** [comment]
@matutem i think you already check for external clk request, but i'll let you comment in more detail.

**Comment by weicaiyang** [comment]
> @matutem i think you already check for external clk request, but i'll let you comment in more detail.

Perhaps we should also check lc_ctrl TB. Before we thought the lc_clk_byp_req could only happen due to LC transition. Now it actually just depends on the current LC state.

**Comment by tjaychen** [comment]
yeah good point.
@cindychip

**Comment by matutem** [comment]
The clkmgr unit tests only depend on lc_clk_byp_req input (it knows nothing about the lc_ctrl state otherwise), and we test this functionality.

**Comment by cindychip** [comment]
@weicaiyang and @tjaychen  thanks for confirming on LC_CTRL side.
As far as I understand, the current LC_CTRL testbench only writes this value when there is a lc_state transition. I am working on a PR to enhance this feature.

**Comment by gdessouky** [comment]
@cindychip I am unsure if your [commit](https://github.com/yehuda-bejar/opentitan/commit/cd963ae1e81a9a66c5f643f5a9fc50ea7a625257 ) takes care of this issue and it should be closed now, this is what I am understanding. Can you please confirm?  Thanks!

**Comment by cindychip** [comment]
@gdessouky thank you for raising this issue. My commit covers the block level check (action item 3). But I think what is missing here is the chip level testcase. 
The chip level testplan does include external clock transition: https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/data/chip_testplan.hjson;l=926?q=chip_testplan.hjson&ss=opentitan%2Fopentitan
With code: https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/tests/sim_dv/lc_ctrl_transition_impl.c;l=92?q=execute_lc_ctrl_transition_test&ss=opentitan%2Fopentitan

What is missing here is to switch to extclk without lc transition.
I think we still need to implement it in chip level and I would suggest P1 or P2 for M2.5

**Comment by gdessouky** [comment]
Thanks @cindychip for commenting, it makes a lot more sense to me now. Will label this as P1 for M2.5 then.

**Comment by gdessouky** [comment]
> estimate 8

**Comment by moidx** [comment]
Updated to P1 as we need to make sure we can use an external clock before leaving `RAW` state. @gdessouky and @cindychip to coordinate top level test implementation.

**Comment by msfschaffner** [comment]
CC @jdonjdon @matutem

**Comment by msfschaffner** [comment]
It looks like this is related to an issue that @jdonjdon and @matutem are currently looking into, hence the reassignment.

**Comment by moidx** [comment]
@gdessouky, @johannheyszl  please note the previous comment. There are some integration issues being debugged, which are related to this issue, so I think this issue can now be resolved by @jdonjdon and @matutem. Thanks

**Comment by jdonjdon** [comment]
I have a fix in my local and running in cs
to confirm. It runs for 12 hrs and still on going.
Will update once the test pass

**Comment by jdonjdon** [comment]
#18361 has raw to unlock transition test fix.
