### ISSUE TITLE
opentitan usb device interface

### ISSUE THREAD

**Issue by jrrk** [lowRISC/opentitan#1653]
Opentitan on Nexys-Video incorporates a USB device that makes use of PMOD connector JB to provide the USB connector, pullup resistor and sense input. Is this a custom item because I don't seem to be able to find it in the Digilent PMOD catalogue ?

**Comment by asb** [comment]
Hi Jonathan. It is indeed a custom board, @mdhayter may be able to provide more info (we had discussed adding the board files to the OT repo as a reference, which seems like it would be worthwhile).

**Comment by imphil** [comment]
I do have some of those adapters around from Mark. Please stop by at the office, or let Rob know and he can bring some with him over next time.

**Comment by alistair23** [comment]
Are these custom boards open to anyone else?

**Comment by mdhayter** [comment]
Sorry, I didn't get round to pushing the info. May have some time Wed or Fri to make a PR with the Kicad files. Parts were from Digikey and pcb from Oshpark so should be easy for people in the US to make their own.

**Comment by alistair23** [comment]
No worries. Cool, that should be pretty easy to do then.
