### ISSUE TITLE
Understanding bazel fusesoc rules

### ISSUE THREAD

**Issue by shareefj** [lowRISC/opentitan#16555]
Hi there,

this is more of a question than an issue against OT.  I've been looking at how you've integrated fusesoc into your bazel flow and had a question.

In my use case I'm trying to integrate gRPC with Verilator so am trying to work out the best way to compile the project as a whole.  My understanding of your Verilator flow is that you don't have any external dependencies so all your CPP files are specified in core files passed to fusesoc.  So just to confirm, does your bazel rule just launch fusesoc to compile the final executable?

I guess I have two options: 1) create a core file for the gRPC source and add that as a dependency in my Verilator core file; 2) use bazel to build the final executable such that I can use the gRPC bazel deps but somehow pass the output of the Verilator build as a dependency to bazel.

In your experience of running fusesoc via bazel, is that second option even possible?

Thanks.

**Comment by drewmacrae** [comment]
> In my use case I'm trying to integrate gRPC with Verilator so am trying to work out the best way to compile the project as a whole. My understanding of your Verilator flow is that you don't have any external dependencies so all your CPP files are specified in core files passed to fusesoc. So just to confirm, does your bazel rule just launch fusesoc to compile the final executable?

We do depend on the local installation of Verilator on the host machine. FuseSoC and Verilator aren't compatible with the bazel sandbox (yet). Bazel invokes FuseSoC which invokes Verilator to make the model which is then used in tests with SW and a test harness (that's usually OpenTitanTool). Let me know if that answers this first part of the question.

> In your experience of running fusesoc via bazel, is that second option even possible?

Our tests then attach a number of interfaces between the harness and the verilated binary. If we wanted to implement gRPC on OT and run it in a test, I'd imagine it would get built in SW and into the test harness, and would run across one of these interfaces.

**Comment by moidx** [comment]
Please let us know if you have any follow up questions.

**Comment by shareefj** [comment]
Thanks and sorry, I missed the replies here.  Must have flown past in my inbox.

I ended up dropping Bazel as it was too much of a pain in the back side to get it working.  I'm just using Fusesoc with a CMake generator to compile the gRPC code into libs and copy those into the Fusesoc Verilator build directory.  Seems to work well enough.
