### ISSUE TITLE
Unreliable SPI programming

### ISSUE THREAD

**Issue by jesultra** [lowRISC/opentitan#16553]
I attempted to use an UltraDebug device to communicate with the ROM bootloader for SPI flashing, but was unsuccessful.

Looking at the analyzer traces, it is not clear to me what makes the difference, as I see the same SPI data going back and forth.  I see that the UltraDebug has little to no time from chip select being asserted to the clock starts toggling.  I do not know if the FPGA hardware needs setup time, then even if I set the clock speed all the way down to 5000 kHz, I still am not able to flash.

On my logic analyzer, I can see that the initial "Chip Erase" is followed by a number of status inquiries, the last of which indicates that the write (erase) operation is no longer in progress.  Then a 256-byte block of data is sent, followed by an endless row of status inquiries, all of which report "write in progress".

**Comment by a-will** [comment]
> I see that the UltraDebug has little to no time from chip select being asserted to the clock starts toggling. I do not know if the FPGA hardware needs setup time

Generally-speaking, this is always the case, for any SPI flash device. However, it appears any paths related to CSB are not actually constrained in the FPGA build, so I couldn't say what the requirement is. Something to fix up...

**Comment by timothytrippel** [comment]
when you say "unreliable SPI programming" do you mean that sometimes the programming succeeded?

**Comment by timothytrippel** [comment]
CC: @alphan

**Comment by jesultra** [comment]
I use `opentitantool --interface ultradebug bootstrap` to attempt programming.  I assume its bootstrapping logic knows to wait for READ_SFDP, as basically only the back-end driver to issue SPI transactions differs between UltraDebug and HyperDebug (and the latter of course works.)
I do see the usual "Boot strap requested" banner when attempting programming with UltraDebug.  I think it could be interesting if the bootstrap ROM could be made to output some more information as it receives/programs each page.  I do have the Xilinx tools to be able to build my own bitstream, though I have not used them for quite a while.  Is there some compile flag that I can set?

**Comment by jesultra** [comment]
I need to run a logic analyzer again.  I have come to suspect that the explanation could be the UltraDebug transport driver in OpenTitanTool not properly supporting keeping the chip select asserted across write/read or write/write transfer combination.

**Comment by alphan** [comment]
@jesultra just checking in to ask if you were able to look into the UltraDebug transport driver in opentitantool.

**Comment by andreaskurth** [comment]
I'm setting this to M2.5 since it's labeled https://github.com/lowRISC/opentitan/labels/SW%3AROM. If that's incorrect, please re-set to the appropriate milestone.

I came across this while triaging issues for `spi_host` and `spi_device`, but IIUC this does not concern those two HW blocks. If that's incorrect, please label according to the hardware block. Thanks!

**Comment by a-will** [comment]
> I'm setting this to M2.5 since it's labeled [ SW:ROM](https://github.com/lowRISC/opentitan/labels/SW%3AROM) ROM related issues . If that's incorrect, please re-set to the appropriate milestone.
> 
> I came across this while triaging issues for `spi_host` and `spi_device`, but IIUC this does not concern those two HW blocks. If that's incorrect, please label according to the hardware block. Thanks!

This _might_ have some relationship to `spi_device`, but it's unclear and may be a bug in host-side tools. Most of us don't have access to an UltraDebug board, though, so this may be troublesome to reproduce.

**Comment by andreaskurth** [comment]
Thanks @a-will. Then I'll additionally label this https://github.com/lowRISC/opentitan/labels/IP%3Aspi_device + https://github.com/lowRISC/opentitan/labels/SW%3Aopentitantool and https://github.com/lowRISC/opentitan/labels/Priority%3AP1 for now, so that we soon discuss this with the product team.

**Comment by jesultra** [comment]
I will spend some time this week trying to establish whether the problem is in the opentitantool drivers or in the FPGA simulation of OT (or in UltraDebug hardware).

**Comment by jesultra** [comment]
I have reproduced the issue, and found that if I simultaneously connect my cheap FTDA-based logic analyzer as well as a Siglent scope on the four SPI signals, the problem disappears.

If I put the scope probes into x10 mode, the problem comes back, but x1 mode makes it go away.  This makes me suspect that the added capacitance of the x1 probes is what makes a difference.

I assume that the issue could be caused by fast slew rate of UltraDebug in conjunction with the rather long connection lines (8" ribbon cable plus 8" mess of jumper wires) that I am using to connect UltraDebug to the CW310 board.

Since I can with at least 80% reliability program OpenTitan on CW310 with the tweaked capacitance, I feel confident that there is no underlying issue in the simulated OpenTitan chip.  I am ready to declare this a non-issue.
