### ISSUE TITLE
I2C clock stretching, need interrupts

### ISSUE THREAD

**Issue by jesultra** [lowRISC/opentitan#16579]
The TPM protocol via I2C make use of request-response interactions, that is, the AP may do a one-byte I2C write to ask for the content of a particular "register", and then do a multi-byte I2C read to retrieve the bytes.  It may read fewer than the full contents of the register, before doing another I2C write to request another register.
In order to avoid bytes left in the TX FIFO from being erroneously transmitted by OpenTitan in the second read, we have the STRETCH_CTRL register. By enabling EN_ADDR_TX, we can ensure that a read transaction is delayed until OpenTitan has had a chance to empty the TX FIFO of any leftover content.  This handles the case of alternating write/reads well.

However, some more degenerate cases could happen.  If the AP does a one-byte write to prepare reading from some register, but then "changes its mind" (maybe due to driver reset), and does not issue an I2C read operation, but instead does another one-byte write asking for some other register.  We would at that time have already set STOP_TX when handling the first one-byte write, but since a corresponding read transaction never arrived, that bit was not cleared by hardware, and the bytes would remain in the FIFO, possibly being sent in the I2C read transactions after the second write, if the interrupt handling of the second write is delayed.

I see two ways of solving this issue:
1. Add another bit to the STRETCH_CTRL register, that when enabled causes STOP_TX to be cleared to zero any time a write transaction is recognized (when OpenTitan acknowledges its address).
2. Alternatively, we could set EN_ADDR_ACQ, to delay processing of the second one-byte write, giving us time to empty the TX FIFO at that point.  However, in order do this, the OpenTitan core need to be alerted to the fact that a (second) write transaction was initiated, and is being indefinitely held via clock stretch.  That would most conveniently be done via two new interrupts: ADDR_TX_STRETCH and ADDR_ACQ_STRETCH, which would be asserted as long as the clock is stretched due to the corresponding bit in the STRETCH_CTRL register.

If not too much to ask, I would like both of the above features implemented, in case of corner case becoming apparent later on, which can be solved only using one or the other.

**Comment by a-will** [comment]
>  We would at that time have already set STOP_TX when handling the first one-byte write, but since a corresponding read transaction never arrived,

That's actually not how that feature was intended to be used. In the current form, STOP_TX should only be set _after_ receiving the read command, for correctness. It sounds like your code is speculating that it can prepare data for a future, expected read command and is committing an error. I do see the attempt to avoid the currently unavoidable latency, though.

Thus, it sounds like this isn't actually a bug and is more of a performance-enhancing feature request. But I'm just being pedantic here. ;)

The first option sounds a little awkward to me (complicating control logic and adding more corner cases), so it might require more consideration. The second option sounds like a variation on something we know we're missing (an interrupt when the target has been addressed).

As to whether we can address this now, others will decide.

**Comment by jesultra** [comment]
I am quite certain that the option of setting STOP_TX before the read transaction arrives was discussed when I requested this feature. (Or maybe it was only for STOP_ACQ, https://docs.google.com/document/d/1VvlgsJIGaHnSCflTKts9LULCaI-tC8czK4YB8eZSxG4/edit?disco=AAAALO0HbXk )

Anyway, as you say, the problem could be solved by not setting the "stop stretching" bit until the transaction is there.  My problem is then how my software will know that a transaction is there! For that, I would need an interrupt telling me that the clock is being stretched at the address byte of a rx/acq transaction, (the 2nd solution from my original post.)

**Comment by a-will** [comment]
> Anyway, as you say, the problem could be solved by not setting the "stop stretching" bit until the transaction is there. My problem is then how my software will know that a transaction is there! For that, I would need an interrupt telling me that the clock is being stretched at the address byte of a rx/acq transaction, (the 2nd solution from my original post.)

Haha, yeah, I hear you. After @tjaychen took on fixing up the target mode, adding that interrupt got on our to-do list, but this is a good reminder why we _needed_ it! :smile:

**Comment by jesultra** [comment]
Yes, a single "transaction started" interrupt would suffice (rather than the two special-purpose ones I proposed), provided that the START entry is going on the ACQ FIFO **before** clock stretching of the address ack bit is stopped by software intervention.  I really hope that such an interrupt can make it into the first silicon.

**Comment by tjaychen** [comment]
yes @a-will and i noticed an issue some time ago that the stop_clock features weren't very helpful because software has no way to know when it's happening (i have an issue somewhere). 

As you say though, there is a problem with the currently re-worked target mode in that the place the clock stretching is done the entry does not get deposited into the ACQ fifo. I can't remember if I had intended to fix this or was going to expose it via some status otherwise.

@jdonjdon found some other bugs with the existing i2c, so I will probably fix those first before returning to this.

**Comment by jesultra** [comment]
The feature is actually quite close to being useful to me, even absent interrupts.  The reason being that e.g. the STOP_TX bit can be set ahead of the transaction being initiated on the bus.  So the typical mode of operation is going to be that whenever processing of the previous transaction completes, I set the STOP_xxx bit to allow the next one through, not needing to know if it is already waiting or not.

I have thought more about my "odd" request for a fifth bit in my first proposal in the original post.  I think it generalizes nicely as below.  I assume that the six bits as described are not much more complicated that the current four, and having them would allow handling all the cases I can foresee without interrupts.

| Bits | Type | Reset | Name | Description |
|-------|---------|-------|-------|-------------------|
| 0 | rw | 0x1 | TX_GO | Allow next TX transaction without stretching clock on address byte. |
| 1 | rw | 0x1 | ACQ_GO | Allow next ACQ transaction without stretching clock on address byte. |
| 2 | rw | 0x0 | CLEAR_TXGO_ON_TX | Upon accepting a TX transaction, reset TX_GO to zero. This will block the next TX transaction unless and until TX_GO explicitly re-set to one.|
| 3 | rw | 0x0 | CLEAR_TXGO_ON_ACQ | Upon accepting a ACQ transaction, reset TX_GO to zero. This will block the next TX transaction unless and until TX_GO explicitly re-set to one.|
| 4 | rw | 0x0 | CLEAR_ACQGO_ON_TX | Upon accepting a TX transaction, reset ACQ_GO to zero. This will block the next ACQ transaction unless and until ACQ_GO explicitly re-set to one. |
| 5 | rw | 0x0 | CLEAR_ACQGO_ON_ACQ | Upon accepting a ACQ transaction, reset ACQ_GO to zero. This will block the next ACQ transaction unless and until ACQ_GO explicitly re-set to one. |

Actually, given the way that START/STOP conditions are put into the ACQ fifo (the previous chip I worked on put only data bytes in there, making it impossible to tell two 1-byte writes from one two-byte write operation, if processing of the trans_complete interrupt was delayed) I actually do not need to ever stretch the acknowledgement of ACQ transactions on OpenTitan, so I do not see an actual use case for ACQ_GO, CLEAR_ACQGO_ON_TX, or CLEAR_ACQGO_ON_ACQ, but it might still be nice to include them for completeness, particularly if combined with an interrupt that will be able to inspect the nature of the pending transaction.

**Comment by tjaychen** [comment]
sorry i need to summarize a bit, there are a lot of ideas flying around.

First off, my original plan was to add an interrupt for the completion of the address phase, and I am also adding #16605.

My assumption is that #16605 would clear out any "stale" contents, and the inclusion of the interrupt would let the software know when a new transaction has arrived.  In this scenario, either the new "address phase" interrupt or the "tx empty" interrupt I assumed would serve your purpose.   Wouldn't this be enough? I would prefer to not add a bunch of detecting conditions in hardware at this point.

**Comment by tjaychen** [comment]
@a-will @jesultra @jdonjdon and I just sync'd up on this topic.
The conclusion are as follows:

1. Remove the existing stretch_ctrl register and its related functions
2. Update the TX stretch state to the following
     1. tx fifo not empty
     2. acq_fifo contains only 1 entry and is a read command
     3. partial read flag is set
3. When in TX stretch date for any of these reasons, generate interrupt for software intervention
     1. the conditions that triggered the stretch will be reflected in status registers

This we believe should handle the partial access cases that have been described.

**Comment by tjaychen** [comment]
@jesultra i forgot to update the related documentation, i'll do that today.
