### ISSUE TITLE
[dv, alert_handler] Low FSM coverage in esc_timer and ping_timer

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#16588]
We are missing transitions to the error state from most states in the esc_timer and ping_timer FSMs.

This occurs as the testing for standardized countermeasures runs with a sequence that isn't stimulating the use of these state machines. Further more the state machines are likely to spend far more time in one or two states vs all the others so with purely random stimulus of countermeasures that would trigger a transition to the error state it will be rare to hit the missing transitions.

Two things are required to address this:

 - Run stimulus of the countermeasures that bring these state machines into the error state during stimulus where the state machines are being excised
 - Add functionality to the standardized countermeasures testing to enable triggering at specific points. The test bench can probe the state machines and trigger the countermeasures when it sees specific states rather than purely random triggering to ensure we hit the missing transitions.

This is related to: https://github.com/lowRISC/opentitan/issues/16572

**Comment by GregAC** [comment]
@cindychip @tjaychen any thoughts?

**Comment by cindychip** [comment]
Hey Greg,
Thanks for filing the issue. I think for any non-idle to Error state, since the error is created by standard countermeasure, we have FPV testbench to verify it will always trigger fatal alert.
I think it is safe to exclude non-idle to Error state for V2S. Do you have any concerns?

**Comment by cindychip** [comment]
Actually I think the exclusion file already excluded it: https://github.com/lowRISC/opentitan/blob/master/hw/ip_templates/alert_handler/dv/cov/alert_handler_cov_excl.el
But maybe there are some RTL change that the checksum does not match anymore.
I can update that exclusion file.

**Comment by cindychip** [comment]
I believe the coverage reached 100% with waivers. Please feel free to re-open it if you have any concerns.
