### ISSUE TITLE
[test-triage] Need for software reset at end of test in SRAM tests

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#16597]
### Hierarchy of regression failure

Chip Level

### Failure Description

We should investigate why some SRAM tests need a software reset at the end of the test in order to not time out in DV simulations, see comment here: https://github.com/lowRISC/opentitan/pull/16259#discussion_r1034558860

CC @engdoreis @sriyerg @weicaiyang @cindychip 

### Steps to Reproduce

```
util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_sleep_sram_ret_contents
```

**Comment by weicaiyang** [comment]
I will take a look soon.
