### ISSUE TITLE
[SDC] Multiple clocks on PAD

### ISSUE THREAD

**Issue by jeoongp** [lowRISC/opentitan#16594]
Is IOC6 dedicated on AST_EXT_CLK?

Two SDC commands seem to conflict as follows.
1.
set IO_BANKS [get_ports IOA*]
append_to_collection IO_BANKS [get_ports IOB*]
append_to_collection IO_BANKS [get_ports IOR*]
append_to_collection IO_BANKS [get_ports IOC*]

2. set AST_EXT_CLK_PIN IOC6

If IOC6 is not used for DIV2 or DIV4 clocks, I think we need to exclude IOC6 from IO_BANKS. Some CDC issues are caused by this conflict.

**Comment by msfschaffner** [comment]
Hm no I don't think it is dedicated. Normally, IOC6 is only used for PWM or some other GPIO - but when an external clock is needed, AST uses this pin as a clock input (the pin is connected to AST at the chip-level). So it can be used for both scenarios...

**Comment by jeoongp** [comment]
I will also ask this question to RI.

**Comment by msfschaffner** [comment]
@jeoongp do you mind posting the error message related to this?

**Comment by jeoongp** [comment]
![Screen Shot 2022-11-29 at 12 25 25 PM](https://user-images.githubusercontent.com/103145460/204640437-3bbe5997-da29-4011-a0c3-41240e013406.png)
![Screen Shot 2022-11-29 at 12 25 46 PM](https://user-images.githubusercontent.com/103145460/204640474-5833df22-50ae-49eb-a4b0-1336ee0335a7.png)

The tool seems to recognize AST_EXT_CLK as IO_BANKS group.

**Comment by tjaychen** [comment]
the ast external clock i think eventually is divided down into various other clocks inside ast.
So it does find it's way to IO_DIV4 eventually for example.

Is that the violation you are seeing?

**Comment by jeoongp** [comment]
I think this ticket is a false alarm. ^_^
The CDC violation message shows two clocks in its info column. And, IOC6 is not found in paths associated with DIV2/DIV4 clocks. Tool seems to recognize it with SDC.

**Comment by tjaychen** [comment]
sounds good. @jeoongp can we close this one down then..?
