### ISSUE TITLE
[CDC] To run RI script to resolve unrecognized signals from async_fifo 

### ISSUE THREAD

**Issue by jeoongp** [lowRISC/opentitan#16595]
Ri provided an interim script to resolve the async_fifo issue as below.
We need to run it to check if the async_fifo issue is resolved.

 === Issue description ====
We've been having some issues trying to figure out the best way to deal with a FIFO connection in our system that verixcdc does not seem to understand.

The diagram below shows the general situation.
 
![image](https://user-images.githubusercontent.com/103145460/204635563-2be884bf-9517-4513-b550-721f10c0e831.png)

The async fifo data is used to create an "error" indication using ECC. 
This error is then qualified with "valid" inside the processor to either grant or silence the next data request (it's a lot like AHB). 
I've looked over the design, and I believe everything is behaving correctly, but the tool continually flags this as W_MASYNC.

 Instead of trying to waive this by 1 by 1 (we have MANY of this type of violation), I was hoping I would be able to place a rule on the Async FIFO itself so that the tool can understand the data / error conversion is safe.

What is your recommendation for how to do this in general?
I see a few possibilities, such as 

- set_cntrl_blocking_value
- set_correlation_safe_signal
- set_user_associated_cells
- set_user_cntl_synchronizers

 Unfortunately the manual description of these controls is very bare, and in many cases it is hard to tell exactly what would work.
I have tried `set_user_associated_cells` on the async-fifo for example and that did not seem to help.

The following is the crossing path shown by the tool

top_earlgrey.u_xbar_main.u_asf_34.rspfifo.storage[3:0][0]
top_earlgrey.u_xbar_main.u_s1n_31.tl_t_p.d_error
top_earlgrey.u_rv_core_ibex.tl_adapter_host_d_ibex.err_o
top_earlgrey.u_rv_core_ibex.u_core.u_ibex_core.load_store_unit_i.data_or_pmp_err
top_earlgrey.u_rv_core_ibex.u_core.u_ibex_core.load_store_unit_i.store_err_o
top_earlgrey.u_rv_core_ibex.u_core.u_ibex_core.id_stage_i.controller_i.wb_exception_o
top_earlgrey.u_rv_core_ibex.u_core.u_ibex_core.id_stage_i.gen_stall_mem.instr_kill
top_earlgrey.u_rv_core_ibex.u_core.u_ibex_core.id_stage_i.instr_executing
top_earlgrey.u_rv_core_ibex.u_core.u_ibex_core.id_stage_i.lsu_req
top_earlgrey.u_rv_core_ibex.u_core.u_ibex_core.load_store_unit_i.data_req_o
top_earlgrey.u_rv_core_ibex.u_core.u_ibex_core.data_req_o
top_earlgrey.u_xbar_main.u_s1n_31.tl_u_o[5].a_valid
top_earlgrey.u_xbar_main.u_sm1_35.gen_arb_ppc.u_reqarb.gen_normal_case.masked_req[0]
top_earlgrey.u_xbar_main.u_sm1_35.gen_arb_ppc.u_reqarb.gen_normal_case.arb_req[0]
top_earlgrey.u_xbar_main.u_sm1_35.gen_arb_ppc.u_reqarb.data_o[32]
top_earlgrey.u_xbar_main.u_asf_34.reqfifo.storage[3:0][106:0]

**Comment by jeoongp** [comment]
I added script codes from RI in line 157 to 162 in run-cdc.tcl as follows.

set async_fifo [get_cells -hsc . -hier * -filter {ref_name == prim_fifo_async}]
catch {rm tmp.env}
set outfile [open tmp.env  w]
puts $outfile "set_data_clock_domain rdata_o -module prim_fifo_async -derived_from rvalid_o"
close $outfile
read_env tmp.env

18 new errors come up but most of the other categories seem to be similar to the existing results. 
![Screen Shot 2022-12-06 at 3 31 22 PM](https://user-images.githubusercontent.com/103145460/206051839-705f5433-9cfe-4293-9ea3-2212b528b1fb.png)

**Comment by msfschaffner** [comment]
@jeoongp does your recent update that adds the FIFO TCL script to the flow address this issue?

**Comment by jeoongp** [comment]
Yes, it's addressed in https://github.com/lowRISC/opentitan/pull/17012. Let me close this ticket.
