### ISSUE TITLE
i2c_target_intr: ack stop triggers tx_nonempty

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#16600]
use (https://github.com/lowRISC/opentitan/pull/16496)
run 
./util/dvsim/dvsim.py ./hw/ip/i2c/dv/i2c_sim_cfg.hjson -i i2c_target_ack_stop -r 1 -v m -s 1 -w fsdb

ignore error, and see @77620204ps 
'tb.dut.intr_ack_stop_o' and 'tb.dut.intr_tx_nonempty_o'

When ack_stop condition is hit, dut also set tx_nonempty interrupt too. Is this expected?

**Comment by tjaychen** [comment]
ah yes, if i'm understanding this correctly, this is somewhat orthogonal.
The `ack_stop` interrupt really is telling the software we encountered an unexpected stop condition during a read. It should be `nack-stop`, but we saw `ack-stop` instead. 

This is independent from the `non-empty` interrupt, which fires whenever a `stop` is seen with data left over in the tx_fifo.
It looks like in this case when `stop` is seen we have one entry left, hence the trigger.

Is there any reason you think this shouldn't be the case? let me know.
