### ISSUE TITLE
Make installation of vivado tools (updatemem) a non-optional part of getting started to work on FPGAs

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#16619]
As FPGA tests rely on a growing set of bitstreams it's become challenging to allow users to run FPGA tests without installing vivado tools to provide updatemem. We can run updatemem without purchasing or acquiring a license and can use it to perform necessary bitstream splices to construct a number of bitstreams necessary for FPGA tests.

We should also consider setting it up in all CI environments so that we can discontinue tools we've constructed to work around it.

- [x] Announce that it's a new requirement and work with contributors to get it set up
- [x] Update docs to reflect it's required
- [x] Update in CI
- [x] Cleanup vivado and manual tags

**Comment by drewmacrae** [comment]
Currently the installation is marked as optional and we've discussed making it non-optional in slack but I'd like to track the issue more formally here.

**Comment by a-will** [comment]
As of #16998, vivado / updatemem is no longer optional.
