### ISSUE TITLE
[test] Outstanding tasks for chip_sw_i2c_device_tx_rx

### ISSUE THREAD

**Issue by vrozic** [lowRISC/opentitan#16628]
#15700 contains the first version of the chip_sw_i2c_device_tx_rx test.
There are a few outstanding tasks to improve this test:

- [ ] Randomize the I2C instance to use for the test (see e.g. I2C host test).
- [x] Randomize the I2C target masks

**Comment by vrozic** [comment]
Randomizing I2C target masks in https://github.com/lowRISC/opentitan/pull/16728

**Comment by johngt** [comment]
Assuming that this was closed off. @vrozic could you please re-open this if this was not completed. Also tagging @andreaskurth and @vogelpi for visibility.

**Comment by vogelpi** [comment]
It's not yet finished, the randomization of the I2C is still a TODO. @vrozic confirmed that he will look into this today.

**Comment by vrozic** [comment]
Working on support for multiple instances in #16972
