### ISSUE TITLE
I2C SCL Glitches after target ACK

### ISSUE THREAD

**Issue by nixie2002** [lowRISC/opentitan#1662]
I simulated I2C IP with EEPROM model.
Usually, an I2C host holds SCL to low after a target asserts ACK.
![fnxAG](https://user-images.githubusercontent.com/56853860/75740193-6283f680-5d4a-11ea-9c52-4acecc1ff966.png)

At the simulation, after the target transmits ack signal, I2C changes its state from _PopFmtFifo_ to _Idle_.
You can see "SCL" pulse at this screenshot.
I guess FSM should be changed a little bit to handle the _PopFmtFifo case_ differently from the _stop_ case or the _idle case.

![i2c_glitches](https://user-images.githubusercontent.com/56853860/75739693-f6ed5980-5d48-11ea-8627-e1e0800c3ebb.png)
![I2C_Glithces_2](https://user-images.githubusercontent.com/56853860/75740031-f0131680-5d49-11ea-8752-8bbacf73984c.png)

Test Sequence

		tl_driver.write(i2c_reg_pkg::I2C_TIMING0_OFFSET, {tlow, thigh});
		tl_driver.write(i2c_reg_pkg::I2C_TIMING1_OFFSET, {t_f, t_r});
		tl_driver.write(i2c_reg_pkg::I2C_TIMING2_OFFSET, {thd_sta, tsu_sta});
		tl_driver.write(i2c_reg_pkg::I2C_TIMING3_OFFSET, {thd_dat, tsu_dat});
		tl_driver.write(i2c_reg_pkg::I2C_TIMING4_OFFSET, {t_buf, tsu_sto});
		tl_driver.write(i2c_reg_pkg::I2C_FIFO_CTRL_OFFSET, 32'h00000003);	// FIFO RESET
		tl_driver.write(i2c_reg_pkg::I2C_CTRL_OFFSET, 32'h00000001);		// Enable I2C Host

		@ (posedge clk_i);

		// EEPROM START (DEV : 0xA0, WR)
		start = 1'b1;
		fbyte = 8'ha0;
		tl_driver.write(i2c_reg_pkg::I2C_FDATA_OFFSET, {nakok, rcont, read, stop, start, fbyte});

		// EEPROM ADDR_MSB = 0x0
		start = 1'b0;
		fbyte = 8'h00;
		tl_driver.write(i2c_reg_pkg::I2C_FDATA_OFFSET, {nakok, rcont, read, stop, start, fbyte});

		// EEPROM ADDR_LSB = 0x0
		start = 1'b0;
		fbyte = 8'h00;
		tl_driver.write(i2c_reg_pkg::I2C_FDATA_OFFSET, {nakok, rcont, read, stop, start, fbyte});

                // EEPROM Write Data 0x0 ~ 0x9
		repeat(10) begin
			tl_driver.write(i2c_reg_pkg::I2C_FDATA_OFFSET, {nakok, rcont, read, stop, start, fbyte});
			fbyte = fbyte + 1;
		end

                // EEPROM Write Data 0xA and Stop
		stop = 1'b1;
		tl_driver.write(i2c_reg_pkg::I2C_FDATA_OFFSET, {nakok, rcont, read, stop, start, fbyte});

**Comment by sjgitty** [comment]
@igk8 @tunghoang290780

**Comment by sriyerg** [comment]
Please note that i2c is still at [V0](https://docs.opentitan.org/doc/project/hw_stages/#hardware-verification-stages) verification stage (initial planning work):
https://docs.opentitan.org/doc/project/hw_dashboard/

As such, bugs are expected to be found (and thanks for the find!). @tunghoang290780, it will be good if this can be reproduced in your testbench and have the fix verified.

**Comment by igk8** [comment]
Thank you for finding the bug. PR #1703 contains the fix.

**Comment by martin-lueker** [comment]
@igk8, @tunghoang290780: Can we close this one?

**Comment by igk8** [comment]
@martin-lueker: Yes, we can close this.

**Comment by mateenfaisal** [comment]
@igk8 please close this issue, as you answered yes to the previous question. :)
