### ISSUE TITLE
[DRAFT] RFC: Structured result output from dvsim

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#16627]
# Overview
In a nutshell, dvsim.py scrip can be divided into three main steps: 

![dvsim drawio_1](https://user-images.githubusercontent.com/65042207/204860236-ef94f895-1af5-42a9-adfd-e89f8d578d8f.svg)

Here we'll focus on the results publishing which can be divided into three main steps andpropose a refactor to improve the history traceability and allow some automatizations such as identifying opened github issues and possibly opening new issues for new failures

![dvsim drawio_2](https://user-images.githubusercontent.com/65042207/204860598-821d6662-0085-4514-8c70-63f5b2f59bfa.svg)
# Proposal
We are proposing to add two new steps to the results publishing. Rather than generating the markdown from the structured object, which discart some important informations such as **output log?**. We would generate an intermidiate json file.
Then using the json file we can input it to a markedown compiler and later to a html compiler in order to generate the current markdown and html files. The json file would also allow us ingest the results into other tools, for example a SQL database, which can be used later with a BI tool such as Metabase to build a nice and personilized dashboards using SQL queries.
 
![dvsim drawio_3](https://user-images.githubusercontent.com/65042207/205026930-43024ced-96ed-4db5-80d8-703427d0aa89.svg)

## Json format
```json
{
"Date" : "10-10-2022",
"github" : "adfe345",
"build-seed" : "983648263",
"tests" : [
  "name": "chip_sim_uart_smoke",
  "results": [
    { "seed": "485736", "result": "Passed", "log": "Test finished"},
    { "seed": "456973", "result": "Failed", "log": "Error 404"},
  ],
  "name": "chip_sim_spi_smoke",
  "results": [
    { "seed": "457965", "result": "Passed", "log": "Test finished"},
    { "seed": "245785", "result": "Failed", "log": "Error 404"},
  ],
]}
```

**Comment by moidx** [comment]
CC @rnongie who has been working on defining machine readable requirements for DVSim reports. It is probably a good idea to find some time to sync on this.

**Comment by moidx** [comment]
CC @sriyerg is also interested in reviewing the proposal. 

I would prefer to use a solution like BigQuery so that we can manage file mappings from GCS, rather than managing a database. This reference may be useful: https://cloud.google.com/bigquery/docs/external-data-cloud-storage

**Comment by sriyerg** [comment]
Aah, this is a hotly requested feature (also tracked to some extent in (the very old) htttps://github.com/lowRISC/opentitan/issues/1727. It will be good to discuss a path forward, since there are other adjacent enhancements needed to the report stage.

**Comment by andreaskurth** [comment]
As of https://github.com/lowRISC/opentitan/pull/17174, dvsim outputs reports also as machine-readable `.json`. Markdown (and thus HTML) outputs are still generated orthogonally, though https://github.com/lowRISC/opentitan/issues/17196 contains a proposal to streamline this. I thus think we can close this issue; please re-open if you disagree.

(I just found this while searching for something else; apologies for not linking that PR and issue here earlier.)
