### ISSUE TITLE
Proposal: Cache spliced bitstreams consistently in GCP bitstream cache

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#16620]
We should figure out what we're doing with https://github.com/lowRISC/opentitan/issues/16619

In addition to the synthesized bitstream, we currently cache 1 spliced bitstream in GCP, we should consider caching all or none of them. This is related to and depends upon https://github.com/lowRISC/opentitan/issues/13807 but will let users testing software rely on updatemem more consistently.

**Comment by a-will** [comment]
Closing, as we've settled on requiring Vivado for updatemem and not storing spliced bitstreams in the cache.
