### ISSUE TITLE
one bug in merge.py

### ISSUE THREAD

**Issue by openhardwarefan** [lowRISC/opentitan#1663]
In the merge.py,  the following line

    elif ip_module["size"] < ip["gensize"]:

should be
    elif ip_module["size"] < "0x%x" % ip["gensize"]:

in order to not run into issue when size field is present. With the change, it works fine.

**Comment by sjgitty** [comment]
@eunchan I assume this is under `util/topgen`

**Comment by openhardwarefan** [comment]
Yes, it's under util/topgen.

**Comment by imphil** [comment]
Thanks for this bug report @openhardwarefan. Would you mind creating a pull request with the proposed fix?
