### ISSUE TITLE
[clkmgr] Template exclusions 

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#16640]
As part of #16625 (thanks @matutem), some clkmgr exclusions were manually written to exclude nets that are not used. 
Similar to [rstmgr](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/dv/autogen/rstmgr_tgl_excl.cfg), we should auto generate these for better long term maintenance.

**Comment by andreaskurth** [comment]
Triaged for `clkmgr`. Labeling https://github.com/lowRISC/opentitan/labels/Type%3AIcebox because this seems to be a cleanup that is not necessary for M2.5.

**Comment by msfschaffner** [comment]
CC @matutem
