### ISSUE TITLE
[dv/rstmgr] Add SVA expecting rst_en_o to track resets_o

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#16641]
These assertions should be generated so they will stay correct if the various resets_o fields change. In addition, there is a flop delay between reset and rst_en, which is on the target clock, and this is well known when generating it from hjson.

> estimate 4

**Comment by jeoongp** [comment]
@matutem yeah. It's better to discuss in advance.

**Comment by jeoongp** [comment]
@matutem can you create a new PR for this prototype? I will look into it and prepare before our discussion.

**Comment by GregAC** [comment]
estimate range: 2 - 4

**Comment by msfschaffner** [comment]
this is a nice-to-have enhancement - not critical for M2.5, hence deferred.
