### ISSUE TITLE
dvsim.py: Report test status in Azure Pipelines-compatible test outputs

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1665]
The test outputs from dvrun are currently reported in Markdown for human consumption only. To report test pass/fail status from Azure Pipelines we need to provide test results in a machine-readable form. Azure Pipelines supports multiple standard formats listed at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml, with JUnit XML probably being the most widely used format.

This issue is to add such test result reporting to `util/dvsim.py`. Once we have that, we make the test results show up in the Checks for a PR.

**Comment by lenary** [comment]
Azure also parses pytest (and a few other formats) which output to stdout, if that is any help.

**Comment by johngt** [comment]
Reference for @HU90m and @engdoreis - but believe this issue is now out-dated / obsolete based on how the information is now used. If still relevant we can re-open this.
