### ISSUE TITLE
RFC: Go

### ISSUE THREAD

**Issue by gkelly** [lowRISC/opentitan#1666]
As we move forward with host-side tooling (and server software, in the slightly-more-distant future) I believe we should 1) allow Go for host-side tooling and 2) mandate it for server-side software.  This RFC seeks to measure sentiment in that regard.

@lenary for visibility.

**Comment by imphil** [comment]
Can you outline your thinking as to why this is beneficial vs. the cost of adding another language to the mix (we currently have C, C++, Rust, Python).

**Comment by eunchan** [comment]
We could use Rust for host-side tooling too, if Python is too slow.

**Comment by GregAC** [comment]
Do we plan to keep server software in this repository? I'd argue it's not so strictly related/coupled to OpenTitan the IP/Chip (even if it's being done under the umbrella of OpenTitan the project) so would be better off it it's own repository. So if that's to be in go it can be without introducing go into this repository.

As for whether we should allow go in this repository I'd echo @imphil's comments. What does it give us that our current mix doesn't?

**Comment by silvestrst** [comment]
> Can you outline your thinking as to why this is beneficial vs. the cost of adding another language to the mix (we currently have C, C++, Rust, Python).

@imphil I was about to post the same comment. I would say that unless there are strong advantages of using Go instead of other languages already used on this project, stick with what we have.

However, my experience in writing tooling is not that rich, so maybe Go is the best option.

**Comment by sjgitty** [comment]
Hi @gkelly, perhaps what is needed is a very rough "benifits of" and
"vision of" thesis
for those that might not know the benefits of the language, and ways you
see it can
play a part on the server side of the world.

**Comment by gkelly** [comment]
@lenary and I discussed this around a month ago. The decision we came to was that if Rust isn't good enough for the tooling then we're doing something wrong. I'd like to withdraw this proposal.
