### ISSUE TITLE
builtin search for hugo opentitan doc website https://docs.opentitan.org/

### ISSUE THREAD

**Issue by kbroch-rivosinc** [lowRISC/opentitan#16664]
I'm wondering if there's any interest in configuring the hugo website to support some type of local search like lunr.js?

I think this https://www.npmjs.com/package/hugo-lunr use to be a popular option but isn't really maintained.  There are other options though like:

* https://github.com/arranf/HugoToJSON
  * found from this link: https://github.com/dgrigg/hugo-lunr/issues/9
* https://github.com/tinysearch/tinysearch

I'm happy to explore the options and submit a PR, just wanted to see if there were any opinions on the matter that should be considered.

**Comment by mundaym** [comment]
Thanks for the suggestion. We've now moved to using [mdbook](https://rust-lang.github.io/mdBook/) for the documentation which has a built in search facility.

**Comment by kbroch-rivosinc** [comment]
Yes mdbook search is great thanks
