### ISSUE TITLE
The first commit introduces the ROM E2E jtag debug and inject tests (addition of shell SV sequence, addition of tests in the hjson, andother related minor updates).

### ISSUE THREAD

**Issue by Aafi11** [lowRISC/opentitan#16677]
The first commit introduces the ROM E2E jtag debug and inject tests (addition of shell SV sequence, addition of tests in the hjson, andother related minor updates). 

THe subsequent PRs are helper commits in various sections of the codebase to support the development of these tests. 

The last commit fully implements the tests in the SV sequence, and fully models the GDB / OpenOCD paths in an SV debugger model. 

Signed-off-by: Srikrishna Iyer <malik.aftab785@google.com>

__Originally posted by @sriyerg in https://github.com/lowRISC/opentitan/pull/16486__

**Comment by sriyerg** [comment]
Was this issue opened by mistake?

**Comment by sriyerg** [comment]
Closing due to insufficient information. Please provide more context and reopen if necessary.
