### ISSUE TITLE
[dv/cdc] Enable CDC instrumentation in all ips

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#16689]
The CDC instrumentation extends the areas of the chip that get tested since it randomly triggers extra cycles across CDC synchronizers. To improve the verification flow this instrumentation should be enabled for all ips and for top-level.

The missing blocks for M2.5 are
- [x] entropy_src (P1) #18743
- [x] lc_ctrl (P1) https://github.com/lowRISC/opentitan/pull/18873
- [x] otp_ctrl (P1)
- [x] rv_dm (P1) https://github.com/lowRISC/opentitan/pull/18740
- [x] spi_device (P1) https://github.com/lowRISC/opentitan/pull/18780
- [x] sram_ctrl (P1) #18830
- [x] sysrst_ctrl (P1) - see https://github.com/lowRISC/opentitan/pull/18815
- [ ] otbn (P1) - see https://github.com/lowRISC/opentitan/issues/18856
- [x] uart (P2) https://github.com/lowRISC/opentitan/pull/18896
~~- [ ] usbdev (P2)~~ this is a waived block
- [x] chip (P2)
- [x] pwm (P3) #18924
- [x] xbar_main https://github.com/lowRISC/opentitan/pull/18300
- [x] xbar_peri https://github.com/lowRISC/opentitan/pull/18300

For top level there are a number of test failures when instrumentation is enabled. These are annotated with a seed and "some" or "all" depending on whether all reseeds of the test fail.

- [x] chip_sw_i2c_device_tx_rx all seed 3288354356
- [x] chip_sw_pwrmgr_random_sleep_all_wake_ups some seed 153045692
- [x] chip_sw_pwrmgr_deep_sleep_all_wake_ups some seed 961561409
- [x] chip_sw_sysrst_ctrl_outputs some seed 3233838025
- [x] chip_sw_sysrst_ctrl_ec_rst_l some seed 901165580
- [x] chip_sw_sysrst_ctrl_ulp_z3_wakeup all seed 2382686925
- [x] chip_sw_kmac_entropy some seed 834948551 prim_sync_reqack: see issue https://github.com/lowRISC/opentitan/issues/19232
- [ ] chip_sw_power_idle_load some seed 2971420598: see issue https://github.com/lowRISC/opentitan/issues/19256
- [x] rom_e2e_boot_policy_valid_a_bad_b_good_test_unlocked0 all
- [x] chip_sw_rv_core_ibex_lockstep_glitch some seed 3689547563

Notice cdc_instrumentation causes random extra cycles, so run some iterations before declaring a block or test ready.

**Comment by andreaskurth** [comment]
I came across this while triaging `pwrmgr`. The description says CDC instrumentation is enabled for that block, so I think there's no work for `pwrmgr`. However, multiple other blocks may benefit from this, and it could be relevant for M2.5. I'm thus assigning it to M2.5.

**Comment by matutem** [comment]
The alert_handler IP has a cycle accurate scoreboard, so it has a some failures caused by the occasional extra synchronization cycle. The failures are very mild, so I will waive cdc instrumentation for alert_handler in M2.5 and I create an explicit post M2.5 issue to deal with it.

**Comment by matutem** [comment]
@andreaskurth @msfschaffner I added you to help track this work.

**Comment by msfschaffner** [comment]
#18240

**Comment by johngt** [comment]
Unsure if this is the correct place to track a regression in CDC results - but capturing here.
Overnight there was a regression in the reports - see https://reports.opentitan.org/hw/top_earlgrey/cdc/latest/report.html

**Comment by msfschaffner** [comment]
Steps to be taken for CDC enablement:
- set `run_opts: ["+cdc_instrumentation_enabled=1"]` in the `*sim_cfg.hjson` (the plusarg should already be there in most cases, but set to zero)
- run full regression at the block level and look at new failures and fix them
  -  initially, the switch `-i all_once` can be used. 
  - after fixing the issues, more seeds should be run with `--reseed N` to verify the fixes (N >= 10).
- note: most issues are likely due to cycle accurate SVAs or scoreboard checks that need to be relaxed to allow for stagger delays or stagger in mubi signals

**Comment by msfschaffner** [comment]
Thanks @marnovandermaas - looks like we didn't account for that in the tracking sheet.

**Comment by crteja** [comment]
> * [ ]  rv_dm (P1)

Enabled CDC instrumentation for RV_DM block with #18740

**Comment by crteja** [comment]
> * [ ]  spi_device (P1)

Enabled CDC instrumentation for spi_device with #18780

**Comment by andreaskurth** [comment]
Enabled CDC instrumentation for `entropy_src` in #18743

**Comment by msfschaffner** [comment]
CDC instrumentation for `sram_ctrl` is coming in #18830.

**Comment by crteja** [comment]
Enabled CDC instrumentation for `uart`([18896](https://github.com/lowRISC/opentitan/pull/18896)) and `pwm`([18924](https://github.com/lowRISC/opentitan/pull/18924))

**Comment by matutem** [comment]
The full chip failure of chip_sw_spi_device_pass_through can be reproduced in spi_device unit tests.

**Comment by GregAC** [comment]
For OTBN I have done a triaging pass on new failures seen with CDC instrumentation: https://github.com/lowRISC/opentitan/issues/19045 beyond https://github.com/lowRISC/opentitan/issues/19044 all new failures are DV environment issues. However some fixes will be required to maintain a pass rate above 90% see https://github.com/lowRISC/opentitan/issues/18856

**Comment by matutem** [comment]
It seems we could turn on CDC instrumentation for top-level: opinions?

**Comment by rswarbrick** [comment]
I feel generally positive: I don't think there are any urgent pending deadlines right now, so maybe this is a good time.  Now will give us a chance to fix anything that falls apart when we turn it on globally!

**Comment by msfschaffner** [comment]
Yeah I think I agree with that as well.

**Comment by matutem** [comment]
Only otbn is pending. Closing this issue, since otbn is tracked separately by https://github.com/lowRISC/opentitan/issues/18856.
