### ISSUE TITLE
[CDC|clock] SPI_HOST_CLK and SPI_HOST_INT_CLK

### ISSUE THREAD

**Issue by jeoongp** [lowRISC/opentitan#16705]
spi_host_int_clk and spi_host_clk are generated from combo logic + FF + buffer on IO_CLK.
It is a divide-by-2 clock separated from IO_DIV2_CLK even though both have the same clock frequency.
Here are my questions.

1. Is there any reason why we don't use the prim div2 clock generator as IO_DIV2_CLK is generated in clkmgr? 
2. Is there any reason why IO_CLK is defined as synchronous with SPI_HOST_CLK and SPI_HOST_INT_CLK in line 437 in chip_earlgrey_asic.sdc? They are not the same clock. FYI, IO_DIV2_CLK and IO_DIV4_CLK are generated from div2/div4 prim library. However, lO_CLK is defined as asynchronous with IO_DIV2_CLK and IO_DIV4_CLK.

**Comment by tjaychen** [comment]
@martin-lueker 

to the first question, I think this is because the `spi_host` can generate a range of output frequencies. See `CLKDIV` [here](https://docs.opentitan.org/hw/ip/spi_host/doc/index.html#Reg_configopts).   So the divide by 2 is just the max frequency it is able to achieve.

to the second question, This is mostly because internally to `spi_host`, the generated `spi_host_clock` isn't really a clock. It's used as a signal that is assumed to be synchronous to the module's operating clock (`IO_CLK` in this case).

**Comment by jeoongp** [comment]
@tjaychen thanks for clarification. 
For 1st question, it makes sense. 
For 2nd question, SPI_HOST_CLK is used for configuring ports as follows.

set_input_delay ${SPI_HOST_IN_DEL} [get_ports SPI_HOST_CS_L] -clock SPI_HOST_CLK -add_delay
set_input_delay ${SPI_HOST_IN_DEL} [get_ports SPI_HOST_D0]   -clock SPI_HOST_CLK -add_delay
set_input_delay ${SPI_HOST_IN_DEL} [get_ports SPI_HOST_D1]   -clock SPI_HOST_CLK -add_delay
set_input_delay ${SPI_HOST_IN_DEL} [get_ports SPI_HOST_D2]   -clock SPI_HOST_CLK -add_delay
set_input_delay ${SPI_HOST_IN_DEL} [get_ports SPI_HOST_D3]   -clock SPI_HOST_CLK -add_delay

set_output_delay ${SPI_HOST_OUT_DEL} [get_ports SPI_HOST_CS_L] -clock SPI_HOST_CLK -add_delay
set_output_delay ${SPI_HOST_OUT_DEL} [get_ports SPI_HOST_D0]   -clock SPI_HOST_CLK -add_delay
set_output_delay ${SPI_HOST_OUT_DEL} [get_ports SPI_HOST_D1]   -clock SPI_HOST_CLK -add_delay
set_output_delay ${SPI_HOST_OUT_DEL} [get_ports SPI_HOST_D2]   -clock SPI_HOST_CLK -add_delay
set_output_delay ${SPI_HOST_OUT_DEL} [get_ports SPI_HOST_D3]   -clock SPI_HOST_CLK -add_delay

SPI_HOST_CLK seem to be used as a clock from these commands, doesn't it?

**Comment by tjaychen** [comment]
right, it's used as a clock from the perspective of the pad and external components.
But internally inside spi_host, it's essentially a data signal, there is nothing clocked by it. 
So it has to remain synchronous with the actual clock inside spi_host, which is IO_CLK in this case.

**Comment by jeoongp** [comment]
Ah. It explains SPI_HOST_CLK is synchronous with IO_CLK inside spi_host and CTS/clock cell is not needed. Thanks
