### ISSUE TITLE
RFC: OpenTitan V3 Milestone - Sign-off Process

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#16724]
Please see this [docs](https://docs.google.com/document/d/1EAtjE4EZZ-jcqS2Id-STW00hgEOv_0ojE0bPBkhboQc/edit#) for the proposal.

**Comment by tjaychen** [comment]
Just a note is the title of the issue wrong? It looks like this is V3 right?

**Comment by weicaiyang** [comment]
> Is the title of the issue wrong? It looks like this is V3 right?

Good catch. I copied from the old issue, but forgot to update the title...

**Comment by weicaiyang** [comment]
closing this as it's duplicated as #13396
