### ISSUE TITLE
[dv] Investigate xprop log

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#16723]
The chip-level xprop log shows that couple hundreds statements are NO instrument-able.
As discussed in the DV meeting, we need to address these 2 things.

- [ ] Find out if these `no instrument-able` errors can be waived and come up with a guidance.
- [ ] Find out if the tool allows us to waive them with a waiver file, so that we can have a clean log.
- [ ] update xprop [document](https://docs.opentitan.org/doc/ug/dv_methodology/#x-propagation-xprop) with the guidance.

**Comment by matutem** [comment]
I found that blocking xprop at module or interface using the common hw/dv/tools/vcs/xprop.cfg means most unit compilation issues warnings for modules and interfaces mentioned in that file that the unit doesn't use.

I wonder if the hjson config supports dedicated xprop.cfg.

**Comment by weicaiyang** [comment]
> I found that blocking xprop at module or interface using the common hw/dv/tools/vcs/xprop.cfg means most unit compilation issues warnings for modules and interfaces mentioned in that file that the unit doesn't use.
> 
> I wonder if the hjson config supports dedicated xprop.cfg.

If VCS can support multiple xprop cfg files, it will be the best solution. If not, we can define a variable (call vcs_xprop_cfg_file or other similar name), each block can override it.
This approach is similar to [vcs_cov_cfg_file](https://cs.opensource.google/opentitan/opentitan/+/master:hw/dv/tools/dvsim/vcs.hjson;l=245?q=vcs.hjson&ss=opentitan%2Fopentitan:hw%2F). You can use that as an example.
