### ISSUE TITLE
[CDC|SDC|clock] create_clock in SDC

### ISSUE THREAD

**Issue by jeoongp** [lowRISC/opentitan#16738]
IO_DIV2_CLK and IO_DIV4_CLK are assigned on an output of a mux that has a constant select.
RI tool seems not to identify clock waveforms for these clocks due to muxes.  

set CLK_MUX_PATH top_earlgrey/u_clkmgr_aon/u_no_scan_io_div2_div/u_clk_mux/gen_*u_impl*
create_generated_clock -name IO_DIV2_CLK -divide_by 2 \
    -source [get_pins $_{CLK_MUX_PATH}/$_{CLK_MUX_SRC_NAME}] \
            [get_pins $_{CLK_MUX_PATH}/$_{CLK_MUX_DST_NAME}]

set CLK_MUX_PATH top_earlgrey/u_clkmgr_aon/u_no_scan_io_div4_div/u_clk_mux/gen_*u_impl*
create_generated_clock -name IO_DIV4_CLK -divide_by 4 \
    -source [get_pins $_{CLK_MUX_PATH}/$_{CLK_MUX_SRC_NAME}] \
            [get_pins $_{CLK_MUX_PATH}/$_{CLK_MUX_DST_NAME}]

I am not sure if there is any intention on this constraint. 
If not, we can assign them on buffer outputs instead of mux outputs.

**Comment by tjaychen** [comment]
yeah moving to the buffer sounds good to me.

**Comment by jeoongp** [comment]
Thanks for the background. 
I found another strange thing from the clock setting using mux.
If we use mux input and output for clock source and new clock, divide_by 2 and divide_by 4 will not work because both clock timings are the same.

**Comment by jeoongp** [comment]
This fix is in https://github.com/lowRISC/opentitan/pull/16773

**Comment by jeoongp** [comment]
Let me close this ticket as #16773 is merged
