### ISSUE TITLE
[pwrmgr] Potential improvement on escalation path to avoid crossing slow FSM

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#16735]
Hey @tjaychen and @jeoongp,

@matutem and I are going over assertions in pwrmgr and we found the escalation request:
esc_rst_req_d -> pwr_rst_o.rst_lc_req  crosses different clock domains.

Since we want to escalate as soon as possible, we want to check with you if it is necessary to cross these clock domains.

Thanks,
Cindy and Matute.

**Comment by tjaychen** [comment]
o do you mean these cross into slow domain before into the fast domain?
Yeah this is a side effect of certain reset requests that can happen during low power. When that happens, we actually need to wake the chip up and then issue the reset (I guess this is a little redundant, but at the time it was easier to keep the two FSMs in sync).

But as a result of this, all reset requests get bundled together and go through the same thing. Ie they first go through the slow domain then back into the fast domain.

**Comment by cindychip** [comment]
> o do you mean these cross into slow domain before into the fast domain? Yeah this is a side effect of certain reset requests that can happen during low power. When that happens, we actually need to wake the chip up and then issue the reset (I guess this is a little redundant, but at the time it was easier to keep the two FSMs in sync).
> 
> But as a result of this, all reset requests get bundled together and go through the same thing. Ie they first go through the slow domain then back into the fast domain.

Oh thanks for explaining! That makes sense.

**Comment by tjaychen** [comment]
maybe we want to rename this as a potential improvement?
We could restructure the fsms a bit to NOT require this.  Although we'd need to think through the implications a bit.

**Comment by cindychip** [comment]
Sure, but it is not a necessary request. We were just curious ;)

**Comment by tjaychen** [comment]
@tjaychen

**Comment by andreaskurth** [comment]
Triaged for `pwrmgr`. Relabeling https://github.com/lowRISC/opentitan/labels/Type%3AIcebox as this may be relevant for M3. From comments that this is "not a necessary request" but a "potential improvement", I think it's not needed for M2.5,

**Comment by johannheyszl** [comment]
Reading through, @tjaychen explained and @cindychip was happy with the explanation indicating there might be no further need to address. Closing this as not planned hence.
cc @vogelpi

**Comment by vogelpi** [comment]
I agree with you @johannheyszl , let's close this as not planned.
