### ISSUE TITLE
[dv] devmode related TODOs in DV

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#16739]
We have some `devmode` related TODOs in DV. The `devmode` is defined in the comportable spec, but hasn't been actually used in design.
Let's see how the design side wants to utilize it or just remove it (depends on #14063, #6104, #4902), then DV side can act accordingly.

**Comment by tjaychen** [comment]
since we've made our final decision in #14063, and are updating the documentation to reflect this in #17048, I think it is safe to kick this issue to backlog until we enable `devmode_i = 0` behavior in the future.

**Comment by weicaiyang** [comment]
> since we've made our final decision in #14063, and are updating the documentation to reflect this in #17048, I think it is safe to kick this issue to backlog until we enable `devmode_i = 0` behavior in the future.

sounds good. Thanks Tim. Let me ICEBOX it in the cip_lib.

**Comment by msfschaffner** [comment]
I am not sure we are going to change this anytime soon, hence I am closing this for now.

@moidx for viz.

**Comment by matutem** [comment]
How is this different from some of the various lc*en outputs? These are already used in various security critical IPs. I vaguely recall we also wanted to change the behavior of tlul errors for bad addresses and the such in dev vs. prod. If that is still the intention we would need this input in each comportable IP.

**Comment by msfschaffner** [comment]
Some time ago this has been discussed in the security working group, where it has been decided that we do not have to change this for the current OpenTitan use case. This has been captured in this relatively old issue here https://github.com/lowRISC/opentitan/issues/10311 which is still open for tracking.

We can reassess whether this should be changed for PROD by bringing it up in the security WG again.
