### ISSUE TITLE
[i2c] possible clock stretch / host restart

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#16731]
This is something @jdonjdon discovered that I had not thought about.

Right now, when the i2c target is being read, we stretch whenever the TX fifo is empty and need to send data back to the host.  The stretch is done after we observe the host's ack bit. 
 
Under normal circumstances, if the host intends to read no more, it will issue a NACK and then a stop.
If however, we have a situation where the host tries to send an `ack-restart`, the whole machinery will clock stretch if the tx fifo is empty.

Based on my reading of the spec, it seems implied that a nack should also precede a restart, but it doesn't look like a hard requirement.
![image](https://user-images.githubusercontent.com/1026250/206530339-29ba53a6-cb24-4735-a1bf-0fdc4fe914a8.png)

But let's say in the worst case this does not happen, we will stretch and notify software. If software realizes this is happening, it could just insert dummy bytes and let the host complete (if for example software knows how many bytes the host wants to read and it knows all has been read).

So overall, this is to me not an issue, but I want to make sure others agree.

**Comment by GregAC** [comment]
Worth a note in the documentation certainly, should maybe do some more research to see if nack before restart is commonplace/seen as a requirement.

**Comment by jesultra** [comment]
Stretching in case the I2C host defies protocol and ACK's the last byte of a read operation is how I would expect any decent I2C device to behave. I also consider this a non-issue.

**Comment by msfschaffner** [comment]
Discussed with @jesultra and @moidx - decided that this is a non-issue, hence closing.
