### ISSUE TITLE
[opentitantool, bazel, test] fpga clear_bitstream will not be executed if a test fails

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#16760]
#16759 adds the `fpga clear_bitstream` comand to `opentitantool` and adds the `clear_bitstream` parameter to `cw310_params`. Due to the way `opentitantool` handles test failures (`--exit-failure` or timeout) this command will not be executed for failing tests.

**Comment by msfschaffner** [comment]
Is this still an issue?

CC @timothytrippel @cfrantz

**Comment by timothytrippel** [comment]
I think it is still true, but I don't think it is an issue ATM, so I am closing. Feel free to reopen if needed in the future.
