### ISSUE TITLE
[CDC|SDC|clock] SPI_HOST_INT_CLK is needed?

### ISSUE THREAD

**Issue by jeoongp** [lowRISC/opentitan#16764]
Two SPI host clocks are defined in SDC : SPI_HOST_CLK and SPI_HOST_INT_CLK.
SPI_HOST_INT_CLK is just created but has no timing constraint such as delay, latency, mcp, and ports different from SPI_HOST_CLK. 
I am not sure if SPI_HOST_INT_CLK is actually needed. RI tool seems to be confused in some paths..

**Comment by tjaychen** [comment]
hmmm... i'm not sure it's needed either. 
Could we just keep `SPI_HOST_CLK` and mark that as divide by 2? 
That's what you're referring to also right?

**Comment by jeoongp** [comment]
I see. 
As I checked, all ports are also configured with SPI_HOST_CLK. So, I am not clear that SPI_HOST_INT_CLK can be also used externally.

**Comment by jeoongp** [comment]
> hmmm... i'm not sure it's needed either. Could we just keep `SPI_HOST_CLK` and mark that as divide by 2? That's what you're referring to also right?

Yes. If all ports and pads are in the sck clock generated by FSM, we can keep SPI_HOST_CLK with divide-by-2. It is currently defined as divide-by-1.

**Comment by tjaychen** [comment]
in addition to changing it to divide by 2, we probably need to update the pin master clock reference. Since right now it's referencing I think the flop, which maybe the tool won't be able to trace through.

**Comment by jeoongp** [comment]
Yes, it's referencing the flop. I agree on the pin master clock reference.
The tool is complaining about SPI_HOST_INT_CLK as follows. SPI_HOST_CLK seems OK when it comes to S_MISSING_SPEC. 
![image003](https://user-images.githubusercontent.com/103145460/206818891-cddba16e-18c4-4980-be9a-5f538a6ea660.jpg)

**Comment by tjaychen** [comment]
ugh this is so annoying. so it's complaining about this relative to ast_ext_clk.
should we just do a stop propagate on ast_ext_clk somewhere? We really don't care about ast_ext_clk muxing into all the downstream clocks. It only changes the root insertion delays slightly, everything else downstream is the same.

**Comment by jeoongp** [comment]
This fix is in https://github.com/lowRISC/opentitan/pull/16773

**Comment by jeoongp** [comment]
> this is so annoying. so it's complaining about this relative to ast_ext_clk.

This is discussed in https://github.com/lowRISC/opentitan/issues/16897.

**Comment by msfschaffner** [comment]
@jeoongp can this one be closed, now that #16773 has been merged?
