### ISSUE TITLE
[util] Improvements to bitstream_bisect.py

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#16788]
cc @drewmacrae 

* [ ] Make the "fast" command optional. 
   In this mode, the script should start a git bisect session, `git bisect skip` each commit with a cached bitstream, and drop the user into the session.
* [ ] Enable passing `BITSTREAM=$commit` to each invocation of the fast command.
    The fast command should only be invoked on commits that are cached, but this would improve assurance that we're actually using the correct bitstream. TODO: Verify that `BITSTREAM=c1` causes a failure when `c1` is not in the cache.
* [ ] Figure out what to do when `git bisect run` can't run any tests. Exit successfully? Nicer error message?
* [ ] Add a canary command for detecting FPGA flakiness.

**Comment by msfschaffner** [comment]
CC @a-will @timothytrippel @cfrantz

**Comment by timothytrippel** [comment]
I don't think this tool is actively being used anymore. Closing this for now, can be re-opened in the future if needed.
