### ISSUE TITLE
[flash_ctrl] Verify hw info page attribute disable

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#16812]
#16799 adds the ability for software to slightly tweak the currently hardwired hardware info page access attributes.
Primarily, this gives software the ability to decide whether creator seed / owner seed / isolated pages need to have scrambled or ecc turned on (they are hardwired on by default).

This just gives software a little bit of flexibility in case something goes wrong. We need to add a directed test case to verify this. 

> estimate 8

**Comment by msfschaffner** [comment]
@tjaychen I believe this should have been assigned to @jdonjdon, right?

**Comment by tjaychen** [comment]
ah yes that is right.

**Comment by jdonjdon** [comment]
@tjaychen , @msfschaffner 
Just to be clarify, this config override only applies to the request initiated by HW. (read,write creator seed / owner seed).
I think isolated partition can be accessed by SW request except rma. But rma does 'erase', so ecc/scramble doesn't really matter.
WDYT?

**Comment by GregAC** [comment]
estimate range: 4 - 8

**Comment by jdonjdon** [comment]
Resolved with #18048
