### ISSUE TITLE
//sw/device/tests:alert_handler_reverse_ping_in_deep_sleep_test fails on workstations but not CI

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#16822]
```
bazel test //sw/device/tests:alert_handler_reverse_ping_in_deep_sleep_test_fpga_cw310_test_rom
```
hangs and times out on my workstation,

Further instrumenting the code shows:
a classa alert is firing
the interrupt isn't cleared by the isr so it hangs.

If I call check_local_alerts() in the ISR, it doesn't identify a cause, so I'm not sure why the class a alert fires in the first place.
I can write a check_alerts() function that identifies it as alert ID 37 which I think is a FlashCtrlFatalErr

**Comment by drewmacrae** [comment]
I00006 alert_handler_reverse_ping_in_deep_sleep_test.c:217] Flash ctrl faults: 2  
Which corresponds with a lifecycle memory permission error

**Comment by drewmacrae** [comment]
https://github.com/lowRISC/opentitan/pull/16683/commits/2de04c75407faac1836c584eb20586a4a89f35df shows where I'm instrumenting the test. I'll clean it up before setting it as ready for review.

**Comment by drewmacrae** [comment]
Hmm, flash_ctrl.[ERR_ADDR](https://docs.opentitan.org/hw/ip/flash_ctrl/doc/#Reg_err_addr) @ 0x188 The error address doesn't appear to be written for this kind of mp_error.

**Comment by drewmacrae** [comment]
There's no programmer's guide for this error and I'm not quite sure what the error is for or why it might be happening.

**Comment by drewmacrae** [comment]
Bisecting this points me to: da28430b27aa27f33a3e11ade1cf2132d2a03d68 [flash_ctrl] Fix hardware info page attribute

**Comment by drewmacrae** [comment]
The bisecting that didn't make sense was running the wrong bitstream, only updating when crossing changes to bitstream_workspace.py and rules/bitstream.bzl which explains the bisection weirdness pretty well so I'm happy but still baffled about this particular bug and why it doesn't appear in Ci

**Comment by drewmacrae** [comment]
Disabling scrambling set in da28430 makes this test pass. Somehow it looks like scrambling is causing a mp_error in the flash_ctrl that's related to lifecycle somehow.

**Comment by tjaychen** [comment]
the main change in that PR is now that the hardware attributes are expecting both scramble and ECC.  So if those partitions are programmed / preloaded by software, they must be done using the same attributes setup otherwise the hardware readback will fail.

Is this test attempting to do that..? 

But I guess more importantly, any guesses as to why it would fail locally but pass on CI? What's different?

**Comment by drewmacrae** [comment]
I couldn't engineer a case where this one passes like I could for https://github.com/lowRISC/opentitan/issues/16576 but I'd expect there's a previous test with a side effect similar to the one that makes it pass.

**Comment by tjaychen** [comment]
do you know how the flash info page contents are populated for these tests? 
If nothing is done by default, they would probably be all F's.  If that's the case, we need to set the otp such that they are NOT read by the hardware. If the hardware OTP is setup to read them, yet they are not populated with valid content, the read will definitely fail.

**Comment by drewmacrae** [comment]
I don't, but I can look into it, Thanks!

**Comment by drewmacrae** [comment]
> Bisecting this points me to: [da28430](https://github.com/lowRISC/opentitan/commit/da28430b27aa27f33a3e11ade1cf2132d2a03d68) [flash_ctrl] Fix hardware info page attribute

In retrospect my bisection is affected by stale bitstreams being cached because of this issue: https://github.com/lowRISC/opentitan/issues/16925

So it may be ROM changes in commits preceding this one that are then provided in the cache when this one ran through CI.

**Comment by moidx** [comment]
Unable to reproduce on HEAD=bf38cd49e36896c352453d38710c18b7c0243ab9
