### ISSUE TITLE
NTIL (Vendor) PRs that waits for approval & merge

### ISSUE THREAD

**Issue by Jacob-Levy** [lowRISC/opentitan#16821]
At the moment, there are PRs in the system (uncheckd) that was reviewed but wait to be approved and merged:

- [ ] V [util, top] Add ANALOGSIM macros for chip_earlgrey_asic #16669 - reopen 2022/12/04
       X [TOP] ANALOGSIM macro-base solution #5875 - closed 2022/09/21
       X [TOP] Add ANALOGSIM define code #5729 - closed  2021/03/31
       
- [x] V [ast] Update D2S review comments #16784 - opened 22/12/12

     Thanks @msfschaffner!

@arnonsha @sha-ron @tjaychen @msfschaffner

**Comment by moidx** [comment]
It seems all PRs have been either closed or merged. Please reopen if there is any work still left here.
