### ISSUE TITLE
[chip-test] chip_sw_plic_alerts

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#16835]
### Test point name

[chip_sw_plic_alerts](https://github.com/lowRISC/opentitan/blob/316831f8c2199f2288dd57ac4aeaec3334b5dfb8/hw/top_earlgrey/data/chip_testplan.hjson#L859)

### Host side component

SystemVerilog

### OpenTitanTool infrastructure implemented

None

### Contact person

sriyerg

### Checklist

This is cross-filed in #15649. The `all_escalation_resets` test needs to be enhanced to cover these. 

> estimate 8

**Comment by andreaskurth** [comment]
Triaged for `rv_plic`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2 because we need this missing TLT to verify alerts coming from `rv_plic`, for which we don't have block-level DV.

**Comment by moidx** [comment]
@msfschaffner to cross reference relevant tests.

**Comment by moidx** [comment]
Closed as duplicate of https://github.com/lowRISC/opentitan/issues/17413.
