### ISSUE TITLE
[hmac/assertion] corner case for ValidHashProcessAssert fail

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#1684]
Hi Eunchan, 

My simulation `hmac_stress_all_with_rand_reset` test failed due to assertion error on a very corner case:
reset issued right when I set `cmd` register's `hmac_process` field to 1. As you can see from the screenshot:
![image](https://user-images.githubusercontent.com/11466553/75928978-6c7a2800-5e24-11ea-8f36-3b4cf09f0dd6.png)

I think since reset is async, if you confirm the RTL behavior is correct, I think we can change the assertion to ignore the first cycle when `rst_ni=0`:
```
  `ASSERT(ValidHashProcessAssert, ##1 reg_hash_process |-> initiated)
```

Simulation path:
/edascratch/chencindy-opentitan/scratch/hmac.sim.vcs/master/failed/0.hmac_stress_all_with_rand_reset
verdi -ssr Verdi.ses

Please let me know what you think.

Thanks,
Cindy

**Comment by eunchan** [comment]
Hum.. This cannot happen in the real simulation as when `rst_ni` asserted, the TL-UL valid will be dropped. But the change is okay to me. Thanks for finding this!

**Comment by cindychip** [comment]
Thanks for the feedback Eunchan! Yeah I think the tool take reset as async mode, but keeping the values from `reg_hash_process` and `initiated` as blocking assignment, thus have this assertion error. I will make a PR to enhance this soon.

**Comment by cindychip** [comment]
As Eunchan mentioned, this issue is illegal case for TL access. And Weicai's PR: https://github.com/lowRISC/opentitan/pull/1699 can fix it.

**Comment by cindychip** [comment]
Thanks Eunchan, this is illegal sequence that should not happen in the real simulation. (d_valid / a_valid stayed high after reset), Weicai fixed this with PR: https://github.com/lowRISC/opentitan/pull/1699
