### ISSUE TITLE
[kmac] Expecting error after clearing sideload key

### ISSUE THREAD

**Issue by gdessouky** [lowRISC/opentitan#16855]
When KMAC is configured in sideload mode, and it receives an invalid key at the sideload port after clearing (see test #16492), this ought to be indicated in the `ERR_CODE`, also in line with the documentation https://docs.opentitan.org/hw/ip/kmac/doc/#keynotvalid-0x01.

This doesn't happen however probably because it is a SW-initiated operation, although the sideload key is invalid. It is probably consuming that invalid (random) key generated at the sideload port to compute the digest. Is this intentional but an error/ambiguity in the documentation or a bug in the error reflection in `ERR_CODE` ?

cc @ballifatih @johannheyszl  @cindychip @eunchan @jadephilipoom

**Comment by ballifatih** [comment]
We had an offline discussion with @gdessouky, and the issue might be due to `kmac_app` FSM not checking `valid` bit of the sideload key within `StSw` state.

Here is waveform from kmac sideload test where we try to use the sideload key after clearing (`st` is the FSM of `kmac_app`):
![Screenshot from 2022-12-15 15-43-09](https://user-images.githubusercontent.com/7850700/207910431-c8bc4a82-64eb-4b2b-9dec-868446427a97.png)

**Comment by tjaychen** [comment]
ah good catch, it does seem like it should be error'd out. Unless we explicitly decided at some point to make it somewhat "hidden" (although we don't do the same with the app interface...).

@cdgori / @eunchan do you have any recollection here? I feel like an error would be better here.

**Comment by cdgori** [comment]
No specific recollection, but it seems as if it should be an error to me as well.

**Comment by tjaychen** [comment]
@vogelpi / @eunchan i'm not completely sure who is handling kmac D3 right now, but would this be a pretty simple fix?

**Comment by ballifatih** [comment]
Marking this as P1, because if an attacker clears the sideload port and then initiates a KMAC operation, then it can leak information on keymgr's internal LFSR state.

It is better to prevent his altogether rather than doing the security analysis of "What can go wrong if an attack recovers LFSR state".

**Comment by cindychip** [comment]
Related issue: https://github.com/lowRISC/opentitan/issues/14596

**Comment by cindychip** [comment]
I believe there is a smiliar issue reported here:  https://github.com/lowRISC/opentitan/issues/10704

**Comment by ballifatih** [comment]
AFAIU by reading the code, the key coming form keymgr is not flopped in KMAC until it reaches to `prim_slicer` inside `kmac_core`. Therefore, I think it is better to check that valid bit remains high throughout the operation (assuming this is not too difficult to implement). My understanding is that #10704 is also converging to this decision.

Normally, sideload/keymgr key valid bit should not go down, except (1) there is a fault injection (2) SW reconfigures keymgr before kmac is done. In either case, I would be OK with kmac hanging or raising an error. I do not see why KMAC is expected to provide a garbage output here, as suggested in #14596. In fact, providing garbage to SW makes it harder to debug. I wonder if I am missing some good security argument here though.

**Comment by johannheyszl** [comment]
Sounds very reasonable to me @ballifatih and nice to see it closes two more issues :)

**Comment by gdessouky** [comment]
Summarizing offline discussion with @ballifatih:  a security argument for providing garbage/random output when keymgr `key_valid` bit goes down is to make an FI attack harder. If an attacker can inject a fault that de-asserts the `key_valid` signal, and gets an indication of the error/hanging behavior, this "helps" the attacker; the attacker knows it was successful and now knows how to inject a fault on that `key_valid` signal. 
Random output obscures that from the attacker. So you gain some on the security (but through obscurity), but you also lose a lot of usability/debuggability as @ballifatih already points. I also agree that the way to go is to not latch in a wrong/random/old key and to indicate an error if the `valid` signal is de-asserted for whatever reason. 

This issue [#17437 ](https://github.com/lowRISC/opentitan/issues/17437) discusses the similar trade-off with communicating OTP scrambling keys and nonces to OTP users.

**Comment by moidx** [comment]
Moving to M2.5.Backlog, for consideration for M3. Priority to be reassessed then.

**Comment by cdgori** [comment]
Commenting only to echo / reinforce the comments of @gdessouky who described the advantage of garbage/random output for this situation.

I would suggest that the minimum we should do is the proposed check that `valid` is not deasserted, if we end up considering this in-scope for M3.

**Comment by msfschaffner** [comment]
@vogelpi can you take a look at this one as well (since you're dealing with some KMAC updates at the moment)?

**Comment by vogelpi** [comment]
Sounds good to me, I'll make sure this is taken care of. Whether this is a TLT or block-level DV (with coverage) can still be discussed when we get closer to M3.

**Comment by johngt** [comment]
@vogelpi - removing RTL as remaining effort is on DV side. Assume this is still security focused rather than needing to go to M4?

**Comment by andreaskurth** [comment]
This is actually still RTL and DV.

**Comment by andreaskurth** [comment]
PR #22794 will address the RTL side of this; some DV work to cover this will be added to M4.

**Comment by vogelpi** [comment]
Most of the work here has been covered by https://github.com/lowRISC/opentitan/pull/22794. I've now filed #22956 to track the DV extension to cover the sideload key becoming invalid in any possible FSM state.
