### ISSUE TITLE
[CDC] static signals reported by tool

### ISSUE THREAD

**Issue by jeoongp** [lowRISC/opentitan#16861]
Here is the list of constant signals reported by the tool. Retention and unused regs are excluded.
I think some of them can be optimized out after synthesis. 
Can you take a look and confirm? 

1) spi_device
![Screen Shot 2022-12-15 at 11 27 16 AM](https://user-images.githubusercontent.com/103145460/207950032-a6d472ec-ec86-409b-99b6-4b03660060be.png)

2) lc_ctrl
![Screen Shot 2022-12-15 at 11 28 46 AM](https://user-images.githubusercontent.com/103145460/207950068-1170878c-e7be-4703-9e03-80fe35f4217e.png)

3) rv_dm
![Screen Shot 2022-12-15 at 11 29 51 AM](https://user-images.githubusercontent.com/103145460/207950142-f3467d34-2c5a-41c4-962f-99c3acd2dde9.png)

4) rv_core
![Screen Shot 2022-12-15 at 11 31 40 AM](https://user-images.githubusercontent.com/103145460/207950706-a32a12bd-9de7-4849-b5df-c6417e8116a9.png)

5) etc.
![Screen Shot 2022-12-15 at 11 33 35 AM](https://user-images.githubusercontent.com/103145460/207950743-139f869f-527d-4a25-a22c-be8b1aeb8d41.png)

**Comment by tjaychen** [comment]
> Here is the list of constant signals reported by the tool. Retention and unused regs are excluded. I think some of them can be optimized out after synthesis. Can you take a look and confirm?
> 
> 1. spi_device
>    ![Screen Shot 2022-12-15 at 11 27 16 AM](https://user-images.githubusercontent.com/103145460/207950032-a6d472ec-ec86-409b-99b6-4b03660060be.png)
> 2. lc_ctrl
>    ![Screen Shot 2022-12-15 at 11 28 46 AM](https://user-images.githubusercontent.com/103145460/207950068-1170878c-e7be-4703-9e03-80fe35f4217e.png)

This looks good to me. These are diverisification values, and we only have a limited set of them. 

> 3. rv_dm
>    ![Screen Shot 2022-12-15 at 11 29 51 AM](https://user-images.githubusercontent.com/103145460/207950142-f3467d34-2c5a-41c4-962f-99c3acd2dde9.png)
> 4. rv_core
>    ![Screen Shot 2022-12-15 at 11 31 40 AM](https://user-images.githubusercontent.com/103145460/207950706-a32a12bd-9de7-4849-b5df-c6417e8116a9.png)
> 5. etc.
>    ![Screen Shot 2022-12-15 at 11 33 35 AM](https://user-images.githubusercontent.com/103145460/207950743-139f869f-527d-4a25-a22c-be8b1aeb8d41.png)

The flash control ones are good. The program path does not ever read, so the response fifo is tied off.
Same with spi host adapter_tx.
The spi Host qd stuff is okay, it seems the qd was defined with an extra bit, it's just not useful in this case.

For rv_plic, bit 0 is explicitly tied to 0, so those are okay. I'm not completely sure why this was done like this, but for now let's not worry about this.

**Comment by jeoongp** [comment]
@tjaychen Thanks for review!

**Comment by tjaychen** [comment]
@eunchan can you have a look at the spi device ones? 
@msfschaffner can you have a look at the rvdm ones?

**Comment by eunchan** [comment]
yep. SPI_DEVICE list looks good. Some of them are TPM_CAP (constant read-only) and some of them are unused (ptr[15:13])

**Comment by msfschaffner** [comment]
the RV_DM ones look OK as well (they are all set to zero on purpose inside `dm_csrs`).

**Comment by jeoongp** [comment]
Thanks all!

**Comment by msfschaffner** [comment]
Are we ok with these paths or is further review required? If not, let's close the issue :).

**Comment by tjaychen** [comment]
i think we're good, we reviewed all of them right?

**Comment by jeoongp** [comment]
Yes. They are reviewed and committed in https://github.com/lowRISC/opentitan/pull/16842.
Let me close this ticket.
