### ISSUE TITLE
alert_handler_reverse_ping_in_deep_sleep_test.c has an interrupt handler that hangs

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#16864]
In #16822 I debugged a hanging interrupt handler:

 Rather than triggering a test failure, the [external interrupt handler in alert_handler_reverse_ping_in_deep_sleep_test.c](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/tests/alert_handler_reverse_ping_in_deep_sleep_test.c;drc=db5c8367b0474e7cad215db8dc0ad6ad1271cacb;l=178) doesn't claim the interrupt before returning so the test hangs.

**Comment by moidx** [comment]
Hi @drewmacrae, where is the test hanging? The test will probably take hours to run in Verilator. It currently takes 3h to run in VCS. It takes this long because the timeout parameter we are testing is hardcoded in the RTL.

**Comment by drewmacrae** [comment]
I hit this on the CW310, I wrote #16903 to help debug the test. While the test was only intended to fail on some firings of the interrupt handler, it only recorded that the interrupt had occurred, so the interrupt handler was never exited and if it fired, would never be reported or allow the test to complete as a pass or a failure.

**Comment by a-will** [comment]
So this passed with bitstream from 482b20d350cb5b6e1243fc4a9334abb480050acb and 6ac47369d86ae7d2a207c92d3500c23197d04961 for the git hash. Are we still seeing failures? (for the CW310)

**Comment by moidx** [comment]
I was able to reproduce the failure. Pending fix in https://github.com/lowRISC/opentitan/pull/18205.
