### ISSUE TITLE
[top_darjeeling] Top level block diagram

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#16884]
### desc

Create top level block diagram for Darjeeling

**Comment by tjaychen** [comment]
Please see [block diagram](https://docs.google.com/drawings/d/1NrABKUmRhggVorIEBScdc01AxGl7rOelX8tgkbmkX44/edit?usp=share_link) and [integration diagram](https://docs.google.com/drawings/d/1uZuxPiKDEImJT92CKgGh3_PfiG-rDeZejY3twkxIv5s/edit?usp=share_link)

**Comment by msfschaffner** [comment]
This has been done [here](https://docs.google.com/document/d/1jGeVNqmEUEJcmOfQ0mEZ_E8pG-RYovtVMelVTQZECcA/edit#heading=h.4urr3p1n50ic) (restricted audience for now).
