### ISSUE TITLE
[top_darjeeling] Finalize high priority dma dataflows for Darjeeling

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#16885]
### desc

Finalize the P0 dataflows for Darjeeling dataflow.
These are currently:

- code load and hashing
- general memory to memory movement
- memory to/from low speed peripherals such as SPI

**Comment by tjaychen** [comment]
Please see additional slides on [DMA / memory encryption proposal](https://docs.google.com/presentation/d/1_AWOkbQCEb0j_QAcuDJjFF4Uch6y8F-CTsmjJZDHi0k/edit?usp=sharing)

**Comment by msfschaffner** [comment]
I believe this has been addressed by now in the spec.
Let me know if we should reopen this issue.
