### ISSUE TITLE
C Application Flow in Opentitan

### ISSUE THREAD

**Issue by ladmangesh805** [lowRISC/opentitan#1688]
Is anyone know flow of C application in Opentitan ??

**Comment by silvestrst** [comment]
Could you please expand on what you are interested in more detail? Description of a problem, and maybe bullet points of what you would like to find out would be useful. Thanks.

**Comment by ladmangesh805** [comment]
Thanks @silvestrst 
In opentitan we have c programm https://github.com/lowRISC/opentitan/tree/master/sw/device/examples/hello_world

I want to understand how this secure c program get executed .
Is it depends on SHA2 (Any Hashing function) or not ??
I am just changing SHA2 with SHA3 then what will be effects on C Application?

**Comment by silvestrst** [comment]
The boot process consists of two stages, [Boot ROM](https://github.com/lowRISC/opentitan/tree/master/sw/device/boot_rom) does some minimal peripheral initialisation, loads a binary to flash if necessary and then jumps into flash. The binary can be the `hello_world` that you have pointed to in your previous post, it can be one of the tests that are under the `sw/device/tests`. A binary is loaded through SPI frame by frame, on the target hash is calculated on each frame, and is sent back to the host. This is described in the link I have provided above.

OpenTitan project is in development stage, in the production devices the Boot ROM will be backed into the chip. For the development purposes we use the [NexysVideo FPGA](https://docs.opentitan.org/doc/ug/getting_started_fpga/) or [Verilator](https://docs.opentitan.org/doc/ug/getting_started_verilator/) for simulation purposes.

I would suggest you have a look at [the documentation](https://docs.opentitan.org/doc/ug/) in general.

**Comment by ladmangesh805** [comment]
Thanks @silvestrst 
I am started working on .

**Comment by silvestrst** [comment]
@ladmangesh805 no problem, glad I could help :)
