### ISSUE TITLE
[e2e] Test regression: sigverify_mod_exp_rma_otbn_fpga_cw310_rom

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#16916]
Steps to reproduce:
```
git checkout 3894081bc2102de8ec467075d8532de985e9c0c8
./bazelisk.sh test //sw/device/silicon_creator/rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom
```

Bisect command:
```
/bazelisk.sh run //util/fpga:bitstream_bisect -- --good 09bd12891a50bca984e7cd8f4c2aadc99e6eb93e --bad 2f112c50d9ed8d9e25c9876b26eb57a76651e96e --fast-command './bazelisk.sh test //sw/device/silicon_creator/
rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom'
```

Relevant output from bisecting: 
```
The first bad commit could be any of:
24053071ebf8a7f3c8971b4d7f6b6a7089cb3181
1fb7299bb6266a44eb48d86ed7cd75c37faa9546
256bf762af20c9f612891362e34e46b76336bf76
2f112c50d9ed8d9e25c9876b26eb57a76651e96e
We cannot bisect more!
```

I'm pretty sure we can exonerate all but one: 

* ~~24053071ebf8a7f3c8971b4d7f6b6a7089cb3181~~ only touches doc/
* ~~1fb7299bb6266a44eb48d86ed7cd75c37faa9546~~ only touches util/dvsim/
* ~~256bf762af20c9f612891362e34e46b76336bf76 touches hw/ip/i2c/{data,dv}~~ (**Edit**: per discussion with @jdonjdon, this commit is now exonerated, too.)
* ~~2f112c50d9ed8d9e25c9876b26eb57a76651e96e~~ only touches ci/azure-pipelines-nightly.yml

@jdonjdon Is it plausible that 256bf762af20c9f612891362e34e46b76336bf76 caused this test regression? It doesn't really make sense to me since it looks like the commit only changes dv-related code and the regression is a functest.

FYI @alphan, since I think you're the author of the test.

**Comment by jdonjdon** [comment]
@dmcardle, not familiar with this test, but https://github.com/lowRISC/opentitan/commit/256bf762af20c9f612891362e34e46b76336bf76
is basically systemverilog testbench update.
I was always wondering why testbench file change triggers fgpa build

**Comment by dmcardle** [comment]
It sounds like the results of this bisect may be bogus. I'm not sure why.

> I was always wondering why testbench file change triggers fgpa build

@jdonjdon, I think the best way to answer that is with a dependency graph :) The e2e test transitively depends on `//hw/ip/i2c/data:all_files`, at least when the Bazel args contain `--define bitstream=vivado` or `--define bitstream=gcp_splice`.

![e2e_dependency](https://user-images.githubusercontent.com/183652/208984383-f5acb104-5227-49ae-a23a-8c4da7dab5b0.svg)

**Comment by drewmacrae** [comment]
I can't reproduce this failure: //sw/device/silicon_creator/rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom PASSED in 1.9s

at master and 3894081bc2102de8ec467075d8532de985e9c0c8

**Comment by dmcardle** [comment]
Bizarre! I just reproduced it again on 3894081bc2102de8ec467075d8532de985e9c0c8.

I tried resetting the FPGA and it still reproduces.

```
./bazelisk.sh run //sw/host/opentitantool -- fpga clear-bitstream
./bazelisk.sh run //sw/host/opentitantool -- fpga reset-sam3x
```

For good measure, I just ran `./bazelisk.sh shutdown` and it still reproduces.

This is the output I get, minus the stack trace.

```
./bazelisk.sh test --cache_test_results=no --test_output=streamed //sw/device/silicon_creator/rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom
Starting local Bazel server and connecting to it...
INFO: Invocation ID: b5d26a24-1a6e-48fd-9ac0-8b771402f240
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
INFO: Analyzed target //sw/device/silicon_creator/rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom (356 packages loaded, 14351 targets configured).
INFO: Found 1 test target...
Invoking test: sw/host/opentitantool/opentitantool --rcfile= --logging=info --interface=cw310 --exec=fpga load-bitstream --rom-kind=rom sw/device/silicon_creator/rom/e2e/bitstream_sigverify_mod_exp_rma_otbn.bit --exec=bootstrap --clear-uart=true sw/device/silicon_creator/rom/e2e/empty_test_sigverify_mod_exp_fpga_cw310.fake_prod_key_0.signed.bin --exec=console --exit-success='use_sw_rsa_verify=0x000001d4' --exit-failure='((FA
IL|FAULT).*\n)|(BFV:[0-9a-f]{8})' no-op
[2022-12-21T19:21:18Z INFO  opentitantool::command::load_bitstream] Loading bitstream: "sw/device/silicon_creator/rom/e2e/bitstream_sigverify_mod_exp_rma_otbn.bit"
[2022-12-21T19:21:18Z INFO  opentitanlib::util::usr_access] Bitstream file USR_ACCESS value: 0x9063a9dd
[2022-12-21T19:21:18Z INFO  opentitanlib::util::rom_detect] Current bitstream: "ROM:9063a9dd\r"
[2022-12-21T19:21:18Z INFO  opentitanlib::transport::cw310] Already running the correct bitstream.  Skip loading bitstream.
[2022-12-21T19:21:18Z INFO  opentitantool] Command result: success.                                                                                                                                                                                                                                                                                                                                                                         [2022-12-21T19:21:18Z INFO  opentitanlib::bootstrap] Asserting bootstrap pins...
[2022-12-21T19:21:18Z INFO  opentitanlib::app] Asserting the reset signal
[2022-12-21T19:21:18Z INFO  opentitanlib::app] Clearing the UART RX buffer
[2022-12-21T19:21:18Z INFO  opentitanlib::app] Deasserting the reset signal
[2022-12-21T19:21:18Z INFO  opentitanlib::bootstrap] Performing bootstrap...                                                                                                                                                                                                                                                                                                                                                                [2022-12-21T19:21:20Z INFO  opentitanlib::bootstrap] Releasing bootstrap pins...
[2022-12-21T19:21:20Z INFO  opentitanlib::app] Asserting the reset signal
[2022-12-21T19:21:20Z INFO  opentitanlib::app] Deasserting the reset signal
[2022-12-21T19:21:20Z INFO  opentitantool] Command result: success.
Starting interactive console
[CTRL+C] to exit.

[2022-12-21T19:21:20Z INFO  opentitanlib::io::uart] set_flow_control to false
ROM:9063a9dd
bootstrap:1
ROM:9063a9dd
BFV:02495202
LCV:2739ce73
ROM:9063a9dd


Exiting interactive console.
[2022-12-21T19:21:20Z INFO  opentitantool::command::console] ExitFailure("BFV:02495202")
[2022-12-21T19:21:20Z INFO  opentitantool] Command result: Matched exit_failure expression
```

**Comment by jdonjdon** [comment]
> It sounds like the results of this bisect may be bogus. I'm not sure why.
> 
> > I was always wondering why testbench file change triggers fgpa build
> 
> @jdonjdon, I think the best way to answer that is with a dependency graph :) The e2e test transitively depends on `//hw/ip/i2c/data:all_files`, at least when the Bazel args contain `--define bitstream=vivado` or `--define bitstream=gcp_splice`.
> 
> ![e2e_dependency](https://user-images.githubusercontent.com/183652/208984383-f5acb104-5227-49ae-a23a-8c4da7dab5b0.svg)

That explains. thx. This might be separate issue but we can exclude hw/ip/i2c/*_testplan.hson for all hw/ip if possible

**Comment by drewmacrae** [comment]
I see what you're seeing now, and none of the stuff I'd expect to fix it works.

**Comment by drewmacrae** [comment]
I also see this on 1566a2ae73462c7ba3272cc70e60800774afdb04 where I can get a bitstream from the cache

**Comment by alphan** [comment]
Just saw this, looking...

**Comment by alphan** [comment]
cc @jadephilipoom

**Comment by alphan** [comment]
could this be a merge skew with b9d0fb5c3cbaaf848c10f06c870a5cd0cb304599?

**Comment by drewmacrae** [comment]
The first commit I see this on is https://github.com/lowRISC/opentitan/commit/6822f12051695de4464988b158b98dd48660fb32

**Comment by alphan** [comment]
`BFV` indicates an illegal instruction, which suggests we are triggering our countermeasures, probably `sec_mmio` expectations. I confirmed that execution reaches `sigverify_mod_exp_otbn()` but fails somewhere inside.

**Comment by drewmacrae** [comment]
This first appears with https://github.com/lowRISC/opentitan/pull/16900 which was rebased onto a commit that also got built and tested @milesdai could this have affected the bitstream in the cache?

**Comment by alphan** [comment]
> The first commit I see this on is [6822f12](https://github.com/lowRISC/opentitan/commit/6822f12051695de4464988b158b98dd48660fb32) It's probably worth seeing if a subsequent run on vivado fails like this, so we know if the bitstream synthesis is flaky here.
> 
> ```
> ./bazelisk.sh test //sw/device/silicon_creator/rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom --define bitstream=vivado
> INFO: Invocation ID: 0251e26b-5b41-4983-b723-346e6efdb0f6
> INFO: Build option --define has changed, discarding analysis cache.
> ERROR: /usr/local/google/home/drewmacrae/review/hw/bitstream/BUILD:90:10: in filegroup rule //hw/bitstream:otp_mmi: non-test target '//hw/bitstream:otp_mmi' depends on testonly target '//hw/bitstream/vivado:otp_mmi' and doesn't have testonly attribute set
> ```

We should fix this but I'm surprised that we didn't hit this before. Where did you see this error? 6822f12051695de4464988b158b98dd48660fb32's cw310 bitstream step seems to be ok.

**Comment by dmcardle** [comment]
@drewmacrae Is this happening on Bazel 5.1.1 or possibly were you using a newer version?

**Comment by alphan** [comment]
Not sure if this is a red-herring but I was able to track this down to the `sec_mmio_check_counters()` call in `rom_boot()`. `expected_write_count` is `0x1e` while `write_count` is `0x1f` (off-by-one). I have a hard-stop at 17:30 (ET) but I might be able to look at this later in the day.

**Comment by alphan** [comment]
Yes, we are missing `SEC_MMIO_WRITE_INCREMENT(kOtbnSecMmioExecute)` after `otbn_execute()` in `mod_exp_otbn.c`. I'll create a PR shortly but we should understand why the CI didn't catch this in b9d0fb5c3cbaaf848c10f06c870a5cd0cb304599 and its PR #16859.

**Comment by alphan** [comment]
Silly question but shouldn't the command in `run-fpga-cw31-tests.sh` include `--bitstream=gcp_splice`? Or is this handled elsewhere?

**Comment by dmcardle** [comment]
> Silly question but shouldn't the command in `run-fpga-cw31-tests.sh` include `--bitstream=gcp_splice`? Or is this handled elsewhere?

Good question. I believe the answer is no, because that script injects  bitstreams and MMI files into the cache [[cs]](https://cs.opensource.google/opentitan/opentitan/+/master:ci/scripts/run-fpga-cw310-tests.sh;l=30-34;drc=d83e222dee41995fcbe7afffae7eb4d75a360aaa). As a result, `//hw/bitstream:rom` and friends should point to those injected bitstream files by default (no `--define bitstream=$x` config setting). 

The `sigverify_mod_exp_rma_otbn_fpga_cw310_rom` unconditionally splices OTP images into `//hw/bitstream:rom` [[cs]](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom/e2e/BUILD;l=1325;drc=ef72d061eae70eb18904e0157334dc1da8e2ce22). These splice operations do not care about any value of `--define bitstream=$x`. (Only targets in `//hw/bitstream:*` care about that config setting.)

**Comment by jadephilipoom** [comment]
Whew, sorry about the broken commit and thanks everyone for the quick work on finding, diagnosing, and fixing it in one my-time-zone night!

**Comment by alphan** [comment]
> Whew, sorry about the broken commit and thanks everyone for the quick work on finding, diagnosing, and fixing it in one my-time-zone night!

No worries at all! All CI checks passed twice (before and after merge). This was actually a pretty lucky accident that unearthed this issue in the CI.

**Comment by drewmacrae** [comment]
> > Whew, sorry about the broken commit and thanks everyone for the quick work on finding, diagnosing, and fixing it in one my-time-zone night!
> 
> No worries at all! All CI checks passed twice (before and after merge). This was actually a pretty lucky accident that unearthed this issue in the CI.

It's worth highlighting that, A "correct" version of the commit also wouldn't have passed CI and that locally we should use `--define bitstream=gcp_splice` when we're writing rom changes we want to see reflected in our tests.
