### ISSUE TITLE
[CI] ROM updates don't trigger bitstream generation in CI so they're not available till a subsequent commit does

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#16925]
[[e2e] Test regression: sigverify_mod_exp_rma_otbn_fpga_cw310_rom · Issue #16916 · lowRISC/opentitan](https://github.com/lowRISC/opentitan/issues/16916)

Shows an issue in ROM, that escaped CI and then shows as unresolved because https://cs.opensource.google/opentitan/opentitan/+/master:ci/scripts/get-bitstream-strategy.sh;bpv=1 excludes it and skips a build and the cache is populated by a stale bitstream with a stale ROM.

**Comment by drewmacrae** [comment]
https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=106115&view=logs&j=c42160f9-8579-523f-695d-70e04e62fcfe&t=36232b1f-a848-5ed5-98ba-6d61a20ad3b4 shows an instance where a ROM change isn't available in the cache and a subsequent ROM test fails

**Comment by drewmacrae** [comment]
We could fix it as described here: https://github.com/lowRISC/opentitan/issues/16620
Cache spliced bitstreams consistently in GCP bitstream cache
and since vivado tools is mandatory for FPGA tests have everyone do the splicing to avoid this

**Comment by drewmacrae** [comment]
We could make everything splice by default so SW can skip vivado builds in all cases and the exclusion becomes effectively correct AFAIK.

**Comment by drewmacrae** [comment]
Or we could narrow the exclusion.

**Comment by drewmacrae** [comment]
I'd prefer B) so we don't see this problem with any sort of software artifact.

**Comment by drewmacrae** [comment]
Ahh, @alphan has pointed out B is already partly implemented: The build and splice step only synthesizes the bitstream now and is intentionally skipped and then the splicing is intended to happen in "prepare-cached-bitstream.sh (and it does, but then the unspliced target is copied because bazel's collision prevention is causing the target to resolve as it would by default.

**Comment by alphan** [comment]
related: #16926

**Comment by alphan** [comment]
Fixed by #16926
