### ISSUE TITLE
[sysrst_ctrl] Change request to add pre-condition to combo detector

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#16928]
@jesultra @a-pronin and @toshaq recently identified a shortcoming of the current `sysrst_ctrl` combo detection circuit: While the circuit can correctly detect a key-pressed combination pattern, it cannot model pre-conditions, where a key-pattern first has to be pressed in order to activate detection of an edge transition on a second key (or key pattern). This is apparently an important use case, hence this change-request to add such a feature.

The RTL change is limited in complexity, but requires a CSR change.
Given that DV is not at V3 yet, and additional work is scoped to improve the current testbench, it may still be possible to absorb such a change (TBD).

Note that the change is backwards compatible with the current testbench and should not lead to new failures, since by default, the pre-condition matching is disabled.

A draft for this change can be found here: #16929.

**Comment by msfschaffner** [comment]
@tjaychen @weicaiyang would you mind taking a look?

**Comment by msfschaffner** [comment]
@marnovandermaas FYI, let me know if you have any questions.

**Comment by marnovandermaas** [comment]
> @marnovandermaas FYI, let me know if you have any questions.

Thanks @msfschaffner!
