### ISSUE TITLE
[dvsim] Return non-zero exit code if a regression fails

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1692]
Currently `util/dvsim.py` always returns a 0 exit code, even if a regression fails. That makes it hard to use this script in CI. Can we change that to return a non-zero exit code if any regression fails?

**Comment by rswarbrick** [comment]
Have you an example command line that shows a failure?

**Comment by imphil** [comment]
```
util/dvsim.py hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson -i sanity --max-parallel 3 --tool=vcs
```

And use the imphil/primgen branch, this one fails for sure :-) (#1679)

**Comment by sriyerg** [comment]
This is already on my list of TODOs for the tool. I will make a update in a day or two.

**Comment by sriyerg** [comment]
Assigining back to you, since the private CI requires riscv toolchain support.
