### ISSUE TITLE
[ci] Bitstream synthesis and implementation step sometimes fails when license is inaccessible

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#16935]
Pipeline runs like this one: https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=106177&view=logs&jobId=c42160f9-8579-523f-695d-70e04e62fcfe&j=c42160f9-8579-523f-695d-70e04e62fcfe&t=0fb6deac-69ab-5654-b7b3-381b8c8dec1b

Occasionally fail around peak hours and show the following warning:
https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=106177&view=logs&j=c42160f9-8579-523f-695d-70e04e62fcfe&t=0fb6deac-69ab-5654-b7b3-381b8c8dec1b&l=364
WARNING: Default location for XILINX_HLS not found
before failing to execute vivado to provide the bitstream. I presume this an attempt to run the synthesis when there are no licenses avaialable and intend to rerun it but wanted to document it.

**Comment by msfschaffner** [comment]
@GregAC @a-will do we still observe this issue in CI?
If not we can probs close this...
