### ISSUE TITLE
[rom,otbn] investigate why OTBN sigverify provides no speedup in sim (over SW sigverify)

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#16990]
### Description

The `rom_e2e_sigverify_mod_exp` test was added to DV recently to compare ROM sigverify runtimes when run in SW vs on OTBN. From the test [results](https://reports.opentitan.org/hw/top_earlgrey/dv/2023.01.01_17.36.04/report.html), it seems there is no runtime improvements when using OTBN over SW. In fact, in some cases it seems executing the sigverify with OTBN is slower. See screenshot of test results below (note, disregard the test failures in the `test_unlocked0` LC state as this is a separate known issue).

<img width="1058" alt="Screenshot 2023-01-05 at 6 08 42 PM" src="https://user-images.githubusercontent.com/5633066/210897486-4a3e8529-7d0e-4ba9-b3f1-2eb9a12cbd8e.png">

Further investigation is required to determine:

1. if the correct values are being set in OTP to tell ROM to perform the sigverify with OTBN vs entirely in SW (a custom sequence can be developed to check this via a backdoor OTP read or just reading the value backdoor printed over the UART during the test).
2. if there is actually a more serious issue here beyond perhaps a test configuration error.

CC: @alphan

**Comment by alphan** [comment]
Hi @timothytrippel, here is what I get when I run the following mod_exp tests that run on ibex and otbn respectively:

```
INFO: Elapsed time: 267.028s, Critical Path: 241.72s
INFO: 3 processes: 4 local.
INFO: Build completed successfully, 3 total actions
//sw/device/silicon_creator/lib/sigverify:mod_exp_ibex_functest_wycheproof_fpga_cw310_test_rom PASSED in 241.6s
//sw/device/silicon_creator/lib/sigverify:mod_exp_otbn_functest_wycheproof_fpga_cw310_test_rom PASSED in 24.8s

INFO: Build completed successfully, 3 total actions
```

The runtimes look reasonable to me. Were you able to find anything on the DV side?

**Comment by moidx** [comment]
@timothytrippel  could this be an issue with the OTP overrides in DV? This doesn't seem to be an issue with RTL.

**Comment by cdgori** [comment]
Is this sigverify behavior still apparent?

**Comment by msfschaffner** [comment]
It almost looks like the settings are not taking effect in DV sims. 
Are we certain we simulate what we think we should be simulating?

**Comment by msfschaffner** [comment]
@timothytrippel can you close this once fixed?

**Comment by timothytrippel** [comment]
Yeah we found out it was due to the fact that the OTP setting for which sigverify mode to use (SW vs OTBN) was not taken into account in the test_unlock* states. #19000 fixed the issue.
