### ISSUE TITLE
[SDC] - SPI_HOST_INT_CLK is no longer needed in CDC

### ISSUE THREAD

**Issue by arnonsha** [lowRISC/opentitan#17001]
https://github.com/lowRISC/opentitan/blob/62226e07625b18c2dd435ec4b80822af9bb2f07a/hw/top_earlgrey/syn/chip_earlgrey_asic.sdc#L421

In #16773 the SPI_HOST_INT_CLK variable was removed. However it still appears in the CDC clock groups.

DC output:
Warning: Can't find clock 'SPI_HOST_INT_CLK' in design 'chip_earlgrey_asic'. (UID-95)

**Comment by tjaychen** [comment]
ah thanks @arnonsha .
do you want to just introduce a fix directly? I think @jeoongp removed this because the clock generation was slightly cleaned up.

**Comment by jeoongp** [comment]
@arnonsha Thanks. 
I fixed it in https://github.com/lowRISC/opentitan/pull/17007
