### ISSUE TITLE
[ci, fpga] Evaluate flakiness of JTAG FPGA tests on CI

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#17009]
### Description

We need to evaluate whether the ["Experimental CW310 ROM JTAG Tests"](https://cs.opensource.google/opentitan/opentitan/+/master:azure-pipelines.yml;l=559;drc=24dbd62ae752ec235bd4dd9958ab246de4eab90c) are flaky on CI. Currently, they are marked `continueOnError: True`, which means that failures within the job will be ignored when deciding whether the CI run was successful.

Ultimately, we should figure out how to unflake the tests. Once that's done, we should drop the `continueOnError: True` attribute.

I wanted to create some tooling to automate this analysis, but I was defeated by the Azure DevOps API (see #16811).

**Comment by msfschaffner** [comment]
I believe this has been addressed by the infrastructure fixes that went in for M2.5.{2,3}.

CC @andreaskurth @pamaury @timothytrippel @a-will
