### ISSUE TITLE
[rv_dm,dv] Verify DTM idle behavior (`jtag_dtm_idle_hint` BLT)

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#17033]
This issue tracks the implementation of the `jtag_dtm_idle_hint` block-level test, which is specified in the testplan for `rv_dm`.

> estimate 8

**Comment by andreaskurth** [comment]
Triaged for `rv_dm`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2 because this is an open V2 test.

**Comment by msfschaffner** [comment]
@rswarbrick  @jdonjdon need to figure out with impare whether this is part of the RV_DM testplan already (and hence addressed).

**Comment by rswarbrick** [comment]
Implemented in 4143382e7ed203ad4726fc355fd0af063b4109eb (part of PR #20009) and merged last October.
