### ISSUE TITLE
[rv_dm,dv] Verify that writes to DMI registers are ignored while DM is not active (`jtag_dmi_dm_inactive` BLT)

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#17035]
This issue tracks the implementation of the `jtag_dmi_dm_inactive` block-level test, which is specified in the testplan for `rv_dm`.

> estimate 8

**Comment by andreaskurth** [comment]
Triaged for `rv_dm`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2 because this is an open V2 test.

**Comment by msfschaffner** [comment]
@rswarbrick  @jdonjdon need to figure out with impare whether this is part of the RV_DM testplan already (and hence addressed).

**Comment by rswarbrick** [comment]
Implemented in f2591927dd0e4c2a47edba40091b16c842f650aa (in PR #20016) last October.
