### ISSUE TITLE
[rv_dm,dv] Verify debugger can read status of unavailable hart (`hart_unavail` BLT)

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#17036]
This issue tracks the implementation of the `hart_unavail` block-level test, which is specified in the testplan for `rv_dm`.

> estimate 8

**Comment by andreaskurth** [comment]
Triaged for `rv_dm`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2 because this is an open V2 test.

**Comment by msfschaffner** [comment]
@rswarbrick  @jdonjdon need to figure out with impare whether this is part of the RV_DM testplan already (and hence addressed).

**Comment by rswarbrick** [comment]
This was implemented in 806815a18389a9eb74a9c878ef504f81892d450a (in PR #19541), merged last August.
