### ISSUE TITLE
[i2c, dv] Add excl for intr_state

### ISSUE THREAD

**Issue by tunghoang290780** [lowRISC/opentitan#1705]
Previously, excl of intr_state register is added via add_csr_exclusions function. With the proposal of #1635, the function add_csr_exclusions was removed by adding excl tags in .hjson file. However, the intr_state (and other intr regs) are not defined by hjson file thus all i2c_csr_* tests failed (add_csr_exclusions).

Should add_csr_exclusions  function are used in combination with excl tags defined in  .hjson file? Another solution is to expose all register via .hjson file to give the designer full controllability.

**Comment by sriyerg** [comment]
PR #1635 does a blanket exlcusion of INTR_TEST with CsrExclWrite (dont write to it) and INTR_STATE with CsrExclWriteCheck (dont read-check it) in the script itself. See [here](https://github.com/lowRISC/opentitan/pull/1635/files#diff-a1398a4d8591b4f725176dc9247905b6R1072). This should get applied to all IPs. Considering this, its a little surprising that your tests are failing. Would you please share logs / waves to debug further?

Also, note that the new solution is backward-compatible with the old methodology (with add_csr_exclusions), so you still have the full controllability from the verification side.

**Comment by tunghoang290780** [comment]
@sriyerg 
I add excl tags into i2c.hjson and remove add_csr_exclusions function. Currently, only csr_hw_reset failed

![image](https://user-images.githubusercontent.com/53881329/76139472-fb459b00-6004-11ea-8d5b-d05b5ae35d4b.png)

**Comment by sriyerg** [comment]
As described in the testplan, csr_hw_reset checks the reset value of the registers. Looks like some interrupt is getting asserted right out of reset (which means SW will get interrupted the moment it is enabled). Please check if this is intentional.

**Comment by rasmus-madsen** [comment]
@tunghoang290780 can this be closed?
