### ISSUE TITLE
[top_darjeeling] Fast subsystem interrupts?

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#17070]
### desc

Is there a need to support fast external interrupts?
From my point of view, most interrupts can probably be hooked into the "gpio" bus for darjeeling. We can then enable the gpio interrupts to trigger and let the software decode the mapping on where it should go. 

However, if there is a need to more directly wire this into the plic, we made need to make some infra changes to support it.

**Comment by msfschaffner** [comment]
This has been implemented using a `soc_proxy` module that is similar in construction like `sensor_ctrl`.
The advantage is that the wiring / mapping to the PLIC is direct.

CC @andreaskurth
