### ISSUE TITLE
Deal with parallel invocations of meson stepping on each other

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#1708]
DV simulations are run in 'batch' mode where tests are farmed out to compute farms. This is the same in our case as well, where we dispatch all chip level tests in parallel. I figured it would greatly reduce the build time if I had all DV tests "share" the same build directory root for compiling their corresponding bare-metal C tests. This unfortunately does not work, since the meson invocations start to step on each other. Please see the following report page for (some) details:
https://reports.opentitan.org/hw/top_earlgrey/dv/latest/results.html

Is there a way meson can do a semaphore lock on the build root directory such that an another invocation "waits" on the previous one to complete?

**Comment by lenary** [comment]
Closed by `bc6aabd2aed83c494c873ce98526928ce6e0bc6e`, I think.
