### ISSUE TITLE
C Application file used in opentitan it is stored in Boot-Rom or Flash??

### ISSUE THREAD

**Issue by ladmangesh805** [lowRISC/opentitan#1709]
https://github.com/lowRISC/opentitan/tree/master/sw/device/examples/hello_world

The above link leaves you at C application file.
One more issue what will be difference in file execution of these two memories ??

**Comment by silvestrst** [comment]
@ladmangesh805 anything in `examples` folder is built to be executed in flash. Boot ROM and Flash applications are built using different linker scripts, crt, irq handlers, etc...

You could examine meson.build in `.../examples/hello_world/meson.build` and `/sw/device/boot_rom/meson.build` to better understand what is used to build `boot_rom` and the binaries that are loaded to flash.

I have given some of the description of how binaries are loaded to flash, and high level interaction between boot_rom and flash in the [comment](https://github.com/lowRISC/opentitan/issues/1688#issuecomment-595138853).

> One more issue what will be difference in file execution of these two memories ??

Boot ROM is kind of like a boot loader, it does what is required to bring up the system and passes the control to flash. From the CPU perspective nothing is different apart from the fact that it fetches the instructions from different addresses in memory.

**Comment by imphil** [comment]
@ladmangesh805 please re-open if your question isn't answered.
