### ISSUE TITLE
[Question] How do I build a bare metal custom test in C? 

### ISSUE THREAD

**Issue by usmnzain** [lowRISC/opentitan#17096]
### Description

I am trying to build a test that I will run on opentitan_earlgrey with renode. I am trying to find a standalone linker and start script. I have a C program that I will compile with riscv-toolchain manually.

**Comment by johngt** [comment]
@andreaskurth - do you mind assisting on this and pointing to the right points in the documentation and/or redirect to others who may be able to assist?

**Comment by andreaskurth** [comment]
Thanks for your question, @usmnzain.

We use [Bazel](https://bazel.build/) to [build our software](https://docs.opentitan.org/doc/getting_started/build_sw/). If Renode supports building with Bazel, I think that would be your easiest option. If that is not an option, you could extract the compile and link commands that Bazel executes by invoking Bazel with the `--subcommands` option (e.g., `bazel build --subcommands //sw/device/examples/hello_world:hello_world`) and put the relevant commands into your own scripts. Note that some files that are necessary for compilation (including header files to interface HW modules and linker files to define memory addresses) are autogenerated from higher-level descriptions.

There is a relatively simple C example program in [`sw/device/examples/hello_world`](https://github.com/lowRISC/opentitan/tree/7bf43b1d56a998a465308eb683b7d8413bc5f1e6/sw/device/examples/hello_world). Linker and start files intended for bare-metal programs can be found in [`sw/device/silicon_owner/bare_metal`](https://github.com/lowRISC/opentitan/blob/7bf43b1d56a998a465308eb683b7d8413bc5f1e6/sw/device/silicon_owner/bare_metal).

**Comment by usmnzain** [comment]
Great thanks, I will look into it. Closing the issue, will re-open if required.
