### ISSUE TITLE
[sw/silicon_creator] typo in rnd_functest

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#17101]
### Description

I noticed that `//sw/device/silicon_creator/lib/drivers:rnd_functest_fpga_cw310_rom` failed in the last two runs of my local coverage pipeline. I noticed the following typo in the test:

https://github.com/lowRISC/opentitan/blob/d1f1f9c1870eb45792ccffe2c19c2ed6c5950280/sw/device/silicon_creator/lib/drivers/rnd_functest.c#L195

Shouldn't this line use `lc_expect_check` instead of `lc_expect_check_skip`?

**Comment by moidx** [comment]
Hi @alphan, I am looking at this now.

**Comment by alphan** [comment]
> Hi @alphan, I am looking at this now.

Thanks! PLMK if I can help.
