### ISSUE TITLE
[build] HTTP request for OpenOCD v0.12.0-rc1 archive 404s

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#17138]
### Description

Example: https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=107475&view=logs&j=62754bfd-1e07-590e-4563-63d5dff44c03&t=da39aa2e-f818-5d8e-57ef-95af7701b447&l=162

```
INFO: Repository openocd instantiated at:
  /home/vsts/work/1/s/WORKSPACE:71:14: in <toplevel>
  /home/vsts/work/1/s/third_party/openocd/repos.bzl:9:26: in openocd_repos
  /home/vsts/work/1/s/rules/repo.bzl:9:21: in http_archive_or_local
Repository rule http_archive defined at:
  /home/vsts/.cache/bazel/_bazel_vsts/5c27df7f718ab35828b0e0cfe0993663/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
WARNING: Download from https://sourceforge.net/projects/openocd/files/openocd/0.12.0-rc1/openocd-0.12.0-rc1.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'openocd':
   Traceback (most recent call last):
	File "/home/vsts/.cache/bazel/_bazel_vsts/5c27df7f718ab35828b0e0cfe0993663/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://sourceforge.net/projects/openocd/files/openocd/0.12.0-rc1/openocd-0.12.0-rc1.tar.gz] to /home/vsts/.cache/bazel/_bazel_vsts/5c27df7f718ab35828b0e0cfe0993663/external/openocd/temp11543241603328735984/openocd-0.12.0-rc1.tar.gz: GET returned 404 Not Found
ERROR: /home/vsts/work/1/s/WORKSPACE:71:14: fetching http_archive rule //external:openocd: Traceback (most recent call last):
	File "/home/vsts/.cache/bazel/_bazel_vsts/5c27df7f718ab35828b0e0cfe0993663/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://sourceforge.net/projects/openocd/files/openocd/0.12.0-rc1/openocd-0.12.0-rc1.tar.gz] to /home/vsts/.cache/bazel/_bazel_vsts/5c27df7f718ab35828b0e0cfe0993663/external/openocd/temp11543241603328735984/openocd-0.12.0-rc1.tar.gz: GET returned 404 Not Found
ERROR: /home/vsts/work/1/s/third_party/openocd/BUILD:37:15: no such package '@openocd//': java.io.IOException: Error downloading [https://sourceforge.net/projects/openocd/files/openocd/0.12.0-rc1/openocd-0.12.0-rc1.tar.gz] to /home/vsts/.cache/bazel/_bazel_vsts/5c27df7f718ab35828b0e0cfe0993663/external/openocd/temp11543241603328735984/openocd-0.12.0-rc1.tar.gz: GET returned 404 Not Found and referenced by '//third_party/openocd:build_openocd'
ERROR: /home/vsts/work/1/s/third_party/openocd/BUILD:31:10: no such package '@openocd//': java.io.IOException: Error downloading [https://sourceforge.net/projects/openocd/files/openocd/0.12.0-rc1/openocd-0.12.0-rc1.tar.gz] to /home/vsts/.cache/bazel/_bazel_vsts/5c27df7f718ab35828b0e0cfe0993663/external/openocd/temp11543241603328735984/openocd-0.12.0-rc1.tar.gz: GET returned 404 Not Found and referenced by '//third_party/openocd:jtag_adapter_cfg'
```

Solution space:

* Switch the URL from SourceForge to GitHub. This is not as simple as it sounds because GitHub's release archives do not contain sources for OpenOCD's third-party dependencies. 
* Downgrade to the last stable release See #17137. I recall this release being a little flakier than v0.12.0-rc1, but I had trouble verifying this due to an unrelated issue: #17136.
* Maintain our own mirror? We could create a GCS bucket and manually upload each release archive. We could list our own mirror and SourceForge in the `urls` parameter of [`http_repository`](https://bazel.build/rules/lib/repo/http) in [`third_party/openocd/repos.bzl`](https://cs.opensource.google/opentitan/opentitan/+/master:third_party/openocd/repos.bzl;l=12;drc=5ec1513687acc9be3d014f7437e21a289c83ed09). This has the added benefit of reducing our outgoing HTTP traffic.

**Comment by dmcardle** [comment]
Looks like the file is back on SourceForge now, so this issue resolved itself!

@timothytrippel: I heard you may have  thoughts on maintaining our own mirror for third-party dependencies (last bullet point above). It would be great to have such a mirror in place as a safety net for future problems like this one.

**Comment by timothytrippel** [comment]
Yeah we have some WIP plans to improve our airgapped environment, part of which involves a GCS bucket that stores mirrors of all external deps,  past and present, so we  could certainly make this bucket available to other (CI) infrastructure to avoid this. There will be more info next week :). Stay tuned.

**Comment by pamaury** [comment]
I am closing the issue since the files are back. The airgapped environment should probably be tracked in another issue and is also much more general than OpenOCD?
