### ISSUE TITLE
[build] Bitstream cache not initialized properly

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#17136]
### Description

I'm not sure when this started, but as of 9e0c9019fd4fdac54248cb150bb31a203110f0d0, I'm hitting an error when my git post-checkout hook runs `./bazelisk.sh sync --configure`.

```console
$ git rev-parse origin/master
9e0c9019fd4fdac54248cb150bb31a203110f0d0
$ git checkout origin/master
HEAD is now at 9e0c9019f [top/dv] Fix back propagation of non-lockstep inputs in lockstep test
WARNING:root:Closest bitstream to HEAD is f5ba9029609a01b3bcbe300b967ac547bce7f21e.
ERROR:root:Could not find the bitstreams to generate a BUILD file:'BUILD.bazel'
in files_by_extension:defaultdict(<class 'set'>, {'mmi': {'cache/f5ba9029609a01b3bcbe300b967ac547bce7f21e/chip_earlgrey_cw310_hyperdebug/otp.mmi', 'cache/f5ba9029609a01b3bcbe300b967ac547bce7f21e/rom.mmi', 'cache/f5ba9029609a01b3bcbe300b967ac547bce7f21e/chip_earlgrey_cw310_hyperdebug/rom.mmi', 'cache/f5ba9029609a01b3bcbe300b967ac547bce7f21e/otp.mmi'}, 'bit': {'cache/f5ba9029609a01b3bcbe300b967ac547bce7f21e/chip_earlgrey_cw310_hyperdebug/lowrisc_systems_chip_earlgrey_cw310_hyperdebug_0.1.bit'}})
using key:'f5ba9029609a01b3bcbe300b967ac547bce7f21e'
INFO: Repository bitstreams instantiated at:
  /usr/local/google/home/dmcardle/REPOS/opentitan/wt2/WORKSPACE:101:16: in <toplevel>
Repository rule bitstreams_repo defined at:
  /usr/local/google/home/dmcardle/REPOS/opentitan/wt2/rules/bitstreams.bzl:52:34: in <toplevel>
ERROR: An error occurred during the fetch of repository 'bitstreams':
   Traceback (most recent call last):
        File "/usr/local/google/home/dmcardle/REPOS/opentitan/wt2/rules/bitstreams.bzl", line 25, column 13, in _bitstreams_repo_impl
                fail("Bitstream cache not initialized properly.")
Error in fail: Bitstream cache not initialized properly.
ERROR: /usr/local/google/home/dmcardle/REPOS/opentitan/wt2/WORKSPACE:101:16: fetching bitstreams_repo rule //external:bitstreams: Traceback (most recent call last):
        File "/usr/local/google/home/dmcardle/REPOS/opentitan/wt2/rules/bitstreams.bzl", line 25, column 13, in _bitstreams_repo_impl
                fail("Bitstream cache not initialized properly.")
Error in fail: Bitstream cache not initialized properly.
ERROR: Bitstream cache not initialized properly.
Loading: loading...
```

**Comment by a-will** [comment]
Odd... that entry is missing the chip_earlgrey_cw310 bitstreams. It has the hyperdebug one only. However, the MMI files are present.

**Comment by dmcardle** [comment]
Looks like CI was unable to stat the file when it created the tar file, but this wasn't a fatal error. https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=107457&view=logs&j=1c15866c-f6d9-5ed5-250e-957338c61f0a&t=de9e445e-c222-56b2-0675-e6115634dfdf&l=115

**Comment by a-will** [comment]
Ah, looks like I missed some CI scripts that depend on file names for emitting cache entries. The spliced image is now named "gcp_spliced_test_rom.bit". Doh! Will fix.

**Comment by alphan** [comment]
Hi @a-will, any updates?

**Comment by alphan** [comment]
I'm trying the following hack to see if it will unblock the pending PRs:
- Add `.orig` suffix to the lastest `bitstream-*.tar.gz`
- Manually upload an archive with the spliced bitstream file renamed to `gcp_spliced_test_rom.bit` per @a-will's comment above.

**Comment by a-will** [comment]
I'm trying a different approach--Just copy the files from the cache directly, instead of using the spliced outputs. Then, the file names won't change.

**Comment by timothytrippel** [comment]
can we close this now that #17142 has merged?

**Comment by dmcardle** [comment]
Let's optimistically close this issue.

I'll note that I'm still hitting the error, but that's expected until either (a) CI uploads a newer bitstream cache entry or (b) the HTTP cache that sits in front of the GCS bucket expires its entry for the 17ffa51715b8d502ddff0f50d5da8f2fc0c0b923 tar file.
