### ISSUE TITLE
[chip] Sensor control rst_ni input is connected to aon reset domain  

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#17135]
### Description

Sensor control that is part of the main power domain is not reset when vcamin power is turned off.
Its signal reset is connected to aon reset: rstmgr_aon_resets.rst_lc_io_div4_n[0].
CC: @arnonsha @yehuda-bejar @meisnere

**Comment by tjaychen** [comment]
ah yes good catch, we should fix this. 
Thanks for the find.

**Comment by sha-ron** [comment]
@GregAC If possible to give this issue high priority it will be great since it is needed for UPF testing.

**Comment by GregAC** [comment]
Bumping to P1 for visibility for project planning purposes. May move back to P2 once properly assigned (with the understanding it will be at the top of the queue for things to fix at P2 level).

**Comment by moidx** [comment]
Hi @arnonsha, We checked on our end and confirmed that `sensor_ctrl` should be part of the `aon` domain. Can you update this configuration on your end? Thanks

**Comment by arnonsha** [comment]
Yes will do. Thanks for confirming

**Comment by arnonsha** [comment]
done on our side. closing
