### ISSUE TITLE
[CDC] static signal to clarify

### ISSUE THREAD

**Issue by jeoongp** [lowRISC/opentitan#17140]
### Description

Is u_otp_ctrl.otp_hw_cfg.o semi-static? 
This signal comes from DIV4_CLK and used for muxing signals in MAIN_CLK.

**Comment by msfschaffner** [comment]
It is, yes. As far as I know, the OTP controller initializes first, before any of the consuming blocks are let out of reset. Right @tjaychen?

**Comment by jeoongp** [comment]
@msfschaffner thanks. Can you also check if u_lc_ctrl.lc_hw_debug_en_o? 
Likewise, it's from DIV4_CLK and used for muxing signals in MAIN_CLK.

**Comment by msfschaffner** [comment]
Yes that is a lifecycle control signal and can hence be treated as quasi-static (the life cycle controller initializes after OTP but before the rest of the system is allowed to boot).

**Comment by cindychip** [comment]
I think this issue is resolved? Please free feel to re-open it if you have any questions.
