### ISSUE TITLE
[top-level,clkmgr] Fix expected clock counts

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#17145]
### Description

Due to CDC instrumentation the expected clock counts for frequency measurements needs an extra cycle. This was already fixed for unit tests, but was missing in top-level, which caused test failures.

**Comment by andreaskurth** [comment]
CC @johngt for keeping in mind when triaging TLT failures

**Comment by johngt** [comment]
Thanks @andreaskurth . I believe that @alees24 was mentioning that there were some assumptions made in the framework. Highlighting in case this is relevant. Also highlighting to @engdoreis for part of on-call activities.
