### ISSUE TITLE
[cw310] documentation of GPIO Pins?

### ISSUE THREAD

**Issue by L0g4n** [lowRISC/opentitan#17179]
### Description

Hello,

I have a support question for the CW310 board. I already tried to read the [schematics](https://github.com/newaetech/cw310-bergen-board/blob/main/docs/BergenBoard_Rev06C.PDF), but could not find it there (probably because I am not yet good at reading electronic schematics).
As I understand, OpenTitan has 32 GPIO pins, and the CW310 board has 8 user LEDs and 3 integrated user push buttons. Where can I find the mapping between the peripherals (LEDs, buttons) and the appropriate GPIO pins?

Thanks!

**Comment by luismarques** [comment]
Hi,

Is this what you're looking for?

https://github.com/lowRISC/opentitan/blob/ae9a6baef1c1e73cc4c73ce33b8cf5ad8e40a26d/hw/top_earlgrey/data/pins_cw310.xdc#L100
https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/ip/pinmux/doc/autogen/pinout_cw310.md
https://github.com/newaetech/cw310-bergen-board/blob/main/pins/bergen.xdc

Check also the pinmux configuration and cross-reference with the schematics.

**Comment by L0g4n** [comment]
That seems right, thanks!

**Comment by cindychip** [comment]
Thank you @luismarques for the quick response. I am going to close this issue. @L0g4n please feel free to re-open it if you have any further questions.
