### ISSUE TITLE
[dv/sysrst_ctrl] Add DV support

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#17173]
### Description

Add DV support for new feature:
https://github.com/lowRISC/opentitan/issues/16928

**Comment by GregAC** [comment]
PR to add test here https://github.com/lowRISC/opentitan/pull/17318

**Comment by johngt** [comment]
@GregAC / @marnovandermaas / @crteja 
I'm assuming that this is now done as both linked references are now merged / completed?

**Comment by crteja** [comment]
@johngt , yes, the issue can be closed.

**Comment by marnovandermaas** [comment]
Since the PR to add this test has been merged (https://github.com/lowRISC/opentitan/pull/17318), I will close this issue.

**Comment by marnovandermaas** [comment]
Adding estimates based on efforts by @crteja and me.

> estimate 64
> remaining 2023-03-08 32
> remaining  2023-03-15 0
