### ISSUE TITLE
[test-triage] E2e tests failing with timeout

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#17183]
### Hierarchy of regression failure

Chip Level

### Failure Description

Job chip_earlgrey_asic-sim-vcs_run_default killed due to: Exit reason: User job exceeded runlimit: User job timed out has 7 failures:

### Steps to Reproduce

- GitHub Revision: [91b09f2d4](https://github.com/lowrisc/opentitan/tree/91b09f2d4bfa63fbb344f250a7313d922953babc)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i rom_e2e_shutdown_output --build-seed 3099685857 --fixed-seed 3099685857 --waves fsdb

### Tests with similar or related failures

- [x] rom_e2e_shutdown_output
- [x] rom_e2e_boot_policy_valid_a_bad_b_good_test_unlocked0
- [x] rom_e2e_sigverify_always_a_bad_b_bad_test_unlocked0

**Comment by engdoreis** [comment]
Waiting until https://github.com/lowRISC/opentitan/issues/17094 is resolved.

**Comment by johngt** [comment]
Probably can be closed

**Comment by engdoreis** [comment]
Closing, as the tests listed below are now failing in the rom_e2e_nightly.
