### ISSUE TITLE
[ci] Some jobs time out

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#17187]
### Description

Some CI jobs currently time out even though there does not seem to be anything fundamentally wrong with them. Affected are, from what I have seen:
- Fast Verilated Earl Grey tests > Build & execute tests
- Earl Grey SW Build & Test > Build & test SW

PR #17186 tries to remedy this problem by increasing the timeout of those jobs.

**Comment by johngt** [comment]
Tagging @jprendes , @pamaury , @luismarques and @mundaym for visibility

**Comment by andreaskurth** [comment]
The build time for the FPGA bitstreams currently seems to vary by quite a lot, which sometimes causes a timeout. For example:
- CW310 Earl Grey Bitstream [built in 1h 57m](https://dev.azure.com/lowrisc/4c50229e-f6cb-4f39-8522-585bb3841438/_build/results?buildId=108074&view=logs&j=c42160f9-8579-523f-695d-70e04e62fcfe) for 6ad9b82e51c90514a7c496bc6b0831e8f5f9be83 :heavy_check_mark: 
- CW310 Earl Grey Bitstream [timed out after 3h 7m](https://dev.azure.com/lowrisc/4c50229e-f6cb-4f39-8522-585bb3841438/_build/results?buildId=108045&view=logs&j=c42160f9-8579-523f-695d-70e04e62fcfe) for 2fd9dfe7879b2bc327b3cd3afc1a2a9d3fd481d8 :x:
- CW310 Earl Grey Bitstream for Hyperdebug [timed out after 3h 0m](https://dev.azure.com/lowrisc/4c50229e-f6cb-4f39-8522-585bb3841438/_build/results?buildId=108074&view=logs&j=b94df8f7-305c-501a-1ed0-aaaef92b098a) for 6ad9b82e51c90514a7c496bc6b0831e8f5f9be83 :x:

PR #17216 increases the timeout for *CW310 Earl Grey Bitstream*

**Comment by andreaskurth** [comment]
From PR #17226:
> Sometimes CI fails due to the timeout of `watchdog_functest_sim_verilator`.
> 
> This commit increases timeout from 3600 s to 5400 s.

**Comment by a-will** [comment]
https://github.com/lowRISC/opentitan/commit/db7e744e5aae42b391bd9ab082f655da6b88d6a9 might be a possible cause. I didn't notice that the related PR's CI run took substantially longer to build the bitstreams.

**Comment by andreaskurth** [comment]
Closing this issue as we now have a more differentiated understanding about the utilization of CI resources
