### ISSUE TITLE
[test-triage] OTBN block-level tests all failed

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#17208]
### Hierarchy of regression failure

Block level

### Failure Description

```
  Error when resetting ISS: Failed to run command 'reset': EOF from ISS.
  Error when resetting ISS: Failed to run command 'reset': EOF from ISS.
  Error when resetting ISS: Failed to run command 'reset': EOF from ISS.
  terminate called after throwing an instance of 'std::runtime_error'
    what():  Failed to run command 'initial_secure_wipe': EOF from ISS.
  xmsim: *F,SIGUSR: Unix Signal SIGABRT raised from user application code. Stack trace information is captured in file sigusrdump.out.
  Stack trace information is captured in file /workspace/0.otbn_smoke/latest/bpad_1427.err
  TOOL:    xrun(64)    21.09-s006: Exiting on Feb 01, 2023 at 01:23:33 PST  (total: 00:00:02)
  WARNING: Destroying OtbnTraceChecker object with an unfinished operation.
  make: *** [/workspace/mnt/repo_top/hw/dv/tools/dvsim/sim.mk:141: simulate] Error 2
```

### Steps to Reproduce

- GitHub Revision: 618f6081aabc81bea33d2b957954573eab7e4816
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  `./util/dvsim/dvsim.py hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson -t xcelium --build-seed 3345409474 -i otbn_smoke --fixed-seed 689795600`
- [Nightly regression started on Feb 1 2023 at 08:06 UTC failed](https://reports.opentitan.org/hw/ip/otbn/dv/uvm/2023.02.02_05.34.04/report.html), Git revision 618f6081aabc81bea33d2b957954573eab7e4816
- [Nightly regression started on Jan 31 2023 at 08:04 UTC failed](https://reports.opentitan.org/hw/ip/otbn/dv/uvm/2023.02.01_04.16.56/report.html), Git revision 2363bcd26bf972b3fe83a863cff854031ee4aa94
- [Nightly regression started on Jan 30 2023 at 08:10 UTC passed](https://reports.opentitan.org/hw/ip/otbn/dv/uvm/2023.01.31_06.29.23/report.html), Git revision 91b09f2d4bfa63fbb344f250a7313d922953babc
- Comparison of last passing to first failing revision: https://github.com/lowRISC/opentitan/compare/91b09f2...2363bcd
- Cannot reproduce locally on 618f6081aabc81bea33d2b957954573eab7e4816 with Xcelium 21.09-s006, which according to the logs is the same version used to run the nightly regressions

**Comment by andreaskurth** [comment]
The [changes between the last passing and the first failing revision](https://github.com/lowRISC/opentitan/compare/91b09f2...2363bcd) include two closely related to OTBN DV:
* 7bf43b1d5 [otbn,dv] Move default simulator to XCelium
* 2363bcd26 [otbn,dv] Mock EDN update for Verilator Sim

My main suspicion is on 7bf43b1d5, since this affects all tests, including all OTBN block-level tests in the nightlies, whereas 2363bcd26 should only affect Verilator simulations, which are not part of the nightlies.

The error messages are fairly generic. The common denominator seems
```
terminate called after throwing an instance of 'std::runtime_error'
    what():  Failed to run command 'initial_secure_wipe': EOF from ISS.
  xmsim: *F,SIGUSR: Unix Signal SIGABRT raised from user application code. Stack trace information is captured in file sigusrdump.out.
```
Although the command `initial_secure_wipe` fails, I doubt the problem is specific to that command, because different commands fail before that (`edn_flush` and `reset`).

As I cannot reproduce the problem locally, I suspect this is related to the environment or procedures through which nightlies are run. Both changes passed the CI checks that are run on PRs.

@cindychip: Do you maybe have access to the environment in which the nightlies are run? If so, do the log files (e.g., `/container/opentitan-public/scratch/os_regression/otbn-sim-xcelium/0.otbn_smoke/latest/run.log`) contain further information? If they don't contain further information, do we maybe have to change something in the nightly setup so that OTBN can be simulated with Xcelium instead of VCS?

**Comment by johngt** [comment]
@cindychip / @andreaskurth - just wondering if you had communicated with the logfiles that Andreas had requested?
I guess this request was across a weekend but it would be good to identify asap. Thanks!

**Comment by cindychip** [comment]
> @cindychip / @andreaskurth - just wondering if you had communicated with the logfiles that Andreas had requested? I guess this request was across a weekend but it would be good to identify asap. Thanks!

I can find the logic file and email to Andreas.

**Comment by cindychip** [comment]
@timothytrippel  fixed it on our end. It is merged and we can check the nightly regression for Feb 8th.

**Comment by andreaskurth** [comment]
Thanks @cindychip and @timothytrippel!

**Comment by cindychip** [comment]
I think we can close this issue?
