### ISSUE TITLE
[dvsim] Gracefully handle CTRL-C

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1723]
When pressing CTRL-C in a dvsim.py run, we currently get an unhandled KeyboardInterrupt:

```
^CTraceback (most recent call last):
  File "util/dvsim.py", line 480, in <module>
    main()
  File "util/dvsim.py", line 462, in main
    cfg.deploy_objects()
  File "/home/philipp/src/opentitan/util/dvsim/SimCfg.py", line 397, in deploy_objects
    super().deploy_objects()
  File "/home/philipp/src/opentitan/util/dvsim/FlowCfg.py", line 415, in deploy_objects
    Deploy.deploy(self.deploy)
  File "/home/philipp/src/opentitan/util/dvsim/Deploy.py", line 398, in deploy
    time.sleep(1)
KeyboardInterrupt
```

It would be nice to catch this exception, clean up, and gracefully exit.

**Comment by sriyerg** [comment]
This is also already on our list of things to do for dvsim. I will create an issue that tracks everything that is planned so that it will be easy to lookup the upcoming feature list.

**Comment by sriyerg** [comment]
> This is also already on our list of things to do for dvsim (see [here](https://github.com/lowRISC/opentitan/pull/1252) for some of them). I will create an issue that tracks everything that is planned so that it will be easy to lookup the upcoming feature list.

**Comment by tjaychen** [comment]
closing! see #1795
