### ISSUE TITLE
[doc] Replace term "aggravate" in SCA/FI context 

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#17256]
### Description

We are using the term "aggravate" when discussing SCA/FI context but this may be ambiguous. We should better use either "deter" or "dissuade".

Changing this is simple but I would like to first wait for the documentation work to stabilize before doing content edits.

> estimate 2

**Comment by ballifatih** [comment]
Triaged for `kmac`.

Between "deter" and "dissuade", I would prefer "deter", and we can even simply say "protect againt SCA attacks/adversaries". In the security context, when someone talks about "dissuading" a particular attack scenario, it sounds like the attack might be successful, but whatever the attacker recovers is not particularly useful.

For instance, there are some mode of operations that use different (ephemeral) key for each block cipher invocation, there I would say the security relies on "dissuading" the adversary. Not sure if I am over-interpreting the words though.

**Comment by ballifatih** [comment]
> estimate 1
