### ISSUE TITLE
[usbdev] Isochronous IN endpoints raises 'pkt_sent' interrupt when no buffer supplied

### ISSUE THREAD

**Issue by alees24** [lowRISC/opentitan#17275]
### Description

Any enabled isochronous IN endpoint will generate a 'pkt_sent' interrupt even in the event that no buffer has been supplied, and thus a zero-length transfer has been transmitted in response to an IN transaction.

With the current DIF code/usb_testutils implementation, this means that dif_usbdev_clear_tx_status reads from the configin register and tries to release buffer 0, breaking the buffer pool management. It is possible to work around this issue (/design feature) by changing usb_testutils to maintain a record of the buffer most recently supplied for IN transmission; all calls to dif_usbdev_send shall then be redirected through the usb_testutils layer.

Driver software shall need to be aware that Isochronous endpoints should be enabled only if the system is prepared to handle 1000 interrupts/second for each enabled IN endpoint, and be ready to supply data buffers at this rate.

More generally, we may want to limit the number of interrupts being raised. Frame interrupts are also expected to be raised with this frequency, and the packet received/sent interrupts could occur more frequently for Bulk Transfer endpoints.

**Comment by a-will** [comment]
Ah, I see the FSM problem. Nice catch!
