### ISSUE TITLE
[aes/doc] Mention possibility of implementing GCM with Ibex and bitmanip

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#17280]
The documentation of AES currently only mentions the block cipher modes fully implemented in hardware (ECB, CBC, CTR, OFB, CFB). GCM isn't mentioned but it can be implemented by doing GHASH on Ibex using bitmanip. We should reflect that in the documentation. Also it might be worth pointing to our GCM implementation part for the crypto library.

> estimate 1

**Comment by moidx** [comment]
Triaging meeting: Since this is a documentation task, it is ok to move post M2.5.
