### ISSUE TITLE
[sysrst_ctrl] Review and merge  #13556

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#17333]
This PR:  #13556 adds a new chip level test for sysrst_ctrl. We must determine if it is still needed and merge (after any required changes) if so.

**Comment by GregAC** [comment]
@doreis-lowrisc, @crteja, @marnovandermaas please note

**Comment by marnovandermaas** [comment]
I decided to close that PR because the test was implemented by @abdullahvarici in October last year and has already been merged into the main repo.
