### ISSUE TITLE
[usbdev/all] Interrupt loss with dif_<x>_irq_acknowledge_all

### ISSUE THREAD

**Issue by alees24** [lowRISC/opentitan#17349]
### Description

Potential for losing interrupts with the auto-generated '_irq_acknowledge_all' function, as in dif_usbdev_irq_acknowledge_all.

The set of pending interrupts is read by the interrupt handler (eg. dif_usbdev_irq_get_state()) but there is no efficient means to clear _just_ the set of interrupts that have been collected by the interrupt handler. Instead the dif_usbdev_irq_acknowledge_all clears all interrupts by writing UINT32_MAX to the register.

This has the potential to cause loss of interrupts that have set other bits in the register, between the invocation of _get_irq_state() and the call to _acknowledge_all().

Perhaps there is a convention/understanding that prevents the loss of interrupts in other blocks, eg. they will immediately be raised again since the underlying condition has not been resolved, but some of the interrupts in the usbdev IP are single-cycle events of which the software should be informed and they cannot be relied upon to occur again.

With the interrupt state register (INTR_STATE) being rw1c, should it not be the case that there is a usbdev_irq_acknowledge_<>(... , uint32_t clr) call that accepts the precise _set_ of interrupts to be cleared, rather than force them to be cleared individually with the current dif_usbdev_irq_acknowledge(..., dif_usbdev_irq_t irq) call which clears just one?

The set of interrupts which are triggered by single-cycle events from state transitions in usbdev is:

- disconnected
- link_reset
- link_suspend
- host_lost
- link_powered

**Comment by alees24** [comment]
If this needs wider attention, to whom should I assign it, please?

**Comment by a-will** [comment]
This is just about the DIFs, right? Know that those are only used for tests, so we're probably the most interested party for usbdev, heh.

Though... this is actually a more general missing feature of DIFs. Things may have changed, but @timothytrippel and I were probably the most recent maintainers of general DIF features. I don't see why we couldn't have a `dif_usbdev_clear_irq_state()`, perhaps taking in a `dif_usbdev_irq_state_snapshot_t` or similar.

**Comment by alees24** [comment]
Yes, it is just about the current software, and I'm aware that the DIFs have never been intended to become the basis for production code. That said, it's something that perhaps an auto-generated API should avoid, because there is a risk of frustrating development/testing, or of tripping up production interrupt-handling code.

Being new to the project, I don't know whether it would be appropriate to flag this more generally, raise a PR against the global cause (reggen?) or perhaps just a PR against dif_usbdev? Thoughts, please?

For the moment I have changed usb_testutils to acknowledge individually only the interrupts collected/processed, because we are indeed perhaps the most likely to run into problems at this stage.

**Comment by a-will** [comment]
> Yes, it is just about the current software, and I'm aware that the DIFs have never been intended to become the basis for production code. That said, it's something that perhaps an auto-generated API should avoid, because there is a risk of frustrating development/testing, or of tripping up production interrupt-handling code.
> 
> Being new to the project, I don't know whether it would be appropriate to flag this more generally, raise a PR against the global cause (reggen?) or perhaps just a PR against dif_usbdev? Thoughts, please?
> 
> For the moment I have changed usb_testutils to acknowledge individually only the interrupts collected/processed, because we are indeed perhaps the most likely to run into problems at this stage.

Right, I just meant that we're probably the ones who will collectively do the work and approve/reject it. I went ahead and created a PR for this in #17363.

And yes, it would be best to flag this more generally. You found that the `...acknowledge_all()` DIFs can create unfortunate race conditions, and it comes with pitfalls for anyone using the DIFs for potentially any IP.
