### ISSUE TITLE
[entropy_src, dv] Disconnect extht agent in block-level DV for M2.5

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#17358]
In Earlgrey nothing is connected to the `entropy_src_xht_i/o` ports and we won't be using external health tests. However, in block-level DV an agent is connected to these ports. Entropy For M2.5, we should probably disconnect the agent/disable it to make block-level DV better match the real scenario.

Ideally we can somehow parametrize the connection to easily keep it enabled for a few test cases and easily re-enable it later on.

**Comment by marnovandermaas** [comment]
As this is fixed by #17638 
> estimate 1
