### ISSUE TITLE
[uart, dv] Write coverage plan and review existing coverage for potential gaps

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#17353]
The UART has implemented functional coverage but it is not documented in a coverage plan. From a brief review the existing coverage is a little bare and could likely do with extra covergroups.

The testplan is comprehensive, fully implemented and achieving a very high pass rate so there is high confidence that new coverage will achieve a good hit rate.

> estimate 4
> remaining 2023-06-16 1

**Comment by marnovandermaas** [comment]
M2.5 effort estimate:
> estimate 4
