### ISSUE TITLE
[rom, rom_ext] Review `SigverifyKeyTypes`

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#17364]
### Description

Review key types versus life cycle matrix and add documentation. Currently `DEV` verification keys are not allowed in `RMA` and `TEST_UNLOCKED`  life cycle stages, however `PROD` keys are. It is not clear why these needs to be the case. 

This issue came up during https://github.com/lowRISC/opentitan/pull/17316 review. 

CC: @alphan, @cfrantz

**Comment by alphan** [comment]
Because we would like to be able to run prod rom_ext images on those life cycle states and prod keys are expected to be guarded better than other types of keys.

**Comment by alphan** [comment]
Also, dev keys are exclusively for the dev lifecycle state since that's the whole point of their existence.

**Comment by moidx** [comment]
Hi @alphan, I created the issue because the following configuration is commonly used. I just want to discuss this so that we can talk about testability of DEV keys in post silicon. Let's leave it open until we get a chance to talk about this.  Thanks!

SigningKeyType | LC_TEST | LC_RMA | LC_DEV | LC_PROD
-|-|-|-|-
TEST | X | X | |
DEV | X | X | X |
PROD | X | X | X | X

**Comment by pamaury** [comment]
Hi @moidx and @alphan, is the table above anywhere is the documentation? It seems to match what the code does but contradicts the [secure boot page](https://staging.opentitan.org/book/doc/security/specs/secure_boot/index.html#silicon-creator-keys-silicon-creator-keys). Maybe this text should be updated with the table?

**Comment by pamaury** [comment]
I have added the table above in #17449 since it seems to make sense to document it at the same time.

**Comment by alphan** [comment]
@moidx @cfrantz are you OK with the current state or do you still think dev keys should be usable in TEST_UNLOCKED ?

**Comment by cfrantz** [comment]
> @moidx @cfrantz are you OK with the current state or do you still think dev keys should be usable in TEST_UNLOCKED ?

I'm ambivalent about whether the DEV key is valid in TEST_* states, but I do think the DEV key _should_ be valid in RMA.  My rationale is that if a customer sends back a chip for RMA analysis and it can still execute code, any valid customer image (ie: even one by customers authorized to have DEV chips) should work in the RMA state.

**Comment by timothytrippel** [comment]
Since the ROM has shipped, should we close this now?

**Comment by timothytrippel** [comment]
Closing this as I believe it has been addressed, feel free to reopen later.
