### ISSUE TITLE
[rom-e2e-triage] rom_e2e_debug_test_otp_dev

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#17376]
### Hierarchy of regression failure

Chip Level

### Failure Description

Log no provided by azure.

### Steps to Reproduce

- GitHub Revision: 38503dbd0c08d5f08cf97dbe45e74114cef7d2ca
- bazel command to reproduce the failure:
```console
bazel test --define DISABLE_VERILATOR_BUILD=true --define bitstream=gcp_splice --test_tag_filters=-verilator,-dv,-broken --build_tests_only //sw/device/silicon_creator/rom/e2e:rom_e2e_debug_test_otp_dev

```

### Tests with similar or related failures

- [ ] rom_e2e_debug_test_otp_dev

**Comment by engdoreis** [comment]
This tests is failing for the same reason as https://github.com/lowRISC/opentitan/issues/17377

**Comment by HU90m** [comment]
Ah nice, thanks Douglas!

**Comment by engdoreis** [comment]
Fixed by https://github.com/lowRISC/opentitan/pull/17555
