### ISSUE TITLE
[manufacturing] Test: manuf_cp_ast_test_execution

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#17388]
### Description

Test point: [manuf_cp_ast_test_execution](https://github.com/lowRISC/opentitan/blob/e8f38cd58f738fe5bb3e5b5e3dbcd1ea91d480dc/sw/device/silicon_creator/manuf/data/manuf_testplan.hjson#L75-L93)

### Test Description

Verify that the tester is able to load/exec test sequences into/from SRAM.

An expected pattern during manufacturing involves loading small program sequences into
SRAM, and use them to run higher level operations such as configuring OTP values in the
OTP hardware partition.

- Pre-load OTP with TEST_UNLOCKED lc_state in pre-silicon environments. Advance to
  state in silicon.
- Select CPU JTAG via strap pins.
- Load program into SRAM to execute OTP word write sequences.
- Trigger OTP writes to HW partition (e.g. device ID).
- Perform reset by toggling POR pin.
- Select CPU JTAG via strap pins.
- Verify that OTP write was successful.

**Comment by timothytrippel** [comment]
#18022 is a prereq.

**Comment by timothytrippel** [comment]
Completed in #18610.
