### ISSUE TITLE
[manufacturing] Test: manuf_cp_unlock_raw

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#17383]
### Description

Test point: [manuf_cp_unlock_raw](https://github.com/lowRISC/opentitan/blob/e8f38cd58f738fe5bb3e5b5e3dbcd1ea91d480dc/sw/device/silicon_creator/manuf/data/manuf_testplan.hjson#L10-L26)

### Test Details

Verify transition from RAW to TEST_UNLOCKED lc_state.

- Pre-load OTP with RAW lc_state.
- Bring device out of reset selecting the Life Cycle (LC) TAP interface using strap pins.

Perfom the following steps via LC TAP interface:

- Switch to external clock via TRANSITION_CTRL.EXT_CLOCK_EN.
- Provide RAW_UNLOCK.
- Poll for lc_ctrl STATUS register for TRANSITION_SUCCESSFUL. Check for errors or timeout.
- Perform reset by toggling the POR pin.
- Verify the lc_state is TEST_UNLOCKED0.

The manufacturing environment is required to support test reruns whenever possible:

- Verify that the RAW_UNLOCK process can be re-tried after failed or interrupted attempts.

**Comment by timothytrippel** [comment]
#17864 completed this.

**Comment by timothytrippel** [comment]
Re-opening as this is still not working: https://github.com/lowRISC/opentitan/pull/18550#issuecomment-1545188597

**Comment by timothytrippel** [comment]
#18550 now fixes this.

**Comment by moidx** [comment]
Closed by https://github.com/lowRISC/opentitan/pull/18550
