### ISSUE TITLE
[manufacturing] Test: manuf_scrap

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#17384]
### Description

Test point: [manuf_scrap](https://github.com/lowRISC/opentitan/blob/e8f38cd58f738fe5bb3e5b5e3dbcd1ea91d480dc/sw/device/silicon_creator/manuf/data/manuf_testplan.hjson#L34-L48)

### Test Details

Verify transition from any state to SCRAP lc_state.

Manufacturing tests should be able to move the device from any lc_state into SCRAP state.

For each manufacturing lc_state `s`:
- Pre-load OTP with `s` lc_state image.
- Bring device out of reset selecting the Life Cycle (LC) TAP interface using strap pins.
- Request transition to SCRAP state via LC TAP interface.
- Perform reset by togglig the POR pin.
- Check we are in SCRAP state via LC TAP interface.

The manufacturing environment is required to support test reruns whenever possible:

- Verify that the transition to SCRAP mode can be re-tried after failed or interrupted attempts.

**Comment by timothytrippel** [comment]
Closed with #17976
