### ISSUE TITLE
[manufacturing] Manufacturing framework - Device Firmware

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#17382]
## Background

The manufacturing infrastructure is divided into the following:

* Host side initiated transactions
  - [x] JTAG life cycle transitions (detailed in: #17490, #17491, #17492)
  - [x] JTAG SRAM code injection (already implemented)
  - [ ] JTAG programming sequences (OTP, Flash)
  - [x] Bootstrap protocol (already implemented)
  - [x] Device reset and general IO (already implemented)
* Device side initiated transactions which are executed from flash test programs
   - [ ] Life cycle checks (handled by testutils)
   - [ ] Device individualization (device_id OTPs, and additional SKU dependent configuration)
   - [ ] Device provisioning (secret initialization)
   - [ ] Provisioning of RMA token
   - [ ] Loading of transport (i.e. factory) image
   - [ ] Loading of device certificates
   - [ ] End of manufacturing

This issue is to track the requirements and design proposal for the manufacturing firmware. Host side tooling will be covered on a separate issue.

## Requirements

1. Specific manufacturing steps will be implemented as libraries, which can then be combined in top-level test cases or a single manufacturing binary.
2. The firmware manufacturing framework should allow for composing binaries will multiple test stages. There should be flexibility as to how the test cases are integrated into the binary.
3. A serial interface should be used to select test cases for execution. ATE testers prefer to avoid bi-directional physical protocols. For example, the tester may send the command, wait for some time, and then poll a serial interface to read the result. A common approach is to playback the response message on a SPI interface in a loop to avoid synchronization issues with the tester. The capture buffer on the tester may capture multiple instances of the response message and use a marker to detect the start of one of the response instances.
4. An interactive configuration should be provided to be able to drive the tests from opentitantool or manually (e.g. via UART).

## References

1. Manufacturing test plan: https://github.com/lowRISC/opentitan/blob/master/sw/device/silicon_creator/manuf/data/manuf_testplan.hjson

**Comment by timothytrippel** [comment]
going to close this meta-issue as each component is handled in individual smaller issues, but we can refer back to it later if needed.
