### ISSUE TITLE
[bazel] refactor `opentitan_functest` to enable HW platform extensibility

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#17385]
## Background / Problem

Currently, we support running top-level tests on several HW platforms (e.g., `sim_dv`, `sim_verilator`, `fpga_cw310_rom`, `fpga_cw310_test_rom`). Soon we will be adding support for running tests on a CW310 + HyperDebug HW platform (see #17381), and later, to support silicon bringup, we will need to add support for a Si+HyperDebug platform.

The Bazel macro for implementing tests on the various HW platforms (i.e., `opentitan_functest`) has evolved in a manner that makes it challenging to add additional test platform targets (i.e., a spaghetti code scenario).

## Solution

Refactor the `opentitan_functest` Bazel macro (potentially creating several simpler macros) to facilitate adding other HW platforms in the future.

## Tasks
TBD

**Comment by timothytrippel** [comment]
Note: this can be done as part of post-si preparations.

CC: @moidx @cfrantz

**Comment by cfrantz** [comment]
Superseded by #19493 and https://github.com/orgs/lowRISC/projects/13/views/54
