### ISSUE TITLE
[manufacturing] Test: manuf_ft_exit_token

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#17391]
### Description

Test point: [manuf_ft_exit_token](https://github.com/lowRISC/opentitan/blob/e8f38cd58f738fe5bb3e5b5e3dbcd1ea91d480dc/sw/device/silicon_creator/manuf/data/manuf_testplan.hjson#L159-L184)

### Test Description

Verify provisioning and use of test exit token.

The test exit token is used to move the device from test mode into DEV, PROD or
PROD_END state. This test also incorporates enabling of ROM execution before
triggering the lc_state change.

- Pre-load OTP with TEST_UNLOCKED lc_state in pre-silicon environments. Advance to
  state in silicon.
- Select CPU JTAG via strap pins.
- Program TEST_EXIT_TOKEN in OTP transition via JTAG.
- Reset device by toggling POR pin.
- Select CPU JTAG via strap pins.
- Program CREATOR_SW_CFG_ROM_EXEC_EN in OTP via JTAG.
- Select LC TAP via strap pins (at runtime).
- Request transition into {pick one: DEV, PROD, PROD_END} state providing TEST_EXIT_TOKEN.
- Perform reset by toggling POR pin.
- Select LC TAP via strap pins.
- Verify lc state.

After this test most of the following manuf_ft_* test cases can be loaded into flash via
boostrap in silicon.

**Comment by timothytrippel** [comment]
This will be covered via #17389, so no need to implement this in addition. Will re-assign to myself, since I am almost done with #17389.

**Comment by timothytrippel** [comment]
#18518 will cover this test point, I will close it once it merges.

**Comment by jwnrt** [comment]
@timothytrippel part of this test is programming the `TEST_EXIT_TOKEN` to OTP via the JTAG.
I see #18518 pre-loads the token into OTP before the tests starts - will that work for a real silicon environment as well?

**Comment by timothytrippel** [comment]
We test provisioning various OTP values in the test (the CREATOR/OWNER_SW_CFG partitions), i.e. blowing fuses in the SRAM program. The provisioning of the test-unlocked token doesn't have to be over JTAG, the device code can blow the fuses to. I can update the test to write the SECRET0 partition in the SRAM program as well (instead of backdoor loading) but I think we are ok.

**Comment by timothytrippel** [comment]
#17389 closed
