### ISSUE TITLE
[manuf] Test: manuf_ft_load_certificates

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#17395]
### Description

Test point: [manuf_ft_load_certificates](https://github.com/lowRISC/opentitan/blob/e8f38cd58f738fe5bb3e5b5e3dbcd1ea91d480dc/sw/device/silicon_creator/manuf/data/manuf_testplan.hjson#L332-L349)

### Test Description

Load endorsed certificates.

Load device certificate endorsing the creator public key. The certificate is signed
by the silicon creator.

TODO: This assumes the ROM_EXT supports a mechanism to update the certificate.
TODO: Should the transport image contain silicon creator pubilc keys to be able to
verify the certificate before install?

- Pre-load the OTP with an image of a personalized device.  See
  `manuf_ft_provision_rma_token_and_personalization` for more details.
- The device flash should be loaded with the transprot image. See
  manuf_ft_load_transport_image for details.
- The host sends a command to the device including the device certificate.
- The device verifies that the certificate corresponds to its device key.
- The certificate is then stored into a flash page (info versus regular flash TBD).
- Send response to the host with test result.

**Comment by timothytrippel** [comment]
this is covered in #19455, so closing.
