### ISSUE TITLE
[manufacturing] Test: manuf_rma_entry

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#17397]
### Description

Test point: [manuf_rma_entry](https://github.com/lowRISC/opentitan/blob/e8f38cd58f738fe5bb3e5b5e3dbcd1ea91d480dc/sw/device/silicon_creator/manuf/data/manuf_testplan.hjson#L374-L401)

### Test Description

Verifies RMA entry.

In silicon, the entire process is executed in a secure environment in adherence to
certification requirements.

- Initialize device to reflect eom state. See manuf_ft_eom for more details.
- Select LC TAP via strap pins.
- Read DEVICE_ID via LC TAP interface.
- Powerdown the device.

The Silicon Creator is expected to lookup the RMA_UNLOCK_TOKEN in a manufacturing database
using the DEVICE_ID and decrypt it at an offline location. The token cannot leave the
secure environment in unencrypted form at any time, implying that there is a way for the
secure environment to handle the decryption operation.

- Select LC TAP via strap pins.
- Power on the device.

The following steps are performed via the LC TAP interface:
- Read DEVICE_ID. Confirm expected response.
- Load RMA_UNLOCK_TOKEN and request transition to RMA state.
- Poll for status completion.
- Reset device by toggling POR pin.

RMA entry will trigger a rotation of scrambling keys. It is recommended to either
connect to the CPU JTAG to continue debug, or bootstrap the device with new a firmware
image. Otherwise the ROM will fail to boot.

**Comment by timothytrippel** [comment]
This test was covered as part of #17393.
