### ISSUE TITLE
[entropy_src/dv] Verify bypass mode

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#17408]
During the Feb 21 Silicon WG meeting it was brought up by Nuvoton that the bypass mode needs to be verified as well (relevant for FIPS). This seems to be covered by the `firmware_mode`, `health_checks` and `conditioning` test points. But this should probably be cross checked.

Personal note: It’s not clear to me at this point whether the tests verify that entropy extracted in bypass mode doesn’t continue to flow through the module (required by FIPS). I need to check this.

From @marnovandermaas comment below:
Updated estimate for M2.5
old estimate 2023-03-25 2

>  estimate 32
> remaining 2023-04-03 20
> remaining 2023-04-06 4

**Comment by marnovandermaas** [comment]
Effort estimation of checking that everything is in order:
> estimate 2

**Comment by vogelpi** [comment]
After having a closer look at the design, I think there are in total four cases all going under the term "bypass" that we need to ensure work as expected:

- [ ] Read data from observe FIFO (`FW_OV_RD_DATA`)
Enabled via `otp_en_entropy_src_fw_over` input + `FW_OV_CONTROL.FW_OV_MODE` field.
Data read out via observe FIFO must not flow further and appear at the CSRNG-entropy_src interface.
I believe this should be covered by the `entropy_src_fw_ov` test. I am currently looking into this.

- [ ] Write data into pre-conditioner FIFO (`FW_OV_WR_DATA`)
Enabled via `otp_en_entropy_src_fw_over` input + `FW_OV_CONTROL.FW_OV_MODE` and `FW_OV_CONTROL.FW_OV_ENTROPY_INSERT` fields.
Could be captured by `entropy_src_rng` test.

- [ ] Read data from esfinal FIFO (`ENTROPY_DATA`)
Enabled via `otp_en_entropy_src_fw_read` input  + `ENTROPY_CONTROL.ES_ROUTE` field.
Data read out via esfinal FIFO must not flow appear at the CSRNG-entropy_src interface.
We should probably verify that what software inputs via pre-conditioner FIFO can be read out again if also the conditioner is bypassed (see next point).
Could be captured by `entropy_src_rng` test.

- [ ] Bypass the SHA3 conditioner
Enabled via  `ENTROPY_CONTROL.ES_TYPE` field.
Allows to forward unconditioned entropy to the esfinal FIFO (readable by CSRNG-entropy interface or `ENTROPY_DATA`).
Could be captured by `entropy_src_rng` test.

All these cases need to be tested for FIPS.

**Comment by marnovandermaas** [comment]
Updated estimate for M2.5
old estimate 2023-03-25 2
> estimate 32

**Comment by moidx** [comment]
We can consider the boundary of the entropy block to also include the cryptolib for FIPS certification purposes. As part of enabling the entropy complex in FIPS mode, we will have to support:

1. KAT of the conditioner block which will require `FW_OV` mode
2. KAT of the CSRNG. 
3. Continuous checks of the health checks. From a FIPS perspective, we are expected to use  a health check configuration that generates some errors, to ensure the tests are actually working. In short, we should be able to see health check errors without triggering fatal alerts.

**Comment by vogelpi** [comment]
Thanks @moidx ! From what I see all this is currently supported.

>     1. KAT of the conditioner block which will require `FW_OV` mode
We can configure `FW_OV` mode with "extract and insert" and also set `ES_ROUTE` to read out the conditioner output. This is supported. Both `otp_en_entropy_src_fw_over` and `otp_en_entropy_src_fw_read` bits of OTP need to be in the enable setting.

>     2. KAT of the CSRNG.
This is supported as well and we have some TLTs for that.

>     3. Continuous checks of the health checks. From a FIPS perspective, we are expected to use  a health check configuration that generates some errors, to ensure the tests are actually working. In short, we should be able to see health check errors without triggering fatal alerts.
This is also supported. Health check failures are recorded in registers readable by firmware. Depending on the configured thresholds, health check failures may result in recoverable alerts and the main state stopping. To get it working again, firmware will have to disable/re-enable the entropy complex but this should be fine. The ENTROPY_SRC block will not trigger fatal alerts from that.

**Comment by vogelpi** [comment]
@moidx and I had an email conversation with @zi-v to confirm that this is indeed sufficient.

Another point that came up during that discussion was whether the firmware will be able to read the observe FIFO quickly enough. According to SP 800-90B the observe FIFO needs to be able to deliver 1000 consecutive samples but it has space for just 500 samples (2 kBit / 4 bits per sample).

From a test where AST generates entropy at the max rate, I could see that filling up the observe FIFO takes more than 40 us = 4000 clock cycles. Since firmware reads 32 bits per word, it needs to do 64 reads in 4000 cycles. So that's on average 60 cycles per read which should be doable. In addition, it's worth noting that the observe FIFO can be written while being read and this is being verified (so it's actually more than 4000 clock cycles), and the interrupt threshold for the observe FIFO is configurable.  

I am thus closing the issue.
