### ISSUE TITLE
[chip-test] chip_sw_otp_ctrl_vendor_test_csr_access

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#17417]
### Test point name

[chip_sw_otp_ctrl_vendor_test_csr_access](https://github.com/lowRISC/opentitan/blob/980d4259b0a676d40923bdd9301a8f5bd9f0feba/hw/top_earlgrey/data/chip_testplan.hjson/#L2840-L2853)

### Host side component

Unknown

### OpenTitanTool infrastructure implemented

None

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by andreaskurth** [comment]
This TLT does not seem to exist yet, and I think we need it for M2.5.

CC @cindychip who has triaged `otp_ctrl`

**Comment by cindychip** [comment]
Thank you Andreas. Good catch. Yes, this should be a M2.5 issue and agree for the tag P2 (Close source should check it on their own but in open source side, we should include this generic check)

**Comment by cindychip** [comment]
Done by #17433 but waiting to see nightly regression results.

**Comment by cindychip** [comment]
![image](https://user-images.githubusercontent.com/11466553/223207555-121bad8b-6f6c-4dc7-a0e8-d26b5881ee6a.png)

Nightly regression passed.
