### ISSUE TITLE
[rv_plic,dv] Implement assertions `EdgeTriggeredIp_A` and `EdgeTriggeredIpWithClaim_A`

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#17412]
Those two assertions are defined in [`rv_plic_fpv_testplan.hjson.tpl`](https://github.com/lowRISC/opentitan/blob/980d4259b0a676d40923bdd9301a8f5bd9f0feba/hw/ip_templates/rv_plic/data/rv_plic_fpv_testplan.hjson.tpl), but they are not implemented.

> 2

**Comment by msfschaffner** [comment]
I don't think this is critical right now, since we already test the PLIC quite extensively at the system level. I think we can defer this .
CC @cindychip @moidx
