### ISSUE TITLE
[chip-test] chip_plic_fatal_alert

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#17413]
### Test point name

[chip_plic_fatal_alert](https://github.com/lowRISC/opentitan/blob/980d4259b0a676d40923bdd9301a8f5bd9f0feba/hw/top_earlgrey/data/chip_testplan.hjson/#L841-L857)

### Host side component

SystemVerilog

### OpenTitanTool infrastructure implemented

None

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

Note that this test ("Verify that the fatal alert is fired from PLIC due to bus integrity violation.") seems to overlap with [`chip_sw_plic_alerts`](https://github.com/lowRISC/opentitan/blob/980d4259b0a676d40923bdd9301a8f5bd9f0feba/hw/top_earlgrey/data/chip_testplan.hjson/#L858-L867) ("Verify alerts from PLIC due to both, TL intg and reg WE onehot check faults."), which is tracked in https://github.com/lowRISC/opentitan/issues/16835. In particular, alerts due to reg WE onehot check faults seem to be verified already since https://github.com/lowRISC/opentitan/pull/16845. This leaves verifying TL integrity errors, which *this* test is about.

> estimate 8

**Comment by andreaskurth** [comment]
> Note that this test ("Verify that the fatal alert is fired from PLIC due to bus integrity violation.") seems to overlap with [`chip_sw_plic_alerts`](https://github.com/lowRISC/opentitan/blob/980d4259b0a676d40923bdd9301a8f5bd9f0feba/hw/top_earlgrey/data/chip_testplan.hjson/#L858-L867) ("Verify alerts from PLIC due to both, TL intg and reg WE onehot check faults."), which is tracked in #16835. In particular, alerts due to reg WE onehot check faults seem to be verified already since #16845. This leaves verifying TL integrity errors, which _this_ test is about.

@cindychip: I think the `chip_sw_plic_alerts` testpoint could be implemented by *this* test plus `chip_sw_all_escalation_resets`. WDYT?

**Comment by cindychip** [comment]
Thanks @andreaskurt, I agree this should be part of the escalation resets, or at least can share the same test infra.

**Comment by moidx** [comment]
@msfschaffner to cross-reference test cases.

**Comment by msfschaffner** [comment]
@cindychip can you close this once you added the SVA?

**Comment by cindychip** [comment]
thanks Michael, closing it.
