### ISSUE TITLE
[usbdev] Write test plan and coverage plan and decide upon top-level/block-level testing balance

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#17424]
usbdev currently lacks a test plan and coverage plan (as well as any meaningful block level testing).

Current work by @alees24 concentrates on the usbdpi model and top-level testing using the model in simulation and working with a real host in FPGA.

We need to write up a test plan for planned top-level tests and discuss what level (if any) of block-level testing we want.

For coverage we could include USB functional coverage collection in the top-level testbench. We will need to get top-level USB tests working in the DV environment to enable this.

**Comment by GregAC** [comment]
@a-will @vogelpi any comments from either of you as to what should be present in the coverage and test plans?

**Comment by alees24** [comment]
> estimate 8

**Comment by moidx** [comment]
Leaving this as P1 as this will cover the top-level smoketest of USB. Coverage collection will be focused on top-level connectivity.  

The estimates will need to be updated once we have an implementation plan for the smoke test.

**Comment by msfschaffner** [comment]
Closing since we have top-level tests in place and the block-level will be closed separately (which will just apply standard V2 signoff criteria).
