### ISSUE TITLE
[usbdev] Device cannot initiate resume from suspend

### ISSUE THREAD

**Issue by alees24** [lowRISC/opentitan#17476]
### Description

Whilst the usbdev supports the suspend behavior and resume signaling from the host, including the ability to enter a deep sleep mode and awaken via the auxiliary 'AON wake' module, if usbdev is required to initiate resume signaling from a suspended bus state, to get the attention of the host, there is no means to achieve this except perhaps direct sw driving of the phy pins. It's worth noting that the usbdev documentation mentions that sw driving of pins is for diagnostic/debugging purposes only.

In addition to having to wait for the host to resume communications, this also means usbdev cannot implement Remote Wakeup behavior. It is not clear to me at this point whether it could reliably be implemented even using sw pin-driving.

Qs: Is usbdev-initiated resume a requirement?
Have I missed something? The design seems fully consistent and built only ever to monitor the link state passively, responding to the behavior of the host controller, rather than initiating.

> estimate 16

**Comment by a-will** [comment]
No, this feature was known unsupported and was not a requirement.

However, we might want to check in with lead user teams and ensure that is still the case. I don't think it's a difficult thing to add, but we are always needing to prioritize.

**Comment by alees24** [comment]
Okay, that's good to know. Thanks for explaining.

**Comment by johngt** [comment]
Placing this in M2.5 for now.
Depending on answer from @mundaym and @GregAC - can then move this to the backlog.

**Comment by msfschaffner** [comment]
Afaik, @a-will is right and usbdev-initiated resume is not a requirement.

@moidx @jesultra to confirm (in which case this can be triaged from PROD.M2 into the backlog).

**Comment by jesultra** [comment]
ChromeOS uses USB only for debugging of the Chromebook. We will have software logic ensuring that OT never goes into deep sleep while a USB connection is established. We will not need OT to wake up the USB host.

**Comment by msfschaffner** [comment]
Thanks @jesultra - I am closing this issue as not planned.
