### ISSUE TITLE
[dvsim] Consistent ordering of P/D/T/... in info output

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1748]
Running dvsim.py on Python 3.5 gives different orderings of the P/D/T/... status numbers depending on the run.

For example, in one run I got:

```
INFO: [Deploy] [00:02:50]: [run]: [P: 17, D: 01, T: 29, K: 11, Q: 00, F: 00]
```

In another run I got

```
INFO: [Deploy] [00:02:37]: [run]: [T: 29, K: 24, P: 05, Q: 00, D: 00, F: 00]
```

Without having looked at the code, I suspect that OrderedDict or something along those lines will solve the problem.

@sriyerg

**Comment by sriyerg** [comment]
Yes, I was going to file this issue myself. I (and everyone else here at Google) don't see this random reordering with 3.7.5. Let me try and figure this out.

**Comment by imphil** [comment]
In Python 3.7 native dicts are ordered, for older versions OrderedDict is needed.

**Comment by eunchan** [comment]
@sriyerg you can see the related issue in previous issues/PR Using `OrderedDict` when creating the dictionary can solve.

**Comment by sriyerg** [comment]
Yup, will make a fix for this soon.
