### ISSUE TITLE
[ottf,ujson] make ujson and OTTF consoles configurable

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#17494]
### Description

# Background

Top-level tests have two consoles for sending data out of the chip (the `ujson` console and `ottf` console). Both currently hook up to UART 0.

# Problem

The Automated Test Equipment (ATE) used in manufacturing is setup to communicate with the DUT over SPI (instead of UART). 

# Solution / Requirements

Addressed in #17678:
- [x] consolidate all OTTF console functions to an `ottf_console` library (including flow control functions)
- [x] make ujson framework's OTTF [console](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/lib/testing/test_framework/ujson_ottf.c) device configurable (defaulting to UART but also allowing spi_device)

Addressed in #17774:
- [x] add spi_device as an option for the OTTF console device
- [x] make OTTF [console](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/lib/testing/test_framework/ottf_main.c;drc=a8abd6eabcf6770a34524bf0dabbeacf2877eaed;l=121) device configurable (same as above), maybe as part of `ottf_test_config_t` [struct](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/lib/testing/test_framework/ottf_test_config.h;drc=efc612c60b114c1691555a6e7d228fc0aadd41f1;l=23)

Addressed in #17816 and #17817:
- [x] refactor UART console module and enable use of SPI as a console interface in opentitanlib

Addressed in #17818:
- [x] add blocking spi_device (generic mode) TX DIF to spi_device DIF lib (current TX DIF is non-blocking, which does not match current UART behavior in `print.c`)
- [x] design / implement simple framing protocol for generic mode SPI frames
- [x] implement top-level smoke test on HyperDebug+CW310 to test the above works

**Comment by engdoreis** [comment]
Should the OTTF console config (UART, SPI or other) be dynamic, or would it be known at compile time?

**Comment by timothytrippel** [comment]
Compile time is OK. Most tests will default to UART console, but the manufacturing tests we most likely only want to run with SPI (as this will be the only interface available).

If we find we need this to be dynamic in the future we can always make that modification later.
