### ISSUE TITLE
[testutils] refactor testutils to return `status_t`

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#17495]
# Background

For [manufacturing tests](https://github.com/lowRISC/opentitan/blob/master/sw/device/silicon_creator/manuf/data/manuf_testplan.hjson), we need to be able to stream out test results in a structured way so they can be easily serialized and transmitted over gRPC.

# Problem

There are a lot of `CHECK*()` macros used throughout the `testutils` functions that trigger an unstructured failure message being printed to the console (i.e., UART0) that opentitantool notices via a regex match to terminate a test. In manufacturing tests are easier to integrate with Automated Test Equipment (ATE) if all device-host interfaces are unidirectional, and structured, and so the messages can be repeated several times to ensure the entire message was transmitted to the host. Additionally, transmitting these messages in a structured allows host-side gRPC services to serialize such messages and forward them along.

# Solution

Refactor the testutils to return `status_t`s instead of immediate failing CHECK assertions, specifically:

- [x] all testutils functions should return status_t (instead of void / bool)
- [x] all `CHECK` macros in testutils functions should be converted to `TRY` macros
- [x] the testutils style guide on the website should state this
- [ ] (potentially; stretch goal) create automated checks to enforce this? maybe use Bazel [visibility](https://bazel.build/concepts/visibility#visibility-specifications) specifications to implement this?

Note: can start with the testutils that will be used in [manufacturing tests](https://github.com/lowRISC/opentitan/blob/master/sw/device/silicon_creator/manuf/data/manuf_testplan.hjson), i.e., lc_ctrl, otp_ctrl, flash_ctrl, pinmux, gpio, entropy complex.

- [x] https://github.com/lowRISC/opentitan/issues/17523
- [x] https://github.com/lowRISC/opentitan/issues/17524
- [x] https://github.com/lowRISC/opentitan/issues/17525
- [x] https://github.com/lowRISC/opentitan/issues/17526
- [x] https://github.com/lowRISC/opentitan/issues/17527
- [x] https://github.com/lowRISC/opentitan/issues/17528
- [x] https://github.com/lowRISC/opentitan/issues/17529
- [x] https://github.com/lowRISC/opentitan/issues/17530
- [x] https://github.com/lowRISC/opentitan/issues/17531
- [x] https://github.com/lowRISC/opentitan/issues/17532
- [x] https://github.com/lowRISC/opentitan/issues/17533
- [x] https://github.com/lowRISC/opentitan/issues/17534
- [x] https://github.com/lowRISC/opentitan/issues/17535
- [x] https://github.com/lowRISC/opentitan/issues/17536
- [x] https://github.com/lowRISC/opentitan/issues/17537
- [x] https://github.com/lowRISC/opentitan/issues/17538
- [x] https://github.com/lowRISC/opentitan/issues/17539
- [x] https://github.com/lowRISC/opentitan/issues/17540 
- [x] https://github.com/lowRISC/opentitan/issues/17541 
- [x] https://github.com/lowRISC/opentitan/issues/17542
- [x] https://github.com/lowRISC/opentitan/issues/17543
- [x] https://github.com/lowRISC/opentitan/issues/17544
- [x] https://github.com/lowRISC/opentitan/issues/17545
- [x] https://github.com/lowRISC/opentitan/issues/17546
- [x] https://github.com/lowRISC/opentitan/issues/17547
- [x] https://github.com/lowRISC/opentitan/issues/17548
- [x] https://github.com/lowRISC/opentitan/issues/17549
- [x] https://github.com/lowRISC/opentitan/issues/17550

**Comment by engdoreis** [comment]
This is the current way the errors as handled in the test utils:
```c
static bool scramble_finished(const dif_sram_ctrl_t *sram_ctrl) {
 dif_sram_ctrl_status_bitfield_t status;
 CHECK_DIF_OK(dif_sram_ctrl_get_status(sram_ctrl, &status));
 return status & kDifSramCtrlStatusScrKeyValid;
}
```

This is how we propose it should be handled based on the description above:
```c
static status_t scramble_finished(const dif_sram_ctrl_t *sram_ctrl) {
 dif_sram_ctrl_status_bitfield_t status;
 TRY(dif_sram_ctrl_get_status(sram_ctrl, &status));
 return INTO_STATUS(status & kDifSramCtrlStatusScrKeyValid);
}
```
This would be a significant change to the code base as the function signature changes. 
@timothytrippel if you agree with this approach, I would create an issue for each IP Block to split the work.

**Comment by engdoreis** [comment]
@timothytrippel, can we close this issue? I couldn't think in an automated check, but I think it is a nice to have.

**Comment by timothytrippel** [comment]
yep sg! no problem on the automated check thats not necessary in the short term. Thanks @engdoreis !
