### ISSUE TITLE
[ujson] implement integrity check mechanism

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#17496]
# Background

For [manufacturing tests](https://github.com/lowRISC/opentitan/blob/master/sw/device/silicon_creator/manuf/data/manuf_testplan.hjson), we will use the [ujson framework](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/lib/ujson/?q=ujson&ss=opentitan%2Fopentitan) to stream out data from the device, see [example test](https://cs.opensource.google/opentitan/opentitan/+/master:sw/host/tests/chip/gpio/src/main.rs) that already uses this in a command-control (host-device) setup.

# Problem

There are no integrity checks on ujson messages. This could cause issues when streaming out critical provisioning data (e.g., public keys) from a new chip.

# Solution / Tasks

- [ ] investigate how to add integrity checks to ujson structs
    - will crc / checksum of binary representation work?
    - will it be valid in C and Rust? (might need rust representation of structs to be #[repr(c)])
- [ ] implement integrity check mechanism in ujson framework

CC: @cfrantz

**Comment by a-will** [comment]
Suggestion: Encapsulate the data in another protocol that provides a checksum.

This is more an organizational suggestion than anything functionally different, but the ujson layer itself probably does not need to provide this / can remain focused. Instead, it seems like something that we'd want to assign to an I/O layer.

**Comment by engdoreis** [comment]
I agree, this would also address the case where the ujson message is larger than the SPI FIFO described here https://github.com/lowRISC/opentitan/issues/17494.

**Comment by cfrantz** [comment]
> So, if we are only worried about bits being flipped in transport, we could just use a crc32 of the serialised struct. We could then send the crc32 as a seperate JSON object with one field following the message, so we can reuse the JSON serialiser to convert the crc32 to valid UTF-8.

I'd suggest going this route: checksum over the serialized form of the struct.  All ujson output is handled through `ujson_putbuf`, which itself uses a `ujson_t` instance to actually direct the IO.   All ujson outputs intended to be consumed by host-based programs are emitted from the firmware via the `RESP_OK` and `RESP_ERR` macros in `ujson_ottf.h`.

I think that `ujson_t` provides an ideal place for carrying enable/disable information for checksums as well as any intermediate data for the calculation.  `RESP_OK/_ERR` look like a reasonable place to calculate and emit the checksums:
```
#define RESP_OK(responder_, uj_ctx_, data_)
  ({
    TRY(ujson_putbuf(uj_ctx_, "RESP_OK:", 8));
    ujson_crc32_reset(uj_ctx_);  // Resets the crc32 calculation to an initial state like all zeros or all ones.
    TRY(responder_(uj_ctx_, data_));
    TRY(ujson_put_crc32(uj_ctx_); // Finalizes crc32 calculation and emits the text "CRC32: <integer value>"
    TRY(ujson_putbuf(uj_ctx_, "\r\n", 2));
    OK_STATUS();
  })
```

The regex match expression in opentitanlib can be easily updated to capture and validate the checksum over the text representation of the json blob.

**Comment by timothytrippel** [comment]
What steps remain here @HU90m ?

**Comment by HU90m** [comment]
Just created https://github.com/lowRISC/opentitan/pull/19236 which adds the integrity checks to responses from tests.

> What steps remain here @HU90m ?

I guess all that is left is to add integrity checks to the commands sent to tests?

**Comment by timothytrippel** [comment]
Since adding checks to tests (i.e., device code) will probably be done on a case-by-case basis as needed, can we close this issue? Is there a device-side lib that can be used to check a message received by a device?

**Comment by HU90m** [comment]
> Is there a device-side lib that can be used to check a message received by a device?

There isn't. There is only an example use in the round trip test:

https://github.com/lowRISC/opentitan/blob/5f3835849aaec8f2df78b4de227e49192784c841/sw/device/lib/ujson/example_roundtrip.c#L23-L34

Happy to write one though, if we need one.

> Since adding checks to tests (i.e., device code) will probably be done on a case-by-case basis as needed, can we close this issue?

Sound good to me.

We could add CRC checks to the commands given in existing tests, e.g. [`sw/device/tests/gpio_pinmux_test.c`](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/gpio_pinmux_test.c), but I'm not sure if this is necessary.

**Comment by timothytrippel** [comment]
ah got it. No worries, I think we can close this then.
