### ISSUE TITLE
[kmac] Prevent SW from reading capacity

### ISSUE THREAD

**Issue by ballifatih** [lowRISC/opentitan#17508]
### Description

I think `kmac` should prevent SW from reading `capacity` (the last 2*sec_str bits) of Keccak state.

In the scenario `kmac` is using a sideloaded key from `keymgr`, we want to hide the key from SW. There should not be a way for SW to read or compute the sideloaded key, because it is a key directly managed by `keymgr`.

The one-way security of the KMAC algorithm relies on the assumption that the attacker only sees the output of the algorithm, and not the full state of Keccak reached at the end of the operation. The output of KMAC is basically read from the `rate` part of Keccak state, and `capacity` remains secret.

If we let the attacker also read the `capacity` part of Keccak state, then it is possible to simply compute the previous Keccak states by executing inverse Keccak permutation. For instance, given full Keccak state for `KMAC(secret_key || known_val)`, one can compute `secret_key`.

It might be a good idea to prevent SW to read `capacity` part of Keccak. What do you folks think?

cc: @vogelpi @cindychip @johannheyszl

**Comment by johannheyszl** [comment]
Yes, defintely agree @ballifatih 

@jadephilipoom I remember we have discussed this last summer in context of the API. Did we open any issue re HW change back then?

**Comment by jadephilipoom** [comment]
> @jadephilipoom I remember we have discussed this last summer in context of the API. Did we open any issue re HW change back then?

No, there are no existing issues that cover this to my knowledge. The conversations last summer were about whether we could support multiple interleaved KMAC operations, which would require a full save/restore of the state (not supported right now because the state registers are read-only). This issue from a few years ago has some context there: https://github.com/lowRISC/opentitan/issues/3479

It seems like a future version of KMAC might support full save/restore functionality, but since it's not supported now I think @ballifatih is right that it makes sense to just block SW access to the latter part of the state, since it should never need those values for proper use.

**Comment by johannheyszl** [comment]
thx @jadephilipoom this is the issue I was looking for. All on same page here re preventing SW reads of KMAC state

**Comment by ballifatih** [comment]
Thanks for your feedback @johannheyszl, @jadephilipoom. I see the conflict between save/restore idea and preventing capacity reads.

All things considered, I would suggest that we implement this for M2.5 and prevent all SW capacity reads for the moment. In the future, if we decide to add save/restore feature, we can reduce this reading restriction to KMAC operations where the key is sideloaded.

Do you think implementing this change has large DV cost? @cindychip

**Comment by ballifatih** [comment]
Based on the feedback from Security WG (16/03/2023), I will implement "SW capacity read restriction" in a way that it only applies to sideloaded KMAC key. Then, for operations where key is provided by SW, or hashing operations that do not have a key, we can still let SW read the full Keccak state. Therefore, we do not lead to any conflict with future Keccak save/restore feature.

However note that, orthogonal to this issue, it is not possible to save/restore context with KMAC. I pointed out what is missing in the other issue #3479, so that we can discuss this feature in length there.

cc: @johannheyszl @moidx @zi-v

**Comment by ballifatih** [comment]
> estimate 8
