### ISSUE TITLE
[pwrmgr,dv] Increase score of `rom_active_blockers_cg`

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#17500]
The covergroup mentioned in the title has a [score <80%](https://reports.opentitan.org/hw/ip/pwrmgr/dv/latest/cov_report/grp18.html). This seems to be mainly due to `blockers_cross`, which has 3 uncovered bins and 2 holes.

That should be fixed to bring the score above 90%.

> estimate 2

**Comment by moidx** [comment]
Marking as P1 to prioritize for implementation, may lower the priority later.
