### ISSUE TITLE
[hmac, testutils] Refactor testutils to return status_t for all hmac

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#17533]

**Comment by cindychip** [comment]
estimate range: 2 - 4
@engdoreis please correct me if the estimate is not accurate :)

**Comment by engdoreis** [comment]
Hi @cindychip there's a PR https://github.com/lowRISC/opentitan/pull/17626 waiting for CI that will close this issue, so we don't need to estimate it :)
