### ISSUE TITLE
[doc] getting 404 errors on website links

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#17588]
### Description

Getting a 404 error when I click "Getting Started" link under "Getting Started" here: https://opentitan.org/book/doc/introduction.html#getting-started. Same with "list of user guides".

Also same when I click "Obtain an FPGA board" here: https://opentitan.org/guides/getting_started/setup_fpga.html#prerequisites

**Comment by mundaym** [comment]
Thanks for reporting these @timothytrippel!
