### ISSUE TITLE
[hw,i2c,dv] Review Timing parameters of I2C block  level TB

### ISSUE THREAD

**Issue by crteja** [lowRISC/opentitan#17609]
### Description

Based on discussion in #17565, review the timing parameters used in I2C base sequence and update them to align with I2C spec.
Re-enable run argument `cdc_instrumentation_enabled` after the update.

Old estimate 2023-04-14 4
> estimate 6
> remaining 2023-04-03 4

**Comment by johngt** [comment]
@crteja / @marnovandermaas - do you mind adding an effort estimate for this? Also please change the priority if incorrectly labelled. Thanks!

**Comment by crteja** [comment]
> estimate 4
> remaining 2023-04-03 2 

 update to [host_perf_vseq](https://github.com/lowRISC/opentitan/pull/17675) covers the timing parameter update partially. Will update the base sequence with timing updates, once https://github.com/lowRISC/opentitan/pull/17675 is merged,

**Comment by marnovandermaas** [comment]
Increasing estimate by 2 because I think there is a day's worth of work left on this.

**Comment by marnovandermaas** [comment]
You're right thanks for checking!
