### ISSUE TITLE
Test_ROM Bitstream Build Error

### ISSUE THREAD

**Issue by supratim-k** [lowRISC/opentitan#17600]
### Description

I am simply trying to build the test_rom bitstream, but it always fails with this error message. I have installed the exact versions of all dependencies specified in the 'Getting Started' documentation.

OS: Ubuntu 20.04
Command that is failing: bazel build //hw/bitstream/vivado:fpga_cw310_test_rom

`
error: linking with /usr/bin/gcc failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/skundu37/.cache/bazel/_bazel_skundu37/37e144886bd49ca4d50697d9648ced13/external/rust_linux_x86_64__x86_64-unknown-linux-gnu__nightly_tools/lib/rustlib/x86_64-unknown-linux-gnu/bin" VSLANG="1033" "/usr/bin/gcc" "-m64" "/tmp/rustcSKVQss/symbols.o" "bazel-out/k8-fastbuild/bin/sw/host/opentitantool/opentitantool.opentitantool.afbe5dce...
`

`
= note: /usr/bin/ld.gold: error: cannot find -lftdi1
          /home/skundu37/.cache/bazel/_bazel_skundu37/37e144886bd49ca4d50697d9648ced13/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/external/lowrisc_safe_ftdi/libsafe_ftdi-922005528.rlib(safe_ftdi-922005528.safe_ftdi.078cba37-cgu.1.rcgu.o):safe_ftdi.078cba37-cgu.1:function safe_ftdi::Context::new: error: undefined reference to 'ftdi_new'
          /home/skundu37/.cache/bazel/_bazel_skundu37/37e144886bd49ca4d50697d9648ced13/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/external/lowrisc_safe_ftdi/libsafe_ftdi-922005528.rlib(safe_ftdi-922005528.safe_ftdi.078cba37-cgu.1.rcgu.o):safe_ftdi.078cba37-cgu.1:func...
`

`
di-922005528.safe_ftdi.078cba37-cgu.1.rcgu.o):safe_ftdi.078cba37-cgu.1:function safe_ftdi::Device::write_data: error: undefined reference to 'ftdi_write_data'
          collect2: error: ld returned 1 exit status
`

`
= note: some extern functions couldn't be found; some native libraries may need to be installed or have their path specified`
`
= note: use the -l flag to specify native libraries to link`
`
= note: use the cargo:rustc-link-lib directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)`
`
error: aborting due to previous error
`

**Comment by mundaym** [comment]
This sounds like libftdi1-dev isn't installed. I suggest checking that you have installed all of the dependencies. See this section of the Getting Started guide for more details: https://staging.opentitan.org/guides/getting_started/index.html#step-2-install-package-manager-dependencies.

I'll close this issue as resolved. Please feel free to reopen if this does not solve your issue.
