### ISSUE TITLE
[testutils] ensure each testutil src file has a unique `MODULE_ID`

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#17605]
### Description

The `status_t` error reporting mechanism enables reporting test status that log the location the error occured, that includes the line number, and MODULE_ID. By [default](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/lib/base/status.c;drc=86a5544966fa82d9715523b5236e88e1072567ef;l=51) the MODULE_ID is the first three letters of the file name. However, it can be overridden by including the line `#define MODULE_ID MAKE_MODULE_ID(...)` at the top of a src file. We need to ensure all the testutils used in manufacturing have a unique MODULE_ID.

**Comment by timothytrippel** [comment]
Thats a good idea, I especially like the bit about having tooling to decode a `status_t`, @moidx and I were just discussing this last week.

**Comment by msfschaffner** [comment]
Moving into the next milestone since we did not end up doing this, and it is marked as a P3.

**Comment by timothytrippel** [comment]
This can be closed now too as #19094 has been merged.
