### ISSUE TITLE
[component] Chip level not all tests need to toggle POR reset

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#17618]
### Description

This issue is brought up by @sha-ron during our discussion.

Some tests such as rom_e2e_boot_policy_valid_a_good_b_good_dev, the sequence might not need to reset the POR pin. We can leave the POR reset pin in active, and the chip should get out of reset by the internal POR mechanism in pwrmgr, once the power is on. This can check the power rampup for some tests.

The action items here are :
- [ ] identity the tests that do not need to drive POR externally.
- [ ] Find a common method to solve this issue in testbench.

**Comment by sha-ron** [comment]
Thinking about again, it is not important for most of the open source tests how the internal por (por_n_i) is asserted.
Also, it might affect FPGA tests, so will handle this in the closed-source.
