### ISSUE TITLE
[EDN] EDN allocation

### ISSUE THREAD

**Issue by rivos-eblot** [lowRISC/opentitan#17654]
### Description

In [EDN documentation](https://opentitan.org/book/hw/ip/edn/index.html#example-topology) the described topology seems to indicate that there are two EDN instances allocated as:
 * EDN0:
     * ep0: AES
     * ep1:  KMAC
     * ep2: OTBN
     * ep3: "Other"
 * EDN1:
    * ep0: Alert
    * ep1: HMAC
    * ep2: KeyManager

However, the Earlgrey variant seems to use a fully different mapping:
  * EDN0:
     * ep0: Key Manager
     * ep1: OTP Controller
     * ep2: AST
     * ep3: KMAC
     * ep4: Alert handler
     * ep5: AES
     * ep6: OTBN URND
     * ep7: Core Ibex

  * EDN1:
     * ep0: OTBN RND

It is also stated that "_There are four request/acknowledge hardware interfaces._"

**Comment by cdgori** [comment]
The diagram located [here](https://opentitan.org/book/hw/ip/edn/index.html) is marked as an example EDN topology.  

We could make that more clear, or change the diagram to match the earlgrey topology.  (I see the clarification is the strategy of #18329 )
