### ISSUE TITLE
[hw,i2c,dv] Update hrst test to cover Target mode state transitions

### ISSUE THREAD

**Issue by crteja** [lowRISC/opentitan#17709]
### Description

Based on observations from https://github.com/lowRISC/opentitan/issues/17448, update `i2c_target_hrst` to issue Start/Stop conditions during target mode transmissions.

 Mode  |  SCL driver | Operation    | Stage        | SDA Driver | Start/Stop condition
 ----- | ----------- | ------------ | ------------ | ---------- | --------------------
 Target|     TB      | Write/Read   | Address Byte |  TB        |  Start/Stop
 Target|     TB      | Write/Read   | Address Ack  |  DUT       |  Start
 Target|     TB      | Write        | Data Byte    |  TB        |  Start/Stop
 Target|     TB      | Write        | Data Ack     |  DUT       |  Start
 Target|     TB      | Read         | Data byte    |  DUT       |  Start
 Target|     TB      | Read         | Data Ack     |  TB        |  Start/Stop

With this, some of the below uncovered transitions should be covered 
### Target mode transitions
transitions | Line No. 
-- | -- 
TransmitWait->Idle |1301
TransmitWait->AcquireStart | 1303
TransmitSetup->Idle |1301
TransmitSetup->AcquireStart |1303
TransmitHold->Idle|1301
TransmitHold->AcquireStart |1303
TransmitAckPulse->Idle |1301
TransmitAck->Idle |1301
TransmitAck->AcquireStart |1303
StretchTxSetup->Idle |1301
StretchTxSetup->AcquireStart |1303
StretchTx->Idle |1301
StretchTx->AcquireStart |1303
StretchAddr->Idle |1301
StretchAddr->AcquireStart |1303
StretchAcqFull->Idle |1301
StretchAcqFull->AcquireStart |1303
AddrRead->AcquireStart |1303
AddrAckWait->Idle |1301
AddrAckWait->AcquireStart |1303
AddrAckSetup->Idle |1301
AddrAckSetup->AcquireStart |1303
AddrAckPulse->Idle |1301
AddrAckPulse->AcquireStart |1303
AddrAckHold->Idle |1301
AddrAckHold->AcquireStart |1303
AcquireStart->Idle |1301
AcquireAckWait->Idle |1301
AcquireAckWait->AcquireStart |1303
AcquireAckSetup->Idle |1301
AcquireAckSetup->AcquireStart |1303
AcquireAckPulse->Idle |1301
AcquireAckPulse->AcquireStart |1303
AcquireAckHold->Idle |1301
AcquireAckHold->AcquireStart |1303
PopFmtFifo->ClockStop | 1063 

> estimate 16
> remaining 2023-03-29 12
> remaining 2023-04-03 1

**Comment by crteja** [comment]
on further analysis of I2C FSM the following state transitions cannot be covered
FSM transitions   | comment
----------------------- | -------------
`AddrAckWait`->`Idle`/`AcquireStart` |  I2C FSM supports only ACK response for write transactions in target mode, since in ACK response SDA is held low by the DUT, `RStart`/`Stop` glitch can not be introduced
`AddrAckSetup`->`Idle`/`AcquireStart` | same as above
`AddrAckPulse`->`Idle`/`AcquireStart` | same as above
`AddrAckPulse`->`Idle`/`AcquireStart` | same as above
`TransmitWait -> Idle/AcquireStart | in TransmitWait state SCL is low, so RStart/Stop can not be introduced
TransmitSetup -> Idle/AcquireStart  | same as above 
TransmitHold -> Idle/AcquireStart | in TransmitHold state SDA is low, so RStart/Stop can not be introduced
StretchAddr -> Idle/AcquireStart | in this state, SCL is held low so RStart/Stop can not be introduced
Stretch* -> Idle/AcquireStart | same as above

which leaves the following transitions, and these are covered with hrst sequence update in https://github.com/lowRISC/opentitan/pull/17746
FSM state transition | 
---|
AddressRead -> Idle
AddressRead -> AcquireStart
Acquirebyte -> Idle
AcquireByte -> AcquireStart
TransmitPulse -> AcquireStart
TransmitACKPulse -> AcquireStart
TransmitACKPulse -> Idle

**Comment by GregAC** [comment]
@crteja if I've understood correctly #17746 solves this in that it covers the things that can be covered and the rest are unreachable?

**Comment by GregAC** [comment]
Great I'll update the remaining to a minimal effort then
