### ISSUE TITLE
[hw,i2c,dv] Add/update test to cover host mode state transitions

### ISSUE THREAD

**Issue by crteja** [lowRISC/opentitan#17710]
### Description

Based on observations from https://github.com/lowRISC/opentitan/issues/17448, add a scenario to disable `host_mode` during operation with DUT in `host_mode`. This will force DUT to enter `Idle` mode and subsequently issue transactions for target mode and check if DUT behaves correctly.
### Host mode transitions
transitions | Line No. 
-- | -- 
PopFmtFifo->AcquireStart | 1303 
atleast one state from Host mode -> Idle |  NA

> estimate 8
> remaining 2023-04-12 4

**Comment by marnovandermaas** [comment]
Addressed by: https://github.com/lowRISC/opentitan/pull/17942
