### ISSUE TITLE
[chip-test, keymgr] Add sequence to test changing OTP root key

### ISSUE THREAD

**Issue by ballifatih** [lowRISC/opentitan#17744]
### Description

Spin-off from the comment https://github.com/lowRISC/opentitan/pull/17739#issuecomment-1487701763.

#17739 removed dynamic latching of OTP root key during block-level `keymgr` testing. In order to cover the case where OTP root key changes (which should not normally happen), we should write a direct sequence for this.

**Comment by ballifatih** [comment]
Duplicate of #17773, so closing this one.

**Comment by cindychip** [comment]
Opps, my bad.. sorry I did not see this one.. Thanks @ballifatih

**Comment by ballifatih** [comment]
No worries @cindychip, we can use the other issue. Should we label the other issue with `Type:FutureRelease` and `Triaged` so that it is not in M2.5 bucket? Or do you think this should be handled before tape out?
