### ISSUE TITLE
[rom e2e] Rewrite e2e_bootstrap_rma using the new jtag API

### ISSUE THREAD

**Issue by pamaury** [lowRISC/opentitan#17742]
### Description

The code currently calls OpenOCD directly. Now that we have the `Jtag` trait in `opentitanlib`, we should be able to convert it to that.

**Comment by pamaury** [comment]
@timothytrippel can we start on this? Should this be tracked in the manufacturing issues or not?

**Comment by timothytrippel** [comment]
yes please, thanks! no need to track in manufacturing board

**Comment by dmcardle** [comment]
@pamaury I'm happy to consult and review!

**Comment by timothytrippel** [comment]
thanks @dmcardle !

**Comment by jwnrt** [comment]
Completed in #17863 and #18151.
