### ISSUE TITLE
[hw,i2c] TXDATA FIFO reset with RSTART/STOP in data byte transmission

### ISSUE THREAD

**Issue by crteja** [lowRISC/opentitan#17750]
### Description

With the update to `i2c_target_hrst_vseq` in https://github.com/lowRISC/opentitan/pull/17746, sequence introduces RStart or Stop condition during active I2C transaction.

In Target mode, during Read data byte transmission, if `RStart` condition is issued as shown in figure below, design is transitioning internal FSM state to `AcquireStart` as expected.

Since this is a glitch and the data in TXDATA fifo is no longer relevant for the request starting with `RStart`, should reset to TXDATA fifo happen via 
- write to FIFO_CTL register ?
- or DUT resets the FIFO internally ? 

![image](https://user-images.githubusercontent.com/124047397/228569807-0d55bc5a-bc17-43a0-a92f-f839276b0696.png)

**Comment by marnovandermaas** [comment]
After some discussions with @crteja and @hcallahan-lowrisc we decided that we can detect this from the Ibex side in device mode by checking whether the receive FIFO is empty on getting a stop interrupt or a read request.

**Comment by marnovandermaas** [comment]
Confirmed that for M2.5 this is low priority.

**Comment by johngt** [comment]
Note from I2C question discussion that Documentation part of this remains.

Summary points;
No RTL change needed. Work-around can be done with SW.
Also to check that this is documented.

**Comment by andreaskurth** [comment]
The plan is to resolve this in #21827, which is currently under review
