### ISSUE TITLE
[dv, kmac] Test sideload capacity zeroing

### ISSUE THREAD

**Issue by ballifatih** [lowRISC/opentitan#17759]
### Description

The PR #17641 solves the issue #17508 by overwriting capacity bits of Keccak state with 0s at the end. However, we do not currently test whether this overwriting is working as expected. 

It would be nice to test both cases:

- For non-sideload operations, full Keccak state can be read by SW at the end
- For sideloaded operations, Keccak state has the correct number of zeroes at the end (should be twice the security strength = capacity)

> estimate 4

**Comment by cdgori** [comment]
Could I request that the title of this PR be changed from "capacity masking" to "capacity blanking" just in the interest of clear terminology?  Otherwise, it will be very confusing to anyone searching for "masking" in the cryptographic sense.

**Comment by moidx** [comment]
@cindychip to evaluate effort so that we can determine if this is something we can do for M2.5. Thanks!

**Comment by ballifatih** [comment]
Indeed the term "masking" is misleading here, I updated the title. Thanks @cdgori.

**Comment by msfschaffner** [comment]
I am moving this to M2.5.2 since I think this is not a critical test that we need to implement for the RTL freeze.

**Comment by msfschaffner** [comment]
@cindychip has this been tested or is this still pending?

**Comment by moidx** [comment]
Discussed with Cindy. This is still a test that needs to be implemented. Moving to V3 based on priorities for M2.5.2.

**Comment by vogelpi** [comment]
I agree that it would make sense to test this. Would it be possible to extend an existing TLT to cover this @ballifatih ? I think this could mean less effort.

**Comment by ballifatih** [comment]
@vogelpi Yes I think extending TLT should be good here (in particular sideload KMAC test), I believe this PR should work: https://github.com/lowRISC/opentitan/pull/23764
