### ISSUE TITLE
[dv/otp_ctrl] Force mubi value for hw cfg read lock

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#17779]
### Description

In current testbench, the `hw_cfg` partition cannot be read locked.
And the current  otp_ctrl_base_vseq function only force the mubi bits to invalid values (non mubi true or false) if the mubi value is `locked`. (Because any invalid values are treated as mubi false, then scb does not need to probe and know the force mubi value)

So, we cannot force the hw cfg partition to invalid mubi values.

This is marked as M3 because in chip level, we can never lock the `hw_cfg` partition's read access.

**Comment by msfschaffner** [comment]
This should be ok since the read access for that partition should not be lockable.
