### ISSUE TITLE
[ci] add hyperdebug board to CI so we avoid top-level test regressions

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#17782]
### Description

Some top-level tests already make use of the hyperdebug board to drive OT pins. Additionally, some manufacturing tests will make use of hyperdebug board to drive the OTTF spi_device console.

Since there is no hyperdebug board connected to any CW310 in CI, we are experiencing test regressions on this platform (most recently #17704 and #17781).

This issue is to track progress getting a hyperdebug board connected to the CW310 boards in CI. Since hyperdebug and CW310 boards are both connected to the host via USB, it is pretty simple to connect (similar to the process of adding the JTAG dongle).

CC: @mundaym @jorge

**Comment by johngt** [comment]
FYI @timothytrippel Swizzle boards are already being manufactured. Being tracked in https://github.com/lowRISC/ot-discrete-eg/issues/3
@moidx - any issues in discussing this in open source - I've kept it closed for now?

**Comment by johngt** [comment]
@jwnrt - could you update on latest status re bitstream selection etc.

**Comment by jwnrt** [comment]
HyperDebug tests need the hyperdebug bitstream which is currently only built on nightly and not with each PR.

There's some discussion in https://github.com/lowRISC/opentitan/pull/18866 about the load that doubling bitstream builds will add.

The discussion has gone towards rebuilding on each PR. Hopefully doing that in parallel to the SAM3X bitstream build won't add any latency to CI, but I'm not familiar with the bottlenecks for bitstream builds (i.e. will we have enough licenses and runners to cope with rebuilding?) Since RTL is frozen, we could potentially use a cached bitstream, but I don't know if the CI is set up to use the cache.

@johngt does this need to be enabled for M2.5.2?

**Comment by jwnrt** [comment]
Thanks @a-will, that's a very helpful map of how the caching works

**Comment by msfschaffner** [comment]
Moving to the next milestone since we were not able to close this for M2.5.2.

**Comment by a-will** [comment]
#19327 will help lay the groundwork for caching the hyperdebug bitstream (in addition to all the other changes that have manifests emitted into the cache). Assuming I've not missed something, it should be as easy as copying the relevant steps from chip_earlgrey_cw310 and swapping the design name.

**Comment by timothytrippel** [comment]
CC: @moidx (relevant for SiVal)

**Comment by jwnrt** [comment]
https://github.com/lowRISC/opentitan/pull/19524

**Comment by timothytrippel** [comment]
just checking again here, @pamaury @jwnrt whats the status of getting Hyper310 tests running in (presubmit) CI?

**Comment by pamaury** [comment]
We have fixed the hyperdebug firmware update problem (#19705) but it needs to be merged. I have created #19732 to test running hyperdebug tests in CI. This requires to build yet another bitstream though.

**Comment by timothytrippel** [comment]
Yeah ideally, once we get hyper310 tests in presubmit, we would switch over all cw310-only tests to be hyper310 tests since and then we could stop building cw310-only bitstream

**Comment by timothytrippel** [comment]
Now that #19732 is merged, the only thing left to close this issue is to make the hyper310 tests blocking right?

**Comment by timothytrippel** [comment]
@pamaury are the hyperdebug tests blocking currently? if so can we close this?

**Comment by pamaury** [comment]
They are not blocking, one needs to remove [this line](https://github.com/lowRISC/opentitan/blob/master/azure-pipelines.yml#L601)
