### ISSUE TITLE
[sysrst_ctrl,sw] DIF support for precondition.

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/opentitan#17786]
### Description

The pre-condition feature for system reset control was added after D3: https://github.com/lowRISC/opentitan/commit/fee5874f2f0cbf30c134b50a89ccfecce65633ad
However, I see no mention of this in the DIF. Can someone have a look at adding this?

**Comment by johngt** [comment]
@moidx / @msfschaffner ; this is blocking for D2.5 of Sysrst_ctrl. Highlighted in Slack.
Changed priority accordingly

**Comment by timothytrippel** [comment]
#17842 will fix this.
