### ISSUE TITLE
[opentitantool] Configuration files dependency declaration

### ISSUE THREAD

**Issue by jesultra** [lowRISC/opentitan#17791]
### Description

The Ti50 team plans on using OpenTitanTool and HyperDebug both with future OpenTitan ASIC as we as current the H1D2 security chip, and possible also older generation of H1 security chips, on custom "shields" sitting on top of HyperDebug.

This will allow us to test that our codebase behaves similarly across the hardware platforms. Or plan is to run exactly identical test scripts to the largest extent possible, and rely on board-specific json configuration files to account for the differences in signal routing.  We will have one configuration file for each of the three hardware setups, which declares e.g. how the OpenTitan pins are mapped to HyperDebug pins, and other for how H1D2 pins are mapped to HyperDebug pins, etc.  On top of that, when running a particular firmware image, that specific image will have some logical name, e.g. "LID_OPEN" mapped to e.g. OpenTitan pin name, another test image could use the same OpenTitan pin for a different logical signal.  So each test execution will use a "stack" of two configuration files, one specific to the hardware, and another specific to the firmware and hardware.  It is important that the two "match", or the pin alias names will not resolve correctly.

I propose a means for letting configuration files declare what they "require" of other configuration files, so that mistakes can be detected early, and not surface during execution of the test int he form of "Unknown pin: A13", or some other error, which could arise if files are mismatched.

Detailed proposal:
A new section in json configuration files, allowing arbitrary key/value pairs:
```
provides: {
  "chip": "opentitan",
  "deep_sleep": "no",
}
```

Another new section, allowing requirements:
```
requires: {
  "chip": "h1d2",
}
```

After loading all configuration files, opentitantool will consolidate the "provides" sections of all the files, and generate an error if multiple values are declared for the same key.  Also, if any key mentioned in any "requires" section is not found in the combined "provides" mapping, or if the value differs, an error is generated.

Furthermore, a command is introduced to allow the test script to query:
```
$ opentitantool transport query deep_sleep
{
  "value": "no"
}
```

The proposed "query" command will allow test scripts to branch in the hopefully few cases in which hardware limitations mean that we cannot test exactly the same thing across different hardware testbeds.  (Maybe the CW310 FPGA implementation does not support deep sleep the same way that OpenTitan ASICs and legacy physical chips do, and the test will have to skip or adapt certain parts)

**Comment by jesultra** [comment]
Pull request #18323 will satisfy this feature request.

**Comment by msfschaffner** [comment]
@jesultra can this issue be closed?

**Comment by msfschaffner** [comment]
Closing since https://github.com/lowRISC/opentitan/pull/18323 has been merged - please reopen if this issue has not been fully addressed.
