### ISSUE TITLE
[crypto] Better `status_t` compatibility for cryptolib.

### ISSUE THREAD

**Issue by jadephilipoom** [lowRISC/opentitan#17803]
### Description

Following up from some previous discussions: https://github.com/lowRISC/opentitan/pull/17762 and https://github.com/lowRISC/opentitan/pull/16930#discussion_r1060866568

The cryptolib currently:
- uses `status_t` internally
- has six hardcoded status values (`crypto_status_t`) in the top-level API
- converts from `status_t` to `crypto_status_t` before every top-level return

This approach has some disadvantages, namely:
- there's a kinda slow and potentially attackable `switch` statement in every top-level return
- testing the top-level API is awkward
  - can't use `status_t` testing infrastructure or e.g. `TRY`
  - I find myself essentially switching the top-level to `status_t` in tests of the top-level API so that I can get debugging information such as line numbers
- the difference between "top-level status codes" and "internal status codes" is a little confusing/complex

So, it would be nice to have something a little more elegant. Some options:
1. Define `crypto_status_t` as `status_t`.
    - (+) simplest option for testing, nice debuggability
    - (+) less complexity for cryptolib implementers, only one error type and nothing special
    - (-) more complex for the caller of the library
    - (-) potentially gives attacker information about where errors occur
2. Make `crypto_status_t`  hardcoded values bit-compatible with `status_t` (e.g. put a hardened value in the `line` field and set the `module` field to a constant, then use an appropriate Abseil code).
    - (+) tests could simply treat them as `status_t`, test infrastructure is easy
    - (+) simple for the caller
    - (-) still no module/line number information in tests
    - (-) still has a subtle difference between `status_t` and top-level
3. Keep the status quo. 

There are tradeoffs for each one, so I'd like to solicit some opinions at this stage. CC @ballifatih @cfrantz @moidx @y-srini , feel free to add others.

**Comment by cfrantz** [comment]
If you choose option (1), is it possible to have the top-level APIs redact the sensitive information from `status_t` before returning?  e.g.:

```
OT_ALWAYS_INLINE
status_t status_redact(status_t sts) {
#ifdef DEBUG
    return sts;
#else 
    return sts == HARDENED_TRUE
        ? sts  // Ok, no change.
        : sts & 0x8000_001F;  // Error: smash all sensitive bits to 0, preserve error in low bits.
#endif
}
```
And then later:
```
status_t my_cool_toplevel_function() {
    status_t sts = some_internal_calculation(...);
    return status_redact(sts);
}
```

Building with `DEBUG` would allow you to still get good error information.  Non-debug versions would redact module and line information before returning from the toplevel APIs.

**Comment by jadephilipoom** [comment]
Hmm, a `DEBUG` definition is a good idea. We can configure test targets to pass it to Bazel.

I'd be a little worried that with option (1) and `status_redact` it would be too easy to accidentally forget the `status_redact`, since you'd get no typecheck errors. We could check it with code review, that's definitely an option. But we could always do option (2) and have essentially the same thing but with more type safety:
```c
crypto_status_t status_redact(status_t sts) {
#ifdef DEBUG
    return sts;
#else 
    return sts == HARDENED_TRUE
        ? (crypto_status_t) sts.value  // Ok, no change.
        : (crypto_status_t) (sts.value & 0x8000_001F);  // Error: smash all sensitive bits to 0, preserve error in low bits.
#endif
}
```
In tests, we'd get `crypto_status_t` values that aren't actually members of the enum, but we'd just add an `INTO_STATUS` clause that casts them back for `status_t` infrastructure.

One other difference between this method and option (1) with `status_redact` is that the very top-level function wouldn't return line numbers in the status code (unless, I suppose, you manually returned `status_redact(OTCRYPTO_BAD_ARGS)` instead of `kCryptoStatusBadArgs`).

**Comment by ballifatih** [comment]
I like the option 1 because of the simplicity it brings. Usually, when there is a trade-off between 1) good debugging information and 2) an obscure counter-measure that brings little security benefit, I favor option 1.

Is it really one of security goals to hide the error line? I would assume that even if we do not print out the line numbers, dedicated attacker could figure out the line number using the fact that everything (or most?) is in the open.

For example, I was trying to modify a top-level test the other day. The returned error code gave very little detail (i.e. internal error), so I had to find the exact line in the DIF library that was causing the error. For that, I used the DV flow to track down the exact line number by looking at TL-UL transactions at HWIP level. Since OT will be in the open, I suppose that the attacker will have the ability to repeat the same.

**Comment by jadephilipoom** [comment]
@ballifatih I agree with you that an attacker can probably just inspect the error using open-source tooling; however, it's significantly more annoying than just handing them the line number. My main hesitation with including the line number in the top level is just that it's a more complicated API. Currently, the caller just checks the errors against hard-coded values. With a line number, they'd have to understand the `status_t` format and properly extract the status. It also means that the cryptolib API, instead of being pretty much self-contained, would include multiple levels of headers describing the format of `status_t` and hardened `status_t`, which live elsewhere in the repo. If the cryptolib needs to have a stable ABI at some point, we would no longer have the freedom to change anything about the `status_t` format because it would break cryptolib. None of that is blocking or impossible to overcome, of course, but I do think there's some simplicity/clarity benefit to error codes that are just one number.

**Comment by ballifatih** [comment]
Thanks for clarifying the trade-off @jadephilipoom. I do not have a strong bias for either option, so I would be OK with either of them. I was just trying to say that there is not much of a security gain/loss by leaking (or not leaking) the line number. Keeping API simpler sounds like a reasonable way to go.
