### ISSUE TITLE
Any other method is available for Simulation other than Synopsys VCS and Cadence Xcelium. 

### ISSUE THREAD

**Issue by ladmangesh805** [lowRISC/opentitan#1782]
I do not have software VCS and Xcelium .
But I want check simulation ,How should I check??
One doubt ..verilator is depends on this VCS and Xcelium??
I was thing of another approach as ILA (Integrated logic Analyzer ) for simulation ,it will work for this opentitan project???

**Comment by imphil** [comment]
No, Verilator doesn't depend on VCS or XCelium, and can be used to record and dump wave forms. Please read https://docs.opentitan.org/doc/ug/getting_started_verilator/ for more information, and read the Verilator manual at https://www.veripool.org/projects/verilator/wiki/Manual-verilator.
