### ISSUE TITLE
[bazel,jtag] Create a macro to simplify the new opentitanlib-based jtag tests

### ISSUE THREAD

**Issue by pamaury** [lowRISC/opentitan#17827]
### Description

The new tests using `opentitanlib` and the `Jtag` trait requires relativelty complex parameters as can be seen in the [test_openocd](https://github.com/lowRISC/opentitan/blob/00b056842175ad3fcdad7a47e4f5c83fb53fb9bc/sw/device/tests/BUILD#L2267) test. We should investigate the creation of a macro similar to `opentitan_gdb_fpga_cw310_test` that hides thoses details.

**Comment by timothytrippel** [comment]
Seems like a good idea. Note, we have longer term plans of refactoring the bazel macros, but I think a simple lightweight wrapper for opentitan_functest, would make sense here to facilitate faster manufacturing test development.
