### ISSUE TITLE
[hw,i2c,dv] I2C protocol transitions coverage

### ISSUE THREAD

**Issue by crteja** [lowRISC/opentitan#17835]
### Description

Implement covergroup in I2C block level TB that covers the following I2C protocol transitions

## Protocol transitions

coverpoint | IP mode| IP mode | Transition | Description
-- | --| -- | -- | --
 | Host | Target | | 
Start_followed_by_Rstart | Y | Y | S->...RS | Valid transfer followed by Rstart condition
Start_followed_by_Stop | Y | Y | S->...P | Valid transfer followed by Stop condition
stop_after_address_ack | Y | Y | S->AD->W/R->A->P | Stop after valid packet of address sent with ACK reply
stop_after_address_Nack | Y | Y | S->AD->W/R->NA->P | Stop after valid packet of address sent with NACK reply
write_address_ack | Y | Y | S->AD->W->A | Device reply with Ack for Write Address
read_address_ack | Y | Y | S->AD->R->A | Device reply with Ack for Read Address
write_address_nack | Y | Y | S->AD->W->NA | Device reply with Nack for Write Address
read_address_nack | Y | Y | S->AD->R->NA | Device reply with Nack for Read Address
Write_data_ACK | Y | Y | S->AD->W->A->D->A | Device ACK for write data
Write_data_NACK | Y | x | S->AD->W->A->D->NA | Device reply with NACK for write data
Read_data_ACK | Y | Y | S->AD->R->A->D->A |  
Read_Data_NACK | x | Y | S->AD->R->A->D->NA |  
Multi_byte_write | Y | Y | D1->A->D2->A->....Dn->A/NA | write multiple bytes to target device
Multi_byte_read | Y | Y | D1->A->D2->A->....Dn->A/NA | read multiple bytes to target device
Stop_after_write_data_ack | Y | Y | S->AD->W->...D->A->P | host issues STOP after valid data transmission for Write
Stop_after_read_data_ack | Y | Y | S->AD->R->...D->A->P | host issues STOP after valid data transmission for Read
Stop_after_write_data_Nack | Y | Y | S->AD->W->...D->NA->P | host issues STOP after write data NACK from device
Stop_after_read_data_Nack | Y | Y | S->AD->R->...D->NA->P | host issues STOP after read data NACK from device
Rstart_after_Address_Ack | Y | Y | S->AD->ACK->RS | host reinitiates transfer before completing/waiting for data transfer
Rstart_after_Address_Nack | Y | Y | S->AD->NACK->RS | Host reinitiates transfer after NACK from device
B2B_write_to_different_device | Y | Y | S->AD1->W->...RS->AD2->W->.. | back to back writes to different device
B2B_read_from_different_device | Y | Y | S->AD1->R->...RS->A2->R->... | back to back reads to different device
Write_after_read_to_different_device | Y | Y | S->AD1->R->A->D...->RS->AD2->W->... | first write and then read to different device address
Read_after_write_from_different_device | Y | Y | S->AD1->W->A->D...->RS->AD2->R->... | first read and then write from different device address
B2B_write_from_same_device | Y | Y | S->AD->W->A->D...->RS->AD->W->... | back to back writes to same device address
B2B_read_from_same_device | Y | Y | S->AD->R->A->D...->RS->AD->R->... | back to back read to same device address
Write_after_read_from_same_device | Y | Y | S->AD->R->A->D...->RS->AD->W->... | first write and then read to same device address
Read_after_write_from_Same_device | Y | Y | S->AD->W->A->D...->RS->AD->R->... | first read and then write from same device address
SCL_stretch_after_write_addr_before_first_write_data | Y | Y | S/RS->AD->W->A->(SCL_Stretch)->D->A/NA->... | Host mode: scenario where FORMAT FIFO has just one entry for address and then empty Target mode: Scenario where ACQDATA FIFO is full after receiving write address from TB
SCL_stretch_after_read_addr_before_first_read_data | Y | Y | S/RS->AD->R->A->(SCL_Stretch)->D->A/NA->... | Host mode: Scenario where target holds the SCL line Target mode: Scenario where ACQDATA FIFO is full after receiving read address byte from TB
SCL_stretch_between_write_data_bytes | Y | Y | D->A->..(SCL_stretch)..->D->A/NA | Scenario where FORMAT FIFO has some entries for WDATA but no entry with STOP/RStart condition
SCL_stretch_between_read_data_bytes | Y | Y | D->A->..(SCL_stretch)..->D->A/NA | Host_mode: Scenario where RDATA FIFO is full and host cannot receive more dataTarget_mode: I2C block cannot accept send more data since TXFIFO is emtpy
read_data_ACK_before_stop | Y | Y | ST->A->R->A->D...->D->A->P | invalid condition, since a NACk is required for read to terminate

RStart/Stop glitches coverage is part of FSM coverage, the states that are covered are mentioned in  https://github.com/lowRISC/opentitan/issues/17709

## Legend
Symbol | meaning
-- | ---
S | Start
A | ACK
NA | NACK
RS | Repeat Start
AD | Address
W/R | Write/read bit
P | Stop
D | Data
W | Write operation
R | Read operation
x | not applicable / irrelevant
Y | can be covered

This issue addresses the following item in https://github.com/lowRISC/opentitan/issues/17458
>  List various bad behaviours/protocol violations we could see in host and target modes, ensure they are tested appropriately

**Comment by marnovandermaas** [comment]
> estimate 16
> remaining 2023-04-11 8
