### ISSUE TITLE
[DV] Cores for generated RAL packages overwrite each other

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1784]
Currently, the `gen_ral_pkg.py` script generates a fusesoc core file and puts it into directories like `$REPO_TOP/scratch/uart.sim.vcs/master/default/gen_ral_pkg/gen_ral_pkg.core`. All cores have the same name `lowrisc:dv:gen_ral_pkg`. When running multiple simulations at the same time, the `scratch` directory fills up with RAL cores.

FuseSoC is instructed to look for all cores in `$REPO_TOP`. It will therefore pick up all `gen_ral_pkg.core` files. Since all cores are named the same, they overwrite each other; only the core file which is found last will be used. Since the directory traversal order is generally undefined, it is not defined which core will actually be used.

There are a couple ways out of it:
- Probably the real solution: Rewrite the `gen_ral_pkg.py` script to be a fusesoc generator, instead of a script called from the Makefile. Then fusesoc takes care that the libraries don't overwrite each other.
- Use unique names for the cores.
- A workaround: Pass a more fine-grained `--cores-root` option to fusesoc, including only the `hw` and the specific scratch directory which is actually used.
- A more far-reaching solution, but always a good idea: Don't create build artifacts, like the `scratch` dir, inside the repository.

FuseSoC warns about replaced cores in verbose mode:

```
cd $REPO_TOP
fusesoc --verbose --cores-root=. list-cores >/dev/null

...
DEBUG: Replacing lowrisc:dv:gen_ral_pkg:0 in ./scratch/usbdev.sim.vcs/primgen/default/gen_ral_pkg with the version found in ./scratch/top_earlgrey.sim.vcs/master/default/gen_ral_pkg
...
```

@sriyerg

**Comment by sriyerg** [comment]
Please define $SCRATCH_ROOT directory as env variable that is outside of the repo. The third "workaround" you've mentioned is already being employed.
Ideally agree with your 4th bullet - never create scratch inside the repo. 

I wanted to explore the fusesoc generator option, but since DV is already lagging way behind, I ended up implementing the quickest solution.

**Comment by sriyerg** [comment]
The tool currently is WAI, so marking this as an enhancement request.

**Comment by imphil** [comment]
`SCRATCH_ROOT` is defaulting to `scratch` inside the source directory; so unless users actively change that, their builds are potentially broken. (That's also true for CI builds.) We either need to enforce SCRATCH_ROOT outside of the source dir somewhere (or at least use such a default), or employ another fix.

**Comment by sriyerg** [comment]
Hi @imphil 
I am giving fusesoc generator another try. The SV file I want to generate depends on another SV package for which a fusesoc core file exists. Is there a way to inject this dependency into the generated core?
