### ISSUE TITLE
[rom] Pull up/down delay when using real IOs

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#17862]
### Description

In real IOs there is a delay (a few usec) between pull enable and until the pad is pulled up/down.
Need to add this delay to https://github.com/lowRISC/opentitan/blob/398c177c52f8a1a9de99598094fd362b1df1052d/sw/device/silicon_creator/lib/drivers/pinmux.c#L109  or somewhere else.
For example, during rom code execution pinmux_init() that activates pull downs on SW straps is called, Until the pull down takes affect, the pin value is unknown and shouldn't be used.

**Comment by sha-ron** [comment]
@alphan I think 5usec should be enough for most IOs.

**Comment by timothytrippel** [comment]
@sha-ron, @alphan  and I were talking today, and the SW straps used for bootstrap are sampled much later than 5 clk cycles (assuming 100mHz clock) from when the pad attributes are set. Its only the RMA straps that @alphan mentioned above that are the issue. Perhaps we could just add a short wait period from when the pad attributes are set to when they are sampled? or move the pad attribute config code earlier in `rom_start.S`?

**Comment by sha-ron** [comment]
Thanks @alphan @timothytrippel for looking into it. Please note that before configuring the AST the frequency can be lower than 100MHz (even 25MHz). I think both options are ok, maybe the second one is safer. Also, it might be best to add the delay also in other places (even tests and not in the rom code) after setting the attribute and before the code continues. Though the rom code is critical and can end up with a bug in the silicon, other places can cause redundant debug when using real IOs simulation.

**Comment by timothytrippel** [comment]
@sha-ron, is this delay required also when changing other pad attributes such as slew rate, drive strength, or any of the other [flags](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/lib/dif/dif_pinmux.h;drc=ef91d455dd5e245cf30182819054194c8548c484;l=148) besides pull up / pull down?

**Comment by sha-ron** [comment]
I think not. @arnonsha please approve.

**Comment by arnonsha** [comment]
Yes
PU/D only

**Comment by timothytrippel** [comment]
I created a draft PR #17959 to fix this, but you all should take a look first to see if this is what we want.
