### ISSUE TITLE
[usbdev] Design sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17875]
### Description

This tracks open design tasks for M2.5.
See effort estimation docs for details.

CC @alees24 @a-will 

>estimate 2

**Comment by johngt** [comment]
Completed with [usbdev D2.5 Review](https://docs.google.com/document/d/1_dfNzxl6F2bCMMm7l7qxhicqWLJD1u7uBB-TGm7G4e0/edit)
