### ISSUE TITLE
[edn] Design sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17879]
### Description

This tracks open design tasks for M2.5.
See effort estimation docs for details.

CC @vogelpi @andreaskurth 

>estimate 4

**Comment by johngt** [comment]
- [ ] NEW_FEATURES_D2.5 [0.5d]
- [ ] REVIEW_RTL [0.5d]

> estimate 4

**Comment by johngt** [comment]
Completed with [EDN D2.5 Review](https://docs.google.com/document/d/1XPIpIFm8WdU9TrCZGEOhNb98hZtT9NRSPEmtzYgCX3U/edit)
