### ISSUE TITLE
[rv_dm] Design sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17874]
### Description

This tracks open design tasks for M2.5.
See effort estimation docs for details.

CC @msfschaffner @gac

>estimate 5

**Comment by johngt** [comment]
Checklist items
- [ ] NEW_FEATURES_D2.5 [2]
- [ ] REVIEW_RTL [2]
- [ ] REVIEW_SW_CHANGE [1]

**Comment by johngt** [comment]
Waiting on resolution of JTAG / RV_DM flakiness issue - https://github.com/lowRISC/opentitan/issues/17729

**Comment by johngt** [comment]
This was resolved with [RV_DM D2.5 Review](https://drive.google.com/drive/folders/1fLxP6EJX7o-g_EeHfwKWrns_8MXtQDvl) 2023-05-12
