### ISSUE TITLE
[spi_device] Design sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17876]
### Description

This tracks open design tasks for M2.5.
See effort estimation docs for details.

CC @hcallahan-lowrisc @abdullahvarici @a-will 

>estimate 26

**Comment by johngt** [comment]
- [ ] NEW_FEATURES_D2.5 (est 0.5d)
- [ ] RTL TODOs (4d)
- [ ] REVIEW_RTL (est 1d)
- [ ] REVIEW_SW_CHANGE (est 1d)

> estimate 26

**Comment by johngt** [comment]
@hcallahan-lowrisc - have stated that these checkbox items above have been closed out.
If something else is needed please re-open and comment how much effort is needed.
