### ISSUE TITLE
[csrng] Design sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17878]
### Description

This tracks open design tasks for M2.5.
See effort estimation docs for details.

CC @marnovandermaas @andreaskurth @vogelpi 

>estimate 1

**Comment by johngt** [comment]
Based on comment by @vogelpi  - Given  #16563 is backlog and #16516 Apr 24 is now backlog. 0 effort.
Leaving as effort 1 task for creating the sign-off doc

**Comment by johngt** [comment]
Completed with sign-off - [csrng D2.5 Review](https://docs.google.com/document/d/1OCSrlQYbyjRO3qyUVVEGGE1ceWwCGCIG1mjk46wvCGI/edit#)
