### ISSUE TITLE
[entropy_src] Design sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17872]
### Description

This tracks open design tasks for M2.5.
See effort estimation docs for details.

CC @vogelpi @andreaskurth 

>estimate 2

**Comment by johngt** [comment]
- [ ] REVIEW_RTL [0.5d]

**Comment by vogelpi** [comment]
The review document is here: https://docs.google.com/document/d/1VorsRpH5tneSEgO_cLaKhvu-xw0YGWWRzhkfdOJsHdU/edit

Currently waiting for feedback from software team before declaring sign-off.

**Comment by johngt** [comment]
@moidx / @cfrantz / @luismarques

**Comment by johngt** [comment]
Signed off on 2023-05-05
