### ISSUE TITLE
[clkmgr] Design sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17884]
### Description

This tracks open design tasks for M2.5.
See effort estimation docs for details.

CC @msfschaffner @matutem

**Comment by matutem** [comment]
Michael, since this is design I may need your help.

**Comment by msfschaffner** [comment]
Hi @matutem - I am already at it for all *mgr design sign-offs. 
It looks like there are no open design TODO's, so it's really just about creating the checklist docs and running through the checklists.

**Comment by msfschaffner** [comment]
[Checklist doc ](https://docs.google.com/document/d/1Bmx6Y5-gVLx8eq_TgBmcXnYCPFd_JH3rJAou9QfGmgM/edit#heading=h.2lzgkooev9uy)

**Comment by msfschaffner** [comment]
Documentation update done in https://github.com/lowRISC/opentitan/pull/18105.
