### ISSUE TITLE
[otbn] Design sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17885]
### Description

This tracks open design tasks for M2.5.
See effort estimation docs for details.

CC @GregAC 

>estimate 8

**Comment by johngt** [comment]
- [ ] NEW_FEATURES_D2.5 [0.5d]
- [ ] REVIEW_RTL [1d]
- [ ] REVIEW_SW_CHANGE [0.5d]

>estimate 8

**Comment by GregAC** [comment]
Design sign off is complete
