### ISSUE TITLE
[entropy_src] Verification sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17889]
### Description

This tracks open verification tasks for M2.5.
See effort estimation docs for details.

Sign-off doc: https://docs.google.com/document/d/1h-AV0molji0VdvLpHEtz1ioD4eaug122WLGBJTl62PY/edit

>estimate 2
>Note not including #18220 as well as NO_ISSUES_PENDING to avoid double counting

**Comment by johngt** [comment]
- [ ] DESIGN_DELTAS_CAPTURED_V2.5 [0.5d]
- [ ] ALL_TODOS_RESOLVED [1d] - https://github.com/lowRISC/opentitan/issues/18220 
- [ ] NO_ISSUES_PENDING [3d] (however no issues seen) (might be 0 now)

**Comment by andreaskurth** [comment]
Done; please see sign-off doc for details.
