### ISSUE TITLE
[kmac] Design sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17882]
### Description

This tracks open design tasks for M2.5.
See effort estimation docs for details.

CC @ballifatih @cindychip

**Comment by ballifatih** [comment]
[KMAC D2.5 sign-off](https://docs.google.com/document/d/10khVj_GOEb-daqxzdAKwLLVUPQpACTy5DMbUTI_HuRg/edit) is complete, so I am closing this issue.
