### ISSUE TITLE
[rv_core_ibex] Design sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17888]
### Description

This tracks open design tasks for M2.5.
See effort estimation docs for details.

CC @gac

>estimate 6

**Comment by johngt** [comment]
- [ ] NEW_FEATURES_D2.5 [0.5d]
- [ ] REVIEW_RTL [0.5d]
- [ ] REVIEW_SW_CHANGE [0.5d]

**Comment by GregAC** [comment]
Design sign-off is complete
