### ISSUE TITLE
[aes] Design sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17883]
### Description

This tracks open design tasks for M2.5.
See effort estimation docs for details.

CC @vogelpi

>estimate 7

**Comment by johngt** [comment]
- [ ] NEW_FEATURES_D2.5 [0.25d]
- [ ] REVIEW_RTL [0.5d]
- [ ] REVIEW_SW_CHANGE [1d]

**Comment by vogelpi** [comment]
Update: sign-off document is prepared [here](https://docs.google.com/document/d/1OhisCfiHCyID-MrP0XVXgS51n9jHNG3WxPWQzBxTQQg/edit#heading=h.rqwofvkgrwnh). Currently doing SCA investigations. Once these have been concluded, we can do the sign-off.

**Comment by johngt** [comment]
Leaving this here until after the security WG meeting

**Comment by mundaym** [comment]
@vogelpi are you happy to close this issue now?

**Comment by vogelpi** [comment]
Yes, I am finishing the sign-off doc right now.

**Comment by vogelpi** [comment]
Sending out the messages in a couple of minutes.

**Comment by vogelpi** [comment]
Okay, it's done now. I am closing this.
