### ISSUE TITLE
[edn] Verification sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17896]
### Description

This tracks open verification tasks for M2.5.
See effort estimation docs for details.

Sign-off doc: https://docs.google.com/document/d/1q1rPcLQwiuh6HKR4ZNkpmC1nbas48KOcWn7tBuZKtp8/edit

CC @andreaskurth @vogelpi 

>estimate 4

**Comment by johngt** [comment]
- [ ] DESIGN_DELTAS_CAPTURED_V2 [0.5d]
- [ ] SIM_CODE_COVERAGE_AT_90 [0.5d]
- [ ] SIM_FUNCTIONAL_COVERAGE_AT_90 [0.5d]

**Comment by andreaskurth** [comment]
Sign off complete
