### ISSUE TITLE
[spi_host] Verification sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17894]
### Description

This tracks open verification tasks for M2.5.
See effort estimation docs for details.

CC @andreaskurth @hcallahan-lowrisc @a-will 

>estimate 3

**Comment by johngt** [comment]
- [ ] DESIGN_DELTAS_CAPTURED_V2.5 [0.25d]
- [ ] ALL_TOOL_WARNINGS_ARE_REVIEWED [0.5d]

**Comment by msfschaffner** [comment]
Closing since SPI_HOST has been signed off.
Please re-open if that is not accurate.
