### ISSUE TITLE
[spi_device] Verification sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17893]
### Description

This tracks open verification tasks for M2.5.
See effort estimation docs for details.

CC @hcallahan-lowrisc @abdullahvarici @a-will 

>estimate 12

**Comment by johngt** [comment]
- [ ] DESIGN_DELTAS_CAPTURED_V2.5 [2d]
- [ ] ALL_TOOL_WARNINGS_ARE_REVIEWED [1d]

**Comment by johngt** [comment]
SPI_Device signed off on 2023-06-28
Waivers captured in doc
