### ISSUE TITLE
[rv_dm] Verification sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17891]
### Description

This tracks open verification tasks for M2.5.
See effort estimation docs for details.

CC @msfschaffner @GregAC 

>estimate 13

**Comment by johngt** [comment]
- [ ] DESIGN_DELTAS_CAPTURED_V2.5 [1d]
- [ ] X_PROP_ANALYSIS_COMPLETED [0.25d]
- [ ] ALL_TODOS_RESOLVED [1d] - see effort estimation doc
- [ ] ALL_TOOL_WARNINGS_ARE_REVIEWED [1d]

**Comment by msfschaffner** [comment]
Indeed, moving to M2.5.2 SGTM!

**Comment by GregAC** [comment]
Closing this as we are not closing rv_dm block level verification for M2.5.2
