### ISSUE TITLE
[csrng] Verification sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17895]
### Description

Sign off doc: https://docs.google.com/document/d/1hZJ-QNi-B9gzoWu0aBV6BRAPmZ3UZ6rhAg7ENS8d4CE/edit

This tracks open verification tasks for M2.5.
See effort estimation docs for details.

CC @marnovandermaas @andreaskurth @vogelpi 

Also see [#17418](https://github.com/lowRISC/opentitan/issues/17418) [4d tracked there]

>estimate 4

**Comment by johngt** [comment]
- [ ] DESIGN_DELTAS_CAPTURED_V2.5 [1d]

**Comment by vogelpi** [comment]
I am closing this issue as CSRNG V2.5 sign-off happened just now. Thanks @andreaskurth !
