### ISSUE TITLE
[i2c] Verification sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17890]
### Description

This tracks open verification tasks for M2.5.
See effort estimation docs for details.

CC @marnovandermaas @hcallahan-lowrisc @a-will 

> estimate 8

**Comment by marnovandermaas** [comment]
Also tagging @crteja in this one

**Comment by marnovandermaas** [comment]
Based on the effort scoping, this is an initial estimate.

> estimate 8

**Comment by marnovandermaas** [comment]
After adding some extra covergroups, the functional coverage numbers are lower. We need to decide how to improve this:


![Image](https://user-images.githubusercontent.com/34654485/233614940-23ebe7fd-c891-4144-972b-65a578abe8d7.png)

**Comment by marnovandermaas** [comment]
@crteja would you mind having a look at whether the sample function calls can be fixed? Otherwise, we might need to defer some of these covergroups to after M2.5.

**Comment by crteja** [comment]
Added sample calls for the newly added covergroups in https://github.com/lowRISC/opentitan/pull/18119

**Comment by marnovandermaas** [comment]
Linking the draft V2 PR here: https://github.com/lowRISC/opentitan/pull/18211

**Comment by marnovandermaas** [comment]
Document tracking this is here: https://docs.google.com/document/d/1z3bShxmEIPVI99yqZTNV3hgZ7WWH_HQmrpATxC8dg8E/edit (restricted access)

Essentially, this PR needs to be merged before closing: https://github.com/lowRISC/opentitan/pull/18983

**Comment by johngt** [comment]
@crteja - I think that https://github.com/lowRISC/opentitan/pull/18983 has been merged so that was the final issue @marnovandermaas wanted before sign-off. If so please just make a quick check that there are no outstanding issues that have not been identified in the document (e.g. ECOs) and then we can close this off / announce V2.5. TIA

**Comment by msfschaffner** [comment]
The ECO has been merged, so it looks like the main open now is https://github.com/lowRISC/opentitan/issues/18985.

**Comment by crteja** [comment]
Closing this issue as https://github.com/lowRISC/opentitan/issues/18985 is resolved and there are no outstanding open issues.
