### ISSUE TITLE
[clkmgr] Verification sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17907]
### Description

This tracks open verification tasks for M2.5.
See effort estimation docs for details.

- [x] #16836
- [x] #17988
- [x] Clean TODOs
  - [x] Complete TODOs in DV code (1.5 d .. 4 d) may be partly covered by [18380](https://github.com/lowRISC/opentitan/issues/18380).  [#18429](https://github.com/lowRISC/opentitan/issues/18429)
- [x] Complete V2.5 checklist items not captured elsewhere (0.75 d .. 1 d) [#18430](https://github.com/lowRISC/opentitan/issues/18430)
 
CC @matutem @msfschaffner 

>estimate 20

**Comment by msfschaffner** [comment]
Apologies for reopening this, @matutem.
There are two TODO issues for this block that have been filed today - but I am not sure these still apply.
I.e., you may already have addressed them (in which case we should close them):

https://github.com/lowRISC/opentitan/issues/18429 
https://github.com/lowRISC/opentitan/issues/18430

**Comment by matutem** [comment]
All items were closed already, and clkmgr was signed off for M2.5.
