### ISSUE TITLE
[lc_ctrl] Verification sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17900]
### Description

This tracks open verification tasks for M2.5.
See effort estimation docs for details.

- [x] https://github.com/lowRISC/opentitan/issues/18369

CC @gdessouky @cindychip 

>estimate 14

**Comment by johngt** [comment]
- [ ] SIM_NIGHTLY_REGRESSION_AT_V2.5 [1d]
- [ ] SIM_CODE_COVERAGE_AT_90 [2d]
- [ ] ALL_TOOL_WARNINGS_ARE_REVIEWED [0.5d]

**Comment by johngt** [comment]
Given the rest is checklist and #18369 is covered elsewhere - shifting this
