### ISSUE TITLE
[pwrmgr] Verification sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17910]
This tracks open verification tasks for M2.5.
See effort estimation docs for details.

- [x] #17500
- [x] Clean TODOs

CC @matutem @msfschaffner

**Comment by msfschaffner** [comment]
@matutem I am not sure but we may be able to close https://github.com/lowRISC/opentitan/issues/18434 since it looks like you may already have done that.

**Comment by matutem** [comment]
The issue https://github.com/lowRISC/opentitan/issues/14887 was moved to backlog.
