### ISSUE TITLE
[pwm] Verification sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17913]
### Description

This tracks open verification tasks for M2.5.
See effort estimation docs for details.

CC @marnovandermaas

**Comment by rnongie** [comment]
- [ ] #18390 V2.5 TODOs

**Comment by rswarbrick** [comment]
I suspect this issue can be closed altogether because it's essentially just a length-one list that points at another issue. Marking as a triage priority.

**Comment by timothytrippel** [comment]
Closing as #18390 tracks remaining work (as @rswarbrick points out).
