### ISSUE TITLE
[rstmgr] Verification sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17915]
This tracks open verification tasks for M2.5.
See effort estimation docs for details.

- [ ] Clean TODOs

CC @msfschaffner @matutem

**Comment by matutem** [comment]
Should this contain checkboxes for pending issues?

**Comment by msfschaffner** [comment]
At the moment this is just a placeholder.
If you'd like to add more details and link to the individual issues, you are welcome to.
