### ISSUE TITLE
[rust] Bring in pqcrypto crate

### ISSUE THREAD

**Issue by jon-flatley** [lowRISC/opentitan#17933]
### Description

I'm trying to add the `pqcrypto-sphincsplus` crate into `opentitanlib`, but I'm running into some trouble during the build. I can add the crate to `crate_universe` just fine, but during `bazel build //sw/host/opentitanlib:opentitanlib_test` I see

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', external/crate_index__pqcrypto-sphincsplus-0.6.4/build.rs:135:5
```

Looks like bazel can't find a file, but I don't know my way around bazel well enough to figure out which file it may be. This should be reproducible on my branch https://github.com/jon-flatley/opentitan/tree/sphincsplus.

I also tried pointing `Cargo.toml` at a local checkout of `pqcrypto` to be able to modify the `build.rs`, but that came with it's own set of problems

```
Error: Failed to splice workspace

Caused by:
    Missing root workspace manifest. Please add the following label to the `manifests` key: "//third_party/rust:Cargo.toml
```

**Comment by cfrantz** [comment]
Are you able to build that library independently (outside of opentitan, using cargo instead of bazel) ?

**Comment by jon-flatley** [comment]
Thanks for taking a look at this @cfrantz! This seems to work when building opentitanlib with `pqcrypto-spincsplus` included, but if I try using it I get a linker error `undefined symbol: PQCLEAN_randombyte`. I'm going to keep investigating, but in the mean time I've updated [my branch](https://github.com/jon-flatley/opentitan/commits/sphincsplus) to reproduce the issue.

**Comment by cfrantz** [comment]
I forgot: when `build.rs` executes it's own `cc` compile action, its PWD is inside the crate.  Bazel's convection is to run the tools at the project root.
Therefore:
```
diff --git a/third_party/rust/BUILD b/third_party/rust/BUILD
index eeea6779f..c673a9ac7 100644
--- a/third_party/rust/BUILD
+++ b/third_party/rust/BUILD
@@ -20,7 +20,7 @@ crates_vendor(
                 "@crate_index__pqcrypto-internals-0.2.4//:include",
             ],
             build_script_env = {
-                "DEP_PQCRYPTO_INTERNALS_INCLUDEPATH": "external/crate_index__pqcrypto-internals-0.2.4/include",
+                "DEP_PQCRYPTO_INTERNALS_INCLUDEPATH": "../crate_index__pqcrypto-internals-0.2.4/include",
             },
         )],
     },
```

And then perform the `repin` action.

**Comment by jon-flatley** [comment]
That seems to work! Thanks for figuring this out!
