### ISSUE TITLE
[test] Use debugger to halt CPU during RMA spinloop

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#18044]
@pamaury @jwnrt @moidx @alphan another side note: I think the intent was to use the debugger to halt the processor during the RMA busy loop so that the ROM code is stopped and does not reset the chip. This may not be important for the open-source test, but since the timing in the closed source for flash writes / erase could be drastically different from the FPGA timing, it would be prudent to do. We can track this in a separate issue, though.

_Originally posted by @msfschaffner in https://github.com/lowRISC/opentitan/issues/17944#issuecomment-1513859420_

**Comment by msfschaffner** [comment]
@moidx do you think this is critical for M2.5, or should we defer this?

**Comment by alphan** [comment]
I don't think we were planning to halt the CPU explicitly. The CPU checks the straps and spins for just enough cycles to let the transition begin.

**Comment by alphan** [comment]
Also, @dmcardle already wrote an e2e test for this.

**Comment by pamaury** [comment]
My understanding of the TAP selection mecanism is that it is only [sampled once](https://opentitan.org/book/hw/ip/pinmux/doc/theory_of_operation.html#strap-sampling-and-tap-isolation) at boot in all states but TEST, RMA and DEV. In fact, I don't even think the RISC-V TAP is accessible in those states and even if it was, we cannot use it if we want to use the LC TAP to perform the transition. This means that the debugger cannot be used to halt in the RMA spin loop if the chip is in PROD for example.

**Comment by msfschaffner** [comment]
Hi @pamaury - you are absolutely right. I misremembered this part.

We can actually rely on the life cycle controller idle status, which will prevent the power manager from going into reset if a life cycle transition is ongoing. Hence, halting the processor during the RMA loop is not necessary.
