### ISSUE TITLE
Any other method is available for Simulation other than Synopsys VCS and Cadence Xcelium.

### ISSUE THREAD

**Issue by ladmangesh805** [lowRISC/opentitan#1805]
Specially HMAC core ??
How it is possible using ILA??

**Comment by imphil** [comment]
@ladmangesh805 you asked more or less the same question in https://github.com/lowRISC/opentitan/issues/1782 and https://github.com/lowRISC/opentitan/issues/1719 and got good answers there.

Can you please have a look at the answers in these issues? If you have trouble using ILA you need to have a look at the Xilinx web site and their forums, it's not something we can help you with here unfortunately. As said in other comments, we encourage you to use Verilator. You can find information on that on the Verilator web site and in our documentation at https://docs.opentitan.org/doc/ug/getting_started_verilator/.
