### ISSUE TITLE
[test-triage] Timeout - chip_sw_alert_handler_lpg_sleep_mode_alerts

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#18053]
### Hierarchy of regression failure

Chip Level

### Failure Description

Job chip_earlgrey_asic-sim-vcs_run_default killed due to: Exit reason: User job exceeded runlimit: User job timed out

### Steps to Reproduce

- GitHub Revision: [24fcee5a4](https://github.com/lowrisc/opentitan/tree/24fcee5a423290416785a58ca3de6328646c1bc9)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
```
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_alert_handler_lpg_sleep_mode_alerts --build-seed 4127990797 --fixed-seed 3423998875 --waves fsdb
```

### Tests with similar or related failures

- [ ] chip_sw_alert_handler_lpg_sleep_mode_alerts

**Comment by johngt** [comment]
As this is a V2 test - assigning as P1 priority for now. Given that this is a timeout there may be no underlying issue other than increasing the timeout time for this test.

**Comment by a-will** [comment]
Fails due to a fatal lc_ctrl alert (FSM state changed to invalid), which prevents software from continuing with just an NMI.
