### ISSUE TITLE
[otbn] Overwrite DMEM contents using new scrambling key before RMA entry

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#18114]
### Description

As suggested in https://github.com/lowRISC/opentitan/issues/17944#issuecomment-1516533570 and agreed in a meeting on THU Apr 20, we want to change the RMA entry routine of OTBN medium term to not only switch the scrambling key as during regular secure wipe, but to also overwrite the current DMEM contents using the new scrambling key. This helps to improve security. For a detailed analysis from a security viewpoint, refer to https://github.com/lowRISC/opentitan/issues/17944#issuecomment-1516233498.

Notes:
- This is not strictly required for M2.5 but we would like to add this soon after. For now, I've assigned myself and @andreaskurth to make sure we don't forget about it.
- Overwriting with anything, even a fixed value should be fine.
- We were also thinking about adding the overwrite routine to the scrambled memory primitive together with a 4-phase handshake protocol.
- It is understood that we the regular secure wipe shouldn't get any slower because it's used very frequently. The goal is really to just trigger this overwrite upon RMA entry. For details, see https://github.com/lowRISC/opentitan/issues/17944#issuecomment-1517488373.

@msfschaffner @johannheyszl @moidx @alphan @GregAC

**Comment by johannheyszl** [comment]
Thx. 
Later and before a change, it might be worth checking, how likely or feasible it is that OTBN has executed crypto on private keys _last_ before the RMA-triggered wipe.

**Comment by johannheyszl** [comment]
The topic was also discussed in #13546

**Comment by johannheyszl** [comment]
as per offline discussion with @vogelpi:
- Even the best possible attack ([here](https://github.com/lowRISC/opentitan/issues/17944#issuecomment-1516233498)) is not effective. Only parts of the last DMEM content before rma ENTRY can be recovered with high effort and only with possession of RMA tokens.
- We recommend closing the issue

**Comment by msfschaffner** [comment]
Thanks for the analysis - closing as per recommendation.

CC @moidx
