### ISSUE TITLE
Basic hello_world test failing on FPGA

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#1813]
Following the 'Getting started on FPGAs' instructions (https://docs.opentitan.org/doc/ug/getting_started_fpga/) results in a hello_world binary that doesn't seem to work.

spiflash appears to succesfully load the binary but something goes wrong and we end up in the exception handler of the bootrom, mepc is set to a value that isn't a PC for any valid instruction (0x464c457e) mtval is the same, mcause is 1, which is an 'instruction access fault'.

I guess the boot rom is jumping to an invalid start address?

**Comment by imphil** [comment]
Please file an issue for spiflash to detect elf files, that's simple to do and I agree, it's a easy mistake.
