### ISSUE TITLE
[doc] Broken links on /book/hw

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#18153]
### Description

It looks like all the links are broken in the "Design Spec", "DV Document", and "Development Stage" columns are broken on <https://opentitan.org/book/hw/>.

**Comment by mundaym** [comment]
Thanks for the report @dmcardle!

> Should this be merged into #17658?

No, that's about links to sites that no longer exist. These seem to be broken links pointing within the documentation book itself.

cc @hcallahan-lowrisc

**Comment by dmcardle** [comment]
> Thanks for the report @dmcardle
> 
> I've inherited #18052 from @hcallahan-lowrisc which I'll try to get fixed up and ready to go in tomorrow.
> 
> Closing this issue, as this is already tracked in #17591.

Feel free to add me as a reviewer!

**Comment by dmcardle** [comment]
> > Thanks for the report @dmcardle
> > I've inherited #18052 from @hcallahan-lowrisc which I'll try to get fixed up and ready to go in tomorrow.
> > Closing this issue, as this is already tracked in #17591.
> 
> Feel free to add me as a reviewer, @HU90m!
