### ISSUE TITLE
[daily_ot/regression] Deal with license check out errors

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#1820]
Currently, if the license check out for the simulation tool fails for the daily sanity checks, such runs enter as failures into the results summary. This makes our summary (currently at https://reports.opentitan.org/hw/top_earlgrey/dv/summary.html) look worse than it actually is. For example, AES passes less than 35% of the tests, and we get the following errors on the [AES Simulation Results](https://reports.opentitan.org/hw/ip/aes/dv/latest/results.html) page:
```
xrun(64): 18.09-s011: (c) Copyright 1995-2019 Cadence Design Systems, Inc.

Trying to check out license...
	Xcelium_Single_Core 18.00 - Failed
	Xcelium_Single_Core_Legacy 18.00 - Failed
	Xcelium_Safety 18.00 - Failed
	Xcelium_Multi_Core 18.00 - Failed
	Xcelium_For_Partners 18.00 - Failed
xmsim: *F,NOLICN: Unable to checkout license for the simulation. 'lic_error -5'.
make: *** [/usr/local/google/home/weicai/daily_ot/hw/dv/data/sim.mk:71: simulate] Error 2
```

I think we should try to catch those errors and for example repeat the test until we actually get a license, or (as a quick workaround) not update the results if we get such errors. Especially as we move towards publishing more results more prominently (#1695), such things may give a bad first impression.

**Comment by vogelpi** [comment]
@sriyerg and @weicaiyang, what do you think? Is there an easy way of improving the situation?

**Comment by imphil** [comment]
There's typically a "wait for license" option with all those tools. I'm pretty sure we set this option for VCS, maybe it's just not set for Xcelium?

**Comment by weicaiyang** [comment]
Thanks @vogelpi for reporting it.
Someone reported a license server issue in Google as well. Will add below option to see if it can be resolved.
`  -licqueue                  Queue simulation till license is available
`

**Comment by sriyerg** [comment]
Hey @weicaiyang, I already made a PR for it. 
Note that we experience license outages every so often, which are out of our scope. Note that results update every night, so it should clear up.

**Comment by weicaiyang** [comment]
> Hey @weicaiyang, I already made a PR for it.
> Note that we experience license outages every so often, which are out of our scope. Note that results update every night, so it should clear up.

Thanks @sriyerg
