### ISSUE TITLE
[connectivity] top_earlgrey ast_mem_cfg.csv isn't reusable for foundry tests

### ISSUE THREAD

**Issue by dkabely-ot** [lowRISC/opentitan#18214]
### Description

`ast_mem_cfg.csv` uses explicit `gen_generic` and `u_impl_generic` paths for connectivity checks:
https://github.com/lowRISC/opentitan/blob/380e7eed9e0f05c293a3b5e7938b0602dbc144f8/hw/top_earlgrey/formal/conn_csvs/ast_mem_cfg.csv#L20-L43 

This prevents the file from being reusable for foundry chip connectivity tests, and in fact breaks conn tests loading in Jasper and prevents other csvs from being loaded.

**Comment by msfschaffner** [comment]
The last level of hierarchy `gen_generic.u_impl_generic` is automatically generated for these modules.
It should therefore be enough to test connectivity down to the wrapper level only, especially if there are more tests in closed source that actually test these SRAM attributes.

**Comment by msfschaffner** [comment]
I just noticed that this CSV will have to be updated to conform with #18099. 
I will do that in the same PR.
