### ISSUE TITLE
[manufacturing] investigate using UART console in manufacturing to avoid relying on SPI generic mode

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18221]
Based on SPI effort scoping (see doc associated with that for further details), the purpose is to avoid needing to rely on SPI generic mode.

**Comment by johngt** [comment]
@moidx - following up a comment / ai thread item in SPI_Device effort estimation doc.
Please feel free to close this if this has been addressed already.

**Comment by moidx** [comment]
The test infrastructure now supports the ability to use SPI or UART.  For M2.5 we should be ok.
