### ISSUE TITLE
[PLIC] PLIC Interrupt IDs Off-by-one Issues

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#1823]
The PLIC interface is confusing and has some oddness which manifests as the potential for off-by-one errors in software.

This comes from the fact that the interrupt id, `i` (as read from `CC<n>`) corresponds to the priority in `PRIO<i-1>`. This is because interrupt id `0` means "no interrupt", which does not need a corresponding priority register.

It would be nice if this off-by-one issue was resolved, I can see two potential resolutions, but it would be good to understand how this affects the hardware design (and verification). I see that `rv_plic` is currently `L1D0V0`, but I think given how it's going to be verified that may not be a reflection of reality.

Possible Changes:
1. We choose a different value to represent "no interrupt", allowing interrupt id `i` to correspond to the `PRIO<i>` register. A string of all-ones (`0xFFFFFFFF`) would make sense for this other value.
2. Create a `PRIO` register for the case of "no interrupt", which is useless (and potentially not connected to anything), but means that `PRIO<i>` corresponds to interrupt id `i`.

I would be interested to hear the possibilities here from the hw side

**Comment by msfschaffner** [comment]
Thanks for bringing this up @lenary. 

Looping in @eunchan who originally designed the PLIC, and @cindychip who owns the DV side of it.


The "reserved" interrupt id 0 seems to be a peculiarity, but it is part of the PLIC spec and we should not remap those values in order to stay compliant. Therefore, I think 2. is the right way to go here, and it looks like the si-five chips resolve this in that way as well. E.g., look at the "PLIC Register Map" table in [this document](https://static.dev.sifive.com/FU540-C000-v1.0.pdf).

**Comment by lenary** [comment]
Ah, nice, I see what they're up to. Ok, so we can make `PRIO0` reserved and start at `PRIO1`? That sounds reasonable. Hopefully that avoids any particularly onerous hardware changes too.

**Comment by eunchan** [comment]
As @msfschaffner mentioned, I think having reserved PRIO0 is good. Before implementing this, I think it is good to check current linux driver and its address map for RISC-V PLIC.

**Comment by silvestrst** [comment]
If `PRIO0` will be reserved, would it still be legal to write into it (even if nothing happens)? Would make it easier to loop through all the `PRIO*` registers.

**Comment by silvestrst** [comment]
If we are changing `PRIO`, we might as well make bit `0` in the other registers reserved as well (`IP`, `LE`, `IE`). As at the moment IRQ with ID `1`, is bit `0` of `IP`, `IE`, `LE` registers.

**Comment by lenary** [comment]
#1950 has been merged!

The approach taken in the end was to effectively create a PRIO0 register that corresponded to source id 0 (and so not having any effect in the RTL, really), and ensure bit 0 in the other source-specific registers corresponded to source id 0. This corresponds to the most recent wording of the PLIC spec, and removes any nasty off-by-one expressions in the DIF.
