### ISSUE TITLE
[aes:dv] checking for residual data

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#1824]
in the AES verification environment we need to verify that no residual data is visible to a user, even when the AES module is used maliciously.

which raises the question of what is the best way to detect residual data in the DUT registers.
also how much correlation should we have before we conclude the data is residual.

Currently there is two suggestions

- have the reference model provide all intermediate calculations

- simulate the LFSR
actually creating a reference model for the LFSR will be very difficult if not impossible as the reference model runs in 0 time so we would have to calculate how many shifts to do before taking the value. using an output from the DUT might be more feasible. 

any comments or suggestions are most welcome

**Comment by vogelpi** [comment]
Thanks @rasmus-madsen for opening the issue.

I think having the reference model doing all the intermediate results (after every AES round) is simpler. Also, we only need to do this if we are actually checking for residual data. So the C model does not need to be run constantly.

Having a reference model for the LFSR is more work but it also allows us to test if e.g. the re-seeding works properly. I thus slightly tend towards this option.

**Comment by martin-lueker** [comment]
Hey Rasmus: So if I understand correctly, the LFSR here could be any entropy source.  The real goal is to ensure that well-defined user bits are replaced with _anything else_, right?  
If that's the case would it be possible to fill the DUT registers with X's?  It might raise some assertions, I guess, but that would be one way to simulate entropy inputs in this particular case.

**Comment by rasmus-madsen** [comment]
> Hey Rasmus: So if I understand correctly, the LFSR here could be any entropy source. The real goal is to ensure that well-defined user bits are replaced with _anything else_, right?
> If that's the case would it be possible to fill the DUT registers with X's? It might raise some assertions, I guess, but that would be one way to simulate entropy inputs in this particular case.

that is actually not a bad Idea it is simple and clean.
at least for the scenarios where the DUT is reset.

**Comment by vogelpi** [comment]
Interesting idea @martin-lueker!

One thing to keep in mind is to perform an ECB/CBC decryption using this X input. Otherwise, the Xs won't make it to the registers that are not writable via TLUL (internal cipher state, full key, decryption key, output).

**Comment by rasmus-madsen** [comment]
> Interesting idea @martin-lueker!
> 
> One thing to keep in mind is to perform an ECB/CBC decryption using this X input. Otherwise, the Xs won't make it to the registers that are not writable via TLUL (internal cipher state, full key, decryption key, output).

Not sure it makes sense then.
what I was thinking is just feed x to the registers when AES is reset or cleared.
