### ISSUE TITLE
[otbn/rtl] Holes in end to end integrity implementation

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#18266]
### Description

Upon reviewing OTBN as part of D2.5 sign-off I found a few holes in our end to end integrity. These are paths where we could use the integrity from the source to write to the destination, rather than re-calculate it, but don't

* GPR to/from `MOD0` to `MOD7` 
* WDR to `ACC` or `MOD`

`MOD0` to `MOD7` to GPR is documented as existing but with a TODO next to it (see https://opentitan.org/book/hw/ip/otbn/index.html#register-file-integrity-protection). The others aren't explicitly mentioned anywhere (did a little digging through D2S sign off and such) but are possible.

I don't feel this is a critical issue for M2.5 but we may want to fix it for post M2.5 in particular the WDR to `ACC` or `MOD` path. We could consider writing some assertions to ensure integrity is preserved in all scenarios we expect it to be to give confidence there are no other holes.

No estimate for now until we've decided if anything is required for M2.5 here.

A little more background here: https://github.com/lowRISC/opentitan/pull/17731 

@andreaskurth @msfschaffner @moidx @vogelpi @johannheyszl @cdgori any thoughts?

**Comment by vogelpi** [comment]
My view is that for M2.5:
- The SVAs to check that integrity is preserved isn't critical.
- Regarding feeding through integrity bits instead of re-calculating them for the two known paths: Precise timing would be required to glitch the data while being in flight. Thus, I think this isn't super critical either. However, feeding through instead of re-calculating would also be better in terms of SCA. So in case it's really easy to do this change and if there is no DV impact, I would say let's do it before M2.5.

**Comment by johannheyszl** [comment]
@jadephilipoom can you pls help us with your SW perspective here? 
Some thoughts for your consideration pls:
- I am assuming some of the mentioned data paths are not an issue. E.g. I assume we load MOD from DMEM, not from GPRs,  WDRs or even ACC. If I understood right, ACC to WDR is covered though. 
- We will use higher-level countermeasures in SW. 
- Confidentiality=SCA is less of an issue for values in MOD.

**Comment by msfschaffner** [comment]
I agree with @vogelpi's assessment. 
I'd prefer to not touch the RTL before M2.5 unless @johannheyszl and @jadephilipoom think this is absolutely needed.

**Comment by jadephilipoom** [comment]
From my point of view, we can leave this until after M2.5.

- The  GPR to/from `MOD` path is not used at all  in current OTBN code; we only use WDRs.
- The `WDR -> ACC` path is also not used at all  -- assuming this means just direct `bn.wsrw` instructions that write to `ACC` and does not include `bn.mulqacc`. (The latter is used a lot, and might change my opinion.)
- Loading a modulus typically means loading from DMEM into a WDR and then loading to MOD, so it sounds to me like that path is affected.
  - However, there's a pretty straightforward software countermeasure we can use for the `WDR -> MOD` path; just read back the value from `MOD` with `bn.wsrr` and check that it matches the register we used to write `MOD`.

**Comment by johannheyszl** [comment]
thx @jadephilipoom, this is what I had hoped for -> let's address it post-M2.5

**Comment by msfschaffner** [comment]
Thanks all! I moved it to the backlog.

**Comment by GregAC** [comment]
I suspect this is best left as a future release (i.e. not PROD), marking as security hotlist for security working group to confirm.

**Comment by johannheyszl** [comment]
@jadephilipoom, I relabeled this since it adds to the SW guidelines for OTBN but it seems no changes to HW are needed.

**Comment by jadephilipoom** [comment]
Thanks @johannheyszl , sounds good. I added the FutureRelease label so it's still tracked on the HW side somehow, though, because it would be nice to fix this on the HW side at a later point. Even though we can work around it in software for now, we may eventually want to use those paths.

**Comment by GregAC** [comment]
> The WDR -> ACC path is also not used at all -- assuming this means just direct bn.wsrw instructions that write to ACC and does not include bn.mulqacc. (The latter is used a lot, and might change my opinion.)
> Specifically: Does the WDR -> ACC path include bn.mulqacc or not? Can you please clarify @GregAC ?

The WDR -> ACC path does not include the `bn.mulqacc` instruction. Though note there is no end to end integrity with `bn.multacc` as with all instructions that involve a computation. The integrity of each operand is checked at the beginning of the operation (this includes the accumulator as well as the two input registers) and new integrity calculated on the result and written to the relevant destination registers (including ACC).

@jadephilipoom @vogelpi please note the above.

**Comment by andreaskurth** [comment]
Closing this issue to remove it from M3; @moidx will create a follow-up issue with the relevant SW-side work.
