### ISSUE TITLE
[otbn/rtl] Consider separate reset scrambling key and nonce for imem and dmem

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#18267]
Currently the scrambling key and nonce for the imem and dmem in OTBN are reset to the same netlist secret (`RndCnstOtbnKey`/`RndCnstOtbnNonce`) it may be preferable to introduce separate netlist secrets for them.

**Comment by GregAC** [comment]
@msfschaffner @moidx @andreaskurth @vogelpi my view here is whilst this is likely straight-forward it isn't important for M2.5 hence this should be postponed til after M2.5 (if we decide it's needed at all).

**Comment by vogelpi** [comment]
This sounds good to me.

**Comment by msfschaffner** [comment]
Agreed with postponing this.

**Comment by cdgori** [comment]
Just making sure I understand - the issue is that the DMEM and IMEM use the same key/nonce pair, not that the key and nonce are equal, right? :)

If we think of DMEM+IMEM as one scrambled object then I can convince myself that this is not nonce reuse.

I would suggest it should be changed post-M2.5 though.

**Comment by msfschaffner** [comment]
Key and nonce are not equal, that is right.

As far as I understand, this issue is really just about the fact that both DMEM and IMEM start out with the same default values after a reset. The scrambling controller inside OTBN actually does request two sets of key/nonce pairs for DMEM/IMEM.

**Comment by GregAC** [comment]
> Key and nonce are not equal, that is right.
> 
> As far as I understand, this issue is really just about the fact that both DMEM and IMEM start out with the same default values after a reset. The scrambling controller inside OTBN actually does request two sets of key/nonce pairs for DMEM/IMEM.

Correct

**Comment by cdgori** [comment]
Oh.  I somehow missed the bit about it only being the reset value.  Given what what said about requesting two sets of key/nonce pairs this is pretty unlikely to be consequential.

If we are reopening the code base later, then yes, having two different reset values is slightly more hygenic but priority is low from my perspective.

**Comment by GregAC** [comment]
@johannheyszl the requests are only done when explicitly requested by Ibex (the secure wipe imem/dmem commands). So if software runs an OTBN operation without requesting a secure wipe first the imem/dmem will be using the netlist constants for key and nonce.

**Comment by johannheyszl** [comment]
thx @GregAC !

@jadephilipoom - can you pls comment on the aspect of: ('how much / critical') do we run crypto without triggering secure wipe?

My guess is this will land on the backlog side since the additional gain in security is more on the defense in depth side.

**Comment by jadephilipoom** [comment]
> @jadephilipoom - can you pls comment on the aspect of: ('how much / critical') do we run crypto without triggering secure wipe?

We don't run any crypto without a secure wipe first. After reset, ROM runs `otbn_load_app` before calling the sigverify RSA routine, which includes: https://github.com/lowRISC/opentitan/blob/c5a9cc9a788f4685c4396e9d573c06014af86d4c/sw/device/silicon_creator/lib/drivers/otbn.c#L231-L233

**Comment by johannheyszl** [comment]
thx @jadephilipoom 
@GregAC it seems we can close this issue :)
