### ISSUE TITLE
[doc] Possible error(s) in SPI Device HWIP Technical Specification - Block Diagram

### ISSUE THREAD

**Issue by jonmccune** [lowRISC/opentitan#1827]
Public page: https://docs.opentitan.org/hw/ip/spi_device/doc/
Public direct link to the problematic diagram: https://docs.opentitan.org/hw/ip/spi_device/doc/block_diagram.svg
Github code link: https://github.com/lowRISC/opentitan/blob/master/hw/ip/spi_device/doc/block_diagram.svg

Empty search for known issues: 
https://github.com/lowRISC/opentitan/issues?q=is%3Aissue+block_diagram.svg

I notice a few issues with this diagram. I don't think this is exhaustive - hopefully an expert can make a pass.

- Should the TX FIFO be directional? Right now it has arrows going both directions.
- Should the Arbiter have a bi-directional arrow to DP_SRAM?
- Are the "Serial to Parallel" and "Parallel to Serial" boxes reversed?

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP4 because I think this is worth keeping in mind on `spi_device`, but we can fix this after M2.5.

**Comment by hcallahan-lowrisc** [comment]
> estimate 2
> remaining 2023-03-22 2

**Comment by a-will** [comment]
Looks like these were for an older block diagram (the s2p and p2s blocks are getting into the noise, and they aren't present anymore, for example). Closing...
