### ISSUE TITLE
[top] Update interface timing constraints

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#18274]
### Description

Need to double check and / or update interface timing constraints for:

- [x] SPI Passthrough #18589
- [x] SPI_HOST #18589
- [x] SPI_DEVICE #18589
- [x] JTAG #18589
- [x] I2C (all instances, existing SDC should cover this already)
- [x] USB (looks ok, need to update comments though to call out the tolerance explicitly) #18581

Use the Full_cycle mode, CPHA = 0, CPOL = 0 SPI configuration for all SPI interfaces.

Internal FIFO and CDC constraints are tracked separately #13011.

**Comment by msfschaffner** [comment]
It looks like there are already generic constraints in place that should work for the I2C and USB:
https://github.com/lowRISC/opentitan/blob/d98b18f186eda61028748a9f9f276cad76dc1058/hw/top_earlgrey/syn/chip_earlgrey_asic.sdc#L46-L80
https://github.com/lowRISC/opentitan/blob/d98b18f186eda61028748a9f9f276cad76dc1058/hw/top_earlgrey/syn/chip_earlgrey_asic.sdc#L125-L130

**Comment by msfschaffner** [comment]
The JTAG constraints may have to be updated:
https://github.com/lowRISC/opentitan/blob/d98b18f186eda61028748a9f9f276cad76dc1058/hw/top_earlgrey/syn/chip_earlgrey_asic.sdc#L152-L163

Specifically, @sha-ron mentioned that this may have to be constrained for 24MHz - is that correct?

**Comment by sha-ron** [comment]
@msfschaffner I am checking internally with TE guys how important it is. Is it hard to support 24MHz instead of 20MHz?

**Comment by msfschaffner** [comment]
Please do. 
The lower the frequency, the better ;), since the constraints can be simplified and relaxed.
(I was going to standardize on 10MHz since that seems pretty common among other devices (Xilinx, Arm), but if there is a minimum requirement, please let us know.)

**Comment by arnonsha** [comment]
I believe the current design meets 24Mhz with no problem and we can also go higher than that.

Higher JTAG clock means faster loading of fw through the JTAG interface.

I'll check on Sun with the BE team what is the current speed that we meet.

**Comment by msfschaffner** [comment]
> I believe the current design meets 24Mhz with no problem and we can also go higher than that.
> 
> Higher JTAG clock means faster loading of fw through the JTAG interface.
> 
> I'll check on Sun with the BE team what is the current speed that we meet.

True, this will enable faster firmware loading.
Note that the SDC does not seem to explicitly constrain TDI, TMS and TDO.
If we want to hit 24MHz or higher I think it we need to constrain them.
We can start to draft something tomorrow so that you can try on Sunday.

**Comment by moidx** [comment]
Targeting for M2.5.1-RC1. This is trending 2023-05-18.

**Comment by johngt** [comment]
@msfschaffner / @moidx for updates

**Comment by msfschaffner** [comment]
This issue can now be closed since the main updates are in.
Further SDC tweaks for M2.5.2 are tracked in #18775.
