### ISSUE TITLE
[clkmgr] Check whether switch to external clock should be disallowed in DEV for production silicon devices

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#18291]
### Description

Assess whether the switch to external clock should be disallowed in DEV for production silicon, based on further security analysis.

For the shuttle (M2.5) this switch in DEV will remain allowed.

CC @johannheyszl @cdgori

**Comment by cdgori** [comment]
I must be missing something terminologically here, because a single given part should either be DEV or PROD, with no ability to switch between the two?

I believe it would be OK for a DEV part to have an external clock, but not PROD.

Do we allow the external clock in RMA states?

**Comment by msfschaffner** [comment]
Apologies, I need to correct that. PROD in this context meant production silicon, not the life cycle state. I edited the text above.

**Comment by cdgori** [comment]
Ah, this makes much more sense now :) - you should change the issue title as well if you can ("PROD devices" -> "production silicon").

After I commented above I looked and we allow external clock in RMA, from what I could tell (and this is what I would expect).  So this is only to allow external clock in DEV, where we were not able to enter RMA for some reason.

For production silicon, I can make the argument either way for DEV lifecycle - probably with a slight preference to not allowing ext clock for consistency.  We're supposed to use the RMA process for this, and there are probably only some rather small surface areas where you have on-die clock marginality such that you cannot do an RMA unlock but would have been able to debug something with ext clock.

It wouldn't be world-breaking to allow it for DEV though.

**Comment by msfschaffner** [comment]
Ack, updated the title.

I believe this was mostly intended for folks wanting to do SCA with DEV parts.
Only the creator can do RMA at their facility.

**Comment by cdgori** [comment]
Yep, I can imagine that it would be very handy for SCA, and has little impact.

**Comment by johannheyszl** [comment]
We appreciate this for SCA testing since we can use key manager, as opposed to in TEST_UNLOCKED.
Thx and let's revisit for M3 whether to turn off again.

**Comment by johannheyszl** [comment]
Removing Hotlist Security label. This will be looked at during triage for production silicon

**Comment by msfschaffner** [comment]
@johannheyszl I presume this is something we do not want to change for PROD now?
Especially if we decide to implement the alternate DEV behavior, ROM_EXT could disable the external clock switch via the CSR before opening up debug via RV_DM.

**Comment by johannheyszl** [comment]
yes, @vogelpi and I discussed and we suggest leaving this in place.

**Comment by msfschaffner** [comment]
Ok closing as not planned.

CC @cdgori @moidx

**Comment by johannheyszl** [comment]
Removing Hotlist label bc. closed as not planned
