### ISSUE TITLE
[spi_passthru] SPI passthru test plan

### ISSUE THREAD

**Issue by cfrantz** [lowRISC/opentitan#18320]
### Description

# SPI Passthrough Testing

## Introduction

This document discusses the tests needed to verify OpenTitan SPI Passthrough.

## EEPROM Parts

Since SPI passthrough puts the OpenTitan chip in the position of a SPI interposer, we need a set of EEPROM parts to serve a representatives of EEPROMs we would expect an OpenTitan user to connect to OpenTitan’s SPI\_HOST.

### Built-in Interposer Opcodes

Tests need to make sure these opcodes return the correct data from the interposer register or memory space and/or set appropriate status/control bits in the interposer.

*   READ\_ID (read Jedec ID)
*   READ\_SFDP
*   READ\_STATUS
*   WRITE\_{ENABLE, DISABLE} (interacts with the status register)
*   EN4B, EX4B (enter/exit 4-byte address mode)

### Read Opcodes

The following opcodes are expected to flow through the interposer to the backing EEPROM.  Their address phase may be subject to the address translation capabilities of the interposer.

*   READ
*   FAST\_READ
*   FAST\_DUAL\_READ (aka DREAD)
*   FAST\_QUAD\_READ (aka QREAD)

Note: 2READ and 4READ opcodes operate in SPI 1-2-2 and 1-4-4 modes and are not supported by the interposer.

All of the prior commands are subject to the address mode of the chip as controlled by EN4B and EX4B.  There are also versions of all of the prior commands that always accept a 4-byte address.  They have the same names as the prior list with “4B” appended to the name: READ becomes READ4B.

### Intercepted Opcodes

The remaining opcodes provide EEPROM erase and write functionality.  Typically, firmware will capture these commands, evaluate the requested operation and regenerate the opcode to the backing eeprom.

*   PP (PAGE\_PROGRAM)
*   SE (SECTOR\_ERASE)
*   BE32K (Block Erase 32K)
*   BE64K (Block Erase 64K)
*   CE (CHIP\_ERASE)

As with the read opcodes, the above opcodes (except chip\_erase) are subject to the address mode and have exclusive 4-byte versions with “4B” appended to the name.

### Opcode Filtering

There are several opcodes (often vendor extensions) which control the state of the backend EEPROM.  For example, the WREAR (write extended address register) provides a mechanism for an upstream SPI host to address the full 4-byte address space via 3-byte addressing.  Generally, we don’t support this type of extended addressing through the interposer and should an upstream SPI\_Host send this opcode, we’d want to prevent it from affecting the backend EEPROM.

### Test Matrix

The following SPI opcodes should have tests.

| Opcode              | FW Intercept   | 3b/4b mode   | Address Translation   | Notes                                                           | PR #   |
|---------------------|----------------|--------------|-----------------------|-----------------------------------------------------------------|--------------|
| READ_ID             | No             | N/A          | N/A                   | SPI_D Register.                                                 | cfrantz #17426 |
| READ_SFDP           | No             | N/A          | N/A                   | SPI_D RAM.                                                      | cfrantz #17452 |
| READ_STATUS1        | No             | N/A          | N/A                   | SPI_D Register.  WIP bit should be set by intercepted commands. | cfrantz #17429 |
| WRITE_STATUS1       | Yes            | N/A          | N/A                   | SPI_D Register.                                                 | cfrantz #17469 |
| READ_STATUS2        | No             | N/A          | N/A                   | SPI_D Register (status bits 15:8).                              | cfrantz #17429 |
| WRITE_STATUS2       | Yes            | N/A          | N/A                   | SPI_D Register (status bits 15:8).                              | cfrantz #17469 |
| READ_STATUS3        | No             | N/A          | N/A                   | SPI_D Register (status bits 23:16).                             | cfrantz #17429 |
| WRITE_STATUS3       | Yes            | N/A          | N/A                   | SPI_D Register (status bits 23:16).                             | cfrantz #17469 |
| WRITE_ENABLE        | No             | N/A          | N/A                   | Affects WEN bit in status.                                      | cfrantz #17429 |
| WRITE_DISABLE       | No             | N/A          | N/A                   | Affects WEN bit in status.                                      | cfrantz #17429 |
| EN4B                | No             | N/A          | N/A                   | Affects SPI_D notion of 3b/4b mode.                             | cfrantz #17429 |
| EX4B                | No             | N/A          | N/A                   | Affects SPI_D notion of 3b/4b mode.                             | cfrantz #17429 |
| READ (1-1-1)        | No             | Yes          | Yes                   | No dummy cycles.                                                | a-will #17497  |
| DREAD (1-1-2)       | No             | Yes          | Yes                   |                                                                 | cfrantz #18292 |
| QREAD (1-1-4)       | No             | Yes          | Yes                   |                                                                 | cfrantz #18292 |
| FAST_READ (1-1-1)   | No             | Yes          | Yes                   | Dummy cycles. Traditionally, 8.                                 | cfrantz #18292 |
| READ4B (1-1-1)      | No             | N/A          | Yes                   | Not supported on CW310                         |              |
| DREAD4B (1-1-2)     | No             | N/A          | Yes                   | Not supported on CW310                        |              |
| QREAD4B (1-1-4)     | No             | N/A          | Yes                   | Not supported on CW310                        |   |
| FAST_READ4B (1-1-1) | No             | N/A          | Yes                   |  Not supported on CW310                       |              |
| PP                  | Yes            | Yes          | In software           |                                                                 | cfrantz #17482 |
| SE                  | Yes            | Yes          | In software           |                                                                 | cfrantz #17469 |
| BE32K               | Yes            | Yes          | In software           |                                                                 | cfrantz #18377|
| BE64K               | Yes            | Yes          | In software           |                                                                 | cfrantz #18377|
| PP4B                | Yes            | N/A          | In software           | Not tested.  Perform as a manual test.    |              |
| SE4B                | Yes            | N/A          | In software           |                                                                 | cfrantz #18377|
| BE32K4B             | Yes            | N/A          | In software           |                                                                 | cfrantz #18377|
| BE64K4B             | Yes            | N/A          | In software           |                                                                 | cfrantz #18377|
| CE                  | Yes            | N/A          | N/A                   |                                                                 | cfrantz #17469 |

Notes:
- #17572 added READ tests with address translation.
- #17606 added READ tests targeting the mailbox.
- #17615 enhances the SPI flash emulator to handle BE32K, BE64K, PP4B, SE4B, BE32K4B and BE64K4B opcodes.
  - The passthru filter write slots are full after #17615.
  - The passthru filter read slots have 2 entries available.
- Not supported on CW310: The IS25WP016 EEPROM on the CW310 board does not support any 4B operations and these opcodes flow through the interposer to the EEPROM.  The can be tested by replacing the IS25WP016 part with a larger eeprom.

### Manual testing
The `spi_passthru_test` can be placed into "spi flash emulator" mode by entering the string `"SpiFlashEmulator"` (with the quotes) at the OpenTitanTool console.  The test will respond with:
```
I00001 spi_flash_emulator.c:120] Configuring spi_flash_emulator.
I00002 spi_flash_emulator.c:124] Setting the EEPROM's QE bit via mechanism 2
I00003 spi_flash_emulator.c:127] Starting spi_flash_emulator.
```

At this point, one can issue any spi transaction via the `opentitantool spi` command hierarchy:
```
opentitantool --interace=<cw310|hyper310> spi sfdp
... SFDP table ...
```

**Comment by johngt** [comment]
@engdoreis / @luismarques - FYI, to avoid duplication while performing https://github.com/lowRISC/ot-discrete-eg/issues/10

**Comment by johngt** [comment]
@moidx - based on yesterday's notes it sounded like this had been completed?

**Comment by moidx** [comment]
Hi @cfrantz, please feel free to close if you are satisfied with the manual checks. I believe all other tests have been merged.

**Comment by msfschaffner** [comment]
@a-will @cfrantz can you double check whether this can be closed?

**Comment by cfrantz** [comment]
I've re-run `//sw/device/test:spi_passthru_test` locally via the `cw310` and `hyper310` interfaces (the latter required to check dual and quad SPI modes).  Both passed.

**Comment by moidx** [comment]
Thanks @cfrantz!
