### ISSUE TITLE
[aon_timer, dv] Pause in sleep feature for watchdog is untested

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#18340]
The aon_timer watchdog has a feature that allows the watchdog to be paused when in sleep. This isn't currently being tested in the testbench.

> estimate 4

**Comment by GregAC** [comment]
P1 so as to discuss if we want to test this for M2.5.1. My view is it's a simple feature that looks correct by inspection of the RTL and isn't critical. Testing would be straight-forward but could end up taking a day or more of effort to implement and deal with any regression issues.

I could have a quick go at doing it and if there's lots of regression failures to wade through that don't appear to be RTL errors leave it til after M2.5.1

@msfschaffner @jdonjdon thoughts?

**Comment by jdonjdon** [comment]
That looks reasonable to me.

Rdgs,

Jaedon

**Comment by msfschaffner** [comment]
Sounds reasonable to me, but I wouldn't invest too much time.
IMO it's fine to punt this to M2.5.1, given that we already have several top-level tests.

**Comment by GregAC** [comment]
Ok I think we'll move this to M2.5.2, no further action will be taken here for M2.5.1

**Comment by moidx** [comment]
DV improvement, moving to M5

**Comment by johngt** [comment]
@GregAC  / @andreaskurth / @moidx 
I think one of the areas integrations team are most concerned about is on sleep and resume from sleep.
@GregAC do we have coverage for this already or should we high grade this as a P1 to give us confidence that this is covered?

**Comment by GregAC** [comment]
This remains a coverage gap and should be addressed for M5, @antmarzam is this something you could take on?

**Comment by GregAC** [comment]
Moved to P1

**Comment by antmarzam** [comment]
Sure - I'll take this on!

**Comment by antmarzam** [comment]
Closing, this is now taken care of in PR #23743
