### ISSUE TITLE
[edn] FSM Coverage improvement

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18370]
### Description

FSM at 71%, but exclude non-idle → error states: Afterwards there will be 91.47% coverage. According to V2S review.
MSF: To verify exclusion file by hand and open an issue to track any future improvements.
→ 0.5d

>estimate 2

**Comment by msfschaffner** [comment]
Does the exclusion file to review already exist?

**Comment by msfschaffner** [comment]
@andreaskurth is there an exclusion file that we can review in order to close out this issue?

**Comment by andreaskurth** [comment]
No exclusion file -- the transitions here should be covered. First PR to fix this is up (#18960), more PRs will follow.
