### ISSUE TITLE
[lc_ctrl] Volatile raw unlock impossible to read status transition_success_o when set to 1

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#18378]
### Description

Hi michael,

In the spec, it mentioned in step 10:
https://opentitan.org/book/hw/ip/lc_ctrl/doc/programmers_guide.html#volatile-raw---test_unlocked0-transition
"
Poll the [STATUS](https://opentitan.org/book/hw/ip/lc_ctrl/data/lc_ctrl.hjson#status) register and wait until either [STATUS.TRANSITION_SUCCESSFUL](https://opentitan.org/book/hw/ip/lc_ctrl/data/lc_ctrl.hjson#status) or any of the error bits is asserted. The [TRANSITION_REGWEN](https://opentitan.org/book/hw/ip/lc_ctrl/data/lc_ctrl.hjson#transition_regwen) register will be set to 0 while a transition is in progress in order to prevent any accidental modifications of the transition interface registers during this phase.
"

But in the waves, it shows it is almost impossible to read out success_o because it is only asserted on clock cycle high, and it is the same cycle when we set `transition start` command.

Maybe we can change the doc wording here, to wait for ready status bit instead?

CC: @moidx 

![image](https://user-images.githubusercontent.com/11466553/236564324-2bc4be27-a19d-4d27-b757-c40110b0fa99.png)

**Comment by msfschaffner** [comment]
Hm... that register should stay high. Let me fix that.
