### ISSUE TITLE
RFC: OpenTitan Hardware Revision and Device ID Registers

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#18393]
### Description

See [RFC doc](https://docs.google.com/document/d/1IuxBKj0jxMpnXUadO9lHBjj_HsdWnKlgnddyx_b7BEQ/edit).
This incurs an update of the `lc_ctrl` CSRs.

CC @moidx

**Comment by johngt** [comment]
Tagging @GregAC and @mundaym for reference

**Comment by johngt** [comment]
> @msfschaffner I think the RFC doc was incorrectly linked as GH issue? I'm getting a 404 error.
Have correct the entry - thanks @gdessouky for raising.

**Comment by msfschaffner** [comment]
Thanks for fixing that!

**Comment by msfschaffner** [comment]
This RFC has been approved by the TC today.

The associated RTL changes are implemented in #18448.

**Comment by msfschaffner** [comment]
The alignment has been merged into RTL - closing.
