### ISSUE TITLE
[usb_dev, rv_dm, i2c] Updated waivers

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18408]
### Description

Given the stage that several blocks were for M2 we will need to prepare updated waivers for M2.5

- [x] USB_Dev updated waiver
- [x] RV_DM updated waiver
- [x] I2C updated waiver

For reference [waivers general](https://docs.google.com/document/d/1vaXaXWiF_dooaeFHjn4ioKINSlWCJsLji7YTaPXL2RY/edit?resourcekey=0-0_ChjR65V7eXKNWQ8QL9dQ#heading=h.q9qepcm0sjy)
[I2C waiver](https://docs.google.com/document/d/1wOBw9_-teVBmsOsHwq8YfUbXvOVnoM6kpesDkKawDUk/edit), [RV_DM waiver](https://docs.google.com/document/d/1GYNEJ_0Q4ixLQTDcrnH21sY4jVnTcZy7BZjQCD6yuuM/edit?resourcekey=0-YindCd4HM6TbkTxxuwjX0Q), [USB V1/2 Waiver](https://docs.google.com/document/d/1Nt6lbwNEa1q-sfrudbHw6ep6eYNOyXBZcGFOPlyd1k4/edit),

**Comment by marnovandermaas** [comment]
I think we can mark the I2C task as done because we will get I2C V2 sign-off done as tracked in this issue: https://github.com/lowRISC/opentitan/issues/18596 Thus we no longer need a waiver for V2.

**Comment by msfschaffner** [comment]
> I think we can mark the I2C task as done because we will get I2C V2 sign-off done as tracked in this issue: #18596 Thus we no longer need a waiver for V2.

Good point!

@moidx @GregAC let's discuss in the TL meeting tomorrow whether we actually need the V signoff waivers for M2.5.1 already.

**Comment by msfschaffner** [comment]
Discussed in TL sync today - I2C will be closed without a waiver, hence marking that as done.

**Comment by msfschaffner** [comment]
[RV_DM waiver doc](https://docs.google.com/document/d/1ElYii8niI-puMZCTYgaO5LqNj3pT4E5MPeSOPsXu7sc/edit?resourcekey=0-0m71x8Ao0R_FnsTpc19Vzw#heading=h.q9qepcm0sjy)

**Comment by msfschaffner** [comment]
The waivers have been updated for M2.5.1, hence this issue can be closed.
