### ISSUE TITLE
[ci] Incorrect Ninja version causing CI failures

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#1840]
We are seeing a CI failure relating to the version of Ninja.

As example can be see on this PR: https://github.com/lowRISC/opentitan/pull/1839

This azure log: https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=9867&view=logs&j=5df5adf8-3577-5927-f0b2-31afed2697ee&t=dcb8db2a-d944-5acc-e50e-bea93f2a14e9&l=58

Which reports

```
ERROR: Could not detect Ninja v1.5 or newer
```

**Comment by imphil** [comment]
Having a look now.

**Comment by asb** [comment]
Looks like someone the issue is reported upstream already https://github.com/mesonbuild/meson/issues/6867. This PR bumped the minimum ninja version to 1.7, but the logic to error when an old version of meson is found is hard-coded to complain that "v1.5 or newer" is required.
