### ISSUE TITLE
[otbn] Tests to V2(S) levels 

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18417]
### Description

V2 tests that require fixing to 90% pass rate (passing / total)
- [ ] otbn_reset (8/10)
- [ ] otbn_escalate (45/60)
V2S tests that require fixing to 90% pass rate (passing / total)
- [ ] otbn_imem_err (7/10)
- [ ] otbn_alu_bignum_mod_err (4/5)
- [ ] otbn_illegal_mem_acc (4/5)
- [ ] otbn_sec_cm (4/5)
- [ ] otbn_ctrl_redun (8/12)
- [ ] otbn_stack_addr_integ_chk (4/5)
Coverage:
Overall numbers are good but some gaps in functional coverage around errors, (ext_csr_err_bits_cg and bad_internal_stat_cg in particular) there is an issue to track these (https://github.com/lowRISC/opentitan/issues/17662) so effort estimate isn’t included here

**Comment by johngt** [comment]
Discussed on 2023-05-08 Triage meeting. Suggested priority downshift to sprint 2.

**Comment by johngt** [comment]
Post CDC enablement there are more failures with this - https://reports.opentitan.org/hw/ip/otbn/dv/uvm/latest/report.html
@GregAC to consider if any need to be high-graded.

**Comment by GregAC** [comment]
Beyond https://github.com/lowRISC/opentitan/issues/19044 none of the other failures are concerns for M2.5.2

**Comment by rswarbrick** [comment]
The current rates less than 90% (from 8th June 2024) are:
**V2:**
- `otbn_stress_all`: 80% (4/5)
- `otbn_escalate`: 80% (48/60)
- `otbn_zero_state_err_urnd`: 80% (4/5)
**V2S:**
- `otbn_sec_cm`: 0% (0 / 5)
- `otbn_stack_addr_integ_chk`: 60% (3/5)

The `otbn_sec_cm` issue is separately tracked as #23578.

I am removing this item from the M4 milestone. That milestone already contains an issue for V2/V2S signoff, which depends on these numbers so I'm not convinced it helps to track it separately through this issue too.

**Comment by vogelpi** [comment]
I am closing this issue as OTBN has been signed of at V2S in the meantime an all tests mentioned in this issue have pass rate of 98% or higher.
