### ISSUE TITLE
[ci] Failures in private CI on HMAC sanity and Chip Sanity

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#1841]
Private CI is seeing failures for both the HMAC and chip sanity tests. I can't reproduce these locally so there's something specific to the private CI environment that is causing them.

One example can be seen in this PR: https://github.com/lowRISC/opentitan/pull/1836

There's an actual error for HMAC, for chip sanity it just reports no 'TEST PASSED' indication was seen.

**Comment by GregAC** [comment]
I'm working on trying to get these reproduced locally, if I can't we'll need to pull out the logs from the private CI for the chip sanity at least.

**Comment by GregAC** [comment]
HMAC seems to be passing now, just the chip sanity failure which requires the log file to be extracted

**Comment by imphil** [comment]
Looks like a fallout from https://github.com/lowRISC/opentitan/issues/1840 as well (chip sanity needs the SW build system).

**Comment by GregAC** [comment]
Indeed the meson version fix fixed this also, thanks!
