### ISSUE TITLE
[aes] AES V2.5 tests + V2(S) corrections

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18427]
### Description

V2.5
- [x] Reseed rate test should be fixed, see #17357 [aes, dv] Fix reseed rate test  [2d recorded there]

V2 
- [x] Sampling for aes_aux_regwen_cg and aes_alert_cg cover groups seems to be broken, but it’s 100% certain that the associated features are being tested correctly. now tracked by #19039

**Comment by vogelpi** [comment]
I've investigated the coverage issues and it cannot be solved easily unfortunately as the scoreboard isn't active during the automated CSR tests and some other configuration tests we do. However, this isn't critical for M2.5. I've created #19039 to describe what needs to be done and to track the work.
