### ISSUE TITLE
[rstmgr] Verification sign-off for M2.5

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18438]
### Description

Couldn't find a verification task for sign-off - created.
Efforts recorded in issues
- [x] Close out TODOs 0.5d .. 1d [#18435](https://github.com/lowRISC/opentitan/issues/18435)
- [x] Complete V2.5 checklist items not captured elsewhere 0.25d [#18436](https://github.com/lowRISC/opentitan/issues/18436)

CC: @matutem  @msfschaffner

**Comment by msfschaffner** [comment]
This has apparently already been closed in #17915.

**Comment by msfschaffner** [comment]
@matutem can you quickly check whether the associated checklist items and TODOs have been resolved (#18435 #18436)?

**Comment by matutem** [comment]
All is done. Closing.
