### ISSUE TITLE
[usbdev] USB TODOs

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18443]
### Description

- [ ] When usbdev is stubbed, register interface is intended to survive, so presumably the alert(s) should too. The only alert is that relating to T-L traffic/register access
- [x] [PR #17673](https://github.com/lowRISC/opentitan/pull/17673) - merged in
- [ ] Rest of issues tracked in https://github.com/lowRISC/opentitan/issues/17892

**Comment by alees24** [comment]
https://github.com/lowRISC/opentitan/pull/17673
