### ISSUE TITLE
[top_earlgrey] Debug JTAG issues on FPGA with ILA

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#18462]
Given the problems reported in #17729, this issue tracks the effort of debugging JTAG on the CW310 with an integrated logic analyzer (ILA).

A (draft) PR that contains contributions that can be committed is here: #18401. That PR is not intended to get merged (at least not in the current state) but can be useful to reproduce the debugging setup.

**Comment by msfschaffner** [comment]
I am closing this since the issue has been root caused.

See also #18554 and #17729 for context.

CC @moidx
