### ISSUE TITLE
[i2c] Device-mode testplan

### ISSUE THREAD

**Issue by cfrantz** [lowRISC/opentitan#18541]
## Introduction
This document describes the tests performed against the I2C block in device mode.  These tests are performed on the FPGA connected to a Hyperdebug board.

## Tests
- Initialize device (aka target) mode:
  - Initialize I2C0, pinmux, pwrmgr and plic.
  - Configure pinmux to connect SDA/SCL to IOA7/IOA8 (location of hyperdebug's I2C master).
  - Set the I2C speed to the standard speed (100KHz)
  - Enable device mode
- Configure target address filter:
  - Set address filter to respond to address 0x33 and addresses 0x70..0x73.
- Test a short read transaction to all configured addresses.
- Test a write transaction to address 0x33.
- Test a long write transaction to address 0x33.
  - Firmware intentionally inserts a long (10ms) delay every 64 bytes.  This causes the I2C device to stretch the clock while the upstream master is writing data to OpenTitan.
- Test a wake up from normal sleep
  - Configure pinmux wake up detector 0 for any edge on IOA7 (SDA).
  - Configure power domains to place the main power domain in low power and usb clock in active power.
  - Go to sleep.
  - Send a read transaction to address 0x22 as a wakeup request.  Expect a failure for this request, but OT will wake up and resume execution from the sleep point.
  - Wait to observe the wake up.
  - Send a read transaction to address 0x33.
- Test a wake up from deep sleep
  - Configure pinmux wake up detector 0 for any edge on IOA7 (SDA).
  - Configure power domains to all off.
  - Go to sleep.
  - Send a read transaction to address 0x22 as a wakeup request.  Expect a failure for this request, but OT will wake up by booting from ROM.
  - Wait to observe the wakeup.
  - Reconfigure the address filter.
  - Send a read transaction to address 0x33.

Tests are implemented in the following PRs:
- #18453
- #18484

Issues observed:
- #18510

**Comment by cfrantz** [comment]
These tests require a Hyperdebug board to run.  They're currently tagged `manual` in the BUILD file.  They should be enabled unconditionally as part of #17782.

**Comment by moidx** [comment]
Closed by https://github.com/lowRISC/opentitan/pull/18484
