### ISSUE TITLE
[csrng] Verify if FIPS bit deassertion at input proceeds to output

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#18568]
### Description

PR #18269 updated the CSRNG testplan and coverpoints. In particular, the TODO
```sv
//TODO - FIPS bit going low from entropy source is currently untested.
```
Got replaced by this covergroup
```sv
  covergroup csrng_genbits_cg with function sample(bit genbits_fips, bit genbits_valid);
    option.per_instance  = 1;
    option.name          = "csrng_genbits_cg";
    // Coverpoint for indicating FIPS/CC compliant bits on genbits register
    genbits_fips_cp : coverpoint genbits_fips iff (genbits_valid){
      bins fips_compliant = {1'b1};
      bins fips_non_compliant = {1'b0};
    }
  endgroup
```
Sampled when software reads the genbits output register. This will tell us whether software reads both entropy bits generated from FIPS compliant and non-FIPS compliant entropy seeds.

However, it's currently not clear if there is indeed a test that verifies that if the FIPS bit at the input of CSRNG goes from high to low, the entropy produced from that seed will also have the FIPS bit set low at the output. We should investigate if this is verified and if not whether we can extend DV accordingly.

**Comment by msfschaffner** [comment]
Discussed in the triage meeting - let's target this for V3.

CC @johannheyszl
