### ISSUE TITLE
[Ci] Default agent isn't accepting jobs

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1857]
We have a huge backlog at https://dev.azure.com/lowrisc/opentitan/_settings/agentqueues?queueId=1&view=jobs

@asb can you have a look?

**Comment by asb** [comment]
The agent has been active and "listening for jobs" since last for the last ~11 hours, with no error output. I'll try to restart it...

**Comment by asb** [comment]
Restarting the agent seems to have done the trick. Unfortunately given there was no error message it's not trivial to increase resiliency on our side (as this failure mode was indistinguishable from there just being no jobs to distribute). I don't suppose Azure DevOps lets us set a warning trigger if the job queue gets above a certain length? That would be pretty useful for flagging issues like this early.

**Comment by asb** [comment]
Marking this closed, as the agent is happily accepting new jobs now.
