### ISSUE TITLE
[tlul] Fix handling of mask for Get and use of PutFullData vs PutPartialData in tlul_adapater_host

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#1860]
Currently tlul_adapter_host simply passes the received be_i straight out to a_mask on the TL interface.

The interface used by the debug module doesn't set any be_i when it's reading when it intends to read everything which has caused https://github.com/lowRISC/opentitan/issues/1802

It's probably reasonable to say on a simple reg/grant/rvalid interface be is ignored for reads and only used for writes so tlul_adapater_host should generate a full width a_mask for reads.

There's also a subtlety around PutFullData vs PutPartialData. tlul_adapter_host always uses PutFullData as the opcode for writes. However when the be_i isn't complete with respect to the size PutPartialData must be used as per the tile-link specification:

```
On channels A and B, which carry a mask field, the mask must be LOW for all inactive byte lanes.
Furthermore, for all messages other than PutPartialData , the bits of mask for all active byte
lanes must be HIGH.
```

**Comment by imphil** [comment]
I'd appreciate if this could be fixed together with https://github.com/lowRISC/opentitan/issues/53. We ran into similar issues now at least twice; the adapter to the core gets quite a bit of testing, while the one for debug doesn't get much testing at all. Using the same code at least reduces the risks of problems here.

**Comment by GregAC** [comment]
Fixing this and #53 will need to await the outcome of discussions in https://github.com/lowRISC/opentitan/issues/1867 and https://github.com/lowRISC/ibex/issues/757
