### ISSUE TITLE
[opentitantool] Check JSON syntax

### ISSUE THREAD

**Issue by pamaury** [lowRISC/opentitan#18618]
### Description

We embed JSON files for configuration, but one had a [syntax error](https://github.com/lowRISC/opentitan/pull/18531) for a long time. Apparently the josn parser still reads it fine but maybe we should check the syntax of those file in the CI?

**Comment by msfschaffner** [comment]
CC @cfrantz @timothytrippel

**Comment by timothytrippel** [comment]
can we close this @pamaury ?

**Comment by pamaury** [comment]
I think so, it's not a priority at the moment.
