### ISSUE TITLE
Flaky test gpio_smoketest_fpga_cw310_test_rom

### ISSUE THREAD

**Issue by luismarques** [lowRISC/opentitan#18623]
### Description

The test `//sw/device/tests:gpio_smoketest_fpga_cw310_test_rom` is very frequently failing, causing CI issues. It should probably be disabled until its reliability is improved (I'll post a PR for that, referencing this issue).

**Comment by johngt** [comment]
I believe that this is now resolved with the fixes to SPI tests @engdoreis ?
