### ISSUE TITLE
[rom_e2e] remove `opentitan_gdb_fpga_cw310_test` rule and `gdb_test_coordinator.py` script

### ISSUE THREAD

**Issue by pamaury** [lowRISC/opentitan#18628]
### Description

This script is a bit of hack and requires a lot of work to properly synchronize everything. This could be done more efficiently and correctly using opentitanlib. In particular we could use all the infrastructure to do the console, bistream loading and openocd starting which is already there.

For context, see e.g. [this discussion](https://github.com/lowRISC/opentitan/pull/18554#issuecomment-1545973878).

**Comment by timothytrippel** [comment]
To expand with a task list:

- [ ] replace the GDB scripts with opentitanlib-based test harnesses for the following ROM E2E tests that use the `opentitan_gdb_fpga_cw310_test` rule:
    - [ ] `debug_disallowed_in_prod_fpga_cw310_test_otp_*`
    - [ ] `asm_interrupt_handler_fpga_cw310_test_otp_*`
    - [ ] `shutdown_exception_asm_otp_*`
    - [ ] `rom_e2e_asm_watchdog_bark_fpga_cw310_test_otp_*`
    - [ ] `rom_e2e_asm_watchdog_bite_fpga_cw310_test_otp_*`
    - [ ] `rom_e2e_debug_test_otp_*`
- [ ] remove the custom `opentitan_gdb_fpga_cw310_test` Bazel rule from the repo
- [ ] remove the `rules/scripts/gdb_test_coordinator.py` script from the repo

**Comment by pamaury** [comment]
The only tests that are not straightforward to convert are those that use symbolic names for breakpoints (e.g. `break kRomStartBootMaybeHalt`): the two watchdog ones and `rom_e2e_debug_test_otp_`. Any suggestion on how to handle these? Probably we don't want to reimplement a debug symbol parser in opentitanlib, but I guess we could produce a symbol map and give it to opentitanlib (those are easy to parse).

**Comment by timothytrippel** [comment]
Is there an ELF parsing crate you could use to augment the flow?

**Comment by dmcardle** [comment]
Agreed that the script is a bit of a hack — it evolved while I developed e2e tests more than it was designed, and we've found a few bugs related to output buffering.

I fully support reimplementing with opentitanlib, but I'd like to encourage you to think about refactoring techniques. I'd like some assurance that the new opentitanlib-based harness agrees with the old gdb_test_coordinator (modulo bugs in gdb_test_coordinator). Maybe the new harness should run the equivalent test in gdb_test_coordinator as well, and assert that it gets the same result.

**Comment by timothytrippel** [comment]
To be clear here, I like to think of the `opentitan_gdb_fpga_cw310_test` infrastructure as a good stepping stone to the infrastructure we built up in `opentitanlib`, it showed us the way if you will, so big thanks to @dmcardle for designing and implementing this originally!

Over the last couple months, as we uncovered issues and pain-points we pivoted towards simplicity, i.e., removing GDB and Python process coordination in favor of driving OpenOCD directly with opentitanlib.

The test refactoring described above is to further enhance the robustness of the above tests, and allow us to simplify our infrastructure. I agree that the new opentitanlib-test-harness these tests are migrated too should contain the same assertions and checks as the original tests, and we can confirm this during code review. However, we should not have the new test harness run the old gdb_test_coordinator test too. The purpose here is simplicity, no need to test our tests. I apologize if I misunderstood what you meant here. Just want to be very clear what the mission is here: simplicity and robustness.

**Comment by dmcardle** [comment]
Thanks, @timothytrippel!

To clarify, I was only suggesting that we *temporarily* run both harnesses and compare the results. The goal being to demonstrate the property that the old and new implementations produce the same outputs when given the same inputs.

Anyway, this is just a suggestion and I trust you to do what you think is best. My goal was correctness, not to prolong the lifetime of the gdb test coordinator :)

**Comment by timothytrippel** [comment]
@nbdd0121 @pamaury is the only left to do here the deletion of the old test / test infra? (i.e., the last two items https://github.com/lowRISC/opentitan/issues/18628#issuecomment-1550019632)

**Comment by timothytrippel** [comment]
I think https://github.com/lowRISC/opentitan/pull/19990 should take care of removing the old tests / infra.

**Comment by pamaury** [comment]
I think #19990 removes everything
