### ISSUE TITLE
[DV] Format code according to our Python coding style

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1863]
In https://github.com/lowRISC/opentitan/pull/1815 we enabled flake8 to check for code style violations in Python code. The DV Python code doesn't pass these tests currently, fix them (e.g. with `util/lintpy.py`) and switch the CI check to be enforcing. (Discussion at https://github.com/lowRISC/opentitan/pull/1815#discussion_r397754504).

**Comment by milesdai** [comment]
Yes, CI currently runs the flake8 check on the entire repo (minus vendored code and some of the linters themselves), and the DV code is passing. @GregAC Is it okay to make this check blocking now (i.e. remove the `continueOnError`?

**Comment by GregAC** [comment]
> @GregAC Is it okay to make this check blocking now (i.e. remove the continueOnError?

Sure assuming we are flake8 lint clean
