### ISSUE TITLE
[opentitanlib,testing] add integrity check mechanism on SRAM programs

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#18635]
Several manufacturing tests load programs in SRAM over JTAG, using opentitanlib infrastructure that drives OpenOCD. Often, theses programs perform critical OTP provisioning operations which are irreversible. When dealing with OpenOCD/JTAG/rv_dm flakiness issues, an integrity check mechanism was proposed to provide confidence that the program injected over JTAG is written to SRAM correctly.

There were two proposed mechanisms:
1. having the SRAM program loading utility (in opentitanlib) read back what was written, after it was written, or
2. having the SRAM program perform the integrity check itself from within.

The runtime impact of option 1 was analyzed in #18621, and deemed to be a 2x impact in runtime. Additionally, option 1 requires roundtrip communication between the host and device, which will not be acceptable during manufacturing. Therefore, option 2 seems most desirable.

Some thoughts on how to implement option 2 (though this will most likely require more thorough exploration):
- when opentitanlib configures the device stack, it could place a checksum/hash over the SRAM contents on the stack
- a testutil function could be written, and embedded into the SRAM program, to read the checksum/hash on the stack, and compare it to the checksum/hash the testutil will compute of the program itself
- this integrity check mechanism may be optionally used, i.e. a test can decide whether or not to use it at all (sacrificing speed for correctness, or vice versa)

**Comment by timothytrippel** [comment]
CC: @pamaury

**Comment by dmcardle** [comment]
Presumably, after the device computes the checksum in option 2, it will have a branch like this: `if checksum != expected { abort(); }`. It might be worth looking at the Hamming distances between RISC-V branch instructions to see whether the condition might be accidentally negated. Maybe we should ensure that multiple checksum comparisons are codegenned.

**Comment by pamaury** [comment]
Regarding option 2, I think we could take this occasion to rework a little bit SRAM programs which are kind of a hack currently:
- create a `sram_start.S`/`sram_start.c` that takes care of calling the test's main, and also can be easily extended in the future if we want to setup things differently without modifying every test
- this start routine could also compute a checksum of the porgram code and check that it is correct
- the checksum could either be computed offline by the build system (like signing), or by opentitantool

**Comment by pamaury** [comment]
Regarding the checksumming hardening, my understanding is that the issue here is not "security" related since there is no signing going on. There could be a problem if a bit-flip causes the branch to negated and this could be partly solved by:
- doing the branch test twice (it is unlikely that a bit-flip occurs at those exact two locations)
- have the SRAM loader on the host read-back just the tiny piece of code that does the checksum verification (i.e. a bit like a chain of trust)

**Comment by timothytrippel** [comment]
Regarding the checksumming hardening, the threat model is much much different during manufacturing than during mission mode. Our initial implementation does not need a hardened check. If we are checking a hash a random single bit flip is highly unlikely to match the hash (by design).

**Comment by timothytrippel** [comment]
> Regarding option 2, I think we could take this occasion to rework a little bit SRAM programs which are kind of a hack currently:
> 
> * create a `sram_start.S`/`sram_start.c` that takes care of calling the test's main, and also can be easily extended in the future if we want to setup things differently without modifying every test

- the sram_start.c could setup a stripped down version of the OTTF (i.e., just setup the OTTF console) so we don't have to do that in each SRAM program
- regarding the sram_start.S, what setup were you thinking including in this?

> * this start routine could also compute a checksum of the porgram code and check that it is correct
- the sram_start.c could include this, instead of doing it in a testutil, but we need to make sure we can disable it (can be a compile time config setting, like the OTTF config settings) in case runtime is too slow to be acceptable during manufacturing time
> * the checksum could either be computed offline by the build system (like signing), or by opentitantool
- would be nice if it was done under the hood by opentitanlib when we load the program
> I am happy to create a prototype if we can agree on how we go about this.

Thanks @pamaury!
