### ISSUE TITLE
[sram_ctrl] FSM coverage

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18646]
### Description

FSM coverage for sram_ctrl is at 70%. E.g. below 90% threshold
https://reports.opentitan.org/hw/ip/sram_ctrl_ret/dv/latest/report.html

**Comment by msfschaffner** [comment]
@msfschaffner

**Comment by msfschaffner** [comment]
I am not 100% certain, but I believe the uncovered state `StFlush` and associated uncovered transition edges are actually unreachable in this design. I will try to confirm this with UNR.

**Comment by msfschaffner** [comment]
Ok UNR flags this as unreachable.
I am going to add an exclusion file generated by UNR for `sram_ctrl` to take care of this.
