### ISSUE TITLE
[test-triage] ROM_CTRL FSM coverage

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18645]
### Hierarchy of regression failure

Block level

### Failure Description

FSM coverage appears to be below 90%
https://reports.opentitan.org/hw/ip/rom_ctrl/dv/latest/cov_report/dashboard.html
The current FSM coverage is 86.67%

This has been the case since https://reports.opentitan.org/hw/ip/rom_ctrl/dv/2023.01.09_23.51.30/report.html where it was 80%

### Steps to Reproduce

NA

**Comment by msfschaffner** [comment]
CC @GregAC 

To check for the V2.5 signoff.

**Comment by msfschaffner** [comment]
Addressed by https://github.com/lowRISC/opentitan/pull/19053
