### ISSUE TITLE
[i2c,dv] Create FSM waiver file

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/opentitan#18651]
### Description

Currently the I2C FSM coverage is reported as 73%. However, this coverage includes state that we don't care about.

For example there is the state machine `i2c_protocol_cov` which is only used for DV purposes. Removing this from the coverage increases the coverage number to 81%.

The remaining coverage holes are state transitions where a host-mode state receives a start or a stop. This is currently not supported by our I2C IP because it only supports a single host on the I2C bus: https://github.com/lowRISC/opentitan/blob/6627e110bee0d2d2a1b1f58a09713a08ca96ee99/hw/ip/i2c/doc/theory_of_operation.md?plain=1#L224

We should thus exclude these transitions:

Transition | Line number | Status
-- | -- | -- 
Active->AcquireStart | 1303 | Not Covered |  
Active->Idle | 1301 | Not Covered |  
ClockLow->AcquireStart | 1303 | Not Covered |  
ClockLowAck->AcquireStart | 1303 | Not Covered |  
ClockPulse->AcquireStart | 1303 | Not Covered |  
ClockPulseAck->AcquireStart | 1303 | Not Covered |  
ClockStart->AcquireStart | 1303 | Not Covered |  
ClockStart->Idle | 1301 | Not Covered |  
ClockStop->AcquireStart | 1303 | Not Covered |  
ClockStop->Idle | 1301 | Not Covered |  
HoldBit->AcquireStart | 1303 | Not Covered |  
HoldDevAck->AcquireStart | 1303 | Not Covered |  
HoldStart->AcquireStart | 1303 | Not Covered |  
HoldStart->Idle | 1301 | Not Covered |  
HoldStop->AcquireStart | 1303 | Not Covered |  
HostClockLowAck->AcquireStart | 1303 | Not Covered |  
HostClockLowAck->Idle | 1301 | Not Covered |  
HostClockPulseAck->AcquireStart | 1303 | Not Covered |  
HostHoldBitAck->AcquireStart | 1303 | Not Covered |  
PopFmtFifo->AcquireStart | 1303 | Not Covered |  
ReadClockLow->AcquireStart | 1303 | Not Covered |  
ReadClockPulse->AcquireStart | 1303 | Not Covered |  
ReadHoldBit->AcquireStart | 1303 | Not Covered |  
SetupStart->AcquireStart | 1303 | Not Covered |  
SetupStart->Idle | 1301 | Not Covered |  
SetupStop->AcquireStart | 1303 | Not Covered |  
SetupStop->Idle | 1301 | Not Covered | 

Tasks to add to the waiver file:

- [ ] `i2c_protocol_cov`
- [ ] Host state transitions to `AcquireStart` and `Idle`

This issue was pulled out from https://github.com/lowRISC/opentitan/issues/17448 and https://github.com/lowRISC/opentitan/issues/18251

**Comment by marnovandermaas** [comment]
I've made an initial attempt at hand-writing the waiver file without much success, but I link it here for reference: https://github.com/marnovandermaas/opentitan/tree/i2c_fsm_waiver

**Comment by johngt** [comment]
@msfschaffner / @moidx - we will need assistance with the creation of the waivers for closing out I2C V2 FSM coverage.
Not sure who would be the best point of contact for getting assistance to @marnovandermaas / @crteja on this?

**Comment by marnovandermaas** [comment]
Yes, specifically we need someone with access to Verdi to generate these waivers for VCS.

**Comment by msfschaffner** [comment]
Indeed, we need someone with the right tooling to generate this.
I will get back to you regarding this.

**Comment by jdonjdon** [comment]
@marnovandermaas @johngt 
I create exclusion file as describe in #18725 
Please copy this and add to i2c/dv/cov and update  cfg.hjson too.

**Comment by marnovandermaas** [comment]
This has now been completed with the merge of #18728
