### ISSUE TITLE
[formal/connectivity] JTAG csv breaks chip_earlgrey_asic connectivity test

### ISSUE THREAD

**Issue by dkabely-ot** [lowRISC/opentitan#18685]
### Description

[jtag.csv](https://github.com/lowRISC/opentitan/blob/4ae519247d580e911cd9421c30a04554a928c908/hw/top_earlgrey/formal/conn_csvs/jtag.csv#L15C1-L20) breaks the compilation of `chip_earlgrey_asic` formal connectivity tests, which stems from unrecognized `top_earlgrey_pkg::*` constants:

![conn_load_err](https://github.com/lowRISC/opentitan/assets/83413366/823ce983-5efb-4a45-a752-f375a3a32263)

**Comment by msfschaffner** [comment]
Yeah this does not look right - the checks are fixed here: https://github.com/lowRISC/opentitan/pull/18777
