### ISSUE TITLE
[hw, hmac] HMAC FIFO backs up when hash_start isn't asserted

### ISSUE THREAD

**Issue by jon-flatley** [lowRISC/opentitan#1869]
It is invalid to write to the HMAC FIFO when `hash_start = 0`, however with the current hardware doing so can cause the core to lock up. From my testing this happens when doing a two writes to `MSG_FIFO` after `fifo_depth = 16`.

This isn't ideal behavior since it forces the DIF implementation to track this bit of state in order to prevent a potential deadlock. It would be better for these writes to get treated as a no-op so an invalid state can't lock up the system.

## Steps to reproduce

If you would like to see this behavior for yourself you can checkout my HMAC DIF branch jon-flatley/opentitan@b3a31b01b47cbc7fa9d7eb5162c0fe2a33ba32d4 and apply this patch to set the test to run without setting `hash_start`:

<details>
  <summary>Test patch</summary>
  
  ```patch
---
 sw/device/lib/dif/dif_hmac.c         | 7 ++++++-
 sw/device/tests/hmac/dif_hmac_test.c | 1 +
 2 files changed, 7 insertions(+), 1 deletion(-)

diff --git a/sw/device/lib/dif/dif_hmac.c b/sw/device/lib/dif/dif_hmac.c
index af4a6537..49780b91 100644
--- a/sw/device/lib/dif/dif_hmac.c
+++ b/sw/device/lib/dif/dif_hmac.c
@@ -6,6 +6,7 @@
 
 #include "hmac_regs.h"  // Generated.
 #include "sw/device/lib/base/memory.h"
+#include "sw/device/lib/log.h"
 
 #define HMAC_HASH_SIZE_BITS 256u
 #define HMAC_KEY_REG_COUNT (HMAC_HASH_SIZE_BITS / 32)
@@ -115,7 +116,7 @@ dif_hmac_fifo_error_t dif_hmac_fifo_push(const dif_hmac_t *hmac,
     return kDifHmacFifoErrorInvalidArgument;
   }
 
-  if (!hmac->hmac_started) {
+  if (false && !hmac->hmac_started) {
     return kDifHmacFifoErrorInvalidState;
   }
 
@@ -127,6 +128,8 @@ dif_hmac_fifo_error_t dif_hmac_fifo_push(const dif_hmac_t *hmac,
 
   // Bring |data_sent| into alignment so we can use |read32()| in the next loop.
   while (unaligned_bytes > 0 && get_fifo_available_space(hmac) > 0) {
+    LOG_INFO("Unaligned bytes remaining = %d\r\n", unaligned_bytes);
+    LOG_INFO("FIFO depth = %d\r\n", get_fifo_entry_count(hmac));
     mmio_region_write8(hmac->base_addr, HMAC_MSG_FIFO_REG_OFFSET, *data_sent);
     data_sent += sizeof(uint8_t);
     --unaligned_bytes;
@@ -134,6 +137,8 @@ dif_hmac_fifo_error_t dif_hmac_fifo_push(const dif_hmac_t *hmac,
 
   // Write whole words until the FIFO fills or there are no words left to send.
   while (words_remaining > 0 && get_fifo_available_space(hmac) > 0) {
+    LOG_INFO("Words remaining = %d\r\n", words_remaining);
+    LOG_INFO("FIFO depth = %d\r\n", get_fifo_entry_count(hmac));
     uint32_t word = read_32(data_sent);
 
     mmio_region_write32(hmac->base_addr, HMAC_MSG_FIFO_REG_OFFSET, word);
diff --git a/sw/device/tests/hmac/dif_hmac_test.c b/sw/device/tests/hmac/dif_hmac_test.c
index ecc5a5fc..2447809a 100644
--- a/sw/device/tests/hmac/dif_hmac_test.c
+++ b/sw/device/tests/hmac/dif_hmac_test.c
@@ -45,6 +45,7 @@ static bool test_setup(const dif_hmac_config_t *config, dif_hmac_t *hmac) {
         return false;
     }
   }
+  return true;
 
   switch (dif_hmac_start(hmac)) {
     case kDifHmacErrorNone:
-- 

  ```
  
</details>

With openocd/gdb you can see things get hung up here:
```
0x200003e0 in mmio_region_write32 (value=543452769, offset=2048, base=...)
    at /home/jflat/ws/opentitan/sw/device/lib/base/mmio.h:137
137	  ((volatile uint32_t *)base.base)[offset / sizeof(uint32_t)] = value;
```

The test I'm using can be build with (I've been testing on fpga)
```
ninja -C build-out sw/device/tests/hmac/dif_hmac_test_fpga_nexysvideo
```

And deployed with
```
./build-bin/sw/host/spiflash/spiflash --input \
build-bin/sw/device/tests/hmac/dif_hmac_test_fpga_nexysvideo.bin
```

**Comment by cindychip** [comment]
Thank you for the report. I could see the issue with my testbench. From the waveform, even though `hash_start` is not set, msg_fifo still starts to count and read all the input data.
To reproduce this scenario, I commented out two assertions: 
```
  `ASSERT(ValidHashProcessAssert, reg_hash_process |-> initiated)
  `ASSERT(MsgFifoEmptyWhenNoOpAssert,
          !in_process && !initiated |-> $stable(message_length))
```
Maybe we can re-investigate these, and change the illegal cases to some error interrupt messages.

**Comment by eunchan** [comment]
Jon, Thanks for raising the issue.

Yes, HMAC does accept the writes to MSG_FIFO without `hash_start`.
I will revise the design to drop the request.

**Comment by eunchan** [comment]
@jon-flatley could you please re-test this ? I hope PR #1875 solves this :)

**Comment by eunchan** [comment]
Ping @jon-flatley

**Comment by jon-flatley** [comment]
Thanks for the ping @eunchan, just updated the HMAC DIF and tested on top of #1875 and pushing to the FIFO with `hmac_start = 0` is no longer locking things up. Thanks for the fix, and I'll close this out!
