### ISSUE TITLE
[tlul,sram] Dealing with Xs in data on the TL-UL bus.

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#1870]
The current TL-UL protocol checker has assertions that check data for active byte lanes is never X, however I'm not convinced this is the correct thing to do, specifically when accessing SRAM or other RAM that could produce Xs as data.

Leaving things as is presents two issues:

1. The Ibex -> TL-UL adapter needs to generate a precise size field for 'Get' messages, rather than just setting it to 32-bit. This is because for a 'Get' message all byte-lanes that could be accessed (as indicated via address and size) must have their mask bits set to comply with the TL-UL specification.

2. It triggers a X-check assertion failure if software reads from a location it has not yet written to. Whilst this may be an error in the software I don't think this should trigger an assertion failure. In particular I think it's reasonable to have a test that reads a bunch of memory locations it hasn't written to and discards all of the data or otherwise does something with that data that overall doesn't have any effect (e.g. do some operations on it and write it back to some other portion of memory that again doesn't effect anything).

1 is easy enough to deal with but I think 2. is a point worth discussing.

If we do allow reading of Xs then this means we'd need to allow writing of Xs too (Ibex could read X from one location then write it back elsewhere).

Perhaps we could selectively enable X checks on data (e.g. for most/all devices we wouldn't want Xs on reads)?

Alternatively setup all memories to have random contents at time 0 rather than X.

**Comment by GregAC** [comment]
@msfschaffner @sriyerg @rswarbrick @imphil @eunchan @weicaiyang any thoughts?

**Comment by eunchan** [comment]
My personal preference is, If any test scripts/ core softwares want to read data from SRAM even it is testing purpose, it should write first. Also, even without this, eventually (probably) all SRAM will have parity protection at minimum. So reading any portion of this will create TL error.

**Comment by cdgori** [comment]
Maybe I'm not being imaginative enough, but what is the purpose of the test in case 2 that reads from uninitialized memory and writes whatever is read (X) to some other place?  (And further, what operations would be done on X?)

> Alternatively setup all memories to have random contents at time 0 rather than X.

Xs have a nice (and also sometimes very annoying) tainting property such that I have seen simulation models for memories that have a mode switch for their init state to choose between X and random, as you suggest.  There are times when random is very handy, and there are times when X is faster to debug consumption of uninitialized values.

**Comment by GregAC** [comment]
From a principled point of view it should be possible for the core to read a bunch of data from uninitialized memory, process it in some way (e.g. sum it all) and write the results elsewhere. If the results are never read again or otherwise used the whole process shouldn't effect any test outcome. So you're testing that isolated data processing hasn't left some kind of side-effect on the core which causes a functional change in how other things are processed.

Practically you're right in that if you wish to test that sort of thing you can initialize the memory beforehand and you'll still end up getting the same kind of coverage.

There is a slight issue around unaligned accesses. Here you'll get tilelink transactions accessing bytes outside of those that the core is actually trying to read. So from a strict software point of view you may have initialized all of the bytes you think you're touching but actually you need to intialize slightly more than that (every 32-bit word that contains a byte you might read) otherwise you'll get Xs in active byte-lanes.

**Comment by sriyerg** [comment]
Prefer to keep the assertion check and force the SW to always read initialized memory addresses. The assertion error provides a way for SW to catch mistakes like these. 

If a test has an explicit requirement to do random reads and writes, it can pre-initialize the memory with junk data for its particular usecase.

**Comment by eunchan** [comment]
I remember the internal discussion about this. And it is expected that 
the software makes sure to initialize all the access region right at the 
beginning (including the stack too). So, any unaligned access pointing 
to bss section falls into the initialized section.

Having that assertion in TL is really helpful to catch the case you 
mentioned. So, let's keep it.

**Comment by sjgitty** [comment]
My preference would be to keep the assertion, and only disable on tests
that have an explainable reason as to why it has fired. If that turns out to
be all tests, then we'd be forced to solve.

**Comment by GregAC** [comment]
Ok, closing this as I believe it's resolved (i.e. we are happy with the current state of affairs and will deal with firings of the data xcheck assertions as and when they occur, e.g. #1880). Thank you for the input everyone.
