### ISSUE TITLE
[rtl,i2c,host] RSTART condition can cause timing violations

### ISSUE THREAD

**Issue by hcallahan-lowrisc** [lowRISC/opentitan#18718]
# Description

In some cases, SDA can be seen to rise synchronously with SCL before then dropping again indicating the RSTART. This looks like a timing violation, although [the specification](https://web.archive.org/web/20210813122132/https://www.nxp.com/docs/en/user-guide/UM10204.pdf) does not explicitly define a setup-time for SDA against this particular edge of SCL.
The specification does seem to imply the violation from the following:
1) `'The data on the SDA line must be stable during the HIGH period of the clock. The HIGH
or LOW state of the data line can only change when the clock signal on the SCL line is
LOW'`
2) A data set-up time t<sub>SU;DAT</sub> is defined against the rising edges of SCL for data bits, which probably implies the same to be required for the SCL edge at the end of a transaction before an RSTART.

In testing on hardware (see waveforms captured below), all of the transactions successfully read and write from the target device without error, so hardware seems to be somewhat tolerant of this behaviour. However, some devices require an RSTART between register address and data phases of a read operation, so it is important that this is not decoded as a STOP followed by a START.

# Repro
```
./util/dvsim/dvsim.py hw/ip/i2c/dv/i2c_sim_cfg.hjson -i i2c_host_rx_oversample --tool xcelium --waves shm --fixed-seed 3318323519
Observe the waveform at t=3700885.617ns
```

# Screenshots
![Screenshot from 2023-05-22 17-07-05](https://github.com/lowRISC/opentitan/assets/102029880/146dd784-0715-45de-bb6c-0f95c03e65bd)
![Screenshot from 2023-05-22 17-07-38](https://github.com/lowRISC/opentitan/assets/102029880/32fcf1fc-39ae-4e83-839d-c4fc1771417b)
![Screenshot from 2023-05-23 14-59-05](https://github.com/lowRISC/opentitan/assets/102029880/36edb03d-123a-46ad-a99a-3e6af73d3873)

**Comment by johngt** [comment]
@hcallahan-lowrisc - I believe that the fixes that went into the ECO/RTL change have resolved this? If so please link to the commit and close this. TIA

**Comment by hcallahan-lowrisc** [comment]
> @hcallahan-lowrisc - I believe that the fixes that went into the ECO/RTL change have resolved this? If so please link to the commit and close this. TIA

Correct, this issue is fixed by https://github.com/lowRISC/opentitan/pull/18729.
