### ISSUE TITLE
[SPI HOST] SPI Host - Test plan - remaining items

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#18710]
## Description

This issue details what needs to be tested for the next deadline, and complements the previous [test plan](https://github.com/lowRISC/opentitan/issues/18640).

- [x] Target tests for both SPI_HOST0 and SPI_HOST1
- [x] Test different flash partnumbers.

**Comment by msfschaffner** [comment]
@engdoreis can you update this issue with the current status?

**Comment by engdoreis** [comment]
There's no progress in spi front since the creation of this issue as I was focusing on i2c.
So I'm planing to go back to spi testing by the end of this week, starting with the last two items in the checklist above

**Comment by engdoreis** [comment]
The PR #18977 completes the last two items.
The remaining SPI NOR flash commands won't increase coverage in my opinion, so I would ignore them.
The remaining SPI host features won't be tested before Friday, I'm afraid.
