### ISSUE TITLE
NameError: name 'utils' is not defined

### ISSUE THREAD

**Issue by satnam6502** [lowRISC/opentitan#1874]
After updating (having not built the bistream in many weeks) I am back at the point where the bitstream builds (at commit b60aaa5f9a93c3e517b27446df1efe56902d62ee):
```console
INFO: SUCCESS! FPGA xc7a200tsbg484-1 successfully programmed with bitstream lowrisc_systems_top_earlgrey_nexysvideo_0.1.bit.
```
but I can't seem to download the bitstream anymore:
```console
$ fusesoc --cores-root . pgm lowrisc:systems:top_earlgrey_nexysvideo:0.1
WARNING: Unknown item formal in section Target
WARNING: Unknown item formal in section Target
Traceback (most recent call last):
  File "/usr/local/google/home/satnam/.local/bin/fusesoc", line 10, in <module>
    sys.exit(main())
  File "/usr/local/google/home/satnam/.local/lib/python3.7/site-packages/fusesoc/main.py", line 908, in main
    args.func(cm, args)
  File "/usr/local/google/home/satnam/.local/lib/python3.7/site-packages/fusesoc/main.py", line 109, in pgm
    None,
  File "/usr/local/google/home/satnam/.local/lib/python3.7/site-packages/fusesoc/main.py", line 490, in run_backend
    edam = utils.yaml_fread(eda_api_file)
NameError: name 'utils' is not defined
```
I went through all the documentation I could find to see if there was a tool I had not upgraded but can't immediately see what is going wrong here.

Has anyone else experienced this or got a suggestion for what I should investigate?
Many thanks.

**Comment by imphil** [comment]
That's indeed a bug in the latest version of fusesoc. You can work around it right now by changing `/usr/local/google/home/satnam/.local/lib/python3.7/site-packages/fusesoc/main.py:490` to read `fusesoc.utils.yaml_fread` instead of `utils.yaml_fread`. I'll follow up with a patch tomorrow.

**Comment by satnam6502** [comment]
Well that worked (after also adding the import for `fusesoc`!
```console
Version:    opentitan-snapshot-20191101-1-875-gb60aaa5f
Build Date: 2020-04-01, 14:51:04
Bootstrap requested, initialising HW...
                                       HW initialisation completed, waiting for SPI input...
```
Thank you very much for your quick response.

**Comment by imphil** [comment]
This is now fixed in fusesoc. Thanks for your bug report!
