### ISSUE TITLE
[bindgen] Failing due to older libstdc++.s0.6 on CentOS 7 

### ISSUE THREAD

**Issue by dbeitel-opentitan** [lowRISC/opentitan#18759]
### Description

Looks like bazel is downloading the bindgen package for a newer version of the libstdc++

bash bazelisk.sh --output_user_root=/home/dbeitel/.opentitan build --jobs 8 //...
which: no bazel in (/home/tools/Xilinx/Vitis_HLS/2022.2/bin:/home/tools/Xilinx/Model_Composer/2022.2/bin:/home/tools/Xilinx/Vivado/2022.2/bin:/home/tools/Xilinx/DocNav:/tools/verible/v0.0-2135-gb534c1fe/bin:/tools/verilator/4.210/bin:/opt/rh/devtoolset-11/root/usr/bin:/usr/lib64/qt-3.3/bin:/home/dbeitel/perl5/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/dbeitel/.local/bin:/home/dbeitel/bin)
INFO: Build option --features has changed, discarding analysis cache.
WARNING:root:Closest bitstream to HEAD is 44c75fcc9cc4c4c4daa551d0614ae49b85e54cc4.
WARNING:root:No manifest found. Attempting to generate manifest from legacy file paths.
INFO: Analyzed 30714 targets (641 packages loaded, 94265 targets configured).
INFO: Found 30714 targets...
INFO: From Running Cargo build script libftdi1-sys:
Build Script Warning: Config for libftdi1 not found, falling back to default search path: `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" PKG_CONFIG_ALLOW_SYSTEM_LIBS="1" "pkg-config" "--libs" "--cflags" "libftdi1" "libftdi1 >= 1.4"` did not exit successfully: exit status: 1
INFO: From Running Cargo build script libftdi1-sys:
Build Script Warning: Config for libftdi1 not found, falling back to default search path: `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" PKG_CONFIG_ALLOW_SYSTEM_LIBS="1" "pkg-config" "--libs" "--cflags" "libftdi1" "libftdi1 >= 1.4"` did not exit successfully: exit status: 1
ERROR: /mnt/hgfs/dbeitel/workspace/com.rivos.opentitan-integrated/sw/host/opentitanlib/bindgen/BUILD:36:21: Generating bindings for sw/host/opentitanlib/bindgen/difs.h.. failed: (Exit 101): bindgen__bin failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_rust_bindgen__bindgen-0.60.1/bindgen__bin --no-rustfmt-bindings '--allowlist-var=CLKMGR_.*_BIT' '--allowlist-var=CLKMGR_.*_REG_OFFSET' ... (remaining 48 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at bazel-out/k8-opt-exec-2B5CBBC6/bin/_solib_k8/_U@bindgen_Uclang_Ulinux_S_S_Clibclang___Ulib/libclang.so could not be opened: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by bazel-out/k8-opt-exec-2B5CBBC6/bin/_solib_k8/_U@bindgen_Uclang_Ulinux_S_S_Clibclang___Ulib/libclang.so)"', external/rules_rust_bindgen__bindgen-0.60.1/src/lib.rs:2172:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/core/src/result.rs:1790:5
   3: std::sys_common::once::futex::Once::call
   4: bindgen::clang_version
   5: bindgen__bin::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
INFO: Elapsed time: 198.363s, Critical Path: 100.03s
INFO: 607 processes: 235 internal, 372 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

**Comment by msfschaffner** [comment]
@timothytrippel FYI

**Comment by timothytrippel** [comment]
@dbeitel-opentitan I had to solve this for our internal infrastructure as well. The way I solved it was two fold:
1. I built a newer version of `libstdc++.so` for our internal infrastructure by building GCC from source (I pulled / built release 9.3.0: `git clone --branch releases/gcc-9.3.0 --depth 1 git://gcc.gnu.org/git/gcc.git <download to this local dir>`)
2. I patched `rules_rust` a while ago to enable it to set `LD_LIBRARY_PATH` during the Bazel build when you set the following envar: `export RULES_RUST_BINDGEN_LIBSTDCXX_DIR="/path/to/gcc/lib64"` (Note: you won't need to patch `rules_rust` yourself, the version Bazel pulls in is already patched, you just need to set the aforementioned envar.)

**Comment by dbeitel-opentitan** [comment]
@a-will I'd love to upgrade, but our HW flow is based on CentOS-7 and I don't think we are upgrading anytime soon.  @timothytrippel Yeah, I can do that but I was hoping there was a way to cleanly work in CentOS-7.

Thanks for the info.

**Comment by yongyw123** [comment]
Hi @timothytrippel , 

Overview: I am a new user of OpenTitan, and I encounter a similar error shown in snippet below when I run this: `bazel test --test_output=streamed //sw/device/tests:uart_smoketest_sim_verilator` on Centos 7 even after I have done the following. Please advise. Thank you.
1. I have built GCC of version 11.1.0 from source and
2. set the `export RULES_RUST_BINDGEN_LIBSTDCXX_DIR="/path/to/gcc/lib64"` in my .bashrc and `source .bashrc`

Environment:
1. Centos 7
2. Verilator version: 4.210
3. GCC version: 11.1.0
4. LLVM (and CLang) version: 16.0.6

What I have done:
1. I am only getting started with OpenTitan, and I use the Verilator workflow as recommended in the [Getting Started page](https://opentitan.org/guides/getting_started/index.html#getting-started).
2. I could run the chip simulation on its own successfully: `bazel build //hw:verilator`
3. Among other things, I have tried to explicitly add the gcc library path to the LD_LIBRARY_PATH but to no avail. Regardless, I could not get past the error. Note that for each change in the environment, I ran a `bazel clean --expunge` to start from a clean slate. 

Error Message Snippet:
![error-message](https://github.com/lowRISC/opentitan/assets/121590608/8c7f88e4-afc9-4996-acba-627a4dc97155)

**Comment by timothytrippel** [comment]
Sorry late to this one, is this still an issue or can we close this?

**Comment by dbeitel-opentitan** [comment]
It is, but I don't know what we can do about it.  There is a workaround, but its ugly.  CentOS 7 is being EOLed, but its still in use in by a lot of HW projects.

**Comment by dbeitel-opentitan** [comment]
Lets just close it for now.

**Comment by yongyw123** [comment]
Hi @dbeitel-opentitan , you mentioned that there is a workaround for this libstdc++.s0.6 issue on CentOS 7, but it is ugly. How ugly it is? Would you mind to share what is the workaround?
