### ISSUE TITLE
[sdc] Tune existing constraints

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#18775]
### Description

This is a placeholder issue for any tuning work that needs to be done for M2.5.2.

Things to check for M2.5.2:

- [x] Update JTAG frequency to at least 24MHz. #18847
- [x] Make sure that the mux on the problematic hold path described in #18687 is synthesized in a safe way.

**Comment by andreaskurth** [comment]
@a-will: Do I understand correctly that the problematic hold path described in #18687 (item 2 above) [got removed with the removal of generic mode](https://github.com/lowRISC/opentitan/issues/18687#issuecomment-1889989176)? If so, do you agree that item 2 above can be checked off?
