### ISSUE TITLE
[usb, dv] usb driver drives differential bus with the same value.

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#18816]
### Description

cmd: 
/util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_usbdev_dpi -r 1 -s 2591390520 -w fsdb

@3241121551ps, tb.u_usb20_usbdpi drives usb_p and usb_n as the same value.
![image](https://github.com/lowRISC/opentitan/assets/99843637/7a423336-ee12-4848-8b82-953aae4b5a39)

**Comment by alees24** [comment]
The USB isn't a true differential bus. It uses both lines low to indicate the end of each packet, and also to signal bus resets. This is referred to as an 'SE0' state. If ever both lines are simultaneously high, that is an invalid state that should not occur.

**Comment by jdonjdon** [comment]
@arnonsha Test is killed by USBRefValKnown_A failure
due to `tb.dut.top_earlgrey.u_usbdev.usb_ref_val_o` goes to x

**Comment by jdonjdon** [comment]
Thanks for clarifying it @alees24. This is not a driver bug.
We will continue to discuss how to address in #18818 and close this.
