### ISSUE TITLE
Closed source hook for Nuvoton validation 

### ISSUE THREAD

**Issue by BenBenderOT** [lowRISC/opentitan#18828]
### Description

Need support for opentitanlib based testing from closed source for Nuvoton post-si validation (using ujson framework as well).

**Comment by BenBenderOT** [comment]
I'll elaborate a little more on what I'm trying to do.
So Nuvoton has internal Testing Equipment Boards (let's call 'em TEBs) I'll be using to validate HW modules.
What I've done up till now is to duplicate the //sw/device/tests/gpio_pinmux target and replaced the test_harness with a duplicate of the host side "//sw/host/tests/chip/gpio" target. In the host side I added my TEB c++ library and successfully compiled it with rust bindings.
This way I can call the TEB functions from a host side harness. 
The only thing is, I'd rather have my TEB lib as well as all of the build targets separated out to an external folder outside the repo. 
Any suggestions would be super helpful.

**Comment by pamaury** [comment]
Pinging @timothytrippel 
Just to make sure that I understand correctly: for the integration, you want to be able to modify the test harness (which is typically opentitanlib-based) to include calls to your TEB library at the right times? And if that's the case, what is missing is:
- a way to include your TEB library in the build system
- a way to call your TEB library at the beginning/end of the test (for example)

**Comment by BenBenderOT** [comment]
Thank you Pouly,
Sorry for taking so long to reply.

So to clarify, I've already created a fully working integration in the
build system. It runs on bazel like everything else.
I've also called the TEB functions during a test with good
synchronization with the chip DUT (thank you ujson ;) ).
But, this would mean I'd need to constantly recopy my changes into the repo
whenever I need to pull from git.

Therefore, ideally there is a way for bazel to inject my files from a
separated workspace. Similar to the manufacturer_hooks target.
I hope this was a little clearer.

**Comment by BenBenderOT** [comment]
And another fix.
I meant to address you as Amaury, not your last name only.
Please forgive me...

**Comment by timothytrippel** [comment]
Sorry a little late to the party here. Yes this is possible. You could just define the targets in the same "manufacturer_test_hooks" Bazel repo, and refer to them in the project with `@manufacturer_test_hooks//:...` labels, the same way closed source code is hooked in the repo: https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/tests/closed_source/BUILD.bazel;drc=9b79762af061a5767376a563499b3f5a6f2af766;l=178 .

Admittedly, this external `@manufacturer_test_hooks` Bazel repo could be cleaned up with a bit more generic names, but as is, it should be able to handle your use-case.

**Comment by BenBenderOT** [comment]
Thanks Tim,
Can I also compile a custom host side test_harness outside the repo or
is manufacturer_test_hooks
good for the device code?

**Comment by timothytrippel** [comment]
I believe @cfrantz resolved this issue with you today @BenBenderOT ? If so, can we close this?

**Comment by BenBenderOT** [comment]
That is correct. We can close it.
