### ISSUE TITLE
[entropy_src/dv] Verify firmware override write and read FIFO over-/underflows

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#18837]
The overflow/full mechanism of the firmware override write FIFO and the underflow/empty mechanism of the firmware override read FIFO need to be tested.

Tasks include (list not exhaustive yet):
- [ ] Read the `fw_ov_wr_fifo_full` and `fw_ov_rd_fifo_overflow` CSR in tests via TL-UL.
- [ ] Predict their expected value in the scoreboard.
- [ ] Verify that a read from the Observe FIFO register when Observe FIFO Depth is zero is according to specification.

**Comment by msfschaffner** [comment]
Possibly related to #18109

**Comment by vogelpi** [comment]
This should be tested as the firmware override modes and observe FIFO are super important. In the past, there was a bug here (fixed as part of M2). Discussed with @h-filali, this is one of the next issues to investigate after coverage closure.

**Comment by vogelpi** [comment]
Update:
- #23923 reads the `fw_ov_rd_fifo_overflow` CSR in tests via TL-UL and predicts the expected value in the scoreboard.
- @h-filali also noted that reading the Observe FIFO while the depth is 0 results in a FIFO error. This is currently not documented but we both believe it's actually desirable behavior.
- What's left is to read `fw_ov_wr_fifo_full` and predict its value. Hakim is currently working on that.
