### ISSUE TITLE
[chip,test] ext96Mhz test requirement

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#18855]
### Description

Current high frequency external clock tests (except chip_sw_uart_tx_rx_alt_clk_freq),
use high speed external clock (96MHz) without configuring clock manager.
and cause closed source test failure.
According to [clock frequency summary](https://opentitan.org/book/hw/ip/clkmgr/doc/theory_of_operation.html?highlight=high%20speed#clock-frequency-summary),
without configuring clock manager, 96MHz cannot be used.
@msfschaffner, Can you confirm this?

**Comment by jdonjdon** [comment]
cc: @moidx @sha-ron

**Comment by msfschaffner** [comment]
@jdonjdon are the failing tests doing life cycle transitions?
I believe these can only support an external clock of 48MHz, since there is no way in the `lc_ctrl` to indicate that the division ratio should be different.

**Comment by jdonjdon** [comment]
> @jdonjdon are the failing tests doing life cycle transitions? I believe these can only support an external clock of 48MHz, since there is no way in the `lc_ctrl` to indicate that the division ratio should be different.
> 
> (Note that this is different from tests that switch to external clock using the clock manager, where you can choose to match the division ration for 48MHz or 96MHz).

One test does volatile raw unlock.
Others are just in a single lc state (dev, unlock0, rma)

**Comment by jdonjdon** [comment]
ok,
Then can I remove 
https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/dv/chip_sim_cfg.hjson;drc=9b79762af061a5767376a563499b3f5a6f2af766;l=880
from the test plan?
I can also modify other 3 tests (chip_sw_clkmgr_external_clk_src_for_sw_fast_test_*) to enable clkmgr csr.
@moidx WDYT?

**Comment by msfschaffner** [comment]
Yes that should be ok, given the fact that we already have the 48MHz one in the testplan:
`chip_sw_lc_ctrl_volatile_raw_unlock_ext_clk_48mhz`

**Comment by jdonjdon** [comment]
The test is removed in #18875
