### ISSUE TITLE
[rom] Check SPX+ signatures as part of pre-signed binary tests

### ISSUE THREAD

**Issue by cfrantz** [lowRISC/opentitan#18860]
### Description

The `presigned_fpga_binary` test used to be dual-signed with RSA and SPX keys.

Since minting the real RSA keys, this test is signed only with the RSA `test_0` key.  We have not yet generated real SPX keys and we do not have either an HSM or developer-secure-token solution for SPX signing.

Address this situation once we've generated real SPX keys and have a signing solution.

**Comment by timothytrippel** [comment]
This was fixed in #18869.
