### ISSUE TITLE
[rom_e2e] Check the chip_info values in `rom_e2e_self_hash_test`

### ISSUE THREAD

**Issue by cfrantz** [lowRISC/opentitan#18868]
### Description

After we freeze the ROM and commit a binary to the codebase, update the `rom_e2e_self_hash_test` to check for the exact chip_info values we expect in the ROM.

**Comment by msfschaffner** [comment]
CC @timothytrippel @moidx

**Comment by moidx** [comment]
Closing this as implemented. The manual hash verification will be done as part of the tapeout checklist sign off.
