### ISSUE TITLE
[component] error while loading shared libraries with python

### ISSUE THREAD

**Issue by chittaja536** [lowRISC/opentitan#18871]
### Description

 I ran the command : bazel build //hw:verilator

I see that it complains about not being able to find libpython3.7m.so.1.0, however, /usr/bin/python3.7.0/lib is set in the LDB_LIBRARY_PATH variable. 

```
WARNING: Output base '/a/b/c/4675eb9b78f0af7fb4f587d32cf4c247' is on NFS. This may lead to surprising failures and undetermined behavior.
INFO: Analyzed target //hw:verilator (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /a/b/c/opentitan/hw/BUILD:35:14: FuseSoC hw/build.verilator_real failed: (Exit 127): fusesoc failed: error executing command fusesoc '--cores-root=.' run '--flag=fileset_top' '--target=sim' --setup --build '--build-root=bazel-out/k8-fastbuild/bin/hw/build.verilator_real' lowrisc:dv:chip_verilator_sim ... (remaining 2 arguments skipped)
/usr/bin/python/3.7.0/bin/python3: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
Aspect @rules_rust//rust/private:clippy.bzl%rust_clippy_aspect of //hw:verilator up-to-date (nothing to build)
INFO: Elapsed time: 0.346s, Critical Path: 0.05s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

**Comment by jwnrt** [comment]
Bazel cuts environment variables when building, so only python's default paths will be looked at. I don't know whether or not yours is a default, I've had this problem with python modules before (https://github.com/lowRISC/opentitan/pull/18689).

Would you mind trying with `LDB_LIBRARY_PATH` added to [rules/nonhermetic.bzl](https://github.com/lowRISC/opentitan/blob/master/rules/nonhermetic.bzl#L5)?

**Comment by chittaja536** [comment]
Hi James,

Thank you! That did it.

Regards,
Meghana

**Comment by a-will** [comment]
Fixed by https://github.com/lowRISC/opentitan/pull/19476 perhaps?

**Comment by msfschaffner** [comment]
Closing for now - please reopen if you have follow-up questions.
