### ISSUE TITLE
[doc] White page navigation arrow obscures text

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#18891]
### Description

When hovering over the page navigation arrow, the background becomes opaque and the arrow glyph is obvious. When *not* hovering, the background disappears, but a white arrow remains, layered on top of the text.

For example, see [Install Vivado](https://opentitan.org/guides/getting_started/install_vivado/index.html):

* Hovering:
  <img width="198" alt="Screenshot 2023-06-12 at 10 19 07 AM" src="https://github.com/lowRISC/opentitan/assets/183652/074deb17-747f-49ac-b02c-7860bcac3d8b">
* Not hovering (look at the "o" in "following"):
  <img width="195" alt="Screenshot 2023-06-12 at 10 19 04 AM" src="https://github.com/lowRISC/opentitan/assets/183652/15f17e34-51bd-4048-a400-ea2391fcc248">

@HU90m do you have time to tackle this?

**Comment by dmcardle** [comment]
Not sure what the best solution is, but I think this is where the arrow comes from: https://cs.opensource.google/opentitan/opentitan/+/master:site/book-theme/index.hbs;l=217;drc=a01d654cbf683e656ee329bab9e24593ae41e619

**Comment by dmcardle** [comment]
I should mention that I observed this on Chrome on macOS.  Info ripped from `chrome://version`:

```
Google Chrome | 114.0.5735.106 (Official Build) (arm64)
Revision | 5148e93c94b4990618801dd6918f26936be770f9-refs/branch-heads/5735_90@{#9}
OS | macOS Version 13.4 (Build 22F66)
```

I was surprised to hear from @a-will that he couldn't reproduce the artifact with  Chromium on Ubuntu 22.04 LTS.

**Comment by a-will** [comment]
> I should mention that I observed this on Chrome on macOS. Info ripped from `chrome://version`:
> 
> ```
> Google Chrome | 114.0.5735.106 (Official Build) (arm64)
> Revision | 5148e93c94b4990618801dd6918f26936be770f9-refs/branch-heads/5735_90@{#9}
> OS | macOS Version 13.4 (Build 22F66)
> ```
> 
> I was surprised to hear from @a-will that he couldn't reproduce the artifact with Chromium on Ubuntu 22.04 LTS.

Ahh, my browser window was too wide. After narrowing it, I could see the white arrow in front of the text.

**Comment by HU90m** [comment]
Thanks for opening this. I can reproduce it in firefox.

I've had a look at the theme files for a cause and nothing jumped out at me, e.g. we are using the same `--content-max-width` as the [original theme](https://github.com/rust-lang/mdBook/tree/a204946d39db89db242783afb3f27a0f75189589/src/theme).

Most of our deviations from the original theme, appear to be for the table of contents. @hcallahan-lowrisc do you have any idea what could be causing this problem?
