### ISSUE TITLE
[i2c] Change FSM to stop processing the FMT_FIFO after receiving a NAK

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#18917]
### Description

From #18764:
Despite the IP registering a NAK, the transaction continues normally, when it should really stop and wait for software to clear the NAK condition. It turns out that there is nothing in the i2c FSM to prevent continuing with the next entry in the FIFO.

Fix this and document the expected handling from software.

**Comment by andreaskurth** [comment]
PR #22049, which is currently being discussed, aims to resolve this issue
