### ISSUE TITLE
[usbdev] Iso IN support

### ISSUE THREAD

**Issue by alees24** [lowRISC/opentitan#18942]
### Description

Investigate whether usbdev properly supports Isochronous IN transmission. The periodic provision of packets via configX_in registers may suffer from an inability to replace a buffer that has not yet been collected by the host controller. Ideally, with Isochronous streams prioritizing real-time delivery over reliability, and with the device having no direct control over when the packets are collected, it should be possible to replace the previous buffer in a hazard-free fashion.

This may be possible with the current interface by careful coding and clearing of the RDY bit before presenting the new buffer. Alternatively, it may be sufficient to rely upon the pkt_sent interrupt being processed in time and/or using the timing of the frame interrupt to replace buffers safely.

@johngt 

> estimate 4

**Comment by a-will** [comment]
Hm... if we wanted more hardware support, what might that look like? Perhaps a TTL (time to live) in config_inX that decrements on every SOF received, then clears ready (and possibly asserts an interrupt?) when TTL reaches 0?

**Comment by alees24** [comment]
Subsumed into #19435
