### ISSUE TITLE
[dv/top_earlgrey] Remove setting ast_init_en

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#18974]
### Description

The SV code in chip_base_vseq, in function initialize_otp_creator_sw_cfg_ast_cfg, will overwrite ast_init_en in the otp_ctrl sw_config. There is a flag to control whether this is done, but that can only be set from SV code.

This code may have been written before the otp_ctrl config could be programatically generated, and it seems redundant nowadays. In fact, it gets on the way of running tests that need the ast NOT being initialized.

I think this code should be removed, and we should just rely on the otp images.

**Comment by msfschaffner** [comment]
Are you referring to `do_creator_sw_cfg_ast_cfg`?

I think I agree for the SW-based TLTs, but I am not quite sure this works for other tests like stub-CPU...
I.e. these tests do not execute any ROM code that could initialize the AST, right?

**Comment by matutem** [comment]
I agree, and already created a branch that does that. I'll push a PR, but should add plusargs for any stub-cpu based tests. How can stub-cpu tests be identified?

As for the setting of do_creator_sw_cfg_ast_cfg, I was wrong: it can be set via plusargs, but it is best to have it set to the most commonly used value by default, which should be 0 because of the rom code.

**Comment by matutem** [comment]
It seems it would not be needed for stub_cpu either: the do_creator_sw_cfg_ast_cfg flag causes the OTP image contents to set a flag that would be used by the rom code to determine whether to copy some data to the AST, but that assumes the ROM will do "something", but in stub mode the ROM code should just not be executed, and nothing would copy stuff to the AST.

This means we would not need to add plusargs to enable do_creator_sw_cfg_ast_cfg via plusargs at least for the stub_cpu tests.

**Comment by msfschaffner** [comment]
We have a few tests (e.g. `rom_raw_unlock`) that run with `ast_init_en` set to zero today, hence we do have coverage for that mode.

Therefore, we decided to move this issue to a later milestone, since changing this now could affect the closed source regression significantly.

**Comment by msfschaffner** [comment]
@matutem how far did we get with removing `ast_init_en`?

**Comment by matutem** [comment]
I created https://github.com/lowRISC/opentitan/pull/21097 that removes the flag altogether. Ready for CI and reviews.
