### ISSUE TITLE
[usbdev] SETUP packet ignored when buffer unavailable

### ISSUE THREAD

**Issue by alees24** [lowRISC/opentitan#19017]
### Description

@a-will So we're on the same page, I'm using this Issue as a placeholder for any observations/discoveries during this final verification, and I'll break them out into separate Issues when they've been more fully assessed/classified. **_Everything mentioned is lower priority/prod only._**

_SETUP packet ignored_

Testing a Control Endpoint whilst other endpoints are transmitting and receiving streaming data, I note that Control Transfers to the Control Endpoints can easily time out. This is on the 10MHz CW310 FPGA so the handling of received data packets is slow, and - despite the deepening of the FIFOs - it appears that we exhaust the available buffers and the SETUP packet is swallowed and not ACKnowledged.

On the logic analyzer I observe the host make two quick retries of the SETUP packet transmission before subsequently failing the transfer after just 30-32us (it retries after 15/16us, which is really not very long, but in the USB 2.0 specification it seems that only data corruption/loss has been anticipated, and not an unavailability of resources. There is no mechanism such as NAKing available).

On the chip, Rx buffers should not be hanging around for so long, but I wonder whether perhaps we can/ought to make a small alteration that would allow us to handle SETUP packets more effectively. With the Default Control Pipe, of course, there is not normally a lot of concurrent traffic to other endpoints.

_Structure of usb_testutils software_
 
On a related note, with our current implementation of usb_testutils_poll we accept and handle as many as Rx buffers as possible until the FIFO becomes empty. For normal streaming this is perhaps okay, but with one or more Control Endpoints active, this breaks the 'handle Sent pkt before Rx pkt' effort (see comment in the function) to ensure that the notification of a completed IN Data stage occurs before notification of the receipt of the Status stage ACK.

That logic works only in the event that other Rx packets are not arriving at the same time. For now I've simply opted for a local change that handles only a single Rx packet per pass through the usb_testutils_poll code (worsening the SETUP packet ignored issue described above!).

I wonder whether it would be worth filtering out the Sent/Received pkt notifications for any control endpoints into sequential queues for the control software that handles those endpoints. We then have one such queue per endpoint, and each handler (such as usb_testutils_controlep) is guaranteed to see its events in the order it expects.

TBC...

**Comment by a-will** [comment]
At first glance, this looks like a scheduling problem where our slower Ibex can't keep up with simpler policies. One thing I may be able to do is simply make the FPGA clocks faster, and we can see if that helps.

**Comment by alees24** [comment]
> At first glance, this looks like a scheduling problem where our slower Ibex can't keep up with simpler policies. One thing I may be able to do is simply make the FPGA clocks faster, and we can see if that helps.

It's not clear to me which point you're answering. A faster CPU may be considered to be a 'solution' to the 'SETUP packet ignored' point, although it seems clear from the USB specification that devices are expected to handle SETUP packets at any time; there is no mechanism for signaling that the device is busy and cannot accept the SETUP packet right now. The fact that usbdev rx logic treats both setup and non-setup data packets identically using a single queue, increases the risk of the SETUP packet not being accepted.

A faster CPU does not solve the second point about sequencing the stages of a Control Transfer. Software such as usb_testutils_controlep.c which relies upon the callbacks from usb_testutils.c occurring such that the IN DATA 'tx_done' callback occurs before the 'OUT Status stage' 'rx' callback, requires that usb_testutils.c be changed as described, otherwise - in practice - we cannot prevent that 'rx' leapfrogging the 'tx_done' callback. Whilst there is concurrent streaming traffic on another endpoint, it requires only that the Status stage be received during the execution of usb_testutils_poll() after the point of checking for 'tx_sent' notifications has been passed; handling one or more previously-received data packets on other endpoints is easily sufficient to consume the transmission time of the Status stage.

**Comment by a-will** [comment]
> > At first glance, this looks like a scheduling problem where our slower Ibex can't keep up with simpler policies. One thing I may be able to do is simply make the FPGA clocks faster, and we can see if that helps.
> 
> It's not clear to me which point you're answering. A faster CPU may be considered to be a 'solution' to the 'SETUP packet ignored' point, although it seems clear from the USB specification that devices are expected to handle SETUP packets at any time; there is no mechanism for signaling that the device is busy and cannot accept the SETUP packet right now. The fact that usbdev rx logic treats both setup and non-setup data packets identically using a single queue, increases the risk of the SETUP packet not being accepted.

Yes, it's the first point I was addressing, where you raised that the FPGA is slow at processing RX packets. Having a special queue for SETUP packets in hardware is one route, but we'll want to be careful about introducing ordering hazards.

**Comment by a-will** [comment]
And in case you _wanted_ to see whether a bump in the frequency helps substantially reduce the time to free up space in the RX FIFO, here's a PR and branch that brings it from 10 MHz to 24 MHz: https://github.com/lowRISC/opentitan/pull/19368

**Comment by alees24** [comment]
> And in case you _wanted_ to see whether a bump in the frequency helps substantially reduce the time to free up space in the RX FIFO, here's a PR and branch that brings it from 10 MHz to 24 MHz: #19368

Thanks. I shall keep a copy of that; useful to have for experimenting!

**Comment by alees24** [comment]
What if we had two AvFIFOs, one for regular OUT DATA packets, and one for SETUP DATA packets, and then a single RxFIFO for the received packets?
Then we pluck from the appropriate AvFIFO when receiving an OUT packet, according to whether it's a SETUP packet, but we reserve the final entry in the FIFO for SETUP packets. Only a SETUP packet is permitted to allow the RxFIFO to become full.

We've already deepened the RxFIFO to 8 entries in ES to improve throughput, so reserving the final entry of the 8 is not limiting, and it sidesteps any reordering issues. It means we can accept a SETUP packet, which should appease the Host and stop it immediately retrying and then timing out the Control Transfer.

I've described it as a separate AvFIFO for separate packets, partly to present the same interface to software and partly because it keeps things more general. We could have to cope with multiple SETUP packets since there could be multiple Control endpoints, but in practice I'm imagining no more than a couple of FIFO entries (though they are very inexpensive anyway). Software manages SETUP packet buffers in the same way as received buffers presently; once a SETUP packet has been received and processed, the SETUP AvFIFO is kept topped up.

HW internals: the RxFIFO is a `prim_fifo_sync` and already presents the depth information required for the logic change, and indeed this is already presented in the register interface for software use.

**Comment by a-will** [comment]
> What if we had two AvFIFOs, one for regular OUT DATA packets, and one for SETUP DATA packets, and then a single RxFIFO for the received packets? Then we pluck from the appropriate AvFIFO when receiving an OUT packet, according to whether it's a SETUP packet, but we reserve the final entry in the FIFO for SETUP packets. Only a SETUP packet is permitted to allow the RxFIFO to become full.
> 
> We've already deepened the RxFIFO to 8 entries in ES to improve throughput, so reserving the final entry of the 8 is not limiting, and it sidesteps any reordering issues. It means we can accept a SETUP packet, which should appease the Host and stop it immediately retrying and then timing out the Control Transfer.
> 
> I've described it as a separate AvFIFO for separate packets, partly to present the same interface to software and partly because it keeps things more general. We could have to cope with multiple SETUP packets since there could be multiple Control endpoints, but in practice I'm imagining no more than a couple of FIFO entries (though they are very inexpensive anyway). Software manages SETUP packet buffers in the same way as received buffers presently; once a SETUP packet has been received and processed, the SETUP AvFIFO is kept topped up.
> 
> HW internals: the RxFIFO is a `prim_fifo_sync` and already presents the depth information required for the logic change, and indeed this is already presented in the register interface for software use.

That sounds good to me!
