### ISSUE TITLE
[edn/dv] Randomly enable `regwen` in as many tests as possible

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#19028]
Currently only the `edn_regwen` test (which is `edn_smoke_test` + `edn_regwen_vseq`, thus very simple) enables `regwen`. We should ideally enable `regwen` with a certain probability in as many of the different test cases as possible, in order to verify that it works properly. (Note that there are also automated CSR tests, which AFAIK take `regwen` into account, so we should only add tests for what is not covered by the automated tests.)

This will also need support from the scoreboard (in the part that predicts the effects of TL accesses).

**Comment by vogelpi** [comment]
Moving to M7 as this is more like a V3 item.
