### ISSUE TITLE
[i2c] Test plan - 2.5.2 remaining items

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#19035]
## Description
This issue details what needs to be tested for the next milestone for the I2C Host and complements the previous [test plan](https://github.com/lowRISC/opentitan/issues/18711).
- [ ] I2C features
   - [ ] Speeds
     - [ ] Slower speeds (5kHz, 10kHz,...) 
     - [x] Fast-mode (400 kbaud) [Note - see comments in [closed source](https://github.com/lowRISC/ot-discrete-eg/issues/11#issuecomment-1533302464)]
     - [x] Fast-mode Plus (1 Mbaud) [Note See comments in closed source - [2023-05-03](https://github.com/lowRISC/ot-discrete-eg/issues/11#issuecomment-1533302464)]
    - [ ] Device irqs
      - [ ] host_timeout
      - [ ] unexp_stop
      - [ ] acq_full
      - [ ] tx_overflow
      - [ ] tx_stretch
   - [ ] FDATA.RCONT?
  ~~- [ ] Loopback. [Low priority - see [comment](https://github.com/lowRISC/ot-discrete-eg/issues/11#issuecomment-1526744587)]~~ plan to remove this from RTL, so not needed anymore

**Comment by hcallahan-lowrisc** [comment]
Closing this issue in favor of #23077
