### ISSUE TITLE
[edn] Don't propagate SW commands after a fatal error

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#19037]
bad029c9c7 fixes the propagation of SW commands, so that writes to the `SW_CMD_REQ` register don’t propagate in multiple Auto mode states. The default assignment in EDN’s main FSM still allows the propagation of SW commands, though, and these default assignments apply even to the fatal error state. **Thus, SW can send commands to CSRNG even if EDN is in the fatal error state.** A CSRNG command that returns `genbits` will get those bits stored in EDN’s internal FIFOs. EDN’s endpoints cannot access the entropy in the fatal error state, however, because the acknowledge FSM stops acknowledging requests. We don’t test this case currently, but we do have the `EdnFatalAlertNoRsp_A` assertion, which ensures that EDN does not acknowledge any requests in the fatal alert state.

**For D3, we should tweak the main FSM so that it only propagates SW commands when needed (and certainly not in the fatal alert state).**

**Comment by msfschaffner** [comment]
@h-filali can you check whether this has already been fixed (and link the PR here + close the issue)?

**Comment by h-filali** [comment]
@msfschaffner this issue should be fixed by #20293 
I also added some checks in the DV if SW commands can be issued during auto mode but not in the alert state.
As discussed with @msfschaffner and @vogelpi, the latter part is not that important.

**Comment by vogelpi** [comment]
Thanks for getting back on this. Yes, I also think that specifically verifying that no SW commands are issued while in the alert state is not critical.
