### ISSUE TITLE
[spi host] Test plan - 2.5.2 Remaining items

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#19036]
### Description

This issue details what needs to be tested for the next deadline, and complements the previous [test plan](https://github.com/lowRISC/opentitan/issues/18710).

- [ ] **Features**:
  - [x] Byte-count.
  - [ ] ~32 bit big or little endian.~ --> It only make sense to be tested in DV as it is a RTL parameter.
  - [ ] ~Max speed of 30 Mhz.~ --> Due to environment constraints, It can be tested beyond 16MHz.
  - [x] Polarity phases (CPOL, CPHA) --> lower priority as there's only one mode used in practice.
     - [x] CPOL = 1
     - [x] CPHA = 1
  - [ ] Chip select automatic control.
    - [x] CSNLEAD, CSNTRAIL and CSNIDLE. (expect this to be covered in DV)
    - [ ] ~Mix transactions with two different devices with different clocks~.--> The spi_host only supports one csb.
    - [ ] ~Different number of CSBs~ --> The spi_host only supports one csb.

**Comment by msfschaffner** [comment]
@engdoreis did we make any progress on this or the status still accurate?

**Comment by engdoreis** [comment]
Yes, the status is accurate. Unfortunately, I haven't spent time on this, so no progress.

**Comment by andreaskurth** [comment]
@engdoreis: Do you think you'll be able to complete this for M4? If not, which items do you think are critical to get tested for Earlgrey-PROD?

**Comment by engdoreis** [comment]
It's not prioritized for SiVal, so unless @moidx changes the priority, it won't be completed before M4.

**Comment by andreaskurth** [comment]
Discussed in triage: okay to move to M5

**Comment by moidx** [comment]
@johngt  to follow up with the software team to update estimates and implementation plan.

**Comment by johngt** [comment]
@luismarques - as discussed - believe we should see if any of the integration tests are failing on the BoBs, particularly around features that have changed in Spi_host. If they are all ok, suggest closing off this issue.
@a-will has suggested that we should have a task in the future to see if we can test either in FPGA or on a modified board to see if we can test multi-controller mode and the other features he worked on.

**Comment by a-will** [comment]
> @a-will has suggested that we should have a task in the future to see if we can test either in FPGA or on a modified board to see if we can test multi-controller mode and the other features he worked on.

A little mix-up here--This note is for i2c, not spi_host.

**Comment by johngt** [comment]
@engdoreis can you look through this issue and see whether there is anything you particularly want to focus on testing for M5. If there are items that are long-tail and nice-to-haves those can be split off. Only important items that need testing should remain here

**Comment by engdoreis** [comment]
Update:
### 32 bit big or little endian
 It only make sense to be tested in DV as it is a RTL parameter.
### Max speed of 30 Mhz.
 Working in progress.
### Polarity phases (CPOL, CPHA)
 Working in progress.
### Mix transactions with two different devices with different clocks
 The spi_host only supports one csb.
### Different number of CSBs 
 The spi_host only supports one csb.

**Comment by engdoreis** [comment]
Due to environment constraints, I can test the chip beyond 16MHz.

**Comment by engdoreis** [comment]
Working on `Polarity phases (CPOL, CPHA)`, which should be finished by Friday, July 12th.
