### ISSUE TITLE
[otbn] Fix OTBN usage of life cycle control signals

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#19050]
### Description

The usage of the life cycle signals `lc_escalate_en` and `lc_rma_req` in OTBN does not follow our design guidance, and hence CDC stagger on these signals may lead to spurious local escalation.

Due to the clock domain composition in Earlgrey, however, this is not an issue for Earlgrey-ES, and hence an ECO was not warranted for fixing this. The usage should however be corrected for PROD.

See https://github.com/lowRISC/opentitan/issues/19044 for context.

CC @GregAC @vogelpi

**Comment by msfschaffner** [comment]
I looked a bit closer at the OTBN usage of these life cycle signals and had some initial discussions with @andreaskurth.
It's probably best if we align the usage with the rest of the design and remove the invalid checks.
The OTBN model will have to be updated as well, though it sounds like removing these checks could get rid of some corner cases that are cumbersome to model.

@vogelpi @GregAC @rswarbrick

**Comment by msfschaffner** [comment]
@vogelpi @GregAC I just realized that we probably have to fix this for integrated due to the removal of the flash controller. If we don't have the time to implement a clean fix, one option would be to use a "rectifying" multibit synchronizer (similar to the one available for mubi signals).

**Comment by msfschaffner** [comment]
I believe @vogelpi has fixed this, but I wanted to check whether this has been carried over to the open repository already?

**Comment by vogelpi** [comment]
Thanks for the ping. This is not yet fixed. I've moved over the first part of the changes (around ` lc_escalate_en_i`). The second part of the fix cannot be carried over yet as we first need to modify LC_CTRL itself to have two parallel RMA request interfaces for flash_ctrl and OTBN. See https://github.com/lowRISC/opentitan/issues/19136.

I could however prepare a draft PR with these OTBN changes. What is your view @msfschaffner , are we going to change LC_CTRL for PROD?

**Comment by msfschaffner** [comment]
The fewer changes, the better - although that change may not be very difficult to do.
Let's keep https://github.com/lowRISC/opentitan/issues/19136 marked as a PROD candidate so that we can discuss this further during feature prioritization.

I still think we can probably close this issue here, since this was related to possible CDC issues.
We are tracking the serial/parallel request issue separately already...
