### ISSUE TITLE
Unable to generate .fst files with bazel tests

### ISSUE THREAD

**Issue by wickedb** [lowRISC/opentitan#19065]
My objective is to understand the cycle-wise behaviour of the otbn module by running one of the sw tests and studying the vcd. I'm referring to [the docs](
https://opentitan.org/guides/getting_started/setup_verilator.html?highlight=--test_output#generating-waveforms-optional) and using the command 

```bash
 bazel test //sw/device/tests:uart_smoketest_sim_verilator \ ###i intend to replace this with an otbn test 
  --test_output=streamed \
  --test_timeout=1000 \
  --test_arg=--verilator-args=--trace=/tmp/sim.fst
```

The build is successful but I don't think any .fst file is generated. The bazel command I used to build the hw is
`bazel build //hw:verilator`. I tried `bazel build //hw:verilator_real` too. 

Do I need to generate .fst files using fusesoc commands instead?

**Comment by a-will** [comment]
As the docs say, the argument to --trace should be where the file is (i.e. `/tmp/sim.fst`). Is the file not at that location after running the test?

And if not, can you post the test output? Also, are you using a recent commit? The docs correspond with the added capability to specify where the trace file goes, from https://github.com/lowRISC/opentitan/commit/e4ce94362b883d7e9fbb96b9dd7fd8008909da2b

> Do I need to generate .fst files using fusesoc commands instead?

No, fusesoc is not running the test here.

**Comment by wickedb** [comment]
Ahh, that commit might've been the issue. I ended up using fusesoc and then used `./Votbn_top_sim --trace --load-elf=prog.elf` for the trace. Thanks for your reply.
