### ISSUE TITLE
[CI] Resolve python lint error 

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#1909]
I see the following python lint error in CI (PR #1768). 
```console
Lint failed:
  flake8 util/device_sw_utils/__init__.py util/device_sw_utils/extract_sw_logs.py

##[error]Bash exited with code '123'.
Finishing: Run Python lint
```

I already ran `util/lintpy.py -c --fix` before committing my changes. The failure does not however block me from submitting this PR though. If this can be safely ignored, can the CI be updated such that it does not even show up?

**Comment by rswarbrick** [comment]
See PR #1815: this is intentional and shows that the code doesn't follow the style guide. Rather than block everyone from doing any work, this lint check doesn't currently cause the CI to fail. I think the idea is that we'll get stricter about this over time.

Does this make sense? If so, is there anything remaining for this issue to track?

**Comment by imphil** [comment]
Sri, there's https://github.com/lowRISC/opentitan/issues/1863 to fully clean up the Python DV code. As discussed last week, we're currently running lint in non-enforcing mode to help ease the development of dvsim while there are many in-flight PRs.

As for `lintpy.py --fix`: It should do the right thing. @rswarbrick can you double-check that it actually does? And @sriyerg if you're using `-c`, you also have all of extract_sw_logs.py in your staging area?

**Comment by rswarbrick** [comment]
I didn't change the behaviour of `lintpy.py` with #1815, so running `lintpy.py --fix` won't actually run flake8 (unless you pass the `--tools` argument). Also, `flake8` doesn't have a "FIXIT" mode, so `--fix` can't do anything: there isn't an extra error (the tool exits with status 1 either way).

About the `-c` comment: this tool isn't the same as `clang-format`, which cleverly gets hunks from git. This tool is simpler and stupider: it uses Git to get a name of changed (or staged) files and then lints those files. So adding only some of ones changes to a file will have the same effect as adding all of them.

**Comment by imphil** [comment]
I know about flake8, the question is more: if you run things through yapf/isort (which is what happens if you run `lintpy.py --fix`), have you checked that it also passes flake8?

**Comment by rswarbrick** [comment]
I'm not sure. I wouldn't want to bet that there aren't corner cases. Sri: Do you have a version of your code that triggers the error in a way you don't think should happen? I just tried the head of your branch from that PR and it doesn't trigger any errors (with or without flake8), nor did the last CI run show any.

**Comment by tjaychen** [comment]
hmm.. .this seems like a very stale issue that we can close down.
