### ISSUE TITLE
[sw/silicon_creator] ROM_EXT Boot Services

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#19129]
### Docs
* [ROM_EXT Spec](https://docs.google.com/document/d/1ub7koDE2DEvzUbZ7aQ6Z9wHBCwpCYB2SmdGbvYW9jHQ/edit#heading=h.dv1sckpdnpj6)
* [OpenTitan Boot Services: Intro and Data Structures](https://docs.google.com/document/d/1TxTa_htOGDr3MVyW-Sz2jGgEWArnbLxBJHKpz7qQ3KY/edit)
* [OpenTitan Boot Services: Next Boot BL0 Slot](https://docs.google.com/document/d/1FHTI1goH2mRjn2UsRVC-Z8PU6GwWQv3Rws2ELf1v64A/edit#heading=h.8s2awb1r3686)
* [OpenTitan Boot Services: Set Minimum Required BL0 Security Version](https://docs.google.com/document/d/1NZzYAoo7z_y09QN0sySCmKIHUdgRzqkcgdhjXdW_gjQ/edit)
* [OpenTitan Boot Services: Set Primary BL0 Slot](https://docs.google.com/document/d/109nZqoPeJDWovGGd1J__4MzvouODl-gOdeneLRLh9SM/edit#heading=h.8s2awb1r3686)

### Tasks
- [x] #19130
- [x] #19153
- [x] #19156
- [x] #19154
- [ ] #19257
- [ ] Ownership transfer

**Comment by timothytrippel** [comment]
Closing this as #19585 is now tracking.
