### ISSUE TITLE
[regtool] Doesn't support register with both rw and ro fields

### ISSUE THREAD

**Issue by meisnere** [lowRISC/opentitan#19127]
### Description

I tried to generate external register with some rw and some ro fields.
The tool generated the following code for the ro field:

prim_subreg_ext #(
    .DW    (1)
  ) u_myregname_myfield (
    .re     (myregname_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.myregname.myfield.d),
    .qre    (),
    .qe     (myregname_flds_we[6]),
    .q      (reg2hw.myregname.myfield.q),
    .ds     (),
    .qs     (myregname_myfield_qs)
);

As we is constant 0, myregname_flds_we[6] is also constant zero.

And 
`assign myregname_qe = &myregname_flds_we;`

Yields constant 0.
Therefore non of the rw fields can be written.

Suggested fix:
replace `assign myregname_qe = &myregname_flds_we;`
with `assign myregname_qe = myregname_flds_we[0] & myregname_flds_we[1] ... ;`
while skipping the read only indexes.

**Comment by msfschaffner** [comment]
Hi @meisnere!

The `myregname_qe` is the QE for the entire register, and I am not entirely sure this should be pulsed high on WE if RO register fields are present. Did you try to use the individual field QEs instead?  There should be something like `reg2hw.myregname.myfield.qe` for each field that you declared.

**Comment by meisnere** [comment]
I'm already using reg2hw.myregname.myfield.qe, but the generated file has also the following lines:
  assign reg2hw.myrename.myfield.qe = myregname_qe;
I guess those lines should be updated.

**Comment by msfschaffner** [comment]
Ah, I see.
I guess in that case we should change that so that the actual field `qe`'s are assigned instead.
Let me see whether I can fix that.

**Comment by msfschaffner** [comment]
Btwy, do you need this for creating an ECO for the ongoing tapeout, or is this for PROD?

**Comment by msfschaffner** [comment]
Update: it looks like we do not allow sub-word writes to CSRs by design: https://opentitan.org/book/util/reggen/index.html#error-responses

Hence, the original solution proposed by @meisnere is fine. 
Let me update the draft PR.

**Comment by meisnere** [comment]
This fixe is needed for PROD.

**Comment by msfschaffner** [comment]
@meisnere can you try whether https://github.com/lowRISC/opentitan/pull/19164 works for you?

**Comment by meisnere** [comment]
It added an extra '\' after 'endmodule' which caused a compilation error.
After removing it manually, the register worked fine.

**Comment by msfschaffner** [comment]
Hi @meisnere - can you double check where that `\` came from? The template should not insert this type of character... I also do not see this when I try it locally.

**Comment by meisnere** [comment]
I didn't use the last version of regtool. After updating problem solved :)
