### ISSUE TITLE
[sw,testutils] flash_ctrl_testutils_backdoor_wait_update can create race condition

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#19122]
### Description

[flash_ctrl_testutils_backdoor_wait_update] (https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/lib/testing/flash_ctrl_testutils.h;drc=06d4f654851c647dd7a7682d5a2ef1401743391d;l=264) is used to detect test variable update by sv backdoor write
[example](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/tests/sim_dv/sysrst_ctrl_outputs_test.c;drc=d73a237f0026893a38e88ce3b82f7f3d0bad98cc;l=102)
As show in the example, typical usage cases is,
1. set test status to unique value in c
2. wait the unique value from sv
In parallel,
2-1. call this api in c
       inside the api, set the location of flash to store the test variable (which is kTestPhase in the example) to all 1's.
       waiting for the location become not all 1's, which implies backdoor write from other domain (sv) happened.

While api is polling the location, in sv,
3. backdoor write executed.

Problem happens inside of step 2-1.
In real flash model, write to flash takes several 10s of usec. So step 3 happens before step 2-1 is finished.
In that cases, this api can be finished without detecting proper backdoor updates.

Therefore, this api needs to be updated for real flash model.

Temporary sv work around is added #19119

**Comment by johngt** [comment]
@andreaskurth - believe this should be a SW / tooling task and should go to that Milestone rather than here.

**Comment by andreaskurth** [comment]
Discussed in triage, there may be potential failures with the real flash model, so we need to fix this properly

**Comment by johngt** [comment]
Assigning to @vogelpi for now - to discuss with @matutem

**Comment by vogelpi** [comment]
Discussed with @matutem yesterday, it's on his list again.

**Comment by matutem** [comment]
It turns out I fixed this in https://github.com/lowRISC/opentitan/pull/19326 in July 2023: all that is needed is to correctly flush the read buffers between read attempts so doesn't get stale data. I am closing this.
