### ISSUE TITLE
[usbdev] Forwarded Low Speed traffic raises bit stuffing errors

### ISSUE THREAD

**Issue by alees24** [lowRISC/opentitan#19148]
### Description

This is more an imperfection than a fault; when our Full Speed device is connected to a hub that is operating in Full/Low Speed mode - because it has no High Speed devices connected - the Low Speed traffic to a device connected alongside usbdev is forwarded to our device with a 'PRE' special packet that prefixes the Low Speed transmission. This results in usbdev attempting to interpret the packet data and raising a 'Bit Stuffing error' to the software.

Suggestion: for this release, software should disable the 'rx_bitstuff_err' interrupt to avoid wasting CPU time responding to spurious interrupts. For the future, the RTL should probably be modified to handle this case more cleanly.

Low Speed devices are typically budget keyboards and mice using Interrupt transfer types; this issue was identified when connecting usbdev to a Raspberry Pi 4 Model B alongside an inexpensive keyboard and mouse setup. Connecting them through an additional USB3-capable Hub prevented the Bit Stuffing errors from occurring.

Details:

Our usbdev logic has no awareness of the PRE special packet. This special PID is not followed by any data bytes, CRC5 or even an End Of Packet; instead the Hub Setup time of **>= 4 Full Speed** bit intervals of **Idle** state ensues, followed by the Low Speed SYNC. This means that either the Idle period or the first Low Speed bit of the SYNC signal causes usbdev to raise a Bit Stuffing error.

Since the bit stuffing error leads to usbdev deciding that the packet has ended, and valid Low Speed data cannot look like a valid SYNC field, the device safely discards the rest of the Low Speed transaction. It's perhaps worth mentioning that usbdev does not see any of the responses from the Low Speed devices; just the downstream-directed Host transmissions within each transaction.

DPI model has been modified to generate this test case, for reproducing the bit stuffing errors in simulation. The top-level test _usbdev_exc_test_ (WIP) now also exercises the propagation of Low Speed SETUP, OUT and IN transactions, switching the bus traffic between Full and Low Speed modes as per real physical hosts.

This diagram captures the real traffic sent from the RPi 4 host controller:
![PRE_Low_cropped](https://github.com/lowRISC/opentitan/assets/117650394/c464e657-7b80-41c0-a9e3-a0d8a7966c98)

For further details see section **8.6.5 Low Speed Transactions** in the USB 2.0 Specification.

**Comment by a-will** [comment]
> For the future, the RTL should probably be modified to handle this case more cleanly.

I don't see how that is possible, not without spending area to create a low-speed receiver. Am I missing something?

If you have a hub that broadcasts low-speed packets, the device is doing its job if it flags it as an invalid packet and drops it:
```
Hubs must comprehend the PRE PID; all other USB devices may ignore it and treat it as undefined
```
On the flip side, the `rx_bitstuff_err` interrupt is merely informative and is not critical to the device's operation. I think what we're finding here is that counting RX signaling errors is only useful in controlled settings.

**Comment by alees24** [comment]
I'm only suggesting that we could preserve the information content/utility of actual Full Speed bit stuffing errors by detecting the presence of the special 'PRE' PID and terminating packet reception then and there. At present we run on and raise the apparent bit stuffing error through trying to decode either the Hub Setup period (Idle state) or the first Low Speed SYNC bit as if it were Full Speed data, before then terminating packet reception (bitstuff_error_q is factored into see_eop).

Once packet reception is terminated, the Low Speed packet is safely ignored by usbdev because no valid LS packet can contain a Full Speed SYNC, and usbdev doesn't generate bit stuffing(/other) errors unless actively trying to decode a packet.

For now, it makes sense to disable the rx_bitstuff_err interrupt, but it does seem it could have some utility in some applications, for detecting unreliable connections/flagging up potential issues. After all, usbdev (as per spec) does a lot of error detection and retrying, without software visibility; the only sign of problems may be decimated data rates?

**Comment by a-will** [comment]
Probably this would do the trick, but I haven't tested it under the new conditions at this point: https://github.com/lowRISC/opentitan/commit/2229ff8acc1293483acbaf1d1b795dde3a91601d

**Comment by johngt** [comment]
@moidx / @msfschaffner for your awareness.
Will only affect OT if there are low speed devices around. Documentation work-around for now. Fix for further iterations as per discussion above.

**Comment by alees24** [comment]
> Probably this would do the trick, but I haven't tested it under the new conditions at this point: [2229ff8](https://github.com/lowRISC/opentitan/commit/2229ff8acc1293483acbaf1d1b795dde3a91601d)
> 
> If we wanted to go further with tracking the packet, we could suspend all responses until we see an EOP (which would have a super long SE0 in this case, since it's a low-speed EOP). At first glance, that doesn't seem necessary, though.

Yes, that's what I had in mind, and as you say there is no need to try to detect EOP. I've re-run the simulation with this change in place and it no longer raises the spurious RxBitstuffErr; plus the other signals look good. It's appropriately deactivating itself as intended until valid Full Speed traffic comes along.

Similarly, a re-spin of the FPGA and connection to the RPi 4 and Low Speed traffic is clear of spurious bitstufferr interrupts. Having checked through the RTL and surrounding logic, I'm happy for you to go ahead and turn this into a PR if you would, please.


The latest FPGA has just cycled in and out of Deep Sleep whilst streaming and resuming Isochronous traffic for the first time. It includes a proposed data toggle save/restore fix that we discussed previously, taking on board the points you made when we discussed that. I need to do a bit more work on the device-side software to reinstate the streaming state from the retention SRAM before this code can be expected to work with non-Iso streams too, but it's looking promising.

**Comment by a-will** [comment]
@alees24 Thanks for testing it! Looking forward to seeing the spiffy deep sleep work :smile:
