### ISSUE TITLE
[rom_ext] ROM_EXT Recovery mode

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#19151]
[OpenTitan ROM_EXT Recovery Mode](https://docs.google.com/document/d/1Ozm4rcA0Z6CrjcntH-aumlkDaei-Q6bbfHTqZgJPO1c/edit#heading=h.8s2awb1r3686)

This issue tracks the implementation of the ROM_EXT Recovery mode, which enables the silicon owner to the parts of flash not occupied by ROM_EXT.

N.B. We are shifting terminology from "ROM_EXT Recovery" to "ROM_EXT Bootstrap".

* https://github.com/lowRISC/opentitan/pull/19133
* #19209
* #18929 
* #19194 
* #19210
* #19312
* TODO: integration tests

**Comment by timothytrippel** [comment]
This is being called "Rescue" now. Additionally, it is being tracked in #19590, #19591, and #19592. So I think we can close this now?

**Comment by arunthomas** [comment]
Yup, makes sense to close
