### ISSUE TITLE
[doc] Link to the section downloads the `.hjson`

### ISSUE THREAD

**Issue by ctopal-rl** [lowRISC/opentitan#19183]
Hey folks,

I noticed this when I was looking into the documentation. Seems like the references on this page downloads the `hjson` instead of pointing me to the book page. Can you have a look please?

https://github.com/lowRISC/opentitan/blob/1f45a46e609ee3eaa8108c6fbc03888a1cf148c2/hw/ip/spi_host/doc/programmers_guide.md?plain=1#L12

Thanks!

**Comment by HU90m** [comment]
Hello there! Thanks for opening an issue for this. It's a problem with the reggen mdBook preprocessor, which we are moving away from in favor of `CMDGEN` (as is used for the AES register tables).

I'll try to get the rest of the blocks moved over pronto, [now that](https://xkcd.com/1319/) I've [implemented](https://github.com/lycheeverse/lychee/pull/1126) anchor checks in the link checker.

**Comment by HU90m** [comment]
There are a few more blocks I need to transition before this is no longer an issue.
