### ISSUE TITLE
[ci] Check status_t Module IDs fails

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/opentitan#19190]
### Description

Ever since this PR was added: https://github.com/lowRISC/opentitan/pull/19062
The CI check named `Check status_t Module IDs` inside the "Quality (in-depth lint)" step is failing.

For example if you take this PR: https://github.com/lowRISC/opentitan/pull/19175
And go into Azure, you can see the following log:
![image](https://github.com/lowRISC/opentitan/assets/34654485/020dcbf4-6737-426c-9428-0c2758caeba5)

**Comment by marnovandermaas** [comment]
Adding @pamaury and @timothytrippel for visibility.

**Comment by nbdd0121** [comment]
I think this is fixed by #19094 but would just need PR rebasing?

**Comment by timothytrippel** [comment]
yeah thats right, can we close this now then?

**Comment by marnovandermaas** [comment]
Great, thanks for the fix!

**Comment by nbdd0121** [comment]
I think this is broken again: https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=121584&view=logs&j=1a082425-b540-5a45-e7d8-d21f721d187f&t=3583c471-2f95-531c-7145-0be3f8c0aecd
