### ISSUE TITLE
[i2c] Need "Read Complete" Interrupt

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#1921]
@mcy has pointed out that there is not really a good way to know when a read is complete in i2c.  The Watermark interrupt is good for long streaming reads, but there doesn't seem to be a way to know then the read is finally done.

**Comment by martin-lueker** [comment]
Just a note on some progress here.  There have been many bug fixes and PRs in i2c this week, and so the code base is rapidly changing.  However Igor and I think we have a plan.

First off, after conversation with @mcy, it seems like this interrupt request has evolved into a "transaction complete" interrupt.   

Secondly a note on proposed hardware implementation.  This event would be triggered every time the I2C FSM started to issue a "STOP" or "RESTART".    The timing is still TBD.  (Question for @mcy: do you care if the interrupt is issued at the beginning or end of the STOP/RESTART?   These signals are pretty slow from a CPU standpoint, but my guess is that as long as all the relevant data has been moved in/out of the FIFO it's all the same. Right?)

**Comment by martin-lueker** [comment]
Finally a note for @igk8: I just double checked the CIP spec, and I want to let you know that I was misremembering the interrupt handling scheme.   All we need to do is create a single event pulse, and the CIP generator will create a rw1c register to hold the state and clear it.   
So no need to do anything except define the interrupt in hjson, and then tie the event to this pulse generator.   Sorry if I caused any confusion.
(https://docs.opentitan.org/doc/rm/comportability_specification/#interrupt-handling)

**Comment by martin-lueker** [comment]
Effort started with #2662

**Comment by igk8** [comment]
Implemented in https://github.com/lowRISC/opentitan/pull/2644

**Comment by igk8** [comment]
@martin-lueker Can this issue be closed now?

**Comment by martin-lueker** [comment]
Oh my.  This has been a long time coming.  Yes.  I think so.

-Martin
