### ISSUE TITLE
RFC: Replace PRNG for random constant generation

### ISSUE THREAD

**Issue by vrozic** [lowRISC/opentitan#19228]
### Description

We propose to replace the random.py module used for generating netlist constants and scrambling keys with a cryptographically secure, AIS31 DRG3 compatible PRNG module.

[RFC document](https://docs.google.com/document/d/13zlkzJiFuYALBGiq9tPWTB5HFxKrmLC4DpwlaVm22PE/edit?usp=sharing)

**Comment by vrozic** [comment]
@johannheyszl @msfschaffner @jadephilipoom @timothytrippel @moidx  for visibility

**Comment by vogelpi** [comment]
Thanks for creating the issue @vrozic . We'll discuss this in this week's Sec WG meeting.

**Comment by msfschaffner** [comment]
This RFC has been approved in the TC today.

**Comment by vrozic** [comment]
The changes were merged in #19079 and the traces of strong_random were removed in #19463 .
i think that this issue can be closed now.
