### ISSUE TITLE
[prim_sync_reqack] Check usage of EnRzHs parameter to make EDN interfaces partial-reset safe

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#19259]
### Description

For Earlgrey ES, most hardware blocks interfacing with EDN are using the default non-return-to-zero (NRZ) handshake protocol in the corresponding prim_sync_reqack modules. This is faster from a peformance point of view but it doesn't allow safely resetting the hardware block without also resetting EDN as there is always a risk of the two sides of the CDC primitive getting out of sync. IIRC, this isn't an issue for the specific reset topology of Earlgrey ES but it might be for other top levels.

We should thus check all hardware blocks interfacing with EDN and decide whether it would better to switch to the slower but partial-reset safe return-to-zero (RZ) handshake protocol.

For details, refer to https://github.com/lowRISC/opentitan/issues/19232#issuecomment-1641854328 . This was also discussed in the Sec WG meeting of Jul 20, 2023.

**Comment by msfschaffner** [comment]
For Earlgrey and Darjeeling, the entropy complex and all entropy-consuming security or crypto devices have the same logical root reset. Or in other words, none of the entropy consumers reside in the AON domain or are SW resettable through `rstmgr`:
https://github.com/lowRISC/opentitan/blob/143098eec598e92bd7dd20939d5c7587f4039705/hw/top_earlgrey/data/top_earlgrey.hjson#L155-L162

Therefore, it is not necessary to use the partial-reset-safe implementation of `prim_sync_reqack` in those cases and no further design changes are needed.
