### ISSUE TITLE
Add sec_mmio audit to manual testplan / final checklist

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#19288]
Yeah, I agree, this should probably a part of our final checklist though. See https://github.com/lowRISC/opentitan/blob/master/sw/device/silicon_creator/rom/data/rom_manual_testplan.hjson and https://github.com/lowRISC/opentitan/blob/master/util/run_manual_tests.py.

_Originally posted by @alphan in https://github.com/lowRISC/opentitan/pull/18719#discussion_r1272338975_

**Comment by msfschaffner** [comment]
CC @mundaym @cfrantz @timothytrippel
