### ISSUE TITLE
Do a snapshot release

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1928]
The current snapshot release is quite outdated. Since timing is never right, we can as well do it right now.

If we do, also update the quickstart to match https://github.com/lowRISC/opentitan/pull/1926

@sjgitty @asb any objections?

**Comment by asb** [comment]
It sounds sensible to me, and should reduce the risk of support burden from people trying the old snapshot. IMO we should ensure messaging is clear (if it's not already) that for many people using current master is likely better, and of course be clear that another snapshot release is No Big Deal.

**Comment by sjgitty** [comment]
Agreed with Alex's recommendation on messaging, and agreeing that now is as
good a time as ever. Might be worth a +1 from @sriyerg from a top-level
cleanliness perspective.

**Comment by moidx** [comment]
Can we promote a successful build?

**Comment by msfschaffner** [comment]
@moidx is this still relevant?

**Comment by msfschaffner** [comment]
Newer snapshots / releases are available (M2.5.x), hence closing.
