### ISSUE TITLE
[ci] Improve module id check reporting

### ISSUE THREAD

**Issue by pamaury** [lowRISC/opentitan#19298]
### Description

The way the module ID check are run make it unecessarily difficult to locate the error since the log is extremely verbose and there is no summary at the end. Find a way to make the ci output more useful. Also the script currently does not remove the temporary directory after running.

- [ ] improve report
- [ ] improve script to delete temporary directory

Tag @timothytrippel

**Comment by timothytrippel** [comment]
I believe this was fixed by #19304. Feel free to reopen if not.
