### ISSUE TITLE
[doc] Selecting items from online documentation may be difficult

### ISSUE THREAD

**Issue by rivos-eblot** [lowRISC/opentitan#19311]
### Description

Using Chrome-based browser, selecting some documentation items is really difficult:
![ot-select](https://github.com/lowRISC/opentitan/assets/115395740/7606cb9b-9663-45bd-bbb6-4b30b53bddb0)

When the cursor is closed to the left margin, the selection gets overridden with the navigation button.
One workaround is to close the left menu, but one has to know this hint...

https://github.com/lowRISC/opentitan/assets/115395740/fd725c7d-b934-48c0-868c-37ddb18a8cf9

**Comment by hcallahan-lowrisc** [comment]
Fixed by #19543
