### ISSUE TITLE
[style] Consistent style for polyglot headers

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#1934]
So, we have a lot of polyglot headers (i.e., headers that are safe to include from both C and C++). Right now we don't really deal with that consistently: either we `extern "C" {}` includes, or, in the case of `mmio.h`, we `extern "C"` the entire header wrapped in `__cplusplus` guards.

Given that polyglot headers can be kinda dicey (esp when there's code in the headers), it might be a good idea to be consistent. I propose two new style rules:
- No `extern "C" {}` allowed around `#includes`.
- Headers which are intended to be included in both `.c` or `.cc` files must be wrapped in `__cplusplus`-guarded `extern "C"` (obviously, this applies to those headers' includes). This makes it clear that the code must be correct when interpreted according to both C and C++ rules.

I expect that the files that will be affected are:
- Freestanding headers.
- Bits of libbase that are safe to include in both languages (memory.h, mmio.h).
- DIF headers.

Thoughts?

**Comment by mcy** [comment]
@gkelly @lenary @silvestrst

**Comment by lenary** [comment]
What would be the issue with doing it the other way around (`extern "C" {}` around includes)? 

I think that is less brittle than `#ifdef __cplusplus extern "C" { #endif … #ifdef __cplusplus } #endif` - especially as I'm keen to avoid as many `#ifdef`s as possible (I think we have two right now, one for host builds, and one for mocks).

It is fair that there are semantic issues between having code in C++ vs C. One of the major ones is `static` locals in `inline` functions, which we should just outright ban in the style guide (we already have a section on inline functions. Are there others you expect could come up?

**Comment by asb** [comment]
I think if it's likely that the same extension is used for both C++ and C headers (meaning it's not easy to tell at a glance if you're including a C or a C++ header and thus tell if you did the right thing with respect to wrapping it with `extern "C"`), the ifdeffed `extern "C"` is probably the straightforward way to go.

**Comment by lenary** [comment]
Ok, that sounds reasonable to me @mcy, I think you can prepare that PR. 

I think it makes sense to also add a rule banning static locals in inline functions, in the same pull request, rather than to only allow them in non-polyglot headers.

**Comment by mcy** [comment]
Is it actually possible to observe the difference in C/C++? The following, for example, is ill-formed in C (and requires a diagnostic):
```
int foo(int a) {
  static int k = a;  // error: initializer element is not a compile-time constant
  return k;
}
```

**Comment by silvestrst** [comment]
> It is fair that there are semantic issues between having code in C++ vs C. One of the major ones is static locals in inline functions, which we should just outright ban in the style guide (we already have a section on inline functions. Are there others you expect could come up?

Might want to mention that should be careful with keywords, like when I ran into the problem of happily having `private` structure member in C, which then wouldn't compile in C++.

**Comment by mcy** [comment]
In the text of my style guide change, I think that's already handled in requiring that C and C++ need to agree on semantics. I think the C compiles but C++ does not is the better failure mode; I'm mostly worried about "both compile but do different things" or "both compiler but fail to link".
