### ISSUE TITLE
[rust] figure out how to deal with serde-derive

### ISSUE THREAD

**Issue by nbdd0121** [lowRISC/opentitan#19362]
### Description

In #19203 it was discovered that serde-derive 1.0.172 starts to use precompiled binary, but the precompiled file is not considered as data file in Rust rules, so Bazel excludes them from sandbox.

There is some ways to fix it:
1. Pin serde-derive to 1.0.171, which is the last version without precompiled binary
2. Patch serde-derive to remove precompiled binary (see serde-rs/serde#2538, there is also a patch in the comments by Fedora people)
3. Add `data_attr` so that the precompiled binary can be used (e.g. https://github.com/google/cargo-raze/blob/afe9b483b0449eb043f3fa8aa08f62afffcfa2ed/impl/Cargo.toml#L138)
4. (?) Wait until a solution is provided by serde-derive to not use precompiled binary?

Personally I don't like the idea of depending on a precompiled binary, so I don't want to pursue (3). For now I opted for (1) in #19203.

**Comment by jwnrt** [comment]
The precompiled binary has been removed in [serde_derive 1.0.184](https://github.com/serde-rs/serde/releases/tag/v1.0.184).
