### ISSUE TITLE
[RFC] SPI_DEVICE Updates for PROD

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#19370]
### Description

[RFC Doc](https://docs.google.com/document/d/1nqgoTFIvnBYCDHBqhc-xiiQyNLvEiBpv06bItm9I5G4/edit)

**Comment by msfschaffner** [comment]
This RFC has been approved by the TC.

**Comment by a-will** [comment]
This is actually an issue that is mostly a task list. The effort in the project will reflect the one task that didn't have its own issue.

- [x] #15452 
- [x] Add option for simplified memory architecture. (Estimate 3 days)
    - Fixed by https://github.com/lowRISC/opentitan/pull/20942
- [ ] https://github.com/lowRISC/opentitan/issues/11718
- [ ] https://github.com/lowRISC/opentitan/issues/16339
    - Remove SPI modes other than 0.
- [ ] https://github.com/lowRISC/opentitan/issues/15785
- [x] https://github.com/lowRISC/opentitan/issues/1212
- [ ] https://github.com/lowRISC/opentitan/issues/12747
- [ ] https://github.com/lowRISC/opentitan/issues/14665
