### ISSUE TITLE
[top_level,tests] Convert sim_dv sysrst_ctrl test to use opentitantool

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#19403]
### Description

Use jtag commands via opentitantool from the host side instead of sim_dv use of backdoor to read and write shared memory locations should allow some sysrst_ctrl sim_dv tests to be ready for bringup. See https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/tests/BUILD;drc=ca4ec8ea9e56df0ab3cc7e6e972244af58a28539;l=2751 and https://cs.opensource.google/opentitan/opentitan/+/master:sw/host/tests/chip/jtag/src/openocd_test.rs for reference.

**Comment by msfschaffner** [comment]
@matutem can this issue be absorbed into a sival test description, or should we keep tracking this separately?

**Comment by matutem** [comment]
- https://github.com/lowRISC/opentitan/issues/19858: The sysrst_combo_reset test is done in https://github.com/lowRISC/opentitan/pull/20180 (approved, but failing on CI for apparently unrelated reasons).
- I added a comment in https://github.com/lowRISC/opentitan/issues/19859
- I think https://github.com/lowRISC/opentitan/issues/19860 is similar to https://github.com/lowRISC/opentitan/issues/19859, but simpler since it doesn't need to know when the external side changed the pins: it is just waiting for interrupt with an aon timer, which if it trips indicates failure. We probably just need to configure the timeout values depending on kDeviceType.
- The sysrst_ctrl wakeup is already tested: https://github.com/lowRISC/opentitan/pull/20059 creates //sw/device/tests:pwrmgr_random_sleep_all_wake_ups_fpga_cw310_test_rom which checks sysrst_ctrl wakeup, among others.

**Comment by matutem** [comment]
I think all these issues are addressed, or are covered by separate issues. Closing this one.
