### ISSUE TITLE
[doc, pinmux] Broken links to pinout tabels in pinmux documentations

### ISSUE THREAD

**Issue by mazurek-michal** [lowRISC/opentitan#19425]
### Description

There are broken links to pinout tables in `Pinmux` documentations: 
[Pinout and Pinmux Mapping](https://opentitan.org/book/hw/ip/pinmux/doc/programmers_guide.html#pinout-and-pinmux-mapping)

broken links:
ASIC: [Pinout Table](https://opentitan.org/book/hw/top_earlgrey/ip/pinmux/doc/autogen/pinout_asic/index.html)
CW310: [Pinout Table](https://opentitan.org/book/hw/top_earlgrey/ip/pinmux/doc/autogen/pinout_cw310/index.html)
CW340: [Pinout Table](https://opentitan.org/book/hw/top_earlgrey/ip/pinmux/doc/autogen/pinout_cw340/index.html)

**Comment by jrvanwhy** [comment]
I believe this is a dupe of #18535 (though #18535 describes a second issue as well).

**Comment by mazurek-michal** [comment]
@jrvanwhy Ticket number that you provide is already merged, and current web page have broken links. 
Can you describe how it is related to current documentation state.

**Comment by jrvanwhy** [comment]
Oops, I meant #18585 .

**Comment by msfschaffner** [comment]
CC @hcallahan-lowrisc @HU90m
