### ISSUE TITLE
[usbdev] Support required for retracting IN packet robustly

### ISSUE THREAD

**Issue by alees24** [lowRISC/opentitan#19435]
### Description

This is a very specific case, although I would contend that support for Isochronous IN traffic could benefit too.

It would be useful if there were a clean and robust way to retract an IN packet from the SW/FW side once it has been presented to usbdev for collection by the host. This relates to section `8.5.3.3 Error Handling on the Last Data Transaction` in the USB 2.0 protocol specification:

- During the Data Stage of a Control Transfer Read, the final IN transaction should be ACKnowledged by the host in the usual manner.
- If the ACK gets lost/corrupted, the normal Data Toggle Synchronization mechanism cannot be employed to ensure that the device/host agree.
- The device is supposed to take the commencement of the Status Stage OUT transaction as evidence that the host has successfully received the final Data Stage transaction, and shall advance automatically.
- usbdev will have retained the IN packet, which the host _has_ already collected. usbdev has no awareness of the packet having been successfully collected.
- SW/FW will need to remove the IN packet manually, because otherwise a subsequent Control Transfer will collect it instead.

With the current implementation, under this very specific case, SW/FW is able to retract the IN packet safely at the point of receiving the OUT transaction of the Status stage since the host shall make no further attempt to collect that IN packet.

SW/FW _must_ retract the IN packet in a 'timely' fashion, however, because the receipt of the Status stage OUT transaction is automatically mediated by hardware, and nothing prevents the commencement of a subsequent Control Transfer. Retraction of an IN packet may be achieved by clearing the `rdy` bit of the `configin` register for the endpoint; in general this is most safely achieved by leaving the other register fields unaltered, in the event that the device is simultaneously transmitting the packet. In this specific case, if the SW/FW is timely in responding, transmission will not occur at the same time as retraction.

Re Isochronous IN traffic, since the priority is always to present the most recent data in the most timely manner, rather than delivering data reliably, there is an argument that usbdev should support replacement of IN packet data for Isochronous endpoints. Note that removal of an IN packet is not generally safe and may result in the transmission of truncated packets, even when the `rdy` field of the `configin` register is the only field modified; for Isochronous traffic this is probably inconsequential because there is no error detection/retrying in normal use, and the recovery of host-side software by other mechanisms is required. It should usually be avoided for non-Isochronous endpoints, however.

**Comment by a-will** [comment]
For control endpoints, would something like clearing the `rdy` upon receipt of a SETUP packet do the trick?

For isochronous endpoints, it's less clear. Maybe the trigger event would be a SW-indicated SOF event, where the frame number is >= the "expiration" value.

**Comment by alees24** [comment]
> For control endpoints, would something like clearing the `rdy` upon receipt of a SETUP packet do the trick?

Investigating a little further, it seems that usbdev does already clear the `rdy` bit when a SETUP packet is received, so SW/FW need only spot that the final packet was never acknowledged and then release the buffer. It must also do this in the event of a link reset, so perhaps this is just an argument for refining the usb_testutils layer on the premise that it serves as example code.
 
> For isochronous endpoints, it's less clear. Maybe the trigger event would be a SW-indicated SOF event, where the frame number is >= the "expiration" value, plus some handling for wrapping the frame number. It seems like that could still end up with unfortunate alignment, though, where the packet is cleared in the same frame that the host would poll... Does our device-side software need to know the last frame number the host polled it for a transaction?

I'm imagining that in general the software dictates when new data is available, without necessarily any awareness of the bus frame timing and when the packets are collected. I was envisaging the IN side packet engine capturing the packet description at the point it receives the IN request, such that changes to `configin` during transmission of the packet cannot cause corruption of the packet, however this is not itself a complete solution to avoiding races.


If we were going to do something more driven by the host/usbdev 'pulling' packets and expecting software to adjust to their timing, I'd suggest a 'Time To Live' bus frame count as part of the configin register could perhaps work - decrement it whenever usbdev starts a new frame (host-signaled or internally 'faked') and clear the `rdy` bit if TTL has reached zero; it then operates in a similar manner to 'bInterval' in the endpoint descriptor.

Such a mechanism could perhaps be built to clear the `rdy` bit when the TTL transitions from 1 to 0, but the mechanism could remain unused in the event of being initially being programmed to zero. It then provides a means for other endpoint types to detect unresponsive host-side software too (ie. don't quality its usage with the 'in_iso' setting; allow it to apply to all endpoints).

> These would be hardware mechanisms, to avoid races with ongoing transmissions.

**Comment by johngt** [comment]
As linked to the issue - draft PR https://github.com/lowRISC/opentitan/pull/21771 should resolve this.
Setting effort spent such that remaining is 0. Leaving this open until the PR is merged in.

**Comment by johngt** [comment]
Issue can be closed as PR https://github.com/lowRISC/opentitan/pull/21771 is merged in now.
If this is not the case please re-open @alees24
