### ISSUE TITLE
[util] sec_mmio audit tool crashes on macro-expanded call sites

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#19438]
I discovered this behavior while working on #19312. That PR will disable the sec_mmio audit step in CI and add a unit test that reproduces this bug/quirk in libclang.

The Python libclang bindings are capable of finding a call site generated by a macro expansion, but when we try to get the spelling of the call site's arguments, we get a sequence of tokens pointing into the original, non-preprocessed source.

Filed bugs upstream:
* https://github.com/sighingnow/libclang/issues/61
* https://github.com/llvm/llvm-project/issues/65112

**Comment by msfschaffner** [comment]
CC @cfrantz @timothytrippel
