### ISSUE TITLE
[util] only use 256 bit seeds

### ISSUE THREAD

**Issue by vrozic** [lowRISC/opentitan#19434]
PR #19079 integrates module `secure_prng` into the project. This PRNG will be used to generate netlist constants and scrambling keys.
At the moment, this PRNG will issue a warning if the provided seed is less than 256 bits. 
Per discussion in [the comments](https://github.com/lowRISC/opentitan/pull/19079#discussion_r1286779196), we should change this warning into an error message.
Before that, we need to modify dvsim and the nightly regressions flow to always work with 256 bit seeds, so that no one's work flow gets broken.

**Comment by msfschaffner** [comment]
Did we change to 256bit seeds already or is this change still pending?

CC @vogelpi

**Comment by vrozic** [comment]
The change is still pending. I will work on it  this week.
It requires some changes on the dvsim to not disturb anyone's workflow.

**Comment by vrozic** [comment]
#20036 will close this issue once merged
