### ISSUE TITLE
[clkmgr] Make `clkmgr` DV top-level agnostic

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#19448]
### Description

When working on Integrated, we've noticed that clkmgr DV is not always top-level agnostic and in some cases is focused on the clkmgr instance of Earlgrey. For example, the top-level specific `clkmgr_bind` is hardcoded rather than being generated from a template. This is not ideal as it doesn't work for other top levels.

**Comment by vogelpi** [comment]
FYI @matutem

**Comment by matutem** [comment]
Thanks @vogelpi, I will address this in the multi-top work, not in the transition to ipgen.

**Comment by andreaskurth** [comment]
Removing from M4; to be addressed in multi-top work
