### ISSUE TITLE
Ibex how to MRET out of an ISR?

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#1945]
On OpenTitan, I have a top level test that generates an external irq to the Ibex twice. The first time, the interrupt gets serviced, but the second time, it doesn't.  

![image](https://user-images.githubusercontent.com/46467186/79076453-144e0580-7caf-11ea-8923-6c41f445e315.png)
 
In the waveform snippet above, on marker M1, I enable the interrupts at Ibex by setting MSTATUS.MIE and MIE.MEIE. 

At the yellow cursor, an interrupt arrives and gets serviced (an overridden `handler_irq_external()` function). Ibex enters the ISR and does some additional processing (which eventually causes another interrupt to fire later). At the end of the ISR, I 'complete' the interrupt at the PLIC and the irq de-asserts. 

At cursor M2, the PLIC fires off another irq to Ibex. However, at this time, the interrupt does not get serviced, because MSTATUS.MIE got de-asserted when the first irq had fired (at the yellow line). 

I read through the Ibex documentation and looks like if an interrupt or an exception occurs, Ibex switches to M-mode and can get out only after executing the MRET instruction (in the ISR). I am not sure what needs to be done here to ensure that my user-defined `handler_irq_external()` function ends with an MRET instruction. I'm sure it is something simple, I'm just not able to figure it out given my admitted lack of RISC-V knowledge. 

If I look at the disassembled code, I do see the MRET at the end of the (default) exception handler `handler_exception()`.

**Comment by sriyerg** [comment]
Here's the disassembled code from this test:

[uart_test_sim_dv.dis.txt](https://github.com/lowRISC/opentitan/files/4468505/uart_test_sim_dv.dis.txt)

**Comment by imphil** [comment]
Have you annotated your ISR with ` __attribute__((interrupt))` as in https://github.com/lowRISC/ibex/blob/5bb41957efe590c1403b81f33f8a13f8499eb4bc/examples/sw/simple_system/common/simple_system_common.c#L185 ?

**Comment by sriyerg** [comment]
That is how it appears to be declared here:
https://github.com/lowRISC/opentitan/blob/160b13be263017e61e4ac30f355bb7eb76934930/sw/device/lib/handler.h#L72

**Comment by sriyerg** [comment]
Found the issue! I forgot to #include `handler.h`. It is working now.
