### ISSUE TITLE
[manuf] Earlgrey ES CP provisioning binary and test harness for generic SKU

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#19453]
A provisioning device binary and host test harness need to be written to run in CP for provisioning Earlgrey ES chips for the generic OpenTitan SKU. The details / requirements for both are listed below:

### Device Binary

The device binary should:
- [x] be loadable into SRAM
- [x] make use of existing manuf libraries in `sw/device/silicon_creator/manuf/lib/`
- [x] check the LC state is TEST_UNLOCKED0
- [x] signal to the host it is ready to receive the provisioning data payload (preferably via a GPIO pin)
- [x] wait for the host to send the data payload over the console consisting of:
    - [x] device_id
    - [x] manuf_state
    - [x] wafer_auth_secret
    - [x] test_unlock_token
    - [x] test_exit_token
- [x] Provision the above data payload in to the device by:
    - [x] writing the following to flash info pages:
        - [x] device_id
        - [x] manuf_state
        - [x] wafer_auth_secret
    - [x] writing the following to OTP secret0 partition
        - [x] test_exit_token
        - [x] test_unlock_token
- [x] lock the OTP secret0 partition and issue a SW reset to activate it

### Host Harness
The host test harness should:
- [x] facilitate loading and running the above provisioning program manually
    - [x] with switches to select which parts get run/skipped
    - [x] with flags to send in provisioning data on cmd line
- [x] transition LC state from RAW to TEST_UNLOCKED0 over JTAG
- [x] wait for device to be ready to receive the provisioning data payload
- [x] drive the provisioning data payload (described above) into the device over the console (via ujson framework)
- [x] wait success/failure indication from the device
- [x] transition to TEST_LOCKED0 over JTAG

**Comment by moidx** [comment]
Adding to the SiVal project as well since many of the manufacturing test points covered in this issue will be part of the bring-up test plan (SV1). 

We should discuss to see if there is any value in allowing the host tool to support an interactive mode to allow the test engineer to select selective manufacturing steps, versus running all of them for a given stage (cp vs ft).

**Comment by timothytrippel** [comment]
> We should discuss to see if there is any value in allowing the host tool to support an interactive mode to allow the test engineer to select selective manufacturing steps, versus running all of them for a given stage (cp vs ft).

@moidx : https://github.com/lowRISC/opentitan/pull/19572 should implement this
