### ISSUE TITLE
[sw] mmio_region_set_bit32 requires readable registers.

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#1946]
Right now we don't really have a good way of setting a single bit on a write-only, W1C register; it may be a good idea to add such a variant?

I ran into this not being available in my SPI DIF, at any rate.

**Comment by sriyerg** [comment]
How about:
```c
  mmio_region_write32(base_addr, offset, 1 << bit);
```

**Comment by silvestrst** [comment]
> How about:
`mmio_region_write32(base_addr, offset, 1 << bit);`

**Comment by gkelly** [comment]
> > How about:
> > `mmio_region_write32(base_addr, offset, 1 << bit);`
> 
> I think as we have dedicated library for MMIO operations, we might as well add a function there - will be more verbose than using `mmio_region_write32`. It is a good option though, thank you @sriyerg .

I agree. It also makes the semantics of expectations easier to read.
