### ISSUE TITLE
[hyperdebug] connect JTAG OT pins to JTAG headers on CW310

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#19472]
### Description

For provisioning binary and SiVal preparation, we want to use the hyper310 setup, but still make use of the Olimex JTAG adapter for JTAG transactions. Currently the OT JTAG pins on the hyperdebug pinout are routed to the USERIOA bank, and not to the CW310 JTAG headers (as is the case for the CW310 FPGA pin config).

**Comment by timothytrippel** [comment]
Closing, see https://github.com/lowRISC/opentitan/pull/19473#issuecomment-1714683246

**Comment by a-will** [comment]
Changing to not planned, since we did not go through with it.
