### ISSUE TITLE
[tlgen.py] ERROR: get_s1n_if_exist hits DEVICE type (unexpected) for node: flash_ctrl

### ISSUE THREAD

**Issue by yikim2256** [lowRISC/opentitan#19500]
### Description

connections: {
    ibex_corei: ["flash_ctrl"],
    ibex_cored: ["sram_ctrl", "flash_ctrl", "adc_ctrl", "dac_ctrl", "i2c_slv"],
    i2c_mas: ["sram_ctrl", "flash_ctrl", "adc_ctrl", "dac_ctrl", "i2c_slv"]
  },

ERROR: get_s1n_if_exist hits DEVICE type (unexpected)

If only one device in the connections, the aforementioned ERROR occurs.

**Comment by msfschaffner** [comment]
This is a duplicate and is already tracked here #2337. 
We will likely be able to fix this soon.
