### ISSUE TITLE
[component] [rtl]  synthesis comb loop 

### ISSUE THREAD

**Issue by shanshuixiangyi** [lowRISC/opentitan#19522]
### Description

Hello, I mets some problem,please help me.
synthesis comb loop 
```
prim max tree file 
   sel = (~vld_tree[C0] & vld_tree[C1]) |
                (vld_tree[C0] & vld_tree[C1] & logic'(max_tree[C1] > max_tree[C0]));

                vld_tree[Pa] = (sel) ? vld_tree[C1] : vld_tree[C0];
                idx_tree[Pa] = (sel) ? idx_tree[C1] : idx_tree[C0];
                max_tree[Pa] = (sel) ? max_tree[C1] : max_tree[C0];

```

**Comment by msfschaffner** [comment]
Hi @shanshuixiangyi - we would need some more information about the steps you were taking, which tool you ran (plus an error message) to root cause this.

**Comment by rswarbrick** [comment]
I don't think we know enough to make progress with this reported issue. Please reopen if you have more information.
