### ISSUE TITLE
[topgen] Feature: inter-module signal connects to a net/struct in top-level not float.

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#1952]
Let inter-module signal to connect to a net/struct in top-level. If `act` is requester, assign the signal to net, if not, assign net to the inter-module signal. It makes power manager, reset manager to connect the broadcast signal easily while connecting to the fabric is done by the tool.

CC: @tjaychen

**Comment by eunchan** [comment]
Addressed in #1997

**Comment by tjaychen** [comment]
thanks @eunchan!

**Comment by eunchan** [comment]
Supported now.
