### ISSUE TITLE
[reggen] Ordering required between regwen and reg

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#1953]
This is pretty low priority, but I did encounter the issue, so I figure I may as well flag it.

Right now if a regwen register is defined as `hwext=true`, the dv ral_gen flow bombs out. Since it's an external register, the base class isn't generated, however, registers it locks still attempt to reference it, causing a null pointer issue. 

It's not a big issue because it's trivial to convert this to a register inside the regfile and appropriately set de/d.  Still I figure I would point it out in case other people do this.  Maybe we can just explicitly error out on hwext when it comes to regwen.

**Comment by tjaychen** [comment]
so my previous description of the issue was completely wrong. 
Turns out the actual issue it seems is that the in hjson, the regwen needs to be declared ahead of the register it protects. 

Maybe this is known already, if so, let me know, and i'll close the issue.

**Comment by sriyerg** [comment]
Thanks for pointing out. 
So just need to move the regwen declaration in the Hjson to the top?

**Comment by tjaychen** [comment]
yeah basically. This came up because Scott pointed out `CTRL` registers should be the first. I just so happened to have a hw managed lock register that managed the `CTRL`, so I mistakenly thought the issue was the hwext.

**Comment by sjgitty** [comment]
interesting, that seems fixable and should be fixed. but not the end of the
world if the order gets a little funny as a workaround until then.

**Comment by tjaychen** [comment]
should i just document this in the regtool spec and close this issue? There's no real reason we have to fix this right?

**Comment by sjgitty** [comment]
In the interest of making decisions and moving on, I agree let's spec it and close. I'll suggest a quick change for this one, thanks @tjaychen
