### ISSUE TITLE
[opentitantool] HyperDebug: "Failed to enter rescue mode"

### ISSUE THREAD

**Issue by jesultra** [lowRISC/opentitan#19564]
### Description

Occasionally, "opentitantool bootstrap --protocol rescue" will show repeated errors like this: Resetting... Failed to enter rescue mode, when attempting to flash legacy Google Titan-class chips.

Typically, once this manifests, it is persistent, until something brings the system out of this state.  Opening an opentitantool console is often enough, so is "transport init" or pushing the black reset button on HyperDebug.

Crucially, power cycling HyperDebug (and the Titan shield) by un-plugging and re-plugging the USB-C cable to HyperDebug, will consistently trigger the situation.

Looking closer, I have observed that if I power cycle HyperDebug, while holding the Titan-class chip under reset with a wire jumper to CN10_29, and then release Titan a few seconds later, and then run "make console", then I will immediately see some boot output (truncated since HyperDebug could not buffer everything that Titan produced).

However, if I instead power cycle HyperDebug, while letting Titan run immediately, and then run "make console", then I do not see any boot message immediately, but upon hitting enter, I will see the boot output like before, followed by a prompt character in response to the input.

So it seems to me, that HyperDebug (really the EC codebase) can get into a state where it buffers UART data, and only wakes up and start propagating it to USB in response to USB character activity (merely establishing a USB connection is not enough.)

Thinking back, I may have seen similar things working with ChromeOS uServo (which uses same EC codebase as HyperDebug), though when used manually, it is not usually a problem, as you would hit enter to see that the AP, EC, or GSC is responding anyway, and getting some previous recorded output or not is not a big deal.

So as the rescue protocol works by opentitantool pulsing the reset pin, and then waiting to see a Titan boot message before sending the "r" key, it seems that when in this state, opentitantool will never see any output, and never attempt to send an "r".

It seems that I could either investigate what goes on the the EC codebase.  But I think that I am going to instead put a workaround in opentitantool.  Simply sending any character before expecting the boot output would get HyperDebug EC USB code out of the bad state.

This was originally reported on Google's internal bug tracker as b/298075416.

**Comment by msfschaffner** [comment]
CC @cfrantz @moidx @timothytrippel

**Comment by timothytrippel** [comment]
Is this still an issue @jesultra ?

**Comment by jesultra** [comment]
HyperDebug firmware still has the issue that it will occasionally (after HyperDebug reboot) be in a state in which it does not forward any UART data to USB, until at least one character has been sent via USB to be output on the HyperDebug UART in question.

The above PR #19546 works around the issue in relation to the Google Titan "serial rescue" protocol.  And in other test cases, we make sure to send a single character before we drain buffers for stale data (which we would do anyway), meaning that we (Google) do not need any further action here.  I am OK with closing this issue.
