### ISSUE TITLE
[top_earlgrey,tests] Fix clkmgr_external_clk_src_for_sw_slow_test_fpga_cw310_test_rom

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#19620]
### Description

This test is failing on the cw310 fpga: only the main clk gets a measurement error, all others clocks are okay. The ..._for_sw_fast_..." test works okay.

**Comment by matutem** [comment]
It turns out the measurements of main in slow speed correspond to the expected values for fast. This means the main clk seems to be running at 96 MHz rather than the expected 48 MHz. In sim_dv main runs at the expected 48 MHz. Seems like an FPGA bug, since in silicon the external clock is used for calibration, and that flow works.

**Comment by a-will** [comment]
The FPGA doesn't support a physical external clock, nor having the main clock at a lower frequency. I think we can close this and accept that the test is not supported on FPGA, then. Throwing in an alternate clock and muxing it out would consume already very impacted clocking resources on the CW310.
