### ISSUE TITLE
About the use case of security key

### ISSUE THREAD

**Issue by bling206** [lowRISC/opentitan#1964]
I see the security use case(U2F) in the page https://docs.opentitan.org/doc/security/use_cases/.
Is there any open source code for this use case with OpenTitan?

Thank you.

**Comment by moidx** [comment]
Hi @bling206, not at the moment. We are currently working on the hw and lower firmware layers. We don't have a timeline yet on any reference code.

**Comment by moidx** [comment]
Please feel free to open if you have any other questions related to this issue. Thanks!
