### ISSUE TITLE
[edn] Should SW commands be allowed in boot_req_mode

### ISSUE THREAD

**Issue by h-filali** [lowRISC/opentitan#19655]
### Description

In the documentation it says :

> In boot-time request mode, the command sequence is fully hardware-controlled and no command customization is possible. In this mode, the EDN automatically issues a special reduced-latency instantiate command followed by the default generate commands. This means, for instance, that no personalization strings or additional data may be passed to the CSRNG application interface port in this mode. On exiting, the EDN issues an uninstantiate command to destroy the associated CSRNG instance.

However, in the RTL I couldn't find anything that keeps SW commands from being issued in boot_req_mode. I also observed SW commands in the tests while CTRL.BOOT_REQ_MODE was set to true. 

Looking at the RTL code I think it is possible that sw commands can be issued in boot mode. It just relies on the SM not being in any of the following states: AutoSendGenCmd, AutoSendReseedCmd, AutoAckWait, AutoDispatch, AutoCaptGenCnt, AutoCaptReseedCnt, BootSendGenCmd or BootLoadIns. Other than in those states, a sw command can be issued if (reg2hw.sw_cmd_req.qe & sw_cmd_valid) is equal to 1’b1. [This](https://github.com/lowRISC/opentitan/pull/17083/commits/793f168b1e18a00c6f2ce63389668af64b7b0981) commit also aligns with the stated above.

If we decide to change the RTL, [this](https://github.com/lowRISC/opentitan/pull/17083/commits/793f168b1e18a00c6f2ce63389668af64b7b0981) commit could be extended to exclude more states. But in my opinion a cleaner solution could be to add a signal in the main_sm, that is high whenever the sm is in the AutoLoadIns or the SW_Port_Mode state. This way we could disallow sw commands unless the above signal is high.

If we decide to keep things as they are we may consider to adapt the documentation.

Another thing to consider is that the SM is in the BootDone state when the boot sequence is done. It stays there until the EDN is disabled or an error occurs. We could also discuss adding a transition from BootDone to Idle when the CTRL.BOOT_REQ_MODE flag is disabled. This might make the RTL align more with the quote from the documentation below, since atm disabling CTRL.BOOT_REQ_MODE doesn't cause the SM to leave the BootDone state. To my observation, there is also no uninstatiate command being issued when exiting boot mode.

> Once firmware initialization is complete, it is important to exit this mode if the endpoints ever need FIPS-approved random values. This is done by either clearing the EDN_ENABLE field or clearing the BOOT_REQ_MODE field in [CTRL](https://opentitan.org/book/hw/ip/edn/doc/registers.html#ctrl) to halt the boot-time request state machine. Firmware must then wait for successful the shutdown of the state machine by polling the REQ_MODE_SM_STS field of the [SUM_STS](https://opentitan.org/book/hw/ip/edn/doc/registers.html#sum_sts) register.

FYI: @vogelpi @andreaskurth

**Comment by vogelpi** [comment]
Thanks for flagging this @h-filali . In my view:

1. We should change the RTL to not allow SW commands in boot-time mode. Your proposed fix to only enable these commands in certain states / instead of disabling in all others sounds good to me.
2. We should change the RTL to leave BootDone upon disabling boot mode and send an uninstantiate command as documented. Caveat: it will be hard to verify this because DV will need to consume all entropy provided in boot mode (will take time).

I am adding the bug label because these are both RTL bugs. The design does not match the specification.

In terms of scheduling, I suggest to first look a the remaining DV tasks we have defined before doing these RTL changes. If in the meantime we get some more test failures that's probably okay.

**Comment by h-filali** [comment]
Thanks @vogelpi for your response. I agree, I'll first look at the remaining DV tasks.
