### ISSUE TITLE
[dv, chip, rom e2e]: Unable to run ROM E2E test with the base OTP image in Prod lifecycle state 

### ISSUE THREAD

**Issue by walaahattab** [lowRISC/opentitan#19708]
### Description

Upon running "rom_e2e_smoke" test with the base OTP image in the Prod LC state. Then, the Booter fails at some stage and calls “shutdown_finalize”.

The cause of this call is an error that occurred during rom_try_boot():
https://github.com/lowRISC/opentitan/blob/709d4e7ca0575e7016b3a09bffea9b1028cb4c81/sw/device/silicon_creator/rom/rom.c#L568-L570

Test: rom_e2e_smoke with "+use_otp_image=OtpTypeLcStProd" plusarg, run over OT earlgrey_es branch.

**Comment by walaahattab** [comment]
CC: @sha-ron

**Comment by timothytrippel** [comment]
Yes that is expected as an that "+use_otp_image=OtpTypeLcStProd" plusarg uses an empty OTP image with just the LC state set to PROD (IIRC), and the ROM requires some OTP fields to be provisioned correctly in order to boot successfully.

To fix this, you can use the "+use_otp_image=OtpTypeCustom" plusarg, and then add the string "//hw/ip/otp_ctrl/data:img_prod:4" to the list of "sw_images" in the dvsim config file. This will tell dvsim to use a Bazel-built OTP image that has the proper OTP fields configured in the `CREATOR_SW_CFG` and `OWNER_SW_CFG` partitions that are required for the ROM to boot the chip.

**Comment by walaahattab** [comment]
> Yes that is expected as an that "+use_otp_image=OtpTypeLcStProd" plusarg uses an empty OTP image with just the LC state set to PROD (IIRC), and the ROM requires some OTP fields to be provisioned correctly in order to boot successfully.
> 
> To fix this, you can use the "+use_otp_image=OtpTypeCustom" plusarg, and then add the string "//hw/ip/otp_ctrl/data:img_prod:4" to the list of "sw_images" in the dvsim config file. This will tell dvsim to use a Bazel-built OTP image that has the proper OTP fields configured in the `CREATOR_SW_CFG` and `OWNER_SW_CFG` partitions that are required for the ROM to boot the chip.

Hi @timothytrippel, this does not work (same issue). Are there any other configurations that should I consider?

**Comment by walaahattab** [comment]
@timothytrippel, it appears that "//hw/ip/otp_ctrl/data:img_prod:" does not contain the necessary OTP fields required for provisioning during the boot process. Could you please check and advice?

**Comment by timothytrippel** [comment]
@walaahattab sorry for just getting back to you; I think I see the other issue. In addition to changing the OTP image as you have done, this [line](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/dv/chip_rom_tests.hjson;drc=6fa3697362823dcb40ef7d43e047fc7775480730;l=14) which currently is
```
sw_images: ["//sw/device/silicon_creator/rom/e2e:empty_test_slot_a:1:ot_flash_binary:signed:fake_rsa_test_key_0"]
```
should be
```
sw_images: ["//sw/device/silicon_creator/rom/e2e:empty_test_slot_a:1:ot_flash_binary:signed:fake_rsa_prod_key_0"]
```

If you want to run in prod LC state, you need to use a flash image that has been signed with a PROD key. Flash images signed with test keys will not boot in the prod LC state.

**Comment by msfschaffner** [comment]
So this issue confirms that our signature verification actually works ;).

**Comment by walaahattab** [comment]
Thank you @timothytrippel, the issue has been resolved with your fix, which involves using the custom PROD OTP image and a signed flash image with a PROD key to ensure a successful boot in the PROD LC state.
