### ISSUE TITLE
[DV] flash_test failing extract_sw_log

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#1974]
Just wanted to file before I forget.

It seems like flash test is now failing the extract step because it does not have the appropriate sections.  As far as I can tell, all I need to do is make the appropriate dependencies in meson, and just make some kind of LOG call inside the test, is that right? I'm guessing this would apply to other tests also?

**Comment by tjaychen** [comment]
i can make the fix for flash (unless you're already doing it), but just wanted to make sure what the right steps are.

**Comment by sriyerg** [comment]
I will take care of it. THanks!
