### ISSUE TITLE
[rv_dm,rtl] Potential issue with hartsel WARL behaviour

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#19750]
### Description

 The debug spec states:

> While the spec allows for 20 hartsel bits, an implementation may choose to implement fewer than that. The actual width of hartsel is called HARTSELLEN. It must be at least 0 and at most 20. A debugger should discover HARTSELLEN by writing all ones to hartsel (assuming the maximum size) and reading back the value to see which bits were actually set.

The rv_dm implementation implements the full 20 bits and doesn't appear to limit the number you can write based upon the number of harts available. For OpenTitan with a single hart I believe this field should act as a read-only field with a constant value of 0. Instead you can write any 20 bit number there and then read it back, any number other than 0 will select a non-existent hart. 

The above is based on RTL inspection rather than testing the behaviour so I may be missing something. I am uncertain what the consequences of using rv_dm functionality against a non-existent hart is.

This is not high priority but could cause issues with certain tools that are doing some kind of autoprobe to determine what harts are available. It should be a simple fix so likely worth doing for prod.

**Comment by msfschaffner** [comment]
CC @andreaskurth @a-will 

This may be an easy fix.
