### ISSUE TITLE
[DV] Continue support make-flow?

### ISSUE THREAD

**Issue by tunghoang290780** [lowRISC/opentitan#1975]
@sriyerg @weicaiyang 
Is the make-flow (in ip/dv area) still supported or we completely move to dvsim.py script

After I rebase from the upstream master, fusesoc showed bellow error when running make command in ip/dv area for simulation. 
![image](https://user-images.githubusercontent.com/53881329/79422746-4642be80-7f72-11ea-9552-1eb3722b9b6a.png)

I check hw/dv/tool and found that all kinds of stuff for RAL (i.e. ral_gen.mk, gen_ral_pkg.py etc.) have been removed from the upstream master thus fusesoc could not found ral_pkg files. Is it intentional to remove ral?

**Comment by sriyerg** [comment]
Prefer to switch to using dvsim exclusively which is a lot more feature packed compared to the old make flow. You can run full regressions with it. It has full support for Xcelium with coverage. Unfortunately, we do not have the bandwidth to support both flows. We plan to remove the make flow completely eventually, unless someone strongly objects to it.

**Comment by rasmus-madsen** [comment]
not sure there is any reason to keep the old make flow around.

**Comment by tunghoang290780** [comment]
Agreed, it'd better switch to the new flow.
