### ISSUE TITLE
[util, reggen] Autogenerate register reset values

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#1977]
In many peripherals, we hardcode the register reset values such as:
#`define PINMUX_OUTSEL_RESET_DEFAULT 0x20820820`
These could be auto generated, however there are some difficulties:

- I think the corresponding `*.hjson` files define reset value son per field basis, which then probably would have to be accumulated into a single 32bit value (If I remember it correctly).
- It would be required to differentiate between `w1c`, `r` and `rw` type of registers when generating the defines, as default reset values as they are not always applicable for reset operations.

It would be nice to have these values autogenerated, but the question is - do you think it is worth, giving potentially non trivial implementation?

**Comment by silvestrst** [comment]
@gkelly @lenary 

I think it's not worth it, but decided to get a second opinion anyway.

**Comment by lenary** [comment]
It sounds doable, and I think we might want to get to a place where we can do this at some point in the future, because if this is a hardware-register-specific value, we should be generating it from the register definitions file.

I do agree that now is perhaps not the right moment for autogenerating it, though. Let's leave this issue open, but not prioritise this work yet.

**Comment by silvestrst** [comment]
> It would be nice to have these values autogenerated, but the question is - do you think it is worth, giving potentially non trivial implementation?

Answering my own question, I think it would be useful. We already have taken approach to check whether DIFs use up-to-date values with the help of `_Static_assert`, like bellow:
```
...
_Static_assert(PINMUX_PERIPH_INSEL_MULTIREG_COUNT == 7,
               "Pinmux instantiation parameters have changed.");
...
```

The thing to remember is this:
> It would be required to differentiate between w1c, r and rw type of registers when generating the defines, as default reset values as they are not always applicable for reset operations.

**Comment by rswarbrick** [comment]
This should be pretty straightforward to support with the current version of reggen. I don't quite understand your second point (about `w1c`, `r` and `rw` registers). The SW access scheme won't make any difference to the reset value itself.

Do you actually want something like "the value to write to the register to set it back to default"? (if so, I'm not sure that's guaranteed to exist).

**Comment by silvestrst** [comment]
@rswarbrick thank you for the change!

> Do you actually want something like "the value to write to the register to set it back to default"? (if so, I'm not sure that's guaranteed to exist).

I think that's what I initially meant, however it was a while ago so I don't remember the exact context.

> if so, I'm not sure that's guaranteed to exist

I agree, I think this change is potentially useful regardless
