### ISSUE TITLE
[manuf] determine *_SW_CFG OTP partition values for Earlgrey ES samples

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#19814]
For Earlgrey ES sample preparation we need to determine the value we want to write to the OTP {CREATOR,OWNER})_SW_CFG partitions.

**Comment by moidx** [comment]
Marking as completed as we now have the following SKU configurations. Any additional OTP  testing on specific features should be tracked separately. 

- `sival_bringup`
- `prodc`
