### ISSUE TITLE
[chip-test] chip_sw_uart_tx_rx

### ISSUE THREAD

**Issue by crteja** [lowRISC/opentitan#19864]
### Test point name

chip_sw_uart_tx_rx

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [X] Hyperdebug + CW310

### Contact person

@rswarbrick

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression
> estimate 3

**Comment by jwnrt** [comment]
It's assigned [here](https://github.com/lowRISC/opentitan/blob/d74d7d29ae7c6e90ca93d21324a8c96913a2770f/hw/top_earlgrey/data/ip/chip_uart_testplan.hjson#L24). Does it need to be in the sival branch too?
