### ISSUE TITLE
[chip-test] chip_sw_uart_rand_baudrate

### ISSUE THREAD

**Issue by crteja** [lowRISC/opentitan#19868]
### Test point name

chip_sw_uart_rand_baudrate

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [X] Hyperdebug + CW310

### Contact person

@rswarbrick

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [ ] Host-side component developed
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 3

**Comment by jwnrt** [comment]
Reopening until https://github.com/lowRISC/opentitan/pull/21513 updates the test plan
