### ISSUE TITLE
[build system] Produce 64 bit-packed VMEM file for SW builds

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1986]
We need a new build artifact for all software which should end up in flash: a VMEM file which packs two 32 bit words next to each other in a 64 bit word.

The relevant code is at https://github.com/lowRISC/opentitan/blob/master/util/embedded_target.py#L44

Note we still need the 32 bit VMEM file, so it would probably be best to unconditionally produce both files next to each other.

If the file name of the file changes docs need to be adjusted as well.

See https://github.com/lowRISC/opentitan/issues/1941 for more context.

**Comment by tjaychen** [comment]
@mcy 
@gkelly

**Comment by GregAC** [comment]
I was going to pick this up, hope to get it done today.

**Comment by tjaychen** [comment]
thanks greg!
