### ISSUE TITLE
[chip-test] chip_sw_uart_rx_overflow

### ISSUE THREAD

**Issue by crteja** [lowRISC/opentitan#19872]
### Test point name

chip_sw_uart_rx_overflow

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [X] Hyperdebug + CW310

### Contact person

crteja

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 2

**Comment by johngt** [comment]
Needs the Bazel test point merged in the testplan. @jwnrt

**Comment by jwnrt** [comment]
Assigned [here](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_uart_testplan.hjson#L41)
