### ISSUE TITLE
[chip-test] chip_sw_uart_noise_filter

### ISSUE THREAD

**Issue by crteja** [lowRISC/opentitan#19870]
### Test point name

chip_sw_uart_noise_filter

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [X] Hyperdebug + CW310

### Contact person

crteja

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard) https://github.com/lowRISC/opentitan/pull/19752
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 2

**Comment by rswarbrick** [comment]
Closing this because it's no longer explicitly in the testplan.
