### ISSUE TITLE
[chip-test] chip_sw_uart_watermarks

### ISSUE THREAD

**Issue by crteja** [lowRISC/opentitan#19871]
### Test point name

chip_sw_uart_watermarks

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [ ] Hyperdebug + CW310

### Contact person

@rswarbrick

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 2

**Comment by johngt** [comment]
Needs the Bazel test point merged in the testplan. @jwnrt
