### ISSUE TITLE
[chip-level,si-val] chip_sw_sleep_sram_ret_contents

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#19892]
### Test point name

chip_sw_sleep_sram_ret_contents

### Host side component

None

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [ ] Hyperdebug + CW310

### Contact person

@rswarbrick

### Checklist

- [ ] Check if existing `sram_ctrl_sleep_sram_ret_contents.c` will handle this on the device side.
- [ ] Develop host-side component. This will need to cause the chip to enter/exit low power mode.
- [ ] Add test name to hjson test plan so that it shows up on dashboard.
- [ ] Get test running on relevant FPGA / silicon regression.

> estimate 5

**Comment by jwnrt** [comment]
This was completed in https://github.com/lowRISC/opentitan/pull/20588.

The sleeping is triggered on the device, so no test harness needed.
