### ISSUE TITLE
[chip-test] chip_sw_gpio

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#19891]
### Test point name

[chip_sw_gpio_out](https://github.com/lowRISC/opentitan/blob/7a9b8d6df255f2917aa4646951c0548c31625945/hw/top_earlgrey/data/ip/chip_gpio_testplan.hjson#L5)
[chip_sw_gpio_in](https://github.com/lowRISC/opentitan/blob/7a9b8d6df255f2917aa4646951c0548c31625945/hw/top_earlgrey/data/ip/chip_gpio_testplan.hjson#L21)
[chip_sw_gpio_irq](https://github.com/lowRISC/opentitan/blob/7a9b8d6df255f2917aa4646951c0548c31625945/hw/top_earlgrey/data/ip/chip_gpio_testplan.hjson#L33)
### Host side component

Unknown

### OpenTitanTool infrastructure implemented

Unknown

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [ ] Hyperdebug + CW310

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [x] For SiVal test cases, test is running relevant FPGA or silicon regression

**Comment by engdoreis** [comment]
Moving to SV2 based on https://github.com/lowRISC/opentitan/pull/20322

**Comment by jdonjdon** [comment]
> Moving to SV2 based on #20322

ack
