### ISSUE TITLE
[chip-test,si-val] chip_sw_rom_access

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#19939]
### Test point name

chip_sw_rom_access

### Host side component

None

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes (maybe: see notes below!)

### Emulation Targets

- [ ] None
- [ ] CW310
- [ ] Hyperdebug + CW310

### Contact person

@rswarbrick

### Checklist

- [ ] Think through the existing `chip_sw_rom_access` testpoint. Does it make sense at all? I suspect that we either need to move it to SV1 (priority! nothing's going to work if this is dead!) or that we should remove it from SiVal testing. My guess (@rswarbrick) is the latter. Either way, tweak the testplan to fix `si_stage` from this test.
- [ ] If there *is* anything to do for SiVal, tweak/write a device-side component that verifies this sensibly. 
- [ ] In this case, wire the test up in hjson test plan so that it shows up in the dashboard.
- [ ] Also in this case, get the test running in relevant FPGA or silicon regression

> estimate 2

**Comment by engdoreis** [comment]
The linked test `chip_sw_rom_ctrl_integrity_check` can't be ported to run with ujson frontdoor write because the vseq is backdoor writing to the rom.
So, I thought through the test description and I came to the conclusion that the only way to check if the CPU can fetch instructions from the ROM in silicon is by trying to run rom. Therefore, should we remove this test from sival?
@luismarques @rswarbrick

**Comment by jwnrt** [comment]
This is meant to be one of the smokiest of smoketests (i.e. we'll know from other tests failing that ROM execution doesn't work, this smoketest needs to be very very basic to demonstrate it's the ROM's fault and nothing else).

I think the closest we'll get to that is writing a pure JTAG test in the OpenTitanLib test harness which checks ibex is executing the ROM and can read ROM data.

That test will depend on the JTAG working, so maybe we should have a second test that runs from software and just tries to read the ROM contents from the memory map. That test will depend on many more components (everything the ROM touches like OTP, entropy, UART, etc) but not the JTAG.

**Comment by engdoreis** [comment]
I considered a test that would run from the SRAM and would attempt to read the ROM, but that doesn't check whether “The CPU can fetch instructions from the ROM” I believe.

**Comment by jwnrt** [comment]
That's true, I think only the JTAG test can check that. The ROM-reading test would be a fallback to at least cover half of the test point if JTAG fails.

**Comment by engdoreis** [comment]
I filed a PR linking a test that checks via JTAG that the ROM is correctly running.
