### ISSUE TITLE
IP AES aes_cipher_core 

### ISSUE THREAD

**Issue by houdonghui1** [lowRISC/opentitan#19955]
Hello everyone, due to work needs, I need to make changes to the AES IP, but I am not familiar with the interface of the 'AES_cipher_core' module. They look quite complex, how can I understand the role of the interface signals of this module? Where can I get its introduction?
https://opentitan.org/book/hw/ip/aes/doc/theory_of_operation.html#block-diagram

**Comment by rswarbrick** [comment]
Hi there. I don't believe that we have anything more introductory than the document you linked to. If you have specific technical questions, please feel free to open extra "question issues": it might be that there's something we could be explaining better and can improve.

I'm going to close this issue as "dealt with": I think we'll probably be more help by responding to future issues that you open if/when you find stuff that's confusing. Good luck!
