### ISSUE TITLE
Double-check toolchain build flags

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#20]
Here's what we currently document: https://bubble.servers.lowrisc.org/doc/ug/getting_started_sw.html

- Is medany the right code model?
- It should be imc, we currently propose ic. This needs to be changed.

**Comment by lenary** [comment]
In the move to our own toolchain, we chose the arguments `-march=rv32imc -mabi=ilp32 -mcmodel=medany`, which is the same that we recommend to people bringing their own toolchain: https://docs.opentitan.org/doc/ug/install_instructions/#option-2-compile-your-own-gcc-toolchain

- `-march=rv32imc` is correct for ibex.
- `-mabi=ilp32` is the only compatible ABI for this platform
- `-mcmodel=medany` seems the right choice for the moment. This allows programs to be located in any 2GB segment of memory. We may move to `-mcmodel=medlow` which requires programs to be located in the low 2GB of memory, but it would only help if we really want to avoid `auipc` instructions.

**Comment by asb** [comment]
Thanks for updating on this Sam. I propose we mark this issue closed.

**Comment by lenary** [comment]
Yeah, I think we can close this. We'll open a new issue if we choose to move to `medlow`, or once we enable the bit manipulation instructions :)
