### ISSUE TITLE
[bazel] Remove cc_side_outputs

### ISSUE THREAD

**Issue by cfrantz** [lowRISC/opentitan#20002]
When we first added bazel support, we added `//rules/cc_side_outputs.bzl` to generate various compiler outputs that we thought would be of interest: preprocessor output, assembly, llvm IR and the linker mapfile.

Between then and now, I'm not aware of anyone using these "side output" artifacts apart from the mapfile.  Since the new `opentitan_binary` rule emits the mapfile, I think we can eliminate the current side_outputs and save some time during the build phase by not invoking the compiler/linker 4 extra times.

**Comment by a-will** [comment]
Note that if these outputs are still needed, some can be reproduced with `--save_temps` on the ELF target. For example:
```
bazel build --platforms=@crt//platforms/riscv32:opentitan --save_temps //sw/device/tests:aes_idle_test_prog_sim_verilator.elf
```

The preprocessor output would appear in the `....../_objs/` directory. You only get the temps for cc_* targets explicitly named on the command line.
