### ISSUE TITLE
[chip-test,sival] chip_sw_nmi_irq

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#20025]
### Test point name

[chip_sw_nmi_irq](https://github.com/GregAC/opentitan/blob/1bca66ecf9a56c64b2655080bfb5d8ff675c4366/hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson#L8-L27)

### Host side component

None

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [X] CW310
- [ ] Hyperdebug + CW310

### Contact person

gregac

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 0.5

**Comment by HU90m** [comment]
*See https://github.com/lowRISC/opentitan/pull/20319*
