### ISSUE TITLE
[chip-test, sival] chip_sw_rv_core_ibex_double_fault

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#20030]
### Test point name

[chip_sw_rv_core_ibex_double_fault](https://github.com/GregAC/opentitan/blob/1bca66ecf9a56c64b2655080bfb5d8ff675c4366/hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson#L110-L124)

### Host side component

None

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [X] CW310
- [ ] Hyperdebug + CW310

### Contact person

@GregAC

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 0.5

**Comment by HU90m** [comment]
The test used to test this `rstmgr_cpu_info_test` passes on the FPGA with the test ROM and in the DV environment, but doesn't pass in ventilator and &mdash; more importantly &mdash; on the FPGA with the full ROM with fake keys.

In both cases, the error happens in the double fault part of the test, so a stripped down version of the test could be used for https://github.com/lowRISC/opentitan/issues/20029 today.

FPGA ROM with fake keys run:

```
I00001 ottf_main.c:154] Running sw/device/tests/rstmgr_cpu_info_test.c
I00002 rstmgr_cpu_info_test.c:238] Checking CPU info dump after single fault.
I00003 rstmgr_cpu_info_test.c:165] exp_mcpc=0x20000898, exp_mnpc=0x2000089c, obs_mcpc=0x20000898, obs_mnpc=0x2000089c
I00004 rstmgr_cpu_info_test.c:258] Setting up watch dog and triggering a double fault.
ROM:37b36ab8
I00001 ottf_main.c:154] Running sw/device/tests/rstmgr_cpu_info_test.c
I00002 rstmgr_cpu_info_test.c:285] Checking CPU info dump after double fault.
E00003 rstmgr_cpu_info_test.c:163] CHECK-fail: Last Exception Access Addr: Expected 0x8 != Observed 0x0
I00004 status.c:34] FAIL!
```

Verilator run:

```
I00001 ottf_main.c:154] Running sw/device/tests/rstmgr_cpu_info_test.c
I00002 rstmgr_cpu_info_test.c:237] Checking CPU info dump after single fault.
I00003 rstmgr_cpu_info_test.c:164] exp_mcpc=0x2000088e, exp_mnpc=0x20000892, obs_mcpc=0x2000088e, obs_mnpc=0x20000892
I00004 rstmgr_cpu_info_test.c:257] Setting up watch dog and triggering a double fault.
I00001 test_rom.c:158] kChipInfo: scm_revision=83155167
I00002 test_rom.c:230] Test ROM complete, jumping to flash (addr: 20000480)!
I00001 ottf_main.c:154] Running sw/device/tests/rstmgr_cpu_info_test.c
I00002 rstmgr_cpu_info_test.c:284] Checking CPU info dump after double fault.
E00003 rstmgr_cpu_info_test.c:289] CHECK-fail: CPU Info dump doesn't show a double fault has happened.
I00004 status.c:34] FAIL!
```

I've spend a little time looking into this but with no luck so far.
