### ISSUE TITLE
[chip-test,si-val ] chip_sw_edn_auto_mode

### ISSUE THREAD

**Issue by h-filali** [lowRISC/opentitan#20048]
### Test point name

[chip_sw_edn_auto_mode](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_edn_testplan.hjson)

### Host side component

None Required

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [X] CW310
- [ ] Hyperdebug + CW310

### Contact person

@vogelpi @h-filali

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [x] Host-side component developed: *none required*
- [x] HJSON test plan updated with test name (so it shows up in the dashboard): *testpoint exists in test plan*
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

**Comment by h-filali** [comment]
I suggest we should create an OTBN app that consumes lots of entropy. There is an existing app called [randomness.s](https://github.com/lowRISC/opentitan/blob/master/sw/otbn/code-snippets/randomness.s). However, this app does not consume enough entropy to really stress test the EDN.
Therefore, a new app that requests entropy in a loop might be useful. To also account for the other EDN sival tests in the test plan the app should also write the received values to a SW accessible reg. Such that we can use it for KAT.
The app should not consume too much entropy such that it can still be used for the chip_sw_edn_boot_mode test.

**Comment by vogelpi** [comment]
Thanks for opening the issue @h-filali . As for the OTBN app: I think we could even extend the existing randomness app to:
- read the randomness registers in a loop
- write the retrieved values to SW-accessible DMEM part for KAT
How many loop iterations to perform, and how many URND (very fast) vs. RND (slow) reads to do per loop iteration could be input arguments passed via the SW-accessible DMEM part.
