### ISSUE TITLE
[chip-test] chip_sw_entropy_src_csrng

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#20143]
### Test point name

https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson#L32

### Host side component

None

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [X] CW310
- [X] Hyperdebug + CW310

### Contact person

@vogelpi @andreaskurth @h-filali 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

We should make sure the device side component of this test is indeed running on the FPGA.

> estimate 1

**Comment by h-filali** [comment]
I just checked and the test completes successfully in 5.6 seconds! @vogelpi can this issue be closed?

**Comment by vogelpi** [comment]
Thanks for checking this out @h-filali ! Yes, I think we can close this.

**Comment by engdoreis** [comment]
@h-filali could you please open a PR linking the tests to the testplan (bazel field) and close the issue #21391?

**Comment by h-filali** [comment]
> @h-filali could you please open a PR linking the tests to the testplan (bazel field) and close the issue #21391?

@engdoreis done as part of #21529.
