### ISSUE TITLE
[chip-test] chip_sw_entropy_src_ast_rng_req

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#20142]
### Test point name

[chip_sw_entropy_src_ast_rng_req](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson#L9)

### Host side component

None

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [X] CW310
- [X] Hyperdebug + CW310

### Contact person

@vogelpi @andreaskurth

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

We need to ensure the device side component of this test is indeed running on the FPGA. The SVA-based connectivity checks cannot be covered for SiVal.

> estimate 1

**Comment by johngt** [comment]
@vogelpi / @h-filali - I believe that this test exists - just need to link it to Bazel test in the testplan and to check it still executes.
