### ISSUE TITLE
[chip-test] chip_sw_alert_handler_lpg_clock_off

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#20174]
### Test point name

[chip_sw_alert_handler_lpg_clock_off](https://github.com/lowRISC/opentitan/blob/3f65c2a534fc75ed43f3af438f01afc5232bfc2b/hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson#L214-L225)

### Host side component

None

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [X] CW310
- [x] Hyperdebug + CW310

### Contact person

@msfschaffner

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [x] Bazel build rules developed
- [ ] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)
- [x] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 0.5

**Comment by matutem** [comment]
This test has been running since around beginning of January.

**Comment by moidx** [comment]
Test is cross-referenced. https://github.com/lowRISC/opentitan/blob/aabeeeec9cde9b2ae418acc5358821e01c2288b0/hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson#L214-L226
