### ISSUE TITLE
[sw] GEN_NUM_VARIABLE_ARGS() requires a dummy token to work correctly

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#2026]
Without the dummy arg, `GEN_NUM_VARIABLE_ARGS()` returns 1 (should be 0). `GEN_NUM_VARIABLE_ARGS(foo)` also returns 1 (correct).

This is defined in `sw/device/lib/base/macros.h`. It is used in the DV logging method.

**Comment by drewmacrae** [comment]
This appears to be fixed.
