### ISSUE TITLE
Redundant Code

### ISSUE THREAD

**Issue by tupipa** [lowRISC/opentitan#20299]
Hi guys, just found a piece of code that seems to be redundant:

https://github.com/lowRISC/opentitan/blob/f87eb7efd2f161278f458676279906c0288a339b/sw/otbn/crypto/p256_verify.s#L56-L59

The above code is not loading to w24 but w11 instead, but w11 is never used before killed later in:

https://github.com/lowRISC/opentitan/blob/f87eb7efd2f161278f458676279906c0288a339b/sw/otbn/crypto/p256_verify.s#L134-L137

However, the w24 is correctly loaded later in similar code as below:

https://github.com/lowRISC/opentitan/blob/f87eb7efd2f161278f458676279906c0288a339b/sw/otbn/crypto/p256_verify.s#L90-L93

So the first piece of code loading r to w11 should be redundant. Shall it be removed?

**Comment by rswarbrick** [comment]
Huh, that's odd. Looking quickly, I think you're probably right. If my git archaeology is working properly, I think the comment probably made sense at first, but became wrong with commit 99f13, back in May 2021(!).

@jadephilipoom: Would you mind taking a look at this? I think you're probably the most qualified, and you're the last person to have touched this file :-D

**Comment by jadephilipoom** [comment]
Yep, you're correct, this code is redundant and should be removed! I'll make a PR. Thanks for the catch and for letting us know, @tupipa !
