### ISSUE TITLE
[alert_handler] escalation ping response fail question

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#2032]
Hi Michael,

Two clarifications about escalation ping fail:
1). From the spec, responding to `esc_p/n` ping response requires: `resp_p/n` toggle with a "1010" pattern. From the current design, if the "1010" pattern does not come right after one cycle of `esc_tx_i.esc_p/n`, then the i`nteg_fail_o `signal will also be asserted. Please refer to the simulation screenshot here:
![image](https://user-images.githubusercontent.com/11466553/80023727-d57c3480-8492-11ea-8137-a738a3510572.png)

Is this behavior expected?
If so, could you update the design spec graph please? (I think at timestamp 10-11 12-13, the integ_fail_o should also be set)
![image](https://user-images.githubusercontent.com/11466553/80023888-15431c00-8493-11ea-9af4-d89ab3dc8f78.png)

2). If escalation response `resp_p/n `comes with pattern "1010" but not the "correct cycle" (not sure if this is understandable, please refer to the screenshot). Then the `ping_ok_o` pattern won't recognize it as a ping_response, but count as integ_fail. Is this behavior expected? If so, do you think is necessary to clarify that in the spec as well?
![image](https://user-images.githubusercontent.com/11466553/80023458-69013580-8492-11ea-9782-bce3621b4e6a.png)

Thanks for your time Michael!
Cindy

**Comment by msfschaffner** [comment]
Hey Cindy!

So in both cases the design is behaving as intended. The `1010` response *must* come in the next cycle, no matter what (this is a bit different from the alert rx/tx where we have an asynchronous variant that can tolerate some delay).

I'll update the spec accordingly. Thanks for flagging these discrepancies!

**Comment by cindychip** [comment]
Thanks for the quick response and your confirmation Michael.

**Comment by msfschaffner** [comment]
Np. One thing to note here is that there is an ambiguity between ping and integrity failures in this particular case. I decided to just allow both to trigger, since otherwise I would have to suppress the integrity failure - which is not preferable from a security standpoint.

Hence, I would expect that the design first raises an integrity alert, and then, after the timeout of the ping timer, it should also raise a ping fail alert in addition to that. Can you double check whether that is actually happening?

**Comment by cindychip** [comment]
Hi Michael, yes, I do see both the signal_int_alert and ping_timeout interrupt triggered in the second scenario :)

**Comment by msfschaffner** [comment]
ok great, thanks for confirming!
