### ISSUE TITLE
[aes:dpi] memory not allocated issue

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#2044]
Hi Pirmin
running with the new dpi calls 
I am seeing this message
![image](https://user-images.githubusercontent.com/53917183/80122278-a0a0d800-858d-11ea-82c2-e0f012e9848a.png)
the input is
![image](https://user-images.githubusercontent.com/53917183/80128577-2a54a380-8596-11ea-9a59-4e8a6f51e6ec.png)
message 
![image](https://user-images.githubusercontent.com/53917183/80128618-393b5600-8596-11ea-9947-35b838076582.png)

and the output of the function is 0.

could you look into this?

**Comment by vogelpi** [comment]
Hi Rasmus,
thanks for reporting the issue. I am looking it.

**Comment by vogelpi** [comment]
@rasmus-madsen and I had a look at this problem. It turned out that there was an issue in a newly added wrapper function for the DPI call. The DPI call itself is fine. I am thus closing the issue.
