### ISSUE TITLE
[keymgr_dpe] messge material is valid for invalid advance operations on erased slot 

### ISSUE THREAD

**Issue by bobby-rivos** [lowRISC/opentitan#20467]
### desc

@ballifatih I am seeing an issue where if I do an advance operation on an erased key slot the digest material sent on the kmac_data_req bus is **valid** data. There is a check in the scoreboard that if the advance is expected to fail that the advance data should be **invalid**.

**Comment by ballifatih** [comment]
Maybe we can close this if the previous PR fixed the issue. @bobby-rivos

**Comment by andreaskurth** [comment]
#20470 has been confirmed to fix this, so I'm closing this issue.
