### ISSUE TITLE
[sw] Minimal code size is very big 

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#20469]
### Description

Even when reading one register the binary size is 30K+, this is a result of DIFs dependencies and log messages.
This is especially problematic when trying to load code through JTAG (in execute from SRAM mode for example).

**Comment by timothytrippel** [comment]
Yes, we have encountered this issue with the provisioning binaries. Is this causing an issue with simulation times loading SRAM programs over JTAG?

Unfortunately, the only way around this is to make use of the silicon_creator libs when building your SRAM binaries as these have been optimized for size.

**Comment by sha-ron** [comment]
Yes the simulation is very long but the more severe problem is that since there are many JTAG transactions on the pads the dump file that we need to run on the tester is too big.
I am not sure if the problem is only with the SRAM binaries because we got the big binaries also when using bootstarp. The status library, for example, indirectly depends on the DIF UART and DIF SPI libraries through the log library dependency (LOG_INFO and such). But we can try using silicon_creator libs, is there an example of a test using it?

**Comment by sha-ron** [comment]
We solved it by using basic abs_mmio operations instead of using DIFs.
