### ISSUE TITLE
[alert_handler] Escalation Receiver Ping Timeout

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#2049]
Link to current spec: https://docs.opentitan.org/hw/ip/alert_handler/doc/index.html

The alert handler module pings all connected alert sender modules and the escalation receiver modules. The escalation receivers however, which are at the end of the escalation chain, do currently not have a mechanism to reverse ping the alert handler in order to double check whether it is still working.

Such a reverse ping mechanism could be added in several ways. Here are two suggestions:

1) active solution: 
we could add a similar pseudo random ping timer to the escalation receivers that would ping the alert handler via the existing wires. if the alert handler does not respond, the escalation receiver would auto-escalate and trigger the corresponding countermeasure. this requires changes to the current escalation protocol, and the ping timer mechanism is a bit more involved than 2) below.

2) passive solution: 
we could add a ping timeout monitor to the receiver side. this is more lightweight in the sense that it would not alter the current escalation protocol, but just observe the ping messages that are being sent by the alert handler. if the alert handler does not ping an escalation receiver within a certain time window, the escalation receiver would auto-escalate and trigger the corresponding countermeasure.

I am leaning towards 2) since it is less invasive and does not require as many changes to the DV/FPV environments than 1). But let me know if you think otherwise or have another idea how we could implement such a reverse ping mechanism.

**Comment by tjaychen** [comment]
2 sounds good to me. It seems like it would achieve the same purpose without having to do major surgery. 

btw, it's a little weird to me that we ping the escalation receivers.  If the escalation receiver doesn't respond...what do we do..? Do we still try to ...escalate..? :) Is the idea that we should configure such that if an escalation receiver fails, we escalate to a different receiver?

**Comment by sjgitty** [comment]
#2 makes sense, and from the original thinking, the purpose
was not for the escalation receiver to respond, necessarily,
but to do just what #2 implies, escalate as if it had received
a request. So in that respect the ping response from the
escalators doesn't really do anything.

**Comment by msfschaffner** [comment]
> 2 sounds good to me. It seems like it would achieve the same purpose without having to do major surgery.
> 
> btw, it's a little weird to me that we ping the escalation receivers. If the escalation receiver doesn't respond...what do we do..? Do we still try to ...escalate..? :) Is the idea that we should configure such that if an escalation receiver fails, we escalate to a different receiver?

So yes it is a little weird if you only have one receiver :). But since we have four of these guys, I thought we could categorize such a fail into the most critical bin and just escalate through all other still functional paths. That is also why I made the ping/integ fails from escalation senders different internal alerts than the pint/integ fails coming from the alert receivers.

**Comment by sjgitty** [comment]
That makes sense, a fail from one escalation sends an escalation on the
most critical one. And the most critical one just ignores the ping failure?

**Comment by msfschaffner** [comment]
To be more precise:

In my previous comment I meant that we can configure the alert handler such that all escalation failures (ping/integ) are classified as, say, class D, which could then trigger a fast-track escalation protocol that triggers all escalation measures immediately and at the same time. Hence, any failure on any of the escalation sender/receiver pairs would then cause all escalation measures including the failing one to be triggered immediately within 1 - 2 cycles.

Now whether or not the escalation trigger actually makes it through the failing sender/receiver chain is dependent on the failure mechanism. But suppose it is only the wiring that is affected, then the escalation receiver will eventually auto escalate due to the absence of pings.

**Comment by msfschaffner** [comment]
This feature has been implemented now - closing the issue.
