### ISSUE TITLE
Stray `self` in static method in dvsim's Modes.py

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#2056]
The static `Regressions.create_regressions()` method refers to `self`. This was caught by running the flake8 linter over the dvsim codebase.

This code can never have run: it would have failed at runtime. I think the correct fix is to replace `self` with `regression_obj`, which is what the first patch in PR #2040 does.

@sriyerg: You committed this code in the first place. Could you either take a look and confirm this is the right fix, or find the original author and ask them to do it?

**Comment by sriyerg** [comment]
I am the original author. Will take a look, thanks.

**Comment by sriyerg** [comment]
The fix is correct, thanks!
