### ISSUE TITLE
[sensor_ctrl/ast] Sensor controls RECOV_ALERT bit 10 should be masked on ES

### ISSUE THREAD

**Issue by meisnere** [lowRISC/opentitan#20678]
### Description

Sensor controls RECOV_ALERT bit 10 should be masked on ES as false alert might rise.

@msfschaffner @timothytrippel @moidx

**Comment by msfschaffner** [comment]
CC @matutem

**Comment by timothytrippel** [comment]
@benjbender will this change the AST calibration values written to flash / OTP?

**Comment by msfschaffner** [comment]
CC @arnonsha

**Comment by johngt** [comment]
@msfschaffner - this has not been captured in any discussions for a while - have added a section in Top Level. Will need to consider if Nuvoton needs to work on this.

**Comment by andreaskurth** [comment]
Re Earlgrey-ES: The issue to track masking flaky alerts in SW is #22778.

Re Earlgrey-PROD: sensor_ctrl now has CSRs to mask individual alerts from AST. All alerts are enabled after reset and there's a section in OTP `OWNER_SW_CFG` to hold the post-ROM configuration (#23149). ROM will read these OTP values and configure sensor_ctrl accordingly (#23150).

I'm closing this issue as no work beyond that tracked in the mentioned issues is left AFAIK.
