### ISSUE TITLE
DV plan vs testplan

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2068]
https://docs.opentitan.org/doc/project/hw_stages/#hardware-design-stages mentions things like "DV Plan available, testplan completed and reviewed". What's the difference between a DV plan and a testplan? Can we document that somewhere or link to it if this documentation already exists?

(And we should standardize in this document on "test plan" vs "testplan".)

CC @sriyerg @sjgitty

**Comment by sriyerg** [comment]
Done - #2071.
