### ISSUE TITLE
[doc] prim_packer behaviour with mask

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#2076]
We're now starting to write software against HW IP that uses the packer.

Based on this, I'm interested in how the packer module behaves in the presence of a non-full `mask_i` (the example uses the same 0xF mask at all time steps). 

This makes a difference in software, because we may end up doing byte-writes into the FIFO registers, but writing into a non-32-bit-aligned byte, and it would be good to know that this is handled correctly in, for example, HMAC. I presume, given the mask exists, that this is handled correctly, so it would be good if this was documented.

Correct handling, I believe, would be that (for HMAC, where the FIFO is 32-bits wide) a byte write of `0x3A` at address `0b????????10` would result in `data_i` of `0x003A0000` and a `mask_i` of `0x00FF0000`. This would then only add `0x3A` onto `data_o`, (in this case, writing something like `0x3A0000` or the whole word would seem to me to be an error).

Is this thinking correct? Would it be possible to update the example in `prim_packer` to show this case?

**Comment by eunchan** [comment]
Yes. Your understanding is correct. I assume you turned on the endian_swap. If not the input data should be `0x0000_3A00` and the mask is `0x0000FF00`. 

prim_packer doesn't send output to `data_o` until it packs full-word, If `0x3A` is the first byte, then it waits until 3 more bytes are received or flush request comes in.

**Comment by lenary** [comment]
My apologies, I did get the endianness wrong. My example was big-endian, now I realise.

Ok. Shall I work out how to update the example to add an instance of the mask being used? I'll try to get the endianness right this time! :)

**Comment by eunchan** [comment]
Thanks for that :)
