### ISSUE TITLE
RFC: Removing the S&P Layer in Scrambling for Top Earl Grey

### ISSUE THREAD

**Issue by johannheyszl** [lowRISC/opentitan#20788]
### Description

This is a [Draft RFC doc](https://docs.google.com/document/d/18jwkg_I3-3DgLvJDd4Q6CWWeS-sAp9wBvOYVQVkhoLc/edit?usp=sharing) for consideration of the TC after discussion in the Security WG and multiple iterations on the doc.

**Comment by johannheyszl** [comment]
addresses #10976

**Comment by msfschaffner** [comment]
This RFC has been approved by the TC today.
