### ISSUE TITLE
Latest stable release version?

### ISSUE THREAD

**Issue by jagadishnayak** [lowRISC/opentitan#2079]
Hi Open Titan Team,

  I am interested in running the Open Titan on Xcelium.  Could you point me to a commit in which the block level tests as well as the chip level tests work.

  Thanks and I do appreciate you making this design available on GitHub.

**Comment by cindychip** [comment]
Hi jagadishnayak,

Thank you for your interest in OpenTitan DV. As you probably already know, our code base has been actively contributed almost in a daily base.
So far, I believe our "master branch" (with the latest commit) maintains pretty stable block level tests on gpio, hmac, rv_timer, and uart modules. Chip level sanity tests and CSR tests are all functional as well. You can refer to our [daily regression dashboard](https://reports.opentitan.org/hw/top_earlgrey/dv/summary.html) here for the lasted regression results. 

Hope this helps.
Cindy

**Comment by jagadishnayak** [comment]
Hi Cindy,
  Thanks for the reply.  I especially like your daily regression dashboard.

Regards,
Jagadish.
