### ISSUE TITLE
[intermodule] Type / Act consistency check

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2081]
I ran across this while doing a draft integration of clkmgr.
It seems like we should probably just add a type / act consistency check.

What do you think?

inside `pwrmgr`, the following end point is defined
```
    { struct:  "pwr_clk",
      type:    "req_rsp",
      name:    "pwr_clk",
      act:     "req",
      package: "pwrmgr_pkg",
    },
```
inside `clkmgr`, the following end point is defined 
```
    { struct:  "pwr_clk",
      type:    "req_rsp",
      name:    "pwr",
      act:     "rcv",
    },
```
and finally, in `top_earlgrey.hjson`, this was defined
```
      'pwrmgr.pwr_clk'  : ['clkmgr.pwr'],
```

The actor inside clkmgr is not defined correctly (unless this is a supported case?), and the output RTL ends up looking like the following on clkmgr
```
      // Inter-module signals
      .pwr_i(pwrmgr_pwr_rst_req),
      .pwr_i(pwrmgr_pwr_rst_rsp),
```

Seems like there probably should have been an error check that failed somewhere.

**Comment by eunchan** [comment]
Thanks for the report. I will add in the validation check :) 
We could combine `type` and `act` into one field ,, `req`, `rsp` for `req_rsp` pair, `src`, `dst` for uni direction? For now, I will add checker in the validation .
