### ISSUE TITLE
[rv_dm] Restricting JTAG-based Debug in DEV 

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20829]
### Description

This is a [Draft RFC doc](https://docs.google.com/document/d/1nY-tAjKvt8aS3tnAEVtIKfN2w0vQx6miXfYvu1O5oWE/edit) for consideration of the TC after discussion in the Security WG and multiple iterations on the doc.

**Comment by msfschaffner** [comment]
CC @johannheyszl

**Comment by msfschaffner** [comment]
This RFC has been approved by the TC.

**Comment by johngt** [comment]
@msfschaffner - if the TC has approved this - is it ok to close the issue or would you like it to remain open for awareness?
I assume that we can say 0 effort now remaining, e.g. time spent = total effort, so updating the figure accordingly. 0 --> 3

**Comment by rswarbrick** [comment]
This will add a feature to the block. Thus, we're going to need to plan (and implement!) a test for that feature. Let's avoid closing this issue until we've either planned a test for the feature or at least filed an issue tracking it.

(I realise this was stating the obvious! But I want to avoid the task falling through a crack)
