### ISSUE TITLE
clock enable and attribute naming

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2085]
I noticed this isn't in our style guide (or at least i didn't notice it), but do people have a preference on how clock enable and related control signals are named?

In my past life, I've done a very suffix heavy naming scheme..for example..
```
clk_a_sw_en
clk_a_hw_en
clk_a_root_en
```
however, it seems like our style guide, at least when related to clocks, are a bit more prefix driven (specifically regarding cdc).

So I just wanted to get some input on what people would prefer (i think this probably applies to resets and power domain related things as well).  I personally don't have a strong opinion, since the readability of either has never bothered me, but I can imagine there are people who feel quite passionate about this. 

If we decide on prefix, i'll probably go through a new PR to rename things, since I am pretty suffix heavy right now.

**Comment by vogelpi** [comment]
I don't have a very strong opinion here, but I usually prefer to not start names with `clk_/rst_` unless it is really a clock or reset.

I would just use the name of the domain as a prefix for the signal name. Assuming your example deals with clock enable signals, I would use the following signal names:
```
a_sw_clk_en
a_hw_clk_en
a_root_clk_en
```
If it is not about clock enable signals, I would just drop the `_clk` part.

**Comment by eunchan** [comment]
abstained. I don't have a preference.

**Comment by tjaychen** [comment]
@vogelpi , but if we imagine everywhere we have `clk_A_i` and `clk_B_i`, would it look strange in the enable signals that we suddenly invert the positions of `clk` and `A`?

That's why I thought maybe you'd want to position the `sw` or `en` portions as a prefix, and end up with 
```
sw_en_clk_A
sw_en_clk_B
```
I'm drawing some inspiration from your comments on the reset manager, where you suggested that reset requests and the like should be renamed to 
```
req_rst_A
req_rst_B
```

Let me know what you think.

**Comment by msfschaffner** [comment]
I don't have a strong preference, but it looks like `A_clk_en` is more aligned with the prefix scheme suggested by the style guide (`<domain>_<signal name>`). The signal name `clk_en` just so happens to carry `clk`, which leads to that position inversion...

**Comment by tjaychen** [comment]
ah yes fair point. 
so do both you and @vogelpi think the following format? You are right this is more aligned with the cdc convention.  Should we keep the `clk` in there?

```
A_sw_clk_en
B_sw_clk_en
```

**Comment by sriyerg** [comment]
Mild preference towards `<domain>_<sig>` convention as pointed out by @msfschaffner :
```
a_sw_clk_i
a_sw_rst_ni
a_sw_rst_req
a_sw_clk_en
```
I am fine with any convention, as long as we stick to it throughout. My vote is for keeping the `clk_` prefix.

**Comment by msfschaffner** [comment]
I am also ok with keeping the `clk` in there.

to @sriyerg's example's, I think following the current recommendation we would end up with
```
(clk|rst)_<domain>
clk_a_sw_i
rst_a_sw_ni
```
for clock and reset signals, since we require they start with `clk` or `rst`.
https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#clocks

the convention
```
<domain>_<signal name>
a_sw_rst_req
a_sw_clk_en
```
applies to normal signals (including clock enable, cdc).
https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#prefixes

**Comment by tjaychen** [comment]
sounds good everyone.
I'll leave this issue here for a few days to see if anyone objects. If not, I'll (eventually) modify the naming to match.

**Comment by vogelpi** [comment]
Sorry for my late reply @tjaychen . (Since doing the reset manager review and implementing the reqack sync primitive, I have changed my mind. I think following the `<domain>_<signal name>` convention you originally started with and most people prefer is indeed better. IMO, it helps readability.)

@msfschaffner's suggestions sounds good to me as well!

**Comment by rswarbrick** [comment]
A quick grep through the code makes me think that we've standardised and match the decision here.

@tjaychen: Anything left to track here? Or should we close?

**Comment by tjaychen** [comment]
okay to close this one.
