### ISSUE TITLE
[fpga] cascaded bufgce

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2086]
I'm doing some experiments with the clock manager and integrating it into top_earlgrey.
One of the issues that's popping up right now is cascaded clock gating between the clkmgr and  local ibex gating, and this makes fpga unhappy. 

Do you guys have a preferred way of solving this? For example do you prefer the clock fed into ibex be completely ungated and ibex will just handle it locally? I tend to prefer some kind of hierarchical clock gating, but it can be argued in this case there is not a huge benefit. 

Part of the reason for wanting the hierarchical clock gating from my perspective is that it makes it easier for the power manager to handle "sleep fall through" cases where the WFI is is nulled by an interrupt that arrived at the right time when the hw is trying to put the chip down.  This of course can still be done without hierarchical gating, but it's typically a little more "racey".

Of course, I can also set an fpga rule to just allow this cascade, let me know what you guys think.

**Comment by tjaychen** [comment]
I underscoped the issue earlier.. vivado is actually flagging every `BUFGCE` introduced by `clkmgr`.  This is because inside `clkgen` there are two root `BUFGs` already, and that causes a ton of cascaded `BUFG`, in addition to the specific ibex case where there are 3.

So the original question still stands.  There is now a second follow-on on question on whether it's okay to remove the `BUFG` from clkgen, since downstream there are already many of them.  It seems like it would be safe to make this a parameter or define option? Let me know what you think.

**Comment by tomroberts-lowrisc** [comment]
Does the FPGA build still work and meet timing with the clock gates? From a quick read of some Xilinx documentation we might have a lot of clock skew issues with cascaded clock gates / BUFGCEs.

I think in general the hierarchical clock gating is a good idea - we could just replace all clock gating cells for FPGA builds.

**Comment by tjaychen** [comment]
sorry let me clarify a bit. The prim_clock_gating cells are already utilizing @imphil's abstract construct. So for RTL, it is a latch and AND gate, and for fpga they are currently BUFGCE cells.

Originally, the path of the clock gate looks like this..
```
clkgen/BUFG -> consuming ips
clkgen/BUFG -> ibex/BUFG -> ibex_core
```

When i added the first version of clkmgr with lots of hierarchical gating, it looked like this.
The tool was VERY unhappy

```
clkgen/BUFG -> clkmgr/root/BUFGCE -> clkmgr/leaf/BUFGCE -> consuming ips
clkgen/BUFG -> clkmgr/root/BUFGCE -> ibex/BUFG -> ibex_core
```

I've since removed the hierarchical gating for most things, as well as the clkgen/BUFG, so now it looks like this

```
clkgen -> clkmgr/leaf/BUFGCE -> consuming ips
clkgen -> clkmgr/root/BUFGCE -> ibex/BUFG -> ibex_core
```
This last version seems to make the tool happy for the consuming ips, I need to double check ibex one more time.  

I'm mainly asking 2 things now

- Is it okay to remove `clkgen/BUFG` in favor of the `clkmgr` ones?
- Do we prefer to remove `clkmgr/root/BUFGCE` upstream of `ibex`? Or should I remove that too?

**Comment by tjaychen** [comment]
sorry final update.
It seems as long as I remove the `BUFG` from `clkgen`, everything else is okay.  Assuming `clkmgr` doesn't use hierarchical gating, then most blocks only have 1 level of `BUFG`.  The only 2 level is from `clkmgr` to `ibex`, and that seems to be placeable for the tool without causing a lot of timing issues. 

Let me know if this is an acceptable fix.  I will break out a separate PR and make the `clkgen` buffers optional.

**Comment by tomroberts-lowrisc** [comment]
I was more thinking that the prim_clock_gating cells could be replaced with a straight pass-through, rather than inferring a BUFGCE cell. That leaves all the clocks running all the time, but I think that's the normal thing to do when stuffing an ASIC design into an FPGA.

If we can get away without doing that, by removing the clkgen BUFGs, then that sounds good to me. Not sure about the Ibex one, but might as well leave it in for now if the FPGA build is happy?

**Comment by tjaychen** [comment]
To be honest, having the CGs be passthrough instead of using BUFGCE is also
what I am used to.
I'd be fine with doing that here also, but I didn't know if there was a
specific reason they were BUFGCEs to start with.
