### ISSUE TITLE
[dv] Add countermeasure annotations in RTL

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#20887]
### Description

RTL files need to have countermeasure annotations. Missing countermeasures trigger warnings from regtool. We currently have such warnings for
- [x] kmac #21315
- [x] keymgr #21315
- [x] rom_ctrl #21315
- [x] otbn #21315

**Comment by msfschaffner** [comment]
Related to https://github.com/lowRISC/opentitan/issues/10071
