### ISSUE TITLE
[aes,dv] Randomly drive invalid operation values to fix coverage hole

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#20941]
### Description

Fixing #20753 (erroneous covergroup sampling function declaration) revealed that there has been coverage hole in AES DV: we were not driving invalid operation values and thus not testing the inherent resolution to the encryption mode in case of an invalid value.

I am not worried at all about this, the logic is super simple an very similar to other config fields where we check the resolution and also have coverage. But we still should solve this for M5.

**Comment by andreaskurth** [comment]
After discussing with @vogelpi, we're deferring this to V3 / M7 because it's about completing coverage under invalid operation

**Comment by vogelpi** [comment]
The PR closing this is now here: #24623.
