### ISSUE TITLE
[entropy_src] Documenting failure/error behavior

### ISSUE THREAD

**Issue by johannheyszl** [lowRISC/opentitan#20948]
### Description

The health tests implemented in HW increment error counters upon tests crossing their configured thresholds. Those thresholds will be derived based on specific properties of the noise source. No samples (a.k.a. symbols; 4 bit width for current health tests) are dropped upon any such errors of health tests during operation. A [recoverable alert](https://opentitan.org/book/hw/ip/entropy_src/doc/interfaces.html#security-alerts) is triggered (see also [interrupt](https://opentitan.org/book/hw/ip/entropy_src/doc/interfaces.html#interrupts)) upon a configurable [amount of errors accumulated](https://opentitan.org/book/hw/ip/entropy_src/doc/registers.html#alert_threshold) and any output is disabled.

It is upon SW to handle such alerts. Persistent errors can be handled by properly restarting the entropy complex (and going through startup testing again). 

Since there is no means for removing samples from the accumulating (Observe) FIFO collecting health-tested samples for conditioning, we do not consider handling intermittent failures (SP 800-90B; i.e. through dropping resprective samples and continuing operation).

Proper documentation is needed.

Issue created after discussion b/w: @moidx @johannheyszl VadimS @vogelpi @zi-v @h-filali

**Comment by vogelpi** [comment]
I've extended #21071 to discuss what happens in case of health test failures (startup and non-startup mode).

What we should also do is to discuss in more detail how the alert / alert threshold setup works. In particular the register description is a bit unclear in my opinion. What we have now:

[ALERT_THRESHOLD](https://opentitan.org/book/hw/ip/entropy_src/doc/registers.html#alert_threshold): This is the threshold size that will signal an alert when value is reached. A value of zero will disable alerts. The default value is 2.

[ALERT_SUMMARY_FAIL_COUNTS](https://opentitan.org/book/hw/ip/entropy_src/doc/registers.html#alert_summary_fail_counts): This field will hold a running count of the total alert count, which is a sum of all of the other counters in the [ALERT_FAIL_COUNTS](https://opentitan.org/book/hw/ip/entropy_src/doc/registers.html#alert_fail_counts) register. It will be reset after every passing test sequence unless in firmware override mode (extract and insert only). If an alert is signaled, this value will persist until it is cleared.

[ALERT_FAIL_COUNTS](https://opentitan.org/book/hw/ip/entropy_src/doc/registers.html#alert_fail_counts): These fields will hold a running count of test failures that contribute to the total alert count. It will be reset after every passing test sequence unless in firmware override mode (extract and insert only). If an alert is signaled, this value will persist until it is cleared.

At least to me it's not fully clear how the different registers interact. I think what we need is a new paragraph in the theory of operation section outlining how they work using a bottom-up approach.

It's also not clear to me if we need a way to a way to clear the counters in firmware override mode.

**Comment by johannheyszl** [comment]
Thanks @vogelpi . 

FW override: Configure threshold to zero to disable alerts from HW health tests since we would do them in SW?

The documentation of the counting and accumulation of alerts seems OK to me. We can document how/when SW needs to restart the entropy complex upon failures at a later point in time IMHO.

**Comment by johngt** [comment]
@vogelpi - If this is purely documentation then I'd suggest this can move to D2S. If there are design changes needed though please keep this here, otherwise consider moving to D2S or Doc Milestones.
@msfschaffner

**Comment by vogelpi** [comment]
Moving to post M2 as we're still working on higher priority design changes with area impact.

**Comment by andreaskurth** [comment]
@vogelpi is currently working on this
