### ISSUE TITLE
Enable continuous power virus test power measurement 

### ISSUE THREAD

**Issue by BenBenderOT** [lowRISC/opentitan#20955]
### Description

The current power virus systemtest for earlgrey_chip has an epoch of only roughly 1us. This is way tooo short to perform any meaningful power usage measurement. The test needs a variant that keeps the repeating the same operation for a long time. 
I tried wrapping the existing test_main with a while. Then after about 10 repetitions freertos malloc failed due to lack of memory. 
Is there a way to reuse/wait-for a task in freertos/otlib?

@timothytrippel @moidx

**Comment by moidx** [comment]
Fixed by #21234
