### ISSUE TITLE
[entropy_src] Test FIPS compatibility of FW override / bypass mode

### ISSUE THREAD

**Issue by johannheyszl** [lowRISC/opentitan#20952]
### Description

The entropy complex can be operated in a FIPS-compatible manner (SP 800-90B) using the provided HW elements (e.g. health tests in entropy_src) or through a [FW override / bypass mode](https://opentitan.org/book/hw/ip/entropy_src/doc/programmers_guide.html#firmware-override--bypass-modes). We need a comprehensive test for the functionality that is needed:
- Enable procedure
- Extraction of raw data for startup and in continuous mode and real time requirements
- (supposed health checking in SW)
- Feeding back samples into conditioning
Should be tested in 4 bit per sample (symbol) and 1 bit per sample mode.

The observe FIFO size is currently 32*64b = 2048b which is sufficient to store the entire 1024 sample startup sequence for the 1 bit case using the 1 to 4 bit packing which is always employed for case of single bit. 1024 4 bit samples cannot be held in the observe FIFO currently.

Issue created after discussion b/w: @moidx @johannheyszl VadimS @vogelpi @zi-v @h-filali

**Comment by johannheyszl** [comment]
cc @msfschaffner @andreaskurth

**Comment by vogelpi** [comment]
Thanks for creating the issue @johannheyszl . @h-filali and I will sit together with the software team to see if and how they can help. Everybody acknowledges that this is of high importance.

**Comment by vogelpi** [comment]
Regarding the Observe FIFO: the FIFO has 64 32-bit wide entries. I.e., it can hold 512 4-bit symbols. As long as the FIFO isn't full, new data can be inserted while software extracts previous data. Only when the FIFO is full, the hardware will stop inserting and drop the data (Firmware Oberride: Extract & Insert mode). At the estimated rates, software should have roughly 64 cycles available to read out each word which should be sufficient.

After extracting the raw entropy, the FIFO will fill up and then data is going to get dropped. To re-enable writing data to the FIFO, SW has to completely empty it, i.e. perform 64 reads. Then it will fill up again. Software won't need to restart the entropy_src and thus the noise source.

The software test should verify that this is possible without restarting ENTROPY_SRC between seeds and without the input FIFO of the ENTROPY_SRC ever being full (this should not happen as it will disable the noise source).

**Comment by vogelpi** [comment]
We did have constructive conversation today (internal meeting notes [here](https://docs.google.com/document/d/1eWoeRidIqNMD02HtrUW_qdAKOwDWd5yn_LWjmbAsojE/edit)) and @pamaury volunteered to do the test implementation work, @h-filali and I are happy to assist and review. He'll probably start with implementing a test plan and then fan out some SiVal test issues.

The test should cover the following:
- Can the Observe FIFO be ready fast enough to extract 1000, 2000, 4000 samples (4-bit or 1-bit symbols)
- Can the data be fed back into the ENTROPY_SRC block and the entropy complex actually works / can consumers use it?
- 4-bit and single-bit mode
- With and without SHA3 condition in hardware

Given the importance of this test, we've agreed to raise this to P0.

**Comment by johannheyszl** [comment]
Thx!
Probably we need to check if it is realistic that SW health tests are completed for the collected 1024 startup values before the FIFO runs full? Otherwise one will always need to restart the entropy_src and physical source to get the next seed, I think.

**Comment by vogelpi** [comment]
> Probably we need to check if it is realistic that SW health tests are completed for the collected 1024 startup values before the FIFO runs full? Otherwise one will always need to restart the entropy_src and physical source to get the next seed, I think.

We've briefly discussed this in the Sec WG meeting today. This is not necessary. Nothing bad happens if the FIFO runs full and it doesn't require restarting the entropy_src.

But what needs to happen is that we read multiple 1000 sample windows. If the FIFO fills up, it needs to be completely emptied and the read samples need to be discarded such that each of the collected 1000 sample windows is contiguous.

**Comment by pamaury** [comment]
There is a prototype in PR #21263

**Comment by vogelpi** [comment]
Update:
- @pamaury 's PR has been merged. This test can successfully extract multiple contiguous 1000-sample windows in Firmware Override: Observe mode. This first test uncovered some bugs which have been fixed on the master branch in the meantime:
   - https://github.com/lowRISC/opentitan/issues/21279 : the overflow status bit was only high for a single clock cycle, there was a workaround for software by using the depth register/field instead
   - https://github.com/lowRISC/opentitan/pull/21640 : the gating for the observe FIFO did not work, this mechanism is supposed to block further write once the FIFO is full, and only re-enable writes after the FIFO has been emptied
- A second test for the Firmware Override: Extract and Insert mode is currently being worked on by @jwnrt here: https://github.com/lowRISC/opentitan/pull/21562

**Comment by vogelpi** [comment]
I am closing this issue as the tests have been implemented and successfully tested on FPGA.

**Comment by vsukhoml** [comment]
Is it possible to add tests for [Firmware Override - Extract & Insert](https://opentitan.org/book/hw/ip/entropy_src/doc/programmers_guide.html#firmware-override---extract--insert) where insert doesn't happen or happens with significant delay, e.g. 20-50ms? 

Are there tests for extract-only mode? This is also a potential use case if we don't need the rest.

**Comment by vsukhoml** [comment]
Also, from the tests it is not clear how firmware can be sure there is something in FIFO and it reads a real value, not a partial state (less than 32-bits).

**Comment by johannheyszl** [comment]
@vogelpi @pamaury do you think what @vsukhoml describes is covered by existing tests?

**Comment by jwnrt** [comment]
The existing (sival) tests do not currently cover the disabling/delaying behaviour you described but I think it would be possible if needed. Is this to check the chip doesn't lock up if entropy is not provided for some period?

> Are there tests for extract-only mode? This is also a potential use case if we don't need the rest.

[entropy_src_fw_observe_many_contiguous](https://github.com/lowRISC/opentitan/blob/86de64f4940251699d6b16fdef407078abf9fa47/sw/device/tests/entropy_src_fw_observe_many_contiguous.c) tests the "observe" mode where we extract the data but let the hardware continue to process it. Is that what you're referring to?

**Comment by vogelpi** [comment]
Note that [entropy_src_fw_observe_many_contiguous](https://github.com/lowRISC/opentitan/blob/86de64f4940251699d6b16fdef407078abf9fa47/sw/device/tests/entropy_src_fw_observe_many_contiguous.c) is may not be what you need @vsukhoml . Because in the Firmware Override: Observe mode, the observed entropy continues to flow through the hardware pipeline and into CSRNG (if CSRNG is configured to reseed from ENTROPY_SRC).

@vsukhoml The disabling/delayed enabling behavior is definitely not tested by either of these tests. Both leave the ENTROPY_SRC and AST continuously on. If you don't extract the entropy, it's just discarded inside ENTROPY_SRC. If you want to specifically test what happens during disable, you'll have to edit the tests / create a new edited version. We are happy to review the code and support you but I think you need to do the implementation work yourself given everybody is more than fully loaded here.

**Comment by vogelpi** [comment]
I have now created a new issue to keep track of the additional things to test recently mentioned in this issue. Closing this issue now.
