### ISSUE TITLE
[entropy_src] Make HW health tests configurable to process either 1 or 4 bit samples/symbols

### ISSUE THREAD

**Issue by johannheyszl** [lowRISC/opentitan#20954]
### Description

We can switch the entropy_src to a single bit mode. However, the health tests currently operate on 4 bit samples. We can change the HW to make them configurable to support single bit noise sources with HW health testing. Alternatively, the single bit FIPS processing can be achieved through FW bypass.

Issue created after discussion b/w: @moidx @johannheyszl VadimS @vogelpi @zi-v @h-filali

**Comment by johannheyszl** [comment]
cc @msfschaffner @andreaskurth

**Comment by johannheyszl** [comment]
Note: this would also include to move the 1 to 4 bit packer to after the health checks

**Comment by vogelpi** [comment]
Thanks for opening the issue. The next thing is that @h-filali and I will look into the relevant NIST specifications.

**Comment by vogelpi** [comment]
From my discussion with @h-filali : the purpose of the health tests is to - assuming initial validation passed - check that there is no catastrophic failure in the noise source. We currently see different options that could get validated:
- 4-bit hardware pipeline
- 1-bit hardware pipeline
- software pipeline (4 or 1-bit)
The key is that the pipeline is operated for the health tests the same way it's used for the validation. I.e., the 1-bit
mode was validated and for validation a bitstream was considered, we should check the health tests. In contrast, if the 1-bit mode was validated and for validation a stream of packed 4-bit symbols was considered, the health tests should be left as is.

Both @h-filali and I currently think it would be better to modify the health tests for the 1-bit mode to get more meaningful health test results.
