### ISSUE TITLE
[hmac] Evaluate whether wider SHA2-384 and SHA2-512 modes should be added

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20968]
### Description

Depending on the need for these (@johannheyszl @moidx to update), we would like to:
- [ ] carry over the SHA2 multimode primitive and associated testbench from the `integrated_dev` branch
- [ ] carry over the instantiation of that primitive in HMAC from the `integrated_dev` branch
- [ ] extend HMAC to be able to switch among modes and output a wider hash

Note that the HMAC IP version should be increased to 2.0.0 and stages reverted back to D1/V1 before making these changes on `master`.

**Comment by gdessouky** [comment]
After evaluating area overhead and scoping effort, we've decided to go forward with this change. PR #21107 (merged) carries over the SHA-2 multimode primitive and its instantiation in HMAC from the `integrated_dev` branch.  PR #21604 (open) extends HMAC to switch among modes and a number of key lengths, and passes basic smoke testing. 
The prim_sha2 testbenches PR #20473 is still open but not priority atm; will take care of requested changes in it and merge it in both `master` and `integrated_dev` branches.

**Comment by andreaskurth** [comment]
The tasks that concern HMAC (items 2 and 3 as well as the non-TB part of item 1 in the description above) have been completed in #21604. I created a new issue (#21882) to track the addition of pre_dv Verilator testbenches, which isn't on the critical path for HMAC DV. With that, we can close this issue.
