### ISSUE TITLE
[fpga_cw310_sival] emulation come up with flash fatal

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#20961]
### Description

While debugging #20589 I found this happens most of tests with
fpga_cw310_sival / fpga_cw310_sival_rom_ext

Same tests pass with silicon_*_rom_ext
Boot with sival_rom code crush in [flash_ctrl_init](https://github.com/lowRISC/opentitan/blob/71c00a834bfb6ed5144714939c743910384974fd/sw/device/silicon_creator/rom/rom.c#L165)

**Comment by jdonjdon** [comment]
With the latest master (296efbb67bdc99feb3df4359622c97f3801d7894)
if I read flash_fault_status, it return 0x144 for 
fpga_cw310_test_rom, fpga_cw310_sival, and fpga_cw310_sival_rom_ext
But it is clean with silicon_owner_sival_rom_ext

This implies we have read seed errors from our secret partition in fpga_cw310_* target.

**Comment by a-will** [comment]
If you can, it might be good to try simulation. The FPGA isn't going to have different logic in flash_ctrl--It uses the same RTL. (There is some potential for different parameters, though.)

**Comment by jdonjdon** [comment]
> If you can, it might be good to try simulation. The FPGA isn't going to have different logic in flash_ctrl--It uses the same RTL. (There is some potential for different parameters, though.)

Running it. I am suspecting creator / owner secret may not be create in consistent with hw_cfg.
i.e.  hw_cfg sets scramble enable while those secrets are written without it.

Will update in this thread.

**Comment by jdonjdon** [comment]
> > If you can, it might be good to try simulation. The FPGA isn't going to have different logic in flash_ctrl--It uses the same RTL. (There is some potential for different parameters, though.)
> 
> Running it. I am suspecting creator / owner secret may not be created in consistent with hw_cfg. i.e. hw_cfg sets scramble enable while those secrets are written without it.
> 
> Will update in this thread.

Simulation returns 0 fault. Next best debug env will be fpga_test_rom :)

**Comment by jdonjdon** [comment]
Once I disabled scramble/ecc from flash_ctrl hw_info, fault status are all clean.
This implies, creator / owner seeds are not created with scrambled.

Mulling over how to fix.

**Comment by jdonjdon** [comment]
Most of fpga tests using either rma or prod_personalized otp image.
This means whenever rom code trigger flash_ctrl_init, flash controller reads
creator/owner seed and pass to key manager. However, in fpga, the device comes up without those seeds
and this end up causing fatal error for every fpga_cw_310_* target.
In silicon, this won't happen because provisioned device have those seeds in flash.
So, workaround for fpga can be to use non-provisioned otp image for those tests
which need clean flash_ctrl status. I will submit a sample workaround for #20589
