### ISSUE TITLE
[rv_dm] D2 Signoff 

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20972]
### Description

Ensure D2 signoff criteria are fulfilled after focus area changes have landed.

**Comment by msfschaffner** [comment]
# [rv_dm] D2(S) Signoff 


This is a focus block.

## Commits since Earlgrey-ES tapeout

Run


```
$ git rev-parse --short HEAD
```
b3c72069c2
```
$ git log Earlgrey-M2.5.2-RC0..HEAD --oneline hw/ip/rv_dm
```
- b3c72069c2 [rv_dm] Implement NDM reset tracking
    - Fixed two open issues XXX and XXX
- a49f888385 Update pulp_riscv_dbg to pulp-platform/riscv-dbg@358f901
    - PULP side change to fix open issues XXX and XXX
- 3a84622670 [RV_DM]Amend the rv_dm_cmderr_exception_vseq
    - DV update
- 1e58899149 [rv_dm,dv] progbuf_read_write_execute_vseq
    - DV update
- 94612fe095 [rv_dm] Implement late debug enablement mechanism
    - implement RFC XXX
- 40cef6c622 [rv_dm] Bump version to 2.0.0
    - version bump due to incompatible changes
- 3208d3b6bf [RV_DM] Add seq_names in Test plan
    - DV update
- f575e4b7dc Make .core files pass FuseSoC 2 schema validator
    - fusesoc cleanup
- e0c4026501 [RV_DM]rv_dm_rom_read_access_vseq
    - DV update
- d0d6da7c9b [rv_dm,dv]Add request_halt task to base vseq and use it
    - DV update
- 9f5c75d70b [RV_DM]New_testplan_entries
    - DV update
- d6b5a48011 [RV_DM]rv_dm_abstractcmd_status_vseq
    - DV update
- 39ce8f45d6 [RV_DM]rv_dm_abstractcmd_testentry
    - DV update
- 882c862068 [RV_DM]rv_dm_progbuf_busy_vseq
    - DV update
- b2d81a3b9b [rv_dm,dv] Shuffle tasks in smoke vseq
    - DV update
- 0fa0d6041e [rv_dm,dv] Factor out cases in smoke vseq
    - DV update
- 4fff7d214e [rv_dm,dv] Add a short wait in rv_dm_smoke_vseq
    - DV update
- 71af5e75f0 [rv_dm,dv] fix typo in seq
    - DV update
- 7c3cb2c3a7 [RV_DM]rv_dm_mem_tl_access_resuming_vseq
    - DV update
- df543ebd4d [rv_dm,dv] Remove TODOs when setting reset values in env cfgs
    - DV update
- c690338f41 [RV_DM]rv_dm_mem_tl_access_halted_vseq
    - DV update
- baf655517f [rv_dm,dv] Add checks to randomization in rv_dm_tap_fsm_vseq
    - DV update
- 253a68801c [rv_dm,dv] Add checks to randomization in ..._debug_disabled_vseq
    - DV update
- 091f292034 [rv_dm,dv] Add a trivial clocking block to rv_dm_if
    - DV update
- c88d92587d [RV_DM]rv_dm_scoreboard
    - DV update
- 85a73504ed [RV_DM]rv_dm_stress_all_vseq
    - DV update
- 74c1b11679 [rv_dm,dv] Remove a TODO in rv_dm_env.core
    - DV update
- ab4b36f6b9 [ipgen,rstmgr] Fix paths to rstmgr in md files
    - doc update
- fc8484601e [reggen,hw] Create index parameter for registers windows
    - generic reggen update
- 31433a46e2 (alees/master) [RV_DM]rv_dm_stress_all_vseq
    - DV update
- 7849658cc9 [RV_DM]rv_dm_mem_tl_access_resuming_vseq
    - DV update
- 18f1692fb6 [rv_dm,dv] Slightly strengthen dmi_debug_disabled test
    - DV update 
- 331ca9e1ea [rv_dm,dv] Add comments to rv_dm_jtag_dmi_debug_disabled_vseq
    - DV update 
- 48cb2e2a83 [RV_DM]rv_dm_mem_tl_access_halted_vseq
    - DV update
- de31bdf1c2 [reggen] Remove the devmode input
    - generic reggen update, no impact on functionlity
- c535a58f13 [RV_DM] rv_dm_jtag_dtm_hard_reset_vseq
    - DV update
- 637d1b88e1 [doc,reset] Fix references to reset behavior
    - doc update
- 5a92acbcdf [RV_DM] rv_dm_jtag_dtm_hard_reset_vseq
    - DV update
- 0dc1bca205 [rv_dm,dv] update test description for jtag_dtm_hard_reset
    - DV update 
- fde2e0c057 [RV_DM]JTAG_dtm_idle_hint_vseq
    - DV update
- 358d838e3a [rv_dm,dv] fix typo in the testplan
    - DV update 
- 51130d721c [RV_DM] rv_dm_jtag_dmi_debug_disabled_vseq
    - DV update
- 17d386c879 [rv_dm,dv] fix regression failure
    - DV update 
- ee62ddbf54 [rv_dm/doc] Add some missing CSR documentation
    - doc update
- ca2b62b28a [dv, testplan] Replace descr by desc for consistency
    - DV update
- 6329668bc0 [rv_dm,sival] RV_DM post silicon validation testplan
    - sival planning update
- f2591927dd [RV_DM]jtag_dmi_dm_inactive
    - DV update
- 4143382e7e [RV_DM]jtag_dtm_idle_hint
    - DV update
- 5d8bab5473 [RV_DM]ndmreset_req sequence
    - DV update
- aa2af96865 [RV_DM]halt_resume_whereto
    - DV update
- efea9f8468 [rv_dm,dv] Add whereto check to halt_resume testplan
    - DV update 
- 467dfb2168 [rv_dm,dv] update testplan for halt/going/resume
    - DV update 
- 1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
    - generic reggen update
- bb5f3b61d4 [rv_dm] update register description
    - DV update
- 7aeb4c2676 [RV_DM]Dataaddr_rw_access Test
    - DV update
- 6585d934a0 [RV_DM] Updated HALTED and RESUMING test
    - DV update
- 9cf0ef2b6b [RV_DM] test_rename
    - DV update
- 21b873302c [RV_DM]cmderr_halt_resume_test
    - DV update
- 806815a183 [RV_DM] Hart unavailable test
    - DV update
- 59f8142826 [doc] Moved badges over to using hosted images
    - doc update
- 0773985f85 [RV_DM] Hart resuming test
    - DV update
- a23f5d6d7d [rv_dm] included seq to seq list
    - DV update
- 0eaa70fbb0 [rv_dm] remove extra displays
    - DV update
- 50d9dbb5fb [rv_dm] Halted test
    - DV update
- 7d5f36f4e3 [RV_DM] Command error exception test
    - DV update
- e9ba8b38fa [RV_DM]cmderr_not_supported_test
    - DV update
- ee6f00f5db [doc] rv_dm registers and interfaces now use CMDGEN
    - doc automation update
- a0f850982d [RV_DM]cmderr_busy_test
    - DV update
- 420c29a1f3 [RV_DM]cmderr_busy test
    - DV update
- 7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
    - generic reggen update
- fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
    - reverts previous commit
- 0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
    - this commit is reverted

## Issues closed since the Earlgrey-ES tapeout

- #21715
- #21531
- #21037
- #21007
- #21002
- #20829
- #20700
- #20419
- #19750
- #19502
- #19044
- #18635
- #18291
- #17036
- #17035
- #17033
- #16689
- #15720
- #15670
- #15667
- #15123
- #13648
- #10462
- #8538 

## Currently open issues

- #22048 
- #22044 
- #21965 
- #21716 
- #21517 
- #21423 
- #21422 
- #21421 
- #21420 
- #21419 
- #21418 
- #21417 
- #21416 
- #21077 
- #21076 
- #21074 
- #20972 
- #20194 
- #19445 
- #19375 
- #18395 
- #18310 
- #17034 
- #16148 
- #15803 
- #15668 
- #15666 
- #14345 

## Summary 

WIP

**Comment by msfschaffner** [comment]
@GregAC @rswarbrick @a-will @andreaskurth

**Comment by andreaskurth** [comment]
I reviewed the following commits, which change rv_dm's RTL (based on `git log --oneline Earlgrey-M2.5.2-RC0..HEAD -- hw/ip/rv_dm/rtl hw/vendor/pulp_riscv_dbg/src`), in detail:
- b3c72069c2 [rv_dm] Implement NDM reset tracking
  --> RTL change tracking the completion of ndmreset. This functionally LGTM and will get verified in #22048, which is tracked for M4.
- a49f888385 Update pulp_riscv_dbg to pulp-platform/riscv-dbg@358f901
  --> RTL change adding a next debug module address input and an input for acknowledging ndmreset. This functionally LGTM and their verification gets tracked in #22357 and #22048, respectively.
- 94612fe095 [rv_dm] Implement late debug enablement mechanism
  --> RTL change implementing late debug enablement in DEV LC. This functionally LGTM and will get verified in #21965, which is tracked for M4. That change should also undergo a security audit for D2**S** signoff, which is tracked in #22356.
- 053f56ff82 Update pulp_riscv_dbg to pulp-platform/riscv-dbg@358f901
  --> RTL change fixing previously non-resettable FFs in `debug_rom`
- fc8484601e [reggen,hw] Create index parameter for registers windows
  --> RTL change without functional impact
- de31bdf1c2 [reggen] Remove the devmode input
  --> RTL change without functional impact
- 1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
  --> RTL change without functional impact
- fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
  --> reverts commit below
- 0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
  --> reverted by commit above

Thus I agree with **signing rv_dm off at D2** again but not yet at D2**S**, which will be done in #22356.
