### ISSUE TITLE
[usbdev] D2 Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20970]
### Description

Ensure D2 signoff criteria are fulfilled after focus area changes have landed.

**Comment by alees24** [comment]
Under construction

## Commits since Earlgrey-ES tapeout


## Issues closed since the Earlgrey-ES tapeout
```
-
-
- [[usbdev] Forwarded Low Speed traffic raises bit stuffing errors #19148](https://github.com/lowRISC/opentitan/issues/19148)
- [[usbdev] Iso IN support #18942](https://github.com/lowRISC/opentitan/issues/18942)
- [[usbdev] Check deadlines for responding to back-to-back packets #10063](https://github.com/lowRISC/opentitan/issues/10063)
```

## Currently open issues

**Comment by andreaskurth** [comment]
We (@alees24, @a-will, @rswarbrick, @andreaskurth) held the [D2S review meeting](https://docs.google.com/document/d/1_jtwDFX6V2Wn9-mlLkvcSYDmvs1sNbsx0itel3FTxVo/edit#heading=h.cv2r5wn6lb3x) yesterday and concluded that usbdev will be ready (again) for D2 signoff once the following two opens are complete:
- #22319 
- #22321

We identified three additional opens that are worth doing but don't block D2 signoff:
- #22335
- #22336

As usbdev only features the standard `BUS.INTEGRITY` countermeasure, we can sign it off at D2S without going through the full D2S checklist (as with other IP blocks for which this is the case).

usbdev already has D2S in its Hjson, so this issue can be closed without a PR.
