### ISSUE TITLE
[sysrst_ctrl] D2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20980]
### Description

Ensure D2 signoff criteria are fulfilled after focus area changes have landed.

**Comment by msfschaffner** [comment]
## Commits since Earlgrey-ES tapeout

```
$ git rev-parse --short HEAD
```
cb32ceeede
```
$ git log Earlgrey-M2.5.2-RC0..HEAD --oneline hw/ip/sysrst_ctrl
```
- a1cb20442c [sysrst_ctrl,doc] Clarify combo actions with both ec_rst_l and rst_req
  - doc update
- a29b686851 [doc,sysrst_ctrl] Fix EC_RST_CTL register description
  - doc update
- 61a237e197 [util/reggen] reverse order of substruct generation
  - generic reggen update
- de31bdf1c2 [reggen] Remove the devmode input
  - generic reggen update
- 975a6eb927 [adc_ctrl,dv] Tidy up access to intr_state in env_cfg files
  - not relevant for sysrst_ctrl
- 22443185ed [hw,sysrst_ctrl,sival] Sival plan for sysrst_ctrl
  - sival issue
- 1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
  - generic reggen update
- 59f8142826 [doc] Moved badges over to using hosted images
  - doc update
- ddcfd96e23 [doc] sysrst_ctrl registers and interfaces now use CMDGEN
  - doc update
- 7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
  - generic reggen update
- fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
  - revert previous commit
- 0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
  - this commit is reverted 

## Issues closed since the Earlgrey-ES tapeout

- #21402 
- #21401 
- #21400 
- #21399 
- #21398 
- #21397 
- #21396 
- #21048 
- #20392 
- #19403 
- #18341 
- #16689 

## Currently open issues

- #21683 
- #21015 
- #20990 
- #20980 
- #20194 
- #19234 
- #14033 

## Summary

**Comment by msfschaffner** [comment]
@GregAC @rswarbrick PTAL

**Comment by rswarbrick** [comment]
This looks sensible to me.

(Minor note: the heading made me think this was a focus-area block, but that's not right. Phew!)
