### ISSUE TITLE
[gpio] D2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20999]
### Description

Ensure D2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by msfschaffner** [comment]
Examining the commit history in this folder, we can see that there were a few miscellaneous changes due to documentation reformatting or generic reggen updates. No changes in functionality, no added TODOs. The currently claimed D3 stage is therefore still fulfilled.

```
$ git log --oneline hw/ip/gpio/ 

61a237e197 [util/reggen] reverse order of substruct generation
de31bdf1c2 [reggen] Remove the devmode input
963a5006cc [doc] Minor tweak to md sanitisation code
e4cc9353f8 [gpio,SiVal] Testplan update for gpio
1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
59f8142826 [doc] Moved badges over to using hosted images
62a022ba10 [doc] gpio registers now use CMDGEN
7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
```

**Comment by msfschaffner** [comment]
@GregAC  can you take a look at this issue and close if you agree that D3 is still fulfilled?

**Comment by andreaskurth** [comment]
I agree that D3 is still fulfilled. I reviewed the following commits, which change `gpio`'s RTL code, in detail (with `git log -p Earlgrey-M2.5.2-RC0..HEAD -- hw/ip/gpio/rtl`):
- https://github.com/lowRISC/opentitan/commit/61a237e1973d6a29d377c2be871139553c7d344f [util/reggen] reverse order of substruct generation
- https://github.com/lowRISC/opentitan/commit/de31bdf1c26be2714ca787c6041a56eb56eb7d1e [reggen] Remove the devmode input
- https://github.com/lowRISC/opentitan/commit/1b16ca2122d956f4b1f909ba2e996b01ff22001e [reggen] Add mubi support SWAccess that sets/clears a reg
- https://github.com/lowRISC/opentitan/commit/fbd888eea85260f03095b7b7f12537638ca27183 Revert "[reggen] Add CIP_IDs and bump all major versions"
- https://github.com/lowRISC/opentitan/commit/0ba10b3cd3157d233c6a9a21676b058971399b99 [reggen] Add CIP_IDs and bump all major versions

**Comment by msfschaffner** [comment]
Thanks @andreaskurth - I am closing this issue then.
