### ISSUE TITLE
[aon_timer] D2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20995]
### Description

Ensure D2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by GregAC** [comment]
@msfschaffner PTAL

**Comment by msfschaffner** [comment]
Agreed, thanks for the summary @GregAC.

The Hjson still mentions D3 and v1.0.0:
https://github.com/lowRISC/opentitan/blob/7e196e6f072791aa17817b7691aed6b258399eeb/hw/ip/aon_timer/data/aon_timer.hjson#L22-L26

Given the interface change, I believe we should move this to v2.0.0 D2S / V1 instead (potentially V2S if we can sign off on the DV part at the same time).

**Comment by GregAC** [comment]
Good point @msfschaffner I'll make the change. I'll move to V1 as I've actually uncovered some issues in the testbench that need addressing (which I'll open an issue about).

**Comment by GregAC** [comment]
PR here to switch to versions: https://github.com/lowRISC/opentitan/pull/21908

**Comment by andreaskurth** [comment]
Closing as completed in #21908.
