### ISSUE TITLE
[ibex] Back to back instruction fetches to same address?

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2099]
i noticed this while working on a flash buffering feature, but is this supposed to happen?  I admittedly have not looked into this..at all, just thought I'd do a quick sanity check first.

![image](https://user-images.githubusercontent.com/1026250/80789190-1255c480-8b40-11ea-84f1-b1329e5a5a8c.png)

I can't really think of a reason for ibex to instruction fetch the same address back to back.  Let me know if I've missed something.

**Comment by tjaychen** [comment]
just FYI, this is the "flash_test" under `sw/device/tests/flash_ctrl`

**Comment by tomroberts-lowrisc** [comment]
It's certainly possible but should be rare - the core can start prefetching an address, then branch to that same address while the fetch is outstanding. If it's happening a lot, or in some repeating pattern it might be something we should look into.

**Comment by tjaychen** [comment]
thanks @tomroberts-lowrisc

**Comment by tjaychen** [comment]
i think i've run into this bug again in a different form.  There is a branch to an uncompressed and misaligned instruction.  The jump / branch instruction seems to stay high forever, and the second part of the instruction is never fetched (instead the core fetches the same address over and over). 

I locally applied your fix, and the problem appears to have gone away, although I didn't look much into it beyond that.  Just FYI if it's helpful.
