### ISSUE TITLE
[usbdev] V1 Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21005]
### Description

Ensure V1 signoff criteria are fulfilled after focus area changes have landed.

**Comment by rswarbrick** [comment]
We had an (initial) V1 review meeting today. Notes [here](https://docs.google.com/document/d/1y0rrfApTpzurICJ4rsh8jShqRnk5-TLM41qiYsB5ejg/edit).

I don't think the block is really V1-ready at the moment. Working through the sign-off list, we extracted the following items (which have been turned into issues):

- #21758
  The usbdev DV document is not really written yet. I suspect this is mostly what got autogenerated when we first ran uvmdvgen. Change that.
- #21759
  Extend the "smoke" regression to do a basic packet transfer in each direction. This might mean that we should extend `usbdev_smoke`, or it might mean that we should add some other (existing?) testpoint to the "smoke" regression.
- #21760
  The testplan hasn't yet been augmented with any real stress tests. We need to work out what this would be, and extend the testplan to specify it.
- #21761
  Get the Verilator lint check passing again
- #21762
  Schedule and hold a testplan review

There are a couple of items that are probably worth thinking about, but probably can't be tracked as issues.

- Lots of the usbdev block's behaviour is really defined at a high enough level that we've thought about it at chip level so far. Is there somewhere that we should list these behaviours in a way that fits better than `usbdev_testplan.hjson`?
- Scope out the V2 checklist and make estimates of what will need doing, and the time associated. This probably needs to happen after all the items above.

**Comment by andreaskurth** [comment]
We held the V1 review meeting yesterday (together with the D2S review meeting) and convinced ourselves that usbdev has reached V1. In particular, the smoke test passes (even 100% according to [current nightly results](https://reports.opentitan.org/hw/ip/usbdev/dv/latest/report.html)) and the testplan has been reviewed (#21762). After the signoff meeting, @rswarbrick scoped the V2 checklist and noted his findings in the [V2 signoff issue](#22325).
