### ISSUE TITLE
[i2c] V1 Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21006]
### Description

Ensure V1 signoff criteria are fulfilled after focus area changes have landed.

[V1 Review Notes](https://docs.google.com/document/d/1VXJUi7edxKygUOZwDiCh_1APMHRiICAMIhcKGdBj6Sk) (OpenTitan ACL)

**Comment by rswarbrick** [comment]
I believe that the remaining i2c verification work for V1/M2 completion is mostly going to be extending the testplan. This is now tracked as #22168. That is hopefully a small job! So I'm going to pinch 2 days effort from the tracker here and move them to that issue.

**Comment by hcallahan-lowrisc** [comment]
Modulo #22337 being merged, after checking the V1 review notes linked above I believe we should be able to signoff at V1.
@andreaskurth @rswarbrick PTAL
