### ISSUE TITLE
[sensor_ctrl] D2(S) Signoff 

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21000]
### Description

Ensure D2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by msfschaffner** [comment]
# sensor_ctrl D2(S) Signoff 

This is not a focus area block.

## Commits since Earlgrey-ES tapeout

```
$ git rev-parse --short HEAD
```
77f0918649

```
$ git log Earlgrey-M2.5.2-RC0..HEAD --oneline hw/top_earlgrey/ip/sensor_ctrl
```

- d352f0cf45 [sensor_ctrl] Add enable register for AST alerts
    - This patch allows us to better handle issue like #20798 in the future
- f575e4b7dc Make .core files pass FuseSoC 2 schema validator
    - No RTL impact 
- 61a237e197 [util/reggen] reverse order of substruct generation
    - Generic reggen change  
- eef87110bb [rtl,sensor_ctrl] Fix CDC bug
    - This fixes a CDC bug #20614 
- de31bdf1c2 [reggen] Remove the devmode input
    - Generic reggen change   
- 1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
    - Generic reggen change  
- 7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
    - Generic reggen change  
- fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
    - Reverts previous commit
- 0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
    - This change is reverted 

## Issues closed since the Earlgrey-ES tapeout

- #20798
    - this bug will be fixed in AST and we added a masking mechanism to sensor_ctrl so that this can be controlled with finer granularity on the open-source side also. top-level tests have been updated to enable AST alerts, but we still have to add a negative test for that -> see #21996
- #20614
    - this bug has been fixed and tested
- #17085
    - this is a Darjeeling issue 
- #17070
    - this is a Darjeeling issue

## Currently open issues

- #21996
  -  
- #21871
  - 
- #20678
  - 
- #17307
  - 
- #8440 
  - 
- #7978 
  - 

## Summary

**Comment by msfschaffner** [comment]
@matutem @andreaskurth @vogelpi PTAL

**Comment by msfschaffner** [comment]
@GregAC

**Comment by msfschaffner** [comment]
@rswarbrick

**Comment by matutem** [comment]
https://github.com/lowRISC/opentitan/issues/21996 is now done. This is ready for sign-off.
