### ISSUE TITLE
[lc_ctrl] V2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21014]
### Description

Ensure V2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by msfschaffner** [comment]
This is WIP.

### LC_CTRL/VOLATILE_UNLOCK_DISABLED Simulation Results

#### Test Results
|  Stage  |                   Name                    | Tests                                   |  Max Job Runtime  |  Simulated Time  |  Passing  |  Total  |  Pass Rate  |
|:-------:|:-----------------------------------------:|:----------------------------------------|:-----------------:|:----------------:|:---------:|:-------:|:-----------:|
|   V1    |                   smoke                   | lc_ctrl_smoke                           |      4.130s       |    114.850us     |    50     |   50    |  100.00 %   |
|   V1    |               csr_hw_reset                | lc_ctrl_csr_hw_reset                    |      0.750s       |     31.550us     |     5     |    5    |  100.00 %   |
|   V1    |                  csr_rw                   | lc_ctrl_csr_rw                          |      0.770s       |     16.243us     |    20     |   20    |  100.00 %   |
|   V1    |               csr_bit_bash                | lc_ctrl_csr_bit_bash                    |      2.100s       |    110.027us     |     5     |    5    |  100.00 %   |
|   V1    |               csr_aliasing                | lc_ctrl_csr_aliasing                    |      1.390s       |     42.869us     |     5     |    5    |  100.00 %   |
|   V1    |        csr_mem_rw_with_rand_reset         | lc_ctrl_csr_mem_rw_with_rand_reset      |      1.400s       |     51.514us     |    20     |   20    |  100.00 %   |
|   V1    | regwen_csr_and_corresponding_lockable_csr | lc_ctrl_csr_rw                          |      0.770s       |     16.243us     |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_csr_aliasing                    |      1.390s       |     42.869us     |     5     |    5    |  100.00 %   |
|   V1    |                                           | **TOTAL**                               |                   |                  |    105    |   105   |  100.00 %   |
|   V2    |             state_post_trans              | lc_ctrl_state_post_trans                |      7.040s       |     80.184us     |    50     |   50    |  100.00 %   |
|   V2    |             regwen_during_op              | lc_ctrl_regwen_during_op                |      16.440s      |    379.746us     |    10     |   10    |  100.00 %   |
|   V2    |        rand_wr_claim_transition_if        | lc_ctrl_claim_transition_if             |      0.660s       |     22.604us     |    10     |   10    |  100.00 %   |
|   V2    |              lc_prog_failure              | lc_ctrl_prog_failure                    |      3.200s       |    240.158us     |    50     |   50    |  100.00 %   |
|   V2    |             lc_state_failure              | lc_ctrl_state_failure                   |      12.730s      |    855.799us     |    50     |   50    |  100.00 %   |
|   V2    |                 lc_errors                 | lc_ctrl_errors                          |      11.820s      |     1.332ms      |    50     |   50    |  100.00 %   |
|   V2    |            security_escalation            | lc_ctrl_state_failure                   |      12.730s      |    855.799us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_prog_failure                    |      3.200s       |    240.158us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_errors                          |      11.820s      |     1.332ms      |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_security_escalation             |      9.280s       |    705.187us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_state_failure              |      1.102m       |     19.859ms     |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_prog_failure               |      13.590s      |     3.903ms      |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_errors                     |      1.005m       |     12.987ms     |    20     |   20    |  100.00 %   |
|   V2    |                jtag_access                | lc_ctrl_jtag_smoke                      |      8.340s       |     1.273ms      |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_state_post_trans           |      21.660s      |    974.056us     |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_prog_failure               |      13.590s      |     3.903ms      |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_errors                     |      1.005m       |     12.987ms     |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_access                     |      20.620s      |     7.590ms      |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_regwen_during_op           |      23.930s      |     1.309ms      |    10     |   10    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_csr_hw_reset               |      1.860s       |    811.090us     |    10     |   10    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_csr_rw                     |      2.020s       |    343.664us     |    10     |   10    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_csr_bit_bash               |      21.020s      |     1.727ms      |    10     |   10    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_csr_aliasing               |      11.170s      |     2.330ms      |    10     |   10    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_same_csr_outstanding       |      1.340s       |     37.714us     |    10     |   10    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_csr_mem_rw_with_rand_reset |      5.240s       |    264.066us     |    10     |   10    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_alert_test                 |      1.150s       |    230.108us     |    10     |   10    |  100.00 %   |
|   V2    |               jtag_priority               | lc_ctrl_jtag_priority                   |      34.260s      |     12.901ms     |    10     |   10    |  100.00 %   |
|   V2    |          lc_ctrl_volatile_unlock          | lc_ctrl_volatile_unlock_smoke           |      0.970s       |     21.105us     |    50     |   50    |  100.00 %   |
|   V2    |                stress_all                 | lc_ctrl_stress_all                      |      6.623m       |     17.823ms     |    50     |   50    |  100.00 %   |
|   V2    |                alert_test                 | lc_ctrl_alert_test                      |      1.040s       |     33.514us     |    50     |   50    |  100.00 %   |
|   V2    |           tl_d_oob_addr_access            | lc_ctrl_tl_errors                       |      3.890s       |    152.658us     |    20     |   20    |  100.00 %   |
|   V2    |            tl_d_illegal_access            | lc_ctrl_tl_errors                       |      3.890s       |    152.658us     |    20     |   20    |  100.00 %   |
|   V2    |          tl_d_outstanding_access          | lc_ctrl_csr_hw_reset                    |      0.750s       |     31.550us     |     5     |    5    |  100.00 %   |
|         |                                           | lc_ctrl_csr_rw                          |      0.770s       |     16.243us     |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_csr_aliasing                    |      1.390s       |     42.869us     |     5     |    5    |  100.00 %   |
|         |                                           | lc_ctrl_same_csr_outstanding            |      1.340s       |     72.285us     |    20     |   20    |  100.00 %   |
|   V2    |            tl_d_partial_access            | lc_ctrl_csr_hw_reset                    |      0.750s       |     31.550us     |     5     |    5    |  100.00 %   |
|         |                                           | lc_ctrl_csr_rw                          |      0.770s       |     16.243us     |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_csr_aliasing                    |      1.390s       |     42.869us     |     5     |    5    |  100.00 %   |
|         |                                           | lc_ctrl_same_csr_outstanding            |      1.340s       |     72.285us     |    20     |   20    |  100.00 %   |
|   V2    |                                           | **TOTAL**                               |                   |                  |    700    |   700   |  100.00 %   |
|   V2S   |                tl_intg_err                | lc_ctrl_sec_cm                          |      14.440s      |     3.823ms      |     5     |    5    |  100.00 %   |
|         |                                           | lc_ctrl_tl_intg_err                     |      2.150s       |     94.411us     |    20     |   20    |  100.00 %   |
|   V2S   |           sec_cm_bus_integrity            | lc_ctrl_tl_intg_err                     |      2.150s       |     94.411us     |    20     |   20    |  100.00 %   |
|   V2S   |      sec_cm_transition_config_regwen      | lc_ctrl_regwen_during_op                |      16.440s      |    379.746us     |    10     |   10    |  100.00 %   |
|   V2S   |         sec_cm_manuf_state_sparse         | lc_ctrl_state_failure                   |      12.730s      |    855.799us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      14.440s      |     3.823ms      |     5     |    5    |  100.00 %   |
|   V2S   |       sec_cm_transition_ctr_sparse        | lc_ctrl_state_failure                   |      12.730s      |    855.799us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      14.440s      |     3.823ms      |     5     |    5    |  100.00 %   |
|   V2S   |        sec_cm_manuf_state_bkgn_chk        | lc_ctrl_state_failure                   |      12.730s      |    855.799us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      14.440s      |     3.823ms      |     5     |    5    |  100.00 %   |
|   V2S   |      sec_cm_transition_ctr_bkgn_chk       | lc_ctrl_state_failure                   |      12.730s      |    855.799us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      14.440s      |     3.823ms      |     5     |    5    |  100.00 %   |
|   V2S   |        sec_cm_state_config_sparse         | lc_ctrl_state_failure                   |      12.730s      |    855.799us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      14.440s      |     3.823ms      |     5     |    5    |  100.00 %   |
|   V2S   |          sec_cm_main_fsm_sparse           | lc_ctrl_state_failure                   |      12.730s      |    855.799us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      14.440s      |     3.823ms      |     5     |    5    |  100.00 %   |
|   V2S   |          sec_cm_kmac_fsm_sparse           | lc_ctrl_state_failure                   |      12.730s      |    855.799us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      14.440s      |     3.823ms      |     5     |    5    |  100.00 %   |
|   V2S   |         sec_cm_main_fsm_local_esc         | lc_ctrl_state_failure                   |      12.730s      |    855.799us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      14.440s      |     3.823ms      |     5     |    5    |  100.00 %   |
|   V2S   |        sec_cm_main_fsm_global_esc         | lc_ctrl_security_escalation             |      9.280s       |    705.187us     |    50     |   50    |  100.00 %   |
|   V2S   |     sec_cm_main_ctrl_flow_consistency     | lc_ctrl_state_post_trans                |      7.040s       |     80.184us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_state_post_trans           |      21.660s      |    974.056us     |    20     |   20    |  100.00 %   |
|   V2S   |           sec_cm_intersig_mubi            | lc_ctrl_sec_mubi                        |      14.580s      |     6.124ms      |    50     |   50    |  100.00 %   |
|   V2S   |       sec_cm_token_valid_ctrl_mubi        | lc_ctrl_sec_mubi                        |      14.580s      |     6.124ms      |    50     |   50    |  100.00 %   |
|   V2S   |            sec_cm_token_digest            | lc_ctrl_sec_token_digest                |      21.060s      |     2.440ms      |    50     |   50    |  100.00 %   |
|   V2S   |        sec_cm_token_mux_ctrl_redun        | lc_ctrl_sec_token_mux                   |      10.700s      |     2.045ms      |    50     |   50    |  100.00 %   |
|   V2S   |       sec_cm_token_valid_mux_redun        | lc_ctrl_sec_token_mux                   |      10.700s      |     2.045ms      |    50     |   50    |  100.00 %   |
|   V2S   |                                           | **TOTAL**                               |                   |                  |    175    |   175   |  100.00 %   |
|   V3    |        stress_all_with_rand_reset         | lc_ctrl_stress_all_with_rand_reset      |      20.933m      |     58.187ms     |    24     |   50    |   48.00 %   |
|   V3    |                                           | **TOTAL**                               |                   |                  |    24     |   50    |   48.00 %   |
|         |                                           | **TOTAL**                               |                   |                  |   1004    |  1030   |   97.48 %   |

#### Testplan Progress
|  Items  |  Total  |  Written  |  Passing  |  Progress  |
|:-------:|:-------:|:---------:|:---------:|:----------:|
|   V1    |    6    |     6     |     6     |  100.00 %  |
|   V2    |   27    |    27     |    27     |  100.00 %  |
|   V2S   |    5    |     5     |     5     |  100.00 %  |
|   V3    |    1    |     1     |     0     |   0.00 %   |

#### Coverage Results

|  SCORE  |  LINE   |  COND   |  TOGGLE  |   FSM    |  BRANCH  |  ASSERT  |  GROUP  |
|:-------:|:-------:|:-------:|:--------:|:--------:|:--------:|:--------:|:-------:|
| 97.46 % | 97.82 % | 95.47 % | 95.74 %  | 100.00 % | 98.52 %  | 98.76 %  | 95.89 % |

**Comment by msfschaffner** [comment]
### LC_CTRL/VOLATILE_UNLOCK_ENABLED Simulation Results

#### Test Results
|  Stage  |                   Name                    | Tests                                   |  Max Job Runtime  |  Simulated Time  |  Passing  |  Total  |  Pass Rate  |
|:-------:|:-----------------------------------------:|:----------------------------------------|:-----------------:|:----------------:|:---------:|:-------:|:-----------:|
|   V1    |                   smoke                   | lc_ctrl_smoke                           |      5.620s       |    630.950us     |    50     |   50    |  100.00 %   |
|   V1    |               csr_hw_reset                | lc_ctrl_csr_hw_reset                    |      0.720s       |     17.742us     |     5     |    5    |  100.00 %   |
|   V1    |                  csr_rw                   | lc_ctrl_csr_rw                          |      0.820s       |     19.422us     |    20     |   20    |  100.00 %   |
|   V1    |               csr_bit_bash                | lc_ctrl_csr_bit_bash                    |      1.500s       |    371.462us     |     5     |    5    |  100.00 %   |
|   V1    |               csr_aliasing                | lc_ctrl_csr_aliasing                    |      1.010s       |    137.981us     |     5     |    5    |  100.00 %   |
|   V1    |        csr_mem_rw_with_rand_reset         | lc_ctrl_csr_mem_rw_with_rand_reset      |      1.320s       |     94.113us     |    20     |   20    |  100.00 %   |
|   V1    | regwen_csr_and_corresponding_lockable_csr | lc_ctrl_csr_rw                          |      0.820s       |     19.422us     |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_csr_aliasing                    |      1.010s       |    137.981us     |     5     |    5    |  100.00 %   |
|   V1    |                                           | **TOTAL**                               |                   |                  |    105    |   105   |  100.00 %   |
|   V2    |             state_post_trans              | lc_ctrl_state_post_trans                |      6.930s       |    376.309us     |    50     |   50    |  100.00 %   |
|   V2    |             regwen_during_op              | lc_ctrl_regwen_during_op                |      12.800s      |    342.012us     |    10     |   10    |  100.00 %   |
|   V2    |        rand_wr_claim_transition_if        | lc_ctrl_claim_transition_if             |      0.600s       |     13.920us     |    10     |   10    |  100.00 %   |
|   V2    |              lc_prog_failure              | lc_ctrl_prog_failure                    |      4.330s       |    163.302us     |    50     |   50    |  100.00 %   |
|   V2    |             lc_state_failure              | lc_ctrl_state_failure                   |      12.010s      |    365.088us     |    50     |   50    |  100.00 %   |
|   V2    |                 lc_errors                 | lc_ctrl_errors                          |      12.060s      |    688.535us     |    50     |   50    |  100.00 %   |
|   V2    |            security_escalation            | lc_ctrl_state_failure                   |      12.010s      |    365.088us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_prog_failure                    |      4.330s       |    163.302us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_errors                          |      12.060s      |    688.535us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_security_escalation             |      9.440s       |     1.781ms      |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_state_failure              |      1.487m       |     19.791ms     |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_prog_failure               |      13.450s      |    716.930us     |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_errors                     |      1.135m       |     3.779ms      |    20     |   20    |  100.00 %   |
|   V2    |                jtag_access                | lc_ctrl_jtag_smoke                      |      9.830s       |    583.161us     |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_state_post_trans           |      20.260s      |     1.937ms      |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_prog_failure               |      13.450s      |    716.930us     |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_errors                     |      1.135m       |     3.779ms      |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_access                     |      13.780s      |     1.614ms      |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_regwen_during_op           |      27.560s      |     2.822ms      |    10     |   10    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_csr_hw_reset               |      2.740s       |    523.999us     |    10     |   10    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_csr_rw                     |      2.130s       |    502.139us     |    10     |   10    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_csr_bit_bash               |      15.830s      |     2.285ms      |    10     |   10    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_csr_aliasing               |      15.510s      |     1.142ms      |    10     |   10    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_same_csr_outstanding       |      1.550s       |     48.311us     |    10     |   10    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_csr_mem_rw_with_rand_reset |      4.160s       |    202.168us     |    10     |   10    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_alert_test                 |      1.890s       |    260.294us     |    10     |   10    |  100.00 %   |
|   V2    |               jtag_priority               | lc_ctrl_jtag_priority                   |      23.500s      |     14.081ms     |    10     |   10    |  100.00 %   |
|   V2    |          lc_ctrl_volatile_unlock          | lc_ctrl_volatile_unlock_smoke           |      0.810s       |     18.985us     |    50     |   50    |  100.00 %   |
|   V2    |                stress_all                 | lc_ctrl_stress_all                      |      4.360m       |     26.580ms     |    49     |   50    |   98.00 %   |
|   V2    |                alert_test                 | lc_ctrl_alert_test                      |      1.240s       |    269.387us     |    50     |   50    |  100.00 %   |
|   V2    |           tl_d_oob_addr_access            | lc_ctrl_tl_errors                       |      3.760s       |    248.139us     |    20     |   20    |  100.00 %   |
|   V2    |            tl_d_illegal_access            | lc_ctrl_tl_errors                       |      3.760s       |    248.139us     |    20     |   20    |  100.00 %   |
|   V2    |          tl_d_outstanding_access          | lc_ctrl_csr_hw_reset                    |      0.720s       |     17.742us     |     5     |    5    |  100.00 %   |
|         |                                           | lc_ctrl_csr_rw                          |      0.820s       |     19.422us     |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_csr_aliasing                    |      1.010s       |    137.981us     |     5     |    5    |  100.00 %   |
|         |                                           | lc_ctrl_same_csr_outstanding            |      1.370s       |    162.784us     |    20     |   20    |  100.00 %   |
|   V2    |            tl_d_partial_access            | lc_ctrl_csr_hw_reset                    |      0.720s       |     17.742us     |     5     |    5    |  100.00 %   |
|         |                                           | lc_ctrl_csr_rw                          |      0.820s       |     19.422us     |    20     |   20    |  100.00 %   |
|         |                                           | lc_ctrl_csr_aliasing                    |      1.010s       |    137.981us     |     5     |    5    |  100.00 %   |
|         |                                           | lc_ctrl_same_csr_outstanding            |      1.370s       |    162.784us     |    20     |   20    |  100.00 %   |
|   V2    |                                           | **TOTAL**                               |                   |                  |    699    |   700   |   99.86 %   |
|   V2S   |                tl_intg_err                | lc_ctrl_sec_cm                          |      8.610s       |     1.661ms      |     5     |    5    |  100.00 %   |
|         |                                           | lc_ctrl_tl_intg_err                     |      2.760s       |    124.990us     |    20     |   20    |  100.00 %   |
|   V2S   |           sec_cm_bus_integrity            | lc_ctrl_tl_intg_err                     |      2.760s       |    124.990us     |    20     |   20    |  100.00 %   |
|   V2S   |      sec_cm_transition_config_regwen      | lc_ctrl_regwen_during_op                |      12.800s      |    342.012us     |    10     |   10    |  100.00 %   |
|   V2S   |         sec_cm_manuf_state_sparse         | lc_ctrl_state_failure                   |      12.010s      |    365.088us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      8.610s       |     1.661ms      |     5     |    5    |  100.00 %   |
|   V2S   |       sec_cm_transition_ctr_sparse        | lc_ctrl_state_failure                   |      12.010s      |    365.088us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      8.610s       |     1.661ms      |     5     |    5    |  100.00 %   |
|   V2S   |        sec_cm_manuf_state_bkgn_chk        | lc_ctrl_state_failure                   |      12.010s      |    365.088us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      8.610s       |     1.661ms      |     5     |    5    |  100.00 %   |
|   V2S   |      sec_cm_transition_ctr_bkgn_chk       | lc_ctrl_state_failure                   |      12.010s      |    365.088us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      8.610s       |     1.661ms      |     5     |    5    |  100.00 %   |
|   V2S   |        sec_cm_state_config_sparse         | lc_ctrl_state_failure                   |      12.010s      |    365.088us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      8.610s       |     1.661ms      |     5     |    5    |  100.00 %   |
|   V2S   |          sec_cm_main_fsm_sparse           | lc_ctrl_state_failure                   |      12.010s      |    365.088us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      8.610s       |     1.661ms      |     5     |    5    |  100.00 %   |
|   V2S   |          sec_cm_kmac_fsm_sparse           | lc_ctrl_state_failure                   |      12.010s      |    365.088us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      8.610s       |     1.661ms      |     5     |    5    |  100.00 %   |
|   V2S   |         sec_cm_main_fsm_local_esc         | lc_ctrl_state_failure                   |      12.010s      |    365.088us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_sec_cm                          |      8.610s       |     1.661ms      |     5     |    5    |  100.00 %   |
|   V2S   |        sec_cm_main_fsm_global_esc         | lc_ctrl_security_escalation             |      9.440s       |     1.781ms      |    50     |   50    |  100.00 %   |
|   V2S   |     sec_cm_main_ctrl_flow_consistency     | lc_ctrl_state_post_trans                |      6.930s       |    376.309us     |    50     |   50    |  100.00 %   |
|         |                                           | lc_ctrl_jtag_state_post_trans           |      20.260s      |     1.937ms      |    20     |   20    |  100.00 %   |
|   V2S   |           sec_cm_intersig_mubi            | lc_ctrl_sec_mubi                        |      14.050s      |     3.397ms      |    50     |   50    |  100.00 %   |
|   V2S   |       sec_cm_token_valid_ctrl_mubi        | lc_ctrl_sec_mubi                        |      14.050s      |     3.397ms      |    50     |   50    |  100.00 %   |
|   V2S   |            sec_cm_token_digest            | lc_ctrl_sec_token_digest                |      12.100s      |     1.709ms      |    50     |   50    |  100.00 %   |
|   V2S   |        sec_cm_token_mux_ctrl_redun        | lc_ctrl_sec_token_mux                   |      16.210s      |     3.510ms      |    50     |   50    |  100.00 %   |
|   V2S   |       sec_cm_token_valid_mux_redun        | lc_ctrl_sec_token_mux                   |      16.210s      |     3.510ms      |    50     |   50    |  100.00 %   |
|   V2S   |                                           | **TOTAL**                               |                   |                  |    175    |   175   |  100.00 %   |
|   V3    |        stress_all_with_rand_reset         | lc_ctrl_stress_all_with_rand_reset      |      15.857m      |    359.359ms     |    22     |   50    |   44.00 %   |
|   V3    |                                           | **TOTAL**                               |                   |                  |    22     |   50    |   44.00 %   |
|         |                                           | **TOTAL**                               |                   |                  |   1001    |  1030   |   97.18 %   |

#### Testplan Progress
|  Items  |  Total  |  Written  |  Passing  |  Progress  |
|:-------:|:-------:|:---------:|:---------:|:----------:|
|   V1    |    6    |     6     |     6     |  100.00 %  |
|   V2    |   27    |    27     |    26     |  96.30 %   |
|   V2S   |    5    |     5     |     5     |  100.00 %  |
|   V3    |    1    |     1     |     0     |   0.00 %   |

#### Coverage Results

|  SCORE  |  LINE   |  COND   |  TOGGLE  |   FSM    |  BRANCH  |  ASSERT  |  GROUP  |
|:-------:|:-------:|:-------:|:--------:|:--------:|:--------:|:--------:|:-------:|
| 97.61 % | 97.89 % | 95.68 % | 95.74 %  | 100.00 % | 98.55 %  | 99.00 %  | 96.43 % |

**Comment by msfschaffner** [comment]
@vogelpi @andreaskurth PTAL

**Comment by vogelpi** [comment]
Thanks @msfschaffner , re-certifying V2S for lc_ctrl sounds good to me. The testplan has been updated to reflect relevant changes (volatile RAW unlock) and to updating the DV environment to get the coverage for the RMA Ack signals is tracked in a V3 issue.

I have two questions:
1. Do we have coverage for the "always allow transitions into scrap" bug fix?
2. The [latest formal FPV results I could](https://reports.opentitan.org/hw/top_earlgrey/formal/sec_cm/summary/latest/report.html) find are pretty outdated and show a pass rate below 100% for lc_ctrl. Is there anything we can do about this at the moment?

**Comment by andreaskurth** [comment]
Answer by @msfschaffner on Q1: Yes, this is covered in the DV changes I made.

**Comment by msfschaffner** [comment]
Thanks, agreed. The failing FPV assertions need some more debugging and look like an FPV environment issue (i.e., the error injection does not quite work as it should in these particular cases). Let's look at them later as part of M3.
