### ISSUE TITLE
[otp_ctrl] V1 Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21018]
### Description

Ensure V1 signoff criteria are fulfilled after focus area changes have landed.

**Comment by msfschaffner** [comment]
@vogelpi @andreaskurth @matutem  PTAL

**Comment by msfschaffner** [comment]
There is a D2S issue that still needs to be fixed https://github.com/lowRISC/opentitan/pull/21953. 
The patch is here: #21953

From a DV perspective, this is however tested implicitly and impact to coverage numbers should be minimal (if at all, since we have pretty high toggle coverage).

We can wait for the Tuesday regression to make sure everything is still good.

**Comment by msfschaffner** [comment]
The regression is looking good, with V2(S) pass rates all above 90%.

![image](https://github.com/lowRISC/opentitan/assets/41358501/54871b61-3e3b-4fca-90b9-50ab142ad9ea)

**Comment by msfschaffner** [comment]
@rswarbrick @matutem  PTAL

**Comment by matutem** [comment]
Update on regression results on 03/18/2024:

![Screenshot from 2024-03-18 17-18-09](https://github.com/lowRISC/opentitan/assets/80294896/dbb4298f-c05a-45c0-b452-b5ce09e07701)

**Comment by vogelpi** [comment]
Note: OTP_CTRL has effectively be signed off at V2S. I've now corrected the issue title and first comment accordingly.
