### ISSUE TITLE
[sysrst_ctrl] V2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21015]
### Description

Ensure V2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by msfschaffner** [comment]
## Commits since Earlgrey-ES tapeout

```
$ git rev-parse --short HEAD
```
cb32ceeede
```
$ git log Earlgrey-M2.5.2-RC0..HEAD --oneline hw/ip/sysrst_ctrl
```
- a1cb20442c [sysrst_ctrl,doc] Clarify combo actions with both ec_rst_l and rst_req
  - doc update
- a29b686851 [doc,sysrst_ctrl] Fix EC_RST_CTL register description
  - doc update
- 61a237e197 [util/reggen] reverse order of substruct generation
  - generic reggen update
- de31bdf1c2 [reggen] Remove the devmode input
  - generic reggen update
- 975a6eb927 [adc_ctrl,dv] Tidy up access to intr_state in env_cfg files
  - not relevant for sysrst_ctrl
- 22443185ed [hw,sysrst_ctrl,sival] Sival plan for sysrst_ctrl
  - sival issue
- 1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
  - generic reggen update
- 59f8142826 [doc] Moved badges over to using hosted images
  - doc update
- ddcfd96e23 [doc] sysrst_ctrl registers and interfaces now use CMDGEN
  - doc update
- 7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
  - generic reggen update
- fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
  - revert previous commit
- 0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
  - this commit is reverted 

## Issues closed since the Earlgrey-ES tapeout

- #21402 
  - TLT issue 
- #21401 
  - TLT issue
- #21400 
  - TLT issue
- #21399 
  - TLT issue
- #21398 
  - TLT issue 
- #21397 
  - TLT issue
- #21396 
  - TLT issue
- #21048 
  - closed as not planned, since this is not really needed for the intended use case.
- #20392 
  - firmware issue (wrong configuration), no RTL impact 
- #19403 
  - top-level test issue 
- #18341 
  - doc update only
- #16689 
  - CDC instrumentation enablement in DV 

## Currently open issues

- #21683 
  - sival issue 
- #20194 
  - sival issue 
- #19234 
  - this issue is out of scope for PROD
- #14033 
  - cleanup/refactoring issue that is out of scope for PROD

## Coverage report from 02/25/2024
![image](https://github.com/lowRISC/opentitan/assets/41358501/9e0014e4-2fbc-48ec-a2a1-8e9189bf8999)

All V2S metrics are still fulfilled (the tests that are not fully passing do still pass with 95% of all seeds in the nightlies).

## Summary 

There have been no relevant RTL changes in this block, hence the recommendation is to leave the block at V2S as claimed in the Hjson:
https://github.com/lowRISC/opentitan/blob/cb32ceeede9592f057a7b55c72eec62e78e4a883/hw/ip/sysrst_ctrl/data/sysrst_ctrl.hjson#L19-L23

**Comment by msfschaffner** [comment]
@GregAC @rswarbrick PTAL

**Comment by rswarbrick** [comment]
I agree: looks good to me.
