### ISSUE TITLE
[rv_core_ibex] V1 Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21023]
### Description

Ensure V1 signoff criteria are fulfilled after focus area changes have landed.

**Comment by andreaskurth** [comment]
@GregAC @hcallahan-lowrisc: Looking through [V1 checklist items](https://opentitan.org/book/doc/project_governance/checklist/index.html#v1), I think only [_TESTPLAN_COMPLETED_](https://opentitan.org/book/doc/project_governance/checklist/index.html#testplan_completed) needs a closer look, right? Then, as described in the [D2 signoff analysis](https://github.com/lowRISC/opentitan/issues/20988#issuecomment-1985854610), there were only 3 changes with actual RTL impact: two security fixes (https://github.com/lowRISC/ibex/commit/8ec0c6f1 and https://github.com/lowRISC/ibex/commit/35bbdb7b) and the removal of the S&P layer from scrambling (https://github.com/lowRISC/ibex/commit/56413ecf). AFAIK from a functionality perspective, all these changes are well covered by existing tests, so the testplan doesn't need to be extended.

If you agree, I suggest closing this as completed.

**Comment by GregAC** [comment]
@andreaskurth I agree, so V1 criteria remain fulfilled.
