### ISSUE TITLE
[alert_handler] V2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21028]
### Description

Ensure V2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by msfschaffner** [comment]
# [alert_handler] V2S Signoff 

This is mostly carried over from #20993.

The alert handler is not a focus block.

## Commits since Earlgrey-ES tapeout

```
$ git rev-parse --short HEAD
```
bc285b7382

```
$ git log Earlgrey-M2.5.2-RC0..HEAD --oneline hw/top_earlgrey/ip_autogen/alert_handler
```

ab4b36f6b9 [ipgen,rstmgr] Fix paths to rstmgr in md files
56399241e7 Revert "[edn] Move prim_edn_req out of prim"
c721c51c13 [rtl, prim] Add 'commit' functionality to prim_count
61a237e197 [util/reggen] reverse order of substruct generation
4a9a881d44 [topgen] Pass topname key/value pair to ipgen
3b4e36e01c [edn] Move prim_edn_req out of prim
de31bdf1c2 [reggen] Remove the devmode input
975a6eb927 [adc_ctrl,dv] Tidy up access to intr_state in env_cfg files
ca2b62b28a [dv, testplan] Replace descr by desc for consistency
3b94957561 [alert_handler,sival] Add feature list to alert_handler data
1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
59f8142826 [doc] Moved badges over to using hosted images
7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
2c6d825855 [alert_handler] Convert theory of operation to template

## Issues closed since the Earlgrey-ES tapeout

https://github.com/lowRISC/opentitan/issues?q=is%3Aissue+is%3Aclosed+closed%3A%3E2023-06-27+alert_handler

- https://github.com/lowRISC/opentitan/issues/21024
  --> signoff of another IP
- https://github.com/lowRISC/opentitan/issues/20989
  --> signoff of another IP
- https://github.com/lowRISC/opentitan/issues/17755
  --> cleanup of TODO comment in code
- https://github.com/lowRISC/opentitan/issues/16689
  --> catch-all issue; the one relevant for this IP is https://github.com/lowRISC/opentitan/issues/18070 (below)
- https://github.com/lowRISC/opentitan/issues/15720
  --> decided to not implement
- https://github.com/lowRISC/opentitan/issues/15458
  --> no longer needed
- https://github.com/lowRISC/opentitan/issues/12323
  --> no action required for this IP
- https://github.com/lowRISC/opentitan/issues/6675
  --> catch-all issue; only remaining open is https://github.com/lowRISC/opentitan/issues/6547, which is planned for M3

None of these issues should block D2(S) signoff of this IP.

## Currently open issues

https://github.com/lowRISC/opentitan/issues?q=is%3Aissue+is%3Aopen+alert_handler

- https://github.com/lowRISC/opentitan/issues/21474
  --> SiVal test involving this IP
- https://github.com/lowRISC/opentitan/issues/21473
  --> SiVal test involving this IP
- https://github.com/lowRISC/opentitan/issues/21472
  --> SiVal test involving this IP
- https://github.com/lowRISC/opentitan/issues/21471
  --> SiVal test involving this IP
- https://github.com/lowRISC/opentitan/issues/21028
  --> V2(S) signoff of this IP
- https://github.com/lowRISC/opentitan/issues/20993
  --> this issue
- https://github.com/lowRISC/opentitan/issues/20991
  --> signoff of another IP
- https://github.com/lowRISC/opentitan/issues/20197
  --> "fake" issue, to be ignored
- https://github.com/lowRISC/opentitan/issues/20194
  --> catch-all issue for SiVal tests, some of which involve this IP
- https://github.com/lowRISC/opentitan/issues/19505
  --> build system issue
- https://github.com/lowRISC/opentitan/issues/19501
  --> OTT issue
- https://github.com/lowRISC/opentitan/issues/18796
  --> DV issue involving this IP; planned for M4
- https://github.com/lowRISC/opentitan/issues/18070
  --> DV issue involving this IP; planned for M5
- https://github.com/lowRISC/opentitan/issues/17754
  --> DV issue involving this IP; planned for M5
- https://github.com/lowRISC/opentitan/issues/17361
  --> DV issue involving this IP; planned for M5
- https://github.com/lowRISC/opentitan/issues/17307
  --> general documentation improvement involving this IP
- https://github.com/lowRISC/opentitan/issues/16894
  --> documentation issue for this IP; planned for M4
- https://github.com/lowRISC/opentitan/issues/16792
  --> mentions this IP but lists no opens related to it
- https://github.com/lowRISC/opentitan/issues/16572
  --> mentions this IP but lists no opens related to it
- https://github.com/lowRISC/opentitan/issues/15427
  --> mentions this IP but lists no opens related to it
- https://github.com/lowRISC/opentitan/issues/14887
  --> DV issue involving this IP; planned for M5
- https://github.com/lowRISC/opentitan/issues/8440
  --> mentions this IP but lists no opens related to it
- https://github.com/lowRISC/opentitan/issues/3421
  --> mentions this IP but lists no opens related to it
- https://github.com/lowRISC/opentitan/issues/3275
  --> DV issue involving this IP; planned for M5
- https://github.com/lowRISC/opentitan/issues/2929
  --> no longer relevant for this IP (I just updated that issue)
- https://github.com/lowRISC/opentitan/issues/2083
  --> topgen issue planned for a future release; not critical for this IP or its integration

None of these issues should block D2(S) signoff of this IP.

## Coverage report from 03/10/2024

![image](https://github.com/lowRISC/opentitan/assets/41358501/f07736b4-cb48-422c-abe4-892090c86096)

## Summary

The following commits changed alert_handler's RTL (from `git log --oneline Earlgrey-M2.5.2-RC0..HEAD -- hw/top_earlgrey/ip_autogen/alert_handler/rtl`):
56399241e7 Revert "[edn] Move prim_edn_req out of prim"
c721c51c13 [rtl, prim] Add 'commit' functionality to prim_count
61a237e197 [util/reggen] reverse order of substruct generation
3b4e36e01c [edn] Move prim_edn_req out of prim
de31bdf1c2 [reggen] Remove the devmode input
1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
However, **none of them changes the behavior of alert_handler**. Thus, documentation and DV environment don't have to be updated.

There are currently no TODOs in alert_handler's RTL and DV code.

## Conclusion

Since there were no changes, and the coverage is still above 90% across the board, I think we can leave the block at V2S as stated in the Hjson:
https://github.com/lowRISC/opentitan/blob/bc285b73820a92ef1c0bf1ff8e5b6a6ebd10d3ab/hw/ip_templates/alert_handler/data/alert_handler.hjson.tpl#L18-L22

**Comment by msfschaffner** [comment]
@andreaskurth @vogelpi PTAL

**Comment by matutem** [comment]
This looks good to me.

**Comment by matutem** [comment]
Closing this.

**Comment by matutem** [comment]
Closing this issue as completed.
