### ISSUE TITLE
[sram_ctrl] V2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21022]
### Description

Ensure V2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by msfschaffner** [comment]
## Commits since Earlgrey-ES tapeout

```
$ git rev-parse --short HEAD
```
2d82cc8e86

```
$ git log Earlgrey-M2.5.2-RC0..HEAD --oneline hw/ip/sram_ctrl
```
be22ed76a0 [dv,sram_ctrl] Fix failing assertion
b5642fe601 [dv,sram_ctrl,otp_ctrl] Add some uvm_info messages and fix comment typos
29c97ad7eb [dv,sram_ctrl] Fix key scramble with escalation
36c168c253 (tag: Earlgrey-PROD-M2-RC0) [dv,sram_ctrl] Fix a few test failures
5e6f05ab70 [sram_ctrl] Minor alignment of init and key request behavior
62ef232b0a [dv,sram_ctrl] Improve detection of init_done and key_scr_valid
887ddfb488 [dv,sram_ctrl] Fix a few failing tests
532da6021f [sram_ctrl/dv] Fix missing case in scoreboard
06bd802092 [otp_ctrl] Add second HW_CFG partition
c721c51c13 [rtl, prim] Add 'commit' functionality to prim_count
61a237e197 [util/reggen] reverse order of substruct generation
c939d9a6d5 [otp_ctrl] Add support for multiple HW_CFG partitions
0aed4e7972 [sram_ctrl] Add RW1C status for scr key rotation
38b32dee8a [sram_ctrl] Bump version of the sram_ctrl
de31bdf1c2 [reggen] Remove the devmode input
803d9aec77 [prim, rom_ctrl] Remove S&P layer from data scrambling
7078872c6e [sram_ctrl,doc] List (testable) features of sram_ctrl
777e5badfa [sram_ctrl,doc] Fix minor style problems in theory_of_operation.md
95d13cba40 [sram_ctrl,doc] Avoid a "double prince" in README.md
1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
59f8142826 [doc] Moved badges over to using hosted images
735dfbf4f3 [doc] sram_ctrl registers and interfaces now use CMDGEN
a2be3833ea [dv/top-level] Fix sram data integrity error injection
7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
d25b1659ce [sram_ctrl] Synchronize lc signals

## Issues closed since the Earlgrey-ES tapeout
- #19500
- #19051
- #18663
- #16689
- #13201
- #12111
- #10970
- #9464 

## Currently open issues
- #19782 -> partially addressed by S&P layer removal, future fixes will be done at system level outside SRAM_CTRL
- #16636 -> SW issue
- #14304 -> DV tooling issue
- #10071 -> does not affect SRAM_CTRL anymore
- #7462 -> future release
- #6220 -> SW issue

The only relevant open issue is https://github.com/lowRISC/opentitan/issues/19782 which will be handled at the system level once a new timing report is available (removal of the S&P diffusion layer in memory scrambling was already done as a partial fix).

## Summary 

Changes since Earlgrey ES tapeout include misc reggen and doc fixes. The most notable changes that affect functionality are:
- addition of an RW1C status CSR for SCR key rotation https://github.com/lowRISC/opentitan/issues/18663
- removal of the S&P layer in the memory scrambling https://github.com/lowRISC/opentitan/issues/20788
- added synchronizers on multibit LC/MuBi input signals https://github.com/lowRISC/opentitan/issues/19051

These changes have been reflected in the docs and the DV has been updated accordingly and several patches have been made to improve the testbench.

**Comment by msfschaffner** [comment]
@matutem @rswarbrick PTAL

**Comment by matutem** [comment]
Agreed.
