### ISSUE TITLE
[adc_ctrl] V2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21027]
### Description

Ensure V1 signoff criteria are fulfilled after focus area changes have landed.

**Comment by msfschaffner** [comment]
# adc_ctrl V2(S) Signoff 

This is a focus block.

## Commits since Earlgrey-ES tapeout

```
$ git rev-parse --short HEAD
$ git log Earlgrey-M2.5.2-RC0..HEAD --oneline hw/ip/adc_ctrl
```
86b94a2457

- a8ba853045 [adc_ctrl] Updates to LP -> NP transition
    - this converts the adc_ctrl interrupt to status type, and adapts the DV accordingly
- f575e4b7dc Make .core files pass FuseSoC 2 schema validator
    - unrelated
- 772a6c2b0d [adc_ctrl/dv] Update UNR file
    - UNR update for improving coverage in DV
- 4c06f37ffe [adc_ctrl] Updates to LP -> NP transition
    - this adds an extra interrupt with wakeup capability so that LP -> NP transitions can be observed for debug purposes.
- 9d8cc486e4 [adc_ctrl] Add FSM state observation register for debug purposes
    - this adds a debug observability register
- 1d8f192c3a [adc_ctrl] Fix low-power sampling mode
    - this introduces an automatic fall-back from NP to LP mode in case a match cannot be confirmed. this is an important bugfix to prevent accidental high power consumption when the device is in any of the sleep modes and the ADC is enabled to detect cable plug/unplug events
- 3ab37e4745 [adc_ctrl] Bump version to 2.0.0
    - version bump in the Hjson
- 10a563bb48 [adc_ctrl/doc] Tweak ADC requirements
    - spec update
- 5db5697a47 [adc_ctrl/doc] Update programming guidance for 0.0V 2.3V full range
    - spec update
- 61a237e197 [util/reggen] reverse order of substruct generation
    - generic reggen change
- de31bdf1c2 [reggen] Remove the devmode input
    - generic reggen change
- 38d5796f7f [doc,adc_ctrl] Fix typos in theory of operation doc
    - minor doc change
- 975a6eb927 [adc_ctrl,dv] Tidy up access to intr_state in env_cfg files
    - DV cleanup
- 93524e9ddd [adc_ctrl,dv] Fix adc_ctrl_lowpower_counter_vseq if used with resets
    - DV fix
- 2042318f5c [SiVal] Test plan update for adc_ctrl
    - sival issue
- 1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
    - generic reggen issue
- 59f8142826 [doc] Moved badges over to using hosted images
    - unrelated
- 7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
    - generic reggen change
- fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
    - revers a previous commit
- 9f6ee514eb [doc] adc_ctrl registers now using CMDGEN
    - doc generation update
- 0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
    - this commit is reverted later

## Issues closed since the Earlgrey-ES tapeout

- #19500
    - no RTL impact 
- #19234
    - no RTL impact
- #18511
    - the issues reported were addressed for PROD 
- #15378
    - this feature request has been implemented for PROD
- #13725
    - this bug has been fixed for PROD
- #2814 
    - closed as not planned

## Currently open issues

- #21832
    - this issue has already been fixed for adc_ctrl
- #21370
    - addressed in #21929
- #13540
    - DV cleanup, planned for later milestone
- #11354
    - not planned for PROD

## Coverage report from XXX

Add newest coverage numbers

## Summary 

There were a few RTL updates in this block:
1) an issue related to sampling during low power states has been fixed so that the ADC_CTRL does not accidentally gets stuck in NP sampling mode while the chip remains in deep sleep. #13725 #18511
    - the sequences in DV were already randomized, so from a stimulus perspective this is covered. the model in the scoreboard has been aligned accordingly.
2) an observability register has been added for the FSM state for debug purposes
    - since it is hard to model the internal state exactly and cycle accurate, this is covered using an assertion. since this is for debug purposes only, this level of coverage is deemed sufficient.
3) an interrupt with wakeup capability has been added so that LP -> NP transitions can be detected. this is mainly intended for debug.
    - the interrupt enable and status registers were already covered with randomized vectors and the test descriptions are generic enough so that this does not need any alignment of the testplan. the DV scoreboard has been updated to model this correctly.
4) adc_ctrl only has one collated IRQ that is generated from multiple internal sources. it therefore made sense to convert the interrupt to status type so that SW does not have to clear multiple IRQ status bits when handling an interrupt. #21832 #15378. the scoreboard has been updated to model this correctly.

Given that all V2S tests pass with >= 90% pass rate and that coverage is > 90% accross the board, I recommend to sign this block off at V2S.

The DV has been adapted accordingly so that these new features are all covered.
There are no countermeasures in this block except for bus integrity.
The recommendation is hence to sign this block off at D2S.

**Comment by msfschaffner** [comment]
@matutem @rswarbrick I may need your help on getting this across the finish line.

**Comment by andreaskurth** [comment]
@matutem has a PR under review that should get this above the threshold required for V2.

**Comment by matutem** [comment]
#22095 Fixes most failures. The test that blocked V2(S) was adc_ctrl_stress_all. Rerunning it with #22095 merged gives the following report:

|   V2    | stress_all | adc_ctrl_stress_all |      16.174m      |      1.016s      |    50     |   50    |  100.00 %   |

**Comment by andreaskurth** [comment]
Very nice, thanks @msfschaffner and @matutem! :+1:

I agree that adc_ctrl meets the V2S criteria.
