### ISSUE TITLE
[gpio] V2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21035]
### Description

Ensure V2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by msfschaffner** [comment]
Examining the commit history in this folder, we can see that there were a few miscellaneous changes due to documentation reformatting or generic reggen updates. No changes in functionality, no added TODOs. 

```
$ git log --oneline hw/ip/gpio/ 

61a237e197 [util/reggen] reverse order of substruct generation
de31bdf1c2 [reggen] Remove the devmode input
963a5006cc [doc] Minor tweak to md sanitisation code
e4cc9353f8 [gpio,SiVal] Testplan update for gpio
1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
59f8142826 [doc] Moved badges over to using hosted images
62a022ba10 [doc] gpio registers now use CMDGEN
7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
```

Coverage report from 02/08/2024:

![Image](https://github.com/lowRISC/opentitan/assets/41358501/2a2619de-460e-4861-a570-7c9b125e833f)

The IP thus still fulfills the currently claimed V2S criteria.

**Comment by msfschaffner** [comment]
@GregAC  can you take a look at this issue and close if you agree that V2S is still fulfilled?

**Comment by GregAC** [comment]
I agree `V2S` is still fulfilled
