### ISSUE TITLE
[sw/dif] GPIO DIF Library does not have bounds checking for pin indices

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#2103]
GPIO DIF library does not have bounds checking for pin indices. It looks like out of indices will not have any observable effects because they will be shifted out of an `uint32_t` but it is a good idea to implement this and add tests.

**Comment by lenary** [comment]
Note: you won't have any generated defines in `gpio_regs.h` to help you for this case because the width of 32 pins is currently hardcoded - something I don't expect to change given the odd high/low masked output registers.
