### ISSUE TITLE
[kmac] Change `fifo_empty` interrupt from event to status type

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#21049]
### Description

KMAC-specific issue of https://github.com/lowRISC/opentitan/issues/15378

KMAC has the following interrupts:
- kmac_done : signals when the absorption has completed, event seems fine for this.
- kmac_err: signals when an error has occured, event seems fine for this.
- fifo_empty: indicates if the message FIFO is empty, status seems more sensible for this one.

**Comment by msfschaffner** [comment]
FYI @jesultra @moidx

**Comment by vogelpi** [comment]
A first version of the PR is here #21657
