### ISSUE TITLE
[fpv,pinmux] Run fpv flow against generated RTL

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#21055]
### Description

The fpv flow for pinmux should run against the top-specific RTL. It is currently running against the code under hw/ip/pinmux.

This can more easily be fixed once we transition pinmux to ipgen: see #8440.

**Comment by msfschaffner** [comment]
We actually have two FPV flows set up for pinmux at the moment, so both the "example" and the Earlgrey specific configurations are run:
https://github.com/lowRISC/opentitan/blob/cb32ceeede9592f057a7b55c72eec62e78e4a883/hw/top_earlgrey/formal/top_earlgrey_fpv_ip_cfgs.hjson#L22-L49

We should just remove the "example" variant once the block has been transitioned to IPgen.
