### ISSUE TITLE
[chip-test] chip_sw_sysrst_ctrl_outputs

### ISSUE THREAD

**Issue by pamaury** [lowRISC/opentitan#21066]
### Test point name

[chip_sw_sysrst_ctrl_outputs](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_sysrst_ctrl_testplan.hjson#L48)

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [X] Hyperdebug + CW310

### Contact person

@rswarbrick 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 1

**Comment by engdoreis** [comment]
@pamaury Could you please link the bazel target in the testplan?

**Comment by pamaury** [comment]
Done in #21560 , backport to master in #21564
