### ISSUE TITLE
[flash_ctrl] when mem prog_fifo is full, writing to it will cause TL hang

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#2110]
@tjaychen 

We have a random mem access test in top-level. And when flash_ctrl mem prog_fifo is full, writing to it will cause TL hang. Should we change to drop the data and trigger overflow interrupt instead?

Here is the command to open the waveform.
> cd /edascratch/weicai-opentitan/ot/top_earlgrey.sim.vcs/fix_hmac/failed/0.chip_mem_partial_access
> verdi -ssr Verdi.ses &

**Comment by tjaychen** [comment]
The original intent was to allow it to be constantly written to while back
pressuring the host.

In this case you're describing, has the flash program been triggrred? Maybe
I could block the fifo filling until an operation has been initiated.

There also is an overflow interrupt, but it won't do anything if the fabric
is hung.

**Comment by tjaychen** [comment]
ah just to clarify, the back pressuring was meant to allow a user to start
a flash transaction, and just keep transferring to it like a memcpy.
So this works well...until we end up locking up the entire system.

I think it'll make sense for me to block the fifo from being filled until
the transaction starts.  That should hopefully get rid of your issue. I'll
jump on and take a look at the waves to confirm my thinkin.

**Comment by weicaiyang** [comment]
> The original intent was to allow it to be constantly written to while back pressuring the host. In this case you're describing, has the flash program been triggrred? Maybe I could block the fifo filling until an operation has been initiated. There also is an overflow interrupt, but it won't do anything if the fabric is hung.

The test only did some random mem write. If it's RW, will read back data for check, but this is a WO mem, so there is no read. I don't think flash program is trigged.

**Comment by tjaychen** [comment]
ah sounds good. But let's say i block the FIFO from being filled based some
other bit, would we then need to set a exclusion on this because it no
longer behaves like normal memory?

**Comment by weicaiyang** [comment]
> ah sounds good. But let's say i block the FIFO from being filled based some other bit, would we then need to set a exclusion on this because it no longer behaves like normal memory?

No exclusion is needed for memory. If it's RW, expect to read back the last value we write. If WO, only do random write. If RO, common mem seq won't test it. 
For the behavior you mentioned, common mem seq won't test that. IP DV owner needs to write specific seq for it.

**Comment by tjaychen** [comment]
sounds good. Then let me at least add the code to block writing into the
prog_fifo until flash programming is activated.
That should resolve this issue.

**Comment by weicaiyang** [comment]
sounds good. Thanks @tjaychen

**Comment by tjaychen** [comment]
This has already been addressed but forgot to close the issue.
