### ISSUE TITLE
[edn] Consider modifying FIFO instantiations

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#21155]
### Description

When reviewing #21142, I notices that inside EDN the FIFO primitives are not hardened and they output zero when empty. This is not ideal and could be changed at low design, area and DV overhead. Each FIFO already has error signals used for detecting cases when an empty FIFO is popped etc.

**Comment by andreaskurth** [comment]
@vogelpi: It may not be possible to turn on hardening due to area optimizations, but we should disable output zero

**Comment by vogelpi** [comment]
I turns out there are just two sync FIFOs that can be hardened and the area impact should be very low for both of them. I've filed a PR to do this here #22599.
