### ISSUE TITLE
[cryptolib] Add support for cryptolib static library release target

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#21196]
### Description

The cryptolib is currently built with the following target:

```shell
bazel build --platforms=@crt//platforms/riscv32:opentitan //sw/device/lib/crypto:otcrypto
```

Bazel however does not have support for generating static library binaries by default. There is an RFC proposing the addition of a `cc_static_library` being tracked in https://github.com/bazelbuild/bazel/issues/1920 (see [doc](https://docs.google.com/document/d/1jN0LUmp6_-rV9_f-Chx-Cs6t_5iOm3fziOklzBGjGIg/edit) and [gist](https://gist.github.com/shareefj/4e314b16148fded3a8ec874e71b07143)).

This issue is to track the implementation of a static library target. 

CC @jadephilipoom for visibility

**Comment by cfrantz** [comment]
#21198 adapts one of the gists to our use case.

**Comment by moidx** [comment]
Fixed by https://github.com/lowRISC/opentitan/pull/21198
