### ISSUE TITLE
[i2c] Change of interrupt types to status

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21209]
### Description

Split out from https://github.com/lowRISC/opentitan/issues/15378:

Change the following interrupts to status type:

- [ ] fmt_threshold 
- [ ] rx_threshold
- [ ] tx_threshold (does not exist yet, only needed if we decide to add it as part of #16444)
- [ ] acq_threshold (should already be status, double check)

**Comment by msfschaffner** [comment]
FYI @jesultra @moidx

**Comment by jesultra** [comment]
Sounds good to me.  One thing: the top description mentions acq_threshold already being status type.  I assume that what is meant is that the existing acq_full interrupt is already status type, and furthermore that acq_threshold, if added along with tx_threshold in #16444 , would both also be status type.

**Comment by jettr** [comment]
Moving these four interrupts to status type SGTM as well

**Comment by msfschaffner** [comment]
Can we keep this open in order to remove temporary workarounds once the CIP lib change has been merged?

**Comment by alees24** [comment]
Fixed by #21794

**Comment by alees24** [comment]
Fixed by https://github.com/lowRISC/opentitan/pull/21226 and https://github.com/lowRISC/opentitan/pull/21794
