### ISSUE TITLE
[otp_ctrl, rom] Move ROM keys to OTP

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#21204]
### Description

This is a [draft RFC doc](https://docs.google.com/document/d/1N0-Wvp73-rzWcpDGFwxt3FAa4oUsOFOgB9SneoOqPyU/edit?pli=1) for consideration of the TC after discussion with the EarlGrey subgroup and the Software WG.

Tasks 

- [x] https://github.com/lowRISC/opentitan/pull/23320
- [x] #22697
- [X] https://github.com/lowRISC/opentitan/pull/21270
- [X] https://github.com/lowRISC/opentitan/pull/22494
- [X] https://github.com/lowRISC/opentitan/pull/22743
- [X] https://github.com/lowRISC/opentitan/pull/22741
- [X] https://github.com/lowRISC/opentitan/pull/22744
- [X] https://github.com/lowRISC/opentitan/pull/22950
- [x] https://github.com/lowRISC/opentitan/pull/23300
- [x] https://github.com/lowRISC/opentitan/pull/23309
- [x] https://github.com/lowRISC/opentitan/pull/23315
- [x] https://github.com/lowRISC/opentitan/pull/23316
- [x] https://github.com/lowRISC/opentitan/pull/23318
- [x] https://github.com/lowRISC/opentitan/pull/23319

**Comment by msfschaffner** [comment]
The OTP side has now been merged, so the remaining parts of this change are SW only.

**Comment by timothytrippel** [comment]
Thanks @msfschaffner !

**Comment by msfschaffner** [comment]
This RFC has been approved by the TC today.
