### ISSUE TITLE
[usbdev] Change of interrupt types to status

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21210]
### Description

Split out from #15378:

pkt_received, pkt_sent, av_empty, and rx_full all come with explanations that the underlying condition needs to be addressed, before the interrupt can be cleared, and that it will otherwise re-assert. I would be more natural to make these status-type, as that is basically how they already work.

**Comment by msfschaffner** [comment]
FYI @jesultra @moidx @a-will

**Comment by a-will** [comment]
> So does `pkt_received` only get cleared with RX FIFO is fully empty? Can we receive more than one packet into the FIFO before the bottom half interrupt handler gets to it (or asked another way: does `pkt_received` being asserted prevent more data from being inserted into RX FIFO)?
> 
> `pkt_sent`, `av_empty`, and `rx_full` as status all SGTM

Yes, `pkt_received` is kind of a misnomer. It is literally "RX FIFO not empty," and the RX FIFO is deeper than one so transactions are not blocked by the latency of processing the head of the queue.

**Comment by jettr** [comment]
Could we rename `pkt_received` to `rx_fifo_not_empty` or something that matches a little better while we are making the conversion from event to status then?
