### ISSUE TITLE
[flash_ctrl] Change of interrupt types to status

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21211]
### Description

Split out from https://github.com/lowRISC/opentitan/issues/15378:

Change the following interrupts to status type:

- [ ] prog_empty  
- [ ] prog_lvl  
- [ ] rd_full   
- [ ] rd_lvl

**Comment by msfschaffner** [comment]
Still need to assess whether we should actually make the change or defer to later.

**Comment by msfschaffner** [comment]
FYI @jesultra @moidx

**Comment by jettr** [comment]
Moving these four interrupts to status type SGTM
