### ISSUE TITLE
[tlul_adapter_sram] wrong mask on outstanding transaction

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#2123]
@msfschaffner @eunchan 

This happens on ram_main which supports Outstanding=2.

There are 2 outstanding read in this waveform.
For source=d, mask='b0010. For source=d1, mask='b1110.

Since it supports more than 1 outstanding items, read data is stored in `storage` when `fifo_incr_wptr` is high, before it's sent to TLUL d_data. This occurs 1 cycle after (a_valid & a_ready) == 1.

```
always_ff @(posedge clk_i)
        if (fifo_incr_wptr) begin
          storage[fifo_wptr[PTR_WIDTH-2:0]] <= wdata;
        end
```
However, the `rmask` (which gates the `wdata`) lasts for too long and the 2nd item (source=d1) actually uses the `a_mask` from 1st item.

![Screen Shot 2020-05-04 at 3 18 02 PM](https://user-images.githubusercontent.com/49293026/81019050-a4005300-8e1a-11ea-8ba0-89b5ad9a2e31.png)

It looks like a side effect from #1732. 

Here is the command to open the waveform.
```
cd /edascratch/weicai-opentitan/ot/top_earlgrey.sim.vcs/try_pr_2112/0.chip_mem_partial_access/out
verdi -ssr Verdi.ses &
```

**Comment by msfschaffner** [comment]
Thanks for catching this one @weicaiyang. Indeed, it looks like the request FIFO is not popped until the transaction response is returned to TL-UL, hence we have to introduce a separate mask FIFO.

I made a patch for this here: #2124

**Comment by msfschaffner** [comment]
@weicaiyang, can you double check whether the patch solved the problem, and close this issue?

**Comment by weicaiyang** [comment]
@msfschaffner the test is passing and waveform looks correct. Thanks

![Screen Shot 2020-05-05 at 11 25 30 AM](https://user-images.githubusercontent.com/49293026/81101885-9eab1300-8ec3-11ea-9e74-4be4be58661e.png)

**Comment by weicaiyang** [comment]
@msfschaffner 

I find simulation hangs when test with TLUL error cases.
`a_valid` is high but `a_ready` is always 0, as mask fifo is full. Maybe we shouldn't save the mask when there is an error.

![Screen Shot 2020-05-06 at 11 52 44 AM](https://user-images.githubusercontent.com/49293026/81216685-28c0ad80-8f90-11ea-9989-1320b90d7608.png)


Here is the command to open the waveform.
cd /edascratch/weicai-opentitan/ot/spi_device.sim.vcs/fix_tl_err/0.spi_device_tl_errors/out
verdi -ssr Verdi.ses &

**Comment by msfschaffner** [comment]
Oh, I see. Yes that makes sense.

**Comment by weicaiyang** [comment]
close via #2146
