### ISSUE TITLE
[usbdev] Feature request for usb_event_frame

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2125]
There is a use case in Nuvoton's clock calibration where they need to make use of of `start of frame` signal to adjust the clock frequencies.

Currently, the request is to have both a `valid` signal, and the actual reference pulse.  The valid basically informs the receiver that it is now safe to view the reference pulse, while the reference pulse itself should come at repeated time intervals.

I think in order to make sure the very first start of frame reference does not show up with really screwed up timing, it makes sense to assert the valid only when the first start of frame is seen after reset.  That way everything stays aligned. Similarly for disabled.

What do you think?

**Comment by vogelpi** [comment]
Hi @tjaychen ,
thanks for opening the issue here. I was just planing to add a toggle signal, but using a pulse + a valid seems fine, too.

Just to clarify, are the following statements correct?
- These signals need to be synchronized to `clk_usb_48mhz_peri`.
- The pulse is high for exactly one clock period.
- The valid is low after reset and goes high after the first pulse. Meaning the clock calibration will only see the second pulse.

**Comment by tjaychen** [comment]
thanks @vogelpi 

I actually originally was hoping for a toggle also :), but our partners specifically requested a valid and pulse. 

yes, i believe all your assumptions are true. Lets give @zi-v a chance to confirm, but if not, I will confirm with him in our meeting next week and reply back here.

**Comment by zi-v** [comment]
Hi guys,
We don't mind if it is a toggle or a pulse, but we do need a valid signal.
If you want I can change 'usb_ref_pulse' to 'usb_ref' 
Regardless if it is a pulse or toggle, I assume it will be synchronous to usb_clk.

**Comment by tjaychen** [comment]
sounds good to me. Pirmin, this is really up to you, I'm fine with either.

**Comment by vogelpi** [comment]
Excellent, thanks for the feedback @zi-v  and @tjaychen . I just checked the RTL again. Inside the USB device, we already have a pulse synchronized to the usb clock. So I think I'll just forward that, meaning it will be a pulse and not a toggle. I will include the valid as discussed.

**Comment by zi-v** [comment]
OK.
About the valid signal, I guess we are pretty flexible here too. @vogelpi , can you please drop a few words on how you plan to implement it? For example, is it a level or edge (I think I prefer level), when it is expected to transition and so... 
Once we get to an agreement, I'll add the description to AST interface.

**Comment by vogelpi** [comment]
My plan was to drive the valid directly from a flop. The flop would simply reset to 0 and be set to 1 with the first pulse. This means the receiver would see the valid go high AFTER the first start-of-frame pulse. The valid would then remain high forever (till the next reset in the USB clock domain), all subsequent SOF pulses would be valid.

Would this be sufficient? The flop could also be cleared back to 0 when the sense goes low, or whenever the link state is changed to active. What would be most suitable for you?

**Comment by zi-v** [comment]
Sounds good.
Here is my suggested text for the usb_ref_val signal description:
“
usb_ref_val serves as a valid signal for the usb_ref_pulse signal.
It is set to 1 after first valid usb_ref_pulse event is detected and remain high as long as usb_ref_pulse continue to behave as expected (per usb_ref_pulse description). Otherwise, usb_ref_val immediately negates to 0 until after the next valid usb_ref_val pulse.
“
If you concur I will update AST interface accordingly

**Comment by vogelpi** [comment]
> usb_ref_val serves as a valid signal for the usb_ref_pulse signal.
> It is set to 1 after first valid usb_ref_pulse event is detected and remain high as long as usb_ref_pulse continue to behave as expected (per usb_ref_pulse description). 

This basically means the `usb_ref_val` has to be 0 if we don't expect any more `usb_ref_pulse` for example because the link is no longer active. This sounds okay.

> Otherwise, usb_ref_val immediately negates to 0 until after the next valid usb_ref_val pulse.

This sounds okay as well.

**Comment by zi-v** [comment]
Thanks!
Updated AST interface accordingly

**Comment by mdhayter** [comment]
There is already logic in the usbdev to detect if a SOF has unexpectedly gone away (none in 4ms) but the link is still active (host_lost). Not sure if that should also affect usb_ref_val because it should never happen.

**Comment by zi-v** [comment]
I think this one is more for OT logic - maybe connect it to an alert or interrupt?

**Comment by vogelpi** [comment]
I thought to de-assert the `usb_ref_val` if either the link is no longer active, or if `host_lost` is high (thanks for the hint @mdhayter). Does that sound reasonable?

Also, I was wondering where these two signals should go? Into clkmgr, or should I just leave them unconnected right now as the AST is instantiated later?

Anyway, I will publish a first PR later today. I think we can also discuss the details there.

**Comment by tjaychen** [comment]
These signals I think should go directly to AST. All the calibration
logic right now is in AST, the clkmgr does very little other than
controlling some of the clock enables.

**Comment by zi-v** [comment]
I think me and @vogelpi are in synch, but just to make sure:
AST needs to know if it can synchronize on usb reference or not. If there are multiple indications about the availability of the usb reference, we expect them to be consolidated into usb_ref_val.

**Comment by tjaychen** [comment]
@vogelpi 
it might make sense to add a software enable for this feature.

**Comment by vogelpi** [comment]
I could add for example a control register bit to keep `usb_ref_val` low. Do you think there would also a benefit in forcing it high?

**Comment by tjaychen** [comment]
hmm...i don't think forcing high would be necessary..because if we forced
it high and the usb is not there, the input calibration reference would
kind of be non-sense.
But it might make sense to force it off if for some reason something is not
working quite as expected.

**Comment by tjaychen** [comment]
thank you!

**Comment by vogelpi** [comment]
I am closing this issue as the corresponding PR has been merged. Please feel free to re-open if further questions arise.
