### ISSUE TITLE
[otp_ctrl/dv] Make sure the otp_ctrl tolerates spurious ECC errors on the VENDOR_TEST partition

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21265]
### Description

In https://github.com/lowRISC/opentitan/pull/21256 we added a patch that filters ECC errors on partitions without integrity. This is done so that the updated OTP_CTRL design (with updates from Darjeeling) is still compatible with the previously implemented `prim_otp` wrapper from NTIL.

We need to test both in open source and with the closed source wrappers that uncorrectable ECC errors reported by the `prim_otp` wrapper do not cause the partition to report fatal alerts.

This is important as otherwise a VENDOR_TEST partition with garbage in the ECC bits may lock up the chip.

**Comment by msfschaffner** [comment]
@sha-ron it may be that your block-level environment already provides a stimulus for this - but it would be good to double check.

**Comment by dkabely-ot** [comment]
Hi @msfschaffner, we'll run `otp_ctrl_macro_errs` and check that everything is ok

**Comment by msfschaffner** [comment]
Sounds good, thanks!

**Comment by andreaskurth** [comment]
@dkabely-ot @sha-ron Could you please update the current status of this? TIA!

**Comment by dkabely-ot** [comment]
Hi, we are currently having problems adjusting the OTP scoreboard to the behavior of the IP, which do not match.
