### ISSUE TITLE
[lc_ctrl/dv] Improve coverage for RMA ACK signals

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21268]
### Description

In #21267 we added additional RMA ACK channels to LC_CTRL so that the ACK signals from OTBN and FLASH_CTRL can be routed back to LC_CTRL in parallel. 

While the DV environment has been adapted to accommodate this change, and while CDC randomization does introduce some level of signal latency variations between the ACK channels, it would be good to improve the DV environment that some sequences assert the ACK channels at different times (several 10s or 100s of cycles appart) in order to better reflect reality.

**Comment by andreaskurth** [comment]
Assigning @rswarbrick for now (as coordinator of lc_ctrl for M4)

**Comment by andreaskurth** [comment]
@moidx: We think the risk of a bug hiding here is low because the change is relatively simple, and even in the worst case of a bug, it would affect the chip only during RMA entry. Thus suggesting to move to M5 (still as P1, though), because if we find a bug, it should be ECO-able. WDYT?

**Comment by moidx** [comment]
Hi @andreaskurth, I agree that this should only impact RMA entry and that the change seems likely to be contained so any issues can be reduced via ECO.

I updated the milestone based on your feedback.
