### ISSUE TITLE
[doc] Rework deprecated references to `docgen` tool

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#2131]
We still have a few references to the old `docgen` tool in our documentation:
```
util/diff_generated_util_output.py
doc/ug/github_notes.md
doc/ug/design.md
doc/rm/markdown_usage_style.md
util/wavegen/README.md
util/dvsim/testplanner/README.md
```

The `docgen` tool got replaced a while ago by the Hugo-based doc system and we should check how to adapt those remaining references.

**Comment by imphil** [comment]
While at it, also add instructions how to produce a preview documentation similar to the ones removed in https://github.com/lowRISC/opentitan/pull/2120.
