### ISSUE TITLE
[tool_requirements] Add Verible version check to tool_requirements.py

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#2132]
The open-source tool Verible has been added to our set of standard tools (like Verilator, see https://github.com/lowRISC/opentitan/pull/1996#discussion_r419951979).

As such, a tool version has been added to `tool_requirements.py`, but we have not yet added the corresponding check in `check_requirements.py`. This should be done after carrying over the changes to this script from the Ibex repo.

**Comment by rswarbrick** [comment]
Since I just failed this check(!), I think this is done. Is that right, @msfschaffner?

**Comment by msfschaffner** [comment]
:smile:  Thanks for reminding me. Completely forgot that there is an associated issue.

This has been added in https://github.com/lowRISC/opentitan/pull/4583
