### ISSUE TITLE
[aon_timer] Software requires 64-bit 1 ms granularity

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#21357]
### Description

The software stack is required to support a 64-bit timer with 1-ms granularity. Since the aon_timer is 32-bits wide, firmware is required to implement an overflow counter, which is not ideal given that it will require measuring the firmware implementation to ensure the timer does not lose precision. The use case will also require to be able to support more than 90 days, which is currently not possible if setting the divider to get 1 ms granularity @ 200KHz.

This issue is to explore potential solutions: 

1. **Extend counter to 64-bits**: What is the estimated DD and DV impact for this change? Given that the register file will have to change, we expect this change to impact top level DV, but need someone more familiar with the IP weigh in on block level impact. 

2. **Use current interrupts to detect counter overflow**: Can the [`WKUP_THOLD`](https://opentitan.org/book/hw/ip/aon_timer/doc/registers.html#wkup_thold) register be used to define an overflow interrupt? From the spec, it seems that the interrupt condition is `WKUP_THOLD >= WKUP_COUNT`, which means that software will have to set `WKUP_THOLD = UINT32_MAX`, and then a second time with `WKUP_THOLD = 0; WKUP=COUNT = 0` to capture the counter overflow. Is there a better way to implement this?

3. **Add overflow interrupt**: Another approach is to add an overflow interrupt. This way software will just need to handle the overflow counter increment when this interrupt fires.

**Comment by moidx** [comment]
CC @msfschaffner, @GregAC 

Hi @GregAC, you are listed as the current coordinator for `aon_timer` :) Can you weigh on the options above, or if there are other better ideas you may be able to come up with? Thanks!

@msfschaffner marking as M2 for triaging purposes. We can adjust as needed.

**Comment by rswarbrick** [comment]
Possibly silly question, but... I think a 32-bit counter gets us almost 50 days before it wraps (`2^32/1000/3600/24 = 49.7..`). If there was some very infrequent task, we could get it to detect a "posedge" on the top bit of the counter and use that to increment some secondary counter. If that's easy, it might be a way to avoid thinking hard about the hardware :-)

I think we'd end up with an equivalent of your option (3), but with sloppier timing for when the "interrupt" happened.

**Comment by GregAC** [comment]
I think a move to 64-bits should be straight-forward, obviously has an area impact but it will be rather minor (under 1 kGE at a guess). Less DV impact than adding new interrupts and nice to avoid software having to jump through hoops to achieve things (the no hardware change option).

**Comment by msfschaffner** [comment]
Agree with @GregAC. Given that this is a relatively straightforward change, I feel like we should just do this for forward compatibility reasons.

**Comment by msfschaffner** [comment]
Should we bump the prio from P2 to P1?

**Comment by GregAC** [comment]
I think the priority bump is reasonable, given the area impact is enough to push a few things around that could have some knock on effects for implementation.

**Comment by GregAC** [comment]
@moidx would it be sufficient to just increase the size of the wake-up counter or does the watchdog counter need expanding as well? I'd assume for the watchdog timer precision over many days isn't needed, as you just reset the counter at a sufficiently rapid frequency to avoid the watchdog triggering.

**Comment by moidx** [comment]
> would it be sufficient to just increase the size of the wake-up counter or does the watchdog counter need expanding as well? 

Hi @GregAC, I think this is reasonable. Thanks

CC @jettr, @jesultra

**Comment by jettr** [comment]
Yes, just the wake-up counter needs to extended to 64-bits, the watchdog timer can remain 32-bits. That SGTM.

**Comment by GregAC** [comment]
Extended in https://github.com/lowRISC/opentitan/pull/21746

@jettr @jesultra I'd be grateful if you could look at the programming guidance I've added to the docs there. Now we have 64-bit values we need to use two seperate 32-bit registers so you cannot read or write the 64-bit values in an atomic way. Please check what I've written about reading/writing the values to avoid issues with race conditions. You can find the guidance in the programmer's guide here: https://github.com/lowRISC/opentitan/blob/4fb16c112bb205b5daa0a4ff7878934de0ad1c19/hw/ip/aon_timer/doc/programmers_guide.md

**Comment by GregAC** [comment]
I've now added an effort estimate of 2.5 days, most of which is done already. This has proved to be more complex than first expected!

**Comment by jettr** [comment]
The [Reading the counter](https://github.com/lowRISC/opentitan/blob/4fb16c112bb205b5daa0a4ff7878934de0ad1c19/hw/ip/aon_timer/doc/programmers_guide.md#reading-the-counter) section LGTM. This is what I have seen before and is expected. Thank you for updating this!

The other sections also look good.

---

I just wanted to add another way I have seen this handled: I have seen a UPPER_BITS_LATCHED register that latches the value of the upper 32-bits when a read on the lower 32-bits occurs. This allows for an "atomic" 64-bit read operation. I am sure this requires more changes in hardware, but I just wanted to mention it. I am completely fine doing a repeated read on the upper bits until it doesn't change in the FW.

**Comment by jesultra** [comment]
As far as I can tell, with the AON wakeup counter now being 64-bit, reading/updating will have the exact same concerns and workarounds as the "main" 64-bit timer (the one not always on).  This will be perfectly fine.

**Comment by GregAC** [comment]
>  I am sure this requires more changes in hardware, but I just wanted to mention it. I am completely fine doing a repeated read on the upper bits until it doesn't change in the FW.

At this point we're definitely seeking to minimize change so I will keep it as is, requiring the repeated read.

Completed with: https://github.com/lowRISC/opentitan/pull/21746
