### ISSUE TITLE
Update text from ADC theory of operation for adc_chn_value_intr registers

### ISSUE THREAD

**Issue by jettr** [lowRISC/opentitan#21370]
From https://github.com/lowRISC/opentitan/blob/dc05d4ce3fc2df1a68241471459ee2459ba67bb8/hw/ip/adc_ctrl/doc/theory_of_operation.md?plain=1#L104

> The current sample values are latched into adc_chn_val[0].adc_chn_value_intr and adc_chn_val[1].adc_chn_value_intr.
>   * If a series of interrupts and matches are seen, these registers only record the value of the last debounced hit.

and

> "However, the [adc_chn_val[0].adc_chn_value_intr](https://opentitan.org/book/hw/ip/adc_ctrl/doc/registers.html#adc_chn_val) and [adc_chn_val[1].adc_chn_value_intr](https://opentitan.org/book/hw/ip/adc_ctrl/doc/registers.html#adc_chn_val) registers record the value at the time the interrupt was first raised and thus reflect the filter state from that point"

Seem to conflict. I would the first text blurb to be "these registers only record the value of the **first** debounced hit"

Or am I misunderstanding how this works?

**Comment by msfschaffner** [comment]
I looked at the RTL and your understanding is correct.
The text is corrected here: #21929
