### ISSUE TITLE
[chip-test, pwrmgr] chip_sw_pwrmgr_external_full_reset

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#21442]
### Test point name

chip_sw_pwrmgr_external_full_reset

### Host side component
Rust?

### Opentitantool infrastructure implemented
Yes

### Silicon Validation (SiVal)

Yes

### Emulation targets
- [ ] None
- [ ] CW310
- [ ] Hyperdebug + CW310

### Checklist
Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

**Comment by matutem** [comment]
Closing this issue since this test is not needed because every test exercises this functionality. I updated its entry in https://github.com/matutem/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson in PR https://github.com/lowRISC/opentitan/pull/21654.
