### ISSUE TITLE
[chip-test, rv_core_ibex] chip_sw_rv_core_ibex_lockstep_glitch

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#21460]
### Test point name

chip_sw_rv_core_ibex_lockstep_glitch

### Host side component
Rust?

### Opentitantool infrastructure implemented
Yes

### Silicon Validation (SiVal)

Yes

### Emulation targets
- [ ] None
- [ ] CW310
- [ ] Hyperdebug + CW310

### Checklist
Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

**Comment by GregAC** [comment]
Closing as this test is implemented and running and there is nothing to be done for SiVal. It is a DV only test. `si_stage` is `none`:

https://github.com/lowRISC/opentitan/blob/27279ff687cb16bf10fa5c9748d2b1aed4ede5cf/hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson#L214-L225
