### ISSUE TITLE
Rename CODEOWNERS once GitHub supports different names

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#215]
This is related to #193 

Everyone looks like agreed to have a way to help collaborators to find the appropriate reviewers for the code. As of now, the only way to assign the reviewers by default is to have CODEOWNERS in the repository in Github system.

My suggestion is to have CODEOWNERS in the repo but pushing Github to provide a way to use alternate file names removing loaded term "OWNER". MAINTAINERS may be a proper candidate.

Please CC more people if needed.

CC: @domrizz0 @sjgitty @asb @achernya @LaurieJ @aytong @tjaychen

**Comment by tjaychen** [comment]
closing based on @imphil comments above.
