### ISSUE TITLE
Build picks incorrect `lowrisc:constant:top_pkg`

### ISSUE THREAD

**Issue by wallento** [lowRISC/opentitan#2151]
The core file and the SV package have been copied into the ibex tree. FuseSoC now picks this duplicate and thereby wrong files.
Opened a PR at ibex: https://github.com/lowRISC/ibex/pull/848
Once this is resolved, you should update the ibex here.

**Comment by rswarbrick** [comment]
As I said at that PR, a quicker solution would be to exclude these files when vendoring back in to OpenTitan. The long-term "proper" solution is for these files to be vendored into Ibex properly. That's on its way soon, I hope.

**Comment by imphil** [comment]
That's fixed now.
