### ISSUE TITLE
[rom,rom_ext] integrate `otbn_boot_services` ECDSA sigverify into ROM/ROM_EXT

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#21550]
Integrate the ECDSA sigverify, embedded in `otbn_boot_services` library, in the ROM/ROM_EXT boot flow.
This will replace the existing RSA secure boot implementation  and trigger the OTBN boot services program to already be loaded by the time the ROM_EXT executes.

**Comment by a-will** [comment]
@moidx Fixed by https://github.com/lowRISC/opentitan/pull/22744 perhaps?

**Comment by moidx** [comment]
Yes. This is correct.
