### ISSUE TITLE
[sw] Enum variables need to be initialized 

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#2157]
I ran into this in PR #2150. 

In this PR, I converted the existing test `sw/device/tests/consecutive_irqs/consecutive_irqs_test.c` to a testlib and I moved it one level up to `sw/device/tests/consecutive_irqs_test.c`. I made the necessary updates to get it working in DV. One such update is to the following line in `handle_uart_isr()` function:
```c
  dif_uart_interrupt_t uart_irq = kDifUartInterruptTxWatermark;
```

The `uart_irq` variable was not initialized before (see the version of this test in HEAD). For whatever reason, on converting this test to a testlib, it had to be initialized to make the error below go away:
```console
../sw/device/tests/consecutive_irqs_test.c: In function 'handler_irq_external':
../sw/device/tests/consecutive_irqs_test.c:72:7: error: 'uart_irq' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   72 |   if (dif_uart_irq_state_clear(uart, uart_irq) != kDifUartOk) {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../sw/device/tests/consecutive_irqs_test.c:46:24: note: 'uart_irq' was declared here
   46 |   dif_uart_interrupt_t uart_irq;
      |                        ^~~~~~~~
```

#### Steps to reproduce
- Checkout PR #2150 locally
- Make the following change in `sw/device/tests/consecutive_irqs_test.c`:
```c
  // dif_uart_interrupt_t uart_irq = kDifUartInterruptTxWatermark;
  dif_uart_interrupt_t uart_irq;
```
- compile the C test by running:
```
ninja -C build-out sw/device/tests/consecutive_irqs_test_export_sim_verilator
```

I dont have a good explanation for why it worked as-is before and why is this change needed after converting it into a testlib.

**Comment by mcy** [comment]
The reason for this is subtle: the relevant code looks like this:
```
enum_t foo;
switch (bar) {
  case kA: 
    foo = kA;
  case kB:
    foo = kB;
  default:
    LOG_FATAL();
}

use_foo(foo);
```

Before your change, `LOG_FATAL()` expanded to `abort()`. `abort()` is `noreturn`, so the compiler can see that regardless of control flow, `foo` is initialized before use. However, `set_test_state()` is *not* `noreturn`, even though for the particular static argument you've passed it is. I think the fix is to either continue using `abort()`, if we really want to leave `uart_irq` uninitialized.

**Comment by lenary** [comment]
Is this resolved?
