### ISSUE TITLE
[sw test] Getting the ISR to be placed at the right location in testlib

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#2162]
I ran into this in PR #2150.

In this PR, I converted the existing tests in  sw/device/tests/* to a testlib and I moved it one level up to sw/device/tests. I made the necessary updates to get it working in DV. One such update is to the following line in `sw/device/tests/meson.build`:
```meson
consecutive_irqs_test_lib = declare_dependency(
  link_with: static_library(
    'consecutive_irqs_test_lib',
    sources: ['consecutive_irqs_test.c'],
    dependencies: [
      dif_uart,
      dif_plic,
      sw_lib_irq,
      sw_lib_mmio,
      sw_lib_base_log,
      sw_lib_runtime_hart,
      sw_lib_testing_test_status,
    ],
  ),
)

foreach sw_test_name, sw_test_lib : sw_tests
  foreach device_name, device_lib : sw_lib_arch_core_devices
    sw_test_elf = executable(
      sw_test_name + '_' + device_name,
      sources: ['main.c'],
      name_suffix: 'elf',
      dependencies: [
        riscv_crt,
        device_lib,
        sw_test_lib,
        sw_lib_uart,
        # T H I S  L I N E  B E L O W
        sw_lib_irq_handlers,
        sw_lib_base_log,
        sw_lib_base_print,
        sw_lib_testing_test_status,
      ],
    )
...
```

What I am highlighting above is the placement of the dependency `sw_lib_irq_handlers`. The `consecutive_irqs_test.c` overrides the weak implementation of `handler_irq_external()` function which is defined in `sw/device/lib/handler.c`. For the SW to jump to the correct address, the `irq_vectors.S` needs to be compiled as a dependency. 

The problem occurs if `sw_lib_irq_handlers` is directly added as a dependency of `consecutive_irqs_test_lib`. The test fails in DV and in Verilator with the following error message:
```console
Simulation running, end by pressing CTRL-c.
TOP.top_earlgrey_verilator.top_earlgrey.u_rv_core_ibex.ibex_tracer_i: Writing execution trace to trace_core_00000000.log
              281841: Illegal instruction (hart 0) at PC 0x2000012c: 0xc78310e7
^CReceived stop request, shutting down simulation.
```
The failure occurs due to improper placement of the ISR. The linker places something else where the ISR should have been, and ends up executing garbage. 

The test passed only if it is added as a dependency of `main.c` instead, even though `main.c` is not using any of that code. 

#### Steps to reproduce
- Checkout this PR locally
- Modify the `sw/device/tests/meson.build`  - move the `sw_lib_irq_handlers` as a dependency of `consecutive_irqs_test_lib` instead. 
- Compile and run the Verilator test:
```console
$  ninja -C build-out sw/device/tests/consecutive_irqs_test_export_sim_verilator
$  build/lowrisc_systems_top_earlgrey_verilator_0.1/sim-verilator/Vtop_earlgrey_verilator   --meminit=rom,build-bin/sw/device/boot_rom/boot_rom_sim_verilator.elf --meminit=flash,build-bin/sw/device/tests/consecutive_irqs_test_sim_verilator.elf
```

**Comment by lenary** [comment]
I think I see what's going on.

All device "executables" need to depend on `sw_lib_irq_handlers`, or another library that provides definitions of the same names, because these names are needed by the CRT. 

I think what's going on here is that `dependencies` of static libraries will only pull in the parts of their dependencies they need, rather than everything, and because the handlers are not called by any other code in `consecutive_irqs_test.c`, it thinks they're unneeded.

**Comment by msfschaffner** [comment]
@sriyerg can this issue be updated or closed?
