### ISSUE TITLE
[flash_ctrl] Reduce severity of ECC error from fatal to recoverable

### ISSUE THREAD

**Issue by jettr** [lowRISC/opentitan#21637]
### Description

We want to give the option for one stage of FW (e.g. ROM) to be able to read a potential candidate for the next stage of FW (ROM_EXT), and treat an ECC failure as a corrupted potential image (similar to signature verification failure) instead of resetting the chip.

See more background discussion in #21353

**Comment by vogelpi** [comment]
After having more context, I think this option makes a lot of sense. IIUC, the alert classification inside the alert handler is quite flexible: once the FW stage of interest has passed, the severity of the corresponding alert can be raised again at the alert handler end. The only difference to the current implementation would then be that the alert would no longer be sticky at flash_ctrl end. But already today, ECC errors inside flash_ctrl don't completely lock up flash_ctrl. It's just that the alert is sticky right now.

**Comment by vogelpi** [comment]
I've now prepared a PR to fix this here: #22431.
