### ISSUE TITLE
[HMAC] The FIFO status never becomes full

### ISSUE THREAD

**Issue by alistair23** [lowRISC/opentitan#2166]
The `FIFO_FULL` bit in the HMAC status register is never set ~~and the `FIFO_FULL` interrupt never triggers.~~

This can be reproduced with the following diff to the OpenTitan repo

```diff
diff --git a/sw/device/lib/hmac.c b/sw/device/lib/hmac.c
index e30e49e8..b33ef184 100644
--- a/sw/device/lib/hmac.c
+++ b/sw/device/lib/hmac.c
@@ -5,7 +5,7 @@
 #include "sw/device/lib/hmac.h"
 
 #include "sw/device/lib/common.h"
-
+#include "sw/device/lib/uart.h"
 #include "hmac_regs.h"  // Generated.
 #include "hw/top_earlgrey/sw/autogen/top_earlgrey.h"
 
@@ -23,24 +23,23 @@ void hmac_init(hmac_cfg_t hmac_cfg) {
   REG32(HMAC_CMD(0)) = 1 << HMAC_CMD_HASH_START;
 };
 
-static int hmac_fifo_depth(void) {
-  return (REG32(HMAC_STATUS(0)) >> HMAC_STATUS_FIFO_DEPTH_OFFSET) &
-         HMAC_STATUS_FIFO_DEPTH_MASK;
-}
-
-static int fifo_avail(void) { return HMAC_FIFO_MAX - hmac_fifo_depth(); }
-
 void hmac_update(const void *data, size_t size_in_bytes) {
   const uint32_t *wp = (const uint32_t *)data;
   uint32_t bytes_per_word = sizeof(uint32_t) / sizeof(uint8_t);
   uint32_t bytes_left_over = (size_in_bytes % bytes_per_word);
   size_t words_remaining = size_in_bytes / bytes_per_word;
+  int i;
 
   // write in all words
   while (words_remaining > 0) {
     if (words_remaining > HMAC_FIFO_GROUP_SIZE) {
-      // wait until FIFO is at least half drained
-      while (fifo_avail() <= HMAC_FIFO_GROUP_SIZE) {
+      // Try to fill up buffer
+      for (i = 0; i < 10000000; i++) {
+        REG32(HMAC_MSG_FIFO(0)) = 0xDEADBEEF;
+      }
+
+      if (REG32(HMAC_STATUS(0)) & (1 << HMAC_STATUS_FIFO_FULL)) {
+        uart_send_str("FIFO FULL\r\n");
       }
 
       // write a whole group
```

The idea of the above code is to write a lot of data to the `MSG_FIFO` register and then see if the `FIFO_FULL` bit is set.

Running this on the current master bistream on the FPGA never prints the  "FIFO FULL" message. ~~I am also unable to trigger the `FIFO_FULL` interrupt.~~

**Comment by cindychip** [comment]
Hi Alistair,

1. I think `intr: fifo_full` is taken away and replaced by `intr: fifo_empty`
2. You can not read status interrupt full is because: when fifo is full, it blocks the tlul transaction by setting `a_ready` to 0. But I think that is a good point - if we block the tlul transaction, status register can never read out "full status". @eunchan could you provide some insight on this?

![image](https://user-images.githubusercontent.com/11466553/81356549-4b34f280-9086-11ea-842e-1c1e77f7964e.png)

**Comment by alistair23** [comment]
Ah, you are right about the interrupt. Sorry, I confused myself.

**Comment by cindychip** [comment]
Oh no worries. Glad i can help.
Not sure if you still need it, but the screenshot below is a case for reading out status data "h'102" -> fifo full bit is up.

I think since status register is not sticky like interrupt, it might be harder to hit the case where fifo_full is set. Maybe you can try to random "i" instead of using a fixed "10000000"?
Hope that helps


![image](https://user-images.githubusercontent.com/11466553/81358898-a36ef300-908c-11ea-8c95-9640ef13f632.png)

**Comment by alistair23** [comment]
The reason why it would be nice to know if the FIFO is to then wait for the interrupt. After writing data you could check if the FIFO is full, if it is stop writing data and wait for the FIFO empty interrupt.

Without knowing that it's full there isn't much of a use for waiting for it to be empty.

**Comment by cindychip** [comment]
Just to clarify, are you suggesting to make the status `fifo_full` bit sticky until the fifo is empty? From what I understand, please correct me if it is wrong - right now, the "status" bit `fifo_full` will set to 1 when fifo is full, and then reset back to 0 as soon as the fifo is not full. 
@eunchan for visibility :)

**Comment by alistair23** [comment]
I assume that is how it works. That is fine as there is also a `fifo_empty` bit so we can tell when it's not empty. I just can't seem to ever see the fifo not be empty.

I am just surprised that on the FPGA platform the HMAC runs fast enough to never fill up when run in a tight loop.

**Comment by eunchan** [comment]
@cindychip is right. as register interface and MSG_FIFO interface shares the same port, TL-UL (window) back-pressuring also affects the reading out of status register. What I talked with Phil was that the full information is not that needed in the software, as it can read the available fifo entries before write to the MSG_FIFO and be able to push the message not to spill over the MSG_FIFO. Empty interrupt is useful for the software to send next message chunk. 

BTW, as you said, with CPU data transfer, HMAC MSG_FIFO cannot be full at all. CPU takes 5 cycles to write a word data into HMAC (load/calc_addr/store) . For 256b (16x32b) message, CPU takes 80 clocks to push, HMAC takes 80 clocks to calculate the hash. exact equilibrium.

**Comment by alistair23** [comment]
Thanks for the clarification. I have a few comments then:

1. If back pressure applies to both `MSG_FIFO` and `STATUS` then I don't see a use for the `FIFO_FULL` bit in the status register. Should it be removed or at least not documented? In which case the fifo length can be used instead as you mention.

2. Could read accesses to `STAUTS` not be back pressured? (then 1 no longer applies).

Ah interesting. From what I can tell OT doesn't have a DMA, so I guess the HMAC can never actually be full.

**Comment by eunchan** [comment]
> Thanks for the clarification. I have a few comments then:
> 
> 1. If back pressure applies to both `MSG_FIFO` and `STATUS` then I don't see a use for the `FIFO_FULL` bit in the status register. Should it be removed or at least not documented? In which case the fifo length can be used instead as you mention.
>
There's a case you can see the FIFO_FULL status. If the core is fast enough, and if the software pushes exact amount that is available in the FIFO, then full condition is set and can be read out.

Yes, that is ridiculous. So I also don't expect that status bit has to be used.

> 2. Could read accesses to `STAUTS` not be back pressured? (then 1 no longer applies).
> 
> Ah interesting. From what I can tell OT doesn't have a DMA, so I guess the HMAC can never actually be full.

**Comment by alistair23** [comment]
Any thoughts on removing it then?

**Comment by tjaychen** [comment]
should we loop back to resolving this? 
Given where we are in the project, I'm inclined to say we should just keep the status indication even if it is not all that useful at the moment.  To @alistair23 point, perhaps this should be better described.  Is that already done @eunchan ? maybe we can close this issue out.
