### ISSUE TITLE
[pinmux] strap pins for functional usage

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2168]
This came up during discussions with the software team.
Even though specific pins are designated as "strap", it would be good to not limit these pins from being used as outputs later on if the integrator chooses to do this.

I believe this is already the case in the design, but wanted to file an issue to confirm we don't accidentally remove this behavior due to other changes in the future.

**Comment by msfschaffner** [comment]
So with the current strap implementation, there is nothing that would limit these pins from being used as outputs. We are placing straps on MIOs exclusively at the moment, and these are under full control of the pinmux matrix. They come up tristated after POR, and sometime during LC init (when the processor has not been released for boot yet) the strap pins are sampled. After that, SW may choose to use these pins however it sees fit.

**Comment by tjaychen** [comment]
sounds good. Thanks @msfschaffner !
Feel free to close this if you feel like this story is final and there's no need to keep a tracking issue.

**Comment by msfschaffner** [comment]
Let's keep it there for now until I did my post-Bronze pinmux update.
