### ISSUE TITLE
[regression] FPV regressions are failing due to dvsim `publish_results()` issue.

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#21694]
### Description

The following error is being thrown by the regression:

```shell
### Saturday February 24 2024 19:33:02 UTC
### GitHub Revision: [`49a27e136c`](https://github.com/lowrisc/opentitan/tree/49a27e136c7b79a3c738dd77cdae3764e19210c0)
### Branch: HEAD

|          name          |  pass_rate  |  stimuli_cov  |  coi_cov  |  prove_cov  |
|:----------------------:|:-----------:|:-------------:|:---------:|:-----------:|
|   aes_masked_sec_cm    |  100.00 %   |      N/A      |    N/A    |     N/A     |
...
Traceback (most recent call last):
  File "util/dvsim/dvsim.py", line 781, in <module>
    main()
  File "util/dvsim/dvsim.py", line 768, in main
    cfg.publish_results()
  File "/container/opentitan-public/util/dvsim/FlowCfg.py", line 574, in publish_results
    item._publish_results(server_handle)
TypeError: _publish_results() takes 1 positional argument but 2 were given
```

FlowCfg.py call site:

https://github.com/lowRISC/opentitan/blob/e0a5f9db7573db704172a7a79776f1f993befe6c/util/dvsim/FlowCfg.py#L564-L574

The issue is probably in FormalCfg.py

https://github.com/lowRISC/opentitan/blob/e0a5f9db7573db704172a7a79776f1f993befe6c/util/dvsim/FormalCfg.py#L250-L263

**Comment by vogelpi** [comment]
It seems that this issue has already been fixed: the dashboards show recent results again:
https://reports.opentitan.org/hw/top_earlgrey/formal/sec_cm/summary/latest/report.html
https://reports.opentitan.org/hw/top_earlgrey/formal/ip/summary/latest/report.html
https://reports.opentitan.org/hw/top_earlgrey/formal/prim/summary/latest/report.html

I am thus closing this issue. Thanks @moidx and @rswarbrick for taking care of this!
