### ISSUE TITLE
[hmac/dv] Verify save & restore

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#21708]
Tentative list of TODOs:
- [ ] Extend testplan and coverplan to test and cover save & restore feature.
- [ ] Enable save & restores in tests and make necessary extensions to the scoreboard as well as `burst_wr_msg` so this gets correctly checked and fully covered.
- [ ] Add additional directed test that covers context switching between multiple message streams (not sure if this has to be an UVM test, maybe a SW test would suffice?).

**Comment by vogelpi** [comment]
@moidx on track according to reports we got today. @andreaskurth agree, TLT in cryptolib is passing now and we made progress in block-level DV. @moidx more TLTs to follow over the next days.

**Comment by martin-velay** [comment]
The current issue can be closed once this PR is merged
- https://github.com/lowRISC/opentitan/pull/23116

as the following issue is overtaking the remaining DV work for M5:
- https://github.com/lowRISC/opentitan/issues/23562

FYI @vogelpi / @johannheyszl

**Comment by moidx** [comment]
Moving this issue to M5, but lets continue to prioritize this to land it by the end of the week if possible.

**Comment by martin-velay** [comment]
Closed as https://github.com/lowRISC/opentitan/pull/23116 has been merged
