### ISSUE TITLE
[manuf,ottf] implement spi_device console over mailbox 

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#21726]
Previously, in #17818, a spi_device OTTF console was added to facilitate manufacturing flows that require used of higher speed IO (than is available with UART). When generic mode was removed in #20856, this feature was also removed, since it made use of generic mode.

To facilitate manufacturing flows for Earlgrey PROD, a new spi_device OTTF console should be implemented using the SPI mailbox.

**Comment by timothytrippel** [comment]
CC: @anthonychen1251

**Comment by anthonychen1251** [comment]
The PRs associated with this task are listed below for the reference
- #24345
- #24366
- #24380
- #24413
