### ISSUE TITLE
[hmac] Verify FIFO empty status interrupt

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#21815]
### Description

When changing the FIFO empty interrupt type from "Event" to "Status" #21809, it turned out that the scoreboard previously tried to model this interrupt cycle accurate. Doing this for the status type interrupt is very challenging (and maybe not needed?). Thus, I've disabled verification of the FIFO empty interrupt (it's currently not being used by software anyway).

For M4/M5, we should verify this interrupt properly.

**Comment by vogelpi** [comment]
Software is currently not using the fifo_empty interrupt and we may thus want to consider de-prioritizing this task @andreaskurth .

**Comment by andreaskurth** [comment]
By @vogelpi: Also, HW is a lot faster at consuming inputs than SW can provide data. So most of the time the FIFO will be empty.
By @moidx: Some Si creator drivers don't even use this for performance reasons.

Agreed in triage to move to M5

**Comment by vogelpi** [comment]
I am closing this as completed as both the DV and the RTL fix have been merged. There is nothing left to do here.
