### ISSUE TITLE
[pwrmgr, doc] Inconsistent register fields for `RESET_EN` 

### ISSUE THREAD

**Issue by ballifatih** [lowRISC/opentitan#21840]
### Description

I was looking at [pwrmgr documentation](https://opentitan.org/book/hw/top_earlgrey/ip_autogen/pwrmgr/doc/registers.html#reset_en) to understand why we have two separate `EN_0` and `EN_1` bits for `RESET_EN` register. Since the documentation does not explain that, I had a look at RTL to see how these bits are used. It turns out that there is only single `EN` bit, so I think the documentation needs to be regenerated.

https://github.com/lowRISC/opentitan/blob/356a47051325226596cbd14bc0eae35765e10418/hw/ip_templates/pwrmgr/doc/registers.md.tpl#L318-L322

It seems like the number of fields in `RESET_EN` register is parameterized with `NumRstReqs`, which is defined as 1 in hjson file:

https://github.com/lowRISC/opentitan/blob/356a47051325226596cbd14bc0eae35765e10418/hw/ip_templates/pwrmgr/data/pwrmgr.hjson#L478-L486

https://github.com/lowRISC/opentitan/blob/356a47051325226596cbd14bc0eae35765e10418/hw/ip_templates/pwrmgr/data/pwrmgr.hjson#L146-L151

Running `util/regtool.py` with `-d` flag generates the correct register documentation, but I am not sure how we are generating documentation for template IPs.

**Comment by matutem** [comment]
pwrmgr is an ipgen block so the "real" artifacts are per top, so for top_earlgrey the documentation and RTL should use hw/top_earlgrey/ip_autogen/pwrmgr/doc, and not the ip_templates tree. The RTL has one reset_en per reset, and there are two in earlgrey.

The way to generate the top_earlgrey artifacts is running topgen: see https://github.com/lowRISC/opentitan/blob/master/hw/Makefile#L134. It boils down to `./util/topgen.py -t hw/top_earlgrey/data/top_earlgrey.hjson`.

I am closing this issue, but you are free to reopen or ask for any clarification.
