### ISSUE TITLE
[ROM] Consider `sensor_ctrl` alerts filter 

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#21871]
### Description

https://github.com/lowRISC/opentitan/pull/21870 added support for filtering `sensor_ctrl` alerts to handle spurious alerts coming from AST. Since the ROM has the ability to configure the alert handler via OTP settings, we should consider adding a mechanism to setup the `sensor_ctrl` alerts as part of the process.

**Comment by moidx** [comment]
HI @andreaskurth, is this issue now superseded by #23150? If so, please feel free to close this issue. Thanks

**Comment by cfrantz** [comment]
ROM sensor-ctrl configuration was added by #23513.
