### ISSUE TITLE
[entropy_src] Functional coverage metrics dropped

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#21888]
### Description

After merging #21369 which made the `rng_fips_o` request bit to the RNG/noise source as well as the `fips_compliance` flag signaled to CSRNG software controllable, the functional coverage for ENTROPY_SRC dropped massively from above 96% to around 46%. The main reason for this massive drop is the coverage cross for the different fields of the CONF register. The PR added two new fields to the CONF register, meaning unless we substantially increase the number of seeds run in simulation, we can cover only about a 4th of the possible configuration settings.

![Screenshot from 2024-03-07 15-28-10](https://github.com/lowRISC/opentitan/assets/20307557/b564a0a9-bfa1-42c4-ace9-c95ae887ea3c)

![Screenshot from 2024-03-07 15-28-48](https://github.com/lowRISC/opentitan/assets/20307557/decb0959-ebc1-44cd-90b3-ae45c337f415)

Since the two new configuration fields directly control a single output bit each and not more, I think we shouldn't spend effort/so much simulation time into getting coverage again to an acceptable level for V2/V2S (90%) and instead not consider these two settings into the crosses.

What is your view @h-filali, @andreaskurth ?

Update:
In addition, also toggle coverage dropped below 90% (currently at 88%). After all these RTL changes, we should probably regenerate the coverage exclusion files.

**Comment by vogelpi** [comment]
For reference:
- the [last report before merging this change](https://reports.opentitan.org/hw/ip/entropy_src/dv/2024.02.08_09.00.50/report.html)
- the [first report after merging the change](https://reports.opentitan.org/hw/ip/entropy_src/dv/2024.02.26_03.33.19/report.html)

**Comment by andreaskurth** [comment]
I agree that the having the two new control fields in the cross doesn't add much value. Do we already measure non-crossed coverage and check their correct implementation in the scoreboard, though?

**Comment by moidx** [comment]
Discussed moving as P1 to M5 due to RTL risk analysis performed during last issue triage.

**Comment by h-filali** [comment]
It might be more interesting to just have a separate cover group which is only for the different fips configurations and remove the fips settings from the other corver groups. Since the fips bit is now software controllable, it should not be related to the other settings.

**Comment by vogelpi** [comment]
This has been taken care of by @h-filali . All coverage metrics should now be above the V2/V2S threshold again. Closing.
