### ISSUE TITLE
[rom] Write value in retention RAM indicate if ROM scrambled it or not

### ISSUE THREAD

**Issue by jettr** [lowRISC/opentitan#21899]
### Description

The owner firmware shouldn't have to duplicate the [ROM logic][0] to deduce whether retention ram has been scrambled or not. It would be nice if the ROM could write a "true"/"false" (using normal hamming distance style) value indicating if ROM scrambled the retention RAM or not.

Owner firmware will need to read this value to handle resetting its retention RAM values back to a good value instead of interpreting the scrambled values as meaningful.

[0]:https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom/rom.c;l=181;drc=97ebef0bbefd6ec273856e993057d4b922d7a947

**Comment by cfrantz** [comment]
Discussed with @jettr today.  I believe the RETRAM SRAM_CTRL status register `INIT_DONE` bit can provide this indication:
- On power-on resets, the ROM initializes RETRAM and the `INIT_DONE` bit will be 1.
- On warm resets, the ROM does not initialize RETRAM and the `INIT_DONE` bit will be 0.

Jett to investigate using this method in the prodc use case.

**Comment by a-will** [comment]
> Discussed with @jettr today. I believe the RETRAM SRAM_CTRL status register `INIT_DONE` bit can provide this indication:
> 
> * On power-on resets, the ROM initializes RETRAM and the `INIT_DONE` bit will be 1.
> * On warm resets, the ROM does not initialize RETRAM and the `INIT_DONE` bit will be 0.

Hm... That doesn't sound right. If `INIT_DONE` goes high once, it will remain high unless init is triggered again or a local escalation occurs. RETRAM SRAM_CTRL and its STATUS CSR don't get reset unless the `Aon` power domain resets are triggered.

However, you might be able to use [SCR_KEY_ROTATED](https://opentitan.org/book/hw/ip/sram_ctrl/doc/registers.html#scr_key_rotated) to detect whether the scrambling key has been changed. This one can be cleared by software, then checked after the reset.

**Comment by a-will** [comment]
However, note that `SCR_KEY_ROTATED` won't tell you if the SRAM has been reinitialized again (i.e. wiped with LFSR data using the _same_ key, using a request where `CTRL.INIT` is 1 and `CTRL.RENEW_SCR_KEY` is 0).

**Comment by cfrantz** [comment]
The title of this bug is somewhat misleading.  The ROM currently never scrambles the RETRAM.  It does initialize the RETRAM upon power-on resets and any other reset indicated by `CREATOR_SW_CFG_RET_RAM_RESET_MASK`.

The initialization of RETRAM fills the RAM with pseudo-random data generated by an LFSR, thus destroying any content that might have been there.

> RETRAM SRAM_CTRL and its STATUS CSR don't get reset unless the Aon power domain resets are triggered.

My observation is that INIT.DONE is set after a POR and clear after other kinds of resets (a `rstmgr` instigated software reset, observing from owner code). 

If I'm incorrect about being able to use INIT_DONE for this purpose, I'm happy to recommend a different solution.

**Comment by a-will** [comment]
> The title of this bug is somewhat misleading. The ROM currently never scrambles the RETRAM. It does initialize the RETRAM upon power-on resets and any other reset indicated by `CREATOR_SW_CFG_RET_RAM_RESET_MASK`.
> 
> The initialization of RETRAM fills the RAM with pseudo-random data generated by an LFSR, thus destroying any content that might have been there.
> 
> > RETRAM SRAM_CTRL and its STATUS CSR don't get reset unless the Aon power domain resets are triggered.
> 
> My observation is that INIT.DONE is set after a POR and clear after other kinds of resets (a `rstmgr` instigated software reset, observing from owner code).
> 
> If I'm incorrect about being able to use INIT_DONE for this purpose, I'm happy to recommend a different solution.

That depends on what you mean by a "warm" reset. I believe INIT_DONE will not reset after waking up from deep sleep (i.e. the deep sleep reset, which doesn't touch the `Aon` power domain resets). For other non-POR types, it should work, since they _do_ hit the `Aon` power domain resets.

**Comment by jettr** [comment]
I can confirm that using `INIT_DONE` versus checking if the reset was caused by Power-on-Reset provide different boolean results when waking from deep sleep. PoR is false while `INIT_DONE` is true. This does not work for us determining if we need to clear the retention ram.

**Comment by cfrantz** [comment]
#23410 Adds a field to the boot_log which records whether or not the ROM initialized the RET-RAM on that boot.
