### ISSUE TITLE
[pattgen] Feature request to avoid glitches

### ISSUE THREAD

**Issue by jesultra** [lowRISC/opentitan#21924]
### Description

ChromeOS intends to use the patterngen IP to temporarily take over control of two I2C wires, in order to generate a special waveform that puts certain ITE chips into bootloader mode.

Ideally, the switch back and forth between I2C IP controlling the wires and patterngen would be without glitches.  I have noticed two undesirable behaviors:

1) When reconfiguring the pinmux to let patterngen control the wires, before starting the patterngen clock, the signals will be driven down, rather than left at the default high level of an I2C bus.
2) When the pattern has run the requested number of iterations, the patterngen IP freezes in a state of driving the output according to the first sample of the repeating pattern, (when the channel enable bit is cleared, the outputs are then driven low.)

The second issue I could work around, by modifying the pattern so that the first sample is at a high level, and by reconfiguring pinmux before clearing the channel enable bit.  The first issue, though, is bound to generate a glitch on the wires.

My proposal is this:
1) Add additional bits to the CTRL register, such that while the pattern generator channel is not enabled, these new control bits will determine the "steady state" output on both clock and data. Four bits in total: PDA_LEVEL_CH0, PCL_LEVEL_CH0, PDA_LEVEL_CH1, PCL_LEVEL_CH1.  (If it proves difficult to support the new bits for clock signal, we could live with having only new steady state bits for the data signal, that is two new bits.  If so, ChromeOS would need to use the data signal of both channels, rather than data and clock signal of one channel.)
2) Make it such that upon completing the requested number of repetitions, the output will immediately go to the configured "steady state" level, rather than the first sample of the repeating pattern.  If this is most easily achieved by letting the hardware clear the ENABLE_CHn bit in the CTRL register, that is fine.

**Comment by andreaskurth** [comment]
This may require changes to pinmux and i2c; to be investigated. Not security-relevant, though, so assigning to M4 with P1.

**Comment by moidx** [comment]
Discussed: Area impact low, complexity low. Required to meet integration requirements.

**Comment by andreaskurth** [comment]
@jesultra: pattgen already has a `polarity` config bit, which defines the polarity of the clock (`pcl`) for each channel. Are you sure that additionally a `pcl_level` config bit is required for each channel? The reason I'm asking is this: If we let `pcl_level` define the value of `pcl` while the pattgen channel is disabled and keep the semantics of `polarity` while the pattgen channel is enabled, there can be spurious transitions when enabling and disabling a channel:

![wavedrom(1)](https://github.com/lowRISC/opentitan/assets/3583291/32f854ea-401c-4279-8ca4-9e4d40afeea0)

The figure shows one channel. The first line shows the value of the `enable` bit, the second line shows the `pda` output (yellow and orange for separate data items), and the third to last lines show the `pcl` output for different `polarity` and `pcl_level` settings. On the third and the last line, `polarity == pcl_level`, so there's no `pcl` transition when the channel gets enabled or disabled. Those transitions are present when `polarity != pcl_level` on the lines between (marked a, b, c, and d). Do we need to support these extra transitions?

**Comment by jesultra** [comment]
@andreaskurth : what I was hoping for was that at the very last transition of the pda line (the third X on your diagram) that the pcl_level would take control of the clock output line, that is, it would not wait for the firmware to clear the enable bit.  Also, transitions _a_ and _c_ on your diagram I was hoping would take place on the very first transition of the pda line.

![patterngen](https://github.com/lowRISC/opentitan/assets/15022811/5036fbad-48f7-4798-b1bf-cf09ef98259d)

Another thing, the other new pda_level should control the level of the pda signal for the entire duration of the shaded area of the pda signal, not merely the periods in which the enable signal is zero.

**Comment by jesultra** [comment]
I want to add that if the requested functionality of pcl_level is not feasible, then the bare minimum ChromeOS would need is that pda_level takes effect in the entire shaded area. Please confirm that it is the case.  (We would then need to use both channels of the pattern generator simultaneously, and not route the clock signal to any pin.)

**Comment by jesultra** [comment]
By the way, the below diagram illustrates the waveform that ChromeOS needs to be able to generate, the top line is the enable signal, which firmware cannot guarantee exacltly when will be cleared, the bottom two lines are the signals we need to put on I2C wires.  If there are other suggestions on how to achieve the below waveforms, sidestepping the issues that I mention at the first post of this Issue that is fine as well.  My proposal for pda_level and pcl_level is just one way of achieving it.

![patterngen2](https://github.com/lowRISC/opentitan/assets/15022811/bf85d0a4-9b42-471c-8238-8ae1c5a20f3f)

**Comment by jesultra** [comment]
Thanks for working on this.  Is there any estimate on when I can try out the logic on my FPGA.  I noticed that the ITE chips appeared to not recognize the waveform generated by the ES chip, possibly because of the glitch at the end.  I would very much like to try updated patterngen logic with the ITE chip, and verify that it works, before it is too late to make further changes.

**Comment by andreaskurth** [comment]
I'll create a branch that implements this. DV will be broken, but we can worry about that later. You should get something to try early next week

**Comment by pamaury** [comment]
Just a note here that the SiVal port that I am currently doing will break as well: #23164

**Comment by andreaskurth** [comment]
Thanks for your feedback, @jesultra. I think I now understand that you want a behavior like this:
![wavedrom(2)](https://github.com/lowRISC/opentitan/assets/3583291/953004ee-ae9e-4ef9-a365-1b69e3cde740)
which I have implemented in draft PR #23198, so when you configure a channel with
- `polarity = 0`
- `inactive_level_pcl = 1`
- `inactive_level_pda = 1`
- `data = 0b1010`
- `len = 3`
- (`reps = 0`, `prediv = 0`)

you should get the following waves on the pins controlled by pattgen:
![image](https://github.com/lowRISC/opentitan/assets/3583291/0fa5c812-2827-4f99-8a42-8dc0db0167f0)
(time folds similar to schematic waves, to show that enable/disable don't affect pda nor pcl)

You should be able to download the bitstream from that draft PR and try it on the target system. Does that SGTY? If so, I'd await your feedback.

**Comment by jesultra** [comment]
Thank you for working on this.  I think I can tell from the diagrams that this PR will satisfy Chrome OS.  I will be able to configure inactive_level_{pcl,pca} before I tell the pinmux to switch the two pins from the I2C IP to the pattern generator, and that way, there will be no glitches on the two normally-high signals, when going in and our of pattern generator mode.
