### ISSUE TITLE
[chip-test] Late debug enablement

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21965]
### Test point name

chip_sw_rv_dm_late_debug

### Host side component

SystemVerilog+Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Unkown

### Emulation Targets

- [ ] None
- [X] CW310
- [X] Hyperdebug + CW310

### Contact person

@msfschaffner @a-will

### Checklist

This test is for covering the RFC #20829 that is implemented in #21964.
We should test the entire truth table below in order to ensure everything plays nicely together at the top-level:

LC State | DIS_RV_DM_LATE_DEBUG (OTP Fuse) | LATE_DEBUG_ENABLE (CSR) | RV_DM reachable via TAP | RV_DM fully ungated
------------|------------|------------|------------|------------
TEST_UNLOCKED* or RMA | x | x | yes | yes
PROD*, RAW or invalid states | x | x | no | no
DEV | kMuBi8True | x | yes | yes
DEV | not kMuBi8True | not kMuBi32True | yes | no
DEV | not kMuBi8True | kMuBi32True | yes | yes

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

**Comment by msfschaffner** [comment]
@rswarbrick FYI

**Comment by andreaskurth** [comment]
@moidx: Worth testing with real ROM

**Comment by andreaskurth** [comment]
@moidx: Do you think this will fit into your workload for M4, or should we reprioritize or reassign? I think this is a more complex feature than the one getting tested by #21990, so maybe this should be priority?

**Comment by vogelpi** [comment]
@moidx: work on track
