### ISSUE TITLE
[chip-test] chip_sw_otp_ctrl_dai_lock

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21990]
### Test point name

chip_sw_otp_ctrl_dai_lock

### Host side component

None

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Unkown

### Emulation Targets

- [ ] None
- [X] CW310
- [X] Hyperdebug + CW310

### Contact person

@msfschaffner, @andreaskurth, @vogelpi, @timothytrippel

### Checklist

This top-level test should test the functionality of the DAI lock register that has been added here: https://github.com/lowRISC/opentitan/pull/21059

The locking mechanism should be used by ROM_EXT long term in order to lock down critical regions.

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

**Comment by andreaskurth** [comment]
@moidx: Do you think this will fit into your workload for M4, or should we reprioritize or reassign?
