### ISSUE TITLE
[sw] MMIO Design Issues

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#2203]
When originally landing the MMIO library, @asb pointed to some potential issues in the design: https://github.com/lowRISC/opentitan/pull/1187#issuecomment-570239639:
> Has a more minimal interface been considered - perhaps one that encourages access to device registers via volatile load/store helper functions and relies on separate helpers for manipulating/masking the value

We seem to be getting closer to doing something like this with #1821 - which created the `bitfield` library, which is now a dependency of MMIO. 

More recently with #2047 we've had to introduce write-only MMIO functions.

It seems now might be a good time to refactor this interface slightly, and I'm filing this issue to start this discussion.

---

My concrete proposal is to move away from functions like `mmio_region_nonatomic_clear_mask32(base, offset, mask, mask_index)` and towards making calls like the following:

```c
// Read current state of the MMIO register into `val`
uint32_t val = mmio_region_read32(base, offset);

// Perform updates to `val` using `bitfield_*` functions
val = bitfield_clear32(val, mask, mask_index);

// write `val` back into MMIO register.
mmio_region_write32(base, offset, val);
```

The idea would be to deprecate everything in `mmio_region_*` that isn't `read<n>` or `write<n>`, and expand the bitfield functions in the bitfield library. Given we have `__attribute__((deprecated(<reason>)))`, I'm not sure we need to refactor all the DIFs immediately, and can still provide the existing API for a transition period. 

This should also have minimal fall-out for the tests, as the tests only mock `mmio_region_read32(…)` and `mmio_region_write32(…)` (and their non-32-bit friends).

One thing I am keen is that we try to keep the bitfield and mmio library APIs as small as we can, and make their functionality composable - something that is not so easy today.

I realise this API is more complex than what we present at the moment - it makes some easy cases longer, but makes some of the more complex cases quite a lot easier.
This also has the potential to allow some of our manipulation of volatile registers to be more efficient, reducing the number of reads and writes. It's true that most of our `dif_*` functions do not do repeated reads/writes to the same offset during a single function call, so this is mostly not an issue.

---

I'm keen to hear any feedback about this issue, such as other points the design should address, or other proposals about this API.

**Comment by silvestrst** [comment]
Just to clarify, you propose to not have `<something>_clear_mask32` helper functions at all, or you proposing to factor them out into their own library?

**Comment by silvestrst** [comment]
I think it makes sense, with `bitfields` library this becomes easy to do. If you need to enable `n` bits, then its as easy as:

```
uint32_t val = mmio_region_read32(base, offset);
val = bitfield_set_bit32(val, bit_index1);
val = bitfield_set_bit32(val, bit_index2);
....
val = bitfield_set_bit32(val, bit_indexn);
mmio_region_write32(base, offset, val);
```

**Comment by lenary** [comment]
As discussed at the meeting yesterday, I'll leave this open for comments until **May 15th**, and then come back with a proposed plan of action.

**Comment by lenary** [comment]
> I think it makes sense, with `bitfields` library this becomes easy to do. If you need to enable `n` bits, then its as easy as:
> 
> ```
> uint32_t val = mmio_region_read32(base, offset);
> val = bitfield_set_bit32(val, bit_index1);
> val = bitfield_set_bit32(val, bit_index2);
> ....
> val = bitfield_set_bit32(val, bit_indexn);
> mmio_region_write32(base, offset, val);
> ```

Yes, The idea is to add functionality to the bitfield library for get, set, clear, mask etc, where that doesn't exist today, but is needed to replace the functionality in the `mmio_region_nonatomic_*` functions.

One related thing that came up at the meeting was the set_bit and clear_bit functions in mmio should maybe be preserved. This does make some sense, as setting/clearing a bit should not take three function calls.

**Comment by silvestrst** [comment]
> One related thing that came up at the meeting was the set_bit and clear_bit functions in mmio should maybe be preserved.

The mentioned functions are R-M-W anyway.
```
Function / mmio_region_nonatomic_clear_bit32
Function / mmio_region_nonatomic_set_bit32
```

On the other hand the following function could stay:
`Function / mmio_region_get_bit32`

**Comment by silvestrst** [comment]
@silvestrst - name dropping, so that correct filter applies when I get notifications.

**Comment by alphan** [comment]
I support this. I think the helper functions in the mmio library has served us well so far but now that we have a good understanding of the kind of operations we need in DIF libraries, this seems like a good time to refactor this functionality to make our APIs more composable.

**Comment by silvestrst** [comment]
I kind of feel its all or nothing, my understanding was that @lenary wanted to strip `mmio` from all `nonatomic` functions. In which case `set/clear` bit functions should go as well. I don't see much difference between these and all the other functions in `mmio`.

**Comment by alphan** [comment]
> I kind of feel its all or nothing, my understanding was that @lenary wanted to strip `mmio` from all `nonatomic` functions. In which case `set/clear` bit functions should go as well. I don't see much difference between these and all the other functions in `mmio`.

I agree, edited my comment for clarity.

**Comment by alphan** [comment]
I think we should consider prioritizing this in the context of #2293. If we move all bit manipulation logic to the `bitfield` library, it would be trivial to support shadow registers by introducing `mmio_shadowed_region_writeX(...)`.

Another concern that I had after looking at #2293 was about the alternative sequence in programmer's model that disables and enables interrupts. While `mmio` is not a DIF library (DIFs must be standalone and should not coordinate cross-functional control), I would like to hear what you think about introducing this additional dependency to `mmio` library. We can also choose to give this responsibility to the driver as suggested in the programmer's model.

**Comment by silvestrst** [comment]
> it would be trivial to support shadow registers by introducing mmio_shadowed_region_writeX(...)

I don't know much about shadow registers, what is different between normal `mmio` access and `shadow mmio`? I guess there is a difference, hence you have proposed a new `mmio_*_writeX(...)` API.

> While mmio is not a DIF library (DIFs must be standalone and should not coordinate cross-functional control), I would like to hear what you think about introducing this additional dependency to mmio library.

Could you please elaborate little bit more, I don't quite understand the issue. `mmio` at the moment is one of the allowed libraries for DIFs to link against. What exactly made you rethink it, and come to the conclusion that it breaks DIF model?

Thanks @alphan , if you could clarify the above for my better understanding, that would be great.

> If we move all bit manipulation logic to the bitfield library

I think even regardless of the above issues, this would be great to get done, as we keep bumping into the absence of these helpers in the library when writing DIFs. It was on my list, but then slipped my mind. I am happy to do the work, but I will only have time, sometime next week. Alternatively if someone have spare time, that would be great.

**Comment by alphan** [comment]
> what is different between normal mmio access and shadow mmio? 

I think you should read the changes in `doc/rm/register_tool/index.md` in #2293 for a better explanation, but in a nutshell shadow registers are a form of protection against fault attacks. In addition to the actual register that is responsible for storage (this is called the _committed_ register in a shadow register), this new primitive has two more registers:  _staged_ register and _shadow_ register. Reads work like regular registers, i.e. you read the value stored in the _committed_ register but writes require writing to the **same** address **twice**. The first write is stored in the _staged_ register and the write operation succeeds only if the value of the second write matches what is stored in the _staged_ register.

> Could you please elaborate little bit more, I don't quite understand the issue.

Since shadow registers require two writes to the same address, the write operation fails if this write sequence is interrupted by another read or write of a different value. Programmer's model has a sequence that disables and re-enables interrupts to guard against such cases. My comment/question was about controlling interrupts from `mmio` if we choose to do it this way.

**Comment by silvestrst** [comment]
I know that this issue has been closed, however it seems that the comment (https://github.com/lowRISC/opentitan/issues/2203#issuecomment-648553410) has not been acknowledged or addressed in this PR.

I think the design idea of mmio library is to only have atomic operations, so I feel like the responsibility for the correct shadow register access should fall onto the user of the mmio library and not the mmio library itself. I think sync issues should be delegated to a higher level driver, and not the DIFs or libraries that they use.

> Programmer's model has a sequence that disables and re-enables interrupts to guard against such cases. My comment/question was about controlling interrupts from mmio if we choose to do it this way.

I think this also should be down to the consumers of DIFs, and not the DIFs or "approved" libraries that DIFs depend on.

**Comment by alphan** [comment]
> I think the design idea of mmio library is to only have atomic operations, so I feel like the responsibility for the correct shadow register access should fall onto the user of the mmio library and not the mmio library itself.

@silvestrst, I agree. The functions that I mentioned/proposed do not have to live in the mmio library. Depending on the level of duplication we can always consider refactoring things out although I don't think we will need that. I think, the most important point was to decouple memory access from bit manipulation so that DIFs could use shadow registers in a scalable/maintainable way, i.e. without having to redefine all mmio functions with bit manipulation for shadow registers.

**Comment by silvestrst** [comment]
Makes sense! Thanks for following up on this thread.
