### ISSUE TITLE
[rv_dm,dv] Extend block-level testing to cover new NDM and WARL behaviour

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#22048]
### Description

Code to implement the behaviour in the design is in PR #22038. We need to:
- Extend the testplan to cover it
- Add functional coverage to make sure we're actually seeing the behaviour
- Strengthen the scoreboard to require the behaviour we expect.
- Write one or more sequences to actually trigger the feature

**Comment by rswarbrick** [comment]
@johngt: As someone with more knowledge of PROD timescales, would you mind trying to figure out which milestone this should be tracked in? (My guess is M4, but I thought I should get a second opinion!)

**Comment by moidx** [comment]
rv_dm DV work carried over to M5.

**Comment by andreaskurth** [comment]
@rswarbrick: Is this planned for M5?

**Comment by rswarbrick** [comment]
It's definitely part of the plan for M5 (honestly, this is part of the V2 verification stage). I'm not certain whether we'll meet the M5 targets for rv_dm, but I don't believe this is any different from the other ones for this block.

**Comment by rswarbrick** [comment]
The main part of this should be completed with #24017. The name of the issue (my fault...) talks about the new WARL behaviour in rv_dm. I'm not entirely sure this is worth testing explicitly, and it *definitely* doesn't need to be part of M5.

**Comment by rswarbrick** [comment]
Following up on this, I realise that the linked PR isn't of the form suggested in the issue description.

- There was an existing test which was basically doing what we needed, so I didn't think there was a need for a tweak to the testplan.
- We don't really have any functional coverage being used for this sort of thing in rv_dm. Honestly, the vseq here is more of a directed test, so fcov might not be the best tool for tracking it.
- Similarly with the scoreboard: this is really a directed test sequence.

**Comment by rswarbrick** [comment]
About the other half of this, I just "bit the bullet" and implemented the obvious check where we write `'1` to `hartselhi` and `hartsello` then read the register back to get the number of harts.

This isn't quite working properly (because of DV problems: we aren't properly updating the RAL in the base classes), but I can look at the waves and I'm convinced that the RTL is handling this correctly.
