### ISSUE TITLE
[chip-test] Extend RV_DM FPGA and DV tests

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#22044]
### Test point name

chip_rv_dm_ndm_reset_req

### Host side component

SystemVerilog+Rust

### OpenTitanTool infrastructure implemented

Unknown

### Silicon Validation (SiVal)

Unkown

### Emulation Targets

- [ ] None
- [X] CW310
- [X] Hyperdebug + CW310

### Contact person

@a-will @msfschaffner @andreaskurth

### Checklist

Extend existing DV and FPGA TLTs to cover the changes made in #22038.
The main change that should be tested is whether the NDM reset tracking and dmstatus.allhavereset / dmstatus.anyhavereset status indication works correctly.
Checking the WARL behavior of the hartsel register is good to do, but secondary. 

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

**Comment by msfschaffner** [comment]
@pamaury @rswarbrick @a-will FYI

**Comment by moidx** [comment]
I don't believe we have any test coverage for this yet. @rswarbrick to confirm. Thanks

**Comment by moidx** [comment]
We'll aim to get some coverage for this new feature as part of M5. The feature itself is aiming to align on RV compliance, but it is not a show stopper for early bring-up and manufacturing flows.

**Comment by andreaskurth** [comment]
@rswarbrick: Could you please check with the SW team if it's possible to implement this for M5, and if not, if we have sufficient coverage in DV TLTs?

**Comment by vogelpi** [comment]
I've now reached out to the software team to ask for help.

**Comment by nbdd0121** [comment]
DV part of this is tracked by #22048 and is already completed. Change this issue to just track FPGA tests.
