### ISSUE TITLE
[ot_certs] create TPM certificate template and generate it during personalization

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#22063]
After addressing #22062:

- [ ] create a TPM certificate template HJSON file
- [ ] generate the TPM TBS cert during personalization (in the FT flow)
- [ ] endorse the TPM cert offline (on the host) during provisioning

**Comment by pamaury** [comment]
Example PR on how to add an extension: #22229

**Comment by timothytrippel** [comment]
This has been implemented.
