### ISSUE TITLE
[sw] PLIC Update Batching API

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#2206]
Based on #2203, a similar issue has come up with the PLIC DIF API:

The PLIC DIF may get a sequence of repeated calls which are hitting the same MMIO fields, which we could try to provide a batch API in the same spirit as #2203 for this - @silvestrst points out the problem here: https://github.com/lowRISC/opentitan/pull/2052#discussion_r418475367 (though he proposes a different, array-based approach, which I am not so convinced by).

My feelings are if we go to a separate bitfield library approach for MMIO, a similar approach could be done for this PLIC API for these batch register update use cases, so the PLIC DIF would present an API to allow a driver or test to be implemented like so:

```c
// this represents a copy of the interrupt enable registers. The data structure is public but
// its fields should be considered private.
dif_plic_batch_enable_state_t temp;

// this reads the current state of the MMIO enable registers into `temp`
dif_plic_irq_get_enabled(base, &temp); 

// Update the temporary structure - I'm not sure if we'll need `base` or not in these calls.
dif_plic_batch_enable([base,] &temp, kTopEarlgreyPlicIrqIdUartTxWatermark);
dif_plic_batch_enable([base,] &temp, kTopEarlgreyPlicIrqIdUartRxWatermark);
// … more …
dif_plic_batch_disable([base,] &temp, kTopEarlgreyPlicIrqId);

// this does the MMIO writes to enable everything that's enabled in `temp` by calls to
// `dif_plic_batch_enable` or `dif_plic_batch_disable`. This isn't actually entirely atomic,
// as the PLIC interrupt enable bits span multiple 32-bit registers.
dif_plic_irq_set_enabled(base, &temp); 
```

(Obviously there are locking issues in this example, as it only works if the enabled interrupts are not changed between `dif_plic_irq_get_enabled` and `dif_plic_irq_set_enabled`).

We could then deprecate and eventually remove `dif_plic_irq_enable_set`, though we could also leave it as it is easier for single-interrupt enable/disables.

---

I'm keen to hear feedback on this proposal, including any design points that I may have missed.

**Comment by silvestrst** [comment]
`dif_plic_batch_enable` I imagine this function will have `null` checks, etc... So the problem still remains of checking error on every call.

I guess `dif_plic_batch_enable` could be renamed slightly, and then it could be used between other functions like `set_prioriry` for example - providing all priorities are the same.

I guess the good thing about this approach is that we don't need to duplicate API, and can transform current functions to take in `dif_plic_batch_enable_state_t`.

**Comment by silvestrst** [comment]
@gkelly @mcy @alphan @jon-flatley - just in case you missed the notification.

**Comment by lenary** [comment]
@silvestrst that is fair - you can't just do something like the following, because if the first one fails you shouldn't do the rest.
```
bool success;
dif_plic_batch_enable_state_t temp;

success = (dif_plic_irq_get_enabled(base, &temp) == kDifPlicOk);
success &= (dif_plic_batch_enable([base,] &temp, kTopEarlgreyPlicIrqIdUartTxWatermark) == kDifPlicOk);
success &= …

success &= (dif_plic_irq_set_enabled(base, &temp) == kDifPlicOk);
```

Hmm

**Comment by lenary** [comment]
Following up from the software meeting yesterday: This proposal is taking suggestions until **15 May**, at which point we will make some decisions about what is next.

**Comment by silvestrst** [comment]
To be honest I am kind of swaying back to the array approach:
```
#define ARRAY_SIZE(x) (sizeof(x) / sizeof(x[0]))

dif_plic_result_t irqs[] = {
  kTopEarlgreyPlicIrqIdUartTxWatermark,
  kTopEarlgreyPlicIrqIdUartRxWatermark,
  kTopEarlgreyPlicIrqIdUartTxEmpty,
  kTopEarlgreyPlicIrqIdUartRxOverflow,
  kTopEarlgreyPlicIrqIdUartRxFrameErr,
  kTopEarlgreyPlicIrqIdUartRxBreakErr,
  kTopEarlgreyPlicIrqIdUartRxTimeout,
  kTopEarlgreyPlicIrqIdUartRxParityErr,
};

dif_plic_result_t result = dif_plic_irq_enable_set(plic, irqs, ARRAY_SIZE(irqs), ..., ...);
if (result != kDifPlicOk) {
...
}
```
Upsides:
- Only have to check return value once.

- No need for extra helper functions like `dif_plic_batch_enable`, `dif_plic_batch_disable`.

- Easier to use.

It is potentially easier to keep several profiles to switch between with your approach.

**Comment by alphan** [comment]
I think there are a number of things that can be improved here: mmio accesses, checking arguments inside the functions, atomicity (all or none), and checking return codes (i.e. ergonomics). It looks like improving the first three will require writing nontrivial functions for each operation that we want to batch. So I focused on the last one and what I have below is basically a variation of @silvestrst's idea that uses an array of structs and a helper function for genericity.

```
// The operation that we want to batch
dif_ip_result_t dif_ip_op(dif_ip_t *ip, t1 p1, t2 p2) {
    ...
    return kDifIpOk;
}
```

The helper (visible only to DIF libraries):
```
// Loops over the array of arguments and calls `step_func` for each step
dif_result_t dif_batcher(dif_result_t (*step_func)(void *, void *, size_t), void *dev, void *args, size_t len_args) {
  int res = kDifOk;
  for (int i = 0; i < len_args; ++i) {
    res = step_func(dev, args, i);
    if (res != kDifOk) {
      return res;
    }
  }
  return res;
}
```
`dif_batcher` introduces a new dependency to DIF libraries that supports batching. It is not a must-have but it may be a good idea if we plan to add several batch operations or want to do something at the beginning or at the end of an operation. Without it, the loop needs to move to `dif_ip_batch_op` below and we don't need `dif_ip_batch_op_step` below.

```
// Struct that holds arguments for each step of a batch operation
typedef struct dif_ip_op_batch_args {
    t1 p1;
    t2 p2;
} dif_ip_op_batch_args_t;

// Performs one step of the batch operation
dif_ip_result_t dif_ip_batch_op_step(dif_ip_t *ip, dif_ip_op_batch_args_t args[], size_t i) {
    return dif_ip_op(ip, args[i].p1, args[i].p2);
}

// Public function
dif_ip_result_t dif_ip_batch_op(dif_ip_t *ip, dif_ip_op_batch_args_t args[] , size_t len_args) {
    return dif_batcher(&dif_ip_batch_op_step, ip, args, len_args);
}
```

And the callsite would look like
```
dif_ip_op_batch_args_t args[] = {
    {...},
    {...},
    {...},
};
if (dif_ip_batch_op(&dif_ip, args, sizeof(args)/sizeof(args[0])) != kDifIpOk) {
   // Error recovery
}
```

Just a note: while this checks the result of each step, the hardware is in an unknown state if a step fails and the caller is responsible for error recovery. We can potentially add that to `dif_batcher` too but wanted to hear your thoughts before going there.

**Comment by lenary** [comment]
@alphan My reaction to that is that I would really rather avoid function pointers that take `void*`, and I'd prefer arrays to function pointers. I'm not sure arrays are the right approach either.

---

In general I don't think we've yet found the right approach for batching updates like this. I'm going to leave this issue open indefinitely while I consider the possibilities. 

In the meantime, let's stick with the current approach of non-batched updates - we can always refactor to a better API later, when we find it.

**Comment by sriyerg** [comment]
I am working on GPIO test at the moment. Invoking PLIC DIFs 32 times is a little ugly. It will be nice to see a solution for this soon.

**Comment by sriyerg** [comment]
> I am working on GPIO test at the moment. Invoking PLIC DIFs 32 times is a little ugly. It will be nice to see a solution for this soon.

Actually nvm, I can just loop it.

**Comment by silvestrst** [comment]
@sriyerg could you point me at the PR please, It would be interesting to see how you are doing it.

Is it something like having an array/structure with IDs, etc... and looping through it in a `for` loop?

**Comment by msfschaffner** [comment]
@alphan @sriyerg can this issue be updated or closed?

**Comment by sriyerg** [comment]
A testutil now satisfies this requirement. 
https://github.com/lowRISC/opentitan/blob/ba061ed571068884e7f9d7bc10d30cbb8dd4ebf9/sw/device/lib/testing/rv_plic_testutils.c#L13
