### ISSUE TITLE
[spi_device,dv] The separate spi_device configs are currently causing test failures in CI

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#22104]
### Description

I can reproduce this by running the following command from a checkout:
```
util/dvsim/dvsim.py hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson --select-cfgs=spi_device -i smoke --fixed-seed=1
```

I think the problem is that the two runs are both writing their output to the same directory and the stuff that looks at the results then gets confused because things have become corrupted.

**Comment by a-will** [comment]
Would the same type of problem be affecting lc_ctrl tests?

https://reports.opentitan.org/hw/top_earlgrey/dv/summary/latest/report.html ended up running tests for both configs for lc_ctrl, but one of them seems to have no results for the majority of tests:

https://reports.opentitan.org/hw/ip/lc_ctrl/dv/2024.03.18_04.36.41/report.html
