### ISSUE TITLE
[hmac/dv] Verify wider digest & configurable key length

### ISSUE THREAD

**Issue by gdessouky** [lowRISC/opentitan#22102]
### Description

Tentative List of TODOs:

- [x] Extend testplan and coverplan (add cover groups) to test and cover the additional digest sizes and key lengths.
- [x] Update the scoreboard and block-level tests to test the new digest sizes X key lengths and read digest CSRs between different digest size/key length configurations.
- [x] Verify the different digest sizes and key lengths in the test vectors tests https://github.com/lowRISC/opentitan/issues/22932
- ~[ ] Extend DIFs and TLTs to verify the additional digest sizes and key lengths supported~ https://github.com/lowRISC/opentitan/issues/22332#issuecomment-2149918855 --> we now have driver-based TLTs that accompanied the driver implementation and give us sufficient coverage at the top level. For M5, we plan to extend the DIFs and build DIF-based TLTs.
- [x] Verify unsupported digest sizes/key lengths once the error flagging to sw has been implemented.
- [x] Extend cryptoc_dpi to test wider digest sizes and different key lengths.
- [x] Stress test changing configuration digest size and key length while hashing.
- [ ] Evaluate coverage and run UNR when RTL is finalized and coverage is increased to generate the new exclusions list https://github.com/lowRISC/opentitan/issues/23683

**Comment by gdessouky** [comment]
The key TODOs left here are:

`- [ ] Verify the different digest sizes and key lengths in the test vectors tests https://github.com/lowRISC/opentitan/issues/22932` which I plan to complete by today. I've already confirmed with @ballifatih that SHA-2 384/512 run with random test vectors interleaved, so I don't expect bugs requiring RTL fixes to surface here.

`- [ ] Extend testplan and coverplan (add cover groups) to test and cover the additional digest sizes and key lengths.` Cover groups have been added @martin-velay, and tests for this feature will be completed once I am done with the test vectors tests above. I only need to update the tests for this feature `wide_digest_configurable_key_length` in the testplan https://github.com/lowRISC/opentitan/blob/master/hw/ip/hmac/data/hmac_testplan.hjson#L119 also today.

`- [ ] Extend DIFs and TLTs to verify the additional digest sizes and key lengths supported.` Current plan (in progress) is to extend the DIFs to be able to program the newer digest sizes and key lengths (currently they are hardwired at SHA-2 256 and 256-bit key) and to add a streaming save & restore TLT that would be effectively testing both (new digest sizes/key lengths + save & restore) features together, see https://github.com/lowRISC/opentitan/issues/22332. I'll align today with @ballifatih on that, but the additional digest sizes and key lengths have already been tested (at top-level) with the ongoing SW driver implementation, and testing out the context switching is also progressing.

**Should be moved to M5:**
- [ ] Evaluate coverage and run UNR when RTL is finalized to generate the new exclusions list -> IMO this makes sense after the DV effort and coverage achieved for `save & restore` also stabilizes.

**Comment by vogelpi** [comment]
@moidx to run UNR. Otherwise good progress so far on the block-level side and TLTs.

**Comment by moidx** [comment]
Moving to M5 with high priority as we are still waiting for increased coverage before running UNR.

**Comment by gdessouky** [comment]
All action items on this list, except UNR (we have a spin-off issue to track coverage and UNR analysis results), have been addressed now. I would close this issue then? @vogelpi @rswarbrick

**Comment by martin-velay** [comment]
If agreed, V2(S) Signoff could be closed for HMAC #22471 as this is the last remaining item.

**Comment by vogelpi** [comment]
This sounds good to me @gdessouky and @martin-velay . I've now adjusted the comment above to link the DIF issue (moved to M7). Thanks for all your hard work on this!
