### ISSUE TITLE
[sw, tock] Error handling in drivers, chip and board

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#2211]
**PROBLEM DESCRIPTION**

Tock Chip integrates with the kernel through `pub trait Chip` trait, of which most functions do not return a value. However, these trait function implementation can fail internally, for example if we trace `service_pending_interrupts` in `chip.rs`:

`service_pending_interrupts(...)` => `handle_plic_interrupts(...)` => `uart::UART0.handle_interrupt(...)`=> `uart::UART0.disable_rx_interrupt(...)` => `dif::dif_bindings::dif_uart_irq_enable(uart, kDifUartInterruptRxWatermark, kDifUartDisable)`

The last function call can fail, and must be handled.

This is just a simple example showing a potential failure as a result of a DIF function call, but the drivers could have conditions of their own that can result in failure.

Similar probably applies to the `board/opentitan` code.

**QUESTIONS**

1. Where should the failures be handled? Directly in the driver, or passed down to the chip?
2. How should we classify the failures (fatal, retry-able, ...)?
3. What to do in case of (fatal, retry-able, ...) failures?

**POTENTIAL SOLUTIONS**

1. I think drivers should possibly pass the errors down to the chip level, as if a failure requires a system reset, or must enter some kind of more complicated "security state", it probably should be done from a chip level. Seems more flexible - **as a crude speculation:** if there can be multiple non-fatal failures that could in combination become a fatal failure, it would be easier to aggregate it on a chip level.

**NOTE: All of this is speculation at this point, but it would be nice to hear what people think about it.**

**Comment by silvestrst** [comment]
@lenary @gkelly @mcy @alphan @jon-flatley

**Comment by silvestrst** [comment]
Related to #2139 .

**Comment by phil-levis** [comment]
@silvestrst This seems like a good question to raise in the core WG. I think the honest answer would be "early implementations did not have error conditions, so we didn't introduce them in the general case." But now that there are error conditions they should be included.

**Comment by alistair23** [comment]
How can enabling interrupts fail though? The bit doesn't stick?

That seems like an unrecoverable error, you can't really pass it back to the interrupt handler.

**Comment by silvestrst** [comment]
I would need to refresh my mind, I have not looked at this since May.

> How can enabling interrupts fail though? The bit doesn't stick?

Perhaps interrupts are not the best example, but DIF API (PLIC in this case) will at least have the following error codes it can return:
```
/**                                                                                                                                                                                                                 
 * The result of a PLIC operation.                                                                                                                                                                                  
 */
typedef enum dif_plic_result {
  /**                                                                                                                                                                                                               
   * Indicates that the operation succeeded.                                                                                                                                                                        
   */
  kDifPlicOk = 0,
  /**                                                                                                                                                                                                               
   * Indicates some unspecified failure.                                                                                                                                                                            
   */
  kDifPlicError = 1,
  /**                                                                                                                                                                                                               
   * Indicates that some parameter passed into a function failed a                                                                                                                                                  
   * precondition.                                                                                                                                                                                                  
   *                                                                                                                                                                                                                
   * When this value is returned, no hardware operations occurred.                                                                                                                                                   
   */
  kDifPlicBadArg = 2,
} dif_plic_result_t;
```
`kDifPlicBadArg` - in particular often means bad input parameters (like `null` handle). In practice I guess for this particular example, it is unlikely there should be some error conditions, however ultimately it depends on whether the driver code does any operations that can fail.

The idea of this issue was to start a conversation about how to handle the errors that originate in drivers. With addition of DIFs there would be at least as many possible error conditions as provisioned by the DIF API.

**Comment by alistair23** [comment]
There are a few different parts here.

I think Tock currently has functions that can reasonably fail, but we don't return failure codes. A good example of this is `configure_mpu()` which could easily fail if all the MPU regions are locked, but we don't return a `Result`. That's also a good example of a place where we have a good fallback, if the PMP can't be configured, don't run the app. My understanding is that OT is going to re-write the arch crate, so I'm not sure how much that impacts OT though.

There are places where maybe where the DIF can fail, but it's not really reasonable for a failure case. For example being in the interrupt handler and disabling interrupts. If that fails what action can you take? You pretty much just have to panic and maybe reboot. So in that case propagating errors up the call stack seems unhelpful, if the DIF call fails just panic.

There are other cases that aren't as clear cut, what happens if the driver `handle_interrupt()` function fails? Is there an action the kernel can take?

How much of this makes it to Tock I'm not sure about though. I suspect most of this will be fully contained inside `arch`, `chips` and `boards`.

**Comment by silvestrst** [comment]
Closing this, we can revisit this when Tock on OpenTitan work resumes.
