### ISSUE TITLE
[csrng] implement context-switching capability

### ISSUE THREAD

**Issue by vsukhoml** [lowRISC/opentitan#22121]
### Description

Currently CSRNG has a single context. This practically allows only `atomic` mode of operation:
1. Instantiate CSRNG in required mode (full entropy or software-only)
2. Run key generation
3. Instantiate CSRNG from entropy source (to discard key specific use).

This single context makes impossible to use CSRNG in multi context environment -- you can't rely on the CSRNG state, when use for key gen it can't be used for anything else, but more importantly in current firmware design DRBG objects are used as a common denominator for key generation. These DRBG objects seeded either using live entropy, hw-backed key or with data from software (entropy stored on flash for deterministic key gen), at different time - DRBG mixes in additional data at one time, and used for key generation at some time later, with 2-3 DRBGs being used at the same time. 

One approach to separate CSRNG from key gen in time is to use fully software DRBG to mix in all key inputs, including derivations from hw_backed keys, and implement cascading DRBG, where randoms from software DRBG will seed CSRNG just before the key gen using software-only inputs.  This approach an issue that DRBG state is unprotected in software,  and more complicated than it can be.

Proposal: implement load/store of CSRNG context in a blinded form, may be bundled with integrity checking via checksum or some other light method. This way software can read out CSRNG content, and restore it, but won't be able to actually interpret it or modify it.
There is no need to make context reloadable after power cycle of OT -- some volatile key can be used for encryption.

**Comment by johannheyszl** [comment]
The root issues is described in #21936. Need for context switching will depend on its resolution.

**Comment by moidx** [comment]
@vogelpi: This requires making the status registers writeable without an area impact. The change can be applied to just the software instance.

Moving to M3 for triaging and implementation target.

@moidx This change will simplify integration with use cases potentially dropping the requirement for a SW based DRBG.

**Comment by vsukhoml** [comment]
it seems CSRNG already supports contexts for applications and EDNs, but they are implicit. If it would be possible to add 1-3 application contexts and make instantiate/generate/reseed command to refer which one to use - this would address the need.

**Comment by vogelpi** [comment]
Adding more hardware contexts is unfeasible for production, from an area, implementation and verification point of view. What could be feasible is to allow software extracting and writing the context of the software instance. Extracting the data is already possible for KATs. Making it writable seems doable.

Everything else is not realistic. This also includes adding context switch capability to the hardware contexts. Because software has no control over when hardware requests updates to these instances.
