### ISSUE TITLE
[Github] Configure the repository to require sign-off for web commits

### ISSUE THREAD

**Issue by kupiakos** [lowRISC/opentitan#22187]
### Description

Twice now I've tried to use the Github web UI to make a one-line change to documentation, and both times they failed CI because I didn't add a signoff to the commit.

Repositories that require signoff are [supposed to mark this in their repo settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository#enabling-or-disabling-compulsory-commit-signoffs-for-your-repository) so that the Github web UI automatically adds it. Please do this to reduce churn.

**Comment by timothytrippel** [comment]
CC: @mundaym

**Comment by mundaym** [comment]
@kupiakos Thanks, sign-off of web UI commits should now be enabled.

**Comment by timothytrippel** [comment]
Thanks @mundaym !

**Comment by kupiakos** [comment]
Thanks @mundaym, I've verified this works with https://github.com/lowRISC/opentitan/pull/22202.
