### ISSUE TITLE
[configuration] Can't configure Nexys Video FPGA Board

### ISSUE THREAD

**Issue by satnam6502** [lowRISC/opentitan#2218]
Profuse apologies: not sure what the right `[topic]` is for this post so I made one up. For a while I have been happily configuring the Nexy Video board and downloading the hello world example and seeing the UART output on my Linux machine via `/dev/ttyUSB2` (or other as appropriate). However, today I can't  see any text on any of the `/dev/ttyUSB*` devices on my machine after configuring a bit file for a recent commit (specifically [27c12ad](https://github.com/lowRISC/opentitan/commit/27c12ad2249f8d38bfaf951757fdf6a3ac28bfba)). I blew away my clone and started from scratch but to no avail. I am slightly inclined to add an ILA that triggers immediately after configuration to look for any wiggles on the UART `TX` but that does seem like a long shot because even the hello world download process does not work which points to something being very wrong with the programming file or the state of the board. I can download other designs to the board and confirm with an ILA that they are working fine. The board itself is on my desk at work and I SSH into the Linux machine it is connected to (I'm not allowed to go into the office).

Has anyone else countered any similar issues with some advice about what to try next? Many thanks.

```console
$ build-bin/sw/host/spiflash/spiflash --input build-bin/sw/device/examples/hello_world/hello_world_fpga_nexysvideo.bin
Running SPI flash update.
Image divided into 10 frames.
frame: 0x00000000 to offset: 0x00000000
Didn't receive correct hash before timeout.
frame: 0x00000000 to offset: 0x00000000
Didn't receive correct hash before timeout.
```

**Comment by satnam6502** [comment]
So I decided to go through all the prerequisites to see if something needed updating. Only the RISC-V toolset got updated and then I rebuilt afresh. After that connecting to the board worked!

```console
I00000 boot_rom.c:35] Version:    opentitan-snapshot-20191101-1-1182-g2aedf641
Build Date: 2020-05-13, 15:04:09

I00001 bootstrap.c:138] Bootstrap requested, initialising HW...
I00002 bootstrap.c:142] HW initialisation completed, waiting for SPI input...
I00003 bootstrap.c:92] Processing frame #0, expecting #0
I00004 bootstrap.c:112] Flash erase successful
I00005 bootstrap.c:92] Processing frame #0, expecting #1
I00006 bootstrap.c:92] Processing frame #1, expecting #1
I00007 bootstrap.c:92] Processing frame #0, expecting #2
I00008 bootstrap.c:92] Processing frame #2, expecting #2
I00009 bootstrap.c:92] Processing frame #0, expecting #3
I00010 bootstrap.c:92] Processing frame #3, expecting #3
I00011 bootstrap.c:92] Processing frame #0, expecting #4
I00012 bootstrap.c:92] Processing frame #4, expecting #4
I00013 bootstrap.c:92] Processing frame #0, expecting #5
I00014 bootstrap.c:92] Processing frame #5, expecting #5
I00015 bootstrap.c:92] Processing frame #0, expecting #6
I00016 bootstrap.c:92] Processing frame #6, expecting #6
I00017 bootstrap.c:92] Processing frame #0, expecting #7
I00018 bootstrap.c:92] Processing frame #7, expecting #7
I00019 bootstrap.c:92] Processing frame #0, expecting #8
I00020 bootstrap.c:92] Processing frame #8, expecting #8
I00021 bootstrap.c:92] Processing frame #0, expecting #9
I00022 bootstrap.c:92] Processing frame #9, expecting #9
I00023 bootstrap.c:122] Bootstrap: DONE!
I00024 boot_rom.c:44] Boot ROM initialisation has completed, jump into flash!
I00000 hello_world.c:30] Hello World!
I00001 hello_world.c:31] Built at: May 13 2020, 15:27:31
I00002 demos.c:17] Watch the LEDs!
I00003 hello_world.c:44] Try out the switches on the board
I00004 hello_world.c:45] or type anything into the console window.
I00005 hello_world.c:46] The LEDs show the ASCII code of the last character.
I00006 demos.c:49] GPIO switch #7 changed to 1
I00007 demos.c:55] FTDI control changed. Enable JTAG.
```

and on the console:
```console
$ build-bin/sw/host/spiflash/spiflash --input build-bin/sw/device/examples/hello_world/hello_world_fpga_nexysvideo.bin
Running SPI flash update.
Image divided into 10 frames.
frame: 0x00000000 to offset: 0x00000000
frame: 0x00000001 to offset: 0x000003d8
frame: 0x00000002 to offset: 0x000007b0
frame: 0x00000003 to offset: 0x00000b88
frame: 0x00000004 to offset: 0x00000f60
frame: 0x00000005 to offset: 0x00001338
frame: 0x00000006 to offset: 0x00001710
frame: 0x00000007 to offset: 0x00001ae8
frame: 0x00000008 to offset: 0x00001ec0
frame: 0x80000009 to offset: 0x00002298
```

Phew! Thank you. In future I shall try to check the requisites for upgrade if something similar happens again.

**Comment by ladmangesh805** [comment]
Thanks @satnam6502 
I am also facing the same issue.
Please you can change print Hello_world to something else check the  output for me??
I have changed the print statement then also output is showing same result..Please check and let us know.

**Comment by ladmangesh805** [comment]
When I changed the C file I follow the steps like:
https://docs.opentitan.org/doc/ug/getting_started_fpga/#testing-the-demo-design
--> Only the steps for testing demo .
--> Is their another steps to follow to check changes in C file Code.
-->I debug Bit stream from Hardware manager.
Thanks
