### ISSUE TITLE
[spi_host,dv] Check enable deassertion logic for Dual/Quad segments

### ISSUE THREAD

**Issue by hcallahan-lowrisc** [lowRISC/opentitan#22182]
### Description

As described [in this comment](https://github.com/lowRISC/opentitan/pull/21338#issuecomment-1984908004) and fixed[ in this PR](https://github.com/lowRISC/opentitan/pull/22040#discussion_r1534369921), the TLT `chip_sw_spi_host_tx_rx` stimulated a failure when the SIO enable was used to mask the non-transmitting wire `sd_en_o[0]` in Standard Mode RxOnly segments ([original issue](https://github.com/lowRISC/opentitan/issues/14969)). 
This TLT generates stimulus that is significantly different to the block level DV environment, and it should be investigated if the same incorrect enable deassertion can be observed when using Dual or Quad mode segments. This will require block level DV enhancements to stimulate any degenerate behaviour.

**Comment by antmarzam** [comment]
> @antmarzam Maybe you can help @hcallahan-lowrisc on this one?

Sure - Happy to help! :)

I just had a chat with Harry about this, and have now an idea about how to tackle this (typing it here for future reference):
1 - Roll spi_host RTL back before this fix
2 - Write an assertion and ensure it fires when running the test in https://github.com/lowRISC/opentitan/pull/21338#issuecomment-1984908004
3 - Place the assertion in parallel for each of the SPI lanes 
4 - Ensure we get stimulus in the block-level TB which fire the assertion (for lane=0)
5 - Update spi_host RTL to the latest and make sure assertion no longer fires.
6 - Generate the stimulus needed to reproduce the same issue for 2 or 4 lanes
7 - Add some FCOV to see these scenarios are hit by the block level TB

**Comment by a-will** [comment]
For what it's worth, I've managed to spot check a few combinations (1-4-4 and 1-2-2 reads), and the waveforms looked fine.

**Comment by antmarzam** [comment]
This can be closed since both DV and RTL changes are in master
