### ISSUE TITLE
pad integration features

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2220]
just starting an issue to track some of the features we'll need on the pad.

- we'll need a way to route "analog" signals.  Ie, these signals touch a particular dedicated pad and then go directly to another non-peripheral module

- we'll need a way to route analog debug signals onto MIOs.  This is used for analog debug.  In this state, it is expected the user will need to manually disable all drive, pu, pd and allow the analog to "short" to the pad and basically take over.

It's not really clear to me how we want to integrate with these features, but I wanted to list them first.

**Comment by tjaychen** [comment]
@msfschaffner  / @zi-v 

specifically for the second point, should we just directly connect them in `top_earlgrey_asic`? Seems like that would be sufficient, especially since the idea is that software / jtag would be used to tri-state the pads.

@zi-v 
this does imply that by default AST should probably not drive the debug signals until enabled.  Does that work for you?

**Comment by sjgitty** [comment]
Yeah, this feels like a back-end issue, but we'll need a way to convey that
information to the P/R

**Comment by msfschaffner** [comment]
Yeah it feels like a back-end thing. Although it probably makes sense to hook these up in RTL since these signals are already defined in the AST interface that is visible in RTL. As for the pad attributes... I also think that those should be manipulated via jtag / padctrl.

**Comment by tjaychen** [comment]
@arnonsha i think this is more of a padring / top level thing as we discussed.
Let me know if you disagree.

**Comment by arnonsha** [comment]
As we agreed, Analog signals will be connected in top_earlgrey_asic hierarchy to the ast ast2pad_*_ao and oad2ast_*_ai pins.
for example

> .ast ast2pad_t0_ao (IOA1)

**Comment by tjaychen** [comment]
sounds good, thanks for confirming @arnonsha

**Comment by tjaychen** [comment]
@arnonsha FYI

**Comment by tjaychen** [comment]
this i believe is already handled at `top_earlgrey_asic`. We agree on the approach already, so the issue can be closed.
