### ISSUE TITLE
[top_earlgrey] Add another 8KB ram for retention purposes

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2221]
we want to add another generic ram for retention purposes.

Unlike the main ram, we probably want this one to be on the slower domain to ensure we don't put any leaky cells around.  So this probably means it should be connected to the peripheral xbar instead of the main xbar. 

Additionally, @msfschaffner and I should probably do some studying of the memory compilers to see what flavor best fits this and feed this information back to partners.

**Comment by eunchan** [comment]
Is making main memory self-retention takes a lot more power?

**Comment by msfschaffner** [comment]
Hm... It is probably easier for PD to place this in the AON domain if we separate it...

Should this support scrambling as well?

**Comment by sjgitty** [comment]
@tjaychen would this change the requirements on the main ram? no longer needs to retain over deep sleep?

**Comment by tjaychen** [comment]
great questions!

So this memory was specifically requested because Nuvoton did not want to
make the main memory retention capable.  The leakage overhead (even with
array shutdown) is actually fairly high, and they of course have
floorplanning and power routing concerns.

As for placement of the memory, my assumption is actually it would be
easier for PD if we did not require this to be in the always on domain.
Michael that's why I think you and I need to find some time to dig through
some of the memory compiler docs to see if we have any reasonable dual rail
options.
If for example there is a version of the memory where the array supply and
peripheral supply were explicitly separated, AND the peripheral supply is
allowed to shut down, this in theory means the memory can be placed in
non-always-on region.

**Comment by msfschaffner** [comment]
It looks like there are is such a dual-rail option, but the documentation is not very specific on how it can be used. We should discuss this with Nuvoton.

**Comment by tjaychen** [comment]
sounds good! thanks for digging this up Michael.

**Comment by tjaychen** [comment]
Done in #2672.  In the end only 4KB was added. 
Nothing special with this memory, it will just be plopped down in always on space.

There is a separate effort to wrap major memories up in comportable controllers, but that will be a separate discussion.
