### ISSUE TITLE
Question about registers with different names but identical layout

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#2222]
This is relatively minor but since it comes up in every DIF library, I thought it would be a good idea to open an issue. Please note that the discussion below is specific to interrupt registers but there may be other cases.

OpenTitan peripherals typically have three interrupt registers: state, enable, and test. DIF libraries typically expose interrupt functionality via four functions: enable/disable, get, clear, test. For a given device, these registers have the same layout, but because their `define`s in the generated header have different names, the same layout is --typically-- duplicated three or four times in the DIF library (in the form of multiple switch statements). I was wondering if it would be possible to define this layout only once in the generated headers so that this duplication in DIF libraries can be safely avoided (as opposed to using only one set of `define`s and assuming the others will not change).

**Comment by alphan** [comment]
@gdk @mcy @silvestrst @lenary @jon-flatley

**Comment by lenary** [comment]
Good news! This is done for the interrupt registers as of #1881. There are still cases where these might not be generated, but most peripherals can use the `#define`s added in that PR. (`rv_timer` is one that cannot).

I'm not sure we yet have other registers that do the same - but yes I agree we should keep an eye on this.

**Comment by silvestrst** [comment]
I ran into this problem a while ago (#1206  ) and @lenary has fixed it in #1881 .

**Comment by alphan** [comment]
Awesome, thanks!
