### ISSUE TITLE
[ci] SAM3x problems on the CW310

### ISSUE THREAD

**Issue by jwnrt** [lowRISC/opentitan#22225]
### Description

We've had a few problems with the SAM3x on the CW310 FPGA boards recently.

* @pamaury observed that `0xff` bytes were being added to UART traffic between the SAM3x and OpenTitan device. Reliably reproducible on multiple boards, but only on firmware version 1.2.0 (and not 0.40.1 or 1.3.0)
* We updated our FPGA boards in CI to use firmware version 1.3.0, however we observed two new errors here:
  * Reading the PLL failed (and therefore so did setting the PLL and flashing SAM3x firmware).
    ```
    ./bazelisk.sh run //sw/host/opentitantool -- --interface=cw310 fpga set-pll
    Error: PLL programming failed: CDCE906 read error: 3
    ```
  * After some period of time running fine, the boards would stop responding to USB traffic, though we didn't investigate very deeply before downgrading.
    ```
    (12:36:59) INFO: Running command line: bazel-bin/sw/host/opentitantool/opentitantool '--rcfile=' '--interface=cw310' fpga clear-bitstream
    [2024-03-25T12:37:00Z ERROR opentitanlib::util::usb] Could not read serial number from device at bus=1 address=94: Operation timed out
    Error: Found no USB device
    ```

As of writing, the boards in our CI are using version 1.2.0 with the UART bug. Note that downgrading from 1.3.0 to 1.2.0 requires shorting J20 on the board to erase the firmware since connecting with the `chipwhisperer` python library fails.

See https://github.com/lowRISC/opentitan/issues/22152 for the UART errors we saw on 1.2.0

We got the binaries from:

* [1.2.0](https://github.com/newaetech/cw310-bergen-board/blob/main/microfw/CW310/Debug/CW310.bin)
* [1.3.0](https://github.com/newaetech/cw310-bergen-board/blob/main/microfw/CW310/src/CW310.bin)

**Comment by johngt** [comment]
Also CC @a-will / @alees24

**Comment by alex-dewar** [comment]
I think I've fixed the PLL read error on this firmware: https://github.com/newaetech/cw310-bergen-board/blob/main/microfw/CW310/src/CW310.bin

BTW, if you're unable to connect, you can erase firmware as follows:

```python
from chipwhisperer.hardware.naeusb.naeusb import quick_firmware_erase
quick_firmware_erase(0xC310)
```

I'll see if I can replicate the second issue. Any estimates on how long it takes for that to pop up?

**Comment by jwnrt** [comment]
> BTW, if you're unable to connect, you can erase firmware as follows:

Thank you, this is a lot easier than reaching J20 in our little cupboard

> I'll see if I can replicate the second issue. Any estimates on how long it takes for that to pop up?

We updated the firmware at 9:30 on Friday and had the first failure around 12:30. The problem went away when I fully power cycled it. Three boards then failed again some time on Saturday (obviously we run fewer jobs on them over the weekend) and then a fifth failed around 12:30 Monday.

They all had at least one successful run through our CI test suite and most successfully did many runs.

**Comment by alex-dewar** [comment]
Alright, that doesn't sound too bad to replicate. I'll have a go and let you know if I run into the issue.

**Comment by alex-dewar** [comment]
BTW, any other commands I should be running? I've just got it repeating `bazel-bin/sw/host/opentitantool/opentitantool '--rcfile=' '--interface=cw310' fpga clear-bitstream`

**Comment by jwnrt** [comment]
It could be something our tests do that causes the failure, but running the CI suite isn't so easy. Could it have been the same error as the PLL one?

We could also take your PLL fix and apply it to one of our CI boards and let it run through CI to see if it still triggers, but I won't be able to do that until a week from now.

**Comment by alex-dewar** [comment]
It's hard to say exactly what's causing it. It would be helpful if you could run it through your CI to see if the issue's still there, though if it is I'll probably have to be able to replicate it to figure out what's going on.

**Comment by alex-dewar** [comment]
I haven't been able to replicate this. It would be good to know what commands were being run when the error occurred.

**Comment by jwnrt** [comment]
It's difficult to narrow down which command causes it from our whole CI pipeline especially since it didn't appear on every run. I would suggest we deploy the firmware with the PLL read fix to one board in CI and monitor it for a while. If it does break down again it could be easier to narrow down the cause on that one board.

**Comment by jwnrt** [comment]
> I haven't been able to replicate this. It would be good to know what commands were being run when the error occurred.

The USB error has cropped up on our CI again with no changes to the firmware, so we think it might be a separate issue. Thank you very much for fixing the PLL read issue, and sorry if you spent a lot of time trying to reproduce the USB error...

**Comment by alex-dewar** [comment]
Just wanted to give a quick update that the v1.4.0 firmware is out with the I2C fix

**Comment by jwnrt** [comment]
Thanks Alex, we’ve got it on one of our FPGAs running the full CI suite a few times to see how it goes.
