### ISSUE TITLE
Update HW IP version numbers

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#22222]
Since Earlgrey-ES TO, we made multiple changes to HW IP modules that demand an increase of the version number, but we haven't updated all versions. To resolve this issue, we need to go through the changes for each IP and decide on the new version number.

To determine the new version number, we apply [semantic versioning](semver.org) to HW IP blocks with a focus on the HW/SW interface. (The focus is not on HW interfaces because those aren't well-defined: for an RTL designer only the ports and parameters of the top-most module may be relevant, while for an engineer working on synthesis or physical design any signal in the internal structure of a HW block could be relevant.)  Specifically, the algorithm to determine whether the patch version, minor version, or major version need to be increased for PROD compared to ES is as follows:
- Did the HW get changed functionally? That is, does the HW behave differently? If so, at least the **patch version** needs to be increased.
- Did SW-visible functionality get changed? For example, were new features added (which are disabled by default and can be enabled by SW)? If so, at least the **minor version** needs to be increased.
- Is the HW backwards-incompatible with SW? That is, would SW written for the previous HW no longer work with the new HW (because at least one register field got changed, for example)? If so, the **major version** needs to be increased.

The results are as follows (details in [this table (OT domain)](https://docs.google.com/spreadsheets/d/1H5s7TOktwA6xD2aXKgw7osg7LBq3IYqueXwlENhwuFc/edit)):

HW IP Block | Version for ES/Z1 | Version for PROD/A1: is currently | Version for PROD/A1: should be
-- | -- | -- | --
adc_ctrl | 1.0 | 2.0.0 | 2.0.0
aes | 1.0 | 1.0.0 | 1.0.1
alert_handler | 1.0 | 1.0.0 | 1.0.1
aon_timer | 1.0 | 2.0.0 | 2.0.0
clkmgr | 1.0 | 1.0.0 | 1.0.1
csrng | 1.0 | 2.0.0 | 2.0.0
edn | 1.0 | 2.0.0 | 2.0.0
entropy_src | 1.0 | 2.0.0 | 2.0.0
flash_ctrl | 1.0 | 2.0.0 | 2.0.0
gpio | 1.1 | 1.1.0 | 1.1.0
hmac | 1.0 | 2.0.0 | 2.0.0
i2c | 1.0 | 2.0.0 | 2.0.0
keymgr | 1.0 | 1.0.0 | 2.0.0
kmac | 1.0 | 2.0.0 | 2.0.0
lc_ctrl | 1.0 | 2.0.0 | 2.0.0
otbn | 1.0 | 1.0.0 | 1.1.0
otp_ctrl | 1.0 | 2.0.0 | 2.0.0
pattgen | 1.0 | 1.0.0 | 1.1.0
pinmux | 1.0 | 1.0.0 | 1.1.0
pwm | 1.0 | 1.0.0 | 1.0.0
pwrmgr | 1.0 | 1.0.0 | 1.0.1
rom_ctrl | 1.0 | 1.0.0 | 1.0.1
rstmgr | 1.0 | 1.0.0 | 1.0.0
rv_core_ibex | 1.0 | 1.0.0 | 2.0.0
rv_dm | 1.0 | 2.0.0 | 1.1.0
rv_plic | 1.0 | 1.0.0 | 2.0.0
rv_timer | 1.0 | 1.0.0 | 1.0.0
sensor_ctrl | 1.0 | 2.0.0 | 2.0.0
spi_device | 1.0 | 2.0.0 | 2.0.0
spi_host | 1.0 | 1.0.0 | 2.0.0
sram_ctrl | 1.0 | 1.1.0 | 1.1.0
sysrst_ctrl | 1.0 | 2.0.0 | 2.0.0
uart | 1.1 | 2.0.0 | 2.0.0
usbdev | 1.0 | 1.0.0 | 2.0.0

**Comment by andreaskurth** [comment]
No version numbers in ROM, chip version from lc_ctrl is used. We should do this before taking the tapeout branch, so M5.

**Comment by johngt** [comment]
Discussed with @vogelpi 
Needs to be done before branching
@andreaskurth
