### ISSUE TITLE
[python3.6] jinja2 cannot be loaded

### ISSUE THREAD

**Issue by anudeepdharavathu** [lowRISC/opentitan#22244]
### Description

![image](https://github.com/lowRISC/opentitan/assets/112287808/1be0d9c9-2f7e-418c-a227-527f762ed527)

I have installed all the Python dependencies, and I run "util/dvsim/dvsim.py hw/ip/uart/dv/uart_sim_cfg.hjson -i uart_smoke --waves fsdb --tool vcs"
it shows the below error.
any help is appreciated.
Please let me know if you need more information.

**Comment by anudeepdharavathu** [comment]
[build.log](https://github.com/lowRISC/opentitan/files/14751218/build.log)

**Comment by andreaskurth** [comment]
Hi @anudeepdharavathu, thanks for reporting this issue. From the logs I see that you're using Python 3.6. Our [officially supported development environment](https://opentitan.org/book/doc/getting_started/index.html) is based on Ubuntu 20.04 LTS, which features Python 3.8. Python 3.6 has reached its end of life at the end of 2021, so we cannot help you with this issue.
