### ISSUE TITLE
[i2c,dv] Verify SMBus NACK restrictions

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#22254]
SMBus requires target devices to never NACK their own address. So even if the ACQ FIFO is full, the byte *after* the address must be NACK'd. (We assume that for reads it's okay to NACK the address, because that's the only position where we as target device ACK/NACK.) This was implemented in PR https://github.com/lowRISC/opentitan/pull/21857 and now we need to verify it in DV.

**Comment by andreaskurth** [comment]
@a-will: You may have already partially covered this in your recent TLT, no?

**Comment by a-will** [comment]
> @a-will: You may have already partially covered this in your recent TLT, no?

I don't think I covered the explicitly specified case in your comment. The TLT doesn't attempt to construct a case where the OT target times out with a full ACQ FIFO on the address stretch.

What it _does_ cover is being able to selectively ACK or NACK data bytes (following the address).

**Comment by andreaskurth** [comment]
> What it does cover is being able to selectively ACK or NACK data bytes (following the address).

Thanks, so the MCTP part of this, which is tracked in #22256, is covered at the top level by your PR #21857, right? Then what remains for #22256 is to cover this at the block level.

**Comment by a-will** [comment]
> > What it does cover is being able to selectively ACK or NACK data bytes (following the address).
> 
> Thanks, so the MCTP part of this, which is tracked in #22256, is covered at the top level by your PR #21857, right? Then what remains for #22256 is to cover this at the block level.

Yes, that's right.

**Comment by moidx** [comment]
I2C DV carried over to M5.

**Comment by hcallahan-lowrisc** [comment]
The feature described in this issue (Target-Mode never NACK'ing its own address, even when the ACQFIFO is full) is described in the block-level [testpoint "target_mode_nack_generation"](https://github.com/lowRISC/opentitan/blob/a7f8506592a2eff50cbfaa74f23ffc4283841bbc/hw/ip/i2c/data/i2c_testplan.hjson#L573-L611), and will be covered by #23192 is merged.

**Comment by hcallahan-lowrisc** [comment]
Closed by #23192
