### ISSUE TITLE
[i2c,dv] Verify handling of max-length SMBus messages

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#22252]
In PR https://github.com/lowRISC/opentitan/pull/21789, we increased the depth of the ACQ FIFO so it can absorb max-length SMBus messages (see the linked PR for a description of such messages) without having to rely on SW to drain the FIFO. We should **add a directed (or tightly constrained) test to check that this holds**, first for the simple case in which the ACQ FIFO starts empty. We should then **add tests** (or extend the previous test) **to cover more complex scenarios**, in which the ACQ FIFO is already almost full and SW is already draining it or will soon start to drain it, and a max-length SMBus message arrives (SW should be modeled such that it drains the ACQ FIFO fast enough that it never overflows; otherwise the i2c IP would have to NACK, which is a separate issue).

**Comment by moidx** [comment]
I2C DV carried over to M5.
