### ISSUE TITLE
[prim] Remove defines to load memories from file

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2225]
We currently have a define in our RAM and ROM primitives, which can be set to a file name to load all the memory contents from a file. That functionality works reasonably well as long as we have a single RAM or ROM in the system, but breaks beyond that.

We should remove those defines altogether and use parameters or other mechanisms instead. This will require a bit more parameter passing around through the hierarchy, but the relevant modules (especially the ROM) isn't buried too deeply in the hierarchy for that to be practical.

https://github.com/lowRISC/opentitan/pull/2205#issuecomment-627690483

**Comment by tjaychen** [comment]
sgtm! I'm all for parameter passing.
