### ISSUE TITLE
[manuf] provision owner configuration block during personalization

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#22266]
### Description

When the chip is personalized, an owner configuration block may be provisioned so that a post-provisioning ownership transfer process does not need to be run on each device. Integrating this into the personalization flow will entail:
- [ ] provisioning an owner configuration block into the OwnerSlot0 flash info page, and
- [ ] updating the boot log to indicate the chip is "ownd".

**Comment by cfrantz** [comment]
#25258
