### ISSUE TITLE
[entropy_src] software `poll mode` operations

### ISSUE THREAD

**Issue by vsukhoml** [lowRISC/opentitan#22295]
### Description

FW Override after Observe FIFO (32x32) practically enables `poll` mode of operations. Are there any changes needed to implement following mode:

1. Enable FW override to read data (but not write).
2. Disable path starting with precon packer, conditioner to reduce power
3. Disable interrupts from entropy source
4. Use status register to detect that observe FIFO has at least 32 bits to read. Can `OBSERVE_FIFO_DEPTH` register be it? Any tests for its correctness?
5. Read from FIFO ( via `fw_ov_rd_data.d`) kicks new bits from entropy source to forego health checks and be added to FIFO
6. Health checks can run, report alerts available to firmware, but do not stop random bits from being added to FIFO
7. When FIFO is full, stop the entropy source to reduce power consumption

I suppose there should be some signal to CSRNG that entropy is not available (es_entropy_valid?). 

What about same as above, but on step 4 read is from `entropy_data.d`?

**Comment by vogelpi** [comment]
This hopefully answers some of your questions: https://opentitan.org/book/hw/ip/entropy_src/doc/programmers_guide.html#firmware-override--bypass-modes @vsukhoml

**Comment by vsukhoml** [comment]
@vogelpi , thanks!  FW override mode is most likely what I'm looking for, but few more specific questions:
1. When [Startup health testing](https://opentitan.org/book/hw/ip/entropy_src/doc/theory_of_operation.html#startup-health-testing) is not yet completed (e.g., entropy source was complete disabled, and now enabled) and one or all health tests are enabled, will Observe FIFO be getting anything or these samples will be dropped until required number of samples is tested?  If firmware plans to implement additional checks, it would be more correct to receive all samples.

2. I assume that if fw disables health test, then Observe FIFO will immediately start receiving samples. Is it correct?

**Comment by vogelpi** [comment]
> @vogelpi , thanks! FW override mode is most likely what I'm looking for, but few more specific questions:
> 
>     1. When [Startup health testing](https://opentitan.org/book/hw/ip/entropy_src/doc/theory_of_operation.html#startup-health-testing) is not yet completed (e.g., entropy source was complete disabled, and now enabled) and one or all health tests are enabled, will Observe FIFO be getting anything or these samples will be dropped until required number of samples is tested?  If firmware plans to implement additional checks, it would be more correct to receive all samples.

Please note the difference between Firmware Override: Observe and Firmware Override: Extract & Insert mode (yes I did come up with these names and they are probably not the best but I had to better distinguish them in the design and doc when starting working on this). The Observe FIFO will always get the samples independent of which Override mode is running. But when running in Extract & Insert, no startup testing is performed (the assumption is that software needs to do that). When running in Observe mode, the startup testing is performed by the hardware.

>     2. I assume that if fw disables health test, then Observe FIFO will immediately start receiving samples. Is it correct?

The only way to "disable" the health tests is configuring very relaxed thresholds.
