### ISSUE TITLE
[hmac,rtl] Flag error for invalid digest size/key length configuration

### ISSUE THREAD

**Issue by gdessouky** [lowRISC/opentitan#22312]
### Description

Unsupported/invalid digest sizes and key lengths are now mapped to SHA-2 256 and 256-bit key. We should instead flag an error to SW and not start the HMAC/SHA-2 operation; this is the most conservative and secure approach.

**Comment by andreaskurth** [comment]
@gdessouky I think you're working on this in #22580, right?
