### ISSUE TITLE
[usbdev,doc] Document all interface signals

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#22335]
This came out of the [D2 review meeting](https://docs.google.com/document/d/1_jtwDFX6V2Wn9-mlLkvcSYDmvs1sNbsx0itel3FTxVo/edit#heading=h.ljvw0i5sqvz6):
> To satisfy DOC_INTERFACE, we need to document the interface signals, including the aon signals. This might just be a matter of linking things between different bits of the document. The signals in the hjson file probably all need nonempty “desc” entries too.

**Comment by alees24** [comment]
PR #23829

**Comment by andreaskurth** [comment]
Moving to M6 as D3 effort

**Comment by alees24** [comment]
#23829 was merged.
