### ISSUE TITLE
[usbdev,doc] Document integration requirements

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#22336]
This came out of the [D2 review meeting](https://docs.google.com/document/d/1_jtwDFX6V2Wn9-mlLkvcSYDmvs1sNbsx0itel3FTxVo/edit#heading=h.ljvw0i5sqvz6):
> Create an issue to go through the USB specification from the integrator / standalone-usage point of view and document the integration requirements (clock speeds etc.) that we require.

**Comment by alees24** [comment]
https://github.com/lowRISC/opentitan/pull/23829 adds the details required for integration:

- USB timing reference
- AON/Wake behavior/monitoring of USB events
- AON/Wake clock frequencies
- AON/Wake signals and connectivity

**Comment by andreaskurth** [comment]
Moving to M6 as D3 effort

**Comment by alees24** [comment]
#23829 was merged.
