### ISSUE TITLE
[kmac,dv] Verify `fifo_empty` status interrupt

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#22341]
In PR #21657 we changed the `fifo_empty` interrupt from event to status. `kmac_scoreboard` currently doesn't model and check that interrupt; we should correct that.

**Comment by vogelpi** [comment]
Software is currently not using the `fifo_empty` interrupt and we may thus want to consider de-prioritizing this task @andreaskurth .

**Comment by andreaskurth** [comment]
Discussed in triage: same as for the similar HMAC issue, we move this to M5

**Comment by vogelpi** [comment]
This would be good to get. Maybe something for @martin-velay after taking care of the same task for HMAC?

**Comment by vogelpi** [comment]
@martin-velay started working on this and has a first draft PR ready here: #23942. Unfortunately, the work is not yet finished and Martin was OoO this week. Since this issue isn't super critical (see previous comments), I am moving this to M7 now.

**Comment by martin-velay** [comment]
Closed as https://github.com/lowRISC/opentitan/pull/23942 has been merged
