### ISSUE TITLE
[rv_dm] Verify `next_dm_addr_i`

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#22357]
Verify that the next debug module address input (`next_dm_addr_i`) behaves in the way specified in the RISC-V debug spec. This functionality was added in https://github.com/lowRISC/opentitan/commit/a49f888385c92429974367b3aa0dd8a765d76056.

**Comment by andreaskurth** [comment]
Note that `next_dm_addr_i` is currently unused and tied off in Earlgrey, hence I'm assigning this to the backlog.

**Comment by rswarbrick** [comment]
I'm not really convinced there's any work to do here, so propose just closing the issue. I don't think we need to carry issues for testing unused features of code that we have vendored... :-)

If I've missed something, please reopen (and point out what I've missed!)
