### ISSUE TITLE
[fpv] Inspect formal FPV results and get them back up to 100% pass rate

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#22385]
### Description

For a couple of weeks during the M2 push, the result publishing for the FPV regressions was broken (see #21694) . The tooling has now been fixed and it seems that during M2 some failures made their way into the system (previously, everything was green and at 100%). Some failures are systematic and prevent FPV from running at all, see e.g. the edn_sec_cm results [here](https://reports.opentitan.org/hw/top_earlgrey/formal/sec_cm/summary/latest/report.html).

For M3, we need to inspect the failures and get things back up to 100% pass rate.

The following regressions should be inspected:
- https://reports.opentitan.org/hw/top_earlgrey/formal/sec_cm/summary/latest/report.html
- https://reports.opentitan.org/hw/top_earlgrey/formal/ip/summary/latest/report.html
- https://reports.opentitan.org/hw/top_earlgrey/formal/prim/summary/latest/report.html

**Comment by vogelpi** [comment]
I recommend starting with the sec_cm regression: https://reports.opentitan.org/hw/top_earlgrey/formal/sec_cm/summary/latest/report.html

**Comment by vogelpi** [comment]
@rswarbrick stuff seems to have been broken for longer than we thought. One issue is the black boxing of prim_count in various places.
@moidx could ask @cindychip on this.
@rswarbrick this would be helpful.

**Comment by rswarbrick** [comment]
On the sec_cm side:

- The failures in `entropy_src` should hopefully be fixed by PR #22506.
- The failures in `lc_ctrl` are more mystifying! I've opened issue #22509 with some more details about the test that is actually failing. Unfortunately, I don't yet understand what's going on with this.

**Comment by rswarbrick** [comment]
A bit of extra background: I don't believe that we've ever had a 100% pass rate for these tests (so I quibble with the "back to" in the title :-D). It's probably still worth putting some serious effort into tidying things up though.

**Comment by vogelpi** [comment]
Thanks for your work on this @rswarbrick . I have three questions:
1. The latest sec_cm regression results for EDN show all N/A. But I am pretty sure we had tests running for this in the past. Would you mind investigating this please?
2. The latest sec_cm regression results show less than 100% pass rate for LC_CTRL. I think this might be related to the issue you've opened (and closed again is it's a duplicate). In the original issue, Cindy mentioned a work around we had in place. Is it feasible to get that working again? Given the importance of LC_CTRL for the system's security, I am really hesitant to leave this as is for the moment.
3. For cases where pass rates are below 100% (e.g. prim and top-level IPs like pinmux and rv_plic): I am not sure whether the pass rate was 100% before or not. For the tapeout, I would like to understand what the previous status (e.g. what we had for the ES tapeout). Would you mind cross-checking with @cindychip please? She might know the details.

**Comment by rswarbrick** [comment]
For (1), this is a compile error. I've just done some bisection and the problem came in with a97410824b48333651d566fef022f4d0d8bb4d1b. I'll do some digging to try to sort this out now.

For (2): This is caused by a tool bug. It's tracked in #12693, which was reported in 2022 and iceboxed in 2023.

For (3): The pass rates have never been 100%. Specifically, every assertion `a |-> b` generates an automatic cover property for `a` to be true. If you have an assertion where `a` is impossible (maybe because this is an instantiation of a module where some of the inputs are constrained in a particular way), this will cause the cover property to fail and the "pass rate" (dubious name in our tools) will not be 100%. I've triaged and fixed quite a lot of these properties in the last week or so. They have never passed before.

**Comment by vogelpi** [comment]
Thanks @rswarbrick for all your work on this!

For M3, I think we're done. I've factored out the other regressions into a new M4 issue here #22721. We should probably discuss what is acceptable for those for tapeout. I don't like that pinmux has currently no results. IIRC, pinmux is mainly verified using FPV.
