### ISSUE TITLE
[flash]  Long term plan for memory protection

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2239]
I would like to solicit some input for flash memory protection.

Currently, the flash uses a scheme similar to pmp (except it's based on page boundaries). There are currently 8 regions that can be configured.  However, this seems insufficient once we factor in both flash data and informational partitions.

Ultimately what makes the most sense depends on software usage during secure boot and provisioning. So it would be good to get some feedback on the flash update document to see what works best. 

One of the suggestions made was that each page should have separate enable bits; these enable bits may even need to extend to sub-page range for information pages.  For the current implementation, I will leave it to the memory protection like structure for both info / data at 8 regions.  As mentioned though, this is probably not enough.

**Comment by tjaychen** [comment]
I am most likely going to introduce a change that modifies how memory protection is performed on flash informational partitions. 
Right now, flash has 8 pmp-like regions that allows a user to specify base page and page size. The problem however, is that informational partitions most likely will be controlled differently on a per-page basis, which would cause us to eat up a lot of the control regions (ie, a few pages will belong to ROM, a few pages will belong to ROM_ext, a few pages will belong to kernel, a few pages to application etc).

So what I'm thinking is the following...
the data partitions will retain the pmp-type protection
the informational partitions will get per region control bits.
We will have roughly 2* (10+2) information pages at most.  Each page has 4 control bits (enable, read enable, program enable, erase enable), so that is 96b at most, way cheaper than burning potentially 5~6 regions of the pmp.

Let me know if there are any objections.

**Comment by sjgitty** [comment]
> We will have roughly 2* (10+2) information pages at most. Each page has 4 control bits (enable, read enable, program enable, erase enable), so that is 96b at most, way cheaper than burning potentially 5~6 regions of the pmp.

This sounds like a good idea. I haven't heard any objections. Are you moving forward in this direction?

**Comment by tjaychen** [comment]
yes i think so.
