### ISSUE TITLE
[tock] Uninitialized Memory Read in ConsoleComponent

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#2241]
@sriyerg has been running a OpenTitan tock image in the DV simulator and ran into an issue where the image was reading uninitialized memory. He got us an instruction trace and a disassembled image:
- [trace_core_00000000_log.txt](https://github.com/lowRISC/opentitan/files/4627428/trace_core_00000000_log.txt)
- [opentitan-disassembled.txt](https://github.com/lowRISC/opentitan/files/4627425/opentitan-disassembled.txt)

The trace fails at PC 0x200039b4, where the address 0x10000fa8 is being read.

# Initial Investigation by me

- The read address is coming from a `lw a4,-24(s0)` instruction, where `s0` has value 0x10000fc0.
- `s0` is initialized in the function prolog: it is the frame pointer.
  - In the function prolog, `sp` enters as 0x10000fc0 (PC: 0x20003942)
  - The function allocates 32 bytes of stack space (`c.addi sp, -32`)
  - The function then saves two words to the stack, using `sp` (PC: 0x20003944-0x20003946), at offsets `28(sp)` and `24(sp)`. Both are word-sized.
  - The function then initializes `s0` to `sp + 32` (PC: 0x20003948)
- Starting at PC: 0x200039a2, there is a run of word-sized fp-based accesses. To offsets:
  - `-12(fp)` (aka `20(sp)`)
  - `-16(fp)` (aka `16(sp)`)
  - `-20(fp)` (aka `12(sp)`)
  - `-24(fp)` (aka `8(sp)`) This last one is the one that fails, *but* every other one in this run is also an undefined access (because those parts of the stack have not been initialized in this function).
- The rust functions that make up this compiled function are:
  - PC: 0x20003942 `<<components::console::ConsoleComponent as kernel::component::Component>::finalize>`
  - PC: 0x20003994 `kernel::sched::Kernel::create_grant()` (inlined)
  - PC: 0x200039a2 `core::ptr::write()` (inlined).

# Investigation still needing followed up

- The run of word-sized accesses that are not valid are to load a series of words into a buffer pointed to by `a3`.
  - `a3` is initialized to the address of `<<components::console::ConsoleComponent as kernel::component::Component>::finalize::BUF>`

**Comment by lenary** [comment]
Looking at the linker script and the `flash_crt.S`:
- the stack is zeroed in `_flash_start`.
- the extents of the stack are `0x200fffe0` to `0x200fe000` (`_stack_start` to `_stack_end`). This is not actually enforced in the function prologs and epilogs, but the CRT should at least zero this range.

**Comment by msfschaffner** [comment]
This is a very old issue and I am not sure it is still a problem.
Closing for now, but please reopen if the behavior is still there.

CC @timothytrippel @cfrantz @mundaym
