### ISSUE TITLE
[dv,rtl,flash_ctrl] Determine why flash_ctrl_phy_arb_redun seems to freeze

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#22411]
### Description

This test injects a fault in the redundant arbiters. After the fault triggers an outgoing alert the test seems to freeze. It seems like a read to the fault _status CSR doesn't complete. If this is caused by the RTL it is a problem since it means the interrupts triggered by alerts could not determine the cause of the fault, leaving SW with no clue, and an arbitration fault is most likely due to malicious 
actors.

On the other hand, the DV code also seems to be triggering CSR reads of rd_fifo, which could (but probably should not) prevent the fault_status CSR read.

I think this needs to be resolved for PROD.

**Comment by vogelpi** [comment]
Thanks for your investigation and and for creating the issue @matutem . I agree, we should resolve this for PROD. My understanding is that this is mostly a DV thing or a minor RTL bug (but no big security issue), so I am moving this to M4.

**Comment by matutem** [comment]
This is an invalid issue, and I am closing it. It was due to my mistake: I had some pending changes in the RTL from when I found the scrambling bug. Unfortunately this test is still failing with integrity ECC errors, but once I find more details I will open a new issue.
