### ISSUE TITLE
[flash_ctrl] V2S Signoff

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#22470]

**Comment by mundaym** [comment]
I think this is already signed off based on this comment: https://github.com/lowRISC/opentitan/issues/21012#issuecomment-1986128320

**Comment by moidx** [comment]
Discussed moving as P1 to M5 due to RTL risk analysis performed during last issue triage.

**Comment by vogelpi** [comment]
> I think flash_ctrl is already signed off at V2S based on this comment: [#21012 (comment)](https://github.com/lowRISC/opentitan/issues/21012#issuecomment-2025200370)
> 
> Can this be closed as a duplicate [@andreaskurth](https://github.com/andreaskurth)?

I've noted that, too. What is missing is the change to the hjson updating the verification stage.
