### ISSUE TITLE
[alert_handler] D3 Signoff

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#22477]
This block has been signed off at D3 previously but may have seen (minor) changes since then, so we need to check that D3 signoff still holds.

**Comment by moidx** [comment]
Moving to capture documentation updates for D3

**Comment by johngt** [comment]
To discuss at triage meeting later today

**Comment by andreaskurth** [comment]
## Analysis of changes since previous signoff

alert_handler got previously signed off at D3 in 542ef5653be7bcc1e1af4e01e75641c089475cf5 and that hasn't changed since. So formally, alert_handler is currently still signed off at D3. For completeness' sake, however, here are the changes since the previous D3 signoff (`git log --pretty=oneline 542ef5653be7bcc1e1af4e01e75641c089475cf5..bff93a06f5e569270c56ec08db723722de9da805 hw/top_earlgrey/ip_autogen/alert_handler/rtl | tac`, thus old to new):
* 94ebb69dc55c0b3dd3e5547b2ef9f826a7daea98 [alert_handler] Hold ping id stable while pinging
* 621b69ea0c35c5d30373755f65fc4108fbceb0dc [otp_ctrl] Use comportable channels for alerts emanating from prim_otp
* 88829b65a0960271121209f996ce47ceeff71882 [flash_ctrl] Use comportable channels for alerts emanating from prim_flash
* 12e3dd9c231754fa533afbc8255a33b0e03bca5b [pwrmgrr/|rstmgr] Moved fault_status regs into LC domain
* 476fd521585a806fcbce21a41e6e5dded2207c4b [util/topgen] Update alert lpg generation
* 8202f9f45697287e4d19588745b71c1b067bda73 [CLOCK group] Fixed some unclear clock groups raised in #5305
* 51513fb937079b89b53129e69fc548702cb782df [PWRMGR|RSTMGR|ESC_ALERT] ESC domain separated from LC domain as requested in #14785
* b0cdccec0f46da022ecc45cc2576cc9b9d785726 [alert_handler] Increase chance that pinged alert ID is valid
* e063764dd06f0c61dad3f992cee794d13679c716 [tlul] Add access latency and ifetch to adapter_reg
* 57c0ce6f627eff4dce390f0136569a94ec71e899 [doc] Fix `it it` typo
* 0ba10b3cd3157d233c6a9a21676b058971399b99 [reggen] Add CIP_IDs and bump all major versions
* fbd888eea85260f03095b7b7f12537638ca27183 Revert "[reggen] Add CIP_IDs and bump all major versions"
* 1b16ca2122d956f4b1f909ba2e996b01ff22001e [reggen] Add mubi support SWAccess that sets/clears a reg
* de31bdf1c26be2714ca787c6041a56eb56eb7d1e [reggen] Remove the devmode input
* 3b4e36e01c130d75844efe5d5b2a31502059e74c [edn] Move prim_edn_req out of prim
* 61a237e1973d6a29d377c2be871139553c7d344f [util/reggen] reverse order of substruct generation
* c721c51c133b75a9c429e7b04eba98b685b3605e [rtl, prim] Add 'commit' functionality to prim_count
* 56399241e7614285e65fdb0ddfc7e37ade1cc7a4 Revert "[edn] Move prim_edn_req out of prim"
* f4c2bb903096d18bd45f0ad6b5e5aeb8f32545e5 Remove trailing whitespaces
* 30d7e787c753caaa03fe68a4a70da1bbcbc1d96f Add the project name to the copyright header
* 67b7d44cc7dbdb04be03859604a84ed12886550c [prim,fpv] Properly "waive" some unreachable prim_count assertions
* a4ad7a84c9b9623a2bb542e50ae4fce31b08c912 [alert_handler,fpv] Move a consistency assertion from FPV to RTL
* 11a56428dc06abbb75e26e1e35f7a1b07d27e7ae [alert_handler,rtl] Correct width of prim_count instance
* 704e91fa25f3b021662b856ac5f1d90ba3ef347d [fpv,prim] Generalise from DecrNeverTrue to listing possible actions
* 75180648a52045ee6fad66ce1bbc02cd9b8840da [fpv,alert_handler] Use PossibleActions param in *_ping_timer
* cd303a4d1b31522ced772abdda26154da5a1ec34 [alert_handler,rtl] Slightly simplify decrementing counter

**Comment by vogelpi** [comment]
This looks good to me @andreaskurth , thanks for pulling the information together!

Two remarks:
- All RTL changes including https://github.com/lowRISC/opentitan/commit/e063764dd06f0c61dad3f992cee794d13679c716 `[tlul] Add access latency and ifetch to adapter_reg` have been part of the ES tapeout. All further changes have no functional impact (as documented above) or they have been flagged by formal and I thoroughly reviewed those two PRs by Rupert (#22798 and #22568) previously who very well documented the motivation.
- The lint waiver did not get changed since the last D3 signoff. I think there is nothing new to be approved by the TC.
