### ISSUE TITLE
[pwrmgr] D3 Signoff

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#22487]

**Comment by moidx** [comment]
Moving to M5 as we are not expecting any further RTL changes as part of M4.

**Comment by matutem** [comment]
pwrmgr was declared D2S by https://github.com/lowRISC/opentitan/commit/efac5480a4b95d2308e0d965d4e22033926e8bfa on Mar 9, 2022. The pwrmgr code location changed from hw/ip/pwrmgr to hw/ip_templates/pwrmgr when it was generated by ipgen near c288cc3.

**Comment by andreaskurth** [comment]
Note for checking RTL changes: `git diff efac5480a4b95d2308e0d965d4e22033926e8bfa:hw/ip/pwrmgr/rtl HEAD:hw/top_earlgrey/ip_autogen/pwrmgr/rtl` (about 2.7k lines)

**Comment by andreaskurth** [comment]
Thanks for the details, @matutem. Based on your analysis above, I agree with signing pwrmgr off at D3.
