### ISSUE TITLE
[clkmgr] D3 Signoff

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#22482]

**Comment by moidx** [comment]
Moving to M5 as we are not expecting any further RTL changes as part of M4.

**Comment by matutem** [comment]
I updated the description to indicate the items in D3 I am able to sign-off at this point.

**Comment by matutem** [comment]
clkmgr was declared D2S on 18772a9 on Mar 9, 2022. and the current state is at 49fd66a73ae0c3e5f47077f32ba0b7120ed61d30.

The clkmgr code location changed from hw/ip/clkmgr to hw/ip_templates/clkmgr when it was generated by ipgen near commit 94e6ba7

# Analysis by checklist item:

## NEW_FEATURES_D3

5967df933a814f72d5212bd43d13a0041a3aaf9d [hw] Align HW IP block versions for Earlgrey-PROD
87799dd1214cf6e50dd03fb7d71bcaef91c7162c [ip_templates] Restore BUILD file templates
52a36297706242e26435e2ca7440aa6ec3096c3a [bazel] Remove invalid autogen_targets.
f9dd6c436f5769090252acda899eb5c00204659c [dv,clkmgr] Generate clkmgr binds
a162fb5d767c7ec77b1d78cd8c6b98a085b0658d [dv,clkmgr] Generate node toggle exclusions from hjson
d167ca0a6551f8d5719ffe73d5979ddeb62b2ad2 [dv,clkmgr] Used synchronized sw enables in SVA
ba71a6df80a034020352ccb07a93907cf86d7695 [ipgen,clkmgr] Delete old files
97c84f803c7f919b345b91abcc06d03c9fe61d7b [ipgen,clkmgr] Update ip_templates with bug fix from old files
82990cc1964c8c189a7be3ad900f4174dde38252 [ipgen,clkmgr] Update templates with updates from old autogen files
1ff9600aec26e86c03f9d844eff0ed594a0a6baf [ipgen,clkmgr] Fix BUILD files
ebbf9a80dec4e0a0daa7aca03f300a4e6faf228b [ipgen,clkmgr] Fix md files
8295903d7e8d6d52fac8ad434c70a773f760a771 [bazel,autogen_hjson] Split C and rust header generation
30d7e787c753caaa03fe68a4a70da1bbcbc1d96f Add the project name to the copyright header
f575e4b7dc75ec811c5bd868a96b1763ae875476 Make .core files pass FuseSoC 2 schema validator
209e4878a086e03baee9ba4e89641dd701a458ba [ipgen,clkmgr] Generate clkmgr files with ipgen
7615b8fc6add84d799e372462394b05646b55c81 [ipgen,clkmgr] Change templates to use plain dictionaries
6311398984d4eff6ba659ff80f0642329ff8616a [ipgen,clkmgr] Fix core files
09314be4a9b31bbe753cd0085f6ccd48920d1281 [ipgen,clkmgr] Turn a few more files into templates and fix paths
d28e33707d4d4cdd0376781cba38dc168867aefc [ipgen,clkmgr] Move template files and remove unused files
ab570a2934871fac178c8ae963355677c0d6aba9 [ipgen,clkmgr] Copy all hw/ip/clkmgr files to ip_templates

0d14dd693f43bf3ce84cfaa5706bb67152bd2297 [docs] Fix repetitions of the definite article
f95c9805b6cdb4117df862e4a026764189a42164 [lint,clkmgr] Clean lint for verible
7c97490c2485fbb5f282d4b1bbc2cdd9586affe7 [clkmgr] Insert hookup buffers on all root clock inputs
ab4b36f6b92617ecd67219df8dc1728a0029cae7 [ipgen,rstmgr] Fix paths to rstmgr in md files
c721c51c133b75a9c429e7b04eba98b685b3605e [rtl, prim] Add 'commit' functionality to prim_count
61a237e1973d6a29d377c2be871139553c7d344f [util/reggen] reverse order of substruct generation
ce648ca68e7c559da1643d1100e53a631d841ac6 [ipgen.pwrmgr] Change core files to vlnv naming and label as virtual
de31bdf1c26be2714ca787c6041a56eb56eb7d1e [reggen] Remove the devmode input
af221615474d5ed9bfe6a6bc1f23a3f57fff0a18 [sival,chip_testplans] Handle alert_handler enables tests
3f88a5512095201c1432d5e4bfb22789f35b25b1 [pwrmgr,ipgen] Generate pwrmgr ip_autogen files with topgen
20c65507565b6f257bb4f0c1b716b53d4cd822ea [dv/clkmgr] Fix clkmgr_env.core dependencies
897b51edc45419e94d07ed56effedfc116840315 [sival,clkgr] Add features in clkmgr.hjson.tpl
1b16ca2122d956f4b1f909ba2e996b01ff22001e [reggen] Add mubi support SWAccess that sets/clears a reg
088eee0df00b924debe357fca84b4c23cad1fa33 [clkmgr,dv] Avoid passing a mubi4_t as a uvm_reg_data_t output arg
59f81428262dd248c0bc9e938ae45c34d20b9610 [doc] Moved badges over to using hosted images
182f51b528a9dd1f03f4de80effa1cada107e5c5 [dv/clkmgr] Ignore coverage crosses that are unrealistic
a005c96cc3db84347e00a95103df04c6472c167d [doc] clkmgr registers and interfaces now use CMDGEN
7d0117c19f9931a32a44d51c4737f04ee61556be [dv/clkmgr] Add test for regwen functionality
e8c303fafb5838409e8fbf001d4ecaa6bb1807e0 [dv/clkmgr] Fix occasional clkmgr_peri test failure
0d8b4d4851fd4a121a0ab5f6a6797e3789540924 [dv/clkmgr] Improve handling of clock measure control CSRs
8ff4837913494f2aa310fc999d0f82cef0d8aff0 [dv/clkmgr] Increase wait cycles in clkmgr_lost_calib_ctrl_en_sva_if
bdf5e83386ec8e8f695e5eb724452fa73eb61eb0 [clkmgr,dv] Fix type in clkmgr_extclk_vseq
7688e714e847ce2672a7f43fc6e9d0c0f53b5730 [reggen] Add initial support for version and cip_id hjson fields
fbd888eea85260f03095b7b7f12537638ca27183 Revert "[reggen] Add CIP_IDs and bump all major versions"
0ba10b3cd3157d233c6a9a21676b058971399b99 [reggen] Add CIP_IDs and bump all major versions
e47df29f3e12a48c62f381a240c8cebf9658b91a [misc] Use lc_tx_t testing functions at endpoints
02fd38a036eb88f0e1068c83667b928d11e1f648 (tag: Earlgrey-M2.5.1-RC1) [gatesim] initial compile clean
d98b18f186eda61028748a9f9f276cad76dc1058 [rtl/clkmgr] Fix verilint warning
05a2f39d9e2892e3a81bf445c7bce7acd1cf07f3 [dv/clkmgr] Clean up compilation warnings
9794d3858851f7ceefb817639bbf59cfcd6d9fe3 [dv/clkmgr] Finish M2.5 pending items
3ecdfa67e294eb3046397d4749d9c598df2c7425 [clkmgr] Update external clocks table
1790498aed071f409b97a0b55c3f8d381a0bb93e [clkmgr] Align signal name with actual usage
e6bad66211df98ff3a84ee79847d6be23d592878 [clkmgr/doc] LC_CTRL ext clock clarification
4227daddc9d0ecddee301a46f4c6808b4b40c9ee [dv/clkmgr] Fix AllClkBypReqFall_A
d8ee53c611bfac5211d46b8b619d474d290ac4b0 [dv/clkmgr] Handle some TODOs
9675ea579586220ac614d0ba876bf74a3b4354ba [clkmgr/doc] Document step down request from AST
8374a0afdf6e96d5c99e2ef17a8dcefb5d521b7f [clkmgr/rstmgr/doc] Add description of LPG output signals
9bb3545f3af7c6e7dc9f29b8748c47b2c2f2690b [chip,external_clock] Improve clkmgr_external_clk_src_for_sw tests
ba8019e8b80a9ebf4ed1a1b2658ce1b849655c33 [dv/clkmgr] Fix SVA for gating clocks
eb9b1ff8fa9882eb57fff2e1b363dfc5032f618d [dv/clkmgr] Improve DV documentation and do simple cleanup
30f43b72a2013f57c4a5c9ca9a9d7487c9f33bd9 [dv/clkmgr] Update some TODOs
5650d343e72b51cbe9afdfa1b5a58749b624f1af [doc] fix `of of` typo
2759055085cd805173f2ffad3c13490fa5564aad Split README.md into theory_of_operation.md and programmers_guide.md
0b0c1e7408388be442c6d9b727fab5c4029a144e Add mini-dashboards to HWIP block READMEs
6321c5ea2bb4c0e0a10396a55b4c19fb162e0f84 [doc] Moved away from {{#regref ... }}
b30b1fde06c8104f3fcae6e80f5377fcced522fd [doc] Update content for testplan preprocessor
ac9f9b5999e25204e327d0859540254fa1080616 [doc] updated content for mdbook-doxygen
ba16bae28cf2dd54a3532947aee0e20925b7d503 [doc] Updated content for new reggen preproc
f6298b377fb582e6af2a615e15e043fe1942e2e5 [doc] Rewrite most frontmatters to Markdown titles
aef0a667f7c4b2dcebe09af35ae8a693d277c496 [doc] Replaced Hugo links with standard markdown
ba1bb8e1f75510b14ab4a05b832a4480b5b81323 [doc mv] hw/ip* doc files moved for new layout.
6211349dbe2bde6626b19a4c44ed4f1c4d8a6896 [hw,doc] Add human-readable name to all blocks
3638f4d6b9b6dff9e19f9ec055245419b4dd6413 [clkmgr,doc] Fix typo in one-paragraph description
f8500c00079d4248a7422ae15d61b0fd6065d8b4 [hw,doc] Add one-paragraph descriptions to all blocks
218294b7481edd0dfcc470d1df6c6f01dea75df5 [hw,doc] Add one-line descriptions to all blocks
bf752f72706e769f5d7efc5df1b94b7f823320a9 [dv/clkmgr] Fix unr file name in clkmgr_cfg
24f53119a5a7d8e43318cc9abfbf82d82a9f2c03 [doc,dv] Fix links to nightly results
e9b2b0f15b3bf6b81f34f7dcdc11c486854b9cd4 [dv/cov] Regenerate exclusions and minor coverage fixes
2608b59314c2a1ce746e915c55778980bea9853a [reggen] Move prj metadata into main hjson
2e16c70982269f842bec01dc576b190afd364ac0 [dv/shadowed_reg] Reduce a env_cfg variable
3e4bf3506e22e45b45b947d5816a7e4c35d0b84c [dv] Resolve TODOs in cip_macros
7411ac9c6fc12949199bfe70fe43e7fd205c7ef3 [dv] Address a few TODO in cip_base
7df806a582c4e6aa53a6a01c5433f577e11112c9 [clkmgr] Update documentation
10d6e41577f6602010c342cf8575cd71f62029f6 [prim_mubi*_sync] Remove clk/rst tie-offs to improve coverage
2b1388ad4b25d9767b18bf7c83e9a6ecbffb7b18 [clkmgr] Add MUBI Synchronizer to Idle
fd54ae6cb609d348e4f8b3210bdea80f6a3ee434 [dv/clkmgr] Enable cdc instrumentation
f753444e59409b74182606be441024200a6b13c6 [dv/clklmgr] Comment about the sec_cm testplan location
e063764dd06f0c61dad3f992cee794d13679c716 [tlul] Add access latency and ifetch to adapter_reg
7c7151f57b26837e5774ea93cafd377c8a4496b7 [dv/clkmgr] Declare V2S
ae555a64d8ed255165cbc02603724259317b933b [dv/clkmgr] Add exclusions and coverage pragmas
a5ca8fc2f6e5abeacb620582f9564bbe436f2702 [doc] Fix typos in //hw/ip
0590730b592955456c067c00036a6fe528b14293 [dv/clkmgr] Fix handling of lost calibration
8202f9f45697287e4d19588745b71c1b067bda73 [CLOCK group] Fixed some unclear clock groups raised in #5305
85ded644498db5ddfaf3ae680871c680941cd9c0 [dv/clkmgr] Add clib_rdy_i input
3fef5173c38588a050a1e7bc062e90719b40a8a0 [sensor_ctrl/clkmgr] update both to use mubi ast_init_done
c2205162dd645326801e649269e7fa8a8504a94e [top/dv] Update dv / test to work with ast usb calibration
d1be61ba88a145e882df4e7c7a47f78bcf2371f8 [testplanner] Replace IP milestone terminology with development stage
3452553ef943b7ca107e4e81dbc8a95454c97520 [prim] Assertion update for prim_reg_cdc
5053c41fc20bc4656a2fdc029a9d16f97f56040a [dv/clkmgr] Keep count check assertions enabled
e201c9f8b554eadcc9f528fb50776ec8745bd778 [dv/clkmgr] Fix clkmgr resets
f774faa51ceb8c875652a80a8992a9b4fe8e7f4e [dv/clkmgr] Fix reset handling
a79ca638323fd1339a29f69763693fa8e920530e [dv/clkmgr] Exclude hint_status reads and fix max_outstanding
f82e75a45f922a3545e54cb0b89daa88a9b8c186 [docs] add DIF list to each IP's docs
0794cfc4a8c1a5cbcd8d94ae3d8664215185afbf [prim_count] This reworks the primitive to make it more generic
e7d338784f00bbda505686edf9e8f86161fb25e7 [clkmgr/pwrmgr] Support synchronous resets for lc domain
5de589cd275f9c67b4cf02d80e2471b8f22de231 [dv/clkmgr] Fix sporadic stress test failures
9f17b8ee0eab1571a6d84e6a18520b1b0c5bc6e5 [clkmgr,rstmgr,pwrmgr] Align checklists
6f306d3dc604b35c495efdc5332863754565ebdc [RTL] Resolve enum assignment violation
2e51319c3fd009c064562da323d30b5176562a4a [doc] Remove README.md files from hw,utils folders
aa542d23c9711d90e8b039298a6a2c13c710dedd [dv/clkmgr] Fix failure in smoke test
29f760ca206ba7e6f163934acb294e6e40f75e72 [top] Auto generate
357d9fbc93d827812e22ea9350476cf210a80eb1 [dv] Add assertion to check reg_we onehot error leads to a fatal alert
5123a71ac14d869cfa60e442cdd5c103278330e8 [dv/clkmgr] Fix trans test
ecf02cc266dccab0b70a27e15c0903dd0330c6eb [dv] Hack alert
4b19b4589da9f75413b4b5203e0f874e16e2c2fb [clkmgr] swap most clkmgr resets to lc root
9a89d46ff17514a0757d46f74b91bd6bea9027d3 [clkmgr] Minor documentation updates
9634d8677a6d28e80f6083568d98b310bb809248 [dv,pwrmgr,top] pwrmgr normal sleep all wake up test
eba99e7b938c28e375a4b195e39103f3b9b4b45d [clkmgr] Allow transactional clock groups with just 1 clock
2fbfbf4224d96b49cc1cbeeb9dd48afe85558fc1 [dv/clkmgr] Fix clkmgr_peri tests
f446683d7e76c511ff214a059141b9b6ebb64611 [clkmgr] Fix cdc issues from reg status
d957c8654e10f029263a1bf10776eb0c7c98f536 [dv] Enable reg_wr_check test for all blocks
48f8172e95d12c3810696c978bf2840bf4a9bc2e [clkmgr,dv] v2s review ready
89917fd4a11774b563729ab3b2fc459918081076 [dv,clkmgr] clkmgr regression fix
68c142b027cd4cca9e16d93e82b69d346dff3d6b [clkmgr] Split clkmgr resets
00dd729d4f254732acb0fb47c545239551fd63b5 [clkmgr,dv] regression fix - shadow register error test
fae10892c0d15aabcd39c0d4d53cd7e99c51f6ec [dv] Remove TB_LINT_PASS in all IP checklists
a8730a3d146870a7c41d3fc15413242e2ed5e74a [dv/clkmgr] DV updates to support refactoring
f44a7a7de1a1b0d67827a66b6b3b7739156e9f76 [clkmgr] refactoring measurement clock for readability
3619bb889beebc8e2c14fdd68a9e9f2d3328bf42 [clkmgr] Handle measurement control on calibration lost
6349970862f4c99db7ab7b3b5b2f0a27135bb371 [clkmgr] De-couple idle count from mubi
df2be2bf98b88f855625385d31a428f49790cdc0 [doc/d2s] Retrospectively update D2S checklist items
a071347e4cfbf78eae80d0a218880a2d44852ef2 [doc] Align all D2S and D3 checklists in the project
c6b2b7af442efecf47c07dbbc71b382a02220f2e [dv/clkmgr] Fix frequency tests
2e3fe6a51cb52d5f8e6257d44cbc7e19590915b3 [mubi/lc_ctrl] Change MUBI / lc_tx_t encodings
208d34a3e1eda12a07f2c9a246ddccc381792fd6 [reggen] Add spurious WE check to autogen'd regfile
14d44ba1e417776302dccb72f0b5aa53310df812 [clkmgr] External ack readback for external clock switch
c62e71d1cb8b09d9fe96f54ecea38dc08bfc70a9 [clkmgr] Connect prim count failure to right alert
6520a791d61654e548a726e74e89ef13eb42fb6c [doc] Clarify lc requested external clock switch
c69acb9e02a5b370ba6bc1a3ba1a146aa94f4268 [dv/clkmgr] Fix handling recov_err_code CSR
c83256698562dd4d5ab0fa24e69759139f79b49b [reggen] Move shadow register error aggregation into reg_top
c788fd296594a6b000d694642c2afa70c34feb4a [clkmgr,dv] add shaow reg auto test and fix auto test
e5ec3c5707609d92985b1702e5e711e458afdefd [reggen] Don't generate reg_busy_sel if there are no async regs
50b10dfd1332f26e370b9473209ceff2276c053c [clkmgr] Bump version to 1.0
a7dd5942185b02b928e3b03dc1c5ea38c4d7517a [clkmgr,dv] fix regression failure
75c69734f2e69f0db70d7fefeb0144ec860477ae [clkmgr] Fix build with Xcelium
ce0b9241b4bf70ee407e5cd5385d246140b5ae10 [dv,clkmgr] sec cm testplan
b53c3b8433edcc52e2f1b45a6581e6bf447f5f0c [dv] Fix clkmgr_cov_bind for lc_tx_t type ports
45bdff52083e7ba9ab992284b01c6b3cb29f2bce [dv,clkmgr] sec cm dv component
8fc2a76136cab25c61f3dc75fae48c58e19f8609 [clkmgr] Add missing items from d2s
67e117d85a9db1e5a0ae94f79762ceb1aaf26570 [doc/clkmgr] Fix trivial typo
0d07362907d5dee4337566e149063a7b06b96a80 [clkmgr] Combined shadow error registers into a single field
cbe41e0de3047b1fec8cdaac21ac11910df1859b [dv/clkmgr] Fix external clock handling
94ce41a785d3d72b49694696785cb76a2d773908 [dv/clkmgr] Populate sec_cm testplan
dc060d430b38dbc7ea4ec2c376678feb3c302454 [dv/clk,pwrmgr] Disable unnecessary exclusions
25d6a536deba189a0551c12fc8f42b1e95b393b9 [clkmgr] clarify documentation for clkmgr
cb8755cbd9acc1d1ce4281c0d6d6e32f399987bc [dv/clkmgr] Fix trans unit handling
7f0118211ff0f719d12afe12d442fb5cb5ef2e9b [dv] Import used uvm_pkg in some interfaces

Most of these are dv changes, minor enhancements, or bug fixes. The following RTL changes are worth mentioning:

**Comment by andreaskurth** [comment]
Similar to rstmgr, it would be valuable if I could check the RTL diff since the previous signoff.

I tried `git diff 18772a998406c1d59f094450607d392604e641b4:hw/ip/clkmgr/rtl HEAD:hw/top_earlgrey/ip_autogen/clkmgr/rtl` but that has 5k lines .. did we really change so much?

**Comment by matutem** [comment]
Along the same line of the pwrmgr and rstmgr, for clkmgr the right comparison is between the generated files under hw/top_earlgrey/ip/clkmgr/rtl and the current files. I also updated the comment above to call out the changes affectig CSRs.

**Comment by andreaskurth** [comment]
Thanks for the details, @matutem. I think this is ready for signoff except that the lint waiver file will have to be approved by TC.

**Comment by andreaskurth** [comment]
[`clkmgr.waiver`](https://github.com/lowRISC/opentitan/blob/earlgrey_1.0.0/hw/top_earlgrey/ip_autogen/clkmgr/lint/clkmgr.waiver) approved by TC
