### ISSUE TITLE
[ci] Sival jobs timing out after running only a few tests

### ISSUE THREAD

**Issue by jwnrt** [lowRISC/opentitan#22495]
### Description

Recently we have seen several silicon validation CI jobs get timed out at 45 minutes after only executing ~12 tests. Bazel's timeout after each test is 60 seconds as far as I'm aware. In the example I'm looking at only 10 tests have failed so at most that's a 10 minute runtime if they all timed out.

This needs investigating.

Here is an example Azure run:

https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=148506&view=logs&j=5011a995-22d7-5073-e1ce-26fc382a8885&t=875997a6-7e2b-594d-05e6-ce6a085f3383

And a copy of the logs for posterity (Azure cleans up after 14 days):

https://gist.githubusercontent.com/jwnrt/93653a0e57a58c103f2e333514459995/raw/597e5de4c4693c36491d9ed15503ec2e0464c661/gistfile1.txt

**Comment by jwnrt** [comment]
I've bumped the timeout on this job up by 30 minutes in #22557 since successful jobs are taking ~40m and it might be legitimate to increase it. I'm still skeptical though given only ~12 tests even run before the timeout.

We've also started seeing the other sival job timeout at 60 minutes similarly after only executing 18 minutes.

**Comment by a-will** [comment]
Note that in the linked gist, basically _every_ test has fallen over and timed out. The FPGA OT's UART is outputting nothing, and it looks like only JTAG somehow works.
