### ISSUE TITLE
[flash] data alignment issues

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2252]
The flash controller currently requires software input to be packed and aligned to word boundaries. Meaning if the source were not word aligned, and the software performed a byte write, it would be both incorrect and use up more storage than necessary.  Imagine the flash wishes to write 7 bytes and memcpys this information into the flash controller. This could be decomposed into a number of writes depending on the source alignment, for example

- 2B, 4B, 1B
- 3B, 4B
- 4B, 3B

These would all impact the flash FIFO differently and that is not desirable.

The right solution should be like `hmac` and make use of `prim_packer`.  The flash controller components then need to make the right decision on when to flush when the end of an operation is reached. 

@sjgitty 
@eunchan 
@sriyerg

**Comment by tjaychen** [comment]
After chatting with some of the software team, it seems at least some use cases are okay with nicely aligning the data in software prior to feeding to flash. So the description above is not necessarily required.  I'll probably need to solicit some more input before making a final decision.

If others would like to chime in, please feel free to do so.

**Comment by cdgori** [comment]
Can we identify which software cases can't be formulated word-aligned?  Would prefer to keep the flash controller simple (word-aligned) and error if the assumption is violated, unless there is a hard req for the non-aligned usage.

**Comment by tjaychen** [comment]
@cdgori indeed that is the question. one software person i spoke to clarified that what matters most is they can efficiently move data. So requiring software to pack and align in his opinion wasn't the worst thing, as long as they have guaranteed efficiencies afterwards.

Areas where mis-alignment is likely desired are areas where they will invoke memcpy calls directly from a memory into a peripheral (for example spi, hmac).  Flash may not fall into this category since there is 'word' resolution to it and also PE concerns.  So..hoping to get some more feedback from others.

**Comment by tjaychen** [comment]
@jon-flatley @gkelly @moidx 
it would be good to hear what you guys think.

**Comment by tjaychen** [comment]
For now the hardware is designed such that software needs to be 4B aligned.
If software makes use of ECC / scrambling, it further needs to be aware of the flash word size (8B) alignment. 

If this becomes an issue, we can reopen and discuss.
