### ISSUE TITLE
[cryptolib] Integrate hw SHA2 384/512 to cryptolib

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#22547]
### Description

Hardware now has this functionality available for `EarlGrey-PROD` in the master branch.

**Comment by ballifatih** [comment]
This has been done as part of the larger issue https://github.com/lowRISC/opentitan/issues/22731 and series of HMAC driver commits, further references to these commits can be found in #22731 if needed.

Closing this issue.
