### ISSUE TITLE
[flash_ctrl] Extend block-level DV test cases

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#22559]
### Description

Related to #22443, #22444, #22549, we've realized that we should probably extend block-level DV to cover some more cases (where they are not yet covered):
- [x] Change the `flash_ctrl_phy_arb_redun` to inject faults into both copies of all four redundant arbiters. In case the right copy is glitched to 1, this may inject new transactions into the read pipeline as a side effect trigger ECC and other errors. It may be necessary to ignore some of these errors during the fault injection (as we have been ignoring the access permission errors or mp_err bit already). --> #22444 
- [ ] Stress test both flash banks in parallel (without FI) but with ECC enabled.
- [ ] Enable ECC more widely (it seems to be disabled with the original scoreboard).
- [ ] Fix DV sequence handling of program resolution errors.

**Comment by andreaskurth** [comment]
Thanks for collecting these cases, @vogelpi. Would it make sense to prioritize the items that test functionality under regular conditions (currently 2 and 3 in the list above) as P1 and the items that test response to FI (currently 1 in the list above) as P2?

**Comment by matutem** [comment]
@andreaskurth the test for case 1 was already created in https://github.com/lowRISC/opentitan/pull/22444.
Case 2 is a subset of case 3, and it boils down to enabling ECC for the flash_ctrl_rw test, which is in progress and we expect a PR soon.
