### ISSUE TITLE
[i2c] Add multi-controller support for MCTP

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#22569]
### Description

Add the necessary elements to support MCTP's multi-controller requirements.

- [x] Add detection of bus idle.
  - Detect Start and Stop + count of SCL high cycles
  - Controller uses the output of this detector for determining when it can transmit.
  - Resolved by https://github.com/lowRISC/opentitan/pull/22864
- [ ] Add detection of lost arbitration (affects both Controller and Target)
  - Note that this actually applies to Targets even in single-controller modes.
    - There are broadcast commands where Targets use bus arbitration to determine who responds first.
  - The detector is little more than a counter + small comparison.
    - While SCL is high while we are in a transaction, SDA_I must be high when SDA_O is high.
    - Count out rising + round-trip delays (worst case delay through synchronizers) on SDA_O changes before being effective.
  - Controller responds in a similar way as a NACK handling timeout.
    - Set an event bit for arbitration lost to inform SW
    - Go straight to Idle and release SDA / SCL
    - Block FMT FIFO processing until event bit cleared
  - Target responds as though the transaction abruptly ended (no longer addressed)
    - ACQ FIFO should report this as a flag as well.
  - For a Controller, SW responds by retrying
  - For a Target, SW's response is context-dependent, but it generally is a No-Op.
    - At a higher protocol layer, it might mean not retiring some response to a request, so it can be retried.
  - To be resolved by https://github.com/lowRISC/opentitan/pull/22872
- [ ] Clock synchronization
  - In SCL high states, trigger the state transition to the “hold” states earlier if SCL_I is low
    - After rise time and round-trip delays, etc.
  - To be resolved by https://github.com/lowRISC/opentitan/pull/22872
- [x] Change stretch timeout to be counted over the entire transaction
  - Don't reset stretch counter until going back to Idle.
  - To be resolved by https://github.com/lowRISC/opentitan/pull/22865

**Comment by andreaskurth** [comment]
Closing as completed, since #22864, #22865, and #22872 have been merged. Thanks a lot, @a-will! :+1:
