### ISSUE TITLE
[hmac/dv] CSR read check commented out in scoreboard

### ISSUE THREAD

**Issue by martin-velay** [lowRISC/opentitan#22578]
### Description

In the HMAC SB, there is condition on "do_read_check" to enable data comparison. But this is commented out since mid-February.

**Comment by johngt** [comment]
@martin-velay - I assume that you'll be doing the DV work here. I'm putting in 2 days of effort which might be too much. Please change the estimate if incorrect.

**Comment by andreaskurth** [comment]
Digest registers are getting checked seperately, message length will get checked as part of save & restore DV. The status register should get checked as P1 because that cannot be reproduced by SW; all other registers can.
