### ISSUE TITLE
[rtl,flash_ctrl] Fix ecc errors

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#22615]
### Description

We are still getting ecc errors in flash_ctrl. Running the flash_ctrl_rw with seed 72088649203256424400418660460856055802845297581904883038901129981482688983152 shows a read fatal fault, but there was a prior write of the same location and apparently the data is identical to what was written. This may indicate an incorrect write. Also, the same error happens with the flash_ctrl prior to sharing the scrambler.

**Comment by matutem** [comment]
One case I reviewed seems to be due to non-overlapping half-word writes with ECC enabled. This is almost certain to result in ECC errors since ecc bits cannot change from 0 to 1. We need to prevent these cases from being generated in tests.

**Comment by vogelpi** [comment]
Thanks for creating the issue @matutem . What just came to my mind is this issue here:  #13429

Can you check if it's related? Maybe we "just" need to constrain DV properly.

**Comment by matutem** [comment]
We have determined all faults we get are due to incorrect tests, which either do half-word updates to both halves of a word with scrambling or ECC enabled, or tests that simple overwrite locations also with ecc or scrambling enabled: both cases result in ECC errors.

Closing this issue :)
