### ISSUE TITLE
[entropy_src] Integration and top-level testing extensions

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#22705]
### Description

During previous discussions it was mentioned that we extend the top-level / SiVal tests of ENTROPY_SRC / the entropy complex to cover the following things:
- [ ] In Firmware Override - Extract & Insert mode, test if things keep working in case a significant delay is added between extracting and inserting entropy, see https://github.com/lowRISC/opentitan/issues/20952#issuecomment-2027811199.
- [ ] In Firmware Override - Extract & Insert mode, test if things keep working if ENTROPY_SRC is disabled between producing seeds WITHOUT disabling CSRNG and the EDNs. See https://github.com/lowRISC/opentitan/issues/20952#issuecomment-2034273059 and https://github.com/lowRISC/opentitan/issues/22293#issuecomment-2210526844

Please add more stuff here if needed rather than creating new issues / re-open previously closed issues.

**Comment by johngt** [comment]
@h-filali / @vogelpi - do you mind adding a rough estimate for time needed to resolve this?
Looking at the issue the related PRs are merged suggesting that this could be closed out?

**Comment by vogelpi** [comment]
Moving to M6 for now as the risk here is low and we have other, more important items for M5.
