### ISSUE TITLE
[csrng/edn] Consider making FIPS flag software defined

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#22732]
### Description

We should consider adding a possibility for making the FIPS flag software defined in CSRNG/EDN. We already did this for ENTROPY_SRC as part of M2 but it's also needed in CSRNG/EDN if we want to do KAT on OTBN.

**Comment by andreaskurth** [comment]
on top of @vogelpi's prios, but may have to wait until 4 June

**Comment by vogelpi** [comment]
The PR implementing this change is here: #23324.

**Comment by vogelpi** [comment]
On track for M4, discussed during triage meeting.
