### ISSUE TITLE
[dv,flash_ctrl] Fix handling program resolution

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#22746]
### Description

The flash program sequence generator doesn't have a constraint that avoids program requests crossing program window boundaries (which are aligned at 64 bytes (8 flash words). Rather than detecting this and expect an error and drop the update, `prog_flash` rewrites the request. Unfortunately this rewrite generates multiple writes to the same locations when multiple consecutive writes are requested.

I think if anything the rewrite should instead break a request that spills into two portions, each fully contained within a single window. There are dedicated tests that check that crossing errors are generated.

**Comment by vogelpi** [comment]
Thanks for filing this issue @matutem . I agree that this should be looked at. For now, I am putting it into M5 / V3.
