### ISSUE TITLE
[fpga] Relax timing?

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2274]
While adding a fairly innocuous looking module #2273 , the fpga worst case path degraded from 170ps to -30ps.  I took a look at the failing path (there was exactly 1), and it didn't have anything directly to do with the change (there was an extra device hanging on the fabric). 

The failing path is related to the flash read pipeline, which has a very small buffer structure to see if the current flash read matches a line that has been previously read.  I could improve this slightly with (i think) not too much downgrade to the read path performance, but i wonder if the fpga is teetering on the edge and other unrelated change will ultimately push it over the edge. 

Should we consider slowing the fpga clock down? This path I'm fairly sure would survive an actual standard cell synthesis, so I'm not sure it makes sense to tweak too much.

Let me know what you think.

**Comment by tjaychen** [comment]
@eunchan @msfschaffner 
i think you guys have the best current view of how much slack there is in the synthesized system... do you think we're really close to the edge and relaxing fpga would be a bad idea..?

**Comment by imphil** [comment]
@tomroberts-lowrisc who has been looking into that to get pmp enabled.

**Comment by sjgitty** [comment]
@imphil do you mean @tomroberts-lowrisc is looking into the same issue? Or just the general issue of slowing down the FPGA in order to get PMP going?

**Comment by imphil** [comment]
Enabling PMP currently breaks timing in our 50 MHz FPGA build (#1888).

@tomroberts-lowrisc is looking into ways to either improve the timing of the design and I think he has made some progress on that. If that turns out to be not sufficient, the plan was to lower the FPGA frequency. 

So potentially the same solution (Relax FPGA timing), but for a different reason.

**Comment by tomroberts-lowrisc** [comment]
Yep looks like we won't need to lower the frequency for PMP once all the timing fixes are in.

We could lower it anyway if we're close to the limit, but it's kind of useful to have something that flags up fmax degradation in CI.

**Comment by tjaychen** [comment]
okay sounds good. Then let me go back and see how I can tweak it.
Just out of curiosity, what sort of timing fixes were made for pmp? On my
end the basic issue is there's a long single cycle path where the address
from ibex is used to select a particular ready.

**Comment by msfschaffner** [comment]
@tjaychen I think we have more headroom on the ASIC side than on the FPGA side at the moment. 

I agree with @tomroberts-lowrisc that it's useful to have CI flag fmax degradation, but I suspect that we will have to lower the frequency of the FPGA anyway at some point since we are about to add a bunch of additional peripherals to the main bus soon...

So, if there is a quick and easy RTL fix to get the FPGA meet timing, let's try and do that. Otherwise I would not be opposed to lower the frequency by a few MHz...

**Comment by tomroberts-lowrisc** [comment]
The timing fixes were inside Ibex - on the core side of the TLUL fifo that breaks paths from the core to the bus. I guess the new path is from the output of that fifo through the bus fabric?

**Comment by tjaychen** [comment]
yep, although for some reason it's not showing up anymore...I wonder if I
just ran into a fluke FPGA run.  The failed synthesis had EXACTLY 1 failure
path, how often does that happen?

There's a path that goes something like this..

ibex_fifo -> fabric -> tlul_adapter_sram -> flash read pipeline -> read
buffer match -> ready to ibex

I think i can improve the timing by not doing the read buffer match, but it
would imply that i won't know whether i should start a flash read until the
next cycle.
Normally this is not a problem..since things like caches just prefetch and
discard later, but flash reads may take a LONG (okay 3~4 cycles, so not
that long) time...so I think for performance reasons I prefer not to start
one unless I absolutely have to.

**Comment by imphil** [comment]
So for PMP we don't need to lower the FPGA frequency any more, but we seem to have quite tight timing now (#1888). 

@tjaychen If any of your changes fail timing we can still reduce the FPGA frequency, just let us know.

**Comment by tjaychen** [comment]
thanks @imphil 
I think it's okay to close for now. The error I ran into was just odd. In subsequent runs (before ibex), i always saw slack of at least 700ps. I'm not sure why that one specific run failed, and failed exactly 1 path (i've never seen that, usually failures come in droves). 

I'll close this for now, and if we need to revisit for whatever reason we will do that.
