### ISSUE TITLE
[documentation] Error or confusion in TL timing diagrams

### ISSUE THREAD

**Issue by olofk** [lowRISC/opentitan#22817]
### Description

Looking at https://opentitan.org/book/hw/ip/tlul/#timing-diagrams it describes some transactions, including an error on I4 response. I haven't dug into the TL spec yet, but to the untrained eye this looks very much like the error happens on transaction I5. Would be great to either have this fixed (if it's wrong) or some comment explaining why the error signal is associated to I5.

**Comment by rswarbrick** [comment]
Thanks for the report. I've just spent some time staring at the TLUL spec and I'm reasonably convinced you're right. I've filed the associated PR which should fix things up.
