### ISSUE TITLE
[usbdev] implement remaining V2 tests

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#22880]
### Description

Implement tests for the remaining testpoints in the testplan.

- [x] streaming_test
- [x] max_clock_error_untracked | max_clock_error_tracking | max_phase_error
- [x] aon_wake_resume | aon_wake_reset | aon_wake_disconnect
- [x] invalid_sync | spurious_tokens_ignored
- [x] rand_bus_resets | rand_bus_disconnects
- [x] max_usb_traffic
- [x] stress_usb_traffic
- [x] in_packet_retraction
- [x] data_toggle_restore (#22709)
- [x] setup_priority

**Comment by alees24** [comment]
All testpoints implemented.
