### ISSUE TITLE
[i2c,dv] Update testplan for MCTP/SMBus M4 features

### ISSUE THREAD

**Issue by hcallahan-lowrisc** [lowRISC/opentitan#22895]

**Comment by andreaskurth** [comment]
@hcallahan-lowrisc Please complete the PR based on Alex's feedback so we can close this

**Comment by hcallahan-lowrisc** [comment]
> [@hcallahan-lowrisc](https://github.com/hcallahan-lowrisc) Please complete the PR based on Alex's feedback so we can close this

PR is now complete pending review.
