### ISSUE TITLE
[sw, dif_uart] uart.VAL, uart.OVRD, uart.TIMEOUT_CTRL not covered by the DIF

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#2292]
uart.OVRD - TX pin override control. Gives direct SW control over TX pin state.
uart.VAL - UART oversampled values.
uart.TIMEOUT_CTRL - UART RX timeout control.

There is no API in the DIF to control these registers, do we need this functionality?

**Comment by silvestrst** [comment]
@gkelly @lenary

**Comment by lenary** [comment]
I'd like @gkelly to chime in - my reaction is we probably only need to be able to access `TIMEOUT_CTRL`, but I could be wrong.

**Comment by gkelly** [comment]
Of the set only `TIMEOUT_CTRL` seems useful outside of DV. However, most timeouts I've seen have been driven by higher level layering driven off of a timer. I'm still in favor of adding it, and I suspect DV might want it too (@sriyerg for visibility).

**Comment by sriyerg** [comment]
We have fully closed the design coverage within UART at the IP level DV testbench. As such, only thing that remains is the connectivity of rest of the interrupts (frame err, break err etc), which will be covered by the automated interrupt (C) test (this is a WIP). At the chip level DV, it is not required to cover any of these features.

**Comment by silvestrst** [comment]
> I'm still in favor of adding it
I can add it, but I would like to get UART to S1.

**Comment by lenary** [comment]
S1 doesn't require the API to never be changed. Let's put it in the queue for after S1.

**Comment by silvestrst** [comment]
Does this still hold for S2 checklist items?

**Comment by silvestrst** [comment]
See #4277
