### ISSUE TITLE
[sival] rv_core_ibex_nmi_irq_test_silicon_owner_sival_rom_ext failure

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#22954]
### Description

Enabling alert_handler ping mechanism results in alert_handler NMI without any reported local of regular alerts. The only way to recover from this is by resetting the device.

**Comment by pamaury** [comment]
I think @nbdd0121 has investigated the test in more depth and might comment here?

**Comment by andreaskurth** [comment]
@moidx is currently investigating this. If there are any comments from others please provide them

**Comment by moidx** [comment]
Configuring the alert_handler triggers nmi interrupt without any alert class association.

https://github.com/lowRISC/opentitan/blob/605da270ddcf70b2af5573e9524f9613bc89383d/sw/device/tests/rv_core_ibex_nmi_irq_test.c#L98-L101

The alert NMI is triggered even when there are no pending alerts. Verified this by removing the force alert.

https://github.com/lowRISC/opentitan/blob/605da270ddcf70b2af5573e9524f9613bc89383d/sw/device/tests/rv_core_ibex_nmi_irq_test.c#L203-L204

Disabling the ping timer removes the spurious NMI issue:

https://github.com/lowRISC/opentitan/blob/605da270ddcf70b2af5573e9524f9613bc89383d/sw/device/lib/testing/alert_handler_testutils.c#L139-L141

The following write in dif_alert_handler.c is what triggers the NMI from alert_handler:

```c
  // Lock the configuration.
  if (locked == kDifToggleEnabled) {
    mmio_region_write32(alert_handler->base_addr,
                        ALERT_HANDLER_PING_TIMER_REGWEN_REG_OFFSET, 0);
  }
```

**Comment by moidx** [comment]
I tried switching the test to use a recoverable alert, different escalation sequences and a valid ping timeout timer configuration, but none of these changes helped to move the alert handler NMI. 

I will submit these test updates separately, but I think at this point I am going to flag this for CDC analysis. 

CC: @a-will @matutem @nbdd0121 who also took a look at this issue.

**Comment by moidx** [comment]
I am going to measure the delay between enabling the ping mechanism and the NMI to try to determine if this is an issue with the reverse ping mechanism supported by the receivers. 

This was recommended by @msfschaffner.

**Comment by moidx** [comment]
Running the test with the alerts and ping configured, and without triggering the alert results in the first alert NMI triggering between 500-4000 microseconds.

This as measured with rv_timer using an equivalent 1us tick.

**Comment by moidx** [comment]
@andreaskurth, this test is reproducible without a ROM_EXT running. @a-will suggested we can try to get a DV test configuration ready to run in GLS in case this is something we want to try. 

CC: @sha-ron @OTshimeon

**Comment by andreaskurth** [comment]
By @moidx: We can run `chip_sw_rv_core_ibex_nmi_irq` with test ROM on the netlist. We need to update the testcase to not trigger a fake alert, just wait. Then we shouldn't see any NMIs and can wait for the timeout. We should run this GLS over the next weekend. @moidx will create a test case.

**Comment by moidx** [comment]
Created the test case in #23441 and added test point to the GLS test plan.

**Comment by vogelpi** [comment]
Discussed during triage meeting. Okay to move this to M5.

**Comment by johannheyszl** [comment]
@moidx thanks for the heads up. IMHO this is OK for the testing we currently do, i.e. not fully invasive and cutting wires.

**Comment by andreaskurth** [comment]
Moving this to M6 as P1. It should be tested early on the final netlist

**Comment by moidx** [comment]
https://github.com/lowRISC/opentitan/issues/24119 tracks the findings after running the `sw_alert_handler_ping_ok` test post synthesis.

**Comment by vogelpi** [comment]
@moidx We could add this test to the GLS test plan as a P2. It should now be passing now with the latest ECO fixes in.

**Comment by andreaskurth** [comment]
Confirmed that `chip_sw_rv_core_ibex_nmi_irq` is on the GLS testplan. Suggest moving this to M7 (still as P1).

**Comment by moidx** [comment]
Closing this issue as the `sw_alert_handler_ping_ok` is now passing in GLS. We can create a new issue if `rv_core_ibex_nmi_req_irq_test` we are able to run the test in GLS and results in failure.
