### ISSUE TITLE
[keymgr] Reduce reseeding and PRNG activity during Disabled and Invalid states

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#22997]
keymgr currently constantly updates its PRNG and periodically reseeds it in the terminal Disabled and Invalid states. This consumes power and entropy, which can be problematic.

**Comment by vsukhoml** [comment]
Could you please update documentation with description of behavior in case of EDN, CSRNG or entropy sources are disabled. Ideally, it shouldn't hang in this case. Adding test for this behavior would be helpful.
