### ISSUE TITLE
[prim_ram] Provide cfg port to RAM primitives

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2307]
Currently we have a `cfg_i` port in the prim_ram_*_adv` modules, but not in the underlying technology-dependent primitives `prim_ram_?p`. 

What will the exact purpose of this config port be, and should it be made available to the SRAM primitive itself (e.g. to influence behavior of an ASIC SRAM macro).

_Originally posted by @msfschaffner in https://github.com/lowRISC/opentitan/pull/2299_

**Comment by imphil** [comment]
CC @msfschaffner @eunchan

**Comment by tjaychen** [comment]
the configuration has all been added.
