### ISSUE TITLE
How to run hello_world.c on open titan?

### ISSUE THREAD

**Issue by yaagna** [lowRISC/opentitan#23070]
I am trying to run hello_world.c file on opentitan the path of this file is 'opentitan/sw/device/examples/hello_world' does anyone know how to make this run on opentitan?

**Comment by jwnrt** [comment]
Are you trying to run it on an FPGA?

This guide runs through programming a CW310 FPGA and running the `hello_world` on it: https://opentitan.org/book/doc/contributing/fpga/ref_manual_fpga.html#general-software-development

That guide is pretty manual. You can run most of our test binaries in the Verilator simulator using `bazel test //sw/device/tests:hmac_smoketest_sim_verilator`, substituting `hmac_smoketest` with any other `opentitan_test` listed in [this BUILD file](https://github.com/lowRISC/opentitan/blob/20b86813f1cde25e2bfd1c36f1de27adb3e59ec3/sw/device/tests/BUILD#L1898).

There's an open PR here that should make `hello_world` easier to run in the future if merged: https://github.com/lowRISC/opentitan/pull/19365

**Comment by yaagna** [comment]
No, I am trying to run to run using simulation. I ran the bazel tests it works as expected. But I am trying to run hello_world in Verilator simulator. Any guide on how to do that?

**Comment by yaagna** [comment]
Yes the build is working and it gives the path of 'bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/examples/hello_world/hello_world_sim_dv.64.vmem'

But in loading the binary to ventilator is difficult for me as I am don't know the command to do that. On the opentitan YouTube video "https://www.youtube.com/watch?v=fczdna1Thks" at 3:12 mins a command to boatload is written which I think becomes "./hw/top_earlgrey/Vtop_earlgrey_verilator --rominit=./sw/device/sim/boot_rom/rom.vmem --flashinit=./sw/device/sim/examples/hello_world/hello_world_sim_dv.64.vmem" for my case but it throws an error saying "-bash: ./hw/top_earlgrey/Vtop_earlgrey_verilator: No such file or directory"

So, I guess some name is changed ? The video is 4 years old.

**Comment by jwnrt** [comment]
Yeah, that must be out of date.

It's gonna take me a while to build Verilator locally here, but in the meantime please could you run `bazel cquery --output=files //sw/device/tests:hmac_smoketest_sim_verilator`? Fingers crossed this should point you to a bash script. That script should hopefully tell you the correct command to run something in Verilator. I won't be able to confirm myself until the Verilated sim is built.

**Comment by yaagna** [comment]
Yes , it ran and the bash file is as follows

<img width="899" alt="Screenshot 2024-05-13 at 9 03 39 AM" src="https://github.com/lowRISC/opentitan/assets/63107418/9f0b7725-66be-490c-914a-37b21cd1b8c3">

**Comment by yaagna** [comment]
ohh okay I will try and update you.

**Comment by pamaury** [comment]
**Automatic method**
The easiest way, by far, is to create a test target and run it. First apply the following diff:
```diff
diff --git a/sw/device/examples/hello_world/BUILD b/sw/device/examples/hello_world/BUILD
index 0edbe962d0..b764a9174d 100644
--- a/sw/device/examples/hello_world/BUILD
+++ b/sw/device/examples/hello_world/BUILD
@@ -2,7 +2,7 @@
 # Licensed under the Apache License, Version 2.0, see LICENSE for details.
 # SPDX-License-Identifier: Apache-2.0
 
-load("//rules/opentitan:defs.bzl", "opentitan_binary")
+load("//rules/opentitan:defs.bzl", "opentitan_binary", "opentitan_test", "verilator_params")
 load("//rules:files.bzl", "exclude_files")
 load("@rules_pkg//pkg:mappings.bzl", "pkg_files")
 
@@ -29,6 +29,18 @@ opentitan_binary(
     ],
 )
 
+opentitan_test(
+    name = "hello_world_test",
+    verilator = verilator_params(
+        binaries = {
+            ":hello_world": "firmware",
+        },
+    ),
+    exec_env = {
+        "//hw/top_earlgrey:sim_verilator": None,
+    }
+)
+
 cc_library(
     name = "hello_world_lib",
     deps = [
```
and then run:
```bash
./bazelisk.sh run //sw/device/examples/hello_world:hello_world_test_sim_verilator
```
Note that here I am using `run` and not `test` because hello world is not a well-defined test so this will just the simulator forever.

**Manual method**

I don't recommand it but if you real want to do every step manually, here is how to do it.

You can build verilator this way. I suggest you make a copy of the binary due to bazel weirdnesses:
```bash
./bazelisk.sh build //hw:verilator_real
# Copy verilator binary to some place safe
VERILATOR_BIN=/path/to/safe/place
cp $(./bazelisk.sh cquery --output=files //hw:verilator_real | grep Vchip_sim_tb) $VERILATOR_BIN
```
Now assuming you have build hello world:
```bash
./bazelisk.sh build //sw/device/examples/hello_world
# query output files
./bazelisk.sh cquery --output=files //sw/device/examples/hello_world
```
and example output is
```bash
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/examples/hello_world/hello_world_fpga_cw310.bin
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/examples/hello_world/hello_world_sim_dv.64.scr.vmem
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/examples/hello_world/hello_world_sim_dv.logs.txt
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/examples/hello_world/hello_world_sim_dv.rodata.txt
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/examples/hello_world/hello_world_sim_dv.64.vmem
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/examples/hello_world/hello_world_sim_verilator.64.vmem # <-- this one
```
You will also need a ROM. Here let's use the test_rom:
```bash
./bazelisk.sh build //sw/device/lib/testing/test_rom
# query output
./bazelisk.sh cquery --output=files //sw/device/lib/testing/test_rom
```
output:
```bash
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/lib/testing/test_rom/test_rom_fpga_cw310.39.scr.vmem
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/lib/testing/test_rom/test_rom_fpga_cw310.32.vmem
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/lib/testing/test_rom/test_rom_fpga_cw305.39.scr.vmem
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/lib/testing/test_rom/test_rom_fpga_cw305.32.vmem
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/lib/testing/test_rom/test_rom_fpga_cw340.39.scr.vmem
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/lib/testing/test_rom/test_rom_fpga_cw340.32.vmem
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/lib/testing/test_rom/test_rom_sim_dv.39.scr.vmem
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/lib/testing/test_rom/test_rom_sim_dv.logs.txt
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/lib/testing/test_rom/test_rom_sim_dv.rodata.txt
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/lib/testing/test_rom/test_rom_sim_verilator.39.scr.vmem # <--- this one
bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/lib/testing/test_rom/test_rom_sim_verilator.32.vmem
```
You also need an OTP image:
```bash
./bazelisk.sh build //hw/ip/otp_ctrl/data:img_rma
# query
./bazelisk.sh cquery --output=files //hw/ip/otp_ctrl/data:img_rma
```
output
```bash
bazel-out/k8-fastbuild/bin/hw/ip/otp_ctrl/data/img_rma.24.vmem
```
You can now run verilator manually this way:
```bash
$VERILATOR_BIN --meminit=rom,bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/lib/testing/test_rom/test_rom_sim_verilator.39.scr.vmem --meminit=flash0,bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/examples/hello_world/hello_world_sim_verilator.64.vmem --meminit=otp,bazel-out/k8-fastbuild/bin/hw/ip/otp_ctrl/data/img_rma.24.vmem
```
If you further needed, say, an OTP image then you would also need to specify it use `--meminit=otp,...` and the similar principle works if you want to use the actual mask ROM and not the test ROM.

**Comment by pamaury** [comment]
Yes the process is the same for the other examples because they do not have a bazel test point. I am not sure what you mean by a c++ model (I am not a HW engineer so it may be obvious to you ^^), can you describe a bit what/how it is supposed to run so we can help you?

**Comment by yaagna** [comment]
So, basically my model tries to simulate Multiparty Computation between two parties. Let's say Alice and Bob. So, Alice will encrypt her data and send to Bob and bob decrypts the data performs the computation (on his data as well as data send by Alice) and then gives the final result.

**Comment by jwnrt** [comment]
That sounds like a pretty cool project. I'm also not a hardware engineer so take this with a grain of salt, but I imagine you will need to make a few changes to connect your model to the opentitan model.

I'm glad you got the `hello_world` example running. I'm going to close this issue, but feel free to open another with questions about the model (or ask in our Zulip if you want). It might get more visibility from a hardware engineer.
