### ISSUE TITLE
[dvsim] Issue about scratch-root

### ISSUE THREAD

**Issue by desorya** [lowRISC/opentitan#23093]
### Description

Hi there,

I'd like to ask that what else need to do when modify the SCRATCH_ROOT using `--scratch-root`?

When running dvsim, once I specified the path of SCRATCH_ROOT I got an error to all the IPs in the form of:
```
ERROR: '<VLNV name>' or any of its dependencies requires '<VLNV name without version>', but this core was not found 
```

And I haven't find a way to reset it other than re-clone the whole repo. 

I wonder if I missed something or the path of the sim results can not be modified in such way?

Thank you!

**Comment by desorya** [comment]
@rswarbrick
Besides, I'd like to report that for `util/dvsim/dvsim.py`, the code modifies the attribute `max_odirs` in the Launcher by user input:
```
line 726, Launcher.Launcher.max_odirs = args.max_odirs
```
This modification succeeded but in function `_make_odir(self)` in `util/dvsim/Launcher.py`:
```
line 175, clean_odirs(odir=self.deploy.odir, max_odirs=self.max_odirs)
```
The `max_odirs` passed to `clean_odirs` is still 5, the defualt value, not user-defined.

I changed it into:
```
clean_odirs(odir=self.deploy.odir, max_odirs=Launcher.max_odirs)
```
and it works for me.

My OS is centos7 FYI.

Thank you.

**Comment by rswarbrick** [comment]
That's rather strange. I'm afraid I don't really know how this is supposed to work (I wasn't the author of this bit of the code).

My guess is that the original author had got a bit confused about inheritance for class variables in Python (it's not obvious to me either!). Presumably, we're changing the value in the base class (`Launcher`) but not in the derived class (probably `LocalLauncher`). A quick grep doesn't show me any reason that the subclasses should have their own copies of this class variable, so I suggest just deleting the redefinitions from the two subclasses. Could you try that and see whether it works? If so, please file a PR :-)

**Comment by desorya** [comment]
It works form my side. I've filed a PR :-D

**Comment by desorya** [comment]
@rswarbrick 
The deletion from subclasses `SgeLauncher` and `LocalLauncher` works on my side and there is no longer a need to modify the base class `Launcher` itself.

Btw back to my first question, I wonder if there's a correct method to designate an output path for scratch directory?

The command
```
python util/dvsim/dvsim.py ... --scratch-root <PATH>
```
may result in a fatal structural error regarding `ERROR: '<VLNV name>' or any of its dependencies requires '<VLNV name without version>', but this core was not found ` for all of the internal and external IPs even without any other changes.

It looks like there may have been some changes to the search tree. I didn't modify the source tree of the project myself, but I'm not sure if that command did so.

Thank you.

**Comment by desorya** [comment]
@rswarbrick 
It was my bad and l just found how this happened.

I used `-sr .` in my previous attempt, which generated a `FUSESOC_IGNORE` file in the project root and blocked subsequent searches for the core files in the project root, thus throwing the error.

**Comment by rswarbrick** [comment]
Brill! In which case, I think this is all resolved. Please re-open if there's anything that should be added to this ticket.
