### ISSUE TITLE
[test-triage] USB DV failures

### ISSUE THREAD

**Issue by jwnrt** [lowRISC/opentitan#23129]
### Hierarchy of regression failure

Block level

### Failure Description

We had quite a few usbdev failures last night, likely related to https://github.com/lowRISC/opentitan/pull/23061.

The new failures are:

* `usbdev_out_stall`
* `usbdev_phy_pins_sense`
* `usbdev_setup_trans_ignored`
* `usbdev_out_trans_nak`
* `usbdev_data_toggle_restore`

I won't paste all of the failures here, but here's a link to the results: https://reports.opentitan.org/hw/ip/usbdev/dv/latest/report.html

### Steps to Reproduce

- GitHub Revision: [00fe426038](https://github.com/lowrisc/opentitan/tree/00fe42603818201da9ef15af892515113cb9540f)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  - ```
    ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i usbdev_out_stall --build-seed 56275124637035941820967954627144971699378360917446801543187025394370981034792 --fixed-seed 106247517304100048910518525394816776713227795932927862909762954696420467672466 --waves fsdb
    ```
  - ```
    ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i usbdev_phy_pins_sense --build-seed 56275124637035941820967954627144971699378360917446801543187025394370981034792 --fixed-seed 64075074256036428496691162217501663565078712811009624972620691263732705112850 --waves fsdb
    ```
  - ```
    ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i usbdev_setup_trans_ignored --build-seed 56275124637035941820967954627144971699378360917446801543187025394370981034792 --fixed-seed 94139371642807007846479779165606758568027409706027793132358510586003170370926 --waves fsdb
    ```
  - ```
    ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i usbdev_out_trans_nak --build-seed 56275124637035941820967954627144971699378360917446801543187025394370981034792 --fixed-seed 86316187622989411203703873426669547988791627251306841840821203154562143328281 --waves fsdb
    ```
  - ```
    ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i usbdev_data_toggle_restore --build-seed 56275124637035941820967954627144971699378360917446801543187025394370981034792 --fixed-seed 38166465933304166370727055802927316966723527257780076941544686186695148613927 --waves fsdb
    ```


### Tests with similar or related failures

- [ ] `usbdev_out_stall`
- [ ] `usbdev_phy_pins_sense`
- [ ] `usbdev_setup_trans_ignored`
- [ ] `usbdev_out_trans_nak`
- [ ] `usbdev_data_toggle_restore`

**Comment by alees24** [comment]
#23133 is expected to fix most of them, but the pass rate probably will not return quite to previous levels because new tests have been introduced which trigger known deficiencies in the DV. (usb20_monitor does not handle the presence of invalid/corrupted traffic on the bus, and we are now introducing tests specifically to test the USBDEV response to bad traffic.)

**Comment by andreaskurth** [comment]
Closing as tests are above 90% pass rate again. Thx!
