### ISSUE TITLE
[hmac] Add endianness swap option to KEY registers

### ISSUE THREAD

**Issue by ballifatih** [lowRISC/opentitan#23158]
### Description

For MSG_FIFO and DIGEST registers of HMAC, we have the option of changing the endianess, and the driver enables them to match Ibex's little endian addressing. Here is how we configure them at the moment:
https://github.com/lowRISC/opentitan/blob/349bab6601c24b1d01b7264296bfc1c3bcd6c631/sw/device/lib/crypto/drivers/hmac.c#L53-L56

Ibex is running on little endian, which means that when we have a key/msg vector as follows:

https://github.com/lowRISC/opentitan/blob/28643828cb74dde504cc6b4d17dc458e2c2130a4/sw/device/tests/crypto/hmac_sha256_functest.c#L28-L34

however this representation does not match HW's expectation. Would it be possible add a similar option for KEY registers so that the driver can enable endianness swap? My worry is that if we have to change endianness at driver level, it would be quite awful from SCA perspective, as it handles key bytes during the swapping.

cc: @gdessouky @martin-velay @andreaskurth

**Comment by gdessouky** [comment]
That makes sense, and should be possible, but will require quite a bit of corresponding DV changes. @ballifatih, can it be the same `endian_swap_bit` we use for the digest registers, or do you see a need for independent bits? 

I would have this as a last priority change, especially since HMAC is not SCA-hardened anyway, or at least have the corresponding DV a last priority because of all the DV work happening at the moment.

**Comment by ballifatih** [comment]
We do not need an explicit setting for key so we can reuse `endian_swap_bit` (or even `digest_swap`) option. I think it would be nice if it isn't adding too much DV work. One use case for HMAC is HMAC-DRBG so it would be nice to have at least some amount of SCA resistance, even though HMAC is not masked.

**Comment by ballifatih** [comment]
I can actually push RTL changes for this one later, I made one-line modification for my driver PR. I think the question is more about whether there is too much DV effort invovled.

**Comment by martin-velay** [comment]
Using the existing field digest/endian swap might be a source of confusion. I would prefer to have a dedicated field `key_swap`. 

About the DV part of it, I would also prefer to make this change a bit later, the time we clear the existing issues. But if we add a dedicated field as suggested above, the RTL change could be merged, @ballifatih can test it at his end, and we'll just add a simple constraint in the IP level DV.

**Comment by ballifatih** [comment]
I can add `key_swap` field if it is not causing too much burden to DV, would that be OK for you @martin-velay? Or would you like me to tag this for future release?

**Comment by martin-velay** [comment]
You can add it this field and and RTL related changes that you need, it won't break anything that way. Could you also raise an issue to test it on the HMAC DV as a P3 please?

**Comment by andreaskurth** [comment]
Adding a `key_swap` field to the `CFG` CSR and implementing this in a way that the reset value (`0`) retains the current behavior SGTM. We can then verify the enabled key swapping as part of M5. @ballifatih can you do the RTL changes this week, and @martin-velay could you afterwards create a DV issue to verify this as part of M5, please?

**Comment by gdessouky** [comment]
> Adding a `key_swap` field to the `CFG` CSR and implementing this in a way that the reset value (`0`) retains the current behavior (no swapping of key bytes) SGTM. We can then verify the enabled key swapping as part of M5. @ballifatih can you do the RTL changes this week, and @martin-velay could you afterwards create a DV issue to verify this as part of M5, please?

I am touching the `hmac.hjson` now to expose the idle bit, will go ahead and add the `key_swap` field while at it.

**Comment by andreaskurth** [comment]
Closing as completed in #23242.
