### ISSUE TITLE
[ROM] Implement AST alert reset configuration and post-reset behavior

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#23150]
As described in [this implementation recommendation](https://docs.google.com/document/d/1KTAkLexrTPsEyJrMc6Auxiuxdv161GdEnyTbjLDY6Fw/edit): At reset we want all alerts in sensor_ctrl to be enabled and set to recoverable. During ROM boot and _before_ alert_handler is configured, we want ROM to read OTP values (from the `OWNER_SW_CFG` OTP partition) to disable specific alerts in sensor_ctrl or set them to fatal.

## TODOs

- [ ] Extend ROM to read the OTP values, verify their digest, and configure sensor_ctrl accordingly, then wait a few cycles (20 cycles in the slower clock domain of sender and receiver should be sufficient) for outstanding handshakes to complete before configuring alert_handler.
- [ ] Mention this design in ROM’s documentation.

Note that this issue is about changes to ROM. See #23149 for the changes to sensor_ctrl RTL and OTP partitions.

**Comment by cfrantz** [comment]
> then wait a few cycles (20 cycles in the slower clock domain of sender and receiver should be sufficient) for outstanding handshakes to complete before configuring alert_handler.

I assume the slower clock domain is the AON domain.  Can I simply use the PWRMGR_CFG_CDC_SYNC register to perform this wait, or is it preferable to use one of the counters in the AON_TIMER peripheral?

**Comment by andreaskurth** [comment]
Using PWRMGR_CFG_CDC_SYNC is probably simpler

**Comment by andreaskurth** [comment]
Closing as completed in #23513, thx @cfrantz!
