### ISSUE TITLE
[manuf] TPM provisioning sequence needs to include generation of a 512 bit secret

### ISSUE THREAD

**Issue by vbendeb** [lowRISC/opentitan#23237]
### Description

This secret needs to be reproducible by the chip in the specific state of the key ladder, and a derivative of this secret (usually the 16th order of hmac) needs to be reported and stored by the host during personalization.

**Comment by timothytrippel** [comment]
@vbendeb I think we can close this now?

**Comment by timothytrippel** [comment]
Confirmed with @vbendeb ; closing.
