### ISSUE TITLE
[top_earlgrey,ROM] Configure AST mux selectors on IOB[0:3] based on OTP bits

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#23282]
As we're adding muxes on IOB[0:3] (PR #23201), which are controlled by AST CSRs (issue #23280), ROM needs to read OTP values (issue #23281) and configure the AST CSRs based on those values.

This issue is about implementing the ROM part.

**Comment by moidx** [comment]
This should already be covered as part of the AST init configuration based on #23281.

CC @meisnere, @andreaskurth, @sha-ron. 

@sha-ron Please let us know if ok to close this issue from your perspective. Thanks

**Comment by sha-ron** [comment]
Yes. it is already covered as part of the AST init configuration.
