### ISSUE TITLE
[top_earlgrey,ast/dv] Verify muxing of IOB[0:3] through AST CSRs

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#23283]
PR #23201 added muxes on IOB[0:3] and issue #23280 tracks adding AST CSRs to control those muxes. Once those are done, we need to verify that this muxing works.

**Comment by sha-ron** [comment]
Yes sure, thanks @andreaskurth.

**Comment by johngt** [comment]
@sha-ron - could you please provide an update on how this has gone?

**Comment by sha-ron** [comment]
It is still ongoing, will close the issue when done.

**Comment by sha-ron** [comment]
Check is done.
