### ISSUE TITLE
[top_earlgrey,pinmux] For BidirOd pads, default to open drain?

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#23296]
> However, there still exists a parallel connection to the supply rail through a protection circuit.
> Therefore:
> - For **BidirOd** pads in open drain mode, the output protection circuit allows voltages that exceed the supply voltage.

The statement as written seems to imply that BidirOd pads not in open drain mode do not allow voltages that exceed the supply voltage.  Is that an accurate statement?

If so, I think there is a potential problem.  As far as I can tell the reset default for MIO_PAD_ATTR is zero for all pads, meaning that a random watchdog reset would put all open drain pads into a mode in which they do not tolerate voltages exceeding the supply.  If that is true, it would severely limit the usefulness of the open drain pads.  Do we need to modify the reset default for some pads to have open drain enabled, or do the BidirOd pads tolerate voltages in excess of the supply voltage under other circumstances, such as when "output enable" is not asserted?

_Originally posted by @jesultra in https://github.com/lowRISC/opentitan/pull/23031#discussion_r1612464359_

**Comment by andreaskurth** [comment]
Question sent to silicon team

**Comment by moidx** [comment]
Issue related to [#23270](https://github.com/lowRISC/opentitan/issues/23270). Let's continue the conversation there.
