### ISSUE TITLE
Missing  MMIO base address and interrupts

### ISSUE THREAD

**Issue by alistair23** [lowRISC/opentitan#2331]
The high level list of registers in the [OpenTitan documentation](https://docs.opentitan.org/hw/top_earlgrey/doc/) does not include the addresses of all of the [IP listed in the documentation](https://docs.opentitan.org/hw/index.html). For example I2C and power management are both missing.

Can the IP blocks that don't have MMIO regions and interrupts documented (like I2C and Power Management) please be documented.

For I2C I can't even find the address in the RTL, `top_earlgrey.json` and `top_earlgrey.h` don't mention the I2C at all.

**Comment by eunchan** [comment]
I am preparing more complete memory map now. Thanks for the report.

**Comment by alistair23** [comment]
@martin-lueker

**Comment by msfschaffner** [comment]
The system memory map is now rendered in the top-level docs, hence I think we can close this (otherwise, please reopen): https://docs.opentitan.org/hw/top_earlgrey/doc/design/#memory-map
