### ISSUE TITLE
[sram_ctrl/dv] Adapt throughput tests for readback mode

### ISSUE THREAD

**Issue by nasahlpa** [lowRISC/opentitan#23321]
### Description

With the introduction of the readback mode (c.f., #23212), the throughput tests need to be adapted to take the additional delay introduced by this feature into account. Currently, the readback feature is disabled for these tests.

**Comment by vogelpi** [comment]
This seems doable without huge effort but the priority isn't very high as the feature can be disabled at run time.

**Comment by vogelpi** [comment]
This doesn't seem like a priority to me. I suggest moving to M7.
