### ISSUE TITLE
Not all IP blocks are listed in the documentation

### ISSUE THREAD

**Issue by alistair23** [lowRISC/opentitan#2332]
The [IP listed in the documentation](https://docs.opentitan.org/hw/index.html) is missing blocks (like the power management). Can all of the HW blocks be added to the documentation?

**Comment by sjgitty** [comment]
yep, working on it, thanks @alistair23

**Comment by tjaychen** [comment]
all the IPs should be there now.
Yes sorry I'm closing this more than 2 years later.
