### ISSUE TITLE
util/tlgen.py does not support a host with one device?

### ISSUE THREAD

**Issue by yaozhaosh** [lowRISC/opentitan#2337]
I tried to modify the connections in example/tlgen/xbar_2x2.hjson:

```
connections: {
  h0: ["d0", "d1"],
 h1: ["d0"]
}
```
it reported the error:
```
ERROR: get_s1n_if_exist hits DEVICE type (unexpected)
```

With the connections change, I changed the clock and reset of "h1" to the "main" ones, it reported the error:
```
ValueError: [U(h1) D(sm1-5)] is not in list
```

It is possible that one host has only one device connected in a sparse connection. Would you please help to take a look at if the script support this scenario?

Thanks a lot!

**Comment by imphil** [comment]
CC @eunchan

**Comment by eunchan** [comment]
Hum.. I think current tool has a corner case. If one host connects to a device, the tool doesn't insert sockets in between (if clock is also same). Then checking the downstream addresses causes error as seen above. Thanks for reporting the issue. I will check how I can add this into tlgen.

**Comment by msfschaffner** [comment]
@andreaskurth FYI

**Comment by msfschaffner** [comment]
I believe we partially fixed this already for integrated. 
Worth checking whether this can be cherry-picked over.

**Comment by andreaskurth** [comment]
I think https://github.com/lowRISC/opentitan/commit/7c0e4bd0b64dd15da08d059a6c82f1cb2e6d359f (from the Integrated branch) should fix thsi
