### ISSUE TITLE
[ROM] Increase test coverage for SLH-DSA (SPX+) enabled

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#23388]
### Description

Consider enabling SPX+ in FPGA SiVal execution environments to improve test coverage.

- [x] https://github.com/lowRISC/opentitan/pull/23391
- [x] https://github.com/lowRISC/opentitan/pull/23442

**Comment by cfrantz** [comment]
@moidx is this issue completed?  Closing this issue; please re-open if needed.
