### ISSUE TITLE
[ROM] Ensure there is a way to disable alert handler ping mechanism

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#23393]
### Description

Ensure there is an OTP configuration option to disable the alert handler pinging mechanism to mitigate potential issues during silicon bring-up. See https://github.com/lowRISC/opentitan/issues/22954 for example.

**Comment by cfrantz** [comment]
As of 126422a98eba6cfbabeff7a33e0731be46efe9da, `alert_ping_enable` is not called by the ROM.

**Comment by moidx** [comment]
This will be handled as part of the manual test sign-off.
