### ISSUE TITLE
[rom,rom_ext] add support for a non-mutable code section to ROM_EXT

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#23425]
This issue is was originally a sub-task in #21583, but it has been split off into a separate issue here. 

Note, **this a lower priority item**, but it may be a useful escape hatch to improve the security posture of the chip over time through provisioning and SW updates, as opposed to ROM/HW changes, as discussed [here](https://github.com/lowRISC/opentitan/issues/21583#issuecomment-2027577371).

As discussed in #21583, it would be convenient to add a non-mutable ROM_EXT code section that serves as the entry point to the ROM_EXT by:

Addressed in #23840:
- [x] updating OTP memory map to add a ROM_EXT non-mutable code section hash field that will be provisioned with a SHA256 hash of the non-mutable section that should be jumped to after ROM execution
- [x] check the non-mutable ROM_EXT code hash region during the boot flow in the ROM
- [x] add a non-mutable code section to the ROM_EXT that is the new entry point (initial section should be a single (hardened) jump instruction that jumps to the mutable ROM_EXT region)
- [x] add ROM E2E test to check the behavior of the above

**Comment by vsukhoml** [comment]
What about rescue procedure for ROM? E.g. firmware erroneously wrote bad code in this non-mutable ROM_EXT part. Now with rescue it would be nice to have some reporting on console what is the expected digest vs. computed - may be first few digits of digest in OTP to identify ROM_EXT to provision and check the source of error.
