### ISSUE TITLE
[manuf] enhance personalization flow to enable per-SKU customizations

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#23426]
We currently implement a reference provisioning flow that provisions a base set of certificates into the chip. However, various SKUs and SKU owners will undoubtedly desire different sets of certificates and/or secrets be provisioned into the chip to suit their use cases. As such, there are some enhancements to the personalization firmware and host logic that can be made to make it more amenable to SKU-owner customization, e.g., adding dependency-injected extension functions to enable adding functionality to the base provisioning flows.

# Tasks:

- [x] enable a "manufacture_hooks" style Bazel repo extension mechanism to facilitate writing customized perso flow extensions (#23951)
- [x] move the TPM provisioning to a perso extension

**Comment by tommychiu-github** [comment]
Thanks for the detailed describing. I'd like to contribute on this issue.
