### ISSUE TITLE
[hmac,doc] Align documentation with changes

### ISSUE THREAD

**Issue by gdessouky** [lowRISC/opentitan#23455]
### Description

Make a pass over the entire HMAC documentation and programmer's guide and make sure it is aligned with all the recent changes and new features added, e.g.,
- block diagrams
- fix latencies for different digest sizes
- context switching/one-shot calls 
- how `hmac_done` and `idle` are expected to work

**Comment by andreaskurth** [comment]
Proposing to move to M6 to resolve this as part of D3

**Comment by vogelpi** [comment]
@gdessouky , can you maybe give an update on the status of this item please?
