### ISSUE TITLE
[test-triage] USBDEV usbdev_aon_wake_resume is failing

### ISSUE THREAD

**Issue by martin-velay** [lowRISC/opentitan#23462]
### Hierarchy of regression failure

Block level

### Failure Description

Job usbdev-sim-vcs_run_default killed due to: Exit reason: Job input files use more disk space than requested *M, please increase the disk requirement.

### Steps to Reproduce

- GitHub Revision: 01a208901a5b8c29dc74f8a500b64b6b2cb5cf4c
- failing for any seed

**Comment by hayleynewton** [comment]
Seems like a fairly new test, keep an eye on through USB dev. Possibly lower priority.

**Comment by moidx** [comment]
This issue was addressed by https://github.com/lowRISC/opentitan/pull/23239
