### ISSUE TITLE
[test-triage] chip_sw_uart_tx_rx_bootstrap reaches timeout

### ISSUE THREAD

**Issue by martin-velay** [lowRISC/opentitan#23487]
### Hierarchy of regression failure

Chip Level

### Failure Description

Job chip_earlgrey_asic-sim-vcs_run_default killed due to: Exit reason: User job exceeded runlimit: User job timed out

### Steps to Reproduce

- GitHub Revision: 01a208901a5b8c29dc74f8a500b64b6b2cb5cf4c
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_uart_tx_rx_bootstrap --fixed-seed 8297356148450362255802387402225996801695448381906300269912928029522279831259 --waves fsdb

**Comment by hayleynewton** [comment]
Improved but now is failing completely.
