### ISSUE TITLE
[spi_host, dv] V2S signoff

### ISSUE THREAD

**Issue by antmarzam** [lowRISC/opentitan#23490]
### Description
Get spi_host ready for V2S signoff and sign it off

**Comment by antmarzam** [comment]
### DESIGN_DELTAS_CAPTURED_V2

List of commits since ES. The list has been compiled via:
```
git log Earlgrey-M2.5.2-RC0..HEAD hw/ip/spi_device/ hw/dv/sv/spi_agent/
```

Newer commits at the top (reverts have been removed):

* d268f271f4 [spi_host/doc]: Correct RST -> SW_RST typo
* ee5f4a1abf [sram_ctrl] Add readback feature
* 11107d5e80 [spi_host] Disable FWFT for the command queue
* 12f60880bd [dv] spi_device_scoreboard flash_status fix
* 432200b06e [dv] spi_monitor fix:
* dc848b3e2a [sram_ctrl,prim,rtl] Fix tlul_we -> ready timing path.
* 66f99a7c3f [spi_host,doc] Cleanup readme and theory-of-operations
* ed56f75219 [spi_host,doc] Move misplaced doc sections around, fixup errors
* 45b6e02e10 [spi_host,doc] Update diagrams to seperate passthrough mux
* 8295903d7e [bazel,autogen_hjson] Split C and rust header generation
* 30d7e787c7 Add the project name to the copyright header
* f4c2bb9030 Remove trailing whitespaces
* a5ce859c07 [spi_host,doc] Clarify that the 'spi_event' interrupt is Status-Type
* 3e9cb7bea6 [spi_host,dv] Update testplan based on D2(S) changes
* ec43583573 [dv] intercept sequence && intr_status stimulus update
* 42dfffeb8c [dv] flash_status dynamically updated TB update
* 9868fa8aa9 [spi_host] Downgrade verification_stage to V1
* 508cd2ff22 [spi_host] Correct TXFULL description
* 18b0cedda1 [dv] Remove phase argument from monitor's collect_trans
* 6e1273580f [spi_host] Fix "bute"/"byte" typo in registers
* e3ca274e77 [spi_host,rtl] Use sd_en_o[0] to only drive sd_o[0] during TX (std_mode)
* 6771ad7f45 Revert "[dv] Remove phase argument from monitor's collect_trans"
* d39c54d91d [dv] Remove phase argument from monitor's collect_trans
* f7fc348358 [spi_host,rtl] Change 'spi_event' interrupt to CIP 'Status' type
* 369be91feb [spi_host,doc] Regenerate register documentation
* 272787cf68 [spi_host,rtl] Factor the byte_sel block into TX FIFO status signals
* 51394dc45b Revert "[spi_host,rtl] Use sd_en_o[0] ..." ( fbbd660 )
* fbbd660c94 [spi_host,rtl] Use sd_en_o[0] to only drive sd_o[0] during TX (std_mode)
* 0d14dd693f [docs] Fix repetitions of the definite article
   * doc change
* 61a237e197 [util/reggen] reverse order of substruct generation
   * reggen order reversed
* fc8484601e [reggen,hw] Create index parameter for registers windows
   * Add Index parameters to RTL reg package
* de31bdf1c2 [reggen] Remove the devmode input
   * devmode input remove from exclusions top-level, reg_top and README
* 963a5006cc [doc] Minor tweak to md sanitisation code
   * doc cleanup
* 975a6eb927 [adc_ctrl,dv] Tidy up access to intr_state in env_cfg files
   * Code tidy up
* 3f128e781f [spi_host] Add feature list for block
   * Feature list added to spi_host.hjson
* 1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
   * RTL reg change
* 59f8142826 [doc] Moved badges over to using hosted images
   * doc change
* 8c772349f3 [doc] spi_host registers and interfaces now use CMDGEN
   * doc change
* 7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
   * Regtool change

**Comment by antmarzam** [comment]
## V3 checklist scoping:
### X_PROP_ANALYSIS_COMPLETED: 
There are RTL blocks reported as disabled for XPROP, but these are not RTL blocks, just refer to code which isn't synthesizable.

### SIM_NIGHTLY_REGRESSION_AT_V3: 
We have no testing enabled at V3 level, presumably due to the failing rate of `spi_host_stress_all_with_rand_reset` - @hcallahan-lowrisc Do you have a view on how long getting these test to 100%?
The rest of the regression is in decent shape, with the lowest passing rate at 88% for `spi_host_status_stall`

### SIM_CODE_COVERAGE_AT_100: 1 week of estimate effort
### SIM_FUNCTIONAL_COVERAGE_AT_100: 1 week of estimate effort
### ALL_TODOS_RESOLVED: 
P2 issue currently wraps all TODOs. 
### NO_TOOL_WARNINGS_THROWN: 1 day
### TB_LINT_COMPLETE: Already satisfied

**Comment by antmarzam** [comment]
cc @rswarbrick @hcallahan-lowrisc

**Comment by johngt** [comment]
Thanks for the summary @antmarzam - it looks like https://github.com/lowRISC/opentitan/pull/23476 is the main thing to get in as a priority.

**Comment by antmarzam** [comment]
Thank you guys!
Before we can sign-off the module, we have the following action items from V2/V2S meeting:

- [ ] RTL PR needs to be in master 
- [ ] DV changes need to be in master
- [ ] `data_fifo_status` testpoint is not linked to any tests
