### ISSUE TITLE
[rom,rom_ext] Consider using SRAM readback feature

### ISSUE THREAD

**Issue by nasahlpa** [lowRISC/opentitan#23495]
### Description

Recently, we introduced the #23212 readback feature to the SRAM.

When enabled, each read request to the SRAM will be performed twice and checked. On a write, the written data is read back and compared. On an error, a fatal alert is triggered.

#23395 adds the DIF for using this feature.

In ROM/ROM_EXT we should consider using this feature.

**Comment by nasahlpa** [comment]
@vogelpi FYI

**Comment by vogelpi** [comment]
Thanks for creating the issue Pascal. I am putting this into the ROM milestone. We can already enable it in ROM based on an OTP setting @moidx .

**Comment by nasahlpa** [comment]
@cfrantz OK to close this issue?
