### ISSUE TITLE
[test-triage] OTBN issue with the Python scripts

### ISSUE THREAD

**Issue by martin-velay** [lowRISC/opentitan#23509]
### Hierarchy of regression failure

Block level

### Failure Description

Similar errors are often raised while running some OTBN tests:
```
* `Job returned non-zero exit code` has 1 failures:
    * Test otbn_zero_state_err_urnd has 1 failures.
        * 0.otbn_zero_state_err_urnd.49783223393755823323792651049911603757994003625678540082947296603666494076901\
         Log /home/dev/src/scratch/master/otbn-sim-xcelium/0.otbn_zero_state_err_urnd/latest/run.log

                    gen_res = self.gen(model, program, end)
                  File "/home/dev/src/hw/ip/otbn/dv/rig/rig/snippet_gens.py", line 167, in gen
                    gen_res = generator.gen(self.gens, model, program)
                  File "/home/dev/src/hw/ip/otbn/dv/rig/rig/gens/branch_gen.py", line 81, in gen
                    off_enc = self.imm_op_type.op_val_to_enc_val(tgt_addr, model.pc)
                  File "/home/dev/src/hw/ip/otbn/util/shared/operand.py", line 430, in op_val_to_enc_val
                    raise ValueError('Cannot encode the value {}{} as a {}-bit '
                ValueError: Cannot encode the value -6410, which encodes to -3205, as a 12-bit signed value. Possible range: -4096..4094.
                ninja: build stopped: subcommand failed.
                make: *** [/home/dev/src/hw/dv/tools/dvsim/sim.mk:52: pre_run] Error 1

```

### Steps to Reproduce

- GitHub Revision: a182fcef27866fb502d8cceb810bdf76cfa3ef42
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
util/dvsim/dvsim.py hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson -i otbn_zero_state_err_urnd -t xcelium --fixed-seed 49783223393755823323792651049911603757994003625678540082947296603666494076901

**Comment by hayleynewton** [comment]
otbn_zero_state_err_urnd - 100%

**Comment by rswarbrick** [comment]
Thanks for the diagnosis. This is indeed a silly bug in the random instruction generator, which causes sporadic failures. I should hopefully be able to address it soon, but it definitely isn't needed for M4: it's not going to hide any RTL bugs! Removing the milestone tag.
