### ISSUE TITLE
Add tests for functions in the mmio library

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#2354]
Created to capture the feedback recevied in #2066.

**Comment by silvestrst** [comment]
@silvestrst (so that notifications go into the right folder)

**Comment by msfschaffner** [comment]
@alphan @cfrantz @timothytrippel is this still relevant?

**Comment by timothytrippel** [comment]
I think these functions are pretty well tested by now across all the DIFs and other top-level tests. Feel free to reopen if you disagree.
