### ISSUE TITLE
[rv_core_ibex] Test alerts triggered from security alerts

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/opentitan#23569]
### Description

This is specific to the new hardening features added since D2S:
- https://github.com/lowRISC/ibex/commit/8ec0c6f1
- https://github.com/lowRISC/ibex/commit/35bbdb7b
- https://github.com/lowRISC/ibex/commit/5977d4e3

Although the primitive block that generates these interrupts are well tested in the rest of OpenTitan it is always good to do an end to end check where you inject the fault and check that the alert is propagated through the whole design.

Related to: https://github.com/lowRISC/opentitan/issues/23542#issuecomment-2154629103

**Comment by GregAC** [comment]
Closing in favour of https://github.com/lowRISC/opentitan/issues/23573
