### ISSUE TITLE
[rv_core_ibex,dv] Extending existing chip_sw_rv_core_ibex_lockstep_glitch test to cover lockstep control faults

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#23572]
Extra hardening has been added to the control logic around lockstep in Ibex: https://github.com/lowRISC/ibex/commit/8ec0c6f1

The existing `chip_sw_rv_core_ibex_lockstep_glitch` test should be extended to inject faults in these

https://github.com/lowRISC/opentitan/blob/27279ff687cb16bf10fa5c9748d2b1aed4ede5cf/hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson#L214-L225

The new functionality will randomly insert a single bit stuck-at-1 or stuck-at-0 fault into `enable_cmp_q` in `ibex_locksteps` along with its existing fault injection. The stuck-at-1 or stuck-at-0 should not effect the result of the test.

**Comment by nasahlpa** [comment]
PR is available at #23885
