### ISSUE TITLE
[rv_core_ibex] New Ibex tests to cover security hardening

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#23573]
This issue is to track the implementation of new tests within the Ibex testbench for testing security hardening features, from gaps highlighted in the M4 V2(S) sign-off review https://github.com/lowRISC/opentitan/issues/23542

- [x] https://github.com/lowRISC/ibex/issues/2175
- [x] https://github.com/lowRISC/ibex/issues/2174
- [x] https://github.com/lowRISC/ibex/issues/2173

**Comment by vogelpi** [comment]
I'd suggest adding these tests to the `chip_sw_rv_core_ibex_lockstep_glitch` FI test. It may not look like a perfect match to do it in there but I fear we otherwise risk to spend too much effort on setup work.

**Comment by GregAC** [comment]
These are actually very easy to implement in the Ibex DV environment and I'd prefer them as block level tests rather than chip level.

**Comment by GregAC** [comment]
A PR (https://github.com/lowRISC/ibex/pull/2182) is available for https://github.com/lowRISC/ibex/issues/2174.

@nasahlpa is working on https://github.com/lowRISC/ibex/issues/2173

Work for https://github.com/lowRISC/ibex/issues/2175 is mostly complete, but I need to create a PR.

**Comment by nasahlpa** [comment]
PR for lowRISC/ibex#2173 is available here: lowRISC/ibex#2184.

**Comment by GregAC** [comment]
PR for https://github.com/lowRISC/ibex/issues/2175 is available here: https://github.com/lowRISC/ibex/pull/2185

**Comment by vogelpi** [comment]
I am closing this issue as all linked PRs have been merged and all boxes ticked off. Thanks @nasahlpa and @GregAC !
