### ISSUE TITLE
[otbn,rtl] Incorrect handling of bogus values for rma request value

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#23585]
### Description

This is visible by running `otbn_escalate` with seed 2:
```
util/dvsim/dvsim.py hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson -i otbn_escalate --fixed-seed=2
```

As @vogelpi correctly described in the comments for 5228dfccf50, the CDC for this signal means that it might have a silly value for a cycle, so we shouldn't lock up if that happens. Unfortunately, the silly value might get stored into `rma_ack_q`, at which point the check on line 375 of `otbn_start_stop_control` fires and locks the block.

I think the fix might be as simple as deleting the `state_d` update.
```
    if (mubi4_test_invalid(rma_ack_q)) begin
      rma_ack_d = MuBi4False;
      mubi_err_d = 1'b1;
      state_d = OtbnStartStopStateLocked;
    end
```

@vogelpi: Would you mind taking a look?

**Comment by rswarbrick** [comment]
Triaging as part of M4 because this seems worth making a decision about before the RTL freeze.

**Comment by vogelpi** [comment]
Thanks @rswarbrick , I've fed back in your PR.

**Comment by rswarbrick** [comment]
Ok, I'm pretty convinced the RTL is correct (and the DV code is not...). Closing this issue accordingly.
