### ISSUE TITLE
[test-triage] chip_sw_csrng_edn_concurrency_reduced_freq regularly times out

### ISSUE THREAD

**Issue by pamaury** [lowRISC/opentitan#23606]
### Hierarchy of regression failure

Chip Level

### Failure Description

The test `chip_sw_csrng_edn_concurrency_reduced_freq` regularly times out.

### Steps to Reproduce

- GitHub Revision: [a182fcef27](https://github.com/lowrisc/opentitan/tree/a182fcef27866fb502d8cceb810bdf76cfa3ef42)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_csrng_edn_concurrency_reduced_freq --build-seed 115716131103921631007013649731972014580281041353363476420230431751664670300928 --fixed-seed 40308221990956139403360512504997844009802296242472870101329624554885491880045 --waves fsdb
- Kokoro build number if applicable

**Comment by pamaury** [comment]
Fixed by #23620 ?

**Comment by vogelpi** [comment]
> Fixed by #23620 ?

Unfortunately not :-/

**Comment by vogelpi** [comment]
I've now found the issue and fixed it with #23861.

Basically, the test was waiting for the esfinal FIFO to fill up before starting the test loop. But in the reduced_freq configuration, it can be that the FIFO never fills up as the RNG produces raw entropy at a lower rate while the AST consuming part constantly consumes entropy from EDN0.
