### ISSUE TITLE
Getting  Error: Command 0x3001a001 not found in bitstream while loading vivado 24.1 generated target for CW340 other project bitstream file

### ISSUE THREAD

**Issue by LalitMPQS** [lowRISC/opentitan#23637]
### Description

I got the target FGPA board CW340 with me.

I am using the opentitan infrstructure to  be reused for  programing the FPGA with vivado 24.1 generated bitstream.

Here is what I got for the three run's

1) Opentitan bitstream run
$ ./bazelisk.sh run //sw/host/opentitantool -- fpga load-bitstream /home/lmsm/FPGA_CW340/gitlab/bitstream-latest/chip_earlgrey_cw340/lowrisc_systems_chip_earlgrey_cw340_0.1.bit
INFO: Analyzed target //sw/host/opentitantool:opentitantool (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: Elapsed time: 0.246s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/sw/host/opentitantool/opentitantool fpga load-bitstream /home/lmsm/FPGA_CW340/gitlab/bitstream-latest/chip_earlgrey_cw340/lowrisc_systems_chip_earlgrey_cw340_0.1.bit
[00:00:21] [██████████████████████████████████████████████████████████████████████████████████████████████████████████████████] 34.18 MiB/34.18 MiB

2) Below is the run for our project1
(0s)lmsm@lalit-HP-PC:~/FPGA_CW340/gitlab/5Jun2024/opentitan$ ./bazelisk.sh run //sw/host/opentitantool -- fpga load-bitstream /home/lmsm/FPGA_CW340/thames/vivado_gui/work/kcu095/thames-fpga-kcu095/thames-fpga-kcu095.runs/impl_1/block_design_wrapper.bit
INFO: Analyzed target //sw/host/opentitantool:opentitantool (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: Elapsed time: 0.277s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/sw/host/opentitantool/opentitantool fpga load-bitstream /home/lmsm/FPGA_CW340/thames/vivado_gui/work/kcu095/thames-fpga-kcu095/thames-fpga-kcu095.runs/impl_1/block_design_wrapper.bit
Error: Command 0x3001a001 not found in bitstream

3) Below is the run for our project2
$ ./bazelisk.sh run //sw/host/opentitantool -- fpga load-bitstream /home/lmsm/FPGA_CW340/thames/gitlab/pqs-hw-oskar/work/kyber-dilithium-cpkc/fpga/cw340/oskar-fpga-cw340/oskar-fpga-cw340.runs/impl_1/cw340_top.bit
Starting local Bazel server and connecting to it...
INFO: Analyzed target //sw/host/opentitantool:opentitantool (421 packages loaded, 22887 targets configured).
INFO: Found 1 target...
INFO: Elapsed time: 14.203s, Critical Path: 3.79s
INFO: 183 processes: 40 internal, 143 linux-sandbox.
INFO: Build completed successfully, 183 total actions
INFO: Running command line: bazel-bin/sw/host/opentitantool/opentitantool fpga load-bitstream /home/lmsm/FPGA_CW340/thames/gitlab/pqs-hw-oskar/work/kyber-dilithium-cpkc/fpga/cw340/oskar-fpga-cw340/oskar-fpga-cw340.runs/impl_1/cw340_top.bit
Error: Command 0x3001a001 not found in bitstream

Note on Vivado I am using the command to dump the bitstream for my two projects
launch_runs impl_1 -to_step write_bitstream -jobs 4

Any suggestion here what I am doing wrong here. Or if I have to switch to fusesoc

**Comment by a-will** [comment]
If you are building opentitan's bitstream, you should use the bazel target `//hw/bitstream/vivado:fpga_cw340`. Your bitstream is likely missing the command to write the USRACCESS register.

**Comment by LalitMPQS** [comment]
Thanks Will, how do I fix this in Vivado saved database to regenerate the bitstream.

**Comment by LalitMPQS** [comment]
Will, I am able to load the updated bitstream using the  bazelisk.sh command.
