### ISSUE TITLE
[doc] USBDev DATA_TOGGLE_CLEAR Usage

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#2364]
The USB device programmer's guide does not explain under which circumstances the data_toggle_clear register should be used (or how and when data_toggle is updated by the hardware during normal packet reception).

@gkelly and I think it might be needed when resetting the peripheral, but it would be good to have some confirmation or correction of this, as we think it will definitely bite us when the software team writes our first USB device implementation.

**Comment by mdhayter** [comment]
I believe this register should not normally be used. The hardware should correctly manage the data toggle per USB spec, including on resets etc. Probably want to mark this "Only use for hardware debug."

**Comment by lenary** [comment]
@mdhayter thanks for the info! I will add that note to the register description.

**Comment by cdgori** [comment]
The "only use for hardware debug" language raised my spidey-sense, unfortunately I have almost no context here.  

Does access to this register need to be enforced/guarded by some hardware mechanism?  What's the worst-case scenario if it's not?

**Comment by alphan** [comment]
> I believe this register should not normally be used. The hardware should correctly manage the data toggle per USB spec, including on resets etc. Probably want to mark this "Only use for hardware debug."

Just to confirm, if the host sends a clear feature ENDPOINT_HALT to an endpoint, will the data toggle bit cleared by the hardware?

**Comment by mdhayter** [comment]
I don't remember testing it, but that would be done with a SETUP control transaction which should always reset the toggle state.

**Comment by a-will** [comment]
@alphan No, software must clear the data toggle for that specific case, since only software implements the USB Device Requests. Essentially, hardware's role is at the transaction level only.

This register is _not_ only for hardware debug.

**Comment by msfschaffner** [comment]
@a-will are there any pending doc tasks for this, or can we close this issue?

**Comment by a-will** [comment]
Ah, this apparently got forgotten, as I did not assign myself. I'll fix that. (still to-do)

**Comment by alees24** [comment]
> estimate 4

**Comment by johngt** [comment]
Closing the issue based on discussion with @alees24 . Irrelevant for prod as mechanism is inadequate and https://github.com/lowRISC/opentitan/pull/19269 removes that register.

**Comment by johngt** [comment]
@msfschaffner - FYI
