### ISSUE TITLE
[rom] sec_mmio audit

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#23652]
Git Commit: e7fa132023eefdbb74b005a04a00f5bb5d0ce95e

Command: `bazel run //util/py/scripts:audit_sec_mmio_calls -- --log-level info`

Results: https://docs.google.com/document/d/1DIIL9tjWQzYhUZcvhhUsvdyjs7mpcvWphNNRDzTLd_Q/edit

**Comment by cfrantz** [comment]
Reviewed by @cfrantz and @timothytrippel.
