### ISSUE TITLE
Issue with Building (and Testing) Software: Verilator Test Read-only File System Error

### ISSUE THREAD

**Issue by J-Williams668** [lowRISC/opentitan#23696]
### Description

I am trying to run the Verilator test (./bazelisk.sh build //hw:verilator) but keep getting a Read-only file system error from the /home/dev/.cache/fusesoc directory. I have done the setup as described in the Getting Started section using both an Ubuntu 20.04 VM and the Docker image and have encountered the same error using both methods.  I have also tried setting my .cache directory permissions to 777 and still encounter the error.

Has anyone else also encountered this error, and if so, do you have a solution?

![image](https://github.com/lowRISC/opentitan/assets/151094335/04348535-0138-4485-922a-a7a0f2438bd7)

**Comment by a-will** [comment]
bazel is not allowed to write outside its directory tree, and fusesoc will attempt to create that folder if it doesn't exist.

I believe you can work around it by simply creating that directory manually. `mkdir ~/.cache/fusesoc`

Likely we need to specify an alternative cache_root in a config file, then hand it over to fusesoc in our build process.
