### ISSUE TITLE
[rom] `Earlgrey-PROD.ROM` Release

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#23695]
### Description

Rom release checklist to be approved by the technical committee: 

https://docs.google.com/document/d/1kk4laD2o_c-0tKc1_4CgTMHvSrgmOa9hafAWQwM7UrA/edit

The contents of the document will be published in the GitHub release for the ROM.

**Comment by cfrantz** [comment]
Commit 49de03cd42e5878ad983df040544283552302b68 is Earlgrey-PROD-M5-ROM-RC0.

The ROM is built with:
```
bazel build --stamp //sw/device/silicon_creator/rom:mask_rom
```

**Comment by timothytrippel** [comment]
The ROM has been re-released (built with the same command above). Commit  6a84251492142c26314bd9ec7e9f16fba348a059 is tagged `Earlgrey-PROD-M5-ROM-RC1`.

Release checklist is here: https://docs.google.com/document/d/1BOWVjcUiuauDYC0jUKk0Pt0kdwGEmoib-F5khbkcdrk/edit

**Comment by timothytrippel** [comment]
The ROM has been re-released (built with the same command above). Commit is tagged [Earlgrey-PROD-M5-ROM-RC2](https://github.com/lowRISC/opentitan/releases/tag/Earlgrey-PROD-M5-ROM-RC2).

Release checklist is here:
https://docs.google.com/document/d/1pgEC0LDkFVnJ4298UBg9NViz0tN1-KXjl880liUCdeE/edit?usp=sharing
