### ISSUE TITLE
[hmac,dv] Reduce reseeding of long HMAC SHA-2/HMAC test vectors tests

### ISSUE THREAD

**Issue by gdessouky** [lowRISC/opentitan#23844]
These tests are very long and with very little randomization (or probably none) involved: fixed-input and output compared with expected output.

@martin-velay suggests to reduce the `reseed` parameter to 10 for the tests with the NIST vectors?

Do we need to run them from the `hmac_stress_all_vseq`? I think the added value is not that significant as tested in standalone and mixing it don't bring so much?

If you have a strong opinion to keep it, maybe we can reduce their weight? (to do so, I would suggest the use of a SV weighted `randcase`)?

For earlier discussion thread:
_Originally posted by @martin-velay in https://github.com/lowRISC/opentitan/pull/23771#discussion_r1656638433_

cc @vogelpi

**Comment by martin-velay** [comment]
Can be closed as https://github.com/lowRISC/opentitan/pull/23848 has been merged
