### ISSUE TITLE
[rom] Audit accesses to CSRs with CDCs

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#23845]
When SW accesses HW IP block CSRs that include a clock domain crossing (CDC), the timing and effect of the access depend on the activity (i.e., gating, frequency, and phase) of both clocks.

One potential problem has been described in https://github.com/lowRISC/opentitan/issues/23303#issuecomment-2184532328: SW writes two fields of `adc_ctrl`'s `FILTER_STATUS` CSR while its non-AON clock is disabled,. The writes happen only after the clock is enabled again. Then, as the AON clock is much slower than the I/O-div4 clock, the second write becomes effective multiple microseconds after the first write. If SW reads the CSR in the meantime, it observes only the first value written, even though from the CPU's perspective both stores have happened.

To ensure that CDCs in CSRs don't cause problems in ROM code, this issue is about auditing ROM code for any accesses to CSRs with CDCs, which are listed in [this sheet](https://docs.google.com/spreadsheets/d/1NjgDx_ZnzRx5pUkO28IFfy_gApAeT7AwTxWzCcc27Os/edit), to check that the code takes clock gating and delays due to clock domain crossings into account.

**Comment by andreaskurth** [comment]
@timothytrippel May I assign this to you to audit the ROM code or delegate to another ROM dev? PLMK if you need more information from the HW / architecture side.

**Comment by cfrantz** [comment]
Of the register names in the linked sheet, I believe only 4 are ever accessed by the ROM:
```
WDOG_CTRL
WDOG_BARK_THOLD
WDOG_BITE_THOLD
WDOG_COUNT
```

As far as I can tell:
- `WDOG_BARK_THOLD` and `WDOG_COUNT` are only written by the ROM, never read.
- `WDOG_CTRL` and `WDOG_BITE_THOLD` are written with `sec_mmio_write32`, meaning that at the end of ROM execution, they are read back and checked against the written value.

These readbacks only happen in a Power-On Reset case - we do not initialize the watchdog for sleep wakeup cases, and therefore, the sec_mmio_writes don't happen and don't add the watchdog registers to the list of expectations to be checked later.

In the power-on reset case, immediately after initializing the watchdog, we initialize `sensor_ctrl` and wait for 5 cycles of setting the CDC_SYNC register and waiting for it to clear.

**Comment by cfrantz** [comment]
I performed an audit of all AON register accesses not too long ago.  It wasn't focused on the problem discussed in this particular issue; you can see my conclusions here: #22614.

**Comment by timothytrippel** [comment]
Can we close this now?

**Comment by andreaskurth** [comment]
Thanks for the audit; no objection from my side to closing this issue now.
