### ISSUE TITLE
[manuf] Enhance test tokens CP provisioning by sending its hash

### ISSUE THREAD

**Issue by sasdf** [lowRISC/opentitan#23895]
### Description

Currently, the test unlock / exit tokens provisioned during CP phase are sent in cleartext to the device, and the device stores their hashes.

https://github.com/lowRISC/opentitan/blob/09b4736fce31af2e520b07fc4b1c5c66f5f17cf8/sw/device/silicon_creator/manuf/lib/individualize.c#L172-L177

 The flow can be improved by hashing the tokens on the host side, and only transferring their hashes to the device instead. With this approach, we can prevent passive eavesdropping on the token provisioning by the hash’s preimage resistance.

**Comment by timothytrippel** [comment]
Thanks @sasdf , this is a great idea.
