### ISSUE TITLE
[bazel] Bazel outquery gives multiple repeated results for outquery/outquery-one after building a target

### ISSUE THREAD

**Issue by AlexJones0** [lowRISC/opentitan#23990]
## Description
After building a target (via `./bazelisk.sh build`), `./bazeilsk.sh outquery` and `./bazelisk.sh outquery-one` will then return multiple duplicated results for the same target, which can cause unintended consequences in scripts that use this and rely on it only having a single output such as [`ci/scripts/target-location.sh`](https://github.com/lowRISC/opentitan/blob/39211701b5d2d8af1d52ab243b5b079bec36535f/ci/scripts/target-location.sh#L33C1-L37C36). This can cause some commands that we would expect to work to break.

## Steps to reproduce
Check for the correct initial state by running one of the following (these are identical implementations) at the repo top e.g.:
```bash
./bazelisk.sh outquery //sw/device/tests:uart_smoketest_fpga_cw340_rom_ext
./bazelisk.sh outquery-one //sw/device/tests:uart_smoketest_fpga_cw340_rom_ext
```
This should return one location, e.g. in my case
`bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/tests/uart_smoketest_fpga_cw340_rom_ext.bash`

Then, run (make sure vivado is available first) e.g.
```bash
./bazelisk.sh build //sw/device/tests:uart_smoketest_fpga_cw340_rom_ext
```
After this builds correctly, once again run one of the outquery commands. The result should now be two repeated locations:
`bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/tests/uart_smoketest_fpga_cw340_rom_ext.bash`
`bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/tests/uart_smoketest_fpga_cw340_rom_ext.bash`

## The problem
Everything points to this being an issue with bazel's `cquery` (or the way we use it) when supplying the `--output=starlark --starlark:expr="$qexpr"` options here: https://github.com/lowRISC/opentitan/blob/39211701b5d2d8af1d52ab243b5b079bec36535f/bazelisk.sh#L105
Replacing this with an equivalent `--output=files` will return the correct single result as we would expect. However, the starlark postprocessing is being used to do some more complex output processing for other forms of `outquery`, such as `outquery-all`, `outquery.*`, `outquery-*`etc.

A few possible thoughts:
  - Figure out why this behaviour is happening with `--output=starlark` and not `--output=files`?
  - A simple solution that would work with all existing functionality would be to append ` | sort | uniq` to the end of the `cquery`. This should work just fine as far as I can tell but I'd need to check, and it could perhaps prevent the ability to intentionally duplicate files via starlark postprocessing (though I don't think the `starlark:expr` is ever exposed to user parameters here). 
  - Another way would be to replace with `--output=files` and replace the starlark post-processing with some other functionality
  - There might also be a way to stop bazel's `cquery` from finding its own built files to stop this behaviour happening?

**Comment by pamaury** [comment]
The reason why there are two outputs is that the target `//sw/device/tests:uart_smoketest_fpga_cw340_rom_ext` is built in multiple configurations. You can check this by running:
```bash
/bazelisk.sh cquery --noimplicit_deps  //sw/device/tests:uart_smoketest_fpga_cw340_rom_ext
```
which prints:
```
//sw/device/tests:uart_smoketest_fpga_cw340_rom_ext (04fa05c)
//sw/device/tests:uart_smoketest_fpga_cw340_rom_ext (db109bb)
```
and you can get more information about the configurations as well:
```bash
./bazelisk config 04fa05c
./bazelisk config db109bb
```
The reason why there are two configurations is a bit weird. This is because one corresponds to the default test configuration and one to the test configuration specified in `.bazelrc` where we override the timeout values:
```
test --test_timeout=60,300,1500,7200
```
You can check that as follows:
```console
$ diff <(./bazelisk.sh config 04fa05c) <(./bazelisk.sh config db109bb)
< BuildConfigurationValue 04fa05c185fa20afe724c387144da7c906891b9bd807242562ca43689a3ed20c:
< Skyframe Key: BuildConfigurationKey[04fa05c185fa20afe724c387144da7c906891b9bd807242562ca43689a3ed20c]
---
> BuildConfigurationValue db109bb24b6e8904eb21fe5dd7bb55a4601f3ec1cd018d82f8d0c3255e6989cf:
> Skyframe Key: BuildConfigurationKey[db109bb24b6e8904eb21fe5dd7bb55a4601f3ec1cd018d82f8d0c3255e6989cf]
105c105
<   test_timeout: {short=PT1M, moderate=PT5M, long=PT25M, eternal=PT2H}
---
>   test_timeout: {short=PT1M, moderate=PT5M, long=PT15M, eternal=PT1H}
```
I believe the reason why there are two configurations is that when you run:
```
./bazelisk.sh build //sw/device/tests:uart_smoketest_fpga_cw340_rom_ext
```
it uses the default configuration, whereas if you were to run it with
```
./bazelisk.sh test //sw/device/tests:uart_smoketest_fpga_cw340_rom_ext
```
it would use the other (indeed the override is specifically for the `test` subcommand).

As to why `--output=files` does not have the issue, I believe this is because internally bazel will gather all files as a set and remove duplicates as a side effect. Therefore I think we really should be using `--output=files` but an interim fix would be to `sort | uniq`

**Comment by pamaury** [comment]
@AlexJones0 made me aware that the above commands will print different results if run in the repository after commit https://github.com/lowRISC/opentitan/commit/8779a3d096b284d50ee7e7c72dcce3aefe07b432
In this case, one needs to add an extra `--output=label` to see it:
```bash
/bazelisk.sh cquery --output=label --noimplicit_deps  //sw/device/tests:uart_smoketest_fpga_cw340_rom_ext
```
