### ISSUE TITLE
[hmac/dv/xcelium] test fails for hmac=1  

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#241]
when running the hmac test it fails for any seed that sets the hmac=1 parameter
if I manipulate the test to never set hmac=1 the test passes.
the error is a unix interrupt signal being raised

command used:
`make TEST_NAME=hmac_sanity SEED=1 SIMULATOR=xcelium`

xmsim: *F,SIGUSR: Unix Signal SIGSEGV raised from user application code.

![image](https://user-images.githubusercontent.com/53917183/65420542-b2f14280-de01-11e9-8b73-9af917005b28.png)

**Comment by rasmus-madsen** [comment]
@msfschaffner not sure if changes in the hmac code or system changes on our workstations. but the issue seem to have dissappeared.. which always scares me when that happens without any apparent reason!

**Comment by cindychip** [comment]
That is great news. I recently cleaned up some Xceilum warning. Could be
related to that? https://github.com/lowRISC/opentitan/pull/805

**Comment by weicaiyang** [comment]
since it's gone, maybe we can close this issue.
