### ISSUE TITLE
[csrng] INTR_STATE and SW_CMD_STS seems to be incorrect for Generate command with large glen

### ISSUE THREAD

**Issue by vsukhoml** [lowRISC/opentitan#24193]
### Description

I instantiate CSRNG with:
SW_CMD_STS=0x00000002
CMD_REQ=0x00800901 // Instantiate
INTR_STATE=0x00000003, ERR_CODE=0x00000000
SW_CMD_STS=0x00000006

Then I try to send Generate command with glen=0x800
SW_CMD_STS=00000006 // from previous Instantiate
CMD_REQ=00800603 // Generate command, glen = 0x800
After waiting 10000 iterations for INTR_STATE.CMD_REQ_DONE it is not set and I end up:
INTR_STATE=00000002, ERR_CODE=00000000
SW_CMD_STS=0x00000002 // Just CMD_RDY bit is set

But:
CSRNG CTRL 00000966 INTR_STATE 00000002, MAIN_SM_STATE 0000004e ERR_CODE 00000000
CSRNG GENBITS_VLD 00000003 GENBITS 56619b25

So I actually get randoms, Generate command was accepted and the rest works.

What is the appropriate method to check acceptance of such Generate command? I can add some heuristics to check wherever it is Generate command, so can just check in this case that there are no errors, but is there a better method?

@vogelpi

**Comment by moidx** [comment]
Hi @vogelpi, @h-filali, 

When we send large generate commands, is there a way to check in software that the command was accepted and being processed? 

Can you also clarify the STS behavior? Is ready only set after all the gen bits are read from the output? 

Thanks!

**Comment by vsukhoml** [comment]
Current entropy driver use this approach:
```
    if (cmd.id == kEntropyDrbgOpGenerate) {
      // The Generate command is complete only after all entropy bits have been
      // consumed. Thus poll the register that indicates if entropy bits are
      // available.
      do {
        reg = abs_mmio_read32(kBaseCsrng + CSRNG_GENBITS_VLD_REG_OFFSET);
      } while (!bitfield_bit32_read(reg, CSRNG_GENBITS_VLD_GENBITS_VLD_BIT));

```
Just waiting for `VLD_BIT`.  It makes sense to document it if this is the way to check state of command.

**Comment by h-filali** [comment]
For generate commands the `sw_cm_sts.cmd_ack` and `intr_state.cs_cmd_req_done` both go high when all of the entropy was absorbed to notify firmware that a new command can be received.
When a generate command is received and the command is not acked with a cmd_sts error, then you know that CSRNG is currently processing the command. To wait for entropy just check `genbits_vld` as you did in your snippet.

Thanks, for the feedback on the doc. I think I'll add some sentences to the sw_cmd_sts register, describing the differences for the generate command. I hope this helps!

**Comment by vsukhoml** [comment]
Would it be ok to check ERR_CODE==0 ? Documentation  https://opentitan.org/book/hw/ip/csrng/doc/registers.html#sw_cmd_sts--cmd_sts says that SW_CMD_STS . CMD_STS will only be set after completion of the command.

**Comment by h-filali** [comment]
Well yes but if the last command was ERR_CODE=0 then you wouldn't know whether the new command has arrived yet of the 0 is from the previous command. You'd have to see the acknowledgement go high to know that the new command was completed.

**Comment by vogelpi** [comment]
I am closing this issue again as the corresponding PR of Hakim (#24205) got merged.
