### ISSUE TITLE
[usbdev,dv] Run UNR towards coverage closure

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#24222]
On our road to close coverage for usbdev, we need to run UNR so we can exclude code that is unreachable.

**Comment by gdessouky** [comment]
Coverage before the UNR:

USBDEV
-------------------------------------------------------------------------------
Total Coverage Summary 

|  SCORE  |  LINE   |  COND   |  TOGGLE  |   FSM   |  BRANCH  |  ASSERT  |  GROUP  |
|:-------:|:-------:|:-------:|:--------:|:-------:|:--------:|:--------:|:-------:|
| 93.59 % | 97.96 % | 93.86 % | 97.44 %  | 81.25 % | 96.42 %  | 98.17 %  | 90.05 % |


Coverage after adding the UNR exclusions:

|  SCORE  |  LINE   |  COND   |  TOGGLE  |   FSM   |  BRANCH  |  ASSERT  |  GROUP  |
|:-------:|:-------:|:-------:|:--------:|:-------:|:--------:|:--------:|:-------:|
| 94.34 % | 98.11 % | 95.94 % | 97.44 %  | 82.54 % | 98.22 %  | 98.17 %  | 89.95 % |


I pushed the UNR exclusions file in PR https://github.com/lowRISC/opentitan/pull/24249.

**Comment by andreaskurth** [comment]
Closing as completed in #24249. Thanks @gdessouky! :+1:
