### ISSUE TITLE
[test-triage] KMAC shake test vectors regression

### ISSUE THREAD

**Issue by jwnrt** [lowRISC/opentitan#24225]
### Hierarchy of regression failure

Block level

### Failure Description

Failures line up with when an ECO was merged to KMAC.
I believe it was decided these failures were P2 since the tests just need updating.

Still generating the exact error message...

### Steps to Reproduce

- GitHub Revision: [e4c5daa580](https://github.com/lowrisc/opentitan/tree/e4c5daa580105299c3f45e0728376382265e0f41)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ```sh
  ./util/dvsim/dvsim.py hw/ip/kmac/dv/kmac_masked_sim_cfg.hjson \
    -i kmac_test_vectors_shake_128 \
    --build-seed 57478527486894479494471273459769404654835266620222125964939301612221385668501 \
    --fixed-seed 11025088414661302387259625850754552315971192149546710050530591896985944121480 \
    --waves fsdb
  ```

### Tests with similar or related failures

- [ ] kmac_test_vectors_shake_128
- [ ] kmac_test_vectors_shake_256
- [ ] Both masked and unmasked versions

**Comment by vogelpi** [comment]
Thanks for flagging this @jwnrt . I've now had a close look. The failures are not related to the ECOs but related to adding DV support for verifying the FIFO empty interrupt (https://github.com/lowRISC/opentitan/pull/23942). This change quite heavily impacts the simulation run time of some long running tests (most tests are not affected though) which lead to many timeouts. I've now filed a PR to increase the timeout for these tests here: #24233.

For reference:
- Regression results w/o #23942: https://reports.opentitan.org/hw/ip/kmac_masked/dv/2024.07.27_09.35.21/report.html
- Regression results w/ #23942: https://reports.opentitan.org/hw/ip/kmac_masked/dv/2024.07.28_10.43.38/report.html

**Comment by jwnrt** [comment]
Thank you for the fix @vogelpi

**Comment by jwnrt** [comment]
The `_256` variants of these tests are now passing regressions, but the `_128` versions are still failing. Do those timeouts need extending further?

**Comment by vogelpi** [comment]
I have been experimenting with a different approach. These tests don't contribute much to the overall coverage but are extremely expensive (as running for several) hours. I'll file a PR.
