### ISSUE TITLE
Wave dumping broken on xcelium

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#2422]
PR #2128 (mine) merged the VCS and xcelium code for dumping waves. This was probably a bad idea, because the two tools have different syntax. We need to split the code out again, either into a file per tool or a "base" file with an xcelium "override".

To get things working locally in the meantime, manually prefix the calls to `fsdb*` in waves.tcl with "`call `". The [original report](https://github.com/lowRISC/opentitan/pull/2128#discussion_r436205818) was inline in the PR that broke things.

**Comment by rswarbrick** [comment]
My personal preference is to have a file per tool (as the PR had originally). @sriyerg, what do you think?

**Comment by sriyerg** [comment]
My preference is to actually move the `$fsdvDump*` system calls to a SV code instead so that we can get rid of the tcl files (we will retain the per-tool tcl file for other tool-specific sim controls). The benefit of that is allowing run-time control of how to dump stuff via plusargs (which is tool agnostic). I am researching a bit on this - will get back with a prototype.

**Comment by rswarbrick** [comment]
Sounds sensible to me.

**Comment by rswarbrick** [comment]
Hi @sriyerg! I'm assigning this issue to you because you said you want to work on it. Given the duplicate issue from last night, it looks like someone (you or someone else) should probably fix it soonish. De-assign yourself if you don't want to do it, and I'll try to do something at the start of next week.

**Comment by svenka3** [comment]
@sriyerg 
>> My preference is to actually move the $fsdvDump* system calls to a SV code instead

With due respect, I differ - doing $fsdb (or any other PLI/VPI) calls inside SV code requires us to recompile/re-elab for various scopes to be dumped (Common practice for large designs/runs - as full dump can be expensive). 

I believe individual tool_name.tcl is perhaps the most time-tested approach (other Unit test frameworks do this already, VUNit is one example). 

Can you please re-consider this?

Thanks
Srini

**Comment by svenka3** [comment]
@sriyerg 
>> My preference is to actually move the $fsdvDump* system calls to a SV code instead

With due respect, I differ - doing $fsdb (or any other PLI/VPI) calls inside SV code requires us to recompile/re-elab for various scopes to be dumped (Common practice for large designs/runs - as full dump can be expensive). 

I believe individual tool_name.tcl is perhaps the most time-tested approach (other Unit test frameworks do this already, VUNit is one example). 

Can you please re-consider this?

Thanks
Srini

**Comment by sriyerg** [comment]
It appears to have been fixed. Closing.
