### ISSUE TITLE
[rom_ext] Do not honor boot service requests on deep sleep resume

### ISSUE THREAD

**Issue by jettr** [lowRISC/opentitan#24235]
### Description

ROM_EXT should ignore and clear and boot service request on deep sleep resume. Owner firmware will not expect to boot from a different slot after deep sleep; this could cause multiple issue if we don't prevent it.

**Comment by cfrantz** [comment]
Are there [other reasons](https://github.com/lowRISC/opentitan/blob/master/sw/device/silicon_creator/lib/drivers/rstmgr.h#L40-L72) besides `LowPowerExit` that you think should skip boot_svc request handling?

Ideally, we'd only handle messages in cases where we knew the user requested a reset specifically to invoke boot services.  However, I don't want to create a mechanism whereby an adversary could intentionally cause the ROM_EXT to skip processing.

**Comment by jettr** [comment]
We should probably avoid handling in the case of `kRstmgrReasonPowerOn` as well otherwise something is really wrong. Others seem okay to me

**Comment by cfrantz** [comment]
> We should probably avoid handling in the case of `kRstmgrReasonPowerOn` as well otherwise something is really wrong. Others seem okay to me

That should already be handled by the fact that a POR re-initializes RETRAM, and thus, there can be no valid boot_svc message there.
