### ISSUE TITLE
CI Not Processing Jobs

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#2426]
CI has stopped processing jobs again this morning.

Looking at https://dev.azure.com/lowrisc/_settings/agentpools?poolId=1&view=agents - all the custom build agents have been offline since yesterday.

[There are stalled jobs building `master`](https://github.com/lowRISC/opentitan/commits/master), which we need to get going again before too many PRs start landing for this week's work.

**Comment by imphil** [comment]
@asb has restarted the agent and it's now churning through the backlog.
