### ISSUE TITLE
[sw, dif_uart] S1 signoff UART sanity check

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#2427]
Me and @lenary last week have discussed whether DIF UART requires a sanity check. Initially @lenary was of an opinion that there should be a sanity check for DIF UART similar to other peripherals, however eventually we "half agreed" that DIF UART is sanity checked in terms of other tests. If UART doesn't work - none of the other checks will succeed, as CI is expecting `SUCCESS` output from the test.

I however had a change of heart today when going through the DIF checklist.

Although DIF UART is validated in terms of other tests, I think it is worth making it explicit and obvious that UART has failed:

- [x] Add FIFO RX/TX API to `dif_uart`.

- [x] Add LOOPBACK API to `dif_uart`.

- [x] Add appropriate tests to the `dif_uart_unittest`.

- [x] Use the newly added API to create a simple UART sanity check: send out a string and make sure it is completely received through the loopback functionality.

- [x] Make DV chip level tests use the sanity test.

- [x] Make CI use the sanity test.

POSSIBLE FURTHER NICE TO HAVE, BUT BEYOND THE SCOPE OF THIS ISSUE:

- Make CI run this unittest first (as there is no point running anything else if this fails).

- Make sure appropriate CI failure message is printed into log.

- Make sure none of the other sanity tests run in case of failure.

**Comment by silvestrst** [comment]
@lenary @gkelly - some thoughts before S1 signoff procedure.

**Comment by lenary** [comment]
I had expected we would discuss this in the S1 signoff meeting.

**Comment by silvestrst** [comment]
> I had expected we would discuss this in the S1 signoff meeting.

It's in preparation for this meeting, so that we have this issue at hand.

**Comment by lenary** [comment]
We discussed this in the UART S1 Signoff meeting. We do think a sanity test would be useful, one that directly uses the uart dif (so that dv's printing infrastructure is bypassed) to print a simple string.

We discussed potentially using the loopback enable to check send and receive, but decided this could wait until later.

We did discuss how many changes to do to the CI infrastructure, and the feeling is this should just be added as "another" test, and we can potentially do CI changes later (unless adding some of this is simple).

**Comment by silvestrst** [comment]
> We discussed potentially using the loopback enable to check send and receive, but decided this could wait until later.

I had a look now, and It seems that my simple idea of printing out `SUCCESS` in the `dif_uart_sanitytest.c` won't work. Sanity tests don't directly print `SUCCESS/FAIL` string anymore - they are returning `bool`, and `sw/devices/tests/main.c`  -> `test_status_set`.

I think the loopback is probably the way to go, hence the questions for @lenary and @gkelly : 
Shall I extend DIF_UART API to be able to turn on and off loopback functionality, and then do the sanity test based on that? During our meeting yesterday, you were under the impression that the loopback functionality should be a DV extension, so would you be opposed for it going into the main DIF API?

**Comment by lenary** [comment]
Yes add the extension for enabling loopback (probably only one of them), and document that that API is only for testing. We still don't know how DV extensions will work so we can delay putting this into a DV extension until we do.
