### ISSUE TITLE
[spi_host] Missing TXEMPTY interrupt on Z1 silicon

### ISSUE THREAD

**Issue by jesultra** [lowRISC/opentitan#24309]
### Description

When generating a SPI transaction consisting of a single outbound byte, and no incoming data.  My code first enables `EVENT_ENABLE::TXEMPTY`, before doing a single byte write to the `TXDATA` register.
What I am seeing is that no interrupt is ever raised, even though `STATUS::TXEMPTY` is set immediately after queuing the data.

I suspect that the hardware immediately transfers the first data byte out of the FIFO and into a shift register, and accidentally never counts the FIFO as non-empty.  Since the interrupt is edge triggered, that would explain why it does not latch.

I do not recall if the SPI host interrupts were changed into level-triggered for A1, if so, this problem would be gone already.  If not, we may want to keep this issue open.

This is not a serious issue, as a simple workaround is for me to check `STATUS::TXEMPTY` right after populating the FIFO, and manually triggering the interrupt, if it is set already.

**Comment by hcallahan-lowrisc** [comment]
Hi @jesultra, we did indeed migrate the 'spi_event' interrupt to a [status-type](https://opentitan.org/book/doc/contributing/hw/comportability/index.html#status-type-interrupt) for A1 in #21278 (Closing #21208 / going towards #15378).

**Comment by hcallahan-lowrisc** [comment]
Great, lmk if you have any more questions!
