### ISSUE TITLE
[AES, doc]  Missing De-initialisation section in https://opentitan.org/book/hw/ip/aes/doc/theory_of_operation.html

### ISSUE THREAD

**Issue by ntomj** [lowRISC/opentitan#24334]
### Description

The document needs an update.
In section https://opentitan.org/book/hw/ip/aes/doc/theory_of_operation.html#system-key-manager-interface, there is 

> (see [De-Initialization](https://opentitan.org/book/hw/ip/aes/doc/theory_of_operation.html#de-initialization) below).
But, there is no De-Initialization section.

**Comment by vogelpi** [comment]
Thanks for filing the issue @ntomj . At some point, we've split up the documentation a bit. The section you're looking for is here: https://opentitan.org/book/hw/ip/aes/doc/programmers_guide.html#de-initialization
