### ISSUE TITLE
[doc] Development stages: "Active" stage?

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2434]
https://docs.opentitan.org/doc/project/development_stages/#life-stages mentions an "Active" stage.

"The final life stage is Signed Off. At this point, a design is frozen and not expected to be updated. There are exceptions if post-signoff bugs are found, in which case the stage returns to **Active** and the version number is not updated."

However, there's no such stage mentioned in the document. Should "Active" be replaced with "Development" (L1)?

@sjgitty

**Comment by sjgitty** [comment]
Yep, let me fix that, thanks
