### ISSUE TITLE
[python] Add support for python 3.12

### ISSUE THREAD

**Issue by pamaury** [lowRISC/opentitan#24360]
### Description

Currently, our repository is not totally hermetic when it comes to python. This is because `rules_python` needs to use the system python to install packages using `pip` (and only after that can it use the pinned python version). But due to a combination of using an old version of `rules_python` and some old version python packages, we cannot support python 3.12. The main issue is that 3.12 removed `distutils` on which old packages depend for installation.

Python 3.12 is now becoming the minimum supported version in major distributions like Debian so we should make sure that it works.

The #24216 by @jwnrt enables 3.12 as a side effect of updating all dependencies.

**Comment by jwnrt** [comment]
Note that this is important as Ubuntu 24.04 uses Python 3.12 so we'll need to support it eventually.

**Comment by jwnrt** [comment]
The commits updating `rules_python` have been extracted to https://github.com/lowRISC/opentitan/pull/24361.
