### ISSUE TITLE
[top_earlgrey] Re-arrange peripherals by memory map

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2437]
Does anyone have any objections if i go through and re-arrange peripherals by memory address? I'm actually having a hard time figuring out where a new peripheral should go, since it's kind of arranged out of order.

@eunchan i'm guessing this is also on your radar since you are re-arranging the memory map.

**Comment by sjgitty** [comment]
sgtm

**Comment by eunchan** [comment]
https://docs.google.com/spreadsheets/d/1ptfdrG5RWiYHKtjYyDO1ubGYPPlN_4YQfzRKO1G1Mls/edit#gid=0

Link for suggested memory map.

**Comment by tjaychen** [comment]
this is done via #4163
