### ISSUE TITLE
[prim_packer] overflow when InW > OutW

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#2446]
Hi Eunchan, 

Thank you for pointing out that prim_packer supports arbitrary InW/OutW.

I found if `InW` > `OutW`, `mask_o` does not seem to output correct values.
In my case, the InW=5 and OutW=4. Input `mask_i` is always `'h1f`, `flush_i` is always 0, but output is `mask_o` is not `'hf`.

![image](https://user-images.githubusercontent.com/11466553/84196699-729c2800-aa55-11ea-8938-8a4313087c5e.png)

I think there is a storage overflow:
At first cycle, user input 5 bits data,
At second cycle, user input 5 bits data, and output 4 bits data.
After cycle two, total bits remained is 6 bits, but in middle, it needs 10 bit storage to hold the second input data. And the Width = (4+5) = 9 bits.

 I reopened the [pull request](https://github.com/lowRISC/opentitan/pull/2431) temporarily and you can use this as a formal testbench.
To run formal, you may use:
`cd hw/formal`
`./fpv prim_packer_fpv -gui`

You would be able to see four countercases:
ValidOPairedWidthReadyI_A
ValidOAssertedForInputGTEOutW_A
ExcessiveDataStored_A
ExcessiveMaskStored_A

Please correct me if I misunderstand your purpose.
Thanks,
Cindy

**Comment by tjaychen** [comment]
hmmm...Eunchan was prim_packer meant to downsize also? I guess I just
always assumed it was upsizing, but I could be wrong.

**Comment by cindychip** [comment]
I could be wrong:)  I think Eunchan mentioned here in this PR: https://github.com/lowRISC/opentitan/pull/2431
```
I think it is good to have a FPV test that can run arbitrary input & output widths. Clearly it may need 32bit input and 64 bit output later . I am expecting the prim_packer to be operable in any bit range from 1bit input.
```

**Comment by tjaychen** [comment]
ah okay sounds good. Yeah for some reason I just always assumed outw >
inw.. probably not the right assumption :)

**Comment by cindychip** [comment]
Haha same here, I did not know until Eunchan commented on my PR today!

  Cindy Chen

**Comment by cindychip** [comment]
Close this issue as PR #3065 is merged.
