### ISSUE TITLE
[Alert_mgr] enable alerts in AES module

### ISSUE THREAD

**Issue by Adam11072000** [lowRISC/opentitan#24517]
### Description

Hey,

how would i configure the alert manager to reset the system if it receives a fatal alert from AES module?

Adam

**Comment by rswarbrick** [comment]
I think you are asking about `alert_handler` here? If so, there is some documentation [here](https://opentitan.org/book/hw/top_earlgrey/ip_autogen/alert_handler/). Turning a fatal alert into a system reset is called "escalation", and explained in detail in the "Theory of Operation" document that is linked from there.

The question about AES suggests that you have a specific top-level in mind, and I assume you're asking about `top_earlgrey`. Maybe you could tweak the question to give us more information about what you're trying to achieve?

**Comment by Adam11072000** [comment]
yes, about alert_handler.
assume i raise a fatal alert from a peripheral like AES, i would expect the system to respond with something.
the response i would like to do is reset the system.

i tried raising it from the AES and i see that there is no response and the system is just stuck.

as such, i figured i need to write to alert_handler registers, but i did not see any example in the tests that is relevant to me.

![image](https://github.com/user-attachments/assets/2e3137e4-37c3-4291-b5cb-905d1940e8e5)

now this goes on for quite sometime (waited 10 minutes before closing down the simulation).

**Comment by rswarbrick** [comment]
I suggest you look further at your waves. The alert handler's escalation signal is in its `esc_tx_o` port. Once of these escalation paths is connected to `pwrmgr`, which can generate the reset you're looking for.

I don't personally know the details of how this works in `top_earlgrey`, but might be able to find out (or ask someone) if you could give more information about what exactly you're trying to do.

**Comment by Adam11072000** [comment]
okay, so basically i added another aes cipher core with a different logical design that works only on 128b keys and unmasked.
at the end of each operation, if the new cipher core can operate, then i check if the output of the two cores are the same, if yes then i do nothing, otherwise i raise an alert.
in a regular test without fault injections, the test passes, and we can see the same value being seen between the two cores
i configured opentitan to be unmasked and i successfully ran a test and passed.
![image](https://github.com/user-attachments/assets/a3114ce2-1e3e-427d-974a-86ac3e2341d3)
i added support for dynamic fault injections via a parameter in the new core, and i ran a test which injects a certain fault at a certain time to the 2nd core, and we see that we have successfully raised the fatal_alert to 1.
![image](https://github.com/user-attachments/assets/670f955f-dc98-4058-a1f0-9956acb13eac)


i see that AES is not connected to the alert_handler_esc_rx bus in the RTL, thus cannot generate a reset?

**Comment by rswarbrick** [comment]
I would expect:
- Your AES block generates a fatal alert, which appears in `alert_fatal_o` (as you see) and then is sent over the AES block's `alert_tx_o` by `u_prim_alert_sender[1]`.
- That signal will appear as a couple of bits in the `alert_tx` signal in `top_earlgrey` (locally, it would be the two that correspond to item 43, so probably bits `87:86`, I think. If you have a different block layout, it might be a different index)
- That will be passed to the alert handler at `u_alert_handler`.
- The alert handler should eventually generate an escalation, which will be transmitted as an `esc_tx_t` in one of the four lanes of `esc_tx_o`.
- That escalation gets routed to the lifecycle controller, the core or `pwrmgr` (depending on some configuration and a length of time / threshold, if I remember rightly).
- If the escalation appears at `pwrmgr`, we might expect that block to reset the chip.

**Comment by Adam11072000** [comment]
Well, i saw the part regarding the bits 42/43, depending on which alert was raised from AES, but the simulation ran for a lot of time and no escalation happened.
Maybe there's a timeout configurable via software that when that timeout ends, an escalation happens?

**Comment by Adam11072000** [comment]
it worked.
i configured it using software :D.
static dif_alert_handler_t alert_handler;
static dif_aes_t aes;

static const dif_alert_handler_escalation_phase_t kEscProfiles[] = {
    // TODO:
    // this first/second duration must be long enough to
    // accommodate a jtag transaction
    // how can this be done in a non-hardcoded way?
    {.phase = kDifAlertHandlerClassStatePhase0,
     .signal = 0,
     .duration_cycles = 10000},
    {.phase = kDifAlertHandlerClassStatePhase1,
     .signal = 1,
     .duration_cycles = 10000},
    {.phase = kDifAlertHandlerClassStatePhase2,
     .signal = 3,
     .duration_cycles = 10000}};

static const dif_alert_handler_class_config_t kConfigProfiles[] = {{
    .auto_lock_accumulation_counter = kDifToggleDisabled,
    .accumulator_threshold = 0,
    .irq_deadline_cycles = 0,
    .escalation_phases = kEscProfiles,
    .escalation_phases_len = 3,
    .crashdump_escalation_phase = kDifAlertHandlerClassStatePhase1,
}};

then init peripherals via MMIO read.

then:
  // set the alert we care about to class A
  CHECK_DIF_OK(dif_alert_handler_configure_alert(
      &alert_handler, kTopEarlgreyAlertIdAesFatalFault,
      kDifAlertHandlerClassA, /*enabled=*/kDifToggleEnabled,
      /*locked=*/kDifToggleEnabled));

    // configurate class A
  CHECK_DIF_OK(dif_alert_handler_configure_class(
      &alert_handler, kDifAlertHandlerClassA, kConfigProfiles[0],
      /*enabled=*/kDifToggleEnabled,
      /*locked=*/kDifToggleEnabled));

![image](https://github.com/user-attachments/assets/fc9c4d85-3834-4556-9d29-88f7599d7a8e)

**Comment by rswarbrick** [comment]
Great! Glad to hear you got it working.
