### ISSUE TITLE
[prim_ram*] Support for generating multiple physical tiles

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#2451]
For ASIC implementations, it would be good if we had a parametric way to split up large logical RAMs into multiple physical RAM banks/tiles, mainly for two reasons:

1) the size of physical SRAM cuts that we can compile for ASIC has an upper limit,
2) for floorplanning reasons in physical design.

An instance of such a large memory is our main RAM. While in this case we could still compile one giant macro of that size, we found in our discussions with Nuvoton that breaking that RAM up into multiple tiles is preferable.

Technically, this could be achieved by manually instantiating multiple `prim_ram_*` with appropriate sizes in the design. However, this would also complicate memory loading via backdoor interfaces. 

Hence I wanted to ask how people feel about adding a parameter to `prim_ram_*` that can be used to control the tiling factor. E.g.:

```systemverilog
module prim_ram_* #(
  parameter  int Width           = 32, // bit
  parameter  int Depth           = 128,
  parameter  int DataBitsPerMask = 1,  // Number of data bits per bit of write mask
  parameter  int PhysicalTiles   = 1,  // Number of physical memory tiles (only relevant for ASICs)
  parameter      MemInitFile     = "", // VMEM file to initialize the memory with

  localparam int Aw              = $clog2(Depth)  // derived parameter
) (
...
```
Note that this parameter would only affect the ASIC primitives, since the FPGA tools can automatically infer block RAMs and perform the appropriate tiling. I.e., the `PhysicalTiles` parameter would not be used in the  `prim_generic_ram*` implementations.

**Comment by msfschaffner** [comment]
Also note that by doing it this way, ECC/Parity logic in the `*_adv` wrappers would be automatically shared among all tiles.

**Comment by tjaychen** [comment]
i actually filed a duplicate issue :) #2445 
let me go close that one.

**Comment by tjaychen** [comment]
so the width / depth, does that represent the overall size? Or individual tile size?  Are we basically going to take those, and if tile is > 1, re-calculate the per tile size?

**Comment by tjaychen** [comment]
o i guess only depth is impacted in this case.

**Comment by msfschaffner** [comment]
yeah sorry about that :). 

Yes that was the intent. I.e., you would specify the total size of the RAM that you want, and for ASIC prims the tiling parameter is used under the hood to split the RAM into multiple cuts.

**Comment by tjaychen** [comment]
sounds excellent to me.

**Comment by msfschaffner** [comment]
We could technically add a second tiling parameter for the RAM width, since sometimes in certain cases you cannot achieve a certain width/depth ratio with a single cut.

**Comment by tjaychen** [comment]
ah you mean like split entries across multiple rams, and also a word across
multiples rams?
That would certainly be good to add, but probably not something needed for
this project....yet...

**Comment by msfschaffner** [comment]
Yeah this would only be to make the prim wrappers a bit more generic (for now).

**Comment by sriyerg** [comment]
Sounds good to me, though it might need `hw/dv/sv/mem_bkdr_if` to be re-jigged perhaps, to fit this construct.

**Comment by GregAC** [comment]
So the tiling parameter would split it up into multiple banks of the same width and add some address decoding/muxing logic to set enables and route read data out from the right bank?

Sounds like a reasonable approach to me, though I do wonder if an option to expose the banking structure might be useful for the icache, it's possible we could have more efficient logic (as the icache is already doing some logical banking for the ways so folding it all together could give better results). @tomroberts-lowrisc ?

**Comment by eunchan** [comment]
If ECC is used in multi-bank SRAM macros, I think it should be two separate instance in current SRAM wrapper design. ECC, as I learned, shall be per bank, for instance, if we want to make 4x 32bit SRAMs for 128 wide bit, then ECC should be per SRAM so eventually the macro shall be 4x 39bit SRAMs. As OT's ECC applies prior to prim_ram_*p module, it is not doable unless the wrapper instantiates ram_*p_adv multiple times (do we plan to to this?)

**Comment by msfschaffner** [comment]
@eunchan is right that under some circumstances (e.g. when ECC is employed), tiling should be explicit.

Hence, based on the comments above I think we can proceed as follows:

1) in cases where multiple banks are functionally needed (e.g. because ECC needs to be separate, or because higher bandwidth is required as e.g. in the I$), the RAM tiles / banks shall be explicitly instantiated in RTL.

2) in cases where multiple physical tiles are needed solely for the purpose of creating a certain logical RAM configuration, the tiling shall be performed "under the hood" in the technology-specific primitive wrapper, since this is not something that RTL needs to care about (this is also how inferred RAMs are assembled by the FPGA tool). 

Note that this does not affect our current RAM loading mechanisms for DV/Verilator simulations, since those use the "generic" memory wrappers. We need to discuss how to deal with RAM loading once we add support for siomulating the actual "ASIC" view instead of the "generic" view - but this is a separate discussion.
