### ISSUE TITLE
[fusesoc] prim_generic_flash dependency ram1p is not getting generated

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#2455]
`lowrisc:prim_generic:flash` adds dependency on `lowrisc:prim:ram_1p`, however the generator for creating the generic version of ram1p does not kick in, causing compile error.

**Comment by sriyerg** [comment]
PR #2452 is a temporary workaround.

**Comment by imphil** [comment]
Yes, that's a known limitation. I did file https://github.com/olofk/fusesoc/issues/404 to keep track of it on the FuseSoC side. Your workaround in #2452 is the currently recommended way to fix that.
