### ISSUE TITLE
[CI] Default runner is backlogged

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2467]
The default runner isn't accepting new jobs since ~8h.

https://dev.azure.com/lowrisc/opentitan/_settings/agentqueues?queueId=1&view=jobs

@asb

**Comment by asb** [comment]
Fixed. Failure remains the same - no errors in logs, agent is "Listening for Jobs". Restarting fixes it.

**Comment by imphil** [comment]
Looks on the surface like the same issue I've seen on the private runners.
