### ISSUE TITLE
[OTBN] Make an instruction set simulator for the v0.1 spec available

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2471]
We'd like to have an instruction set simulator for OTBN. 

The goal of this issue is to provide a starting point for such a simulator: the necessary framework, and the implementation of at least some of the v0.1 OTBN instructions.

**Comment by imphil** [comment]
@wallento and @felixmiller have started work on that.

**Comment by wallento** [comment]
The Python RISC-V Model is a proposal for this: https://github.com/wallento/riscv-python-model
The ISA is very easily overloaded by defining instruction types (https://github.com/wallento/riscv-python-model/blob/master/riscvmodel/insn.py#L123) and then the instructions using this type along with their modelling (https://github.com/wallento/riscv-python-model/blob/master/riscvmodel/isa.py#L29). We can simply overload both the ISA classes and the model, I don't expect any blockers.

**Comment by imphil** [comment]
I think I missed that we don't need any assembler or model extensions as a starting point, we can simply start with a bit of normal RV32 assembly in standard encoding.

So I think it would be a helpful starting point to just hook up the unmodified simulator first, we can then gradually extend it with the BN instructions.

**Comment by wallento** [comment]
Adding a trivial TODO item that does not significantly impact the effort:

- [ ] Write trace to file (needs extra argument and if given writes trace there)
