### ISSUE TITLE
[OTBN] Produce a minimal "assembler"

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2472]
Produce a minimal "assembler" for OTBN instructions. This does not need to be integrated into any toolchain, a minimal script should do the trick to complete this task.

Dependencies:
- [x] Define initial OTBN instruction encoding #2391 

> estimate 8

**Comment by wallento** [comment]
It is a side product of the Python RISC-V model I am building: https://github.com/wallento/riscv-python-model
Assembler programs can be
- Written programmatically: https://github.com/wallento/riscv-python-model/blob/master/riscvmodel/program/tests.py#L9, or
- given in text and converted to binary code (trivial, but tbd)
I am doing some crafting along with extending the model for OTBN to do it in a generic way.
Please assign to me

**Comment by wallento** [comment]
Generate the following outputs:
- Binary string
- Binary file
- C-struct

**Comment by rswarbrick** [comment]
I wouldn't worry too much about the C-struct bit: I suspect you can do that as a separate step from a binary with something like objcopy.

**Comment by imphil** [comment]
@wallento with #2919 merged, we can close this one?

**Comment by wallento** [comment]
ah, yes, the "fixes" were in the comments..
