### ISSUE TITLE
[dvsim] creates local scratch dir when SCRATCH_PATH is set

### ISSUE THREAD

**Issue by lmg260a** [lowRISC/opentitan#24728]
### Description

It is bad practice to have generated output appear inside a repo.
I set SCRATCH_PATH a location outside of opentitan's clone.
But when I ran

./util/dvsim/dvsim.py hw/ip/adc_ctrl/dv/adc_ctrl_sim_cfg.hjson -i adc_ctrl_smoke --tool questa

It still created opentitan/scratch/, with all the resulting files.

**Comment by rswarbrick** [comment]
I think you need to set `$SCRATCH_ROOT`.

The "SCRATCH_PATH" name *does* appear in the project (in `common_project_cfg.hjson`). An unfortunate name! But this is used as a TCL variable, not an environment variable, and points at a subdirectory of $SCRATCH_ROOT>
