### ISSUE TITLE
[syn aes] error: Value for list “object_list” must have 1 elements. (CMD-036)

### ISSUE THREAD

**Issue by lin-snail** [lowRISC/opentitan#24742]
**aes syn command:**
./util/dvsim/dvsim.py -t dc hw/ip/aes/syn/aes_gtech_syn_cfg.hjson --purge --local

**aes syn flow errors:  results.hjson**
{
  tool: dc
  top: aes
  messages:
  {
    flow_errors:
    [
      Error: Value for list 'object_list' must have 1 elements. (CMD-036)
      Error: Value for list 'object_list' must have 1 elements. (CMD-036)
      Error: Value for list 'object_list' must have 1 elements. (CMD-036)
      Error: Value for list 'object_list' must have 1 elements. (CMD-036)
      Error: Value for list 'object_list' must have 1 elements. (CMD-036)
    ]
.......

thanks!

**Comment by rswarbrick** [comment]
I don't actually have `dc` available here, so can't try it out myself. But I tried running the command you give and it looks like it tried to run `dc` with sensible looking arguments.

I think the "CMD-036" text is probably from the internals of `dc`? I think you'll need to do a bit of digging to figure out what has come unstuck.

**Comment by lin-snail** [comment]
"set_dont_touch-h .....*]" in gtech-constraints.sdc,  it  cause ‘object_list’ error. 
Deleted these lines, sythesis pass.
file link: hw/syn/tools/dc/gtech-constraints.sdc

so, issue closed.
