### ISSUE TITLE
[syn top_earlgrey] issue: *** [./hw/syn/tools/dvsim/syn.mk:28: do_build] Terminated

### ISSUE THREAD

**Issue by lin-snail** [lowRISC/opentitan#24747]
***syn top_earlgrey_gtech_syn_cfg.hjson command:***

./util/dvsim/dvsim.py -t dc hw/top_earlgrey/syn/top_earlgrey_gtech_syn_cfg.hjson --purge –local

***issue:***
make: *** [/home/riscv/project/opentitan/hw/syn/tools/dvsim/syn.mk:28: do_build] Terminated

***build.log:***

[build.zip](https://github.com/user-attachments/files/17301909/build.zip)

**Comment by rswarbrick** [comment]
I've just looked at the attached log. Thanks for including it. I think the failure is probably in the `compile` command, and any failure message will appear in `compile.rpt`. Can you add a comment with the last lines of that report? (They will presumably show what is failing)

**Comment by lin-snail** [comment]
Thanks for your help. Please check the attached compile.rpt file with the last lines.
[compile(last lines).rpt.txt](https://github.com/user-attachments/files/17300840/compile.last.lines.rpt.txt)

**Comment by lin-snail** [comment]
"syn.mk:28:do_build terminated" fixed by configuring termination_stage to "reports" from "compile" in common_gtech_syn_cfg.hjson.
link: hw/syn/tools/dvsim/common_gtech_syn_cfg.hjson.

Issue closed. Thanks for your help, have a good day.
