### ISSUE TITLE
[Question] Wonder if there's a way to create build_modes dynamically

### ISSUE THREAD

**Issue by desorya** [lowRISC/opentitan#24858]
Hi there,

I'm using DVSim to run the simulation on VCS and I have a silly question for building the hjson simulation flow with sequential build-options which receiving the parameter from the test cases.

In the design, I have three parameters named `PASS_RATE`, `FAIL_RATE` and `MAX_ITER`, each of them in the range of `[10, 100]`, stride of `10`, and my test case may have different value of those parameters. So these parameters can be regarded as both `build_opts` and `run_opts` together.
```
//  The estimated Makefile format may as below
sim:
    vcs -f flist.f +UVM_TESTNAME=$(TEST_NAME) $(PRATE) $(FRATE) $(MAX_ITER) (Other options)

case_1:
    @$(MAKE) sim TEST_NAME=case_1 PRATE="+define+PASS_RATE_10" FRATE="+define+FAIL_RATE_20" MAX_ITER="+define+MAX_ITER_30"
```

The problem here is, in general way, I need to create the `build_modes` based on the combinations of the possible values of three parameters, which means that there may be up to `1000` build modes and it is horrible to build them manually.

```
// The hjson flow format may as below
build_modes:[
            {
                name: mode_1
                build_opts: [
                    "+define+PASS_RATE_10",          // from 10 to 100, stride of 10
                    "+define+FAIL_RATE_20",          // from 10 to 100, stride of 10
                    "+define+MAX_ITER_30"            // from 10 to 100, stride of 10
                ]
                is_sim_mode: 1
            }

           {
              // Up to 1000 build modes depends on the value of the parameters
           }
]

tests: [
        {
            name:           case_1
            uvm_test_seq:   case_1_seq
            uvm_test:       case_1_test
            build_mode:     "mode_1"
            run_opts:      [
                            "+PASS_RATE_10",
                            "+FAIL_RATE_20",
                            "+MAX_ITER_30"
                           ]
        }
]
```

I wonder if there's an alternative way to create the `build_mode` dynamically such as using the wildcard in tests to match?

Thank you for all the help!

**Comment by matutem** [comment]
Before considering options, I am curious why you pass things like PASS_RATE_10 as a +define to the simulator. I would think this is a property of the orchestrator, not of each simulator invocation.

**Comment by desorya** [comment]
> Before considering options, I am curious why you pass things like PASS_RATE_10 as a +define to the simulator. I would think this is a property of the orchestrator, not of each simulator invocation.

Thank you for the reply, the as shown `PASS_RATE` is the supposed write accuracy limitation and will affect the design behavior because for different `PASS_RATE` the design has different response method, and usually related to `MAX_ITER`.

**Comment by matutem** [comment]
It seems this is only a runtime mode, since a build failure means all bets are off. It seems you only need an iteration count and a pass percentage (the fail rate should be 100 - pass percentage). As for the run modes, you can create various run_modes with different settings of your parameters (say large_iter_80_pct_pass, etc.). And you can assign run modes to tests in the corresponding hjson file, and if needed you can override this in the dvsim invocation, so you could run a regression with your favorite iter_pass_rate mode. However, there is currently no way to assign per test run modes in the dvsim command.
