### ISSUE TITLE
[manuf] Propose to store DICE certificates in the flash_info with the "Cert Header"

### ISSUE THREAD

**Issue by tommychiu-github** [lowRISC/opentitan#24942]
### Test point name

NA

### Host side component

None

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [x] Hyperdebug + CW310

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Device-side (C) component developed

Currently, during ft_perso, the host write the RAW endorsed DICE certificate to flash_info pages.
When it needs to access them later on, the certificate length is calculated by parsing the header (1 or 2 bytes). This design works for X509 but not CWT-CBOR since there's no such information in some CBOR types (map, array specifically).
Ref: 
- https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/manuf/base/ft_personalize.c;l=627
- https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/manuf/base/ft_personalize.c;l=316

 I'm proposing to change the certificat storing format as below. The certificate is prepended by a 16 bits header followed by the ASCII  characters of the certificate name, followed by the certificate body.
This format is used already when transfering tbs & certificates from host vs. device.

The original X509 parsing logic can be reused for cross checking the result from the Cert Header.

```
   *  d15                                         d0
   * +-------------+--------------------------------+
   * | 4 bit       |            12 bits             |
   * +-------------+--------------------------------+
   * | name length |12 bits total cert payload size | <-- Cert Header
   * +-------------+--------------------------------+
   * |             cert name string                 |
   * +----------------------------------------------+
   * |                   cert                       |
   * +----------------------------------------------+
```

## Update
Move to the new storing format based on the [conclusion](https://github.com/lowRISC/opentitan/pull/24951#issuecomment-2449088327).
```
   *  d15                                         d0
   * +-------------+--------------------------------+
   * | 4 bit type  |   12 bits total object size    | <-- Object Header
   * +-------------+--------------------------------+
   * | name length |12 bits total cert payload size | <-- Cert Header
   * +-------------+--------------------------------+
   * |             cert name string                 |
   * +----------------------------------------------+
   * |                   cert                       |
   * +----------------------------------------------+
```

**Comment by tommychiu-github** [comment]
> [@timothytrippel](https://github.com/timothytrippel) for viz

I have a patch for that already. Can file a PR soon.

**Comment by timothytrippel** [comment]
This sound reasonable to me. It looks like #24951 is the associated fix?

**Comment by tommychiu-github** [comment]
> This sound reasonable to me. It looks like [#24951](https://github.com/lowRISC/opentitan/pull/24951) is the associated fix?

Yes, that's it.

**Comment by tommychiu-github** [comment]
Update the new storing format based on the [conclusion](https://github.com/lowRISC/opentitan/pull/24951#issuecomment-2449088327).

```
   *  d15                                         d0
   * +-------------+--------------------------------+
   * | 4 bit type  |   12 bits total object size    | <-- Object Header
   * +-------------+--------------------------------+
   * | name length |12 bits total cert payload size | <-- Cert Header
   * +-------------+--------------------------------+
   * |             cert name string                 |
   * +----------------------------------------------+
   * |                   cert                       |
   * +----------------------------------------------+
```
