### ISSUE TITLE
[otbn] Revisit design of hardware loops

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2496]
Currently, the OTBN specification contains a LOOP and a LOOPI instruction, which are modeled to closely follow the other implementation.

While developing the specification we have identified some areas for improvements and potential clean-ups which we need to have a closer look at.

Options range from fully removing hardware loops, over simplifying their design to allow only (e.g.) one or two nested loops, to leaving them as they are currently defined. 

The discussion need to look at security as well as performance.

@imphil has done initial investigations on the performance side which indicate that fully removing hardware loop has a significant runtime performance cost. https://docs.google.com/presentation/d/14ZDASGkVJTxwJpCB5HDxNV7TG_heeCLbwlRTppczPRQ/edit#slide=id.g74be9215a0_0_1109 contains a summary of that discussion, talk to @imphil for more data points.

> estimate 8

**Comment by wallento** [comment]
Maybe further clarification needed, in case I am not missing anything: `LOOP` will be executed once and iterations initialized with the gpr value. Changes to the gpr in the loop body will not be reflected in the loop iterations.
Correct? That could be an important difference to the suggested standard "soft" loop wrt. security (wild guess ;)

**Comment by wallento** [comment]
Another thing that comes to my mind about nested LOOP.
Consider the following code:
```asm
LOOPI 2 3
LOOPI 8 2
LOOPI 4 1
ADD x0,x0,x0
```
It is supposed to run the last instruction 64 times. Is OTBN supposed to execute each loop and check the condition for each loop statement or is this supposed to occur implicitly, i.e. count down instructions of the current loop and then start the next iteration at the first instruction of the body?
If that is the case: Hardware would require to pop the loop stack and check conditions *multiple times* at the end.
If it is not the case: It will be extra hardware complexity to check if `last_pc==pc-4` or `last_pc==pc+bodysize*4`.
Sorry if I am missing something.

**Comment by cdgori** [comment]
Is this something the dcrypto code does?  Or is this a hypothetical?
Seems like a compiler should be able to merge LOOPIs quite easily.

I'm not sure exactly how to manifest this but it seems like consecutive LOOPIs without other non-LOOPI instructions intervening could be considered some type of error, and then we just don't allow it.

Or is there a valid reason for this that I'm missing?  (I think it might get even worse for the CFI logic, thus my interest in simplifying it, if possible.)

**Comment by rswarbrick** [comment]
@cdgori: Stefan's not talking about consecutive LOOPIs, but nested ones. I don't think we'll have a C compiler, but the corresponding C code would be something like this:
```C
A
for (int i = 0; i < 100; ++i) {
    for (int j = 0; j < 100; ++j) {
        B;
    }
}
C
```

The point is that we run `B` 10,000 times, but there's no instruction between B and C, so (as currently specced) the processor would have to pop 2 entries off the loop stack at once.

I think we could disallow this and check at decode time that a new loop instruction has an instruction count strictly less than any innermost existing loop. We'll probably want a check a bit like this anyway (because an inner loop shouldn't have an instruction count greater than an outer one!), so I think the only cost is to the programmer, who will need to insert a nop at the end of the inner loop. Probably not an issue.

**Comment by cdgori** [comment]
@rswarbrick yes, understood.  In the instruction stream the LOOPIs would be consecutive though, right?  (though the net effect is to nest as in your example code).

I'm saying that LOOPI back to back with another LOOPI shouldn't be done (though I'm unclear if LOOPI has an index variable that can be used by instruction "B" in your example e.g. to do some [i][j] indexing, at which point maybe my statement is no longer valid).

Assuming there's not a usable index variable, I think your decode-time solution is probably reasonable.

**Comment by rswarbrick** [comment]
I don't think that's quite right. For example:
```
loopi 10, 5
add x1, x1, x2
add x1, x1, x2
add x1, x1, x2
loopi 20, 1
sub x1, x1, x3
```
If I got it right, this would look something like this in Pseudo-C:
```C
for (int i = 0; i < 10; ++i) {
    x1 += x2;
    x1 += x2;
    x1 += x2;
    for (int j = 0; j < 20; ++j)
        x1 -= x3;
}
```
The `loopi` instructions are separated in the instruction stream, but their "end addresses" are the same.

**Comment by felixmiller** [comment]
@wallento: Re your initial question regarding the `LOOP` instruction: yes, once initialized, changes to the GPR containing the loop count from within the loop body are reflected in the current loop (for all iterations). Or in other words, you can't "break" and you could use the same GPR for other things from within the loop.

Re nested loops with loop end at the same address: Here the main question for me is whether the count check at the end of the loop is meant to be zero overhead. My initial assumption was that this check would always consume a cycle. Much like a implicit `BNE` instruction with a branch back to the start of the loop body. If we target zero overhead here indeed we would have to enable as many comparisons in HW as the max. depth of the loop stack, I guess this is unrealistic. The other option is to explictely disallow this and require a `NOP` to be inserted between the endings if the implemented algorithm contains such nested loops with identical endings.

side node: I don't really know how this is handled in dcrypto. The code I've seen does not contain such loops, nor do we know anything about the HW implementation whether the checks are zero overhead, so it could be both ways.

**Comment by rswarbrick** [comment]
I think we've decided to keep the current design for now. Let's close this and raise a new issue if we decide to do something new.
