### ISSUE TITLE
Dependency Management Scripts

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#2497]
Building OpenTitan has a lot of dependencies. These are all of the lowrisc-related places where these are specified or checked (I cannot speak to how other organisations have configured their CI setups)
- `apt-requirements.txt`
- `python-requirements.txt`
- `util/get-toolchain.py`
- `util/build-docs.py`
- `util/check_tool_requirements.py`
- `ci/install-package-dependencies.yml`
- some individual rules in `azure-pipelines.yml`
- duplicated rules in `jobs.yml@opentitan-private-ci`
- `site/docs/builder.Dockerfile`
- `util/container/Dockerfile`
- (Some lowrisc-internal provisioning scripts for the private CI builder).

I note that juggling all of these dependencies is not particularly easy. especially as:
- There are lots of different tools, and it's not clear which are necessary for which usecases.
- For CI we need to be able to automate installation and update of these tools (this is not always possible on developer machines)
- Some tool versions are specified in multiple places.

We should also note different developers need different sets of tools:
- Software Developers don't need all the DV or FPGA tools, necessarily.
- Digital Designers and DV don't always need toolchains (if they're not compiling software).

I'm filing this issue so we can keep track of all these places and start to work to unify them in some way.

**Comment by msfschaffner** [comment]
CC @moidx @cfrantz @mundaym @timothytrippel

**Comment by timothytrippel** [comment]
Bazel solve this.
