### ISSUE TITLE
[otbn] Specify hardening of hardware loop stack

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2498]
The hardware loop stack needs to be hardened.

Specify
- What kind of hardening programmers (users) can expect.
- How/if that is visible on the ISA level.

@cdgori wrote in https://github.com/lowRISC/opentitan/pull/2393#discussion_r438892442:

> Should we indicate that CFI/other integrity checks can/will be applied to the loop stack? (The only implementation detail that might be exposed here would be if we need to have some value-and-its-complement representation of the count, but we might formulate that internally as well.)

This discussion depends a bit on how we want hardware loops to ultimately look, see #2496.

**Comment by rswarbrick** [comment]
@GregAC: This is implemented, but do we document it anywhere? (I guess a more general question is what documentation we're generating for FI countermeasures, and where it should live). Let's leave this open until we've got an answer for the loop hardening, at least.

**Comment by johngt** [comment]
Have captured the documentation element of this task in https://github.com/lowRISC/ibex/issues/1710 
I believe that based on @rswarbrick comment that there is no further development effort needed for this task and will leave it is an item for the documentation improvement. Tagging @GregAC in case this is not the case and the issue needs re-opening.
