### ISSUE TITLE
[otbn] Provide programmer guidance on safely using hardware loops

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2499]
Hardware loops are dedicated control flow functionality, and we need to provide programmers with guidance how to safely use them.

The exact guidance will depend on how we ultimately choose to implement hardware loops, which is tracked in #2496.

@cdgori wrote in https://github.com/lowRISC/opentitan/pull/2393:
> Also, since we make recommendations about GPR allocations for code authors in this document, should we make a recommendation that authors use the LOOP construct for data manipulation sequences? (As opposed to the BEQ/BNE/JAL/JALR instructions?) I am assuming that LOOP is going to be the most FI-robust structure we have, but perhaps that is not a correct assumption on my part.

> estimate 2

**Comment by GregAC** [comment]
Guidance now available in docs, added in PR: https://github.com/lowRISC/opentitan/pull/4598

**Comment by cdgori** [comment]
The clarifications about how LOOP/LOOPI work are great, thank you.  

My original comment was more to steer/nudge code authors towards using LOOP/LOOPI (vs BNE/etc) for (potentially) increased fault resistance.  I don't think the doc does that at the moment, but I didn't expand it completely to check for certain.

(It also might be the case that LOOP/LOOPI ultimately are similar in terms of fault resistance to branch/jump depending on how we implement CFI, at which point this comment is moot.)
