### ISSUE TITLE
[Xbar] Xbar_main is too big

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#2501]
Based on the current area report of bronze, xbar_main occupies 45kGE, which is relatively big. As I see the area report in detail, still Socket 1:N , socket M:1 occupy quite big chunk of area and FIFO's are enabled.

```
u_xbar_main                         39121.4819
u_xbar_main/u_asf_22                 1718.5672
u_xbar_main/u_asf_24                 1720.8996
u_xbar_main/u_s1n_32                10055.7995
u_xbar_main/u_sm1_18                 2276.2852
u_xbar_main/u_sm1_23                 3451.1288
u_xbar_main/u_sm1_25                 3453.8728
u_xbar_main/u_sm1_26                 2497.5888
u_xbar_main/u_sm1_27                 2491.2776
u_xbar_main/u_sm1_28                 2637.3956
u_xbar_main/u_sm1_29                 2571.8140
u_xbar_main/u_sm1_30                 2515.0132
u_xbar_main/u_sm1_31                 1601.8100
```

CC: @tjaychen @sjgitty @msfschaffner

**Comment by eunchan** [comment]
Need to check if clock, pipelined configs are correct.

**Comment by sjgitty** [comment]
We should review socket fifo depths; there could easily be slop in there
that won't affect performance to remove.

**Comment by msfschaffner** [comment]
@tjaychen I think you made a fix for this that removed unnecessary FIFO slices back in Summer 2020?

**Comment by tjaychen** [comment]
yep that's right. let's close
