### ISSUE TITLE
CI broken on master with FPGA not meeting timing any more

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2508]
The Nexys Video design has been close to the edge timing wise for quite a while now, but it seems like we've finally pushed it over the edge in https://github.com/lowRISC/opentitan/pull/2240 (the change itself looks innocent and did pass on its branch).
 
https://dev.azure.com/lowrisc/opentitan/_build?definitionId=9&_a=summary&repositoryFilter=5&branchFilter=566

CI is failing now on master, which is non-pleasant. 

@tomroberts-lowrisc Did you prepare a change back in the days to lower the FPGA frequency when we talked about it in #2274?

We need to either disable the test and allow the design to fail timing, fix the design, or lower the frequency. Ideally today :smile:

**Comment by tomroberts-lowrisc** [comment]
No sorry - I didn't have a board to test it on so didn't start that

**Comment by tomroberts-lowrisc** [comment]
We could just disable the check for now to get things moving

**Comment by imphil** [comment]
I'll give removing the timing check a try.

**Comment by imphil** [comment]
The timing check is now removed, making CI "green" again (by cheating). We still need to figure out if we can fix the design, or need to lower the FPGA frequency. I have a feeling that lowering the FPGA frequency will come rather soon anyways, so we might want to go for that straight away.

**Comment by tjaychen** [comment]
thanks Phil!

**Comment by tjaychen** [comment]
On a separate note, Greg are having different discussions on just
increasing the latency on access to flash.
I believe that's where the worst case paths are, I could try doing that
also.
