### ISSUE TITLE
[OTBN] Choose a bus

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2518]
Should OTBN be connected to the main or peri crossbar? Latency doesn't matter for that device.

@eunchan

**Comment by tjaychen** [comment]
i feel like this should be the main xbar, since OTBN itself will most
likely be on the main system clock (the peri xbar will be on a slower
clock).
And I'm guessing it would be easier for the design to not have async
boundaries between OTBN configs and the internal logic.

**Comment by imphil** [comment]
Sounds good, thanks @tjaychen! (I thought it would be that way, but I wasn't sure that the exact motivation behind the partitioning was.)

**Comment by eunchan** [comment]
Agree with Tim.
