### ISSUE TITLE
[Issue with Getting Started] Cargo build script failing at examples

### ISSUE THREAD

**Issue by tomrsae** [lowRISC/opentitan#25202]
## Description
Hi, I am having an issue with the examples in [Getting Started - Verilator Setup](https://opentitan.org/book/doc/getting_started/setup_verilator.html).

I have successfully completed the prior steps, but when trying to run the example
`bazel test --test_output=streamed //sw/device/tests:uart_smoketest_sim_verilator`
or
`bazel test --test_tag_filters=verilator --test_output=streamed //sw/device/tests:uart_smoketest`
(From within `$REPO_TOP` of course)
I keep getting the following error:
```
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
DEBUG: /import/lab/users/saetre/repos/opentitan/rules/autogen.bzl:151:14: NOTE: stamping is disabled, the chip_info section will use a fixed version string
INFO: Analyzed target //sw/device/tests:uart_smoketest_sim_verilator (1 packages loaded, 2571 targets configured).
INFO: Found 1 test target...
ERROR: /home/saetre/external/crate_index__serde-1.0.189/BUILD.bazel:97:19: Running Cargo build script serde failed: (Exit 101): cargo_build_script_runner failed: error executing command (from target @crate_index__serde-1.0.189//:_bs) bazel-out/k8-opt-exec-2B5CBBC6-ST-e846b08c7501/bin/external/rules_rust/cargo/cargo_build_script_runner/cargo_build_script_runner ... (remaining 11 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
thread 'main' panicked at 'CARGO_MANIFEST_DIR was not set: NotPresent', external/rules_rust/cargo/cargo_build_script_runner/bin.rs:33:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
INFO: Elapsed time: 2.533s, Critical Path: 0.06s
INFO: 37 processes: 37 internal.
FAILED: Build did NOT complete successfully
//sw/device/tests:uart_smoketest_sim_verilator                  FAILED TO BUILD

Executed 0 out of 1 test: 1 fails to build.
```

[output_sandbox_debug.txt](https://github.com/user-attachments/files/17816895/output_sandbox_debug.txt) shows the error when adding `--sandbox_debug` as suggested by the error.

## Bazel setup
I tried this with both alternatives in [Getting Started - Building (and Testing) Software](https://opentitan.org/book/doc/getting_started/build_sw.html#troubleshooting), but with the same result in both cases.

### Similar issue from Bazel git
I found this issue: [Build script env is overridden by use_default_shell_env in Bazel 6 #2665](https://github.com/bazelbuild/rules_rust/issues/2665), which pretty much exactly matches my issue.

However, it is still an open issue and neither of the proposed workarounds are possible in this case (Bazel version < 7 and using packaged version).

*I am making the issue here because the dev's response advises downgrading. However, I am using the exact version of Bazel as suggested in the setup guide, so I was hoping to find help here.*

### CI status
I am currently on commit `77c14f72971e18aad0f61a8a626d5fa9633b9075` (which has running CI checks), but I also tried on `a1200af401065a1cc6140e33e1bb1d1eb61a2dd3` which passed all CI checks (and error remains).
Finally, I tried with `778143fa63cd0d96fea3c1e7ad93ae65364bce0a`, which is the most recent one as of writing time, but same error.

### Chip simulation build
I am able to build the chip simulation itself (i.e. running `bazel build //hw:verilator`).
This builds successfully.

### Local cargo installation
I have tried both with cargo installed and uninstalled (ideally should remain uninstalled).

### Running with `bazel build` instead
Running `bazel build --test_output=streamed //sw/device/tests:uart_smoketest_sim_verilator` yields the exact same error message as stated above.

**Comment by a-will** [comment]
Make sure you're using bazel 7.3.1 (as specified in the `.bazelversion` file). To check the version, you can use `bazel version`.

**Comment by tomrsae** [comment]
@a-will I am using the version specified in [Building (and Testing) Software](https://opentitan.org/book/doc/getting_started/build_sw.html#building-and-testing-software), which is 6.2.1?

But I also tried it with ./bazelisk.sh from project root, which I assume would be using the correct version either way?

But like @pamaury mentions, did you manage to fix it using `rules_rust`? The issue I linked mentions modifying something there, but I can't figure out how I would do that for the packaged version of Bazel.

**Comment by a-will** [comment]
The doc is wrong / out of date. The source of truth for the required bazel version is always the .bazelversion file:

https://github.com/lowRISC/opentitan/blob/77c14f72971e18aad0f61a8a626d5fa9633b9075/.bazelversion

In addition, bazelisk.sh doesn't seem to work as some of us expected if `bazel` points to a binary.

**Comment by tomrsae** [comment]
Solution was indeed to use the Bazel version found in `.bazelversion` in project root, thanks for pointing it out @a-will!

In the interest of feedback I would highly suggest just adding a quick note about that on the docs page, especially considering the file is hidden as well (. prefix)
