### ISSUE TITLE
[sival] `hash_kat` test in crypto testplan

### ISSUE THREAD

**Issue by jwnrt** [lowRISC/opentitan#25271]
### Description

The crypto testplan for sival points to the `//sw/device/tests/crypto/cryptotest:hash_kat` target which no longer exists.

This test seems to have been split into a separate test for each kind of hash. If this is the case, the testplan needs to be updated.

**Comment by nmoroze** [comment]
cc @milesdai, I think https://github.com/lowRISC/opentitan/pull/25256 takes care of the last instance, it just needs to be cherry-picked to earlgrey_1.0.0 now.

**Comment by milesdai** [comment]
#25333 performs the cherry-pick
