### ISSUE TITLE
[docs] Preview builds broken with "Error: too many open files"

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2531]
I'm currently unable to build documentation on my machine, it errors out with

```
./util/build_docs.py --preview

...

Built in 512 ms
Watching for changes in /home/philipp/src/opentitan/{.github,build,ci,doc,hw,resources,site,sw,test,test2,util}
Error: too many open files
Error building site
```

This is most likely due to hugo picking up too many temporary build files in my working directory. We do set ignores in `config.toml`, however, they look quite fishy: the items should be regex matches, but we do use glob-style matches at times. It's also not quite clear what the base directory for those matches is, and if the file watcher (which seems to prevent the preview from working) is using those. Hugo documentation is not overly useful, and there a quick googling did make me find a couple of issues and PRs, but no answer.

**Comment by cdgori** [comment]
Is it possible your default soft-limit is set low on your machine?  Try `ulimit -Sn` (soft limit) and/or `ulimit -Hn` to check - if it's only 1k it might actually need to be raised.  If it's 4k or higher, your suspicions are probably correct about the globbing issues.

**Comment by towoe** [comment]
I think adding more rules to the ignores will not help as Hugo will probably need to check for all files and will apply the ignore filter after that. But this might not be true since it complains about open files.

Could you try the following to check if that might help?
```diff
diff --git a/util/build_docs.py b/util/build_docs.py
index bb2038b9..64d34ee2 100755
--- a/util/build_docs.py
+++ b/util/build_docs.py
@@ -293,6 +293,8 @@ def invoke_hugo(preview, hugo_bin_path):
     ]
     if preview:
         args += ["server"]
+        args += ["--watch=false"]
     subprocess.run(args, check=True, cwd=str(SRCTREE_TOP))
```

The best would be to restrict '--contentDir' to apply only to a limited subset, but I did not see how that would be possible.

**Comment by imphil** [comment]
OK, I finally got to the bottom of this. Increasing ulimit was something I did before, but generally wasn't sufficient.

Turns out, (my configuration of) VS Code is rather excessively watching files, exceeding the limits. Closing VS Code solves the problem. I probably need to spend a bit more time excluding build output directories there.
