### ISSUE TITLE
`top_pkg` for multiple tops in the repo

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#2544]
A few modules refer `top_pkg` to creates logic. TL-UL is one thing, `flash_ctrl` is another.
The top_pkg has its own `.core` file to be added into dependency list in above packages.

Its VLNV is `"lowrisc:constants:top_pkg"`, which is independent of top name. So if multiple tops exist in the repo, it has two sets of top_pkg with same name. It means the top_pkg should be identical.

We need to have a way for an IP to get the top-dependent files in `hw/ip`.

Idea 1. Split out top directory and use multiple `--cores-root` while calling `fusesoc`. Then `lowrisc:constants:top_pkg` can refer correct core file.

Idea 2. Use `generator` in `fusesoc` to create top_pkg from target. It means every time we call `fusesoc`, the user needs to give the top information (same to the Idea 1 but different manner).

Idea 3. Make any top_pkg dependent modules to be placed under top directory and use generation script to make it unique.

**Comment by imphil** [comment]
You nicely summarized the options, and I don't know any further ones. One way or the other, the user must decide when running fusesoc which toplevel they want to build. 

The two `--cores-root` option is probably the easiest to implement, but makes the command line slightly longer. Since fusesoc invocations are already slightly long, that's probably not making things worse :-)

**Comment by imphil** [comment]
Let me know if there's a pressing need to get that work done.

**Comment by eunchan** [comment]
yeah. I think Option 1 is easiest one as we can do it right now 
`fusesoc --cores-root hw/ip --cores-root hw/top_earlgrey`

**Comment by msfschaffner** [comment]
I kind of like Option 1 since it is explicit and straightforward to implement. 

Generators are nice and flexible, but also add more complexity to the build flow - so they sort of feel like a "last resort" to me :)...

**Comment by tjaychen** [comment]
i think this is probably something @vogelpi is looking at now for his separate top level PR.

**Comment by vogelpi** [comment]
Oh yes, thanks @tjaychen for pinging me. In PR #4329 I've implemented idea Nr. 2 on your list: If the flag `--flag=fileset_topgen` is provided to FuseSoC, it will generate all top-specific files (packages, IPs, top level RTL on demand).

**Comment by vogelpi** [comment]
I am closing the issue as #4329 got merged. But feel free to re-open it if further discussion is needed.
