### ISSUE TITLE
[aes/dv] Failure of aes_tl_errors

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#2551]
@rasmus-madsen 

In [nightly regression](https://reports.opentitan.org/hw/ip/aes/dv/latest/results.html), we saw below errors from aes_tl_errors.
```
xmsim: *E,MEMALC: Memory not allocated for actual array.
xmsim: *E,MEMALC: Memory not allocated for actual array.
xmsim: *E,MEMALC: Memory not allocated for actual array.
xmsim: *E,MEMALC: Memory not allocated for actual array.
xmsim: *E,MEMALC: Memory not allocated for actual array.

```

in aes_tl_errors, it only drives illegal TL items and check some interrupt regs at the end.
But in aes scb, before end of sim, it sends an empty msg item to process, which involves some C function to allocate unexpected size memory (maybe 0 size).
```
        wait( finish_message )
        `uvm_info(`gfn, $sformatf("\n\t ----|Finish test received adding message item to mg_fifo")
         , UVM_HIGH)

        `downcast(msg_clone, message.clone());
        msg_fifo.put(msg_clone);
```

there are 2 potential solutions to fix it.
1. (preferred) make scb more robust, if no actual data is processed, don't call C function.
2. set en_scb=0 in hjson file for aes_tl_errors. With #2479 merged, there is a separate knob to control tl_error check.

Thanks

**Comment by vogelpi** [comment]
Thanks @weicaiyang for filing this issue. I also noted these failures but did not get around to investigate it further. I would also prefer Option 1 but I can't estimate the amount of work required for this. @rasmus-madsen , what do you think?

**Comment by rasmus-madsen** [comment]
@weicaiyang @vogelpi 
The tl_errors is a V2 test - the code is at V1.
there should be no expectance to see V2 tests passing until we claim to be at V2. and no need to report the failures.

@weicaiyang if you want you can take V2 out of the nightly regressions.- but that might give a false indication for people not looking into the details.

**Comment by weicaiyang** [comment]
> @weicaiyang @vogelpi
> The tl_errors is a V2 test - the code is at V1.
> there should be no expectance to see V2 tests passing until we claim to be at V2. and no need to report the failures.
> 
> @weicaiyang if you want you can take V2 out of the nightly regressions.- but that might give a false indication for people not looking into the details.

sorry for the late reply.
Yes, it's a V2 test. We can fix it later. I just happened to debug it as it's a common test, so provide some debug info here. 
It's OK to keep in nightly since we don't expect nightly is 100% passing now.

**Comment by sriyerg** [comment]
Agree - if a DUT has reached Vn milestone, only spend time debugging all test failures up to Vn and the tests that have been developed and are expected to pass at Vn+1. The `*_tl_errors` test fall into the latter bucket - so you can debug and fix it right away (or later if you prefer).

**Comment by vogelpi** [comment]
Thanks @weicaiyang and @sriyerg for your feedback. This sounds very reasonable. We currently also see some failures for the newly added stress test (also V2) which we will look into soon.

I suggest to leave this issue open for visibility.

**Comment by vogelpi** [comment]
There has been quite some work on the DV side of AES recently which is great guys! It seems that these tests are now passing. Shall we close this issue @weicaiyang and @rasmus-madsen ?

**Comment by rasmus-madsen** [comment]
@vogelpi  sure.. I will close this
