### ISSUE TITLE
[dv] xcelium with fsdb doesn't work

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#2553]
FYI
With recent update, we can't run Xcelium to dump fsdb waveform.

Here is working tcl command.
https://github.com/lowRISC/opentitan/blob/75ad5fea480cda8bb71f0052ca3cdc1ef4113cb0/hw/dv/tools/xcelium/xcelium_fsdb.tcl

Prefer to be able to dump fsdb. If no one fixes it, I will continue to work on this when I'm back

**Comment by cindychip** [comment]
Hi Weicai, I think this is a known issue: https://github.com/lowRISC/opentitan/issues/2422.
Seems like there is a solution, we just need to draft a PR for that.

**Comment by weicaiyang** [comment]
Thanks @cindychip let me close this one.
