### ISSUE TITLE
Cloning the OpenTitan repository by following is giving error

### ISSUE THREAD

**Issue by rbs6** [lowRISC/opentitan#25676]
### Description

Cloning the OpenTitan repository by following is giving error as in snippet.
git clone https://github.com/lowRISC/opentitan.git

![Image](https://github.com/user-attachments/assets/c74143f8-2ac1-4dc9-a732-92bd3462885a)
![Image](https://github.com/user-attachments/assets/f78d0cbe-428e-42eb-9321-9d3eaea17546)

**Comment by rswarbrick** [comment]
I'm not sure what could cause this, but GitHub was having some trouble yesterday so maybe that's to blame.

I'm closing this (because I don't think there's anything we can do about it!) but please re-open if there's anything else that comes up.

**Comment by rbs6** [comment]
Hello

the URL -  https://github.com/lowRISC/opentitan.git/info/refs is said to be
phased out.

[image: image.png]

Please suggest

**Comment by a-will** [comment]
You'll need to update your git client, says GitHub:

```
Please upgrade your git client.
GitHub.com no longer supports git over dumb-http: https://github.com/blog/809-git-dumb-http-transport-to-be-turned-off-in-90-days
```

For more help: https://docs.github.com/en/repositories/creating-and-managing-repositories/troubleshooting-cloning-errors
