### ISSUE TITLE
[OTBN] sub(b) and cmp(b) instructions not fully identical in spec

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#2570]
In the OTBN spec we write [here](https://github.com/lowRISC/opentitan/blob/master/hw/ip/otbn/doc/_index.md#bncmp) and [here](https://github.com/lowRISC/opentitan/blob/master/hw/ip/otbn/doc/_index.md#bncmpb) that the CMP and CMPB instructions were identical to the SUB and SUBB instructions, respectively.
However, in the current spec the SUB instructions allow immediate shift of the 2nd input register and the CMP instructions don't.
I guess from a logic complexity standpoint we should allow the immediate shifting of rs2 also for the cmp instructions, to let cmp and sub share the same logic.

**Comment by imphil** [comment]
Is the shift in CMP/CMPB ever used in existing software? 

The implementation doesn't look different with shift tied to 0, so that's not really a concern to me.

I'm wondering if we need to be careful adding more functionality to CMP/CMPB. The current description of these instructions is fully driven by the implementation on the hardware side, making it a rather odd-looking instruction for software developers. If we can avoid adding more functionality to it, we will make it easier for ourselves to potentially find a better compromise design.

**Comment by felixmiller** [comment]
The shift is currently not used in software and probably won't be needed in future.
Were I have currently an issue with is the statement that CMP behaved exactly like SUB with the only difference being that the result is not written to a register.
I agree that there is the problem with specifying functionality that is not used but adds complexity on the spec and test efforts. But on the other hand, isn't it also here the case that we could reuse at much as possible from the SUB instructions (in terms of test cases for example)? Can't we completely remove the detailed spec of CMP and CMPB and only refer to SUB and SUBB and only note for the CMP and CMPB that the result is not written?

**Comment by cdgori** [comment]
> Were I have currently an issue with is the statement that CMP behaved exactly like SUB with the only difference being that the result is not written to a register.

This is probably the key point for me too - even having it behave the same but with shift tied to zero would likely be enough to distinguish it.  The idea is that the underlying structure is identical (even if the shift-function is not used in CMP).

**Comment by imphil** [comment]
From a "programmer's perspective", I'm not really a fan of CMP(B) and I think adding more functionality to it will make it harder to improve that later, but I see the motivation coming from the implementation as well. So let's get this change in for now, and see if it becomes a problem down the road.

**Comment by imphil** [comment]
Fixed by https://github.com/lowRISC/opentitan/pull/2571
