### ISSUE TITLE
[OTBN] assembly format of JALR instruction

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#2599]
I wonder which one is the correct assembly format of the JALR instruction and which one should we use in our OTBN spec [here](https://github.com/lowRISC/opentitan/blob/de59699a6640469a3e25a54675009488991fea62/hw/ip/otbn/doc/_index.md#jalr).

I see the two formats:
1. `JALR <rd>, <offset>(<rs>)`
2. `JALR <rd>, <rs>, <offset>`

Currently we use # 2, but apparently this was changed [here](https://github.com/riscv/riscv-isa-manual/commit/4dc3fa254ccc54e6f090722810506602ea59dbce#diff-894011b3addc3658c0b810a1fdbfdfc9).

**Comment by asb** [comment]
Both formats are valid and supported by RISC-V assemblers. The argument for preferring 1) is that you're then addressing memory addresses consistently as `<offset>(reg)` across jalr, lw, sw, and so on.

**Comment by felixmiller** [comment]
Thanks @asb . @imphil should we change this in the otbn spec, since we are using format # 2 for lw and sw?

**Comment by felixmiller** [comment]
Closing this since we are now consistently using #1
