### ISSUE TITLE
[OTBN] Bring up UVM regression for toplevel

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2615]
Produce a basic UVM DV setup with CSR tests for OTBN's top-level interface.

Depends on #2468

**Comment by imphil** [comment]
Seems like the auto-generated CSR tests are enabled by default and should be working with #2580.

**Comment by rswarbrick** [comment]
In fact, we do even better: the auto-generated tests also check memory access. This turned up a couple of bugs, but they should now be fixed.
