### ISSUE TITLE
[OTBN] Propose pre-dv approach for module-level testing

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2616]
Hardware designers need a pre-DV setup to be able to test individual modules during the development of these blocks.

Goal: Discuss, propose and potentially prototype (if it helps to argue about it) a pre-DV approach for this purpose.

Disclaimer: This is about *pre-DV*, *not* the sign-off DV. The primary audience for this testing are RTL designers.

We have in the past discussed approaches like cocotb, Verilator/DPI, and others. This is the time if one of those options could be a good fit.

> estimate 4

**Comment by rswarbrick** [comment]
Done: presented a [plan document](https://docs.google.com/document/u/2/d/12GGPzWHJOEi8YSZqCp73ivfUwC8gg8OZH4Op7i0KdkA) in the silicon meeting and tried to notify anyone else who might have an opinion on this.
