### ISSUE TITLE
[otbn] Add timing accuracy to bus-functional model

### ISSUE THREAD

**Issue by wallento** [lowRISC/opentitan#2617]
As discussed here: https://github.com/lowRISC/opentitan/issues/2477
Timing is cycles===instructions, hence we can move forward with just returning the cycles.

- [x] Add backchannel for this information, most easy is obviously a file
- [x] Count down from this return until the done goes up

**Comment by wallento** [comment]
Ready for review in #2625

**Comment by imphil** [comment]
Did go into otbn-dev through 51ae3f3ac0b7a43af62ca751e70d4d487953bb9a
