### ISSUE TITLE
[otbn] create generic ECC lib

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#2619]
Currently we only have ECDSA for the p256. We have to modify this algorithm such that other curves are supported by making the domain parameters modifiable

Work in implementing P384 is tracked in https://github.com/lowRISC/opentitan/issues/2982

**Comment by rswarbrick** [comment]
@felixmiller, @jadephilipoom: This issue is kind of ancient, but I'm not sure of the current status. Have we done everything that we wanted to do? Do we plan to? :-)

**Comment by jadephilipoom** [comment]
I think @felixmiller has something in the works?

**Comment by felixmiller** [comment]
Yes, I am currently working on this

**Comment by msfschaffner** [comment]
> Yes, I am currently working on this

Is there an update on this one @felixmiller?

**Comment by msfschaffner** [comment]
What's the status on this one?

**Comment by felixmiller** [comment]
This is actually something I am still working on. I think though that we don't need to track it here, since it is on the list of algorithms.

**Comment by msfschaffner** [comment]
Sounds good, let me close this then.
