### ISSUE TITLE
[OTBN] Create minimal OTBN frontend in RTL

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2622]
Create minimal RTL frontend for OTBN: fetch and decode

> estimate 16
> remaining 2020-07-24 1

**Comment by imphil** [comment]
@GregAC I now finished a very rough version of the decoder mostly by taking code from Ibex. I realized that we'll need more discussion on the control signals for CSR access, for load/store, and more importantly for jumps/branches. Should we, in line with your PR #2950, focus on the arithmetic/logical instructions for now only?

I'll then strip out all other instructions and open a PR for the ALU-only version, and we can step by step discuss the next instruction groups and associated control signals.

**Comment by GregAC** [comment]
I think an ALU-only version would make sense, then we will have a minimal OTBN that can actually run real instructions inside a top-level simulator which is a good base to work from.

**Comment by imphil** [comment]
Sounds good! I've pushed the decoder to https://github.com/imphil/opentitan/pull/new/decoder-only-alu. Instead of doing a PR, it's probably most convenient for you if you simply take this commit and integrate it into your PR? Or otherwise get your PR merged, and I'll then do it on top of it.

**Comment by GregAC** [comment]
Sounds good to me, I'll merge your stuff into my PR.

**Comment by imphil** [comment]
Merged into otbn-dev as part of #2950. Will go to master in #2981.
