### ISSUE TITLE
 [OTBN] Create minimal OTBN backend in RTL

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2623]
Create OTBN core "backend" modules in a minimal form: execute (with ALU), register file and  write-back.

> estimate 12
> remaining 2020-07-24 1

**Comment by GregAC** [comment]
I have written an ALU and register file that when stitched together will allow us to execute all of the ALU ops. You can find this on my OT fork here: https://github.com/GregAC/opentitan/tree/otbn_backend_wip/hw/ip/otbn/rtl

I've done a scratch testbench that stitches the two together and runs a simple test on the available operations, which is working.

Next I need to implement memory access and probably a shifter (inclusion of shift instruction is still under discussion)

**Comment by GregAC** [comment]
ALU integrated into top-level is in review now: https://github.com/lowRISC/opentitan/pull/2950

When combined with a fake decoder and some suitable instructions loaded in IMem the top-level simulation can run all the ALU operations writing results to the register file.

**Comment by imphil** [comment]
Merged into otbn-dev as part of #2950. Will go to master in #2981.
