### ISSUE TITLE
[topgen] Reset manager to be more generic

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#2629]
Reset manager in topgen/merge.py assumes the reset manager instance name to be `rstmgr`.

In Bronze, it is temporary revised to `rstmgr_aon` to make the IP being inside AON power domain. It would be better to have topgen to refer generic reset controller rather than fixed signal.

**Comment by tjaychen** [comment]
ah yes i've been wondering this for awhile, where in your opinion is a good place to define what that connection should be called? (there are a few other places like this too).

Should we add a field in `top_earlgrey.hjson` to specify this? and default to `rstmgr` otherwise?

**Comment by eunchan** [comment]
> Should we add a field in `top_earlgrey.hjson` to specify this? and default to `rstmgr` otherwise?

Sounds good

**Comment by tjaychen** [comment]
this has been addressed! closing issue now.
