### ISSUE TITLE
[otbn] confirm wall-clock predictions with full crypto algorithms

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#2635]
Once the simulator fully supports the otbn instruction set, we need to confirm in the simulation that we need all wall-clock requirements for the different algorithms

**Comment by imphil** [comment]
Done for RSA, no accurate numbers for ECC yet. First ballpark results look promising against our internal requirements, however.

Now blocked by #4206 and #2982.

**Comment by felixmiller** [comment]
Closing this, since we are tracking this in #6449
