### ISSUE TITLE
[otbn] done interrupt signaling

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#2636]
In the [spec](https://github.com/lowRISC/opentitan/blob/916bca2fb6f66bff26467a284e3c751cc344ecd1/hw/ip/otbn/doc/_index.md#ecall) we define the ECALL instruction to fire the done interrupt.

This is an issue with existing code sequences since some subroutines are called from both within the bignum firmware and from the host CPU. (e.g. a modexp primitive)
In the existent architecture, the done interrupt was therefore triggered at an underrun of the call stack (encountering a `ret` instruction when there is nothing an the call stack).

In otbn we could either:
1. Change to the approach described above (use the call stack)
2. Add wrappers for all subroutines that might be called directly from the host

Thoughts?

**Comment by imphil** [comment]
Option 2 sounds much saner to me. I find it odd to rely on a programming model where we jump into arbitrary pieces of code and execute until we happen to return from the last function.

Creating `main()`-like wrappers for the designated entry points, which end with an ECALL, would be my preferred solution.

**Comment by felixmiller** [comment]
Agreed, we have to consider though, that we sacrifice one position of the call stack (need to make the call stack one pos deeper)

**Comment by imphil** [comment]
Given the size of bignum, an additional 32b register in the call stack isn't going to change its area significantly.

**Comment by felixmiller** [comment]
Let's move forward with option 2 then
