### ISSUE TITLE
[OTBN] Feed randomness to the RND CSR/WSR

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2638]
The CSRNG block provides ports for consumers of random numbers, such as OTBN (or AES). The exact interface isn't defined yet, as is the bandwidth of this interface.

Also add a local LFSR within OTBN if needed.

> estimate 16
> remaining 2021-02-22 12
> remaining 2021-03-08 8
> remaining 2021-03-22 4

**Comment by imphil** [comment]
Depends on https://github.com/lowRISC/opentitan/issues/2693

**Comment by GregAC** [comment]
EDN hookup is here: https://github.com/lowRISC/opentitan/pull/5286, discussions around how EDN bits are accessed via OTBN (including adding an LFSR) are ongoing.

**Comment by GregAC** [comment]
Related issues are #3522 and #4209

**Comment by GregAC** [comment]
RND implementation is here https://github.com/lowRISC/opentitan/pull/5470

**Comment by imphil** [comment]
Implemented in #5470
