### ISSUE TITLE
[sw] boot_rom mode for 'regular' DV tests

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#264]
For DV, we dont want all tests to have to go through the full flow (code download, hashing, etc). It would be good to have bulk of the tests backdoor load and run the SW test image directly and skip the boot rom process. We will have one test in DV that does the whole flow (read SW test image in SV sequence, pump data via SPI, have boot rom verify / auth etc). Filing this as an issue for more discussion. 

@tjaychen, @moidx

**Comment by alphan** [comment]
Closing this issue since we are using the _test_ boot_rom for most of the tests in DV (except for TBD tests specific to the production rom).
