### ISSUE TITLE
[OTBN] Idle signal feedback to clkmgr

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2646]
The clock manager needs an "idle" indication so that it can ensure the clock is not manipulated while operations are ongoing.  This is primarily to ensure software cannot inject clock glitches into a running design.

It would be preferable is such a signal were level.

**Comment by imphil** [comment]
The current design has such a signal provisioned (https://github.com/lowRISC/opentitan/blob/bbfb0e02a34fe7898970096d43c54d916f43886b/hw/ip/otbn/data/otbn.hjson#L39). It's rather underspecified at the moment, so maybe we can take this issue to flesh things out.

For a start: Does "idle" only mean the core itself is idle, i.e. the bus device register interface doesn't matter? I.e. the clock manager takes care not to shut down the clock in the middle of a bus device transaction?

**Comment by tjaychen** [comment]
yes that's right. In my mind this is more related to when software starts
otbn on some operation, it cannot shut off the clock until otbn is done.
So a level signal that drops on a "start" and asserts on your "done" should
be more than enough.

Let me know what you think.

**Comment by imphil** [comment]
Sounds good, that's what I've implemented so far in https://github.com/lowRISC/opentitan/pull/2641. I'll update the spec to make it slightly clearer what the `idle` signal is about.

**Comment by tjaychen** [comment]
thanks! feel free to take yourself off the assign and i'll make sure to
hook it up before closing.

**Comment by tjaychen** [comment]
since this signal is already added, this issue is resolved.
