### ISSUE TITLE
[aes] Idle signal feedback to clkmgr

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2647]
The clock manager needs an "idle" indication so that it can ensure the clock is not manipulated while operations are ongoing. This is primarily to ensure software cannot inject clock glitches into a running design.

It would be preferable is such a signal were level.

**Comment by vogelpi** [comment]
Sounds reasonable. There is already a bit in the status register indicating that. I will expose this on the top level and connect it. Is there already a corresponding port in the clock manager?

**Comment by tjaychen** [comment]
I think there is (need to double check).
But I should also double check if i intended to change how that idle is
generated.

**Comment by vogelpi** [comment]
Hi @tjaychen,
sorry for my late response. I now did a first PR for bronze to add the connection. I am not sure if interconnection is done correctly and would be happy if you could take a look.

**Comment by vogelpi** [comment]
I think we can close this issue. The signal is connected both in bronze and master. what do you think @tjaychen ?

**Comment by tjaychen** [comment]
yep! thanks!
