### ISSUE TITLE
[CSRNG] Additional User Input Features

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#2652]
In #2463, @moidx has requested two specific features that are currently not in the google doc.
1. User input for generate calls. This is specified as an optional feature in SP 800-90A. We need to evaluate whether the current interface proposal in Bronze can support this.
1. Fully deterministic instances made available from software.   Originally I envisioned that software would have access to a low-bandwidth TRNG, but the very opposite is also desirable.  As @moidx indicates in his review, prehaps the best option here is to allow multiple instances to keep TL-UL access even in normal operation.   Practically speaking this probably means we would need separate OTP fuses to independently disable access to each instance.

**Comment by mwbranstad** [comment]
There is support in CSRNG to do deterministic tests, such as recreating the NIST golden vectors. Does this support satisfy this issue, or is there more to consider?
@moidx can you confirm? Assigning to you for now. If more requirements are needed, define them and assign back.

**Comment by msfschaffner** [comment]
What is the status of this issue? Has the feature been added in the meantime? If so, please link the associated PR(s) and close the issue.

**Comment by mwbranstad** [comment]
Need confirmation from @moidx, but I believe all support for user input is in place.

**Comment by moidx** [comment]
I believe we can close this. @jadephilipoom please re-open if we need to discuss (1.).  Thanks

> 1. User input for generate calls. This is specified as an optional feature in SP 800-90A. We need to evaluate whether the current interface proposal in Bronze can support this.

This was not implemented, but we expect the cryptolib to use the seed additional data interface instead. @jadephilipoom to confirm this is ok. 

> 2. Fully deterministic instances made available from software.   Originally I envisioned that software would have access to a low-bandwidth TRNG, but the very opposite is also desirable.  As @moidx indicates in his review, prehaps the best option here is to allow multiple instances to keep TL-UL access even in normal operation.   Practically speaking this probably means we would need separate OTP fuses to independently disable access to each instance.

There is a CSRNG instance available to software. We are planning to use this in general operations.

**Comment by jadephilipoom** [comment]
> > 1. User input for generate calls. This is specified as an optional feature in SP 800-90A. We need to evaluate whether the current interface proposal in Bronze can support this.
> 
> This was not implemented, but we expect the cryptolib to use the seed additional data interface instead. @jadephilipoom to confirm this is ok.

Discussed offline -- it looks like the CSRNG does in fact support additional data (see https://docs.opentitan.org/hw/ip/csrng/doc/#command-description) and fully meets the needs of the cryptolib.

**Comment by msfschaffner** [comment]
Thanks for confirming @jadephilipoom!
