### ISSUE TITLE
[hw] ROM integrity checks

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#2656]
Based on secure boot, attestation and identity conversations, we need a mechanism to check the integrity of the ROM. One proposal from @sjgitty is to implement a light weight integrity check before reset, and a more cryptographically strong after reset.

This issue is to track the design and implementation of such feature.

@tjaychen, @gkelly, @cdgori

**Comment by tjaychen** [comment]
is there any reason to not do the strong check before reset? Are we worried that it could be buggy?

**Comment by sjgitty** [comment]
Just a question of area and boot time. Not worried about bugginess.

**Comment by moidx** [comment]
+ @eunchan

**Comment by mateenfaisal** [comment]
@moidx, I suggest to close this issue, as ROM integrity check doc is in review. You will have one less Github issue to look at :)

**Comment by rswarbrick** [comment]
@mateenfaisal: This issue tracks a task that is to spec out and implement a block. We haven't done that yet; we definitely shouldn't be closing the issue.

**Comment by rswarbrick** [comment]
Ah, looks like we built `rom_ctrl` in the meantime. That's now at "D2 minus hardening", so I think this can be closed.
