### ISSUE TITLE
[primgen] Parameters not populated

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2679]
It seems like if a prim module has the following parameter format
`parameter logic [Width-1:0] ResetValue`

That paramater does not get populated when it is instantiated. 

If instead I do
```
localparam int WidthSub = Width-1,
parameter logic [Width-1:0] ResetValue
```

Then parameter is correctly populated during instantiation.

I've not looked into why this is happening at all yet.. hopefully will get a chance later today / tomorrow.

**Comment by msfschaffner** [comment]
I am not 100% sure, but it looks like the corresponding regex expects an initial value assignment:
https://github.com/lowRISC/opentitan/blob/10013f4113d8ac494be743cef6c7dd3174e2a822/hw/ip/prim/util/primgen.py#L182
can you try with something like `parameter logic [Width-1:0] ResetValue = '0`?

**Comment by tjaychen** [comment]
yeah what you have there was exactly what I had before.

**Comment by imphil** [comment]
It's very likely a bug in the regex, I'll have a look tomorrow morning.
