### ISSUE TITLE
Pull OTBN instruction documentation into something more "machine readable"

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#2719]
Put the existing OTBN documentation into a YAML file that can be used as a database from which we can generate other stuff too (tags for the random instruction generator, for example).

**Comment by rswarbrick** [comment]
So far, I've done the tedious reformatting, moving the existing markdown code into YAML and extracting the structure. To do: a YAML -> Markdown script that we can use for putting this back into documentation. Work estimate left: A day or so.

**Comment by imphil** [comment]
I assume this work can also be used as a starting point for https://github.com/lowRISC/opentitan/issues/2618?
