### ISSUE TITLE
[rtl] Use CSR abstraction for FIFO windows wherever possible

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#2724]
An example of this is in the `flash_ctrl` where the `prog_fifo` and `rd_fifo` are single 32-bit windows to a fifo implementation underneath. 

https://github.com/lowRISC/opentitan/blob/00cad63f191454a95f97830a009de3a0381e84eb/hw/ip/flash_ctrl/data/flash_ctrl.hjson#L470

The UVM register abstraction automation uses the `window` keyword to create a memory, which makes scoreboard / checking logic development slightly tricky, since these are better suited as registers. I wanted to know if we can change these to WO and RO registers instead, similar to `WDATA` and `RDATA` in UART.

**Comment by eunchan** [comment]
I think @tjaychen can comment in detail but register interface doesn't
have back pressure mechanism. Reg interface would be safer but has
chance to lost the data.

**Comment by sriyerg** [comment]
Aah, I see. Do you think we could add a `backpressured` field to the register hjson dict? Or, alternately, split `window` into two types of abstractions - one is a CSR backing a fifo and the other is a pure memory instance such as ram / rom / flash.

**Comment by eunchan** [comment]
Having type inside window field as you mentioned looks good idea.

**Comment by tjaychen** [comment]
@sriyerg , for the `type` abstraction you're talking about, would that just be a note for DV? Because I can't quite tell based on the comment what would change in the design.  It sounds like in both cases it would still be a tlul going out, and we would rely on the design to do the right thing? (either FIFO or real memory)

Also, is there something about the `flash_ctrl` usage of fifo that is different from `hmac` that makes it harder to handle? Or both these modules have the same issue?

**Comment by sriyerg** [comment]
I should have been clear - nothing would change in the design. This is more of a DV modeling issue. with `window` `rd_fifo` and `prog_fifo` in DV gets models as a UVM memory. It felt like they were better modeled as registers. I just wanted to see if we can update the ralgen automation in a way where that the design is not affected in any way, but for DV it creates a UVM register model rather than a UVM memory model. Let me think about this a little more and get back.

**Comment by tjaychen** [comment]
thanks @sriyerg 
let me think about this some more also. I'll check in with the software team on the back-pressuring, because some members of the software team will be very against the idea of deadlocking.
