### ISSUE TITLE
[sw, DIFs] unresolved PR comments and follow-ups

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#2737]
I completely agree that DIFs don't have to be impeccable for the initial merge, and we can fix-up a lot of the comments as follow-ups. However, I think we should establish some procedures to capture the fact that some merged PRs have unresolved comments. This would allow to avoid wasting review effort (after several weeks, nobody remembers what review comments they have left, and would have to re-review from scratch), and will allow the developers to keep track of unresolved issues.

This could be done through creating an issue and assigning it to the author, possibly?

**Comment by silvestrst** [comment]
I have noticed that there are a lot of suggested follow-up changes on I2C, and hence this issue.

**Comment by gkelly** [comment]
Just for clarity, the RFC proposal here is "Any PR merged with open comments must generate issues for each of the comments assigned to the PR author"?

**Comment by silvestrst** [comment]
> Any PR merged with open comments must generate issues for each of the comments assigned to the PR author

I was thinking that if we have unresolved comments, but we would like to merge the PR under question and address the remaining comments in the follow-up, or as a part of larger change. We open an issue, assigning it to the author of the PR with remaining comments, post a link to the PR with a description.

This was more or less what I was thinking, so that we don't loose track of unresolved comments, and avoid wasting effort re-reviewing and retyping the comments.

Just a suggestion, was wondering what you guys think.

**Comment by gkelly** [comment]
Okay, so something like adding the language: "When approving a change a committer can request that the outstanding comments be transferred into a GitHub issues assigned to the original PR author. The timeline for resolving the issue should be agreed upon before the PR is submitted."? I chose "a committer can request" to differentiate drive-by reviews from non-project-members.

**Comment by silvestrst** [comment]
> I was thinking that it would probably go in Committers, does that seem reasonable?

Sounds good to me!

**Comment by sjgitty** [comment]
The Technical Committee has reviewed this RFC and has opted to "abstain with comments".

In this case, the TC considered the proposal as drafted too narrow to be elevated to TC review. This does not mean it is not worthy of pursuing, on the contrary. As written, it appears to lie under the purview of the Software Committee to agree upon, institute, and codify. In addition, the TC sees that there might be merit in extending this concept beyond the SW vertical. If upon execution of the codified plan, the software team finds it valuable and extendable, the TC requests that the proposal be resubmitted as a wider cross-cutting recommendation, at which time the Standard Committee should take up the matter.

I am removing the `RFC: Proposal` label and adding the `Hotlist: Software` label.
