### ISSUE TITLE
[otbn] need shift left instructions for GPRs

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#2738]
To support some loop calculations we need a shift left for GPRs. I would suggest to add SLLI and SLL. Actually adding SLLI would be sufficient but to keep it more general it makes probably sense to support both.

> estimate 2

**Comment by GregAC** [comment]
Shall we add right shift as well? Even if there's no immediately obvious need seems sensible to add a full set of shifting instruction if we're adding some. Comes at a minor extra area cost but shouldn't be a big issue.

**Comment by felixmiller** [comment]
yes, probably makes sense to include the full set then

**Comment by GregAC** [comment]
They're now documented in the ISA, just need to implement them...

**Comment by felixmiller** [comment]
Fixed via 7ea7f0d9e1e5551fd7ad2251155388423917860c
