### ISSUE TITLE
Question about rv_timer register layout

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#2740]
This came up in #1501. Currently, IRQ registers of rv_timer come after comparator registers, meaning that their addresses depend on the number of comparators, which is configurable. To support different configurations without requiring recompilation, #1501 uses a helper function but it could be eliminated if the irq registers were placed before the comparator registers. Just to be clear, this does not block #1501 but would be nice to have if it doesn't require a lot of changes from the hw side.

@mcy, @sriyerg, @lenary, @gkelly

**Comment by eunchan** [comment]
Yeah. I will revise rv_timer accordingly. (IRQ registers precedes the counter registers.

**Comment by msfschaffner** [comment]
Can this issue be updated or closed?

**Comment by alphan** [comment]
Hi @msfschaffner, replying to your email here: This issue is about writing a generic piece of software that can work with different numbers of comparators. Can we rearrange the register layout to get rid of the `irq_reg_for_hart()` function [here](https://github.com/lowRISC/opentitan/blob/3db58a50e3b8739cfde242bbf29079a4707c888d/sw/device/lib/dif/dif_rv_timer.c#L221)? Please take a look at the issue description and the comment of that function.

**Comment by timothytrippel** [comment]
> Hi @msfschaffner, replying to your email here: This issue is about writing a generic piece of software that can work with different numbers of comparators. Can we rearrange the register layout to get rid of the `irq_reg_for_hart()` function [here](https://github.com/lowRISC/opentitan/blob/3db58a50e3b8739cfde242bbf29079a4707c888d/sw/device/lib/dif/dif_rv_timer.c#L221)? Please take a look at the issue description and the comment of that function.

Rearranging the register layout won't get rid of the `irq_reg_for_hart()` function, will it? It will just remove the `extra_comparator_offset` from the computation right? B/c there could still be multiple harts, right?

Also note, the [autogenerated DIFs](https://github.com/lowRISC/opentitan/blob/3db58a50e3b8739cfde242bbf29079a4707c888d/sw/device/lib/dif/autogen/dif_rv_timer_autogen.c#L60) should NOT be impacted by this change since the base offset uses the autogenerated IRQ register macros.

**Comment by msfschaffner** [comment]
That sounds right, but in that case we can still remove and replace it by `reg_for_hart()` (a different function that is being wrapped by `irq_reg_for_hart()`), right?

**Comment by alphan** [comment]
Yes, @eunchan's change [here](https://github.com/lowRISC/opentitan/pull/13914/files#diff-26cec7db5f770f90023fc546347a1a38a122ad8a2d4e29ea227a53efddf310ab) is basically what I had in mind.
