### ISSUE TITLE
dif_rv_timer followups

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#2741]
- [ ] Add comments to `dif_rv_timer_result_t`.
- [ ] Bring `_irq_` functions into consistent names (pending on https://github.com/lowRISC/opentitan/issues/2366#issuecomment-637071965).
- [ ] Remove `_reset()` call in `_init()` (pending on #2366, too).

**Comment by lenary** [comment]
- [ ] `_Static_assert` on member sizes in `dif_rv_timer_config`
- [ ] Update name of `dif_rv_timer_arm` to `dif_rv_timer_set_threshold`
