### ISSUE TITLE
[OTBN] Reset requirements

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2748]
Following a comment from @moidx [here](https://github.com/lowRISC/opentitan/issues/2696#issuecomment-655714103), I think it's worth discussing a bit the finer grain reset control for OTBN.

The current reset definition does not have an OTBN specific reset that can be manipulated by software, we can certainly add one here, or OTBN can provide one locally. 

The original reason for not allowing a peripheral specific reset is because there were worries this could be used as an attack (for example a reset releases any access restriction and the dmem is made readeable).  

We might want to discuss a bit then what sort of reset control makes sense.  Blocks like OTBN are a bit more transactional by nature, so I think there are periods where it is safe to issue a reset, and periods where it is not.  So as long as we are clear about the reset expectation and when it can be used / accessed, there's no harm in adding it. 

@moidx 
you mentioned in the other comment there could be a reset before OTBN operation, and a clean-up step afterwards.  Do you envision both being done by the host processor? Or would the clean-up step potentially be done by code downloaded into OTBN? I imagine the clean-up would involve wiping away keys and any sensitive material left over in dmem.

**Comment by moidx** [comment]
Just to move the context to this thread, the OTBN reset discussed [here](https://github.com/lowRISC/opentitan/issues/2696#issuecomment-655714103) is mainly to enable handling of some error conditions without requiring a system reset, for example, unexpected timeouts. This reset could be reduced to reseting the OTBN control logic to be able to bring it back to ready state.

Is the concern that the code running on the host may not be trusted?

It is worth noting that the OTBN execution model relies on a trusted host, for loading initial parameters and polling for completion, so I think in various cases the host could emulate OTBN if it wanted to. Based on this, I think exposing the DMEM state between OTBN reset and clean-up is probably ok.  Please let me know if this claim is too relaxed :) 
 
@tjaychen, yes as you mentioned, clean-up would involve wiping away keys and sensitive material [with random data]. To summarize the clean-up cases mentioned above:

1. After successful execution, host reads results before secrets are cleared from DMEM. Alternatively, OTBN could also clear
   secrets before setting the done status.
2. After a failure is detected. This could be implemented as OTBN reset+clear.
3. Before starting execution of a new operation. This could also be implemented as OTB reset+clear.

And to summarize the clean-up functions being discussed:

DMEM secure clear:
* direct host-side
* triggered by host and handled in OTBN:
  * OTBN-code via secure clear function call with obfuscation quality RND source instruction.
  * OTBN-hw via hw control logic

WDRs secure clear:
* triggered by host and handled in OTBN:
  * OTBN-code handled by runtime, with obfuscation quality RND source instruction.
  * OTBN-hw via hw control logic

We'll have the host-side option available, but I would also like to also discuss the OTBN-code OTBN-hw options. Thoughts?

**Comment by tjaychen** [comment]
@moidx 
yes what you say makes sense.
From my perspective, I do agree the host system is in the same trusted boundary, otherwise, the host would never be able to supply keys or see the results of a bignum operation.

Your points on secure clearing make sense also, although that sounds more like a managed sequence than it does a big reset button.  Maybe @imphil and @GregAC can comment a bit more on how they envision this being implemented.  I tend to think that this is better handled with HW, with host software it may take quite a bit of time and I don't think is completely necessary.

Finally, regarding reset.  I think my main point is that we should not allow OTBN to be reset when it is ongoing a transaction.  This is related to the other issue where @GregAC is discussing accessibility of OTBN during a transaction.   If OTBN does feel like it needs a clean-slate reset, I would recommend following the same approach of only allowing software to provide a hint, and such a reset can only happen when OTBN is "not" busy or a timeout has happened (OTBN has hung - this is kind of a localized watchdog).   This way we prevent any glitch attacks (at least in certain areas of the reset manager) and also prevent software from accidentally shooting itself in the foot.  

Finally, regarding where to implement such a reset.  Remember that resets will all need some kind of DFT bypass, so I would also recommend pulling that into reset manager instead of implementing a local software reset inside OTBN. 

@cdgori , do you see any red flags about what I said?

**Comment by cdgori** [comment]
My 2c:

-It seems like we are in a bit of a catch-22 because we don't want to allow this reset during an ongoing transaction, but one of the proposed uses of this reset is to clear a hung/stuck OTBN?  (At which time, OTBN is almost certainly going to think it's in the middle of a transaction).  I guess @tjaychen is proposing a watchdog that will accept the reset-vote when it times out?

-I was trying to think of a case where you might not want to clear all the DMEM, like you are chaining crypto operations, or had to do some precomputation steps on the key (or curve?) that you would use across multiple signing/key-exchange operations, and therefore you wouldn't want to throw away that intermediate.  I couldn't come up with one, but if others could think about that, it might be helpful.  I can also make a good argument that it's safer to always start from scratch, regardless of performance targets.  :)

-The point about DFT bypassing means I strongly agree with @tjaychen about putting the reset into reset manager rather than generating it locally.

What's the use-case for the OTBN-code reset option?  I'd like to get down to a standard formulation and reduce the number of paths we have to consider, so if that one can be removed I think it's a win.  (If there's a reason for it, that's fine too, I just don't know what it is.)

**Comment by tjaychen** [comment]
@GregAC @imphil 
what do you guys think on this issue? If you've already implemented something, feel free to close this

**Comment by tjaychen** [comment]
@GregAC @imphil 
just wanted to check in with you guys with what's planned today.
This issue might be completely outdated and we can just close it.

**Comment by tjaychen** [comment]
i think this issue is stale now and the resolution is all clear across multiple other issues.
I will close this.
