### ISSUE TITLE
Nightly regression results have rather odd-looking dates

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#2776]
For example, the CHIP results list for yesterday (9th July, with URL https://reports.opentitan.org/hw/top_earlgrey/dv/2020.07.09_02.09.58/results.html) looks like this:

![ss0](https://user-images.githubusercontent.com/104845/87163657-9a361880-c2bf-11ea-8ee2-254f9f2cda01.png)

I assume that the time code in the URL (02:09 am on the 9th of July) corresponds to when the tests finished. I'm pretty certain that the date and time in the page corresponds to when the tests were started (I think they are set in `dvsim.py` before anything gets run). And I believe the "UTC" (looking at the source code).

But then things look a bit confusing: if the tests started at July 8th 04:58am UTC (July 8th 05:58 BST; July 7th 09:58 PDT), this seems to suggest that they took a *long* time: 21 hours if the URL time code is in UTC. Looking at the nightly regression email on the OT list, I got an email with this set of tests around July 9th 02:10 BST, so I think that's right.

Is that correct? If so, is there any way we could run a shorter set of "nightly" regressions with a turn-around time of one night? At the moment, a bug fix will only appear in regression reports two days after it is merged.

**Comment by imphil** [comment]
@msfschaffner @cindychip

**Comment by cindychip** [comment]
Hi Rupert,
I think you have a good point on it.
1). Yeah the nightly regression does run a long time (around 21 hours). I have been monitoring it. We started the regression around 7:30pm PDT Time, usually we do not get VCS license until next day around 9am PDT. That is why the time has been very long. I can contact license person internally to check if there is anything we can do to acquire licenses faster.

2). For a shorter regression, if we reduce the number/set of tests we are running, we might not enable to get 100% coverage. But I do see your point, and since we are adding more and more IPs/tests to the nightly regression, the run time will be even longer. @sriyerg do you have any input on this?

**Comment by sriyerg** [comment]
Lets discuss offline on how we can increase the throughput.

**Comment by sriyerg** [comment]
In the meantime, lets experiment with the test reseeds in each IP and find out if running fewer iterations is enabling us to get to the same level of coverage.

**Comment by cindychip** [comment]
Sounds good, I can try to play around with the current stable IPs.

**Comment by rswarbrick** [comment]
Forgetting about time differences with the UK, it sounds like you're saying that the tests don't actually start until 9am in the morning. I guess that addressing that is probably a higher priority than reducing reseed counts (even if it is harder to get working).

**Comment by imphil** [comment]
If tests don't get licenses until 9am PDT, can you start them at 9am? This way we should get roughly the same end time, but with more recent commits tested (i.e. a lot of work done in morning and early afternoon in the UK).

**Comment by cindychip** [comment]
That could be an option too!

**Comment by msfschaffner** [comment]
Regarding the other regressions (lint, synth): these typically run fairly quickly. Both lint regressions take around 16min together (including result upload). Synthesis is somewhere around 30mins at the moment.

**Comment by imphil** [comment]
It would be nice to have all these reports from roughly the same changeset; so it would be nice to start them roughly at the same time.

**Comment by sriyerg** [comment]
This problem is not solved easily, considering there are several other hardware projects at Google that we are competing with for acquiring a license to run our tests. As I mentioned before, we will discuss internally and find the best way to mitigate this in the short term and in the long term.

**Comment by cindychip** [comment]
Quick update: we moved the time back to trigger at 7pm PST, last night's regression finished at around 2am PST. Total run time is around 7 hours. I will:
1). Keep monitor the runtime to make sure the license issue is resolved.
2) Experiment on reducing the number of seeds to each IPs and see if we can get a satisfied coverage.

**Comment by sriyerg** [comment]
Thanks Cindy for the update!

**Comment by rswarbrick** [comment]
That's great! I'll close this issue now, since we seem to have a fix (and, frankly, the issue name is not particularly helpful: sorry!). We can always open a new one if we see new problems with overnights.
