### ISSUE TITLE
[otbn] Accumulator access instructions

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#2778]
Do we want to add instructions to give easy access to the accumulator used by `BN.MULQACC`? You can already use the `BN.MULQACC` instruction for this purpose but it's a bit awkward (use a series of 1 * N multiplies with appropriate shifts to load desired value into the accumulator, use a 0*0 multiply with a write out to get the current accumulator value). Proposed instructions would be along the lines of

```
BN.WRACC <wrs1>

Write contents of wrs1 register to the accumulator

BN.RDACC <wrd>

Write contents of the accumulator to register wrd
```

We could add some shifting and quarter word enables and such (e.g. allowing you to write the bottom 64 bits of a register into the top 64 bits of the accumulator) if we feel that's useful.

**Comment by imphil** [comment]
With that instruction we could also remove the `.Z` variant from the BN.MULQACC instruction. (Not sure if that's good or bad.)

@felixmiller

**Comment by GregAC** [comment]
You would need an extra instruction to zero the accumulator though, the intent of the `.Z` was to avoid this but this may be a bit of a micro-optimisation ;)

**Comment by rswarbrick** [comment]
The Broadcom DSP I used to work with had a whole load of operations like "macss" (multiply accumulate, signed saturation), "mzcss" (multiply, accumulate from zero), "mncss" (multiple accumulate negative) and (I think) "mnzcss". There were other variants for different saturation options.

I think they basically went for the "encode all the flags in the mnemonic" approach. This makes the syntax nice and regular, but you get a plethora of different instructions.

**Comment by felixmiller** [comment]
If we think about adding such instructions as proposed above by @GregAC , wouldn't it be more straight forward to treat the accumulator just like another WSR, since we already have the required instructions then (BN.WSRRS and BN.WSRRW)? Or is this not a good idea from a hw design perspective?

**Comment by wallento** [comment]
I think @felixmiller's is the best way to add it

**Comment by GregAC** [comment]
Sounds good to me, let's do that. I'll update the documentation.
