### ISSUE TITLE
[otbn] BN.MULQ instruction

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#2779]
Do we want a plain multiply instruction? We do effectively have one in the form of  `BN.MULQACC.WO.Z r2.l, r1.0, r0.0` and similar instructions (i.e. zero accumulator to start then write out result after multiply-accumulate giving you just the multiply result) but this zeros the accumulator.

**Comment by felixmiller** [comment]
If I am understanding this correctly this would only be helpful if we needed to nest some plain multiply within a longer sequence that is using the accumulator, right?
If we don't need this nested multiply, we could just add a pseudo instruction on the assembly level, right?

**Comment by GregAC** [comment]
Indeed this is only useful if you care about the accumulator getting clobbered.

It is maybe a bit surprising for a BN.MULQ instruction to clobber the accumulator but given the specialised nature of the ISA a little bit of odd/surprising behavior may be ok.

Perhaps we want to use a mnemonic that makes it clear ACC gets clobbered? BN.MULQ.WACC or something?

**Comment by rswarbrick** [comment]
I think we've probably decided that we don't need this. @felixmiller, do you agree? If so, I propose closing this issue.

**Comment by felixmiller** [comment]
Yes, I agree, don't think that we need one (that goes beyond what we can already do with MULQACC)
