### ISSUE TITLE
[otbn] Memory Access Alignment

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#2782]
Currently I can't see anything in the OTBN spec that specifies whether memory access should be aligned or not.

I would propose that all accesses must be 4-byte aligned (both narrow and wide accesses). Any unaligned access would cause OTBN to halt with an error.

**Comment by rswarbrick** [comment]
Sounds reasonable to me. Should this also apply to bus accesses?

**Comment by imphil** [comment]
Yes, only aligned accesses. That should be added to the docs.

Rupert: What kind of bus accesses do you mean?

**Comment by imphil** [comment]
Actually, wide DMEM accesses also should be 256b-aligned.

**Comment by wallento** [comment]
Yes, I think both should be the case, alignment to XLEN

**Comment by rswarbrick** [comment]
@imphil: I mean, can the TL-UL bus generate a read for address 0x123 within, say, our DMEM?

**Comment by imphil** [comment]
> can the TL-UL bus generate a read for address 0x123 within, say, our DMEM?

For reads: sub-word accesses not crossing a word boundary are supported by the bus adapter.
For writes: only aligned word accesses.

For all "inside OTBN" accesses: only aligned word accesses; for DMEM, a word can be 32b when accessed from the base ISA side, or a 256b word when accessed fro the BN side.

**Comment by GregAC** [comment]
From a hardware perspective we can happily support reading 32-bit aligned 256 bit words on the wide side.

Though a related question is do we want to increase the data bus width between OTBN and DMem to allow faster reads on the wide side? When we were doing the performance numbers how many cycles did we assume for a load and store?

**Comment by imphil** [comment]
> From a hardware perspective we can happily support reading 32-bit aligned 256 bit words on the wide side.

Yes, but there's no BN instruction using that functionality.

> Though a related question is do we want to increase the data bus width between OTBN and DMem to allow faster reads on the wide side?

The dmem bus is already 256b wide. The performance numbers were assuming a single cycle for loads/stores.

**Comment by GregAC** [comment]
Ah my mistake I had thought it was currently a 32-bit data bus, hence easily supported reads of 32-bit aligned 256 bit words.

In that case the original suggestion of 32-bit aligned narrow and 256-bit aligned wide accesses only is the way to go. I will add this to the docs.

**Comment by GregAC** [comment]
Ah on a closer look there's already mention of alignment on the LID/SID instructions, though the psuedo code for the instructions looks a bit odd

```
memaddr = GPR[rs1] + offset / WLEN / 8
```
The `offset / WLEN / 8` is turning the offset into an address for  a WLEN width memory (i.e. the native addresses used by the DMem) but GPR[rs1] is indicated as a byte address. I think we want something like:

```
memaddr = (GPS[rs1] + offset) / (WLEN / 8)
```

**Comment by imphil** [comment]
yes, it's a mistake I've made consistently in various places :-)

**Comment by GregAC** [comment]
Ok I'll have a look through and correct and ensure alignment requirements as suitably obvious.
