### ISSUE TITLE
 [otbn] register references in MULQACC example

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#2800]
The assembly instructions in the 256x256 multiplication sequence example [here](https://github.com/lowRISC/opentitan/blob/master/hw/ip/otbn/doc/_index.md#algorithmic-example-multiplying-two-wlen-numbers-with-bnmulqacc) are supposed to show directly usable instructions, right? So I think there are probably typos with the additional 'r's. 

So e.g. `BN.MULQACC.Z wr0.0, wr1.0, 0` should read `BN.MULQACC.Z w0.0, w1.0, 0` instead, right?

**Comment by felixmiller** [comment]
@GregAC

**Comment by imphil** [comment]
Yes, that's wrong. Can we add the two "algorithmic examples" in the spec to the snippet collection we've just started to actually run this code through the assembler, and then add it back to the spec?

**Comment by rswarbrick** [comment]
As a quick note, if you add a file `foo.S` in that snippets folder, then run "make" in the `hw/ip/otbn/util` directory, it should get picked up and we'll check that the assembler doesn't explode on it. That's not in CI (yet?), but it's better than nothing, I think.

**Comment by imphil** [comment]
The examples are fixed now, and we have the code in the code snippets collection as well. Including the code from there is tricky, since we add an explanatory table in the docs to visualize how the algorithm works.
