### ISSUE TITLE
[FPGA] utilize NexysVideo ADC for AST

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/opentitan#2814]
The NexysVideo FPGA board has an ADC that we could use to model the functionality of the ADC portion of the AST. @mdhayter has trailblazed this and we can piggyback on that work at the appropriate time (post-bronze).

My recommendation for the order of events here would be:

 - [ ] @nimrodpeled et al complete their work for the behavioral model of the ADC within the AST code base
 - [ ] @esshiu work with @mdhayter to pick up the work there to layer it on top of the behavioral code so that in FPGA mode this functionality is enabled. This requires:
 - [ ] some sort of \`ifdef FPGA switch within the AST to recognize when in FPGA mode in order to switch to the functionality utilizing the ADC. We have similar functionality within several `prim_` modules but would need to apply it here too.

Cc: @tjaychen @msfschaffner @eunchan

**Comment by msfschaffner** [comment]
@a-will @moidx 
Obviously we wouldn't do it on NexysVideo since we don't support that board anymore, but we could technically do it with a newer board.
I just don't know whether it is useful enough to invest effort to implement it.

**Comment by a-will** [comment]
That might be nice-to-have as a demo feature, but it seems doubtful that we'd instrument boards in CI with DACs to test that physical waveforms make it into the device. If we wanted to test adc_ctrl, an FPGA-internal waveform generator is probably the more useful thing for automated tests.

**Comment by msfschaffner** [comment]
Ok sounds good. I will close this issue then since it seems unlikely that we will do this in the near future.
