### ISSUE TITLE
[intermodule] Define the `default` value of the signal

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#2838]
Current implementation requires fixed format for the default value of intermodule signal for any struct type signal. For `logic`, it is tied to `'0`.

There's need to define the default value other than the predefined one.

Currently in `v1-bronze` branch, inter-module signal data structure can have `default` field which can be used to tie the value in some form, which is intended to be bit-wise value not the signal name in the packages. 

CC: @tjaychen @msfschaffner

**Comment by tjaychen** [comment]
@eunchan i think this is already supported right? I have vague memories of reviewing a PR that does something like it :)

**Comment by msfschaffner** [comment]
I think I've carried that functionality over to master as well
https://github.com/lowRISC/opentitan/blob/e3c2150bcc974d66674068b61bdab2d2d1a39ddd/util/topgen/intermodule.py#L763-L784
But I am not sure this covers everything that @eunchan had in mind...

**Comment by eunchan** [comment]
Yeah, I think Michael's implementation is good enough. Thanks Michael!
