### ISSUE TITLE
[otbn] Complete simulator

### ISSUE THREAD

**Issue by wallento** [lowRISC/opentitan#2841]
The simulator should support all instructions and features as currently specified in the spec.

**Comment by imphil** [comment]
@wallento can you outline what's missing?

**Comment by wallento** [comment]
Yes, not much:

- [ ] RSHI and SEL
- [ ] Adopt assembler to syntax change (comma was removed before shift, ++ instead of + etc.)
- [ ] pytests for all instructions, corner cases mostly

**Comment by wallento** [comment]
ETA is before next sprint meeting

**Comment by rswarbrick** [comment]
Long-term, I assume that the simulator is going to consume binary input, rather than assembly. Would it make more sense to do that instead of working on the syntax?

**Comment by wallento** [comment]
It accepts binary, but this needs to come from ibex. So we probably need the carray functionality for that to fill the arrays.
For now, especially the pytests its much easier to just consume the syntax without comma instead of waiting for this.

**Comment by wallento** [comment]
so, the action items are like minutes to an hour, in total probably 2-3 hours of working time

**Comment by wallento** [comment]
Approaching completeness, will fix the tests to be more proper and call stack needs some tests. Will push them hopefully tomorrow

**Comment by imphil** [comment]
@wallento @rswarbrick anything else we need to do as part of this issue?

**Comment by rswarbrick** [comment]
I think we're at the bug fixing stage now. I don't think this issue has any more use.
