### ISSUE TITLE
[otbn] Evaluate performance of modular arithmetic subroutines for NIST_P384

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#2856]
The NIST_P256 implementation makes extensive use of modular arithmetic instructions `BN.ADDM` and `BN.SUBM` to optimize performance in constant time. This works because the architecture supports prime module operands of up to 256b.

By the time OTBN is used in silicon, NIST_P384 is most likely going to be the minimum requirement in some use cases, including device attestation, which requires generating signatures on some boot paths. 

It would be ideal if we can support a level of performance similar to the one achieved with P256 and the initial instruction set.

This issue is to track the following:

* [ ] Profile implementation of P256 and P384 sign/very operations, and evaluate performance degradation due to lack of       extensible modular instructions for P384. (#2982)
* [ ] Investigate instruction set modifications to improve performance for > P256, considering both P384 (required) and 
        P521 (optional).
* [ ] (optional) Capture performance degradation of removing modular operations in P256.

**Comment by imphil** [comment]
Potentially useful paper: https://arxiv.org/pdf/1902.10313.pdf

**Comment by felixmiller** [comment]
ECDSA sign: 17.9 ms on OTBN @ 100Mhz

**Comment by rswarbrick** [comment]
@moidx: Is there anything left to track for this issue? I doubt we're going to change the OTBN ISA before the first tapeout... :-)

**Comment by msfschaffner** [comment]
Echoing the question @moidx @jadephilipoom @GregAC , is this obsolete by now?

**Comment by moidx** [comment]
Closing as obsolete.
