### ISSUE TITLE
[otbn] Document instruction format general approach?

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2864]
We do have a section "Instruction Format" in the OTBN spec at https://docs.opentitan.org/hw/ip/otbn/doc/index.html#instruction-format, which points to the now-closed issue #2391. 

I'm not sure what to do with the "Instruction Format" section.
- Remove it completely?
- Extend it slightly to say that the instructions are given next to each instruction?
- Add a bit of text on the instruction format(s) and how it follows the RISC-V encoding scheme?
- Add potentially even the instruction format templates that are present in the yaml file?

@wallento @rswarbrick

**Comment by rswarbrick** [comment]
I'd suggest removing entirely, or at most keeping the alignment requirements.

**Comment by wallento** [comment]
I agree
