### ISSUE TITLE
[otbn] Remove "Replacing BN.MULH with BN.MULQACC" section?

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2877]
We do have a section "Algorithic Example: Replacing BN.MULH with BN.MULQACC" in the OTBN spec. Since BN.MULH didn't survive the switch to the insn.yml based instruction description (I did miss the discussion on that apparently), should we remove this section?

@GregAC @rswarbrick

**Comment by rswarbrick** [comment]
Yeah, maybe. I guess this section explains our decision but, since the audience for the document has never heard of `bn.mulh`, I suppose it doesn't mean very much. Would it make more sense to rewrite it as "how to do a 256x256 multiply with mulqacc"?

**Comment by GregAC** [comment]
I'd be favour of leaving it in under a different title. I think it's a useful snippet to show how `BN.MULQACC` can be used which is less complex than the 256x256 example.
