### ISSUE TITLE
[otbn] Doc conversion broken?

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2887]
Looks like something recently broke in how we generate the OTBN docs from the insn.yml on master:

![grafik](https://user-images.githubusercontent.com/1467123/87927166-af0e6b00-ca7a-11ea-9f77-a75f25589287.png)

https://docs.opentitan.org/hw/ip/otbn/doc/index.html#instruction-format

@rswarbrick

**Comment by rswarbrick** [comment]
Ah, that's my fault. I've pushed a fix as part of #2807, but I'll factor that out into a quick-apply PR.
