### ISSUE TITLE
[doc, hw] Generated documentation for flash_ctrl's `prog_fifo` and `rd_fifo` is wrong.

### ISSUE THREAD

**Issue by gkelly** [lowRISC/opentitan#2892]
Looking at [the generated docs](https://docs.opentitan.org/hw/ip/flash_ctrl/doc/index.html#register-table), the `prog_fifo` and `rd_fifo` show very strange layouts, including self-overlap, cross-region overlap, and even overlap with previous registers. Given these are one-element FIFOs shouldn't they just be one 32-bit entry as rendered?

**Comment by gkelly** [comment]
@lenary @sjgitty for visibility.

**Comment by lenary** [comment]
Triaging: The problem is here: https://github.com/lowrisc/opentitan/blob/0bd7566655a0d18b044a0acb749110273c36bee2/util/reggen/gen_html.py#L277-L278 If `win['items']` is 1, then the generated table is too long.

**Comment by rswarbrick** [comment]
This seems to be fixed now:
![image](https://user-images.githubusercontent.com/104845/122566873-f660fb00-d03f-11eb-8ebe-c5e5f0d68ca0.png)
