### ISSUE TITLE
List of IP supported for FPGA(Nexys Video)

### ISSUE THREAD

**Issue by nashsrg** [lowRISC/opentitan#2907]
Hello,

Is there documentation which list out Currently integrated List of IP on FPGA platform or road map for IP integration on FPGA. 
Is there any time line to integrate Entropy_src IP on Nexy Video platform.

**Comment by tjaychen** [comment]
sorry for the late reply, but that one will be coming soon, along with the rest of the entropy complex.
There are still a lot of discussions on exactly how those blocks should behave right now.

**Comment by msfschaffner** [comment]
In the meantime we have transitioned to the CW310 FPGA board, and the NexysVideo board has been deprecated.

If you look at the [hardware dashboard](https://docs.opentitan.org/hw/), you will see that most of our IPs are at or beyond the D2 design stage, which basically means that IP integration into the top-level is now complete and we are focusing on bug fixes and coverage closure.

Please feel free to reopen this issue if you have more questions.
