### ISSUE TITLE
[otbn] Document/comment modexp.S assembly

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#2908]
The bignum assembly lib for otbn should be better documented.

A documentation header for each subroutine should be added containing at least:
- General description of purpose for each subroutine
- Input and output GPRs and WDRs
- Temp register usage

Effectively the only algorithm we have right now is modexp.S, the other files in `sw/otbn/code-snippets` are minimal test cases and reasonably well documented.

> estimate 16
> remaining 2020-09-20 8
> remaining 2020-10-05 2
> remaining 2020-10-11 0

**Comment by imphil** [comment]
Fixed by https://github.com/lowRISC/opentitan/pull/3774
