### ISSUE TITLE
[otbn] Document software toolchain

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2930]
We now have a almost complete toolchain for OTBN, we should start documenting how to use it from the perspective of a software developer.

I'm proposing to create a "OTBN software developer user guide" document at https://github.com/lowRISC/opentitan/tree/master/doc/ug.

> estimate 4

**Comment by rswarbrick** [comment]
Just noticed that this is part of the sprint that I can help with. I'll start working on this now.
