### ISSUE TITLE
[otbn] Where should software targeting OTBN live?

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2935]
Up to now, we do have two (and a half) software hierarchies: host, device, and boot_rom. With the introduction of OTBN, we have a third target with its own toolchain and software: the "otbn device".

We currently don't have production software, but we have started collecting example assembly code for OTBN (partial algorithms, see https://github.com/lowRISC/opentitan/commit/1047ba2fb548d120c82ac653c588218f505de39e), and we have produced a toolchain (assembler, disassembler, objdump) for it.

The question is: where should this software live? Maybe `sw/otbn` (with example code as we have it today in `sw/otbn/examples`, etc. mirroring the hierarchy in `sw/device`?

@gkelly @lenary

**Comment by lenary** [comment]
I'm happy with `sw/otbn`, with subdirectories `lib`, `examples` and `tests` for the moment.

**Comment by moidx** [comment]
Will `boot_rom` then have a dependency such as `sw_otbn_lib_rsa_3072_verify_bin`? 

I think `sw/otbn` is ok, with the understanding that `device` targets will have `otbn` dependencies.

**Comment by lenary** [comment]
Yes, I agree cross-device dependencies will be needed, but I don't think that's a problem with this approach. #2936 covers more of the build system concerns.

**Comment by moidx** [comment]
SGTM

**Comment by imphil** [comment]
Seems like we do have agreement on where OTBN device code should live. Next: move it there.
