### ISSUE TITLE
[hw] RFC: Finalize hardware support for secure boot

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#2947]
*Note: This proposal changed a bit over its lifetime. The current proposal is to implement the enhanced PMP spec as discussed below.*

## Introduction
There are ongoing discussions about the most appropriate way to secure the boot process against glitch attacks that would cause the PC to move to untrusted code giving an attacker control over an OpenTitan device whilst various sensitive configuration settings and keys may be available that are later locked down. The use of PMP regions to prevent execution of untrusted code is one way to prevent this but the existing PMP functionality isn’t ideal for this purpose. More background to this can be found in RFC: OpenTitan Secure Boot HW Support and M-Mode PMP change proposal (an older RFC that is superseded by this one). The RISC-V TEE (Trusted Execution Environment) working group has been working on an enhanced PMP specification which is now stable and on it’s way to ratification.

## Proposal 
Implement the enhanced PMP specification in full, it provides useful functionality for both secure boot as well as for Tock. Work to support it in Tock is already underway https://github.com/tock/tock/pull/1873. ePMP though not yet ratified is expected to become part of the RISC-V specification and there are clear benefits to implementing standardised functionality rather than our owr custom functionality.

**Full proposal text: https://docs.google.com/document/d/1vqwbRHTpPxD8MUI9jVmTMPMXmFzPpChmAdwciLCZFZ8/edit**

----

*Old Proposal below, only to preserve history.*

> ## Introduction
> 
> The secure boot implementation requires a mechanism to only allow execution of verified code. The implementation shall support this even when handing over execution between partitions running in Machine mode (M). Additional considerations are taken to make sure the unlock for execution operations are glitch resistant. 

> Current list of proposals:

> 1. Change default PMP `M` mode to DENY execution. This potentially forces the use of a PMP region per verified partition. (lowrisc/ibex#909)
> 2. Consider option to enforce PMP access without requiring `L` bit. This is potentially not recommended as it would make
    auditing of `M` access harder to implement.
> 3. Implement additional unlock functionality for block regions. Additional details below.

> ## Additional unlock functionality

> An additional PMP-like construct provides the ability to enable any mode of execution (`M` or User `U`) in at least 3 to 4 contiguous memory regions, which are configured as part of secure boot. 

> Each region is configured via a start address and size, where the size can be specified in a granularity level compatible with the flash page size configuration. There is no support for misaligned start or end addresses in this implementation.

> The unlock interface is implemented as described in: https://docs.google.com/document/d/1O7st0Vdv6gIIQzrYHtQ3CuNmzAWYeVEi5pFEvpULGOU/edit?usp=sharing

> This proposal may or may not require the use of additional PMP entries to enable execution if PMP is configured in `M` DENY default mode.

**Comment by gkelly** [comment]
@lenary @gkelly @alphan @GregAC for visiblity.

**Comment by tjaychen** [comment]
Andrey from ChromeOS also chimed in that in addition to PMP type function, it may be interesting based on the HW results to directly jump software to a success / failure location.

This sounds basically like an NMI to me and I think could be interesting.   We could for example, require the activation of the comparator be based on a bunch of programming and `wfi`, and wait for the comparator output to both unlock the execution region and jump software to the appropriate place. 

Just a thought.

**Comment by GregAC** [comment]
On the hardened comparator along with the pmp-like construct could we just side-load things into PMP based upon it's comparisons? This will of course burn some more PMP regions

**Comment by tjaychen** [comment]
yes that would be good. Does this mean ibex will expose an interface for
contents "to be loaded"?

**Comment by GregAC** [comment]
Yes I think we could do that. May not be strictly spec compliant but as I see it only the mask ROM (and maybe ROM exts?) would see this special behaviour of PMP regions appearing outside of what the software has written to the PMP CSRs. The normal firmware won't see it at all just the end result which it can't distinguish from the mask ROM having set the regions up the normal way. Slight spec deviation should be ok for the ROM as it's very specific software so reasonable to say anyone working on ROM software needs to be aware of some OT specific details.

**Comment by moidx** [comment]
@GregAC has put together a proposal covering PMP changes for secure boot:

https://docs.google.com/document/d/1jWBtlgFs-m-V6sF6lNqP-Wp0DhUgYJB7wZc8-LaMURQ/edit#heading=h.arl1336hpt50

**Comment by rbohn** [comment]
I commented in the other doc already, but why introduce new off-spec behavior in the PMPs instead of implementing the enhanced PMP spec? The enhanced PMP spec has been in development for a couple years and is considered stable / no longer being actively worked. The specific allow / deny default behavior in M mode is covered by mseccfg.MMWP. If the enhanced PMP spec doesn't cover some use case you have in mind I'm sure the TEE group would be interested in looking at it.

**Comment by moidx** [comment]
Adding a link to the enhanced PMP spec referenced by @rbohn : 

https://docs.google.com/document/d/1Mh_aiHYxemL0umN3GTTw8vsbmzHZ_nxZXgjgOUzbvc8/edit#

**Comment by GregAC** [comment]
Thanks for highlighting the work of the TEE group @rbohn. I had been planning on reviewing what discussions and proposals had been happening around PMP in the RISC-V community but had yet to do so in detail.

We can potentially get the functionality we need from the proposal.

Initially it looked like `mseccfg.MML` would do what we need however with `mseccfg.MML` = 1 we can have a non-locked region that denies execute to M mode but looking at the truth table we can't setup a region that M mode can execute without setting the locked bit. I believe we'll also want to setup read-only regions (that M-mode can read) again without setting the locked bit which we can't do either. Plus `mseccfg.MML` is sticky in the opposite direction to what we might want (we'd want to start with `mseccfg.MML` set and then clear it).

The `mseccfg.RLB` may do what we want. If we reset with that set then we can boot in a mode that gives generally the same functionality as what my proposal provides. The only difference being the inability to set a 'true' locked region (if `L` is set with `mseccfg.RLB` the region can still be modified), practically I'm not sure we care about that part of the proposal and if we do it's likely we'd want to setup a locked region or two at the end of the boot process in which case setting them then clearing `mseccfg.RLB` should suffice.

One thing that does give me pause for thought is the wording that describes `mseccfg.RLB`

> Note that it’s intended to be used as a debug mechanism, or as a temporary workaround during the boot process for simplifying sw

It makes it sound like using this in a non-debug context is a bit of a hack that is to be avoided. Which doesn't really match with what we're doing, where this will be a key part of the OpenTitan boot process. I do note later rationale frames `mseccfg.RLB` exactly in this way (something to be used at boot then locked down).

Another concern is the threat model described at the beginning of the proposal (namely Machine/Supervisor code tampers with User mode code/data) isn't the threat we're worried about during OT boot. It's more incidental that the functionality the proposal introduces can also help us and it's only a small bit of the proposal (namely `mseccfg.RLB` and potentially `mseccfg.MMWP`). So to fully implement the proposal we'd need to spend effort on the design and verification of a feature we're mostly not using. Of course we may decide the `mseccfg.MML` bit is of interest to the firmware in which case we'll want to implement the proposal in full.

Perhaps a way forward for us would be to only implement the `mseccfg.RLB` and potentially `mseccfg.MMWP` for now and on the Ibex roadmap plan implementation of the full proposal. That way Ibex will eventually become fully compatible and OpenTitan itself wouldn't have anything off-spec even if it doesn't implement the full spec.

**Comment by rbohn** [comment]
You might want to join the TEE mailing list and describe the problem you're trying to solve. I believe they were trying to cover a lot of use cases that the original PMP lacked. If there is some legitimate security use case not handled even by the enhanced PMP spec there could be time yet to change. I imagine nobody wants to be entertaining an enhanced enhanced PMP spec any time soon after the enhanced PMP spec is ratified.

**Comment by GregAC** [comment]
I joined it this morning, have been looking through some of the discussions. There does seem to be further discussion looking to move beyond or replace the TEE PMP proposal on the tech-privileged mailing list. Is it likely this will go anywhere or will the TEE PMP proposal definitely become spec and anything else will be future modifications/extensions to it?

I'd like to resolve some of our internal discussion threads before I post to TEE, however once we're more certain on the way we'd like to go I'll post, either to describe why our use case doesn't fit the available functionality or simply to point the working group members to what we're doing with it as a matter of interest.

**Comment by alistair23** [comment]
+1 on ePMP. There is work ongoing in Tock to support it.

**Comment by moidx** [comment]
Cross-linking @alistair23's ePMP efforts in TockOS tock/tock#1873

**Comment by GregAC** [comment]
Implementing ePMP in full is now being investigated in detail. I will share around a document with some details.

**Comment by GregAC** [comment]
I've put together a short proposal on use of ePMP in OpenTitan here:  https://docs.google.com/document/d/1vqwbRHTpPxD8MUI9jVmTMPMXmFzPpChmAdwciLCZFZ8/edit#

**Comment by alistair23** [comment]
That is great to hear!

The Tock HIL has been merged. A ePMP implementation is on my TODO list. There are patches for QEMU support as well to help with testing.

**Comment by imphil** [comment]
The Technical Committee approved the plan to implement the Enhanced PMP proposal (ePMP). @GregAC, please have a look at the outstanding commits from @alistair23 in the linked document to ensure that we don't miss valuable input as we move along.

**Comment by mickflemm** [comment]
Hello there, we made a last-minute change on the ePMP proposal, the encoding LRWX=1111 when MML=1 now encodes a shared read-only region (read-only for both M and S/U mode) instead of a locked read/write/execute region. The latest version can be found here -> https://docs.google.com/document/d/1Mh_aiHYxemL0umN3GTTw8vsbmzHZ_nxZXgjgOUzbvc8 Since we 'll hopefully soon move on to public review, I'd love to work with you and make sure your use cases are also covered. Please let me know if I can help in any way.

**Comment by GregAC** [comment]
Thanks for the heads up, @alistair23 @gkelly @lenary please note the change.

**Comment by silvestrst** [comment]
@silvestrst @mundaym for visibility

**Comment by moidx** [comment]
Closing this issue as we are moving into implementation.
