### ISSUE TITLE
[otbn] The simulator should decode instructions based on the encodings in insns.yml

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#2964]
If the encodings in the YAML file are the "golden reference", the simulator should probably decode using them. There's a simple (if inefficient) example of how to do this in `otbn-objdump`.

The difficulty here is mapping between the mnemonic-keyed dictionary in `insns.yml` and the hierarchical instruction classes in riscv-python-model. Maybe we can do some introspection on the class hierarchy (one-off!) to produce that mapping and make ourselves a factory method?

**Comment by imphil** [comment]
@rswarbrick this one is done as of #3312, isn't it?

**Comment by rswarbrick** [comment]
Yep! Apparently, I forgot to link the issue. Thanks.
