### ISSUE TITLE
[otbn] What should traces look like?

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#2966]
At the moment, we haven't got a tracer in the RTL. We do, however, have tracing in otbnsim. The basic design is that you get a list of Python "trace items" which can be printed with `str()`.

Eventually, we're going to want to compare the RTL's behaviour with that of the simulator. The easiest way to do this is diffing the output traces. Are we happy to force the SystemVerilog tracer to generate the existing trace format from otbnsim? If not, how do we fix it? Do we change the riscv-python-model code (dubious, because it's not just used by OTBN), or do we have some sort of translation layer?

I don't really have a preference but, if we do go for a translation layer, I propose that we put it in the otbnsim code. This will make it much simpler to do lock-step comparisons (because then the C++ or SystemVerilog code that's doing the juggling between the design and the model can just do a textual diff between the two outputs).

**Comment by imphil** [comment]
The tracer is now implemented and a documentation is available in the README.
