### ISSUE TITLE
[otbn] elf loading non-functional for standalone OTBN sim

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#2968]
When building a binary using otbn-as directly supplying the elf file as initial memory contents for the IMem in the standalone simulation doesn't seem to work. You need to produce a .vmem from the .elf with objcopy and srec_cat.

> estimate 4

**Comment by rswarbrick** [comment]
Yep, we definitely need to get this working! :-) I think the easiest approach might be a simple-minded Python tool that gets called as a subprocess. Then we can use `pyelftools` to do the heavy lifting, and can probably re-use the result for the final DV environment too (calling the subprocess via some DPI wrapper).

**Comment by GregAC** [comment]
Given it works fine with the same code in the ibex simple_system environment and the OT earlgrey I'd hope we wouldn't need to do anything that involved as the work is already done. Mostly raised the issue so I don't forget about it, wanting to concentrate on non OTBN things for the rest of the day.

I've switched this to a 'bug' from 'enhancement' as it technically should work already.

**Comment by GregAC** [comment]
After looking into this .elf loading is perfectly functional but you need to be supplying it with an appropriate .elf (I had initially used the a.out produced by otbn-as but as this lacked a program header it didn't load).

I've written a short shell script that will build a single .S link it (with otbn-ld) then use objcopy to get seperate imem and dmem elfs. We could alter the Verilator infrastructure to make this a bit easier (take a single .elf then load it into seperate dmem and imem memories) but this was the simplest thing to do for now.

I'll close this issue as I've marked it as a bug but it's perfectly functional after all. We may consider improvements to the verilator infrastructure but that will be a separate issue.

**Comment by rswarbrick** [comment]
Well, long term, we should definitely consume a single ELF for IMEM and DMEM. But I'm happy to track that separately.

**Comment by GregAC** [comment]
Yup agreed. For now I'm trying to get smoke test going in the simplest way possible (as it will be retired when we have more DV infrastructure). Doing this properly may involve some changes to the shared verilator infrastructure or spinning up something new which I felt fit better with the overall DV infrastructure work.
