### ISSUE TITLE
TL-UL Channel A signal "a_ready" an input?

### ISSUE THREAD

**Issue by hadirkhan10** [lowRISC/opentitan#2985]
I have this confusion regarding the bus specification document of OpenTitan. The **_a_ready_** signal is defined as input to the host from the device, is this correct? I mean studying the TileLink specification what I understood is that Channel A is a uni-directional channel which requests and Channel D responds to it. Wouldn't the **_a_ready_** signal be the output from the host to the device to tell the device that the host is ready to accept the response from the device (slave)?

**Comment by sjgitty** [comment]
See TLUL spec, ready signals are in reverse direction to the rest of the bus.

![Screen Shot 2020-07-27 at 3 53 23 PM](https://user-images.githubusercontent.com/41092437/88599766-6b3ed700-d021-11ea-95ce-8eefca1f3307.png)

**Comment by hadirkhan10** [comment]
Oh, so here a_ready signal will indicate the host that device has accepted it's data and new data can be sent?

**Comment by sjgitty** [comment]
Basically, yes. It is the typical valid/ready handshake. Host indicates data is valid, Device indicates it is ready to receive, thus transaction is accepted. If !ready then host must resend the next cycle.

**Comment by hadirkhan10** [comment]
Alright got it!
