### ISSUE TITLE
[prim/rtl] prim_packer creates feedback loop when interfacing to FIFO

### ISSUE THREAD

**Issue by mwbranstad** [lowRISC/opentitan#3000]
After some analysis, it appears that the prim_packer module can not conveniently hook up to a feeding FIFO. In other words, a feedback loop is created when trying to gate the valid_i with the output ready_o. I have instructions from @eunchan to expressly not do this, but this is not user friendly. Instead, the output from the internal packer space counter should be provided as an output as a potential fix. When full (count is max, and based on flops), the result of that count can be used directly to gate the packer write signal (valid_i). Please consider this feature. Otherwise, external logic will need to be added to do this same function.

**Comment by tjaychen** [comment]
Hey Mark,
Just so I understand, what is the reason you want to gate valid_i and not
use the valid / ready handshake upstream to know that information from a
feeding FIFO should not be popped?
Am I understanding this correctly?

**Comment by mwbranstad** [comment]
@tjaychen correct! The prim FIFO operates this way, for example.

**Comment by tjaychen** [comment]
sorry Mark, I think i didn't state this correctly.
I'm asking why we would need to gate the valid vs using the condition of
valid / ready to pop the upstream fifo?

**Comment by mwbranstad** [comment]
@tjaychen here is my view of this: the prim_packer module is actually quite useful in the function it provides. However, I am used to a fifo flow and related controls. Having feedback signals breaks this model I believe. It could be that the prim_packer was specifically design for a certain flow (maybe high performance) that requires this capability. I was expecting this behavior:
1 - ready_o is asserted (packer is empty)
2 - valid_i is pulsed for N times, where N is full
3 - valid_o asserts on cycle N; if ready_i is asserted, valid_o de-asserts next cycle, else remains asserted and ready_o de-asserts next cycle
The above behavior is like the prim_fifo, where there is a 1 clock cycle delay from input to output of the fifo, and no direct control pass-through paths.
Again, if this module was designed for a certain usage, I can certainly add external logic to get around the feedback issue. just thought is this were a common problem, all users might benefit from a logic change to remove this potential loop case.

**Comment by tjaychen** [comment]
Thanks Mark.
Actually what you described is exactly how I would expect prim packer to
behave. Eunchan can you confirm?
What are you seeing the packer do instead..?

**Comment by mwbranstad** [comment]
Already changed the original setup. Working on re-creating this.

**Comment by mwbranstad** [comment]
@tjaychen I could not get the prim_packer to work as I would have expected it to work. So, after adding an external "depth" counter, I got the timings that I wanted - timing diagram attached. However, I get the following assert to fire and have notidea how to avoid:

![image](https://user-images.githubusercontent.com/52834797/88852249-a113c500-d1b3-11ea-8125-0ef0e2c79f4d.png)
[
![Packer](https://user-images.githubusercontent.com/52834797/88852319-b7ba1c00-d1b3-11ea-99bd-c9b81ea76332.PNG)
](url)

**Comment by cindychip** [comment]
Hi @mwbranstad, just want to double check: are you trying to downsize using prim_packer? is your `InW` > `OutW`, if so, I think the current `prim_packer` might not fully support this case. I filed an issue here https://github.com/lowRISC/opentitan/issues/2446. Just want to check if your issue is similar to this one?

**Comment by mwbranstad** [comment]
Hi @cindychip - yes, going from 128 bits to 32 bits. The waveform shows this working functionally, but the assert may not handle this case. Can this assert be commented out until it has been tested? Otherwise it bombs out the test run currently.

**Comment by cindychip** [comment]
Sure if this is only an assertion issue. I will try to fix it soon then.
Sorry for the inconveniences.

Cindy

**Comment by mwbranstad** [comment]
Thanks @cindychip. I believe that it is only an assertion issue.

@tjaychen - back to the functional issues of prim_packer. I see that there are 3 options to proceed:
1 - added a packer_full signal (based on a flop count), which when inverted can be used as "ready" for the upstream FIFO.
2 - create a "prim_packer2" that has prim_fifo_sync controls
3 - Do as I have in the attached waveform, and just add external logic to do this function
Please advise on your preference. Thanks.

**Comment by eunchan** [comment]
I think I need to review the prim_packer design again. Maybe I forgot the assumption on the behavior of prim_packer.

As far as I know, prim_packer is designed to have max(InW, OutW) storage inside. So basically, it is not FIFO. It is bridge to FIFO. In order to make it in the way @mwbranstad describe, it should have full storage of (InW + OutW) and the `valid_o` asserts at least one cycle after `valid_i`. 

If we want FIFO behavior, it would be better to have another packer module (maybe `prim_packer_fifo`?)

**Comment by mwbranstad** [comment]
@eunchan that makes sense to me (my option 2 from above). If it would be helpful, I will offer making a simple version, one that does not support masking and uses the minimum storage possible. Let me know. Thanks.

**Comment by eunchan** [comment]
Thanks @mwbranstad More than welcome for the contribution :)

**Comment by mwbranstad** [comment]
A PR has been made to include the new "prim_packer_fifo" and related documentation. It has also been included as a used module in entropy_src rtl.
