### ISSUE TITLE
[regtool] Change in multireg suffix from `N` to `_N`

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#3006]
When generating multiregs, the regtool currently adds a `N` suffix to the basename to identify the individual registers. For example, for a multireg named `DATA_IN` with `count` equal to 4, the regtool generates 4 registers: `DATA_IN0`, `DATA_IN1`, `DATA_IN2`, `DATA_IN3`.

This works all fine, but if the basename already ends on a number character, this may cause issues. We already have that in the PLIC today: there can be multiple targets (basename) each having multiple interrupt enable registers (that's the multireg) resulting in register names like `RV_PLIC_IE00`, `RV_PLIC_IE01`, `RV_PLIC_IE02`. If we would add a second target, we would get also `RV_PLIC_IE10`, `RV_PLIC_IE11`, `RV_PLIC_IE12`. I see the following problems with that:
1. Readability could be better.
2. It may be confusing that there are registers `RV_PLIC_IE02` and  `RV_PLIC_IE10` but no   `RV_PLIC_IE03` - `RV_PLIC_IE09`.
3. What if we have more than 10 multiregs? We then get  `RV_PLIC_IE00` -  `RV_PLIC_IE010` forming a group and `RV_PLIC_IE10` -  `RV_PLIC_IE110`...
 
It's expected that we get more of these cases during the process of hardening our crypto accelerators, which in some/many cases may involve adding multiple multireg copies to pass in the data/key material in multiple shares as shown for AES in #2933  where we have `KEY_SHARE0` and `KEY_SHARE1` with 8 registers each.

I am thus suggesting that we change the suffix added for multiregs from `N` to `_N` either:
- Whenever the basename ends on a number (this is what PR #2980 would do). The PLIC registers would be renamed to `RV_PLIC_IE1_0` -  `RV_PLIC_IE1_10`.
- In general. Also the `DATA_IN` registers above would be renamed to `DATA_IN_0` - `DATA_IN_3`.

What do you think?

**Comment by silvestrst** [comment]
Sounds reasonable to me, it would be nice to figure out whether this change will affect much beyond `_regs.h` files. I think so far (might be wrong), the only merged DIF that has peripheral with multireg registers is PLIC? And if I correctly remember how generate cheader, etc... works - the proposed change should not have any impact on that?

**Comment by lenary** [comment]
The only real concern I have is if we need to generate camelcase names for any registers/fields - camelcase cannot separate adjacent numeric parts (because it does not use underscores to separate parts).

**Comment by imphil** [comment]
The Google C++ style explicitly allows `_` in this case even for camel case names, e.g. https://google.github.io/styleguide/cppguide.html#Constant_Names.

**Comment by lenary** [comment]
Ah, ok, then I have no issues :)

**Comment by alphan** [comment]
Sounds good to me.

**Comment by vogelpi** [comment]
Regarding how many files are affected beyond `_regs.h`:
Option 1 - Change only multiregs where the basename ends on a number:
```
sw/device/lib/dif/dif_plic.c
sw/device/tests/dif/dif_plic_unittest.cc
```
Option 2 - Change all multireg names:
Difficult to estimate. Doing a `make -C hw regs`, one can see that the follwoing IPs are affected:
- aes
- flash_ctrl
- hmac
- otp_ctrl
- padctrl
- pinmux
- usbdev

The affected files include both RTL and DIFs (not sure which ones have one at the moment).

**Comment by alphan** [comment]
I lean towards option 2 because I think it is more consistent. I know the list looks long but I am wondering if the script can be temporarily modified to output the before and after names of the registers so that we can update everything by doing an in-place search & replace?

**Comment by lenary** [comment]
If we modify to using underscores, the software build should fail everywhere those macros are being used, which achieves what we want without having to include both old and new names. Given the register layouts aren't changing, just their names, I'm less worried about places that don't use the macros.

I don't know how this affects RTL though.

**Comment by vogelpi** [comment]
It's good to know that you guys are in favor of the more consistent second option. I am now in the process of doing a PR.

**Comment by vogelpi** [comment]
PR #3051 implementing Option 2 was merged. I am closing this issue.
