### ISSUE TITLE
CI Checks not Reporting Results on some PRs

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#3007]
Checks were never run on this PR: https://github.com/lowRISC/opentitan/pull/3003

I almost clicked "Merge", but then realised there should be CI runs there.

Do we need to do something to require the CI runs to have happened before merging is allowed?

**Comment by imphil** [comment]
The tests get run, only the results don't get reported back. I've seen that for a day or so now, and I've also seen it with Travis in another project (https://github.com/olofk/fusesoc/pull/431 is missing a Travis run). So I'm pretty sure there's a service outage somewhere, likely on the GH side. 

Not much we can do at this point. To merge stuff, you unfortunately need to manually look up the run in the Azure Pipelines UI.

**Comment by lenary** [comment]
Oh wow, ok, so they are triggered

**Comment by lenary** [comment]
I am going to leave this open while we are seeing this kind of issue.

**Comment by imphil** [comment]
I did file a support ticket with MSFT, ticket number SR120072925002958.

**Comment by imphil** [comment]
https://github.com/lowRISC/opentitan/pull/3013 does have now both checks again. Let's see if that is consistently the case for new PRs.

**Comment by imphil** [comment]
Recent PRs have both checks visible again, seems to be resolved. 

MSFT did get back to me and they didn't see any error on their side, so it likely was a GH issue that is now resolved.
