### ISSUE TITLE
[top] Adding external TL-UL ports

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#3031]
As Earlgrey receives AST, top_earlgrey needs to have TL-UL port to communicate with AST, which sits outside of `top_earlgrey` module. There's way to create top port using inter-module signal `ext` feature.

But, Xbar is not handled as comportable IP currently. So its ports are not in inter-signal list. Here are the list to make it work:

- [x] tlgen: `generate()` to create comportable IP hjson that contains `inter_signal_list` for the all ports for a Xbar
    - #3026 addresses this
    - Still it is debatable whether we make generated Xbar hjson to be comportable IP hjson or create new hjson file. Issue #3026 chooses latter, but personally I think amending to the generated hjson is more proper.
- [x] reggen: When validating, convert `bus_device` or `bus_host` into `inter_signal_list` with fixed naming format `tl_o`/`tl_i`. Issue #3040 
- [x] topgen:
    - (TBD) When reading the IP hjson object and amending to xbar hjson, add the connection to `inter_modue["connect"]`
    - After requesting `tlgen.generate()`, read-back the generated hjson object and add to `inter_signal["definition"]` Issue #3040 
    - `intermodule.py` to support arbitrary pair names for "req_rsp". Currently it only supports `{name}_req/rsp_t` type and `{name}_o/_i` name but for TL-UL, it needs to support `{name}_h2d/d2h_t` and `{name}_h2d/d2h` port name too. Issue #3040 

This issue is to achieve the request in #2956

CC: @tjaychen @msfschaffner @sjgitty

**Comment by eunchan** [comment]
CC: @sriyerg As this may affect top level DV environment too.

**Comment by eunchan** [comment]
#3040 addresses most of the items. But still topgen need to create connections manually.

**Comment by eunchan** [comment]
Closing the issue, as these are addressed in #3040 but still a few small updates are required such as autoconnect (#3086 ) and external port naming issue (not yet PR). Let me create an issue for the latter.

**Comment by eunchan** [comment]
#3098 addressed last part. Need to check if TL-UL port can be exported or not. But let me close this issue.

**Comment by tjaychen** [comment]
i'll try this one as part of AST, i need to rebase for the clock name
changes anyways.
