### ISSUE TITLE
[otbn] How should we package OTBN Python code?

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#3036]
At the moment, the simulator (on the `otbn-dev` branch) uses `pip`/`distutils`/`setup.py` to install itself as a proper Python package. The other code in `hw/ip/otbn/util` doesn't.

We're going to have shared Python code that is used by both the simulator and the other OTBN tooling. For example, we currently have `mem_layout.py`; we'll probably grow more as time goes on. I don't think this should be part of the simulator (since I don't think that a tool like `otbn-ld` should depend on a simulator!). But, as far as I can tell, for a distutils-based package to load code, that code needs also to be installed as a distutils-based package.

How should we do it? My thoughts so far:

  1. We probably need to put the shared code in some directory that isn't above the simulator. Maybe something like `hw/ip/otbn/util/<FOO>`, but I'm not sure what `<FOO>` should be.
  1. I'm not really a fan of distutils for local packages: if you install `otbnsim` with pip, you'd better either use virtualenv or make sure you only have one OpenTitan checkout. Otherwise, you're going to get very confused with mismatched python code. But I'm not sure whether there's a neater way to deal with this. Anyone?

@wallento, @imphil, @lenary: I'd love some input!

**Comment by rswarbrick** [comment]
Another way of doing things, which keeps us at just one distutils package is to have a single "otbn" package, which has `otbn.sim` as a submodule and something like `otbn.shared` for the shared code. This also avoids a proliferation of "otbnFOO" directories, which would be nice.

**Comment by wallento** [comment]
I suppose we should use namespaces in packages as you suggest (`otbn.sim`, `otbn.tools`, ...). I will adopt the PR towards master accordingly. The organisation in the tree is orthogonal to the discussion I believe.
Re 2: Currently its installed editable (-e) by the requirements file, which in my opinion is the best way to do it with venv in the opentitan local copy (which I believe is the dominant use case, right?)

**Comment by rswarbrick** [comment]
Well, I think we currently are requiring anyone who wants to use more than one OpenTitan checkout to understand how to use the `venv` command. This seems a little unfair if they don't care about our stinkin' Python :-)

Or have I misunderstood something?

**Comment by rswarbrick** [comment]
About the namespacing: that sounds sensible. I don't think it's completely orthogonal to the organisation in the tree, unless you want multiple distutil packages, which seems unnecessary to me.

**Comment by lenary** [comment]
I don't have strong opinions as I know very little about python packaging. Maybe a different question is: why do we need to release otbnsim as a separate package, rather than running it from inside the repo?

**Comment by rswarbrick** [comment]
@lenary: We are running it from inside the repository. I think the main reason for the `otbnsim` code to use distutils packaging is that it means we can list dependencies on other Python packages in `hw/ip/otbn/util/otbnsim` rather than at the top of the repository. These dependencies get included by `python-requirements.txt` (with a line containing `-e hw/ip/otbn/util/otbnsim`) and it's kind of nicer not needing to list them all at the top-level.

The other side effect of using a distutils package is that the command line programs get inserted into the user's path. I think this is a bad thing, and think we should stop futzing around with users' `~/.local/bin` directories: whatever else we decide, I'm going to be agitating to get rid of that!

As far as I know, there's no other benefit to making a proper package rather than using the traditional "pile of directories with `__init__.py` files".

@wallento: Have I missed something?

**Comment by wallento** [comment]
Well, you are making the case for using venv. The presence of `$REPO_TOP` all over the place seems less attractive to me, but in the end its a project decision and I will not be agitating. Also, you are already trashing people's environment with occasional 
The definition of a Python package literally is to have a pile of directories with `__init__.py` files ;)
So, I don't really care. I can move things around if others have stronger opinions. In particular we can use a relative path to the simulator python module.

**Comment by rswarbrick** [comment]
@wallento: I think I understand most of that. Could you expand on "Also, you are already trashing people's environment with occasional"? I think there might be some words missing, and that seems like it might be an important point!

**Comment by imphil** [comment]
> The other side effect of using a distutils package is that the command line programs get inserted into the user's path. I think this is a bad thing,

I disagree. It's a good thing.

There are roughly three variants to make Python applications available to the user: global installation, user-local installation, and directory-local installation with a venv. Let users decide what they want to do by running "pip install" the way they want their applications to be installed. I don't see a need or benefit from inventing a fourth version which is manually modifying `sys.path` to create a custom package discovery mechanism. 

I'm clearly opting for the use of distutils.

> make sure you only have one OpenTitan checkout

That's the standard case, and the one we should be optimizing our usability story for.

**Comment by rswarbrick** [comment]
Ok, it looks like we have consensus between `N-1` of the people that care about this (and I'm the -1) :-(.

@wallento: Once you've got the simulator on the master branch, I'll generate a distutils package for any shared OTBN code that it's going to depend on.

**Comment by GregAC** [comment]
Late to the party here but I will mention:

> >  make sure you only have one OpenTitan checkout

> That's the standard case, and the one we should be optimizing our usability story for.

I don't think it's a good idea to break having multiple opentitan checkouts (I often do for instance). It's ok to need something extra to make it work well but we certainly shouldn't just leave it to people to work out how to make this work. Ideally we'd have a warning pop up somewhere saying 'It looks like you have multiple opentitan checkouts, if you're working with OTBN you may need a python virtualenv setup please see the documentation here: ...' or at the very least ensure the need to do something to make multiple checkouts work is highlighted prominently in the documentation.

**Comment by rswarbrick** [comment]
I think it's probably worse than that. If someone builds a "top-level thing" that includes OTBN code, they'll be running the OTBN python.

**Comment by rswarbrick** [comment]
After sleeping on this, I think it's a proper problem.

@imphil, @wallento: I believe that your position is "People should only have one OT checkout, or they should learn to use `venv`". Is that correct?

Since this will affect anyone who needs to run OTBN tools (including people who want to run top-level simulations and don't care about OTBN internals), I think we need a more "project-wide" signoff for using packages in this way. I'd rather not be responsible for someone getting angry because they're seeing weird tool errors just before a tapeout deadline!

If I've understood your position correctly, let me know and I'll add Scott (and others?) to get a more project-wide view on things.

**Comment by wallento** [comment]
I think you are actually making the point _for_ venv as the default, which I would highly encourage:
1. The probability you crashed your computer setup with the currently encouraged global or user installation is much higher. That was what I forgot to complete above I believe: The chance you mess up your fusesoc because you installed the upstream version in another project with a tapeout approaching is much higher with a shared environment (even with one OT checkout).
2. venv is not hard to learn:
    ```
    python3 -mvenv .venv
    source .venv/bin/activate
    pip install -r python_requirements.txt
   ```
   Many IDEs, such as VSCode, will automatically enter the env when you are in the repository.

I personally have not used Python without venv for years. It is much more stable, reproducible and easier to debug. So my standpoint is actually: You can use multiple OT with multiple repos, but be aware that venv is the best way to handle Python package management anyways. Also, I don't assume that otbnsim will differ between most local copies of other devs, plus if they don't even use it in their sim, its not really an issue, is it?

**Comment by rswarbrick** [comment]
You might be right that everyone should be using `venv`, but that's not currently listed in our "how to get started" documentation and requiring it probably needs some buy-in.

The note about otbnsim isn't quite right: the simulator is going to depend on some shared, non-simulator Python. If otbnsim is installed as a distutils package, that shared Python code will also need to be a package. But *that* code is a dependency for the OTBN tooling (assembler, linker etc.) Someone building a top-level and running smoke tests will almost certainly need to assemble and link OTBN code. This is the person who I'm worried about breaking things for.

**Comment by GregAC** [comment]
Personally I'd be happy with a requirement to setup/use `venv` as part of using the repository but as @rswarbrick says that needs to be come a project wide discussion.

**Comment by imphil** [comment]
We already today have (Python) dependencies which need to match the repository version (e.g. fusesoc, compiler toolchain, etc.). If you want to switch between multiple checkouts in different states, you need to re-do the documented install steps, which include running "pip". That's not a new requirement, but probably not a very well documented one.

If you run tests, you should do so in a clean environment and run the install steps. That's what we do in CI. 

The "reinstall dependencies" solution should always work. For day-to-day work, there might be in-between solutions. Using a venv for the Python dependencies is one of them.

We should document these solutions as well as we can, but there's no way to give a "always right" solution, as we simply don't have a solution today which installs all dependencies isolated within a single directory.

**Comment by rswarbrick** [comment]
@imphil: I understand what you're saying, but I think there's a difference between a package downloaded and installed with pip on the one hand, and code that's in your checkout on the other.

I realise that we point at some "ot" branch in our `python-requirements` for fusesoc and similar, which does change over time. But that feels much less fast-moving (and maybe more monotonic!) than "the current contents of the OpenTitan directory in which I last ran pip install".

**Comment by asb** [comment]
To add my 2 cents:
* Encouraging people use venv sounds like a sensible future direction and would address this direct issue as well as other issues mentioned in this thread (e.g. the fusesoc and edalize dependencies)
* Until that move to documenting and encouraging the use of venv, requiring the installation of otbnsim is perhaps surprising given this isn't necessary for any other in-tree Python code.

I think documenting the recommended use of venv shouldn't be overly contentious. After all, people can simply ignore that advice and install packages user-local (or system-wide!) and deal with the consequences if they prefer.

If the venv guidance isn't in place before otbnsim lands in the `master` branch, my personal preference would be to start out by not requiring it be installed (matching other in-tree tools).

**Comment by rswarbrick** [comment]
For now, at least, there seems to be a de facto answer.
