### ISSUE TITLE
[otbn] Produce Design Doc

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#3073]
There has been lots of discussion and various documentation about features and requirements around OTBN. We need to bring this all together into a single design document (either bringing information into that document or referencing where it can be found).

It will focus on why particular design choices were made and how they are intended to fulfill the requirements of OTBN as opposed to the current technical specification which is a simple explanation of ISA and how to use the available features.

This will start as a document in GDrive and can become part of the published technical specification at a later date.

> estimate 16
> remaining 2020-08-21 2
> remaining 2020-09-07 8

**Comment by GregAC** [comment]
The draft is now available on the OT GDrive: https://docs.google.com/document/d/1nxvpyN4qb0-tZmqkFRSD-mGotRTLbfQA48KUOMW6PVQ/edit it's had a first pass of review and I've addressed the feedback.

Completing the document will be a long-term project. In terms of sprint tasks I think we can consider this complete.

**Comment by GregAC** [comment]
Actually there's a few minor things I should address, so leave this as 'In Progress' for now.

**Comment by imphil** [comment]
In this sprint, updated document to incorporate feedback from various stakeholders.
