### ISSUE TITLE
[aes] Security/functional cover points for DV

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#3075]
@rasmus-madsen  is ramping up his work on documenting the functional coverage methodology for OpenTitan DV. In this context, we have now started to collect security and functional cover points for the AES module in the following Google doc:

https://docs.google.com/document/d/1CNK-FX8Fq_z2D-tqiM72XX_I8ZE3sijF56Jsil02rH0/edit

The document is on the OpenTitan team drive. You have to use your OpenTitan login.

We looking for further input and feedback especially on the security side.

**Comment by vogelpi** [comment]
I am pinging our security heads @cdgori , @zi-v, @felixmiller , @moidx  but everyone is welcome to provide input!

**Comment by moidx** [comment]
I am also adding @tjaychen for security feedback.

**Comment by GregAC** [comment]
This is likely tracked by other AES DV tracking so closing. Re-open if you feel this isn't the case
