### ISSUE TITLE
meson fails to find libftdi1 even though it's installed

### ISSUE THREAD

**Issue by mauroid** [lowRISC/opentitan#3078]
Running meson_init.sh I get a fatal error about libftdi1. However the library has been installed through 'sudo apt-get install libftdi1', and can be found under ./x86_64-linux-gnu/libftdi1.so.2. I do get some more Warnings; full output and log files attached. Here are the warnigs etc and the final fatal error:

/tools/opentitan%> ./meson_init.sh 
The Meson build system
Version: 0.53.2
WARNING: Unknown options: "build.c_std, build.cpp_std"
Compiler for C supports arguments -Wa,--no-pad-sections: NO 
meson.build:72: WARNING: Consider using the built-in optimization level instead of using "-Os".
Build-time dependency libftdi1 found: NO (tried pkgconfig and cmake)

**sw/host/vendor/meson.build:5:0: ERROR: Dependency "libftdi1" not found, tried pkgconfig and cmake**

[x.out.txt](https://github.com/lowRISC/opentitan/files/5037585/x.out.txt)
[meson-log.txt](https://github.com/lowRISC/opentitan/files/5037586/meson-log.txt)

**Comment by gkelly** [comment]
The package you're looking for is `libftdi1-dev`. See `apt-requirements.txt` in the project root for all of the apt packages you'll need for development.

**Comment by mauroid** [comment]
Thank you! I did not find apt-requirements.txt mentioned in the documentation but I may have missed it.
