### ISSUE TITLE
[hw, reset_manager] combine multiples of REGEN and RST registers

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#3089]
### Observation

Currently we have the following set of `REGEN` and `RST` registers:
```
// Register write enable for spi_device reset.                                                                                                                                                 
#define RSTMGR_SPI_DEVICE_REGEN(id) (RSTMGR##id##_BASE_ADDR + 0x4)
#define RSTMGR_SPI_DEVICE_REGEN_REG_OFFSET 0x4
#define RSTMGR_SPI_DEVICE_REGEN_SPI_DEVICE_REGEN 0

// Register write enable for usb reset.                                                                                                                                                        
#define RSTMGR_USB_REGEN(id) (RSTMGR##id##_BASE_ADDR + 0x8)
#define RSTMGR_USB_REGEN_REG_OFFSET 0x8
#define RSTMGR_USB_REGEN_USB_REGEN 0

// Software reset control for spi device                                                                                                                                                       
#define RSTMGR_RST_SPI_DEVICE_N(id) (RSTMGR##id##_BASE_ADDR + 0xc)
#define RSTMGR_RST_SPI_DEVICE_N_REG_OFFSET 0xc
#define RSTMGR_RST_SPI_DEVICE_N_RST_SPI_DEVICE_N 0

// Software reset control for usb                                                                                                                                                              
#define RSTMGR_RST_USB_N(id) (RSTMGR##id##_BASE_ADDR + 0x10)
#define RSTMGR_RST_USB_N_REG_OFFSET 0x10
#define RSTMGR_RST_USB_N_RST_USB_N 0
```

By the looks of it and the description - these registers have single purpose:

- `REGEN` - "allow/disallow" peripheral to be reset.

- `RST` - "hold/release" peripheral in/from reset.

### Question

Would it be reasonable to combine these registers into a single `REGEN` and single `RST` register. It then would make it similar to what PLIC peripheral does with the interrupts - single bit for an IRQ source.

**Comment by silvestrst** [comment]
@gkelly + @lenary for visibility

**Comment by lenary** [comment]
I think there's some automatic behaviour about how `regen` registers work - which may not support compacting the register-enable bits into a single register - but I'm not sure.

**Comment by tjaychen** [comment]
yeah i think the idea was to have these registers be individually lockable from a software perspective.  So we may disable the user's ability to issue USB resets, but allow SPI resets.  And yes, I also thought that the regen registers worked on a 1-to-1 basis, and did not allow compacting. 

Is the idea behind combining them just cleaner for DIFs and not be so uniquified? Because the clocking stuff is even more unique at the moment...

**Comment by silvestrst** [comment]
> Is the idea behind combining them just cleaner for DIFs and not be so uniquified? Because the clocking stuff is even more unique at the moment...

I guess from my perspective it is slightly cleaner, but it is not a an issue, was me just wondering. Is it guaranteed that the layout of these registers won't differ (always a single purpose, and always the same offsets for all `REGEN` and also `RST` registers)?

Thanks

**Comment by tjaychen** [comment]
yes, we can re-arrange them into blocks if that's easier? Ie continuous `regen`, then continuous `resets`.
by the way, the reset manager needs to be re-templated for other design reasons, but i don't think that should impact what you have now.  

Let me know if you have other ideas on how to make this cleaner / friendlier to software.  We can definitely consider them.  It would be great also if you can have a peek at the reset management doc to see if overall this makes sense to you, and what else you might want to handle differently.

**Comment by silvestrst** [comment]
@tjaychen , thank you for your help.

Regarding continuous `regen` and `rst` registers, I think it would be cleaner to have them packed - similar to how the IRQ sources are packed for PLIC. My reasoning is:

- More consistent - same pattern for repeating 1/multiple bit enable/disable.

- It then makes it clear that, different peripheral `regen` are handled the same way. In case of separate registers, for example, `RSTMGR_SPI_DEVICE_REGEN` and `RSTMGR_USB_REGEN` it is not immediately obvious whether the register layout is always meant to be the same for different peripherals.

- There is less different register addresses to care about.

Just an opinion, I leave the final decision with you, as there might be good reasons not to pack these signals, and you are in much better position to better evaluate this.

> It would be great also if you can have a peek at the reset management doc

Could you please point me at it? I have ran `find . -name *rstmgr*` in the upstream top directory, and it didn't come up with any `.md` or `doc`. There is also no documentation or the development stage information for this peripheral in https://docs.opentitan.org/hw/ .

Thanks again @tjaychen

**Comment by silvestrst** [comment]
If we take the alert handler, it uses a single `ALERT_HANDLER.REGEN` to lock the entire peripheral (or most of it). I wonder whether Reset Manager should do the same thing, or there is a reason why there are multiple `regen` registers?

https://docs.opentitan.org/hw/ip/alert_handler/doc/index.html

**Comment by tjaychen** [comment]
ah yes the separate regwen is intentional, because the expectation is that
resets might be individually disabled.  For example, software may decide to
control a particular peripheral's reset dynamically, but disallow it on
another.
In general, i think software control of resets really should not be
allowed.  However for interfaces such as spi / usb, where the peripheral
may actually lock-up based on bad behavior from the host, it might be good
to leave an emergency exit if required.

if the regtool were enhanced such that regwen were multi-bits and each bit
can apply to one register, that would also solve this problem (i need to
check if regwen already does that).

**Comment by tjaychen** [comment]
@cdgori

**Comment by silvestrst** [comment]
For the reference, I have a DRAFT DIF Reset Manager PR open in #3093 . Awaiting some header sanity checks from Sam and Garret, and then will do the corresponding changes and promote it to a full PR.

**Comment by lenary** [comment]
Let's land something with the current register layout, this is an optimisation for later.

**Comment by tjaychen** [comment]
@silvestrst 
just wanted to circle back to this one.  If you prefer, I think I can combine these into one register as you asked.  Just let me know.

**Comment by silvestrst** [comment]
@tjaychen 
Unless there is a good reason not to, I would prefer them combined, thanks!

**Comment by tjaychen** [comment]
let me have a look today. I think i can still actually achieve the
individual controls by combining.

**Comment by tjaychen** [comment]
This should be supported now.  Please give it a try and let me know.

**Comment by tjaychen** [comment]
okay looks like there are a few issues.

Since rstmgr is a templated module, the target inside `meson.build` needs to be changed.  However when i update that, the C-header generation then breaks.  I haven't look into that part yet.

**Comment by tjaychen** [comment]
okay please see #3602 
the rstmgr difs now need some updating :)

**Comment by silvestrst** [comment]
@tjaychen apologies for leaving this PR hanging. I will try to fixup the DIF appropriately today.

**Comment by cdgori** [comment]
Sorry for not reading this chain until now.  Your comment

> In general, i think software control of resets really should not be
allowed.  However for interfaces such as spi / usb, where the peripheral
may actually lock-up based on bad behavior from the host, it might be good
to leave an emergency exit if required.

matches my expectations / preferences perfectly, since having parts of the device in reset while others are not is usually not desirable (except for the absolutely necessary recovery/emergency exit sequences).
