### ISSUE TITLE
[otbn] What should we do on out-of-range memory accesses?

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#3094]
If we execute
```
LW x1, 0(x2)
```
and `x2` is enormous, or we execute something like
```
LW x1, 0x1000(x0)
```
(where "0x1000" is some constant bigger than DMEM), what should we do?

I think we have two options:
1. Spot the out-of-range access, issue an alert and come to a screeching halt.
2. Wrap the address (so `<addr> = (<offset> + <grs1>) & <mask>`)

Option 1 seems "obviously right", and might catch some silly bugs that would lead to security holes. Option 2 might be cheaper to implement because you don't need a 32-bit adder. It might also allow some clever addressing tricks, but I'm not sure. Option 2 is not possible if DMEM isn't a power of 2 bytes long.

I'm leaning towards option 1, but think we need to make a proper decision about it.

Obviously, the same questions go for `sw`, `bn.lid` and `bn.sid`.

There's a similar question about branch targets, but there I think the answer is more obviously "Option 1, duh!".

@felixmiller, @wallento, @imphil, @GregAC, @tomroberts-lowrisc, @sydgibs: Any thoughts?

**Comment by GregAC** [comment]
I'd also agree with 1.

Pending our discussion on what we do on errors 1. could always change into 'issue an alert but carry on anyway as if the operation succeeded'

I'd note on the adder cost we're likely using the main narrow side ALU for address calculation anyway so I don't think that's a factor.

**Comment by tjaychen** [comment]
just chiming in, i'm not sure 1 necessarily needs to trigger an alert. Couldn't this just be a software error? I think it's reasonable to have this propagate to an alert if configured, but otherwise I feel like an otbn halt combined with some error status for the host cpu seems more reasonable.

**Comment by GregAC** [comment]
Ah yes I forget alert has a particular meaning, by alert I was meaning whatever we choose to do in OTBN to indicate an error.

**Comment by cdgori** [comment]
Another vote for option 1 here (@GregAC thanks for confirming the address calculation adder is likely available).

> Pending our discussion on what we do on errors 1. could always change into 'issue an alert but carry on anyway as if the operation succeeded'

From my perspective "carry on anyway" is almost never going to be correct here - this condition should mean something is very wrong and we should stop/halt + propagate error status to Ibex.

Option 1 is even more clear to me for branch targets, as @rswarbrick 's  intuition seems to be guiding him :)

**Comment by wallento** [comment]
Also from a certification perspective cleary option 1

**Comment by rswarbrick** [comment]
Cool, sounds good! I'll push up a documentation PR next week to make it clear this is how things work.
