### ISSUE TITLE
[otbn] Should we add one to the iteration count in `loop` and `loopi`?

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#3102]
As currently specified, the `loop` and `loopi` instructions take an iteration count (from a register or immediate, respectively). This is treated as an unsigned number, but there's a note that the count must be positive. We could just "add one", so that e.g.
```
LOOPI 2, 0
ADDI x1, x2, x3
SUBI x2, x3, x4
```
does the addition and subtraction once. (`LOOPI 2, <n>` would do it `n+1` times.)

My guess is that this will have a negligible effect on the design itself, but it gets rid of a class of undefined instructions, which makes the spec simpler.

A disadvantage is that it might be confusing for programmers (because "LOOPI a, b" no longer means "do something b times"). It might also be a problem for code using `LOOP`: would the code that currently uses it need to subtract one?

@felixmiller, @wallento, @imphil, @GregAC, @tomroberts-lowrisc, @sydgibs: Thoughts?

If we decide not to change the spec, I think we should add a note to it explaining why ("You might think that ... would be a good idea, but no! In fact..." etc.)

**Comment by rswarbrick** [comment]
Of course, another way to simplify the spec would be to allow zero counts (which just skip the loop body). I know that's a bad idea for pipelined designs, because it's a conditional branch so somewhat negates the advantage of the zero-overhead loop in the first place. OTBN, won't be deeply pipelined, though. Maybe we should just allow them?

**Comment by GregAC** [comment]
I don't think allowing zero counts would be a big issue. Currently we only have a single stage, so there's no stalls around branches (branch computes next instruction address, presents to IMEM, data available next cycle which is immediately decoded and executed straight off the memory output). Perhaps we will adjust his design once we've seen some timing results (or indeed when we start actually implementing branches!) so you will get a stall cycle around branches but I suspect that a zero count loop isn't something you're going to see much/any of in real code so the impact of the extra stall cycle shouldn't be a problem.

**Comment by wallento** [comment]
I think especially for `loopi` it is probably what could be intended (zero iteration loops), right? People could live with the stall cycle then for it I agree

**Comment by rswarbrick** [comment]
@GregAC: Just making sure I understand what you're saying. For code like this:
```
A

loopi 2, 2
B0
B1

C
```

I *think* you're saying we'll compute things on the following cycles:

| Insn | Cycle
|-|-|
| A | 0
| LOOPI | 1
| B0 (1) | 2
| B1 (1) | 3
| B0 (2) | 4
| B1 (2) | 5
| C | 6

where we do the branch calculation as part of setting up the world for `loopi`, and then have a true zero-overhead-loop for the tail (after `B1`). Is that what you're imagining?

**Comment by GregAC** [comment]
Well we have yet to implement `loop` but that is how I'd anticipate it working. For a 0 iteration loop we may end up with:

| Insn | Cycle
|-|-|
| A | 0
| LOOPI | 1
| *stall* | 2
| C | 3

Where the *stall* from the branch can get hidden in another instruction where we actually execute a loop body.

**Comment by rswarbrick** [comment]
Ok, that makes sense. I'll make a PR that removes the "no zero counts!" message from the documentation. If it turns out to be needed in future, we can always add it back, but I think it's better to avoid the gotcha if we can.
