### ISSUE TITLE
[OTBN] Produce random instruction generation framework

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#3106]
We require a method to generate random instructions for OTBN Pre-DV

Issue comprises the following tasks:

- [x] Basic instruction generation
- [x] Instruction generation for all of RV32I except branch
- [ ] Instruction generation for all remaining instructions (branch, loop)

> estimate 24

> remaining 2020-08-21 8
> remaining 2021-01-22 1

**Comment by rswarbrick** [comment]
Basic instruction generation was merged as #3140.

**Comment by rswarbrick** [comment]
Generation for all of RV32I except for the CSR instructions will have been implemented once #3181 is merged.

**Comment by rswarbrick** [comment]
**Update:** Everything is now done (and merged) except for LOOP/LOOPI support. I've got that working locally and it should be merged early next week.
