### ISSUE TITLE
RFC: Add partial support for AES-GCM in hardware

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#3113]
AES-GCM is a mode of Authenticated Encryption with Additional Data (AEAD) used by applications planned to run on OpenTitan. Integrity is achieved by using a GHASH function based on a Galois Field (multiplier)  as described in [NIST 800-38D](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf). 

This RFC discusses hardware and software implementation options for GCM mode support in OpenTitan. 

The discussion is currently being tracked here:

https://docs.google.com/document/d/1qvWcmVA3CjvGu8JFV8AihcXz00FcxFEQQwAWCr-IB_U/edit?usp=sharing

**Comment by moidx** [comment]
@vogelpi, @tjaychen, @cdgori, @felixmiller, @gkelly, @alphan PTAL

**Comment by gkelly** [comment]
@lenary for visibility.

**Comment by moidx** [comment]
Status update: 

@vogelpi is in the process of finalizing a hybrid (sw/hw) implementation proposal, aiming to minimize bus interactions. The proposal will be integrated into the RFC document.

We are also finalizing hardening requirements.

**Comment by vogelpi** [comment]
Update, I have added the following to the doc:
- a hybrid HW/SW implementation proposal,
- a SW-based approach using the carry-less multiplier instructions available in the RISC-V Bitmanip ISA Extension, 
- synthesis results for our GF multiplier with different latencies
- area estimates for hardening this GF multiplier with different 1st order masking schemes (boolean, DOM, multiplicative).

**Comment by rasmus-madsen** [comment]
Pirmin just brought this change to my attention.
I am currently in the process of reviewing the implementation suggestion in the document in order to come up with a good estimate on the DV effort needed.

**Comment by vogelpi** [comment]
Update: Rasmus had a look at the proposal and based on his feedback, we added another paragraph on verification of the proposed hybrid implementation.

**Comment by moidx** [comment]
Resolved remaining comments, thanks @vogelpi and @rasmus-madsen for closing the loop on DV feedback.

@sjgitty, @asb, the document is ready for final TC review. 

Thanks!

**Comment by sjgitty** [comment]
The Technical Committee has met and discussed this RFC. At this time, the TC is requesting a few revisions that we're sending back to the author(s). I will move back to `RFC:Proposal` state for now, @moidx please return to `RFC:TC Review` once those are addressed and the TC we review again.

**Comment by vogelpi** [comment]
Update: I have added estimates for the expected design and verification effort, as well as a performance comparison of the hybrid vs. the software option.

There are still some questions to be answered around security recommendation and product requirements (security and performance).

**Comment by gkelly** [comment]
Just following up on this issue, are we planning on continuing the investigation here or do we have a final answer about the inclusion of AES-GCM?

**Comment by imphil** [comment]
@moidx Is this RFC still relevant? (I don't think so.)

**Comment by moidx** [comment]
Hi @imphil, I agree we can close this. He have moved to consider an implementation in software leveraging bitmanip instructions.
