### ISSUE TITLE
[toolflow/Fusesoc] conflicting requirements

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#312]
in extension to https://github.com/lowRISC/opentitan/issues/300
after the issue I did a hard reset of master,
then I pull upstream and pushed to origin.

when I try to run the uart sanity test I get this message
![image](https://user-images.githubusercontent.com/53917183/66044592-2e4da500-e522-11e9-90c8-7e9de7161ef5.png)

Other on WDC side has seen this issue, sometimes we have been able to recover using
`git checkout tests`

but this is not always the case.
I can do another hard reset and that resolves the issue. but I rather figure out what is causing this issue.

**Comment by imphil** [comment]
Assuming this is working now, please re-open if that's still an issue.

**Comment by camaabdo** [comment]
Hello,

I need help with this problem. I am working on a student project in my last year of school. When I try to run FuseSoC with the open titan platform, I have this problem appear, and my work tree is clean.
<img width="965" alt="image" src="https://user-images.githubusercontent.com/55259057/145564406-e90bccc4-db58-41b3-9fe9-9fba6d398774.png">


Thanks for your help

**Comment by rswarbrick** [comment]
This probably means you are using the wrong version of fusesoc (see the install guide: you need a special "OpenTitan" flavour). If you can't get things working, please open a new issue on the repository and someone should be able to help you.
