### ISSUE TITLE
[pwrmgr] Generate a C header of connected wakeups  and reset requests

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#3138]
similar to plic / pinmux, we should generate a C header with information on what wakeups / resets are connected to the power manager.

**Comment by lenary** [comment]
I shall try to fold this into my work on https://github.com/lowRISC/opentitan/pull/2975

**Comment by lenary** [comment]
I've managed the first half of this (wakeups). I don't know how to deduce the structure of the resets.

**Comment by tjaychen** [comment]
o thanks! sorry don't worry about the resets yet, since it is not yet even done in the design. 
once i do the reset hook-ups in the design, I can maybe follow the example of your work and add resets?

**Comment by lenary** [comment]
Sure! I'm going to file an issue for the bits that #2975 doesn't do, and I don't mind who implements it.
