### ISSUE TITLE
[dv/top_level] Enable `AonWkupReqKnownO_A` assertion

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#3158]
Pinmux has an assertion to ensure that `AonWkupReqKnownO` is not X.
However `spi_device.sdi_i` could be X if simply means no input data.
If `wkup_padsel` selects the SDI signal, which is connected to MIO input `IO_DPS1` if `jtag_en=0`.
Since pinmux will be re-write soon, we temp disabled this assertion in PR https://github.com/lowRISC/opentitan/pull/3156. 
Needs to remove this temp disable once the Pinmux is re-written.

**Comment by msfschaffner** [comment]
@cindychip can this be closed?

**Comment by cindychip** [comment]
PR merged, close it
