### ISSUE TITLE
[doc/dv] Revisit "Pending Work Items" section in DV methodology doc

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3169]
https://docs.opentitan.org/doc/ug/dv_methodology/#pending-work-items mentions "Provide ability to run regressions" as "Pending Work Items". We do have the ability to run regressions, and do so. 

Under "Testplan", there's a bullet point "this feature is not yet available and is under active development", linking to the "Provide ability to run regressions" section. I'm not sure if we have implemented everything envisioned in this paragraph, but it needs at least a bit of clarification.

@sriyerg

**Comment by sjgitty** [comment]
Given that lots of stuff is stacking up on @sriyerg's plate, wondering if @cindychip @weicaiyang or @udinator could take a stab at writing these up, and just have @sriyerg review them?

**Comment by sriyerg** [comment]
The DV methodology doc does need a significant amount of refactoring. I (or one of the others) will try to get it in within the next two weeks.

**Comment by msfschaffner** [comment]
@sriyerg is there still something to do here or can this be closed?
