### ISSUE TITLE
[otbn] Implement/evaluate modular add/sub for p384

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#3191]
The current implementation of the p256 curve heavily uses the `addm` and `subm` pseudo instructions. These instructions are not available for numbers wider than `WLEN`.

Come up with a proposal for HW support for addm/subm for 384 bit wide numbers.

Split out of #2982

Depends on addition code in P384, tracked in #2982

**Comment by felixmiller** [comment]
Here is some typical example code to continue this discussion:

P-256 quantities are represented as single limb 256-bit wide numbers and a typical "pseudo" modular add is:
`addm w1, w2, w3`
This implements `w1 <= w2 + w3 mod MOD` where `MOD` is the contents of the MOD WREG.

In the current microarchitecture, P-384 quantities are represented as dual limb numbers, occupying a full 256-bit reg and 128 bit of a 2nd reg.

The `addm`, `subm` instruction actually perform three steps in a single instruction:

1. addition / subtraction
2. comparison with subtraction / addition of modulus
3. selection of result of (1) or (2)

Essentially this performs:
```
add w1, w2, w3
sub w4, w1, w5
sel w1, w1, w4, C
```
here `w5` is assumed to contain the modulus.

For a P-384 version this becomes 6 instructions:
```
/* [w7, w6] <= [w1, w0]+[w3, w2] mod [w5, w4] */
bn.add    w6, w0, w2
bn.addc   w7, w1, w3
bn.sub    w8, w6, w4
bn.subb   w9, w7, w5
bn.sel    w6, w6, w8, C
bn.sel    w7, w7, w9, C
```

**Comment by felixmiller** [comment]
Given the first results from P-384 signature generation it seems less likely that we will do anything about this.

**Comment by imphil** [comment]
Not necessary at the moment.
