### ISSUE TITLE
BN.MULQACC arguments inconsistent in documentation and snippets in sw/otbn

### ISSUE THREAD

**Issue by sydgibs** [lowRISC/opentitan#3201]
https://github.com/lowRISC/opentitan/blob/aa8ed45826b570acf2b9716b9dc3895ced45325a/sw/otbn/code-snippets/modexp.S#L17

The `BN.MULQACC` instructions in this snippet are inconsistent with the current documentation, which gives the acceptable range of values for the `acc_shift_imm` argument as `0..3`. This snippet appears to implement an instruction that takes the number of bits to shift the result by, rather than the number of quarter-words.

**Comment by rswarbrick** [comment]
Nice catch, thanks! This is a bug in the documentation: the assembler follows the RISC-V assembler so things that are encoded with a shift get their "shifted" values in the assembly. I'll try to fix it today.

Note to self: Need to add the shift to `ImmOperandType.markdown_doc` in `operand.py`.

**Comment by rswarbrick** [comment]
The linked PR should fix things, I think. The documentation will now look like this:

![ss](https://user-images.githubusercontent.com/104845/90786617-af10bd80-e2fb-11ea-9adf-779a9d1c60c3.png)
