### ISSUE TITLE
[top-level DV] Framed bootstrap data

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#3203]
I'm trying to load flash data from SPI for bootstrap in DV simulation, instead of backdoor loading data. We have the raw data but SW requires framed data with header.

Current [spiflash](https://github.com/lowRISC/opentitan/tree/master/sw/host/spiflash) generates bootstrap framed data for Verilator and FPGA. Can we add a function to provide converted data for DV sim? Perhaps take the file that contains raw data as input and output file with converted data.

**Comment by moidx** [comment]
Hi @weicaiyang, this sounds possible. How are you planning to send the frames and check for the response? Are you planning to add a c wrapper on your test bench?

**Comment by weicaiyang** [comment]
> Hi @weicaiyang, this sounds possible. How are you planning to send the frames and check for the response? Are you planning to add a c wrapper on your test bench?

@moidx 
We will use a SPI host to drive the frames. SPI host is part of UVM TB, so no C wrapper is needed.
I'm thinking to just send a frame and then wait for a long period to send another frame as well as checking the frame number matching to previous one. Probably not to test all kinds of error handling in SW. WDYT?

**Comment by moidx** [comment]
I think that would work.

You'd have to setup some dependencies in meson to build the spiflash binary, the target binary you want to download, and then set all of that into a dependency of your test. 

@sriyerg, @gkelly, are you guys ok with this approach? If so, I can add a new option to spiflash to dump a binary with the frames required to drive the test bench. 

Thanks!

**Comment by weicaiyang** [comment]
> I think that would work.
> 
> You'd have to setup some dependencies in meson to build the spiflash binary, the target binary you want to download, and then set all of that into a dependency of your test.
> 
> @sriyerg, @gkelly, are you guys ok with this approach? If so, I can add a new option to spiflash to dump a binary with the frames required to drive the test bench.
> 
> Thanks!

Sounds good. Thanks

**Comment by sriyerg** [comment]
If I understand this correctly, for this particular test, the meson build invocation will not only generate the existing embedded targets, but also the spiflash compliant binary (with the help of an additional dependency). If yes, then this sounds great to me!

**Comment by weicaiyang** [comment]
Done at #3218
