### ISSUE TITLE
RFC: Key sideload scheme

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#3204]
## Objective

The objective of this RFC is to collect feedback on sideload architecture options, and decide what level of 
support to implement in the key manager integrated into Earl Grey. 

The RFC is currently in open for comments. Once a consensus has been reached, the RFC will be updated with the
design decision before promoting it to the Technical Committee for final review.

## Background - What is Sideload?

Sideload, or key manager sideload, refers to a direct hardware connection from the OpenTitan key manager module to hardware symmetric crypto components for supplying keys.

When sideload is employed, keys are generated within the key manager and fed directly to the hardware crypto components for usage.  At no point during this process are the keys exposed to software.  Thus, compromised software can only abuse the keys but cannot permanently expose them [see doc for more details][no-sideload-proposal].

## Design Options

Currently, there are a couple of proposals under consideration. As part of this RFC, we are requesting inputs for 
additional proposals.

### Key slot implementation

The implementation may provide a limited number of key slots in the key manager, with support for sideloading keys into the
`HMAC`, `KMAC`, and `AES` engines. The number of key slots is left as an implementation detail which needs
to take into consideration tradeoffs between: use cases versus hardware cost.

Additional considerations:

*   Even though software does not have visibility into the key material, it is still responsible for managing the key slot
     mapping to consuming applications.
*   The number of bits sideloaded to other IP may be constrained to meet a security level up to 256 bits.
*   Sideloading keys into `OTBN` is not considered a security feature given that the target does not implement
     isolation of critical data from software. The current recommendation is to avoid sideloading into `OTBN`.

### No-Sideload Support

Given the limitations of the key-slot proposal above, and additional considerations, we have put together a justification
to remove support for sideloading from the architecture. 

See the [proposal document][no-sideload-proposal] for more details.

[no-sideload-proposal]: https://docs.google.com/document/d/1kTh5E9wgD-X1eQSX3h-67tFvcmHTjjo7ng5bZKYIA-E/edit?ts=5ee97acc#

## Update
See [sideload memo](https://docs.google.com/document/d/1BVxsA6-19eUuempvtiv136LH8Z0GLnc5cpapmk0H1uw/edit?usp=sharing) for the latest thinking and proposals.

The ongoing [key manager update deck](https://docs.google.com/presentation/d/1noUFDWAHlcz5zHByuav6I9z7HrNM3hsiyYwmi2z7N3s/edit?usp=sharing) also details the matching hardware updates for key manager only.

**Comment by moidx** [comment]
PTAL @sjgitty, @tjaychen, @felixmiller, @cdgori, @vogelpi, @gkelly, @eunchan, @zi-v, @cyrilguyot

**Comment by mateenfaisal** [comment]
@moidx - what is the decision on the key sideload scheme?

**Comment by moidx** [comment]
Hi @mateenfaisal, this is pending feedback from reviews. Expect this to close in 2-3 weeks.

**Comment by mateenfaisal** [comment]
@felixmiller to start looking at keysideload this week.

**Comment by imphil** [comment]
@tjaychen I think we have a complete sideload proposal now? Can you link it here? And it would be good to get that bubbled up to the technical committee as well, since the TC has been talking about key sideload in the past. Let me know when it's ready and I'll add it to the TC agenda.

**Comment by imphil** [comment]
The keymanager has been updated with the outcome of the chosen sideload approach, and the sideloading is also being implemented in other IP blocks, such as OTBN. Let's close this issue, since there are no real open questions around the fundamental workings of key sideload any more.
