### ISSUE TITLE
RFC: Identities and Root Keys

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#3212]
Request for comments for the Identities and Root Keys Specification. 

The specification describes the composition of the Silicon Creator and Silicon Owner
identities and the Silicon Owner root key derivation scheme. This scheme is based
on a symmetric key manager with support for software binding and key versioning.

This document also defines a non-cryptographic Device Identifier to facilitate
silicon tracking during manufacturing flows. The Device Identifier is also mixed
into the Creator Identity.

Critical comments for the [google doc version](https://docs.google.com/document/d/1Q78pufgGr79K8hxLUXVTB_y1IRrykUfvo0m2-1F8QeY/edit#) of the document have been resolved, and PR lowrisc/opentitan#3136 is now under review. 

Any outstanding opens will be logged as GitHub issues and incorporated in a follow up revision of the document.

**Comment by sjgitty** [comment]
The technical committee has reviewed this RFC and approved it. We expect it will still undergo minor revisions over time, but are content with the level of review so far, and the direction. If it does undergo major changes please re-request review. I am marking it as approved with the tagging process.

**Comment by moidx** [comment]
Thanks @sjgitty. Committed initial version in PR lowrisc/opentitan#3136.
