### ISSUE TITLE
[shadow_reg] standardize shadow_reg's storage error status?

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#3232]
As @sriyerg suggested in PR: https://github.com/lowRISC/opentitan/pull/3163 - 

I just copied the discussion over here:

AES status register has one field for shadow_reg's storage error. Can we standardize shadow_register's storage error in all modules? 
If yes, then DV engineers can automate shadow_reg_storage_err_post_write() rather than maintain it manually.

Reply from @vogelpi:
"We do this in aes but it is not standardized at the moment. But it's a good idea, I think this would be generally useful. However, status registers are very module dependent and I am wondering how we could standardize this status bit. Should there be one bit per module collecting all storage errors? Potentially, there could be multiple shadow registers per module."

**Comment by vogelpi** [comment]
Thanks for opening the issue. Also the idea about handling this similar like interrupts (and the added benefits for testing) sounds great! I don't know when I get around to do this though. But it's now on my list.

**Comment by msfschaffner** [comment]
@vogelpi @cindychip can you upodate this issue?

**Comment by vogelpi** [comment]
I think adding a standardized shadow reg status register is out of scope at the moment. The current status is that we have standardized the way of indicating the alerts triggered by the shadow register in the hjson, but not the corresponding status register.

Loooking at some IPs using shadow registers it seems that AES and KMAC both have a status register with one bit per alert. KeyMgr has two seperate error status bits for storage and update error as well but they are located in different registers. For the alert handler I am not sure: If I understand the spec correctly, it update errors are visible in LOC_ALERT_CAUSE_5 and storage errors in LOC_ALERT_CAUSE_6. So there seems to be the 1:1 relationship also here and we could probably just add a tag to specify the status bit in the hjson (just like we do for specifying the alert name). WDYT?

**Comment by msfschaffner** [comment]
@cindychip @sriyerg do we still plan to work on this infrastructure for DV, or can we defer this?
At least on the RTL side, I don't think we can make any alignments anymore due to the churn this would incur.

CC @tjaychen

**Comment by sriyerg** [comment]
I just went through the comments to jog my memory. The issue was filed to explore if the alerts fired due to various reasons could be wired up to a status CSR, which would help develop standardized and automated tests. This will need tooling, RTL and DV infra to be built, which seems infeasible. We should close this issue.

**Comment by msfschaffner** [comment]
Yeah let's close this then.

I remember we had discussed a standardization of status bits (including alerts) a while ago, but dismissed that since it would cause significant reorganization of CSRs in several IPs.
