### ISSUE TITLE
[OTBN] How to handle memory errors within the OTBN CPU

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3238]
How should we handle errors from the instruction and data memory when they are accessed from within the OTBN CPU? We know that we need to raise an alert (and have [documented this behavior](https://docs.opentitan.org/hw/ip/otbn/doc/index.html#hardware-interfaces)), but what else should we do? 

- Continue somehow (e.g. with dummy data or dummy instructions?)
- Halt the CPU?
- Retry? How often?

What can we expect to happen after an alert is raised? 
- Is OTBN reset immediately?
- Can the alert system decide to let it go on?

@cdgori @GregAC @felixmiller @moidx

**Comment by imphil** [comment]
This issue is being addressed as part of #4318: All memory errors are considered fatal, there's no retrying, but terminate the operation immediately and alert.

**Comment by rswarbrick** [comment]
I think this is done, since we've documented (a) behaviour and implemented it. If we see any further problems, let's open a new issue.
