### ISSUE TITLE
[otbn] Implement alert when popping an empty call stack

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#3239]
~~Should this have a pre-defined value (0, maybe)? Or should it raise an alert?~~

We've agreed to raise an alert. Implement this in spec, ISS and RTL.

> estimate 2

**Comment by felixmiller** [comment]
I tend more towards an alert here. If this happens it means that integrity is violated, in a non-correctable way (or there is a SW bug). I think therefore we should follow the same strategy as with detection of CFI violation.

Maybe lets here @cdgori thoughts on this as well.

**Comment by rswarbrick** [comment]
Now documented and implemented in ISS. Still to do in RTL.

**Comment by GregAC** [comment]
All OTBN errors will now trigger alerts, so this is no longer relevant
