### ISSUE TITLE
RFC: Attestation 

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#3254]
Request for comments for the Attestation specification. 

Attestation is the mechanism in which software verifies the authenticity and integrity of the hardware and software of a device.

Critical comments for the [google doc version](https://docs.google.com/document/d/1EADg4C3-ywEL89Zks6dCAiNbf2Cv3TOlVfGvETOsu4g/edit?usp=sharing) of the document have been resolved, and  PR lowrisc/opentitan#3233 is now under review.

Any outstanding opens will be logged as GitHub issues and incorporated in a follow up revision of the document.

**Comment by sjgitty** [comment]
The Technical Committee has reviewed this proposal and has decided to Approve the RFC. Please re-tag for review if major changes are considered. I will change the tag to indicate approval.

**Comment by moidx** [comment]
Closed by PR lowrisc/opentitan#3233
