### ISSUE TITLE
RFC: Ownership Transfer

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#3265]
Request for comments for the Ownership Transfer specification, covering ownership assignment flow.

The Silicon Owner is defined as a logical entity or entities allowed to sign code for execution, as well as to sign ownership management commands. OpenTitan supports the following device life cycle states to manage the ownership state of the device:

*   _UNOWNED_: The device is ready to be assigned to a new owner.
*   _OWNED_: The device is assigned to an owner and in operational mode.

The document defines the ownership management functions that control the transitions between ownership states.

Critical comments for the [google doc version](https://docs.google.com/document/d/1M2qRL99kxo_dJj4b9nuGGC32lg_qrsxidVtCtFP3NMg/edit?usp=sharing) of the document have been resolved, and PR lowrisc/opentitan#3264 is now under review.

Any outstanding opens will be logged as GitHub issues and incorporated in a follow up revision of the document.

**Comment by sjgitty** [comment]
@moidx I think there will be discussion about how much review the Google Doc has received. There isn't comment history to rely upon.

**Comment by moidx** [comment]
Hi @sjgitty,  @felixmiller, @gkelly and @domrizz0 should have access to the version of the document we used to receive comments. I hope they can provide feedback. I didn't copy the comments to the public doc given that the original version had some sections that were cert-sensitive classified.

**Comment by sjgitty** [comment]
The Technical Committee reviewed this proposal but did not have enough time to complete the review, and will thus leave it in `TC Review` status. We will attempt to complete the review within the next two weeks.

**Comment by asb** [comment]
The Technical Committee reviewed this day, and all outstanding questions have been answered since the last meeting, meaning the TC have now voted to approve this RFC. I've updated the issue labels accordingly.

**Comment by moidx** [comment]
Closed by lowrisc/opentitan#3264
