### ISSUE TITLE
[otbn] optimize register usage for Barrett reduction

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#3267]
The[ code snippet](https://github.com/lowRISC/opentitan/blob/8d78d9be15924ed2b2486a6b57e9d2efbfa7d388/sw/otbn/code-snippets/barrett384.S) for 384 bit modular multiplication (currently in [this](https://github.com/lowRISC/opentitan/pull/3257) PR) via Barrett reduction consumes quite some temporary registers. Naturally it consumes more than the 256 bit variant, since it requires two regs to store a single number.
However, it can probably optimized by changing the order of how temp regs are accessed there.

**Comment by rswarbrick** [comment]
@felixmiller: Did you ever look at this? Looking at the git blame for the list of clobbered flag groups in `barrett384`, I think not? Is it worth keeping on our todo list?

**Comment by msfschaffner** [comment]
@jadephilipoom @GregAC is this still relevant?

**Comment by jadephilipoom** [comment]
I don't think this is relevant any more; in fact, we don't even use Barrett reduction for P384 any more. There's still a code snippet that shows it, but it's only an example OTBN program and to my knowledge nothing actually calls it.
