### ISSUE TITLE
[otbn] Produce multiply-routine generation script

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#3269]
`MULQACC` can be used to produce arbitrary width multiplies, however it's tedious to write the most efficient code by hand. A simple python script could be given operand sizes and produce specific routines for them (e.g. a 128x384 bit multiply if such a thing was desired).

> estimate 4

**Comment by msfschaffner** [comment]
CC @rswarbrick @jadephilipoom

**Comment by rswarbrick** [comment]
Honestly, I don't think this is worth building at the moment. Maybe it makes sense to look at what we've got (handwritten) and try to auto-generate it in future. But I'm not sure we need to track this as an issue any more. Does this make sense, @jadephilipoom? (I think you're the most likely to think about it)

**Comment by jadephilipoom** [comment]
We already have it! I didn't realize this issue existed, but it was fixed by https://github.com/lowRISC/opentitan/pull/12591 last year.

**Comment by rswarbrick** [comment]
Oh, brilliant! Oops, and it turns out that I even reviewed that PR :-D
