### ISSUE TITLE
[OTBN] Specify shift amounts always in bit?

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3271]
We now specify most shift amounts in bit, also in cases where not all possible bit values are valid. For BN.SUB and friends we still specify the shift amount in bytes, and have the `B` suffix to indicate that in the assembly. 

Should we, for consistency, also switch the shift_bytes fields to bit shift amounts, and remove the `B` suffix from the assembly? 

> estimate 2

**Comment by rswarbrick** [comment]
I like that idea.

**Comment by GregAC** [comment]
I'd be in favour of shift amounts in bits everywhere.

**Comment by felixmiller** [comment]
same for me
