### ISSUE TITLE
fusesoc/DV/VCS issues on CentOS 7 - and possible fix

### ISSUE THREAD

**Issue by svenka3** [lowRISC/opentitan#3297]
Hi,
  Thanks for this good reference. Kudos to the team!

On CentOS7, I am trying to run OpenTitan (OT) HW simulations with VCS. I follow the instructions including the "pip3 install --user -U -r python*.txt" (i.e. -U related issue, reported by others here).

My fusesoc still fails (version checked). With some digging I see it gets an empty RAL_MODEL_DIR.

I see that fusesoc.mk needs this variable.
But no other setup/script seems to set this variable. 

So below is what I use now and it seems to work (Also needed TOOLS_SRCS_DIR, though minor)

Please comment if RAL_MODEL_DIR is to be handled elsewhere (I did grep -R and could not find it).

Thanks
Srini

-- vw_setup.csh --

setenv REPO_TOP `pwd`
setenv RAL_MODEL_DIR ${REPO_TOP}/hw/dv/
setenv TOOL_SRCS_DIR ${RAL_MODEL_DIR}/tools/vcs/

**Comment by rswarbrick** [comment]
I'm not quite sure what's going wrong for you. Please could you post the exact command you ran, together with the output?

**Comment by svenka3** [comment]
Thanks @rswarbrick for timely response. To run, I read:

https://docs.opentitan.org/doc/ug/getting_started_dv/

And did:
```

cd hw/ip/aes/dv
make
```

And below is what I see as commands transcript:

```
mkdir -p /home/srini/proj/vworks/OT_fsoc/opentitan/hw/ip/aes/dv/scratch/aes/default && \
env > /home/srini/proj/vworks/OT_fsoc/opentitan/hw/ip/aes/dv/scratch/aes/default/env_vars
cd /home/srini/proj/vworks/OT_fsoc/opentitan/hw/ip/aes/dv/scratch/aes/default && fusesoc --cores-root /home/srini/proj/vworks/OT_fsoc/opentitan/hw/dv/tools/../../.. **--cores-root**  run --target=sim --setup lowrisc:dv:aes_sim:0.1

```
Especially notice the "empty string" after second **--cores_root ** option, this makes fusesoc confused and I get:


```
usage: fusesoc [-h] [--version] [--cores-root CORES_ROOT] [--config CONFIG]
               [--monochrome] [--verbose] [--log-file LOG_FILE]
               {build,init,pgm,fetch,core,list-cores,core-info,gen,list-paths,library,run,sim,update,dep}
               ...
fusesoc: error: invalid choice: 'lowrisc:dv:aes_sim:0.1' (choose from 'build', 'init', 'pgm', 'fetch', 'core', 'list-cores', 'core-info', 'gen', 'list-paths', 'library', 'run', 'sim', 'update', 'dep')
make: *** [gen_sv_flist] Error 2



```

Luckily I had an older version of OT (OpenTitan) without these recent RAL_MODEL_DIR stuff, and did a diff on fusesoc commands to isolate - error from fusesoc wasn't useful to isolate the issue, unfortunately. 

I am not sure what the correct value for RAL_MODEL_DIR should be BTW, it worked with a hack, perhaps you can suggest better one here.

Regards
Srini

**Comment by rswarbrick** [comment]
Ahah! Now I see what's going wrong. A few months ago, we changed how we run tests, moving from a Makefile based flow to a script called "dvsim.py". It seems that we missed updating some of our docs to match (oops). That's being done now (in PR #3309).

In order to run the AES tests with the VCS simulator, you can run the following command:
```
./util/dvsim/dvsim.py hw/ip/aes/dv/aes_sim_cfg.hjson --tool vcs
```

The `--tool vcs` bit is needed because the default simulator for AES tests is Xcelium (I think because the DV work has mostly been done by engineers at Western Digital, who use Xcelium as their main simulator).

**Comment by sriyerg** [comment]
Hmm, I will try to prioritize and get rid of the Makefiles to avoid this confusion.

**Comment by sriyerg** [comment]
@svenka3, please close if this is resolved.

**Comment by sriyerg** [comment]
https://docs.opentitan.org/doc/ug/getting_started_dv/ 
is now updated to reflect the right command to run the simulations.

**Comment by svenka3** [comment]
@sriyerg Yes, resolved, will close this issue. Thanks
