### ISSUE TITLE
FSDB Dumping choice in OpenTitan

### ISSUE THREAD

**Issue by svenka3** [lowRISC/opentitan#3298]
My preference is to actually move the `$fsdvDump*` system calls to a SV code instead so that we can get rid of the tcl files (we will retain the per-tool tcl file for other tool-specific sim controls). The benefit of that is allowing run-time control of how to dump stuff via plusargs (which is tool agnostic). I am researching a bit on this - will get back with a prototype.

_Originally posted by @sriyerg in https://github.com/lowRISC/opentitan/issues/2422#issuecomment-640841162_

**Comment by svenka3** [comment]
@sriyerg 
>> My preference is to actually move the $fsdvDump* system calls to a SV code instead

With due respect, I differ - doing $fsdb (or any other PLI/VPI) calls inside SV code requires us to recompile/re-elab for various scopes to be dumped (Common practice for large designs/runs - as full dump can be expensive). 

I believe individual tool_name.tcl is perhaps the most time-tested approach (other Unit test frameworks do this already, VUNit is one example). 

Can you please re-consider this?

Thanks
Srini

**Comment by svenka3** [comment]
@sriyerg 
>> My preference is to actually move the $fsdvDump* system calls to a SV code instead

With due respect, I differ - doing $fsdb (or any other PLI/VPI) calls inside SV code requires us to recompile/re-elab for various scopes to be dumped (Common practice for large designs/runs - as full dump can be expensive). 

I believe individual tool_name.tcl is perhaps the most time-tested approach (other Unit test frameworks do this already, VUNit is one example). 

Can you please re-consider this?

Thanks
Srini

**Comment by sriyerg** [comment]
We have kept the dumping calls in TCL files/ Closing this issue (feel free to reopen if needed).
