### ISSUE TITLE
[otbn] style guide/secure coding guidelines for otbn assembly

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#3314]
For the sake of consistency across OTBN assembly files and as much as possible across OTBN and RISC-V assembly we should come up with a style guide for OTBN assembly.
As a starting point this can just be a copy of the [RISC-V style guide](https://docs.opentitan.org/doc/rm/asm_coding_style/).

Some initial thoughts:
**Comments**
-  Only C style comments (due to toolchain restrictions)

**Letter case**
  - mnemonics: lower case
  - registers: lower case
  - flags and flag groups: upper case
  - half word identifiers in multiplication instructions: upper case

**Indentation:**
- Same as with RISC-V guidance for directives
- The RISC-V guide does not mandate any indentation for operands. We should come up with some for OTBN, since we have more often coherent blocks:
  - We should include a proposal on arranging sequences of multiplication instructions
  - We could come up with something for loops (loop kernel being indented) or not, if this is a no-go
  - In multi-limb adds and subs registers should be right-aligned across all lines forming a block

**Pseudo instructions:** (see also #2967)
  - use `ret`, `li` and `nop` whenever possible
  - prefer `loop`/`loopi` pseudo instructions with end labels over the ones with immediate loop length (once this is available)
  - ...

**Subroutine and label naming**
- Is there sth. here?

**ABI names for register**
- If we come up with sth. here we should enforce the usage. Special purpose is only `x0` and `x1` at the moment.

**Named CSR and WSR**
- Currently we don't support named WSRs and CSRs in the assembly. If we support this, we should encourage it to be used

**Subroutine doxygen header**
- Like in the RISC-V guide every input and output parameter shall be listed as a doxygen style `@param[in]`/`@param[out]` statements
- Ideally usage of temporary registers should be described but at least every clobbered registers shall be named
- All clobbered Flag Groups shall be named

**Constants in the .data section** (see also #3604 for some context)
- Prefer the `.word` directive over `.quad`

There are other aspects where I am not sure if the style guide is the right place for such information:
- How to write constant time code, avoid data dependent branching, use `BN.SEL` whenever possible
- Use of the `ecall` instruction and wrappers such that subroutines can be called internally and externally

Further thoughts?

**Comment by rswarbrick** [comment]
> Only C style comments (due to toolchain restrictions)

If this is really annoying, we could always call `cpp` in `otbn-as`: I didn't so far, because I wanted to make something that looked like the binutils `as`, but I guess that a call to `cpp` wouldn't change any files that were already valid. If we do this, it will actually make the work of `otbn-as` easier (since it no longer needs to care about parsing comments).

About indentation: I agree. I rather like tabulating blocks of operands. I think I'd avoid being too prescriptive, so would suggest something like "tabulate operands in blocks that look sensible" or similar.

> Currently we don't support named WSRs and CSRs in the assembly.

Good point. We should! I'll open an issue to track that.

**Comment by lenary** [comment]
I would prefer the assembly style guide was not forked into a separate style guide just for OTBN. What about making it clear that https://docs.opentitan.org/doc/rm/asm_coding_style/ is a general style guide, with RISC-V- and OTBN-specific sections? (Like we have C and C++ specific sections in the C/C++ style guide).

**Comments:**
I don't really have an issue if we require `.S` files to all have `/* */` comments, we can easily fix that in existing assembly, if it makes everything easier for the OTBN tooling. This is probably what we should have done anyway, but we failed to notice that the `.S` files in meson were being run through gcc, which preprocesses them first. (Aside: do we want to preprocess the OTBN files? if not, they should be using `.s`)

**Operand Blocks**
I have no issue here requesting indenting operands, it makes sense given `loop` is both an instruction, and something like a label. Yes we can suggest operands are all aligned together, or at the very least allow and heavily suggest doing so.

**Comment by felixmiller** [comment]
Re pseudo instructions: I think, we should not be too strict in enforcing their usage. There might be more obvious reasons to not use them, compared to standard RISC-V assembly. E.g. if you want to have two subroutines having a similar timing and power profile, but loading two different constants. If the number of machine instructions depends on the loaded value, this can be critical and an assembly author might choose to directly use `addi` instead of `li` to make this explicit.

We also need to think about what should be the guidance to handle pseudo instructions in loop bodies (see #3607).

**Comment by imphil** [comment]
Two more points in this discussion:

We do have currently programmer's guidance in a user guide at https://docs.opentitan.org/doc/ug/otbn_sw/ and in the OTBN reference docs at https://docs.opentitan.org/hw/ip/otbn/doc/index.html#writing-otbn-applications.

In addition to a pure style guide we also need a programmers guide which discusses practical conventions of programming routines for OTBN (e.g. how to best pass arguments between Ibex and OTBN), and a secure programmers guide, which discusses things like clearing of intermediate secrets at the end of an operation.
With probably a fair amount of overlap between purely cosmetic style, programmers guidance for functionality, and guidance for security, it might make sense to have all that content in a single document.

**Comment by imphil** [comment]
Another point for the coding guidelines: Prefer BN.MOV over `BN.ADDI xd, xs, 0` to maintain integrity protection when copying data between registers (see also https://github.com/lowRISC/opentitan/issues/6482).
