### ISSUE TITLE
[dv/common] calculate parameter *_ADDR_MAP_SIZE

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#3317]
As @tjaychen brought up, currently we need to manually set parameter `*_ADDR_MAP_SIZE` for each IP. This parameter defines the actual address size used for this IP, the rest of bits are ignored by design. And we need to manually update this parameter every time reg map is changed.

I think we may calculate this based on size of registers and size of mem, which we can get from RAL.
- if only registers or mem, DDR_MAP_SIZE = round up size_of_reg/mem to 2**N. size_of_reg = 4 * num_of_regs
e.g. IP contains 3 regs, DDR_MAP_SIZE = 16

- if it contains both registers and mem, round_up( max2(size_of_reg, size_of_mem)) * 2.
e.g. size_of_reg = 1k, size_of_mem = 4k, DDR_MAP_SIZE = 8k

we could also auto-generate DDR_MAP_SIZE based on reg hjson, but calculating in TB will be able to cross-check it.

@tjaychen @eunchan does this make sense? I assume all registers are continuous and at max one memory in the IP

**Comment by sriyerg** [comment]
Sounds good to me!

**Comment by eunchan** [comment]
As far as I know, start of the memory can be arbitrary. So `ceil2(max2(size_of_reg, size_of_mem))*2` may not be correct. For instance, memory can be placed in between the registers or it can start from 16kB in above example.

**Comment by weicaiyang** [comment]
> As far as I know, start of the memory can be arbitrary. So `ceil2(max2(size_of_reg, size_of_mem))*2` may not be correct. For instance, memory can be placed in between the registers or it can start from 16kB in above example.

@eunchan 
we could get the starting address of mem from RAL. How about ceil2(biggest_reg_offset+4, biggest_mem_offset+mem_size) and then round up to 2**N?
for example, biggest reg offset is 1k, mem offset is 16k and size is 2k, DDR_MAP_SIZE is 32k.

**Comment by eunchan** [comment]
> > As far as I know, start of the memory can be arbitrary. So `ceil2(max2(size_of_reg, size_of_mem))*2` may not be correct. For instance, memory can be placed in between the registers or it can start from 16kB in above example.
> 
> @eunchan
> we could get the starting address of mem from RAL. How about ceil2(biggest_reg_offset+4, biggest_mem_offset+mem_size) and then round up to 2**N?
> for example, biggest reg offset is 1k, mem offset is 16k and size is 2k, DDR_MAP_SIZE is 32k.

Looks good.

**Comment by weicaiyang** [comment]
> > > As far as I know, start of the memory can be arbitrary. So `ceil2(max2(size_of_reg, size_of_mem))*2` may not be correct. For instance, memory can be placed in between the registers or it can start from 16kB in above example.
> > 
> > 
> > @eunchan
> > we could get the starting address of mem from RAL. How about ceil2(biggest_reg_offset+4, biggest_mem_offset+mem_size) and then round up to 2**N?
> > for example, biggest reg offset is 1k, mem offset is 16k and size is 2k, DDR_MAP_SIZE is 32k.
> 
> Looks good.

Thanks for confirming. Will implement it.

**Comment by tjaychen** [comment]
thanks for looking into this!

**Comment by weicaiyang** [comment]
Done via #3441
