### ISSUE TITLE
Strange issue with dvsim.py on CentOS7

### ISSUE THREAD

**Issue by svenka3** [lowRISC/opentitan#3322]
Hi,
  I somewhat feel embarrassed to ask this silly question, but I couldn't figure out quickly.

I run:

`
./util/dvsim/vw_dvsim.py -t vcs hw/ip/rv_dm/data/rv_dm.prj.hjson --purge

`

I get:

`
ERROR: [utils] Substitution for the wildcard "l" not found

`
I did narrow it down to a single line as below inside dvsim.py:

  ```
 factory = factories.get(args.tool, SimCfg.SimCfg)
    return factory(args.cfg, proj_root, args)
 
```
I am on CentOS7 if that matters. 
Python 2.7.5

Thanks 
Srini

**Comment by tjaychen** [comment]
our setup flow requires python 3.5.2 or newer.  Can you give that a try?

**Comment by cindychip** [comment]
Hi Srini,

I also think the hjson seems to point to a different file. Can you try:
`./util/dvsim/vw_dvsim.py hw/ip/rv_dm/dv/rv_dm.prj.hjson  -i rv_dm_sanity
-t vcs --purge`

  Cindy Chen

**Comment by svenka3** [comment]
On my original post, I made a mistake on PY version. I have both Pyhton 2 & 3 installed and since dvsim looks for "env python3", it picks up 3.6.8

So I am definitely 3.5.2+ - Thanks @tjaychen 



env python3
Python 3.6.8 (default, Aug  7 2019, 17:28:10) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
[srini@vw-2020 opentitan]$ python3 --version
Python 3.6.8

**Comment by svenka3** [comment]
Also tried UART:
 
```
[srini@vw-2020 opentitan]$ ./util/dvsim/dvsim.py -t vcs hw/ip/uart/data/uart.prj.hjson 
ERROR: [utils] Substitution for the wildcard "l" not found

```
Same issue :-(


Python 3.6.8

Thanks

**Comment by cindychip** [comment]
For UART, can you try:

```./util/dvsim/dvsim.py hw/ip/uart/dv/uart_sim_cfg.hjson -t vcs -i uart_sanity```

**Comment by rswarbrick** [comment]
Following up from what Cindy said: The stuff in `hw/ip/rv_dm` is for the debug module. I don't believe we've done any verification work for this yet. It seems that trying to run its testbench fails, but that's not massively surprising: the testbench doesn't actually exist! If you look for `rv_dm` in the table at https://docs.opentitan.org/hw, you'll see it's marked as "V0". This means we don't believe we've done any of the verification work yet.

For the uart example, Cindy's command should work.

As a general rule, the OpenTitan project uses the "hjson" format (JSON, with a couple of additions) for lots of its configuration files. Some of these configuration files are used to tell `dvsim.py` what to do; some aren't. The `uart.prj.hjson` file that you tried falls into the latter category :-)

However, `dvsim.py` could be a bit more helpful when given the wrong sort of file. I'll do some digging in a minute and try to make a PR that improves the error message.

**Comment by svenka3** [comment]
Thanks all for the comments, had some funny scenarios, but quick sum-up:

1. Fresh clone, ran 
`
./util/dvsim/dvsim.py hw/ip/uart/dv/uart_sim_cfg.hjson -t vcs -i uart_sanity

`

That sort of worked. I say sort of as I believe it uses xprop in VCS by default and I had to remove it, for now edited vcs.hjson - my "Build" sort of hung for a while, so I did this. What's the preferred approach to tweak VCS command-line if I have to?

Thanks again

Srini

**Comment by svenka3** [comment]
Out of the box, dvsim on UART shows me:

```
INFO: [Deploy] [00:13:30]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
INFO: [Deploy] [00:13:40]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
INFO: [Deploy] [00:13:50]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
INFO: [Deploy] [00:14:00]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
INFO: [Deploy] [00:14:10]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
INFO: [Deploy] [00:14:20]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
INFO: [Deploy] [00:14:30]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
INFO: [Deploy] [00:14:40]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
INFO: [Deploy] [00:14:50]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
INFO: [Deploy] [00:15:00]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
INFO: [Deploy] [00:15:10]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
INFO: [Deploy] [00:15:20]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
INFO: [Deploy] [00:15:30]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
INFO: [Deploy] [00:15:40]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]

```


I kind of expected it and hence fixed vcs.hjson to knock-off xprop (License issue, unrelated to your team). Is there a built-in timeout in such cases? It does not expose VCS Comp log (that would show waiting for a specific license etc.), so am wondering how end-users would debug such cases?

Thanks
Srini

**Comment by rswarbrick** [comment]
Answering the question about the command line: I think that command should work! If not, it would be good to figure out what's going wrong.

You can find all sorts of stuff in the `scratch` directory. When I just ran that command, the build generated `scratch/uart.sim.vcs/master/default/build.log`, which shows the VCS command to build things (if you're on a different branch from `master`, you'll need to change that part of the patch).

The runs also get put in `scratch/uart.sim.vcs/master/`, with a directory per run. Again, you can find the command that ran them there.

About the timeout, this is for the "build" stage (running `vcs`, not `vsim`), so we don't include a timeout and just expect someone to hit Ctrl-C at their terminal if something has gone horribly wrong :-) You should hopefully see some errors in the `build.log` I mentioned above.

**Comment by sriyerg** [comment]
> Thanks all for the comments, had some funny scenarios, but quick sum-up:
> 
> 1. Fresh clone, ran
>    `
>    ./util/dvsim/dvsim.py hw/ip/uart/dv/uart_sim_cfg.hjson -t vcs -i uart_sanity
> 
> `
> 
> That sort of worked. I say sort of as I believe it uses xprop in VCS by default and I had to remove it, for now edited vcs.hjson - my "Build" sort of hung for a while, so I did this. What's the preferred approach to tweak VCS command-line if I have to?
> 
> Thanks again
> 
> Srini

You can try the `--xprop-off` switch. Please run `dvsim.py --help` for more details.

**Comment by sriyerg** [comment]
> Out of the box, dvsim on UART shows me:
> 
> ```
> INFO: [Deploy] [00:13:30]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
> INFO: [Deploy] [00:13:40]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
> INFO: [Deploy] [00:13:50]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
> INFO: [Deploy] [00:14:00]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
> INFO: [Deploy] [00:14:10]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
> INFO: [Deploy] [00:14:20]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
> INFO: [Deploy] [00:14:30]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
> INFO: [Deploy] [00:14:40]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
> INFO: [Deploy] [00:14:50]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
> INFO: [Deploy] [00:15:00]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
> INFO: [Deploy] [00:15:10]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
> INFO: [Deploy] [00:15:20]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
> INFO: [Deploy] [00:15:30]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
> INFO: [Deploy] [00:15:40]: [build]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]
> ```
> 
> I kind of expected it and hence fixed vcs.hjson to knock-off xprop (License issue, unrelated to your team). Is there a built-in timeout in such cases? It does not expose VCS Comp log (that would show waiting for a specific license etc.), so am wondering how end-users would debug such cases?
> 
> Thanks
> Srini

If you scroll up, `dvsim` prints the scratch directory that is used to put all the build and run artifacts including the log files.

**Comment by imphil** [comment]
I assume the issue reported in here is now resolved, please reopen or create a new issue if not.
