### ISSUE TITLE
[otbn] Specify flags in bignum logical instructions for FG0 only

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3335]
Currently the modexp.S assembly and the old simulator expect a behavior where BN.OR and BN.XOR set the Z, M and L flags of flag group 0. This behavior doesn't match the ISA spec.

@felixmiller Can you come up with a way to modify the assembly to work around that, or do we need to come up with a spec change?

> estimate 2

(estimate is for updating documentation and tooling)

**Comment by felixmiller** [comment]
The workaround would be to add a dummy `addi wdr, wdr, 0` after each logical operation when the flag is needed.

I think we should update the spec here and set the flags for all logical operations. Actually I started writing an issue on exactly this some days ago, but in the middle of it looked at the spec, misread it somehow and thought it was covered already and discarded it again.

I realized that I use the flags quite often after logical operations. Most of the time, it would not really be performance critical but nevertheless we save quite some dummy instructions and I think the HW overhead is probably negligible. 

What we need to discuss though is what happens to the C flag. As you write correctly above, current behavior of the old sim is that it is left untouched in logical instructions. This is apparently also dcrypto behavior. Should we stick to this and preserve it or set it to 0? My gut feeling is that programmers would rather expect that instructions touch either all of the flags or none.
However, we would have to go over the code in `modexp.s` and check where this is an issue and if there is a good workaround (by using the other flag group or rearranging instructions)

**Comment by imphil** [comment]
> The workaround would be to add a dummy addi wdr, wdr, 0 after each logical operation when the flag is needed.

I tried that, but it doesn't work out of the box, since it also resets the C flag, which the next instructions depend on (at least in the modexp.S case). (Or I made a mistake somewhere when trying it.)

**Comment by imphil** [comment]
@rswarbrick @wallento could we find space in the encoding for flags for bignum logical instructions?

**Comment by felixmiller** [comment]
> I tried that, but it doesn't work out of the box, since it also resets the C flag
right

@imphil By encoding you mean the bit for the Flag Group or is there anything else?

**Comment by imphil** [comment]
Yes. We could do it without encoding changes and always use fg0, but that would be rather inconsistent and something I'd like to avoid if possible.

**Comment by felixmiller** [comment]
@imphil yes, I agree

**Comment by imphil** [comment]
@felixmiller So what would be your preferred option be? Make all logical instructions from the big number subset (namely: BN.OR, BN.XOR, BN.AND, and BN.NOT) set the Z, M and L flags, but not the C flag?

Thinking about getting modexp.S running on the documented spec: Is this change our best chance to get modexp.S working, or can you think of other (reasonably easy) changes to the assembly to make it work without flag setting?

**Comment by rswarbrick** [comment]
We've agreed that we'll set Z, M, L. We need to update the documentation.

We'll also support the different flag groups. This is a small amount of tooling work, plus we need to re-jig the encoding as described by Stefan above.

**Comment by imphil** [comment]
@wallento If you have time, can you come up with a PR to change the encoding in the YAML files to find space for the FG bit in the wide logical instructions?

**Comment by wallento** [comment]
Yep, will work on it!

**Comment by GregAC** [comment]
Will we want this behaviour with BN.RSHI as well? (i.e. set Z, M, L flags). I would note flag group can't fit into the current BN.RSHI encoding.

Could I confirm that the intended behaviour for C is to leave it alone (rather than clear it) on logical operations?

**Comment by rswarbrick** [comment]
About the C flag: Yes, I think that's what we agreed. We should probably update the documentation to make that explicit.

**Comment by wallento** [comment]
Getting RSHI to support flag group seems hard but not impossible, is this desired?
