### ISSUE TITLE
[otbn] modexp.S assumes WSR 2 is RND

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3337]
The random number WSR is index 1, not index 2. The code in modexp.S uses the wrong WSR number https://github.com/lowRISC/opentitan/blob/master/sw/otbn/code-snippets/modexp.S#L38. 

(The old simulator is also wrong here.)

@felixmiller

**Comment by felixmiller** [comment]
created PR #3342 for this and updated the old simulator, but probably let's conclude on #3338 before merging this

**Comment by imphil** [comment]
Fixed in #3342, since this is really an orthogonal issue to the whole other discussion around accessing WSR (no matter how we access it, we need to access the right register). Thanks for the patch @felixmiller!
