### ISSUE TITLE
[dvsim] The single-character wildcards in common_sim_cfg.hjson are a bit confusing

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#3344]
As it currently stands, you get a very strange error if you call dvsim on an hjson file that it doesn't understand. One part of making this less mysterious is to change how these wildcards work.

I proposed one way to do this in PR #3325, but Sri explained that this isn't really generic enough: we want to support verbosity flags for non-simulator tooling. A way to make the error messages less bizarre is to rename the wildcards that are currently called `l`, `m`, `h`, etc. to something more like `uvm_level_for_verbosity_l` etc.

Before coding something, I'd like to get some feedback on how this would best be fixed.

@sriyerg: What do you think is the best way to tidy this up?

**Comment by sriyerg** [comment]
I am fine with changing those to `none|low|medium|high|debug` if we want to make it sound less mysterious.

The original problem (#3322) arose due to suppling an invalid hjson to `dvsim`. This can be easily fixed by setting an identifier in the hjson telling dvsim that it is a valid cfg input. If that is missing, we fail immediately citing the wrong / incompatible hjson. Something like this:
```json
  is_dvsim_cfg: true
```

**Comment by rswarbrick** [comment]
Cool. I'd probably names that are specific to the "type of flow": if we add verbosity support to `FooCfg` in the future, we're going to want non-clashing names for `expand_foo_verbosity_low`, `expand_foo_verbosity_medium`, etc. I'll push up a PR in a minute.

About the `is_dvsim_cfg` variable: I wondered about that, but thought it was a pity to have to tag everything. I suspect that (for now, at least) we probably only have to sort this out for `SimCfg`, because people are more likely to know what they're doing if they explicitly pass a lint tool or similar. Maybe there's a cleverer trick we can use.

**Comment by rswarbrick** [comment]
I've just pushed up a proposal for the verbosity thing. Also, I've realised that we can do much better than I was thinking for the "is_dvsim_cfg": let's define a "dvsim_cfg_type" variable. That will also let us get rid of the hacky logic to select a `FlowCfg` subclass in `dvsim.py`'s `make_cfg`. I'll hack together a patch now.
