### ISSUE TITLE
[otbn] RTL: Implement big number logical instructions (BN.NOT, BN.AND, BN.XOR, BN.OR)

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3364]
Implement big number logical instructions (BN.NOT, BN.AND, BN.XOR, BN.OR)

Ideally we can sort out the flag behavior in #3335 first.

**Comment by GregAC** [comment]
We've also got this issue: https://github.com/lowRISC/opentitan/issues/2953 I would include the logic instructions as part of that issue. Do we want to close #2953 and have separate wide side register file and arithmetic instruction issues?

**Comment by imphil** [comment]
Ah good point, let's clarify the original issue then.
