### ISSUE TITLE
[otbn] Implement big number instruction compare/select instructions

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3366]
Instructions to be implemented
* BN.SEL
* BN.CMP
* BN.CMPB

CMP and CMPB are effectively SUB/SUBB. Estimate assumes these instructions are already implemented.

> estimate 3
> remaining 2020-10-05 3

**Comment by GregAC** [comment]
This has not yet begun so remaining same as initial estimate

**Comment by GregAC** [comment]
Implemented in https://github.com/lowRISC/opentitan/pull/3710
