### ISSUE TITLE
[otbn] Implement data movement/load store of big number instruction subset

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3367]
Instructions to be implemented

  * BN.LID
  * BN.SID
  * BN.MOV
  * BN.MOVR

> estimate 4
> remaining 2020-10-05 4

**Comment by GregAC** [comment]
This is part way done but the indirection side of things ended up being a lot of more fiddly than anticipated so it still isn't complete. Hence my remaining estimate is the same as the initial estimate but significant work has actually happened!

**Comment by GregAC** [comment]
Implemented in https://github.com/lowRISC/opentitan/pull/3710
