### ISSUE TITLE
[otbn] Implement WSR access instructions

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3368]
Instructions to be implemented
  * BN.WSRRS
  * BN.WSRRW

(Estimate assuming this is using functionality from #3245)
> estimate 2

**Comment by GregAC** [comment]
To be implemented RISC-V style for now, will return to the discussion as to whether we should instead implement plain CSR Read/Write later.

**Comment by imphil** [comment]
Done as part of #3471.
