### ISSUE TITLE
[otbn] verbal specification for carry/borrow flag set/clear condition in arithmetic instructions

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#3387]
We should add a verbal definition for the condition of the carry/borrow flag being set/cleared in arithmetic instructions.

At the moment we only include an indirect definition of such a condition via the `AddWithCarry` method in the [spec](https://docs.opentitan.org/hw/ip/otbn/doc/#big-number-instruction-subset).

We should include a verbal definition e.g. "[...] implements y=a-b [...] carry flag is set when b>a and cleared otherwise [...]" for being able to capture this on the highest possible level of abstraction in the formal verification work by @sydgibs.

**Comment by rswarbrick** [comment]
I agree that a verbal description is a good idea. But a formal spec is probably easier via the (shared) `AddWithCarry` function than by deciphering written English. I think this will probably be most useful for software writers who want to understand what's going on.

**Comment by rswarbrick** [comment]
We've got this now at https://docs.opentitan.org/hw/ip/otbn/doc/#flags.
