### ISSUE TITLE
[doc] "Hardware Development Stages" vs "Development Stages"

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3469]
In our documentation at https://docs.opentitan.org/doc/project/development_stages/ we talk about "hardware development stages" and "development stages" somewhat randomly. The development stages focus primarily on a single IP block, but cover RTL, verification, and DIFs (which are the "software" part). 

It would be nice to clarify the scope of the development stages document by using consistent naming.

I can't see a clearly better naming, here's my thinking:

- Use "Hardware Development Stages" to clearly indicate that we only consider everything hardware-related topics, but not software other than DIFs.
- Use "Development Stages" to avoid the potential confusion about DIFs being software, but still within scope for the development stages.

I guess one main question would be how strongly we need/want to separate the lifecycle scheme from software other than DIFs. What's your thinking there @gkelly @lenary?

@sjgitty @asb @sriyerg

**Comment by sjgitty** [comment]
Agree, we should not typically refer to them as Hardware Development Stages; I think we even changed the file to reflect that a while back and just didn't update the content underneath. Feel free to suggest a PR, or I will as soon as my machine is resurrected / replaced.

**Comment by sriyerg** [comment]
Fine with 'Development Changes' since we are not just building HW but also SW drivers that goes with it. 

IMO DIFs are more tightly coupled with HW since we use it in pre-Si verification (which gates tapeout / final chip signoff), whereas the rest of the SW stack can continue to develop beyond tapeout.

**Comment by lenary** [comment]
I've been pretty careful to try to use "Development Stages" when talking about them from the software side, but I was wary of updating all the Silicon documentation.

Other software will not be using this S1/S2/S3 development stage model, I don't believe, but I don't think @gkelly and I have had a chance to discuss that in any great detail.

**Comment by moidx** [comment]
Closed as obsolete. We have settled down on using "Development Stages" to refer to hw and software development stages.
