### ISSUE TITLE
[otbn] Broken smoke test

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3470]
https://github.com/lowRISC/opentitan/commit/42ea809e459ee95fc40c31f40e534e12a2653ba1 (merged in https://github.com/lowRISC/opentitan/pull/3460) breaks the OTBN smoke test in CI, ass seen in https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=21673&view=results. It didn't break in PR CI (https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=21647&view=logs&j=1454b898-4e5e-5cfa-4c06-965e95c83d2e&t=7e6b977f-9c6a-5377-ff05-a6efdb19c231), so something on master likely changed between the PR opening and the merging.

**Comment by imphil** [comment]
@rswarbrick

**Comment by GregAC** [comment]
This PR has a fix for it: https://github.com/lowRISC/opentitan/pull/3468

**Comment by GregAC** [comment]
can spin that out as a separate PR if we want the fix now without awaiting review for the rest of it

**Comment by GregAC** [comment]
Breakage was introduced by this change: https://github.com/lowRISC/opentitan/commit/e4665c1fd2861ecd274d3d86c967422cf5a5d717 though the bug was in the OTBN verilator simulation top. It failed to specify the dmem size as 256 bit which didn't matter until that change came in.

OTBN smoke only runs on OTBN changes which is how this slipped through.

**Comment by imphil** [comment]
No need to split it out, I'll have a look at #3468 now. Thanks Greg!

**Comment by rswarbrick** [comment]
> Breakage was introduced by this change: e4665c1 though the bug was in the OTBN verilator simulation top. It failed to specify the dmem size as 256 bit which didn't matter until that change came in.

Sorry about that. The PR (#3459) didn't run the OTBN smoke test as part of CI because the change didn't touch any OTBN-specific code. Oddly, things seemed to work locally, but maybe I didn't run exactly what I thought I'd run.
