### ISSUE TITLE
Issues Debugging with OpenOCD/GDB

### ISSUE THREAD

**Issue by aroelke** [lowRISC/opentitan#3488]
I'm having some trouble running code on an OpenTitan (using [this](https://github.com/lowRISC/opentitan/commits/f264970134eef253e77f9f52350e9bd8acc39c24) commit) system with OpenOCD and GDB, on a Nexys Video board.  I've downloaded the toolchain using util/get-toolchain.py and built OpenOCD according to the instructions [here](https://docs.opentitan.org/doc/ug/install_instructions/#openocd) (Using [this](https://github.com/riscv/riscv-openocd/commit/1712dc2c547f41670aabcffc100426d81210dae0) riscv-openocd commit), but I've had several problems and still can't get it to run:
- That commit of OpenOCD segfaults upon trying to connect to the board.  I've been able to fix this by adding an `init` command to lowrisc-earlgrey.cfg before the `riscv set_prefer_sba on` command, and then moving both to the bottom of the file (as `init` has to happen after some of the other commands there).
- After fixing that, GDB reported a failure to load the binary (the hello_world example included in OpenTitan).  After some digging, this appeared to be because OpenOCD doesn't support writes of lengths that aren't multiples of 4 bytes, and that binary has a section with an odd number of compressed instructions in it (so it doesn't end on a 4-byte boundary).  I fixed this by identifying the section (`.crt`) and padding it out to the correct alignment in flash_link.ld.
- That causes the program to load, but it won't run.  After loading and stepping once, GDB reports "[0] Found 1 triggers" and then can't identify where in the code it is: `0x00008000 in ?? ()`.  A second step causes it to report "Cannot find bounds of current function," which it repeats for every step thereafter.  I haven't been able to fix this problem yet.

**Comment by aroelke** [comment]
Are you sure?  I thought [riscv-dbg](https://github.com/pulp-platform/riscv-dbg) allows you to load programs over GDB?

**Comment by alistair23** [comment]
I am not sure. I use GDB regularly with OpenTitan though and don't see any issues. I do load images with the `spiflash` script instead of via GDB though.

**Comment by aroelke** [comment]
It seems like the problem was a memory mapping one--the linker script (which, in retrospect, I probably should have realized) puts all the data into flash, which GDB can't write.  If I modify it to put it into main memory and add an entry point at `_start`, I can step part of the way through the program.  Now I encounter two additional issues:
- I can't add breakpoints.  When I try (at `main`, for example), it says
  ```
  Error: Target riscv.tap.0: Failed to read memory (addr=0x10001f0a)
  Error:   progbuf=disabled, sysbus=skipped (unsupported size), abstract=disabled
  ```
  From running OpenOCD in debug mode, it looks like it's trying to write a packet of size 2 using the system bus, which isn't supported.  This doesn't seem like a problem unique to the way I'm loading the code, as I imagine it would still be that way even if it were loaded from flash; has anyone ever encountered this?
- When I step too far, GDB starts getting `E0E` returned to it and stops being able to tell where it is in the code.  What could be causing this?

**Comment by aroelke** [comment]
This ended up being a combination of memory size issue and startup file issue.  The memory wasn't big enough to store the binary, and the startup files also don't need their sections for copying data from where it's stored into another place in memory, as in this case it's already in memory.  Changing both of these things fixed the issue.
