### ISSUE TITLE
Remove TB for rv_core_ibex 

### ISSUE THREAD

**Issue by taoliug** [lowRISC/opentitan#35]
Right now there's a block level TB for rv_core_ibex:
https://github.com/lowRISC/stwg-base/tree/master/hw/ip/rv_core_ibex/dv

This is created before ibex TB which is already open sourced:
https://github.com/lowRISC/ibex/tree/master/dv/uvm

Since we expect to do all the processor verification work on ibex repo, it's kind of an overhead to maintain the TB for rv_core_ibex in STWG repo. The logic in rv_core_ibex wrapper is mainly protocol conversion between ibex proprietary memory interface to TileLink interface, which can be verified at SOC level. 

File this bug to discuss whether everybody is OK to remove this TB to eliminate the maintaining overhead.

**Comment by imphil** [comment]
Closed through #746
