### ISSUE TITLE
[otbn] byte/bit shift mixed up in simulator

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#3505]
It seems that in the dmem model of the otbn simulator in the `load_i32` method in [this line](https://github.com/lowRISC/opentitan/blob/8c710f6200b0dcdd7286db0f3040e2b04c49a6a6/hw/ip/otbn/dv/otbnsim/sim/dmem.py#L171) the shift amount has to be indicated in multiples of 32 bits, not bytes

**Comment by rswarbrick** [comment]
You're right! I think this was fixed by PR #3485 (by deleting the code in question). Does that look right to you?

**Comment by felixmiller** [comment]
Yes, didn't see this, this should fix it. This should also fix #3509, right?

**Comment by rswarbrick** [comment]
Oh, I hadn't got to the end of my inbox yet! Yes, I hope so.

**Comment by felixmiller** [comment]
fixed with #3485
