### ISSUE TITLE
[entropy_src] Health check updates required

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#3511]
The `entropy_src` IP is currently going through a large review in #3004.

Changes include: 
1. Complete overhaul of the architecture to include the health check management discussions.
2. Creation of 2 tests outside of SP 800-90A
3. Interface with the AST noise source (In addition to the previous LFSR).
4. Light-weighting of early-boot initialization procedure for simplifying interactions with the boot ROM.
5. Support for SHA-2 or SHA-3 conditioning etc.
6. Support for a single Pre-FIPS seed.

In light of all these changes, the PR should go through.
However, I'm opening issues for any obvious details that I see in the PR before I approve it.

However, the Markov test is its initial implementation is incomplete (as one can see from simple visual inspection).
- It needs to have an upper and lower threshold (like the adaptive proportion implementation)
- Currently no Thresholding is done (the test simply compares the counts to 0).

Clearly this is a WIP.   I'm happy to approve it, but this issue should stay open until the implementation is complete.

**Comment by martin-lueker** [comment]
We may also need to change the Repetition count test as described in #3004.  It currently runs on a window, and resets at the window boundary.  This is technically non-compliant.

**Comment by mwbranstad** [comment]
Based on the entropy_src group meeting discussions, there is a new issue to document where the health checks should perhaps be all on a symbol basis (versus bit) for all health checks, and that 2K bits need to be tested (versus 1K bits).

**Comment by mwbranstad** [comment]
All of the above listed issues have been addressed, either by implementation or documentation. Assigning to @martin-lueker to approve and close this issue.
