### ISSUE TITLE
[entropy_src/CSRNG/EDN/doc] Language review

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#3512]
Need to do a complete review of the terminology in the entropy_src, CSRNG & EDN specs, to align them with CC/FIPS, and each other. 
There are various terms in the specifications for these three blocks that are not totally aligned with each other, or perfectly clear what they mean when comparing to CC & NIST docs.   (They are pretty self-consistent when taken independently though).

Examples: 
- EDN refers to "pre-FIPS" entropy, but the entropy source refers to "Bypass-mode" seeds.
- Entropy source now refers to a "Physical True Random Number Generator mode", but the registers still say "RNG" mode.  (@mwbranstad, I'd like to rename the registers, but I'll wait until you are ready). 
- Entropy source document could use some more references to both SP 800-90B and AIS31.

**Comment by moidx** [comment]
Hi @martin-lueker, should we keep this issue open?

**Comment by martin-lueker** [comment]
We don't need this any more closing.
