### ISSUE TITLE
[otbn] Do base and bignum ISAs need seperate RND register?

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#3522]
There is a register named `RND` for both the CSRs (base ISA) and WSRs (bignum ISA) that provides a random number. Can this register share the same random number source? 

If we can request varying numbers of bits from the random number source then this can be implemented efficiently. We we can only request fixed numbers of bits then this will be inefficient, in that a CSR read of 'RND' will use 32-bits then throw away 224 bits. In this case the frequency of use of 'RND' as a CSR is important.

**Comment by rswarbrick** [comment]
Even if we have to read 256 bits at once, we could always have an 8-element FIFO for narrow `RND`, so I think we can share an EDN connection between the two (guess what spec I've been reading recently...)

**Comment by GregAC** [comment]
A good point, I think it really comes down to the cost of the connections if they're fixed bit wise. You suggestion is certainly doable but with some implementation complexity, how does that compare to two connections vs one?

**Comment by imphil** [comment]
There's also https://docs.google.com/document/d/1rgtPlXiJo21dq7gL_QZdV2XPISR78hkoLhJV8f1pt5M/edit#heading=h.k9tb5f5zh7q5 (I should turn this into an issue) to specify the properties of these random numbers.

**Comment by GregAC** [comment]
Closing as covered by #2638
