### ISSUE TITLE
Window generation in Flash Controller

### ISSUE THREAD

**Issue by hadirkhan10** [lowRISC/opentitan#3527]
Hello, I was trying to understand the [flash_ctrl.hjson#L743](https://github.com/lowRISC/opentitan/blob/master/hw/ip/flash_ctrl/data/flash_ctrl.hjson#L743) configuration file and cannot understand the purpose of the `window` parameter for the ready fifo and program fifo. In the UART we did not use this parameter in the configuration file for creating an RX FIFO and TX FIFO. We generally created a FIFO and controlled it using the `ctrl` and `status` registers. Why didn't we follow the same procedure here? What is the actual reason of using a `window` parameter for allocating a memory space rather than creating a FIFO itself? 
Thanks in advance!

**Comment by sriyerg** [comment]
+@tjaychen, @eunchan

**Comment by tjaychen** [comment]
the window function just allows you to expose the tlul bus directly through
the regfile.
This allows you to implement additional functions on the other side if
desired.  It is specifically useful if you want to implement back pressure
type functions, which is not possible without using the "window" feature.

**Comment by hadirkhan10** [comment]
Okay thanks @tjaychen
