### ISSUE TITLE
[keymgr] HW status update and SW read clear happens at the same time

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#3533]
When HW status update and SW read clear happens at the same time, read clear has the priority and HW status can't be read properly.
In waveform below, status_o with `OpDoneSuccess` has been captured , but this update can't be seen in `working_state_o` by SW as read clear occurs at the same cycle.
![Screen Shot 2020-09-21 at 4 48 37 PM](https://user-images.githubusercontent.com/49293026/93832411-88131780-fc2a-11ea-9dc0-f3faf9abf3b5.png)

Waveform:
/edascratch/weicai-opentitan/ot/keymgr.sim.vcs/km_sanity/0.keymgr_sanity/out
verdi -ssr Verdi.ses &

**Comment by tjaychen** [comment]
good catch. Let me change this to w1c.

**Comment by weicaiyang** [comment]
Fixed via #3535
