### ISSUE TITLE
[life cycle] Execution from SRAM

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#3572]
Execution from SRAM should be allowed during TEST / RMA states but prohibited during DEV / PROD / PROD_END type states.
Obviously it should also be restricted during SCRAP states.

Need to find a way to hook this functionality up at the top level, or possibly inside Ibex. 

This is to satisfy Nuvoton's requirement that they be able to execute code without touching flash during manufacturing.

**Comment by tjaychen** [comment]
@tomroberts-lowrisc wanted to see if you want to consider absorbing this into ibex directly.
It would almost be like a hard-wired pmp region that activates only under certain conditions.  We could think about other ways of doing it also.

**Comment by tomroberts-lowrisc** [comment]
Adding @GregAC - Possibly something we could wrap into the PMP sideloading scheme, but we might be at risk of overlaying too much stuff on to PMP!

**Comment by GregAC** [comment]
I did think this was going to be handled by the crossbar, so it would only allow transactions from the Ibex instruction data port to reach the SRAM under certain states.

**Comment by tjaychen** [comment]
that's fine too, we could easily attach the idea of an ID for some function in `rv_core_ibex`.
Where do you guys think is the right place?

**Comment by tjaychen** [comment]
o i should also say we have a similar issue with access to the debug ROM, so we should really handle both of these similarly. What do you think?

**Comment by tjaychen** [comment]
just a note, i'm going to get a one pager out for this soon... but we're aiming for a two fold solution..

First level 
1. add transaction attributes inside rv_core_ibex to denote whether a transaction is instruction or data
2. inside the memory wrapper, disallow instruction type access when we are in the appropriate life cycle state

Second level
Either inside rv_core_ibex or the fabric, do a further gating based on address range that only during TEST / RMA states we can let the instruction ports go to memory.

**Comment by eunchan** [comment]
> 1. add transaction attributes inside rv_core_ibex to denote whether a transaction is instruction or data

Maybe we could also add the privilege level in user data too?

**Comment by tjaychen** [comment]
Yeah we can allocate space for that as well.  To make use of it though we
would need ibex to expose information about which state it is in.
It might be worth bringing up, because it would also imply a hard memory
split downstream where we need to know what memory is associated to what.

**Comment by GregAC** [comment]
It'd be easy enough for Ibex to expose the privilege level a particular access was from. It's already available internally for the PMP check so it would just be a case of wiring that signal out to top-level (along with carrying it through the TL interconnect). Though I'd suggest moving it from RISC-V ISA encoding to either a single bit signal (M or U) or a hardened signal that has some reasonable hamming distance between the two valid M and U values.

**Comment by tomroberts-lowrisc** [comment]
Hi @tjaychen - it looks like progress on this has started in #5209 - is there anything else we need to expose from the core under that scheme?

**Comment by tjaychen** [comment]
thanks for the reminder on this issue. 
I dont think there's anything else we need to expose from ibex at the moment. 

If you guys want to expose the privilege level from the ibex, we can certainly hook it up, although right now there is no immediate plans to use them.  Would you guys mind taking a look at the other PR to make sure things seem okay to you? Especially around `rv_core_ibex` and `rv_dm`?

**Comment by tjaychen** [comment]
this is now implemented per https://docs.google.com/drawings/d/1N_zpxu9T4pj_Mf0mz2y2Qa94F6EeS_-Xw8RVbQyMoTc/edit?usp=sharing
