### ISSUE TITLE
[CSRNG] Need optional interrupt for entropy required 

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#3575]
With many of the bypass and shutdown options added to entropy_src in #3004, it is clear that there are many times when the entropy_src will be disabled or waiting for firmware in some firmware-driven option.  

CSRNG needs to have a mechanism to inform firmware that it is looking for entropy right now, so that firmware can reactivate the entropy_src if needed.

**Comment by martin-lueker** [comment]
@zi-v: FYI this will facillitate more firmware driven operation of `entropy_src`

**Comment by mwbranstad** [comment]
Not sure there is a use-case where ES is shut down and needs to be re-activated anymore, but in any case the interrupt has already been added to CSRNG. Closed this issue.
