### ISSUE TITLE
[otbn] Keeping ISS/RTL in sync

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#3579]
https://github.com/lowRISC/opentitan/pull/3577 and https://github.com/lowRISC/opentitan/pull/3471 have raised the issue of what requirements we want to place on keeping otbnsim and the RTL in sync in terms of what they implement.

I think there's two main issues:

1. Do you allow something to be implemented in RTL and merged in without corresponding simulator support?

Allowing a feature to added in RTL without it being implemented in the simulator isn't something that you want long-term though I'd argue it's reasonable in the short term in some cases. Where adding support is an easy change then it can be done as part of the RTL PR but if something more complex crops up it's not unreasonable to do them separately. You could of course say the simulator PR must come first, allowing the simulator to implement functionality RTL doesn't yet have but not allowing the opposite.

2. What is the smoke test for?

Up til recently it's purely been testing RTL along with some of the tooling. Now the model is integrated it partially tests that too (though in a limited fashion as we don't have much comparison between the model and RTL yet, once that is complete it will test the model to the same extent it tests the RTL). I think it's a good idea for it to be testing both model and RTL though if your answer to 1. is 'yes' you will have a situation where there's an RTL feature you might like to test in the smoke but can't because it'll fail against the model. As anytime we have an RTL feature that isn't supported in the model we would intend to update the simulator quickly I think saying smoke test must always be run with model included/checking enabled is reasonable and just leave any RTL only feature as un-tested in CI.

**Comment by rswarbrick** [comment]
Copying and pasting from my comments in 3577:
- [First comment](https://github.com/lowRISC/opentitan/pull/3577#issuecomment-698387868)
  I think the question about whether we take RTL with no model is above my pay grade :-) But I think it's a pretty strange thing to do. We've presumably specced the design. Updating the simulator is way easier than updating the RTL, so I think we should do that first and add simple tests (smoke or otherwise) as the RTL is updated.
- [Second comment](https://github.com/lowRISC/opentitan/pull/3577#discussion_r494377505)
  Forcing the model to be enabled will only break CI if we both
  -  add / modify an instruction that doesn't match the simulator
  -  add lines to the smoke test that use the instruction

  I think we just shouldn't do that.

**Comment by rswarbrick** [comment]
I should add: From my point of view, "is the RTL correct?" is shorthand for "does the RTL do the same thing as the model?".

Obviously, when the ISS is super-shonky or has massive missing features, there's an argument for running ahead. But it's not all that bad now: we should be able to fix up corner cases in a couple of hours, so I don't see a problem with gating RTL changes that long.

**Comment by imphil** [comment]
My 2c: 

* We should work hard to keep simulation and RTL in sync. (There's only limited value to a model that models something different than the RTL.) Typically that means get the ISS changes in first, or together with the RTL.
* Life isn't black and white. There are situations where we RTL and model might diverge for a good reason. We should retain a (reasonably easy) way to let that happen, e.g. by disabling a CI job, or setting a parameter. Doing so as an explicit action can unblock us while avoiding unintended diversion between model and RTL.
* I don't expect us to run into that situation very often. Once we're through with an initial implementation of the spec we shouldn't have ISS-visible diversions very often.

**Comment by cdgori** [comment]
Just probing some assumptions: do we regard "spec as golden reference" and both ISS & RTL as derived implementations?  Obviously you can't simulate a spec, so something has to be the preferred simulation (modulo the fact that bugs happen).  Is the "preferred" simulation target the ISS or the RTL?

I am used to having the ISS & RTL sort of cross-check each other for implementation errors (especially when implemented by different people who might interpret ~ambiguous spec language differently) and also cross-check the spec for architectural/construction errors.

I've also seen a situation where the ISS is more of an architectural reference model, perhaps cycle-accurate or even transactional in nature, and there is another verification-team-created, very detailed design reference model allowing for checking of internal design state/behavior against the RTL.  This is also fine, it just affects how we all think about ensuring correctness at the different levels of description/implementation.

**Comment by rswarbrick** [comment]
I think we're aiming for "spec + ISS" as golden reference. We can't snip the ISS out completely because we're planning to auto-generate the pseudo-code operation for each instruction from the ISS, so the contents of the ISS definitely end up in the spec. As you said, this also has the advantage that you can run it.

Yes, about the ISS/RTL cross check: my take is that we're implementing the two separately (obviously! They are in different languages!), so I'd expect the RTL implementation to find some more bugs in the ISS and lots more corners in the spec.

I've also just pushed up some code (#3613) to add simple testing for the ISS. My plan is that each instruction will have an associated smoke test that gives examples of what happens in each of the corner cases.

**Comment by GregAC** [comment]
From the RTL side I've been implementing things independently of the ISS, in that I read the spec and implement the instruction as it specifies. My bring-up testing for any feature involves manually working out what the results of an operation should be based upon the spec and then checking the RTL does indeed do that. This is what has resulted in the RTL smoke test (a short program that runs various instructions and has expected register values at the end, those values were calculated by me, not just by running the smoke test in the ISS).

Now that the ISS is (almost) at the point we can run the ISS and RTL in parallel and cross check register values at every clock that will be run as the final stage of my RTL bring-up. At that point if I encounter any differences I won't just assume the ISS is correct and alter RTL to match but rather go back to the spec and look at the ISS code to understand what the difference is and where it's come from. For anything that isn't a clear error on either the RTL or ISS side I'll open an issue to discuss, otherwise a PR to fix (which itself can be used for discussion).

So I think between @rswarbrick and me writing the ISS and RTL respectively, @felixmiller writing software and @imphil reviewing as well as doings parts of the ISS and RTL work we have a good degree of cross checking.

Long-term, as @rswarbrick says, spec + ISS is golden reference in that the spec will be partially auto-generated from ISS source. For now with everything under development (those the ISA itself is pretty stable, various small things still being discussed, potential for further change with CFI and if we need anything new for performance reasons) I don't think anything is really regarded as the golden reference (in that if it says its the way something is done, everything must match it). This is mostly because the spec doesn't delve into all the corner cases yet (e.g. see https://github.com/lowRISC/opentitan/issues/3587), these are being found and specified as we come across them as we write implementations.

**Comment by GregAC** [comment]
I wonder if once we think we're at a point the spec can be considered our golden reference we should do a 'corner case review' where go through all the instruction descriptions one by one and think about corner cases just to double check we've not missed anything.

**Comment by cdgori** [comment]
Thanks for the comments @GregAC and @rswarbrick - this helps me to understand the strategy you are going for.  Spec + ISS as golden seems pretty reasonable, especially with the ISS smoke testing layered on top.

I think the idea of a 'corner case review' is a good one - I'm happy to participate if you think you would find another pair of eyes helpful.  But I'll defer to you collectively to decide when you've reached that golden reference point for the spec.

**Comment by imphil** [comment]
I guess this question has been answered in favor of keeping RTL and ISS always in sync, and that's what we test for. If there's a need to "de-sync" the two for an intermediate period, the recommended solution is to disable the relevant tests.
