### ISSUE TITLE
[otbn] Multiple increment flags in BN.LID / BN.SID

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#3588]
What should be the architectural behaviour if an instruction encodes `grd_inc = 1` and `grs1_inc = 1`? Should we signal an illegal instruction from the decoder? Or fail later in some way?

> estimate 3

**Comment by rswarbrick** [comment]
(Or ignore one of the increments?)

**Comment by imphil** [comment]
It's an illegal instruction and raises an alert.

**Comment by rswarbrick** [comment]
Cool. We should probably document this (I'll leave the issue open until that's done).
