### ISSUE TITLE
Topics for a contribution/collaboration guide

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#359]
We already have a [contribution guide](https://github.com/lowRISC/opentitan/blob/master/CONTRIBUTING.md) but this one is rather minimal and just gives a set of quick guidelines. It for example does not cover how and where we discuss things before creating a PR, who merges the PR once it is approved, how we link issues, etc. With more people boarding onto the project and everything becoming open soon, I think it would it would be very useful to work out a more detailed contribution or even collaboration guide. I don't see such a guide as the one-and-only truth that decides whether or not we accept contributions. There are always exceptions, for example when timing is very critical. Instead, this guide should be a golden model, i.e., how we would like to collaborate ideally.

The goal of this issue is primarily to collect a list of topics and points we want to have addressed in such a guide but NOT to discuss the solution for the individual points. Once we have a list of points we want to address, I will create a GDoc with a proposal where we can discuss individual points, and then transfer it to markdown as we do for example with IP specs.

Things I would like to have in the new contribution guide:

- Procedure for adding a new feature, major changes
- Where do we discuss implementation details/proposals before creating PRs
- How does a PR look like (single commit, multiple commits, many commits)
- Who should review PRs
- Who should merge the PR once it is approved
- How long do we wait for further reviews even though a PR is approved (time difference between contributors), wait at least for CI to pass
- Do we rebase and merge or squash multiple commits into a single one?
- How should commit messages look like?
- How do we reference open issues in PRs, commit messages? E.g. should we quickly summarize the outcome of a discussion to motivate the changes in a PR, commit message?
- What about TODOs?
- What about auto-generated files?
- Reference to coding style guides, usage of clang-format

Please let me know if you want additional things being discussed (if possible, link other related issues), or let me know if you do not agree with this plan. As mentioned above, this issue is just about collecting topics but not about discussing them.

**Comment by moidx** [comment]
This is being tracked somewhere else now.
