### ISSUE TITLE
[hw] hw/ dashboard and issues improvements

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/opentitan#3601]
The following issues were discovered upon reviewing D/V status of some modules.

 - [x] [flash controller checklist](https://docs.opentitan.org/hw/ip/flash_ctrl/doc/checklist/index.html#d1) says D1 signed off Nov 2019; I assume this is lingering from before and not representative of the current status. @tjaychen 
- [x] [key manager checklist](https://docs.opentitan.org/hw/ip/keymgr/doc/checklist) somehow dropped the `D1` `D2` etc labels before the tables; @tjaychen 
- [x] nmi_gen: do we still need this? @msfschaffner (#7299)
- [x] pwrmgr pointer in the `hw/` dashboard points to nothing. Issue with the .prj.hjson perhaps? @tjaychen 
- [x] ditto rstmgr
- [x] rv_dm points to the checklist template, not the rv_dm checklist. @tomroberts-lowrisc 
- [x] ditto usbdev (#7297)

In addition, we note the following suggested improvements

- [ ] for DV modules that are tested at the top level, their .prj.hjson should point to a bookmark of the top level test plan / dv plan for their section. @sriyerg et al
- [ ] the V1 checklist should indicate how to handle modules that are solely tested at the top level, since they will not have their own testplan and testbench. @sriyerg et al

**Comment by tjaychen** [comment]
yeah those are mistakes, flash / pwrmgr / etc had not officially reached D1
stage (i guess depending on what the definition of D1 is).
So the checklist was not created.
The keymanager one was just auto-generated, so nothing is populated yet.

I expect all of these modules to officially cross D1 status next week, so
will begin working on the relevant paperwork.

**Comment by msfschaffner** [comment]
`nmi_gen` will technically be removed in MS4, I think. but given that this is just a dummy, we can also remove the D/V status completely at this point such that it disappears from the dashboard.

**Comment by msfschaffner** [comment]
Just came across this issue again and updated it with the current status.
@sriyerg can you take a look at the two DV suggestions above and decide whether to spin them out into separate issues or whether they can be dismissed (such that we can close this issue)?

**Comment by msfschaffner** [comment]
Hey @sriyerg, just came accross this rather dated issue. Is there anything to be done here, still, or can we close this?

**Comment by sriyerg** [comment]
Let me take a look later tonight, thanks!

**Comment by GregAC** [comment]
I don' think this is relevant any more, closing.
