### ISSUE TITLE
[otbn] pseudo instructions in loop bodies

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#3607]
How do we want to handle pseudo instructions within loop bodies?

The issue here is that a pseudo instruction can be replaced by more than one machine instruction. Especially with `li` this is tricky, since here it depends on the immediate whether this will result in a sequence of 1 or 2 instructions.

At the end, the loop length immediate of the `loop` and `loopi` machine instruction has to match the count of machine (not pseudo) instructions.

Long term we also want to have pseudo instructions for `loop` and `loopi`. Then this issue is solved (when they are used).

But independent from that (as long as pseudo instr. for `loop`/`loopi` are not there, or later if they are not used), do we want to allow pseudo instructions in loop bodies? And if so, should the assembler automatically adjust the loop length immediate or does the author of assembly have to be aware of the number of resulting machine instructions?

**Comment by rswarbrick** [comment]
I'd suggest the "easy" option: don't use `li` in a loop body (at least until we have a magic pseudo-instruction for `loop` / `loopi`), and definitely don't mandate it in any style guide.
