### ISSUE TITLE
[otbn] Can the last instruction of a loop be a jump?

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#3609]
When the last instruction in a loop body is a `JAL`, the address that has to be pushed to the call stack is different in the last cycle of the loop. Do we want to support this, or do we want to mandate a `nop` following such an instruction?

**Comment by rswarbrick** [comment]
I think we should specify that the address pushed into the call stack is `pc + 4` regardless of the current loop iteration. Writers of software might well want to avoid putting a `JAL` at the end of a loop body, but I don't think it makes sense to worry about that in hardware.

As a separate note, I think that @imphil was wondering about whether to prohibit jump-and-link (and branches?) in loops entirely. If we do that, I guess this point is moot.

**Comment by rswarbrick** [comment]
"No" :-D We now raise an error if you do that.
