### ISSUE TITLE
[otp_ctrl/rtl] cannot read OTP after initialization

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#3624]
Hi Michael, 

For register ["direct_access_cmd"](https://github.com/lowRISC/opentitan/blob/master/hw/ip/otp_ctrl/data/otp_ctrl.hjson#L461), right now it is declared as `R0W1C` but not an external register. I had an OTP CmdInvErr I think it might be related to this reg.

After OTP initialization, the `otp_dai` state goes to `IdleSt`. I did the  following:
1). write data `1'b1` to `direct_access_regen`
2). pick address `h'6` by writing to `direct_access_address`
3). write data `1` to `direct_access_cmd` to read out some OTP data
But I get an error `CmdInvErr`. 

Looking at the waveform below, the `direct_access_cmd.read.de` is set to 1, but `direct_access_cmd.read.d` is set to 0 due to it is `w1c`.
I wonder if declaring the register as `external register` will solve this issue? Or did I miss any sequence?

![image](https://user-images.githubusercontent.com/11466553/94510881-bbc2e400-01cc-11eb-8293-869f7c899e23.png)

Thanks
Cindy

**Comment by msfschaffner** [comment]
Hey Cindy,

Concerning the programming sequence, step 1) is not required anymore (see updated programming guidance here: https://github.com/lowRISC/opentitan/pull/3456).
However, this is not the cause of the failure that you observe here.
I think your suggestion is correct, this command trigger reg needs to be `hwext` - see linked PR above.

Thanks!

**Comment by cindychip** [comment]
Thanks michael for the comments and quick fix. I will take away Step 1).
