### ISSUE TITLE
Tock UART has stopped working on Nexys FPGA

### ISSUE THREAD

**Issue by alistair23** [lowRISC/opentitan#3629]
Somewhere between commit 1d1febce1cf73071436dd4e31b2b2077e8fc9c84 (good) and commit e26a00ba788992c16ac362b76a857a48d39b24bc (bad) there has been a regression in Tock's UART printing.

With commit e26a00ba788992c16ac362b76a857a48d39b24bc instead of seeing any prints from Tock I only see this:

```
I00931 bootstrap.c:103] Processing frame #0, expecting #464
I00932 bootstrap.c:103] Processing frame #464, expecting #464
I00933 bootstrap.c:103] Processing frame #0, expecting #465
I00934 bootstrap.c:103] Processing frame #465, expecting #465
I00935 bootstrap.c:103] Processing frame #0, expecting #466
I00936 bootstrap.c:103] Processing frame #466, expecting #466
I00937 bootstrap.c:138] Bootstrap: DONE!
I00938 boot_rom.c:42] Boot ROM initialisation has completed, jump into flash!
�xx<�x��x�x<x�x�x<x��x�x��x��x<��x�x<��x<x�x<��x�x<x�x<��x��x��x��x�x�x<�x�x<�x�x��x<x��x�x<�x��x<x<��x��x��xx<��x�x<�x<x�x�x<��x�x<x<���x<�x<x�x<�xx<x<x�x��x��x�x<�x��x<�x�x��x<��x
```

It looks like the frequency is off, but I don't see any changes in the OpenTitan software between those commits to indicate that the UART clocks have changed.

**Comment by alistair23** [comment]
This commit looks like it has changed the UART clocks which causes the failure

```diff
commit dc19cf91accd869fdd9e2fd2296053194645c8d3
Author: Timothy Chen <timothytim@google.com>
Date:   Thu Aug 20 16:38:21 2020 -0700

    [dv] update dv template to also include derived clocks
```

Is it possible to get notified of breaking changes like this?

**Comment by imphil** [comment]
@alistair23 this change is only relevant to the DV environment (e.g. when simulating with VCS or Xcelium). If you're using Verilator or an FPGA build, the UART baud rates haven't changed.

However, the FPGA design is currently known to fail timing. That means, depending on luck, a bitstream might or might not work. We're working on it. I don't think there's tracking issue for that at the moment, but I'll ping you once I know it's working again.

Note also that as of #3401 we'll run tests on an FPGA in CI to hopefully find breaking changes much earlier and make your work less frustrating.

**Comment by alistair23** [comment]
Thanks for the info!

Interestingly it seems like this patch to Tock fixes the UART issue reliably: https://github.com/alistair23/tock/commit/98254cf287dc79b4c7f9f45485d94d16d51f837c so it does seem like something is wrong with the clocks Tock uses. I'm not sure what changed between those two commits though that caused this.

That's great to hear that you are improving the CI. I actually don't find the OpenTitan builds too unreliable though. Overall you guys do a great job.

**Comment by imphil** [comment]
That tock change looks good and necessary, it matches the configuration for the different targets that we have at https://github.com/lowRISC/opentitan/tree/master/sw/device/lib/arch.

**Comment by alistair23** [comment]
Yeah, I thought so as well.

Closing this with a PR submitted to Tock: https://github.com/tock/tock/pull/2133
