### ISSUE TITLE
[fpga][prim] Use Xilinx-specific primitives for integral clock dividers `prim_clock_div`

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#3634]
The `prim_clock_div` primitive currently uses `prim_flop`, `prim_clock_inv` and `prim_clock_buf` primitives internally to build up the integral clock divider.

For FPGA implementation is not ideal and the resulting implementation is quite fragile when it comes to defining the clock constraints (see #3625). Instead it is recommended to explicitly instantiate BUFGCE/BUFHCE primitives on Xilinx FPGAs to build integral clock dividers as outlined here:

- https://forums.xilinx.com/t5/Implementation/Deriving-a-slow-clock/m-p/672350/highlight/true#M14258
- https://forums.xilinx.com/t5/Other-FPGA-Architecture/How-to-divide-a-clock-by-2-with-a-simple-primitive-without-Clock/m-p/1115993/highlight/true#M39250

**Comment by tjaychen** [comment]
@vogelpi thanks for the issue! please see #2676 also where some of this is discussed. 
I think my main concern was that I did not want to create non 50/50 duty cycle clocks.

**Comment by vogelpi** [comment]
Thanks @tjaychen for your input and the link to the other issue. Reading the Xilinx posts I also thought the duty cycle might be problematic but wasn't sure. It's good to know that you  already reasoned about this and came up to this implementation with good reasons. We probably don't need to change this. But we should find a way to make it more robust for the constraints.

Currently the final clock buffer `prim_clock_buf` is not there on the FPGA as there is no Xilinx primitive defined (the generic is just a feed through). I now have defined this primitive. But what remains is to define an anchor point at the input.

**Comment by vogelpi** [comment]
Alright, as input anchor point, I have now used the output of the PLL. I think we can close this.
