### ISSUE TITLE
[fpga][otbn] substantial negative slack

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#3636]
Yesterday evening, we noted a big increase in FPGA implementation time which caused most CI runs to fail. As a result, we reverted the last PR that went in before we started noting the failures (see #3630). This morning CI was more or less back to normal.

However, since I and other people noted CI failures suddenly occurring for other PRs even before the reverted PR was merged (they including the reverted one were fine last week), I had a closer look. It seems that a recent OTBN PR (#3471) merged during the weekend is the root cause of the troubles. From what I see, this PR added the wide register file inside OTBN and led to a big increase in WNS (now more than -10ns, before -0.9ns).

I suspect that this causes Vivado to heavily optimize and in the end CI fails because the FPGA build gets a timeout (after 2h). I think the reason for not seeing the failures this morning but only yesterday evening is the higher load of the pipeline during that time.
 
We should definitely do something about this.

**Comment by vogelpi** [comment]
Attached is an excerpt from the timing report. 

[timing_report.txt](https://github.com/lowRISC/opentitan/files/5306865/timing_report.txt)

I think short term we should
- Increase the CI timeout
- Lower the frequency
- (See how OTBN or it's ALU can be mapped better to FPGA.)

**Comment by vogelpi** [comment]
@imphil @GregAC this is probably relevant to you

**Comment by GregAC** [comment]
Ah tricky, I think short term we'll need to do something quick and ugly to stub out OTBN from the FPGA build.

Long-term we may be able to structure the OTBN ALU to fit nicely in the FPGA but I don't think it's something we'll have time for in the short-term (or we simply bring down the FPGA frequency so it works).

**Comment by vogelpi** [comment]
Something that is certainly worth trying is to use LUTRAM instead of FFs for the register files (just on FPGA of course). This is super easy to achieve (I think just the regfile needs to be minimally adapted, remove the reset or so) and gives substantial savings on LUTs and FFs. But it won't give us back 10ns of delay obviously.

**Comment by vogelpi** [comment]
Out of curiosity, I had a look at the register files. Using LUTRAM gives us back almost 5ns on the critical path. That's much more than I expected. I have done a PR.

**Comment by cdgori** [comment]
I looked at this timing path quickly.  I do not know exactly how Vivado infers different types of adders (I know it much better in DesignCompiler), but if I understand what I am seeing, this path is through the Y adder into flags_q.C (pardon the notation).

The target FPGA part has 4-bit carry lookahead chains as macrocells, and I believe I see 64 of them cascaded (to make the 256-bit adder).  Do we need to think about pipelining here or structuring this to map onto DSP slices instead?  Basically I am wondering if we getting a bad mapping because our arithmetic structure doesn't match the characteristics of the macro primitives? (or if this should even be a priority vs a clean standard-cell implementation that uses something "fancier" than a CLA adder, which is sort of another interesting question)

**Comment by GregAC** [comment]
My current approach is I don't worry about FPGA implementation and focus exclusively on ASIC implementation. I'd only want to add pipelining if it was required to make timing closure on ASIC. Some RTL tweaks to make it map to FPGA better may be a good idea but I wasn't planning at looking at that until we've got some feature complete RTL and some initial implementation results to understand where we are frequency and area wise.

I think the current approach of going to 10 MHz on the frequency should mean we don't need to worry about FPGA implementation, let's wait and see what the MAC implementation looks like on FPGA!

**Comment by cdgori** [comment]
To quote Rupert (I believe), "seems sensible" :)

**Comment by vogelpi** [comment]
Both PRs addressing this issue have been merged now. I am thus closing the issue.
