### ISSUE TITLE
[fpga] Invalid input clock frequency for BUFGMUX

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#3637]
Currently we get a notable amount of warnings during the FPGA build related to invalid input clock frequencies for BUFGMUX cells similar to:
```
WARNING: [Power 33-230] Invalid input clock frequency for top_earlgrey/u_rstmgr/u_sys_aon_mux/gen_xilinx.u_impl_xilinx/bufgmux_i. Out of range!
```
Most of these warnings originate inside rstmgr where we use `prim_clock_mux2` primitives for muxing resets. Some more warnings come from within spidevice and debug module. I wonder if those warnings can be avoided by associating the affected resets with a clock (just using a Vivado constraint) or by defining constraints for the SPI/JTAG clocks, respectively.

I don't know if this is critical, it could be related to #3606.

**Comment by vogelpi** [comment]
@tjaychen this might be relevant to you.

**Comment by msfschaffner** [comment]
@vogelpi can you double check whether this warning still persists?

**Comment by msfschaffner** [comment]
CC @a-will

**Comment by a-will** [comment]
After the introduction of the NoFpgaBufG parameter, this issue likely no longer applies.

**Comment by msfschaffner** [comment]
Yeah, also this is a very old issue (from 2020).
Let's close this - we can spawn another one if it turns out to become a problem again.
