### ISSUE TITLE
Explicit X's in case statements/ternary statements

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#366]
In commenting on a PR with ternary statements, I noticed an OpenTitan practice that I find alarming: Setting variables to X in the case of unhandled defaults.   This is also recommended in the style guide: 
https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#dont-cares-xs

Now this is great in simulation, don't cares propagate through the whole system and cause assertions to fire everywhere.  

However in a real device (ASIC or FPGA, doesn't matter) a silently uncaught X can cause a disaster!   Furthermore in silicon, cosmic ray events, or external tampering (!) can cause states to fall outside their usual allowed enumeration values, and these are exactly the kind of events that one should catch in the defaults.

If there are defaults that we think should "never happen" shouldn't we explicitly catch them and raise an exception or an alarm?

**Comment by taylor-bsg** [comment]
In the coding guidelines used for BaseJump STL,  BlackParrot and BaseJump Manycore, we use the macro approach proposed here and clarify that ‘X is for simulation and not for synthesis. This has served us well.

The write up is under the heading

“Use don’t cares (X) only in simulation; not in synthesis”

In:

https://docs.google.com/document/d/1xA5XUzBtz_D6aSyIBQUwFk_kSUdckrfxa2uzGjMgmCU/

**Comment by msfschaffner** [comment]
Welcome to OpenTitan @taylor-bsg :), and thanks for pointing us to your style guide. We will take that into consideration.

@martin-lueker what's the status on your side on this issue?

**Comment by mwbranstad** [comment]
Hi Michael,
I have a question about an unrelated issue regarding the prim_lfsr, which shows you as author. Is this email an ok forum for you to discuss?

**Comment by msfschaffner** [comment]
Hi @mwbranstad, 

I'll be happy to answer your question regarding to `prim_lfsr`, but since this is unrelated to this GitHub issue, I would like to ask you to open up a separate issue on GitHub, and assign it to me and label it as a question. You can do that by clicking here: https://github.com/lowRISC/opentitan/issues/new

**Comment by martin-lueker** [comment]
Hi @msfschaffner, @taylor-bsg 
   I fully agree with you @taylor-bsg, and that is exactly where we are going with this macro.  The status is that this fell on the back burner in the last couple weeks.   I should have time very soon for it though.  I will send an update when I make the PR's (however there will probably be two, one for the style update, and then after that is approved, and then one for deployment of the macro.).
-Martin

**Comment by tjaychen** [comment]
@martin-lueker 
actually @msfschaffner and I spoke with some of our other colleagues yesterday, and due to our style requirement of requiring `unique_case`, this may not be quite as straightforward.  I am going to summarize this quickly with @msfschaffner and report back.  We will let you know soon.

**Comment by mwbranstad** [comment]
Hi Michael, I think I opened a github issue as your instructed. Did you get it? Since many of these processes are new to me, it is very likely I did not do something properly.

**Comment by sjgitty** [comment]
@msfschaffner is this closeable now that we've executed on the style and coding changes?

**Comment by msfschaffner** [comment]
Yes, I'll close this as soon as the coding style is merged.

**Comment by msfschaffner** [comment]
For reference: https://github.com/lowRISC/style-guides/pull/12
