### ISSUE TITLE
[otbn] Alter BN.SID encoding to keep register files consistent

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#3666]
`BN.SID` is the only instruction (across base and bignum ISAs) that uses different bits for a register compared to all other instructions that have consistent use of the `grs1`,`grs2`,`grd`/`wrs1`,`wrs2`,`wrd`  fields. Being the sole exception for this is a minor pain for the decoder and I wonder if we should alter the encoding so it remains consistent across all instructions?

For instance we could place `grs2` in `BN.SID` where it is now for all the other instruction (bits [24:20]) and move the offset bits and the increment control to bits [11:7].

This does give two seperate kinds of immediate to deal with but we've already got multiple immediate types so less of an issue to deal with compared to introducing multiple sources for a register index.

> estimate 2

**Comment by rswarbrick** [comment]
That sounds like a good idea to me. I guess the tradeoff is just where we put the mux latency: if you reckon that we can absorb it more easily on the immediates, let's do that. Would you like me to push up a patch to the YAML?

**Comment by GregAC** [comment]
Actually thinking about this more it makes sense to do the above altering for both `BN.SID` and `BN.LID`. The reason being the D for `BN.LID` isn't actually a destination register, it's an index into the GPR to give us the WPR write register index. So what is labeled as the `grd` field in `BN.LID` makes sense to move to  the `grs2` location as it will feed into the `grs2` address port on the register file.

This has the pleasing side effect of making the location of the offset and increment control bits consistent again (though not consistent with `BN.MOVR`.

I'm happy to patch the YAML. Think I'm best doing that locally whilst I work on the decoder changes in case I come across anything else that's awkward, then I can do it all in one PR for the YAML (which I'll submit seperately to the RTL PR).

**Comment by imphil** [comment]
CC @wallento

**Comment by GregAC** [comment]
And indeed for `BN.MOVR` the same thing makes sense, the `grd` is actually doing a lookup on the GPR register file so could also move to the `grs2` field. Then the increment control fields will be consistent (as much as they can be anyway, as the `BN.LID`/`BN.SID` increment increment a memory address for one whilst the `BN.MOVR` increments always increment a register index).
