### ISSUE TITLE
[meta] need a tag for future issues

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/opentitan#3678]
Looking for a name to give to a tag for issues that aren't relevant at the moment, but we don't want to forget it. That way we won't push to close it, but don't need to think about it now. Suggestions: `for later`, `icebox`, `tabled`. Other suggestions?

**Comment by vogelpi** [comment]
I think we don't want these to look like low-priority issues that will eventually be looked at when everything else is done (i.e. never). As you say it's more about things that will be more relevant in the future or when the time is right.

What about something like `Don't forget`, `Keep in mind (for future)` or `Future topic`?

**Comment by rswarbrick** [comment]
Surely this doesn't matter since we're planning to get the issue count to zero? :-D

**Comment by cdgori** [comment]
I have seen `pre-tapeout` or `before tapeout` for very coarse "don't forget to do XYZ" type of issues ... if we need more granularity we could do `pre-D1` `pre-D2` etc. to indicate things that need to be cleared out before changing status.

**Comment by tjaychen** [comment]
i think we've temporarily decided to classify these with the labels enhancement and some low priority.
@msfschaffner

**Comment by msfschaffner** [comment]
ah yes, I believe this is related to #10318. @moidx

**Comment by msfschaffner** [comment]
See #10318 for the resolution.
