### ISSUE TITLE
[otbn] Setting MLZ flags in MULQACC

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#3683]
We might think of setting the MLZ Flags in the MULQUACC instruction if:

1. This is not a timing problem in the HW
2. We are sure that we do not clobber flags anywhere that are needed after an MULQACC where we can switch to the other FG

This would save us dummy instructions in the multiplication kernels, where this is performance critical.
I need to analyze #2 first before we move forward.

**Comment by imphil** [comment]
See also https://github.com/lowRISC/opentitan/issues/3683 for an earlier discussion on that.

**Comment by imphil** [comment]
Using https://github.com/lowRISC/opentitan/issues/2979 to track this.
