### ISSUE TITLE
[otbn] Make RSA in modexp.S run "standalone"

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3686]
Currently, the RSA code in modexp.S is split into sub-functions which need to be triggered separately from "Ibex" software. Create a wrapper that executes RSA/modexp from start to finish on OTBN. This can then also be used to make testing this algorithm ISS/block-level testing easier.

> estimate 4
> estimate 0 2020-10-17

**Comment by felixmiller** [comment]
> estimate 0 2020-10-17

Available with #3823 and #3813
