### ISSUE TITLE
[otbn] Prepare an overview of usable Control Flow integrity (CFI) mechanisms

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3690]
Come up with a "one pager" describing CFI approaches and narrow it down to the ones which might be applicable to OTBN. Share for discussion.

> estimate 16

**Comment by tjaychen** [comment]
@tjaychen just subscribing out of interest.

**Comment by imphil** [comment]
After a couple days of studying threat models and CFI approaches, I have a clearer picture, but also a new set of questions. As next step, I'll collect input from others working closely on OTBN before sharing a more fleshed-out version to the security meeting.
