### ISSUE TITLE
[otbn] load constant > 2047 and < 4096 to gpr

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#3698]
So I want to load the constant 2272 to a GPR.

When using the pseudo instruction: `li x21, 2272`
I get the following error when building: `Error: illegal operands addi x21,x0,2272`

Apparently this is directly replaced by the `addi` since the immediate is smaller than 2^12. However `addi` expects a signed immediate in the assembly, so 2272 needs to be written as -1824 to get the intended binary representation in the reg.

So it could be that that this just how it is specified in riscv assembly, that you need to provide the immediate as a signed number. But what confuses me is that if I add 4096 to the constant and do:
`li x21, 6368`
this produces:
```
lui	x21,0x2
addi	x21,x21,-1824
```

Here the assembler creates the negative immediate correctly (the `0x2` seems not correct though). So it seems that any positive number, but anything in the range 2048 to 4095, is accepted. This seems odd to me. But maybe there is some way to encode the literal I am not aware of. So not 100% sure whether this is a bug.

I would have thought that this translation is handled by the riscv (not otbn) assembler but since it shows up in the `*.dis` file, maybe I am wrong.

**Comment by felixmiller** [comment]
@rswarbrick

**Comment by rswarbrick** [comment]
Gah, this is a bug in the (OTBN) assembler. Thanks for the report: I'll sort it out today.

**Comment by rswarbrick** [comment]
About this:

> I would have thought that this translation is handled by the riscv (not otbn) assembler but since it shows up in the *.dis file, maybe I am wrong.

I didn't want to pass pseudo-instructions through to the underlying assembler, because I'm wary of it suddenly inserting instructions in certain cases that OTBN doesn't actually support (or certain future versions of binutils). I guess this is rather unlikely for `li`, but thought "how hard can expanding the operation be?". Apparently, harder than I thought :-)

**Comment by rswarbrick** [comment]
I think the expansion of 6368 is correct, by the way. I was worried I'd missed something (and will push up a checking patch to the back of the bug-fix PR in a sec), but I get this in the simulator for `li x7, 6368`:
```
lui          x7, 2                  | [x7 = 0x00002000]
addi         x7, x7, -1824          | [x7 = 0x000018e0]
```
(note that 6368 = 0x18e0)

**Comment by felixmiller** [comment]
Ah, right, of course, the `addi` is also sign extending, then the `0x2` for the `lui` is correct of course. And also the 2272 already needs to be expanded to two instructions then. Thanks for looking into it.

> I didn't want to pass pseudo-instructions through to the underlying assembler

Yes, I think that is the right approach. The only thought that bothers me is that this probably also prevents using constants (i.e. the `.equ` directive) and this would be really helpful. Or is there some other way to achieve it? Supporting it in the otbn-as maybe?

**Comment by rswarbrick** [comment]
You're right: `.equ` won't work with `li`. I wonder whether we should just pre-process with CPP for that sort of thing. Otherwise, I agree: we'll need to teach `otbn-as` about `.equ` lines.
