### ISSUE TITLE
[regtool] multi-reg displays enum for every generated field

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#3703]
In [OTP_CTRL spec](https://docs.opentitan.org/hw/ip/otp_ctrl/doc/index.html#Reg_err_code_0), the `enum` description is generated for every field in the multi-reg. For OTP register `err_code`, this enum is very long and makes it hard to read the spec. It would be nice to display the `enum` only once.

**Comment by tjaychen** [comment]
this might be something i did with my most recent multireg change.
Cindy do you recall if it used to behave like this..?  

I can patch this pretty quickly tomorrow.

**Comment by cindychip** [comment]
Hey Tim,
Thank you for your help. It would be great if you can help. I remember vaguely that it was not like this before (from alert_handler spec).

**Comment by cindychip** [comment]
Close via #3744
