### ISSUE TITLE
RFC: PMP side-loading

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#3712]
## Objective

Part of the boot process will require enabling code execution in a memory region once the signature of code in that region has been verified (the jump from mask ROM into ROM_EXT which ROM_EXT code will be in flash). One way to accomplish this is via a PMP region. We are exploring the idea of controlling this via a separate hardened comparator block in hardware.

## Design Options

The basic idea is to add an interface to Ibex that allows modification of PMP regions. This can be done with differing levels of flexibility, which can be broadly categorised into:

1. Full flexibility - The interface will allow full modification of all PMP regions
2. Limited flexibility - The interface can only be used to modified aspects of PMP regions and/or can only modify a specfic PMP region.

I have put an RFC document together proposing a design from category 2. It introduces a couple of new CSRs (which will be placed in the custom CSR space). The CSRs specify a PMP entry and a PMP config. A new top-level signal is added 'pmp_sideload_i'. When this signal is asserted the PMP config is written into the specified PMP entry.

Please see the [proposal document](https://docs.google.com/document/d/1N5tUZIAHUDkaby9x8XjdIAKb5kCmONf72KZq4KLVk0M) for more details

**Comment by GregAC** [comment]
As we've had broad discussion on this issue for a while I intentionally came up with something fairly concrete to focus the discussion on what we might actually do, so feel free to wildly disagree with what is proposed :)

**Comment by GregAC** [comment]
I've also added a section on the hardened comparator to the linked [proposal document](https://docs.google.com/document/d/1N5tUZIAHUDkaby9x8XjdIAKb5kCmONf72KZq4KLVk0M)

**Comment by lenary** [comment]
Adding @silvestrst as he's working on the Mask ROM lockdown module.

**Comment by imphil** [comment]
@GregAC Is this RFC still relevant now that we implemented ePMP?

**Comment by GregAC** [comment]
No

**Comment by tjaychen** [comment]
Just to clarify, the reason we are dropping this because we already have redundancy through shadow cores, is that right?

**Comment by GregAC** [comment]
That's an orthogonal issue really. The sideload was just looking unwieldy and complex, it was felt better to use standardized features instead. Suitable hardening is required which will be a combination of the shadow core and software but then if we had side-load we'd also need to have hardened that.

**Comment by tjaychen** [comment]
sounds good.
