### ISSUE TITLE
Keymgr Operation Results

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#3719]
@tjaychen 
Can you confirm if keymgr operation results below are expected, especially those with question mark as they either have error status without interrupt, or have interrupt without error status?

Assume life cycle doesn't disable keymgr and there is no other error like version error.

| state | operation | next state |op status|intr_err|
|------|-----------|-----------|--------|--------|
| StReset |advance state|go to StWipe for several cycle and then StInit| DONE_SUCCESS |No|
| StReset |gen_sw_output|| DONE_ERROR |Yes|
| StWipe |advance state|will enter StInit regardless this OP| DONE_ERROR |Yes|
| StWipe |gen_sw_output|will enter StInit regardless this OP| DONE_ERROR |Yes|
| StCreatorRootKey/StOwnerIntKey/StOwnerIntKey |gen_sw_output|| DONE_SUCCESS |No|
| StCreatorRootKey |advance state|StOwnerIntKey| DONE_SUCCESS |No|
| StOwnerIntKey |advance state|StOwnerIntKey| DONE_SUCCESS |No|
| StOwnerIntKey |advance state|StDisabled| DONE_SUCCESS |Yes?|
| StDisabled, StWait or other undefined value|advance state|No change| DONE_ERROR |No?|
| StDisabled, StWait or other undefined value |gen_sw_output|| DONE_ERROR |No?|

I haven't tested gen_hw_output, but I guess it should have same results as gen_sw_output, right?

I also find below results when both `inti` and `start` in `control` reg are programmed to 1 at the same time. Please confirm if they make sense

- `init` takes effect when it's in StReset and is ignored in the other states. Also will be clear after any operation is done.
- `start` will trigger error when it's in StReset.

[Added] One more observation. 
When it's in StDisabled, StWait or other undefined value, alert will be sent forever until reset occurs. Is this expected?

**Comment by tjaychen** [comment]
@weicaiyang would it help if i included an expected error table like this into the programmers model?

To your questions, I don't believe my intent was to continuously error while in one of the undefined states.  I will correct that.
I believe my intent is that once we are in disabled state, every time we call an actual operation will cause an error, but not necessarily trigger an error just by being in that state. 

I'm a bit confused by the entry of `StOwnerIntKey` advancing to `StDisabled`, that shouldn't happen unless there was an error.
Is that what you mean? 

I didn't think about the case where init / start were programmed at the same time. I think the behavior you're observing is what happens right now, but I'm not sure if that's the right behavior.

**Comment by tjaychen** [comment]
i'm also seeing some other coding confusion around `init` and `start`, i'll clean that up too.

**Comment by weicaiyang** [comment]
> @weicaiyang would it help if i included an expected error table like this into the programmers model?

Yes, it definitely helps. 

> To your questions, I don't believe my intent was to continuously error while in one of the undefined states. I will correct that.
> I believe my intent is that once we are in disabled state, every time we call an actual operation will cause an error, but not necessarily trigger an error just by being in that state.
> I'm a bit confused by the entry of `StOwnerIntKey` advancing to `StDisabled`, that shouldn't happen unless there was an error.
> Is that what you mean?

SW sees some problem or may be done with keymgr, then it advances to `StDisabled`. The result for this is `status=DONE_SUCCESS` with `interrupt error` triggered. I'm fine if we define this behavior. Just want to confirm it.

> I didn't think about the case where init / start were programmed at the same time. I think the behavior you're observing is what happens right now, but I'm not sure if that's the right behavior.

I accidentally set both `init` and `start`, then observed this. If we're fine with current behavior, perhaps document `init` is ignored when it's not in `StReset` state. When `init` and `start` are set in `StReset`, both are executed. seems reasonable that `init` moves state to `StInit` and `start` triggers error

**Comment by tjaychen** [comment]
for the `StOwnerIntKey` to `StDisabled` case, is the error you're seeing because we're in error state? And thus related to the other issue of constant alerts while in disabled state?

Let me clean up init/start a bit. I meant for those to be mutually exclusive. It definitely doesn't make a ton of sense for the key manager to init when there's actually an error condition.  And you're right, after the init state, the init doesn't really do anything anymore.

**Comment by weicaiyang** [comment]
> for the `StOwnerIntKey` to `StDisabled` case, is the error you're seeing because we're in error state? And thus related to the other issue of constant alerts while in disabled state?

yes, I checked the code. It's the same issue. In `StDisabled`, err_code is set which triggered the interrupt error. Also, interrupt is edge triggered and err_code is set all the time, so there is no interrupt for operation during `StDisabled`

After fix, the table should be like this. `DONE_SUCCESS` will have no intr_error. `DONE_ERROR` always comes with intr_error and alert.
state | operation | next state | op status | intr_err
-- | -- | -- | -- | --
StReset | advance state | go to StWipe for several cycle and then StInit | DONE_SUCCESS | No
StReset | gen_sw_output |   | DONE_ERROR | Yes
StWipe | advance state | will enter StInit regardless this OP | DONE_ERROR | Yes
StWipe | gen_sw_output | will enter StInit regardless this OP | DONE_ERROR | Yes
StCreatorRootKey/StOwnerIntKey/StOwnerIntKey | gen_sw_output |   | DONE_SUCCESS | No
StCreatorRootKey | advance state | StOwnerIntKey | DONE_SUCCESS | No
StOwnerIntKey | advance state | StOwnerIntKey | DONE_SUCCESS | No
StOwnerIntKey | advance state | StDisabled | DONE_SUCCESS | ~Yes?~ No
StDisabled, StWait or other undefined value | advance state | No change | DONE_ERROR | ~No?~ Yes
StDisabled, StWait or other undefined value | gen_sw_output |   | DONE_ERROR | ~No?~ Yes




> Let me clean up init/start a bit. I meant for those to be mutually exclusive. It definitely doesn't make a ton of sense for the key manager to init when there's actually an error condition. And you're right, after the init state, the init doesn't really do anything anymore.

**Comment by tjaychen** [comment]
Slightly different from the table.

In `StReset`, any operation should generate error (i'm fixing that right now).  Only valid command should be `init`.
I've also updated such that it is not possible to issue a command in `StWipe` since it is a transition state (basically the `regwen` will be 0).

**Comment by weicaiyang** [comment]
> Slightly different from the table.
> 
> In `StReset`, any operation should generate error (i'm fixing that right now). Only valid command should be `init`.
> I've also updated such that it is not possible to issue a command in `StWipe` since it is a transition state (basically the `regwen` will be 0).

`StWipe` lasts for several cycles. What happens if keymgr receives an operation?

**Comment by tjaychen** [comment]
i have changed in the latest PR (i pushed it as draft for you to look at)
so that after INIT is called, the regwen goes to 0.
This means it is no longer possible for software to make modifications to
the CONTROL register until the init is complete.

At least that's my intent.

**Comment by weicaiyang** [comment]
Can you also confirm how to trigger all the error defined in err_code reg?
INVALID_OP: it's the error from what we just discussed in above table.

INVALID_CMD: I look at the RTL. Looks like it's either one hot check of command (adv, gen_id, gen_out) or FSM error. But we can only issue one of adv, gen_id, gen_out, so it will be one-hot unless we force internal value. FSM error is also in a unreachable branch (default branch of FSM), so we need force to trigger it as well. Please correct me if it's not right.
`assign kmac_op_err = kmac_cmd_err_i | kmac_fsm_err_i;`

INVALID_KMAC_INPUT: it's due to version error for gen sw/hw out

INVALID_KMAC_DATA: check kmac data if they're all 1s or all 0s

**Comment by tjaychen** [comment]
hey @weicaiyang, you are right on all of these.
I will make sure to add an error code section to the markdown.

Regarding `invalid_cmd`, that's honestly meant to be more of a hardware failure.  It is NOT something I would expect normal software / DV to trigger.

**Comment by weicaiyang** [comment]
> hey @weicaiyang, you are right on all of these.
> I will make sure to add an error code section to the markdown.
> 
> Regarding `invalid_cmd`, that's honestly meant to be more of a hardware failure. It is NOT something I would expect normal software / DV to trigger.

I see. Thanks @tjaychen

**Comment by tjaychen** [comment]
@weicaiyang i think we can close this one now right?

**Comment by weicaiyang** [comment]
> @weicaiyang i think we can close this one now right?

yes, thanks for reminding.
