### ISSUE TITLE
reggen spits out a warning about the extra key "hier_path" in ALERT_HANDLER

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#3732]
The extra key was added by PR #2486 (commit 0768219). Looking at [this conversation](https://github.com/lowRISC/opentitan/pull/2486#discussion_r441204573), @weicaiyang originally added it to the list of optional keys in reggen, but then had to remove it again.

Can we just add it back in? I've attached a patch that fixes up the obvious breakage, but I don't want to do a PR without understanding how this is all supposed to work. Oh, and I had to rename the file .txt because apparently GitHub doesn't support patches (huh?!).

[0001-Add-hier_path-to-list-of-optional-keys-in-validate.txt](https://github.com/lowRISC/opentitan/files/5341470/0001-Add-hier_path-to-list-of-optional-keys-in-validate.txt)

@weicaiyang, @eunchan

**Comment by weicaiyang** [comment]
I was not aware of the warning. Looks like it makes sense to add it. Thanks for fixing this.
@eunchan WDYT?

**Comment by eunchan** [comment]
Yup. I agree adding it to optional field.
