### ISSUE TITLE
[sw] ROM_EXT Manifest Parser

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#3734]
#3561 Contained the initial rom_ext manifest parser. This is the "things we can address in a follow-up" pull request.

There is already #3576 which covers auto-generating the offset header from a machine-readable format description. 

Things that are missing:
- [x] Get the entry point of a ROM_EXT (as a C function pointer that we can call into)
- [x] Get the potential `mtvec` address of a ROM_EXT (we may not end up using this, but we should be able to read it out).

Things we have discussed and need to change:
- [ ] Instead of the parser doing the memcpy, the parser should just return the address and size of the long fields, and let other software do the copy if it needs to - this should avoid memcpy's unless necessary. Given we know the DIF will have to copy from addressable memory into either hmac or OTBN, there's no point in us doing a copy from Flash into RAM (both addressable) if we can avoid it. This came from discussions with @alphan and @silvestrst. 
- [ ] Using non-volatile pointers rather than `mmio_region_t`.

**Comment by alphan** [comment]
Should we also mention using `mmio_region_t` vs pointers?

**Comment by lenary** [comment]
Done.

**Comment by silvestrst** [comment]
Looks good, thank you for opening this issue @lenary !

**Comment by lenary** [comment]
Some issues from the generator PR (#3576)
- [ ] `--output-dir` documentation
- [ ] `whic`/`which` typo.
- [ ] TODOs in Field Descriptions

And some additional features
- [ ] entry address
- [ ] interrupt vector
- [ ] start of signed area.

**Comment by lenary** [comment]
There are improvements coming in #3800 and #3590 (which need to land in that order).

**Comment by lenary** [comment]
#3839 updates the image length getter to return all the extents together, which should be useful for both signing and any range checking that might need to happen.

We need to more fully document the movement of trusted vs untrusted values in these accessors, for instance the pointers to the extension values are totally unchecked, and the returned values may end up pointing outside the signed area.

**Comment by moidx** [comment]
Superseded by #5955
