### ISSUE TITLE
[keymgr] reg value of err_code only lasts for 1 cycle

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#3740]
@tjaychen 
It's almost impossible to read the err_code by SW as it's only available for 1 cycle
![Screen Shot 2020-10-07 at 4 20 53 PM](https://user-images.githubusercontent.com/49293026/95397845-1c32df00-08b9-11eb-9cac-9ab92ad07190.png)

waveform: 
/edascratch/weicai-opentitan/ot/keymgr.sim.vcs/try_stwipe/0.keymgr_op_at_wipe_state/out
verdi -ssr Verdi.ses &

**Comment by tjaychen** [comment]
yes good catch i will fix this.
