### ISSUE TITLE
[dv] Xcelium does not support arrays of covergroups

### ISSUE THREAD

**Issue by gaurangchitroda** [lowRISC/opentitan#375]
Hi Verif-Team,

As some of you may be already aware, Xcelium tools does not seem to support arrays of covergroups. We can make the code more concise by having arrays of covergroups. (for example, taking array of size NUM_GPIO of covergroup that is meant for each gpio pin).

As a workaround, we can enclose covergroup inside class and take array of objects of that class type. However, SystemVerilog LRM does not seem to clearly suggest that array of generic covergroups is not supported inside class. We can still confirm on this.

Best Regards,
Gaurang

**Comment by msfschaffner** [comment]
Has this issue been addressed in the mean time?

**Comment by sriyerg** [comment]
Yes, we can close this issue. Wrapping covergroups in classes has become the go to method of doing this.

**Comment by cindychip** [comment]
I believe this is done. We wrapped it around with a class.
