### ISSUE TITLE
Broken links on website in README output

### ISSUE THREAD

**Issue by mithro** [lowRISC/opentitan#3750]
Go to https://docs.opentitan.org/ -- click the `README` link on the left side.

Issues;
 * Broken OpenTitan logo
 * CONTRIBUTING link in the page goes to non-existent https://docs.opentitan.org/README/CONTRIBUTING.md
 * LICENSE link in the page goes to https://docs.opentitan.org/README/LICENSE

The CONTRIBUTING page on the left side has similar issues.

It is unclear to me if the README / CONTRIBUTING files were actually meant to be included in the output or not?

**Comment by msfschaffner** [comment]
Thanks for reporting this (somehow this issue got lost).

The logo issue has been addressed by now, but the links still seem broken.

I will create PR shortly to fix this.
