### ISSUE TITLE
[otbn] optimize/improve modexp assembly

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#3776]
Now that modexp is fully documented we can tackle some improvements:

- [x] **Rename subroutine labels**

- Use labels that fit to our terminology
- Use prefix/suffix for externally callable routines
- Stick with either camelCase or snake_case

- [x] **Improve calling conventions**
- Currently we have a quite complex calling convention with the four 256-bit descriptors at the beginning of the dmem image. This includes some redundancy and it should be possible to simplify this. Especially with a fully self contained RSA implementation

- [x] **remove unnecessary pointer reloading**

- [x] **Don't reload pointers from dmem in subroutines**
- It should be possible to avoid this to reduce dependencies

- [x] **add `modexp_65537` routine**
For RSA verify we currently don't use the full constant-time `modexp` routine  for obvious reason but stitch together the pub exp with multiple calls to `mulx`. We should add this to the assembly.

- [x] **remove some unnecessary instructions**

- [x] **potentially unify some subroutines**
There are some subroutines (e.g. conditional subtract) which are present multiply times with only slight differences. It might be possible to combine those in one. This is always a trade-off though between code size and performance, since some copying between regs might be needed. Another possibility is to use them inline in some cases

> estimate 8
> estimate 0 2020-11-02

**Comment by imphil** [comment]
Fixed in #3995
