### ISSUE TITLE
How to track D/V status of modules that are developed in separate repos (e.g. Ibex)

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#3808]
Split out from https://github.com/lowRISC/opentitan/pull/3772

@sriyerg: Ibex is verified in a separate repo. We verify this wrapper at the chip level (i.e. close the coverage on this module). Our dashboard has a separate heading for Ibex, which is where the status (and Ibex's checklist) should be tracked. IMO having a checklist for this testbench-less module does not seem useful. Alternately, we treat this the same way as rstmgr and others verified at chip level. But if we do, then this has no relation to Ibex checklist / status. So we ought to decide if this is really of value.

**Comment by sriyerg** [comment]
To clarify, this is regarding maintaining the checklist for `rv_core_ibex`.

**Comment by rswarbrick** [comment]
The plan is now that we're going to wire Ibex testing in with dvsim, so this should be a non-issue. (Obviously, *completing* the verification is another matter, but maybe beyond the scope of this! :-D)
