### ISSUE TITLE
[padctrl] Additional Pinmux Features

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#381]
This issue came up during our recent silicon meeting, and deals with the question whether additional features such as hardware selection signals and custom design-time default mappings are needed for our basic `v0.5` target. 

Some background first:
- The current pinmux implementation just uses a global default value for all periph and pad mux-select signals when coming out of reset, which basically causes all peripheral inputs to be tied to constant 0, and all MIO pad outputs to be set to high-Z. 
- All mux select signals are connected to SW controllable CSRs in the pinmux, and there is no way to use other signals coming from hardware to steer the muxes.
- Available peripheral IOs can either go through the full pinmux (MIOs), or they bypass the pinmux and become dedicated IOs (DIOs). There is no other way at the moment to specify the partial mux connectivity in the top-level `.hjson` (i.e., we cannot specify the full connectivity matrix).
- See [pinmux spec](https://github.com/lowRISC/opentitan/blob/master/hw/ip/pinmux/doc/pinmux.md) for more info.

Open points (feel free to add more if you come across them):
1) Do we need custom default mappings at reset for our current boot sequence (e.g., for UART TX, or some GPIO pin that needs to be sampled), or can we rely on the bootrom to program the pinmux before anything is transmitted through MIO? 
2) How shall we deal with the SPI / JTAG ports that are currently muxed using a DIP switch input signal?

In both cases we could just work around using DIOs at the moment, and wire the signals up by hand in `top_earlgrey`. I.e., UART could be directly connected to DIOs instead of going through the pinmux, and SPI / JTAG could be muxed using a dedicated mux steered by a DIP switch signal that is mapped to DIO. This may however lead to a target-dependent code section in `top_earlgrey`, and we may have to use an `'ifdef` for that.

Is that acceptable, or should we expedite some of the features such that they can make it into the `v0.5` code-base in time?

**Comment by tjaychen** [comment]
@msfschaffner i think everyone described here has been implemented in some way. 
What do you think? Feel free to close the issue.

**Comment by msfschaffner** [comment]
Indeed, this one can be closed down. Thanks!
