### ISSUE TITLE
Unify enable register behavior

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#3815]
Not sure if we can unify the regwen behavior, so that we can have a common test to verify it easily.

Can I assume below are true for regwen?
1. if it's a regen register, it only contains one field which is the regen.
2. regwen default value is always enable. If it's one bit, it will be 1.
3. only support W1C, W0C. W1C means when it's cleared, can't enable it again except reset. W0C means it can be enabled/disabled multiple time without reset

If regwen is more than 1 bits (like keymgr it's 2 bits), how design behaves when we write random value to it
1. if write non all 1s value to W1C, will it clear the reg? Can we read back the written value?
2. if write non zero value to W0C, will it clear the reg? Can we read back the written value? 

It will be even better, if we always have same bit width for a regwen.

@tjaychen 
There are a few discrepancies in the keymgr.hjson.
1. looks like we want to make all regen 2 bits wide, but `ROM_EXT_DESC_EN`, `MAX_CREATOR_KEY_VER_EN`, `MAX_OWNER_INT_KEY_VER_EN` and `MAX_OWNER_KEY_VER_EN` are just 1 bit wide
2. may forget to add `ROM_EXT_DESC_EN` as regwen for `ROM_EXT_DESC_*`

**Comment by tjaychen** [comment]
thanks for catching the missing one on keymgr @weicaiyang!
I honestly think we should unify W0C for regwen.  That makes it consistent for software readback checks. 

If we expand to more than 1 bit (i know we don't have it yet), we should unify on one specific value (for example 101 for 3-bit, 10 for 2-bit, 1010 for 4-bit etc) to be "enable".  All other values should be disable. I think even in that case we can still support these as W0C, just ANY intermediate value is also "disable".  That is probably the safest / most consistent approach in my view.

@cdgori 
any thoughts Chris?

**Comment by cdgori** [comment]
That seems reasonable to me - a specific enable pattern per width, and all-others as disable.  

I'm probably missing the really specific contrast of "ANY intermediate value" here as opposed to "All other values" though?

**Comment by weicaiyang** [comment]
> thanks for catching the missing one on keymgr @weicaiyang!
> I honestly think we should unify W0C for regwen. That makes it consistent for software readback checks.
> 
> If we expand to more than 1 bit (i know we don't have it yet), we should unify on one specific value (for example 101 for 3-bit, 10 for 2-bit, 1010 for 4-bit etc) to be "enable". All other values should be disable. I think even in that case we can still support these as W0C, just ANY intermediate value is also "disable". That is probably the safest / most consistent approach in my view.

@tjaychen 
if W0C regwen is written with other value, will this value be stored in the reg or not? 
Is the enable value (10,101,1010) always same as default value? It's yes for now, but may be not always the case. If not, we may need to extract the enable value from hjson file.

**Comment by tjaychen** [comment]
i dont think we should assume the default value is always going to be
logical 1.  There will definitely be examples where a regwen is controlled
by hardware, and the conditions for those might be completely different.
For W0C, I think if you write 1 to it, nothing should happen (although I
have not double checked the behavior).

So if we imagine the register value is 101, my opinion is that if you write
110, it should end as 100 (ie, the 1 does nothing, and the 0 clears).
If we then take the approach of multi-bit regwen, 100 would then be
considered "disabled".

Does that make sense? This is a topic that's worth socializing at the
weekly meetings to make sure everyone is onboard.  But the above is my take.

**Comment by weicaiyang** [comment]
> i dont think we should assume the default value is always going to be logical 1. There will definitely be examples where a regwen is controlled by hardware, and the conditions for those might be completely different. For W0C, I think if you write 1 to it, nothing should happen (although I have not double checked the behavior). So if we imagine the register value is 101, my opinion is that if you write 110, it should end as 100 (ie, the 1 does nothing, and the 0 clears). If we then take the approach of multi-bit regwen, 100 would then be considered "disabled". Does that make sense? This is a topic that's worth socializing at the weekly meetings to make sure everyone is onboard. But the above is my take.

@tjaychen Thanks for the example. Now I understand more about the W0C behavior. 
Since writing 1 does nothing for W0C and writing 0 does nothing for W1C, if the regwen is modified to a non-enable value, both require reset in order to set it enable again. I'm not sure how we choose between W0C and W1C.

Agree, we should socialize this in next weekly meeting.
I think we just need to confirm below these 3 rules, then I can update our common enable register test. 
1. if it's a regwen register, the whole register only contains one field which is the regwen.
2. only support W1C, W0C.
3. regwen enable value is 1 for 1-bit, 10 for 2-bit, 101 for 3-bit, 1010 for 4-bit etc

**Comment by tjaychen** [comment]
thanks @weicaiyang , let me add this to the agenda and hopefully we will discuss it with a wider audience.

**Comment by tjaychen** [comment]
@lenary @silvestrst @alphan @mcy @gkelly 

Adding the software team. 
Do you guys have any opinions here? 

Specifically regarding point 2 and point 3 above?
For point 2, I think a lot of it comes down to how software chooses to support configuration redundancy checks (if we want to do it at all).  Writing 0's to clear sounded simple because whatever you write..is what you read back.

For point 3, are there places in our software where we want to check for the "enable" value of a regwen register? Because that could get kind of annoying if everything is different number of bits.

**Comment by silvestrst** [comment]
> For point 3, are there places in our software where we want to check for the "enable" value of a regwen register? Because that could get kind of annoying if everything is different number of bits.

For example, `dif_pwrmgr` has static `request_sources_is_locked` function, that is used further by public API like `dif_pwrmgr_request_sources_is_locked`. These do read the `REGWEN` register to check whether the relevant functionality is locked or not. These are used internally (error when trying to write into locked register) as well as to directly inform the caller whether something is locked.

> For point 2, I think a lot of it comes down to how software chooses to support configuration redundancy checks (if we want to do it at all). Writing 0's to clear sounded simple because whatever you write..is what you read back.

From my perspective there is not too much difference, however I think `w0c` is more natural, and if it is just a matter of preference then I would prefer that. However, if there are good reasons for having `w1c`, that is fine as well. That is my take, maybe others have stronger preferences.

**Comment by tjaychen** [comment]
thanks @silvestrst ! it would be good to hear what others think also.

Regarding the point on reading lock status back for other use, what in your mind would be a good way to handle this if we decided to extend to multiple bits for the lock register themselves? Do we have to use a single bit-width for the entire design? Or is there a good way to support different widths per module / DIF?

**Comment by alphan** [comment]
>only support W1C, W0C. W1C means when it's cleared, can't enable it again except reset. W0C means it can be enabled/disabled multiple time without reset

If these registers can be enabled/disabled multiple times without reset, why are they not `RW`? Is re-enabling done by other means?

> For point 2, I think a lot of it comes down to how software chooses to support configuration redundancy checks (if we want to do it at all). Writing 0's to clear sounded simple because whatever you write..is what you read back.

I think `W1C` is useful when we want to clear a single bit, e.g. pending interrupts, as it avoids a read-modify-write but I don't think this is relevant in this context and I agree with @silvestrst, `W0C` feels more natural here.

> For point 3, are there places in our software where we want to check for the "enable" value of a regwen register? Because that could get kind of annoying if everything is different number of bits.

Yes, as @silvestrst mentioned, DIFs have a `..._is_locked` function for functionality that can be locked. IMHO having different values for peripherals is not a big problem as long as it makes sense from a hardware/security perspective and these values are generated. If not, it would be nice to have a consistent value to avoid mistakes. But I think we should strive to be consistent within a peripheral though.

**Comment by tjaychen** [comment]
ah sorry, the `regwen` registers, especially those exposed to software directly are NOT meant to be enabled / disabled multiple times.  You configure whatever you want, lock it, and it is never modifiable again until next reboot.

The ones that are in a slightly different category are temporary configuration lock registers for blocks like aes, kmac, keymgr etc. Where once you "start" a transaction, you don't want any of the configured parameters to change until the transaction finishes.  These locks are self-set/clear, and not directly exposed to software. 

To your question about being consistent, I definitely think being consistent within a peripheral is not a problem. If it helps, maybe modules can define a parameter to indicate what should be considered a "valid" value? (all others would be considered invalid).  That way we can still stick with `w0c` and not have to worry too much about what exactly is an invalid value.

**Comment by alphan** [comment]
> The ones that are in a slightly different category are temporary configuration lock registers for blocks like aes, kmac, keymgr etc. Where once you "start" a transaction, you don't want any of the configured parameters to change until the transaction finishes. These locks are self-set/clear, and not directly exposed to software.

Thanks for the clarification!

> If it helps, maybe modules can define a parameter to indicate what should be considered a "valid" value? (all others would be considered invalid). That way we can still stick with w0c and not have to worry too much about what exactly is an invalid value.

That would be good.

**Comment by tjaychen** [comment]
this is completed (all regwen are now rw0c).
The multi-bit regwen should probably be handled as a different issue.
