### ISSUE TITLE
[alert_esc_if] Illegal use of a constant without an explicit width specification

### ISSUE THREAD

**Issue by tunghoang290780** [lowRISC/opentitan#3819]
![image](https://user-images.githubusercontent.com/53881329/96076625-9e477880-0e62-11eb-97f7-0a00fe5b64e7.png)

This may only raise an error with Xcelium but it can simply be fixed by add `2'b..`

**Comment by cindychip** [comment]
Thanks Tung for reporting this. Hope this PR would fix this: https://github.com/lowRISC/opentitan/pull/3820. Sorry for the inconvenience.

**Comment by tunghoang290780** [comment]
Fixed with PR #3820
