### ISSUE TITLE
Repeated Timer Interrupts

### ISSUE THREAD

**Issue by aroelke** [lowRISC/opentitan#3829]
I'm trying to make a timer function that periodically interrupts the main program to perform a task, but I can't get it to execute after the first time.  I'm configuring the timer the same way it's configured in dif_rv_timer_sanitytest.c and writing the interrupt handler in the same way as well, with the exceptions of rearming the timer with a new comparator value and re-enabling the counter at the end (after clearing the interrupt flag).  When I do this, not only does the interrupt not run a second time, but when I restart the program without reconfiguring the FPGA first I get errors trying to configure the timer.  Is there some other step I have to take in order to get the timer interrupt to repeat itself?

**Comment by imphil** [comment]
Thanks for your question. To better help you out we need to have a look at your source code.

Do you see the same problem in the timer sanity test? If not, can you either post your code, or modify the timer sanity test in a way that shows the problem?

**Comment by aroelke** [comment]
It seems to work when I make the change to the sanity test.  I copied the sanity test code back over to my file, making only a few small modifications, but it still doesn't work.  Here's my test code:
```c
#define TICK_FREQ_HZ 1000000
#define TIMER_FREQ 50000

static dif_rv_timer_t timer;

int main(int argc, char* argv[]) {
  uart_init(kUartBaudrate);
  base_set_stdout(uart_stdout);

  irq_global_ctrl(true);
  irq_timer_ctrl(true);

  mmio_region_t timer_reg = mmio_region_from_addr(TOP_PERSEUS_RV_TIMER_BASE_ADDR);
  CHECK(dif_rv_timer_init(timer_reg, (dif_rv_timer_config_t){.hart_count = 1, .comparator_count = 1}, &timer) == kDifRvTimerOk);

  dif_rv_timer_tick_params_t tick_params;
  CHECK(dif_rv_timer_approximate_tick_params(kClockFreqPeripheralHz, TICK_FREQ_HZ, &tick_params) == kDifRvTimerApproximateTickParamsOk);
  CHECK(dif_rv_timer_set_tick_params(&timer, 0, tick_params) == kDifRvTimerOk);
  CHECK(dif_rv_timer_irq_enable(&timer, 0, 0, kDifRvTimerEnabled) == kDifRvTimerOk);

  uint64_t current_time;
  CHECK(dif_rv_timer_counter_read(&timer, 0, &current_time) == kDifRvTimerOk);
  LOG_INFO("Current time: %d; timer theshold: %d", (uint32_t)current_time, (uint32_t)(current_time + TIMER_FREQ));
  CHECK(dif_rv_timer_arm(&timer, 0, 0, current_time + TIMER_FREQ) == kDifRvTimerOk);

  CHECK(dif_rv_timer_counter_set_enabled(&timer, 0, kDifRvTimerEnabled) == kDifRvTimerOk);

  while (true) {
    wait_for_interrupt();
  }
}

void handler_irq_timer(void) {
  bool irq_flag;
  CHECK(dif_rv_timer_irq_get(&timer, 0, 0, &irq_flag) == kDifRvTimerOk);
  CHECK(irq_flag, "Entered IRQ handler but the expected IRQ flag wasn't set!");

  CHECK(dif_rv_timer_counter_set_enabled(&timer, 0, kDifRvTimerDisabled) == kDifRvTimerOk);
  CHECK(dif_rv_timer_irq_clear(&timer, 0, 0) == kDifRvTimerOk);

  uint64_t current_time;
  CHECK(dif_rv_timer_counter_read(&timer, 0, &current_time) == kDifRvTimerOk);
  LOG_INFO("Current time: %d; timer theshold: %d", (uint32_t)current_time, (uint32_t)(current_time + TIMER_FREQ));
  CHECK(dif_rv_timer_arm(&timer, 0, 0, current_time + TIMER_FREQ) == kDifRvTimerOk);
  CHECK(dif_rv_timer_counter_set_enabled(&timer, 0, kDifRvTimerEnabled) == kDifRvTimerOk);
}
```
As far as I can tell, the only differences are the wait time between interrupts and not having the initial test setup, but I don't think I need the latter (beyond setting up the UART), do I?

**Comment by imphil** [comment]
@silvestrst can you have a look?

**Comment by mcy** [comment]
Does it behave differently if you remove the `wait_for_interrupt()` call, and spin instead? There might be some issues around the `wfi` instruction...

Can you show what gets printed to UART?

**Comment by silvestrst** [comment]
>> Does it behave differently if you remove the wait_for_interrupt() call, and spin instead? 

At the first glance I second that. I would try a busy loop like @mcy suggested and if that doesn't help then we should investigate further.

**Comment by aroelke** [comment]
No, the behavior is no different whether or not I have `wait_for_interrupt()` in the loop.  Here's the UART output:
```
I00002 irq_test.c:35] Current time: 0; timer theshold: 50000
I00003 irq_test.c:55] Current time: 50056; timer theshold: 100056
```

Just for comparison, here's the sanity test code that I modified to repeat its interrupt, which works for some reason (the value of `kHart` is 0 here):
```c
static dif_rv_timer_t timer;

// Flag for checking whether the interrupt handler was called. When the handler
// is entered, this value *must* be set to false, to catch false positives.
//
// This variable is volatile, since it may suddenly change from the compiler's
// perspective (e.g., due to an interrupt firing).
static volatile bool irq_fired = true;

// NOTE: PLIC targets need not line up with hart ids; in the future, we should
// generate hart ID constants elsewhere.
//static const uint32_t kHart = (uint32_t)kTopEarlgreyPlicTargetIbex0;
//static const uint32_t kComparator = 0;

static const uint64_t kTickFreqHz = 1000 * 1000;  // 1 MHz.
static const uint64_t kDeadline = 30000;          // 30 ms.

static void test_handler(void) {
  CHECK(!irq_fired, "Entered IRQ handler, but `irq_fired` was not false!");

  bool irq_flag;
  CHECK(dif_rv_timer_irq_get(&timer, 0, 0, &irq_flag) ==
        kDifRvTimerOk);
  CHECK(irq_flag, "Entered IRQ handler but the expected IRQ flag wasn't set!");

  CHECK(dif_rv_timer_counter_set_enabled(&timer, 0, kDifRvTimerDisabled) ==
        kDifRvTimerOk);
  CHECK(dif_rv_timer_irq_clear(&timer, 0, 0) == kDifRvTimerOk);

  uint64_t current_time;
  CHECK(dif_rv_timer_counter_read(&timer, 0, &current_time) == kDifRvTimerOk);
  LOG_INFO("Current time: %d; timer theshold: %d", (uint32_t)current_time, (uint32_t)(current_time + kDeadline));
  CHECK(dif_rv_timer_arm(&timer, 0, 0, current_time + kDeadline) == kDifRvTimerOk);
  CHECK(dif_rv_timer_counter_set_enabled(&timer, 0, kDifRvTimerEnabled) == kDifRvTimerOk);

//  irq_fired = true;
}

// Register our own IRQ handler by overriding a weak symbol in `handler.h`.
void handler_irq_timer(void) {
  LOG_INFO("Entering handler_irq_timer()");
  test_handler();
  LOG_INFO("Exiting handler_irq_timer()");
}

const test_config_t kTestConfig = {};

bool test_main(void) {
  irq_global_ctrl(true);
  irq_timer_ctrl(true);

  mmio_region_t timer_reg =
      mmio_region_from_addr(TOP_EARLGREY_RV_TIMER_BASE_ADDR);
  CHECK(dif_rv_timer_init(
            timer_reg,
            (dif_rv_timer_config_t){.hart_count = 1, .comparator_count = 1},
            &timer) == kDifRvTimerOk);

  dif_rv_timer_tick_params_t tick_params;
  CHECK(dif_rv_timer_approximate_tick_params(kClockFreqPeripheralHz,
                                             kTickFreqHz, &tick_params) ==
        kDifRvTimerApproximateTickParamsOk);
  CHECK(dif_rv_timer_set_tick_params(&timer, 0, tick_params) ==
        kDifRvTimerOk);
  CHECK(dif_rv_timer_irq_enable(&timer, 0, 0,
                                kDifRvTimerEnabled) == kDifRvTimerOk);

  uint64_t current_time;
  CHECK(dif_rv_timer_counter_read(&timer, 0, &current_time) ==
        kDifRvTimerOk);
  LOG_INFO("Current time: %d; timer theshold: %d", (uint32_t)current_time,
           (uint32_t)(current_time + kDeadline));
  CHECK(dif_rv_timer_arm(&timer, 0, 0,
                         current_time + kDeadline) == kDifRvTimerOk);

  irq_fired = false;
  CHECK(dif_rv_timer_counter_set_enabled(&timer, 0, kDifRvTimerEnabled) ==
        kDifRvTimerOk);

  LOG_INFO("Waiting...");
  while (!irq_fired) {
    wait_for_interrupt();
  }

  return true;
}
```

**Comment by mcy** [comment]
I don't see anything obviously different between the two code snippets you posted, except for `TOP_PERSEUS_RV_TIMER_BASE_ADDR`. Did you modify the hardware instantiation? That may make this a hardware issue rather than a software one...

**Comment by aroelke** [comment]
Sorry, I should have corrected that.  That constant has the same value as `TOP_EARLGREY_RV_TIMER_BASE_ADDR`.  I've been testing this on a vanilla earlgrey system, though.

**Comment by silvestrst** [comment]
Would it be possible to get a link to a github branch with the changeset to check it out locally?

**Comment by aroelke** [comment]
No, I'm afraid not.  It's not in a public repo.  The first code block I posted is the entire code for the program, though, except for header imports and the timer base address constant name.  All the other build scripts, linker scripts, entry code, etc. that's involved in building the code is the same between my code and the timer sanity test.

**Comment by aroelke** [comment]
It looks like the problem was a header issue; I forgot to include sw/device/lib/handler.h.  I removed my header imports from the code I posted to reduce the size of it since I assumed it didn't matter as much as it apparently does, but it seems I was wrong.  Thanks for all your help.

**Comment by silvestrst** [comment]
@aroelke glad you found a solution to your problem! That would explains it `INTERRUPT_HANDLER_ABI` if I am not mistaken then `__attribute__(interrupt)` makes sure that `mret` instruction is used to return from the interrupt handler.
