### ISSUE TITLE
[sw, testing] Allow mmio mocks to set all bits set with one cleared expectations

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#3847]
# Background

Present mock mmio implementation doesn't allow for `0xFFFFFFFE` type of expectations without using the `bitfield` library. It would make for a nicer experience when writing unittests to have this integrated into the Mock MMIO framework.

This has been raised in the following [pull request](https://github.com/lowRISC/opentitan/pull/3514/commits/6067ff04f2556a91f3eb8bfd6bba8c3132133ea1#r505557078).

## Possible solutions

`Inverted()` function in `mock_mmio.h` that takes what `LeInt` normally does (as suggested by @mcy in the [comment](https://github.com/lowRISC/opentitan/issues/3847#issuecomment-713618534) bellow.

## Relevant directories

`sw/device/tests/dif/`
`sw/device/lib/testing/`

**Comment by silvestrst** [comment]
@lenary @gkelly FYI

**Comment by mcy** [comment]
My thought is to just have an `Inverted()` function in `mock_mmio.h` that takes what `LeInt` normally does. Admittedly I am tempted to move these functions into their own C++ test header, where we can more easilly add generic test-value-construction things (as a C++ test analogue to bitfield.h).

**Comment by silvestrst** [comment]
I wonder if this should be left as "Good First Issue", as we don't have many of those and this seems like not a bad place for someone new to get involved?

**Comment by msfschaffner** [comment]
@cfrantz @moidx @timothytrippel is this still relevant?

**Comment by timothytrippel** [comment]
I don' think is this needed at them moment. We can re-open in the future if that changes.
