### ISSUE TITLE
RFC: AON timer proposal

### ISSUE THREAD

**Issue by tomroberts-lowrisc** [lowRISC/opentitan#3849]
## Objective
The objective of this RFC is to collect feedback on the proposed AON timer for OpenTitan.

The RFC is currently in open for comments. Once a consensus has been reached, the RFC will be updated with the design decision before promoting it to the Technical Committee for final review.

## Background - Always-On Timer
The always-on timer resides in the always-on power/clock domain and performs two functions:
### Wake timer
The wake-up timer is designed to generate an interrupt to wake the core from a low-power mode. This can either be a backstop to wake the processor to aid debug of malfunctioning software, or as a slow periodic timer interrupt similar to that of a real-time clock.
### Watchdog timer
The watchdog timer is designed to deal with stuck or malfunctioning software. There are two timer thresholds to allow the generation of an interrupt initially, then a full reset request if that fails.
 
Please see and comment on the proposal document [here](https://docs.google.com/document/d/1ih0aoixmX6tVtR4p4SC4tO87iZhlTk0JWqYoTyzicZw/edit).

**Comment by asb** [comment]
The Technical Committee met to discuss this RFC and it was **approved** - thank you Tom. We anticipate that any minor outstanding queries (e.g. Garret's comment about quantifying the bounds of accuracy) can be resolved when the relevant parts of this move to PRs for IP documentation.

**Comment by tomroberts-lowrisc** [comment]
Closing the issue now that this has progressed to RTL
