### ISSUE TITLE
[i2c] Target feature requests

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#3858]
Please see [this document](https://docs.google.com/document/d/1VvlgsJIGaHnSCflTKts9LULCaI-tC8czK4YB8eZSxG4/edit?usp=sharing)

The feature requests are pretty lightweight and primarily relate to handling bad hosts and host back pressure.

**Comment by tjaychen** [comment]
@mdhayter 
@igk8

**Comment by mateenfaisal** [comment]
@martin-lueker, @tunghoang290780 - how is the implementation of these two I2C features coming along?

**Comment by martin-lueker** [comment]
Unless I'm mistaken we are just now getting to basic target functionality, but @igk8 and @tunghoang290780 should confirm

**Comment by igk8** [comment]
These two features are being implemented in PR #4739

**Comment by igk8** [comment]
> These two features are being implemented in PR #4739

PR #4906

**Comment by tjaychen** [comment]
this has been added by @igk8 , closing.
