### ISSUE TITLE
[otp_ctrl] question related to sw_cfg_read_lock regs

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#3897]
Hi Michael,

I have a question related to `sw_cfg_read_lock` regs. I would like to confirm that they are not gated/reg-enabled by `DIRECT_ACCESS_REGWEN`.

The reason I am asking was that I have a seq like this:
1. Use DAI interface to access sw partition and triggered digest operation.
2. In the middle of HW calculating digest, I lock the `sw_cfg_read_lock`.
3. The error code showed `AccessError` and an assertion fired: 
` ASSUME(ReqStaysHighUntilGranted0_M, (|req_i) && !ready_i |=> (req_i & $past(req_i)) == $past(req_i))`
Because `otp_req_o` dropped before `ready_i` is asserted.

Details you can refer to the waveform below:

If this behavior is intended, I can fix the assertion error by setting the `EnReqStabA` parameter to 0.

![image](https://user-images.githubusercontent.com/11466553/97051894-e175ab80-1534-11eb-939c-3901f957b106.png)

Thanks for your time,
Cindy

**Comment by msfschaffner** [comment]
Hey Cindy,

The behavior is correct insofar that it is expected that a partition locked with `sw_cfg_read_lock` will lead to an `AccessError` in the DAI. However, we may want to protect the read lock CSRs with `DIRECT_ACCESS_REGWEN` to make sure they cannot be altered once a DAI access has been triggered. WDYT?

**Comment by cindychip** [comment]
I think it would be good to add the `DIRECT_ACCESS_REGWEN`.

**Comment by cindychip** [comment]
Close this issue via #3907
