### ISSUE TITLE
Verilator compilation error (jtagdpi) on macOS

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#39]
I am seeing below error(jtagdpi.c) on macOS with verilator.

```
      ssize_t num_written = send(ctx->cfd, &tdo_ascii, sizeof(tdo_ascii),
                                 MSG_NOSIGNAL);
 ```

It complains `MSG_NOSIGNAL` isn't defined. Does anyone see this?

**Comment by sjgitty** [comment]
On a mission to clean up old issues, scraping from stalest to freshest.

@eunchan can you try this again? Is this something that we want to
support @asb @imphil ?

**Comment by eunchan** [comment]
Oh... I have no longer macOS. We can close this.
