### ISSUE TITLE
Location for general macro's & global .vh files

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#390]
This question came out of issue #366 , which is converging on adding a macro for use in case statements ( executive summary: X's will be inserted into the RTL only when in simulation mode as a verification tool, otherwise a "safe" default must be chosen).   
I'd like to put a draft of the associated header and macro into the repo with the same PR where we proposes changes the style guide to mandate this.    

I'm proposing adding a directory: hw/include, are there any other suggestions?
Also, in a follow on PR we'll need to actually add build support for this, thus I'd especially like feedback anyone responsible for creating the build system.

**Comment by imphil** [comment]
I think we have found a good home for all our macros these days, let's consider this issue done.
