### ISSUE TITLE
[otbn] Do we want to allow simulatenous push/pop of the call stack?

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#3903]
Is this a useful thing to have? Pop would be ordered before the push (you read the register in an instruction before you write a result back) It's easy enough to implement in RTL and indeed is already available in my current PR. However it's maybe an odd thing to do in software and not allowing it will slightly ease the call stack handling in RTL. Thoughts?

**Comment by imphil** [comment]
So this would effectively be needed to support something like `ADDI x1, x1, 10`, but not for the actual operation of the call/loop stack?

Since we are "hiding" the call stack behind x1 and code like the one shown above would be expected to work just fine, I'd go with allowing push & pop at the same time.

**Comment by GregAC** [comment]
Yes indeed, I don't think this is an operation you'd need for standard call/return, you could do `JALR x1, x1` (i.e. pop off current top of call stack and jump to it, push PC of instruction after JALR as a replacement) possibly useful for doing tail-call optimisation for recursion?

**Comment by imphil** [comment]
If it easy to support in RTL I'd just allow it, it's easier than specifying "x1 cannot be used as source and destination register in the same instruction" (and potentially checking for that in some way).

**Comment by GregAC** [comment]
It's easy enough, just gets a little fiddly when dealing with the stack full case, here we need to decide if a simultaneous push and pop should be allowed (it's possible but disallowing it would be easier).

We can of course mark an instruction using x1 as a source and destination as an illegal instruction easily enough but I take your point this could be surprising behaviour.

**Comment by GregAC** [comment]
Actually I think if you're allowing it disallowing it on stack full vs allowing it on stack full doesn't have any meaningful difference in implementation (The complexity comes from the fact you'd normally say no pushing if full, but you can allow on pop, but on the otherside if you disallow a pop when full would normally be fine but would have to check you're not doing a push instead).

So I'll allow it and make it work correctly when the stack is full.

**Comment by GregAC** [comment]
Simultaneous push and pop when full is implemented (not actually tested yet but plenty of call stack corner cases aren't!) https://github.com/lowRISC/opentitan/pull/3852
