### ISSUE TITLE
Pattgen parametrization

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#3913]
Question: Should we support a parametrizable number of channels for pattgen?   Do we need this for the D2 milestone?

**Comment by martin-lueker** [comment]
Note: see discussion in #1844 for background.

**Comment by imphil** [comment]
IMO, there's no requirement to get this done for D2. If the current spec fulfills our needs (and I don't know if it does), then things can stay the way they are. I don't really know who's driving the requirements for pattgen, though.

**Comment by tjaychen** [comment]
i agree with @imphil.  Especially if the original requirement was that we only support 2 channels (and that's what we have), making them parameterizeable is really only a nice to have and not a must.

**Comment by martin-lueker** [comment]
Great.  This originally came from Randall, and the requirement was for 2 channels.  I'll close this for now then.
