### ISSUE TITLE
[pattgen, doc] Questions for pattgen specificification

### ISSUE THREAD

**Issue by tunghoang290780** [lowRISC/opentitan#3915]
I went through the Pattgen specification document and some issues are not clear to me (for DV development)

1) When a pattern is completely generated, do we need to clear `ctrl.enable_ch0/ctrl.enable_ch1` before re-programming registers then re-enable those bits to generate new patterns?
2) Can `ctrl.enable_ch0/ctrl.enable_ch1` bits be set within the progress of a pattern generation? if yes, does it terminate the current pattern then start the new pattern?

Do we need to update the specification document?

Original PR: #3235

**Comment by martin-lueker** [comment]
Answers:
1. Yes.  For simplicity, all setting changes are ignored while the pattern is set. Updates do not get reloaded from the TL-UL block until enable is deasserted.
2. Deasserting `enable` kills the currently running pattern, re-establishing enable starts a new pattern.

**Comment by martin-lueker** [comment]
Please let me know if the spec can be any clearer on these two points.
As to the question 1. The spec clearly states: 
"Please note that writes to a channel's configuration registers have no effect while the channel is enabled. For operational simplicity, the configuration registers are only transferred into the internal finite state machines while a channel is disabled. Changes to the configuration registers only take effect once the channel has been disabled and re-enabled."

As to Question 2 it states, after describing the entire process: 
"The entire sequence can be restarted either by resetting or disabling and re-enabling the FSM."

**Comment by martin-lueker** [comment]
As for describing the halting of the device: There is another sentence which states:
The pattern can be started (or halted) on either channel by setting the corresponding CTRL_ENABLE bit to 1 (or 0) for the desired channel.

**Comment by tunghoang290780** [comment]
thanks for clarification
