### ISSUE TITLE
[otp/lc_ctrl] Preloading mechanisms for simulation and FPGA emulation

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#3920]
At the moment, OTP is initialized with all-zeros on FPGA and in simulation.
This is fine for the time being, since the life cycle controller has not yet been implemented and hooked up in the system.

However, once that is implemented, we need to figure out how OTP should be preloaded on FPGA and in Verilator/VCS sims, such that we do not always have to run through the full secret provisioning process and all life cycle transitions from `RAW` to `PROD_*` or `DEV` in order to run a SW test. 

The purpose of this issue is to track the state of these preloading mechanisms and gather feedback and ideas.

-----------------------------

Further points to consider:

- Certain functionality is not available in certain life-cycle states (e.g., debug is not available in `PROD_*` states). Hence, SW will likely need to have support for different life cycle states at some point, and be aware of the functionality that is available in a specific state. 

- Also, life cycle transitions cannot be initiated by SW, but have to be performed via a dedicated JTAG interface. 

- The OTP controller supports pre-loading via a `MemInitFile`. Hence the preloading mechanism could build on top of that. But we will need to add support for ECC to that mechanism, and we need a way to generate the OTP memory image with all the key material and HW/SW config bits. This will also need support for the scrambled and digest-protected regions.

**Comment by tjaychen** [comment]
can you amend the title to include flash also? :)
Flash also has the ECC / scramble issue.

**Comment by msfschaffner** [comment]
Ok, added!

**Comment by lenary** [comment]
@gkelly @asb I mentioned something along these lines in my braindump on OT Mask ROM testing.

**Comment by msfschaffner** [comment]
This mechanism has now been implemented for OTP/LC and integrated into the simulation and FPGA emulation flows.

Some more information on how this has been done can be found here:

https://docs.google.com/presentation/d/1YCSuCoNc4W-UkaPlAGAmqL9VprzZEv9Yycm3dNqEQcc/edit?resourcekey=0-iM7pJM-KlgyvszhLDJmuWw

and 

https://github.com/lowRISC/opentitan/blob/master/util/design/README.md

**Comment by msfschaffner** [comment]
I spun out the flash preloading as a separate issue: https://github.com/lowRISC/opentitan/issues/5436
