### ISSUE TITLE
Verilator build fails in memutils

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3926]
```
../src/lowrisc_systems_top_earlgrey_verilator_0.1/top_earlgrey_verilator.cc:8:10: fatal error: verilator_memutil_extension.h: No such file or directory
 #include "verilator_memutil_extension.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=24817&view=logs&j=a8b61b66-4668-57fb-dcc3-ba755ef807ae&t=d8303847-c8da-507b-1651-4a69545a97af

Fallout from #3883 most likely.

@rswarbrick can you have a look?

**Comment by rswarbrick** [comment]
I'll have a look now. Thanks for the heads-up.

**Comment by rswarbrick** [comment]
Damn. Looks like I merged the PR without noticing the CI results (because the Azure -> GitHub connection was broken). Sorry about that.

**Comment by imphil** [comment]
I hadn't noticed it either. Easy to miss indeed.
