### ISSUE TITLE
Create OTP Memory Map

### ISSUE THREAD

**Issue by gkelly** [lowRISC/opentitan#3930]
We don't currently have a detailed map of the contents of the OTP regions. We need this to parse and allocate the OTP bits in each of the software-accessible regions. This issue tracks the creation of such a memory map.

**Comment by msfschaffner** [comment]
I've just recently added a parseable OTP memory map here:

https://github.com/lowRISC/opentitan/blob/master/hw/ip/otp_ctrl/data/otp_ctrl_mmap.hjson

Would that suit this purpose? We can also amend this and add more details.

Also note that this memory map is currently not top level dependent, but it may be in the future.

**Comment by gkelly** [comment]
Hey @msfschaffner, thanks for that link. The map we need to generate is specifically the actual byte-for-byte allocation of the `CREATOR_SW_CFG_CONTENT` and `OWNER_SW_CFG_CONTENT` sections. I think it's reasonable for the `CREATOR_SW_CFG_CONTENT` region (at least) to live in that file.

**Comment by msfschaffner** [comment]
OK. We can discuss whether we want to split up the `OWNER_SW_CFG_CONTENT` item in this file as well and name all the items needed. One of the benefits of doing this here is that this gets propagated into the OTP controller documentation [here](https://docs.opentitan.org/hw/ip/otp_ctrl/doc/index.html#direct-access-memory-map) and the item offsets and sizes become available in the autogen'd header via the [HJSON](https://github.com/lowRISC/opentitan/blob/972c0f8dbf7cd47eccad789bdcbeba1cb9bcd5f5/hw/ip/otp_ctrl/data/otp_ctrl.hjson#L85).

**Comment by tjaychen** [comment]
@mcy 

wait.. @gkelly, if it's software content only, do we really want that to be exposed in the controller though?
The software content likely will change between each creator / owner right? It almost makes more sense for this to be declared as some kind of top specific header file that can be invoked when instantiating the otp DIFs.

What do you think? Remember the software partitions are basically completely unmanaged by the hardware beyond basic checks (@msfschaffner please correct me if i'm wrong).

**Comment by msfschaffner** [comment]
Yeah you are right, @tjaychen. The content is completely software managed. The only thing HW looks out for is the value of the SW digests in order to determine whether the partitions are write-locked or not.
So keeping the detailed memory map information of the individual software partitions in a separate header makes probably more sense, especially if the collateral is different for each creator / owner.

**Comment by lenary** [comment]
Ok, a separate parseable definitions sounds like the way to go here - we've got a way of doing this for the rom_ext image definition, I think we might re-apply that script/scheme here for each of the creator/owner partitions.

**Comment by tjaychen** [comment]
just a note also that the creator partition is going to be owned by the
vendor / partner.
So they might want their own scheme of how they want it maintained.  Also
in the case of Nuvoton, they do not wish to expose the exact definition,
and instead would prefer to have some kind of scheme where contents from
OTP are just copied over to the AST.
It might be good  to have a sync here with the relevant stakeholders.

**Comment by gkelly** [comment]
For the OTP->AST chunk we've had some discussions around that, but there are other bits that end up in the creator region that Mask ROM has interest in, so we do need to have the layout defined there. I'm completely happy to put the layout outside of the mmap hjson, but I think there needs to be _some_ map.

**Comment by tjaychen** [comment]
ah sounds good.
For the other regions you guys are interested in, do you think there's a
need to sync with Nuvoton?

**Comment by tjaychen** [comment]
@cfrantz is this issue still valid? i think this is more or less resolved between you and @msfschaffner right?

**Comment by tjaychen** [comment]
i'll close this for now. If there are objections, please reopen.
