### ISSUE TITLE
API to query build/run commands for simulation

### ISSUE THREAD

**Issue by svenka3** [lowRISC/opentitan#3944]
Hello,
  As a follow-up of:

https://github.com/lowRISC/opentitan/issues/3923

Is there an easy way/API to see what build (and/or run) command is ultimately used for a given set of tests/regression? Of course individual LOG files may help, but assume we  want to qualify/tweak run command at end-user level before launching the simulation - sort of "make -n" 

Thanks
Srini

**Comment by sriyerg** [comment]
`dvsim` does have a `-n or --dry-run` switch which behaves exactly the same way as GNUMake's -n switch. Please try `util/dvsim/dvsim.py --help` for a detailed list of features. 

In this dry run mode, the script will progress in the same manner as it would when actually running the tests. Just that it will not actually dispatch the build and run commands. You can open the individual `build.log` or `run.log` to see the full command string (which is printed even when not in dry run mode) which you can copy-paste on the terminal, tweak as needed and run manually.

**Comment by svenka3** [comment]
Great, thanks I should have looked deeper.
