### ISSUE TITLE
Killing simv processes after Control-C in dvsim

### ISSUE THREAD

**Issue by svenka3** [lowRISC/opentitan#3947]
Hi,
  I run dvsim as below:

`./util/dvsim/dvsim.py hw/ip/gpio/dv/gpio_sim_cfg.hjson -i gpio_sanity
`
Say I want to exit/abort, I type Control-C. I notice that many of the tests/runs are still running in background (Could see several simv) as below:

```
24683 pts/1    00:00:00 simv
24727 pts/1    00:00:00 sh
24728 pts/1    00:00:00 simv
26539 pts/1    00:00:00 sh
26540 pts/1    00:00:00 simv
26547 pts/1    00:00:00 sh
26548 pts/1    00:00:00 simv
26569 pts/1    00:00:00 sh
26571 pts/1    00:00:00 simv
26576 pts/1    00:00:00 sh
26579 pts/1    00:00:00 simv
26586 pts/1    00:00:00 sh
26588 pts/1    00:00:00 simv
26593 pts/1    00:00:00 sh
26595 pts/1    00:00:00 simv
26602 pts/1    00:00:00 sh
26604 pts/1    00:00:00 simv
26614 pts/1    00:00:00 sh
26618 pts/1    00:00:00 simv
26630 pts/1    00:00:00 sh
26633 pts/1    00:00:00 simv
26641 pts/1    00:00:00 sh
26644 pts/1    00:00:00 simv
26649 pts/1    00:00:00 sh
26651 pts/1    00:00:00 simv
26679 pts/1    00:00:00 sh
26680 pts/1    00:00:05 simv
27087 pts/1    00:00:00 ps
```
I had to kill them one-by-one, painful. I couldn't see a top-level process that I can easily spot and kill (such as "dvsim"). I guess it is due to the way it is spawned by the script. 

Any tricks that you folks use at your end (barring the fact that you may have the luxury of unlimited licenses :-) )

Thanks
Srini

**Comment by rswarbrick** [comment]
My trick is to run `killall simv` in another terminal if I want to stop a running dvsim. Hitting Ctrl-C also sometimes seems to trash the terminal, needing a call to `reset` to clean up: I'm not sure why.

I'm pretty certain that dvsim is correctly sending a SIGINT to the simv process. Maybe we just need to do that, wait a bit and then send a SIGTERM (and then a SIGKILL) if the process is still hanging around.
