### ISSUE TITLE
[top] Turning on icache for top level?

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#3974]
Would we be comfortable turning on icache during top level tests?
I thought ibex / icache was relatively stable, so wanted to double check.

**Comment by tjaychen** [comment]
@sriyerg 
@imphil 

FYI

**Comment by udinator** [comment]
I think I'd be comfortable turning it on at top-level, I haven't seen any errors in Ibex tests due to icache thus far.

**Comment by imphil** [comment]
Duplicate of #3539

We enabled the icache in Ibex CI/DV last week and haven't seen any issues so far. We can proceed turning it on in OT.

**Comment by sriyerg** [comment]
SGTM.

**Comment by tjaychen** [comment]
ah forgot there was already an issue.
