### ISSUE TITLE
[sw] Add Rust Support in CI

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#3984]
We're starting to add more and more Rust to the Software tree. We want to make sure we can test this on every PR, inside CI. This has been an outstanding issue since we added Tock to the repository.

If we're lucky, this is as simple as adding something like `rustup` to the CI environment, and triggering it to install the correct targets. If we're not, it's a whole lot harder and less fun. I'm expecting it will be the latter.

**Comment by GregAC** [comment]
No longer relevant
