### ISSUE TITLE
[otbn] document and add code for p256 ECC

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#4000]
This issue tracks the effort to implement and document a p256 ECC implementation on OTBN. It is also supposed to from the basis for a generic ECC (for 256 bit curves) as tracked in #2619.

- [x] Initial code dump
- [x] document and add p256 specific things (like domain parameter setup)
- [x] document and add 256 bit Barrett reduction/multiplication
- [x] document and add point doubling
- [x] document and add point addition
- [x] document and add scalar multiplication
- [x] document and add coordinate transformation (projective <-> affine)
- [x] document and add curve point verification: #4960
- [x] document and add sign
- [x] document and add verify
- [x] document use of Stein's algorithm: #4959
- [x] document loading of curve domain parameters and constants

> estimate 32
> remaining 2020-12-14 24
> remaining 2021-02-08 16 
> remaining 2021-02-16 4
> remaining 2021-02-17 0

**Comment by imphil** [comment]
Auto-converted code is now at #4205.

**Comment by felixmiller** [comment]
The code containing the work on the checked boxes is [here](https://github.com/felixmiller/opentitan/blob/otbn-doc-p256/sw/otbn/code-snippets/p256.s) currently. I could make a PR but I would prefer to have a single commit that adds all the documentary comments to the P-256 snippet at once. (Probably in two weeks)

**Comment by felixmiller** [comment]
Finished with #5273
