### ISSUE TITLE
[otbn] investigate/discuss RSA padding on OTBN

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#4004]
We need to investigate to what extend we want to perform RSA padding on OTBN.

- What are the padding schemes we want to support
- Where do wen want to perform padding (OTBN vs. Ibex)

**Comment by GregAC** [comment]
@felixmiller is this still live?

**Comment by jadephilipoom** [comment]
I seem to recall that Felix and I discussed this a while ago and decided not to do padding on OTBN; for ROM we do it on Ibex and that's the plan for the cryptolib as well. I think it's safe to close this unless @felixmiller remembers differently.

**Comment by felixmiller** [comment]
Yes, this can be closed.
