### ISSUE TITLE
[otbn] Implement error and alert handling in RTL

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#4005]
The current RTL is sprinkled with TODOs around error conditions and no error handling is implemented. We need to:

* Come to an agreement on what happens on an error condition
* Implement this for all error handling TODOs
* Scrutinize the RTL and specification for other error conditions that need dealing with that aren't explicitly flagged by a TODO

Alerts also need similar attention

I'm uncertain of the current state of error handling the ISS but likely some matching work will need to be done there also.

> estimate 8

**Comment by rswarbrick** [comment]
> I'm uncertain of the current state of error handling the ISS but likely some matching work will need to be done there also.

It's essentially non-existent!

**Comment by GregAC** [comment]
I've made some decent progress on the RTL for this, but not yet ready for a PR.

> remaining 4
