### ISSUE TITLE
[otbn] [OTBN.H.REG_INTEGRITY] Specify hardening for register files

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#4007]
The OTBN register files currently don't have any protection. Discuss and agree on the necessary hardening for them (from a security perspective).

Implementation trials are out of scope.

> estimate 2
> remaining 2021-05-17 1

**Comment by GregAC** [comment]
Discussion has begun, haven't yet reached a conclusion

**Comment by imphil** [comment]
Spec is in  #6469 waiting for final review.
