### ISSUE TITLE
[otbn] Examine OTBN timing results

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#4008]
With the OTBN RTL nearing functional completion we should look at the timing of the OTBN to see what timing issues, if any, are present in the complete design that weren't identified from the mock RTL.

> estimate 8

**Comment by mateenfaisal** [comment]
Will we gauge any timing issues from synthesis timing reports?

**Comment by GregAC** [comment]
Initial timing and reports from OTBN block-level synthesis look good, no timing issues are currently seen.
