### ISSUE TITLE
[dif/otp_ctrl] OTP followups

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#4056]
- [ ] Use the correct lock registers (CHECK_REGWEN vs. CHECK_TRIGGER_REGWEN).

**Comment by moidx** [comment]
Closing as obsolete.

**Comment by a-will** [comment]
Not obsolete, actually. Sorry I didn't notice this was assigned to me.

**Comment by a-will** [comment]
It looks like there is more to do here than initially expected. The lock code is from back when regwen was rw1c, but it's now rw0c. There might need to be an audit for other such changes.
