### ISSUE TITLE
[dv] ral package refers uninitialized object if REGWEN defines later

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#4058]
If REGWEN register is defined later than the original register, the RAL package refers REGWEN without defining it first.

The proper way, I think, is to define(create) all the registers first then adding fields inside.

```systemverilog
      cfg = kmac_reg_cfg::type_id::create("cfg");
      cfg.configure(.blk_parent(this));
      cfg.build(csr_excl);
      default_map.add_reg(.rg(cfg),
                          .offset(32'hc),
                          .rights("RW"));
      cfg_regwen.add_locked_reg(cfg);
```

`cfg_regwen` in KMAC is created after cfg.

CC: @tjaychen @msfschaffner

**Comment by sriyerg** [comment]
An easy fix is to move the regwen CSRs before the CSRs it controls.

**Comment by eunchan** [comment]
> An easy fix is to move the regwen CSRs before the CSRs it controls.

I did. this is for tracking purpose. I hope DV RAL also revised to remove that limitation.

**Comment by tjaychen** [comment]
i actually think i might have filed a similar issue somewhere .. :)

**Comment by tjaychen** [comment]
aha! #1953

**Comment by sriyerg** [comment]
Ohh, ok. We will fix it then.

**Comment by weicaiyang** [comment]
I will make a PR to fix this soon.
