### ISSUE TITLE
[SW] manifest.h is generated later in the compilation order

### ISSUE THREAD

**Issue by rmbhagwat** [lowRISC/opentitan#4088]
ninja -C build-out
ninja: Entering directory `build-out'
[33/678] Compiling C object 'sw/device/mask_rom/55d4b04@@mask_rom_sim_verilator@exe/mask_rom.c.o'.
FAILED: sw/device/mask_rom/55d4b04@@mask_rom_sim_verilator@exe/mask_rom.c.o
/tools/riscv/bin/riscv32-unknown-elf-clang -Isw/device/mask_rom/55d4b04@@mask_rom_sim_verilator@exe    -I/home/project/rot/20201105/rstspi -I/home/project/rot/20201105/rstspi/build-out -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -g -nostdinc -isystem/home/project/rot/20201105/rstspi/sw/device/lib/base/freestanding -fno-asynchronous-unwind-tables -fno-common -Wimplicit-fallthrough -Wswitch-default -Wno-covered-switch-default -Wgnu -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wno-gnu-zero-variadic-macro-arguments -Os -fvisibility=hidden --gcc-toolchain=/tools/riscv -march=rv32imc -mabi=ilp32 -mcmodel=medany -MD -MQ 'sw/device/mask_rom/55d4b04@@mask_rom_sim_verilator@exe/mask_rom.c.o' -MF 'sw/device/mask_rom/55d4b04@@mask_rom_sim_verilator@exe/mask_rom.c.o.d' -o 'sw/device/mask_rom/55d4b04@@mask_rom_sim_verilator@exe/mask_rom.c.o' -c ../sw/device/mask_rom/mask_rom.c
In file included from ../sw/device/mask_rom/mask_rom.c:12:
/home/project/rot/20201105/rstspi/sw/device/rom_exts/rom_ext_manifest_parser.h:12:10: fatal error: 'sw/device/rom_exts/manifest.h' file not found
#include "sw/device/rom_exts/manifest.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[34/678] Compiling C object 'sw/device/mask_rom/55d4b04@@mask_rom_sim_dv@exe/mask_rom.c.o'.
FAILED: sw/device/mask_rom/55d4b04@@mask_rom_sim_dv@exe/mask_rom.c.o
/tools/riscv/bin/riscv32-unknown-elf-clang -Isw/device/mask_rom/55d4b04@@mask_rom_sim_dv@exe    -I/home/project/rot/20201105/rstspi -I/home/project/rot/20201105/rstspi/build-out -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -g -nostdinc -isystem/home/project/rot/20201105/rstspi/sw/device/lib/base/freestanding -fno-asynchronous-unwind-tables -fno-common -Wimplicit-fallthrough -Wswitch-default -Wno-covered-switch-default -Wgnu -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wno-gnu-zero-variadic-macro-arguments -Os -fvisibility=hidden --gcc-toolchain=/tools/riscv -march=rv32imc -mabi=ilp32 -mcmodel=medany -MD -MQ 'sw/device/mask_rom/55d4b04@@mask_rom_sim_dv@exe/mask_rom.c.o' -MF 'sw/device/mask_rom/55d4b04@@mask_rom_sim_dv@exe/mask_rom.c.o.d' -o 'sw/device/mask_rom/55d4b04@@mask_rom_sim_dv@exe/mask_rom.c.o' -c ../sw/device/mask_rom/mask_rom.c
In file included from ../sw/device/mask_rom/mask_rom.c:12:
/home/project/rot/20201105/rstspi/sw/device/rom_exts/rom_ext_manifest_parser.h:12:10: fatal error: 'sw/device/rom_exts/manifest.h' file not found
#include "sw/device/rom_exts/manifest.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[35/678] Compiling C object 'sw/device/mask_rom/55d4b04@@mask_rom_fpga_nexysvideo@exe/mask_rom.c.o'.
FAILED: sw/device/mask_rom/55d4b04@@mask_rom_fpga_nexysvideo@exe/mask_rom.c.o
/tools/riscv/bin/riscv32-unknown-elf-clang -Isw/device/mask_rom/55d4b04@@mask_rom_fpga_nexysvideo@exe    -I/home/project/rot/20201105/rstspi -I/home/project/rot/20201105/rstspi/build-out -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -g -nostdinc -isystem/home/project/rot/20201105/rstspi/sw/device/lib/base/freestanding -fno-asynchronous-unwind-tables -fno-common -Wimplicit-fallthrough -Wswitch-default -Wno-covered-switch-default -Wgnu -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wno-gnu-zero-variadic-macro-arguments -Os -fvisibility=hidden --gcc-toolchain=/tools/riscv -march=rv32imc -mabi=ilp32 -mcmodel=medany -MD -MQ 'sw/device/mask_rom/55d4b04@@mask_rom_fpga_nexysvideo@exe/mask_rom.c.o' -MF 'sw/device/mask_rom/55d4b04@@mask_rom_fpga_nexysvideo@exe/mask_rom.c.o.d' -o 'sw/device/mask_rom/55d4b04@@mask_rom_fpga_nexysvideo@exe/mask_rom.c.o' -c ../sw/device/mask_rom/mask_rom.c
In file included from ../sw/device/mask_rom/mask_rom.c:12:
/home/project/rot/20201105/rstspi/sw/device/rom_exts/rom_ext_manifest_parser.h:12:10: fatal error: 'sw/device/rom_exts/manifest.h' file not found
#include "sw/device/rom_exts/manifest.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[41/678] Generating rom_exts_manifest_h with a custom command.
Template sucessfuly written to /home/project/rot/20201105/rstspi/build-out/sw/device/rom_exts/manifest.h.

**Comment by imphil** [comment]
Sorry for the wait, this issue got lost somewhere. We did have some races in there in the past, but merged at least one PR recently fixing one of those issues. Please re-try and reopen this issue if the problem persists.
