### ISSUE TITLE
[gpio] Incorrect register mask values in specification

### ISSUE THREAD

**Issue by gaurangchitroda** [lowRISC/opentitan#41]
Hi Eunchan,

Register Mask values for following GPIO registers seem incorrect to me:
(1) gpio.INTR_STATE @ + 0x0
     mask 0x1
(2) gpio.INTR_ENABLE @ + 0x4
     mask 0x1
(3) gpio.INTR_TEST @ + 0x8
     mask 0x1

For all 3 registers above, I think that mask value should be 0xffff_ffff as all 32-bits are defined.
I am not sure whether mask means represents "defined"/"unreserved" bits or "writable bits"?
Also, I see "Register enable =" in all registers. Are we missing some information here?

Best Regards,
Gaurang

**Comment by aytong** [comment]
@eunchan, ping.

**Comment by sjgitty** [comment]
@eunchan what is the status on this old bug?
