### ISSUE TITLE
[kegmgr] KMAC side load timing diagram

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#4104]
@tjaychen 
As discussed, it's helpful to have a timing diagram for KMAC side load interface (kmac_data_i/o and kmac_key_o) in the keymgr spec.

**Comment by tjaychen** [comment]
added through #4624
let me know if it's enough info and we can close this one.

**Comment by weicaiyang** [comment]
> added through #4624
> let me know if it's enough info and we can close this one.

Thanks Tim. Closing this.
