### ISSUE TITLE
[otbn] rshi instruction: mismatch doc/sim and expectation of assembly

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#4112]
In the documentation and the simulator we currently have a definition for `RSHI` as follows
`BN.RSHI <wrd>, <wrs1>, <wrs2> >> <imm>`
here `wrs1` forms the upper 256 bit and `wrs2` the lower 256 bit of the full 512 bit concatenated word that is right shifted.

This matches with the [implementation ](https://github.com/lowRISC/opentitan/blob/95bcc90b2324e89918b7b4567687503aed9a1467/hw/ip/otbn/dv/otbnsim/sim/insn.py#L707)in the ISS. 

The code for the Barrett multiplication, however, expects this the other way round (see e.g. [here](https://github.com/lowRISC/opentitan/blob/95bcc90b2324e89918b7b4567687503aed9a1467/sw/otbn/code-snippets/barrett384.s#L141)). The latter is also how I had it implemented in the "old" simulator and how the instruction was initially defined. 

We do not use the `RSHI` instruction in modexp, therefore this didn't come up so far. And probably we only tested the Barrett code against the "old" simulator so far (what confuses me though: @imphil didn't you just recently create a test for this? Did that run successfully?)

So it looks to me that we need to either update the doc/sim or the Barrett code. Both is fine for me. Updating the Barrett code is probably the less intrusive changes. Are there opinions on what is the more natural definition of the instruction? @imphil @GregAC @rswarbrick 

> estimate 2
> remaining 2021-01-25 0

**Comment by imphil** [comment]
Yes, Barrett produces (for the input variables I chose) the right result in ISS and RTL.

**Comment by rswarbrick** [comment]
I probably slightly prefer the definition in the docs (just because then you can sort of read the number MSB-first as `wrs1; wrs2`, which matches the syntax). Does the choice make any difference to muxing cost @GregAC?

**Comment by GregAC** [comment]
The current version (`wrs2` is lower 256-bit) is better for hardware implementation.

The reason being is I use a single 512-bit shifter to implement RSHI as well as the byte shifts for the second operand in the ALU instructions. When doing the byte shifts for the second operand I just take the bottom half of the shift output. With the current setup `wrs2` gets fed in as the low 256-bits in either case. Were we to switch to `wrs1` as the low half of the RSHI that shifter would need an extra mux for the lower half input. Given timing is looking good this would be doable but unless we've got a compelling reason to change I think we're better off leave it as is.

**Comment by GregAC** [comment]
Or alternatively modify the shifter so I can take the top half of its result for the byte shifts for the ALU instruction operands. This would mean adding some logic so it just shifts 0s into the top half rather than the bits of the bottom half.

Again doable (and potentially preferable to the extra mux) if needed.

**Comment by rswarbrick** [comment]
@felixmiller: Are you happy with this? In which case, I think we can close this issue.

**Comment by felixmiller** [comment]
@rswarbrick There is potentially still an issue in the Barrett 384 code related to this. Looking into this within this week

**Comment by felixmiller** [comment]
Added an estimate to this. This is mainly to run the test and see what's going on and potentially change the order of the operands. I believe, there must still be sth. off, since the assumption I had on the definition of `RSHI` when I wrote this code was different compared to the one we are using now.

**Comment by imphil** [comment]
Fixed by https://github.com/lowRISC/opentitan/commit/7c42f67eb759fa2e02868f447187ceac5dafa0d5
