### ISSUE TITLE
CI fails on the majority of PRs at the moment

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#4128]
It seems that the rv32i test times out for most pushes. If we can't speed it up, would it make sense to turn this test off so that we don't have to keep hitting "re-submit"?

CI latency is currently ~1 hour if all is well, but this more than doubles if you're unlucky.

@imphil as resident CI guru!

**Comment by imphil** [comment]
Yes, let's disable them. We didn't have a single issue caught by them for a long time now, so doing that shouldn't have much influence on the quality of results.

I'll do a PR shortly.
