### ISSUE TITLE
[flow] Update fusesoc expressions with quotation marks

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#4157]
See #4145 

When using fusesoc conditionals, or really any expression that contains non-alphanumeric characters or underscores, we should try to encapsulate the entire expression with quotation marks to ensure there are no yaml reading issues.

This will mostly apply to the various fileset and tool flags that we use.  Specifically things like `fileset_ip` or `tool_ascentlint`.
We should go through and update everything to make sure we don't run into future issues.

**Comment by tjaychen** [comment]
@sriyerg 
@imphil

**Comment by sriyerg** [comment]
Ack.

**Comment by tjaychen** [comment]
being addressed where available.
This is more like a sticky for the project than anything else. Will close for now.
