### ISSUE TITLE
[test] RISC-V Compliance for Earlgrey

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#417]
Currently, we run [RISC-V compliance tests](https://github.com/riscv/riscv-compliance) on Ibex (though on the Ibex repo rather than in the vendored-in copy in OT). However, these tests do not run on the Earlgrey toplevel system; running these tests as part of CI would have caught https://github.com/lowRISC/opentitan/issues/350, for example.

To do this, we will need a toplevel system that can dump the results of the tests from memory; there's a few options for doing this, which boil down to either "dedicated peripheral" or "dump *something* through UART". I'm not sure how much of this work can be undertaken by software and how much of it is hardware work, though, so I'd appreciate some guidance there.

**Comment by mateenfaisal** [comment]
as PR #485 addressed this issue, can we close this issue @imphil?
