### ISSUE TITLE
[clocks] Core and Peripheral clock relationship

### ISSUE THREAD

**Issue by rmbhagwat** [lowRISC/opentitan#4184]
I would like to modify the clocking scheme.
Presently,
Core clock : Xperi clock : IO clock relationship is 1:2:4

I want to change it to 1:4:8 OR 1:8:16.

What all considerations do I need to take in HW and SW?
Thank you!

**Comment by rmbhagwat** [comment]
Also what is the significance of 96MHz clock? I see its reference in following files but I don't see if it is actually used.
The ourput from PLL is 10MHz and 48MHz only.

- https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/top_earlgrey.hjson

- https://docs.opentitan.org/hw/ip/clkmgr/doc/

**Comment by tjaychen** [comment]
hmmm... since this question is quite old. I'm not sure if it's still relevant.
If you would still like to know the answer let me know, and i can provide guidance.

**Comment by tjaychen** [comment]
i'll close this for now due to inactivity. But again, if there is interest, please re-open.
