### ISSUE TITLE
pipeline the escalation handshake logic

### ISSUE THREAD

**Issue by rmbhagwat** [lowRISC/opentitan#4188]
Would it be nice if the escalation handshake logic is pipelined to break the timing?

**Comment by msfschaffner** [comment]
Thanks for the question, and apologies that this never got answered.

The escalation handshake logic has intentionally not been pipelined to keep the signalling latency (in terms of clock cycles) low.
There are only 4 escalation endpoints, and the frequency of the corresponding clock domain is pretty low (the peripheral clock domain runs at 24MHz).
Hence this is likely not going to create any timing issues.

Please feel free to reopen if you have any other questions related to this topic.
