### ISSUE TITLE
hw/ip/rstmgr/data/rstmgr.cfg.example.hjson needs update

### ISSUE THREAD

**Issue by rmbhagwat** [lowRISC/opentitan#4190]
hw/ip/rstmgr/data/rstmgr.cfg.example.hjson needs to be updated if it is really used.

It is used in hw/ip/rstmgr/util/rstmgr_gen.py

**Comment by rmbhagwat** [comment]
@eunchan @tjaychen , can some one create an explanotory video how this topgen and other utilities work?

**Comment by msfschaffner** [comment]
Apologies that this question never got answered - this somehow fell through the cracks.

By now all templated RTL files can be regenerated using the `make -C hw` command in the project repository root, including the templated `rstmgr` files.
You will see the individual commands used when looking at [this `Makefile`](https://github.com/lowRISC/opentitan/blob/master/hw/Makefile).

We are constantly updating and improving our documentation, but at the moment there are no plans to create instructional videos.

Please feel free to reopen the issue if there are more questions related to this topic.
