### ISSUE TITLE
[top] inter-module connection

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#42]
@tjaychen @sjgitty 
I would like to discuss the top gen inter module connection scheme here.

### hjson struct **in IP** vs **in Top**

Current comportability spec has `available_{input|output|inout}_list` for the module connection. As the ports are usually connected to Pinmux, all port signals have `cio_` prefix. But some of the signals could connect to the other modules (for instance, eFlash and eFlash controller). We should choose between below two options to enable this.

1. specifying the port isn't goes to Pinmux or outside of the top in the IP. It means the entry in `available_{input|output|inout}_list` will have `name`, `width`, and now `inter_module` (boolean). If `inter_module`(name can be changed) is set to `true`, the port won't have `cio_` prefix but have a direct name. For instance, if `keymgr_secretkey` input port has `inter_module` as true, then the port will be defined as `input [width-1:0] keymgr_secretkey_i`.

    It still needs the top hjson to define the relationship such as:

    ````hjson
    inter_module: [
      { from: keymgr.secretkey, to: [hmac.keymgr_secretkey, aes.keymgr_secretkey] }
      ...
    ]
    ````
2. all assumed as a input/output in the IP, and top configuration determines the connection property. It means all ports in a IP will have `cio_` prefix but some of the signals connecting to the other modules.

    With above (item 1) example, the top gen will assume from as an output, to as an input and put `cio_` prefix and `_o` or `_i` postfix accordingly.

### input/output data type

The other issue on inter module connection is the input/ output data type.

to reduce the connection between the modules, `struct packed` type can be used. Issue is, where the struct type should be defined.

1. From the output module means it introduces extra dependencies between the IPs (not good in my opinion)
2. Common definition in `hw/common/` directory. (still not that beautiful. just moving the dependencies to `common` directory)
3. Assume input/output always `logic`. width is defined in `available_{input|output|inout}_list` item. Each module will have its own casing from/to the struct packed type. In this case, the sizeof(struct packed) needs to be calculated by the designer or the tool. **by tool** will be difficult. and width mismatch can happen.
4. Just stop using struct packed define each signals in the available IO list

### clocking information

If the signal is used in the other modules and if the other modules are clocked in another clock, then CDC logic is needed. But it isn't recognized until the clocks are defined in the top. And FPGA version and the ASIC version can have different clock scheme. 

So, putting the CDC logic inside IPs isn't feasible in my opinion. Top needs to have CDC logic if needed.

1. **by tool**: input, output list have clock information if the signal isn't clock by main IP clock. Tool recognizes clock differences and put the CDC (2ff sync if 1 bit if multibit valid/ready on both sides are mandatory). This is hard problem.
2. Just do it manually by the top-level designer.

lowRISC/stwg-base#230

**Comment by sjgitty** [comment]
@eunchan please refresh with current thinking, has been stale for 6 months

**Comment by eunchan** [comment]
PR #1490 is merged. But still a few things need to be implemented.
A.I:

1. Define unique inter-module signal (naming rule) when it has multiple
   connections of the same struct
2. Reduce the fields of `inter_signal_list` in the ip.hjson
3. Add `broadcast` type and handling
4. Add validation check
5. Revise `inter_module` structure to cover the cases:
    - 1:1 -> currently supported
    - 1:N -> structurely OK, but not implemented
    - N:1 -> Not possible to cover with current structure

**Comment by tjaychen** [comment]
@eunchan should we close this issue now? 
I think `intermodule` is pretty well known now and also in use.

**Comment by eunchan** [comment]
Agree :) thanks for the ping
