### ISSUE TITLE
[otbn] end-to-end tests for P-256 ECC

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#4206]
In order to capture issues when refactoring the P-256 lib on OTBN we need to provide end-to-end tests for:

- [x] curve point test (currently exists, but gives wrong results)
- [x] scalar multiplication
- [x] ECDSA sign
- [x] ECDSA verify

Start with RSA encode/decode-style self-contained assembly test.

> estimate 4
> remaining 2020-11-30 1 
> remaining 2020-12-10 0

**Comment by imphil** [comment]
We do now have (auto-converted) tests for these algorithms in our tree, closing.
