### ISSUE TITLE
[otbn] Decide on alert interface

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#4208]
At the moment, we have 3 alerts (DMEM ECC; IMEM ECC; Something Else). Other IP blocks seem to have standardised on (Low Priority; High Priority). Decide whether to follow suit.

OT-wide discussion at https://github.com/lowRISC/opentitan/issues/3767

> estimate 2

**Comment by cdgori** [comment]
I think Michael/Tim are going to show a proposal for handling the 4 alert priorities in tomorrow's Silicon meeting, not sure if this will influence your thinking directly but definitely take a look tomorrow.

**Comment by rswarbrick** [comment]
To figure out what other blocks are doing, I looked at the alerts defined by each. You can get a rough list of these blocks with

    git grep -l alert 'hw/ip/*/*.hjson' | grep -v alert

Here's the list:

    | Block       | Alerts                                      |
    |-------------+---------------------------------------------|
    | aes         | 2: ctrl_err_update, ctrl_err_storage        |
    | entropy_src | 1: es_alert_count_met                       |
    | keymgr      | 2: fault_err, operation_err                 |
    | lc_ctrl     | 2: lc_programming_failure, lc_state_failure |
    | otp         | 2: otp_macro_failure, otp_check_failure     |

Other than `entropy_src`, which only has one alert, the others all have 2, which are split by what caused the alert (rather than by severity).

I'm not sure that will work so well for OTBN: it's a processor, so there are lots of possible things that can go wrong! Are we happy to define just 2 or 3 classes of alert and bucket things up statically, or do we need some sort of configurability for what event triggers what alert?

**Comment by rswarbrick** [comment]
@imphil, @GregAC: What do you think?

**Comment by imphil** [comment]
Looking at the proposed guidance at https://github.com/lowRISC/opentitan/issues/3767#issuecomment-725625551, it looks to me that we want two alerts, a recoverable and a non-recoverable one. Additionally, we need two alert cause registers, as we'll very likely have more than one reason to trigger both a recoverable and a non-recoverable alert.

We should be able to go ahead with the Hjson/spec change on this to get the wire connections in place.

We can also start with a table of alert causes that includes the current places where we have mentioned in the spec "this will cause an alert" to start the discussion on specific alert causes and how they should be grouped.

@msfschaffner 
* Is that roughly what you were planning to present to the silicon meeting?
* Is there thinking on standardized naming for the recoverable/non-recoverable alert and the associated alert cause registers?

**Comment by rswarbrick** [comment]
That sounds sensible. Does OTBN actually *have* any recoverable errors?

**Comment by GregAC** [comment]
Depending on hardening there may be the possibility of correcting single bit flips with ECC. This could be a recoverable alert. Though this does raise the question of whether OTBN would need to pause after such a recoverable alert to be given the go-ahead or it just continues onwards and software on Ibex just decides if it wants to throw away the result for instance.

**Comment by imphil** [comment]
The non-recoverable alerts are sticky "until the next reset". I understand this as "until the next full chip reset".

In the bucket of recoverable alerts I'd put all things which can be recovered from by resetting/restarting OTBN alone, i.e. in the next software execution. Things which might well be a programming error, such as reading beyond the end of the call/loop stack, accessing invalid memory regions, etc.

**Comment by GregAC** [comment]
Do basic errors even need to trigger alerts? I was thinking for those it would simply halt OTBN, software on Ibex will see OTBN is done, read the status and see the error without raising an alert.

**Comment by rswarbrick** [comment]
Right, well may I suggest the following as an initial spec?

- ECC errors on memories and register files are evidence of badness happening. Put them in one bucket.
- All other errors might have been caused by a programming screw-up. Put them in the other bucket.

In the future, we might decide that some errors should move buckets, have no buckets, or even have configurable buckets(!), but we can probably punt on that for now.

Does that sound like a reasonable start?

**Comment by msfschaffner** [comment]
@imphil: We had to strip down the content we presented this week as it would have been too much together with the update on life cycle. We'll go over the alert guidance in the next silicon meeting. But in essence, what we're proposing is described in the comment you linked, so if you stick to that model I think you should be on the right track.

Regarding the naming: we have not formalized a naming convention for those two buckets yet, but we can discuss that. It could ease auditing and severity mapping in the alert handler (i.e., the SW programmable alert classification).

To @GregAC's point: no I don't think basic errors should trigger alerts. They should just trigger an IRQ in my view.

For example, you could choose to just report a normal error when a correctable ECC error has occurred. However, when an uncorrectable ECC error occurred, you could send out a recoverable alert.

Unrecoverable alerts should be really critical in the sense that they brick the IP. For instance, if you have a redundantly encoded FSM somewhere, and that FSM is glitched into an invalid state, the FSM should stay there and an unrecoverable alert should be signaled. In case of Ibex or OTBN, such an alert could for instance be triggered by CFI mechanisms.

**Comment by msfschaffner** [comment]
FYI
@tjaychen
@weicaiyang 
@cindychip

**Comment by tjaychen** [comment]
@msfschaffner 
are we sure we want to consider ECC errors recoverable..? I honestly think for something like otbn (especially the regfile) that should be a fairly serious error.

**Comment by msfschaffner** [comment]
yeah we can also step up the severity of ECC errors in this case (I just meant to give an example). would it make sense to standardize how ECC errors are to be treated system-wide?

we have several other places where ECC errors can occur.
for instance, in OTP, correctable ECC errors in the OTP macro are reported as "normal" errors via an IRQ, whereas uncorrectable ECC errors are unrecoverable and send out an unrecoverable alert.

**Comment by tjaychen** [comment]
i actually think ECC (for better or worse) probably needs to be separated into two categories..
The NVM case like you mentioned probably need to treat the 1-bit error case like business as usual. 
Whereas volatile memory / flops I think can reasonably treat them as a fatal error. 

I accidentally made the mistake of attempting to convert flash into the latter category recently, and that probably would have been a terrible  idea.

**Comment by msfschaffner** [comment]
Yeah that sounds good to me. How do we want to proceed with SRAM? Treat it the same way as registers or rather like NVM?

**Comment by tjaychen** [comment]
my opinion is treat it like reg.  

I think the size we're looking at is not big enough to require redundancy..and i'm personally not too worried about cosmic rays flipping a bit that leads to the device resetting (so let's hope no one ever puts this into a vehicle or something...)

I think it's worth running it by Nuvoton to see if they are comfortable with this.

**Comment by msfschaffner** [comment]
ok so to summarize, the ECC guidance would become:

1) on regs and SRAM, treat both correctable and uncorrectable errors as fatal, unrecoverable alerts.
2) on NVM (OTP, FLASH), signal correctable errors as "normal" errors via IRQs, and uncorrectable errors as fatal, unrecoverable alerts.

WDYT?

**Comment by tjaychen** [comment]
yes that looks good to me.
