### ISSUE TITLE
[otbn] Fully specify RND CSR/WSR

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#4209]
Specify what to expect when reading from the CSR/WSR.

## Better specify quality of random number in the RND CSR/WSR
Code on bignum has access to random numbers through the RND CSR or WSR. We need to specify the properties of these random numbers. 

We currently haven’t decided on how the random numbers exposed to the bignum application are generated. They will be somehow linked to the CSRNG outputs, but could be produced by CSRNG directly, or the output of CSRNG could be used as seed for a local LFSR.

## Provide more than one type of randomness
Currently, there is one single type of randomness made available to the application through the RND special-purpose register. It might be interesting to provide more than one type of randomness, e.g. “weak” and “cryptographically strong” randomness. This could be made available for example through two separate registers, e.g. RNDWEAK and RNDSTRONG

See also https://github.com/lowRISC/opentitan/issues/3522

**Comment by GregAC** [comment]
Closing as covered by #2638
