### ISSUE TITLE
[CI] "Check what kinds of changes the PR contains" Fails

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#4226]
Intermittently, this task fails, with no output and no clarity on why, for instance with this build for #4212 (but has also happened on others): https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=26790&view=logs&j=3a559e2a-952e-58d2-b8db-2e604a9266d7&t=dcdf62d6-c818-5cd7-fbbc-5e277ab47ca1

Re-running the job normally works, but it would be great if this kind of error didn't happen at all.

**Comment by imphil** [comment]
We've not seen this error for a while now, let's assume it's fixed.
