### ISSUE TITLE
[otbn] Specify what a LC_ESCALATE_EN does

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#4227]
OTBN should wipe internal state when it receives the LC_ESCALATE_EN signals. We need to specify what exactly is meant by that (and later implement it).

> estimate 2

**Comment by GregAC** [comment]
Note that `otbn_scramble_ctrl` in https://github.com/lowRISC/opentitan/pull/7020 handles the scramble keys and nonces. We can wire escalate directly into there and it should revert to the default key/nonce (specified with the `RndCnstxxx` parameters).
