### ISSUE TITLE
Support Uart baud rate 1500_000 when IO is 24Mhz

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#4263]
@eunchan @tjaychen 

Based on below formula, if uart baud rate is 1500_000 and IO is 24Mhz, NCO is 'h1_0000.
`NCO = (baud_rate * 2^20) / (clk_freq_mhz * 1000_000) `

But NCO in design is only 16 bit, so it's just over the max value we allow. So technically we don't support this baud rate.
Should we increase the size of NCO? Or can we use NCO='hffff for it, since the error of 1/'h1_0000 is way smaller than 2.5% error we can tolerate?

**Comment by tjaychen** [comment]
i need to look at this again..because i've completely forgotten what i read last time.
But if I remember correctly, increasing the NCO size does not actually help you support more frequencies.  Something about the way the baud rate is done I thought created an upper limit. 

I'll dig up some old emails...

**Comment by mdhayter** [comment]
Based on the documentation this should be fine.
The actual baud rate (fbaud equation) would be (1/16)*(65535/65536)*24MHz = 1499977 i.e. off by less than 0.0015%. What is the crystal tolerance?

The issues really only come when you are trying to make the low baud rates.

**Comment by eunchan** [comment]
As Mark mentioned theoretically with 24MHz, UART does not support 1.5Mbps (I would say Mbps as Mega/Giga in serial interface are usually power of 10). But in reality, it would be no problem to communicate at 1.5Mbps as error rate is really low.

**Comment by weicaiyang** [comment]
> Based on the documentation this should be fine.
> The actual baud rate (fbaud equation) would be (1/16)*(65535/65536)*24MHz = 1499977 i.e. off by less than 0.0015%. What is the crystal tolerance?
> 
> The issues really only come when you are trying to make the low baud rates.

Thanks Mark. To Mark's question "What is the crystal tolerance", @tjaychen do you have answer for this?

**Comment by weicaiyang** [comment]
> But in reality, it would be no problem to communicate at 1.5Mbps as error rate is really low.

@eunchan 
Just want to confirm the 1.5Mbps you mentioned here is 1500_000. I think with 1.5 * 2**10, the error is too big.

**Comment by tjaychen** [comment]
> > Based on the documentation this should be fine.
> > The actual baud rate (fbaud equation) would be (1/16)*(65535/65536)*24MHz = 1499977 i.e. off by less than 0.0015%. What is the crystal tolerance?
> > The issues really only come when you are trying to make the low baud rates.
> 
> Thanks Mark. To Mark's question "What is the crystal tolerance", @tjaychen do you have answer for this?

let me get back to you on that one.  It's probably going to be sum of the worst case errors from both our own clock and the external clock.  The latter we don't have a ton of control over, but at least I can find out what the former is, and we can maybe double that.

**Comment by eunchan** [comment]
Yes. I think M or G in the serial interface (e.g. PCIe) is always 10**6 , 10**9.

**Comment by weicaiyang** [comment]
> Yes. I think M or G in the serial interface (e.g. PCIe) is always 10**6 , 10**9.

Agree. For testing IO 24Mhz and baud rate 1.5Mbps, I will use NCO='hffff. Should we also mention this in the design spec, since this NCO is not calculated based on the equation in the spec?

And we also need to convince SW people that 1Mbps is 10**6.

**Comment by weicaiyang** [comment]
> i need to look at this again..because i've completely forgotten what i read last time.
> But if I remember correctly, increasing the NCO size does not actually help you support more frequencies. Something about the way the baud rate is done I thought created an upper limit.
> 
> I'll dig up some old emails...

Do you have a chance to get back to this issue? For IO 24 Mhz and baud rate 1.5 Mbps, we should use NCO = 'hffff as discussed. Ideal NCO should be 'h10_000, but we only have 16 bits for it. Is this the right approach we use go? Thanks

**Comment by tjaychen** [comment]
just wanted to document our discussion, and we've agreed that the 1-bit error out of the full 16b should be okay.

**Comment by weicaiyang** [comment]
Closing this. DV update is done at #4178
