### ISSUE TITLE
[keymgr] What is KMAC key value when transitioning to CreatorRootKey 

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#4284]
@tjaychen 

> CreatorRootKey is the first operational state of the key manager. When transitioning from Initialized to this state, a KMAC operation is invoked using the RootKey as the key (from OTP), and the remaining inputs as data.

From spec above, key value is just RootKey from OTP. Look at the RTL, key value is entropy ^ RootKey. Could you explain this?
```
      StWipe: begin
        prng_en_o = 1'b1;

        // populate both shares with the same entropy
        // This is the default mask
        if (cnt < EntropyRounds) begin
          cnt_en = 1'b1;
          for (int i = 0; i < Shares; i++) begin
            key_state_d[i][cnt] = entropy_i;
          end
        end
        // when mask population is complete, xor the root_key into the zero share
        // if in the future the root key is updated to 2 shares, it will direclty overwrite
        // the values here
        else begin
          cnt_clr = 1'b1;
          key_state_d[0] = key_state_q[0] ^ root_key_i;
          init_done_o = 1'b1;
          state_d = StInit;
        end
      end
```

**Comment by tjaychen** [comment]
yeah so this will change slightly in the future, because the value coming out of OTP will be two shares already.

But the basic idea here is that the `root_key` is split into "two shares" as it's being sent to kmac.  One share is entropy, and the other share is the same entropy^ the key.

That way when you xor the two shares together, you get key ^ entropy ^ entropy, which just gives you the key.

Does that help?

**Comment by weicaiyang** [comment]
> yeah so this will change slightly in the future, because the value coming out of OTP will be two shares already.
> 
> But the basic idea here is that the `root_key` is split into "two shares" as it's being sent to kmac. One share is entropy, and the other share is the same entropy^ the key.
> 
> That way when you xor the two shares together, you get key ^ entropy ^ entropy, which just gives you the key.
> 
> Does that help?

I see. how about the 2 shares digest data from KMAC? is it using the same way share1 ^ share0 to get the digest? Thanks

**Comment by tjaychen** [comment]
yeah that's right. The kmac digest is also in two shares. However we never explicitly combine them.
So when I integrate kmac with otp, i'm going to change the wipe state to wipe to all entropy, and then directly ingest the otp input. 

That should be clearer when i do it.

**Comment by tjaychen** [comment]
> > yeah so this will change slightly in the future, because the value coming out of OTP will be two shares already.
> > But the basic idea here is that the `root_key` is split into "two shares" as it's being sent to kmac. One share is entropy, and the other share is the same entropy^ the key.
> > That way when you xor the two shares together, you get key ^ entropy ^ entropy, which just gives you the key.
> > Does that help?
> 
> I see. how about the 2 shares digest data from KMAC? is it using the same way share1 ^ share0 to get the digest? Thanks
> 
> EDIT:
> I didn't see any logic to check the correlation of 2 share data in keymgr. Perhaps I can just randomize these 2 share digest data, right?

o yeah that's right.  From a testing perspective, you can randomize it however you like.

**Comment by weicaiyang** [comment]
Cool. Thanks for the explanation.
