### ISSUE TITLE
[otbn] Should we condense our memory layout a bit?

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#4285]
At the moment, we claim a 4MiB address space, containing a couple of registers and 2 lots of 4 KiB memory. Obviously, this is still peanuts compared to the 32-bit address space, but maybe we should dial this down a bit to make SoC-level work a bit easier. This came up in #4163.

How about changing base addresses of IMEM and DMEM to 64KiB and 128KiB, respectively? That way, we'll shrink by a factor of 16 in the address map (from 4MiB to 256KiB) but we've still got space to expand either memory by a factor of 16, which I think would probably swamp the rest of the chip :smile:

The tooling etc. *should* just work. Probably a one line change in the RTL somewhere.

@imphil, @felixmiller, @GregAC: What do you think?

**Comment by GregAC** [comment]
I'm happy to shrink things, as you say a factor of 16 is still plenty of growth room. We wanted the capability to do an easy last minute expansion and it that's more than 16x I suspect we'll have bigger problems!

**Comment by imphil** [comment]
Your proposal sounds good.

For reference: The current layout was done in https://github.com/lowRISC/opentitan/pull/2573.

I wonder how we got to a point where we have problems to fit a 4 MiB peripheral into the memory map, but I don't mind as long as we have a bit of breathing space.
