### ISSUE TITLE
[keymgr] KMAC data mismatch for advance state from StInit

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#4292]
@tjaychen 

In StInit, there is no statement `stage_sel_o = disable_sel ? ...`, so that stage_sel_o is `Disable` and we use random data for KMAC to generate key_state when we advance state to `StCreatorRootKey`

```
      StInit: begin
        op_done_o = op_start_i & kmac_done_i;
        op_accepted = op_start_i;

        // key state is updated when it is an advance call
        if (!en_i) begin
          state_d = StWipe;
        end else if (op_done_o && (disable_sel || kmac_op_err)) begin
          key_state_d = kmac_data_i;
          state_d = StDisabled;
        end else if (op_done_o && advance_sel) begin
          key_state_d = data_valid ? kmac_data_i : key_state_q;
          state_d = StCreatorRootKey;
        end else if (op_done_o) begin
          invalid_op = 1'b1;
        end
      end

      // all commands are valid during this stage
      StCreatorRootKey: begin
        op_done_o = op_start_i & kmac_done_i;

        op_accepted = op_start_i;
        stage_sel_o = disable_sel ? Disable  :
                      advance_sel ? OwnerInt : Creator;
        hw_sel_o = gen_out_hw_sel ? HwKey : SwKey;
```

Another minor issue:
I think we want to output digest data from KMAC if SW issues a gen_id or gen_sw_out even it's in non-working state (StInit, StDisabled). This is true for StDisabled. However, in StInit, there is no statement `hw_sel_o = gen_out_hw_sel ? HwKey : SwKey;`, so that hw_sel_o is default HwKey, which causes KMAC digest data aren't sent to sw_share_output registers. 

waveform:

> cd /edascratch/weicai-opentitan/ot/keymgr.sim.vcs/km_agent/0.keymgr_smoke/out
> verdi -ssr Verdi.ses &

**Comment by tjaychen** [comment]
oops, i missed this.
i'll push a fix tomorrow. 

I honestly at this point can't remember what's supposed to happen on invalid operations... but i think what you're saying is right.
So i should probably double check the documentation is consistent.

**Comment by tjaychen** [comment]
hmm...this makes me want to re-write `keymgr_ctrl` in a nicer way... let me think about it.

**Comment by tjaychen** [comment]
i think we can close this now right?

**Comment by weicaiyang** [comment]
> i think we can close this now right?

Thanks for reminding. Let me close it.
