### ISSUE TITLE
[doc] Secure Boot and Reference Mask ROM: Secure Boot Description

### ISSUE THREAD

**Issue by KVISDAOWNER** [lowRISC/opentitan#4315]
I have read the documentation and some of the source code and it is unclear to me when/how the [boot ROM](https://github.com/lowRISC/opentitan/tree/master/sw/device/boot_rom) is a part of the boot process flow. 

The [Secure Boot](https://docs.opentitan.org/doc/security/specs/secure_boot/) documentation mentions (metal) mask ROM as being known as Boot ROM. This makes me think that _ROM_ corresponds only to the functionality in mask_rom.c.

To my knowledge, there is no mentioning of the functionality from boot_rom.c and bootstrap.c. (Also not in [Reference Mask ROM: Secure Boot Description](https://docs.opentitan.org/sw/device/mask_rom/docs/) documentation)

**When is the boot_rom.c code executed?** It is mentioned in its [README](https://github.com/lowRISC/opentitan/blob/master/sw/device/boot_rom/README.md) that the boot_rom part is the first code to be executed in the system. But the documentation mentioned above suggests that the mask_rom part is executed right after power on. 

And also as a **suggestion**, I think it could be nice for the reader to see a diagram or some sequential explanation about how the boot files (especially boot_rom.c) corresponds to the documented boot process (what steps).

**Comment by imphil** [comment]
The boot rom you're linking to is a stopgap that we use currently. It is neither secure nor will it ship in silicon. It is in the process of being rewritten, the mask rom work you're seeing in this repository is part of it.

**Comment by KVISDAOWNER** [comment]
Okay, that makes sense, thank you for the quick response. But when will the bootstrap functionality eventually be executed during boot. As part of the secure boot? I assume that bootstrapping will be executed sometime after the ROM and ROM_EXT stages described in [Secure Boot
](https://docs.opentitan.org/doc/security/specs/secure_boot/)?

**Comment by imphil** [comment]
Which bootstrap functionality are you referring to? The whole boot process that we aim to use eventually is outlined in https://docs.opentitan.org/doc/security/specs/secure_boot/ (subject to changes, of course).

**Comment by KVISDAOWNER** [comment]
I'm referring to the functionality currently seen in [bootstrap.c](https://github.com/lowRISC/opentitan/blob/master/sw/device/boot_rom/bootstrap.c), i.e. validation of the image received over SPI and programming the image into flash. 

To my knowledge, this functionality is not described in https://docs.opentitan.org/doc/security/specs/secure_boot/ 

Is this also something that will be rewritten?
And will this functionality be part of the final boot, if so, at what stage?

**Comment by imphil** [comment]
Everything you find in boot_rom is the current development bootloader and will not be part of the final chip. The work in [mask_rom](https://github.com/lowRISC/opentitan/tree/master/sw/device/mask_rom) is intended to match the secure boot spec you've linked to, but again, both parts are under heavy development at the moment and not finalized.

**Comment by GregAC** [comment]
Note that the final boot setup will be strictly from code in flash/ROM, not a boot via SPI. For development purposes something like that may be required but this is all still under discussion and such functionality wouldn't be generally usable (likely the lifecycle state would be used: https://docs.opentitan.org/doc/security/specs/device_life_cycle/ to ensure an SPI boot, if one is at all available, is only possible in devices used for development/under test).

**Comment by KVISDAOWNER** [comment]
Okay, that makes sense!
