### ISSUE TITLE
dvsim - skip fusesoc/file-gen step?

### ISSUE THREAD

**Issue by svenka3** [lowRISC/opentitan#4333]
Hi,
  In dvsim flow, how do I say "Jump to compile/elab" with already generated code? In my case I am adding a new SIM support, and any issues on compile/elab is much faster to spot and debug if I can compile - first time fusesoc is fine, next time onwards I want to jump to compile and skip fusesoc steps (It takes definitive 2-3 minutes on a laptop).

dvsim --skip-fusesoc ? (:-)) 

Thanks
Srini

**Comment by rswarbrick** [comment]
dvsim doesn't support this at the moment. You might find it quicker to build just one IP block at once? This will still run through all the tool stuff that you want to test, but the design will be much smaller.

**Comment by svenka3** [comment]
Yes, am starting at uart IP level. But what I see happening is the fusesoc step executes every time I run dvsim, as you said it does not allow me to skip as of now. Possible enhancement request maybe?

Regards
Srini

**Comment by sriyerg** [comment]
We rely on FuseSoC to only generate the file list. This involves copying over all sources to a separate scratch area, and invoking external generators to create additional on-the-fly sources. Do you think you could benchmark it and see if there are any inefficiencies? I would assume that it is slow the first time, but on subsequent invocations, it is smart enough to update only if sources are modified, or generate files only if the generators or fusesoc cores have been updated. If there are inefficiencies, then you could file a bug with [olofk/fusesoc](https://github.com/olofk/fusesoc). 

ATM there are no plans to provide full control of all ASIC tool flow phases (unless sufficient people request it), so this would be quite low on our priority. In the meantime, you can simply comment out the steps you want to skip in `hw/dv/tools/dvsim/sim.mk`.

**Comment by rswarbrick** [comment]
Running FuseSoc takes just a second or two on my (old) machine. @svenka3: Maybe you could try running just the fusesoc command and timing it? If it's really slow for you, we should probably find out why.

If you're feeling adventurous, you could try out [py-spy](https://github.com/benfred/py-spy), which I used to profile and speed up fusesoc by quite a bit a few months ago (you'll have those patches, so there's presumably a different performance problem that you're hitting).

**Comment by sriyerg** [comment]
Closing because this is out of scope. Please use the suggested workaround above. Feel free to reopen if not satisfied.
