### ISSUE TITLE
[otbn] Make zero sized loops impossible to encode

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#4338]
As discussed in #3934 we'd like to alter the encoding of LOOP so a zero sized loop isn't possible. This will require some minor changes to the ISA yaml/documentation, ISS and RTL.

@rswarbrick will any changes be required to the RIG to support this?

> estimate 4

**Comment by rswarbrick** [comment]
No changes needed in the RIG (it doesn't yet support LOOP/LOOPI).
