### ISSUE TITLE
class variables not needed in reggen/topgen/tlgen

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#4341]
@eunchan 
@rswarbrick pointed out class variables are not needed in data.py below at #4309 
I feel it's better to change all these to just use instance variables. If you all agree on this, I can make a PR for this.

https://github.com/lowRISC/opentitan/blob/d0ab3e7074b5deb0fa653a61732a470d71d115ae/util/reggen/data.py#L20-L54

same for topgen and tlgen
https://github.com/lowRISC/opentitan/blob/d0ab3e7074b5deb0fa653a61732a470d71d115ae/util/topgen/validate.py#L146-L161

https://github.com/lowRISC/opentitan/blob/d342ce818292d715aac79427f5e4f082a637c3b8/util/tlgen/xbar.py#L10-L33

**Comment by eunchan** [comment]
Agree. Sorry for premature python codings from me (ashamed haha...)

**Comment by weicaiyang** [comment]
> Agree. Sorry for premature python codings from me (ashamed haha...)

Haha, I thought that were needed until I learned from @rswarbrick's comment

**Comment by rswarbrick** [comment]
Yeah, Python's pretty weird about this. To keep the "static schema" obvious, the usual style is to assign each field in the constructor (as you're already doing). Honestly, I think this is a pretty major flaw in the language design, but I think we're probably stuck with it. :disappointed:

**Comment by weicaiyang** [comment]
close via #4346
