### ISSUE TITLE
[RFC] IP generation script

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#4345]
## Objective

topgen tool has all the IP-specific generation codes inside. Each configurable IP also has its own generation script to generate example IP model. This RFC suggests a way to resolve the duplicated code issues and to have more maintainable topgen code by isolating the ip generation and merging process.

## Design Options

The idea is to introduce one script tool, ipgen. It reads config hjson and generate the IP into a target directory. It can run as a standalone or called by topgen. It still has limitations as most of the config knobs in current IP depend on the top-level (e.g. #interrupts).

I propose the ipgen in the slide below with the stretch goal to resolve the limitation. It introduces new IP-level config Hjson file and `config` field in the top-level Hjson.

Please see the [proposal slide](https://docs.google.com/presentation/d/1ue2BL0Qvc7ogzK_7DbxAKKVKT3Xq07r9nzaHATgTB2U/edit) (requires opentitan.org account) for more details

**Comment by asb** [comment]
Hi Eunchan - what's needed for this to be ready for TC review? It looks like there's a fairly thorough proposal, but it's lacking comments/input so might need circulating more widely / tagging likely reviewers?

**Comment by eunchan** [comment]
Hi Alex,

I didn't pay attention to this RFC due to other issues. I think I can make time after churning out current tasks (SPI Device).

**Comment by imphil** [comment]
Eunchan's design doc is available at https://docs.google.com/document/d/1jimqHdR1x8on3jwzsi8SHTdhXFvujHj-EFk-eGU9mX4/edit
