### ISSUE TITLE
dvsim - user experience (UX) enhancement

### ISSUE THREAD

**Issue by svenka3** [lowRISC/opentitan#4370]
Hello,
  Please read this from a newbie (to OpenTitan env/flow) perspective than expert/developer.

With that prologue, I get:

>> INFO: [FlowCfg] [results summary]: generated for email purpose [/home/srini/proj/OpenTitan_Google_VW/Git_OT_VW/opentitan/scratch/email.html]
>> ERROR: [dvsim] Errors were encountered in this run.

Having used dvsim for few days/weeks I understand there is 
 
> scratch/uart.sim.questa/qsta-support/default/build.log

How about the UX for a newbie? 

Would you consider printing a last line that shows the last-working-dir? or better thoughts?

Thanks
Srini

**Comment by sriyerg** [comment]
Yeah, I've been wanting to add it already. Will fix (but it will take a while).

**Comment by sriyerg** [comment]
Fixed with #4440.
