### ISSUE TITLE
[top_earlgrey] Memory map inconsistencies (vs. spreadsheet)

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#4376]
Comparing the hjson to the spreadsheet docs.google.com/spreadsheets/d/1ptfdrG5RWiYHKtjYyDO1ubGYPPlN_4YQfzRKO1G1Mls/edit#gid=0 I've seen the following inconsistencies in the memory map.

Naming:
- Rename "uart" to "uart0".
- Rename "eflash" to "flash" (or the other way around in the spreadsheet)
- All AON peripherals need to be renamed to have the _aon suffix.
- padctrl should be renamed pad_ctrl_aon.
- ram_ret -> ram_ret_aon (probably)

One further issue:
- sensor_ctrl is marked to be in Aon domain, which doesn't match the spreadsheet? Or is it hooked up in a special way? @tjaychen is this a bug or a misunderstanding on my side?

(I can then follow up with a PR.)

CC @msfschaffner @martin-lueker

**Comment by msfschaffner** [comment]
@tjaychen I believe you cleaned up some of that recently in https://github.com/lowRISC/opentitan/pull/5057. 
Can this issue be closed or are there still pending items?

**Comment by msfschaffner** [comment]
Closing this down since it has been addressed in #5057.
