### ISSUE TITLE
dvsim: hjson - help needed to pass double-quotes

### ISSUE THREAD

**Issue by svenka3** [lowRISC/opentitan#4378]
Hi,
  In HJSON how do I escape and sneak in  "" (double quotes)?

Say inside run_opts we have:

>  // "-do {run_script}"

but in Questa I need:
> -do "run -all; exit"

or

> -do "do questa/questa_run.do"

I tried below without luck:

```json
               //"-do \"run -all; exit\""
```

Maybe I am tired/lazy, seeking help!

Thanks
Srini

**Comment by sriyerg** [comment]
Try three single-quotes`''' do "run -all; exit" '''`.

**Comment by svenka3** [comment]
Thanks for the tip, did try, seeing an automatically inserted "do", so not 100% done - will debug, fix and report soon.

**Comment by sriyerg** [comment]
The '-' in front of 'all' needs to be doubly escaped. Otherwise, `vsim` will treat it as a switch and throw "invalid switch" error. This works:
```
               '''-do \"run \\-all; exit\"''',
```

**Comment by sriyerg** [comment]
I have confirmed that this works. Closing bug.

**Comment by svenka3** [comment]
@sriyerg

I see you recommending:

>  '''-do \"run \\-all; exit\"''',

With that I see inside Questa log run \-all --> though it works, I tidied it a bit as below and it works as well:             

>>  '''-do \"run -all; exit\"'''

I will soon change it to use DO file. 

Thanks for your help
