### ISSUE TITLE
Can't see anything in the serial console, when I run the coremark program

### ISSUE THREAD

**Issue by Sampsonksw** [lowRISC/opentitan#4387]
I have successfully ran the hellow_world program according to Getting started on FPGAs. Then I compiled coremark_top_earlgrey_fpga_nexysvideo.bin with the following command:
ninja -C build-out sw/device/benchmarks/coremark/coremark_top_earlgrey_fpga_nexysvideo.bin
And download to FPGA  with the following command:
build-bin/sw/host/spiflash/spiflash --input build-out/sw/device/benchmarks/coremark/coremark_top_earlgrey_fpga_nexysvideo.bin
But I can't see anything in the serial console, can someone help me?

**Comment by msfschaffner** [comment]
Apologies that this question has never been answered. 
This somehow fell through the cracks.

There has been a lot of development in the mean time including many many bugfixes (also in the debug module).
I hence encourage you to try with the most recent version of OpenTitan.

Please feel free to re-open this issue if the problem persists.
