### ISSUE TITLE
[otbn] Generate explicit documentation about operand shifts / offsets

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#4388]
We should improve the auto-generated documentation so that it clearly shows the relationship between:

 1. The number written in the source code
 2. The number used by the operation ("what actually gets added" etc.)
 3. The number that appears in the encoding

We're sort of doing that for operands with shifts already, but it's not very explicit. The "+1" offset that's added in #4373 needs documenting properly too.

**Comment by rswarbrick** [comment]
This is partially addressed by #4782.

**Comment by adzilee** [comment]
Nice

Pada Sel, 12 Jan 2021, 1:32 PG Rupert Swarbrick <notifications@github.com>
menulis:

**Comment by rswarbrick** [comment]
I think this is kind of done now (I forgot the issue when implementing it!)
