### ISSUE TITLE
[usbdpi] Improvements to USB DPI interface

### ISSUE THREAD

**Issue by mdhayter** [lowRISC/opentitan#44]
The usbdpi interface currently includes the test stimulus in the main-line code and is quite fragile as regards to timing.

Improvements:

- Read stimulus from a file (will require the DPI state machine to understand higher level constructs like packets)

- Build in initialization of USB device and make the simulation available as a usbip device. This allows the simulated USB device to be "plugged in" to a virtual USB port on the host.

**Comment by sjgitty** [comment]
On a mission to clean up old issues, scraping from stalest to freshest.

@vogelpi @mdhayter does @stefanlipunner's recent work in this
area change the status of this issue? Related comment: we will initiate
a conversation on how to move forward with USB soon.

**Comment by mdhayter** [comment]
The recent work was a good clean-up but doesn't really address the code being fragile to timing. I think both these are possible approaches to improvements.

**Comment by GregAC** [comment]
@alees24 is currently undertaking significant work in this area. I think this issue is superseded by issues he has opened and work he's currently doing so closing.
