### ISSUE TITLE
KMAC mem access stuck

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#4409]
@eunchan 

looks like TL may get stuck if randomly accessing KMAC memory. This causes some top-level mem test and TL test fail.

I think in the other IP we let memory return 0 rather than get stuck, if mem access occurs without proper initialization.
![Screen Shot 2020-12-03 at 12 10 14 PM](https://user-images.githubusercontent.com/49293026/101082598-8b971900-3560-11eb-9547-d59450a79b84.png)

Waveform:
/edascratch/weicai-opentitan/ot/top_earlgrey_asic.sim.vcs/fix_top_tl/0.chip_tl_errors/out
verdi -ssr Verdi.ses &

**Comment by eunchan** [comment]
Thanks Weicai,

I will make the ready signal to be 1 always if Sw access is not selected. And should report error for the scenario.

**Comment by weicaiyang** [comment]
> Thanks Weicai,
> 
> I will make the ready signal to be 1 always if Sw access is not selected. And should report error for the scenario.

Sounds good, thanks Eunchan.

**Comment by weicaiyang** [comment]
fixed via #2698
TL_error test should pass now. 
But we need to configure mem to be accessible at dut_init in order to make mem test pass. @udinator perhaps you can add this in your kmac_base_vseq and also update chip_base_vseq.
