### ISSUE TITLE
[dvsim] Allow setting `{tool}_build_opts` and `{tool}_run_opts` 

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#4414]
DVSim tool provides the ability to set built time and run time options via `build_opts` and `run_opts` keys in HJson. But what if the switches need to be set differently for each tool? We solve this by setting tool specific build / run modes and we enable those modes like this `en_build_modes: ["{tool}_my_custom_mode"]`. An example of this can be found here: 

https://github.com/lowRISC/opentitan/blob/1a10750ef129f39eab9bde2b12fee62ad492ce4f/hw/ip/aes/model/aes_model_sim_opts.hjson#L12

A better alternative is the augment the DVSim `Modes` class to allow setting `vcs_build_opts` and `vcs_run_opts` directly which will be used to set the tool-specific options, rather the limit it to generic, tool-agnostic versions of these opts. The example above would then look like this:

```
  build_modes: [
    {
      name: aes_model_build_opts
      vcs_build_opts: ["-CFLAGS -I{build_dir}/src/{aes_mode_src_dir}", "-lcrypto"]
      xcelium_build_opts: ["-I{build_dir}/src/{aes_mode_src_dir}", "-lcrypto"]
    }
  ]
```
This makes it relatively easy and natural to add support for more tools.

**Comment by svenka3** [comment]
I like this. Also what if a user wants to add a few options to run across a regression - typically run-time, such as:

+UVM_TIMEOUT=1000 +uvm_set_severity, +my_own_value_plusargs 

While we can do inside the HJSON - hard to across tests (Maybe HJSON can allow this indeed), maybe we can add an env-var like:

setenv SIMV_OPTS <>

I have mixed feeling about that solution, maybe there are better ways, but the problem is real, I face it at many client projects.

**Comment by sriyerg** [comment]
> I like this. Also what if a user wants to add a few options to run across a regression - typically run-time, such as:
> 
> +UVM_TIMEOUT=1000 +uvm_set_severity, +my_own_value_plusargs
> 
> While we can do inside the HJSON - hard to across tests (Maybe HJSON can allow this indeed), maybe we can add an env-var like:
> 
> setenv SIMV_OPTS <>
> 
> I have mixed feeling about that solution, maybe there are better ways, but the problem is real, I face it at many client projects.

That's exactly what the tool-agnostic `run_opts` is for, which can be set at various places - 'bare' in HJson (applies to all tests), within `build_modes` (collection of build options distilled into a single switch), `run_modes` (collection of runtime options distilled into a single switch), test specifications (applies to only that particular test entry), and regression entries (applies to all tests in that regression).
