### ISSUE TITLE
dvsim - alias for --run-only?

### ISSUE THREAD

**Issue by svenka3** [lowRISC/opentitan#4425]
Can we have an alias/short form for dvsim --run-only (may be -ro?)

Thanks

**Comment by svenka3** [comment]
I see -ro is taken up, need another - maybe "-rs" --> RunSim, or "ru"

**Comment by weicaiyang** [comment]
Agree, this is useful opt, it's better to have a shortcut. 
Created PR #4434
Welcome to create PR to make change directly, which saves some iteration time.
