### ISSUE TITLE
[kmac] Error Handling, additional control logics

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#4433]
This issue summarizes remaining tasks in KMAC. The item listed below should be implemented in KMAC.

## Error Scenario

- [ ] While in KDF operation, if the software sends commands or Message, assert error and discard the software inputs.
- [ ] If the software initiates the KMAC by sending `CmdStart`, then KMAC should hold KeyMgr request and notify the software for collisions.
- [ ] KMAC checks the first 6 bytes of the prefix when the software initiates KMAC operation (not SHA3, SHAKE, cSHAKE). If it is not `encode_string("KMAC")`, then raises an error and abort the operation.

**Comment by tjaychen** [comment]
@cindychip 
we probably want to double check if these are still valid :)
I think in all liklihood it has been handled in a different way (probably the `kmac_app` interface arbitration).

**Comment by tjaychen** [comment]
i believe these are all done already.
I'm closing this now, please re-open if there are any objections.
