### ISSUE TITLE
dvsim - interactive run?

### ISSUE THREAD

**Issue by svenka3** [lowRISC/opentitan#4445]
Hi,
  How do I run an interactive test using dvsim? Say I want to bring in UCLI (not GUI, just command line) in VCS, TCL in XLM or Questa. As of now it looks to me like the Deploy/Run seems not to give the prompt to user control. 

What am I missing?

Thanks
Srini

**Comment by sriyerg** [comment]
We have not had the need to do this yet, so it is not supported out of the box in an easy way (GUI is not supported either). The other reason is, for ad hoc debug you can easily edit the `hw/dv/tools/dvsim/vcs.hjson` and delete `-do {run_script}` so that the `simv` returns back the `ucli` prompt to the user. I assume likewise for other tools.

**Comment by svenka3** [comment]
With Questa adding GUI was easier. That command prompt led to some hang, will debug and report.

So should I attempt and raise PR? Or is dvsim meant to be a regression only script? I would prefer to evolve something that many projects can adopt beyond OT.

**Comment by sriyerg** [comment]
The goal is indeed to go beyond OpenTitan and cater to as many projects' needs / tools / ASIC flows as possible! It's built not just for running regressions, but for debugging simulations as well (and running several other ASIC tool flows such as FPV, lint and synthesis). 

We would love to have Questa supported as well, though we will not be able to run simulations periodically ourselves to check its health. Please go ahead and submit the PR - we will fix things as needed through review comments. The guidelines for making a PR can be found here:
https://docs.opentitan.org/doc/ug/github_notes/

**Comment by msfschaffner** [comment]
@sriyerg @cindychip can you update this issue?
