### ISSUE TITLE
[edn] async requests

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#4446]
There may be some peripherals that will request entropy from a different clock domain (for example otp / lc_ctrl).
For these modules, we probably need to move to a full 4 phase handshake.  Or maybe the edn should just assume all the interfaces could be async. 

However, the existing design (only looked at the diagram) seems like it might be assuming a fully synchronous interface.
I don't think we want to route the edn clock into all the peripheral modules that might make entropy requests.

What do you think?

**Comment by tjaychen** [comment]
@martin-lueker 
@senelson7

**Comment by tjaychen** [comment]
if we do want to route the edn clock to the various end points that request entropy (we should probably do this for all, just because something is on the same domain now doesn't mean it always will be), then it might make sense to have edn source / destination modules that everyone re-uses (similar to alert handlers).

Then we can at the integration level point out which module is async and which is sync (again similar to alert handler).  My personal preference (though it's a bit overkill), is to just assume these interfaces are async since I prefer not to route `edn_clk` to all the modules (and this could set a bad precedence because there are other clock domain crossings) , but let me know what you guys think.

**Comment by mwbranstad** [comment]
@tjaychen EDN was intended as the "gasket" to delivery entropy, so things like an async interface would naturally belong in it. I would like to make all ports the same, as in all async interfaces, even for sync interfaces, would should work ok if we have a good common async block to do this function.

**Comment by tjaychen** [comment]
yes that sounds good to me.

Before we do any changes though, @udinator / @weicaiyang / @cindychip can you guys chime in?
I'm not sure how the generic push-pull verification interface you guys designed is intended to work these.  If you see my other issue, there is a similar issue from otp to the modules receiving the scramble key.

So it seems like the design / dv here should ideally go hand-in-hand.  We have a common async block to handle this as Mark says, and also make sure the DV is okay to match.

**Comment by mwbranstad** [comment]
@senelson7 fyi

**Comment by weicaiyang** [comment]
> yes that sounds good to me.
> 
> Before we do any changes though, @udinator / @weicaiyang / @cindychip can you guys chime in?
> I'm not sure how the generic push-pull verification interface you guys designed is intended to work these. If you see my other issue, there is a similar issue from otp to the modules receiving the scramble key.
> 
> So it seems like the design / dv here should ideally go hand-in-hand. We have a common async block to handle this as Mark says, and also make sure the DV is okay to match.

It makes sense to me to make the request async. We need to update push-pull agent to make the req/ack interface support async as well. I think the protocol should be similar to 4 phase handshaking in alert handler, but it's good if we can have a doc to describe this protocol and the parameters it can support.

**Comment by tjaychen** [comment]
see #4441 for the conclusion.
