### ISSUE TITLE
Byte offset error on Verilator

### ISSUE THREAD

**Issue by berkguldiker** [lowRISC/opentitan#4470]
Hello,
I am trying a program written in Rust for OpenTitan. It can be flashed into the board but I want to debug it on Verilator. I use the boot_rom_sim_verilator.elf as ROM code and the Rust program as the flash code. Unfortunately, I get an error, which reads "ERROR: Could not set `flash' memory at byte offset 0x40000." I couldn't find any explanation about the error. Do you know what it means or why it happens?
Many thanks in advance.

**Comment by rswarbrick** [comment]
This error message is generated by the code that loads your ELF file into memory. I suspect that you haven't got the (rather arcane) command line quite right: can you share the command line you ran?

**Comment by berkguldiker** [comment]
$ build/lowrisc_systems_top_earlgrey_verilator_0.1/sim-verilator/Vtop_earlgrey_verilator   --meminit=rom,build-bin/sw/device/boot_rom/boot_rom_sim_verilator.elf   --meminit=flash,/media/earlgrey-uart

**Comment by rswarbrick** [comment]
Ok, so the error is saying the code was reading `/media/earlgrey-uart` and trying to write it into our simulated flash memory. It managed to write the first `0x3ffff` bytes, and failed at the next one. I think you're probably just passing in the wrong file as your flash image.

**Comment by berkguldiker** [comment]
According to readelf the file size is not bigger than 100 KiB. However unlike your Hello Word file the text section is in segment 01.

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x001000 0x10000000 0x10000000 0x00000 0x00001 RW  0x1000
  LOAD           0x001000 0x20000000 0x20000000 0x03f15 0x03f15 R E 0x1000
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0x10

 Section to Segment mapping:
  Segment Sections...
   00     .bss 
   01     .flash_header .crt .text .rodata 
   02

**Comment by berkguldiker** [comment]
According to readelf the file size is not bigger than 100 KiB. However unlike your Hello Word file the text section is in segment 01.

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x001000 0x10000000 0x10000000 0x00000 0x00001 RW  0x1000
  LOAD           0x001000 0x20000000 0x20000000 0x03f15 0x03f15 R E 0x1000
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0x10

 Section to Segment mapping:
  Segment Sections...
   00     .bss 
   01     .flash_header .crt .text .rodata 
   02

**Comment by rswarbrick** [comment]
Oh, it's an ELF file? The problem is that you need to tell the meminit code so (it's currently trying to load the file as vmem). The easiest thing is to rename the file to end in `.elf`. The code that's getting confused is `DetectMemImageType` in `dpi_memutil.cc`. If you're feeling enthusiastic, it would be great to add a magic number test that could recognise an ELF file here.

**Comment by berkguldiker** [comment]
I added `.elf` to the name but the error persists. Can the problem be because of the difference in section to segment mapping?

**Comment by rswarbrick** [comment]
Oh! Yes, it could. The code works by flattening the segments just like `objcopy` does. Here, you have two segments of size 1 byte and 0x3f15 bytes, but they will be laid out starting at the first non-empty segment. So the flattened image will actually be `0x2000003f15 - 0x10000000` bytes (roughly 256 MiB) big. Oops!

I think you'll have to ask someone who knows more about our Rust toolchain to figure out what you actually need to do here. @lenary: Could you weigh in?

**Comment by lenary** [comment]
@berkguldiker What source code are you using for your rust program? This is very likely to be some kind of linker script problem, but i see you have a `.flash_header` section which is a name we use for information the boot rom needs. It's really hard to debug without seeing the linker script, in all honesty, so if you can find a way to share that, that would be a massive help. I may also ask to see some assembly files if they're relevant (esp the file where the `.flash_header` section is defined).

**Comment by berkguldiker** [comment]
@lenary I am using [https://github.com/nholstein/opentitan.rs](https://github.com/nholstein/opentitan.rs). It had a former version of `flash_link.ld` but I have changed the script a bit and added the `.flash_header` section. Here are the linker and the assembly. (which is is in main.rs) 
[LinkerAndAsm.zip](https://github.com/lowRISC/opentitan/files/5664423/LinkerAndAsm.zip)

**Comment by berkguldiker** [comment]
It started working after I put the program headers in right addresses in the physical memory.
