### ISSUE TITLE
[rom-checker] Consider merging with ROM to make a "ROM controller"

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#4498]
We're early in the design drafting stage for a "ROM checker" module, which would run at the start of time to make sure the contents of ROM hadn't been tampered with.

Rather than communicate with the ROM over the main system bus, another option would be to bundle the ROM and the checker together into one tightly-coupled block.

We should think this through properly before we start writing any RTL.

**Comment by rswarbrick** [comment]
@tjaychen: Does this properly capture what you were saying?

**Comment by tjaychen** [comment]
yes that's right!
This ROM controller module then would have connections to pwrmgr, keymgr
and kmac as you've pointed out.

**Comment by rswarbrick** [comment]
I think we can safely say that this is done :-D
