### ISSUE TITLE
[lc / flash] Access rights

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#4504]
The flash isolated partitions have the following access rules

Accessible = read / write
Readable = read only
Writeable = write only

Software Access Table 
| Asset                  |   Raw / Test Locked   |  Test unlocked         | Production states  | RMA |
|------------------      | ----------------------------  | -------------------         | ------------------------ |  ----- | 
| creator seed       |  no access                  |  no access               | accessible if ID blank | accessible |
| owner seed        |   no access                 |  no access               | accessible  | accessible |
| isolated partition |  no access                   |  writeable               | accessible |  accessible  |

Hardware Access Table 
| Asset                  |   Raw / Test Locked   |  Test unlocked         | Production states / RMA |
|------------------      | ----------------------------  | -------------------         | ------------------------ | 
| creator seed       |  no access                  |  no access               | readable if ID not blank | 
| owner seed        |   no access                 |  no access               | readable if ID not blank |
| isolated partition |  no access                  |  no access               | no access                       |

To support this function, the life cycle controller will implement the following signals instead of the existing `provision_wr_en` and `provision_rd_en` which are not enough to cover its needs. 

```
creator_seed_sw_rw_en
owner_seed_sw_rw_en
iso_part_sw_rd_en
iso_part_sw_wr_en
seed_hw_rd_en
```

Additionally, the `lc_nvm_debug_en` signal also needs an earlier cut-off (before production states) to ensure the isolated partition above cannot be backdoor'd during specific TEST states.  Whether this should be tied directly to life cycle or another OTP needs to be quickly discussed.

**Comment by tjaychen** [comment]
@cindychip 
@sriyerg 
FYI

**Comment by msfschaffner** [comment]
I am about to update the lc_ctrl documentation to reflect this.

One thing I notices is that the way we currently lock down partitions in OTP, we cannot re-enable access to the partition holding the ROOT_KEY.

Hence the creator seed SW access is currently only `accessible if ID blank` in the RMA state. Is that ok?
