### ISSUE TITLE
[otbn] At what point do we fault on a bad PC?

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#4511]
If I execute an instruction like
```
  jalr x2, x3, 0
```
and `x3` contains `0x1`, this will cause a fault because of the misaligned PC. Do we spot the fault at the start of the next instruction, or as part of executing the jump?

This probably doesn't need documenting, because it shouldn't be visible to the host processor. But we do need to decide, because the ISS and RTL need to agree on the final value of `x2`.

@GregAC: I don't think this is implemented in RTL yet(?). What are you planning?

**Comment by GregAC** [comment]
This is implemented (thought not tested!) in RTL. It will fault on that instruction.

The controller looks at the next address being fetched, and will fault if it's misaligned or generated from a calculation that's overflowed.

**Comment by GregAC** [comment]
however final value of `x2` still TBD pending discussion of https://github.com/lowRISC/opentitan/issues/4507, right now OTBN will halt on that instruction but the register write will still occur.

**Comment by rswarbrick** [comment]
Thanks for the reply. It looks like the ISS should definitely catch the fault on the evil jump instruction. Let's discuss what happens next in #4507 :-)

**Comment by rswarbrick** [comment]
Oh, drat. I forgot to ask about the other error case. Do we also do range checks on the jump instruction? For example, when do we spot a problem if `x3` contains `0xf0000000`?

**Comment by GregAC** [comment]
We do

**Comment by rswarbrick** [comment]
Brill, that's easy then! :-)
