### ISSUE TITLE
[otbn, sw] clarification on the RSA signature verification routine

### ISSUE THREAD

**Issue by yizhou7** [lowRISC/opentitan#4547]
Following up on a discussion with @gkelly  @domrizz0 : 

We are wondering what the plan is for the RSA signature verification routine that will be used for the secure boot process. `modexp.s` seems to be a general verification routine that handle variable key lengths. Is there going to be a version tailored to the specific key length used by the secure boot process? If so, what differences would be expected? Thank you.

**Comment by imphil** [comment]
We now have a specialized version of RSA verification for secure boot, merged in https://github.com/lowRISC/opentitan/pull/6132 and further updated since.
