### ISSUE TITLE
Unable to flash images over SPI

### ISSUE THREAD

**Issue by alistair23** [lowRISC/opentitan#4553]
Between https://github.com/lowRISC/opentitan/commit/956bc343f714df574d671870def96791b1a2663c and https://github.com/lowRISC/opentitan/commit/9e10420314861224009ef04c5f1201743fdfa862 the spiflash tool is unable to flash images to the SPI.

Before commit https://github.com/lowRISC/opentitan/commit/9e10420314861224009ef04c5f1201743fdfa862 running the following command:

```
./build-out/sw/host/spiflash/spiflash --dev-id="0403:6010" --input=tock/target/riscv32imc-unknown-none-elf/release/earlgrey-nexysvideo-app.bin
```

would print

```
Running SPI flash update.
Image divided into 217 frames.
frame: 0x00000000 to offset: 0x00000000
frame: 0x00000001 to offset: 0x000003d8
frame: 0x00000002 to offset: 0x000007b0
frame: 0x00000003 to offset: 0x00000b88
...
```

and flash an image to the flash on the Nexys Video FPGA and boot the image.

Between https://github.com/lowRISC/opentitan/commit/956bc343f714df574d671870def96791b1a2663c and https://github.com/lowRISC/opentitan/commit/9e10420314861224009ef04c5f1201743fdfa862 the spiflash tool is unable to flash images.

On the host I see:

```
Running SPI flash update.
Image divided into 217 frames.
frame: 0x00000000 to offset: 0x00000000
Didn't receive correct hash before timeout.
frame: 0x00000000 to offset: 0x00000000
Didn't receive correct hash before timeout.
frame: 0x00000000 to offset: 0x00000000
Didn't receive correct hash before timeout.
frame: 0x00000000 to offset: 0x00000000
...
```

and on the UART I see:

```
I00000 boot_rom.c:52] Version:    opentitan-snapshot-20191101-1-3549-g9e104203
Build Date: 2020-12-13, 23:42:26

I00001 boot_rom.c:61] Boot ROM initialisation has completed, jump into flash!
```

So it seems like the ROM thinks it has something to boot to, but doesn't actually load anything.

**Comment by imphil** [comment]
The two commits you linked to are part of one push and depend on each other; I wouldn't expect master between those commits to work. However, it should work on master, and CI confirms that.

Unrelated to spiflash, we however see after 9e10420 that a GPIO smoke test broke. I'm therefore backing out this change in #4555.

Can you double-check if spiflash on the current `master` works for you? It certainly does for non-rust-SW on FPGAs in CI.

**Comment by imphil** [comment]
Oh no, even more confusing. The PR CI (https://github.com/lowRISC/opentitan/pull/4155) did only fail on the GPIO smoke test on FPGAs, the CI after the PR was merged into master now shows the spiflash problem @alistair23 is reporting here. So two things to sort out, either way, the backout should get us back into a better state for now.

Sorry for the confusion.

**Comment by imphil** [comment]
We run spiflash on Nexys Video in CI and are reasonably confident that it works in the general case. @alistair23 please re-open with more information if that is still a problem for you.
