### ISSUE TITLE
[Github] Issue and Pull-Request Template

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#456]
Looks like github supports [Issue template](https://help.github.com/en/articles/creating-issue-templates-for-your-repository) and [Pull-Request template.](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository)

It would be helpful for users to create a bug issue or to get a hint (of what to do before create pull-request) while creating pull-request

CC: @asb @sjgitty @aytong

**Comment by aytong** [comment]
Coming back to this aging issue, I don't have admin privilege to this repo.  @asb, @sjgitty, can you grant me, or reassign?  Thanks.

**Comment by asb** [comment]
Hi Andy - issue and PR templates can be committed using normal pull requests + review, which would be our preferred path. I think the next step is to draft the proposed PR/issue templates you feel would be useful.

**Comment by rswarbrick** [comment]
Are we still seriously considering this? (@eunchan: I think you opened the issue?)

Personally, I'm not convinced it's worth it, and would suggest just closing.
