### ISSUE TITLE
Pre-submit check lintpy

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#4567]
As discussed in #4554, should pre-submit check lintpy.py only applies to the incremental chance or the entire updated file?

I keep seeing `lintpy` create a lot of changes in dvsim script. I feel we may use a different version of style tools or maybe my setting is not right. With `./lintpy.py --fix -f dvsim/FlowCfg.py`, I see a bunches of style violations.

@eunchan @rswarbrick any thoughts?

**Comment by sriyerg** [comment]
@weicaiyang, try these steps:
- `git add <py-files>`
- `./util/lintpy.py -c --fix`

This should IMO only lint the incremental changes. I may have on rare occasions, run into problems though, with something else getting updated as well, for instance the `import` lines being moved around.

**Comment by rswarbrick** [comment]
We can't run `lintpy --fix` as a pre-commit hook with Yapf because it's not stable. See the (ancient) #77 for a discussion. I think we've got a lint run (with flake8, at least) as part of CI, but we're ignoring its results. We've got #1863 that discusses this. Maybe we should turn on the check?

@imphil: As CI guru, do you have an opinion?

**Comment by imphil** [comment]
flake8 by itself isn't really helping the developer experience as it doesn't have a "fix" mode. I'd go for another enforcing formatter instead, and black seems to be stable and preferred by other projects as well (e.g. Mozilla reformatted their whole tree recently). I added a bit of discussion to #77, let's hopefully find agreement there.

**Comment by weicaiyang** [comment]
Thanks everyone's comments. 
I will use `./util/lintpy.py -c --fix` for now as Sri suggested. Let me close this one and continue the discussion at #77
