### ISSUE TITLE
[doc] CreatorIdentity and OwnerIdentity VS Silicon Creator/Owner public and private keys

### ISSUE THREAD

**Issue by KVISDAOWNER** [lowRISC/opentitan#4596]
**Are the following notions of keys/identities equivalent?**
Silicon Creator public and private key pair  = CreatorIdentity asymmetric keys?
Silicon Owner public and private key pair  = OwnerIdentity asymmetric keys?

_Identities are mentioned in:_ 
https://docs.opentitan.org/doc/security/specs/identities_and_root_keys/
https://docs.opentitan.org/doc/security/specs/attestation/

_Public and private are mentioned in:_ 
https://docs.opentitan.org/doc/security/specs/secure_boot/

**Comment by KVISDAOWNER** [comment]
Or to rephrase to the question: **Are the CreatorIdentity or OwnerIdentity at any point used to sign or validate the signature of some of the boot stages?**

**Comment by tjaychen** [comment]
@lenary 
@gkelly 
@moidx 

I could be wrong, but my understanding is that the identity is really meant for authentication and attestation purposes for the HW / SW combo of the chip.  The actual signing of the firmware loaded onto the device I understood to be a separate key pair.

**Comment by moidx** [comment]
Hi @KVISDAOWNER, the CreatorIdentity and OwnerIdentity keys are only used in attestation flows. Secure boot is handled via a separate set of keys. 

*   Attestation details are covered in https://docs.opentitan.org/doc/security/specs/attestation/
*   Provisioning of code verification keys for the Silicon Owner are covered in the Ownership Transfer doc: https://docs.opentitan.org/doc/security/specs/ownership_transfer/

**Comment by KVISDAOWNER** [comment]
Many thanks for your response! I was hoping for the opposite answer as this have somewhat shattered my understanding :D So I have some follow up questions:

- It is my understanding that the key derivation is done at every boot. How does the chip then determine that the derived keys are correct?

- How are the Creator and Owner Identity used to attest the authenticity and integrity of the SW/HW combo? It is my understanding that they can be used to vouch for a new owner during ownership transfer, but other than that I find it hard to find their use in the documentation.

- Are the Silicon Creator public key (stored in ROM) and the Silicon Owner public key (stored in Boot Info Page) readable for subsequent boot stages (i.e. BL0 and the Kernel)?.

**Comment by moidx** [comment]
> How does the chip then determine that the derived keys are correct? 

*    The silicon creator identity is endorsed by the manufacturer at manufacturing time. There is a certificate signed with the
      Silicon Creator manufacturing PKI. The certificate will be available on the device, but also distributed along with the
      devices (e.g. device shipment registry). 
*    The silicon owner will endorse the Silicon Owner identity at ownership transfer time. This is a mechanism used to
      bootstrap the Silicon Owner PKI.
*    There are also considerations for key derivations for storage flows, but I am leaving that out from this discussion since 
      this thread is mostly focused in attestation.

>  How are the Creator and Owner Identity used to attest the authenticity and integrity of the SW/HW combo? 

*   The attestation keys are used to sign certificate chains that endorse the hardware and software configuration of the 
     device. An attestation chain can be used to define an authentication protocol. There are two mechanisms
     available for this: (1) Via PKI, the measurements are rooted in the PKI of the root certificates (either Silicon Creator or 
     Silicon Owner. (2) Via a device registry; at Ownership Transfer time, the Silicon Owner can ingest device identities into
     a device registry for authentication purposes. Depending on the device system integration flow, a hybrid flow employing
    (1) and (2) may be used. 

>   Where are the code signing keys stored? 

*   Silicon Creator public keys will most likely be stored in the mask ROM. They may also be stored in OTP. 
*   The pub keys for the first stage of the Silicon Owner code is stored in a special flash partition. It only needs to be 
     available to the ROM_EXT. Subsequent boot stages can manage the storage of public keys for next boot stages, so it is 
     not a requirement to make public keys available in stages where they are not consumed.  Here is an example of 4 boot
     stages:

     ROM (`rom_ext_pub_keys`) --> ROM_EXT (`bl0_pub_keys`) --> BL0 (`kernel_pub_keys`). 

     In this case ROM_EXT only knows how to verify BL0, and is not required to understand how to parse `kernel_pub_keys`, 
     and consequently, BL0 is required to manage these keys.

**Comment by moidx** [comment]
Please reopen the issue if you have any follow up questions in this topic. Thanks.
