### ISSUE TITLE
[otbn] Change error code to bitfield

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#4597]
OTBN errors are currently indicating with a single error code. This should be switched to a bit-field. This will allow multiple errors to be indicated so no prioritisation to produce a code will be required.

There is a need for a mode where this bitfield only indicates success or error, without further details on what the error was. This mechanism should be implemented and controller via a top-level signal input into `otbn_core`. For now this top-level input can be tied to 1 whilst discussions are ongoing about how to control this mode.

> estimate 6

**Comment by GregAC** [comment]
First renumber things but still have one error at once (for both RTL and ISS), then allow multiple errors as the next step.

**Comment by GregAC** [comment]
First PR for this is here: https://github.com/lowRISC/opentitan/pull/4822 switches to using an error bitfield with appropriate SW/Doc/RTL updates.

Next ISS changes are required so it can generated multiple errors. We can then modify RTL to drop the error prioritization.

**Comment by imphil** [comment]
With #4822 errors are now a bitfield, which is what we wanted to achieve here. Further work will be needed to actually generate more than one error bit at the same time.

@GregAC can you file follow-ups for that?
