### ISSUE TITLE
[security block power] Can cypher blocks run at the same time and spike chip power?

### ISSUE THREAD

**Issue by mwbranstad** [lowRISC/opentitan#4601]
Should there be a handshake/semaphore between power hungry blocks (cyphers) to prevent the worst case power spike condition? It is assumed that these blocks run rarely, so preventing a worst case power condition is deemed desirable.

**Comment by mwbranstad** [comment]
@tjaychen @zi-v @martin-lueker @cdgori @senelson7

**Comment by tjaychen** [comment]
@moidx 
@gkelly 
ah i think when we originally thought about this, the idea was more to manage it using software.
None of the crypto blocks (with the exception of es / csrng which run in the background) activate by themselves, and all need to be marshalled by software.

So my hope at least is that we will manage it at that level. 

Let me know what you guys think.

**Comment by mwbranstad** [comment]
An interface between entropy_src and csrng has been added to prevent power spikes, which basically prevents sha3 in ES and AES cipher core in csrng from running at the same time.
