### ISSUE TITLE
[question] OpenTitan mailing list?

### ISSUE THREAD

**Issue by jhand2** [lowRISC/opentitan#4617]
Hello! I was looking through some of the OpenTitan docs and saw that CONTRIBUTING.md mentions a mailing list:

> If you would like to make a large-scale change or discuss multiple implementation options, discuss on the mailing list.

However I don't see any mention of a mailing list in any docs. Does a mailing list exist for the project or is that line just a leftover artifact?

**Comment by imphil** [comment]
Thanks for your interest in OpenTitan.

There is a mailing list at [opentitan-dev@opentitan.org](https://groups.google.com/a/opentitan.org/forum/#!forum/opentitan-dev).

There's also a PR to fix the documentation on this which is awaiting review from @domrizz0 at https://github.com/lowRISC/opentitan/pull/3824. Please have a look at this PR for more information on the mailing lists and the contribution process.

**Comment by jhand2** [comment]
Ah, thanks for the pointer!
