### ISSUE TITLE
[otbn] Document error priorities

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#4631]
We've got various different ways that OTBN code can stop with an error and only one error can "win" in a cycle. However, it's possible to cause multiple errors at once. For example, this code has a jump at the end of a loop (not allowed), which jumps to a misaligned address (also not allowed): which error code do we register?
```
loopi 1, 1
jal   x0, 0x3
```

@GregAC: This probably just means writing down the priority order that's currently encoded in the RTL. I don't think it really matters what the ordering is, but we need to document it because the ISS needs to match.

**Comment by imphil** [comment]
Both of them, once we have made the error code a bitfield? (#4597)

**Comment by rswarbrick** [comment]
Duh, good point! I'll pick one arbitrarily in the ISS for now, and fix things up to use a bitfield properly when the RTL switches over.
