### ISSUE TITLE
[prim_ram] High FPGA BRAM utilization

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#4670]
I just noted that the `prim_ram_1p` component instantiated inside the retention RAM has utilizes a lot more BRAM resources than expected. The memory has a width of 32 bits + 4 bits for parity and is 1024 entries deep. I would expect Vivado to map this to two BRAM36 instances. These are 36 bits wide and 1000 entries deep. However the actual utilization is 18 BRAM blocks.

As we are currently using 80% of the BRAM resources on the NexysVideo, we should probably investigate what's going on here.

I am not sure, it could also be that this is a known issue. Any ideas @tjaychen , @msfschaffner ?

**Comment by msfschaffner** [comment]
Thanks for catching that @vogelpi!

Indeed, this is a problem, and I believe it is not only the retention RAM, but also the main RAM seems to be twice as large as it needs to be.

I.e. I would expect the tool to map the rams to the following resources:
- main RAM: 16k x (32+4bit) = 16 RAMB36
- ret RAM: 1k x (32+4bit) = 1 RAMB36

If I recall correctly, one has to be careful to correctly specify the byte write enables in RTL such that the tool can map that correctly. I think this is currently specified the in the wrong format within `prim_ram_1p_adv`, hence leading to a suboptimal mapping (i.e. the word is assembled as `{data, parity}`, while it should actually be `{data[31:24], parity[3], data[23:16], parity[2] ...}`). I'll take a look and try fix it.

**Comment by msfschaffner** [comment]
Ok, I made a fix for this. Utilization goes down to 65% with the fix applied.

**Comment by vogelpi** [comment]
Awesome, thanks for the quick fix!
