### ISSUE TITLE
[dv] dvsim + Xcelium - top/snapshot name 

### ISSUE THREAD

**Issue by svenka3** [lowRISC/opentitan#4690]
Hi,
  Using Xcelium to simulate:

```log
util/dvsim/dvsim.py -t xcelium hw/ip/uart/dv/uart_sim_cfg.hjson -i uart_smoke -r 1
```
I see the XLM snapshot as:
```log
	Writing initial simulation snapshot: worklib.uart_bind:sv
```
Not a very big deal, but somewhat misleading - ideally it should have been "tb". 

I believe this is due to how XLM names the sanpshot by default and I see in the build.log the command as:
```log
 -top uart_bind -top uart_cov_bind -top tb -access +rw +define+XCELIUM
```
I guess XLM choses the first -top as snapshot name by default. I believe they support a -snapshot (or used to be that) option to rename if needed. But I believe it is easier if the hjson/dvsim does an append than prepend of sim_tops. The was I see it, common_sim_cfg.hjson has

sim_tops : ["tb"]

And then UART adds as:

```json
 // Add additional tops for simulation.
  sim_tops: ["uart_bind", "uart_cov_bind"]
```
Is it easy to make that an append style so that the eventual build command gets "tb" as first?

Cheers

 -top uart_bind -top uart_cov_bind -top tb

**Comment by sriyerg** [comment]
The tool should not be assuming a specific ordering for the supplied `-top` options. Is there another missing switch to `Xrun`?

**Comment by svenka3** [comment]
Well the tool has to make a choice and IIRC this has been the choice since 2000 or so in Incisive tool. There is a -snapshot argument to specify the name, should I add 

  -snapshot tb

To xcelium.hjson

**Comment by sriyerg** [comment]
> Well the tool has to make a choice and IIRC this has been the choice since 2000 or so in Incisive tool. There is a -snapshot argument to specify the name, should I add
> 
> -snapshot tb
> 
> To xcelium.hjson

I read the Xcelium ref manual. The tool uses the first specified 'top' as the name for the elaborated tb. Since we have a 'multi-top' architecture where the tops are specified in different HJson files, it is not possible to order it such that the tb is first in that list. The `-snapshot` seems like the correct solution for this - it enables the name for the elaboration to be set correctly. It needs to be set like this: `-snapshot {tb}` in `xcelium.hjson`.

**Comment by svenka3** [comment]
> > Well the tool has to make a choice and IIRC this has been the choice since 2000 or so in Incisive tool. There is a -snapshot argument to specify the name, should I add
> > -snapshot tb
> > To xcelium.hjson
> 
> I read the Xcelium ref manual. The tool uses the first specified 'top' as the name for the elaborated tb. Since we have a 'multi-top' architecture where the tops are specified in different HJson files, it is not possible to order it such that the tb is first in that list. The `-snapshot` seems like the correct solution for this - it enables the name for the elaboration to be set correctly. It needs to be set like this: `-snapshot {tb}` in `xcelium.hjson`.

Yep, that would be the appropriate fix. Should I initiate a PR or will you do?

**Comment by sriyerg** [comment]
Already testing it now :)
