### ISSUE TITLE
Flash Controller: Interrupts only occur for the first operation

### ISSUE THREAD

**Issue by alistair23** [lowRISC/opentitan#4730]
When using interrupts with the flash controller the `INTR_STATE` bits don't get set correctly. From what I can tell the bits are correctly set for the first interrupt and then after the interrupts are disabled/cleared and re-enabled by software the bits don't get set again.

There seems to have been a change between 4429c362 and f083eb5a that causes the problem.

None of the status bits in `INTR_STATE` get set, even though `DONE` is correctly set in `OP_STATUS` and that an interrupt occurs. `INTR_TEST` can correctly set the bits and cause an interrupt though.

**Comment by alistair23** [comment]
This has been fixed, I'm not sure when though.

**Comment by tjaychen** [comment]
glad it's been fixed! i didnt even know there was an issue filed.
thanks!
