### ISSUE TITLE
Running software with SRAM scrambling

### ISSUE THREAD

**Issue by alistair23** [lowRISC/opentitan#4731]
A change between commit bec47c7bb and bacb3ad66 has caused Tock to fail to run. It seems like the very early memory init code fails to load from address `0x10000eb8`. I'm assuming this is related to SRAM scrambling, but I don't see anything new that needs to be done, any ideas?

**Comment by alistair23** [comment]
Issue is still there in the latest bitstream (https://github.com/lowRISC/opentitan/commit/1056d3d7967ae4d651e524bda8f6d8745ccf9235)

Full log is:

```
I00001 boot_rom.c:62] Boot ROM initialisation has completed, jump into flash!

panicked at 'fatal exception: LoadFault: 0x10000b5c', chips/earlgrey/src/chip.rs:248:13
        Kernel version release-1.6-679-g4b917ae34

---| Global debug writer not registered.
     Call `set_debug_writer_wrapper` in board initialization.

---| App Status |---
```

This seems to be timing related. If I step through with GDB it successfully boots.

**Comment by tjaychen** [comment]
just curious do you see the same issue in verilator?

**Comment by alistair23** [comment]
Things get even stranger.

If I comment out most of the Tock setup, I can get Tock to load. After that I can un-comment most of the code and that works. If I reset the board though then it doesn't work again. I need to go back to commenting everything out again.

If I set GDB breakpoints at special locations and then single step I can also get it to work.

**Comment by alistair23** [comment]
I haven't tried verilator

**Comment by towoe** [comment]
I think this is a problem with uninitialized values in RAM as the load operation will result in a parity error. The parity check is enabled by `prim_ram_1p_scr` for `prim_ram_1p_adv`.

My guess is that when single stepping with GDB the exception handling is ignored and as the program does not depend on the data it will run correctly afterwards.

**Comment by tjaychen** [comment]
hmmm... do we still have uninitialized values in RAM?
I thought Tock actually went through and initialized all of RAM? Or at
least the stack?

**Comment by towoe** [comment]
I think the stack is initialized but when I tested it the address which was accessed was not part of the stack.
In Tock I see a reference to clearing bss and data, but not sure if it is supposed to clear all. Boot rom clears the stack, so that should be okay.

**Comment by tjaychen** [comment]
ah, maybe we should give that a try? Could we add an all clear or some kind?
You are right that if if it is uninitialized the parity bits and the actual
data won't be aligned.

**Comment by towoe** [comment]
I created #5185 as this looked to me to be something that should have a more general solution.
But I guess a hot-fix would be to add an all clear.

**Comment by alistair23** [comment]
Thanks.

Any idea on what the long term solution will be? I would like to avoid having to zero all memory at boot as it will waste time, especially it hardware/ROM ends up doing it anyway.

**Comment by tjaychen** [comment]
so the main reason we can't immediately do this in HW is because the sram
is protected with per-boot scramble keys.
The scramble key itself is set up by software, so we have to wait at least
to a certain point in time to do this.
We can consider adding a wiping mechanism in hardware, but this would still
need to be triggered by software.

On a separate note, we should discuss if known zero-ing is really a good
idea given our scramble scheme... the srams use CTR scramble, and those do
not work well if a known is written to all addresses...

**Comment by alistair23** [comment]
Ah ok. If we have to zero/set it that's ok. I would just like to confirm that's the best option.

Interesting. This will be early boot code, so we won't have a RNG up and running yet. We could do some sequential values so they aren't all at least the same. Maybe a previous boot stage could write random-ish values to all of memory?

**Comment by tjaychen** [comment]
ah you ask great questions
So one of the first things boot rom has to do is setup RNG :).
We only need a tiny bit of RNG because our entropy is generated via
hardware through a DRBG.
Let me share a boot sequence diagram that shows this.  So the very start of
our code involves our ROM going through, setting up RNG, initiali sram
scramble, then setting up CRT.

**Comment by alistair23** [comment]
Even if the RNG is setup, Tock won't be setup to use it at it's early boot stage. Ideally we want to set the SRAM when we are zeoring BSS, which is Rust code, but very early Rust code. We don't have the kernel loop setup, or the `Chip` and drivers at this stage.

That's not to say it's impossible. We can still execute Rust code, so we could have a way to write to memory with data from the RNG, but it starts to get messy.

It would be great if the ROM could do this as part of setting up scrambling and the RNG.

**Comment by tjaychen** [comment]
ah we might have to loop in Garret and others on when is the best time to
do the zero-ing.
Having said that, i don't think it's a bad idea to put a small HW feature
to do this kind of init.
From what I gather, the only thing we care about is the sram has "some
value" right? It doesn't have to be 0 or anything specific.

So if there were something that software can trigger, and the memory would
just self initialize with entropy, i think that would work too.

**Comment by tjaychen** [comment]
I should also add, doing this with HW will be way faster than software.

**Comment by alistair23** [comment]
That would be great

**Comment by tjaychen** [comment]
would you mind filing an issue just so we don't forget?

**Comment by towoe** [comment]
I guess we can just add the zeroing of RAM in boot_rom as this is used by Tock right now and is only a placeholder for the final initialization routine.
All the security topics are covered with mask_rom and I think in the end Tock will only be executed after "everything" is setup.

**Comment by alistair23** [comment]
Done: https://github.com/lowRISC/opentitan/issues/5291

**Comment by towoe** [comment]
I created #5292 as a quick fix.

**Comment by tjaychen** [comment]
hey all, #5572 has been implemented.
So software should be able to trigger a memory initialization that is relatively fast.
The caveat to using this is that we first need to enable the entropy subsystem, there is some basic code do that as well.

**Comment by alistair23** [comment]
Is the expectation that Tock does that or that the stage before Tock does that?

**Comment by tjaychen** [comment]
i think ideally we want this to be done really early in the boot chain,
right after memory scrambling is enabled.
So I would say stage before Tock, but someone from the software side should
chime in.

**Comment by alistair23** [comment]
Agreed! It seems like https://github.com/lowRISC/opentitan/pull/5714 does this and now SRAM it initalised in the ROM https://github.com/lowRISC/opentitan/blob/4ca4a2f07bce8912d6adc10a56584319cea67491/sw/device/boot_rom/rom_crt.S#L99

Is that correct?

**Comment by tjaychen** [comment]
yes that's right.

**Comment by alistair23** [comment]
Great! I can now run Tock again, closing this issue.
