### ISSUE TITLE
[util] add verible to dockerfile

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#4746]
Dockerfile is great for creating a reproducible development environment. It is especially useful for developers who use a non-standard linux distribution and newcomers.

I think current Dockerfile version is out-of-date, as it doesn't include Verible that is required for building verilator.

**Comment by silvestrst** [comment]
I guess verible was a recent dependency and Dockerfile just was not updated, rather it being a deliberate decision not to include it?

**Comment by lenary** [comment]
Isn't verible in `apt-requirements.txt`/`python-requirements.txt` or is it installed from source?

You may have to rebuild the container to pick up changes in either of those two mentioned files.

**Comment by silvestrst** [comment]
```
$ export VERIBLE_VERSION=v0.0-808-g1e17daa

$ wget https://github.com/google/verible/releases/download/v${VERIBLE_VERSION}/verible-${VERIBLE_VERSION}-Ubuntu-18.04-bionic-x86_64.tar.gz
$ tar -xf verible-${VERIBLE_VERSION}-Ubuntu-18.04-bionic-x86_64.tar.gz

$ sudo mkdir -p /tools/verible/${VERIBLE_VERSION}/
$ sudo mv verible-${VERIBLE_VERSION}/* /tools/verible/${VERIBLE_VERSION}/
```

The installation for this tool is more like verilator rather than python dependencies.

**Comment by lenary** [comment]
Ok, you'll need to add a section like the one starting `FROM ubuntu:18.04 as verilator` (so, lines 33-47 of the Dockerfile), which runs and installs verible, and then later you'll need a `COPY --from=verilator /tools/verible verible` line in the group at line 61-62. Also add an `ARG VERIBLE_VERSION=` at the top, so it can be changed easily when @imphil inevitably updates the version used.

**Comment by imphil** [comment]
Since verible is a precompiled binary, you don't need a build container, you can directly do the download & copy in the final container.
