### ISSUE TITLE
[doc] Reference util/container/Dockerfile in the OT starter guide

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#4747]
Dockerfile is great for creating a reproducible development environment. It is especially useful for developers who use a non-standard linux distribution and newcomers.

At the moment there are no references to this container in:
https://docs.opentitan.org/doc/ug/install_instructions/

As a consequence it is probably not used as much as it would be otherwise.

**Comment by silvestrst** [comment]
@mundaym @luismarques  what do you guys think?

**Comment by imphil** [comment]
The current state of affairs is intentional, as we don't support (or test) the docker image. That can be changed, of course, however it will require a bit more effort.

**Comment by silvestrst** [comment]
> The current state of affairs is intentional, as we don't support (or test) the docker image. That can be changed, of course, however it will require a bit more effort.

Makes sense
