### ISSUE TITLE
[doc] OpenTitan Hugo theme seems to prevent HTML <br> tags being rendered correctly

### ISSUE THREAD

**Issue by sjalloq** [lowRISC/opentitan#4762]
I've noticed a strange artefact of what I think is the Hugo theme you're using.  If I try using \<br> tags inside a table cell, the first one is rendered correctly but subsequent ones are not.  I've replicated this with the latest version of Hugo and also tested it with a generic theme which works fine. So it's some funny interaction with your own theme.

I'm using the following syntax:

```
| Col0 | Col1 |
| - | - |
| Example | Line 1<br>Line 2<br>Line 3 |
```

and what I get with the OT theme is:

| Col0 | Col1 |
| - | - |
| Example | Line 1<br>Line 2Line 3 |

instead of the correct:

| Col0 | Col1 |
| - | - |
| Example | Line 1<br>Line 2<br>Line 3 |

**Comment by imphil** [comment]
HTML inside Markdown inside HTML is always a tricky combination. To help us reproduce this faster, could you link to a git branch somewhere with a modified documentation file that shows this behavior?

@gkelly @towoe Any idea?

**Comment by sjalloq** [comment]
Is this good enough?  Stick the table in any of your markdown files.  My CSS skills are poor so I didn't want to go down that rabbit hole but I've confirmed the generic syntax is fine for Hugo and other themes in general.  Sorry.

```console
$ git diff hw/_index.md
diff --git a/hw/_index.md b/hw/_index.md
index 6f5bab2..7f1c5b5 100644
--- a/hw/_index.md
+++ b/hw/_index.md
@@ -3,6 +3,10 @@ title: "Hardware Dashboard"
 aliases: [/doc/project/hw_dashboard/]
 ---
 
+| Col | Col1 |
+| - | - |
+| Line1<br>Line2<br>Line3| |
+
 This page serves as the landing spot for all hardware development within the OpenTitan project.
 
 We start off by providing links to the [results of various tool-flows](#results-of-toolflows) run on all of our [Comportable]({{< relref "doc/rm/comportability_specification" >}}) IPs.
```

**Comment by towoe** [comment]
Thanks for the example @sjalloq, I tested it and see the error locally.
I had a look at the Hugo config options, those seem okay. `html` templates look also okay, so it might be a CSS thing.

**Comment by towoe** [comment]
Inspect Element got me this:
https://github.com/lowRISC/opentitan/blob/7e131447da6d5f3044666a17974e15df44f0328b/site/docs/assets/scss/_markdown.scss#L109-L111

Now I need to find out why we have it there, I assume there is a reason.
We have quite a few tables, some auto generated, so this might be there to improve some of those.
