### ISSUE TITLE
[keymgr] HWIP technical specification

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#4769]
Creating this issue to capture some issues that I noticed while I was working on #4256:

- References to the error interrupt, which was recently removed, should be removed (searching for "error interrupt" and "interrupt" should show those references).
- The spec reads:
> Each state, when valid, supplies its secret material as the “key” input to a KMAC operation.

  However, IIUC this statement is correct only for transitions between operational states and not for `Reset -> Initialized`, `Initialized -> CreatorRootKey`, and `OwnerRootKey -> Disabled`.
- `RomExtSecurityDescriptor` should probably be a 128b value if the `SOFTWARE_BINDING` register will be used for it too.
- Regarding sideload keys (and clearing them): When keys are sideloaded to other peripherals, do they also store these keys internally or are these direct inputs to those peripherals? If they are stored, should we have a mechanism to delete those as well?
- In section "Errors, Interrupts and Alerts", there is "Invalid input" under "Software operation errors" but it doesn't have a corresponding bit in the `ERROR_CODE` register.
- In section "Invalid Operation", reference to `Init` operation should be removed ("Note that even though Init is not a legal operation in most states, ...")
- In section "Invalid Operation", the title of the second column of the table should probably just be "Operations" since the table lists both valid and invalid operations.
- "Advance" should be removed from the second column of the second row of the same table.
- `OwnerKey` should probably be replaced with `OwnerRootKey` (noticed two such instances).
- In section "Software Binding", the spec reads:
> This software binding exists for every stage of key manager except for OwnerKey.

But, the [Identities and Root Keys](https://docs.opentitan.org/doc/security/specs/identities_and_root_keys/) document reads:
> `OwnerRootKey = KM_DERIVE(OwnerIntermediateKey, SoftwareBindingValue)`

**Comment by tjaychen** [comment]
> Creating this issue to capture some issues that I noticed while I was working on #4256:
> 
> * References to the error interrupt, which was recently removed, should be removed (searching for "error interrupt" and "interrupt" should show those references).
> * The spec reads:
> 
> > Each state, when valid, supplies its secret material as the “key” input to a KMAC operation.
> 
> However, IIUC this statement is correct only for transitions between operational states and not for `Reset -> Initialized`, `Initialized -> CreatorRootKey`, and `OwnerRootKey -> Disabled`.

ah yes i can clarify this. 

> 
> * `RomExtSecurityDescriptor` should probably be a 128b value if the `SOFTWARE_BINDING` register will be used for it too.

RomExtSecurityDescriptor should be gone now.  Do you still see it? I was thinking we just use sw_binding only.

> * Regarding sideload keys (and clearing them): When keys are sideloaded to other peripherals, do they also store these keys internally or are these direct inputs to those peripherals? If they are stored, should we have a mechanism to delete those as well?

This is a good question. I think all the modules will store them in some form, so this should be part of the other module's (aes / kmac / hmac) self clearing routine between runs to ensure there is nothing residual left over.  I'm not completely sure they belong to keymgr DIF though.  What do you think? We should do an audit to make sure there are mechanisms in place for clear. 

> * In section "Errors, Interrupts and Alerts", there is "Invalid input" under "Software operation errors" but it doesn't have a corresponding bit in the `ERROR_CODE` register.

i think this one is `INVALID_KMAC_INPUT`.  Do you want me to just rename it as `INVALID_INPUT`?

> * In section "Invalid Operation", reference to `Init` operation should be removed ("Note that even though Init is not a legal operation in most states, ...")

thanks for the reminder. 

> * In section "Invalid Operation", the title of the second column of the table should probably just be "Operations" since the table lists both valid and invalid operations.
> * "Advance" should be removed from the second column of the second row of the same table.
> * `OwnerKey` should probably be replaced with `OwnerRootKey` (noticed two such instances).
> * In section "Software Binding", the spec reads:
> 
> > This software binding exists for every stage of key manager except for OwnerKey.
> 
> But, the [Identities and Root Keys](https://docs.opentitan.org/doc/security/specs/identities_and_root_keys/) document reads:
> 
> > `OwnerRootKey = KM_DERIVE(OwnerIntermediateKey, SoftwareBindingValue)`

yes thanks for catching these, i will update. The implementation does not preclude software binding for ownerkey. 
#

**Comment by tjaychen** [comment]
@alphan , i believe i've addressed all these issues with the latest spec update.
Please have a look.

**Comment by alphan** [comment]
Thanks @tjaychen, LGTM. Just some comments:

>> Regarding sideload keys (and clearing them): When keys are sideloaded to other peripherals, do they also store these keys internally or are these direct inputs to those peripherals? If they are stored, should we have a mechanism to delete those as well?
>
>This is a good question. I think all the modules will store them in some form, so this should be part of the other module's (aes / kmac / hmac) self clearing routine between runs to ensure there is nothing residual left over. I'm not completely sure they belong to keymgr DIF though. What do you think? We should do an audit to make sure there are mechanisms in place for clear.

I also think that they don't belong to keymgr DIF but we should probably do an audit and I should definitely mention this in the comments of the DIF (#4256).

----

>>In section "Errors, Interrupts and Alerts", there is "Invalid input" under "Software operation errors" but it doesn't have a corresponding bit in the ERROR_CODE register.
>
>i think this one is INVALID_KMAC_INPUT. Do you want me to just rename it as INVALID_INPUT?

I thought this is directly related to SW inputs because the doc says:
> Invalid software input was supplied (for example a greater key version than allowed in MAX_OWNER_KEY_VER.

whereas `INVALID_KMAC_INPUT`'s description is "Invalid data issued to kmac interface".

----

There seems to be an issue with the table:
![image](https://user-images.githubusercontent.com/57949550/104757998-bfeb2100-572b-11eb-9622-8f2ae8da38a6.png)

**Comment by alphan** [comment]
`MAX_*_KEY_VER_REGWEN.EN` fields have the following in the description column:
> All values except for 2 are interpreted as configuration disable.

but these are single-bit fields.

**Comment by tjaychen** [comment]
yeah this needs to be updated to multi-bit regwen, which is kind of a
project wide thing.
the comments got a bit ahead of the implementation.

**Comment by alphan** [comment]
Sounds good, thanks @tjaychen! The DIF will need to be updated when that change lands but I don't think we can miss it because it won't build :)

**Comment by tjaychen** [comment]
i believe all the comments here have been addressed. let me know if you disagree!
