### ISSUE TITLE
[otbn] Implement sparse state encoding in (controller) FSMs

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#4793]
Use a sparse FSM state encoding in the OTBN (controller) FSMs. See also https://github.com/lowRISC/opentitan/blob/master/hw/ip/prim/util/sparse-fsm-encode.py.

> estimate 4

**Comment by rswarbrick** [comment]
Done with https://github.com/lowRISC/opentitan/pull/9903.
