### ISSUE TITLE
[otp] read digest with DAI interface

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#4799]
Hi Michael,

Could you take a look at this question reading secret digest reading from DAI interface.

Firstly I would like to confirm: reading a digest from DAI interface (using `direct_access_cmd` -> rd command and `direct_access_address` -> the digest address) is legal. I believe it is legal because I did not see any status error when I read digests from DAI.

If the sequence is confirmed to be legal, then when reading secret partitions' digests, the CSR (for example: `secret0_digest_0`) register readout is different from the DAI readout result. From the waveform, we are trying to read address ('h7c3), normalized to decimal `1984` which is `Secret2DigestOffset`. Looks like the DAI readout added a descrambling step. (in the screenshot, where the second inserted bookmark, DAI interface returns data `0x59731f0b`, but partition_digest is all 0, and digest CSR readout is all 0s).

I think it would be good to unify both returns to avoid confusion. Do you think that is something the OTP_init script fix is enough, say by initializing the digest to descrambling as all 0s? Or severe enough to be a corner case that needs to be aligned and fixed in RTL?

![image](https://user-images.githubusercontent.com/11466553/104258022-941e2180-5433-11eb-8e33-5312fa143773.png)

Thanks,
Cindy

**Comment by msfschaffner** [comment]
Hey @cindychip! 
Yes, reading the digests through the DAI as you explained is legal.
Did you perform a reset after programming the digest? 
The digest value in the CSRs is a buffered value and first needs to be re-sensed before becoming visible in the CSRs...

**Comment by msfschaffner** [comment]
Ah sorry I think misunderstood you. Are you saying that the DAI erroneously adds a descrambling step and hence does not return 0, although it should actually return 0 in your test case?

**Comment by cindychip** [comment]
Yeah, i did add a reset, forget to mention that this case happened when we did not trigger a digest. So CSR is supposed to readout as all 0s.
The discrepancy comes in when we initialize OTP. The digest value in OTP is backdoor to all 0s. So readout adding descrambling is non-zero.
I can align it with init script, but would like to double check there is no security or any other concerns here.

**Comment by cindychip** [comment]
Also, I have a follow up question regarding read digest in DAI interface.
If a partition is locked, can we still read digest using DAI interface? (I believe right now RTL give an access error if read digest will it is not locked)

**Comment by msfschaffner** [comment]
OK I think I know why you ran into this. 
The DAI always descrambled the full partition - which is wrong. See fix in linked PR.

The digests should always be readable through the DAI, since they are not secret (i.e., they are also exposed through the CSRs).
Let me check...

**Comment by msfschaffner** [comment]
Turns that there was a similar issue when reading HW digests of locked partitions.
I.e. access to the entire partition got locked down.
I addressed this in the same PR, such that digests can be read through the DAI even when the partitions are locked.

**Comment by cindychip** [comment]
Thanks Michael for the quick fix. Sorry I made the report sounds so much complicated than it should be. i really need to work on how to report issues clearly..

**Comment by msfschaffner** [comment]
You're reporting is fine, @cindychip. 
It just turns out that the fix was easy - but it could have been a more complicated bug ;).
