### ISSUE TITLE
[otbn] Should we simplify the BN.LID / BN.SID instructions?

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#4805]
When discussing a corner of their spec, [Felix mentioned](https://github.com/lowRISC/opentitan/issues/3587#issuecomment-758168987) that we could simplify things further without breaking any existing software. Quoting from his message:

> Looking at this purely from the SW perspective we never use the full capabilities of the instructions.
> 
> Currently we only have two variants how we use them:
> 
>  1. `bn.lid x[0..31], <imm>(x0) `for loading a full WLEN word into a WREG from DMEM with hard coded address
>  2. `bn.lid x[0..31], 0(x[1..31])` for using a narrow reg as pointer into dmem
> 
> 
> plus:
> 
>  * `bn.sid `we only use in the 2nd variant currently.
>  * the 1st variant for `bn.lid` is only used in the transition phase of the code in the code snippets, we currently use it to load constants from IMEM via a DMEM detour. These constant will eventually end up in DMEM.
> 
> 
> So from my perspective any of the following would also be fine:
> 
>  * completely get rid of the offset
>  * requiring either the offset being zero or the address being zero (x0).
>  * allowing only predefined values for the offset (this might be helpful, if we added say a DROM or partition DMEM in any other way)

**Comment by rswarbrick** [comment]
@GregAC: What do you think from the RTL implementation point of view? Would ditching the offset make much difference?

**Comment by rswarbrick** [comment]
Looking at this again after filing #4807: if we ditched the offset then we would just need something like a 10-bit counter for the base address increment and we could freely decide whether to mask out the top of the address.

**Comment by GregAC** [comment]
Is isolation the only hardware advantage you get from dropping the offset is reducing a bit of muxing (one less immediate type to mux out to the ALU). There's also a timing advantage, earlier address due to lack of offset computation but I don't think we've got any timing issues currently.

**Comment by rswarbrick** [comment]
We've decided not to do this for now. We might drop the offset field entirely in the future (mainly to recover the encoding space!), but there's no point in tracking this at the moment.
