### ISSUE TITLE
[otbn] Operate on just the lower bits of memory address in BN.LID / BN.SID

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#4807]
At the moment, the BN.LID and BN.SID instructions use a 32-bit base address. For example, if `x2 = 0xffffffe0`, then
```
    bn.lid x0, 32(x2)
```
loads from address `0xffffffe0 + 32 = 0`. That addition is "free", because it can use the existing adder in the ALU. What's not free is the increment needed if we do
```
    bn.lid x0, 32(x2++)
```
To get that right, we currently need an extra 27-bit adder (less than 32 because the offset and base address are 5-bit aligned).

We could simplify things by operating only on the bottom 16 bits (say). Then the base address would be computed as `x2 & 0xffff` and the offset calculation and increment would be done modulo 2^16. Finally, we'd write back the value as something like `{x2[31:16], x2[15:0] + 32}`.

This just needs an 11-bit adder (16 minus 5) for incrementing things, which seems like a win. Of course, it might mean more muxing in the ALU (to do a 16-bit offset calculation).

Is this an improvement? (@GregAC: can you comment on the HW impact?)

This was triggered by #4727, plus [Philipp's comment](https://github.com/lowRISC/opentitan/issues/3587#issuecomment-756871416) on the more general increment question. It might become moot if either we restrict things so that base addresses must be valid Dmem addresses or we cut down the instruction, as discussed in #4805.

**Comment by GregAC** [comment]
We will get some area reduction for a smaller incrementer, but it's only an incrementer you need not a full adder, which is smaller anyway. Plus as you point out we end up with extra logic on the address + offset computation. In the context of OTBN I think it's a negligible area change so better to decide based upon what is best for SW and security. SW wise I think operate everything on full 32-bits and then fault if DMem address out of range makes the most sense.

**Comment by GregAC** [comment]
If we did drop the offset then we'd pass the bottom N bits of the register file read straight out as an address, in which case by making the increment operate on N bits only we will overall save area.

So I'd say we need to both this and #4805 or neither (full 32-bit operation everywhere just fault if we end up attempting to access an out of range address)

**Comment by rswarbrick** [comment]
Let's keep the existing behaviour: the 32-bit incrementer is going to be tiny compared to the rest of OTBN, and the existing semantics are probably the most easy to understand for a programmer.
