### ISSUE TITLE
[otbn] Should we error out when incrementing "past 31" for WDR in BN.LID / BN.SID

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#4808]
When discussing the behaviour of increments, Philipp [suggested](https://github.com/lowRISC/opentitan/issues/3587#issuecomment-756871416) that we could raise an error if the WDR index was incremented past 31, since it probably shows a bug in the code.

The current spec allows code like this:
```
    addi x2, x0, 16
    addi x3, x0, 24
    addi x4, x0, 0x100
    loopi 8, 3
      bn.lid x2++, 0(x4)
      bn.lid x3++, 32(x4)
      addi x4, x4, 64
```
to load up "striped" data without too much pointer manipulation. The last iteration of that loop will wrap `x3` around from `0x1f` to zero. This wouldn't be allowed with the proposed change.

Should we raise an error in this case?

> estimate 8
> remaining 2021-03-08 4
> remaining 2021-03-22 1

Also need to change the RIG to not produce LID/SID code which uses register values larger than 31.

**Comment by GregAC** [comment]
Presumably we want whatever behaviour we choose to be consistent with `BN.MOVR` too?

I was wondering if we should raise an error if the GPR doesn't contain a valid WDR Index (i.e. it's a number greater than 31). Currently we just feed the bottom 5 bits as a register read address and ignore the rest. While the wrapping behaviour could be useful an out of range index seems more like a straight programming error in all cases.

**Comment by rswarbrick** [comment]
Yes, definitely about `BN.MOVR`.

For the top bits of the WDR index... maybe? I'm not keen, but only because it means the RIG won't generate quite such "random" programs. Probably not a strong argument! Since we have an `ANDI` instruction, I would think that any code that genuinely wants to grab the bottom bits from something could use that to only take a 1-cycle penalty.

**Comment by rswarbrick** [comment]
@cdgori [commented](https://github.com/lowRISC/opentitan/issues/3587#issuecomment-759708574) on the parent issue, and I'm copying the comment here to keep everything together:

> 1. Seems like the re-alignment of zero-reg will make this wrapping behavior more likely/common? So allowing the wrap around is necessary/useful. I had originally thought we could just narrow the functionality to disallow this wrap but seems like that is not going to be the case.
> 1. I do think having any bits 31..5 set in the WDR reference is very bad and we should detect it. I'm also not convinced that alert is sufficient here, maybe some more drastic action is needed, as we would have for detected glitches/faults. (I am not generally sympathetic to "programmer error" here as this code should be very thoroughly tested, so things that should not occur should be flagged as such, because they are often indicators of / correlated to attack scenarios.)

**Comment by rswarbrick** [comment]
Probably part (2) is more relevant to #4806 (I'll update that in a sec).

**Comment by rswarbrick** [comment]
The plan:
1. Raise an error if any of the top bits are set.
2. Increment without wrap-around. That way, you can increment from `w31` to "32". That's fine, but using the register again will cause an error.

**Comment by rswarbrick** [comment]
RIG changes required are tracked in #5731.
