### ISSUE TITLE
[keymgr] kmac_key valid high forever after the first advance operation

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#4817]
@tjaychen 
I'm adding checking for kmac_key valid and find kmac_key valid is high forever after the first advance operation
I think it should only remain high when it's a kmac sideload operation.
![Screen Shot 2021-01-12 at 5 49 08 PM](https://user-images.githubusercontent.com/49293026/104395866-82ee1700-54fe-11eb-8c95-bb0f494e910a.png)

/edascratch/weicai-opentitan/ot/rerun_pr_4802/keymgr-sim-vcs/0.keymgr_smoke/out

**Comment by tjaychen** [comment]
good catch.
i think i introduced this issue when i changed the definition of op_accept.
I just pushed a PR.

**Comment by weicaiyang** [comment]
fixed via #4818
