### ISSUE TITLE
Interrupt Service Routine 

### ISSUE THREAD

**Issue by sajjadahmed677** [lowRISC/opentitan#4819]
I need guidance regarding ISR. we have multiple devices in an SoC, and only a single wire indicates the core about external interrupts. so how do we get to know that which device interrupted the core and how we will deal that. for example i wanted to read a value from a GPIO so, what will be the flow of reading the value from GPIO in terms of ISR.

**Comment by tjaychen** [comment]
The ISR will need to go through the `plic` to figure out which module sent the interrupt, and then from there jump to an appropriate routine.

Please see the interface code written for the plic [here](https://github.com/lowRISC/opentitan/blob/master/sw/device/lib/dif/dif_plic.h)
