### ISSUE TITLE
Question - any document related to VCS simulation

### ISSUE THREAD

**Issue by aloke-tortuga** [lowRISC/opentitan#4823]
I am trying to simulate top_earlgrey with VCS. I found the Verilator simulation document:
https://github.com/lowRISC/opentitan/blob/master/doc/ug/getting_started_verilator.md

Is there any such document available for VCS simulation for the top level? I have been able to compile the design, but while simulating, I do not know which memory files to pass or if there is a top level testbench that I can use.

**Comment by sriyerg** [comment]
DV simulations are run with `dvsim`. Please try the following command:
```console
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i all 
```

This will run the full regression. To find individual tests to run, try passing `--list tests`.

**Comment by aloke-tortuga** [comment]
Thanks, Sri, for suggesting the way to run. I am able to make some progress, but need to adjust my env setup. I will take some more time and inform soon.

**Comment by aloke-tortuga** [comment]
Sri - many thanks for your help and pointers to the documentation. I was able to run the tests and found the 'build.log' and 'run.log' files under the scratch directory. This gave a detailed idea about how the VCS compilation/simulation is happening. We will be able to run some AES specific tests for security-centric applications. Best.
