### ISSUE TITLE
[otp_ctrl] DAI interface write sw partitions digest error

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#4825]
Hi Michael,

Here is a corner case when writing SW partitions digests via DAI interface.
For example to write OwnerSwCfg Partition's digest, the DAI address is 1528, hex format is `h5F8`. Because the digest has a granularity of 64 bits. I think issuing any address between `h5F8` to `h5FF` for DAI interface should work. The DAI interface works fine when I input `direct_access_address` between `h5F8` to `h5FB`. But it has error if I input address between `h5FC` to `h5FF`.

Sequence is:
1. Write digest through DAI interface with address `h5fc` with wdata_0 `h5985_54ea` and wdata_1 with data `he139_6c70`
2. Read out digest through DAI interface with address `h5fc`, get rdata_0 `h5985_54ea` and rdata_1 `0`.
3. Read out digest through DAI interface with address `h5f8`, get rdata_0 `0` and rdata_1 `h5985_54ea`.

So from the observation. The digest value writes to DAI address `h5FC`(wdata0)  instead of `h5F8`(wdata0). 

Looking at the waveform, when writing data from DAI interface to OTP, I think the `otp_addr_o` has some issue. For digest with 64 bits granularity, the output address from DAI to OTP is `2fe`. This treats the digest address as normal secret partition address. But I think RTL should treat it as secret and the OTP address should be `2fa`.

![image](https://user-images.githubusercontent.com/11466553/104516417-1f6cf380-55a9-11eb-84bc-bfa4c2cce096.png)

Thanks,
Cindy

**Comment by msfschaffner** [comment]
Thanks @cindychip. Yeah this was not entirely correct. PR with the fix is up.
