### ISSUE TITLE
[keymgr] KMAC key isn't random value for invalid input

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#4826]
@tjaychen 
I found one case that KMAC key isn't random value for invalid input in StOwnerIntKey.
These 2 error cases are very similar, both are operation errors, but they use different kmac key.
1. In StInit, gen-operation uses random value for KMAC
2. In StOwnerIntKey, gen-operation with invalid input uses internal key for KMAC
Since we don't output result for above 2 cases, it may not be an actual problem. Let me know if you want to make them more consistent.

![Screen Shot 2021-01-13 at 2 59 48 PM](https://user-images.githubusercontent.com/49293026/104520636-4bd83e00-55b0-11eb-9f52-d628a86a358b.png)
/edascratch/weicai-opentitan/ot/km_sl_scb/keymgr-sim-vcs/failed/1.keymgr_invalid_kmac_input

**Comment by tjaychen** [comment]
Ah ... yes...
this is ..somewhat expected.

In StInit, gen-operation is an invalid operation, so immediately we know to
use an invalid key.
In StOwnerIntKey, gen-operation is a valid operation, and kmac interface
checks that data is invalid.  So you should see the kmac data being random
in this case.

The fact that invalid input is seen is then fed back as an error later.
How are you modeling this as part of scoreboard? Because there are cases
where the error happen at different points in time.

**Comment by weicaiyang** [comment]
> Ah ... yes... this is ..somewhat expected. In StInit, gen-operation is an invalid operation, so immediately we know to use an invalid key. In StOwnerIntKey, gen-operation is a valid operation, and kmac interface checks that data is invalid. So you should see the kmac data being random in this case. The fact that invalid input is seen is then fed back as an error later. 

> How are you modeling this as part of scoreboard? Because there are cases where the error happen at different points in time.

In scb, I simply expect kmac key is random if there is any input error or it's advancing to disabled state.
I also check kmac data are random too. Since we can change kmac data to random, why not make kmac key random too? And the `key_version_vld` is dropped before we send out the key.
This is very minor. I'm fine with current design behavior too.

**Comment by tjaychen** [comment]
let me think about this a bit.

Generally speaking, the way this is currently structured is that invalid_op
leads to random key
Invalid data, invalid command etc leads to random data.

It wouldn't be difficult for invalid data to actually lead to random key
also, but then it also raises the question of the other errors (which may
happen at different times) should cause key to become invalid also.

Does that make sense?

**Comment by weicaiyang** [comment]
> let me think about this a bit. Generally speaking, the way this is currently structured is that invalid_op leads to random key Invalid data, invalid command etc leads to random data. It wouldn't be difficult for invalid data to actually lead to random key also, but then it also raises the question of the other errors (which may happen at different times) should cause key to become invalid also. Does that make sense?

I'm thinking about the timing of each error.
Invalid op/input/command occurs and are checked before sending data/key to KMAC. Looks like these should send random data and key to KMAC
invalid output is checked after receiving digest data from KMAC. This leads to random data on SW output or sideload key.

keymgr_en off happens anytime, so it wipes secret anytime. If it's in the middle of operation, wipe kmac data and key with random value.

Is this right?

**Comment by tjaychen** [comment]
So invalid command can technically happen at any time..it's more or less an
FI check.
And yes right now i'm basically tying valid key to valid op, and valid data
to valid data (which is why invalid_input has correct key but random data).

and yeah that's right on keymgr_en.  It can happen any time.

**Comment by weicaiyang** [comment]
> So invalid command can technically happen at any time..it's more or less an FI check. And yes right now i'm basically tying valid key to valid op, and valid data to valid data (which is why invalid_input has correct key but random data). and yeah that's right on keymgr_en. It can happen any time.

Thanks @tjaychen. Will align this behavior in scb.
