### ISSUE TITLE
[otp_ctrl] DAI and KDI interface both uses scrambling issue

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#4852]
Hi Michael,

I wanted to ask can DAI and KDI issue request in the same time? If that is okay, I think there is an issue.

Seq:
1. Issue `otbn_otp_key_i`
2. While calculating the key in DAI interface, issue `cal_digest` (in this sequence, is for hw_cfg partition)
3. Then I can see a mismatch in second 64 bits otbn output key

Issue:
In the sequence above, the scrambling module did the following thing:
Step 1. Calculate first 64 bits otbn key with key input: 1) key_seed_from_OTP 2).EDN 3).Final_constant
Step 2. Calculate second 64 bits otbn key with key input 1). key_seed_from_OTP
Step 3. Then DAI interface digest calculate request came, and scrambling module jumped to calculate digest
Step 4. When digest finished, it went back to do second key with input EDN, however, the input 64 bits data is not correct.
 --> The input 64 bits are supposed to be the result from step 2, but it uses the output from step 3 

I could not capture a good waveform to really show the issue (but still paste one here in case...). To see the entire waves, you can open a verdi session here:
/edascratch/chencindy-opentitan/scratch/otp_sequence_key_req/otp_ctrl-sim-vcs/0.otp_ctrl_rand_key_rsp/out
verdi -ssf waves.fsdb

![image](https://user-images.githubusercontent.com/11466553/104765299-857a8780-571d-11eb-8a81-baa768756730.png)

Thanks,
Cindy

**Comment by msfschaffner** [comment]
Hey @cindychip,

I think I understand what you're saying.
Yeah this is possible and expected to happen.
Let me take a look...

**Comment by msfschaffner** [comment]
Looks like I forgot to hold the mutex on the scrambling datapath when requesting EDN data in the KDI. Fix is coming...
