### ISSUE TITLE
[otbn] Define canonical disassembling for instructions

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#4871]
Check and ensure that our docs give a unambiguous path from an instruction (bits) to a "line of assembly". Covers questions like "if a pseudo-op exist, should it always be preferred?"

**Comment by rswarbrick** [comment]
We run objdump with `numeric,no-aliases` and will never generate pseudos. Doing anything else would probably be rather difficult and what we've got is at least canonical :-) Closing this as I can't imagine us ever getting around to working on it!
