### ISSUE TITLE
 tlgen.py doesn't seem to work standalone any more: should it be deleted?

### ISSUE THREAD

**Issue by jackiezhangcn** [lowRISC/opentitan#4892]
If the user tried to run the script to generate a xbar in standalone mode, it would failed due to some variables NOT defined

def validate_hjson(obj):
    if "type" not in obj:
        obj["type"] = "xbar"
    if "name" not in obj:
        log.error("Component has no name. Aborting.")
        return None, 1

    component = obj["name"]
    error = check_keys(obj, root, component)

    if error > 0:
        log.error("{} has top level error. Aborting".format(component))
        return None, error
    return obj, 0

In the above function, root variable is NOT defined

**Comment by tjaychen** [comment]
this is probably something we need to look at and address.
Because I imagine there will be cases in the future where we want to use
this outside of topgen.

Thank you for the issue.

**Comment by eunchan** [comment]
Hjson should be complete to run tlgen.py The current ones in the repo should be amended by topgen. If anyone wants to run tlgen, they need to prepare a separate, complete hjson.

**Comment by eunchan** [comment]
Let me close this issue.
