### ISSUE TITLE
[dv] Rework (aes_)shadow_reg_errors

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#4895]
With #4781 we have reworked how the shadow register errors (update and storage errors) translate into alerts and the implications they have on the AES module. Unfortunately, I wasn't careful enough and didn't realize that the `aes_shadow_reg_errors` test is neither run in CI nor in the default config I used to verify the changes. As a result, the design and DV are now out of sync. I tried to fix it myself but since I am not familiar enough with UVM and the CSR tests, I need some help.

In particular, the main changes I did and that we would need to adjust the test infrastructure for are:
1. Update and storage error no longer necessarily have an own alert called `"csr_name"_storage/update_err`. In the case of AES, we have two alert signals `fatal` and `recoverable` that can both collect multiple alert conditions. What would probably be needed here is a tag in the hjson description saying which alerts the storage and update errors are connected to (Like the tag specifying the path of the shadow register in the design).
2. Fatal alerts (e.g. produced by a storage error) should lock up the peripheral. In AES it is now no longer possible to get out of such a condition except by a reset. Writes to the shadow reg are ignored after a storage error is detected and the alert remains asserted - even if the backdoor interface is used again to put the two copies back in sync. This behavior is not inherent to the shadow register but to AES. The test framework might need to adapt on a per case basis.
3. In AES, the recoverable alert (produced by an update error) remains asserted until the next write to the shadow register. (This could also be changed in the RTL.)
4. In AES, we now have a separate status bit for both fatal and recoverable alerts in the status register. Previously, we just had one for storage errors/fatal alert. As a result, the test now sometimes stops because it reads an unexpected value in the status register.

I am sorry for not realizing this earlier and would be happy if @cindychip and/or @weicaiyang could have a look. Also pinging @rasmus-madsen and @sriyerg for visibility.

**Comment by vogelpi** [comment]
Thanks @cindychip ! Re 3.: I will now do a PR make the update error being asserted for just one cycle as this is required by the new alert guidance. However, the corresponding status register bit will remain high until the next write of the control register. I will ping you in the PR to keep you in the loop.

**Comment by cindychip** [comment]
Sorry I missed the PR: https://github.com/lowRISC/opentitan/pull/4909. I will make an update in shadow_reg test to support recoverable_error assert one clock cycle and fatal_error keeps firing until reset by the end of the week.

**Comment by cindychip** [comment]
One remaining item on DV: check fatal error continuously triggered without enabling scb. (Make sure this can be also used in keymgr)

**Comment by cindychip** [comment]
Hi @vogelpi! Just want to follow up on this:

> However, the corresponding status register bit will remain high until the next write of the control register. I will ping you in the PR to keep you in the loop.
Have you implemented this already? I just want to double check to make sure I did not miss your PR.

Thanks,
Cindy

**Comment by vogelpi** [comment]
Hey @cindychip ,
the corresponding PR (#4909) got merged quite a while ago. Sorry, I didn't ping you in here, but just in the PR.

The behavior of the two alerts is as described initially:
- `recov` fires for just one clock cycle. The corresponding status bit in the STATUS register remains high until the next write to the shadow register occurs. This second part (keep status big asserted until next write) probably doesn't need to be tested. It's not part of the shadow register specification but more specific to how the shadow register is used inside AES. I can imagine some shadow registers will not have status bits at all.
- `fatal` remains asserted until reset. There is also a status bit in the STATUS register that remains asserted until reset. But again, that's quite specific to AES probably.

So, I think from the AES side everything looks good. Thanks a lot for the work you put into this Cindy!

Or is there anything else you wanted to know from me?

**Comment by cindychip** [comment]
Thanks @vogelpi for getting back to me! I think the AES sides should be good as well. I am just reviewing this issue and see if i missed anything. The status register checking is covered in the shadow_reg_err sequence. 
I will close this PR since all the updates are covered in the `shadow_reg_errors` sequence.
Please feel free to open it again if you find anything missing :)

Thanks,
Cindy
