### ISSUE TITLE
[keymgr] HW invalid input for advance operation

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#4899]
@tjaychen 
From recent spec update, we will update result for operation with invalid input.
But for advance operation, we just skip updating internal key and it moves to next state with old internal key.
![Screen Shot 2021-01-20 at 10 16 00 AM](https://user-images.githubusercontent.com/49293026/105218257-c56cb080-5b09-11eb-811f-eeea83247045.png)

```
      KeyUpdateKmac: begin
        data_valid_o = data_update & ~fault_err & ~op_err;
        key_state_d = key_update & ~fault_err & ~op_err ? kmac_data_i : key_state_q;
      end
```

I feel if we don't want to corrupt the internal key, perhaps don't move the state, otherwise, keymgr requires a reset to get back to normal. Or we can update internal key with random data and move state to disabled, which is clear that we have to do a reset to recover. WDYT?

wave: /edascratch/weicai-opentitan/ot/km_out_chk/keymgr-sim-vcs/0.keymgr_hwsw_invalid_input/out

**Comment by tjaychen** [comment]
yes i think you're right. We probably should not the key or the state. I'll fix this.

**Comment by weicaiyang** [comment]
@tjaychen I have another question regarding the fault error.

In RTL, any of these 4 fault errors leads to ErrInvalidCmd. And kmac invalid data (like kmac digest share0 is all 0s or 1s) leads both ErrInvalidCmd and ErrInvalidOut. Not sure if it make sense to have one error trigger one error bit. For example, Invalid command or Invalid fsm state leads to ErrInvalidCmd. Invalid kmac operation or Invalid output leads to ErrInvalidOut
```
  assign error_o[ErrInvalidCmd] = op_ack & fault_err;
  assign error_o[ErrInvalidOut] = op_ack & ~kmac_out_valid;
```

> Invalid command - A non-one-hot command was issued from the key manager controller to the KMAC data interface. This is not possible by software and indicates a hardware fault. This error can also happen if the KMCA data fsm gets into an invalid state.
> Invalid fsm state - The fsm reached an invalid state. This is not possible by software and indicates a hardware fault.
> Invalid kmac operation - The KMAC module itself reported an error. This is not possible given the set of KMAC data interface inputs.
> Invalid output - The data return from KMAC is all 0’s or all 1’s. This is not possible given the set of KMAC data interface inputs.

**Comment by tjaychen** [comment]
yeah i think invalid command is actually kind of a bad name. It's really meant to kmac_fault (ie, things that should never really happen) Would it be  better if i changed to that? I was going to change it last time, but decided not to in the end because i didn't cause a whole cascade of new error names.

**Comment by weicaiyang** [comment]
> yeah i think invalid command is actually kind of a bad name. It's really meant to kmac_fault (ie, things that should never really happen) Would it be better if i changed to that? I was going to change it last time, but decided not to in the end because i didn't cause a whole cascade of new error names.

Agree, that name doesn't reflect its behavior. But 4 invalid behaviors lead to this error bit. Will it be an issue when it's triggered, we don't know what exact error occurs. Not sure if we need to break it down to provide more info for post silicon test.

**Comment by tjaychen** [comment]
i think it's okay.  Because all 4 of these represent essentially fault
attacks (let me double check that is the case).

**Comment by weicaiyang** [comment]
> i think it's okay. Because all 4 of these represent essentially fault attacks (let me double check that is the case).

these 2 errors are driven kmac. not sure if it's due to fault attach too.
> Invalid kmac operation - The KMAC module itself reported an error. This is not possible given the set of KMAC data interface inputs.
> Invalid output - The data return from KMAC is all 0’s or all 1’s. This is not possible given the set of KMAC data interface inputs.

**Comment by tjaychen** [comment]
let me check with Eunchan.
I thought they were because we are never expecting an all 0's all 1's
return, so to see one implies an attack.  But KMAC error itself might
indeed be something separate.

**Comment by weicaiyang** [comment]
@tjaychen any update on this. Thanks
