### ISSUE TITLE
Fix spitest.py due to PyFtdi API change

### ISSUE THREAD

**Issue by jackieke724** [lowRISC/opentitan#4907]
According to the [PyFtdi API change](https://eblot.github.io/pyftdi/index.html#major-changes), the line shown below would cause `AttributeError: 'bytearray' object has no attribute 'tobytes'`. 
https://github.com/lowRISC/opentitan/blob/275dd04aca5fb00b3fff1e10bef849af547e2a0d/util/simplespi/spitest.py#L140

I simply removed `.tobytes()` and it seemed to be working.

**Comment by jackieke724** [comment]
Another question is when I ran the flippy test, the output was always selecting JTAG. Is that expected or could the GPIO pin assignment have been changed?

**Comment by imphil** [comment]
@jackieke724 Thanks for debugging this. Would you mind doing a pull request with your changes? If you haven't done a PR before you can find documentation at https://docs.opentitan.org/doc/ug/github_notes/.

**Comment by jackieke724** [comment]
@imphil , thanks for the pointer. I have opened a pull request.
Please ignore the `9db9f9a` commit, as that includes changes which port opentitan to the Genesys2 FPGA board.
