### ISSUE TITLE
[dv] Create another layer of class lib on top of CIP for supporting EDN interface

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#4929]
Currently, the EDN interface agent is added to CIP lib. EDN is required only for a small number of IPs. It is not listed as a part of the Comportability spec, and hence it should not be a part of CIP base class lib. Perhaps we could create another layer of class lib on top of CIP class lib instead.

**Comment by sriyerg** [comment]
@weicaiyang

**Comment by weicaiyang** [comment]
not sure if it's worth creating another layer of classes just for EDN.
All security IPs have alert interfaces. In my impression, more than half of these IPs have EDN interfaces. I feel perhaps we can consider to add EDN interface in our design comportability spec. @tjaychen @eunchan WDYT?

**Comment by tjaychen** [comment]
yeah i think that's a reasonable idea.
I do expect that most of our security modules in the end will need an edn
interface, and others that are not necessarily security focused (otp, lc,
flash) may also end up needing it.

**Comment by sriyerg** [comment]
Closing this due to infeasibility.
