### ISSUE TITLE
[hw, AES] OUTPUT_VALID 1 on reset

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#4955]
It seems that `OUTPUT_VALID` is set on reset instead of `INPUT_READY` (status register), discovered this when working on `dif_aes_smoketest`. I think maybe in the latest change RTL signals have accidentally swapped.

**Comment by vogelpi** [comment]
Hey @silvestrst ,
thanks for pinging me. I just checked the RTL and simulation. It is still the `INPUT_READY` bit which is high upon reset and not the `OUTPUT_VALID` bit as you suggested. The HW/RTL is correct. What changed in the meantime is that we've inserted another bit to the register which caused some of the bits to shift up: `INPUT_READY` is now Bit 4 (previously 3). Please also check the documentation: https://docs.opentitan.org/hw/ip/aes/doc/

You'll need to update your DIF PR accordingly.

**Comment by silvestrst** [comment]
Thanks @vogelpi , false alarm - rookie mistake, forgot to rebuild verilator after RTL changes.
