### ISSUE TITLE
[sw/sca] SCA remaining device-side tasks

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#4971]
Remaining tasks after #4972:

- [ ] Most of the return values are ignored in `sca.c`, `simple_serial.c`, and `aes_serial.c` to maximize the capture rate. Evaluate their effects and check as much as possible without reducing capture rate.
- [ ] Setting `ack = False` in the call to `cw.capture_trace` also removes acks from key set function. We should probably handle it separately. so that it works for both single and batch encryption operations.
- [ ] Send `ack` from `k` and `s` since these should not affect capture rate and can help catch setup issues earlier.
- [ ] Consider renaming `aes_serial.c` to `aes.c`.
- [x] Consider moving everything in `sw/device/sca/aes_serial` one level up and removing this folder. May want to move libraries to a new folder like `sw/device/sca/lib`. (#5239)
- [x] Start using AES DIF library.
- [ ] Evaluate additional options for PRNGs including the onboard DRBG (or a SW version of it) (see this [comment](https://github.com/lowRISC/opentitan/pull/4972#discussion_r564882508))
- [ ] Check whether `dif_uart_byte_send_polled()` introduced significant overhead (see [this comment](https://github.com/lowRISC/opentitan/pull/7513#discussion_r679985206))

**Comment by msfschaffner** [comment]
@alphan @vogelpi can you update this issue?

**Comment by moidx** [comment]
CC @alphan @vogelpi @bilgiday 

Is this issue still relevant or is work now being tracked somewhere else?

**Comment by msfschaffner** [comment]
@vogelpi I tentatively put this in PROD.M4 - let me know if you think this belongs elsewhere.

**Comment by johannheyszl** [comment]
We are working on the tooling in the ot-sca repo. It has and will change significantly. This issue is outdated. Hence I am closing it now.

**Comment by vogelpi** [comment]
Sounds good!
