### ISSUE TITLE
[rv_dm] Support non-word bus access

### ISSUE THREAD

**Issue by jrrk2** [lowRISC/opentitan#4975]
It seems that JTAG access via system bus only supports word access on Ibex, can you confirm?

**Comment by tomroberts-lowrisc** [comment]
Yes that looks to be the case. Not sure why it's hardwired that way, but there is currently a PR open to add support for other sizes in the debug module repo ([here](https://github.com/pulp-platform/riscv-dbg/pull/106)).

**Comment by jrrk2** [comment]
Hi Tom,
  That patch seems to work well. Recommended if you want to use SEGGER Jlink rather than openocd/Olimex 

Regards,
Jonathan

**Comment by imphil** [comment]
Just a quick update here: Segger J-Link V6.94c+ (05 Feb 2021) now works if only word accesses are provided according to https://github.com/lowRISC/ibex/pull/1218#issuecomment-786114724.

**Comment by msfschaffner** [comment]
I have the feeling that this is not strictly required for the first revision, and would recommend to label this as a future enhancement that we can vendor in once the patch mentioned above has landed upstream.

**Comment by sriyerg** [comment]
Agreed, as long as it is clearly documented somewhere.

**Comment by rswarbrick** [comment]
Sounds good to me.

**Comment by msfschaffner** [comment]
Support for this has been merged upstream: https://github.com/pulp-platform/riscv-dbg/pull/106.

However, there is a fix for a CDC bug outstanding here https://github.com/pulp-platform/riscv-dbg/pull/123 and I would recommend to wait for that one to land before we vendor in anything.

**Comment by msfschaffner** [comment]
Closing this issue since it is a duplicate.
Updates will be tracked here from now on:  #11095.
