### ISSUE TITLE
[otbn] Consider which errors need prioritisation and implement it

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#4996]
With the new bitfield structure there's no total error prioritisation but whilst working on #4995 I found at least one instance where we need a partial prioritisation.

If you execute `loop x1, 2` when the call stack is empty you get a call stack error due to popping an empty stack but depending on what happens to be seen on the read data coming from the register file (which will be the last element that was on the stack or 0 when the stack never had any contents) you may or may not get an loop error for having zero iterations.

In this case saying only the call stack error should be reported and the loop error ignored is sensible. We should consider what other cases like this exist and determine the behaviour for each.

In particular how does this interact with other loop errors, how about executing `loop x1, 2` as the final instruction of an outer loop with an empty call stack, should that give a call stack error and a loop error (you cannot execute loop as the final instruction of a loop)?

Task: Create a table with all possible error bit combinations and document their behavior.

> estimate 8
> remaining 2021-04-19 4

**Comment by rswarbrick** [comment]
Eugh. I think that popping from an empty call stack should never have an architectural effect. So I suggest just a call stack error in the first case. For the second case, isn't this obviously both errors?

**Comment by GregAC** [comment]
> Eugh. I think that popping from an empty call stack should never have an architectural result. So I suggest just a call stack error in the first case

Agreed

> For the second case, isn't this obviously both errors?

From a architectural perspective yes, but going into the micro-architecture there's no way for the top-level controller to differentiate between the different loop error types so it starts getting a bit messy. It can be done of course but do we want to? E.g. we could say any call stack error where the pop result would feed into a loop means we don't even attempt the loop and thus see no loop errors. I don't think we really care about this fine level of detail for SW so it just a case of building something sane that doesn't make things too complex for either ISS or RTL.

**Comment by rswarbrick** [comment]
Oh, I see. Let's get the patch in #4986 merged and then we can hack on the exact ordering by changing the code in `insn.py` (which should hopefully make it into the spec soonish).

**Comment by GregAC** [comment]
Another prioritisation issue I found whilst doing multiple error testing in the RTL:

Loading from an unaligned address with full call stack as the destination, ISS generates both load address error and call stack error, RTL only generates load address error. In the RTL the load request is squashed by the error so we never get to the cycle where the data is returned and would trigger the call stack push that causes the call stack error.

I haven't altered the ISS to match yet as I think we're better off coming to some general decisions, then applying them to the various corner cases rather than fixing things ad-hoc.

**Comment by GregAC** [comment]
A proposal is here: https://github.com/lowRISC/opentitan/issues/5445 further progress awaits discussion and agreement of that proposal.
