### ISSUE TITLE
[otbn] Embedding executable code with ld binutils 2.36 not allowed

### ISSUE THREAD

**Issue by towoe** [lowRISC/opentitan#5021]
I got a warning with binutils 2.35 when building the `dif_otbn_smoketest_*` and then I saw that binutils 2.36 will prevent linking against an executable:
```
/usr/local/bin/riscv32-unknown-elf-ld: cannot use executable file 'sw/otbn/libbarrett384.a(barrett384.rv32embed.o)' as input to a link
```

This might only be a problem for the testing, and maybe there are already plans to change the behavior of including otbn apps into a larger binary, but if the toolchain is updated the current setup will not work.
Maybe @imphil  or @rswarbrick are already aware of this?

**Comment by rswarbrick** [comment]
That's interesting. I couldn't see it mentioned in the [Binutils NEWS file](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=binutils/NEWS;hb=refs/tags/binutils-2_36). Do you know if this change of behaviour is intentional?

**Comment by towoe** [comment]
I see a reference to it in 2.18, so maybe they just now started to produce the correct warning?

In [ldelf.c](https://sourceware.org/git/?p=binutils-gdb.git;a=blame;f=ld/ldelf.c;h=049992544a26a780ce57922e23e445524f51c4a1;hb=HEAD#l1051) there are some changes which produce the warning/error on my side.
And for reference here are some bug reports [26047](https://sourceware.org/bugzilla/show_bug.cgi?id=26047) [26288](https://sourceware.org/bugzilla/show_bug.cgi?id=26288)

Extracting symbols from executables is still allowed, but for otbn .text and .data needs to included?

**Comment by rswarbrick** [comment]
Hmm, this definitely doesn't look like they're trying to support our use-case :-)

Conceptually, what we're trying to do with this build flow is:
- Take an ELF file containing OTBN code.
- Shove that code into a RISC-V ELF file, treating it as data
- Grab some symbols from the OTBN ELF file and use them when linking the RISC-V code.

It looks like the `--just-symbols` flag would let us do that last thing, but we'd no longer get the "globs of code" part. It looks like the Linux kernel solved similar problems for BPF support: https://www.mail-archive.com/netdev@vger.kernel.org/msg323561.html (they needed to support `lld`, which has been pickier for longer). I think they used to hack `e_type` with dd(!!), but have switched to a sort of "double link", which I think matches what we'll need.

I'll try to hack up something that works.
