### ISSUE TITLE
spiflash on FPGA is timing out

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#5029]
On master, the FPGA tests currently time out because they are unable to load the application image to the FPGA using the spiflash utility. This was first seen on master after https://github.com/lowRISC/opentitan/pull/5002 got merged (which passed in PR CI). Since this PR got merged, all master builds consistently failed.

Since the PR check passed, it's likely a combination of two commits that actually caused the issue. 

Full log (not very helpful): https://dev.azure.com/lowrisc/4c50229e-f6cb-4f39-8522-585bb3841438/_apis/build/builds/32144/logs/194

--- 

Update 2021-02-01 14:30 GMT:
- In CI we now ignore failures from FPGA tests (#5043), allowing us to resume merging into master.
- The root cause of the issue is as unclear as before, @vogelpi and me are looking into it.

**Comment by imphil** [comment]
Backout in #5030, let's see what CI has to say on that.

**Comment by tjaychen** [comment]
i actually have been seeing inconsistent failures (not sure if it's the
same).
Where sometimes a run will pass, sometimes it will fail.

I actually thought it was related to this PR that I was trying to back out
https://github.com/lowRISC/opentitan/commit/71d98f8e4adf0b1ba851ce096ecc10909327156b

But then I found out it sometimes passed.

**Comment by imphil** [comment]
Still no clear root cause, I'm now individually rebuilding the commits which were batched together when the master build failed the first time. Tracking the status at https://docs.google.com/spreadsheets/d/1nzX5ie_mBiIcy4C33fx0i6-QEijkmENKssJDuq3F8F4/edit?usp=sharing

**Comment by imphil** [comment]
Still no clear root cause, looks like something is oddly flaky in a reproducible way. I'll call it a day for today, but I'll continue looking over the weekend. If you want to help, you can try downloading the bitstream/sw/spiflash artifacts from one of the failing runs on master (https://dev.azure.com/lowrisc/opentitan/_build?definitionId=9&_a=summary&repositoryFilter=5&branchFilter=566%2C566%2C566%2C566%2C566%2C566%2C566%2C566%2C566%2C566) and test on a local NexysVideo board to check if a bitstream which fails in CI also fails on a different board. But it's important to use all of the build artifacts from CI.

**Comment by tjaychen** [comment]
thanks ! i will give that a try!

**Comment by imphil** [comment]
Update: I am able to reproduce the same failures we see in CI locally with the build artifacts produced by CI, indicating that the FPGA that we have in CI is behaving correctly.
Spiflash was reported to be unreliable before, and we might just have been lucky before (e.g. the timing in the FPGA bitstream happened to be relaxed enough), e.g. as reported in #4553 and seen in Verilator much longer (#3708)

To confirm, I'd appreciate if someone else could try reproducing the failure we see in CI with another local Nexys Video board. STR:

* Download the [build artifacts](https://artproduks1.artifacts.visualstudio.com/Ace3fc167-bb91-4c33-a65a-ae648df7f974/4c50229e-f6cb-4f39-8522-585bb3841438/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2xvd3Jpc2MvcHJvamVjdElkLzRjNTAyMjllLWY2Y2ItNGYzOS04NTIyLTU4NWJiMzg0MTQzOC9idWlsZElkLzMyMjQ4L2FydGlmYWN0TmFtZS9vcGVudGl0YW4tZGlzdA2/content?format=file&subPath=%2Fopentitan-snapshot-20191101-1-4100-g9e7eb06f0.tar.xz) of build https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=32248&view=results
* Extract the archive.
* Flash the FPGA: `$REPO_TOP/util/opentitan-pgm-fpga/opentitan-pgm-fpga xc7a200tsbg484-1 hw/top_earlgrey/lowrisc_systems_top_earlgrey_nexysvideo_0.1.bit` (replace $REPO_TOP with the path to your opentitan repository)
* Run spiflash to flash an arbitrary binary: `sw/host/spiflash/spiflash --input sw/device/tests/dif_otbn_smoketest_fpga_nexysvideo.bin`

I'm inclined to disable running the tests on an FPGA for now until we've sorted this out in order to unblock merging into master. This will of course mean our tests will degrade quickly, so we'll need to sort this out with highest priority, and then re-enable the test.

**Comment by vogelpi** [comment]
I have a board here and will take a look. However, I can already say now that #5002 doesn't have anything to do with the failure. The only thing t hat really changes in this PR are a couple of assertions. The functionality is exactly the same.

**Comment by imphil** [comment]
None of the jobs that are failing at the moment are clearly responsible for the failure, that's quite clear by now -- the failure seem to be non-deterministic. It looks like simple bisect won't give us a solution, unfortunately.

**Comment by vogelpi** [comment]
It seems the FPGA bitstream is completely broken. I don't even get the boot ROM output over UART...

**Comment by imphil** [comment]
Oh fun. I just redid the tests I did yesterday as outlined at https://github.com/lowRISC/opentitan/issues/5029#issuecomment-770377344 and now I'm actually getting a working system (spiflash and SW work as expected), which is the opposite behavior of what I've seen yesterday and what CI reports. Either it's even flakier than I hoped for, or I did something wrong yesterday and actually the CI runner is at fault ...
