### ISSUE TITLE
Rule for defining memory map

### ISSUE THREAD

**Issue by sajjadahmed677** [lowRISC/opentitan#5040]
Hello everyone! referred to "xbar_main" and "xbar_peri"  i have a confusion regarding memory map. is there any hard coded rule for defining memory map in such manner as defined in opnetitan project. or designer can assign base address for devices by his choice?? and what is the benefit of such definition?

**Comment by tjaychen** [comment]
the main difference between xbar_main / xbar_peri is that they run at
different clock frequencies.
So if you plan to add any new module, you could follow this scheme as well.

**Comment by sajjadahmed677** [comment]
thank you @imphil. 
actually i was asking for defining the base addresses for all the devices. why we define in such manner like GPIO starts from 0x40040000 why not from any other address. so, is there any convention for setting base addresses.

**Comment by GregAC** [comment]
I don't think there's any particular convention. It can be driven by software requirements, for example if you use the PMP memory protection provided by Ibex you only have 16 regions to work with. Depending on what kinds of access control you may wish to implement there will be certain IPs you would want to group in the same address range to make efficient use of PMP regions.

More broadly it can be useful to define different areas of address space for different purposes, e.g. have one region for 'device' memory where peripheral registers live and another for 'real' memory like SRAM. The system may treat these memories types differently (this is referred to as PMA, physical memory attributes, in the RISC-V privileged specification) but OpenTitan doesn't do this currently.

**Comment by sajjadahmed677** [comment]
Alright @GregAC!
so you mean its up to the designer that which regions he specifies for devices and real memories or according to software needs.
