### ISSUE TITLE
Add pull request check to Python lint check

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#5048]
@rswarbrick your recent CI change broke master CI, see https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=32320&view=logs&jobId=3a559e2a-952e-58d2-b8db-2e604a9266d7&j=3a559e2a-952e-58d2-b8db-2e604a9266d7&t=f2c464ff-acea-55de-fd89-91767e1cc5fc

It looks like the Python lint check should only run in PRs, not on master.

**Comment by rswarbrick** [comment]
Oops! I'll fix that now.
