### ISSUE TITLE
[otbn] Add vector-vector Rotate and Add SIMD instructions

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#5058]
The current OpenTitan design only has planned support for SHA2-256 in hardware, leaving SHA2-384 and SHA2-512 to be implemented in software. Even though these algorithms could be implemented in Ibex, this issue focuses on requesting new OTBN SIMD instructions with support for 32B and 64B slice lengths. This will enable optimized SHA2 implementations, and also allow us to consider other algorithms in the future (Salsa20, Chacha, Blake2). 

## Instructions 

*   **vector-vector rotation**: Similar to the vector rotation proposed in [riscv-crypto-spec-v0.7.0-vector](https://github.com/riscv/riscv-crypto/releases/tag/v0.7.0).
*   **vector-vector addition**:  `wrd[i]  = wrs1[i] + wrs2[i]`.  No AddWithCarry support needed. 

The slice width can be set via a separate instruction or  different variants can be implemented (e.g. `bn.vadd.vv32`, `bn.vadd.vv64`, `bn.vrot.vv32`, `bn.vrot.vv64`). 

+@imphil  and +@felixmiller  for initial thoughts.

**Comment by mundaym** [comment]
Do you have a rough idea how much execution time and/or code size would be saved by utilising these vector operations for SHA2? I don't think SHA2 vectorizes particularly well but perhaps the proposed vector operations would help enough to make them worthwhile. For the other algorithms you mention I agree that adding these vector instructions would allow significantly faster implementations.

If this proposal is accepted it might be worth adding some vector permutation instructions to make it easier to reorder elements and/or bytes in the WDRs. I think that would be hard with the existing instruction set (at least as currently published in the docs).

**Comment by mundaym** [comment]
(By the way I'm asking just to satisfy my own curiosity, I don't have any objections to this proposal.)

**Comment by GregAC** [comment]
Hardware wise I don't think this would be much trouble. I'd anticipate it wouldn't require vast amounts of new area (maybe similar to the existing bignum ALU, smaller even as it doesn't need to support the same range of operations).

We'd need to consider what spare encoding space we have for any potential new vector instructions.

**Comment by felixmiller** [comment]
I think it is probably worth to create a version of ISS that experimentally adds the instructions. We can then play with the SHA2-512 code to get a pretty good understanding of the performance improvement and also see if we have an issue with the encoding. I can look into this next week.

**Comment by imphil** [comment]
I talked to Miguel the other day and he's in the process of cleaning up his unoptimized SHA2-512 OTBN assembly code and get that added to the code-snippets directory. We can then use that as base for optimizations on the instruction set.

**Comment by msfschaffner** [comment]
@GregAC @rswarbrick @felixmiller I am assuming this is not on the roadmap for PROD, is that right?

**Comment by felixmiller** [comment]
This came up here at a time when it was still realistic to include the HW for the required machine instructions but we later decided to not do this for "OTBN 1.0". It is definitely one of the top features for a future HW release but nothing that should be relevant to PROD in any way. We keep track of possible features for future releases elsewhere so I think this can be closed here.
