### ISSUE TITLE
Byte-enable access in Regtool

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#5090]
Is it possible to create in regtool to create a hwext register and collect the byte enables?

My use case is that I want to collect data into a fifo using a full 32-wide TLUL register, but not force the user to always write to all 32-bits.   If firmware does a half-word or single byte write, I'd like to capture that into the FIFO as well.

What are the options here?

**Comment by tjaychen** [comment]
ah if you want to do that Martin, it's better to ask the regtool to expose
the entire TLUL as a window, then you can do with that TLUL bus what you
like.
For registers specifically, we made very specific decisions very early on
to not allow byte writes.

Let me know if that sounds like it works, and I can point you to more
examples.

**Comment by martin-lueker** [comment]
Thanks tim.  I'll look into it.

**Comment by tjaychen** [comment]
just as an example, both flash / spi device export a tlul from the regtool
directly. We then feed this through tlul_sram_adapater and use it to access
local storage (spi device actually accesses memory, while flash ctrl only
accesses FIFOs).
hope that helps.

**Comment by martin-lueker** [comment]
Ah! Thanks, that really helps.  The flash_ctrl fifo example particularly!
