### ISSUE TITLE
[top] Some peripherals not hooked up to edn

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#5120]
There are various modules that need to be hooked up to edn but have not done so.

These fall into two categories:

1. `edn` gadgetry exists and just needs to be hooked up
- [x] `kmac`
- [x] others?

2. `edn` gadgetry does not exist and needs to be created and hooked up
- [x] `aes`
- [x] `alert_handler`
- [x] `otbn`
- [x] second OTBN connection: https://github.com/lowRISC/opentitan/issues/5523
- [x] others?

**Comment by msfschaffner** [comment]
Yeah that's on my list of things that need to be adjusted in the alert handler.
I thought I'd bunch these mods all together since they are not super urgent, and the entropy fetching period will have implications on the escalation reverse ping mechanism (yet to be added, https://github.com/lowRISC/opentitan/issues/2049).
However, if you can take a stab at just aligning the interface and hooking that up to EDN, that would be great (I can take care of the internals when adding reverse ping).

**Comment by vogelpi** [comment]
Thanks for raising the issue @tjaychen . Hooking up `aes` with `edn` is on my list.

**Comment by GregAC** [comment]
Hooking up OTBN to the EDN is planned for this OTBN sprint: https://github.com/lowRISC/opentitan/issues/2638

**Comment by GregAC** [comment]
PR for OTBN EDN hookup is here: https://github.com/lowRISC/opentitan/pull/5286

**Comment by vogelpi** [comment]
PR for AES EDN hookup is here: #5427

**Comment by msfschaffner** [comment]
@eunchan, what is the status of the EDN hookup on KMAC?

**Comment by tjaychen** [comment]
i think at the top level, that one is already done.
https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/top_earlgrey.hjson#L775

**Comment by msfschaffner** [comment]
Ok so it looks like the critical blocks are connected.
Do we have any others that we anticipate need to be hooked up to EDN?

**Comment by tjaychen** [comment]
the last two should be otbn rnd and urnd i believe.

**Comment by GregAC** [comment]
There's already one OTBN hookup, that was before I knew we had two seperate hookups planned. Shall I implement the second one now? Do we need to worry about what is connected to what EDN instance or is it sufficient to just have all hookups in place and we can worry about IP -> EDN allocation later?

**Comment by tjaychen** [comment]
yeah if you can just add a second interface, I will make sure to hook it up
to the correct edn instance.
For now, would you mind just diversifying the names a bit with something
like rnd / urnd? That would be very helpful at the top level.

**Comment by tjaychen** [comment]
i believe this is done. 
Thanks everyone.
