### ISSUE TITLE
[spi_host]: TX Behavior when TX FIFO is empty.

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#5133]
In PR #5077, the proposed behavior for spi_host is to stall when the TXFIFO is out of data. In discussion with @tjaychen, we are wondering if there is some alternative behavior that would be useful.  i.e. a mode where the host would continue to send some default value even if firmware has not provided data.

**Comment by martin-lueker** [comment]
FYI: @a-pronin.

**Comment by tjaychen** [comment]
@martin-lueker , i checked with Andrey offline as well a few others, and indeed it seems like this "dummy" feature wouldn't be useful on spi host. I think we can close this issue.
