### ISSUE TITLE
how to cover unknown transitions

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#5139]
For Xcelium/IMC transistions from 'x to either '0 or '1 and vice versa is not counted towards toggle coverage.

this means that ports in the AES register is not counted in the coverage even if the ports are exercised in the simulation.

as an example the key_share register port q and WD are both marked as uncovered.
![image](https://user-images.githubusercontent.com/53917183/107230676-a6ce4b00-6a1f-11eb-99c6-16746947f491.png)

while they are infact exercised.

should we exclude these upon inspection or is there a smarter way to cover this?
![image](https://user-images.githubusercontent.com/53917183/107230801-cbc2be00-6a1f-11eb-8051-c2b477f658e6.png)

**Comment by sriyerg** [comment]
We collect toggle coverage only on DUT ports. We do not attempt to cover any signals in the internal hierarchy, the motivation being that already manifests in the coverage of other metrics - line, condition, branch and fsm. 

For VCS, we do this by adding this switch (`hw/dv/tools/dvsim/vcs.json`):
```
                   // Dump toggle coverage on mdas, array of structs and on ports only
                   "-cm_tgl mda+structarr+portsonly",
```

In combination with compile-time coverage 'pruning' to limit toggle coverage to only the DUT ports here (`hw/dv/tools/vcs/cover.cfg`):
```
begin tgl
  -tree tb
  +tree tb.dut 1
end
```

As such, attempting to cover all internal signals does not provide a good ROI (if all other metrics are fully covered, the things that show up as uncovered on the toggle coverage metric on the internal DUT signals are unreachable / dead code). I have indicated this in the methodology doc as well:
https://docs.opentitan.org/doc/ug/dv_methodology/#code-coverage

Thanks,
-Sri

**Comment by senelson7** [comment]
Sri is indicating we don't collect coverage on the internals but FYI... xcelium default x's/z's are not treated as transitions but to enable use: set_toggle_includex, set_toggle_includez.

**Comment by rasmus-madsen** [comment]
@sriyerg Thanks that detail slipped my mind.
@senelson7 thank you for the solution
