### ISSUE TITLE
[tlul] does TLUL crossbar need devmode?

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/opentitan#514]
Right now in Comportability specification, non-security devices always return error when an address is requested that is not in the device's address map. Security devices return the same error if devmode_i == 1'b1.

There is another error responder in the system, and that is the in-between error responder in tlul_socket_1n. It currently always responds in error. For it to conform to the guidance, it needs to either be considered a non-security device, or receive devmode_i to determine how to respond.

The question is whether or not we want to concern ourselves with error responses in the gaps between IP addresses. If so, we need to consider the TLUL fabric to be a "secure device" and provide it with devmode_i.

Opinions?

**Comment by msfschaffner** [comment]
Reviving this old issue: 
are we still OK with the decision to not add any more address range checks to the fabric (i.e., add a `devmode` for the fabric)?

In terms of glitch detection, we do have ECC-based bus integrity protection now that checks the address, cmd and data fields.
However, the actual checks are instantiated at the packet consumer side, so the bus fabric itself does not contain any checkers, nor does it output alerts at the moment.

**Comment by msfschaffner** [comment]
@eunchan @dsandrs

**Comment by tjaychen** [comment]
i think it is okay to close this issue.
