### ISSUE TITLE
[dif_spi_device] Frame size mismatch

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#5145]
in PR #5068 , I upsize the SPI_DEVICE internal DPSRAM buffer for SPI Flash / Passthrough mode. The FPGA test failed as BOOTROM cannot download the FW image and update internal flash.

Revised BOOTROM's `SPIFLASH_RAW_BUFFER_SIZE` to 2048 (4kB/2) from 1024. Still failed. Figure out that the BOOTROM (or dif_spi_device) reads whole buffer rather than what host system sent?

Host spiflash app sends 1kB chunk of image through SPI interface. What I expect was the DIF reads only 1kB and consist the fw image from the series of 1kB chunk. Looks like the code strictly expect the RX buffer and the half of DPSRAM and also the SPIFlash frame size are exactly matched.

Can anyone in assignee list comment? Did I understand correctly?

**Comment by moidx** [comment]
Hi @eunchan  is this still an issue? I see lowrisc/opentitan#5068 was merged. I believe @mcy is the most familiar with the spi_device dif.

**Comment by eunchan** [comment]
I still think this is worth to discuss, DIF SPI_DEVICE assumes the buffer to be half of the SRAM But the SRAM size is not correctly propagated into DIF header so that the design change results in SW changes too. I think we won't change DPSRAM size in near future. So we can lower this or close and re-open when needed.

I will close this and re-raise later :)

**Comment by tjaychen** [comment]
sorry to re-open @eunchan , can you make the sram size a param inside spi_device.hjson? Then maybe this same parameter can be propagated to the instantiation of the `dpsram` inside `spi_device`.  The params get automatically converted into headers for software, and maybe they should just re-use that one in the future as you say.

**Comment by eunchan** [comment]
Ah. That's good idea. Let me do that.

**Comment by eunchan** [comment]
This one has been addressed in #5264 . Closing now.
