### ISSUE TITLE
[spi_host] Support for XIP

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#5168]
PR #5077 makes no reference to Execute in place.  Does the current spec support it?

This issue is just meant to cross check the spec and determine if there are any functionality requirements that are missing for this type of operation.   If it is not supported, the goal is to briefly understand what is missing.

**Comment by tjaychen** [comment]
wow, XIP? what's the context here? Do you mean our cpu needing to execute directly out of serial flash?

**Comment by martin-lueker** [comment]
Hi Tim,
   This is more of a question, than a insistence that we support it.

**Comment by tjaychen** [comment]
ahhhh! i don't think we need to support it :)
if that helps.

**Comment by martin-lueker** [comment]
Resolution: No support for XIP in OpenTitan SPI Host
