### ISSUE TITLE
[prim_ram] Parity error for uninitialized data

### ISSUE THREAD

**Issue by towoe** [lowRISC/opentitan#5185]
Reading uninitialized data results in an unrecoverable error.
Maybe code should not do that, but it should be either more obvious or configurable?
A config option would make it clear that after activating the parity check errors can occur.

If the memory always needs to be cleared after a reset maybe it would make sense to do it in hardware?
This would prevent "unintended" parity errors.

**Comment by msfschaffner** [comment]
Thanks for bringing this up @towoe!
This is a good point, we'll discuss this offline and come back to this issue.

Related: #5262

**Comment by tjaychen** [comment]
hey all, #5572 has been implemented.
So software should be able to trigger a memory initialization that is relatively fast.
The caveat to using this is that we first need to enable the entropy subsystem, there is some basic code do that as well.

**Comment by tjaychen** [comment]
see #5714 for how boot rom can set this up.

**Comment by tjaychen** [comment]
this issue should be resolved through memory init.
