### ISSUE TITLE
[keymgr] Update the sizes of sw_binding and salt in key manager

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#5194]
We decided to use 256b for sw_binding and salt in #4256 (please see this comment). @tjaychen apologies for the noise if you were already tracking this.

----

Remaining SW tasks:
- [ ] Uncomment (and simplify) static_asserts when #5578 is merged.

**Comment by tjaychen** [comment]
thanks for the issue, i will update.

**Comment by tjaychen** [comment]
@weicaiyang just FYI on this requested change.  The design has not been updated yet.  I'll do that first and see if it's straightforward to update the others.

**Comment by weicaiyang** [comment]
> @weicaiyang just FYI on this requested change. The design has not been updated yet. I'll do that first and see if it's straightforward to update the others.

Thanks Tim. I can push the DV change into your PR. LMK if you want me to do that.

**Comment by tjaychen** [comment]
@alphan this change has been merged.
I'm keeping this issue open for now in case there's anything we need to do on software side.

**Comment by alphan** [comment]
Thanks, updated description.

**Comment by tjaychen** [comment]
i believe this is done
