### ISSUE TITLE
Move top_earlgray_usb to use auto generation

### ISSUE THREAD

**Issue by mdhayter** [lowRISC/opentitan#52]
Need to auto generate the top_earlgray_usb (for now it is still in the old standalone model). Hope to have some time to do this next week. (I don't know how to cc you so added as assignees for the questions)

@eunchan is there documentation on this? I didn't find on bubble but I seem to remember it in a review.

@eunchan @imphil as part of this should I move to a new top_earlgray_usb directory? Originally it made sense to keep them in the same place because there was so much shared and you only had to update files like the xilinx clock generation in one place, but if things are generated there should be almost nothing shared. Or since we are soon moving on from earlgrey should I keep it where it is? Or maybe just rtl_usb in the top_earlgrey?

**Comment by imphil** [comment]
@stefanlippuner @vogelpi you're planning to work on this AFAIK?

**Comment by vogelpi** [comment]
Yes, the we continued this discussion in Stefan's original USB issue here: #1007 .

**Comment by sjgitty** [comment]
This issue can be closed once we decide to move forward with USB within `top_earlgrey`, which is our current intention. Discussion next week on game plan.
