### ISSUE TITLE
GDB Breakpoint not working  

### ISSUE THREAD

**Issue by sajjadahmed677** [lowRISC/opentitan#5231]
I am trying to debug a simple c code open earlgray using gdb but it not giving the required behavior.

Breakpoint 1 at 0x20000180: file ../sw/device/examples/hello_world/hello_world.c, line 20.
(gdb) c
Continuing.
Breakpoint 1, main () at ../sw/device/examples/hello_world/hello_world.c:24
24      }
(gdb) step

here i have inserted the breakpoint at line 20 but when it starts execution gdb stops at line 24 which is the end of my program.
ant it always doing the same at any breakpoint. what will be the possible reason for that or i am doing something wrong.

**Comment by rswarbrick** [comment]
What version of the repository are you using? Here (commit 558f3313a), line 20 of that file is a definition of a static variable and line 24 is the first line of `main`, which seems like a reasonable thing for gdb to do.

**Comment by sajjadahmed677** [comment]
actually i have edited that hello_world.c file and right now i am running a simple a+b code for understanding the debugging process through gdb. if i am doing wrong will you please guide me that how can i run my custom programs.

**Comment by tomroberts-lowrisc** [comment]
What is on line 20 in your modified program? As rswarbrick noted, that is a variable declaration in the unmodified file (the breakpoint has to be placed on a line that is actually executed i.e. something inside the main {} body - apologies if you already knew that but thought I better explain anyway!)

Assuming the breakpoint is placed somewhere sensible, can you post the exact commands used and let us know if there were any error messages. We used to have problems in the past with gdb not knowing whether to use hardware breakpoints vs software breakpoints but I believe that was fixed.

**Comment by sajjadahmed677** [comment]
Alright @tomroberts-lowrisc  thank you for your response.
so here is what i am doing and what is in my code.
for running simulation on verilator i am using the following command flow,

1.  ninja -C build-out all (running this command on REPO_TOP)

2. build/lowrisc_systems_top_earlgrey_verilator_0.1/sim-verilator/Vtop_earlgrey_verilator   --meminit=rom,build-bin/sw/device/boot_rom/boot_rom_sim_verilator.elf   --meminit=flash,build-bin/sw/device/examples/hello_world/hello_world_sim_verilator.elf
(for running simulation of my code).

3. openocd -s util/openocd -f board/lowrisc-earlgrey-verilator.cfg (for starting openocd session).

4. iscv32-unknown-elf-gdb -ex "target extended-remote :3333" -ex "info reg"   build-bin/sw/device/examples/hello_world/hello_world_sim_verilator.elf (for starting gdb session).

once i got gdb prompt then i am setting breakpoint at main function of my code. using "b main" gdb command.
but it is always inserting breakpoint at the end of my code either i am using "b main" or "b 1".
here is my code

int main() {
 int a= 3, b= 4, c;
 c = a+b;
 return 0;
}

i am not getting any error message but also i am not getting breakpoint at my desired location.

**Comment by tomroberts-lowrisc** [comment]
Hi @sajjadahmed677 - it might be that you just need to restart the execution (i.e. you have gone past the breakpoint before you ever inserted it)
type `monitor reset halt` in gdb (this should take the cpu back to the start of bootrom), then if you type `c` you should hit the breakpoint at main()
I just tried this and it worked for me

**Comment by sajjadahmed677** [comment]
i have tried it but same behavior i am getting.

(gdb) b 1
Breakpoint 1 at 0x20000180: file ../sw/device/examples/hello_world/hello_world.c, line 20.
(gdb) monitor reset halt
JTAG tap: riscv.tap tap/device found: 0x04f5484d (mfg: 0x426 (Google Inc), part: 0x4f54, ver: 0x0)
(gdb) c
Continuing.

Breakpoint 1, main () at ../sw/device/examples/hello_world/hello_world.c:24
24      }

it is again stopping at line 24 which is the end of my code.

**Comment by tomroberts-lowrisc** [comment]
Hi @sajjadahmed677 - in that case I'm not sure, it is working with the standard hello_world for me.

You could try looking at the assembly that has actually been produced. Looking at the example code you gave:
```
int main() {
int a= 3, b= 4, c;
c = a+b;
return 0;
}
```
It's likely that a compiler would optimize this away to nothing

**Comment by sajjadahmed677** [comment]
@tomroberts-lowrisc  will you please guide me how can i debug custom programs on it??

**Comment by tomroberts-lowrisc** [comment]
If you execute:
`riscv32-unknown-elf-objdump -d build-out/sw/device/examples/hello_world/hello_world_sim_verilator.elf`
you will get the disassembly of your program.

If you look in the "main" section you will see that there are no instructions there (just a load and then `ret`). This is because the compiler has optimized away your code (because the results of c = a + b are never used anywhere).

I believe what is happening is that when you add a breakpoint at main, the debugger is telling you that you are at the end of main (because it is an empty function, so the beginning of main == the end of main).

This is generally a hacky solution(!) but if you modify your program as below, it won't get optimized away and you should be able to step through it.
```
int main() {
volatile int a= 3, b= 4, c;
c = a+b;
return 0;
}
```

**Comment by sajjadahmed677** [comment]
Thank you @tomroberts-lowrisc it worked for me as well.
