### ISSUE TITLE
[sw, rom_ext_signer] outstanding work to be done

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#5232]
- [x] Tests (Partially, includes one unit-test)
- [ ] Use non-dummy system state
- [ ] More comprehensive error handling
- [ ] Better input argument handling (see [comment](https://github.com/lowRISC/opentitan/pull/5115#discussion_r573839542))
- [x] Exponent and modulus getters (see the [issue](https://github.com/google/mundane/issues/28), resolved in #5467)
- [ ] Receipt
- [ ] `device_usage_value` parsing from `device_usage_constraints`
- [ ] `peripheral_lockdown_info` (need to figure out encoding, see [issue](https://github.com/lowRISC/opentitan/issues/5081))
- [ ] Documentation
- [ ] To avoid confusion, calculate image length in the signer (technically don't need to do it, as it is done on the fly inside `manifest.S`)
- [ ] Sync manifest.rs generation with the ROM_EXT Signer build (currently is checked in, but not generated on every build)

**Comment by silvestrst** [comment]
@asb @mundaym @mcy @jon-flatley @moidx @alphan 

For visibility

**Comment by moidx** [comment]
Marking this issue as obsolete as we are currently tracking the manifest tasks in a separate burndown.
