### ISSUE TITLE
hw/top_englishbreakfast/util/prepare_sw.py needs some attention

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#5242]
@vogelpi, I tried regenerating the fpga bitstream and building `aes_serial` using `hw/top_englishbreakfast/util/prepare_sw.py` at opentitan:master but it looks like two things need to be fixed (I did a `git bisect` to save you some time):
* Topgen cannot find the hjson file for alert_handler, starting from commit f1006bd24a5d81b2887bb60924bc49d209e107a2
* Macro definition for UART0 base address is missing (bootrom build fails), starting from commit 2971a1ea44cb941c4fb58376e312c30617644192

**Comment by alphan** [comment]
@moidx, fyi in case you want to generate a new bitstream.

**Comment by vogelpi** [comment]
Thanks @alphan for reporting this. I am looking into this now.
