### ISSUE TITLE
[otbn] Get performance numbers for ECDSA P-256

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#5248]
PR #5247 provides us with an end-to-end sign/verify test for ECDSA P-256. We can now use this test to get performance numbers for ECDSA P-256.

To make the numbers slightly more accurate, it would be nice to get answers to two questions. (If we don't have them right now that's fine as well, it won't make that much of a difference.) 

Currently, the test uses a hardcoded random value `k`, which must be generated on the fly in a real-world scenario. For the verify test the final comparison (r == r') is done on Ibex (and not included in the performance numbers right now).

To make the performance numbers we get from this test close to reality I have two questions:

* Should we produce the random value `k` on OTBN, or on Ibex?
* Should we perform the final comparison in verify on OTBN (returning only "verify passed" back to Ibex), or on Ibex?

(Doesn't matter is a valid answer, in that case I'll go for OTBN, as it will be faster.)

@moidx @felixmiller

**Comment by felixmiller** [comment]
Re k: This number should be generated on OTBN in the future. The requirement here is guaranteed fresh and high entropy, since this number is part of the algorithm specification.
Re comparison: Also here I don't see a reason why this shouldn't happen on OTBN (which is faster here). Result encoding shouldn't be a single bit obviously but a 32 bit magic number probably.

We can tackle both as soon as #4000 is through.

**Comment by imphil** [comment]
With the current code in the OpenTitan source tree we get the following performance numbers for ECDSA P-256:

* Signing: 788 us (initialization) + 6604 us (signing) = 7392 us
* Verification: 788 us (initialization) + 4650 us (verification) = 5438 us

The initialization part is primarily loading the instruction code into OTBN, which of needs to be done only once for consecutive operations.

Things to note:
* The current OTBN assembly code isn't optimized, but is also missing some small features (as discussed in this issue). Expect an error margin of around +- 20% (with a tendency towards decreasing the runtime actually).
* These numbers are for ECDSA P-256, *not for P-384*. Expect numbers for P-384 to be roughly 6x as large, based on current very rough estimates.

@mateenfaisal @felixmiller @moidx
