### ISSUE TITLE
Why the TOP_EARLGREY_BATCH_SIM UVM Simulation results of PASS RATE and Coverage data almost became near 0%

### ISSUE THREAD

**Issue by JmheYouzi** [lowRISC/opentitan#5249]
run nightly regressions on all of your IPs, including the full chip. The results can be found here:

https://reports.opentitan.org/hw/top_earlgrey/dv/summary.html,

and this is the UART Simulation Results :

https://reports.opentitan.org/hw/ip/uart/dv/latest/results.html

**Comment by rswarbrick** [comment]
There seems to be some problem with our EDA tooling infrastructure that has come up in the last couple of days. I believe that @cindychip is on the case.

**Comment by cindychip** [comment]
Sorry for the confusion. Yes as Rupert mentioned, I am working on fixing it :)

**Comment by JmheYouzi** [comment]
Thank you !
