### ISSUE TITLE
Working with regtool generates an ERROR message

### ISSUE THREAD

**Issue by danaagur** [lowRISC/opentitan#5267]
Hello,
I am trying to run regtool on my recent hjson file (with minor and irrelevant change), and get ERROR:

In the hjson file I have:
{ name: "REGWEN",
      desc: "Register write enable for a bank of registers",
      swaccess: "rw1c",
      fields: [ { bits: "0", resval: "1" } ]
    }
And it worked properly in the past. However recently I wanted to run it again and got the following ERROR message:
ERROR: REGWEN used as regwen fails requirement to be swaccess=W0C or swaccess=RO and hwaccess=HWO
Changing swaccess to W0C or swaccess=RO and hwaccess=HWO yields other ERROR message.

Please advise, thanks,
Dana

**Comment by danaagur** [comment]
@arnon.sharlin

**Comment by tomroberts-lowrisc** [comment]
Hi
There was a recent project-wide change to rw0c as the convention for all REGWEN registers. This worked for me recently:
```
      swaccess: "rw0c",
      hwaccess: "none",
      fields: [
        { bits: "0",
          name: "regwen",
          desc: "Once cleared, the watchdog configuration will be locked until the next reset",
          resval: 1
```

**Comment by danaagur** [comment]
Right, thanks, it works now.
I suggest the ERROR message will be correct.
Thanks,
Dana

@arnonsha
