### ISSUE TITLE
[DFT] - spi_device clock should be muxed with scan clock

### ISSUE THREAD

**Issue by arnonsha** [lowRISC/opentitan#5276]
top_earlgrey.u_spi_device.cio_sck_i is driven by pad. As such it is not fully controlled during scan. about 145FFs of spi_device are removed from the scan chains as a result.

Suggested solution:
Add a scan_clk dedicated input and connect a clock with the expected clock frequency. Maybe io_div2 ?

**Comment by arnonsha** [comment]
@NoamGottlieb

**Comment by tjaychen** [comment]
thanks @arnonsha.

**Comment by tjaychen** [comment]
checked offline with @arnonsha, and the scan clock connected to spi_device can one of the existing functional clocks.  Those clocks already have scan clock control, thus we do not need an additional bypass. 

This is really for my own clarification.
