### ISSUE TITLE
[DFT] - dap tck_i port is not controlled during scan

### ISSUE THREAD

**Issue by arnonsha** [lowRISC/opentitan#5277]
The tck_i port is driven from pad. During scan it is not controlled. About 350 FFs are removed from scan as a result.
To solve this, need to mux it with a controlled clock that has about the same speed (IO_div4 ?)

**Comment by arnonsha** [comment]
@NoamGottlieb

**Comment by msfschaffner** [comment]
Sure let me do that  (should not be difficult).

**Comment by arnonsha** [comment]
I am not sure #5293 solves this. Will run spyglass next week
My understanding is that tck needs to be muxed with another controlled clock. For example the tlul_clk:

Something like
clk_i = scan_mode ? tlul_clk : tck_i

So just adding scan mode is not enough

**Comment by msfschaffner** [comment]
You are right, @arnonsha. I thought the TAP we use muxes the clock already when it is in scanmode. However, it looks like it only bypasses a clock inverter, which is not sufficient. I will add the mux.
