### ISSUE TITLE
[topgen] Currently unavoidable warning ("device peri in Xbar main is connected to another Xbar")

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#5282]
Running `make -C hw top`, we currently spit out several copies of:
```
WARNING: device peri in Xbar main is connected to another Xbar
```
As far as I can tell, there's no way to connect up our chip the way we want without triggering this warning. So we either need to add a "yeah, I know" flag to the tool to silence it, or remove the warning altogether.

@eunchan: I think you added this warning in commit c745294243. Could you explain what it's trying to say? (I'm definitely not an expert on this part of the tooling!)

This currently blocks landing PR #5026, which fixes several bugs in our CI linting flow.

@msfschaffner: FYI

**Comment by eunchan** [comment]
I think this should be INFO rather than warning. :)
