### ISSUE TITLE
OpenTitan commit 99cb19827, can't run Tock OS on self-built bitstream

### ISSUE THREAD

**Issue by gemarcano** [lowRISC/opentitan#5288]
This is an issue I reported to tock/tock#2438, but they appear to think this some problem in bitstream generation.

As far as I understand it, Tock OS cannot run on OpenTitan commits newer than 99cb19827 (might be related to #4731). As such, I installed Vivado 2020.2 on my Gentoo Linux system in order to build the bitstream for 99cb19827. I built the bitstream, and after installing it on my Nexys Video board it appears to run the OpenTitan bootloader just fine, but then Tock for some reason throws up a panic. I was provided a different bitstream by one of the Tock developers of the same OpenTitan commit, which booted Tock just fine (same exact kernel).

Let me know what kind of diagnostic information you would like from me to help figure out what is going on. I also tried downgrading Vivado to 2020.1, but the generated bitstream resulted in the same issue manifesting. I have copies of both the bad bitstreams (plus I can build them) and the good one.

**Comment by imphil** [comment]
Did you run `top_earlgrey_reduce.py` before building the bitstream and the bootrom?

Effectively, the sequence looks like that (that's the script I'm using):


```sh
#!/bin/bash

set -e
set -x
. util/build_consts.sh

module load "xilinx/vivado/2020.1"

./hw/top_earlgrey/util/top_earlgrey_reduce.py

# build sw/bootrom
./meson_init.sh -f
ninja -C $OBJ_DIR all

mkdir -p "$OBJ_DIR/hw"
mkdir -p "$BIN_DIR/hw/top_earlgrey"

BOOTROM_VMEM="$BIN_DIR/sw/device/boot_rom/boot_rom_fpga_nexysvideo.32.vmem"
test -f "$BOOTROM_VMEM"

fusesoc --cores-root=. \
  run --flag=fileset_top --target=synth --setup --build \
  --build-root="$OBJ_DIR/hw" \
  lowrisc:systems:top_earlgrey_nexysvideo \
  --BootRomInitFile="$BOOTROM_VMEM"

cp "$OBJ_DIR/hw/synth-vivado/lowrisc_systems_top_earlgrey_nexysvideo_0.1.bit" \
  "$BIN_DIR/hw/top_earlgrey"
```

**Comment by gemarcano** [comment]
Yes, I did run the reduce script (I think in 99cb198 it's called `opentitan_earlgrey_flash_size_reduce.py`). I made sure to build the bootrom after doing this.

I will attempt to build it once again, from scratch, using your script, since I'm seeing extra parameters being passed to fusesoc that I don't remember passing in myself (I was following the instructions from the OpenTitan docs).

**Comment by imphil** [comment]
Oh yes, you're using an old version. For that version you don't need to reduce the flash size, a regular build will do the trick. See the CI config at that time: https://github.com/lowRISC/opentitan/blob/99cb19827ebbd5dcee097c061a271ac09be5b523/azure-pipelines.yml#L423

**Comment by gemarcano** [comment]
I wonder if the reduce script was the source of the problem? I'm attempting to build a new bitstream, this time without calling the reduce script. I'm using a slightly modified version of your script (I'm only building spiflash and the bootrom instead of all objects, there seems to be some problem with LD not liking `sw/device/tests/dif_otbn_smoketest_sim_dv.elf`, something about `/usr/libexec/gcc/riscv32-unknown-elf/ld: Using an executable file (sw/otbn/libbarrett384.a(barrett384.rv32embed.o)) as input to a link is deprecated - support is likely to be removed in the future`), which I'll post here once I can confirm everything built properly (I also had to provide a custom toolchain.config, I'll post it here as well once I finish building and testing this new bitstream).

**Comment by gemarcano** [comment]
This is what I ended up using to build it:

build.sh:
```
#!/bin/bash

set -e
set -x
. util/build_consts.sh

#module load "xilinx/vivado/2020.1"
. /opt/Xilinx/Vivado/2020.1/settings64.sh

# build sw/bootrom
./meson_init.sh -f -K -t toolchain.config
ninja -C $OBJ_DIR sw/device/boot_rom/boot_rom_export_fpga_nexysvideo sw/host/spiflash/spiflash_export
#ninja -C $OBJ_DIR all

mkdir -p "$OBJ_DIR/hw"
mkdir -p "$BIN_DIR/hw/top_earlgrey"

BOOTROM_VMEM="$BIN_DIR/sw/device/boot_rom/boot_rom_fpga_nexysvideo.32.vmem"
test -f "$BOOTROM_VMEM"

fusesoc --cores-root=. \
  run --flag=fileset_top --target=synth --setup --build \
  --build-root="$OBJ_DIR/hw" \
  lowrisc:systems:top_earlgrey_nexysvideo \
  --BootRomInitFile="$BOOTROM_VMEM"

cp "$OBJ_DIR/hw/synth-vivado/lowrisc_systems_top_earlgrey_nexysvideo_0.1.bit" \
  "$BIN_DIR/hw/top_earlgrey"
```

toolchain.config:
```
[binaries]
c = '/usr/bin/riscv32-unknown-elf-gcc'
cpp = '/usr/bin/riscv32-unknown-elf-g++'
ar = '/usr/bin/riscv32-unknown-elf-ar'
ld = '/usr/bin/riscv32-unknown-elf-ld'
objdump = '/usr/bin/riscv32-unknown-elf-objdump'
objcopy = '/usr/bin/riscv32-unknown-elf-objcopy'
strip = '/usr/bin/riscv32-unknown-elf-strip'
as = '/usr/bin/riscv32-unknown-elf-as'

[properties]
needs_exe_wrapper = true
has_function_printf = false
c_args = ['-march=rv32imc', '-mabi=ilp32', '-mcmodel=medany', '-fno-stack-protector']
c_link_args = ['-march=rv32imc', '-mabi=ilp32', '-mcmodel=medany', '-fno-stack-protector']
cpp_args = ['-march=rv32imc', '-mabi=ilp32', '-mcmodel=medany', '-fno-stack-protector']
cpp_link_args = ['-march=rv32imc', '-mabi=ilp32', '-mcmodel=medany', '-fno-stack-protector']

[host_machine]
system = 'bare metal'
cpu_family = 'riscv32'
cpu = 'ibex'
endian = 'little'
```

Turns out, not using the reduce script seems to have fixed my issue! I was able to boot Tock perfectly fine with this generated bitstream.

As this is not a commit at HEAD, I can't say if the reduce script has problems there, so I don't know if there is any value to leaving this issue open. Looks like #4731 needs to be resolved before I can test with the reduce script on master.

**Comment by imphil** [comment]
Great that you got it working. To reduce your confusion a bit:

- `opentitan_earlgrey_flash_size_reduce.py` is a script that was used in previous versions of OpenTitan for CW305 boards; it's not designed for the Nexys Video board and not needed there. In the version you're using, you shouldn't use any reduce script, the normal build works fine on Nexys Video.
- On OpenTitan master you need to use `/hw/top_earlgrey/util/top_earlgrey_reduce.py` currently to create a bitstream that fits on the Nexys video board.
- The linker problem you're seeing ("Using an executable file (sw/otbn/libbarrett384.a(barrett384.rv32embed.o)) as input to a link is deprecated - support is likely to be removed in the future") is completely unrelated and due to a change in behavior of binutils. It's worked around in master (https://github.com/lowRISC/opentitan/issues/5021)
