### ISSUE TITLE
[top] Audit clock groups

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#5305]
In #5278 it has been noted that we should think about auditing clock groups after synthesis. Since the implementation is currently changing at fast pace, we decided to just abort synthesis (FPGA) if clock constraints cannot be applied. But eventually, we should maybe do timing reports and check that all specified clock groups are actually generated and visible in the implementation.

This topic came up in the context of the FPGA emulation but it's maybe also be relevant for the ASIC target.

**Comment by vogelpi** [comment]
FYI @msfschaffner, I don't think we should do this right now as the design still changes regularly. But we might consider it once everything is more stable.

**Comment by msfschaffner** [comment]
Yes this is a good point. But as you say I think at the moment things are still too much in flow.
Let's revisit this once the design has become more stable.

**Comment by tjaychen** [comment]
Changing to task to indicate this is a P0 item that should be done prior to gold.

**Comment by msfschaffner** [comment]
Action items from the review:
- [ ] Move `clk_i` to the `powerup` clock in `rstmgr`
https://github.com/lowRISC/opentitan/blob/7d941705c42a8bec8f360f5468dd08e28a07d740/hw/top_earlgrey/data/top_earlgrey.hjson#L385-L388
- [ ] Move `pwm` to the `peri` clock group
https://github.com/lowRISC/opentitan/blob/7d941705c42a8bec8f360f5468dd08e28a07d740/hw/top_earlgrey/data/top_earlgrey.hjson#L466
- [ ] Move `sysrst_ctrl` to `secure` clock group
https://github.com/lowRISC/opentitan/blob/7d941705c42a8bec8f360f5468dd08e28a07d740/hw/top_earlgrey/data/top_earlgrey.hjson#L450
- [ ]

**Comment by msfschaffner** [comment]
https://github.com/lowRISC/opentitan/pull/14958 has been merged. @jeoongp is there anything left to do here?

**Comment by jeoongp** [comment]
The connectivity test was not an actual run in #14985. The fix will be merged in #15183.

**Comment by moidx** [comment]
Lowering priority as the changes are under review.

**Comment by tjaychen** [comment]
actually this has already been merged as part of #14958 , i will close for now.

**Comment by jeoongp** [comment]
The connectivity errors were fixed and merged in #15183.
