### ISSUE TITLE
Doc builder failing

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#5306]
The documentation build on master is currently broken, which runs in GCP somewhere. Until that is fixed, no updated documentation will be visible on docs.opentitan.org

It seems like the documentation builder in GCP doesn't install all required Python packages from python-requirements.txt, since it first failed after adding a libcst requirement.

![image](https://user-images.githubusercontent.com/1467123/108488270-1520d200-7298-11eb-8ee7-9c0cf52087ea.png)

@gkelly can you have a look?

**Comment by gkelly** [comment]
Hmm, this is actually because it's trying to find DIF functions inside of something that doesn't have DIF functions.

```
ERROR: No DIF functions found for sw/device/lib/dif/dif_warn_unused_result.h
INFO: Generated DIF Listing for sw/device/lib/dif/dif_warn_unused_result.h
Traceback (most recent call last):
  File "/workspace/hw/ip/otbn/util/yaml_to_doc.py", line 18, in <module>
    from docs.get_impl import read_implementation
  File "/workspace/hw/ip/otbn/util/docs/get_impl.py", line 7, in <module>
    import libcst as cst
ModuleNotFoundError: No module named 'libcst'
Traceback (most recent call last):
  File "./util/build_docs.py", line 477, in <module>
    main()
  File "./util/build_docs.py", line 454, in main
    generate_otbn_isa()
  File "./util/build_docs.py", line 338, in generate_otbn_isa
    check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
```

**Comment by gkelly** [comment]
Taking a look now.

**Comment by imphil** [comment]
I would be surprised if "No module named 'libcst'" wasn't the root cause.

**Comment by gkelly** [comment]
Haha, same. In the C++ logger errors are usually fatal, but not so here.

**Comment by gkelly** [comment]
Ran the `deploy_builder.sh` script and then re-ran the latest failure in the GCB console which passed. https://console.cloud.google.com/cloud-build/builds;region=global/90394c87-4449-4b0e-b59c-ec3dc0684d3b?authuser=1&project=active-premise-257318

**Comment by imphil** [comment]
It's working again, thanks @gkelly!
