### ISSUE TITLE
[comportable] Recommends Error Code across the IPs

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#531]
As same as interrupt register (generated by reggen), let reggen creates Error Code register which introduces Error FIFO (or just 1 depth error cause) across the IPs. Each IP can have error code register and one interrupt line connects to the `!fifo_empty` signal (or edge of the signal).

I will fill out the rest later with more details.

**Comment by rswarbrick** [comment]
@eunchan: Is this feature still planned? It sounds like it's probably subsumed by the alert manager?

**Comment by eunchan** [comment]
> @eunchan: Is this feature still planned? It sounds like it's probably subsumed by the alert manager?

The error code somewhat differs from the alert. Each alert has its own dedicated alert line and severity. The error code has one interrupt line (consolidated all error interrupts) and the error code has not only what error occurs, but also useful information, internal states for SW to handle the error. It is up to the IP designer which information should be reported together (up to 24bit as of now).

**Comment by rswarbrick** [comment]
Oh, I see. Which IPs currently use this? I know we've done something custom (but basically the same) for OTBN: maybe we should be fitting into an existing framework.

**Comment by eunchan** [comment]
HMAC, KMAC and maybe flash_ctrl?

**Comment by tjaychen** [comment]
There is a [proposal](https://docs.google.com/presentation/d/1_TjfPF2zWtUHb2IC-C2USyK7jH5u7YgnbOex_GCk7ds/edit?usp=sharing) written that we should revisit when time permits.

**Comment by tjaychen** [comment]
duplicated by #7901
