### ISSUE TITLE
[sram] Document execute from sram scheme

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#5317]
Convert the following drawing into an actual description somewhere
https://docs.google.com/drawings/d/1N_zpxu9T4pj_Mf0mz2y2Qa94F6EeS_-Xw8RVbQyMoTc/edit?usp=sharing

**Comment by msfschaffner** [comment]
This has been added to the `sram_ctrl` docs now: https://docs.opentitan.org/hw/ip/sram_ctrl/doc/index.html#code-execution-from-sram
