### ISSUE TITLE
Enable debug access

### ISSUE THREAD

**Issue by towoe** [lowRISC/opentitan#5332]
Right now the life cycle controller disables the core debug access per default.
For the development stage it should be easy to activate the debug access again.
This might be possible with the correct initialization of LC per boot ROM.
Or, if all the TAPs are connected, this could also be done with an OpenOCD routine.

**Comment by imphil** [comment]
@msfschaffner @tjaychen @gkelly 

Currently it is impossible to connect to an OpenTitan design with OpenOCD/GDB. We need to find a solution that gives us debug access for the development that's happening currently.

**Comment by tjaychen** [comment]
ah... this might have been my doing when i connected the execute from sram function. 
Indeed, until the OTP backdoor-ing at top level with verilator / fpga is ready to go, it's probably best to hard-tie the value going into rv_dm.  I can do that.  

Thanks for catching this.

**Comment by msfschaffner** [comment]
Ah sorry about that.
We are still working on the OTP backdoor loading mechanism that will allow us to preload the OTP with the correct life cycle state.
For Verilator/FPGA we are likely always going to preload in DEV life cycle state, where the RV TAP will be accessible.

**Comment by msfschaffner** [comment]
Related: https://github.com/lowRISC/opentitan/issues/3920

**Comment by msfschaffner** [comment]
The backdoor loading mechanism for OTP has been implemented for all tool flows, and the debug enable signal has been connected again. So this issue can now be closed.
