### ISSUE TITLE
[otbn] improve P-256 assembly

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#5334]
There are some minor improvements we can do on the [P-256 code.](https://github.com/lowRISC/opentitan/blob/master/sw/otbn/code-snippets/p256.s) At least:
* [x] include the call to the [init](https://github.com/lowRISC/opentitan/blob/254cf26b9f1b782fe58addb9084a638fc09d9bb2/sw/otbn/code-snippets/p256.s#L97) routine in the individual subroutines
* [x] some simplifications (remove some unnecessary pointer loading)
* [x] load constants from dmem (we have some constants in the instructions stream which are moved to Dmem and then read back, those should be moved to the .data section in the first place)

> estimate 4
> remaining 2021-05-17 0

**Comment by imphil** [comment]
Fixed through #6576
