### ISSUE TITLE
[otp_ctrl] Should otp_error interrupt be sticky?

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#5350]
Hi Micheal,

I would like to confirm with you that the otp_ctrl's otp_error interrupt is intended to be sticky.

So here is my sequence:
1). Use dai access to read a HW locked partition
2). Check intr pin, otp_error is high
3). Try clear interrupt pin by writing `2'b11` to `intr_state` register.. One cycle after, otp_error pin is still high
4). Use dai access to do a correct read (no error)
5). Check intr pin, otp_error is still high
6). Try clear interrupt pin by writing `2'b11` to `intr_state` register, otp_error pin reset to 0

There is NO logic issue if your intention is to make the interrupt sticky. I just thought would be good to double check with you, because in step 5). I think it is a little bit confusing when I see `otp_err` interrupt pin is high but there is no error :)

![image](https://user-images.githubusercontent.com/11466553/108793129-b24d6600-7537-11eb-86ed-190d22abe5eb.png)

**Comment by msfschaffner** [comment]
Hi @cindychip, this is a good point. 
I think interrupts should not be sticky, even in the case of fatal errors since the SW does likely not expect them to be sticky.
I made a modification to that piece of logic that should hopefully fix this.
