### ISSUE TITLE
[sw, secure_boot] Secure Boot integration: on-device tests

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#5353]
# Introduction

The production chip will run Secure Boot, which means that all the on-device tests should be run via **Mask ROM -> ROM_EXT -> test** chain. At this point all the on-device tests use "legacy" boot rom in `sw/device/boot_rom` and "legacy" flash loader in `sw/device/exts`.

The end goal is to shift completely from the "legacy" execution chain to Secure Boot. This issue outlines several paths to this goal.

# Solution 1 - Gradual transition

Gradual transition without disrupting current CI and development flow. The main idea is to create redundancy - all of the existing tests would run as normal. But with minimal effort we "piggy-back" the Secure Boot tests onto existing framework. The example of this approach can be found in #5352 .

This approach doesn't require additional step in Azure Pipelines, both test sets will be executed in the same step.

**Upsides:**
- Gradual and non-invasive

**Downsides (Please not that eventually these downsides are expected to disappear - with the final switch):**
- Redundancy
- Longer CI execution times

# Solution 2 - full transition

Full transition from running tests on the "legacy" `boot_rom` to Secure Boot.

**Upsides:**
- Done in one go
- No redundancy
- Similar CI execution times

**Downsides:**
- More to consider
- More disruptive
- Harder to pinpoint issues
- One big PR

# Additional comments 

This issue is intended as conversation starter, any comments and suggestions are very welcome.

# Open questions
- Should we have a stripped down version of Mask ROM and ROM_EXT for some testing?
- ...

**Comment by imphil** [comment]
> The production chip will run Secure Boot, which means that all the on-device tests should be run via Mask ROM -> ROM_EXT -> test chain.

I question that assumption, at least in that generality. I see two types of tests:

1. Applications that will run on OpenTitan "production" and/or use multiple subsystems that need to be properly initialized.
2. Low-level unit or smoke tests (e.g. the DIF smoke tests), typically using a single IP block.

Tests of the first category benefit from running them in a "close to production" environment, i.e. after the full ROM/ROM_EXT has completed.

Tests of the second category are meant to test low-level hardware interaction. They are often run in HW development environments to smoke-test the software interface and the hardware block itself. There I mainly value test execution time and a high signal-to-noise ratio: I want to focus on the test code itself, not debug a potentially huge framework around it.

So what's the story on "time to test" with the mask rom-based approach? How many cycles do we need to execute in the bootloader before we reach the test itself?

**Comment by silvestrst** [comment]
> So what's the story on "time to test" with the mask rom-based approach? How many cycles do we need to execute in the bootloader before we reach the test itself?

That is a good question. The honest answer is that - at the moment we don't know.

Also, I am not sure that the sequence of how we test the DIFs, etc... is optimal - as some of the DIFs are used inside the boot_rom or Mask ROM, before the tests are run.

**Comment by alphan** [comment]
Thanks for creating this issue @silvestrst. I think how we transition to the new Mask ROM code and which Mask ROM code we use for tests are somewhat orthogonal:

**Lean Mask ROM for focused tests**: I didn't see this in the meeting notes but IIRC we mentioned that we should probably have a lean version of the Mask ROM (similar to what we have right now) for smoke-tests and DV as @imphil points out (for better test execution time and less noise). The thing is, since we don't have this distinction right now, we can keep using the current code for most of the tests until we have a plan for the lean version. But when we are ready, that transition should probably be gradual.

> So what's the story on "time to test" with the mask rom-based approach? How many cycles do we need to execute in the bootloader before we reach the test itself?

We don't have a number yet but I think it is safe to assume that it won't be negligible due to signature verification.

**Transition**: IMHO we should handle this gradually as you captured in the first bullet, i.e. 
* keep implementing the new Mask ROM code (along unit-tests that run on the host),
* add necessary tests to the CI (in a run-but-ignore fashion initially),
* announce the change,
* swap the new and old code, and
* remove the old one after we are confident.

**Comment by silvestrst** [comment]
So what do you guys think of the #5352 approach?

**Comment by silvestrst** [comment]
@alphan am I understanding correctly that you are suggesting we start gradually switching to Mask ROM based on-device testing once we have this "lightweight Mask ROM" for testing?

But in general, what are you thoughts on dupping testing for CI purposes and gradually adding different testing bits to Mask ROM, like in #5352?

**Comment by asb** [comment]
For me, the questions are:
Looking ahead, do we want smoke tests be booted by the 'full' mask ROM? => Consensus is that even if we did support this, we'd want a stripped down mask ROM too. Is there any value at all in having these tests loaded via the mask ROM? Is "run all existing smoke tests via the mask ROM" itself intended as a mask ROM smoke test?

**Comment by silvestrst** [comment]
> Is there any value at all in having these tests loaded via the mask ROM?

Well, my rationale is following - the production code will be Mask ROM, so we should run any on-device tests that add to the coverage via Mask ROM. Practically there probably is not too much difference, but it is better to be safe than sorry.

**Comment by silvestrst** [comment]
#5516 adds a single MaskROM + ROM_EXT smoke test for now - the expectation is that we eventually would add all the rest. The versions of MaskROM and ROM_EXT will be "lightweight" - excluding things like signature verification, etc...

**Comment by silvestrst** [comment]
@mundaym can this be closed?

**Comment by mundaym** [comment]
Yes I think so.
