### ISSUE TITLE
[keymgr] one-hot command for fault attack

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#5363]
@tjaychen 
the way we coded the command selects are all combination logic. There is no such storage unit like reg, which we can flip to trigger this error. In sim, I can force the wires, but I wonder if fault attack can flip a wire.

```
  assign enables = {adv_en_i, id_en_i, gen_en_i};
  assign enables_sub = enables - 1'b1;
  // command error occurs if kmac errors or if the command itself is invalid
  assign cmd_error_o = |(enables & enables_sub);
```

```
  assign advance_sel    = op_start_i & op_i == OpAdvance  & en_i;
  assign gen_id_sel     = op_start_i & op_i == OpGenId    & en_i;
  assign gen_out_sw_sel = op_start_i & op_i == OpGenSwOut & en_i;
  assign gen_out_hw_sel = op_start_i & op_i == OpGenHwOut & en_i;
```

if it can happens, this error can only be caught when the non-one-hot command lasts until end of KDF (kmac sends back done)
In this waveform, this error occurs for one cycle at the middle of an operation, which it doesn't trigger any error.
/edascratch/weicai-opentitan/ot/km_fatal_err/keymgr-sim-vcs/0.keymgr_cmd_invalid/out

The FSM error may be more meaningful. It has storage unit and when it's flipped to unsupported value, the fault error is triggered immediately. This is the wave for FSM error.
/edascratch/weicai-opentitan/ot/force_fsm/keymgr-sim-vcs/0.keymgr_cmd_invalid/out

WDYT? Thanks

**Comment by tjaychen** [comment]
ah good catch. I should probably latch the enables error any time it happens instead of doing what i do now.

**Comment by weicaiyang** [comment]
> ah good catch. I should probably latch the enables error any time it happens instead of doing what i do now.

that sounds better. thanks
