### ISSUE TITLE
[dif/spi_device] To get SRAM size from parameter

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#5369]
as discussed in #5145 and implemented in #5264, SPI_DEVICE HWIP now defines SRAM size in the module parameter. This issue is to follow up the change in the software (DIF). Currently, SRAM size in dif_spi_device is hard-coded. It will be more flexible if dif also use the parameter.

CC: @tjaychen

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. Labeling https://github.com/lowRISC/opentitan/labels/Type%3AIcebox as I think this is relevant for this release but not for the next milestone (M2.5).

**Comment by a-will** [comment]
Confirmation can come later, but it looks like this might specifically refer to `kFifoPhaseMask` and `kFifoPhaseOffset` in the DIFs.

**Comment by a-will** [comment]
Generic mode is to be removed, so the original intention no longer applies. However, it might be useful to have the breakdown of flash mode parts and their offsets come from regtool-generated params.
