### ISSUE TITLE
[rv_dm] Get D1 sign-off

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#5371]
Get D1 sign-off on rv_dm.

* [ ] Go through all open issues to check if we have got all required functionality implemented.
* [ ] Go through the checklist at https://docs.opentitan.org/doc/project/checklist/index.html#d1

(Slightly changing gears here, rv_dm isn't even at D1 yet, which needs to come first.)

**Comment by tjaychen** [comment]
given that rv_dm is already d2 signed off..it's fair to say this issue is stale...
