### ISSUE TITLE
[fpga] Switch top_earlgrey to new FPGA board "NEWFPGAv1"

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#5388]
We need to switch to a newer FPGA board to provide enough space for the OpenTitan top_earlgrey design, replacing top_earlgrey_nexysvideo with top_earlgery_newfpgav1.

The existing Nexys Video code needs to move to another toplevel, see https://github.com/lowRISC/opentitan/issues/5396, as the design is too large to fit the Nexys Video board.

@msfschaffner @dsandrs Do we have the specs (FPGA type, pinout, etc.) for this board yet? Even if we don't have the board we can already start the process by looking at the spec only.

**Comment by msfschaffner** [comment]
Hey Philipp, we know the FPGA type (XC7K410T-1FBG676C), but the board specs and pinout are still in flux.

For the time being  I suggest just to rename `top_earlgrey_nexysvideo`, switch the FPGA type, but leave everything else as is (this should work for the synthesis check). 
We could however increase the system frequency again.

CC: @tjaychen

**Comment by imphil** [comment]
Just a quick note on timing: we can make this switch today, but it would mean we effectively give up even synthesis testing on top_earlgrey, and would be left with no working FPGA platform.

* Until we have a commercial Vivado license available and installed we cannot even synthesize for the given FPGA. @asb is working on it.
* Switching top_earlgrey to another FPGA without having the corresponding board available, and without having another toplevel that supports the Nexys Video board means effectively we give up all FPGA testing, which also includes testing of spiflash and some software tests which we only run on FPGA at the moment for time reasons (e.g. the OTBN software tests).

So if we have to switch today, it'll be just disabling the FPGA builds altogether, which is very easy to do. Please ping me when the first PRs break due to FPGA over-utilization and I'll do that.

However, I really want to delay doing that until the very last minute since disabling FPGA synthesis and tests would be a rather large quality regression. I'm trying to get another toplevel which supports Nexys Video ready first, but no guarantees (tracked in #5397).

**Comment by msfschaffner** [comment]
Thanks @imphil, 

I agree that we should only take FPGA CI out if there is no other way. 
If needed, I can also temporarily stub some unused things in the NexysVideo top-level to buy us some more time.

If we can get another toplevel up and running for NexysVideo, and a synthesis-only regression for the target device, that would however be great!

**Comment by vogelpi** [comment]
@imphil , should we close this issue? It seems that this has been addressed in #6614 .
