### ISSUE TITLE
[otbn] Error prioritisation proposal

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#5445]
I've gone through all 256 error bit combinations and come up with some rules which are below. I've written these up in a formal style and we'll likely want something like this in the documentation but as there's areas of discussion around RTL microarchitecture, levels of detail required for the ISS etc I felt this was better off all in an issue for discussion. Once we're agreed a form of this can be put into the documentation.

I do have a spreadsheet giving the explicit result for all the different combiantions but it's a bit of a mess as I kept changing my mind on how to handle things! I'd be happy to produce a clean version based on the agreed rules if we think it is useful.

Where errors occur together there shall be situations where the presense of one error will suppress the reporting of another error. This is done where the presense of the suppressed error (were it not suppressed) is dependent on some undefined data (e.g. what's on an empty call stack) on some complex condition (if an empty call stack is popped as store data, the store address is still valid so bad_data_addr could be a valid error, but if it's popped as the store address base bad_data_addr cannot be a valid error, we just suppress bad_data_addr always for simplicity).

When any of the fatal_X errors occur all other errors are simply suppressed.  There may be some reasonable combinations where this is not required but it is not thought these provide much in the way of useful information so simplicity is preferred.

There are some error combinations that CANNOT OCCUR. These are combinations that could only happen if there was a bug or an induced fault but ignoring the fatal_X errors. If an error combination that CANNOT OCCUR would be produced the fatal_X bits are kept and all other bits are set to 0. A new fatal_bad_err bit is set triggering a corresponding alert.

Error suppression rules are given below, for each error that can suppress other errors it lists what that error suppresses.

call_stack
----------
If an error on pop, suppresses:
  - bad_data_addr (pop may have supplied address)
  - bad_insn_addr (pop may have supplied target or conditonal branch operands)
  - loop

Does not suppress anything if there is an error on push. Note that no loop instruction pushes to the call stack so the call_stack error always suppresses the loop error.

illegal_insn
------------
Suppresses all non fatal_X errors:
  - bad_data_addr
  - bad_insn_addr
  - call_stack
  - loop
 
If there is an illegal instruction some bits may or may not decode into things that could cause the RTL to observe another error but the instruction won't be executed so those errors are suppressed.  

CANNOT OCCUR combinations
-------------------------
  - loop & bad_data_addr (loop cannot load/store data)
  - call_stack (on push) & bad_data_addr (load or couldn't happen so no call stack push)
 
Anything that includes of those combinations CANNOT OCCUR, excepting combinations contains illegal_insn (as the instruction decode may do undefined things result in in normally CANNOT OCCUR combinations of errors).

We could call some combinations involving fatal_X codes CANNOT OCCUR, e.g.  fatal_dmem & fatal_imem, with fatal_imem no instruction to cause a load should be executed so there should be no fatal_dmem but given these are already raising alerts I'm not sure there's much value in making them CANNOT OCCUR combinations.

Note that in cases where one error gets suppressed by another that doesn't indicate the action related to the suppressed error would have, or is, occurring.  The logic controlling the actual excution is divorced from the error detection.  E.g. on a call_stack error we suppress the bad_data_addr a load might produce.  The bits from an invalid call stack entry get fed into the logic that calculates an address and determines if it is invalid. The raw bad_data_addr gets signalled if the calculated address is invalid and a load or store instruction is in the decode stage, actual execution would always be suppressed regardless of supression rules. The CANNOT OCCUR combinations fall out of such scenarios where the raw error signalling could only happen if there was a logical bug.

Error bit definitions are found here: https://docs.opentitan.org/hw/ip/otbn/doc/#Reg_err_bits

**Comment by cdgori** [comment]
I thought about your rules for call_stack and illegal_insn - these seem correct to me.

Did you propose to take some action for CANNOT_OCCUR combinations?  Or apply some filtering/suppression?  (It wasn't clear to me from what you wrote.)

**Comment by tjaychen** [comment]
quick question, the text above says no loop instruction pushes to the call stack, so shouldn't that also become a "cannot occur" error?

In the error bits description, bad_insn_addr can be caused by a store to imem, is that possible from otbn's perspective? Or does this include ibex writes?

**Comment by GregAC** [comment]
> Did you propose to take some action for CANNOT_OCCUR combinations? Or apply some filtering/suppression? (It wasn't clear to me from what you wrote.)

I was proposing a CANNOT_OCCUR becomes a new fatal_X err which triggers a fatal alert (like the alerts for integrity check failure on imem/dmem/reg)

> quick question, the text above says no loop instruction pushes to the call stack, so shouldn't that also become a "cannot occur" error?

The call_stack error isn't separated into push and pop categories (both errors would set the same bit) so in terms of what can happen in the RTL you could see the raw call_stack and loop errors signaled together and that doesn't signify a bug.

> In the error bits description, bad_insn_addr can be caused by a store to imem, is that possible from otbn's perspective? Or does this include ibex writes?

That should be read only as it's from OTBN's perspective think this is just a typo. The only errors you can see in the OTBN error bits that might relate to Ibex activity are the fatal_imem and fatal_dmem ones.

**Comment by cdgori** [comment]
SGTM re: CANNOT_OCCUR

**Comment by GregAC** [comment]
This has been superseded by other spec work.
