### ISSUE TITLE
[dft] - Remove output scan mux from prim_clk_div

### ISSUE THREAD

**Issue by arnonsha** [lowRISC/opentitan#5453]
The prim clock divider contains a scan mux. Currently clk_o = clk_i during scan.
This is bad practice since all at-speed checks should be performed with the functional clk frequency.
DC adds OCC at the divider's output to switch between the functional clock (capture) and the slow ATE clock (shift), so the mux can be removed.

**Comment by tjaychen** [comment]
this issue should be fixed. Please re-open if you still see problems (or open a new one).
