### ISSUE TITLE
[entropy_src,csrng,edn] Implement DIFs

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#5465]
Now that we have multiple devices connected to the entropy complex (entropy_src, csrng, edn), we should look into writing DIFs for these IPs, see also https://github.com/lowRISC/opentitan/pull/5427#pullrequestreview-603979681.

FYI @martin-lueker @mwbranstad @gkelly @asb @moidx

**Comment by moidx** [comment]
Cross-linking: 

- entropy_src (lowrisc/opentitan#5187)
- csrng: (lowrisc/opentitan#5581 (draft))
- edn: (wip)

**Comment by alphan** [comment]
I was about to create an issue for stopping EDN during SCA but found this issue. The header added in #5581 already declares `dif_edn_stop()` which seems to be what we need. Once it is implemented, writes to EDN registers in `sca.c:sca_disable_peripherals()` can be replaced with this function. See this [comment](https://github.com/lowRISC/opentitan/pull/7757#discussion_r690584186) in #7757.

**Comment by alphan** [comment]
Also created #7837 for `dif_csrng_stop()`.
