### ISSUE TITLE
[rv_core_ibex] Hookup into alert handler system

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#5478]
Due to integrity checks both inside and outside of ibex, it is possible for rv_core_ibex now to have alertable error conditions.
There needs to be a way to hook-up these alerts into the alert_handler network.  The alert handler network at the moment only handles peripherals, this should be enhanced to handle hosts as well. 

There is a "host" data structure in `top_earlgrey.hjson`, so that is probably a reasonable place to start.

**Comment by tjaychen** [comment]
During a quick discussion on this today it was determined that instead of doing all the work to template `rv_core_ibex`, it would be better to create an "rv_core_ibex" device module.  The events would connect from the host module to device module, and then from the device module to the alert handler.

This would also give us an easy way to handle #5896 without changing anything in the alert handler.
The configuration for #5947 could also be added and fed back to the host module. 

@imphil 
@rswarbrick

**Comment by msfschaffner** [comment]
Update: An `rv_core_ibex` peripheral as discussed above has been added in https://github.com/lowRISC/opentitan/pull/7128.

Note: It has in the mean time become possible to have modules with TL-UL device and host plugs. 
Hence we plan to make ibex a fully comportable module, and absorb the functionality that has been added as part of the `rv_core_ibex` peripheral mentioned above. This is tracked separately in https://github.com/lowRISC/opentitan/issues/7212.

@tjaychen do you want to keep this issue open, or can we close it?

**Comment by tjaychen** [comment]
let's close it for now. The ibex as a peripheral will come separately.
