### ISSUE TITLE
[top, edn] Group entropy consumers and re-assign to EDNs according to entropy quality

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#5487]
Currently, the different entropy consumer devices are arbitrarily connected to the two EDN instances. Once the entropy story is more finalized we should group the various endpoint devices according to the required entropy quality and connect one group to EDN0 and a second group requiring higher-quality entropy to EDN1 (as discussed in the security meeting on March 4).

See for example below diagram:
![entropy_complex](https://user-images.githubusercontent.com/20307557/110208615-8c558900-7e88-11eb-8384-72276cbf8749.png)

The number of endpoint ports per EDN is a design parameter (currently set to 4). Some work might be required in topgen to support than 4 endpoints or a different number of endpoints per EDN.

**Comment by tjaychen** [comment]
thanks for filing the issue @vogelpi

**Comment by vogelpi** [comment]
Thanks @tjaychen for taking and solving this issue :+1:
