### ISSUE TITLE
[otbn] Increase IMEM and DMEM width

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#5494]
Increase imem width to ~40 bit~ 39 bit.

Increase dmem width to ~8*40 = 320 bit~ 8*39 = 312 bit

@msfschaffner are these the widths we should be using, or is 32 -> 39 bit the right width for SRAMs?

**Comment by tjaychen** [comment]
the one where we have the 40b restriction is ROM only, so 39b is the right width for SRAMs

**Comment by msfschaffner** [comment]
Yes I have prepared a 39bit wide SRAM for IMEM, and a 312bit wide configuration for DMEM.

**Comment by GregAC** [comment]
This was completed with #5547
