### ISSUE TITLE
[hw/tlul] Create generic module for re-order buffer to support out-of-order responses

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#55]
as @NilsGraf mentioned in lowRISC/stwg-base#474 `a_source` should be unique. If a host wants to send multiple requests, it needs to handle out-of-order responses. It looks like `{a|c}_source` may consider NoC case but it introduces a little bit of complex in a simple interconnect like the one in OpenTitan.

It is planned to implement DMA module later, so we should prepare the general logic to handle out-of-order response. 

Idea is: to have general re-order buffer under tlul. It is parameterized ( #ofOutstandings ). Internal interface should be similar to the tilelink but `a_source` can be ignored. The re-order buffer will take care of it (assigning new tag(source id) and releasing it). 

@taoliug @sriyerg could you please check if current tlul_agent uses arbitrary `a_source` value for each request?

**Comment by sjgitty** [comment]
@eunchan any update in the thinking on this one?

**Comment by eunchan** [comment]
Thanks for the brought up this issue (buried deeply long long ago). This module, re-order buffer isn't necessary in OT design yet. If we have to adopt TL IPs into OT, reorder buffer will be needed.

We can close this issue for now and re-open when it is needed.
