### ISSUE TITLE
Building binaries without instruction compression

### ISSUE THREAD

**Issue by galsanka** [lowRISC/opentitan#5509]
Hello all,

I have been trying to build OpenTitan software from C sources using this tutorial: https://docs.opentitan.org/doc/ug/getting_started_sw/. 

I want to generate the binaries without instruction compression. I built the riscv toolchain without the C extension (i.e. by [using all the recommended flags except for `--with-arch=rv32im`](https://docs.opentitan.org/doc/ug/install_instructions/#compiler-toolchain) when building). After that, I added and modified the toolchain configuration file to replace the default toolchain with the one I built. I also modified `meson-init.sh` to point to that configuration file.

Unfortunately, the build's compiler settings only change after adding the -f flag to `./meson-init.sh -r`, which removes the previously working binaries built with the original working compiler. I don't want to happen, because compiling all the other binaries without compression doesn't work.

So my question is: **is there a way to compile new c binaries without compressed instructions while keeping the original working binaries (e.g. boot_rom) for the rest of the system?** Meson is not cooperating and only changes after deleting all other working files, even after adding an -r flag to reconfigure. Should I just compile them using my own build system instead of relying on OpenTitan's?

Thank you,
Georges

**Comment by imphil** [comment]
@silvestrst

**Comment by silvestrst** [comment]
Hi Georges,

Thank you for your question.

Am I understanding it correctly that you are trying to selectively compile
some of the binaries without the `C` extension, whilst keeping all the rest
built with the provided toolchain?

If my above conclusion is correct, then I think that the project as is
doesn't support this option. Moreover I think meason doesn't support mixing
and matching of different toolchains - you can have "build" (usually x86
machine), host (rv32xx). There is this meason merged PR
<https://github.com/mesonbuild/meson/pull/5083> that allows to overlay
cross files, but I have never tried it, and not sure whether it allows to
override toolchain completely or just some options.

A non ideal alternative
<https://github.com/mesonbuild/meson/issues/5125#issuecomment-474990932> -
the use-case is slightly different, here someone needs to build for N
targets at the same time.

I think I would look into the "--cross-file" overlay, if that is not
helpful, then you would need to have a custom solution for your problem.

@Luís Marques <luismarques@lowrisc.org>
Adding Luis who has worked on the toolchains infrastructure for OpenTitan,
just to double-check the above.

P.S.
Please let us know if you have further questions, and also it would be
interesting to know what you went for in the end.

Regards,
Silvestrs

**Comment by silvestrst** [comment]
Hi Georges,

I don't see why this would be an issue?

Have you tried building without instruction compression and encountered any
issues?

Thanks,
Silvestrs

**Comment by imphil** [comment]
Please reopen if this problem persists.
