### ISSUE TITLE
[Question] Temporary work around for FPGA boards without SPI interface

### ISSUE THREAD

**Issue by jackieke724** [lowRISC/opentitan#5514]
I added a customized IP. Due to the size of my IP, I need to switch to VC707, but this board does not seem to have any compatible SPI interface. I also tried to use FMC to access the IOs on Genesys2, but the FMC pins on VC707 cannot supply the 3.3V required by the DPTI/DSPI interface. All the "large-enough" FPGA boards I looked can only supply 1.8V for their FMC pins.

Is there any work-around to execute my application binary without the SPI interface? The "flash" seems to be implemented with BRAMs, so is it possible to fuse the binary during synthesis?

Thank you!

**Comment by imphil** [comment]
You can remove the SPI device peripheral if you only want to use it to load the memories -- you can do the memory loading through JTAG/OpenOCD as well.

**Comment by jackieke724** [comment]
Thank you @imphil. The JTAG pins on VC707 are dedicated pins, so I think I cannot use them for loading the memories.

**Comment by jackieke724** [comment]
I have found an FMC interface card, [DC2159A](https://www.analog.com/media/en/dsp-documentation/evaluation-kit-manuals/dc2159af.pdf), which has FT2232H, but I am not sure if it can support 1.8V yet. 

If there is neither a JTAG nor SPI interface, can I still load memory?

**Comment by imphil** [comment]
No.

**Comment by jackieke724** [comment]
I think there is no way to drive the DPTI/DSPI interface by the 1.8V FMC, but I have found an FMC carrier card [TSW14J10](https://media.digikey.com/pdf/Data%20Sheets/Texas%20Instruments%20PDFs/TSW14J10.pdf) that I can attach to VC707. It has a FT4232HL USB device onboard. You also mentioned this device in #1008.

**Comment by jackieke724** [comment]
I am trying to use DC2159A (mentioned above) for the JTAG/SPI interface. I have attached it to FMC2 on VC707, but when I ran spiflash with: 
`build-bin/sw/host/spiflash/spiflash --dev-id=0403:6010 --dev-sn=LT1UZH97 --input build-bin/sw/device/examples/hello_world/hello_world_fpga_nexysvideo.bin`, it returns
> Unable to open FTDI SPI interface

Does anyone know if I need to modify `spiflash` or if DC2159A is just not compatible? Thank you!


`lsusb` output:
> Bus 003 Device 013: ID 0403:6010 Future Technology Devices International, Ltd FT2232C Dual USB-UART/FIFO IC
> Device Descriptor:
>   bLength                18
>   bDescriptorType         1
>   bcdUSB               2.00
>   bDeviceClass            0 (Defined at Interface level)
>   bDeviceSubClass         0 
>   bDeviceProtocol         0 
>   bMaxPacketSize0        64
>   idVendor           0x0403 Future Technology Devices International, Ltd
>   idProduct          0x6010 FT2232C Dual USB-UART/FIFO IC
>   bcdDevice            7.00
>   iManufacturer           1 LTC
>   iProduct                2 LTC Communication Interface
>   iSerial                 3 LT1UZH97
>   bNumConfigurations      1

`dmesg` output:
> [ 1309.101908] usb 3-4.1: Product: LTC Communication Interface
> [ 1309.101908] usb 3-4.1: Manufacturer: LTC
> [ 1309.101909] usb 3-4.1: SerialNumber: LT1UZH97
> [ 1309.108760] ftdi_sio 3-4.1:1.0: FTDI USB Serial Device converter detected
> [ 1309.108787] usb 3-4.1: Detected FT2232H
> [ 1309.110447] usb 3-4.1: FTDI USB Serial Device converter now attached to ttyUSB1
> [ 1309.113732] ftdi_sio 3-4.1:1.1: FTDI USB Serial Device converter detected
> [ 1309.113751] usb 3-4.1: Detected FT2232H
> [ 1309.115163] usb 3-4.1: FTDI USB Serial Device converter now attached to ttyUSB2

**Comment by jackieke724** [comment]
Which mode of FT2232H are we using? Currently I have only set the constraints for the ADBUS[7:0] of the FT2232H pins, corresponding to the FMC LA02_P/N, LA04_P/N, LA07_P/N, LA11_P/N pins. To me, that seems to match the configuration on Nexys Video, but it could be that I did not set the pins appropriately.

Are the rest of FT2232 I/O's shown in the [schematic](https://www.analog.com/media/en/dsp-documentation/evaluation-kit-manuals/dc2159af.pdf) (page 4-5) needed?
![image](https://user-images.githubusercontent.com/15860703/112095506-9640f100-8bd7-11eb-8be1-8cd637dfd273.png)

**Comment by jackieke724** [comment]
I figured that I need to run in sudo mode to open the device. Nevertheless, I still cannot send data by SPI or JTAG, which probably means DC2159a does not support 1.8V IO. Could anyone confirm that from the schematic? Is there any other 1.8V-compatible FMC interface card, or PMOD for FT2232H?
