### ISSUE TITLE
[ipgen] Provide a clean way to produce IPs from IP templates

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#5519]
We have a number of IP blocks currently in top_earlgrey which are produced from IP Templates:

- alert_handler
- ast
- clkmgr
- flash_ctrl
- padctrl
- pinmux
- pwrmgr
- rstmgr
- rv_plic
- sensor_ctrl
- xbar
- xbar_main
- xbar_peri

The instantiation of an IP block from a template is currently done within `topgen.py`, and additionally with a script within most of the IP blocks. The variables which can be modified when producing IP blocks from templates are not really documented.

@eunchan has produced a proposal document for a new tool solving this issue called ipgen. The proposal can be found at https://docs.google.com/document/d/1jimqHdR1x8on3jwzsi8SHTdhXFvujHj-EFk-eGU9mX4/edit#.

**Comment by eunchan** [comment]
#4345 is related RFC

**Comment by imphil** [comment]
Now I know why I've heard of the proposal before (and then almost completely forgot about it). Thanks @eunchan

**Comment by imphil** [comment]
Duplicate of #4345
