### ISSUE TITLE
[util] dvsim dry-run and remote

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#5527]
This was encountered while adding a new module to the regression list. 

It seems that when the dry-run option is given, the remote syncing step is skipped.  As a result, the dry-run is performed over either stale data or errors out.  This may be work as intended, but I wanted to clarify what the ideal behavior should be.

**Comment by tjaychen** [comment]
yeah that's fine.  Should we have an error check that catches that case?

**Comment by weicaiyang** [comment]
> My opinion on this is - if you are just doing a dry run, don't pass `--remote` or the `--job-prefix`.

I suggested not to use `--remote` with dry-run yesterday too. But `--job-prefix` should not matter, right?
But if user does `--remote` with dry-run, what should the right behavior be? perhaps we should do remote copy first.

**Comment by sriyerg** [comment]
Fix in #5531. PTAL, thanks for reporting.
