### ISSUE TITLE
[sysrst_ctrl] ULP wakeup feature

### ISSUE THREAD

**Issue by esshiu** [lowRISC/opentitan#5550]
I have one more feature to implement. It's the wakeup circuitry to exit from the ultra-low-power state.

-Eric

**Comment by esshiu** [comment]
Just finished the coding. Waiting for a good time to create the pull request. The team is working on the Silver integration. sysrst_ctrl has two new pins, z3_wakeup and lid_open.

**Comment by tjaychen** [comment]
@tjaychen

**Comment by msfschaffner** [comment]
This has been implemented.
