### ISSUE TITLE
[dv] `BUILD_ROOT=${sw_build_dir}` doesn't work for tcsh

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#5552]
Thanks @snpsverif for finding this issue.

It's fine when we run in bash, but seems like we need to use `setenv BUILD_ROOT ${sw_build_dir}` for tcsh
how can we code this better to support tcsh as well?

https://github.com/lowRISC/opentitan/blob/d20804dfa0f1699919dd8c189561a9ec9078d697/hw/dv/tools/dvsim/sim.mk#L59

@sriyerg @rswarbrick any thoughts?

**Comment by imphil** [comment]
You can simply set the SHELL variable in the makefile to bash to ensure all commands within the makefile are run through bash.
