### ISSUE TITLE
d_data and d_user are unknown in a TL write

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#5573]
@tjaychen 
Do we change to d_data always return the CSR value even it's a write? I didn't really pay attention to what d_data is when it's a write.
We have excluded to read the CSR when it may return unknown value in CSR tests, but now seems like the unknown can be propagated at a write.

![Screen Shot 2021-03-11 at 6 28 02 PM](https://user-images.githubusercontent.com/49293026/110882945-8cde8d00-8297-11eb-94f2-7f08e206232b.png)

/edascratch/weicai-opentitan/ot/HEAD/top_earlgrey_asic-sim-vcs/0.chip_csr_rw/out
verdi -ssr Verdi.ses &

FYI @sriyerg @cindychip

**Comment by tjaychen** [comment]
hmmm i don't think we did anything explicit to do this.
It seems like a side effect of just how the read back path is written, it doesn't check for read enable. 

I think it's probably best to change this behavior.  Are you saying the behavior was different before?

**Comment by weicaiyang** [comment]
> hmmm i don't think we did anything explicit to do this.
> It seems like a side effect of just how the read back path is written, it doesn't check for read enable.
> 
> I think it's probably best to change this behavior. Are you saying the behavior was different before?

@tjaychen 
I'm not sure if it's due to recent change, as I didn't pay too much attention to the d_data for write before. From regression report, only 1-2 cases have the similar failure. Maybe it's because of the behavior of this particular CSR in pinmux.

**Comment by tjaychen** [comment]
there's a simple fix to change the behavior, i can do that.

**Comment by weicaiyang** [comment]
Great, thanks @tjaychen
