### ISSUE TITLE
[csrng] Instantiation of CSRNG in full deterministic mode

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#5580]
Reference doc: https://docs.opentitan.org/hw/ip/csrng/doc/

I am trying to understand how to perform instantiation of CSRNG in full deterministic mode by setting `flag0` to 1 while meeting the `seedlen` requirements specified in SP 800-90Ar1 section 10.2.1.3.

Is CSRNG using the instantiation function without a derivation function as specified in section 10.2.1.3.1? 

If so,  is this interpretation correct `CSRNG.command.clen = seedlen = 384`?

With the assumption that software is pre-processing the input additional data as follows:

 `seed_material = entropy_input ^ personalization_string`.

**Comment by martin-lueker** [comment]
Hi Miguel,
   That is correct, we are not using a derivation function.  Furthermore the personalization string can be used this way, but it is optional.   @mwbranstad, would probably be the best authority on the software options here.

**Comment by mwbranstad** [comment]
Hi Miguel, as Martin says, true about the DF - not using this mode.
For the CSRNG command, it sounds like you want to set up a instantiate command with your own seed (seed_material equation above). If that is the case, I would set the clen to 12 (384 bits/32b bus). Setting flag0=1 and clen= 12 will give you a fully deterministic set of entropy being returned. If I misinterpreted any of your comments, let me know. Thanks.

**Comment by moidx** [comment]
Thanks @mwbranstad  and @martin-lueker! Sounds good. I will leave this issue open until this details incorporated into the DIF.

**Comment by mwbranstad** [comment]
Following up on this issue post-V2 review. All the comments are still accurate. Unless there is still some confusion, I think we can close this issue. This function has been tested since this issue was written, so more reason to close.
@moidx please confirm no issues here and close if that is the case. thanks.

**Comment by moidx** [comment]
This is now available in the DIF.
