### ISSUE TITLE
[sw/mask_rom] Device measurements for ROM_EXT image signature

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#5585]
It looks like we have an agreement on how to use device measurements when generating and verifying the signature of a ROM_EXT image (as a prefix according to [ROM_EXT Manifest Format][1]). We need to finalize this set of measurements and update ROM_EXT tooling and signature verification module.

[1]: https://docs.opentitan.org/sw/device/silicon_creator/rom_ext/docs/manifest/index.html

**Comment by alphan** [comment]
@silvestrst @asb for visibility.

**Comment by moidx** [comment]
Closing as obsolete.
