### ISSUE TITLE
[sw/dif_pwrmgr] Add smoke tests for dif_pwrmgr

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#5592]
Creating this issue based on @tjaychen's [comment](https://github.com/lowRISC/opentitan/pull/5553#issuecomment-797669304) in lowRISC/openTitan#5553.

I created a draft PR (lowRISC/opentitan#5591) with some boilerplate code that may save you some time.

**Comment by tjaychen** [comment]
`dif_pwrmgr_somketest` has been added.
