### ISSUE TITLE
[mask_ROM] Is the boot policy verified during boot?

### ISSUE THREAD

**Issue by KVISDAOWNER** [lowRISC/opentitan#5607]
To my knowledge, there is no documentation stating that the boot policy is verified against any signature or hash. Will the boot policy be verified in any way during boot or is it inherently trusted?

**Comment by tjaychen** [comment]
@moidx 
@alphan 
@silvestrst

**Comment by alphan** [comment]
Thanks for the question @KVISDAOWNER. We are still working on the design but the current plan is to verify its integrity using a checksum.

**Comment by KVISDAOWNER** [comment]
Thank you for the response. I suspect that there could be security risks involved if the checksum is distributed along with the boot policy. Is it stored in a different part of memory or transmitted at a different time? In other words, are there any enforcements that prevent the checksum from being altered along with the boot policy?

**Comment by moidx** [comment]
The boot policy implementation is now available here: https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/lib/boot_data.c

The boot policy is stored in internal info flash pages and it is only accessible to the ROM and ROM_EXT. The info pages are lockdown before jumping into the next boot stage. 

Closing this issue for now, but feel free to re-open if there are any follow up questions. Thanks
