### ISSUE TITLE
[otbn/sw] Add missing OTBN ECDSA signature_r value to test verification step.

### ISSUE THREAD

**Issue by TRJensen** [lowRISC/opentitan#5626]
An ECDSA test exists in sw/device/tests/otbn/otbn_ecdsa_p256_test.c

The ECDSA signature verification step requires the R value as input.
In the OTBN test code, a signing is done followed by a verification.
Because the correct R value already exists in OTBN memory,
we get a successful signature verification. However when clearing
OTBN memory between the signing and verification step, the
verification step fails. Adding the R value to verification step
solves problem.

**Comment by imphil** [comment]
Thanks for this bug report. Would you mind doing a pull request that addresses the problem as you propose?

**Comment by TRJensen** [comment]
Suggest adding Philipp Wagner.
I have a suggested update available on a local branch ( also attached here )

[ECDSA_TEST_PATCH.TXT](https://github.com/lowRISC/opentitan/files/6149671/ECDSA_TEST_PATCH.TXT)

**Comment by TRJensen** [comment]
Yes, I would be happy to - I am however still new - just created GitHub account yesterday.
I have however worked with GIT for last couple of years, but I am still new to the process for opentitan.

I have a branch available locally - but it is branched out from master.
I understand I cannot push my development branch directly and need to do a pull instead.

How do I do the pull step specifically?

**Comment by TRJensen** [comment]
Yes, I would be happy to - just investigating process (as I am new) - will let you know if I need support.

**Comment by imphil** [comment]
No problem! If you'd like to give it a try, there's a OpenTitan-specific documentation at https://docs.opentitan.org/doc/ug/github_notes/. If you have further questions, feel free to ask them here or join the lowRISC zulip chat at https://lowrisc.zulipchat.com/.

**Comment by TRJensen** [comment]
Thank you for the link - it was a great help :)
I have created the pull request. Hope I did it correctly :)
