### ISSUE TITLE
[entropy_src] Behavior of ENTROPY_DATA register on partial reads

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#5630]
From @asb on Slack “I've been working through @mcy 's entropy_src DIF header in companion with the IP spec. Under "Entropy Processing" the spec says "A full twelve 32-bit words need to be read at a time." Am I misunderstanding this - i.e. is this just a requirement in a specific scenario? The programmer's guide for instance doesn't provide an interface where 12 words are read at a time”

I responded in Slack that this is not a typical use case, but all the same this just means that we have to read this register 12 times to cleanly read it out.  However this brings up the question: 
**What the heck happens if software DOESN’T read a full 384 bits from ENTROPY_DATA?**
There is no theoretical reason why software should need 384 bits. Software could be doing something completely different than our DRBG.   So why do we require software to read out in multiples of 384 bits?  My only presumption is that this is because that would cause mixing of 384 bit SHA3-conditioning output blocks, and though that shouldn’t *theoretically* be a security problem, someone would be uneasy releasing split portions of a conditioning block to different consumers.

However 
- Is this purely a security issue or is there a hardware design issue here as well?    
- Will reading out a portion of 384 bits gum up the pipelines? 
- Is this fractional read case in the DV test plan all the same? (It should be)

**Comment by martin-lueker** [comment]
FYI: @moidx, @asb

**Comment by martin-lueker** [comment]
Update: this was discussed in our weekly entropy discussion.

It turns out this dates back from a very early version of this IP, one that predates CSRNG and EDN.  As such it is no longer strictly needed.   

It is also undesirable as it is an interface which is distinctly different from CSRNG and EDN, and provides an alternative software path to something that is also available in CSRNG.  In a meeting @corgi and @zi-v claimed that this was undesirable from a security/complexity standpoint.

What's worse the software usage model is unclear.  If software reads a portion of the 384 bits, there is no register indicating how much is left to read. Furthermore, reading a portion of this 384 bits may stall the entropy flow to CSRNG.   

At this point we propose removing this feature, and if needed adding  back similar PTG.2 quality access via EDN (see #5639 for details)

**Comment by moidx** [comment]
+1 on removing `ENTROPY_DATA` from `entropy_src` . Stalling flow into CSRNG can easily result in unintended side effects.

**Comment by cdgori** [comment]
Just tagging onto here so I get notifications for comments.  (@martin-lueker has me @ mentioned above as corgi - he's not the first to do that, and certainly won't be the last ;) - I'm very used to it at this point!)

**Comment by martin-lueker** [comment]
> Just tagging onto here so I get notifications for comments. (@martin-lueker has me @ mentioned above as corgi - he's not the first to do that, and certainly won't be the last ;) - I'm very used to it at this point!)

Lol...  I once knew better, however when I once saw you tagged as corgi I was so charmed and delighted, that may first thought was "That man Chris is a genius!".  Though I do wonder what the real corgi thinks of our random tags.  Just think of all the github spam!

**Comment by mwbranstad** [comment]
Adding @felixmiller since I believe he was looking into this as a requirement or not.

**Comment by mwbranstad** [comment]
My understanding of this issue now is this: this ENTROPY_DATA register will remain in entropy_src module, and all 12 entropy values must be read to empty the head of the attached FIFO.
Assigning issue to @martin-lueker to agree and close this issue.

**Comment by msfschaffner** [comment]
Has this been addressed by now?

**Comment by martin-lueker** [comment]
This issue can be closed with an additional comment.

Now that the interface prohibits configuration updates while enabled, there is definitely no risk of interactions between the ENTROPY_DATA register and the CSRNG point.   Even still, the implementation would not have allowed this previously any way, though we can now be absolutely confident of this non-interaction and it is easily verified by the stress test.
