### ISSUE TITLE
[doc] Validation of public keys in ROM_EXT manifests

### ISSUE THREAD

**Issue by Bjerkk** [lowRISC/opentitan#5671]
It is my understanding that the public keys found in each ROM_EXT manifest must be validated somehow. I am curious about the function _check_pub_key_id_valid(rom_ext_pub_key_id)_ found in the pseudocode under the section [Secure Boot Process](https://docs.opentitan.org/sw/device/mask_rom/docs/) .

From my understanding, based on reading through the documentation, the function takes the calculated rom_ext_pub_key_id and tries to match that against the Silicon Creator pub_key_id. However, I am not sure exactly how this is done and where the Silicon Creator pub key id resides in memory. Therefore I have the following questions:
- What happens in _check_pub_key_id_valid()_ exactly?
- Where does the Silicon creator pub key id reside on the chip? Is it in the creator_certificate found in each of the flash banks right after the manifest as (illustrated by [Memory Layout](https://docs.opentitan.org/doc/security/specs/secure_boot/))
- How exactly is the rom_ext_pub_key_id calculated? Is it calculated by performing a KMAC operation on the public key found in the manifest?

**Comment by imphil** [comment]
@moidx @alphan

**Comment by tjaychen** [comment]
@tjaychen

**Comment by moidx** [comment]
Hi @Bjerkk, 

The pseudo code notes aim to capture earlier conversations on secure boot, and may not reflect the final implementation. 

> * What happens in _check_pub_key_id_valid()_ exactly?

This aims to capture the public key lookup stage. Devices usually have multiple public keys that can be disabled in the manufacturing stage, so the mask rom needs to ensure that the key used to verify ROM_EXT is part of the valid key allow list.

> * Where does the Silicon creator pub key id reside on the chip? Is it in the creator_certificate found in each of the flash banks right after the manifest as (illustrated by [Memory Layout](https://docs.opentitan.org/doc/security/specs/secure_boot/))

ROM_EXT verification pub keys are stored in mask ROM. 

> * How exactly is the rom_ext_pub_key_id calculated? Is it calculated by performing a KMAC operation on the public key found in the manifest?

The manifest also has the full pub key. The key ID doesn't have to be calculated via a strong cryptographic mechanism, and thus this is just an implementation detail. The important point here is that verification of the ROM_EXT is performed against the public key stored in immutable memory.
