### ISSUE TITLE
[dbg] Improve debug support

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#574]
It's possible to connect OpenOCD to an earlgrey verilator system and then use GDB however there are issues:

* Ibex doesn't currently support hardware breakpoints and GDB cannot use software breakpoints as the emulated flash disallows writes
* OpenOCD generates FENCE.I instructions which aren't implemented in Ibex resulting in illegal instruction exceptions, these don't seem to totally break anything but will slow things down
* Single stepping in GDB is possible but rather slow

I note there's a debug test suite available at https://github.com/riscv/riscv-tests/tree/master/debug. The OpenOCD compliance test suite fully passes but clearly isn't a sufficient set of tests as actually using GDB is a painful experience currently (especially without working breakpoints).

I am looking at improving the debug.  As my first steps I am going to implement FENCE.I and hardware breakpoints in Ibex (https://github.com/lowRISC/ibex/issues/391 and https://github.com/lowRISC/ibex/issues/382) and try the debug test suite from riscv-tests and look into any issues that raises.

This isn't a priority for launch but it's nice to have.

**Comment by imphil** [comment]
Probably the only thing missing from this list is enabling hardware breakpoints in OpenTitan (we already support them in Ibex). @tomroberts-lowrisc is looking at that.
