### ISSUE TITLE
[sw, difs] Inconsistency around use of bool vs dif_ipname_toggle_t

### ISSUE THREAD

**Issue by asb** [lowRISC/opentitan#5746]
It looks like some DIF APIs are using a bool for indicating things like lock state (`bool *is_locked`), while others are using `dif_$IPAME_toggle_t` for the same purpose (mostly `dif_$IPNAME_toggle_t *state`). We should pick one or the other and use it consistently.

**Comment by silvestrst** [comment]
In this particular case I probably prefer `bool`, bot don't have strong feelings.

**Comment by moidx** [comment]
This is done now. Marking as obsolete.
