### ISSUE TITLE
[fpga] Look into ways to make ROM loadable on FPGA

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#5751]
To aid the development of mask rom we want to have an easy way to update the ROM in development FPGA images. 

One approach would be making the ROM accessible through OpenOCD. This would mean attaching the ROM (or a backdoor interface to the ROM) to the TL-UL bus, which can be accessed by the system bus access (SBA) debug module.

None of this loading should obviously leak into the production image, and will likely be removed as soon as mask rom development has stabilized.

CC @moidx

**Comment by tjaychen** [comment]
@moidx can we close this? i know you did a lot of work on the rom splicing stuff.

**Comment by moidx** [comment]
Hi @tjaychen, this is ok to close. We have splicing integrated into CI now.
