### ISSUE TITLE
[otp_ctrl] TLUL sw partition window has no return after lc_escalate_en is On

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#5790]
Hi Michael,

I found that after lc_escalate_en is `On`, and we try to access TLUL SW partitions. I expect to get a `d_error` with `d_data` 0, but design does not return anything on the bus.

I saw the `tlul_req_i` goes up, but `tlul_rvalid_o` stays 0 because the state machine it is in `ErrorSt`.

Personally, I think it is easier for the user to get a d_error instead of hanging on the TLUL bus :)

![image](https://user-images.githubusercontent.com/11466553/112403558-e0a39a00-8ccb-11eb-8428-c7e279c69e1b.png)

Thanks,
Cindy

**Comment by msfschaffner** [comment]
Hey Cindy, 

This is not hard to fix, see linked PR and let me know if that is along the lines of what you where thinking.
