### ISSUE TITLE
[CI] Expose Vivado build logs as artifacts

### ISSUE THREAD

**Issue by asb** [lowRISC/opentitan#58]
When Vivado fails, the info on stdout is not useful. It would be good to expose the more detailed log files as artifacts for people to review. The fact this is probably reliant on having access to the Azure org makes it a bit inconvenient, but there may be other options (e.g. scp to bubble.servers.lowrisc.org/ci_artifacts/prNNN/).

From @imphil on zulip:

> Philipp Wagner: yes, Vivado doesn't output synthesis results on stdout (it does output implementation results ...) You need to look into the *.runs/synth_1/runme.log file. This and other *.rpt files from the impl_1 and synth_1 directories should be available as artifacts, otherwise debugging is almost impossible

> Philipp Wagner: This is what we do for optimsoc: https://github.com/optimsoc/optimsoc-autobuild/blob/master/.gitlab-ci.yml#L130-L133

**Comment by msfschaffner** [comment]
@imphil has this been addressed by now?

**Comment by imphil** [comment]
Yes
