### ISSUE TITLE
[sw] dif_aon_timer delay

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#5805]
In one of the [smoketests](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/dif/dif_aon_timer_smoketest.c#L63), we program a few registers in the `aon_clk` domain of `aon_timer`, and then explicitly place a software wait for this write to take effect. 

For `aon_timer` at least, I thought the written value would propagate into the other domain and then feed back for the register to read.  So it seems like it would be better to add a `check` boolean to the `dif_aon_timer` functions if we want the values to be explicitly checked before returning. 

In addition, @rswarbrick recent change for multi module interfaces I think also now means modules such as `aon_timer` can natively support two incoming transaction streams targetted at different clock domains.  Would anyone mind if I did an experiment with that on `aon_timer` just to see how it would work? I can push it as a draft PR for people to gauge its feasibility.  If we have that, there shouldn't be a need for software to check at all, the transaction will simply complete when it's actually done (long write latency of course).

**Comment by rswarbrick** [comment]
Sounds like a good idea to me. I guess the only question for this sort of thing (probably not relevant for aon_timer) is exactly how long the write latency might be. If it's ~10 cycles, I shouldn't think it matters, but if it's hundreds of cycles then SW might want to be able to do stuff while it waits, meaning we'd need a "fork; join"-style flow.

**Comment by silvestrst** [comment]
> So it seems like it would be better to add a check boolean to the dif_aon_timer functions if we want the values to be explicitly checked before returning.

Do you mean something like a `polled` (function polls until the slow clock domain have registered the change) type of behaviour that can be requested via flag?

> but if it's hundreds of cycles then SW might want to be able to do stuff while it waits, meaning we'd need a "fork; join"-style flow.

I guess that is up to higher level driver that uses the DIF.

**Comment by tomroberts-lowrisc** [comment]
> Would anyone mind if I did an experiment with that on aon_timer just to see how it would work?

Please go ahead! I meant to give this a go myself but have been tied up with other things.

**Comment by rswarbrick** [comment]
>> but if it's hundreds of cycles then SW might want to be able to do stuff while it waits, meaning we'd need a "fork; join"-style flow.
>
> I guess that is up to higher level driver that uses the DIF.

Yes, but I think that the design Tim is suggesting would stall the CPU on a write to the config register, which means that neither the DIF nor the higher level driver could support this sort of "fork; join" behaviour. As I said, no biggie if it's just a few cycles, but it might be an issue if it's hundreds.

**Comment by silvestrst** [comment]
> Yes, but I think that the design Tim is suggesting would stall the CPU on a write to the config register, which means that neither the DIF nor the higher level driver could support this sort of "fork; join" behaviour. As I said, no biggie if it's just a few cycles, but it might be an issue if it's hundreds.

I see, thank you for the clarification.

**Comment by tjaychen** [comment]
this is slightly outdated now and will soon be replaced by a different proposal.
