### ISSUE TITLE
[spi_host, spec] Support independent configuration per CS line

### ISSUE THREAD

**Issue by tunghoang290780** [lowRISC/opentitan#5806]
According to the specification, `spi_host `is able to support programming independent configuration for CS by using `multireg` with `MaxCS` parameter for `CONFIGOPTS `and `COMMAND` registers. Although the value of `MaxCS` is currently set to 1 in RTL meaning one configuration is supported, it still requires efforts to developing a parameterize spi_agent for general cases. 

@tjaychen @msfschaffner Do we really need supporting independent configuration per CS line (keep MaxCS only for the number of CS lines)?

**Comment by tjaychen** [comment]
if it's make it easier, we don't need to keep this parameterizeable and can hard-code it.
I can't imagine we would need more than 4 in the long term.
