### ISSUE TITLE
[top] Audit xbar connections

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#5816]
It seems the `core_d` and `dm_sba` xbar connections list can sometimes get out of sync.
It's probably good to audit these before major milestones to make sure `dm_sba` is able to access all the modules it is supposed to.

**Comment by msfschaffner** [comment]
It looks like the only thing that has to be done here is align the `rv_core_ibex.cored` and `rv_dm.sba` lists here:
https://github.com/lowRISC/opentitan/blob/0681ffa10a42f151309530fc10511e284a76fc18/hw/top_earlgrey/data/xbar_main.hjson#L198-L211

**Comment by tjaychen** [comment]
@GregAC 
@andreaskurth 

i took a quick look at this.. and the only thing `cored` can access that `sba` cannot is `rv_dm.mem`.
Do we see any reason this should be excluded?  I guess I don't see a ton of utility in the path, but I don't see any reason why it should not be there either. 

If it's okay with you all, I will add it back to make the two sides consistent.

**Comment by andreaskurth** [comment]
I agree, thanks @msfschaffner  and @tjaychen

**Comment by GregAC** [comment]
Sounds good to me
