### ISSUE TITLE
[sw] Utilization reports

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#5820]
It is very useful to get utilization reports integrated with the build infrastructure. This helps in tracking various binary sizes, and setup alerts if the code size starts getting above certain threshold. 

This issue is to propose setting up utilization reports for all device libraries and executable targets. Ideally, we should also have an aggregated report in a parsable format providing a comprehensive utilization snapshot.

**Comment by msfschaffner** [comment]
This sounds like something we can defer into M3. Please relabel if that is not the case.

**Comment by moidx** [comment]
This is now supported by https://github.com/lowRISC/opentitan/blob/master/util/py/scripts/mapfile_to_json.py.
