### ISSUE TITLE
[Question]: Programming Opentitan with Jatg

### ISSUE THREAD

**Issue by sajjadahmed677** [lowRISC/opentitan#5833]
I am trying to program opentitan using GDB and jtag interface. But when I run ```load``` command on gdb it gets failed. So, my question is can we program opentitan using jtag.?? Right now am testing it on verilator.

**Comment by cindychip** [comment]
Hello,

Thank you for raising this question. For DV testing, I have not tested on TOP_LEVEL, but I think JTAG works on LC_controller (i have a pending PR here for jtag driver updates： https://github.com/lowRISC/opentitan/pull/5439). Could you share more on what kind of error you see on Verilator?
@msf for visibility.

Cindy

**Comment by msfschaffner** [comment]
Hi @sajjadahmed677,

Thanks for trying out OpenTitan.
As described in the documentation, it is indeed possible to connect to OpenTitan via OpenOCD/GDB:
https://docs.opentitan.org/doc/ug/getting_started_verilator/

However, the programs are executed from the embedded flash, and **write** accesses to the flash memory are not memory mapped. That means that a special SW driver is be needed on the device to actually reprogram what is located in the flash memory region (basically programming word by word using the register interface of the flash controller).

Hence I would not expect GDB to be able to directly load a program into the flash region via the JTAG (@imphil @tjaychen please correct me if I am wrong).

You should still be able to debug the program via GDB, though.

Best regards,
Michael

**Comment by tjaychen** [comment]
yeah that's right. Flash cannot be directly written via memory map.
You can take a look at sw/device/lib/flash_ctrl.c to get an idea how to
actually write to it.

Although, you should be able to load the program into sram and execute from
there if that's what you want.
How does load program decide where to write..? sorry i'm not too familiar
with this area.

**Comment by sajjadahmed677** [comment]
Thank you all for your response!
the syntax of command that i am trying to run is as 
```load filename offset```
we know that gdb reads symbols from elf file so if i give offset in this command it will add the offset value to the base address that is defined in elf file and load the file into that address. 
i have tried this command on opentitan but as you mentioned flash is not physically writable yet. 
i have also tried this command on my scaled down version of opentitan where i have a physically writable memory but the same issue. 
``` load command failed```
so, my question is do i need any additional driver for writing memory through jtag or i am missing something??

**Comment by sajjadahmed677** [comment]
this issue is resolved now. after setting proper connections to the targeted memory.
