### ISSUE TITLE
[feature request] add inout to inter-module signal type

### ISSUE THREAD

**Issue by jake-ke** [lowRISC/opentitan#5834]
According to the [Comportability Spec](https://docs.opentitan.org/doc/rm/comportability_specification/#inter-signal-handling), inter-module signals can only be input/output as specified by the `type` attribute. I would appreicate an extension of `type` so that topgen can interpret signals as `inout`. 

My use case, as shown in #5598, is passing FPGA DDR3 inout pins directly to an IP which instantiates MIG7. This cannot be done by pinmux since it converts inouts to *_i/_o/_oe. Currently, I am using the inter-module to pass pins, but I need to manually change the ports in `top_earlgrey.v` to inout after each topgen.

This proposal would definitely benefit my case, but I am not sure if it will be generally useful. Please let me know if it will be supported in future. Thanks!

**Comment by tjaychen** [comment]
this is already supported (although documentation not yet updated).
If you look at `flash_ctrl.hjson` for example, you can specify the type as `io`.
