### ISSUE TITLE
[otbn] Add CSR/WSR definitions to yaml and refactor to use them

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#5841]
The OTBN ISS uses hard-coded constants for the CSR and WSR addresses. These should be defined in a yaml file somewhere instead. The ISS can be refactored to use the names from the yaml and strip out magic constants. This will also enable named CSR/WSRs for otbn assembly and can be used to autogenerate the CSR/WSR documentation.

**Comment by msfschaffner** [comment]
@rswarbrick Is this still relevant?

**Comment by rswarbrick** [comment]
Heh, a sensible question! Actually, I spent some time last week trying to do it :-) I think it's probably worth doing this, and it will also allow the toolchain to support register names, which would be nicer than magic indices.

**Comment by rswarbrick** [comment]
This is a duplicate of #3323, which was fixed by #20421 late in November (and I didn't realise it was tracked in two places).
