### ISSUE TITLE
Idiomatic Rust: permit tests to return Result<()>

### ISSUE THREAD

**Issue by cfrantz** [lowRISC/opentitan#5844]
According to [the Rust docs](https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html#tests-and-), tests are permitted to return `Result<()>` so you can use `?` in place of `unwrap()`.

1. Update the codebase.
2. Update the rust style guide documentation (and/or _start_ some rust style guide documentation).

**Comment by mcy** [comment]
This mostly affects Manticore, but it's useful to unify this across OT projects.

**Comment by msfschaffner** [comment]
Anything left to do here?
