### ISSUE TITLE
RAL genaration update needed

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#5852]
1. generate multi-reg to an array. refer to discussion at #5796
2. generate correct backdoor path when there are multiple regfiles in a IP

FYI @sriyerg @tunghoang290780 @cindychip

**Comment by rswarbrick** [comment]
(2) should hopefully be fixed by #5856.

**Comment by weicaiyang** [comment]
Thanks @rswarbrick for fixing it

> (2) should hopefully be fixed by #5856.

**Comment by sriyerg** [comment]
Yes, this issue has been addressed. Closing.
