### ISSUE TITLE
[keymgr] return OpDoneSuccess when lifecycle is off during an operation 

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#5853]
@tjaychen 
since LC is off, expect any OP will return failed status. WDYT?

![Screen Shot 2021-03-29 at 6 36 50 PM](https://user-images.githubusercontent.com/49293026/112920410-c0a21b00-90bd-11eb-80d8-0212514c2d60.png)

/edascratch/weicai-opentitan/ot/fix_lc/keymgr-sim-vcs/0.keymgr_lc_disable/out

**Comment by tjaychen** [comment]
wait are you saying right now it 'does not' return failed status? because i think the intent is that it should.
let me check the waveform.

**Comment by weicaiyang** [comment]
> wait are you saying right now it 'does not' return failed status? because i think the intent is that it should.
> let me check the waveform.

yes, it returns OpDoneSuccess. in the issue title I said "return OpDoneSuccess when lifecycle is off during an operation", perhaps I should repeat this in the issue body too.

**Comment by tjaychen** [comment]
good catch @weicaiyang , it turns out this one the en dropped during the middle of transitioning to invalid.
I forgot to mark operations as invalid during that state.  Can you see if this helps?

**Comment by weicaiyang** [comment]
> good catch @weicaiyang , it turns out this one the en dropped during the middle of transitioning to invalid.
> I forgot to mark operations as invalid during that state. Can you see if this helps?

thanks for quickly fixing this. the change looks good to me.
