### ISSUE TITLE
Flash space usage for ownership transfer context

### ISSUE THREAD

**Issue by bluegate010** [lowRISC/opentitan#5869]
Just wondering, roughly how much flash will be required to store the ownership transfer context managed by ROM_EXT?

**Comment by cfrantz** [comment]
The size of the ownership transfer manifest will vary in the type and number of keys to be endorsed for the next owner, and there may be some additional hardware binding info in the manifest (still working through the details; think fuse config).  Please take the following numbers as initial estimates.

1) We expect the ownership transfer manifest to be 4KiB or less.
2) We expect the ROM_EXT binary size (which includes code for processing the manifest) to be about 16KiB.

**Comment by tjaychen** [comment]
i'm closing this issue, please file another or re-open if there are follow-on questions.
