### ISSUE TITLE
[rtl, aon_timer] common interrupt bit offsets

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#5882]
The question has really originated from this [comment](https://github.com/lowRISC/opentitan/pull/5624#discussion_r599565167).

Is the flag in `no_auto_intr_regs: "true"` deliberate, and also whether we are correctly using this flag to determine whether to generate `_INTR_COMMON_` set of defines? From software perspective all the `aon_timer` software interrupt bit offsets are the same across `intr_state`, `intr_test` registers.

**Comment by tomroberts-lowrisc** [comment]
Sorry I didn't get to this earlier!
`no_auto_intr_regs: "true"` is set deliberately to avoid generating the interrupt enable registers. For both timers, we don't need a mechanism to disable interrupts (that's all the module does). Also, for the watchdog timer we definitely can't have an auto-generated enable that isn't locked (defeats the point of the lock).

**Comment by silvestrst** [comment]
@tomroberts-lowrisc thanks! I think we might be misusing this flag in SW for common interrupts generation, but that's a different story.
