### ISSUE TITLE
[boot_rom] Add a simple message to let users know the boot_rom has started properly

### ISSUE THREAD

**Issue by gkelly** [lowRISC/opentitan#590]
This came up from talking to Ram, but right now there's no clear indication that boot_rom has started properly.

**Comment by silvestrst** [comment]
Currently when boot_rom is started it does some initialisation first to configure and initialise uart, after that it prints out the commit hash. It then does the rest of bootstrapping and before jumping to the application code in flash - prints out "Jump!".

I think it probably would be helpful to have a more descriptive message than "Jump!".
