### ISSUE TITLE
[entropy_src/csrng/edn] need a start/stop/start function for the entropy complex blocks

### ISSUE THREAD

**Issue by mwbranstad** [lowRISC/opentitan#5941]
It appears that there are use cases that require the capability to start, then later stop the entropy flow. At that point the blocks would be re-programmed and then re-started again. This is really the difference between the boot-time case and the normal operational case for the entropy complex blocks.

**Comment by mwbranstad** [comment]
Meeting consensus was that this issue will also need a transactional register lock function, versus the current software global lock.

**Comment by vogelpi** [comment]
This got addressed by #6124. I think it can be closed. Can you please confirm @mwbranstad ?

Btw I noted that you usually reference the related issues in your PR title with something like "fixes #xyz". It seems this doesn't work as intended. If you instead put that text in to the PR body two things will happen:
1. GitHub will recognize the reference and link the corresponding issue. Reviewers can then just hover over the link or click to get to the issue.
2. If you keep writing "fixes #xyz", then Issue xyz will indeed be closed automatically once the PR gets merged.

**Comment by mwbranstad** [comment]
@vogelpi correct, This issue was fixed with #6124. I followed guidance earlier to include the "fixes" in the commit message. I actually do not like this, and it doesn't seem to work, as you say. Looking at github pages, it seems they recommend to put this in the body of the comment message, not the title/subject line. I will do this going forward as I think I like this feature.

**Comment by mwbranstad** [comment]
Based on the above discussion, manually closing this issue.
