### ISSUE TITLE
[sw/silicon_creator] Manifest software binding configuration

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#5954]
The following are required in the manifest to implement software binding and key versioning as defined in the key manager spec and the identities and root keys documentation:

```c
// This input will be used for sealing key derivations.
uint32_t sw_binding_tag[8];

uint32_t max_key_version;
```

**Comment by alphan** [comment]
These fields were added to the manifest in #6956 and are currently used in `mask_rom_boot()` to configure the key manager. I think this issue can be closed now, please let me know if you think otherwise.
