### ISSUE TITLE
[sw,tooling] Repeated calls to ninja repeat work

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#5980]
Repeated calls to `ninja -C build-out` with no changes in the source tree seem to repeatedly call `export_target.sh` to copy things to the `build-bin` directory. This seems to be because `build_always_stale` is set: is that *really* what we want to do?

@imphil (as the lowRISC Meson expert) and @mcy (as a less local Meson expert!)

**Comment by moidx** [comment]
Leaving open as there are some otbn dependencies still using ninja.

**Comment by GregAC** [comment]
We should definitely eradicate ninja use if it's still in the repository, though this is low priority.

**Comment by msfschaffner** [comment]
Seems like this can be closed, given that we're not using Meson anymore.
