### ISSUE TITLE
[top] Hook-up integrity alerts to all module regfiles

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#5985]
Need to hook up integrity failure outputs to fatal alerts for all modules.

**Comment by rswarbrick** [comment]
OTBN done at #5993; rom_ctrl done at #5994.

**Comment by tjaychen** [comment]
thanks Rupert!

**Comment by tjaychen** [comment]
this is now done. Thanks ot @msfschaffner for doing the vast majority of them.
