### ISSUE TITLE
[silicon_<creator, owner>] Interrupt vectors and exception handlers

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#5997]
# Introduction

The current thinking is that after the jump/handover, there is a time period where the current executing stage will use interrupt vectors and handlers from the previous execution stage. For example in transition from MaskROM to ROM_EXT, until ROM_EXT CRT re-configures `mtvec` - in case of an exception the MaskROM exception handler will be executed.

This is also related to #5996 . 

# Questions

- Does anyone see any issues with this approach?
- Would it be better if this is configured before the jump?

**Comment by mundaym** [comment]
We might want to consider switching back to the assembly exception handler during ROM_EXT C runtime initialization since it will clobber the mask ROM's C runtime. I think it is safe to do that early in the ROM_EXT though, I don't think we need to do it before the jump.

**Comment by alphan** [comment]
@mundaym I agree, exception handlers are set to the ones defined in `mask_rom.c` at ROM -> ROM_EXT jump. Switching to the asm handler early in ROM_EXT and then to those defined in `rom_ext.c` SGTM.

**Comment by mundaym** [comment]
This issue has been discussed in the Security WG meeting on 2021-11-15. No objections were raised to setting `mtvec` *after* control has been transferred to ROM_EXT.
