### ISSUE TITLE
Update docs now cfg and register hjson is in same file

### ISSUE THREAD

**Issue by mdhayter** [lowRISC/opentitan#60]
A whole bunch of detail in Comportability doc overlaps RegisterTool doc. Now the config info is merged we need to revisit how to document. Probably Comportability has the overview and RegisterTool the syntax?

@sjgitty thoughts?

**Comment by sjgitty** [comment]
@mdhayter I looked this over and it doesn't appear to be too much of an overlap. WDYT? Shall we close it? The one thing that is a bit oddly specific in the Comportability spec and not very detailed in the Regtool spec is the three interrupt registers.

**Comment by mdhayter** [comment]
I don't see much overlap. 

It just seems strange with having all the detail and example file on registers in the register tool doc and almost nothing on the configuration, whereas there is lots of detail and example file on configuration in comportability spec and almost nothing on registers. So if you want to look up details you have to remember which doc has it.

Certainly this is more of a nit.
