### ISSUE TITLE
[mask_rom_lockdown] ePMP MMWP status in Tock for OpenTitan

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#6003]
# Introduction

The current thinking is that an OpenTitan chip starts with the ePMP MMWP bit set (any access to the memory space that has not been explicitly granted by ePMP is denied). The implication is that this bit once set, cannot be unset.

Tock OS is Silicon Owner code kernel, and should be able to operate in ePMP MMWP mode.

# Questions

- How much Tock OS for OpenTitan is expected to diverge from the upstream version?
- What does BL0 need to do (ePMP preparation) prior to jump into kernel?

**Comment by alistair23** [comment]
>     * How much Tock OS for OpenTitan is expected to diverge from the upstream version?

Hopefully very little :)

>     * What does BL0 need to do (ePMP preparation) prior to jump into kernel?

Right now Tock expects to be able to set all of the PMP config/addresses and then sets the `MML` bit. If the `MML` bit was already set this should be fine as long as Tock can edit all of the regions.

**Comment by mundaym** [comment]
The MMWP bit is now set by the mask ROM (and probably will be part of the MSECCFG reset value too).
