### ISSUE TITLE
Discuss alert handler configuration

### ISSUE THREAD

**Issue by cfrantz** [lowRISC/opentitan#6041]
I've requested we add a SW alert to alert handler in https://github.com/lowRISC/opentitan/issues/5896.

The alert handler documentation states that the ping timer won't start until the initial configuration is set and "locked in", which later (in Initialization step 4) implies write-locking the configuration registers.

This means in order to generate a SW alert in the ROM, I need to lock in an alert configuration.
Also means that since the ping timer isn't running, I will be unaware if alert manager would alert for any peripherals (e.g: `OtpCtrlFatal{Macro,Check}Error`, `LcCtrlFatal...` and few others have names that sound interesting to Mask ROM).

- Do we need the ROM to configure and lock an alert configuration?
  - Set alert configuration in OTP, let customers choose?
- Do we want to defer alert configuration to silicon owner code (e.g. BL0)?
  - ROM only locks in alert configuration if it determines it needs to alert.

**Comment by moidx** [comment]
For initial bringup, it is recommended to set the alert configuration in OTP. 

> This means in order to generate a SW alert in the ROM, I need to lock in an alert configuration.

Is it possible to gradually lock down alert enablement? In case we want MaskROM to enforce certain alerts, and then delay further configuration in the ROM_EXT?

**Comment by cfrantz** [comment]
[Initialization](https://docs.opentitan.org/hw/ip/alert_handler/doc/#initialization) step 4 says one must write-lock the registers to enable the ping timer (and thus, I assume, any alert manager activities like escalations).

In order to support a gradual lockdown, I think we'd want to separate enable and register-locking.  If we were to do that, we could have Mask ROM turn on the alerts it cares about and allow BL0 to reconfigure to the silicon_owner's preferred configuration. In such a separated enable/lock scheme, we'll have to consider whether trying to glitch/reprogram alert manager before full lockdown in BL0 then is a viable method of attack.

**Comment by tjaychen** [comment]
yeah i think separate enable / locking would be possible, but we'd have to
see how that maps to the classes though... because that might not be so
easily differentiated.

**Comment by tjaychen** [comment]
this conclusion of this issue is now captured in #6108 
Will close this one down.
