### ISSUE TITLE
[dvsim] Dubious csr_rw test dispatch for chip-level testing

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#6060]
If you run
```
util/dvsim/dvsim.py hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson --select-cfgs chip -i chip_csr_rw --reseed 20
```
with commit 1def47b then you'll run 20 tests (good!). But they get reported like this:
```
|  Milestone  |          Name           | Tests       |  Passing  |  Total  |  Pass Rate  |
|:-----------:|:-----------------------:|:------------|:---------:|:-------:|:-----------:|
|     V2      | tl_d_outstanding_access | chip_csr_rw |    12     |   20    |   60.00 %   |      
|     V2      |   tl_d_partial_access   | chip_csr_rw |    12     |   20    |   60.00 %   |
|     V2      |                         | **TOTAL**   |    24     |   40    |   60.00 %   |
|             |                         | **TOTAL**   |    24     |   40    |   60.00 %   |

```

Should this command have actually run 40 tests (where two different "name"d tests each use the same sequence)? Or is there something wrong with how we're reporting things?

@sriyerg: You can probably understand this the quickest: I suspect something's come a bit unstuck in dvsim.

**Comment by sriyerg** [comment]
I've been meaning to fix this, but never got to it until now - fixed in #6246 - we need to stop counting the same tests multiple times when they are mapped to multiple testplan entries.
