### ISSUE TITLE
[kmac] Make entropy valid in reset state.

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#6069]
ROM_CTRL sends SHA3/cSHAKE operations through KMAC Application Interface when no SW is loaded. It is to verify ROM code is genuine and not corrupted.

Current KMAC requires some SW configurations to run the module. Need to check the CSRs and revise the design to use pre-defined value right out of reset.

**To Be Added to the list**

- [ ] `CFG.entropy_ready`: Make `rand_valid` to 1 and send garbage data to SHA3.

**Comment by cindychip** [comment]
implemented for rom
