### ISSUE TITLE
[util] Rename vendor_hw.py

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#607]
The vendor_hw.py script was initially done (as the name says) to vendor in hardware components; it's now used for more than hardware, so we should rename it to a more appropriate name. Possibly `vendor.py`?

**Comment by moidx** [comment]
`vendor.py` or `vendor_src.py` SGTM.

**Comment by moidx** [comment]
Seems like `vendor_src` is easier to regexp in the future. WDYT @imphil?

**Comment by sjgitty** [comment]
`vendor_src` or `vendor_copy` sgtm

**Comment by sjgitty** [comment]
or `vendor_in`

**Comment by moidx** [comment]
Closed by lowrisc/opentitan#1001
