### ISSUE TITLE
[otbn] Use Entropy Src/EDN/CSRNG DIFs in OTBN tests

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#6082]
The OTBN smoke test and RSA/ECDSA tests contain direct register writes to setup the entropy src, EDN and CSRNG. These should be replaced with DIF usage when the DIF is available.

**Comment by GregAC** [comment]
Initial DIFs are available for entropy SRC and CSRNG but not EDN

**Comment by imphil** [comment]
Depends on https://github.com/lowRISC/opentitan/issues/5465. The EDN DIF is only a header currently, which is of little use.

**Comment by rswarbrick** [comment]
This was fixed by d04b048, where @moidx added an `entropy_testutils` module.
