### ISSUE TITLE
[otbn] Choose a final LFSR structure for URND

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#6083]
The current URND implementation is taken from the AES blocks LFSR implementation for masking. It uses 4  Galois XOR LFSRs (64 bits each) with some final scrambling provided by an SBox. URND required for OTBN must be carefully evaluated and a final URND implementation chosen to meet them.

Scope: PR with RTL for new PRNG block, replacing the current setup in OTBN for URND, ask Michael to do a synthesis experiment for area/timing numbers, and present result to security WG for final decision.

> estimate 8

**Comment by imphil** [comment]
@vrozic has an implementation of the XorShiRo256** RTL. Next steps: Do a PR with this RTL and run through DC for area numbers.

**Comment by msfschaffner** [comment]
Hey @imphil @GregAC, what is the status on this? Do we need an A/B synthesis comparison?

**Comment by GregAC** [comment]
XorShiRo256 PRNG is now implemented in OTBN
