### ISSUE TITLE
[entropy_src/rtl] move the fw FIFO out of the main path for simplicity

### ISSUE THREAD

**Issue by mwbranstad** [lowRISC/opentitan#6086]
The firmware override path currently has a FIFO buffer in the mainline path. This FIFO is not needed for the main hardware only path of operation. Because of this construction, there are extra controls required, and some unnecessary limitations.

A new proposal is to move the FIFO out on its own path. Also, the depth of the FIFO will be made available to the firmware, with a comparison register to create an interrupt. With a 64 entropy deep FIFO of 32b each, the time to service the interrupt would be 32 x 10us per 32b word (or 320 us), using the middle of the FIFO as the trigger. This should be plenty of time for the processor to see and process the interrupt without dropped new incoming entropy. The processor can collect and track the entropy up to the point it needs to process it. Optionally, it can enabled the hardware health tests, or performs its own health tests. Optionally, it can write the entropy back to the sha3 conditioner, or perform its own conditioning and write the results through the bypass path.

The attached diagram shows how the FW FIFO has moved location in the entropy flow.
[fw_path_diag.pdf](https://github.com/lowRISC/opentitan/files/6305216/fw_path_diag.pdf)

**Comment by mwbranstad** [comment]
For entropy meeting discussion: @tjaychen @martin-lueker @cdgori @felixmiller @moidx

**Comment by mwbranstad** [comment]
forget @senelson7 @zi-v

**Comment by mwbranstad** [comment]
Meeting review consensus was that this change is good and should be implemented.

**Comment by zi-v** [comment]
Some questions and comments:
The latency calculation above assume 100kbps. We might want to be prepared for upside (better bit rate).
Now that we understand that it is just a latency FIFO and does not need to consume the whole buffer, maybe we need to think about its optimal size (it does not necessarily need to be 2kB).
In case we use firmware health test, is there a way to stall the RNG flow from publishing bits until the firmware tests are concluded?

**Comment by tjaychen** [comment]
I think what we discussed during the meeting is that the FIFO would follow
the same behavior as the final FIFO.
Ie, new entries will evict older entries if the FIFO overflowed.

I don't really see this as a problem, but let me know if you think
otherwise and we can discuss tomorrow.

**Comment by mwbranstad** [comment]
I think we have an opportunity to reduce the FW FIFO to maybe 1K bits or so. It is sized to make sure that the processor can remove bits out of the FIFO before the FIFO overruns. It was stated as a requirement prior that bits from RNG are not dropped. Maybe this is not the case now.
