### ISSUE TITLE
[syn] Add and adjust DC primitives for pim_xor2, prim_flop_en and prim_buf

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#6097]
With #6037, we've added generic and Xilinx-specific primitives `prim_xor2` and `prim_flop_en` and we've added a width parameter to the `prim_buf` primitives. The same primitives need to be created for DC and `prim_buf` needs to be adjusted accordingly.

This is related to #4238.

**Comment by msfschaffner** [comment]
The primitives have been adjusted / added, so we can close this issue.
