### ISSUE TITLE
[pinmux/padctrl] Update and merge pinmux and padctrl documentation

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#6102]
Split out from https://github.com/lowRISC/opentitan/issues/5221.

- [ ] Update and merge pinmux and padctrl documentation
- [ ] Automatically generate pinmux documentation tables

**Comment by imphil** [comment]
This is probably resolved by https://github.com/lowRISC/opentitan/pull/7551?

**Comment by msfschaffner** [comment]
Yes, this can be closed now. Thanks!
