### ISSUE TITLE
[ip/clkmgr] clkmgr is missing devmode input.

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#6104]
Apparently this is an omission, but it is required to have one.

**Comment by tjaychen** [comment]
it has been decided in another forum that for generation of devices we will not intentionally block debug visibility from the software.
As a result, the hook-up of the `devmode` input is now unimportant and should be revisited in a future release.

**Comment by msfschaffner** [comment]
See https://github.com/lowRISC/opentitan/issues/16739 for a discussion.
Closing for now, since we are not going to change that anytime soon.
