### ISSUE TITLE
[sw] Move unittests next to the module under test

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#6107]
This makes unittest maintenance more intuitive.

Example: 

```shell
sw/device/lib/dif/dif_csrng.c
sw/device/lib/dif/dif_csrng_unittest.cc
```

Currently, this is what we have:

```shell
sw/device/lib/dif/dif_csrng.c
sw/device/tests/dif/dif_csrng_unittest.cc
sw/device/tests/dif/dif_csrng_smoketest.c
```

**Comment by asb** [comment]
I think this makes sense for the unit tests - the tradeoffs would be different if were considering introducing a bunch of other files to the sw/device/lib/dif directories (and even then, not a huge deal one way or the offer).
