### ISSUE TITLE
[alert_handler] Enhancements for mask ROM

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#6108]
Mask ROM will activate a subset of alerts as part of its boot-up and shutdown procedure.
As a result of this, we need more fine grained control over how the alert handler can be locked and configured.

Specifically

- Alert enable and assignment to classes need to be individually lockable
- The configurations for a particular class need to be individually lockable
- The enabling of the alert mechanism also needs to be more fine grained such that a particular class can be activated without locking down all configuration

**Comment by tjaychen** [comment]
After discussing with @cfrantz some more, it turns out I misunderstood the original intent. 

What we really want to achieve is the ability to give alert handler multiple passes of configuration.
Specifically, the ROM may be more or less stringent than downstream stages of software.  However, this should not preclude the downstream stages (for example owner code) from making the alerts more or less stringent based on their needs. 

The separation of controls and bits in #6136 helps, but does not fully achieve this goal. 

As @msfschaffner mentioned, this multi configuration is difficult with the current alert handler because the ping timer expectation would change, and that might result in false positives.

We should keep this issue for further investigation on how we might improve this.

**Comment by cfrantz** [comment]
After discussing this with msf@, I believe the alert manager gives us the functionality we need:

Alerts may be configured, classified and activated by the mask ROM, but still open to further configuration.  Alert events will cause escalation.

As msf@ explained, turning on pinging still requires locking the alert configurations.  As I understand it, the pinging protocol is a defense against a certain class of attacks but is not required to be enabled for alert escalations to work.

**Comment by msfschaffner** [comment]
Thanks for the feedback @cfrantz.

Indeed, the only two prerequisites for an alert to be able to trigger escalation are:
- the alert needs to be enabled
- at least one escalation timer needs to be enabled and configured to detect that alert

@cfrantz do you want to keep this issue open for further tracking, or do you think we can close this down?

**Comment by alphan** [comment]
@cfrantz can we close this issue or do you want to keep it open for enabling pinging in rom?

**Comment by tjaychen** [comment]
@msfschaffner this is an old issue where I think all the items actually have been addressed.
I think when I filed this issue originally it was more about the enhancements needed on `alert_handler`.
let me know what you think.

**Comment by msfschaffner** [comment]
I think this is also how I see it. I think we can close it.
