### ISSUE TITLE
[sw] Coverage build configuration is broken due to missing `sw_lib_uart`

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#6117]
1. Switch coverage dependencies to use `dif_uart`.
2. Enable coverage in CI 

See also lowrisc/opentitan#3155

**Comment by imphil** [comment]
I had a fix for that around for a while and pushed it now to https://github.com/lowRISC/opentitan/pull/6120. The coverage in CI is tracked in #3155 I guess.

**Comment by moidx** [comment]
Thanks @imphil!

**Comment by msfschaffner** [comment]
@moidx can this issue be closed?

**Comment by moidx** [comment]
@alphan was the last person to look at coverage. Should we close this? I think it will be easier to integrate coverage with Bazel.
