### ISSUE TITLE
Key 'cores' not found in GAPI structure. Install a compatible version with 'pip3 install --user -r python-requirements.txt'.

### ISSUE THREAD

**Issue by wxz1003083273** [lowRISC/opentitan#6122]
the following cmd is what i run, i just can not run the test, i am very confused, who knows what the problem is, help me please~

[xiaotu@xiaotu-eda ~/Desktop/work/git_test/opentitan]$pip3 install --user -U -r python-requirements.txt
Collecting fusesoc>=1.11.0
  Cloning https://hub.fastgit.org/lowRISC/fusesoc.git (to revision ot) to /tmp/pip-install-lrrps_3d/fusesoc_cb2252644cc04b66ac23a56c5d185eae
  Running command git clone -q https://hub.fastgit.org/lowRISC/fusesoc.git /tmp/pip-install-lrrps_3d/fusesoc_cb2252644cc04b66ac23a56c5d185eae
  Running command git checkout -b ot --track origin/ot
  Switched to a new branch 'ot'
  Branch ot set up to track remote branch ot from origin.
  WARNING: Requested fusesoc>=1.11.0 from git+https://hub.fastgit.org/lowRISC/fusesoc.git@ot#egg=fusesoc >= 1.11.0 (from -r python-requirements.txt (line 30)), but installing version 1.11.dev57+g1fb8c93
Collecting edalize>=0.2.0
  Cloning https://hub.fastgit.org/lowRISC/edalize.git (to revision ot) to /tmp/pip-install-lrrps_3d/edalize_0b3a8054769b4e76ba4cba443b1fe151
  Running command git clone -q https://hub.fastgit.org/lowRISC/edalize.git /tmp/pip-install-lrrps_3d/edalize_0b3a8054769b4e76ba4cba443b1fe151
  Running command git checkout -b ot --track origin/ot
  Switched to a new branch 'ot'
  Branch ot set up to track remote branch ot from origin.
Requirement already satisfied: enlighten in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 6)) (1.9.0)
Requirement already satisfied: flake8 in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 7)) (3.9.0)
Requirement already satisfied: gitpython in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 8)) (3.1.14)
Requirement already satisfied: hjson in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 9)) (3.0.2)
Requirement already satisfied: ipyxact>=0.2.4 in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 10)) (0.2.4)
Requirement already satisfied: isort in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 11)) (5.8.0)
Requirement already satisfied: libcst in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 12)) (0.3.18)
Requirement already satisfied: livereload in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 13)) (2.6.3)
Requirement already satisfied: mako in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 14)) (1.1.4)
Requirement already satisfied: meson<=0.54,>=0.53.0 in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 15)) (0.54.0)
Requirement already satisfied: mistletoe>=0.7.2 in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 16)) (0.7.2)
Requirement already satisfied: premailer in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 17)) (3.7.0)
Requirement already satisfied: pycryptodome in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 18)) (3.10.1)
Requirement already satisfied: pyelftools in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 19)) (0.27)
Requirement already satisfied: pyftdi in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 20)) (0.52.9)
Requirement already satisfied: pyserial in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 21)) (3.5)
Requirement already satisfied: pygments in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 22)) (2.8.1)
Requirement already satisfied: pytest in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 23)) (6.2.3)
Requirement already satisfied: pytest-timeout in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 24)) (1.4.2)
Requirement already satisfied: pyyaml in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 25)) (5.4.1)
Requirement already satisfied: tabulate in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 26)) (0.8.9)
Requirement already satisfied: yapf in /home/xiaotu/.local/lib/python3.6/site-packages (from -r python-requirements.txt (line 27)) (0.31.0)
Requirement already satisfied: Jinja2!=2.11.0,!=2.11.1,>=2.8 in /home/xiaotu/.local/lib/python3.6/site-packages (from edalize>=0.2.0->-r python-requirements.txt (line 33)) (2.11.3)
Requirement already satisfied: pyparsing in /usr/local/python3.6.5/lib/python3.6/site-packages (from fusesoc>=1.11.0->-r python-requirements.txt (line 30)) (2.4.7)
Requirement already satisfied: simplesat>=0.8.0 in /home/xiaotu/.local/lib/python3.6/site-packages (from fusesoc>=1.11.0->-r python-requirements.txt (line 30)) (0.8.2)
Requirement already satisfied: MarkupSafe>=0.23 in /home/xiaotu/.local/lib/python3.6/site-packages (from Jinja2!=2.11.0,!=2.11.1,>=2.8->edalize>=0.2.0->-r python-requirements.txt (line 33)) (1.1.1)
Requirement already satisfied: okonomiyaki>=0.16.6 in /home/xiaotu/.local/lib/python3.6/site-packages (from simplesat>=0.8.0->fusesoc>=1.11.0->-r python-requirements.txt (line 30)) (1.2.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/python3.6.5/lib/python3.6/site-packages (from simplesat>=0.8.0->fusesoc>=1.11.0->-r python-requirements.txt (line 30)) (1.14.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/python3.6.5/lib/python3.6/site-packages (from simplesat>=0.8.0->fusesoc>=1.11.0->-r python-requirements.txt (line 30)) (19.3.0)
Requirement already satisfied: jsonschema>=2.5.1 in /home/xiaotu/.local/lib/python3.6/site-packages (from okonomiyaki>=0.16.6->simplesat>=0.8.0->fusesoc>=1.11.0->-r python-requirements.txt (line 30)) (3.2.0)
Requirement already satisfied: zipfile2>=0.0.12 in /home/xiaotu/.local/lib/python3.6/site-packages (from okonomiyaki>=0.16.6->simplesat>=0.8.0->fusesoc>=1.11.0->-r python-requirements.txt (line 30)) (0.0.12)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/xiaotu/.local/lib/python3.6/site-packages (from jsonschema>=2.5.1->okonomiyaki>=0.16.6->simplesat>=0.8.0->fusesoc>=1.11.0->-r python-requirements.txt (line 30)) (0.17.3)
Requirement already satisfied: setuptools in /usr/local/python3.6.5/lib/python3.6/site-packages (from jsonschema>=2.5.1->okonomiyaki>=0.16.6->simplesat>=0.8.0->fusesoc>=1.11.0->-r python-requirements.txt (line 30)) (39.0.1)
Requirement already satisfied: importlib-metadata in /usr/local/python3.6.5/lib/python3.6/site-packages (from jsonschema>=2.5.1->okonomiyaki>=0.16.6->simplesat>=0.8.0->fusesoc>=1.11.0->-r python-requirements.txt (line 30)) (1.6.0)
Requirement already satisfied: blessed>=1.17.7 in /home/xiaotu/.local/lib/python3.6/site-packages (from enlighten->-r python-requirements.txt (line 6)) (1.18.0)
Requirement already satisfied: prefixed>=0.3.2 in /home/xiaotu/.local/lib/python3.6/site-packages (from enlighten->-r python-requirements.txt (line 6)) (0.3.2)
Requirement already satisfied: wcwidth>=0.1.4 in /usr/local/python3.6.5/lib/python3.6/site-packages (from blessed>=1.17.7->enlighten->-r python-requirements.txt (line 6)) (0.1.9)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /home/xiaotu/.local/lib/python3.6/site-packages (from flake8->-r python-requirements.txt (line 7)) (0.6.1)
Requirement already satisfied: pycodestyle<2.8.0,>=2.7.0 in /home/xiaotu/.local/lib/python3.6/site-packages (from flake8->-r python-requirements.txt (line 7)) (2.7.0)
Requirement already satisfied: pyflakes<2.4.0,>=2.3.0 in /home/xiaotu/.local/lib/python3.6/site-packages (from flake8->-r python-requirements.txt (line 7)) (2.3.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/xiaotu/.local/lib/python3.6/site-packages (from gitpython->-r python-requirements.txt (line 8)) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in /home/xiaotu/.local/lib/python3.6/site-packages (from gitdb<5,>=4.0.1->gitpython->-r python-requirements.txt (line 8)) (4.0.0)
Requirement already satisfied: typing-inspect>=0.4.0 in /home/xiaotu/.local/lib/python3.6/site-packages (from libcst->-r python-requirements.txt (line 12)) (0.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.2 in /home/xiaotu/.local/lib/python3.6/site-packages (from libcst->-r python-requirements.txt (line 12)) (3.7.4.3)
Requirement already satisfied: dataclasses>=0.6.0 in /home/xiaotu/.local/lib/python3.6/site-packages (from libcst->-r python-requirements.txt (line 12)) (0.8)
Requirement already satisfied: mypy-extensions>=0.3.0 in /home/xiaotu/.local/lib/python3.6/site-packages (from typing-inspect>=0.4.0->libcst->-r python-requirements.txt (line 12)) (0.4.3)
Requirement already satisfied: tornado in /home/xiaotu/.local/lib/python3.6/site-packages (from livereload->-r python-requirements.txt (line 13)) (6.1)
Requirement already satisfied: lxml in /home/xiaotu/.local/lib/python3.6/site-packages (from premailer->-r python-requirements.txt (line 17)) (4.6.3)
Requirement already satisfied: cssutils in /home/xiaotu/.local/lib/python3.6/site-packages (from premailer->-r python-requirements.txt (line 17)) (2.2.0)
Requirement already satisfied: cachetools in /home/xiaotu/.local/lib/python3.6/site-packages (from premailer->-r python-requirements.txt (line 17)) (4.2.1)
Requirement already satisfied: cssselect in /home/xiaotu/.local/lib/python3.6/site-packages (from premailer->-r python-requirements.txt (line 17)) (1.1.0)
Requirement already satisfied: requests in /home/xiaotu/.local/lib/python3.6/site-packages (from premailer->-r python-requirements.txt (line 17)) (2.25.1)
Requirement already satisfied: pyusb>=1.0.0 in /home/xiaotu/.local/lib/python3.6/site-packages (from pyftdi->-r python-requirements.txt (line 20)) (1.1.1)
Requirement already satisfied: pluggy<1.0.0a1,>=0.12 in /usr/local/python3.6.5/lib/python3.6/site-packages (from pytest->-r python-requirements.txt (line 23)) (0.13.1)
Requirement already satisfied: packaging in /usr/local/python3.6.5/lib/python3.6/site-packages (from pytest->-r python-requirements.txt (line 23)) (20.3)
Requirement already satisfied: toml in /home/xiaotu/.local/lib/python3.6/site-packages (from pytest->-r python-requirements.txt (line 23)) (0.10.2)
Requirement already satisfied: iniconfig in /home/xiaotu/.local/lib/python3.6/site-packages (from pytest->-r python-requirements.txt (line 23)) (1.1.1)
Requirement already satisfied: py>=1.8.2 in /home/xiaotu/.local/lib/python3.6/site-packages (from pytest->-r python-requirements.txt (line 23)) (1.10.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/python3.6.5/lib/python3.6/site-packages (from importlib-metadata->jsonschema>=2.5.1->okonomiyaki>=0.16.6->simplesat>=0.8.0->fusesoc>=1.11.0->-r python-requirements.txt (line 30)) (3.1.0)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/xiaotu/.local/lib/python3.6/site-packages (from requests->premailer->-r python-requirements.txt (line 17)) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /home/xiaotu/.local/lib/python3.6/site-packages (from requests->premailer->-r python-requirements.txt (line 17)) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/xiaotu/.local/lib/python3.6/site-packages (from requests->premailer->-r python-requirements.txt (line 17)) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/xiaotu/.local/lib/python3.6/site-packages (from requests->premailer->-r python-requirements.txt (line 17)) (1.26.4)
[xiaotu@xiaotu-eda ~/Desktop/work/git_test/opentitan]$python3 /home/xiaotu/Desktop/work/git_test/opentitan/hw/ip/prim/util/primgen.py /home/xiaotu/.cache/fusesoc/generated/lowrisc_prim_prim_pkg-impl_0.1/impl_input.yml
Key 'cores' not found in GAPI structure. Install a compatible version with 'pip3 install --user -r python-requirements.txt'.

**Comment by wxz1003083273** [comment]
@imphil

**Comment by imphil** [comment]
OpenTitan uses a modified version of fusesoc. Ensure you run pip with python-requirements.txt, e.g. `pip3 install --user -r python-requirements.txt` See https://docs.opentitan.org/doc/ug/install_instructions/#system-preparation for full system requirements.

**Comment by wxz1003083273** [comment]
> OpenTitan uses a modified version of fusesoc. Ensure you run pip with python-requirements.txt, e.g. `pip3 install --user -U -r python-requirements.txt` See https://docs.opentitan.org/doc/ug/install_instructions/#system-preparation for full system requirements.

i do run the cmd "**pip3 install --user -U -r python-requirements.txt**" and it runs well but get an warning below,
**WARNING: Requested fusesoc>=1.11.0 from git+https://hub.fastgit.org/lowRISC/fusesoc.git@ot#egg=fusesoc >= 1.11.0 (from -r python-requirements.txt (line 30)), but installing version 1.11.dev57+g1fb8c93**
then i run fusesoc --version, it is **1.11.dev57+g1fb8c93**

**Comment by wxz1003083273** [comment]
> > OpenTitan uses a modified version of fusesoc. Ensure you run pip with python-requirements.txt, e.g. `pip3 install --user -U -r python-requirements.txt` See https://docs.opentitan.org/doc/ug/install_instructions/#system-preparation for full system requirements.
> 
> i do run the cmd "**pip3 install --user -U -r python-requirements.txt**" and it runs well but get an warning below,
> **WARNING: Requested fusesoc>=1.11.0 from git+https://hub.fastgit.org/lowRISC/fusesoc.git@ot#egg=fusesoc >= 1.11.0 (from -r python-requirements.txt (line 30)), but installing version 1.11.dev57+g1fb8c93**
> then i run fusesoc --version, it is **1.11.dev57+g1fb8c93**

and i see lowRISC the newest tag of fusesoc is 1.10.0, there is not 1.11.0 version
