### ISSUE TITLE
[tracking] [OTBN.H.REG_INTEGRITY] Register file with integrity protection

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#6167]
This is a tracking issue covering all aspects of specification and implementation for the feature. Please link to/comment in separate issues for subtasks.

* [x] Document/specify feature in OTBN documentation: #4007
* [x] Implementation: #6186
* [ ] Design Verification: #6188 
* [x] DIF/host SW (not necessary, feature transparent to SW)

**Comment by tjaychen** [comment]
I take it this means the registers have not widened for ECC yet is that
right?
Should we try to do that first for silver area purposes?

**Comment by rswarbrick** [comment]
You're right, the register files aren't widened yet. I think Greg's planning to work on this in this sprint anyway, so maybe it's better just to do it for real - I think that should still be in time for the silver drop?

**Comment by tjaychen** [comment]
yeah if you guys feel this is important, just make sure Faisal / Don are
aware.
