### ISSUE TITLE
[tracking] [OTBN.H.DMEM_INTEGRITY] Data memory with integrity protection

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#6168]
This is a tracking issue covering all aspects of specification and implementation for the feature. Please link to/comment in separate issues for subtasks.

* [x] Document/specify feature in OTBN documentation: #6469
* [x] Implementation: #6421 
* [x] Design Verification #8991, #8990
* [x] DIF/host SW (waived; feature is transparent to software)

**Comment by rswarbrick** [comment]
The memories are expanded already, but we're currently ignoring the top bits.
