### ISSUE TITLE
[tracking] [OTBN.H.STATEHARDENING] State Hardening

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#6172]
This is a tracking issue covering all aspects of specification and implementation for the feature. Please link to/comment in separate issues for subtasks.

* [ ] Document/specify feature in OTBN documentation
* [ ] Implementation
* [ ] Design Verification
* [ ] DIF/host SW (if necessary)

**Comment by rswarbrick** [comment]
This was a reasonably generic "harden some stuff" placeholder that we put in when we weren't exactly sure what we needed to do. The D2S review meeting and follow-ups gave us a much more precise definition of what needs doing (see e.g. #11019). Closing this accordingly.
