### ISSUE TITLE
[tracking] [OTBN.H.BLANKING] Blanking unused data and control paths

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#6174]
This is a tracking issue covering all aspects of specification and implementation for the feature. Please link to/comment in separate issues for subtasks.

* [ ] Document/specify feature in OTBN documentation
* [ ] Implementation
* [ ] Design Verification
* [x] DIF/host SW (transparent to SW)

**Comment by GregAC** [comment]
Closing in favour of this issue: https://github.com/lowRISC/opentitan/issues/9662
