### ISSUE TITLE
[otbn] handle data sections of multiple assembly inputs

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#6181]
So far we supplied constants and input data only in the self-contained test assembly (e.g. [here](https://github.com/lowRISC/opentitan/blob/master/sw/otbn/code-snippets/p384_scalar_mult_test.s#L65)) or some wrapper assembly containing the entry point that is called by SW (e.g. [here](https://github.com/lowRISC/opentitan/blob/master/sw/otbn/code-snippets/rsa.s)).

With EC crypto we have now the issue that we want to include constants (domain parameters) in the `.data` section of the lib assembly (e.g. in `p384.s`). This collides with having test data in the test assembly, since we directly referencing physical addresses in `li` and `lw` instructions.

Let's discuss the clean way to resolve this, e.g.:
- Use a dedicated section for test data
- Enable symbol references with the `lw` instructions
- anything else

For the symbol references, If I am understanding correctly how our tooling currently works, I think it should be straight forward to enable this. I think this is currently only caught by `otbn-as` as invalid syntax. I think we just need to unblock this and forward the label to the gnu assembler here to make this work. On the other hand, we might want the constants to always and up at the same physical address location in dmem, regardless of whether the lib is used in the test assembly or called by Ibex SW.

**Comment by felixmiller** [comment]
@imphil 
@rswarbrick

**Comment by rswarbrick** [comment]
Should be handled by #6185.

**Comment by rswarbrick** [comment]
This should hopefully be sorted by #6192, but I'm not going to link the issue and PR. When it's merged, @felixmiller, could you check that this works the way you expect?

**Comment by rswarbrick** [comment]
@felixmiller: Is this fixed now? (I hope so, but don't want to close it without checking with you)
