### ISSUE TITLE
DFT – In rstmgr_ctl block rst_aon_n resets should be controlled in scan-mode 

### ISSUE THREAD

**Issue by NoamGottlieb** [lowRISC/opentitan#6193]
rst_aon_n affecting ~2 FFs. In scan mode it is not controlled, hence these FFs are removed from scan.
SpyGlass-DFT messages: 
'chip_earlgrey_asic.top_earlgrey.u_rstmgr_aon.u_lc_src.rst_aon_n' is not disabled for 1 flip-flop(s) 
'chip_earlgrey_asic.top_earlgrey.u_rstmgr_aon.u_sys_src.rst_aon_n' is not disabled for 1 flip-flop(s)

![image](https://user-images.githubusercontent.com/79256454/115271384-f62ea700-a145-11eb-8fa3-dc709a705fbe.png)

**Comment by arnonsha** [comment]
Please note that in each case only one FF is affected by the non controlled reset, Adding a mux may not be "economical"  in terms of additional faults to add a mux. We usually fix such cases by ANDing with scan_shift:
`rst_scan = rst & ~scan_shift;
rst_scan_n = rst_n | scan_shift;
`
This way the reset reaching the FF is inactive during shift.
