### ISSUE TITLE
[prim_fifo_sync] case of write, read, and full fifo state acts unexpected

### ISSUE THREAD

**Issue by mwbranstad** [lowRISC/opentitan#6230]
@msfschaffner @tjaychen recommended that an issue be written for this case.

What is observed is that when the fifo is full (say a depth count of 4 is reached and is the depth size of the fifo), if a write fifo pulse and a read fifo pulse arrive at the same cycle, in the next cycle the depth counter goes to 3. I would have expected it to remain at 4, where the new entry gets pushed in at the same time as the oldest entry gets popped out.

**Comment by mwbranstad** [comment]
@msfschaffner maybe this goes to @eunchan, please re-assign if that is the case.

**Comment by msfschaffner** [comment]
It could be that the FIFO does not propagate readiness information from the read side to the write side for timing reasons. In that case, the FIFO fill state first has to decrease to 3 before a new element can be written.

@eunchan is that how the FIFO has been designed? 

@mwbranstad is this performance critical? 
In that case we may want to consider adding a parameter that enables simultaneous read and write when the FIFO is full...

**Comment by tjaychen** [comment]
ah to be clear, when talking to Mark yesterday, he has built his
surrounding logic to accommodate this particular point.
But I asked him to file an issue still for future enhancement
considerations.

This i do not think is something critical for fixing right now. Mark please
correct me if I am wrong.

**Comment by mwbranstad** [comment]
This is definitely not performance critical in this use case, but the fifo controls are "clunky" as in most FIFOs that I have worked with do not behave this way. An extra flop delay was added to pop the entry first, then push the new one in. As @tjaychen states, we discussed this in the entropy mtg and he suggested writing up an issue on this. A parameter is a good idea (maybe required) because there is probably lots of usages that depend on the current behavior.

Since I need to add this same logic to anther FIFO, I though if this change could be made, I will update the RTL one time with the straight forward controls - at least that was the idea behind this.

**Comment by eunchan** [comment]
The design was changed after I (or Scott) designed, so my understanding may be incorrect.
But, If FIFO is full, then FIFO does not accept new write request, which `wready_o` is low. So, unless read side pops the entry. It won't. 

So when FIFO is full and write request and read acceptance come together, read processed but not write. Depth drops to 3 and next cycle write will be acked. 

Why?, it is to break timing path. If read acceptance affects writing ready, it creates long timing path backwards.

**Comment by mwbranstad** [comment]
@eunchan thanks for the explanation - all seems reasonable and what I am observing for behavior. 

If we assume this FIFO is always flop based (which I think it is), I am quite certain that we can build a timing hardy FIFO that has the push/pop/full behavior. Not sure if there is any interest in this, other than myself. Maybe it is too late in the game, unless we created a new prim_fifo altogether.

**Comment by eunchan** [comment]
> @eunchan thanks for the explanation - all seems reasonable and what I am observing for behavior.
> 
> If we assume this FIFO is always flop based (which I think it is), I am quite certain that we can build a timing hardy FIFO that has the push/pop/full behavior. Not sure if there is any interest in this, other than myself. Maybe it is too late in the game, unless we created a new prim_fifo altogether.

The `prim_fifo_sync` has `Pass` parameter, at least controls the **forward** timing path. We can add another parameter and implement **backward** pass timing path too.

**Comment by mwbranstad** [comment]
It is probably best to leave the overall behavior alone for now.
