### ISSUE TITLE
[otbn] Produce preliminary area estimate for proposed vector instructions

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#6232]
For the two vector instructions proposed in https://github.com/lowRISC/opentitan/issues/5058 produce a rough area estimate.

**Comment by GregAC** [comment]
We have no plans to investigate those specific instructions. A next generation OTBN could contain some vector functionality for PQC. Investigations for a next-gen OTBN will naturally include generating area estimates so closing this issue.
