### ISSUE TITLE
[tracking] [OTBN.H.DMEM_SCRATCHPAD] Data memory area inaccessible to the host CPU

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#6233]
This is a tracking issue covering all aspects of specification and implementation for the feature. Please link to/comment in separate issues for subtasks.

* [x] #8720
* [x] Implementation
* [ ] Design Verification
* [ ] DIF/host SW (if necessary)

---- 

Currently, OTBN exposes all of its 4kB DMEM through a window to the main bus, making it accessible to Ibex and other hosts on the bus.

Change the design to only expose a part of the DMEM to the bus.

The amount of memory that should be accessible through the bus window is TBD, early discussions indicate making the top 2 kB bus-accessible, while the bottom 2 kB are only accessible from OTBN.

@felixmiller @tjaychen would this split be roughly what you had in mind? 2kB should be plenty to transfer parameters/constants, input arguments, and operation results between Ibex and OTBN, judging from the OTBN software we have today.

**Comment by GregAC** [comment]
DV work is being tracked for V2 via other means
