### ISSUE TITLE
[doc] Clarify the behavior of the `hmac.CFG.endian_swap` and `kmac.CFG.msg_endianness` flags

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#6251]
The `hmac.CFG.endian_swap` and `kmac.CFG.msg_endianness` flags both disable or enable byte swapping on values written into the appropriate `MSG_FIFO`. However from a software perspective the technical specifications do not make clear exactly what the behavior is when values smaller than a word are written into the FIFO. It would be good to clarify this. Similarly it would be nice to unambiguously specify the behavior of unaligned writes and that the order of the writes themselves is affected by the flag.

### `hmac.CFG.endian_swap`

**Current text:** Convert TL-UL wdata[31:0] to big-endian style {w[7:0], w[15:8], .. }

**Suggested text:** Message byte swap disable. If 0 each individual multi-byte value, regardless of its alignment, written to `MSG_FIFO` will be added to the message in big-endian byte order. If 1 the value will be added to the message in little-endian byte order. Writes will not be reordered with regard to one another. A message written to `MSG_FIFO` one byte at a time will therefore not be affected by this setting.

### `kmac.CFG.msg_endianness`

**Current text:** Message Endianness. If 1, Convert TL-UL write data[31:0] to {d[7:0], d[15:8], ...}0: Little-endian. Keep input value as it is 1: Big-endian. Convert incoming value

**Suggested text:** Message byte swap enable. If 1 each individual multi-byte value, regardless of its alignment, written to `MSG_FIFO` will be added to the message in big-endian byte order. If 0 the the value will be added to the message in little-endian byte order. Writes will not be reordered with regard to one another. A message written to `MSG_FIFO` one byte at a time will therefore not be affected by this setting.

**Comment by mundaym** [comment]
@eunchan @alphan

**Comment by imphil** [comment]
@mundaym For things like that feel free to open a pull request right away with the proposed changes.
