### ISSUE TITLE
[otbn] Support comments in otbn-as after instructions

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#6258]
Assembling the following lines with otbn-as:

```as
addi    x10, x0, 12 /* comment */
```

fails with `Cannot match syntax for 'addi' ('<grd>, <grs1>, <imm>').`

**Comment by rswarbrick** [comment]
That should definitely work! I suspect it's a problem to do with trailing space (between the 12 and the comment). I'll try to take a look at this in the next couple of days.

**Comment by imphil** [comment]
No hurry at all, this is a low-prio item for the backlog.
