### ISSUE TITLE
[hw] Makefile targets

### ISSUE THREAD

**Issue by towoe** [lowRISC/opentitan#626]
Follow-up from #583 

The `hw/Makefile` has a target `regs-header` to allow building the register headers manually. `.gitignore` is adapted so the generated files are not tracked.

The generated headers are needed by the software build process, which automatically and independently creates the headers.

But they might also be useful for debug purposes for tool development so this local target exist.
This issue should serve for the discussion what is needed or what changes are required.

@eunchan @msfschaffner @sriyerg

**Comment by msfschaffner** [comment]
I think this issue can be closed.
The currently implemented solution does basically what @sriyerg suggested above.
I.e., the headers are generated in `$REPO_TOP/build` as part of a build. 
If needed, the registers can be build manually using `regs-header`.
