### ISSUE TITLE
[tlul_adapter_sram] ifetch clarification

### ISSUE THREAD

**Issue by udinator** [lowRISC/opentitan#6271]
Hi @msf, @tjaychen,

I just wanted to clarify something in the `tlul_adapter_sram` with you guys and confirm whether it is intended or not.

```  // An instruction type transaction is only valid if en_ifetch is enabled
  assign instr_error = tl_i.a_user.tl_type == InstrType &
                       en_ifetch_i == InstrDis;
```

As per an offline discussion with Michael, the multi-bit signal `en_ifetch_i` acts similarly to the `lc_tc_t On/Off` signals in that it enables ifetch functionality when set to `InstrEn`, but disables it when set to anything else (even if not `InstrDis`).

However in my DV environment if I set `en_ifetch_i` to, say, `3'b111`, I can sneak bus errors past this detection logic.

Should this line in the adapter sram be changed to `en_ifetch_i != InstrEn` to properly reflect its behavior?

**Comment by tjaychen** [comment]
yeah this is a bug.
I think this should be `en_fetch_i != InstrEn`

**Comment by msfschaffner** [comment]
agreed, let's make this `en_fetch_i != InstrEn`

**Comment by udinator** [comment]
sgtm, I'll get a PR open shortly.
thanks for the inputs!
