### ISSUE TITLE
[sw/build] Meson does not provide a reliable way to disable local `-I` args to GCC.

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#628]
As of https://github.com/lowRISC/opentitan/pull/503, we're using a small regular expression to strip Ninja files of all `-I` args that are not absolute, to work around Meson not having a global switch to disable generating `-I` arguments, and `implicit_include_directories` sometimes not working correctly[1].

In the middle-term, we should try to eliminate this small regular expression, and instead figure out how to ask Meson to not generate any `-I` args we don't provide manually in the top-level `meson.build`.

[1] I haven't been able to produce a minimal repro case for this, unfortunately. My current suspicion is that it falls out of the many special-use arguments we pass to Meson's build rule functions.

**Comment by moidx** [comment]
Closing as the software builds are not moving to bazel lowrisc/opentitan#7972.
