### ISSUE TITLE
[mask_rom] Consider using const rom driver handles. 

### ISSUE THREAD

**Issue by cfrantz** [lowRISC/opentitan#6283]
Consider making all ROM driver handles constant, so that they can be stored in `.rodata`. This requires creating a version of `mmio_region_from_addr` which can be used in a const context.

**Comment by mundaym** [comment]
Sounds reasonable to me. I think we should just remove the 'opaque handle' restriction on the `mmio_region_t` type and document it as part of the API.

**Comment by mundaym** [comment]
I think this was fixed with the introduction of [abs_mmio](https://github.com/lowRISC/opentitan/commit/b71cb35c5d878763ca25a5fcf93af6fa6ee03cf1), closing.
