### ISSUE TITLE
[sysrst_ctrl] explicit wakeup signal to pwrmgr

### ISSUE THREAD

**Issue by esshiu** [lowRISC/opentitan#6323]
When the GSC(CPU) is in sleep mode and sysrst_ctrl fires the interrupt, it needs to fire the wakeup to pwrmgr as well.

**Comment by tjaychen** [comment]
@esshiu is it okay if i add a wakeup signal to sysrst_ctrl first for now? just so i can integrate everything.
Then you can connect to that signal whenever you're ready.

**Comment by esshiu** [comment]
adc_ctrl and sysrst_ctrl are on the always-on clock and power domain.
When GSC(CPU) is in sleep mode and adc or sysrst wants to raise an interrupt, it needs to communicate with pwrmgr first
pwrmgr prefers a level wakeup signal from adc and sysrst_ctrl
Protocol wise, I'm thinking of the following. HW writes to SW-visible register when the wakeup event is detected. Once the GSC is waken up, SW can write a "wakeup reset" bit so that the HW will de-assert the wakeup signal to pwrmgr.

**Comment by esshiu** [comment]
For sysrst_ctrl, the wakeup event will be ULP(z3_wakeup) and all the interrupt source(triggered by combo and keyboard actions)

**Comment by tjaychen** [comment]
the integration portion of this is now done, so we just need to add the sysrst_ctrl side functionality.

**Comment by esshiu** [comment]
Sounds good. Thank you, Tim for integrating the wakeup signal to pwrmgr.

-Eric

**Comment by esshiu** [comment]
The feature is added to https://github.com/lowRISC/opentitan/pull/6314

**Comment by msfschaffner** [comment]
This feature has been implemented and connected at the top-level.
