### ISSUE TITLE
[ci] Current master is broken (since commit ef717d9)

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#6335]
CI is broken at the moment because of a failing chip-level CSR test. To reproduce:
```
util/dvsim/dvsim.py hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson --select-cfgs chip -i chip_csr_rw --fixed-seed=1
```

I'm taking a look now, but it's not completely obvious what's going wrong so I'm not sure whether I'll be able to fix things before the end of the day. If not, maybe a Google engineer could take a look (conveniently, there's a DV sync-up meeting in a minute, so I'll hand this over in person).

**Comment by tjaychen** [comment]
i'll help take a look. I ran into (through unrelated changes) an issue with otp escalation yesterday.
So maybe it's something else similar.

**Comment by rswarbrick** [comment]
Looking at the waves really quickly, it looks like the `csr_rd_check` task is spotting an unexpected value of an interrupt enable register. Weirdly, this happens *exactly* when reset strikes. So I think it's probably some odd race in the DV code. I'm hoping @weicaiyang (who understands this stuff much better than I do) will be able to pinpoint the problem quickly.

**Comment by rswarbrick** [comment]
A bit more information: I *think* there's a pending TL access that is trying to read the value of the register. It gets cancelled by the reset coming in, but that cancellation is scheduled by VCS before the environment exposes the fact that a reset came in. So then the check (which should have been disabled by the reset) still runs, with bogus data.

**Comment by tjaychen** [comment]
ah i see the issue now.
The uart does get read, but the "right data" does not make it back to the processor because the device is undergoing a reset and has turned off the clocks.

This is happening because the `watchdog` function of `aon_timer` has been unintentionally kicked off. 
I can quickly introduce some exclusions to handle this.

**Comment by tjaychen** [comment]
@cindychip 
@sriyerg 
@weicaiyang 

FYI

**Comment by tjaychen** [comment]
@rswarbrick i've merged the fix, let me know if you still see the problem.

**Comment by rswarbrick** [comment]
If CI is happy, so am I :grin:

**Comment by sriyerg** [comment]
Sorry for the late response. Seems like the correct fix here is to prevent writes that enable the WDOG. THe reset_en is pwrmgr really enables the reset sources to wake up the chip from sleep. That by itself does not have any side effect. Enabling WDOG does have a side effect (if not serviced it escalates to reset the chip).

**Comment by rswarbrick** [comment]
Well, maybe. We still have some tests that have a race condition if the chip gets reset when they're running. Maybe that's fine, but I definitely wasted a couple of hours trying to work out what the heck was going on. I'd probably suggest trying to fix that at some point.
