### ISSUE TITLE
[rom] entropy setup for early silicon

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#6340]
As discussed, when we first receive devices, there will not be any otp programming for the entropy source, so for the very first few boots, we will be relying on some kind of default setting in ROM. 

To ensure the ROM does not get stuck waiting on entropy, we need to think of how to qualify ROM entropy setup based on the state we are in, or whether otp settings are even available. 

One idea is to only setup production ROM settings when we are in production state, and use a safer default otherwise.

**Comment by zi-v** [comment]
Yeh, just need to make sure that the ROM branching between TEST and PROD (each if more than one) is secured against fault-injection.

**Comment by tjaychen** [comment]
@zi-v sorry just revisiting this information a bit.
Do you have safe defaults we can directly use in ROM? Or rather I'm guessing the "safe defaults" are going to be in ast directly right?

**Comment by zi-v** [comment]
We plan for safe defaults in AST hardware.

**Comment by tjaychen** [comment]
thanks @zi-v
