### ISSUE TITLE
[kmac] Is function name (N) limited to 4 bytes?

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#6359]
The documentation for the KMAC `PREFIX_N` registers state:

> It means that the software can freely decide the length of N or S based on the given Prefix register size 320bit. 320bit is determined to have 32-bit of N and up to 256-bit of S + encode of their length.

I originally took this to mean that the function name (N) was limited to 32 bits and the customization string (S) limited to 256 bits. However now I'm wondering if there are any limits so long as the combined string fits into the 352 bit `PREFIX` register (320 bits is a typo in the docs).

It is also worth noting that the TupleHash and ParallelHash functions described in [NIST SP 800-185](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-185.pdf) both *require* functions names larger than 32 bits. So if N is limited to 32 bits these functions cannot be implemented.

The KMAC DIF API currently limits N to 32 bits and S to 256 bits. Should it be changed? If so, what should the limits be?

**Comment by eunchan** [comment]
The requirement from SW folks was 4B is what they need. (and 256b for the customization string). Based on that requirement, I've set the `PREFIX` CSR to be 352b. SW can freely choose the size of `N` and `S` within the size of `PREFIX`.

So, technically `N` can be more than 32b. But then, `S` should be smaller than what originally SW folks wanted.

CC: @moidx @cfrantz

**Comment by moidx** [comment]
Currently the main plan is to support primarily support SHA3 and KMAC variants. In some cases we may also use cSHAKE.  Based on this I think it is ok to restrict `N` to 4B.  

At the moment, we don't have documented TupleHash or ParallelHash use cases.

**Comment by mundaym** [comment]
Thanks guys. I'll leave the limits in the DIF as-is then.
