### ISSUE TITLE
[top] chip_earlgrey_asic parameters

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#6366]
remove `chip_earlgrey_asic` parameter settings for `top_earlgrey`.
`chip_earlgrey_asic` should really use the same "safe" default settings and have no need to override.

This way we make sure whatever goes out the door is as intended via the hjson parameter defaults.

**Comment by vogelpi** [comment]
Yes, I fully agree. `top_earlgrey` parameters should only get non-default values on the emulation platforms.
