### ISSUE TITLE
[kmac] configuration errors

### ISSUE THREAD

**Issue by udinator** [lowRISC/opentitan#6370]
Currently, the `sha3pad::ModeStrengthCombinations_M` assertion checks that the selected mode and strength are confined within correct values.

Should the KMAC output this as an error state instead of an assertion?

**Comment by eunchan** [comment]
Good Idea. I think, if we want to report, it would be good to have pre-condition checker. It may check these errors when SW asserts `start` signal, in addition to other config errors (PREFIX checker, etc).

**Comment by tjaychen** [comment]
i think we can close this one now right?

**Comment by udinator** [comment]
@tjaychen yup you're right, closing now.
