### ISSUE TITLE
[pinmux] invert/pu/pd jtag pin attributes should be cleared when jtag is used

### ISSUE THREAD

**Issue by arnonsha** [lowRISC/opentitan#6392]
When JTAG pins are connected to any of the taps (lc/risc-v/dft), the pinmux attributes may be active.
A scenario where GPIOs have their inversion attr set, and then these pins become jtag pins will prevent JTAG from working !

Need logic that will clear these attributes when the pins are used as JTAG pins

**Comment by arnonsha** [comment]
@Leonid-Shamis

**Comment by arnonsha** [comment]
See also issue #6418

**Comment by msfschaffner** [comment]
@arnonsha can you close this issue if #6555 resolves it?

**Comment by msfschaffner** [comment]
This has been addressed - @arnonsha please feel free to reopen if there are still issues with this.
