### ISSUE TITLE
[kmac] main FSM hangs after kmac_app completion

### ISSUE THREAD

**Issue by udinator** [lowRISC/opentitan#6408]
Hi Eunchan,

I am running into a FSM bug when running some transactions through the application interface ports, the waves are below:

![Screenshot from 2021-05-02 17-38-27](https://user-images.githubusercontent.com/16736281/116833365-908ee180-ab6d-11eb-9f0b-9f277adc6e7e.png)

At the marker, `kmac_app` module has received the `absorbed_i` input from SHA3 logic, so raises the `app_o[0].done` signal for the KeyMgr interface port and transitions into Idle state, outputting `CmdDone` to top level KMAC module.

Meanwhile, the top level FSM sees the same `sha3_absorbed` signal from SHA3 logic and transitions from `KmacMsgFeed` into `KmacDigest` state.
However on the same cycle `sha3_done` goes high since `CmdDone` is seen from `kmac_app` logic, so we skip over the `KmacDigest -> KmacIdle` transition and fail to properly reset the entropy state for upcoming transactions.

**Comment by eunchan** [comment]
Ah.. Thanks for finding the bug. I will fix the main FSM to move to Idle state directly in case of App requests.
