### ISSUE TITLE
[pinmux] OE of JTAG input pins should be set to 0 by hw when JTAG is used

### ISSUE THREAD

**Issue by arnonsha** [lowRISC/opentitan#6418]
This is somewhat related to issue #6392

Need to set clear the OE of the JTAG pins (TCK/TMS/TDI/TRST)
The OE of TDO is controlled by the TAPs, so no need to set it.

@Leonid-Shamis

**Comment by msfschaffner** [comment]
@arnonsha can you close this issue if #6555 resolves it?

**Comment by msfschaffner** [comment]
This has been addressed - @arnonsha feel free to reopen if that is not the case.
