### ISSUE TITLE
[aes/alert] some aes state information available upon fatal alert

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#6437]
When injecting a bit flip to cause a fatal alert in the AES engine - reading the status register will give information on the status of the core. Idle, data_in_ready, stall etc.

could this be a security risk?
I imagine that running the AES module in manual mode and injecting errors at different times then reading the status could potentially give away information.

The aes_alert_reset test currently do not fail on this - but maybe we want to force an all 0's or a random value on the status register in case of a fatal?

I have tried to read the other registers but I don't see any feasible way of trying to correlate this to internal round keys etc.

**Comment by vogelpi** [comment]
Thanks @rasmus-madsen for bringing this up. I didn't think about this when implementing the alerts. My guess is that it would be better to set all other bits in the status register to zero or a random value whenever the fatal bit is set. The same should probably happen with the trigger register as triggers are only cleared after an specific operation has started/finished. So this could also give away information. I would be curious to get the views of @cdgori and @tjaychen.

**Comment by cdgori** [comment]
Seems better to blank the non-fatal-error bits in the status register if that fatal error bit is set (and probably for the triggers as you say).  Potentially makes life a bit harder for the software team, but I believe fatal really does imply an attack situation so not the end of the world to me.  If the software folks come up with a real reason to need this status as part of error recovery we can think about allowing it, but it's pretty much what the adversary wants to know when refining their glitch timing.

I would discourage random for the status register - that will be very confusing for everyone.

**Comment by vogelpi** [comment]
Thanks for the feedback @cdgori . In this case I will prepare a PR to change the behavior around this.
