### ISSUE TITLE
[otbn] Agree on desired feature set for assembler

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#6447]
The OTBN assembler is currently a rather low-level assembler. We need to agree what feature set we want, e.g. if we want to include higher-level functionality like a register allocator, more convenience in loop descriptions, etc.

**Comment by imphil** [comment]
@felixmiller @moidx if you come across features in the OTBN assembler which would be required or nice to have please dump them into this issue for now. I'll follow up with a summary and meeting for the proposed feature set later this quarter.

**Comment by rswarbrick** [comment]
Looks like the meeting didn't happen :-) I think we've got a couple of obvious missing features (nicer loop handling; named CSR/WSRs) which are tracked separately already. Probably no need to keep this open.
