### ISSUE TITLE
[otbn] Add ECDSA P-384 to end-to-end test

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#6448]
We currently have an end-to-end test for ECDSA P-256 at https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/otbn/otbn_ecdsa_p256_test.c. Produce a similar test for ECDSA P-384.

**Comment by rswarbrick** [comment]
This is probably superseded by the chip-level testplan. The SW guys can figure out exactly what they want to run to test their software :-)
