### ISSUE TITLE
[prim_secded] Inverted version of Hsiao code?

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#6478]
In OTBN (and many other places) we are currently using the integrity protection code calculated by `prim_secded_39_32`, which is a (39,32) Hsiao code (https://arxiv.org/pdf/0803.1217.pdf). 

It maps 
* `32'h0` to `39'h0`
* `32'hFFFF_FFFF` to `39'h00_FFFF_FFFF`

The all-1s code word `39'h7F_FFFF_FFFF` is not a valid code word.

We discussed (and I thought implemented) in the past an inverted version in which 0x0 is not a valid code word any more.

@msfschaffner Am I missing something (e.g. did we only implement in one particular case somewhere?), or is this just something we only talked about but never implemented?

CC @cdgori @tjaychen @udinator @eunchan

**Comment by msfschaffner** [comment]
This issue has been addressed.
We are now using a "inverted" Hsiao codes system-wide, where it is guaranteed that all-zero and all-one code words are invalid.

CC @moidx @cdgori
