### ISSUE TITLE
[otbn] Hardening BN.CMP and BN.CMPB

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#6483]
OTBN has two instructions to compare wide numbers, [`BN.CMP`](https://docs.opentitan.org/hw/ip/otbn/doc/isa/#bncmp) and [`BN.CMPB`](https://docs.opentitan.org/hw/ip/otbn/doc/isa/#bncmpb). Both are effectively subtractions which don't write a result register, but only set the corresponding flags. The instructions can be used to compare two register values for equality, but also to establish an ordering relation.

`sw/otbn/code-snippets/p256.s` has examples for both use cases (some additional comments added below):

Equality check:
```c
  /* goto 'fail' if w0 == w31 <=> s == 0 */
  bn.cmp    w0, w31
  /* read FG0 CSR, see https://docs.opentitan.org/hw/ip/otbn/doc/#control-and-status-registers-csrs */
  csrrs     x2, 1984, x0
  /* Mask out the zero flag */
  andi      x2, x2, 8
  bne       x2, x0, fail
```

Ordering (greater-than-equal in this case):
```c
  /* goto 'fail' if w0 >= w29 <=> s >= n */
  bn.cmp    w0, w29
  csrrs     x2, 1984, x0
  /* Mask out the carry flag */
  andi      x2, x2, 1
  beq       x2, x0, fail
```

The equality could be done on the full integrity-protected data word (i.e. the setting of the Z/zero flag). The calculation of the other flags requires us to remove the ECC, since the data needs to pass through the ALU.

The main question I'm having: Is testing for equality of two wide register values something that needs more protection than, e.g. a greater-than relationship?
(There are a couple of questions that would result from this being the case, but let's see if we need to go down that decision tree first.)

@felixmiller @cdgori

**Comment by moidx** [comment]
Assigning to M2 for further triaging.

**Comment by johngt** [comment]
@GregAC - Could you take a look at this and suggest if this is something that we should be doing in M2 / waiver, or if not whether you or someone else should be assigned to it?

**Comment by GregAC** [comment]
I don't think this is something we need to address for M2. Instead this is something to consider for a future version of OTBN. We may want to harden the comparisons but as this isn't something that was raised for D2S in the absence of a particularly compelling security reason to need it I don't think we should implement it at this stage.

@moidx any thoughts?

**Comment by moidx** [comment]
I agree with @GregAC. Given the amount of effort required to implement this change and the current stage of development of OTBN, I think it is preferred to harden this on the software side. I think it makes sense to move this issue to the backlog milestone, and label it as enhancement request for a future release.

@jadephilipoom  for visibility.

**Comment by GregAC** [comment]
For the security working group to make the final ruling but I think this isn't worth doing for PROD

**Comment by johannheyszl** [comment]
As per discussion @vogelpi @johannheyszl:

This is potential defense in depth. However, if really needed, more SW protection could be added with broader coverage. No identified relevant attack vectors.
