### ISSUE TITLE
Document how to vendor in Rust dependencies

### ISSUE THREAD

**Issue by cfrantz** [lowRISC/opentitan#6484]
Write a document which describes how to vendor in Rust dependencies.

Such a document should include:
- How to vendor in vendor in a new dependency.
- How to get approval for vendoring in a new dependency.
- How to configure your code to use the vendored version.
- How to update vendored dependencies (including approval).

**Comment by asb** [comment]
Another point to be determined is what sort of Rust dependencies should be vendored and when?

We don't currently vendor everything in (e.g. Python dependencies are external). Vendoring is usually used for hardware dependencies, and occasionally SW dependencies where there's a judgement it would be more painful to rely on it externally (e.g. some light patching is needed or it isn't commonly packaged+distributed).

As has been touched on in other meetings, we likely want to think more generally about ways to make builds hermetic, reproducible, and so on

**Comment by rswarbrick** [comment]
Is this issue still live, given the move to Bazel?

**Comment by msfschaffner** [comment]
@cfrantz @timothytrippel @moidx can this be closed?

**Comment by cfrantz** [comment]
Rust vendoring is accomplished with rules_rust's `crate_universe`.
