### ISSUE TITLE
[Question]: gdb command timing.

### ISSUE THREAD

**Issue by sajjadahmed677** [lowRISC/opentitan#6485]
Hello all!
i have a question that why the debugging process is too slow when using ```jtag``` interface in simulation. i have also tried the ```dmi``` interface but the issue is same. is there any specific way of speeding up the process except ```set_command_timeout_sec``` and ```set remotetimeout``` commands.

**Comment by rswarbrick** [comment]
I think we'd need some more information on what is being slow here. Is it just that the simulated chip isn't simulated very fast? (If so, not much we can do!) Or are you talking about some sort of timeout? In which case, why are we hitting the timeout at all?

**Comment by rswarbrick** [comment]
It's been a year without comment, so I'm going to close this as unanswered.
