### ISSUE TITLE
[spi_host] spi_host_fsm is stalled

### ISSUE THREAD

**Issue by tunghoang290780** [lowRISC/opentitan#6497]
*DV Branch:            [ebf5ecfc05](https://github.com/tunghoang290780/opentitan/commit/5197ba209536f272c9118df3aa388d27d6ae46b8)

*Seeding number:  1129857389

*Description:
Since (fsm_en=1'b1 && command_valid_i=1'b1) and stall=1'b'1 are both true so spi_host_st_q is not updated though spi_host_st_d  is updated to WaitLead. As the result, the spi_host_fsm is stalled at Idle state

*Waveform
![image](https://user-images.githubusercontent.com/53881329/117897590-fc610080-b277-11eb-9939-aa4767dc6d84.png)

**Comment by rasmus-madsen** [comment]
FYI  @Muqing-Liu

**Comment by rasmus-madsen** [comment]
@tunghoang290780 can you list what command to run to replicate this?

**Comment by rasmus-madsen** [comment]
solved with  #7377 waiting for it to be merged to close this issue

**Comment by rswarbrick** [comment]
If #7377 fixes the issue, you can link the PR to this issue (see "linked pull requests" on the right hand side of the page). If linked, the issue will be closed automatically when the PR is merged.

**Comment by rasmus-madsen** [comment]
> If #7377 fixes this issue, you can link the PR to it (see "linked pull requests" on the right hand side of the page). If linked, the issue will be closed automatically when the PR is merged.

ahh nice feature I never noticed. thank you
