### ISSUE TITLE
[util/reggen] Revise error to uvm_error and clean-up register top assertion

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#65]
- [X] Replace regparity assertion to use implication
- [ ] create `a_user` (and/or `d_user`) struct and use it for assertion 
- [X] Replace `$error()` to `uvm_error()`

This is the task of lowRISC/stwg-base#365

CC: @sriyerg @sjgitty

**Comment by rswarbrick** [comment]
The last item (`d_user_t`) was added by Tim in February with d12569fa30.
