### ISSUE TITLE
[sw] DIF pwrmgr smoketest does not work in DV

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#6503]
It works in Verilator possibly due to its single clock system. In DV, the wakeup arrives before the WFI. 

![image](https://user-images.githubusercontent.com/46467186/117924580-d0ab3e00-b2aa-11eb-9809-d50cb1a06750.png)

Working on a fix for this.

**Comment by sriyerg** [comment]
The test sets the AON timer to issue a wake up after 5 clock cycles at 200KHz, which computes to 5 * 5us = 25us. 

On the next line, the test puts the Ibex to sleep for 100us. 
https://github.com/lowRISC/opentitan/blob/c48b9195507755e58235583f6ceed8261a792954/sw/device/tests/dif/dif_pwrmgr_smoketest.c#L50

I am not sure I understand the need for this delay - 100us >> 5us. Seems like the wakeup should arrive before the WFI on Verilator too. Will investigate further.

**Comment by sriyerg** [comment]
The pwrmgr setup routine consumes about 50us, so the programmed threshold needs to be at least 10. 

![image](https://user-images.githubusercontent.com/46467186/117928253-22a29280-b2b0-11eb-84d9-c4f036169453.png)

This is because the DIF APIs hide the synchronization routine (notice the large number of `Get` transactions after each pwrmgr CSR is programmed. We end up incurring the delays due to synchronization 3 times. IMO a better strategy would be to instead expose the sync routine as an separate API so that we incur it only once.

**Comment by sriyerg** [comment]
Fixed in https://github.com/lowRISC/opentitan/pull/6500/commits/ea4789518e646e665d3fdcd4f8a4d82727160346.

**Comment by tjaychen** [comment]
i believe this been addressed some time ago.
