### ISSUE TITLE
[pwm] Mismatch behavior between the outports and programmed configuration of pwm channels

### ISSUE THREAD

**Issue by tunghoang290780** [lowRISC/opentitan#6526]
*DV Branch: [5a9c0767 ](https://github.com/tunghoang290780/opentitan/tree/pwm_smoke_v1)

*Seeding number: 3335280515

*Description:
- Some channels are programmed to the disabled states but their corresponding outports are still asserted. For instance, channel 0 status has been programmed to `disabled `state (e.g. `pwm_en[0]=1'b0`) but cio_pwm_o[0] is still asserted/de-asserted.
- Other channels (i.e. channel 2) are programmed to enabled state (e.g. `pwm_en[2]=1'b1`) but the pulses (e.g. cio_pwm_o[2]) are not continuously generated (while pwm_en[2] is kept at 1'b1)

*Waveform
![image](https://user-images.githubusercontent.com/53881329/118179849-ac567b00-b3ea-11eb-86bc-56946389f291.png)

**Comment by martin-lueker** [comment]
@muqing-liu: This might be a first good issue for you.
