### ISSUE TITLE
[sw/silicon_creator] Key manager driver for mask ROM.

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#6528]
This issue tracks the implementation of the keymgr mask ROM driver. 

- [x] Functionality:
  *   `keymgr_init()`
  *   `keymgr_advance_state()`
  *   `keymgr_get_state()`
- [x] Functional Test Cases:
  *    Standalone initialization and configuration flows. May require derivation function to properly test the output. 
- [x] Mask ROM integration:
  *   Activate the key manager after signature verification, and before jumping to rom_ext.

**Comment by moidx** [comment]
Also need to check the EDN intialization before advancing the state of the keymgr. EDN init happen well before we start using the keymgr, but adding a comment here to make sure we check the precondition.

**Comment by alphan** [comment]
@moidx, can this issue be closed?
