### ISSUE TITLE
[hw/entropy_src] LFSR as a compile-time option instead of configurable option

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#6539]
This came up as an action item during security review. 

Making the LFSR a compile-time option removes the ability to accidentally or maliciously switch to very deterministic entropy. 

If this is tracked somewhere else, please cross-link the issue and close this one as a duplicate.

**Comment by tjaychen** [comment]
I believe this has been done.
@mwbranstad to confirm.

**Comment by mwbranstad** [comment]
The LFSR has been completely removed now, so no issue anymore.
