### ISSUE TITLE
[hw/entropy] Harden the debug scenarios and other single points of failure on critical paths

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#6540]
Harden the debug scenarios (for example bypassing AES, and other OTP options) against fault injection attacks. Similarly to examine single points of failure on critical paths. 

Marking as P0 in terms of implementation priority with respect to other hardening tasks.

**Comment by tjaychen** [comment]
I believe we have addressed these concerns in the latest hardening.
@moidx @mwbranstad @cdgori let me know if you disagree.
