### ISSUE TITLE
[hw/otp] Consider using kmac for token processing

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#6548]
Consider moving from the current cipher construction into a token that can be verified using the kmac module.

**Comment by msfschaffner** [comment]
Changing to KMAC for token hashing is in the works:
- [x] Remove PRESENT token hashing from `otp_ctrl` (#6558)
- [ ] Switch `lc_ctrl` over to use KMAC for token hashing
- [ ] Update scripting to correctly calculate life cycle design constants

**Comment by msfschaffner** [comment]
This is now implemented, hence we can close this issue.
