### ISSUE TITLE
Add rust toolchain file and improve invoke_cargo.sh

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#6549]
Context: #6524, comment.
- [ ] Add rust toolchain file.
- [ ] Update `invoke_cargo.sh` to `cd` to the source dir so that `cargo` can find the toolchain file.
- [ ] Remove toolchain arg from `invoke_cargo.sh`.
- [ ] Running tests.
- [ ] It looks like `build_tock.sh` can be removed.

**Comment by moidx** [comment]
Is this still an issue?

**Comment by moidx** [comment]
Closing as obsolete.
