### ISSUE TITLE
[hw/entropy] Integrity of random bits

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#6551]
Parity along the data may be sufficient for checking entropy seed and output coming out of each stage.  There are additional checks that could be added to ensure that the level of delivered entropy is within a reasonable range.

@tjaychen to provide inputs on scope and priority.

**Comment by dsandrs** [comment]
@eunchan, @msfschaffner - Miguel pointed out what we do need to figure out integrity for entropy network.

**Comment by msfschaffner** [comment]
looping in WD as well @martin-lueker @mwbranstad

**Comment by mwbranstad** [comment]
which part of the "network" are you thinking about checking. The seed coming out of entropy_src has been checked and squeezed as it emerges. Are you thinking of added a parity bit to ride along, or something else.

**Comment by msfschaffner** [comment]
This would be more along the lines of a transmission integrity scheme that is capable of detecting bit errors in the distribution network.

**Comment by tjaychen** [comment]
@mwbranstad @moidx @cdgori i think we can close this now.
Ultimately we settled on the output checks from `entropy_src`, `edn` and `csrng`. 

I'll close for now, but let me know if you disagree.

**Comment by mwbranstad** [comment]
SGTM.
