### ISSUE TITLE
[dv] Set up regression for all IPs

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#659]
TODO item from signoff meeting. Currently, each DV owner maintains a local script to run regression. Need to set up a regression flow for everyone to use.

**Comment by sriyerg** [comment]
A tool for this has been added in `util/dvsim.py`. It is far from complete, but is minimally viable and should help users start running regressions.

**Comment by weicaiyang** [comment]
Thanks @sriyerg. Close this issue.
