### ISSUE TITLE
[ip/hmac] Wipe out secrets when hash/hmac done

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#66]
When hmac is done, wipe out (XOR with random value (eventually from LSFR)) internal variables.

1. SHA256: w[15:0][31:0], hash (not digest), stored message length (txcount), state
2. HMAC: secret_key (? is it necessary?), received message length, txcount. state.

**Comment by sjgitty** [comment]
On a mission to clean up old issues, scraping from stalest to freshest.

I think this one should stay open until new "2020 specification" is written.

**Comment by mateenfaisal** [comment]
Resuming @sjgitty mission to clean up old issues, scraping from stalest to freshest.

@eunchan, @tjaychen - should this issue still stay open?

**Comment by eunchan** [comment]
Yes. Should be in open status. Trying to clean up this now.

**Comment by msfschaffner** [comment]
@eunchan another status ping on this issue :). Can this be closed?

**Comment by eunchan** [comment]
Yup. I think everyone agrees FW wiped function is fine for HMAC.
