### ISSUE TITLE
[sw/silicon_creator] Update the size of the sec_mmio_ctx expectation table.

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#6609]
Update the size of the `sec_mmio_ctx` expectations table by updating the  `kSecMmioRegFileSize` and `kSecMmioRndStep` constant values.

Consider adding a test case to scan the table utilization in `ROM` and `ROM_EXT` boot stages.

**Comment by mundaym** [comment]
https://github.com/lowRISC/opentitan/pull/8145 doubles the size of the table. A size increase is necessary because the PR makes more OTP reads go through sec_mmio.

**Comment by alphan** [comment]
@moidx do we need to keep this issue open? For the test, were you thinking of a functional test?

**Comment by alphan** [comment]
Adding notes from the ROM sync:

> ROM and ROM_EXT share the same table, it should be large enough to accommodate new entries from ROM_EXT.
> We may need to add additional measurements to the .static_critical section, e.g. ROM_EXT digest.
> should write a small design doc on this that also covers the backup plan, e.g. copy over, if we need to enlarge the memory in ROM_EXT.
