### ISSUE TITLE
[pwm, doc] Incorrect paths to PWM spec. and dvplan in opentitan.org

### ISSUE THREAD

**Issue by tunghoang290780** [lowRISC/opentitan#6636]
@martin-lueker could you fix paths to PWM specification and dvplan in opentitan.org? Those paths are not accessible.

![image](https://user-images.githubusercontent.com/53881329/118933614-455f2780-b8fe-11eb-9c45-0ab7f66a845e.png)

**Comment by imphil** [comment]
@tunghoang290780 It should be easy to fix, would you mind doing a pull request?

In https://github.com/lowRISC/opentitan/blob/master/hw/ip/pwm/data/pwm.prj.hjson the paths need to be relative to the hjson file. Here's an example: https://github.com/lowRISC/opentitan/blob/master/hw/ip/pwm/data/pwm.prj.hjson

Once you've made the changes, you can check if it works by running `util/build_docs.py --preview`

**Comment by tunghoang290780** [comment]
@imphil thanks, PR #6642 is submitted to resolve this issue

**Comment by martin-lueker** [comment]
Thank you @tunghoang290780 and @imphil.  I see that the PR is merged, can we close this then?
