### ISSUE TITLE
[kmac] centralized location for error codes

### ISSUE THREAD

**Issue by udinator** [lowRISC/opentitan#6645]
Hi Eunchan,

Right now, we have `err_code_e` enums in both the `kmac_pkg` and the `sha3_pkg`, both containing a subset of the overall error codes supported by KMAC.

Does it make sense to merge these into a single enum in `kmac_pkg`?
At first glance it seems to make more sense to have these all in a single location (and it prevents DV from having to duplicate and manually stay up-to-date with the error types).

**Comment by eunchan** [comment]
that is actually a little bit tricky. Sha3 can be used as a standalone
primitive design as you see in the EDN (or csrng?). So we cannot combine
the error code in kmac pkg or sha3 pkg.

**Comment by udinator** [comment]
hmm okay - that complicates things a little bit, but is still doable.
Thanks!
