### ISSUE TITLE
[Verilator] AST not instantiated in chip_earlgrey_verilator

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#6656]
This is probably already known, but filing an issue nevertheless because it impacts what tests can be run on Verilator. For example, pwrmgr relies on interactions with AST to get into low power mode. Hopefully we can use this to document a path forward.

**Comment by msfschaffner** [comment]
Yes this is a known issue.
The Verilator TB is not fully aligned with the ASIC TB environment.
See also: 
- https://github.com/lowRISC/opentitan/issues/295
- https://github.com/lowRISC/opentitan/issues/6103

**Comment by tjaychen** [comment]
this one should be working for now. 
I added some minor fixes in the tb such that pwrmgr can go into sleep and power up (needed for another test on verilator).
The underlying issue still isn't solved, but pwrmgr_smoke can at least run.
