### ISSUE TITLE
[DV] failing regressions not reproducable

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#6667]
the nightly regression found a problem in the aes_clear test
![image](https://user-images.githubusercontent.com/53917183/119131295-8f98f380-ba39-11eb-9fea-d77b87c61963.png)

unfortunately, I cannot reproduce these results - I came across this once before and wrote it off as due to code changes.
but I don't think anything changed this time.

it is a problem if we cannot reproduce the results of the regression.
a few questions come up.
where do I see the revision the regression has been run on?
should we not email TB owners when tests fail?

**Comment by rswarbrick** [comment]
Hi Rasmus! Do you still see this sort of thing happen? I remember irritating problems like this a few months ago, but not for a while.
