### ISSUE TITLE
Revisit app_silicon_creator_selfchecking in test_sim_verilator.py

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#6669]
`app_silicon_creator_selfchecking` is currently a separate function in `test_sim_verilator.py` with a different config. We should move the differences between `boot_rom` and `mask_rom` tests to a single config and just use `app_selfchecking` for both cases.

Context: #6550, @imphil's [comment](https://github.com/lowRISC/opentitan/pull/6550#discussion_r636957489).

**Comment by moidx** [comment]
Marking as obsolete as we are moving to Bazel + opentitantool driven test cases.
