### ISSUE TITLE
[alert_handler] FSM and Counter hardening

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#6674]
The FSMs and counters inside the alert handler need to be hardened with sparse encoding / duplication.

CC: @tjaychen @moidx @cdgori

**Comment by tjaychen** [comment]
sounds good to me.
can you remind me was this one of the original review recommendations?

**Comment by msfschaffner** [comment]
In general one of the recommendations was to avoid single points of failure. Hardening FSMs and duplicating counters helps against glitches in general, and makes some FIB attacks more difficult (although, it is hard to completely avoid single points of failure, unless we duplicate the whole alert handler logic).

**Comment by tjaychen** [comment]
sounds good. 
did we already do a survey of where else counters like this need to be hardened? i know aes also did something similar, but i'm betting kmac / key manager / flash all fall into the same category but have not done the same.

**Comment by msfschaffner** [comment]
Yeah I have the feeling that all security IP needs something like this.
Is there maybe a case for making a hardened counter primitive, or are these things "too custom" to turn into a primitive?

**Comment by tjaychen** [comment]
i feel like a hardened primitive would make sense (although to be honest i haven't thought a ton about it in terms of timers).
Otherwise we might end up in a situation where everyone does it slightly differently and that could be problematic later.

@cdgori

**Comment by msfschaffner** [comment]
Yeah it sounds doable, although we may have to prepare 2-3 different flavors, depending on whether it's a up/down counter etc

**Comment by msfschaffner** [comment]
The main FSMs and counters inside the alert_handler have now been hardened (see https://github.com/lowRISC/opentitan/pull/6839 and https://github.com/lowRISC/opentitan/pull/6750).
