### ISSUE TITLE
[dv/sim] dvsim no longer works for regression V1 and V2

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#6686]
Dvsim no longer works for regression sets V1 and V2 - but it does still work for the all option.

I have tested with boch Hmac and AES.
both gives 
![image](https://user-images.githubusercontent.com/53917183/119351332-a8efa900-bca0-11eb-8e27-feabf20a5dbf.png)
on the lastest Master.

**Comment by sriyerg** [comment]
Whoops! I did modify the logic that computes the tests per milestone. I will take a look and fix it soon.

**Comment by sriyerg** [comment]
Fixed wit h#6698.
