### ISSUE TITLE
[topgen] Support for struct field breakout in broadcast signals

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#6713]
We currently broadcast the hardware configuration partition as a struct with individual breakout fields to the consuming IPs in the system like this:

https://github.com/lowRISC/opentitan/blob/d5927724859777c1c1de3a05e36f6f8f533467cb/hw/top_earlgrey/data/top_earlgrey.hjson#L922-L925

This unfortunately creates both many lint warnings and uncovered inputs in DV since not each IP reads all of the bits - hence many unnecessary waivers have to be added.

We should come up with a solution that breaks out these struct fields before connecting them to the IPs.
Possible solutions: enhance the topgen intersignal feature, break out signals manually within the top template.

I will take a look at this shortly.

**Comment by msfschaffner** [comment]
CC @eunchan @sriyerg

**Comment by msfschaffner** [comment]
PR #6716 removes the `otp_hw_cfg_i` broadcast connection from the individual blocks in order to address coverage and lint issues caused by the many unread/dangling input ports.

If we are fine with the manual breakout connections in the top-level template, this issue can be closed after that PR has landed. Otherwise, if we want to be able to specify these connections in the toplevel hjson, some additional topgen / intersig work is needed.

**Comment by tjaychen** [comment]
i'm late to this, but this lgtm.

**Comment by msfschaffner** [comment]
Ok, thanks @tjaychen. I'll close this issue then.
