### ISSUE TITLE
[sw/rom] keymgr advance state and boot policy 

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#6714]
During secure boot, the key manager inputs need to be locked and the state needs to be advanced before jumping into the next code partition.  This raises an issue with the boot policy if a selected boot partition fails to execute and control is returned into the mask ROM. The recommendation is to only configure the key manager after manifest verification is  complete. Any errors after the key manager has been configured should result in a shutdown module escalation.

This issue is to track specification documentation updates and implementation changes.

**Comment by alphan** [comment]
We currently configure the key manager in `mask_rom_boot()` and any returns from this function leads to a shutdown. Thus, I think that this issue can be closed now. PLMK if you think otherwise.
