### ISSUE TITLE
[doc/pwrmgr] Improve technical specification details

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#6754]
Some suggestions for improvement:
- rename wake_status to wakeup_status (consistent with wakeup_en)
- specify what the bits in wake* correspond to
- wakeup_en_regwen should mention it controls wakeup_en
- specify what the bits in reset* correspond to
- reset_en_regwen should mention it controls reset_en
- rename wake_info_capture_dis to wakeup_info_capture_dis and wake_info to wakeup_info for consistency

Theory of Operation says rom hashing can be mediated by pwrmgr, but there are rom_ctrl inputs, and the FastPwrStateRomCheck state waits for rom_good. Should this mention it requires successful rom checks instead, not a maybe?

Slow Clock Domain FSM link to AST interface is broken.

**Comment by tjaychen** [comment]
@matutem great inputs!

so for you second point above, `pwrmgr` technically isn't aware of who exactly is requesting wakeup / resets, since that is more of a top level decision.  Is there any way to just generically verify this?

yes good point, the spec should be updated to say it requires a successful rom_ctrl check.

**Comment by matutem** [comment]
Yes, the pwrmgr tests don't care what is the source of these, so the wakeup and reset bit assignments are not needed. Let's drop this part of the request.

**Comment by matutem** [comment]
Some additional suggestions:
The discussion of power domain handling could be clearer, and could highlight the importance of the main_pd_n bit. Perhaps it should also mention the aon and main domains (it says nothing about the number of power domains), and it is not clear about the power domain for the peripherals: they seem to be aon, with the option of disabling their clock.

It would be good to have some discussion of retention or isolation cell management, or a pointer to some relevant spec at the full chip level.

**Comment by matutem** [comment]
The "Supported low power modes" section fails to mention what triggers deep sleep (main_pd_n). It is also somewhat vague about io power domains: it only mentions disabling the clock (clock gating), not powering units off. Does it mean if the clock is disabled then power will also be off?

**Comment by matutem** [comment]
Most of this issues are already addressed, and some others were dropped, so I consider this done.
