### ISSUE TITLE
[otbn] investigate bn_256 implementation

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#6771]
We should investigate the potential implementation of the Barreto-Naehrig pairing friendly curve (bn_256) on OTBN.

This should cover:
- To what extent can the existing P-256 bit implementation be reduced
- Is the implementation well covered by our current instruction set
- Rough estimation on code size
- Rough estimation on performance

> estimate 8

**Comment by imphil** [comment]
A bit of background: we might need carry-less multiplications to support this curve better, initial evaluation is only if that instruction would be needed.

**Comment by msfschaffner** [comment]
CC @jadephilipoom @moidx 

Is this still an active issue?

**Comment by jadephilipoom** [comment]
I don't think so. It's not on the cryptolib list of algorithms, so it seems like there isn't much demand for this curve. I'll close, others please feel free to reopen if there's a reason to look into this.
