### ISSUE TITLE
Nexys Video fails timing

### ISSUE THREAD

**Issue by wallento** [lowRISC/opentitan#6780]
I have two Nexys Video boards and they seem to be on the slower end of the speed grade, resulting in the fact that they cannot run an OpenTitan system, neither the last from CI nor self built. There are over a hundred failing endpoints on the timing report, which makes that no real surprise.
So, we need to lower the clock(s) and I am wondering if there is some guidance on how to do this in the hjson. Does anyone remember a commit that changed the clock to fix timing before?

**Comment by imphil** [comment]
https://github.com/lowRISC/opentitan/pull/3647 was the last PR where we did decrease the frequency.

**Comment by wallento** [comment]
Timing was not the issue, its borderline but okay
