### ISSUE TITLE
Setting cmd_status to 0 results in interface check never being executed.

### ISSUE THREAD

**Issue by hehgoog** [lowRISC/opentitan#6783]
The loop on [L#59](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/dif/dif_csrng_smoketest.c#L59) never gets run since ` dif_csrng_cmd_status_t cmd_status = {0};` sets `cmd_status`  equal to [`kDifCsrngCmdStatusReady`](https://github.com/lowRISC/opentitan/blob/master/sw/device/lib/dif/dif_csrng.h#L175)

https://github.com/lowRISC/opentitan/blob/50fe3b9fd45fdfb1fa555da66995dfd94023143f/sw/device/tests/dif/dif_csrng_smoketest.c#L58

One alternative is to set 
  `dif_csrng_cmd_status_t cmd_status = {kDifCsrngCmdStatusBusy};` resulting in a check

Another is to use a do..while loop.

**Comment by moidx** [comment]
The do..while loop option sounds good to me.

**Comment by moidx** [comment]
I believe this has been fixed now. Closing as obsolete.
