### ISSUE TITLE
[kmac] Add timer prescaler to EDN wait timer

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#6789]
@mwbranstad reported in #6753 that the EDN IP may return the entropy data in 5ms. Current EDN Wait timer inside the KMAC IP has 16 bit counter. It only can wait about 655us @ 100MHz.

This issue is to create a prescaler so that the KMAC generates `tick_1us` based on SW configuration, and use this `tick_1us` to increase the counter value.

CC: @udinator @cdgori

**Comment by cindychip** [comment]
implemented already.
