### ISSUE TITLE
All SW unit tests are skipped in meson, affecting CI, container workflows, and fresh pip installs

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#6794]
Noticed this after rebasing my changes and rebuilding the container (`util/container`). This seems to be related to #6767 ([CI log](https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=42595&view=logs&jobId=5df5adf8-3577-5927-f0b2-31afed2697ee&j=5df5adf8-3577-5927-f0b2-31afed2697ee&t=1253ba27-4e8c-57af-d0ba-888237644875)) because tests were executed normally in earlier CI runs.

Reverting back to meson 0.54 seems to resolve this issue.

@alistair23 @imphil assigning to you since I don't have enough context around #6767. Unless there is a trivial fix, we should probably revert #6767.

**Comment by alphan** [comment]
@cfrantz @moidx @mundaym @mcy FYI

**Comment by alphan** [comment]
Forgot to mention: `testlog.txt` contains `Not run because can not execute cross compiled binaries.` after each test.

**Comment by imphil** [comment]
Please go ahead and revert the version constraint relaxing in #6767 then. It was thought that the only issue preventing Meson 0.54 from working was a bug that Alistair fixed, but that seems to be not the case. (Of course, I'd be also interested in figuring out what we would need to do to support a newer meson version, but that's a separate issue.)

**Comment by mcy** [comment]
I think it's important to ask:
- Why do we care about newer Meson?
- Is this effort worth it, given that a build system rewrite is imminent?

It seems like this is unnecessary risk for hitherto unjustified gain.
