### ISSUE TITLE
[doc] Missing documentation on the relationship between AST clocks/resets and chip clocks/resets

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#6798]
For example, to which clock the AST entropy clock input is connected? Is AST ADC reset input connected to vcaon_pok or to vcmain_pok?

**Comment by tjaychen** [comment]
@zi-v 
where is the most appropriate place to document something like this?

**Comment by zi-v** [comment]
IMO, clkmgr and rstmgr

**Comment by tjaychen** [comment]
those modules technically don't have any idea of what the top level
connections are..
i feel like this should go into top level documentation (which has not been
updated for awhile).

Maybe i will add something there for now, does that sound okay to you?

**Comment by zi-v** [comment]
Thanks Tim.
For us, mainly for DV, it is not crucial where exactly it is documented. We mainly want to use this data to narrow down the DV scenarios of which reset is active when and so

**Comment by tjaychen** [comment]
The document is [here](https://docs.google.com/document/d/14zni9BzxuWLWObSZSdF_SAnnu1ZFYNE4aYp2k3dKBuc/edit?usp=sharing), however it has not yet been converted to markdown.

**Comment by msfschaffner** [comment]
@tjaychen @zi-v has this been addressed in the meantime?

**Comment by tjaychen** [comment]
Yeah the document was created some time ago and reviewed.
But it's not been added to any markdown yet. The best place to do it is probably `top_earlgrey.md`.
That update is...coming.
