### ISSUE TITLE
[dv/testplanner] allow automated test names to be prefixed

### ISSUE THREAD

**Issue by udinator** [lowRISC/opentitan#6803]
This issue arises from a discussion on #6799.

For IPs that have several compile-time configurations (or "variants") that are individually tested, such as KMAC, our approach right now to map tests is to use a unique `variant` string to prefix each manually written test name (e.g. `kmac_unmasked_smoke` and `kmac_masked_smoke`).

However, dvsim and the testplanner utilities do not like when we try to prefix the automated test names as well by using an updated `name` field in the variant testplans.

We should update these to allow prefixes to be added to automated test names for consistency.

**Comment by cindychip** [comment]
I believe weicai already had a pr to solve this, and merged for nightly.
