### ISSUE TITLE
[sw/silicon_creator] Defining manifests in assembly may cause issues if boot stages access their own manifests

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#6814]
#6727 replaces the MMIO-based manifest parser with a struct and adds `manifest.S` for defining the manifest sections of boot stage images stored in flash. The main reason to use an .S file was to ensure that the sizes of the manifests of boot stage images and the size of the corresponding struct defined in C match. @mcy raised a [concern](https://github.com/lowRISC/opentitan/pull/6727#discussion_r644907999) that
> this generates a TU that LLVM could potentially look at, and perhaps optimize all manifest accesses out to zero.

While boot stages don't access their own manifests right now, we should be aware of this potential issue if this changes in the future.

**Comment by moidx** [comment]
Closed by #11990
