### ISSUE TITLE
[rtl/pwrmgr] Clear low_power_o on failed transitions

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#6819]
The output low_power_o is set in state FastPwrStateDisClks for non-reset transitions into low power.
However, it is not cleared in cases that don't complete the transition: either lc, otp, of flash not idle in
FastPwrStateNvmIdleChk, or when the processor is not sleeping in FastPwrStateFallThrough.

This output is connected to u_aon_timer_aon and u_pinmux_aon.

**Comment by tjaychen** [comment]
i believe this one should be fixed now. @matutem feel free to re-open if you see more issues or don't agree.
