### ISSUE TITLE
[kmac] incorrect CmdProcess during manual squeezing causes assertion error

### ISSUE THREAD

**Issue by udinator** [lowRISC/opentitan#6843]
Hi Eunchan,

I'm seeing this scenario when I incorrectly write a `CmdProcess` instead of `CmdManualRun` to test error behavior:

![Screenshot from 2021-06-04 14-39-59](https://user-images.githubusercontent.com/16736281/120865376-c7785e80-c542-11eb-8f47-7076de6d1568.png)

In this scenario, `CmdProcess` has already been written by SW to produce the initial digest, but manual squeezing is required.

Instead of writing `CmdManualRun`, the test sequence writes `CmdProcess` again - this causes the `PackerDoneValid_a` assertion in the `kmac_msgfifo` to fire, as it is not expecting to see `process_i` during the `FlushClear` state.

Should this assertion be removed, as the new error checking logic in #6753 will handle SW command sequencing?

**Comment by eunchan** [comment]
I think the solution is quite similar with #6842 If we block the incorrect command, the MsgFIFO won't catch the assertion.

**Comment by udinator** [comment]
hmm, that makes sense to me.

**Comment by udinator** [comment]
Adding @cindychip  for visibility.
