### ISSUE TITLE
Nexys A7 board for opentitan

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#6857]
Hi 
Is it possible to use Nexys A7 board instead of Nexys video as target fpga for the opentitan on FPGA?
If yes, could you please hint the procedures to do it.

Thanks a lot.

**Comment by imphil** [comment]
Hi @nicolast0604, thanks for your interest in OpenTitan. 

The A7 board isn't currently usable in OpenTitan, as the earl grey toplevel design is much too large. You'll need to produce a toplevel which removes some functionality, reduces memories, etc.

The top_earlgrey example is a starting point for such an approach, but you'll see quickly that the tooling around that is rather fragile at the moment. 

We intend to improve the tooling to make it easier to produce customized toplevels for smaller FPGA boards, initial work is available at #5636 and #5782. It will take a couple more weeks before we have the bandwidth to push this work over the finish line, however.

So for now, I'd suggest you start with top_englishbreakfast and try to reduce it until it first onto the A7 board. Doing so will require a bit of experience with FPGA board bringup, so if you haven't done that before I'd recommend going with a Nexys Video board instead.

**Comment by msfschaffner** [comment]
I believe this question has been addressed. Feel free to reopen if that is not the case.
