### ISSUE TITLE
[doc, sysrst ctrl] Update design spec

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#6873]
The design spec (the md file checked into the repo) is considered the source of truth. Some pieces of information is currently missing, but can be found in other docs such as the one pagers below:
https://docs.google.com/document/d/1LgPRkYrpIgT-7VZhlfSrjTzWcUeVC2VKDnJ8xna655o
https://docs.google.com/document/d/1HAcTabepsQyDW_b8Vv-IZyhpf74jBUVAMstdvVkIdoQ

Filing an issue to track the design spec for completeness.

**Comment by weicaiyang** [comment]
@msfschaffner has updated the spec
