### ISSUE TITLE
Power-up request questions

### ISSUE THREAD

**Issue by tomroberts-lowrisc** [lowRISC/opentitan#6909]
Looking at the AON Timer, we currently create a power-up request signal based on either of the interrupts firing then latch it until SW writes to a register to "acknowledge" the power-up.

The DIF currently doesn't do the acknowledgment, and it seems a bit strange to me for SW to have to do this. Two possible alternatives:
- Latch the wakeup request until the sleep input goes away then clear it in HW.
- Base the wakeup on the interrupt lines (clearing the interrupt also clears the wakeup).

There are some other wakeup sources coming soon (adc and sysrst) which will have to do something similar. Any thoughts on this from a HW/SW perspective?

**Comment by silvestrst** [comment]
> Looking at the AON Timer, we currently create a power-up request signal based on either of the interrupts firing then latch it until SW writes to a register to "acknowledge" the power-up.

Which register do you mean? I assume it is not `aon_timer.INTR_STATE`, because you are saying:
> The DIF currently doesn't do the acknowledgment, and it seems a bit strange to me for SW to have to do this

Does it mean that `dif_aon_timer_smoketest.c::aon_timer_test_wakeup_timer` is not correctly handling the wake-up interrupt, or this is not an interrupt specific issue but a more general?

**Comment by silvestrst** [comment]
Thanks for clarifying I think both alternatives that you have specified are good. I think it probably depends whether we need to know or not what caused the wake-up. If not then first bullet-point is nicer from SW perspective, otherwise the second bullet-point.

This is from my perspective, but @cfrantz might have a more informed opinion.

**Comment by tomroberts-lowrisc** [comment]
@tjaychen What the aon timer currently does seems to be in-line with what the sysrst block also does (SW visible register which SW must "ack" to drop the level wakeup signal).

If there's no further input on this I'll consider the current approach OK and proceed with D2 prep for the aon timer.

**Comment by tjaychen** [comment]
sounds good, thanks Tom.
