### ISSUE TITLE
[verible lint] Broken in nightly runs 

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#6927]
Here's the report:
https://reports.opentitan.org/hw/top_earlgrey/lint/veriblelint/summary.html

Seems like we need to update the Verible version.

**Comment by sriyerg** [comment]
@msfschaffner, would you please TAL?

**Comment by msfschaffner** [comment]
Thanks for spotting this. I thought we made sure this is aligned when the update went in https://github.com/lowRISC/opentitan/pull/6434.
@eunchan is running the nightlies at the moment. can you take a look why this fails?

**Comment by eunchan** [comment]
OK. I will update the veriblelint tool.

**Comment by eunchan** [comment]
Hum.. looks like I already installed 1213 version in my workstation. Figuring out why it points to the old version

**Comment by eunchan** [comment]
Fixed. Looks like the old build files affected the new build. cleaned out the repo and re-built the verible.
