### ISSUE TITLE
[otp_ctrl] part_init_done is set to 0 during FSM state error

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#6937]
Hi Michael,

I would like to confirm if it is your intention to drop `part_init_done` signal during FsmStateError
after otp_init is done.
The issue is coming from a top-level sequence, where I find that an OTP check timeout error can 
immediately trigger `lc_escalation_en`.
I wonder if this contradicts the purpose of this PR: https://github.com/lowRISC/opentitan/pull/6889?

Here is the entire sequence:
1). OTP init done, LC init done, LC in RMA state.
2). OTP timeout set to 1 and timeout failed.
3). `tp_lc_data_i.valid` is reset to 0.
4).`state_invalid_error_o` is set and `lc_escalation_en` is triggered.

Here is the screenshot:
![image](https://user-images.githubusercontent.com/11466553/121729986-f1ca9e80-caa3-11eb-821f-64f700a9b65b.png)

**Comment by msfschaffner** [comment]
Good catch - that can indeed be a problem.
I've changed this slightly such that the part init signals are not deasserted anymore, once a partition has initialized: https://github.com/lowRISC/opentitan/pull/6938

**Comment by msfschaffner** [comment]
Hm... I am starting to think we should simplify the escalation behavior instead of making this more complex by adding more corner cases. Maybe it makes sense to just combine "escalate_en" (wipe secrets) and "lc scrap" for simplicity. Let me think about this a bit more.

**Comment by msfschaffner** [comment]
OK, I have changed the escalation behavior in https://github.com/lowRISC/opentitan/pull/7014, so I think this issue will become obsolete after that change has landed.
