### ISSUE TITLE
[i2c] Width mismatch

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#6950]
I am seeing the DC elab error:

    Error: Width mismatch on port 'fmt_fifo_depth_i' of reference to 'i2c_fsm' in 'i2c_core_2'. (LINK-3)

**Comment by martin-lueker** [comment]
Thanks @eunchan.  @igk8 is this something that is covered in #6841?

**Comment by eunchan** [comment]
Thanks @martin-lueker . Looks like that PR is addressing this issue :)

**Comment by igk8** [comment]
Yes, this is covered in #6841 . Thanks
