### ISSUE TITLE
[mask_rom] Debug alert handler functest on an FPGA board

### ISSUE THREAD

**Issue by cfrantz** [lowRISC/opentitan#6965]
The alert handler functest fails in CI on the FPGA boards.

I suspect this is because the test resets the chip and may require some additional support in the test infrastructure for such tests (ie: as imphil suggested, re-opening a uart or somesuch).

**Comment by drewmacrae** [comment]
This doesn't occur when the test is run with bazel

**Comment by drewmacrae** [comment]
There is however, a TODO that points to this issue in systemtest/config.py for the watchdog functest which is marked as broken for the cw310
