### ISSUE TITLE
[top,dv] Add system-level test for faulted rom_ctrl reset

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#6976]
We should probably have a test that checks that a faulted reset line to `rom_ctrl` (causing it to run a second time) causes an alert to be fired. I expect this to be noticeable by either the power manager (which will see an unexpected negative edge on the "done" signal) or KMAC (which will see an unexpected second transaction on its application interface).

We could either do this "for real" at a system level by forcing `rom_ctrl`'s reset line, or add it to a block-level test on one of the blocks listed above. @sriyerg: Where do you think is the best place to do this?

This came from some review comments from @cdgori on #6899. It might actually be on a testplan already (in which case, it's going to be quick to close!). But I'm not sure, so thought I should raise it.

More generally, do we have a plan for "unexpected resets" from all blocks? It seems like we should at least be documenting what we expect to happen and how we expect to see things at a system level.

**Comment by sriyerg** [comment]
Yes: https://docs.opentitan.org/hw/top_earlgrey/doc/dv/#dv-plan
Search for 'chip_rom_ctrl_reset_glitch'.

Feel free to update the wording if needed.

**Comment by cdgori** [comment]
great, thank you @rswarbrick for writing this up and @sriyerg for already having this in test plan.

**Comment by sriyerg** [comment]
Re. your question on reset tests - it should be captured as a part of the [system level scenarios testplan](https://docs.google.com/spreadsheets/u/2/d/1YK3mO9n5xyjT6cIPlW1bixcNVMj833XQfKXPPXvUw78/edit#gid=0) (which will eventually get folded into the chip DV plan).

**Comment by rswarbrick** [comment]
Brill, thanks!
