### ISSUE TITLE
How to write back to the original top_earlgrey.hjson file after auto modefied by script top_earlgrey_reduce.py ?

### ISSUE THREAD

**Issue by JunminHe** [lowRISC/opentitan#6996]
Hello,
        I am trying to use the opentitan on  NexysVideo FPGA Board . When I deploy size reduction script top_earlgrey_reduce.py , the top_earlgrey.hjson auto changed , but when I want to edit the original top_earlgrey.hjson for configuring i2c inputs and relate pads , I am not sure how to write back to the original top_earlgrey.hjson file after auto modefied by script top_earlgrey_reduce.py ?  Can you give me some tips  for this question?
![issue](https://user-images.githubusercontent.com/73106972/122231562-1af88e00-ceed-11eb-89d5-31bde3542d28.png)

      Thank you !

**Comment by imphil** [comment]
Just revert the changes in your working directory using `git checkout -- FILENAME`, as the message indicates.

**Comment by JunminHe** [comment]
Thank you for your help ~

**Comment by JunminHe** [comment]
Hello, @imphil , when I edit some ports in the top_earlgrey.hjson file, and deployed size reduction script top_earlgrey_reduce.py, a new top_earlgrey.hjson file was auto-generated, but when I want to add something in the top_earlgrey.hjson that I had previously hand-edit, how to undo the changes brought by the top_earlgrey_reduce.py script and write it back to the version before the script was executed?
