### ISSUE TITLE
Wire up integrity alerts

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#7003]
Thanks @msfschaffner for connecting integrity alerts for most of the IPs. I created this list to keep track of the unconnected blocks

- [x] adc_ctrl
- [x] aes
- [x] alert_handler
- [ ] aon_timer
- [ ] clkmgr
- [x] csrng
- [x] edn
- [x] entropy_src
- [ ] flash_ctrl
- [x] gpio
- [x] hmac
- [x] i2c
- [x] keymgr
- [x] kmac
- [x] lc_ctrl
- [ ] otbn
- [ ] otp_ctrl
- [x] pattgen
- [x] pinmux
- [ ] pwm
- [ ] pwrmgr
- [ ] rom_ctrl
- [ ] rstmgr
- [ ] rv_plic
- [ ] rv_timer
- [x] spi_device
- [x] spi_host
- [x] sram_ctrl
- [ ] sysrst_ctrl
- [x] uart
- [ ] usbdev

@sriyerg @matutem @cindychip

**Comment by msfschaffner** [comment]
Hey @weicaiyang, thanks for filing this, but we've already been keeping track of this here ;) : https://github.com/lowRISC/opentitan/issues/5985. So I am closing this because it's a duplicate issue.
