### ISSUE TITLE
[otbn] Grant signals on scrambled memories

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#7021]
The scrambled memory primitive `pram_ram_1p_scr` introduces a grant signal for requests.

OTBN doesn't currently deal with stalling on its memory request interface, it assumes any request is granted.

The scrambled memories only don't grant where there isn't a valid key or a memory initialization using an LFSR is in progress.

Rather than altering OTBN to deal with stalls here I think we're better off assuming requests will always be granted when OTBN is running. Though we want some kind of backstop to ensure this will be the case. A couple of things spring to mind:

1. Stall OTBN start until a valid key is available or immediately produce an error if you try to start OTBN without a valid key
2. Produce an error from OTBN if a request isn't granted

I'd say we'd want both 2. would effectively only occur if there was a hardware bug but better than OTBN fails in that case rather than silently doing something incorrect.

> estimate 1

**Comment by rswarbrick** [comment]
Maybe a simpler approach would be that we don't rotate keys when OTBN is actually running instructions. So writes to the "rotate my key please" register are ignored while it's running and "start" stalls until the memories are ready.

If we're doing key rotation on failure as a sort of secure wipe, we might need an "almost finished" state, where OTBN is no longer running instructions but hasn't yet told the host that it's done.

**Comment by msfschaffner** [comment]
I like 1. a bit better. I.e., it would be good to get some feedback from HW when you try to request a key while OTBN is running, since otherwise you don't really know whether a key request has successfully completed, or whether it has just been ignored.

Btwy, what happens when Ibex is trying to access the Dmem and Imem while a key request is pending?

As a side note: if EDN has not been initialized before triggering a key request, the key request will hang forever. However, this is a constraint SW should be aware of already, since the SRAM controller key requests have the same limitation (and I guess this applies to 
 OTBN entropy fetch as well?).

CC @cdgori @tjaychen

**Comment by tjaychen** [comment]
yeah i think some form of stall handling is inevitable. 
I think the normal sequence of events would be 

request scramble key rotation -> write into imem / dmem -> start.

So it seems like the start stall is not the case where you will run into issues. 

I think it's okay to construct by policy that if a rotation is ongoing, then all accesses are errors.  Then you wouldn't necessarily need to handle the stalls, although you still would have to feed the error condition into the tlul adapters probably.

**Comment by GregAC** [comment]
> Btwy, what happens when Ibex is trying to access the Dmem and Imem while a key request is pending?

It won't get a grant til it's done, which is a point worth raising as I think sram behaves similarly. We might want to return an error response instead as a situation where Ibex reading a memory location that hasn't been configured correctly (i.e. EDN not on with pending key request) leads to a system deadlock isn't great. Even NMI would wait for a pending memory access to complete so if it never completes we'd never enter an NMI/alert handler. The watchdog will eventually hard reset things of course and the crash dump should at least point to the hanging load or store.

**Comment by rswarbrick** [comment]
The question about access to memory while OTBN is running is handled in the somewhat stalled issue #2696. I think that, whatever we decide there, we should make the same decision here.

**Comment by tjaychen** [comment]
i think from that issue we also settled on errors correct? If that's the case, it seems consistent with the behavior here.
I would also go with otbn error-ing if key rotation is ongoing and any external agent tries to access.

I guess if you couple this with start stall, it would also ensure otbn's processor could never reach this case right?

**Comment by cdgori** [comment]
If I understood @GregAC 's original comment, he suggested doing both?  Which matches Tim's comment:

| I guess if you couple this with start stall, it would also ensure otbn's processor could never reach this case right?

And is basically what I would suggest.  Stall the start until the keys are loaded, but also fatal-error if a grant is not given for some reason.

**Comment by msfschaffner** [comment]
Ok, error-ing out sounds like the consistent solution then (i.e., also error out when an external agent tries to access OTBN memory while OTBN is busy, or a key request is ongoing).

It probably makes sense to carry that behavior over to the SRAM controller as well (https://github.com/lowRISC/opentitan/issues/7059).

**Comment by msfschaffner** [comment]
We've discussed this in our security design meeting and settled on the following:
- external accesses to OTBN memory shall stall if there is a pending key request (same behavior as for SRAM accesses).
- if OTBN is started and memory accesses are not granted immediately by the scrambled OTBN memory - produce an error and stop.
- a CSR should be added that allows software to 
  - spin wait while a key request is pending.
  - double check the key request has completed before initiating an OTBN operation. 
 
@GregAC @rswarbrick please amend if needed.

**Comment by rswarbrick** [comment]
Yep :-)

**Comment by tjaychen** [comment]
nothing sounds better than something... especially since we will also have software redundancy.
Do you want to run this by the lowrisc side internally? I'm honestly good with what you've described here.

**Comment by rswarbrick** [comment]
@GregAC: Maybe this would be good for Monday's planning meeting? (@tjaychen: I'm actually on holiday next week, so I look forward to coming back and seeing what happened!)

**Comment by tjaychen** [comment]
@rswarbrick enjoy your vacation!

**Comment by GregAC** [comment]
We shall leave this as is (no specific functionality to poll if a key rotation is occurring as existing OTBN busy status suffices).
