### ISSUE TITLE
[keymgr] Mismatch between "rc" in hjson and RTL behaviour for SW_SHARE*_OUTPUT reg

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#7041]
The `SW_SHARE0_OUTPUT` and `SW_SHARE1_OUTPUT` multiregs are listed in the hjson as having software access type RC ("read clears"). This doesn't seem to be what the RTL actually does: a read from the register doesn't cause the value to be zeroed.

Either the RTL needs updating to match the hjson or the hjson needs the "rc" entries changing to "ro".

@tjaychen: Could you comment on what's supposed to happen? (I'm happy to make the changes if you're busy, but can't really fix it without knowing which way to go)

**Comment by tjaychen** [comment]
hey rupert, could you point me to where you might have run into this?
The register is built using the automated script, so at least inside the
regfile the behavior should be read clear.

I think where things could get odd is how the hardware feeds the value.
Where if we happen to be in the "wipe key" state, the value will constantly
update to a random value even though the software requests for it to be
cleared.
Is that what you are seeing?

**Comment by rswarbrick** [comment]
Gah, this was caused by a bug in my proposed change (I should have been setting a `we` using the `re` because it was an `RC` register). Thanks for helping me figure out what was going on!
