### ISSUE TITLE
[otbn,rtl] insn_cnt_o doesn't follow spec just after operation starts

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#7052]
The following waveform shows what's going on (extracted from `util/dvsim/dvsim.py hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson -i otbn_multi --fixed-seed 2100792378 -w` after disabling the failing assertion):

![ss](https://user-images.githubusercontent.com/104845/122788839-a5a30980-d2ae-11eb-9455-0a079ac1a8e4.png)

The spec currently says that INSN_CNT gets zeroed at the start of an operation, then counts up each time an instruction gets executed. Unfortunately, the `start_i` input on the controller is delayed, so the counter doesn't get zeroed immediately. In this particular test, an assertion that the RTL and ISS agree about INSN_CNT fails for the period between the assertion of `start_i` and when the `insn_cnt_o` signal shown goes from `32'hb` to zero. This would be observable to software that read the INSN_CNT register in that period.

The quick fix is to pass an un-delayed version of the `start_i` signal to the controller and use that to control when the counter gets reset. @GregAC: Does that sound like a good approach, or can you see a cleaner way to fix things?

@vrozic as the author of the instruction counter, but I think this is probably more a "system integration" question.

**Comment by GregAC** [comment]
The `start_i` reaching the controller is delayed by the `otbn_start_stop_control` module.

Perhaps a `controller_reset_insn_cnt_o` signal from `otbn_start_stop_control` that resets the counter that's raised when `start_i` is seen?

**Comment by rswarbrick** [comment]
Yep, sounds sensible. Looking again at what I wrote, it was a bit ambiguous: I meant passing an extra un-delayed signal, not removing the delay!
