### ISSUE TITLE
[otbn] Scrambling nonce width from OTP

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#7054]
The OTP provided nonce for scrambling OTBN memories is 256-bit wide.

With integrity protection OTBN requires 320 bits of nonce when using replicated PRINCE primitives to generate the keystream. Potentially nonce bits could be reused to give the full 320 bits.

Alternatively a single PRINCE could be used and the keystream replicated, requiring 64 bits of nonce.

What do we want to do?

**Comment by msfschaffner** [comment]
I think we have been discussing that for this particular use case, replicating the keystream of one PRINCE primitive should be good enough.

I.e. we are mainly guarding against FI, and that can be achieved with both replicated and unreplicated keystream.

Am I remembering correctly, @tjaychen @cdgori?

**Comment by tjaychen** [comment]
yeah i agree with @msfschaffner . since this is mostly meant for FI protection, i think replicating the keystream is sufficient.
@msfschaffner also pointed out this could simplify the nonce requesting interface on the otp side, which would be a nice plus.

**Comment by msfschaffner** [comment]
OK, great! The OTP nonce width changes are implemented in #7144.

**Comment by msfschaffner** [comment]
The PR has been merged, so I think we can close this now.
