### ISSUE TITLE
[sram_ctrl] Should it be possible to configure retention SRAM as executable?

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#7107]
In the `chip_sram_execution` test in the [DV test plan](https://docs.opentitan.org/hw/top_earlgrey/doc/dv/) it is mentioned that *both* SRAMs should be executable when configured as such:

> Verify that CPU can fetch data from both SRAMs when in executable mode.
> * Load instruction data into the SRAMs.
> * Configure main/ret SRAMs to allow instruction execution.
> * Have the CPU fetch the instruction data from the SRAMs and verify that SW can finish the test successfully.

I tried to enable execution through the retention RAM controller when writing a verilator test for the mask ROM PMP implementation and could not get it to execute an instruction (main RAM worked fine). It is possible there is a bug in my code but I am fairly confident that I at least enabled it correctly (I verified that `sram_ctrl.EXEC` was set to the magic value 5).

Any thoughts? Should it be possible to configure retention RAM to be executable? If not, should `sram_ctrl.EXEC` and `sram_ctrl.EXEC_REGWEN` be hardwired to 0 for the retention RAM?

**Comment by tjaychen** [comment]
ah you're right.
I dont think the retention sram is meant to be executable.
This is probably something outdated we need to update.

**Comment by cdgori** [comment]
> ah you're right. I dont think the retention sram is meant to be executable. This is probably something outdated we need to update.

I think even more than that, when we reviewed the retention SRAM plan some long time back, I think it's expressly not supposed to be executable.
