### ISSUE TITLE
[mask_rom] What bounds should be used for the MMIO memory protection region?

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#7117]
The memory protection specification (https://github.com/lowRISC/opentitan/pull/6959) specifies that one ePMP entry should be used to provide read/write access to the entire MMIO address space.

However as far as I can tell there are currently no auto-generated addresses that specify the bounds of the address space. To workaround this I've temporarily hardcoded the address space as `[0x4000_0000, 0x5000_0000)`. I think that a higher upper bound would also be reasonable: `[0x4000_0000, 0xFFFF_FFFF]`.

Should we stick with hardcoded addresses or should we auto-generate/specify them instead? Are there any existing constants that we could use to derive these constants?

**Comment by felixmiller** [comment]
This issue has been discussed in the Security WG meeting on 2021-09-16. Group feedback:

- The current layout of the peripherals makes it difficult to lockdown a particular set of MMIO regions.
- @rswarbrick: If reordering makes sense, we can totally do that. 
- @tjaychen: The current memory layout is ordered by clock domain almost. If we want to group them by hierarchy that is probably ok too. 
- This is related to #8220 
- Action Items: 
  - Look at generating some bounds for MMIO.
  - Look into the TockOS use case.
