### ISSUE TITLE
[spi_device] Only mode 0 (CPOL=0, CPHA=0) works

### ISSUE THREAD

**Issue by wallento** [lowRISC/opentitan#7136]
I added a second SPI device. Please find the commit here: https://github.com/wallento/opentitan/commit/75c827987be1d6aed41acecd11872aeff7606080
I am using this new device from my code in OT and it works nearly as expected ;) Unfortunately I cannot get it to work properly and I am running out of ideas. I am interfacing this second device from a Particle Argon and send a sequence "TEST" (`0x54 0x45 0x53 0x54`) to OT. Here is what I can see on my oscilloscope:
![SCR02](https://user-images.githubusercontent.com/299017/123419780-efdfff80-d5ba-11eb-9357-eedb8e0403c3.PNG)
Beautiful! The "SPI!" is sent from the example code which is a redacted version of hello world: https://github.com/wallento/opentitan/commit/75c827987be1d6aed41acecd11872aeff7606080#diff-c4e69f5c1a45c63b4541776f6921a4ce9e64aa1f77cf4e47ce412e1b45a96a56L77
So this direction seems to work well, I also read the sequence `0x53 0x50 0x49 0x21` from the buffer on my device.
But reading the buffer from the software in OT is odd. Here is the simple code I added: https://github.com/wallento/opentitan/commit/75c827987be1d6aed41acecd11872aeff7606080#diff-c4e69f5c1a45c63b4541776f6921a4ce9e64aa1f77cf4e47ce412e1b45a96a56R73
What I am expecting is to read the `0x54 0x45 0x53 0x54`. Framing also works properly, but what I actually get is:
```
[13:43:50:836] I00000 hello_world.c:65] Hello World!␍␊
[13:43:50:836] I00001 hello_world.c:66] Built at: Jun 25 2021, 13:32:18␍␊
[13:43:52:197] I00002 hello_world.c:78] SPI: 1␍␊
[13:43:52:197] I00003 hello_world.c:80] 2a␍␊
[13:43:52:197] I00004 hello_world.c:78] SPI: 3␍␊
[13:43:52:197] I00005 hello_world.c:80] 22␍␊
[13:43:52:197] I00006 hello_world.c:80] a9␍␊
[13:43:52:197] I00007 hello_world.c:80] aa␍␊
```
At first glance it looks like some leftover uninitalized buffer gibberish, but actually it is the expected data *shifted by one bit*.

```
sent:     01010100 01000101 01010011 01010100
sent>>1:  00101010 00100010 10101001 10101010
received: 00101010 00100010 10101001 10101010
```
Obviously I played around with the SPI modes endlessly already (its mode 1 by the way), but I cannot get it working. What am I missing? SPI clock speed is 1 kHz by the way.

**Comment by wallento** [comment]
Okay, after some more experiments I think I am sure that only SPI mode 0 works. I can confirm it does work, I assume I messed something up in testing. May I suggest while fixing this to fix the abstraction naming: `kDifSpiDeviceEdgePositive` and `kDifSpiDeviceEdgeNegative` is probably not the right naming for polarity and phase shift. The actual edges of data assertion on the out side and data sampling on the in side are a derivative of polarity and phase.

**Comment by wallento** [comment]
To complete the experiments:
- `CPOL=0`, `CPHA=0` works as expected
- `CPOL=0`, `CPHA=1` input is shifted by a bit to the lsb, output works as expected
- `CPOL=1`, `CPHA=0` input works as expected, output is shifted by a bit to the msb
- `CPOL=1`, `CPHA=1` input is shifted by a bit to the lsb and output is shifted by a bit to the msb

**Comment by sriyerg** [comment]
@eunchan, @weicaiyang

**Comment by sriyerg** [comment]
Note that SPI device IP is not fully verified - it is still in the V1 stage.

**Comment by weicaiyang** [comment]
@wallento 
I dumped a wave for `CPOL=0, CPHA=1`
![Screen Shot 2021-06-28 at 10 49 43 PM](https://user-images.githubusercontent.com/49293026/123744143-2c358900-d863-11eb-8476-13750cc6ce54.png)

here is the gold wave we refer to.
https://en.wikipedia.org/wiki/Serial_Peripheral_Interface#/media/File:SPI_timing_diagram2.svg

I feel the wave I dumped matches to the gold wave. data starts at rising edge and can be sample at falling edge. Please let me know if you find any problem in this wave. Thanks

**Comment by wallento** [comment]
Yes, as I wrote, the output direction works for mode 1. *But* the input direction does not read it properly, it seems the serial-2-parallel samples delayed. Did you confirm you read correctly? Can you confirm output is broken for `CPOL=1` too?

**Comment by wallento** [comment]
# Software Test Setup

```c
  // Add DATE and TIME because I keep fooling myself with old versions
  LOG_INFO("Hello World!");
  LOG_INFO("Built at: " __DATE__ ", " __TIME__);

  CHECK(dif_spi_device_send(&spi, "SPI!", 4, /*bytes_sent=*/NULL) ==
        kDifSpiDeviceOk);
    
  while(1) {
      uint8_t data;
      size_t received;
      CHECK(dif_spi_device_recv(&spi, &data, 1, &received) ==
            kDifSpiDeviceOk);
      if (received > 0) {
          LOG_INFO("SPI: %02x", data);
      }
  }
```
# `CPOL=0, CPHA=1`

![SCR06](https://user-images.githubusercontent.com/299017/123821946-250e8980-d8fc-11eb-9182-98711813f370.PNG)

Looks great, but what OT reads: :-1:

```
[16:58:40:226] I00002 hello_world.c:77] SPI: 29␍␊
[16:58:40:248] I00003 hello_world.c:77] SPI: a8␍␊
[16:58:40:248] I00004 hello_world.c:77] SPI: 24␍␊
[16:58:40:248] I00005 hello_world.c:77] SPI: 90␍␊
```

But it sends right, what I read:  :+1: 

```
53 50 49 21
```

# `CPOL=1, CPHA=0`

![SCR07](https://user-images.githubusercontent.com/299017/123822431-8fbfc500-d8fc-11eb-876c-8ffd848c5bc5.PNG)

The MSB is missing. :-1:

But at least it reads correct: :+1: 

```
[17:00:39:730] I00002 hello_world.c:77] SPI: 53␍␊
[17:00:39:730] I00003 hello_world.c:77] SPI: 50␍␊
[17:00:39:752] I00004 hello_world.c:77] SPI: 49␍␊
[17:00:39:752] I00005 hello_world.c:77] SPI: 21␍␊
```

But I read what the scope shows: :-1: 

```
a6 a0 92 42
```

# `CPOL=1, CPHA=1`

![SCR08](https://user-images.githubusercontent.com/299017/123822634-c1d12700-d8fc-11eb-9c83-67e5a9c2ff62.PNG)

The device should present the MSB with the falling edge, but it seems it skipped the first :-1: 

And it also reads incorrectly: :-1:

```
[17:02:03:273] I00002 hello_world.c:77] SPI: 14␍␊
[17:02:03:295] I00003 hello_world.c:77] SPI: d4␍␊
[17:02:03:295] I00004 hello_world.c:77] SPI: 12␍␊
[17:02:03:295] I00005 hello_world.c:77] SPI: 48␍␊
```

Because it sends incorrectly, I also read incorrectly: :-1: 
```
a6 a0 92 42
```

# Summary

`CPHA=1` is broken on the input path. The sampling seems incorrect, because its the correct data shifted.

`CPOL=1` is broken on the output path. Phase is correct, but all bits are one cycle too early.

**Comment by weicaiyang** [comment]
@wallento thanks for sharing the waveforms. Can you also add the `csb` input signal to the wave? `csb` affects the design sample and output. We can focus on the setting `CPOL=0, CPHA=1` first.

**Comment by wallento** [comment]
Ha, that was indeed the issue. I need to properly frame the transfer, the falling edge of CSB was way too early and never re-asserted. Thanks for pointing that out!

**Comment by weicaiyang** [comment]
Great. Thanks for the update. LMK if you see any other issue on spi_device.
