### ISSUE TITLE
Eclipse embedded CDT

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#7137]
Can opentitan nexys video FPGA work with Eclipse for debugging or trace code  in openocd/GDB?

If yes, do I need specific JTGG cable or something like that ?

Thanks a lot.

**Comment by nicolast0604** [comment]
Is this the solution?
https://eclipse-embed-cdt.github.io/debug/openocd/riscv/

**Comment by spequer** [comment]
@GregAC Is there any reference  of the VSCode IDE ?

**Comment by johngt** [comment]
@GregAC - I don't think that we support this in the reference OT platform?
Marking as closed - however please feel free to re-open it if it is still relevant.
