### ISSUE TITLE
[kmac/keymgr] kmac masking dependency and keymgr correctness

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7149]
It turns out that if kmac masking is not enabled (via parameter), keymgr can't function at all because one of the shares coming back is always 0.  

This causes keymgr to fire off its kmac data invalid check and just completely disables the key manager.
We probably need to pass the same parameter information to keymgr also to ensure that the two sides are consistent.

This also brings up the question if this kind of data error really should be considered "fault" in the keymgr.  It's probably to leave as is right now, but could be difficult to debug if we ever run into it. It might be better for keymgr to disclose more fine grained errors.

**Comment by vogelpi** [comment]
Hey @tjaychen ,
you probably already know this and I also noticed that you have some comments around the `valid_data_chk` function in keymgr saying that it's not yet final. But just to be sure: an all-0 share is indeed valid. It's very unlikely but it is possible to get that. Also, it is theoretically possible that one share of two subsequent runs is the same.

What you could do is some hashing (every share separately) and then compare the hashes across say two or three runs.

**Comment by tjaychen** [comment]
@vogelpi did you mean inside the HW? The unfortunate part right now is that some of the keymgr derivation cannot be seen by software.  So to hash it and compare across (to make sure the derivation was not faulted), would require some change to saving the value and re-comparing it.

At the moment we're not doing that for keymgr since we're relying on the same principle that something is hard to glitch to the same value twice, so then software would simply run the operation again (without being able to observe the values).
