### ISSUE TITLE
[sw] Make Rust a mandatory dependency

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#7159]
Right now Rust is an optional dependency. Build targets that depend on Rust are simply skipped if it is not installed. This then leads to test failures since Rust is required to build signed binaries. This is a bad user experience and leads to wasted time investigating the failures. The project is only going to depend on Rust more over time so we should just make it a mandatory dependency.

**Comment by moidx** [comment]
This is the case now with Bazel. Closing as Done.
