### ISSUE TITLE
[doc] dead link of sim result page

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#7166]
hi Cindy
on the Different IP simulations results page in the bottom there is a link to the lint results
but they all returning 404
https://reports.opentitan.org/hw/ip/aes/dv/latest/results.html

scroll to the bottom

![image](https://user-images.githubusercontent.com/53917183/123704348-d9110580-d865-11eb-80e7-5171fbb9f117.png)

**Comment by cindychip** [comment]
Thanks Rasmus, I will take a look!

**Comment by cindychip** [comment]
I do not see any more dead links in the simulation page. I will close this issue.
If you have any further questions, feel free to reopen this one, or file another issue.
