### ISSUE TITLE
[clkmgr] Security enhancements

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7167]
As part of reviews, it was determined that clkmgr needs to some basic security enhancements

- clock frequency measurement to ensure clocks are not drifting away from their intended targets.

if the clock frequency measurement fails, a alert must be triggered.
This will be done only for the fixed frequencies as the jittery clock will anyways change on average.

**Comment by tjaychen** [comment]
@dsandrs 
let me know what you guys think of this item.  This was a result from the security reviews and I want to make sure we give it some thought.

**Comment by sriyerg** [comment]
I will let Matute assess (and update the clkmgr testplan) these enhancements. For the chip level, the alert will get  tested as a part of the common alert test. LMK if there is any other impact at the chip level, otherwise this seem contained within the IP.
