### ISSUE TITLE
[rstmgr] Reset security hardening

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7168]
There are a few things to enhance on the reset manager side

- reset integrity checking (if a reset fires, it is firing because something in the upper hierarchy nodes has fired)
- reset integrity checks (using potentially multiple bits to determine a reset should have fired
- shadow resets (shadow registers should ideally use different reset lines per copy)

@mateenfaisal 
@dsandrs

**Comment by tjaychen** [comment]
let me know what you guys think.
These features will incur some impact on the schedule, both design and dv.

**Comment by sriyerg** [comment]
Pending DV work tracked here:
https://github.com/lowRISC/opentitan/issues/7845
