### ISSUE TITLE
[clkmgr] bug dealing with multiple clocks under 1 idle

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7170]
clkmgr's support for multiple clocks in a transactional block is currently incomplete.
Specifically, it is not clear whether the single idle from a block should cover all clocks or one of them.

To address this, #7121 (and other related PRs) are doing the following:

- each block has one idle signal
- the idle signal is sync'd into the appropriate domain to gate off the clock
- for blocks that have multiple clocks, the idle applies to all and means clocks may gate off and turn on at slightly different cycles

This last portion has an impact on DV as the gate off is no longer immediate and must now account for cdc crossings.

**Comment by tjaychen** [comment]
@dsandrs 
@mateenfaisal

**Comment by rswarbrick** [comment]
We had a chat about this at the lowRISC end and it probably makes more sense to have an idle per clock. The only use-case at the moment is OTBN and our discussion quickly got into the exact behaviour that we expect in various weird situations. It looks like this probably needs handling at the block level (where these discussions belong!), which should make clkmgr's life easier too.

**Comment by rswarbrick** [comment]
Assuming we do decide to have an idle signal per clock, there's a bit of tooling work to do: we need to teach topgen how to wire up the "idle" signals correctly. I've just opened #7176, which is a sort of staging post in that direction. Assuming we're happy with that change, a followup commit can add an optional "idle" field to a `ClockingItem`, which could then be grabbed by the topgen code that's doing the wiring up.

**Comment by tjaychen** [comment]
sure, just do whatever you guys want i guess.
just keep @matutem in the loop. I won't add more to this discussion for now.
