### ISSUE TITLE
[sram] update block level testbench to account for transmission integrity

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7177]
After #7066 is merged, need to update block level testbench since now transmission integrity for memory will be fully implemented.

**Comment by tjaychen** [comment]
@weicaiyang 
@udinator i can take a first crack at this also, since i'm more familiar with the ...many options i put on tlul_adapter_sram.
But i think in general we just want it to match the version used in top_earlgrey.

**Comment by udinator** [comment]
sure, that sounds good! LMK if there is any debug that I can help out with.

**Comment by msfschaffner** [comment]
Another thing that remains is the integrity alert hookup inside the `sram_ctrl` (this is one of the only outstanding modules that still needs to be wired up https://github.com/lowRISC/opentitan/issues/5985).

@tjaychen once you've added the correct adapter parameterizations to the testbench, I can then go in and connect the alert if you want.

**Comment by udinator** [comment]
adding @weicaiyang for visibility.

**Comment by weicaiyang** [comment]
We have tested both integrity for SRAM_CTRL.
1. sending request with integrity error on either cmd or data
2. hack data integrity in sram and read the memory location, the wrong integrity will be sent but no error/alert will be triggered.

I think we can close this issue now.

**Comment by msfschaffner** [comment]
Yes indeed, let's close it.
