### ISSUE TITLE
[mask_rom] Initialize mask_rom with pre-CRT safe interrupt vector.

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#7189]
The interrupt/exception handlers are setup in the mask ROM before the C runtime is fully initialized. If an NMI or exception occurs during C runtime intialization calling these handlers might result in undefined behavior since the stack and global data will not be fully initialized.

<del>One potential fix is to write a short stub of assembly that checks whether the C runtime is initialized or not and if not calls a fallback assembly shutdown routine.</del>EDIT: probably best to just switch interrupt vector.

**Comment by mundaym** [comment]
Any thoughts on this @cfrantz? I'm thinking we just sit in a `wfi` loop if this happens.

**Comment by cfrantz** [comment]
IIUC, the chip boots with `_mask_rom_interrupt_vector` in mtvec and the setting of mtvec in mask_rom_start is merely a formality.  I was going to suggest we have 2 vector tables: pre-CRT and post-CRT.

The pre-CRT vector would do something sensible considering the C runtime is not initialized, whereas the post-CRT vector would invoke the shutdown manager.

In your suggestion, how would you propose having the code tell whether or not CRT-init has completed?

**Comment by mundaym** [comment]
Yeah, I think you are right and we should just have two vectors.

Anything else I can think of is likely to either be a hack (e.g. finding a spare bit in a CSR to use) or unreliable (e.g. using a value in SRAM). We probably wouldn't save much space anyway given the interrupt vector is relatively short.

**Comment by mundaym** [comment]
> IIUC, the chip boots with _mask_rom_interrupt_vector in mtvec and the setting of mtvec in mask_rom_start is merely a formality.

That is correct.

**Comment by mundaym** [comment]
@imphil suggested that it might be better to have a hardware solution. For example, exceptions could be escalated and trigger a reset unless the software has configured a (new) CSR.

**Comment by rswarbrick** [comment]
Isn't that essentially the same behaviour as you'd get if you installed a "`while (1) {}`" loop as the handler until ready to deal with things properly? I'm not sure how writing to the proposed new CSR would be any simpler than just updating the vectors?

**Comment by mundaym** [comment]
@cfrantz has suggested that we could use the watchdog timer to request a reset. I think I'll try that approach and see how far it takes us.

@rswarbrick I think we want to avoid ending up in an infinite loop without first locking down the chip. A reset is one way to achieve that.

**Comment by rswarbrick** [comment]
> @rswarbrick I think we want to avoid ending up in an infinite loop without first locking down the chip. A reset is one way to achieve that.

Right, makes sense. I was imagining that the watchdog would kill us quickly. Chris Frantz's idea sounds good to me (assuming it's "in the initial handler, configure the watchdog to reset us ASAP")
