### ISSUE TITLE
[sw/device] Separate interrupt/exception enum definitions from handler code

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#7190]
Currently the interrupt/exception enum that represents `mcause` values is part of the handler library: https://github.com/lowRISC/opentitan/blob/99e893798a52a2ecb91c1403e1cc0e9ccda6dc35/sw/device/lib/handler.h#L8-L17

To use it one also has to adopt  the handler library's interrupt handlers which isn't ideal. It would be better for these to live in a separate header file so that, for example, the mask ROM could use them. While we are at we should clean up the names to make them more descriptive.

**Comment by alphan** [comment]
@timothytrippel would you mind working on this?

**Comment by timothytrippel** [comment]
sure thing, no problem, I can take this.

**Comment by alphan** [comment]
Thanks @timothytrippel!
