### ISSUE TITLE
Arty board: JTAG off-chip connectivity

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#72]
On the Arty board we don't have a second channel of the FT2232 chip available for JTAG to the CPU core. Options are either using a separate JTAG PMOD, or tunneling JTAG through the Xilinx BSCANE2 primitive. Using this primitive is a bit annoying and requires OpenOCD changes. There's a branch in the riscv-openocd repository at  https://github.com/riscv/riscv-openocd/tree/bscan_tunnel which might help.

**Comment by msfschaffner** [comment]
We do not support OpenTitan on the Arty board anymore. @imphil are we still considering to use the BSCANE2 primitive or can we close this for now?
