### ISSUE TITLE
[rv_dm] Do we need a standard way to prevent low power entry when in debug mode? 

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7215]
When the system is in an active debug state through the rv_dm, do we need to provision a mechanism that will prevent the debugger from going into low power?

This can obviously be done by the debugger just programming specific configuration in the `pwrmgr`, but just wanted to know if there was a standard way to do this like with other architectures.  If we have to add a fully customizeable bit, I think that would be no different from just programming a bit in the `pwrmgr`.  Let me know what you think. 

> estimate 16

**Comment by matutem** [comment]
I guess you mean "... mechanism that will prevent the ..." in the first paragraph above.

I suppose you are referring to the control.core_clk_en CSR bit in pwrmgr? My natural tendency is to avoid replication of mechanisms so I would assume we don't need anything else, but I defer to the software team.

**Comment by imphil** [comment]
To narrow things down: All normal debug operations are done by executing code on Ibex, so its idle signal should prevent it from going into low-power mode. Also entering debug mode is effectively an interrupt to ibex, so it goes out of a low-power mode if necessary.

In addition to "normal debugging", the debug module provides bus access (the system bus access/SBA module: https://raw.githubusercontent.com/riscv/riscv-debug-spec/4e0bb0fc2d843473db2356623792c6b7603b94d4/riscv-debug-release.pdf section 3.9). Even though SBA could be used to directly talk to peripherals over the bus, in practice it's only used to read (and for SRAMs, write) the memories.

So if software developers want to use SBA while the main core is powered down, they need to first power up the system.

But alternatively, developers can just avoid using SBA and access the peripherals through Ibex, which is a single line change in a config file: https://github.com/lowRISC/opentitan/blob/c920c93586a7002360c878a4ace6c82d61947450/util/openocd/target/lowrisc-earlgrey.cfg#L29

So my feeling is: as long as the debug module itself doesn't become unavailable we're good.

**Comment by matutem** [comment]
For the record: entering low power is triggered by the low_power_hint field in the pwrmgr CONTROL CSR. On the other hand, if rv_dm is active and the processor is running code that enters low power mode the debug session will seem to freeze until something wakes up the processor.

If the software team thinks this is undesirable we could add an extra input from rv_dm to the logic that enables low power entry, like the rv_dm dmactive_o output.

**Comment by msfschaffner** [comment]
Are we ok with punting this to a future revision then (just to document what the decision is)?

**Comment by andreaskurth** [comment]
@msfschaffner Do I understand correctly that this will not be relevant for M3?

**Comment by msfschaffner** [comment]
@tjaychen I think this would be a post-ES enhancement, right?

If so, let's move it to the backlog.

**Comment by tjaychen** [comment]
yes agreed. I think ideally we would prefer to use something standardized to indicate "debug ongoing".  But I really don't think it's a huge issue for M3.

**Comment by andreaskurth** [comment]
Triaged for `rv_dm`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP1 because I think we should make sure the current HW behavior is suitable for production (discuss with the SW engineers working on debug).  If no, we need time to resolve, hence the high priority. If yes, defer back to https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease.

**Comment by andreaskurth** [comment]
As discussed in today's SW WG Meeting, the current behavior where software can prevent or trigger low-power entry through `pwrmgr` is useful and flexible. No additional hardware features or further standardization are necessary at this point. We have thus decided to close this issue until we see a need arise.
