### ISSUE TITLE
[sram_ctrl] Correctly calculate integrity bits when triggering the LFSR initialization

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#7225]
See https://github.com/lowRISC/opentitan/pull/7220#discussion_r663126562 for context.

**Comment by msfschaffner** [comment]
@msfschaffner 
one thing that i realized about the memory init... because the integrity right now is handled inside `tlul_adapter_sram`, the sram init actually still does not produce correct integrity.  

This is probably something we'll want to update and allow the init to happen either in the sram itself or from the tlul adapter sram.

_Originally posted by @tjaychen in https://github.com/lowRISC/opentitan/pull/7220#discussion_r663126562_

**Comment by msfschaffner** [comment]
yes I can update that. I am in the process of absorbing the ram primitive into the sram_ctrl, so I can technically pull the LFSR back out into the sram_ctrl and compute the correct ECC. let me make an issue for this.

_Originally posted by @msfschaffner in https://github.com/lowRISC/opentitan/pull/7220#discussion_r663219028_

**Comment by msfschaffner** [comment]
do you think it makes sense to give the tlul_adapter_sram the "init" ability?
The ecc encoders are tiny..so it doesn't bother me too much, but it feels a little weird to have duplicate copies in tlul_adapter_sram (for the byte purpose), and also one in sram_ctrl.

let me know what you think.

_Originally posted by @tjaychen in https://github.com/lowRISC/opentitan/pull/7220#discussion_r663220213_

**Comment by msfschaffner** [comment]
we can also move it into `tlul_adapter_sram`, yes. maybe this init mechanism comes in handy in some other designs in the future. we just have to be aware of the coverage impact in existing modules that make use of this module...

_Originally posted by @msfschaffner in https://github.com/lowRISC/opentitan/pull/7220#discussion_r663292430_

**Comment by tjaychen** [comment]
yeah. Honestly both are okay with me.
The main reason i was thinking to move this to `init` because as things are structured now `prim_ram_1p_scr` isn't actually aware of the integrity, it just treats it like extra storage bits.

So it feels like if we were to stay consistent, the "init" would also need to be at a place that understood the integrity.

**Comment by msfschaffner** [comment]
This will be addressed as part of #7218.
