### ISSUE TITLE
[lc_ctrl] token mismatch error

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#7229]
Hi Michael,

I am working on a top-level test for LC_CTRL to issue a transition from `testunlock0` state to `rma` state,
I believe this transition requires 0 token.
But I kept getting this invalid_token error on status.

I saw the expected Zero token is `8d05_b96d_5fd2_c1d5_f15f_cfae_5b30_5238`
But the output token from kmac is `3852_305b_aecf_5ff1_d5c1_d25f_6db9_058d`
Looks like the MSB and LSB was swapped. I input all zeros to the LC_CTRL token registers. Could you help me take a look at design and see if there is any issue?

Here is the waveform:
![image](https://user-images.githubusercontent.com/11466553/124334672-b70cd100-db4c-11eb-80d7-3b01df4b383b.png)

Thanks,
Cindy

**Comment by msfschaffner** [comment]
Hi @cindychip - I almost expected that this might happen. The python cshake library apparently works in reversed order. Let me take a look (might be a scripting change only).

**Comment by msfschaffner** [comment]
Can you check whether #7231 fixes the problem?
