### ISSUE TITLE
[doc] documenting nits / issues / bugs with #638

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/opentitan#723]
Refers to #638 . I will push issues here to allow it to move forward and still
have a live place to document issues found. This will end up being a combination
of nits and RFEs and slightly related thoughts.
List of all captured comments:
- [x] 1 Top level: `relref` links render with newlines, not sure why, didn't see an obvious way to fix
- [x] 2 unrelated: `project.md` and `product.md` have to go, they were placeholders. I will remove in a separate pass
- [x] 3 style nit: ```console content is overly large font and I miss the gray background
- [ ] 4 style nit: `backtick` content is hard to distinguish from normal font content, I miss the gray background
- [x] 5 `doc/ug/systems_list/index.md` needs improving. Also, the link within the row for `Earl Grey` is a dead link
- [x] 6 meta: footer says copyright OpenTitan Contributors, all our content says Copyright lowRISC contributors.
- [x] 7 meta: top file is `_index.md`, all others are `index.md`. Required?
- [x] 8 format issue: `doc/ug/getting_started_sw/index.md` last line has a broken []() link
- [x] 9 footer: all links are relative (Documentation, Blog, Partners, GitHub, Twitter, Privacy Policy)
- [x] 10 footer: `slack` and `twitter` logos point to `Github.html`
- [ ] 11 question: sometimes you have new subdirectories (nb. `doc/rm/comportability_specification`), sometimes you dont (nb. `doc/rm/markdown_coding_style.md`). Is it obvious when to use one vs. the other? What is the criteria?
- [ ] 12 @asb: we still have `doc/rm/verilog_coding_style.md`. I recall that the goal was to get the one in lowrisc/style-guides rendered somewhere so that we could point to that. Thoughts?
- [x] 13 link to `register_tool.md` within `doc/rm/comportability_specification` is broken (relative; in three places)
- [x] 13b ditto `hjson_usage_style.md`
- [x] 14  TODO: `doc/ug/hw_stages` can now link to `doc/project/rfc_process.md` and `doc/project/hw_dashboard.md` (two places), and could add a pointer to the signoff template.
- [ ] 15 kind of P0-ish for me, two parts a) (P2) `doc/ug/design` points to `/project.md`, but that will be deprecated; b) (P0) we had a to-do to discuss FPGA vs Silicon philosophy which I earlier said was done, but it has not been published, and needs a new home and sign-off.
- [ ] 16 remove Validation Methodology (TODO) section, I think we have enough verbiage in the user guides for FPGA
- [x] 17 Personally I think we should remove reference to "Titan Style header files" in `/doc/rm/register_tool/`. Opinions?
- [x] 18 formatting: `*` based bulleted list in `doc/rm/c_cpp_coding_style` is broken near top.
- [x] 19 meta: all technical docs have lost their banner, so they just start with `OVERVIEW`. Will the --- title --- section expand later?
- [ ] 20 make uniform decision on location of specs regardless of whether or not they have images currently so that in future when images are added it is consistent?
- [ ] 21 turns out "specboard" is manual now, need a way to recreate
- [ ] 22 style nit: ```console formatting wrapping behaviour - It wraps lines to fit the fixed width white box
- [x] 23 tables often stretch beyond page width without a horizontal slide bar (example `hw/ip/rv_timer/doc/dv_plan`). Also tables are not that attractive in this case.
- [ ] 24 with `util/docgen/README.md` deprecated, we need a replacement for hugo
- [x] 25  "selfdoc" feature is missing, such as, in `doc/rm/crossbar_tool/index.md`
- [ ] 26 `doc/rm/markdown_usage_style.md` refers to docgen, needs to get refreshed with hugo verbiage.
- [x] 27 `hw/ip/*/doc/dv_plan/#top-level-testbench` bullets are not appearing as expected.
- [x] 28 bubble needs to be updated for the new hugo build
- [ ] 29 need to rethink links within READMEs since they were supposed to be navigable within GH but no longer are with `relref`
- [ ] 30 Nit: in dark mode shell examples still seem to be black on white which makes them stand out

**Comment by sjgitty** [comment]
@gkelly I believe all of the interesting ones here have been recreated in other PRs or issues. If you agree, I will close the issue.

**Comment by sjgitty** [comment]
@gkelly bump

**Comment by sjgitty** [comment]
@gkelly bump

**Comment by gkelly** [comment]
Yep, I think the interesting bits (and some new issues) have been captured in separate issues.  Happy to close this one.

**Comment by sjgitty** [comment]
closing this one as they are all either completed or separated out into other issues.
