### ISSUE TITLE
[otp_ctrl/lc_ctrl] Open RTL alignments / security bugfixes

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#7245]
This issue is intended to keep track of the comments on #7150 and the decision whether to move forward with this and related changes.

**Comment by msfschaffner** [comment]
@cindychip, please pull this PR locally and run full otp ctrl nightly to assess V2 readiness. If our coverage drops below V2 level, we will need to revert the D/V stage and do a version bump. @msfschaffner, i suppose you need to check the same for D2 readiness. 

Also, please assess the amount of work to account for this change and lets have the smartsheet updated to reflect that. 

@msfschaffner, are there any more changes anticipated in otp ctrl? We really ought to start freezing blocks so that we can make progress on other things in our (huge) list of pending items. Though i do understand it may be hard to foresee it. 

@dsandrs, do you agree?

_Originally posted by @sriyerg in https://github.com/lowRISC/opentitan/issues/7150#issuecomment-868948337_

**Comment by msfschaffner** [comment]
Thanks Sri for tagging me. I do need to add more checkings for this new `valid` output ports.
As for DV impact: I ran the DV nightly with this new change. The V1 and V2 tests are all passing. Only failing test is `otp_ctrl_tl_intg_err`.

Not much coverage impact for V2 either:
|  SCORE  |  LINE   |  COND   |  TOGGLE  |   FSM    |  BRANCH  |  ASSERT  |  GROUP  |
|:-------:|:-------:|:-------:|:--------:|:--------:|:--------:|:--------:|:-------:|
| 96.11 % | 99.24 % | 91.16 % | 97.73 %  | 100.00 % | 95.40 %  | 92.81 %  | 96.44 % |

_Originally posted by @cindychip in https://github.com/lowRISC/opentitan/issues/7150#issuecomment-869999600_

**Comment by msfschaffner** [comment]
Sorry I should have communicated this better.

This is fixes a security bug. 

For context: 
The life cycle controller did not check the provisioning status of `SECRET2` upon life cycle transitions from `PROD*/DEV` into `RMA`, which opens up an undesirable loop hole. In particular:
- The HW currently does not  It is not enforced that `SECRET2` becomes unreadable by SW when moving through `PROD*/DEV` into `RMA`.
- Further, a life cycle transition to `RMA` can be initiated with an all-zero token in certain cases when the `SECRET2` partition is not locked right away, e.g.:
  - when only the root key is provisioned, but not the `RMA_UNLOCK_TOKEN` token.
  - when the `RMA_UNLOCK_TOKEN` is provisioned, but the chip is has not yet been reset.

There are provisioning flow workarounds for this, but it would be good to enforce this check directly in hardware. The `SECRET2` partition holds the root key which should not remain readable by SW when transitioning into `RMA`. Also, there should not exist another way to move from `PROD*/DEV` into `RMA` without providing a valid, non-zero `RMA` token.


Although the change does not look trivial in the diff, it is actually rather localized.
I.e., this change updates the OTP->LC_CTRL connection such that the (readily available) "digest locked status" is output alongside each life cycle token as a redundantly encoded "token valid" signal. 

This "token valid" signal is then used as an additional condition when the token comparison is made in the life cycle controller. If a token is not valid / has not been provisioned, this check would fail and abort the life cycle transition. 

That way it becomes impossible to move from `PROD*/DEV` -> `RMA` without provisioning and locking the `SECRET2` partition.


This change does not really add a new feature, but rather fixes existing mechanisms. 
As @cindychip confirmed, this change does not impact coverage adversely and can be tested with existing test sequences.

---------------------------------------------------------------------------
There are currently three other pending changes to OTP in addition to this PR:

1. Bus integrity alert hookup https://github.com/lowRISC/opentitan/pull/7151
2. Width alignment of OTBN scrambling nonce https://github.com/lowRISC/opentitan/pull/7144
3. Increase of background check timer reseed period https://github.com/lowRISC/opentitan/pull/7152

I'll comment more on the corresponding PRs, but 1. is a known enhancement that we have to add to all IPs, and 2./3. are minor adjustments that should not have an adverse impact on DV (these are not new features).

If nothing changes in the provisioning and production test flows, I do not expect additional changes at the moment.

_Originally posted by @msfschaffner in https://github.com/lowRISC/opentitan/issues/7150#issuecomment-870106859_

**Comment by msfschaffner** [comment]
The minor alignments #7151 and #7152 have been merged in by now. 
The two that are still open are:

- #7150 
- #7152

From a discussion that @cindychip and I had, these changes should not affect V2 status (backed by the coverage statistics posted above), nor introduce significant DV overhead as they are not really new features and can be covered with existing vectors.

Can you confirm this, @cindychip?

Everybody else: are we ok moving forward with these two changes?

**Comment by tjaychen** [comment]
> The minor alignments #7151 and #7152 have been merged in by now.
> The two that are still open are:
> 
> * [[lc_ctrl/otp_ctrl] Check whether a token is valid before performing a transition #7150](https://github.com/lowRISC/opentitan/pull/7150)
> * [[otp_ctrl] Increase LFSR reseeding period #7152](https://github.com/lowRISC/opentitan/pull/7152)
> 
> From a discussion that @cindychip and I had, these changes should not affect V2 status (backed by the coverage statistics posted above), nor introduce significant DV overhead as they are not really new features and can be covered with existing vectors.
> 
> Can you confirm this, @cindychip?
> 
> Everybody else: are we ok moving forward with these two changes?

okay from my side.

**Comment by cindychip** [comment]
Hi Michael. Thanks for documenting it. yes I can confirm both should not affect DV V2 status.

**Comment by msfschaffner** [comment]
Thanks for the feedback. Can someone approve the two PRs?

**Comment by msfschaffner** [comment]
OK, the pending items have been merged - closing this one down.
