### ISSUE TITLE
[doc] too many "Getting Started" pages make its difficult to follow instructions

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#7260]
In order to make the project more appealing to newcomers I propose:
1. Moving the master [Getting Started](https://docs.opentitan.org/doc/ug/getting_started/) page to the [top level documentation page](https://docs.opentitan.org/).
2. Refactoring the [Getting Started](https://docs.opentitan.org/doc/ug/getting_started/) page to: a) make it more concise, b) add a flowchart highlighting instructions, c) incorporate/promote use of Docker container with correct build environment to get started faster with (if verilator is your only target).

**Comment by tjaychen** [comment]
these all sound good to me.  Do you want to maybe mock up a diagram of what you have in mind? Because that master page also doesn't link any info about DV at the moment, or the top level documentation (which is itself outdated right now).

**Comment by timothytrippel** [comment]
@tjaychen Will do. 

I also noticed the [Quickstart](https://docs.opentitan.org/doc/ug/quickstart/) page relies on releases almost 2 years old, since the documentation references pre-built Verilator sim. binaries and FPGA bitstreams. Though I think this should be filed as another issue (or will be addressed in future build system upgrades).

**Comment by timothytrippel** [comment]
@domrizz0 @tjaychen I was thinking something like this for the figure:

![getting-started-workflow](https://user-images.githubusercontent.com/5633066/125129123-f5663b00-e0cc-11eb-8daa-a09f1e49b3d8.png)

I will include the refactored writing and finalized figure in a PR for review.

**Comment by tjaychen** [comment]
o nice, i like that.  Should build SW be its own veritical you think? Because that also technically feeds into DV as well. 

@imphil 
@sriyerg 

would be good to hear from others also.

**Comment by rswarbrick** [comment]
Definitely, OTBN testing needs a working RISC-V toolchain, and so do some of the chip-level tests (which can be run through VCS or Xcelium, so belong in the "left column" of the diagram)

As the documentation currently stands, we claim that you have to install a whole load of stuff as a "base system": we don't currently distinguish between different use cases. Maybe we should, but that will be quite a bit of unpicking, I think.

**Comment by asb** [comment]
@mundaym has been sketching out some proposals in this area - what do you think Michael? It would make sense for you to join efforts on this I think.

**Comment by timothytrippel** [comment]
> Definitely, OTBN testing needs a working RISC-V toolchain, and so do some of the chip-level tests (which can be run through VCS or Xcelium, so belong in the "left column" of the diagram)

Ah got it, I will include 'BUILD SW' under the DV flow too.

> 
> As the documentation currently stands, we claim that you have to install a whole load of stuff as a "base system": we don't currently distinguish between different use cases. Maybe we should, but that will be quite a bit of unpicking, I think.

Agreed, maybe just keep it simple for now (i.e., install the "base system"), and add more detailed installation guides in the future for the various use cases?

**Comment by timothytrippel** [comment]
> > 1. Moving the master Getting Started page to the top level documentation page.
> 
> Are you proposing to replace the existing [introduction page](https://docs.opentitan.org/) with the getting started guide or just link to it at a higher level? A great big 'GET STARTED' button on the introduction page would be a good start I think. Right now the link is obscured by being buried in the text.

I was thinking the latter: just adding a big 'GET STARTED' button on the introduction page. Yes agreed, I think it is currently obscured by the text.

> 
> > 1. Refactoring the Getting Started page to: a) make it more concise, b) add a flowchart highlighting instructions, c) incorporate/promote use of Docker container with correct build environment to get started faster with (if verilator is your only target).
> 
> There was an issue raised about using Docker in the getting started guide: #4747. I am in favour of doing it but we should make sure that the Docker files are adequately tested/supported before referencing them.
> 

Yes, makes sense. Personally, I too am a big fan of Docker containers for reproducibility. There are a couple options here:
1) leave things as they are for now, i.e. just request users to install deps manually, or
2) add a pointer to the Dockerfile in the "Getting Started" page with a (temporary) disclaimer: "Not supported, but could make your life easier if it works", until adequate testing of the docker image can be integrated into CI. Additionally, make the "Setup Env. (manual)" shaded "recommended for new users". 

I'm fine with either, and in both cases container integration can be done in a separate (later) PR. Just let me know if anyone feels strongly either way!

> Other than that the refactoring you propose to the getting started page sounds great.
> 
> In case it helps my provisional TODO list for refactoring the page looks something like this (don't feel like you need to do any/all of this as well though!):
> 
> * Add a simplified system overview including a diagram.

Yes, +1. Maybe in addition to my diagram describing the various workflows above?

> * Remove all discussion of Git repositories (should be set up after dependencies are installed).

Agreed.

> * Restructure the links so that there are 4 clear steps to setup a development environment with a brief description of each step:
>   
>   1. Check system requirements
>   2. Install dependencies
>   3. Build the software and run the host tests
>   4. Build the simulation and run software on it, including device tests
> * Rework the information in the ‘device software flow’ into the system overview section.
> 

Yes, +1. As it stands, it feels like the sub-links to these instructions are buried in the text. Exposing them above would help too I think.

Thanks for the pointers, I really like these. I will incorporated them into the refactor.

> Please do add me to any PRs you create, I'm more than happy to help review them. Thanks and welcome to the project @timothytrippel!

Will do, thanks! I'm excited to be here!
