### ISSUE TITLE
spi_host does not start transmission

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#7281]
hi @martin-lueker / @Muqing-Liu 
as mentioned I am working on a very basic spi_host.
But I can't even get the chip-select to activate. 
I am unsure if I am missing a setting in a register or if there is a hardware bug.

polling status until READY is high
then I am writing 
config opts: 0x041F_0000
control:        0x8000_0200
CSID:            0x0000_0000

REad Status wait for READY

DATA window: 0x0011_2233
Command       0x0000_3007

I would expect the scb to drop and the sck to start toggling but nothing happens.
if I look inside the fsm, it looks like the stall is set and that might be the reason.

could you take a look and let me know if I am missing something in the programming sequence?
don't bother debugging the UVM it is currently in a very raw state.

to reproduce do. checkout my branch: https://github.com/rasmus-madsen/opentitan-1/tree/spi_smoke
and run:
` ./util/dvsim/dvsim.py hw/ip/spi_host/dv/spi_host_sim_cfg.hjson -i spi_host_smoke -r 1 -t xcelium --job-prefix="nc run -C ncsim_batch -Il" --waves=shm --seed=1`

Be aware the test passes as I have not enabled the scoreboard or any other checking features.

![image](https://user-images.githubusercontent.com/53917183/125349254-9cf99c80-e35d-11eb-9bc2-84dc47078089.png)

MLB EDIT: Changed the name of the batch queue to `ncsim_batch` in the command line instructions above as this is preferred by our sysadmins (and at least as of today, I don't actually have interactive access for Xcelium)

**Comment by martin-lueker** [comment]
Hi Everyone, the first issue seems to be that the registers for this test bench are out of date.  The `passthru` bit has been removed.   I can try to straighten that out.

However may be a secondary issue as the spi_smoke tb doesn't even compile against master.  So we should how this works out once the testbench fixed.

**Comment by martin-lueker** [comment]
Update: It's seems there may be *two* bugs in the RTL
1. Data does not seem to be getting into the shift register and the FSM is reporting a stall
2. Rather than indicating a persistent stall the SPI host, FSM is resetting to idle.  

Both conditions need to be fixed.

**Comment by martin-lueker** [comment]
PR (#7377) submitted master for RTL fixes.  This PR will fix the present issue.

Minor DV updates submitted to rasmus-madsen/spi_smoke to help confirm fixes. (https://github.com/rasmus-madsen/opentitan-1/pull/4)

Functional waveform (obtained after these changes):
![image](https://user-images.githubusercontent.com/47870387/126387020-2f9653e7-3d3c-46e8-8223-767a6b2f9f7b.png)

**Comment by tunghoang290780** [comment]
@rasmus-madsen could you reproduce #6497? Just use "--seed=1129857389". This is RTL bug and Martin solution will fix it. I actually did the same thing to move DV forward and I can see the write transactions are captured correctly by monitor.

**Comment by rasmus-madsen** [comment]
> @rasmus-madsen could you reproduce #6497? Just use "--seed=1129857389". This is RTL bug and Martin solution will fix it. I actually did the same thing to move DV forward and I can see the write transactions are captured correctly by monitor.

Hi Tung yes those are infact the exact same issue - for some reason I forgot about that issue.
would it be ok if I close yours and just mention this - to not have duplicates?

**Comment by rasmus-madsen** [comment]
I can confirm this is solved with  #7377
