### ISSUE TITLE
OpenTitan to register for PEN with IANA

### ISSUE THREAD

**Issue by moffen** [lowRISC/opentitan#7287]
Current X.509 proposals include an OpenTitan unique extension, e.g., the "OpenTitan Creator Identity custom extension", see: https://docs.opentitan.org/doc/security/specs/attestation/

Use of OT unique X.509 extensions requires OT to have a PEN with IANA in order to create OIDs for these extensions. Last check (July 12, 2021) indicates that OT does not have its own PEN; see:
https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers

Recommend LowRISC to request OpenTitan PEN and become point of contact.
https://pen.iana.org/pen/PenApplication.page

**Comment by moidx** [comment]
CC: @asb @domrizz0

**Comment by imphil** [comment]
Thanks @moffen for bringing this up. The Technical Committee looked at this request today and found that we don't need to get involved. 

@moidx can you coordinate with @asb in case lowRISC should register for such a number, or alternatively propose to use another one (e.g. one from Google)? Thank you!

**Comment by moffen** [comment]
Closing due to no further activity.
