### ISSUE TITLE
[fusesoc] Compile DPI modules into shared libraries and link them afterwards

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#73]
Currently we compile all DPI code together with the Verilator-generated C++ code. We need to extend fusesoc to first compile the DPI modules into shared libraries, and then pass those libraries to the Verilator makefile to link all components together into one simulation.

This allows us to actually compile C code with a C compiler, as opposed to a C++ compiler (that's what we do right now).

**Comment by GregAC** [comment]
We haven't seen any issues with compiling our DPI C code with a C++ compiler so closing this.
