### ISSUE TITLE
[lc_ctrl] Updates for secure manufacturing

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#7330]
It has recently been determined that the life cycle architecture and controller need a few updates to facilitate retest iterations during the secure manufacturing flow. In particular:
- The number of  `TEST_LOCKED`/`TEST_UNLOCKED` states should be increased from 3/4 to 7/8.
- The size of the `DEVICE_ID` field in the `HW_CFG` OTP partition, which is exposed through the LC TAP, should be doubled from 256bit to 512bit.

In addition to the changes above, behavior of the `NVM_DEBUG` enable signal should be slightly changed such that it is not set to `ON` in the last `TEST_UNLOCKED` state such that the isolated flash partition can be written without risk of exposure through the flash backdoor test interface (see also https://github.com/lowRISC/opentitan/issues/4526).

In terms of design and DV impact, these updates should all be relatively straightforward, since they do not conceptually change the already existing functionality. The most involved change is the `TEST_LOCKED`/`TEST_UNLOCKED` states expansion since the states have unique enum names which are hardcoded in several places.

**Comment by msfschaffner** [comment]
@cfrantz do we have to align anything on the SW / ROM side for the above changes to work correctly?

**Comment by cfrantz** [comment]
There will be some trivial changes required to `sw/device/silicon_creator/lib/drivers/lifecycle.[ch]` to enumerate the additional states.

**Comment by cfrantz** [comment]
Could you clarify a bit on the expansion of DEVICE_ID?  I'm given to understand that the extra bits are for testing and that the proper DEVICE_ID is still 256 bits..

**Comment by msfschaffner** [comment]
If I recall correctly, the idea was to just double the size of `DEVICE_ID` for simplicity. 
Would it be preferable for SW to keep `DEVICE_ID` 256bit in size and split this additional information into a separate CSR field?

**Comment by moidx** [comment]
I think it would be preferable to handle the additional bits as `manuf_state`. These bits are primarily for manufacturing tracking purposes, and I don't consider necessary to send them to the key manager. A separate CSR would work better in this case.

**Comment by cfrantz** [comment]
> If I recall correctly, the idea was to just double the size of `DEVICE_ID` for simplicity.
> Would it be preferable for SW to keep `DEVICE_ID` 256bit in size and split this additional information into a separate CSR field?

Yes, I think so.  SW (the ROM and ROM_EXT) will have the capability to bind software to the DEVICE_ID (think a nodelocked package or a sku-locked package on a subset of DEVICE_ID).  Just from a naming convention perspective it would be nice to keep the `DEVICE_ID` registers as meaning the 256-bit device ID. 

The additional bits can be given an appropriate name - they can even be right next to the existing registers if that's convenient.

**Comment by msfschaffner** [comment]
Alright, I've split the extra 256bit into a separate field named `MANUF_STATE` on #7328.
I have also updated the life cycle enum in `sw/device/silicon_creator/lib/drivers/lifecycle.[ch]`.

**Comment by zi-v** [comment]
@msfschaffner, sounds good. Thanks!

**Comment by msfschaffner** [comment]
The changes mentioned above have been implemented and merged.
