### ISSUE TITLE
[mask_rom] Update memory protection module to take into account simple address translation

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#7337]
If the mask ROM is to make use of the [simple address translation unit](https://github.com/lowRISC/opentitan/pull/7147) then the memory protection schema and implementation will need to be modified to take that into account.

Initial thoughts:

- Probably want to keep read access to raw flash region.
- Need new region(s) to grant read access to the virtual flash region(s).
- ROM_EXT code region will need to be in an entry **before** the virtual flash region.

**Comment by moidx** [comment]
Closed by #11761.
