### ISSUE TITLE
[sw/silicon_creator] Integrate OTBN-based modular exponentiation to sigverify

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#7347]
- [ ] Implement `sigverify_mod_exp_otbn()`.
- [ ] Add functional tests for `sigverify_mod_exp_otbn()`.
- [ ] Unit tests (mostly for testing the interaction between sigverify and the OTBN driver).

**Comment by msfschaffner** [comment]
Is this issue up to date?

**Comment by alphan** [comment]
Should be fixed by #8170, there also have been additional updates since then.
