### ISSUE TITLE
[otbn] Sort out access permissions for CSRs and WSRs

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#7405]
In RISC-V, writing to a CSR which is read-only raises an illegal instruction exception. In OTBN, we currently ignore writes to read-only registers (without explicitly saying so).

We need to sort that out and implement it consistently in RTL and ISS.

See also review comments at https://github.com/lowRISC/opentitan/pull/7402.

**Comment by rswarbrick** [comment]
We're now explicit that we ignore those writes. RTL & ISS match and we've got an entry for this in the coverage plan.
