### ISSUE TITLE
[otbn] Test OTBN with "correct" EDN configuration

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#7424]
OTBN requires certain EDN configurations, as described in https://docs.opentitan.org/hw/ip/otbn/doc/index.html#hardware-interfaces. We currently run all tests with the boot EDN configuration, which doesn't meet these requirements.

Figure out the right configuration, and update the tests to use it.

> estimate 16

**Comment by moidx** [comment]
Capturing @mwbranstad's comment here: 

> I think for EDN1, we should not set the "boot_req_mode" field, assuming this EDN is connected to OTBN. Only one EDN can get the boot seed from ES, so let's not make it a race. Agreed?

Sounds good. Since EDN1 is expected to be of high quality entropy, I don't think we need to use it in boot init entropy mode.

**Comment by rswarbrick** [comment]
@moidx: Is there still work to do here, do you know?

**Comment by GregAC** [comment]
As far as I'm aware decide on appropriate end to end testing involving the EDN and OTBN is still an open question

**Comment by ctopal** [comment]
@GregAC Any news on this front?

**Comment by GregAC** [comment]
@andreaskurth was taking a look at this

**Comment by johngt** [comment]
Tagging @andreaskurth to comment on latest status

**Comment by andreaskurth** [comment]
In progress in #13569.

**Comment by andreaskurth** [comment]
> estimate 16

cannot edit original post

**Comment by andreaskurth** [comment]
Done in #13569.
