### ISSUE TITLE
[flash_ctrl] DV Review Action Items

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7431]
- [x] Missing documentation on what happens during `flash init`
- [ ] Need a closed flash documentation (describe testing interface) - Must figure out where to put the closed documentation
- [x] Clarify the pwrmgr / flash interaction on idle entry 
- [x] Default value of seeds to keymgr if flash seed read is not enabled
- [x] Document function of flash disable (similar to escalate)
- [x] Look into whether it makes sense for escalation to NOT kill host accesses. Escalate is a software decision, and okay to kill host access.
- [x] Document the flash_alert path (from flash_shim -> ast -> sensor_ctrl)
- [x] Track down mission mode frequency operating points
- [x] Document nvm_debug_en usage

**Comment by tjaychen** [comment]
@arnonsha 
@sha-ron 
i know you guys mentioned the proprietary documents may not be checked into the foundry area yet, could you please confirm?

**Comment by arnonsha** [comment]
Yes, they are still not in foundry
We'll upload once all reviews are done.
@danaagur 
@zi-v

**Comment by GregAC** [comment]
@arnonsha any idea if this got resolved?

**Comment by arnonsha** [comment]
Nuvoton now only supports its internal database and the open source database and therefore there is need to upload the document to the foundry database and the issue can be closed.
