### ISSUE TITLE
[ci] No module named 'google_verible_verilog_syntax_py'

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#7440]
I found this warning while analyzing the failure of building FPGA bitstream.

BTW, looks like the FPGA build fails even the bitstream is generated.

```
Bitstream generation completed
ERROR: Implementation and bitstream generation step failed.
```

**Comment by imphil** [comment]
The "no module named google_..." error is a problem in the prim setup, but we have a fall-back in place, so it shouldn't cause any build to fail. (I'll have a fix in the coming days.) Thanks for filing an issue for it!

The bitstream error is missing a bit of context (and it's certainly not connected to the verible syntax issue), so let's maybe handle that in a separate issue?
