### ISSUE TITLE
[dv] Split up the tl_agent tests for same-cycle responses?

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#7445]
This is following up on a [review comment](https://github.com/lowRISC/opentitan/pull/7101#discussion_r674188573) from Sri on PR #7101. At the moment, the TL agent test runs with `device_can_rsp_on_same_cycle = 1`. Maybe we should split this into two tests, one for each mode.

@weicaiyang: What do you think?

**Comment by tjaychen** [comment]
ehhh? we actually do same cycle responses??
because the last time Weicai and I looked at this, we needed to change
certain things in our fabric to even support it. (see #3295)

Am I missing something?

**Comment by weicaiyang** [comment]
@rswarbrick In mode `device_can_rsp_on_same_cycle = 1`, we enable the chance that device may respond in the same cycle. But for most of cases, device doesn't respond immediately as we randomly add some delays. I think one test is sufficient and the CI will tell us if we mess up the TL agent.

**Comment by weicaiyang** [comment]
> ehhh? we actually do same cycle responses?? because the last time Weicai and I looked at this, we needed to change certain things in our fabric to even support it. (see #3295) Am I missing something?

@tjaychen we don't enable this mode when testing our OT designs. Since TL spec supports this by default and I also implemented it to try your PR, I keep this support to make it compliant with the spec. Also added a test to make sure we don't screw up this mode.

**Comment by tjaychen** [comment]
thanks weicai!

**Comment by rswarbrick** [comment]
> @rswarbrick In mode `device_can_rsp_on_same_cycle = 1`, we enable the chance that device may respond in the same cycle. But for most of cases, device doesn't respond immediately as we randomly add some delays. I think one test is sufficient and the CI will tell us if we mess up the TL agent.

Maybe. The only issue is that the TL monitor works differently when this flag is set, so arguably this test isn't actually running the thing we want for the chip we're making. Not sure whether that's a big deal though. @sriyerg: Do you have an opinion?

**Comment by sriyerg** [comment]
@weicai, PTAL at this issue to see if it can be closed. Thanks!

**Comment by weicaiyang** [comment]
Checked the test. It should be able to hit both cases easily. Closing this issue now
