### ISSUE TITLE
[otbn] Automate tests in code-snippets directory

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#7454]
OTBN's code snippets directory has a fair amount of tests for different algorithms which need to be executed manually and then the result compared against a reference at the end of the test file. We should automate these tests (and probably run them in CI).

**Comment by GregAC** [comment]
@rswarbrick anything planned here? I'll put a future release label on for now. Please change as appropriate if you're thinking of doing this for V2/V2S/V3 milestones

**Comment by rswarbrick** [comment]
I don't think we're ever going to do anything here. Some of the snippets in question have been moved into the mask rom and are being tested properly there. The others probably don't need any testing. I think we should just close this.
