### ISSUE TITLE
[Regfile Change Proposal] Regfile CDC Handling

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7455]
In OpenTitan, there are multiple modules whose core operating frequency differs from the bus interface.  For example:

- usbdev
- spi_host
- spi_device
- pwrmgr
- pinmux
- pwm
- adc_ctrl
- sys_rst_ctrl
- aon_timer

All of these are handling regfile / core CDC function differently in someway. 
The slower modules however (from `pwrmgr` to `aon_timer` in the list above) are most critical, because depending on how we handle them, could incur significant latency on the operating host. 

As a result, we would like proposal a unified way of handling CDC directly in the regfile.  Please see in [this proposal](https://docs.google.com/presentation/d/1o-3Kf7DkppXVgwrkHhGP4HnaXTx2emTgb3XxXXgVAOk/edit?usp=sharing). 

Please see the prototype implementation in #7331.  In this PR, `aon_timer` uses the more complex cdc scheme as an example, while `pwm` uses the simpler one. 

**PROS**
- The main benefit of such a scheme is that we would unify CDC handling and free most modules (especially those using `aon_clk`) to implement most of its local logic in the other domain without worrying about crossing.  The higher speed modules (`usbdev` / `spi_host`) don't necessarily need to follow the same scheme since they do not have the clock latency downsides.  However, it could still benefit from streamlining and simplification of module logic. 

- This would unify the method of HOW software discovers writes to a different domain are done, which can be very useful. 

- This would simplify eventual CDC checking as all modules would conform to one scheme.  It would also simplify the review process if we all agree on what to use. 

**CONS**
- For blocks that are already mature, this would represent unnecessary churn.  It may not make sense then to revamp all blocks with this.

- It is additional effort on DV (perhaps very heavy) to verify another common functionality inside the regfile

I am opening this issue to solicit feedback from everyone (especially the impacted design and dv folks) to see what you all think. 
We will be going over the proposal in more details in a future OpenTitan project meeting. 

Even if we agree to this scheme, it is an open question exactly which modules should convert. The mature high speed modules do not materially benefit from a switch.  Some modules (such as `spi_device`) cannot use this scheme because the core clock is not always going to be available.

**Comment by tjaychen** [comment]
@dsandrs 
@cfrantz 
@moidx 
@Muqing-Liu 
@GregAC 
@rswarbrick 
@rasmus-madsen

**Comment by rswarbrick** [comment]
On the DV side, I don't think this should cause any problems. We don't have "register file verification" separate from the blocks themselves, so there's nothing to worry about there. I don't think this should have any impact on a block that doesn't use the scheme. For blocks that do use the scheme, I'd hope we can verify that it's working right: if not, we have other problems :-)
