### ISSUE TITLE
[Rstmgr Change Proposal] Shadow Reset Implementation

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7456]
To further enhance OpenTitan's shadow register scheme, it was suggested early on during the design (and by security consultation) to augment shadow registers with shadow resets. 

The basic idea of shadow resets is that each the normal and shadow copies of a register receive different resets. So if an attack managed to glitch one of the reset lines, the two copies become different and trigger an error condition.  

This error condition should then propagate through the module and trigger the alert handler (there is a longer discussion of what happens if the alert sender / handler are also in reset, but that is separately handled through our ping / escalation ping mechanisms and not part of the scope of this issue).

The prototype PR for this mechanism is #7442. In this PR, both `aes` and `alert_handler` are augmented with a secondary shadow reset. 

**PROS**
- Enhance the shadow reset scheme
- Provide better glitch resistance for shadow registers

**CONS**
- Increases DV burden both for common component verification / module specific verification.  
- It will become necessary to negative test the shadow resets to ensure that a glitch on either reset (normal or shadow) can still allow an alert to propagate through the module.

**Comment by tjaychen** [comment]
@cdgori 
@moidx 
@dsandrs 
@domrizz0 
@imphil 
@rswarbrick 
@tomroberts-lowrisc 
@GregAC

**Comment by vogelpi** [comment]
Hey @tjaychen ,
thanks for creating the issue and the prototype PR. This makes sense.

I think the main open question is how to handle cases where the two resets are not released together as this might trigger a fatal alert:
- On the alert handler side things should be okay: software first needs to activate it. However, if things can be reset while the alert handler is running. This might be a problem.
- On the module side things are different. According to the [alert handler guidance](https://docs.opentitan.org/doc/rm/comportability_specification/#alert-handling) fatal alerts should always trigger local security countermeasures. In most cases, the module will just lock up and wait for reset. So we also need to come up with a way to handle this on the module side.

I think you have this on your list as well but wanted to get the CDC regfile proposal through first. But if you could outline possible ideas for handling this that would be interesting.

**Comment by tjaychen** [comment]
So at the moment I am not too worried about the reset assertions.
Our resets are async so under normal circumstances they will pull related logic to the same value immediately.  There is technically STILL a possibility of false positives if the reset occurs RIGHT on the clock sampling edges and look like two different values.  For the software reset case, this is okay since software-caused resets are actually synchronous.  For asynchronous reset sources we'd have to look a bit more closely.  However these async resources are usually wide ranging and impact the entire design. 

For the release, my thinking is that even if they are not at the same time, it does not necessarily matter because the two flops are already the same value.  The real issue is if during that one cycle gap someone tries to access the register.  So my idea is that for shadow registers, they would rely on the `reg_busy` indication (similar to the CDC regfile) to back-pressure any writes directed at them until we are out of the ambiguous reset region.  This should keep the two sides in sync.

**Comment by msfschaffner** [comment]
@tjaychen Afaik this has been implemented so I think we can close this.

**Comment by tjaychen** [comment]
yes sounds good.
