### ISSUE TITLE
[sram_ctrl] Need to handle additional RAW hazards due to byte write handling

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#7461]
https://github.com/lowRISC/opentitan/pull/7218 updates the `sram_ctrl` to include the scrambled RAM primitive and the `tlul_adapter_sram`, and turns on all bus integrity-related features. Since the bus integrity scheme requires additional read-modify-write operations in case of partial writes, new RAW hazard conditions are introduced which the DV environment cannot handle at the moment.

As a workaround, the logic inside `tlul_sram_byte` currently inserts an idle cycle after a partial write operation such that these additional RAW hazards cannot occur.

We should discuss whether it is ok to leave that HW workaround in place, effectively reducing the throughput of partial writes even further, or whether the DV environment should be extended to handle the additional RAW hazard conditions.

**Comment by tjaychen** [comment]
can you remind me what this work around is? i actually have no recollection of this.

**Comment by tjaychen** [comment]
are you talking about the cycle from wait read to write command? that wasn't intended as a work-around, more i didn't want to have back to back memory timing from clk-to-q to setup.

**Comment by msfschaffner** [comment]
Sorry I should have been more specific. I added this workaround as part of #7218 to make the smoke tests pass - it is not something that you have added.

**Comment by msfschaffner** [comment]
In addition to the idle cycle **after** a partial write operation, the workaround has been modified to also include an idle cycle **before** a partial write operation in back-to-back access scenarios.

- The idle cycle **after** partial writes guards against RAW hazards due to a read op sequenced back-to-back with the write phase of the partial write. I.e., `[PR | idle | idle | PW | R]` scenarios, where PR / PW represent the read/write phases of the same partial write operation.

- The idle cycle **before** a partial write op guards against RAW hazards due the read phase of the partial write op, sequenced back to back with a write op, or a read op with a pending previous write. I.e., `[W | PR | idle | idle | WR]` or `[W | R* | PR | idle | idle | WR]` scenarios.

**Comment by tjaychen** [comment]
@tjaychen

**Comment by weicaiyang** [comment]
@msfschaffner can we close this issue now?

**Comment by msfschaffner** [comment]
Yes, this should be resolved now. Thanks for aligning the DV side in order to enable this!
