### ISSUE TITLE
[otbn] User-demanded secure wipe of internal state not needed

### ISSUE THREAD

**Issue by vrozic** [lowRISC/opentitan#7468]
It seems that there is no situation in which the host software might need to securely wipe the internal state.
Current specification states that the  host software can trigger this operation only when OTBN is not busy and that internal state secure wipe is always performed at the end of the OTBN operation.

I suggest to remove SEC_WIPE.INTERNAL and to adjust the specifications.

> estimate 1

**Comment by tjaychen** [comment]
would you mind clarifying a bit why there's no need?
Is it because after appropriate operations the Otbn would wipe itself?

**Comment by vrozic** [comment]
Indeed, the secure wipe of the internal state (register file + modulus + accumulator) is performed automatically at the end of the OTBN operation, and after an error, so there is no need for the host software to do it afterwards.

On the other hand, data and instruction memories are not always wiped by default, so it makes sense for the host software to request it. This feature will still be provided.

**Comment by tjaychen** [comment]
sounds good!
just to confirm, Felix has a use case where he wanted to preserve certain
content between otbn runs, this will still be supported as well right?

**Comment by rswarbrick** [comment]
Yep. That's all stored in memory, I think. This is to do with things like the loop stack and register data (which are mostly architecturally zeroed at the start of an operation anyway).
