### ISSUE TITLE
[otbn] Implement internal secure wipe

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#7469]
RTL changes only.

> estimate 16
> remaining 2021-08-09 8
> remaining 2021-08-23 8
> remaining 2021-09-06 16
> remaining 2021-10-04 4
> remaining 2021-10-18 2

**Comment by imphil** [comment]
RTL PR is available at #7657, but model changes are required to make the `done` signals match between RTL and model.

**Comment by imphil** [comment]
Status update: RTL changes are done, ISS changes need more work.

**Comment by vrozic** [comment]
Continuing work at the separate PR #8498  for RTL changes behind the parameter.
