### ISSUE TITLE
[hw/sw] CSRNG KAT Generate Bits mistmatch

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#7505]
The test vector introduced in PR lowrisc/opentitan#7303 matches all internal `{K,V}` states for instantiate and generate commands, but fails to match the output. 

```console
I00001 boot_rom.c:76] Boot ROM initialisation has completed, jump into flash!
I00000 dif_csrng_smoketest.c:63] Instantiate KAT
I00001 dif_csrng_smoketest.c:110] Generate KAT
E00002 dif_csrng_smoketest.c:131] [0] actual = 0xe48bb8cb; expected = 0x793e01c5
E00003 dif_csrng_smoketest.c:131] [1] actual = 0x1012c84c; expected = 0x87b107ae
E00004 dif_csrng_smoketest.c:131] [2] actual = 0x5af8a7f1; expected = 0xdb17514c
E00005 dif_csrng_smoketest.c:131] [3] actual = 0xd1c07cd9; expected = 0xa43c41b7
E00006 dif_csrng_smoketest.c:131] [4] actual = 0xdf82ab22; expected = 0x510494b3
E00007 dif_csrng_smoketest.c:131] [5] actual = 0x771c619b; expected = 0x64f7ac0c
E00008 dif_csrng_smoketest.c:131] [6] actual = 0xd40fccb1; expected = 0x2581f391
E00009 dif_csrng_smoketest.c:131] [7] actual = 0x87189e99; expected = 0x80b1dc2f
E00010 dif_csrng_smoketest.c:131] [8] actual = 0x510494b3; expected = 0xdf82ab22
E00011 dif_csrng_smoketest.c:131] [9] actual = 0x64f7ac0c; expected = 0x771c619b
E00012 dif_csrng_smoketest.c:131] [10] actual = 0x2581f391; expected = 0xd40fccb1
E00013 dif_csrng_smoketest.c:131] [11] actual = 0x80b1dc2f; expected = 0x87189e99
E00014 dif_csrng_smoketest.c:131] [12] actual = 0x793e01c5; expected = 0xe48bb8cb
E00015 dif_csrng_smoketest.c:131] [13] actual = 0x87b107ae; expected = 0x1012c84c
E00016 dif_csrng_smoketest.c:131] [14] actual = 0xdb17514c; expected = 0x5af8a7f1
E00017 dif_csrng_smoketest.c:131] [15] actual = 0xa43c41b7; expected = 0xd1c07cd9
E00018 dif_csrng_smoketest.c:132] CHECK-fail: Generate ninKAT output mismatch
I00019 test_status.c:34] FAIL!
```

**Comment by mwbranstad** [comment]
@moidx this is unexpected. Not sure I can re-create either. I think the best path for debug is to create a VCD wave file, compress it, and then try to send it to me. Think that is possible?

**Comment by tjaychen** [comment]
@moidx @mwbranstad do we have the C code that generates this error merged somewhere?
we can probably see if it can be recreated in DV / verilator.

**Comment by mwbranstad** [comment]
I tried to re-create this scenario on my multi-block system verlog testbench (has es, cs, edn0, edn1) and it passed for me. I am sure that something that i cannot guess at this point is aligning and causing an issue. At this point i need a wave file to debug.

**Comment by tjaychen** [comment]
mark it could be something specific to verilator.
So we might want to run the vector there and see if anything looks
different.

**Comment by moidx** [comment]
Hi @tjaychen, https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/tests/dif/dif_csrng_smoketest.c can be used to reproduce the issue. So far, I have only tested this on Verilator.

**Comment by mwbranstad** [comment]
@moidx @tjaychen I would like to resolve this, but i will need a waveform generated. I am pretty sure I can look at a VCD formatted wave file.

**Comment by tjaychen** [comment]
sorry @mwbranstad i still didn't have a chance to get back to this.
let me try tonight or some time tomorrow.

**Comment by mwbranstad** [comment]
@moidx does this test use additional data on the generate command? We just found a bug for this case.

**Comment by weicaiyang** [comment]
@tjaychen @moidx can you take a look at this issue and assign priority to it?

**Comment by moidx** [comment]
No longer an issue, verified as part of #13223
