### ISSUE TITLE
[rtl/clkmgr] Remove clk_io_div4_peri glitches

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#7524]
I recently noticed the output peripheral clk_io_div4_peri shows a glitch in simulation, but could also happen in the real hardware. Apparently when the reset signal is asserted the clock falls immediately which could result in glitches. Also, reset is meant to be okay to assert asynchronously, so this could happen during normal reset cycles.

If this is deemed to need fixing it seems the prim_clock_div cell is the root cause. Notice the glitchy clk_io_div4_i signal is used to generate the peripheral clock and also for plenty of logic in the clkmgr.

![Screenshot from 2021-07-29 08-59-39](https://user-images.githubusercontent.com/80294896/127526218-978c61e9-42c9-4bdb-97f4-5ea37fc84a73.png)

**Comment by tjaychen** [comment]
i'll have a look, but i'm not sure if there is a real way to fix this.
When the reset asserts (especially if it's the POR), it will wipe away all
the dividers and everything.

There's no simple way to change the reset state based on where we last
were..so the only thing we might have to rely on is the reset cleaning up
the system state.

**Comment by matutem** [comment]
POR is fine, but this may affect other resets that keep the clkmgr active. Clock circuitry typically needs to use a latch to avoid glitches, suggesting the prim divider cell is not up to snuff.

**Comment by tjaychen** [comment]
are you saying the clock divider out of latches...? can't say i've seen
that before.

**Comment by tjaychen** [comment]
i think the other piece is all of `clkmgr's` resets used are `por` related. 
see [here](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/top_earlgrey.hjson#L357)

**Comment by tjaychen** [comment]
@matutem for the purposes of this test, could we try to sequence the `resets` after the `pwr_i` req/handshake?
It doesn't REALLY matter at the top level because all the resets are `por` related. But if they are not, the idea is the entity controlling the reset should be cycling through the clocks turning off, THEN asserting reset. 

I think that's how this was supposed to addressed at a protocol level.

**Comment by matutem** [comment]
Tim, you are right: the reset causing the glitch is the clkmgr rst_ni, which is POR, so it shouldn't matter if some peripheral clock  glitches at this time. Closing this.
