### ISSUE TITLE
[spi_host, doc] Indicate currently unverified parameter-dependent features

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#7553]
SPI_HOST has a couple of parameter dependent features which are not used in Earlgrey:

- Endianness
- Multiple CS lines

Given that the our design flow makes it a bit more challenging to change parametrizations.   These features should be listed implemented but unverified, as discussed in #7237

**Comment by martin-lueker** [comment]
FYI: @weicaiyang, @rasmus-madsen

**Comment by msfschaffner** [comment]
@martin-lueker, can we close this issue?

**Comment by martin-lueker** [comment]
Hi @msfschaffner, I'm not sure.  This question is still coming up in conversations with @visbaz and others.  So it seems that there are still questions about whether we are going to test non-taped out parameter values like this.   It shouldn't be hard to solve though.  Just one line in the test document somewhere should do it.

**Comment by weicaiyang** [comment]
we agree that it's not needed to verify non-taped out parameter values. Just clarify it in `Compile-time configurations` section in DV doc.

**Comment by msfschaffner** [comment]
Closing this since we are only testing the taped out parameter set.
