### ISSUE TITLE
[reggen] Report error when bit field is reused

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7566]
it seems like reggen does not notice if a bit field is re-used, so we end up with code like this 

```
      addr_hit[59]: begin
        reg_rdata_next[0] = fault_status_cmd_qs;
        reg_rdata_next[1] = fault_status_kmac_fsm_qs;
        reg_rdata_next[2] = fault_status_kmac_op_qs;
        reg_rdata_next[3] = fault_status_regfile_intg_qs;
        reg_rdata_next[3] = fault_status_shadow_qs;
        reg_rdata_next[4] = fault_status_ctrl_fsm_intg_qs;
      end
```

We should have reggen notice something is being re-used and error out right way so we don't get strange lint errors that a particular net is not being used.

**Comment by rswarbrick** [comment]
Oof! Do you have a way to reproduce the example?
