### ISSUE TITLE
[otbn] Incorrect behaviour on a BN.LID/BN.SID that increments x1

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#7579]
Example code that reproduces things:
```
.section .text
  addi    x1, x0, 10
  bn.lid  x0, -10(x1++)
  ecall

.section .data
.word 0
.word 0
.word 0
.word 0
.word 0
.word 0
.word 0
.word 0
```

The problem is that we sample the value "10" and use it for the base address for the load. Unfortunately, this causes a pop so we then get a bogus value to be incremented before storing back the new `x1`.

Probably the right fix is for the "pop" to take effect on the second cycle of the stalled instruction.

Attached is a simple directory with Makefile that lets you generate the same example. Unzip it in the top of the OpenTitan folder, build the Verilator sim with `fusesoc --cores-root=. run --target=sim --setup --build lowrisc:ip:otbn_top_sim`, then `make -C lid-bug test`.

[lid-bug.zip](https://github.com/lowRISC/opentitan/files/6925761/lid-bug.zip)

@GregAC: Could you take a look at this? I can sort of see a fix, but I don't want to come in wielding a hatchet if there's a nicer way to do it :-)

**Comment by GregAC** [comment]
The `bn.lid x1++, 0(x0)` case also needs consideration, I've settled for a solution where the timing of the write is altered depending on which register is being incremented. See the linked PR
