### ISSUE TITLE
[dv] extracted from the pinout configuration for a chip from hjson

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#7587]
As Sri pointed out, we need a layer (a wire-like data structure) extracted from the pinout configuration for a chip from the HJSon that represents what functionality (either muxed or dedicated) is available on each of these pins, and use that to connect the peripheral agents.

**Comment by msfschaffner** [comment]
I think this is not needed anymore since we have the `chip_if` in DV now.
