### ISSUE TITLE
[Rstmgr Change Proposal] Reset consistency checks

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7591]
To further enhance OpenTitan's reset integrity, it was suggested through security consultation to check for reset consistency. 

This means if a node issues a reset, it must be that somewhere upstream has also requested a reset. A reset cannot happen in isolation.  If it does, it is considered a fault. 

PROS
Enhance the integrity checks of resets.

CONS
Requires DV directed test cases to ensure that if a random reset does fire without cause, it is registered as a fault.
Requires random assertion of resets to ensure we do not get false positive faults.

**Comment by tjaychen** [comment]
@dsandrs 
@msfschaffner 
@eunchan

**Comment by tjaychen** [comment]
this has been implemented.

**Comment by tjaychen** [comment]
@matutem i'll assign this issue to you for now so you can think about the DV consequences.

**Comment by msfschaffner** [comment]
@matutem I believe the DV side of this has by now also progressed further. Can we close this or do you still want to keep it open?
