### ISSUE TITLE
[hmac] Enhancements (resolve TODO)

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#761]
A few TODOs exist in the HMAC IP. Need to decide if removing it or not.

- SHA-224 is similar with SHA-256. Decide if HMAC supports SHA-224 too or not
- HMAC second phase, OPad can be done in parallel with pusing the digest data into MSG_FIFO. 
- SHA-256 engine can reduce the total computation cycle by fetching the 16 words from MSG FIFO from round 48. It, however, makes the cases more complex as it needs to consider the FIFO empty case.

CC: @sjgitty @cindychip

**Comment by msfschaffner** [comment]
This is a pretty old issue -  have the TODOs been resolved by now @eunchan?
