### ISSUE TITLE
[top, wakeup modules] Create assertion to check wakeup signals and ack

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7613]
the power manager does not latch the incoming wakeup signals, so it is the responsibility of the various modules to keep wakeups high and level until some form of acknowledgement.

We should add these as individual module assertions to ensure correct behavior.

**Comment by tjaychen** [comment]
@msfschaffner 
@tomroberts-lowrisc 


honestly this might already be done... but just filing to double check.  I can't really put these assertions on `pwrmgr` side since it is not aware of the acknowledgements.

**Comment by msfschaffner** [comment]
For pinmux, I believe this is implemented that way (it's a level signal, driven by the cause register that needs to be ack'd by software). adding an assertion would however not hurt.
