### ISSUE TITLE
[keymgr] Entropy to first key

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7614]
Right now, when keymgr is initialized, it populates the secret key state with entropy before overwriting with the secret key from OTP.  The purpose of the entropy is basically to create an unknown hamming delta from the base state to the loading of the first key. 

However, a better approach is to load the two shares of the key state with random data, and directly XOR in the OTP key. This will ensure that the secret key state is different "per boot" but also does not change any of the downstream consumption (since everywhere the key is maintained in two shares).

However, this particular feature will need to be tabled as it would have a large impact on DV.  Instead of verifying that the keys match a particular value, the DV will need to XOR the outgoing data stream (to KMAC) and incoming data stream (from KMAC) to compare against a known correct value. 

Filing this issue as an enhancement for the future.

**Comment by tjaychen** [comment]
@cdgori 
@weicaiyang

**Comment by cdgori** [comment]
Of course, I generally like the per-boot diversification this would get us (from a non-repeatability of attack / non-predictability of hardware perspective), but I understand the DV impact too.  

Because we are going to step the key values by two unknown hamming distances in the init process, we at least don't have to worry about a hamming weight leak, which I think would be the main worry.

**Comment by tjaychen** [comment]
it's kind of unfortunate honestly...because the native masking would be nice.
I'll leave it to @weicaiyang to decide if he's willing to absorb the potentially big DV change.

**Comment by weicaiyang** [comment]
@tjaychen 

Thanks for considering the DV impact.
With approach 1, we just need to XOR(key1, key0) to get OTP key, right?
For approach 2, seems like we need to do one more KDF with KMAC, not sure how exactly we get the OTP key to compare with?

**Comment by tjaychen** [comment]
hey @weicaiyang this is my understanding of the complication..

1. with the scheme today, you know what to expect in the "key" slot (because you can observe otp inputs and kmac input), so whenever a transaction goes out, you know exactly which value to compare against.

2. in the future, instead of doing a direct compare, you could not directly compare the key value or the kmac input value (since these will be masked with random data).  Instead for the outgoing key slot, you would need to XOR to get the real thing, and same with the returning kmac data.  Note however, that internally, we will always still store as 2 shares.
I guess it's not really a BIG dv change, but its yet another change..so i thought maybe it was best to table it.

**Comment by weicaiyang** [comment]
> hey @weicaiyang this is my understanding of the complication..
> 
> 1. with the scheme today, you know what to expect in the "key" slot (because you can observe otp inputs and kmac input), so whenever a transaction goes out, you know exactly which value to compare against.
> 2. in the future, instead of doing a direct compare, you could not directly compare the key value or the kmac input value (since these will be masked with random data).  Instead for the outgoing key slot, you would need to XOR to get the real thing, and same with the returning kmac data.  Note however, that internally, we will always still store as 2 shares.
>    I guess it's not really a BIG dv change, but its yet another change..so i thought maybe it was best to table it.

Thanks for explanation. Instead of comparing {key1, key0}, we will compare with XOR(key0, key1). It's a reasonable feature, and it probably doesn't look like a big DV change. I can work on the the DV update when you start the design change. Thanks

**Comment by GregAC** [comment]
@weicaiyang can this be closed?

**Comment by tjaychen** [comment]
this is actually labled as future enhance, let me move it to icebox.

**Comment by GregAC** [comment]
We've got a new FutureRelease type for things we intend to do for a future release. I think Icebox will be reserved for things we might not want to totally drop on the floor but are likely to continue to ignore. I think this fits better in the FutureRelease category?

**Comment by tjaychen** [comment]
yeah that makes sense. Thanks for the correction.

**Comment by ballifatih** [comment]
This indeed sounds like the right thing to do from SCA perspective. However, given that the secret value is large (256-bit) and there is already fresh randomness to prevent Hamming weight leakage, we can probably defer this to post-M2.5.

On the other hand, it would be great if we can ensure that KMAC is configured such that `CFG.msg_mask` is on, so that a fresh masking is applied prior to KMAC call. I suppose the part of the code that configures KMAC is part of ROM-Ext, but please correct me if I am wrong.

@jadephilipoom, @johannheyszl, @vogelpi

**Comment by ballifatih** [comment]
This was already merged before the sign-off  #17509, so I am closing this issue.
