### ISSUE TITLE
[spi/rtl] spi does not raise csb after ended transaction

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#7621]
with the fix in #7377  a new bug surfaces

when the spi_host finishes a transmit it does not raise csb to indicate transaction finished.
which keeps the test running until timeout! (CSAAT = 0)

with out having the full picture I think the problem might come from this code:
```
InternalClkHigh: begin
          // One of two active clock states. sck is low when CPOL=0.
          // Typically often the last state in a command, and so the next state depends on CSAAT,
          // and of CSAAT is asserted, the details of the subsequent command.
          if (!last_bit || !last_byte) begin
            prestall_st_d = InternalClkLow;
          end else if (command_i.segment.csaat) begin
            prestall_st_d = WaitTrail;
          end else if (!command_valid_i) begin
            prestall_st_d = IdleCSBActive;  // **<---- I think this is the problem**
          end else if (command_i.csid != csid_q) begin
            prestall_st_d = WaitTrail;
          end else begin
            command_ready_o  = 1'b1;
            prestall_st_d = InternalClkLow;
          end
        end
```

I think going to `IdleCSBActive`
when both `last_byte`and `last_bit` set 
is a mistake.
if there is no new command and CSAAT is low, shouldn't it just go to -> `WaitTrail` -> `WaitIdle` -> `IDLE`?

![image](https://user-images.githubusercontent.com/53917183/128371536-c44b0d66-0cfc-481a-9771-d2d61a77cc98.png)

to reproduce the issue
checkout
`spi_host_csb_stay_asserted` from my fork and run
`./util/dvsim/dvsim.py hw/ip/spi_host/dv/spi_host_sim_cfg.hjson -i spi_host_smoke -r 1 -t xcelium --job-prefix="nc run -C ncsim_interactive -Il" --waves=shm --seed=123`

**Comment by rasmus-madsen** [comment]
@martin-lueker or @Muqing-Liu 
could you take a look at this at you convinience

**Comment by martin-lueker** [comment]
Looks like there is an error in the sign interpretation of `command_i.segment.csaat`. This should be an easy fix.
