### ISSUE TITLE
[sw] Key Manager Configuration Changes for Sealing and Attestation

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#7652]
This issue describes the key manager configuration changes required to integrate the new key manager sealing and attestation derivation flows in alignment with the [Open Profile for DICE Specification](https://pigweed.googlesource.com/open-dice/+/refs/heads/main/docs/specification.md).

The proposed changes will be incorporated in relevant security specifications and in the `ROM` and `ROM_EXT` implementation.

## DICE Terminology

* **Unique Device Secret (`UDS`)**: per-device hardware-level secret only accessible to the DICE compliant function.
* **Compound Device Identifier (`CDI`)**: Represents the hardware/software configuration measured by DICE.
  * **Attestation CDI (`CDI_attestation`)**: Used to attest the hardware and software configuration. It is expected to change between software or configuration updates.
  * **Sealing CDI (`CDI_sealing`)**: Derived from the `UDS` and stable device configuration values. This `CDI` is appropriate for sealing use cases requiring a stable key derivation function.

### DICE to key manager state mapping

The key manager is advanced during the secure boot sequence to derive the following key manager internal states. There are two `CDI` levels available (`CDI0` and `CDI1`), which gives the Silicon Owner the ability to implement sealing and attestation policies for the `OWNER` code managed by the `BL0` partition.

Note that the key manager internal state is never exposed to software. Software can only use derived outputs from the internal state, either directly or sideloaded into one of the cryptographic accelerators.

DICE   | Key Manager Internal Sate       | Availability                 |
------ | ------------------------------- | ---------------------------- |
`UDS`  | `CreatorRootKey`                | `ROM_EXT`                    |
`CDI0` | `OwnerIntermediateKey`          | `ROM_EXT`, `BL0`             |
`CDI1` | `OwnerKey`                      | `BL0`, `OWNER (e.g. kernel)` |

## Key Manager configuration

The proposed changes provide the following properties:

### `ROM_EXT_UPDATABLE`

The Silicon Owner is allowed to push `ROM_EXT` updates to the device without changing the `UDS`. A stable `UDS` allows any Silicon Owner to attest the device against the `UDS` Silicon Creator endorsement certificate, which is specially useful during device ingestion, and ownership transfer.

The Silicon Creator may opt to force a `UDS` internal state change as part of the `ROM_EXT` update by changing the `ROM_EXT` manifest `binding_value` field. This process renders te `UDS` Silicon Creator endorsement certificate invalid.

### `ROM_EXT_OBSERVABLE_UPDATES`

`ROM_EXT` updates force the `CDI0` to change, allowing the Silicon Owner to measure the software configuration changes as part of device attestation.

The `ROM_EXT` must be verifiable out-of-band by the Silicon Owner. This means that the Silicon Owner must be able to compile the `ROM_EXT` from source and reproduce the expected hash of the build result. This gives the Silicon Owner a strong guarantee that the measured code during device attestation corresponds to the audited `ROM_EXT` version.

### `STABLE_CDI_SEALING`

All key manager CDI sealing derivations implement the following properties as described in the identities and root keys specification:

1. **[software binding](https://docs.opentitan.org/doc/security/specs/identities_and_root_keys/#software-binding)**: Software binding is used to ensure that the key derivation scheme is only reproducible for a trusted software configuration. This is achieved by having the secure boot implementation configure runtime-irrevocable binding tags in the key derivation scheme. Such tags are delivered inside the signed manifest of each boot partition.
1. **[key versioning](https://docs.opentitan.org/doc/security/specs/identities_and_root_keys/#key-versioning)**: Key versioning is the mechanism by which software implements key rotation triggered by security updates. Since there is more than one updatable code partition in the system, the key versioning scheme implements at least 4 32b version comparators with lockable controls, which are configured as part of the secure boot process.

#### `ROM`

The `ROM` configures the key manager to provide additional inputs to the derivation of the `CreatorRootKey` internal state. The `CreatorRootKey` is used to derive `UDS`.

* `ATTEST_SW_BINDING_{0-7}`: `ROM_EXT` manifest `binding_value`.
* `SEALING_SW_BINDING_{0-7}`: `ROM_EXT` manifest `binding_value`.

#### `ROM_EXT`

The `ROM_EXT` configures the key manager to provide additional inputs to the derivation of the `OwnerIntermedateKey` internal state. The `OwnerIntermedateKey` is used to derive `CDI0`.

The following measurements are required at this boot stage:

1. `ROM_EXT_CODE_HASH`: SHA2-256 of the `ROM_EXT` code partition excluding the manifest `signature` field.
1. `BLO_CODE_HASH`: SHA2-256 of the `BL0` code partition excluding the manifest `signature` field.

Configure the key manager software binding registers as follows:

* `ATTEST_SW_BINDING_{0-7}`: `SHA2-256(ROM_EXT_CODE_HASH | BL0_CODE_HASH)`   where `|` is the concatenation
  operator.
* `SEALING_SW_BINDING_{0-7}`: `BL0` manifest `binding_value`.

#### `BL0`

`BL0` configures the key manager to provide additional inputs to the derivation of the `OwnerKey` internal state. The `OwnerKey` is used to derive `CDI1`.

The following measurements are required at this boot stage:

1. `OWNER_CODE_HASH`: SHA2-256 of the next `OWNER` code partition excluding the manifest `signature` field.

Configure the key manager software binding registers as follows:

* `ATTEST_SW_BINDING_{0-7}`: `OWNER_CODE_HASH` value.
* `SEALING_SW_BINDING_{0-7}`: `OWNER` manifest `binding_value`.

**Comment by moidx** [comment]
CC: @mcy @cfrantz @alphan @drewmacrae @tjaychen

**Comment by tjaychen** [comment]
looks good to me! @weicaiyang i guess one important thing we'll need to do is to ensure the binding value is actually propagating to all the advanced calls correctly.

**Comment by weicaiyang** [comment]
> looks good to me! @weicaiyang i guess one important thing we'll need to do in testing is to ensure the binding value is actually propagating to all the advanced calls correctly.

Yes, we have that check in the scb.

**Comment by alphan** [comment]
@moidx can this issue be closed? It looks like https://github.com/lowRISC/opentitan/pull/13149 fixed this.

**Comment by moidx** [comment]
I think so. Let's close. I still have to update the documentation, but this issue can be used as a reference for now.

**Comment by moidx** [comment]
CC @johannheyszl  since this has some documentation related to attestation.

**Comment by johannheyszl** [comment]
cc @gdessouky
