### ISSUE TITLE
[rtl/lc_ctrl] Add assertions for lc_clk_byp_req_o

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#7663]
The lc_clk_byp_req_o output requests the system to use an alternate external clock. This should never be set in prod states, but should be used in some other states, like RMA, RAW, and some others. Add assertions for this behavior, either in the RTL or the DV collateral.

**Comment by msfschaffner** [comment]
Good point - I ahve added an assertion for this in RTL: #8051
