### ISSUE TITLE
[RV_PLIC Change Proposal] Address map compliance and CDC handling

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#7670]
Two design updates are proposed:

1. The RV_PLIC address map doesn't currently conform to the spec (#1491). The proposed change would be to correct that and reshape the CSR layout. 
2. We still need to synchronize all interrupt source signals to the RV_PLIC clock domain (this is currently NOT implemented yet #7435). To simplify synchronization, it would be good to standardize on level-triggered interrupts, and remove the runtime configurable, edge-triggered option. Note that OpenTitan comportable IP has to instantiate the standardized interrupt generation registers, which follow the level-triggered approach (https://docs.opentitan.org/doc/rm/comportability_specification/#interrupt-handling).

**PROS:**
1. The RV_PLIC address map would become standard compliant, which has benefits in terms of SW compatibility.
2. CDC handling can be simplified at the PLIC integration level.

**CONS:**

The RV_PLIC is currently in D2/V2 status. Need to re-assess FPV coverage to see whether the D2/V2 status can be maintained.
DV impact should be minimal, since this only moves / removes CSRs. No functionality is added.

----------------------------

A draft implementation of the above changes can be found here: #7648.

**Comment by dsandrs** [comment]
@cindychip @sriyerg  - Can you take a look and assess the DV impact?

**Comment by cindychip** [comment]
Thanks @dsandrs , the FPV block level impact is around 1 week (max 2 weeks with review).
1). Remove `LE` should be quite easy - mainly remove some assertions.
2). Add clock sync might affect the timing of some assertions, might take a few days to check and align.
Then we will revisit coverage to make sure it is not dropped below V2 requirement.

**Comment by tjaychen** [comment]
i think it might be worth pointing out one thing...

1. the LE change is the more optional one IMO
2. the synchronizer is more of a bug that has to be fixed. If we don't do that, the process will end up seeing interrupts from different domains and that could cause problems.

**Comment by msfschaffner** [comment]
Indeed, 2. is a required change for the CDC's to work correctly.

Note however that the LE selection currently does not fully work either, even if we leave it there. 
I.e., in order for this to work correctly, we would have to implement both level and pulse sync CDC options and make them runtime configurable using LE.

So, either we fix up the current LE feature with pulse and level CDCs, or we remove it altogether and only implement level syncs (proposed solution).

**Comment by msfschaffner** [comment]
Oh and I forgot to mention that if we decide to keep the runtime level / edge-triggered configurability, system integration gets a bit more involved as well, since the pulse CDCs require access to the source clocks and resets...

**Comment by msfschaffner** [comment]
This issue has now been addressed by #7648.
