### ISSUE TITLE
Cannot access memory at address 0x200005c0 after x/16xw 0x200005c0

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#7693]
nicolast0604@nicolast0604-VirtualBox:~/opentitan$ /tools/riscv/bin/riscv32-unknown-elf-gdb -ex "target extended-remote :3333" -ex "info reg" sw/device/boot_rom/rom.elf
GNU gdb (crosstool-NG 1.24.0.41-475d72f) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=x86_64-build_pc-linux-gnu --target=riscv32-unknown-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<toolchains@lowrisc.org>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
sw/device/boot_rom/rom.elf: No such file or directory.
Remote debugging using :3333
warning: Target-supplied registers are not supported by the current architecture
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
Truncated register 16 in remote 'g' packet
The program has no registers now.
(gdb) x/16xw 0x200005c0
0x200005c0:	Cannot access memory at address 0x200005c0
(gdb) disassemble 0x200005c0,0x200005c0+16*4
Dump of assembler code from 0x200005c0 to 0x20000600:
   0x00000000200005c0:	Cannot access memory at address 0x200005c0
(gdb) monitor mdw 0x200005c0 16
"monitor" command not supported by this target.
(gdb)

**Comment by tjaychen** [comment]
is this one still valid? not sure what fpga this was tried on.
but gdb / jtag access has only recently been enabled on cw310.  I will close this for now, feel free to re-open if my assumptions are incorrect.
