### ISSUE TITLE
[kmac]  SW cmd during App operation triggers SwSequence error

### ISSUE THREAD

**Issue by udinator** [lowRISC/opentitan#7716]
Hi Eunchan,

I'm testing a scenario where SW sends a random command (in this case `CmdManualRun`) to the KMAC during operation of the App interface, expecting that the RTL raises a `ErrSwIssuedCmdInAppActive` error.

However, I end up getting an `ErrSwCmdSequence` error from the RTL instead, which IMO is incorrect.

This is because the `kmac_errchkr` module processes the incoming SW cmd one cycle before sending it out to the rest of the IP (including `kmac_app`) .

The FSM remains in `StIdle` as `app_active_i` will be high, so the sequencing check logic sees a `CmdManualRun` while the FSM is still in Idle state and raises a `ErrSwCmdSequence` one cycle before the `kmac_app` has a chance to do anything.

I think the fix for this would be to only treat sequence errors as valid inside the `kmac_errchkr` if we are not in App mode, as the `kmac_app` will detect any SW commands sent during App operations.

WDYT?

**Comment by udinator** [comment]
Hi @eunchan, could you take a look at this issue if you have time?

**Comment by eunchan** [comment]
OK Sorry for missed this! Let me take a look.

**Comment by eunchan** [comment]
I just read your description. It looks like the stimuli sent ManualRun without Start command. I expect that one could fall into both category. As the state machine won't move from StIdle to next states, the `kmac_errchk` logic only accepts Start command and hand over to kmac_app module.

The case we may see the `ErrSwIssuedCmdInAppActive` is when the SW sends Start command while the App Interface is active.

**Comment by udinator** [comment]
ahh got it, so SwIssuedCmdInAppActive is specifically when SW sends Start command during App interface.
Is it possible to update the specs to reflect this?

**Comment by tjaychen** [comment]
@eunchan do you mind having a look at this? from what i remember this has also been addressed.

**Comment by eunchan** [comment]
Yep. Thanks for pinging me. This has been addressed. There's explicit errchk module to check the sequence.
