### ISSUE TITLE
[Change Proposal] Further OTP/LC Updates for Secure Manufacturing

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#7725]
This is a continuation of #7330 and proposes additional changes to OTP/LC to support vendor-specific OTP smoke checks for the secure manufacturing flow.

In particular:
1. **OTP_CTRL**:
    - allocate a new SW partition, to be used for vendor specific testing purposes only. the partition will be called `VENDOR_TEST`.
    - the partition will be 512bit in size, and allocated at offset 0x0 of the OTP memory map (i.e., before the `*_SW_CFG` partitions)
    - the corresponding offset and size parameters generated by the memory map script will be forwarded into the `prim_otp` wrapper
    - the `prim_otp` wrapper may disable ECC checks on that region, and implement vendor-specific OTP smoke checks
2. **LC_CTRL**:
    - two additional CSRs will be added to the life cycle controller TAP: a vendor test control and status register (both 32bit in size)
    - these two registers will be connected to the `prim_otp` wrapper, and the bits in those registers can be used for vendor-specific OTP smoke checks
    - these two registers will only be usable in `TEST*`, `RAW` and `RMA` life cycle states

The design and DV impact on the open-source side is not substantial, since we only add a new partition (this is partially scripted), and two CSRs with no functionality attached (the CSRs are routed to the `prim_otp` wrapper).

The changes have been discussed and agreed upon.

**Comment by msfschaffner** [comment]
CC: @danaagur

**Comment by zi-v** [comment]
Thanks @msfschaffner!
Sounds good.

**Comment by msfschaffner** [comment]
Ok, these changes have now been implemented.
