### ISSUE TITLE
Warn : JTAG tap: riscv.tap       UNEXPECTED: 0x00000001 (mfg: 0x000 (<invalid>), part: 0x0000, ver: 0x0) Error: JTAG tap: riscv.tap  expected 1 of 1: 0x04f5484d (mfg: 0x426 (Google Inc), part: 0x4f54, ver: 0x0) Error: Trying to use configured scan chain anyway... Warn : Bypassing JTAG setup events due to errors

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#7733]
openocd -s util/openocd -f board/lowrisc-earlgrey-nexysvideo.cfg with Nexysvideo

Please hint, thanks a lot.

Open On-Chip Debugger 0.11.0
Licensed under GNU GPL v2
For bug reports, read
http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter speed' not 'adapter_khz'
Info : Hardware thread awareness created
force hard breakpoints
none separate

Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : clock speed 30000 kHz
Info : JTAG tap: riscv.tap tap/device found: 0x00000001 (mfg: 0x000 (), part: 0x0000, ver: 0x0)
Warn : JTAG tap: riscv.tap UNEXPECTED: 0x00000001 (mfg: 0x000 (), part: 0x0000, ver: 0x0)
Error: JTAG tap: riscv.tap expected 1 of 1: 0x04f5484d (mfg: 0x426 (Google Inc), part: 0x4f54, ver: 0x0)
Error: Trying to use configured scan chain anyway...
Warn : Bypassing JTAG setup events due to errors
Info : datacount=2 progbufsize=8
Info : Examined RISC-V core; found 1 harts
Info : hart 0: XLEN=32, misa=0x40101104
Info : starting gdb server for riscv.tap.0 on 3333
Info : Listening on port 3333 for gdb connections

**Comment by nicolast0604** [comment]
openocd -s util/openocd -f board/lowrisc-earlgrey-nexysvideo.cfg with Nexysvideo

Please hint, thanks a lot.


Open On-Chip Debugger 0.11.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter speed' not 'adapter_khz'
Info : Hardware thread awareness created
force hard breakpoints
none separate

Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : clock speed 30000 kHz
Info : JTAG tap: riscv.tap tap/device found: 0x00000001 (mfg: 0x000 (<invalid>), part: 0x0000, ver: 0x0)
**Warn : JTAG tap: riscv.tap       UNEXPECTED: 0x00000001 (mfg: 0x000 (<invalid>), part: 0x0000, ver: 0x0)
Error: JTAG tap: riscv.tap  expected 1 of 1: 0x04f5484d (mfg: 0x426 (Google Inc), part: 0x4f54, ver: 0x0)
Error: Trying to use configured scan chain anyway...**
Warn : Bypassing JTAG setup events due to errors
Info : datacount=2 progbufsize=8
Info : Examined RISC-V core; found 1 harts
Info :  hart 0: XLEN=32, misa=0x40101104
Info : starting gdb server for riscv.tap.0 on 3333
Info : Listening on port 3333 for gdb connections

**Comment by vogelpi** [comment]
We've officially dropped support for the NexysVideo (see #7814 ). The ChipWhisperer CW310 is our main FPGA development platform. #10625 will add openocd support but we still need to change some pins in the FTDI MPSEE emulation of the SAM3X. I am closing this issue.
