### ISSUE TITLE
ERROR: 'lowrisc:dv:chip_verilator_sim' or any of its dependencies requires 'chip_verilator_sim', but this core was not found

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#7734]
nicolast0604@nicolast0604-VirtualBox:~/opentitan$ fusesoc --cores-root . run --flag=fileset_top --target=sim --setup --build lowrisc:dv:chip_verilator_sim
WARNING: Unknown item formal in section Target
WARNING: Unknown item formal in section Target
WARNING: Unknown item formal in section Target
ERROR: 'lowrisc:dv:chip_verilator_sim' or any of its dependencies requires 'chip_verilator_sim', but this core was not found

Any hint is welcome, I am new to this field. Thanks a lot.

**Comment by imphil** [comment]
Have you made any change to the source tree? The command works for me on a clean opentitan checkout, and also runs in CI.

**Comment by nicolast0604** [comment]
Hi I didn't make any change to the source tree. 
opentitan-earlgrey_silver_release_v5-561-g5392c8604

I will re-git clone it again and try to see if I missed anything.

**Comment by nicolast0604** [comment]
The repro I just git cloned works so I guess there is database truncated last time I download.

Thanks a lot.
