### ISSUE TITLE
[rtl/top_earlgrey] Fix clk/rst_n pairs

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#7763]
Connect rst_n synchronous to the clk for flops.

In the following two cases rst_n is from a different clock domain as the corresponding clk:
- u_pwrmgr_aon has clk_i connected to an io_div4 , and rst_ni to rst_por_n reset output of rstmgr, which is clocked by clk_main_i.
- u_rstmgr_aon has clk_i connected to some io_div4 clock, and the rstmgr logic is reset by its local_rst_n, which is hooked up to its own rst_por_io_div2 reset output, which is from the io_div2_clk domain.

**Comment by tjaychen** [comment]
good catch on `pwrmgr`!
can you double check rstmgr on top of tree? because i removed the usage of `local_rst_n` some time ago, it was related to #7459

**Comment by tjaychen** [comment]
i believe this should have been fixed already.  `local_rst_n` is no longer present and the others should be matching the correct synchronizing domains.
