### ISSUE TITLE
[dv/hmac] enhancement on DV testbench

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#777]
These are the items I plan to implement after design finalized:

- [x] Wipe Secret Test: current hmac testbench only check if the wipe secret registers can be read and write, no functionality check.

- [ ] Throughput Test: with no delays, check if the throughput meets the timing.

- [x] Toggle config register (sha_en only or shall we test all of them?) between msg stream in, test DUT won't hang. 

- [x] Confirm on max outstanding items in this PR: https://github.com/lowRISC/opentitan/pull/10489 with designer

Add @eunchan  @sriyerg for visibility.

**Comment by cindychip** [comment]
item 3 is finished in PR https://github.com/lowRISC/opentitan/pull/1023

**Comment by msfschaffner** [comment]
@cindychip can you update the status of this issue?

**Comment by cindychip** [comment]
They are still TODOs for HMAC to reach V3.

**Comment by cindychip** [comment]
https://github.com/lowRISC/opentitan/pull/9185 Reference for 1) TODO

**Comment by cindychip** [comment]
https://github.com/lowRISC/opentitan/pull/10363 Finished TODO 1).

**Comment by tjaychen** [comment]
@arunthomas 
@cfrantz 

is the throughput item something the software team could help with? :)
Especially since we probably care most about throughput at a system level and not just the block.

**Comment by martin-velay** [comment]
I have discussed this with @vogelpi and we both believe that is not a critical requirement. We don't have such throughput tests for other crypto blocks and thus believe we should invest our DV resources into more critical items.
I am closing this now, but feel free to re-open if you feel it should be covered.
