### ISSUE TITLE
[doc, entropy_src] Provide description of how otp_en_entropy_src_fw_read_i is used 

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#7785]
I am mapping the TODOs that came from chip level testplan reviews to issues. One of these is:
```
Add description on how otp_en_entropy_src_fw_read_i input from OTP is used by entropy_src
```

**Comment by mwbranstad** [comment]
A description is provided in PR #7497.

**Comment by tjaychen** [comment]
i think we can close this one now since the description is there.
