### ISSUE TITLE
How to add custom modules in example Verilator simulation

### ISSUE THREAD

**Issue by ninipa** [lowRISC/opentitan#7804]
Hi Experts,

I'm freshman of Opentitan and fusesoc compilation flow. I have followed "Getting Started with Verilator" and run the example simulation successfully. 
My build options are:
_fusesoc --cores-root . run --flag=fileset_top --target=sim --setup --build lowrisc:dv:chip_verilator_sim_
Now, I'm going to add some customized monitors in the design, however I can't find obvious file list or configuration file to modify. Since I'm not familiar with Opentitan fusesoc flow, could you please kindly point me how to add certain module in the simulation?
Thanks very much!

**Comment by imphil** [comment]
Welcome to OpenTitan! To add a new IP block, you need to
- Create the block itself (probably in a new directory in hw/ip)
- Add a FuseSoC .core file with the source files and other build description
- And add a dependency to this new core in the toplevel core (probably hw/top_earlgrey/top_earlgrey.core)

To learn more about FuseSoC core files, have a look at the documentation at https://fusesoc.readthedocs.io/en/stable/user/index.html or existing core files in OpenTitan.

**Comment by ninipa** [comment]
> Welcome to OpenTitan! To add a new IP block, you need to
> 
> * Create the block itself (probably in a new directory in hw/ip)
> * Add a FuseSoC .core file with the source files and other build description
> * And add a dependency to this new core in the toplevel core (probably hw/top_earlgrey/top_earlgrey.core)
> 
> To learn more about FuseSoC core files, have a look at the documentation at https://fusesoc.readthedocs.io/en/stable/user/index.html or existing core files in OpenTitan.

Thanks very much! I can add new module and run simulation now.
Another question about building the simulation database:
How to do incremental building with fusesoc? I didn't find related options or configurations. Now, even I just modify a little bit in RTL, I need to remove "build" directory and re-build it from scratch, otherwise if "build" already exists, it will not start a build operation with
_fusesoc --cores-root . run --flag=fileset_top --target=sim --setup --build lowrisc:dv:chip_verilator_sim_

**Comment by imphil** [comment]
You don't need to remove the build directory, but you'll still get a full rebuild with Verilator -- there's no way around it, Verilator doesn't do incremental builds.

You can use the latest version of Verilator and ccache, this will give your faster builds for many cases. Or you can reduce the optimization level in Verilator, which is set in top_earlgrey.core (e.g. go down to -O0). This will give you faster builds, and slower runtime.
