### ISSUE TITLE
[reggen] Could we move the CDC from prim_subreg_async to a register-level class?

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#7810]
After thinking for a while about how to de-duplicate signals like the per-field `qe` in hw2reg, I realised that this was doomed to failure! The problem is that registers that instantiate `prim_subreg_async` synchronise their signals from one clock domain to the other at a per-field level. That means that it's not possible to guarantee that a "register-level signal" like `we` crosses at a single point in time.

Would it make sense to define something like `prim_reg_cdc` that synchronised signals like `we`, but also synchronised write data for all the fields needed? If we did that, we'd know that all the fields of a register were guaranteed to be updated on the same cycle in the destination clock, which is probably a nice property to have. Also (and, arguably, less important), it would make it possible to de-duplicate some signals that are logically per-register.

@tjaychen: I know this is your design. Am I missing some fundamental reason that we have to do the CDC per-field?

**Comment by tjaychen** [comment]
the cdc per field is mostly out of convenience (since we've already split things up this way). And yes you're right, this could mean if you update a bunch of fields from the software side, they will update value at slightly different times on the other side.   But is this a problem? The fields are effectively independent entities no?

Ideally what i prefer to do is to wrap up the fields into something like prim_reg (the whole register) that then declares individual fields underneath.

**Comment by rswarbrick** [comment]
I assumed that the reason we don't have "`prim_reg`" is that we'd need to auto-generate it for all the different field layouts that we see in the design. My cunning plan above(!) avoids this problem because the only parametrisation needed is the wdata width. But maybe I've misunderstood your suggestion?

You're right about the fields being independent entities, but I'm a little worried about SW writing a consistent set of field values and hardware spending a cycle where it only sees half of the updates, and spits out an alert because it thinks something weird is going on. Not sure whether we have any such hardware at the moment, but it's the sort of weirdness that we probably wouldn't expect to trigger when testing.

Also, good point about `prim_subreg_arb`. I *think* that's a separate question: once we've crossed clock domains, `prim_subreg_async` has a `prim_subreg` which itself has the synchronous `prim_subreg_arb` arbiter. I'd guess that all the arbitrations will go the same way (because everything is synchronous!), and maybe we could get rid of that duplication in future as well... assuming that we don't have any hardware that sets `de` for the different fields differently.

**Comment by tjaychen** [comment]
ah i should clarify i guess i have 2 questions

1. is the qe de-duplicating something very important to have at the moment?
2. assuming qe de-dupe is not super high priority right now, do we think the fact that individual fields updating at different times can cause a problem?
3. would be okay with wrapping the individual prim_subreg up into a prim_reg as a solution?

**Comment by rswarbrick** [comment]
For me: (1): No! (2): Hmm, maybe: see above (we collided!) (3): I'm not sure whether that can be done in SystemVerilog.

**Comment by tjaychen** [comment]
> I assumed that the reason we don't have "`prim_reg`" is that we'd need to auto-generate it for all the different field layouts that we see in the design. My cunning plan above(!) avoids this problem because the only parametrisation needed is the wdata width. But maybe I've misunderstood your suggestion?
> 
> You're right about the fields being independent entities, but I'm a little worried about SW writing a consistent set of field values and hardware spending a cycle where it only sees half of the updates, and spits out an alert because it thinks something weird is going on. Not sure whether we have any such hardware at the moment, but it's the sort of weirdness that we probably wouldn't expect to trigger when testing.

this part at least shouldn't be a problem. the way the prim cdc works (at least in theory) is that if one update is not done, it asserts "busy".  Until all busy's are 0, software cannot access the same register again (read or write). 

> 
> Also, good point about `prim_subreg_arb`. I _think_ that's a separate question: once we've crossed clock domains, `prim_subreg_async` has a `prim_subreg` which itself has the synchronous `prim_subreg_arb` arbiter. I'd guess that all the arbitrations will go the same way (because everything is synchronous!), and maybe we could get rid of that duplication in future as well... assuming that we don't have any hardware that sets `de` for the different fields differently.

**Comment by tjaychen** [comment]
> For me: (1): No! (2): Hmm, maybe: see above (we collided!) (3): I'm not sure whether that can be done in SystemVerilog.

sorry for 3 what i meant is that we skip around the part where i was lazy and actually re-code this part of regfile hehe.
I didn't want to introduce a ton of change, but IMO the right change is probably to change the hierarchy here.

**Comment by rswarbrick** [comment]
> this part at least shouldn't be a problem. the way the prim cdc works (at least in theory) is that if one update is not done, it asserts "busy". Until all busy's are 0, software cannot access the same register again (read or write).

I guess I'm imagining a situation where a (slightly crazy...) HW block has a register with two fields, A and B. It's an error to write a value where A != B, and the HW will decide we're under attack and raise an alert. The register is currently all zeros. SW now writes the value `0xffffffff`. One field makes it across before the other and... bang!

Obviously, that would be a pretty silly design, but the notion of "we assume these fields are consistent because SW writes them all at once" doesn't sound so crazy to me.

**Comment by tjaychen** [comment]
well i think the most likely thing that would happen is a control register with a bunch of fields, and one such field is the "enable".
so you might trigger the enable with the other fields not completely at the right value, and maybe that'll trickle into something else.

**Comment by tjaychen** [comment]
i can make a fix for this, but this will need some changes i think with how 're' is propagated. 
right now before arbiter, we need to assign re to we depending on the type. 

So the we received by the fields of the same register are not necessarily the same. So we probably need to refactor the logic a little bit.

**Comment by tjaychen** [comment]
actually there may be a quicker fix than i realized without having to change too much.
I'll try to have a look later today.

**Comment by tjaychen** [comment]
@rswarbrick i have a prototype of this, but it's not super clean.

Before added cdc, we basically had this

`regfile front door handling logic -> per field subreg`

After we added cdc (by treating each field as independent), we got this:
`regfile front door handling logic -> per field cdc handling (if needed) -> per field subreg`

The nice part about this is that we did not have to change most of the logic on the per subreg handling. (Ie all the determination of what a signal should be based on what types they are).

If we move the cdc handling to the reg level, but allow old vanilla registers to stay the same, we now effectively have two paths
```
regfile front door  |-> per reg cdc handling -> per field subreg
                            |-> per field subreg
```
This causes us to duplicate some of the python logic as we need some at the reg level and some at the field level. 
I think the cleaner way long term is to introduce an extra hierarchy, the "reg" to wrap up all the relevant fields, then everything will become more streamlined. 

I'm...not going to do that for this one :). Anyways, I'll run some sims and see if it works and push for review.

**Comment by rswarbrick** [comment]
Awesome! Thanks for looking at it.
