### ISSUE TITLE
[sysrst_ctrl, top] Default pin assignments

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7821]
This issue is related to #7797 

Since `flash_wp_l` is currently missing from the design, the [pin assignments](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/top_earlgrey.hjson#L1172) are not quite right.

There are a few things to fix.

1. the new `flash_wp_l` function, once added, should be the dedicated function on IOR9
2. `ec_rst_in_l` and `ec_rst_out_l` are actually the same pin, so they both should be dedicated to IOR8 (we detect the input value and then drive right back onto it to stretch)
3. There is one extra IOR pin and there are current sysrst_ctrl functions (see line 64 [here](https://docs.google.com/spreadsheets/d/1jp-paagh2_sJFMUFnewx0XAUmLdCCgXn8NnB2BNEk-Q/edit?usp=sharing)). This pin can thus act as a generic GPIO since it is fully muxable (there's nothing exactly to fix for this one, but rather just wanted to point it out).

**Comment by tjaychen** [comment]
@toshaq @dsandrs @sriyerg FYI

**Comment by msfschaffner** [comment]
1. This should be straightforward to add.
2. Hm ok this introduces a nice combo loop with the current design, and I believe the design currently can't handle the dynamic IO enable that would be needed. Does this have to be implemented that way, or can we loop it through (e.g. using this extra IOR0 pin)?

**Comment by tjaychen** [comment]
hmm? i dont really follow what you mean on 2. 
where's the combo loop introduced?

**Comment by msfschaffner** [comment]
if ec reset in / out are connected to the same pad, we get a combo loop since the passthrough logic is purely combinational.

**Comment by tjaychen** [comment]
wait, is there an ec reset in / out passthrough? when i was poking at it
earlier, i only saw ec_rst_in hitting a dual flop directly.
I might be looking at outdated code though.

**Comment by msfschaffner** [comment]
sorry, you are right. the ec reset input is one of those that do not have a combo passthrough mode.
however, the hardware currently always drives the output (i.e., there is no dynamic modulation of OE).

**Comment by tjaychen** [comment]
hmmmm.... let's sync up with Toshak here to be sure.
I know in the past this was supposed to be...we sit and listen for the line
(input), then when we see it go low, we come back and drive it low.

we should check to see if this is still the case.

**Comment by tjaychen** [comment]
i just checked in @toshaq 

so we do need `ec_rst_l_in` and `ec_rst_l_out` to be on the same pin. 
`sysrst_ctrl` does drive OE to high all the time, however since these are all open drain pins, when we drive a '0' value, it effectively releases us from driving the pin.

**Comment by msfschaffner** [comment]
Ok I see. I'll remap things accordingly then.

**Comment by msfschaffner** [comment]
Ok the pins have been reassigned. 

However, let's keep this issue open until we could double check the OD behavior with @toshaq.
