### ISSUE TITLE
Can opentitan/ibex work with general purpose debugger like Seggar J-link and then with Eclipse and VC code?

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#7832]
Hi All

As there is plugin for Seggar J-link with Eclipse and can upload the ELF and debug with Eclipse.
I am curious if there is this kind of option for opentitan/ibex and if yes how. If no, what is the direction to make it happen?

Nicolas

**Comment by GregAC** [comment]
Hi @nicolast0604 

OpenTitan has JTAG which could be connected to the Seggar J-link. To do this with the FPGA you'd need an FPGA build that exposes the JTAG pins to an external header than the probe could then be plugged into.

OpenOCD can be used to connect to the RISC-V debug module over JTAG and provide a remote target that GDB can connect to. Eclipse or other IDEs can use this to implement interactive debug and ELF uploading (see OpenOCD and GDB details here: https://docs.opentitan.org/doc/ug/getting_started_fpga/ near the bottom of the page).

This would potentially just work once the appropriate JTAG pins are exposed on the FPGA. Someone with access to a Seggar J-Link and a CW310 board would need to try it and see.
