### ISSUE TITLE
[ibex, epmp] Set reset values for ePMP CSRs

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#7834]
Currently all ePMP CSRs are set to 0 when the device is reset. Ideally I think we should have a more locked down configuration encoded in the reset logic. I see a couple of options for the reset logic (we could also combine them):

1. Specify a single PMP entry which makes eFlash read-only or totally inaccessible at reset (i.e. hard code entry 5 in [memory protection](https://docs.opentitan.org/sw/device/silicon_creator/mask_rom/docs/memory_protection/) into the reset logic).

    | Entry | Address Space | Encoding | Permissions |
    |-|-|-|-|
    | 5 | eFlash | NAPOT | L or LR |

2. Specify PMP entries for the ROM (RX) and MMIO (RW) address spaces and lock down all other accesses using either a final locked NAPOT region disabling all other access to the entire address space or by enabling MMWP.

    | Entry | Address Space | Encoding | Permissions |
    |-|-|-|-|
    | 2 | ROM | NAPOT | LRX |
    | 11 | MMIO | TOR (or NAPOT) | LRW |
    | 15? | All | NAPOT | L (no access) |

I prefer option 1 since it is simpler while still preventing premature execution of eFlash. It also means that the test ROM can easily disable memory protection and therefore existing test behavior can be retained for the time being.

**Comment by mundaym** [comment]
@GregAC @alphan @moidx

**Comment by mundaym** [comment]
(We will also need to add `MSECCFG.RLB=1` to the reset logic.)

**Comment by tjaychen** [comment]
> Currently all ePMP CSRs are set to 0 when the device is reset. Ideally I think we should have a more locked down configuration encoded in the reset logic. I see a couple of options for the reset logic (we could also combine them):
> 
> 1. Specify a single PMP entry which makes eFlash read-only or totally inaccessible at reset (i.e. hard code entry 5 in [memory protection](https://docs.opentitan.org/sw/device/silicon_creator/mask_rom/docs/memory_protection/) into the reset logic).
>    
>    
>    
>    Entry
>    Address Space
>    Encoding
>    Permissions
>    
>    
>    
>    
>    5
>    eFlash
>    NAPOT
>    L or LR
> 2. Specify PMP entries for the ROM (RX) and MMIO (RW) address spaces and lock down all other accesses using either a final locked NAPOT region disabling all other access to the entire address space or by enabling MMWP.
>    
>    
>    
>    Entry
>    Address Space
>    Encoding
>    Permissions
>    
>    
>    
>    
>    2
>    ROM
>    NAPOT
>    LRX
>    
>    
>    11
>    MMIO
>    TOR (or NAPOT)
>    LRW
>    
>    
>    15?
>    All
>    NAPOT
>    L (no access)
> 
> I prefer option 1 since it is simpler while still preventing premature execution of eFlash. It also means that the test ROM can easily disable memory protection and therefore existing test behavior can be retained for the time being.

Just to double check, is the idea here you don't want ROM to have to do any settings, or that we want things super locked down? 
If it's the latter, wouldn't option 2 be better? I'd almost also recommend removing entry 11 and let ROM decide how to free things up.  Because otherwise you technically want to carve out specific regions for the peripherals you care about right?

**Comment by tjaychen** [comment]
one more shameless plug. The read logic in front of the flash controller can also be set that by default, it will not execution reads to pass through. So we could also make use of this mechanism (in addition to pmp), to achieve the first above.

**Comment by mundaym** [comment]
> is the idea here you don't want ROM to have to do any settings, or that we want things super locked down? If it's the latter, wouldn't option 2 be better? I'd almost also recommend removing entry 11 and let ROM decide how to free things up. Because otherwise you technically want to carve out specific regions for the peripherals you care about right?

Personally I think the only thing that needs to be locked down at reset is eflash execution. I don't want to limit access to the MMIO address space too much as that would limit our ability to reset and otherwise lock down the chip. We could consider locking out particular peripherals if we felt it was worthwhile, but we currently don't do that.

> The read logic in front of the flash controller can also be set that by default, it will not execution reads to pass through. So we could also make use of this mechanism (in addition to pmp), to achieve the first above.

Sounds good to me. I think this would be a fine way to achieve what I am after. We could then continue to leave the ePMP configuration up to the mask ROM.

**Comment by tjaychen** [comment]
what would be the best way to make use of this bit? I can easily default it to no execute, and let ROM come in later to flip it.
Btw, i think it would still be a good idea to have a dedicated region, that way we have some defense in depth against faulting very early on.

And one last question, regarding no execute at power-up, wouldn't you want to apply it to everything but the ROM? I don't mean read access here, but execute.

**Comment by mundaym** [comment]
> what would be the best way to make use of this bit? I can easily default it to no execute, and let ROM come in later to flip it.

That makes sense to me.

> And one last question, regarding no execute at power-up, wouldn't you want to apply it to everything but the ROM? I don't mean read access here, but execute.

Yes. As I am aware the only memories from which instructions may be fetched are the ROM, main SRAM and flash. Main SRAM has execution disabled at reset already, so if we added the feature you propose then I think the ROM would be the only memory left that would be executable at reset. Does that sound right to you?

**Comment by tjaychen** [comment]
that sounds good!
just to be clear, who disables sram execution by default? Are you relying
on the OTP disable of sram execution?

**Comment by mundaym** [comment]
The reset value of `sram_ctrl.EXEC` is 0 which means (IIUC) SRAM execution is disabled initially even if SRAM execution is enabled in OTP.

**Comment by tjaychen** [comment]
sounds great! yes that uses almost an identical mechanism to flash.
So we can do the same thing on flash side.

**Comment by tjaychen** [comment]
i'm going to assign myself to this issue otherwise i'm never going to remember.
I still honestly would recommend a blanket region to cover everything but ROM, defense in depth would be good :)

**Comment by felixmiller** [comment]
This issue has been discussed in the Security WG meeting on 2021-09-16. Group feedback:

1. Set ePMP registers to have non-zero reset values.
2. Add a register to explicitly enable flash execution. This is already supported in the flash controller.
- Need ROM support so that the assembly exception handler can reset the chip.
- @tjaychen: I recommend doing both 1. and 2. so that we can increase the coverage against glitch.
- @GregAC: Looking into a mechanism to enforce reset values.
- Action Item: @GregAC to work with mike.m to implement a set of reset values aligned with the ROM’s secure boot requirements.
