### ISSUE TITLE
[dv/shadow_reg] DV TODOs for shadow reg

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#7845]
Discussed in PR: https://github.com/lowRISC/opentitan/pull/7753

- [x] Shadow reg functional coverage
- [x] Shadow reg sequence mixes with CSR rw sequence
- [x] Shadow reg check status
- [x] Shadow reg resets

**Comment by msfschaffner** [comment]
Has this been addressed by now?

**Comment by cindychip** [comment]
> Has this been addressed by now?

Oops, I have not finished the functional coverage.. I will do it next week!
