### ISSUE TITLE
[Change Proposal] Otbn key wipe request to keymgr

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7847]
Keymgr sideload, generally speaking, is actuated by software.  Software commands keymgr to setup sideload keys for a specific target and requests keymgr to discard them when the operation is complete.  This works fine for Aes / Kmac. 

For Otbn, the story is a bit different since Otbn also runs its own software stack. Otbn thus knows exactly when it has no more use of the keys, but this may happen in the middle of its execution and it is not able to inform the host software to clear key manager keys. 

Ideally, the long term solution is that Otbn should be made an equivalent controller of keymgr as the ibex is.  This would however require some mutexing between the two sides to correctly arbitrate.

For now, this proposal suggests we add a "key wiping request" from otbn to keymgr, so at least we are able to discard the otbn key when it is no longer needed. 

> estimate 2

**Comment by tjaychen** [comment]
@moidx 
@felixmiller

**Comment by tjaychen** [comment]
@weicaiyang , this obviously increases the burden on keymgr verification.  Specifically on the otbn sideload key (this does not apply to the other interfaces). Can you let me know what you think? I don't personally think this feature is critical (conferring with others to make sure), so this is something we could consider tabling.

**Comment by weicaiyang** [comment]
@tjaychen
I think it's OK. We can add it. This should be a very simple feature to DV.

**Comment by imphil** [comment]
I'd see a "wipe the sideloaded key" request from OTBN to the key manager as optimization, but not as necessity.

If the author of a crypto routine wants to remove the sideloaded key from the key manager after a certain point in time, they can use a workaround like this:

1. Execute the first part of the crypto routine on OTBN which reads the sideloaded key. Store the key in OTBN's DMEM (either raw, or in some processed form).
2. End the routine on OTBN, hand control back to Ibex.
3. Have software on Ibex instruct the key manager to remove the sideloaded key.
4. Execute the second part of the crypto routine.
5. On Ibex, read the results and instruct OTBN to wipe the DMEM.

That's not as performant as having a "delete key request" from OTBN to the key manager, but it's not massively slow either (effectively 1 interrupt latency and a couple instructions on Ibex).

Given our current schedule situation and the availability of a (as I find) reasonable workaround, I'd not implement the feature.

**Comment by cdgori** [comment]
Agreed that this is nice-to-have.  @imphil 's proposed workaround looks OK if this is considered necessary for a specific OTBN crypto routine.

**Comment by johannheyszl** [comment]
@jadephilipoom for quick opinion pls: Seems ok for ibex to trigger key wipe and no direct trigger from OTBN to key mgr is needed, WDYT?

**Comment by jadephilipoom** [comment]
Yep, agreed, the summary above by @imphil makes sense to me. Especially since the keymgr use cases will normally be two-step anyway (generate private key from seed, then generate public key from private key), passing back to Ibex is not prohibitively inconvenient.

**Comment by johannheyszl** [comment]
Closing this issue since discussion reasonable shows we do not need this.
