### ISSUE TITLE
[keymgr] shadow reg status issue

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#7873]
Hi Tim,

According to Weicai's comment on this PR:
https://github.com/lowRISC/opentitan/pull/7872#discussion_r693232514

When storage error triggered, we expect to see `error_code.invalid_states` to set to 1 and `ault_status.shadow` to set to 1.
However in the waveform, `error_code.invalid_states` did not set to 1 because it is gated by `op_ack` signal.
All the other signals behave correctly, including: ral.fault_status.shadow and alert_rx/tx.

![image](https://user-images.githubusercontent.com/11466553/130301567-a0e9ccce-dd7e-4650-8331-9ff195694540.png)

CC: @weicaiyang 

Thanks,
Cindy

**Comment by weicaiyang** [comment]
looks like it's the same issue as #7772

**Comment by tjaychen** [comment]
yes i'm not sure right now what the right behavior should be.

Otbn is taking the approach where ERR_CODE represents operational errors,
whereas fault status is any fault.
I feel like that might be a reasonable approach, and if everyone agrees, i
want to converge on that so we don't have so many different ways of
handling things (of course..other modules also behave differently..)

**Comment by tjaychen** [comment]
@weicaiyang @cindychip is this issue clearer now given the recent keymgr updates?
A shadow update error will show up in err_code, but shadow storage will show up in fault_status.

let me know what you guys think.

**Comment by weicaiyang** [comment]
> @weicaiyang @cindychip is this issue clearer now given the recent keymgr updates?
> A shadow update error will show up in err_code, but shadow storage will show up in fault_status.
> 
> let me know what you guys think.

This has been fixed. Let me close this issue now. Thanks Tim
