### ISSUE TITLE
[otbn] Integrity-protect BN.LID destination register during multi-cycle execution

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#7888]
Add integrity information for BN.LID destination register which is read in the first cycle and used in the second cycle. Implementation idea: duplicate the 5 bits, possibly inverted.

**Comment by GregAC** [comment]
We haven't and we probably should. I'll add it to the D2S task list.

**Comment by GregAC** [comment]
No extra work is required here. The predecode cross check already gives us the check.

When we do an indirect RF access (any of BN.SID, BN.MOVR, BN.LID) the controller calculates one-hot read and write enables for the bignum registers after the base register file read. These get flopped in the instruction fetch stage for use in RF read/writes the following cycle. In addition the register indexes are flopped within the controller. In the cycle the bignum read occurs the onehot decoded versions are checked against the flopped indexes in the controller.

So the `BN.LID` destination register already has duplication (in two different forms, index and one-hot) with a cross check between them.
