### ISSUE TITLE
[otbn] Evaluate performing blanking calculation on negative edge

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#7889]
One solution to https://github.com/lowRISC/opentitan/issues/7883 is to use negative edge clocking. Pre-decode would occur in the first half of a cycle and the rest of execution in the second half of the cycle.

Run some synthesis trials to determine the feasibility of this. E.g. try synthesizing the current OTBN core to run at 250 MHz 

> estimate 2
> remaining 2021-10-04 0

**Comment by GregAC** [comment]
Thanks to @msfschaffner for running the synthesis. As expected we cannot come close to meeting timing at 250 MHz however I do note that for the worst path, which goes through the base register file, the enable signal for the read it generated roughly half way through. Looking at the top few paths they all go through the read enable for the base RF, so presumably the address for the base RF is appearing earlier (otherwise it would also be in the top few paths).

There is significant logic to generate the enable/address: imem read delay -> scrambling -> decode -> some controller stuff -> enable/address, perhaps it is possible to clock the result here on the negative edge with the actual calculation side (i.e. from address to register file onwards through the ALU/MAC to register write) occurring in the second half of the clock cycle.

I also note the longest paths all involve indirect register access, as you might expect, read from base to determine bignum address, then read from bignum. To implement blanking here I think we'd end up adding in a stall cycle anyway (as you'd need to flop the output of the base register file to use as a read address for bignum the following cycle) so those paths wouldn't exist any more giving us some more timing slack to play with.

Some further experiments here may be warranted. An easy one would be to remove the indirect register address functionality and see what we get. A more involved one would be to do a mock-up of the clock decode signals on negative edge and run a synthesis trial on that. I'll put together something former as it's quick and easy RTL wise then @msfschaffner can rerun the 250 MHz trial on it when he has time to do so.

**Comment by tjaychen** [comment]
btw @GregAC , given the results you see here, do you still think this path is worth pursuing vs the prefetch idea you originally had? 
It sounds like you see some light at the end of the tunnel? or am I misunderstanding?

**Comment by imphil** [comment]
With the light potentially being a train :-)

**Comment by tjaychen** [comment]
very possible :)

**Comment by GregAC** [comment]
Follow up work to be covered by #8500
