### ISSUE TITLE
Should `boot_policy_manifest_*_get()` return `volatile` pointers?

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#7893]
See this [comment](https://github.com/lowRISC/opentitan/pull/7878#discussion_r693815097) for context.

**Comment by moidx** [comment]
Closing this issue as obsolete as the bootstrap mechanism does not operate on the `boot_policy_manifest_*_get()` return values.

**Comment by alphan** [comment]
@moidx this issue is not really related to bootstrap and boot_policy still uses the return values of these functions.

I thought about this a little bit and also discussed this offline with @luismarques. My thoughts were:
> These pointers point to a flash location but they are not modified within the ROM. So unless the compiler can optimize away the first read from a pointer I think we should be good but I don't think it can really do that without seeing a prior write to the same location.

@luismarques also agreed.

I think we can keep this closed. Please feel free to reopen if you don't agree.
