### ISSUE TITLE
[mask_rom] Decide retention SRAM scrambling strategy.

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#7895]
Currently we aren't scrambling the retention SRAM because it will result in the retention SRAM being effectively wiped when the device experiences a non-low power reset. More detailed discussion is [here](https://github.com/lowRISC/opentitan/pull/7220#issuecomment-873117531).

We should decide whether we want to scramble the retention SRAM or not, and if not what, if any, mitigations are required.

@moidx (in [comment](https://github.com/lowRISC/opentitan/pull/7885/commits/bd0b5f7ec2f7654b07c1c4e6332618bae92714de#r694327657)):
If we leave retention ram unscrambled, we should add a warning to the c struct, and also add a checksum or digest to protect the integrity as an attacker may be able to manipulate the data to abuse boot services. Or perhaps the multibit encoding of boot_services is sufficient.

**Comment by mundaym** [comment]
(cc @tjaychen @cfrantz who originally discussed this)

**Comment by mundaym** [comment]
If we do decide to scramble retention SRAM then we can use the code from this [PR](https://github.com/lowRISC/opentitan/pull/7182).

**Comment by alphan** [comment]
@tjaychen closing this since IIRC we agreed that using the ephemeral key is what we want since otherwise the scrambling key would be gone after reset.

**Comment by tjaychen** [comment]
yeah that's right. But just to clarify, we're going to be using the "fixed" scrambling key for FI protection since that will be preserved across reset domains.

**Comment by msfschaffner** [comment]
indeed, I was also confused by the word `ephemeral`. the default key is a fixed (but secret) netlist constant.

**Comment by alphan** [comment]
Yeah, my bad, the "fixed" scrambling key, (edited my comment above) apologies for the confusion.
