### ISSUE TITLE
[keymgr] last strb is 0 when LC turns off keymgr

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#7902]
@tjaychen 
usually `strb` is never 0 when the valid is high. We also have assertion to check that and I think KMAC TB probably never test the case that `strb` is valid with value 0.

When LC turns off keymgr in the middle of an operation, we will see the last `strb` is set to 0.
![Screen Shot 2021-08-24 at 10 54 44 AM](https://user-images.githubusercontent.com/49293026/130666192-58914373-3087-4323-84fd-a7efcdff6828.png)

Since this interacts with KMAC, we probably can't test this corner scenario in chip-level. If we do want to have this case in the keymgr side, we may need to test it at KMAC block-level TB as well.

cc @eunchan @udinator

**Comment by tjaychen** [comment]
@weicaiyang can you remind me if there's anything wrong with this issue? since we closed it some time ago. was it mainly to ensure there was an assignee?

**Comment by weicaiyang** [comment]
> @weicaiyang can you remind me if there's anything wrong with this issue? since we closed it some time ago. was it mainly to ensure there was an assignee?

yeah, nothing wrong here, just to add an assignee.
