### ISSUE TITLE
[csrng] hw_exc_sts register not behaving as RW

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#7905]
The `hw_exc_sts` CSR is not behaving as a RW register. This is evident from the failing CSR tests in the nightly regressions:
https://reports.opentitan.org/hw/ip/csrng/dv/2021.08.19_11.18.49/results.html

Should it be marked `rw0c` instead (based on its description)?

**Comment by senelson7** [comment]
Yes, Mark has already made this change as part of PR #7482 (I think that's the one) but it hasn't been merged yet.

**Comment by sriyerg** [comment]
Great, thanks!

**Comment by sriyerg** [comment]
@mwbranstad, @senelson7 
I am not sure if there is more work to be done on PR #7482. But unfortunately, this issue is causing a lot of CI flakiness (csrng or the chip level tests in CI is failing). It will be great to just have the fix for this issue merged in quickly. Please advise.
