### ISSUE TITLE
[otbn,dv] Cover known and unknown CSRs with randomly generated instruction streams

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#7949]
We've already got coverage points for these (e.g. `csr_cross` in `insn_csrrw_cg`). When doing this, add an explicit coverage point to match the UNIMP instruction that we added with PR #7923.

**Comment by ctopal** [comment]
I believe this was mostly handled by https://github.com/lowRISC/opentitan/commit/b51084435ad3a7de7a7719899172ec597d130698 (thanks @prajwalaputtappa!) and for the last little tweaks I opened up https://github.com/lowRISC/opentitan/pull/13451. @GregAC : If you have any suggestions about some more things to do for this one, please let me know.

**Comment by ctopal** [comment]
Closing this as it's discussed as done in OTBN planning meeting
