### ISSUE TITLE
[top] Better documentation for USB connectivity

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7951]
- clarify `chip_earlgrey_asic` use case on RX / TX differential signaling.
- clarify `vbus detect` functionality and how it should be managed.

**Comment by a-will** [comment]
> In the meantime, @mdhayter did test the differential mode with a TUSB1106 PHY connected to the NexysVideo in #4330. The ChipWhisperer CW310, i.e., the new main FPGA development board for OpenTitan, has the same PHY onboard. The single-ended signals are still there but currently routed to the header USERIO-B. So, the intention is to use differential mode via TUSB1106.

On the subject of the CW310, https://github.com/lowRISC/opentitan/pull/8476 hooks it up to make things functional. I neglected to handle low-power mode there, though.

**Comment by a-will** [comment]
For `vbus_detect`, this is a prerequisite for enabling the pull-up resistor. From the USB 2.0 spec, the pull-up resistor must not supply current on the data line if VBUS is removed.

We're missing a hardware association between the pull-up enable and the VBUS sense in usbdev right now. Was the intention to have firmware implement this aspect of the spec?

**Comment by stefanlippuner** [comment]
> We're missing a hardware association between the pull-up enable and the VBUS sense in usbdev right now. Was the intention to have firmware implement this aspect of the spec?

I think we did not worry about that, because in our case the 3.3V rail is derived from VBUS (via an LDO), so this requirement is fulfilled anyway. But I guess it would make sense to also have a digital solution for other power supply configurations.

**Comment by vogelpi** [comment]
I think the TUSB1106 does the same (integrated regulator for 5V to 3.3V conversion based on VBUS). But I agree, changing the pullup behavior based on `vbus_detect` inside `usbdev` would make sense. @a-will , would you be willing to implement this?

**Comment by a-will** [comment]
Aye, I can add it to my to-do list. :)

**Comment by a-will** [comment]
I think with the latest RTL and doc updates, this can be closed. Is there anything missing still?

**Comment by tjaychen** [comment]
it looks good to me.
