### ISSUE TITLE
[doc] dvsim.py lacks centralized documentation

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#7954]
Would be great if there was some centralized documentation for dvsim.py and all of its wonderful features for continuity and ease of ramping up new DV contributors.

cc/@domrizz0

**Comment by moidx** [comment]
Marking this as higher priority as we need to improve the DV velocity. There are DV engineers ramping up across organizations that would benefit from instructions on how to reproduce test cases and/or run tests locally. 

Many people are currently relying on CI to ensure things are running correctly with dvsim.

**Comment by tjaychen** [comment]
the work has begun in #15601, but should we table the rest of this to post M2?
@moidx / @sriyerg let me know what you think.

**Comment by moidx** [comment]
Agreed

**Comment by timothytrippel** [comment]
Documentation was added recently and is here: https://opentitan.org/book/util/dvsim/doc/design_doc.html
