### ISSUE TITLE
[ast] Make ast a comportable module or at least a comportable front-end

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7978]
The fact that ast is a "comportable-like" module that exists outside of the `top_earlgrey` boundary causes a lot of issues that frankly could be otherwise avoided.

In the future, there should not be any comportable-like module that exists outside of the boundary of top_earlgrey. 
If there is a proprietary portion that needs to be hidden, there are two solutions

1. Follow the example of otp / flash and wrap the proprietary portion under the comportable open source.
2. Maintain the comportable open source front end inside earlgrey, and forward a struct connecting that module to some entity sitting outside top_earlgrey.  The outside world SHOULD NOT have any concept of comportable buses / clocks / alerts etc.

It may be too late to do this now, so we'll have to live with the mess we made and fix it some other day.

**Comment by tjaychen** [comment]
@arnonsha 
@zi-v 
@Jacob-Levy 
@dsandrs

**Comment by msfschaffner** [comment]
Totally agree. Ideally, AST would be a comportable IP (or the AST open-source wrapper for that matter).

**Comment by sriyerg** [comment]
My vote is for standardizing option 1.

**Comment by zi-v** [comment]
We discussed this in one of the latest sync meetings and concluded to keep AST as is. 
Note that the AST register space is opaque to software, During boot, the ROM code copies a configuration blob from OTP to AST. The ROM code is not aware of the blob content, the chip creator sets the right values into the relevant OTP space during production flow. After the AST configuration is done, AST registers will be blocked.

**Comment by glaserf** [comment]
Several files inside ``hw/top_earlgrey/ip/ast/rtl`` claim to be auto-generated (PLEASE DO NOT HAND-EDIT THIS FILE. IT HAS BEEN AUTO-GENERATED in the header).

However, I cannot find any generator for these files or ``ast`` in general. Did I miss something or does the header not apply?

**Comment by msfschaffner** [comment]
Afaik, there is no opensource generator available for this. 
But Nuvoton might have generated that internally before upstreaming.
@zi-v @meisnere can these comments be removed if there is no opensource generator?

**Comment by meisnere** [comment]
The generator is closed source. I prefer to leave the comment there, so no one will try to change it manually by mistake.

**Comment by glaserf** [comment]
Thanks for clearing this up. Maybe it would make sense to include the fact that the generator is not open-sourced in said comments?
During the creation of a customized toplevel, this left me a bit puzzled as I could not find such a generator in the repository. In the end I copied the respective files from ``top_earlgrey``, along with some other ``.core`` and HDL files for various top-level modules (``rstmgr``, ``clkmgr``, ``pwrmgr``, ``sensor_ctrl``) that ``topgen.py`` does not generate automatically.

**Comment by matutem** [comment]
Just to be clear, the only issue pending in this is to extend the comment to state the generator for this file is not open-source to avoid open-source developers trying in vain to find the generator.

**Comment by andreaskurth** [comment]
> Just to be clear, the only issue pending in this is to extend the comment to state the generator for this file is not open-source to avoid open-source developers trying in vain to find the generator.

Closing as completed in #23356.
