### ISSUE TITLE
[keymgr] Make lc_en=0 behavior consistent in RESET state

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7981]
Right now, when keymgr makes its first advance operation (from reset to init), an operation error is not generated if for whatever life cycle enable is dropped right in the middle.

All other transitions report an error when this happens, so it is better to also make reset more consistent.

**Comment by tjaychen** [comment]
@weicaiyang

**Comment by weicaiyang** [comment]
@tjaychen 

seems like this issue still exists.
![Screen Shot 2021-09-01 at 9 25 14 PM](https://user-images.githubusercontent.com/49293026/131781591-6f655cf1-55d9-40a4-ba1e-cee498f8b514.png)

**Comment by tjaychen** [comment]
also can you clarify what "this issue" is in this case? is the invalid operation not generated?

**Comment by tjaychen** [comment]
reproduce with ```keymgr_lc_disable  -s 1901011244```

**Comment by tjaychen** [comment]
ooops! you're right.  I covered the case where a fault occurs in the beginning, but i completely forgot about lc disable. Let me have a look at what the right fix is.

**Comment by tjaychen** [comment]
turns out the issue was something else. I made a fix and ran locally with 100 different seeds, it seems to be behaving now.

**Comment by weicaiyang** [comment]
Thanks @tjaychen 

sorry, there is an unrelated small issue.
Looks like we latch the otp_key as key_state while advancing to StInit, but we don't check if the values are all 0s/1s. In this case, one share are all 1s.

When advancing to Creator state, these value are used as KMAC key which we check if they're all 1s/0s. Then it fails due to that all 1s share. But I think we should fail the first advance. Maybe OTP is not ready. Then we can configure the OTP and redo advance command again. 
Now since we latch the all 1s value from OTP and store in key_state, we will get stuck at StInit till a reset.
![Screen Shot 2021-09-01 at 10 57 07 PM](https://user-images.githubusercontent.com/49293026/131789823-0b8e65b2-4352-42b1-939b-f0576b9396cb.png)

**Comment by tjaychen** [comment]
hmm... that seems like a pretty minor thing at this point though.
it would be nice to check, but to me it's fine to have it checked as input
into the next state.

we cannot reconfigure otp and advance again anyways. otp only senses once
per power cycle, so we would HAVE to issue some kind of reboot anyways.

**Comment by weicaiyang** [comment]
> hmm... that seems like a pretty minor thing at this point though. it would be nice to check, but to me it's fine to have it checked as input into the next state. we cannot reconfigure otp and advance again anyways. otp only senses once per power cycle, so we would HAVE to issue some kind of reboot anyways.

OK. I think it's fine. Let me change scb to align with design

**Comment by tjaychen** [comment]
let me know if it gets too cumbersome, we can change the design side also.

**Comment by tjaychen** [comment]
actually weicai, you just reminded.
you remember in the otp struct, there is a valid signal?

That valid signal is actually tied to whether this otp value can be further
programmed on the otp side.
So we do not actually update the value until that valid is 1.

This also means as long as the valid is 1, the otp input CANNOT be all 0's
or all 1's in reality.  This would mean we locked the value prematurely and
cannot update it again..effectively this will give us a part where otp can
never be used.
So i guess what i'm saying is ....the key value check that we perform is
actually somewhat pointless.  Maybe it's best I remove it altogether, or
you constrain your test bench to not have such a condition.

**Comment by weicaiyang** [comment]
yeah, I had a TODO to verify if valid isn't high, what should we do?
I'm fine with either keeping the check or removing it.

**Comment by tjaychen** [comment]
yeah if valid isn't high, the key isn't even loaded (stays default value).
so on the next run it just bombs out because there's no key.

**Comment by weicaiyang** [comment]
> yeah if valid isn't high, the key isn't even loaded (stays default value). so on the next run it just bombs out because there's no key.

I see. Will try that out. Thanks
