### ISSUE TITLE
[rtl/ast] Review ast POK outputs

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#7986]
If either main, io, or aon power fail the full chip should probably reset, but only aon failure causes a full reset. The AST logic seems to treat these pok's independently. A main or io power failure when they are turned off may be okay.

The main_pok ast output is only used by pwrmgr to deal with power transitions, perhaps it can qualified by main_pd_n and and'ed into rstmgr's por_n_i to drive full reset.

**Comment by tjaychen** [comment]
@zi-v 
@arnonsha 

let us know what you think. My assumption is that this is mostly handled through the alert event mechanism. Ie, if there is a glitch on the power lines, that'll come through as an alert to the handler. 

However, it also does not hurt to have a consistency check on pwrmgr side, ie, if the main power turns off unexpectedly when not dictated by pwrmgr, we take some kind of local action immediately.  Would you want to consider this? 

@matutem the io power doesn't completely apply here. ioa/iob are legal to be turned off by an external source as part of the system. If ioc turns off, it will also trigger por from ast.

**Comment by zi-v** [comment]
Maybe it is trivial, but if you mess with the por_ni AST input, you must make sure you don't cause a deadlock because AST will keep all output POKs cleared until por_ni is released.
Most error conditions are indeed handled through the alerts. Note that power glitch may also trigger the main power detector which will essentially reset the chip.

**Comment by tjaychen** [comment]
@zi-v, when you say the main power detector, are you referring to the rail behind main_pok? Or do you mean VCC overall?

**Comment by zi-v** [comment]
Both. Power loss on either will cause main_pok to negate

**Comment by tjaychen** [comment]
as pointed out by @zi-v , we should consider using main_pok in a similar way as we do aon_pok.
Ie, instead of just a one time status check, it should double as the root reset for non-always-on domains.

This is something I will look into and should also address this issue.
