### ISSUE TITLE
[fpga] Support memory scrambling in boot ROM splicing script

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#7988]
Our boot ROM splicing script under `util/fpga/splice_nexysvideo.sh` doesn't work anymore due to modified layout resulting from scrambling the boot ROM. This script has proven pretty helpful in the past to debug issues around the boot ROM and FPGA builds and I was wondering if we could reactivate that on the ChipWhisperer CW310 FPGA board.

Looking at the script, it looks like the main challenge is to produce the `.brammem` image from the scrambled ROM. Previously, we were feeding the `.bin` to `srec_cat` which did some magic. But if I understand it correctly, the `.bin` is not yet scrambled and doesn't contain the ECC bits. Can we do the same starting from the scrambled `scr.39.vmem` @rswarbrick , @imphil?

**Comment by imphil** [comment]
See also https://github.com/lowRISC/opentitan/pull/1618

If you need another output format, you can modify the meson rules at https://github.com/lowRISC/opentitan/blob/master/sw/device/boot_rom/meson.build and https://github.com/lowRISC/opentitan/blob/3b38e95591eeb7d979c79d655dfeb40049537758/sw/device/meson.build

**Comment by vogelpi** [comment]
Thanks for your input @imphil . I've rebased PR #1618 and top of that (re-)enabled boot ROM splicing for scrambled and unscrambled boot ROMs. I've directly pushed back into #1618 .

**Comment by vogelpi** [comment]
#1618 has been merged, we now have support from splicing scrambled boot ROMs :-)
