### ISSUE TITLE
[sw] Move build system to Meson 

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#8]
Replace software Makefiles with Meson build files. The work is broken down as follows:

* [ ] Add support for Meson. Starting with:
   * sw/boot_rom
   * sw/lib
   * sw/host
   * sw/tests
* [ ] Update documentation with new build instructions, e.g.:
  ```console
  $ cd ${REPO_TOP} && ./meson_init.sh
  # Verilator
  $ cd ${REPO_TOP}/build-sim && ninja
  # FPGA
  $ cd ${REPO_TOP}/build-fpga && ninja
  ```
* [ ] Update documentation with new dependencies:
  ```console
  $ pip3 install --user meson
  $ apt-get install ninja-build
  ```
* [ ] Update Docker container to support new dependencies
* [ ] Update otx to support new dependencies
* [ ] Update other build targets, e.g. `sw/benchmark`
* [ ] Update CI to trigger `build-sim` and `build-fpga` builds

**Comment by mcy** [comment]
See #1032.
