### ISSUE TITLE
[sw/testing] current SW patching for english-breakfast top level does not scale

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#8007]
Currently, we [patch SW srcs](https://github.com/lowRISC/opentitan/blob/master/hw/top_englishbreakfast/util/sw_sources.patch) (both runtime  and smoke tests) to enable use with English Breakfast toplevel. Making matters worse the English Breakfast toplevel build is run in CI.

This doesn't scale, as we have to keep regenerating the patch if we touch any of the code it patches. What we should do is parameterize this code to run on any top level. I believe this will happen as a part of my work overhauling our on-device test infra (which is a WIP). But want to track log this issue for now.

**Comment by tjaychen** [comment]
@timothytrippel do you have any thoughts as to how likely it will be software to run across different tops?
I personally feel like if the chip architecture is "mostly" similar, it will probably be okay.

The bigger issue is when things that ROM expects to be there suddenly starts disappearing. 
The real ROM obviously needs to be hardened.. but maybe for the fake rom we could have it check for configurations? 

Just an idea, i'm sure there will be others.

**Comment by timothytrippel** [comment]
There are both short-term and long-term motivations for this issue. Short-term the SW patching mechanism used for building the English Breakfast top needs to be fixed. This patching mechanism is used to make toplevel-specific patches to portions of the: 1) fake (test) boot rom, 2) pinmux.c, 3) some SCA sw, and 4) the AES smoke tests. To avoid this for the time being, a quick fix could involve a few macro switches. This obviously doesn't scale past a few top-levels but its better that what we currently have.

Long term, regarding tests, I was thinking we should parameterize everything we can to run on different tops, i.e. make them as generic as possible, and ones that are top specific just subfolder them and create separate tests per top (see #7976). Regarding (real) ROM, I would expect that to be top-specific given constraints (though this is probably better answered by @cfrantz or @moidx), but the fake ROM currently used for testing could most certainly check for configs, or have parameters passed by the build system.

**Comment by tjaychen** [comment]
That sounds good to me! I know @imphil at one point explored the idea of dynamically generating all the design tops, does it make sense to have a larger discussion on how everything converges?

**Comment by timothytrippel** [comment]
That seems like a good idea, best we settle on this.

**Comment by moidx** [comment]
In the software WG we have discussed this topic in the past and @mcy created a link-time dependency injection guidance doc. We should revisit this topic and work on publishing implementation guidelines. 

CC: @mundaym, @cfrantz, @mcy

**Comment by tjaychen** [comment]
> That seems like a good idea, best we settle on this.

@timothytrippel this is not directly related to this issue, but COULD impact you. 
I think part of the discussion we need to have is... "what exactly is a top"? This is a subject that we have not found wide agreement on in the project.  Is it a chip, is it any variation from FPGA, is it a variant of a type of chip, or is it a configuration of a particular architecture?  What I worry is that if we have two VERY distinct architectures, it will be difficult to map the software on top such that it is always generic and happy. So to me there is still a clear breaking point somewhere. 

I think once we settle on that decision, a lot of the downstream collateral such as design, dv, documentation, software and validation framework will all be affected.

**Comment by mcy** [comment]
Making this a Bazel migration priority. I suspect the way we'll deal with this is with teporary ifdefs, and long term with either a link shim or support for arbitrary tops as separate Bazel platforms.
