### ISSUE TITLE
[rtl/clkmgr] Keep clocks on for busy trans units

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#8014]
The clock for transactional units must remain active while they are busy. Apparently the idle_i signal is not part of the logic generating clk_status. Foe example, the screenshot below shows the the aes clk drops even though it is not idle.

![Screenshot 2021-08-31 18 54 12](https://user-images.githubusercontent.com/80294896/131586154-f198d48b-5c5d-4cf7-975f-3a81e88e3b03.png)

**Comment by tjaychen** [comment]
which clk_status are you referring to? i'm not sure which module i'm looking at.

**Comment by tjaychen** [comment]
o this is the clkmgr status that's fed back to pwrmgr? If yes then that is intended. 
The clk status is meant to reflect the status of the root gating, not the leaf gating that is part of the transactional modules.

**Comment by matutem** [comment]
Hmm, in a way you are right, but it may be a messy mistake: the units will be reset and I don't know what kind of side-effects this will cause due to unfinished transactions. But, software beware.

**Comment by matutem** [comment]
I mean messy when software makes a mistake, not that it is a bad call for the hardware to work this way. I am closing this PR and will fix a clkmgr test that is tripping because of this.

**Comment by tjaychen** [comment]
let's reopen this issue and i'll put a "users" beware label in the spec.
Part of the reason I don't want to reach too deeply into the idle conversation is because i've been a part of systems where this was done, and the end result was the device could never get to sleep and it becomes a huge pain to debug why. 

I do believe you are right that this could get messy if software makes a mistake, so at least we should make that tradeoff clear as to why this is done.

**Comment by matutem** [comment]
That argument works both ways, since with the current approach it means this system would occasionally trip the transactional uints into truncating transactions.

I think if prior to transition to low power software disables all trans units with `clk_hints` CSR, then wait for `clk_hints_status` to show they are off, and then transition we would be assured `idle` would not be an issue since it should be all ones. This could be a programmer's note. With that approach we could handle this issue either way.
