### ISSUE TITLE
[clkmgr change proposal] Update external clock selection logic

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8027]
For manufacturing flexibility, we need to add more flexibility on how to select external clocks. 
Right now the step down and selection is driven largely automatically by hardware, but we would like to be able to control step down through software as well. 

See this [link](https://docs.google.com/presentation/d/1N-PBsD5dkEnHZCG5p0DEsTy6UcGgfqGZXzQSixDBWmM/edit?usp=sharing) (limited visibility and not open to public) for more details.

**Comment by tjaychen** [comment]
@dsandrs

**Comment by imphil** [comment]
Backed out in #8305 for a DV regression failure. The DV code needs updating to match the newer field names.

**Comment by imphil** [comment]
In-progress PR to update the naming available at https://github.com/lowRISC/opentitan/pull/8303.

@cindychip in the future, if you see failing CI, please do the backout first before attempting a fix. This buys everyone time to get a proper fix developed, reviewed, and merged.

**Comment by cindychip** [comment]
Thanks, sounds good, will do the backout first next time .

Cindy
