### ISSUE TITLE
[all] Not all modules use the prim_intr_hw module

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8035]
- [x] spi_device
- [x] flash_ctrl (#8210)
- [ ] others?

**Comment by eunchan** [comment]
Thanks!. I will revise `SPI_DEVICE` to use prim_intr_hw

**Comment by tjaychen** [comment]
i did a quick survey of all the other modules and they seem to all be using prim_intr_hw.
Closing.
