### ISSUE TITLE
[alert_handler/pwrmgr] Ensure escalation receivers are on same clock/reset domains as the alert_handler

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#8037]
Since the escalation sender/receiver pairs employ a synchronous protocol, we must ensure that they are connected to the same clocks and resets in order to not run into spurious escalation issues. I.e., if the clocks / resets are not the same, a delay difference in clock gating or reset assertion may lead to spurious escalation (either due to the escalation ping monitor or due to locked up protocol FSMs).

Need to double check all receivers:
- [ ] 1. NMI in `rv_core_ibex` -> needs to be fixed (TODO)
- [x] 2./3. in `lc_ctrl` -> ok since `lc_ctrl` resides in the same clock/reset domains as `alert_handler`
- [ ] 4. in `pwrmgr` -> needs to be fixed (TODO)

**Comment by tjaychen** [comment]
my current thinking to this problem is to allow clocks to be individually
assigned groups instead of relying on the module group as we do now.
This is similar to resets allowing different domains which gives more
flexibility.

I will experiment and get back to this.

**Comment by msfschaffner** [comment]
ok that would be great.

just noticed that `rv_core_ibex` has the same issue, since that module is in the `infra` clock group, as opposed to `lc_ctrl`, which is in `secure`.
