### ISSUE TITLE
[verilator] ELF file loader does not ignore `NOBITS` sections

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#8075]
The ELF file loader is relatively simple: it takes all the segments in an ELF file with type `PT_LOAD` and pads them from file size to memory size with zeros. It then combines them into a contiguous vector whose start address is the lowest physical address (LMA) of any section with a memory size greater than 0. It then loads this vector into the specified memory (e.g. flash) starting at the lowest address mentioned earlier.

Unfortunately this means that the ELF file loader serializes `NOBITS` sections and tries to load them into the target memory. This typically works for `.bss` because it is merged with `.data` into a single segment. Notably however it also means that **`.bss` is included in the output memory image despite having the `NOBITS` attribute**. `NOBITS` sections that are not combined with other sections into a single segment will typically have their physical address (LMA) in RAM which triggers an assertion in the loader because the address is outside the target memory.

I think that we need to do two things to fix this:

1) Discard segments with a physical address (LMA) outside of the target memory.
2) Truncate segments to file size (i.e. do not pad with zeros to memory size) if their physical address (LMA) does not match their virtual address (VMA).

An example of this is below. The `.critical_data` section is `NOBITS` but is still copied into a memory image triggering an out of bounds assertion:

```
Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .flash_header     PROGBITS        80000000 001000 000004 00   A  0   0  4
  [ 2] .crt              PROGBITS        80000004 001004 0000e0 00  AX  0   0  4
  [ 3] .vectors          PROGBITS        80000100 001100 000080 00  AX  0   0 256
  [ 4] .init_array       INIT_ARRAY      80000180 005338 000000 04  WA  0   0  4
  [ 5] .text             PROGBITS        80000180 001180 001f02 00  AX  0   0  4
  [ 6] .rodata           PROGBITS        80002088 003088 0013b2 00   A  0   0  8
  [ 7] .critical_static  NOBITS          10000000 001000 000330 00  WA  0   0  4
  [ 8] .data             PROGBITS        10000330 005330 000008 00  WA  0   0  4
  [ 9] .bss              NOBITS          10000338 005338 000014 00  WA  0   0  4
  [10] .logs.fields      PROGBITS        00010000 005338 0003ac 00      0   0  4
  [11] .riscv.attributes RISCV_ATTRIBUTE 00000000 0056e4 000026 00      0   0  1
  [12] .debug_info       PROGBITS        00000000 00570a 00e6f8 00      0   0  1
  [13] .debug_abbrev     PROGBITS        00000000 013e02 002486 00      0   0  1
  [14] .debug_aranges    PROGBITS        00000000 016288 000098 00      0   0  1
  [15] .debug_line       PROGBITS        00000000 016320 008890 00      0   0  1
  [16] .debug_loc        PROGBITS        00000000 01ebb0 009b8b 00      0   0  1
  [17] .debug_ranges     PROGBITS        00000000 02873b 000b08 00      0   0  1
  [18] .debug_str        PROGBITS        00000000 029243 004b9b 01  MS  0   0  1
  [19] .debug_frame      PROGBITS        00000000 02dde0 000eb0 00      0   0  4
  [20] .symtab           SYMTAB          00000000 02ec90 015ad0 10     21 5457  4
  [21] .strtab           STRTAB          00000000 044760 000f2f 00      0   0  1
  [22] .shstrtab         STRTAB          00000000 04568f 0000f2 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  p (processor specific)

There are no section groups in this file.

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x001000 0x10000000 0x10000000 0x00000 0x00330 RW  0x1000
  LOAD           0x001000 0x80000000 0x80000000 0x0343a 0x0343a R E 0x1000
  LOAD           0x005330 0x10000330 0x8000343c 0x00008 0x0001c RW  0x1000
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0x10

 Section to Segment mapping:
  Segment Sections...
   00     .critical_static 
   01     .flash_header .crt .vectors .text .rodata 
   02     .data .bss 
   03     
```

**Comment by mundaym** [comment]
The existence of memory translation makes this more 'fun' since it means there isn't actually a mapping from the claimed physical address to the real physical address.

**Comment by mundaym** [comment]
It might actually be correct to ignore the padding (i.e. keep segments at file size (FileSz) rather than padding out to memory size (MemSz)). I'm going to try that and see how far I can get.

**Comment by rswarbrick** [comment]
I think it's worth getting our head around which targets have a separate loader and which don't. For something where you're loading directly into data memory (like OTBN does), you absolutely *want* to expand things like BSS sections. There's no other "crt0" to do it for you! For Ibex, maybe that's not true.

**Comment by mundaym** [comment]
In the OTBN linker script symbols in the `.bss` section are placed directly into the `.data` section. There are no other `NOBITS` sections and so MemSz equals FileSz in all of the OTBN ELF files I looked at. Assuming no further changes are made to the OTBN linker script OTBN programs will be unaffected by a switch to FileSz.
