### ISSUE TITLE
[otbn,dv] We struggle to hit "GPR type cross coverage"

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#8077]
When an instruction has a GPR operand, we expect to see it equal to `x0` (the zeros register), `x1` (the call stack) and `x2..x31` (anything else). When we have several GPR operands, we cross this to give `3 ** num_operands` points.

We don't take this into account when we're picking operand values, so we end up with a very skewed distribution (mostly hitting the `x2..x31` bin). That's ok (and probably makes sense), but we need to "unskew" it a bit in order to see things like `add x0, x1, x1` and similar.

To do so, we might be able just to tweak probabilities of the various registers (increasing `x0` and `x1`). If that doesn't work, we'll have to pick the registers together instead of separately.

Covergroups that see this problem:
- [ ] `enc_is_cg`
- [ ] `enc_s_cg`
- [ ] `enc_r_cg` (really bad because of the 3-way cross)
- [ ] `enc_bnxid_cg`
- [ ] `enc_i_cg`

**Comment by rswarbrick** [comment]
The milestone was wrong here: this is about hitting a specific coverage point (from when I went through a coverage report trying to work out what we were missing). Moving to V3 and removing from the M2 project.

**Comment by GregAC** [comment]
Coverage here is now looking healthy so closing as complete
