### ISSUE TITLE
[otbn,dv] We don't seem to be triggering at_loop_end_cp for some jumps/branches

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#8085]
This persists even with 500 seeds, so needs a bit more investigation. We *should* be seeing it for each of `beq`, `bne`, `jal`, `jalr`, `loop` and `loopi`.

Marking as a bug because I thought the `BadAtEnd` generator would be handling it.

**Comment by GregAC** [comment]
This is now getting hit so closing as completed.
