### ISSUE TITLE
[otbn,dv] Most "bad branches" are taken

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#8087]
In `insn_bxx_cg`, the `eq_oob_cross` and `eq_neg_cross` crosses track whether a branch was taken and whether the destination was above the top of memory or negative, respectively.

We generate branches hitting these crosses with `BadBranch`, but seem to very rarely pick the direction that means the branch wasn't taken, which means ew miss some of the bins.

**Comment by rswarbrick** [comment]
The milestone was wrong here: this is about hitting a specific coverage point (from when I went through a coverage report trying to work out what we were missing). Moving to V3 and removing from the M2 project.

**Comment by GregAC** [comment]
This coverage is getting hit now so closing as done
