### ISSUE TITLE
[keymgr] keymgr doesn't enter Invalid state after intg error

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#8100]
@tjaychen 

There is a minor issue. keymgr doesn't enter Invalid state after intg error, if it's in StReset
secrets are wiped correctly, but working_state is still at StReset
![Screen Shot 2021-09-07 at 3 16 31 PM](https://user-images.githubusercontent.com/49293026/132418022-83e7bfe2-f685-4d7b-9fda-37f39b797e37.png)

It's because we don't check `inv_state` in a few states (StCtrlReset, StCtrlEntropyReseed and StCtrlRandom), so it's not changed to StCtrlWipe and working_state remains at StReset

```
     unique case (state_q)
      // Only advance can be called from reset state
      StCtrlReset: begin
        prng_en = 1'b0;

        if (advance_sel) begin
          state_d = StCtrlEntropyReseed;
        end else if (op_start_i) begin
          invalid_op = 1'b1;
        end
      end

      // reseed entropy
      StCtrlEntropyReseed: begin
        prng_reseed_req_o = 1'b1;

        if (prng_reseed_ack_i) begin
          state_d = StCtrlRandom;
        end
      end

      // This state does not accept any command.
      StCtrlRandom: begin
      ...

      // load the root key.
      StCtrlRootKey: begin
        init_o = 1'b1;
        state_d = (!en_i || inv_state) ? StCtrlWipe : StCtrlInit;
      end
```

**Comment by tjaychen** [comment]
yeah this is also fixed by #8042.
There are some minor issues with this PR right now, i'm looking at how to
fix it.

**Comment by weicaiyang** [comment]
> yeah this is also fixed by #8042. There are some minor issues with this PR right now, i'm looking at how to fix it.

but the change is to fix for init state, while that one is at StReset. I feel we may need tune a bit more.
```
      StCtrlRootKey: begin
        init_o = en_i & ~inv_state;
        state_d = !init_o ? StCtrlWipe : StCtrlInit;
      end
```

**Comment by tjaychen** [comment]
i'm not sure if we should apply this to reset honestly. Because in `reset` state, nothing has even started, ie there's no valid key. 
If a fault really happened prior to reset, it would cause the alert_handler to escalate, which in turn would NEVER allow the key manager to start.  

So to me all the interesting error handling happens after we've initialized out of reset state.  Does that make sense?

**Comment by tjaychen** [comment]
> i'm not sure if we should apply this to reset honestly. Because in `reset` state, nothing has even started, ie there's no valid key.
> If a fault really happened prior to reset, it would cause the alert_handler to escalate, which in turn would NEVER allow the key manager to start.
> 
> So to me all the interesting error handling happens after we've initialized out of reset state. Does that make sense?

**Comment by weicaiyang** [comment]
From the spec, looks like we only transition to StInvalid after an operation.
For this case, since we capture the error, it will enter StInvalid when advance is issued. I think the behavior makes sense. 
Let me close this issue. Thanks

> If the fault happens while there is no transaction, an alert is first sent to the alert handler. If before the alert handler escalates an operation is run, the key manager again transitions to Invalid state. If the alert handler escalates and disables the key manager, then the key manager will also transition to Invalid state if it is not already there.

**Comment by tjaychen** [comment]
ah yes it should. let me know if it doesn't.
The latest PR should make it so if we register an error during reset, by the time we actually advance it would error back out.

**Comment by weicaiyang** [comment]
> ah yes it should. let me know if it doesn't.
> The latest PR should make it so if we register an error during reset, by the time we actually advance it would error back out.

sounds great. Thanks
