### ISSUE TITLE
[fpga] Excessive Vivado Implementation Time

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#8128]
Since a couple of days we are observing strong variations in Vivado implementation time in CI. In some cases implementation runs through in a bit more than 1h, in other cases the time limit of 2h is reached (on local machines without a time limit run times of 5 hours can be sometimes observed).

The strong variation as well as the logs suggest that there is a place & route / congestion issue. Vivado spends a lot of time in the route phase. Xilinx has a useful answer record on the topic: https://www.xilinx.com/support/answers/66314.html

So far, we have tried the following things to investigate/solve this problem:
- Analyzing the time waiting for Vivado license checkout: this seems not to be a problem, the wait time is usually in the order of a couple of seconds
- Provide log output already during synthesis: #8046
- Enforce BRAM placement to let place & route start already from a known good placement: #8063
- Enforce clock gate placement: #8138 
- Disable gating of software controllable clocks on FPGA: #8122 
- Disable gating of software hintable clocks on FPGA
- Enforcing replication of high-fanout nets: https://github.com/vogelpi/opentitan/tree/fpga-highfanout-replication

I will keep updating this as I get more results.

**Comment by vogelpi** [comment]
FYI @tjaychen , @msfschaffner, @GregAC

**Comment by tjaychen** [comment]
@vogelpi should we close this for now and open another the next time we have an fpga fire?

**Comment by vogelpi** [comment]
Yes Tim, we can close this. For the record, we've tried out several things that didn't notably improve the situation. What worked in the end is to enforce the placement of the local clock gate (BUFHCE) for AES into a separate clock region (see PR #8138 by @tjaychen ). Without this placement constraint Vivado did place all BUFHCEs and all flops driven by these into one single clock region while the associated combinatorial logic needed distribution over multiple, surrounding logic tiles. This led to heavy routing congestion and excessive run times.

As the design grows further and once we e.g. enable KMAC masking on FPGA, we might need to do the same for other IPs as well.
