### ISSUE TITLE
[prim_esc] false alarm for sig_int_fail

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#8139]
Hi Michael,

I think with the newly support feature for prim_esc_receiver, there is a corner case below that triggered a false signal integrity error.

Seq:
1). Send `ping_req` from `prim_esc_sender`
2). After three clock cycles, send `esc_req` from `prim_esc_sender`
3). After one clock cycle, `prim_esc_sender` reported a `signal_integrity_error`.

I think the issue comes from the `prim_esc_receiver` side that it sends out two continuous pulse of `resp_p = 1 resp_n = 0`.
The FSM (from prim_esc_receiver) goes from `Idle` to `Check` state has error when `esc_level = 1`. I think during `Idle` state, if `resp_p` is high, we might need to stay one more clock cycle in Idle state to reset the `resp_p` before moving to `Check` state.

![image](https://user-images.githubusercontent.com/11466553/132773528-216253a4-7a5a-45b6-ad6e-f9c8cd1c3843.png)

I will push a PR with some changes in prim_esc_tb and we can reproduce it with:
```
dvsim.py prim_esc_sim_cfg.hjson -i prim_esc_test --seeds 573207815
```

Thanks,
Cindy

**Comment by msfschaffner** [comment]
I think I found a fix for this. @cindychip can you take a look at #8212?
