### ISSUE TITLE
[dv] Create a generic way for DV to load arbitrary vmem files

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#814]
This is especially helpful for debugging software images without needing to re-create an entire test path.  It can be something as simple as just providing a loading path and thus skip part of the sw build step.

**Comment by tjaychen** [comment]
let me know if you guys this is useful to have.
If not, we can just close this.

**Comment by sriyerg** [comment]
Yes, this is certainly useful and hopefully not too difficult to implement. I will try to prioritize on it next.

**Comment by sriyerg** [comment]
Addressed in #2210.
