### ISSUE TITLE
[rstmgr] Convert multireg use of regen to regwen_multi

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8154]
@matutem 
@cindychip 
@weicaiyang 
@sriyerg 

This should simplify DV and make things consistent with other modules.

**Comment by tjaychen** [comment]
I remember now why this was done this way.
It was a specific request by software to have the reset controls compacted into one register. 

We can either go back and make sure our reggen flow support this, or we can just have an exception test case for `rstmgr` for now.
Given the amount of tooling we'd need to add to both design and dv, it's probably better to stick with the latter for now.

**Comment by weicaiyang** [comment]
> I remember now why this was done this way.
> It was a specific request by software to have the reset controls compacted into one register.
> 
> We can either go back and make sure our reggen flow support this, or we can just have an exception test case for `rstmgr` for now.
> Given the amount of tooling we'd need to add to both design and dv, it's probably better to stick with the latter for now.

I think the latter approach is fine, given we have verified this regen already. @matutem WDYT?

**Comment by cindychip** [comment]
I see, I am fine with the second approach and maybe good to have some comments to document the special handling.
