### ISSUE TITLE
[alert_handler] Low power features

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#8174]
Due to the various clock and reset domains in our system, the alert handler ping mechanism needs to have additional logic to deal with alert senders that are either held in reset, or that are clock gated.
This is needed to ensure that no false alarms are produced when an alert channel does not respond due to the sender being either in reset or clock gated.
In addition, this mechanism needs to be able to properly initialize a given alert channel to a "good" working state whenever that channel comes back from reset / clock gated state.

This issue is intended to track these enhancements.
More info about the solutions will be linked in shortly, but the main idea is to route all relevant resets and clock gating information to the alert handler such that individual channels can be excluded from the ping sequence if they are in reset or clock gated.

**Comment by tjaychen** [comment]
hey michael,
just wondering if you've given any thought to the escalator type solution
where we put things on similar grouping of clocks (but not identical
clocks).
or are there too many drawbacks for that approach?

**Comment by msfschaffner** [comment]
Block-level implementation of the low-power features: #8296, #8418, #8419
Top-level integration: #8369
Doc updates: #8490
