### ISSUE TITLE
[Private CI] clkmgr hangs

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#8191]
clkmgr tests failed with `Segmentation fault` error, which I think it may be due to an infinite loop. Then I enabled `loopdetect` to rerun and now it has been stuck for over 1 hour.

Looks like we need some time to debug it. So temporarily remove clkmgr from smoke and nightly.

This is discussed at #8030

cc @tjaychen @matutem

**Comment by weicaiyang** [comment]
According to Synopsys, this is a tool issue fixed in VCS 2020.12-SP2-2.

It appears with VCS 2020.12-SP2-1, but I tried with VCS 2020.12-SP2 (the default version used in OpenTitan) and it's also fine.

Let me add clkmgr test back and close this issue.

**Comment by tjaychen** [comment]
i think this is closed now, @weicaiyang let me know if you disagree.

**Comment by weicaiyang** [comment]
I forgot to close this. Thanks @tjaychen.
