### ISSUE TITLE
[dv,top] PR #8184 is a hack to allow AST registers to extend from ast_base_reg

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#8204]
ast_base_reg (that extends dv_base_reg) is a class from which all of the 'real' AST register models extend from and it is visible only in Nuvoton's internal repo.
The chip level register model extend dv_base_reg class and there is no support to use a specific dv_base_my_prefix even if it was used in IP level.

**Comment by cindychip** [comment]
This PR is created to fix this issue: https://github.com/lowRISC/opentitan/pull/9007

**Comment by sriyerg** [comment]
I think this is addressed. Perhaps we can close it?

**Comment by sha-ron** [comment]
closed via #9007
