### ISSUE TITLE
[doc] Vivado link in install instructions broken

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#8223]
It looks like the documented version of Vivado (2020-1) has been removed from Xilinx's main downloads page (https://www.xilinx.com/support/download.html). The link in the installation guide appears to be broken: https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/vivado-design-tools/2020-1.html.

The docs should probably be updated to at least 2020-2. That seems to be what we recommend.

**Comment by vogelpi** [comment]
I agree that we should fix the link, but I don't think it's absolutely needed to update the documentation. It's quite time consuming to re-install Vivado just to update the screenshots.
