### ISSUE TITLE
[mask_rom] Call to base_printf in shutdown_finalize jumps out of .shutdown section

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#8236]
PR #8237 places the `shutdown_finalize` function into the `.shutdown` section placed in the ROM after all other executable code. However the `shutdown_finalize` function makes a call to `base_printf` in order to report the redacted error message which means there is a call back into the `.text` section.

There are a few possible courses of action:

1) Leave as-is. The print will likely be disabled in PROD anyway.
2) Create a bespoke minimal print function and inline it into `shutdown_finalize`.
3) Move `base_printf` (and all its baggage) into the `.shutdown` section.

I think (2) would probably be ideal. Option (3) seems messy to me.

**Comment by moidx** [comment]
Hi @alphan, @mundaym is this issue still pending feedback from the security WG or has it been resolved?

**Comment by alphan** [comment]
#10749
