### ISSUE TITLE
[otbn] Define a list of errors to align ERR_BITS and FATAL_ALERT_CAUSE

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#8238]
We currently have two external CSRs containing error information, `ERR_BITS` and `FATAL_ALERT_CAUSE`. `ERR_BITS` is only updated when an operation (one started by writing `CMD`) fails, while `FATAL_ALERT_CAUSE` only contains fatal errors.

Since we defined these registers we made smaller changes to the spec and the implementation, creating a bit of inconsistency and sources for confusion. For example, we expanded the term "operation" to not only mean "execute code", but also "execute a secure wipe operation". That means `ERR_BITS` can now also be set as result of a data or instruction memory secure wipe operation. [That's not yet implemented, but specified.]

To reduce the confusion a bit, here's a proposed list of action:
* Create a table with all errors (which also includes a unique error name).
* Update the documentation on `ERR_BITS` and `FATAL_ALERT_CAUSE` to reference these errors, instead of defining two lists of similar errors.

I had a look at the errors we have today and created a quick spreadsheet at 
https://docs.google.com/spreadsheets/d/1zLSFSWAY6VetNSDRvmVkZAUdMlJU5E5YfygpsIN1yZo/edit?usp=sharing

@rswarbrick @GregAC WDYT? If you're OK with the general course of action, I'll follow up with a PR.

**Comment by rswarbrick** [comment]
This sounds like a good idea to me.

**Comment by GregAC** [comment]
Sounds good to me also
