### ISSUE TITLE
[prim_lfsr] Improve statistics of non-linear output

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#8249]
This discussion has been spun out from https://github.com/lowRISC/opentitan/pull/8222.

------------------------------------------------------
After looking into PRESENT_PERM32 and PRESENT_PERM64, I'm not sure that these are good choices for the aligned permutation.
e.g. 
lfsr bits 63, 47, 31 and 15 connect to SBOX_0
lfsr bits 62, 46, 30 and 14 connect to SBOX_1

after shifting the LFSR data by 1, SBOX_0 will have the same output as SBOX_1 in the previous cycle.
The same is true for any two neighbouring SBOXes.  
I'm not sure if this could be used by the attacker, but it might be better to have a permutation without this particular pattern.

_Originally posted by @vrozic in https://github.com/lowRISC/opentitan/pull/8222#discussion_r711229598_

**Comment by msfschaffner** [comment]
Good catch @vrozic.

The nice thing about this permutation is that it can be technically extended to work for any input vector size that is an integer multiple of 4. It just strides over the input vector and taps out SBox inputs at regular intervals, e.g. for a 16bit vector:
```       
     SBox #
        v
input: [0|1|2|3|0|1|2|3|0|1|2|3|0|1|2|3]
```
In order to break the shifting property that you identified, how about we make the following modification.
- Require vector size to be a multiple of 4.  
- Distribute first half of input vector bits as above
- Reverse assignment of second half of input vector bits, plus rotate that second half `lrot 1` to avoid adjacent bits in the middle. 

E.g. for a 16bit vector:
```       
[0|1|2|3|0|1|2|3 | 0|1|2|3|0|1|2|3] // original assignent
                 v
[0|1|2|3|0|1|2|3 | 3|2|1|0|3|2|1|0] // reverse second halve
                 v
[0|1|2|3|0|1|2|3 | 2|1|0|3|2|1|0|3] // lrot 1 second halve
```
WDYT?

_Originally posted by @msfschaffner in https://github.com/lowRISC/opentitan/pull/8222#discussion_r711296519_

**Comment by vogelpi** [comment]
Thanks Michael for creating the issue. I think the proposed reverse-second-half + lrot-1-second-half scheme is fine.

From your draft PR one can observe that this gives the following assignment:
```
    // SBox0: 0,  4, 10, 14
    // SBox1: 1,  5,  9, 13
    // SBox2: 2,  6,  8, 12
    // SBox3: 3,  7, 11, 15
```
As you can see there is still a linear relationship in the first two bits. This is probably okay but we can avoid that by changing the pattern as follows (again for a 16-bit vector):
```
[0|1|2|3 | 0|1|2|3 | 0|1|2|3 | 0|1|2|3] // original assignent
                   v
[0|1|2|3 | 1|2|3|0 | 2|3|0|1 | 3|0|1|2] // lrot x all 4-bit nibbles, where x is the nibble/S-Box index
                   v
[0|1|2|3 | 1|3|2|0 | 2|3|0|1 | 3|1|0|2] // flip middle bits of odd 4-bit nibbles
```
This should give the following assignment:
```
    // SBox0: 0,  7, 10, 14
    // SBox1: 1,  4, 11, 13
    // SBox2: 2,  6,  8, 15
    // SBox3: 3,  5,  9, 12
```
Does that make sense? @vrozic ?

**Comment by vrozic** [comment]
@vogelpi , I'm trying to figure out how this method would scale to a 32 bit case. Is it something like:
```
0 1 2 3 | 4 5 6 7 | 0 1 2 3 | 4 5 6 7 | 0 1 2 3 | 4 5 6 7 | 0 1 2 3 | 4 5 6 7 |  // original 
0 1 2 3 | 5 6 7 4 | 2 3 0 1 | 7 4 5 6 | 0 1 2 3 | 5 6 7 4 | 2 3 0 1 | 7 4 5 6 |  // after lrot 
0 1 2 3 | 5 7 6 4 | 2 3 0 1 | 7 5 4 6 | 0 1 2 3 | 5 7 6 4 | 2 3 0 1 | 7 5 4 6 |  // after flipping middle bits
```

This should give the following assignment:
```
// Sbox 0:
// Sbox 0:
// Sbox 0:
// Sbox 0:
// Sbox 0:
// Sbox 0:

**Comment by vogelpi** [comment]
Thanks for weighing in @vrozic . For the 32-bit case one would have to increase the granularity as there will be 8 instead of just 4 S-Boxes, i.e., take bytes instead of 4-bit nibbles. So, the lrot would be applied at a byte level and the flipping would become a shuffle/zip/interlace (see e.g. [here for an illustration](https://programming.sirrida.de/bit_perm.html)):
```
0 1 2 3 | 4 5 6 7 | 0 1 2 3 | 4 5 6 7 | 0 1 2 3 | 4 5 6 7 | 0 1 2 3 | 4 5 6 7 |  // original 
0 1 2 3 | 4 5 6 7 | 1 2 3 4 | 5 6 7 0 | 2 3 4 5 | 6 7 0 1 | 3 4 5 6 | 7 0 1 2 |  // after lrot on bytes
0 1 2 3 | 4 5 6 7 | 1 5 2 6 | 3 7 4 0 | 2 3 4 5 | 6 7 0 1 | 3 7 4 0 | 5 1 6 2 |  // after shuffling odd bytes
``` 
The assignment then becomes:
```
// SBox0: 0, 15, 22, 27
// SBox1: 1,  8, 23, 29
// SBox2: 2, 10, 16, 31
// SBox3: 3, 12, 17, 24
// SBox4: 4, 14, 18, 26
// SBox5: 5,  9, 19, 28
// SBox6: 6, 11, 20, 30
// SBox7: 5, 13, 21, 25
```

**Comment by vrozic** [comment]
Thanks for the clarification @vogelpi , I think I understand now how it works.
However I still see the same type of 2-bit dependencies:
e.g. SBox4(n) = 0x0x       Sbox5(n+1) = 0x0x
       SBox4(n) = x0x0       Sbox0(n+1) = x0x0

It seems to be difficult to get rid of it in a simple way.

**Comment by msfschaffner** [comment]
Thanks for digging deeper into this.

The goal of my first proposal above was really just to get rid of linear 4bit dependencies, which basically result in a situation where the Sbox outputs are just shifted as @vrozic has pointed out originally (since the sbox has 4 input bits).

If we want to get rid of sub-4bit linear dependencies as well, I also think that this will be difficult to achieve in a simple way....
One way I could think of is just doing multiple sbox/permutation rounds - but do we really need to go that far, given that this is supposed to be a "simple PRNG with slightly better statistics"?

**Comment by vogelpi** [comment]
Yes I agree it's probably not required to get rid of all sub-4-bit relationships. In the end, it's still a non-linear element: if we flip two out of 4 input bits, the number of output bits that change can still varies, it depends on all of the input bits.

So for me its fine to go with your proposal Michael, especially as also Vladimir thinks it's okay.

**Comment by msfschaffner** [comment]
Ok, sounds good! I opened #8250 for reviews. Could you PTAL?

**Comment by msfschaffner** [comment]
The permutation update has now been merged - closing.
