### ISSUE TITLE
[otbn] Add BUS_INTG_VIOLATION to ERR_BITS?

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#8259]
The only error which isn't present in ERR_BITS at the moment is BUS_INTG_VIOLATION. Is there a reason why we don't have it in ERR_BITS, but only in FATAL_ALERT_CAUSE? 

@GregAC

**Comment by GregAC** [comment]
I can't think of a reason not to include it.

I guess at the time it was seen as an error not related to the execution of OTBN so wasn't included in ERR_BITS. We've already got two errors in ERR_BITS that aren't related to the execution of OTBN (fatal_illegal_bus and fatal_lifecycle) so we should add fatal_bus_intg_violation and keep things uniform.

**Comment by imphil** [comment]
Sounds good, I'll do a PR.
