### ISSUE TITLE
External flash potential flow changes + analog components

### ISSUE THREAD

**Issue by rafpsiakis** [lowRISC/opentitan#8260]
Hello all,

We are building a chip with opentitan as an ROT but the integration of flash is not possible. The flash will be external to the SoC.
Is that ok security wise? Is DiversificationKey ok to be provisioned in OTP instead? What else needs to change or it is violated in your opinion?

Another question we have is wrt the analog components. Is there any recommendation from opentitan community for the analog components like sensors, shiled, entropy source etc? Is there anyone who has taped out opentitan and could probably give us some insights on these things?

Thanks a lot,
Rafail

**Comment by rafpsiakis** [comment]
Hello @tjaychen,

Thanks for addressing my request. Your commit states that it fixes lowRISC#8260 but the fix is about edn. Is it a mistake or its something I dont get?

Thanks a lot,
Rafail

**Comment by tjaychen** [comment]
sorry that was a mistake on the PR.
