### ISSUE TITLE
[hw/rv_timer] is not particularly aligned with other RISC-V systems

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#8274]
The harts / timer mapping in the rv_timer block is not particularly aligned with how other RISC-V systems implement this.

According to the OpenTitan [rv_timer specification](https://docs.opentitan.org/hw/ip/rv_timer/doc/):

_"The timer IP supports more than one HART and/or more than one timer per hart. Each hart has a set of tick generator and counter. It means the timer IP has the same number of prescalers, steps, and mtime registers as the number of harts. Each hart can have multiple sets of mtimecmp, comparater logic, and expire interrupt signals. This version of the IP is fixed to have one Hart and one Timer per Hart."_

# HW Discussion

Note: below recaptures much of the discussion in #8142.

@tjaychen mentioned: _"i think the idea behind the separate registers for each HART in timer might be in the event of multiple hosts, we want them to be able to independently manage their own timers without potentially having rmw conflicts or requiring mutexes. I feel like if we want things consistent, the better longer term approach might be to not differentiate within rv_timer, but have independent rv_timers for each HART, that way they are all consistent."_

@tjaychen also mentioned: _"to be honest, the RIGHT way to deal with this is probably using banked registers. Ie each HART would then see the "same address" for its timer, but based on an incoming ID bank to separate physical set. We would then get the benefit of actual isolation without different code per HART.  I think the existing solution might also have a different
address / bit issue."_

@msfschaffner mentioned: "_I am not sure this is required anymore in the newest RISC-V privileged spec, but looking at some other systems from SiFive (e.g. [FU540, Chapter 9](https://static.dev.sifive.com/FU540-C000-v1.0.pdf#page=60)) it looks like there is only one timer value (mtime) that is shared among multiple harts (i.e. each hart has its own mtimecmp). Also, it looks like we do not follow the same register map structure here. I.e., the timer regs are exposed as part of the CLINT module, which also contains the msip registers (that register is currently located in our rv_plic module)._"

@tjaychen mentioned "_i recall there was a discussion about sticking with the current interrupt
structure or switching to CLINT.  But I think the latter's spec may not
have been clear at the time?_"

@eunchan mentioned: "_If we decide to follow [the SiFive memory map], then we probably need only one RV_TIMER and remove prescaler feature also. I think it is too simple so that SW could not have a consistent code across the generations or have more calculation inside the timer Interrupt Service Routine to correctly compute the next event time. As of now, RV_TIMER has two knobs to configure. One is # of Harts another is # of Timers / Hart. I think the Hart in SiFive impl matches with Timers in our RV_TIMER with only one Hart. So that the IP has only one mtime but has mutliple mtimecmp values._"

@eunchan also mentioned:  _"I think that one we discussed was CLIC."_

@msfschaffner mentioned:  _"Right, the naming here does not make it easy to keep these things appart. The CLIC is yet another module that provides low-latency, vectored interrupts - which we do not support in OpenTitan at the moment."_

# SW Discussion

@timothytrippel mentioned: "_Regarding the OTTF, I’ve been able to port FreeRTOS to our system with the current rv_timer, and as far as DIF autogeneration (#8142) goes I can make the current rv_timer implementation work as well, so not critical from my side._"

@hudson-ayers mentioned: "Tock currently does not require a risc-v compliant mtimer -- chips just have to have some timer capable of implementing Tock's Alarm HIL, which earlgrey does. That said, I just took a look at the current upstream [rv_timer implementation](https://github.com/tock/tock/blob/master/chips/earlgrey/src/timer.rs), and it assumes that it is mtimer compliant, so we should fix that where those assumptions are wrong."

**Comment by timothytrippel** [comment]
per @domrizz0's request, separated this (from #8142) into a separate issue.

**Comment by mundaym** [comment]
I think this issue can be closed now. Please reopen if you disagree.
