### ISSUE TITLE
[sw/usbdev] OpenTitan USB HID support

### ISSUE THREAD

**Issue by felixoberhansl** [lowRISC/opentitan#8290]
Hi,
as you describe [here](https://docs.opentitan.org/doc/security/use_cases/), some use cases for the OpenTitan require it to act as an USB Human Interface Device (HID).
Do you plan to release an USB HID library that can leverage the exisiting usbdev and the corresponding dif library? If so, do you have a rough timeline you could provide us with?
Or do you see that functionality out-of-scope for the OpenTitan project? 
Thank you!

**Comment by tjaychen** [comment]
i think that functionality will come, but it's not super high on the priority list right now.
This is partially because the `usbdev` module itself has not received sufficient verification to begin any major development work based on it.

**Comment by imphil** [comment]
There is no roadmap for this module right now, and I don't expect major changes to that during the remainder of this year. Of course, you're invited to jump in and drive the IP block forward: OpenTitan is open source and we're happy to accept contributions!

**Comment by msfschaffner** [comment]
@a-will can you take a look and update this issue accordingly?

CC @vogelpi @mdhayter

**Comment by a-will** [comment]
For `usbdev`, all the necessary hardware features are present, modulo a lack of verification beyond the UART example we have implemented. The HID class uses control and interrupt endpoints, with short packets delimiting the end of a transfer. This is all in scope for the module.

For implementing U2F and the HID class, software will be required to get that "personality," so to speak. I'm not aware of any plans to create such an example, but patches may be welcome. :)

That said, in the not-too-distant future, I have tentative plans to clean up the DIFs, rebase the example USB stack on top of them, and possibly retool some of the APIs. Arguably, the DIFs also might not be the best target for that example--Targeting an RTOS with proper drivers would likely produce a more rewarding outcome.
