### ISSUE TITLE
uartdpi: Use modern APIs for PTS device

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#83]
Currently we use a mix of old-school, non-standard BSD APIs to open a pseudo-terminal. There are newer APIs, which are unfortunately a bit underdocumented. However, the code at https://github.com/opensocdebug/osd-sw/blob/master/src/libosd/terminal.c#L188 does the trick.

**Comment by msfschaffner** [comment]
This issue came up in the D3 review for UART. 
Is this something that we can close or re-categorize?

**Comment by msfschaffner** [comment]
Thanks @a-will. Let's label this as V3 for now, and re-categorize once we are holding the V3 signoff review.
