### ISSUE TITLE
[Hugo] Mobile Firefox doesn't show full-width content

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#830]
I see the responsive  of the opentitan webpage. But Firefox on Android shows the sidebar that results the content isn't shown full-width.

![Screenshot_20191102-212645](https://user-images.githubusercontent.com/1192814/68146677-63686100-feed-11e9-8d85-ad1e4b915453.png)

**Comment by johngt** [comment]
Closing this as there have been subsequent improvements to the website. We can revisit web-page issues more generally with newer issues.
