### ISSUE TITLE
[dv/chip] Improve SW test pass/fail status logic

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#8300]
From this comment: https://github.com/lowRISC/opentitan/pull/8189/files#r713434978

As Sri pointed out:
"The problem is with our test vseq - in SwTestStatusFailed case, it continues on to the next iteration, which causes the sw_test_status value to transition from a terminal state (fail) to under reset, triggering the error from line 53."

Need to revisit the SW status p/f logic.

**Comment by msfschaffner** [comment]
Is this still an issue or can we close this?

**Comment by cindychip** [comment]
Thank you for reminding us. 
I think this test is fixed via: https://github.com/lowRISC/opentitan/pull/8730
Please feel free to re-open it if I interpret it wrong.

**Comment by sriyerg** [comment]
Agreed - this is now supported.
