### ISSUE TITLE
[keymgr] Add some additional regwen

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8301]
During keymgr v2 review, it was discovered.

- `reseed_counter` is not locked down with `regwen`, this is not good
- it would be good to cover `sideload_clr` with transactional `regwen`, that way we remove the need to have to test `sideload_clr` under a bunch of conditions.

**Comment by tjaychen** [comment]
@cindychip 
@weicaiyang 
@sriyerg 

let me know if this looks right to you.

**Comment by weicaiyang** [comment]
Thanks @tjaychen. this looks great.

**Comment by cindychip** [comment]
Sorry just saw it. LG :)
