### ISSUE TITLE
[doc/pwrmgr] Fix name of wakeup bit 5

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#8337]
The generated pwrmgr hjson file lists PWRMGR_PARAM* names for each of the 6 wakeup bits.
The name for bit 5 is PWRMGR_PARAM_WKUP_REQ_IDX, but should be PWRMGR_PARAM_SENSOR_CTRL_WKUP_REQ_IDX.

**Comment by tjaychen** [comment]
thanks @matutem for noticing this. The topgen process probably is not concating the instance name with the wkup name, this could cause problems later. 

I will look at fixing this.
