### ISSUE TITLE
Connect UART to IOC3/IOC4 rather than IOC10/11

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#8355]
Right now the standard configuration (assumed by the test boot ROM, smoke tests, Verilator etc.) is that pins IOC10 (RX) and IOC11 (TX) are UART connections. For the mask ROM we will need to use IOC3 (RX) and IOC4 (TX) as the UART.

I'm wondering how arbitrary the existing IOC10/11 assignments are. Should we continue to support IOC10/11 as well or could we just switch everything to IOC3/4?

**Comment by mundaym** [comment]
@tjaychen @sriyerg any opinions?

**Comment by mundaym** [comment]
Using IOC3/4 as the UART is probably going to mean reconfiguring Verilator to use different pins as GPIO. I'm fairly certain that IOC10/11 were chosen because there are 32 GPIO pins and IOC10 and IOC11 are the first two pins following that allocation, pins 32 and 33 respectively.

**Comment by tjaychen** [comment]
@timothytrippel / @sriyerg  i think we talked some time ago (although we've not actualized this yet) that DV, verilator etc would primarily support the most stressful use case we have.  In all of our use cases so far we denote 3/4 as the native UART, so I think it is reasonable to switch to them as well.

**Comment by sriyerg** [comment]
Pinmux is sufficiently verified with FPV, which, in conjunction with top level connectivity obviates the need to test for example, UART0 IO can be connected to every single pin. 

We decided that our pinmux config for all usecases (CrOS, TI, etc.) will be extracted from a corresponding HJSon which will capture the configuration for that usecase, and we will only stick to that limited set, rather than randomly switch the pinmux assignments at runtime. Since that configuration comes from the HJSon, the SW running on the device AND the host should automatically adhere to it. As such, this should be transparent to all of our simulation platforms.

**Comment by timothytrippel** [comment]
> Pinmux is sufficiently verified with FPV, which, in conjunction with top level connectivity obviates the need to test for example, UART0 IO can be connected to every single pin.
> 
> We decided that our pinmux config for all usecases (CrOS, TI, etc.) will be extracted from a corresponding HJSon which will capture the configuration for that usecase, and we will only stick to that limited set, rather than randomly switch the pinmux assignments at runtime. Since that configuration comes from the HJSon, the SW running on the device AND the host should automatically adhere to it. As such, this should be transparent to all of our simulation platforms.

+1, as @sriyerg stated, this won't matter in the long run since it will be transparent to each platform so assign how you need them.

We have a doc describing this, it just has not been actualized yet as you stated @tjaychen.

**Comment by tjaychen** [comment]
sorry quick question, in the top level dv TB though, won't we have to
physically connect the uart agents to IOC3/4?

**Comment by sriyerg** [comment]
> sorry quick question, in the top level dv TB though, won't we have to physically connect the uart agents to IOC3/4?

Agreed, but that is trivial.

**Comment by tjaychen** [comment]
o yes agreed, i just meant in my original reply that's the "change" dv
should make to match.

**Comment by sriyerg** [comment]
> o yes agreed, i just meant in my original reply that's the "change" dv should make to match.

Right - that should be ok. Once those pinmux config HJSons are ready, we will extract that info into an SV data structure which the TB top can use to know which port to connect the UART (and all the other) agents to.

**Comment by timothytrippel** [comment]
> @timothytrippel sorry can you remind me, do we have an issue to track those hjson's already? if we do, feel free to add me to it, and i can look into creating it since I really want to deprecate the sheet we're using to maintain things now.

We did not, but I just created one: #8380.

**Comment by tjaychen** [comment]
thank you Tim!
