### ISSUE TITLE
[doc/checklist] Consider removing specific countermeasure guidance

### ISSUE THREAD

**Issue by tomeroberts** [lowRISC/opentitan#8395]
Continuing the discussion from #8198 on the issue of keeping specific countermeasure line items (such as SEC_NON_RESET_FLOPS) in the D3 checklist.

It was suggested to either list all such standard countermeasures in the checklist, or to remove them from the checklist and point to a separate guidance doc.

In addition, it was suggested to reword the existing point, or add a new one to cover the explicit review of countermeasures.

**Comment by moidx** [comment]
Closing as obsolete. We now have a standard process for listing/auditing countermeasures.
