### ISSUE TITLE
[doc/checklist] Update post-D2 blocks for checklist changes

### ISSUE THREAD

**Issue by tomeroberts** [lowRISC/opentitan#8397]
PR #8198 updates the checklists to match the current practice of deferring security countermeasure implementation to the D3 stage. All existing checklists have been updated to match the changes, but those blocks that have been through D2 already might have inconsistent text written against the security items in D2 and D3.

This issue tracks required updates to make the checklists consistent with the spec. Those blocks are:

- [x] aon_timer
- [ ] clkmgr
- [x] csrng
- [x] edn
- [x] entropy_src
- [ ] flash_ctrl
- [x] gpio
- [x] hmac
- [x] i2c
- [ ] keymgr
- [x] lc_ctrl
- [x] otp_ctrl
- [x] pattgen
- [x] pinmux
- [ ] pwrmgr
- [ ] rstmgr
- [ ] rv_core_ibex
- [x] rv_plic
- [x] rv_timer
- [x] sram_ctrl
- [x] sysrst_ctrl
- [x] tlul
- [x] uart

Quite a few blocks! but the changes required will be minimal

**Comment by msfschaffner** [comment]
I went through the blocks quickly and corrected some of the inconsistencies in #10661.
For the blocks that we have not marked off above: these will still go through D2S reviews, so we're going to correct them / check them off later.
