### ISSUE TITLE
[rom] Mitigate slow or uncalibrated TRNG issues

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#8430]
The entropy complex provides random bits which are consumed by hardware countermeasures. In general, unavailable or slow entropy should be escalated as an attack vector. However, during early manufacturing, we may need the ability to enable  secure boot even when the TRNG has not been fully calibrated. 

This is issue is to track the investigation of mechanisms needed to mitigate any issues with uncalibrated or not properly calibrated TRNGs, and potential issues with the entropy distribution network. 

One specific case is SRAM scrambling key rotation during secure boot. Should we add an OTP configuration value to skip this step during manufacturing and/or to handle production issues?

**Comment by moidx** [comment]
CC @alphan not sure if we are tracking this already in a different place

**Comment by alphan** [comment]
Thanks @moidx! I vaguely remember adding an item to the spreadsheet but let's keep this open as well just in case.

**Comment by moidx** [comment]
https://github.com/lowRISC/opentitan/pull/18787 added `CREATOR_SW_CFG_SRAM_KEY_RENEW_EN` which can be used to skip SRAM re-scrambling. All other uses of entropy in software can be bypassed via other OTP settings.

Adding an OTP to skip entropy complex initialization results in boot hangs, so this is not targeted for M2.5. With the entropy complex enabled by default, any non-local alerts resulting from hardware bugs can be masked to avoid escalations.

**Comment by moidx** [comment]
Audited use of entropy in ROM release https://github.com/lowRISC/opentitan/releases/tag/Earlgrey-M2.5.2-ROM-RC1.

* EDN1 is not enabled during ROM boot
* EDN0: 

edn_req_id | endpoint | requested bits
-- | -- | --
0 | keymgr | 0
1 | opt_ctrl | ~1920 - Scrambling key requests and flash_ctrl countermeasure req
2 | ast | 32
3 | kmac | 0
4 | alert_handler | 32
5 | aes | 32
6 | otbn_urnd | 1024
7 | rv_core_ibex | 320
  | Consumed | 3360

`otp_ctrl` and `otbn_urnd` consumption can be reduced via ROM settings by disabling SRAM scrambling and OTBN based signature verification.
