### ISSUE TITLE
[rstmgr/clkmgr] Update DV environment and add SVAs

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#8442]
The following two PRs add "clock gated" / "reset asserted" output to the clock and reset managers:

https://github.com/lowRISC/opentitan/pull/8418
https://github.com/lowRISC/opentitan/pull/8419

These are simple "ON / OFF" indication signals, but they are encoded with a multibit type for security reasons, since they are used by the alert handler to temporarily turn off the background ping checks (see also [this document](https://docs.google.com/document/d/1MHksAy_p3yQ4kYbQC3zlOutIvTBffuVCaP53LAy5zUM/edit#heading=h.l7qwxjui9ien) for more info).

A simple SVA check will probably suffice.

**Comment by msfschaffner** [comment]
Note that the multibit type is `lc_tx_t` at the moment, but I will go through and replace all that with `mubi` types once the alert handler low-power feature has landed.

**Comment by msfschaffner** [comment]
I am not sure this is implemented already.
If so, please close the issue.

**Comment by matutem** [comment]
This is all done.
