### ISSUE TITLE
[keymgr] kmac_if.u_cnt.err_o is only checked in a particular state

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#8464]
@tjaychen 

you mentioned it may be better to always trigger alert if the cnt has an error, rather than only trigger in a particular state.
Let me know if we can update that.

**Comment by tjaychen** [comment]
yeah thanks for the reminder. I'll have a look.
I think it should be possible.

**Comment by weicaiyang** [comment]
@tjaychen is this still true, or we have updated the design?
