### ISSUE TITLE
[mubi] True/false terminology

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#8511]
> Do we maybe have to change the mubi terminology a bit so it can be used without wrapping? I.e., something along the lines of `en` / `dis` or `on` / `off` instead of `hi` / `lo` ?

i'm honestly not sure yet... it feels like the answer is yes, but for situations where i use this to represent transaction type (ie, instruction or data), it doesn't seem to quite fit either. I feel like HI/LO is more generic, at the expense of certain situations not completely mapping..

_Originally posted by @tjaychen in https://github.com/lowRISC/opentitan/issues/8462#issuecomment-932684249_

**Comment by msfschaffner** [comment]
@rswarbrick runs eagerly forwards with bikeshed paint... How about "yes / no"?

_Originally posted by @rswarbrick in https://github.com/lowRISC/opentitan/issues/8462#issuecomment-933268298_

**Comment by msfschaffner** [comment]
Some more bike shedding: I remember that one of our SW folks (@alphan?) implemented something similar for a SW boolean type with a high Hamming distance, and he just used true / false (and called them "truthy / falsey" values :)): https://docs.opentitan.org/sw/apis/hardened_8h.html

**Comment by tjaychen** [comment]
ah yes yes / no and true / false would too.
I would probably lean towards true / false since it's sound more binary-y

**Comment by msfschaffner** [comment]
Agreed. And it would be consistent with what SW does for hardened booleans.

**Comment by tjaychen** [comment]
o wait, does YES / NO or TRUE / FALSE make things more confusing with the
logical AND / OR?

**Comment by msfschaffner** [comment]
For the logical functions, we should probably change the terminology to active high / low instead of true / false in order to not make it more confusing:

E.g:
```systemverilog
  function automatic mubi4_e mubi4_or_high(mubi4_e a, mubi4_e b);
    return mubi4_or(a, b, MuBi4True);
  endfunction : mubi4_or_high
```

**Comment by rswarbrick** [comment]
Maybe we should just define an alias (or even just put 4 entries in the enum, with two entries for each value?) to allow a version that sounds less like true and false for the logical functions? Or (my preferred option) don't worry about it and just write a comment explaining what's going on :-)

**Comment by alphan** [comment]
I probably don't have all the context to have a strong opinion or suggestion, true/false sounds reasonable but true/false should ideally capture the meaning (not the physical value) to avoid confusion when active high/low signals are involved. I guess this is in line with @rswarbrick's comment above, i.e. 2 entries for each.

**Comment by msfschaffner** [comment]
we can make an alias, but it sounds like true/false or similar would actually fit well. since these are multibit signals, we are talking about labels for the logical interpretation, and not the physical values on the wires.

**Comment by msfschaffner** [comment]
The names are going to be aligned in https://github.com/lowRISC/opentitan/pull/8535. PTAL.
