### ISSUE TITLE
[reggen] Clarify async + regwen usage

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8514]
Automatically check in the tool to ensure `regwen` are not asynchronous registers.
`regwen` can be used to gate registers in other domains, but it is handled as part of `prim_reg_cdc` and does not need the user to declare it in the other domain.

When the user does this, the behavior is not "wrong" per se, but it is completely unnecessary.

**Comment by msfschaffner** [comment]
Hey @tjaychen, this should be an easy check to do - however, are there any cases where we want to have access to the `regwen` in the other domain? In such a case, wouldn't the automatic CDC handling for the `regwen` itself be beneficial?

**Comment by tjaychen** [comment]
o you mean the logic outside the `reg_top` wanting to view `regwen` in a different domain?

**Comment by msfschaffner** [comment]
yeah that's right.

**Comment by tjaychen** [comment]
that's a good point.. i had not considered that. So maybe you're suggesting that we change the "write lock" functionality to always be on the bus clock side, but allow the actual regwen hardware visibility to be on the other domain?

**Comment by msfschaffner** [comment]
For example, yes. Just to clarify, is the current behavior that the lock would be done in the other domain?
So it would work correctly, just with added sync delay?

**Comment by tjaychen** [comment]
naw the lock is actulaly done in the bus facing domain. It locks the bus side update from happening, which presents the async domain from taking on the new value.

**Comment by msfschaffner** [comment]
So does that mean that the current implementation already supports this usage (i.e., lock always in bus domain, but optional sync to other domain possible)?

**Comment by tjaychen** [comment]
i dont think so.. i think regwen type registers MIGHT ignore the fact that you invoke it as async. I could be wrong though, would need to double check.

**Comment by msfschaffner** [comment]
Ok - I just implemented a check for this to make sure we do not use this combination anywhere in our code base (thankfully no :)). It's probably safer to disallow this combination then if we're not explicitly supporting it.
