### ISSUE TITLE
[hw/aon_timer] HJSON 'interrupt_list' names do not match reg bits

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#8533]
Every IP that can raise IRQs has an `interrupt_list` field in its HJSON file that lists the names (in snake case) and brief descriptions (in a full sentence/phrase) of each interrupt it produces. See [here](https://github.com/lowRISC/opentitan/blob/master/hw/ip/aon_timer/data/aon_timer.hjson#L14) for an example of the aon_timer.

Additionally, for IPs that raise IRQs, their HJSON usually defines the following three registers (in the [`registers` field](https://github.com/lowRISC/opentitan/blob/master/hw/ip/aon_timer/data/aon_timer.hjson#L80)): INTR_STATE, INTR_ENABLE, and INTR_TEST. Typically, the bit fields within each of those three registers map 1:1 with the interrupts listed above in the `interrupt_list` field, and **_therefore their names match_**. For example, the aon_timer's interrupt name [`wkup_timer_expired`](https://github.com/lowRISC/opentitan/blob/master/hw/ip/aon_timer/data/aon_timer.hjson#L15) matches the bit-0 names in the [INTR_STATE](https://github.com/lowRISC/opentitan/blob/master/hw/ip/aon_timer/data/aon_timer.hjson#L198) and [INTR_TEST](https://github.com/lowRISC/opentitan/blob/master/hw/ip/aon_timer/data/aon_timer.hjson#L217) registers, i.e., `wkup_timer_expired` and `wkup_timer_expired`, respectively.

This is important, because the DIF auto-generation tooling---[`util/make_new_dif.py`](https://github.com/lowRISC/opentitan/blob/master/util/make_new_dif.py) and [associated templates](https://github.com/lowRISC/opentitan/tree/master/util/make_new_dif)---assumes these names match when making use of the auto-generated regs macros (e.g., `<ip>_regs.h`).

With the aon_timer, I discovered this assumption is broken with the [`wdog_timer_bark`](https://github.com/lowRISC/opentitan/blob/master/hw/ip/aon_timer/data/aon_timer.hjson#L18) interrupt. Specifically, the bit field names that correspond to the `wdog_timer_bark` IRQ  in the [INTR_STATE](https://github.com/lowRISC/opentitan/blob/master/hw/ip/aon_timer/data/aon_timer.hjson#L202) an [INTR_TEST](https://github.com/lowRISC/opentitan/blob/master/hw/ip/aon_timer/data/aon_timer.hjson#L221) registers are renamed `wdog_timer_expired`.

As is, this makes auto-generating IRQ DIFs (#8142) for the aon_timer more challenging.

To fix this, I propose simply changing the `interrupt_list` name of the [`wdog_timer_bark`](https://github.com/lowRISC/opentitan/blob/master/hw/ip/aon_timer/data/aon_timer.hjson#L18) interrupt to `wdog_timer_expired`, to match the corresponding register bit field names, _only if this will have no major impact on the HW side_. 

@msfschaffner @tjaychen @sriyerg will this impact indeed be minimal? If so, I already have a draft PR (#8534) with this fix available for review, just want to confirm this is true.

**Comment by tjaychen** [comment]
@timothytrippel yes this looks good!
I think this is happening partially because `aon_timer` is one of the only modules that does not use interrupt auto creation.

I THINK the reason at the time was either because of clock domain issues, or because `aon_timer` simply did not have a use for one of the registers. 

@tomroberts-lowrisc do you remember why? Any reason we can't convert them to just the normal ones? I'll see if I can dig up the PR.

**Comment by sriyerg** [comment]
I'd probably rename it the other way around (`wdog_timer_bark`). Impact seems very minimal - will let Tom / Rupert confirm.

**Comment by tomroberts-lowrisc** [comment]
We didn't add the INTR_ENABLE since that would allow the watchdog (bark) to be trivially disabled. I don't know if this is really a big deal since the bite would still trigger so happy to add them in to make things more consistent. Any thoughts on this @tjaychen ?

Definitely makes sense to align the field names, and `wdog_timer_bark` sounds good to me but we should decide on whether we're happy with adding in the enable before doing any changes.

**Comment by timothytrippel** [comment]
> We didn't add the INTR_ENABLE since that would allow the watchdog (bark) to be trivially disabled. I don't know if this is really a big deal since the bite would still trigger so happy to add them in to make things more consistent. Any thoughts on this @tjaychen ?

Just to clarify, no need for a INTR_ENABLE on the aon_timer from my DIF-autogeneration side of things (I already made it work in #8540. Was just stating something I noticed. Just need the interrupt names to match the bit field names. :)

> Definitely makes sense to align the field names, and `wdog_timer_bark` sounds good to me but we should decide on whether we're happy with adding in the enable before doing any changes.

Ok great, thanks @tomroberts-lowrisc ! I will update #8534 to use `wdog_timer_bark` instead of `wdog_timer_expired`.

**Comment by timothytrippel** [comment]
> > We didn't add the INTR_ENABLE since that would allow the watchdog (bark) to be trivially disabled. I don't know if this is really a big deal since the bite would still trigger so happy to add them in to make things more consistent. Any thoughts on this @tjaychen ?
> 
> Just to clarify, no need for a INTR_ENABLE on the aon_timer from my DIF-autogeneration side of things (I already made it work in #8540. Was just stating something I noticed. Just need the interrupt names to match the bit field names. :)
> 
> > Definitely makes sense to align the field names, and `wdog_timer_bark` sounds good to me but we should decide on whether we're happy with adding in the enable before doing any changes.
> 
> Ok great, thanks @tomroberts-lowrisc ! I will update #8534 to use `wdog_timer_bark` instead of `wdog_timer_expired`.

@tomroberts-lowrisc @sriyerg
Updated #8534 to use `wdog_timer_bark` instead of `wdog_timer_expired`, as requested.
