### ISSUE TITLE
[rtl/clkmgr] Fix alert for clock measurement

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#8556]
When a frequency measurement fails we issue an alert, but apparently alert sending should be edge triggered, and instead it is level in the clkmgr RTL, so we keep sending alerts for the failure. Weicai is more familiar with alerts, and he thinks this explains the DV exp_alert errors we keep getting for the frequency measurement test.

**Comment by matutem** [comment]
Good question. If there was some counter for these alerts then it would be useful to send one per failed measurement. Otherwise the behavior is boolean in that we would only know there was a measurement error. This would argue to just send a single alert. Software can implement some counter, where upon receiving an alert it increments a counter and clears the recov_err_code and alert, starts another measurement, etc.

**Comment by weicaiyang** [comment]
It makes sense to me if we trigger an alert after every measurement

**Comment by matutem** [comment]
It seems sending one alert per incorrect measurement is the right approach. SW should set things up so that bad measurements should  be very rare. It should be possible to maintain a count of times it got out of spec and deterrmine what to do if the count is too high. So I agree with your comment quoted below.

> sounds good. I'll change the recoverable alerts to one time firing as they should be.
> 
> hypothetically, if the clock frequency is just off for a very long time, it should be fine if we trigger an alert after every measurement right? I think what you're pointing out here is that if we are off for only one measurement, we should not keep sending alerts.

tb/
