### ISSUE TITLE
[lib] Write RISC-V assembly versions of some constant-time helpers

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#8566]
#8510 adds constant-time helpers to `hardened.h`, many of which can be significantly compressed into RISC-V instructions. For example:

```c
inline ct_bool32_t sltu(uint32_t a, uint32_t b) {
  ct_bool32_t out;
  asm("sltu %0, %1, %2; neg %0, %0" : "=r"(out) : "r"(a), "r"(b));
  return out;
}

inline ct_bool32_t seq(uint32_t a, uint32_t b) {
  ct_bool32_t out;
  asm("xori %0, %1, %2; seqz %0, %1; neg %0, %0" : "=r"(out) : "%r"(a), "%r"(b));
  return out;
}
```

**Comment by msfschaffner** [comment]
@timothytrippel @cfrantz anything left to do here?

**Comment by timothytrippel** [comment]
This would certainly be useful in the future, but it is not critical at them moment. I think we can close for now, and reopen later in the future if we decide to take this on.
