### ISSUE TITLE
error: failed to run custom build command for `libudev-sys v0.1.4`  

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#8577]
opentitan master 2021-10-8
Ubuntu: 18.04.4

error: failed to run custom build command for `libudev-sys v0.1.4`

Caused by:
  process didn't exit successfully: `/home/nicolast0604/opentitan/build-out/sw/host/opentitantool/release/build/libudev-sys-0308a6720829dd60/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBUDEV_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBUDEV_STATIC
  cargo:rerun-if-env-changed=LIBUDEV_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"` did not exit successfully: exit status: 1\n--- stderr\nPackage libudev was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libudev.pc'\nto the PKG_CONFIG_PATH environment variable\nPackage 'libudev', required by 'world', not found\n"', /home/nicolast0604/.cargo/registry/src/github.com-1ecc6299db9ec823/libudev-sys-0.1.4/build.rs:38:41
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
[435/2748] Generating 'sw/device/lib/e287d45@@flash_ctrl_ot@sta/flash_ctrl_regs.h'.
WARNING: Non-homogeneous multireg MP_REGION_CFG_SHADOWED skip multireg specific data generation.
WARNING: Non-homogeneous multireg BANK0_INFO0_PAGE_CFG_SHADOWED skip multireg specific data generation.
WARNING: Non-homogeneous multireg BANK0_INFO1_PAGE_CFG_SHADOWED skip multireg specific data generation.
WARNING: Non-homogeneous multireg BANK0_INFO2_PAGE_CFG_SHADOWED skip multireg specific data generation.
WARNING: Non-homogeneous multireg BANK1_INFO0_PAGE_CFG_SHADOWED skip multireg specific data generation.
WARNING: Non-homogeneous multireg BANK1_INFO1_PAGE_CFG_SHADOWED skip multireg specific data generation.
WARNING: Non-homogeneous multireg BANK1_INFO2_PAGE_CFG_SHADOWED skip multireg specific data generation.
[456/2748] Generating 'sw/device/lib/e287d45@@pinmux_ot@sta/pinmux_regs.h'.
WARNING: Non-homogeneous multireg WKUP_DETECTOR skip multireg specific data generation.
[460/2748] Generating 'sw/device/lib/e287d45@@usb_ot@sta/usbdev_regs.h'.
WARNING: Non-homogeneous multireg configin skip multireg specific data generation.
[591/2748] Compiling C++ object 'sw/device/silicon_creator/lib/drivers/1f256dc@@sw_silicon_creator_lib_driver_hmac_unittest@exe/.._.._.._.._vendor_google_googletest_googlemock_src_gmock-all.cc.o'.
FAILED: sw/host/opentitantool 
/home/nicolast0604/opentitan/util/invoke_cargo.sh /home/nicolast0604/.cargo/bin/cargo '--manifest-path=/home/nicolast0604/opentitan/sw/host/opentitantool/Cargo.toml --target-dir=/home/nicolast0604/opentitan/build-out/sw/host/opentitantool --release ' '' /home/nicolast0604/opentitan /home/nicolast0604/opentitan/build-out
[599/2748] Compiling C++ object 'sw/device/silicon_creator/lib/drivers/1f256dc@@sw_silicon_creator_lib_driver_hmac_unittest@exe/.._.._.._.._vendor_google_googletest_googletest_src_gtest-all.cc.o'.
ninja: build stopped: subcommand failed.

**Comment by nicolast0604** [comment]
After sudo apt install libudev-dev
It works, but 
ERROR: [Common 17-69] Command failed: Part 'xc7k410tfbg676-1' not found

**Comment by imphil** [comment]
Good that you solved the first issue!

The second one is tracked in #8618.
