### ISSUE TITLE
Anchor point additions

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8611]
- [x] rv_dm enable locations (implicitly covered by prim_lc_sync)
- [x] clkmgr clock bypass
- [x] aes critical registers? (covered by #10753)
- [x] kmac data register valid (covered by #6544)

**Comment by matutem** [comment]
This issue is not descriptive enough. I think it should be clarified or closed.

**Comment by tjaychen** [comment]
so this was a bug to remind myself to add buffers (if needed) to anchor signals for the backend.
