### ISSUE TITLE
[prim_count] switch to standardized use of prim count

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8612]
- [x] alert_handler ping timer (https://github.com/lowRISC/opentitan/pull/9594)
- [x] alert_handler escalator (https://github.com/lowRISC/opentitan/pull/9594)
- [x] alert_handler accumulator (https://github.com/lowRISC/opentitan/pull/9594)
- [x] prim_esc_receiver (https://github.com/lowRISC/opentitan/pull/9594)
- [x] otp_ctrl background check timer (https://github.com/lowRISC/opentitan/pull/9598)
- [x] otp address counters in DAI, LCI, KDI, partitions and scrambling block (https://github.com/lowRISC/opentitan/pull/9598)
- [x] sram_ctrl (#9703)
- [x]  ~aes~ not needed since aes uses a replicated fsm approach
- [x]  kmac key length count?
- [x]  entropy refresh count?
- [ ]  others?

**Comment by msfschaffner** [comment]
yeah, `lc_ctrl` does not really have traditional counters in its logic, and the transition count is modeled as part of the state transition logic (which is already hardened).

so yeah maybe you intended to put down `otp_ctrl` :). let's remove it...

**Comment by msfschaffner** [comment]
CC @vogelpi for AES

**Comment by vogelpi** [comment]
Thanks @msfschaffner and @tjaychen, the prim_count module looks interesting especially as it also supports the cross count mode. Regarding the integration in AES, I am tempted to just switch back to a single counter and move it back into the FSM. As we are now using multi-rail FSMs, the counter would still be hardened but it would simplify the design considerably. I need to think a bit more about that.

**Comment by msfschaffner** [comment]
If it's part of the FSM and therefore instantiated multiple times, this would be ok as well I think.

**Comment by tjaychen** [comment]
yeah if there's multi FSM already, i think just using a single count is fine. I added the cross count function to `prim_cnt` initially in case we wanted to use it for `AES`, but we don't have to.  By now, other places are also using cross count.

**Comment by vogelpi** [comment]
Okay cool, thanks for the feedback. So, I might indeed switch back to a single counter hardened through the multi-rail FSM. But anyway, having a shared primitive including cross count capability is really nice!

**Comment by m-temp** [comment]
Regarding KMAC:
https://github.com/lowRISC/opentitan/commit/63bd755d052a9a7f1282d632caf075b38dc141d6 implements the key index counter. Other counters were also covered in https://github.com/lowRISC/opentitan/pull/9477

**Comment by tjaychen** [comment]
thanks @m-temp.
It looks like we can close this issue now.
