### ISSUE TITLE
[prim] Add option for ECC inversion

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8623]
For ECC, in general data of all 0 generates check bits of all 0's.

This creates a situation where all 0's is a valid combination. 
This has been known for some time, and we just need to add an option in the ECC primitives to have an inversion option such that all 0 data has an all 1 check.

**Comment by msfschaffner** [comment]
Just a heads up that I am looking into this right now.

**Comment by tjaychen** [comment]
thanks Michael!

**Comment by rswarbrick** [comment]
I think this might be duplicated in #6478 as well.

**Comment by msfschaffner** [comment]
This issue has been addressed.
We are now using a "inverted" Hsiao codes system-wide, where it is guaranteed that all-zero and all-one code words are invalid.

CC @moidx @cdgori
