### ISSUE TITLE
[prim_double_lfsr] switch to standardized use of prim double lfsr

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#8629]
- [x] alert_handler ping timer (https://github.com/lowRISC/opentitan/pull/8628)
- [x] otp_ctrl background check timer (https://github.com/lowRISC/opentitan/pull/8628)
- [x] others?

**Comment by GregAC** [comment]
We may want something like this for OTBN for the LFSR backed URND but we're moving to a new PRNG @vrozic has been working on it.

**Comment by msfschaffner** [comment]
We discussed this in the security meeting today and concluded as follows:

We think the masking PRNGs are more critical than the clearing ones and it would be good to have some sort of redundancy there to guard against the continuous fault scenarios described above.
For KMAC this means that we should switch to the double LFSR since it only employs a single LFSR at the moment.
For AES however, no change is needed since 5 independent LFSRs are used to construct that PRNG.

For the clearing use cases, we believe that doubling the LFSR is not strictly required, and simply updating the seed more frequently would be sufficient.

We have the following action items:
- [ ] Use `prim_double_lfsr` for KMAC masking (@eunchan)
- [ ] Investigate more frequent seeding of SRAM_CTRL init (@msf)
- [ ] Investigate more frequent seeding of AES clearing (@vogelpi )
- [ ] Investigate more frequent seeding of KEYMGR clearing (@tjaychen)

**Comment by tjaychen** [comment]
so just FYI, the reseeding for keymgr is completely software controlled. So
software can certainly make that quite frequent if they so chose.
As for the sram_ctrl, I think that's more or less the power up init that
we're worried about right? For that one, there is effectively a reseeding
every time we do it in hw :)

**Comment by msfschaffner** [comment]
Ah ok, so in that case we probably won't have to do anything for KEYMGR.

As for SRAM_CTRL... The shutdown module may trigger this as well, I think. But what you're saying is that we basically rely on power-up init to wipe the memory clean (including left over state from previous power cycles), right?
In that case you are correct, we reseed it every time we use it, so this may be ok to leave as-is, too.

**Comment by tjaychen** [comment]
ah good point, i missed the shutdown case. But I guess you are right that
the shutdown would be accompanied by a reset and another wipe.

**Comment by vogelpi** [comment]
For AES, the clearing PRNG reseeding is also software controllable. So I think this should be fine, too.

**Comment by msfschaffner** [comment]
Thanks for the feedback @vogelpi - sounds good. 
So it looks like the only change we should make is in KMAC.

**Comment by msfschaffner** [comment]
@eunchan @m-temp can you take a look at the KMAC item? Thanks!

**Comment by m-temp** [comment]
Thx for mentioning that. I totally forgot about that. I'll have a look.

**Comment by msfschaffner** [comment]
Closing since the KMAC is now also using `prim_double_lfsr`.
