### ISSUE TITLE
[cdc] Add Dvsim support for Verix CDC

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#8638]
It has been decided to use Verix from RealIntent for signing off on CDC's.
In order to enable this tool flow, the following tasks need to be implemented:

- [x] Add the tool image to our internal Dvsim environment
- [ ] Create a `CdcCfg` class to Dvsim (derived from `OneShotCfg`)
- [ ] Add run scripts for Verix CDC
- [ ] Add Verix-specific results parser
- [ ] Tweak SDC for CDC runs
- [ ] Set up a CDC regression for the open-source view with generic libraries
- [ ] Set up a CDC regression for the closed-source view with target tech libraries
- [ ] TBD: check whether a waiver mechanism is needed

**Comment by tjaychen** [comment]
i think this is actually complete.
Will close for now. @msfschaffner feel free to reopen if what i'm saying is not true.

**Comment by msfschaffner** [comment]
Most of this is done - I believe the only outstanding part is the closed-source version of CDC that needs to be added at some point...

**Comment by tjaychen** [comment]
ah thanks for the reminder. 
should we bring this up during one of the nuvoton syncs on the potential libs?

**Comment by msfschaffner** [comment]
Yeah that would be good. I remember talking to them a while ago, but it would be good to remind them...
