### ISSUE TITLE
SPI host Misses last Byte of Segment

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#8643]
After #8620 was fixed another bug shows up - that wasn't there before.

after transmitting the segment 0 of 1 byte correctly - the DUT misses that last byte of segment 1

----| Command Register |----
----| Command: WriteStd
----| Segment Command
----| Length: 0
----| Mode: Standard
----| CSAAT: 1
----| Direction: Bidir
----| DATA |----
----| [ 0] fc |----

Segment 1 (address 32bit)
----| Command Register |----
----| Command: WriteStd
----| Segment Address
----| Length: 3
----| Mode: Standard
----| CSAAT: 1
----| Direction: TxOnly
----| DATA |----
----| [ 0] 4a |----
----| [ 1] e5 |----
----| [ 2] 79 |----
----| [ 3] 28 |----   **<------- THIS BYTE IS MISSED**

tracking this backwards this seem to be due to a premature clr_i to the prim_packer
which is generated by the cmd_end in the FSM

![image](https://user-images.githubusercontent.com/53917183/137128713-70384503-619f-4139-8137-9612ce67a38a.png)

recreate this checkout:

run: 
./util/dvsim/dvsim.py hw/ip/spi_host/dv/spi_host_sim_cfg.hjson -i spi_host_smoke -r 1 -t xcelium --job-prefix="nc run -C ncsim_interactive -Il" -w=shm -s=1

**Comment by Muqing-Liu** [comment]
Hi @rasmus-madsen, thank you for pointing this out! I can reproduce the error, but I am wondering in this case, is the last segment data not successfully transmitted? It seems like the data in the first segment (data "cc") is not transmitted, since csb was asserted after tx_data_i was changed. Am I missing something here? Thanks!
![image](https://user-images.githubusercontent.com/83983643/137558494-1ad2f6e0-6b11-4267-b482-404f7fba7df9.png)

**Comment by rasmus-madsen** [comment]
> Hi @rasmus-madsen, thank you for pointing this out! I can reproduce the error, but I am wondering in this case, is the last segment data not successfully transmitted? It seems like the data in the first segment (data "cc") is not transmitted, since csb was asserted after tx_data_i was changed. Am I missing something here? Or they are not aligned in this way? ![image](https://user-images.githubusercontent.com/83983643/137558494-1ad2f6e0-6b11-4267-b482-404f7fba7df9.png) 

Hi @Muqing-Liu 
I am not sure if you figured this out - but the CC is transmitted.
the CC you are point in to is from the bus - but the CSB circled in my drawing is related to the spi pins. which is why it comes later.

> Besides, I'm wondering what is the use of the data transmitted in the third segment for read command? Thanks!

Since this is legal behavior it it needs to be verified that the DUT handles it correctly
