### ISSUE TITLE
[pwrmgr] Add clk / rst checker for escalation receiver

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#8658]
It has been decided to implement these checks at the integration level (i.e., not inside the escalation receiver primitive).

The idea is to sample the clock and reset tree leafs next to the escalation receiver instance inside the power manager, and have the power manager trigger a system wide reset in case the escalation receiver clock and reset are in an inconsistent state.

Drawing from the discussion:
https://docs.google.com/drawings/d/1hKf9OeAziHIudlK8VINAjoiKMv42du7zlJh4kgiVPng/edit

For context:  #2049, #8037 and #8519

**Comment by tjaychen** [comment]
This implementation will make use of prim_clk_meas, but it must be enhanced to support clock timeout detection.
