### ISSUE TITLE
[boot_rom] flash program / erase before calibration

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8700]
Until clocks are calibrated, we technically should not be programming / erasing flash. 
Should we add some kind of qualification into boot_rom so that it knows to not honor boot strap requests if it's not in the right state?

We will eventually be able to determine whether clocks are calibrated based on whether AST has been initialized.

**Comment by tjaychen** [comment]
@zi-v 
@moidx 
@cfrantz 
@mundaym

**Comment by moidx** [comment]
We can probably use an OTP value to explicitly enable bootstrap functionality.  

We will need a system test to load a test program via JTAG into SRAM and configure OTP to initialize AST and enable bootstrapping.

**Comment by tjaychen** [comment]
@alphan can you confirm that this is effectively implemented through `OWNER_SW_CFG_ROM_BOOTSTRAP_EN`?

**Comment by alphan** [comment]
> @alphan can you confirm that this is effectively implemented through `OWNER_SW_CFG_ROM_BOOTSTRAP_EN`?
> 

Confirmed
