### ISSUE TITLE
[test] Add system level test for jtag initiated sram execution

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8702]
Add a test point for the case where jtag loads a program into sram and then jumps the ibex core to execute from sram.

**Comment by tjaychen** [comment]
@sriyerg this might be in the test plan already, i need to double check again, but i don't think i saw it.

**Comment by sriyerg** [comment]
This is not in the testplan yet. I will add it.

**Comment by msfschaffner** [comment]
@sriyerg has this been added to the testplan?

**Comment by msfschaffner** [comment]
This should now be in the testplan - closing.
