### ISSUE TITLE
[sram_ctrl] incorrect d_opcode for partial write

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#8703]
@tjayche

for write, we should return AccessAck. But sram_ctrl returns AccessAckData for partial write. Looks like internally it's recognized as a read. May be because it's a read modify write.

![Screen Shot 2021-10-15 at 4 08 47 PM](https://user-images.githubusercontent.com/49293026/137563198-0276aa2d-a1f9-47e7-b71e-6ab285e11ea8.png)

This is found in the same test as #8699
Waves: ot_debug -j smart:0892d9cb-1617-48dd-b598-876effe741e6
please get this PR #8701 and run sram_ctrl_main_smoke with seed=2822932991 (probably reproducible with any other seed)

**Comment by tjaychen** [comment]
@weicaiyang i think this issue is addressed now right?

**Comment by weicaiyang** [comment]
Yes, thanks @tjaychen
