### ISSUE TITLE
[fpga] rom.mmi needs to be updated after increasing the ROM size to 32kB

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#8716]
lowrisc/opentitan#8671 broke the FPGA ROM splicing flow. I was able to get it to work by making the following changes to the generated `rom.mmi` file: 

1. Use 4-bit address ranges, e.g. `<DataWidth MSB="3" LSB="0"/>`.
2. Swap Placement nibbles to get the correct nibble order. For example:

Before: 

```xml
<BitLane MemType="RAMB32" Placement="X8Y2">
  <DataWidth MSB="3" LSB="0"/>
  <AddressRange Begin="0" End="8191"/>
  <Parity ON="false" NumBits="0"/>
</BitLane>
<BitLane MemType="RAMB32" Placement="X8Y3">
  <DataWidth MSB="7" LSB="4"/>
  <AddressRange Begin="0" End="8191"/>
  <Parity ON="false" NumBits="0"/>
</BitLane>
```

After:
```xml
```xml
<BitLane MemType="RAMB32" Placement="X8Y3">
  <DataWidth MSB="3" LSB="0"/>
  <AddressRange Begin="0" End="8191"/>
  <Parity ON="false" NumBits="0"/>
</BitLane>
<BitLane MemType="RAMB32" Placement="X8Y2">
  <DataWidth MSB="7" LSB="4"/>
  <AddressRange Begin="0" End="8191"/>
  <Parity ON="false" NumBits="0"/>
</BitLane>
```

I suspect there are some changes required here: hw/top_earlgrey/util/vivado_hook_write_bitstream_pre.tcl

**Comment by msfschaffner** [comment]
@moidx can this one be closed, or is there more work needed?

**Comment by moidx** [comment]
This is now fixed.
