### ISSUE TITLE
[ CI ] Differences in Azure top files from locally generated files, even when using latest python packages

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#8721]
We are having a doozy of a CI troubles:
https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=55307&view=results

In this PR the system says that I have not been updating all the files properly.  It says I need to run `make -C hw top` (which I’ve done and committed everything).

I updated my python packages (as of 2021-10-16), and run  `make -C hw top` again.
I even tried running `./ci/scripts/check-generated.sh` several times.  
It found a lot of other changes (all software-related, but unrelated to top).
 I dutifully checked in and pushed all the recommended changes.

However even after all this, my local run of this script says I’m not up to date with the autogenerated files.

Any idea what is going on here?  Am I doing something wrong or is CI broken?  Please let me know if you can help.  I have another PR that is stalling because of this as well.

For the record we are using python 3.6.6

**Comment by martin-lueker** [comment]
@rasmus-madsen is having troubles with this in #8667.
My original PR was #8709

**Comment by timothytrippel** [comment]
@martin-lueker After looking at your PR it looks like there are three files/sets-of-files that are causing CI problems for you (all are related to the clang-format issue @imphil pointed out above):
1. `hw/ip/prim/dv/prim_secded/secded_enc.c`
2. the autogenerated IRQ chip-level test: `sw/device/tests/autogen/plic_all_irqs_test.c`
3. all of the autogenerated DIF unit tests: `sw/device/lib/dif/autogen/*_autogen_unittest.cc` 

The way to fix all of these such that they pass lint checks in CI is to:
1. ensure you machine has the right version of clang-format: see #8604 (as @imphil  mentioned aboved); or invoke the following two commands in the docker container (see [`util/container`](https://github.com/lowRISC/opentitan/tree/master/util/container) for how to build and launch,
2. run `make -C hw` on a machine with the right version of clang-format (#8604) or in the docker container
3. run `util/make_new_dif.py --mode=batch --only=autogen` on a machine with the right version of clang-format (#8604) or in the docker container

Let me know if you are still having problems!

------------------------------------------------------------------------------------------------

@imphil As for _not_ running clang-format as part of `make -C hw` and `util/make_new_dif.py` that _would_ solve the problem, but at a cost. Specifically, it is difficult to enforce formatting on  C/C++ Mako templates, that when rendered, produce C/C++ code that passes lint checks (i.e. running the autogenerated files through clang-format produces identical files as what was input). Hence, formatting the rendered files with clang-format as part of the autogeneration was the path chosen. (If you know of a mako template linter though I would be all ears!) As long as we are checking-in autogenerated C/C++ code this will be an issue. 

If we (through migrating to the Bazel build system) decided to autogenerate C/C++ code on the fly during each build, and not check these files into our repo, this would also solve the problem, but at a cost of not being able to search our code base as easily (i.e., reduced code visibility).

To me, requiring contributors to use a specific version of clang-format (especially if we keep this dependency updated, and provide a Dockerfile with the right system setup) seems like a good compromise to this issue, but perhaps this warrants a deeper discussion.

**Comment by msfschaffner** [comment]
@timothytrippel can this issue be closed?
