### ISSUE TITLE
[opentitantool] Add support for configuration files

### ISSUE THREAD

**Issue by jesultra** [lowRISC/opentitan#8769]
This issues tracks the implementation of feature of "Symbolic names for pins and ports" as discussed in [this brainstorming document](https://docs.google.com/document/d/1jEutTFPiE4HWxWMfTU4szy8ronS7nC_PPJOa5xOMWPg/edit?pli=1#heading=h.p6v6).

**Comment by msfschaffner** [comment]
CC @arunthomas

**Comment by jesultra** [comment]
This has been done a long time ago.
