### ISSUE TITLE
[doc] `hwcfg` should not show the table header if no input/output exists in a IP

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#878]
Problem:

    If IP only has TL-UL port, `hwcfg` shows table header only.

As seen in [HMAC doc](https://docs.opentitan.org/hw/ip/hmac/doc/#hardware-interface) (could be changed after this issue is fixed), _Peripheral Pins for Chip IO_ section shows no entry but only shows the table header.

Suggestion:

    Replace the table to _none_ if  `available_input/output/inout_list` are empty list.

QQ: How we can handle this in case of inter-module connection such as [flashctrl](https://docs.opentitan.org/hw/ip/flash_ctrl/doc/#hardware-interfaces)

**Comment by sjgitty** [comment]
This appears to be fixed. I experimented with no chip pins and it now says `none`
