### ISSUE TITLE
Is there any demo code for PWM and what's the base address of it ?

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#8796]
Hi 
Is there any demo code for the pwm in Earl Grey?

and, I can't find the base address of pwm in the link below.
https://docs.opentitan.org/hw/top_earlgrey/doc/

Could you please provide me this information? 
Thanks a lot.

**Comment by imphil** [comment]
There's neither a driver nor demo code at the moment for PWM. 

You can find the base address of all modules e.g. in hw/top_earlgrey/sw/autogen/top_earlgrey.h:

```
#define TOP_EARLGREY_PWM_AON_BASE_ADDR 0x40450000u
```

**Comment by tjaychen** [comment]
@martin-lueker 
do you guys have any dv code that could be used as a reference?

**Comment by martin-lueker** [comment]
Hi @tjaychen, @nicolast0604,
  It's all SystemVerilog right now, there no any c-examples yet.

**Comment by tjaychen** [comment]
i think that would be helpful too

**Comment by andreaskurth** [comment]
PWM now has a [DIF](https://github.com/lowRISC/opentitan/blob/87dfa897f16f80f0a79c6b9f2df461c8115561a1/sw/device/lib/dif/dif_pwm.c) and there are Earlgrey top-level tests using PWM, e.g., [`sleep_pwm_pulses_test.c`](https://github.com/lowRISC/opentitan/blob/87dfa897f16f80f0a79c6b9f2df461c8115561a1/sw/device/tests/sleep_pwm_pulses_test.c). That could serve as demo code (although it's test code, so it does not necessarily follow best principles for using PWM).

I'm thus closing this issue. If anyone has objections, please re-open it.
