### ISSUE TITLE
I2C in nexys video pinmux and xdc

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#8797]
Hi I am very confused about the xdc and pinmux table, is there anything wrong ? It seems having discrepancy.
Or, any one who can help me understanding it.
Great thanks.

<html>
<body>

i2c0_sda | muxed | - | kTopEarlgreyPinmuxOutselI2c0Sda / kTopEarlgreyPinmuxPeripheralInI2c0Sda |  
-- | -- | -- | -- | --
i2c0_scl | muxed | - | kTopEarlgreyPinmuxOutselI2c0Scl / kTopEarlgreyPinmuxPeripheralInI2c0Scl |  
i2c1_sda | muxed | - | kTopEarlgreyPinmuxOutselI2c1Sda / kTopEarlgreyPinmuxPeripheralInI2c1Sda |  
i2c1_scl | muxed | - | kTopEarlgreyPinmuxOutselI2c1Scl / kTopEarlgreyPinmuxPeripheralInI2c1Scl |  
i2c2_sda | muxed | - | kTopEarlgreyPinmuxOutselI2c2Sda / kTopEarlgreyPinmuxPeripheralInI2c2Sda |  
i2c2_scl | muxed | - | kTopEarlgreyPinmuxOutselI2c2Scl / kTopEarlgreyPinmuxPeripheralInI2c2Scl

</body>
</html>

## I2C
#set_property -dict { PACKAGE_PIN W5    IOSTANDARD LVCMOS33 } [get_ports { scl }]; #IO_L15N_T2_DQS_34 Sch=scl
#set_property -dict { PACKAGE_PIN V5    IOSTANDARD LVCMOS33 } [get_ports { sda }]; #IO_L16N_T2_34 Sch=sda

**Comment by vogelpi** [comment]
Hi @nicolast0604 ,
is this still an issue?

Regarding the configuration of the pinmux for I2C, I recommend having a look at `pinmux_init()` in `sw/device/lib/pinmux.c`. This function configures the pinmux for the GPIOs as well as UART0 and UART1. This should help you to do the same for I2C.
