### ISSUE TITLE
[sw/rom_ext] Implement ePMP initialization for ROM_EXT stage

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#8800]
Implement ePMP initialization for the ROM_EXT stage.

**Comment by engdoreis** [comment]
I think this issue has been addressed by the PR https://github.com/lowRISC/opentitan/pull/14855 (issue https://github.com/lowRISC/opentitan/issues/13507).

- The ePMP is initialized by the ROM which creates a copy in memory.
- ROM_EXT checks the ePMP configuration against the copy in memory.
- ROM_EXT enables the next stage to execute and updates the memory copy.

@moidx is this enough?

**Comment by johngt** [comment]
@moidx - @engdoreis has worked on this and has asked if this is sufficient or if there is anything missing. If not then we can close the issue. Thanks in advance!

**Comment by engdoreis** [comment]
@alphan do you think we can close this issue?

**Comment by engdoreis** [comment]
I think the issue can be closed as completed, if anyone disagrees we can reopen it later.
