### ISSUE TITLE
[sw] cleanup pwrmgr_usbdev_smoketest

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8811]
See [this link](https://github.com/lowRISC/opentitan/pull/8789#issuecomment-948097235) for more details.

**Comment by tjaychen** [comment]
@matutem 
@sriyerg 
FYI

**Comment by andreaskurth** [comment]
Triaged for `pwrmgr`, suggesting https://github.com/lowRISC/opentitan/labels/Type%3AIcebox as it's a cleanup and not necessary for M2.5.

**Comment by GregAC** [comment]
Triaged for `usbdev`, agree with @andreaskurth

**Comment by matutem** [comment]
This has no owner: assigning to @timothytrippel for him to delegate if that makes sense.

**Comment by matutem** [comment]
As far as I can see, this really refers to the usb wakeup. There are existing tests for this at both unit and top-level. See //sw/device/tests:pwrmgr_random_sleep_all_wake_ups for example.Closing it.
