### ISSUE TITLE
[dv, clkmgr] update to support latest external clock switch scheme

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8813]
#8791 updates the external clock support scheme. 
The current `clkmgr` DV does not fully support this since there is only a single `ast_clk_byp_req/ack`.
This is now split into `all/io_clk_byp_req/ack`, so corresponding dv updates will be needed.

**Comment by matutem** [comment]
Fixed in https://github.com/lowRISC/opentitan/pull/9413.
