### ISSUE TITLE
spi_device CSR test fails for seed

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#8832]
spi_device_csr_mem_rw_with_rand_reset -
fails on master and is blocking PRs

it also fails local runs with seed  2257198085
using xcelium (CI uses vcs)

could you look into this ASAP as it is blocking my PR

**Comment by msfschaffner** [comment]
Does this error still persist or can we close the issue?

**Comment by eunchan** [comment]
Let me close this issue. If this happens, open this up again and let me know.
