### ISSUE TITLE
[mask_rom] Consider skipping SRAM scrambling if AST is not configured

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#8858]
If AST configuration is skipped (which may happen if the configuration has not yet been written to OTP) then we may want to have a mechanism to skip SRAM scrambling in order to avoid the key request stalling forever while it waits for entropy.

**Comment by zi-v** [comment]
> I feel like if the values were incorrect / invalid..then all bets would be off. I understood what @zi-v meant to be if we do "nothing", the entropy should still be good enough to enable entropy complex and scrambling.
> 
> Ziv can you confirm?

Confirmed

**Comment by alphan** [comment]
Closing this issue based on @zi-v and @tjaychen's comments: We can skip AST init based on the value of the OTP entry and even if we skip it SRAM scrambling is expected to work.

**Comment by zi-v** [comment]
Just double confirming that you don't scramble the retention SRAM by ROM code with a per boot key.
