### ISSUE TITLE
Try Vivado 2019.1

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#89]
Vivado 2019.1 is out and the [release notes](https://www.xilinx.com/products/design-tools/vivado/vivado-whats-new.html) seem pretty promising.

- They now have a command line web installer, so we can simplify our installation instructions from GUI screenshots to a single line.
-  "Disk usage optimization enabled to reduce install footprint of Vivado tool" We can update our install instructions with that. (Most likely they found out that they can use symlinks instead of having independent copies of lib.so.0.1 lib.so.0 lib.so ...) 
- "Incremental Synthesis now available, with optional auto-incremental mode for Vivado projects." I wonder what that is, it should help us if we include ILAs.

**Comment by rajesh-s** [comment]
Has this issue (with 2019.1) been reproduced on 2019.2 (released recently) as well? Was just getting started and from the docs page it wasn't clear if I can start with the most recent version

**Comment by towoe** [comment]
@rajesh-s, thanks for bringing this up. 2019.2 has not been tested by us. We recommend to use 2018.3. But if you want to test 2019.2 we would be happy get feedback on that.

**Comment by mdhayter** [comment]
I did one successful build over the weekend with 2019.2 (because the Xilinx installer was unable to download 2018.3). But from the hit-and-miss with 2019.1 that probably isn't enough to tell.

**Comment by rajesh-s** [comment]
@mdhayter I'm new to this project. Just started reading the docs yesterday. What FPGA board are you using?

**Comment by imphil** [comment]
He used the Nexys Video board
