### ISSUE TITLE
[kmac] Security hardening

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8982]
- [x] Sparsely encode critical kmac fsms - this may already be complete
- [x] Add shadow registers to critical kmac configuration : (WIP) #7439 
- [x] Replace critical counters with prim_count (for example key count / slicer index count)
- [x] Hook-up detected local faults (fsm in bad state, integrity error, shadow storage error, count consistency error) to local error escalation and alert output. Also connect external escalation request for similar response. 
- [x] One point that was brought up during the AES review is that during escalation, we should suppress the output capture.  As this may prevent a lot of analysis an attacker can do.

**Comment by eunchan** [comment]
Thanks for summarizing the pending items Tim. I will get back to this after SPI_DEVICE D2 stage :)

**Comment by m-temp** [comment]
As discussed with @moidx I will start looking into this and will soon file a [WIP] PR

**Comment by m-temp** [comment]
@tjaychen, @eunchan Most of the points should be covered by now.
Only the external escalation request hasn't been implemented yet.
... and the documentation.

**Comment by tjaychen** [comment]
thank you @m-temp

**Comment by tjaychen** [comment]
@eunchan @m-temp i just added one more item based on feedback from the Aes review (@vogelpi @cdgori )
This might already be done, but I think it would be good to double check.

**Comment by m-temp** [comment]
#9583 adds the lc_ctrl_escalate_en input and a first draft for a local escalation.

@tjaychen What do you exactly mean with "suppress the output capture"? Set a random/all-zero digest and bring all output ports of the FSM/KMAC in a defined and secure state?

What also could be discussed in this issue: Do we need key wiping for `sw_key_data`?

**Comment by tjaychen** [comment]
so aes has a mechanism where basically if a fault is detected, it does not populate the output registers with results. Because those results could be used as a kind of attack vector.  So either we don't allow the `de` to be set, or we can simply populate with random data, both would work. 

The `sw_key_data` is the software supplied key correct?  Since that is `wo`, there is no way already for software to read it out.  If on escalation or fault we also disallow `kmac` from doing anything further (or do anything with the real key), I don't think we need to wipe.

**Comment by m-temp** [comment]
> so aes has a mechanism where basically if a fault is detected, it does not populate the output registers with results. Because those results could be used as a kind of attack vector. So either we don't allow the `de` to be set, or we can simply populate with random data, both would work.

yeah, that makes sense. I'll have look on that.


> The `sw_key_data` is the software supplied key correct? Since that is `wo`, there is no way already for software to read it out. If on escalation or fault we also disallow `kmac` from doing anything further (or do anything with the real key), I don't think we need to wipe.

Yes, it's `wo` but internally latched. As long as we make sure that in `kmac` does not combine the shares in the event of a fault or messes around otherwise, we are fine.

I'll address both points in a separate PR that drives `kmac` in a secure state in the event of a fault / escalation.

**Comment by tjaychen** [comment]
thank you! btw, if it's super simple for you to clear, don't feel like you HAVE to skip it.
I assume clearing is still better than not clearing.

**Comment by tjaychen** [comment]
@m-temp would you mind checking off the boxes above if they're already done? I feel like they have already been handled.

**Comment by tjaychen** [comment]
@m-temp i actually just noticed that in kmac, when escalated the `mux_sel` is always `SelNone`. So this protection I'm talking about is in fact partially there. I think like you said, we need to actually make use of the valid.. and maybe it would be a good idea to make the app selection wider as well. 

@msfschaffner has a PR in life cycle control where the mux selection is more manipulated based on the duplication of the select signal.  We could consider utilizing that here as well.

**Comment by msfschaffner** [comment]
For reference, this is the PR that @tjaychen mentioned: https://github.com/lowRISC/opentitan/pull/10496

**Comment by m-temp** [comment]
@tjaychen @msfschaffner I see. Could you habe a look at #10744?
- I used a sparse encoding, so if there's a missmatch the `mux_sel` is not set to `SelSw` and `reg_state_o = '{default:'0}`
- `mux_sel` and `reg_state_valid_o` are buffered now
- and if `reg_state_valid_o` is zero, the TL input is not `reg_state_o`  but zero.

**Comment by m-temp** [comment]
@tjaychen I think we can close this, as we move to D2S, can we?
