### ISSUE TITLE
[all] Add prim mechanism to protect sensitive global constants in the design

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8983]
This primarily applies to

- [x] ~otp~
- [x] keymgr - in progress
- [x] lc_ctrl - state values?
- [x] optionally, also applies to default scramble keys - in progress
- [x] optionally, also applies to lfsr permutations / default seeds

**Comment by msfschaffner** [comment]
@tjaychen do we want to follow through with this enhancement, or postpone it?

**Comment by tjaychen** [comment]
i can't completely remember what i had in mind now...but i think i was really going to just use secure anchor buffers so that they can be identified and thus buried. What do you think?

**Comment by msfschaffner** [comment]
Indeed, I think we settled on burying these nets.
There was this other idea with muxes that I believe we have abandoned (for now).
