### ISSUE TITLE
[otbn] Implement internal secure wipe - non RTL work

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#8989]
Implement the non RTL parts of internal secure wipe

> estimate 8
> remaining 2021-11-15 8
> remaining 2021-11-29 8

**Comment by GregAC** [comment]
Draft PR is available: #9400

**Comment by rswarbrick** [comment]
This is done now. It's not enabled by default because it triggers some test failures that seem to be an RTL bug.

**Comment by GregAC** [comment]
Do we have an issue open for that RTL bug?

**Comment by rswarbrick** [comment]
Hmm, probably not. I'll re-create it and open a specific issue later today and then close this one.

**Comment by GregAC** [comment]
Closing as the work this tracks is complete. More specific issues can be opened around bugs and any bring-up required.
