### ISSUE TITLE
[sw] Reproducible sw/device builds with hermetic toolchain

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#899]
Add a mechanism to vendor-in toolchain binaries in order to support reproducible builds from a developer and CI perspective. 

The hermetic build requirement should also be evaluated with Meson. 

As a follow up task, we should also evaluate host software dependencies to determine how to support reproducible builds for host targets.

**Comment by mcy** [comment]
Assigning to myself, since I'm the one who works in this space the most right now.

This is more-or-less blocked on Meson-everywhere.

**Comment by moidx** [comment]
> Assigning to myself, since I'm the one who works in this space the most right now.
> 
> This is more-or-less blocked on Meson-everywhere.

Can you add the list of blocking issues? We can file bugs to Meson in case there are missing features: https://mesonbuild.com/Reproducible-builds.html; or this issue could be referenced when considering alternative build systems.

Regardless of the build system though, having the ability to configure the toolchain as part of the build configuration is something that is pretty standard in terms of reproducibility.

**Comment by mcy** [comment]
It's less of issues with Meson itself, and more like unresolved questions about how we should organize our build artifacts long-term. I'm mostly nervous about trying to make big decisions on our hermeticity story before we've got a good story for how artifacts are generated. Vendoring in toolchain stuff is almost certainly a nonissue though.

Mind, I could be completely wrong; this is just a preemptive "hmm maybe we should be careful about making commitments".

**Comment by asb** [comment]
I full agree with the goal of hermetic builds, though I'm not keen on the proposed approach of checking in binaries.

I think we can meet the hermetic build requirement without vendoring in binaries to our repo. Just as we have now, referring to a particular prebuilt toolchain tarball is surely sufficient? If there is concern in ensuring that artifact is always available, we can explore further backup options for the toolchain releases, e.g. syncing them elsewhere. Downstream users who really want everything in one repo can also do this in an automated way.

Or am I misunderstanding the proposal?

**Comment by msfschaffner** [comment]
CC @cfrantz since he's looking into improvements for our current SW build system.

**Comment by moidx** [comment]
CC @drewmacrae as well.
