### ISSUE TITLE
Ensure docs have appropriate license headers / info

### ISSUE THREAD

**Issue by asb** [lowRISC/opentitan#9]
We expect we will prefer our docs to by CC-BY licensed, but this isn't reflected in doc license headers etc.

I need to confer with the legal committee before this issue becomes actionable.

**Comment by msfschaffner** [comment]
On a mission to close down old issues: @asb, @imphil has there been an update regarding the licensing issue?

**Comment by msfschaffner** [comment]
@mundaym do we still have to track this?
