### ISSUE TITLE
[clkmgr, dv] DV updates

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9012]
Due to recent `clkmgr` changes in #8791 and #9001, there are a couple of dv updates required

1. Since jitter enable has switched to a `mubi` value, it is now necessary to test to non-true / non-false values to ensure behavior is correct
2. External clock switch is now split between io_clk_byp_req and all_clk_byp_req variants, both would have to be tested.

**Comment by matutem** [comment]
The external clock changes were incorporated in the clkmgr_extclk some weeks ago in https://github.com/lowRISC/opentitan/pull/9413.

I am changing the clkmgr_smoke test to account for jitter_enable mubi type.

**Comment by tjaychen** [comment]
thanks @matutem

**Comment by msfschaffner** [comment]
@matutem has this issue been addressed?

**Comment by matutem** [comment]
This is all done.
