### ISSUE TITLE
Move GlobalMock to a more universal location

### ISSUE THREAD

**Issue by cfrantz** [lowRISC/opentitan#9027]
Currently, `GlobalMock<T>` exists under sw/device/silicon_creator, however it is a useful class for testing in other parts of the codebase.

Move/refactor GlobalMock into a more universal location.

**Comment by msfschaffner** [comment]
+ @timothytrippel Anything left to do here?

**Comment by timothytrippel** [comment]
Looks like it is sw/device/lib/base/ now.
