### ISSUE TITLE
Extend `multibits.h` with conversion functions

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#9036]
Should we inline this in `dif_base.h`? Other blocks will likely need this conversion too.

_Originally posted by @sriyerg in https://github.com/lowRISC/opentitan/pull/9034#discussion_r742348151_

**Comment by msfschaffner** [comment]
How about we replicate the `mubi?_test_(true|false)_(strict|loose)` functions in `multibits.h`, similar to what we do in RTL?

_Originally posted by @msfschaffner in https://github.com/lowRISC/opentitan/pull/9034#discussion_r742350339_

**Comment by timothytrippel** [comment]
Yeah I think this makes sense to add to DIF base. Actually ether are also some `toggle_to_bool()` and `bool_to_toggle()` private functions floating around across many of the DIF libs.

**Comment by timothytrippel** [comment]
Task Burndown:

- [ ] add `bool_to_toggle()` and `toggle_to_bool()` functions to `dif_base` lib
- [ ] add `multibit_bool_{4,8,12,16}_to_toggle()`and `toggle_to_multibit_bool_{4,8,12,16}()` functions to `dif_base` lib
- [ ] deprecate DIF lib specific implementations of above and integrate the base versions across all IP DIF libs

**Comment by sriyerg** [comment]
Sounds great!
