### ISSUE TITLE
[prim] Enhance sparse fsm script for DV compatability

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9043]
- create another primitive that wraps the prim_flop that can be used by DV to anchor
  - an input that indicates the state is "invalid"
  - this needs to be added by the designer

- Assertion at the ip top level has 
  - hierarchical path to this prim module
  - associated alert

**Comment by sriyerg** [comment]
Few more notes: The signal indicating the FSM is in valid state can be hidden behind a macro. This will expose an unused signal `valid_state`. 

The sparse FSM script will, in addition to generating the FSM state enum, dump the line below that the designer can stick into the module implementing the FSM. 
```systemverilog
  logic unused_valid_state;
  `PRIM_SPARSE_FSM_IS_IN_VALID_STATE(state_e, state_q, unused_valid_state)
```

This macro will be defined in `prim_sparse_fsm` module (or separate file in the same fusesoc core) and will look something like this:
```systemverilog
`define PRIM_SPARSE_FSM_IS_IN_VALID_STATE(_state_e, _state_q, _valid_state) \ 
  `ifdef INC_ASSERT \
    _state_e tmp; \
    assign _valid_state = $cast(tmp, _state_q); \
  `else \
    assign _valid_state = 1'b0; \
  `endif
```

The `valid_state` need not be an input to `prim_sparse_fsm` instance. The IP top level assertion (macro) needs the hierarchical path to the module implementing the FSM, not the hierarchical path to `prim_sparse_fsm` instance.

**Comment by weicaiyang** [comment]
> The unused_valid_state need not be an input to prim_sparse_fsm instance.

Good point. Internal signal also works and we can fully isolate it from synthesis.

seems like macro is not needed either, since it's only used once in prim_sparse_fsm. 


> The IP top level assertion (macro) needs the hierarchical path to the module implementing the FSM, not the hierarchical path to prim_sparse_fsm instance.

we need to know the name of the prim_sparse_fsm instance too, right? It could be any arbitrary name.

**Comment by tjaychen** [comment]
yeah echoing @weicaiyang 's question, don't we still need a prim module that takes the valid_state signal as an input?

**Comment by weicaiyang** [comment]
> yeah echoing @weicaiyang 's question, don't we still need a prim module that takes the valid_state signal as an input?

@tjaychen In order to write the alert assertion, I think we still need a valid_state signal, but it can be an internal signal, which is easier to be isolated by INC_ASSERT.

**Comment by msfschaffner** [comment]
Looks like this issue has been addressed - can we close it?

**Comment by tjaychen** [comment]
yep! let us close.
