### ISSUE TITLE
[sw/silicon_creator] boot_data copies during write operations

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#9056]
Given that `boot_data` is a complex type, this looks like an implicit copy operation. Since `boot_data_entry_write` copies the data into a buffer, I wonder if we should create an `union` type (ignoring endianness concerns).

_Originally posted by @moidx in https://github.com/lowRISC/opentitan/pull/9015#discussion_r742411456_

**Comment by moidx** [comment]
Hi @alphan, should we close this issue? I don't think we are going to perform this optimization in the mask ROM?

**Comment by alphan** [comment]
I think so. I'm also not sure if the write performance is that critical, since we expect it to happen much less frequently than reads.
