### ISSUE TITLE
[ast,pwrmgr] Strange glitch in usb clock

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#9064]
This is a strange issue, and may not be a problem at all, but it is weird enough we should consider it.

Imagine a low power transition when the usb clock was disabled in active mode, but is configured on when in low power. Yes, this is bizarre. On top of that, imagine we set main_pd_n to 0. So main power is off, yet we have the clocks configured on and main power off during low power.

Well, in this strange situation, the AST will actually turn the clocks off as it does to low power, regardless the pwrmgr's intentions. But the clocks go off after power clamping. Not sure it this mixes well with retention and all the low power circuitry.

To make things even more goofy, the USB clock briefly turns on before going off... remember it was configured to to turn on when the low power transition happens.

Here are some waves:
![Screenshot from 2021-11-04 20-59-40](https://user-images.githubusercontent.com/80294896/140457613-55283996-bff4-4769-ba6d-78dffc524490.png)

**Comment by tjaychen** [comment]
yeah this is indeed kind of odd. i wonder if it would be better if we just removed the lp / active indication for usb, and just leave one of them. Then we leave the control unambiguously in software's hand all the time. 

Ie, if software wishes to have usb clock active for some reason, they will simply just leave it on all the time.

**Comment by matutem** [comment]
Hmm, my concern is that we are saying any of the clocks should remain active when main_pd_n is low, yet we end up turning the clock off anyway. In fact, I think the control reg spec may say when main_pd_n is low all clocks will be turned off regardless of their config bit.

I looked more closely at the waves in full chip: when pwrmgr sets main_pd_n low the AST treats it as a main power glitch, and sends a rst_main_n to pwrmgr, and ast also turns all clocks off at the same time. But this time is much later than the slow fsm's SlowPwrStateClocksOff, so it is "suspicious". If main_pd_n is active low there is no reason for the clocks to continue to run, so just turning them all off seems to be the cleanest way to deal.

**Comment by tjaychen** [comment]
o fair point. So you're trying to say is when we turn off power, just turn off the oscillator clocks too always right?

**Comment by matutem** [comment]
I think this misses the case of non-deep sleep low power. If main_pd_n remains high then each of the clk_en bits in control just control the clock, and we can independently choose which clocks remain active. It seems what you propose simply removes this clock gating functionality, even if only for usb. Why?

**Comment by matutem** [comment]
And I also think the weird extra activity of the usb clock before power is shut off would go away if we turned clocks off in the correct slow fsm state, which my proposed fix should end up doing.

**Comment by tjaychen** [comment]
> I think this misses the case of non-deep sleep low power. If main_pd_n remains high then each of the clk_en bits in control just control the clock, and we can independently choose which clocks remain active. It seems what you propose simply removes this clock gating functionality, even if only for usb. Why?

no actually what i intended is what you're describing. In "low power", ie real deep sleep, just kill the enables, because as you say, there's no point in keeping them up.  When we are in non-low-power deep sleep (ie, normal sleep), we do not force USB to a particular value, instead just allow it to remain under software control.  So in this world, we only need 1 bit, whose value is ignored when we are in deep sleep.

**Comment by matutem** [comment]
If I understand correctly, the usb_clk_en bit would behave differently from the main and io_clk_en: the latter are ignored in active power, but you propose usb_clk_en would not? We would need to explicitly update the usb_clk_en prior to entering shallow low power for active-enable switching to shallow_sleep-disable, and conversely we would need to update it upon wakeup to have shallow_deep-disable to active-enable.

I think the current scheme with two bits for usb is simpler. But I definitely agree whenever we enter deep sleep (main_pd_n == 0) we should turn all three clocks off regardless of their control enables.

**Comment by tjaychen** [comment]
Yes what you're saying is right, that's what I had in mind. 
Mostly I think this is simpler because I wanted to make it "deep sleep" vs all other cases.

**Comment by tjaychen** [comment]
o wait i see what you mean. 
yeah let's go with what you're suggesting then. Low power usb control for lighter sleep, active control for active region, and then when in deep sleep a more defined behavior.
