### ISSUE TITLE
PINMUX_REGEN redefinition warning in generated pinmux_regs.h

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#907]
Filing issue for this warning msg thrown:

In file included from opentitan/sw/device/../../sw/device/lib/pinmux.h:10,
                 from examples/hello_world/hello_world.c:7:
sw/device/../../build/sw/device/examples/hello_world/lib/pinmux_regs.h:15: warning: "PINMUX_REGEN" redefined
 #define PINMUX_REGEN 0
 
sw/device/../../build/sw/device/examples/hello_world/lib/pinmux_regs.h:14: note: this is the location of the previous definition
 #define PINMUX_REGEN(id) (PINMUX##id##_BASE_ADDR + 0x0)

**Comment by eunchan** [comment]
. I thought I changed pinmux regen register field name as 'wen'. Hum... don't know why it is not visible to you.

Could you please check if you have latest `sw/device/rules.mk` file?

**Comment by sriyerg** [comment]
Aah apologies, I made a mistake. Closing this.
