### ISSUE TITLE
[sw/silicon_creator] Is the RSA modulus definitely > R / 2?

### ISSUE THREAD

**Issue by jadephilipoom** [lowRISC/opentitan#9072]
The Ibex implementation of `sigverify` assumes that the RSA modulus (public key) is between R / 2 and R (R=2^3072); that is, the highest bit of the 3072-bit number must be set:
https://github.com/lowRISC/opentitan/blob/3d156ce35e0ba559b5246c96286c0568cfa559c0/sw/device/silicon_creator/lib/sigverify_mod_exp_ibex.c#L78-L80

However, I'm having trouble finding a reference that guarantees this is _definitely_ always the case.  When I generate keys using various RSA tools they're always large enough, and "3072-bit modulus" definitely implies the high bit is set, but I think being extra-paranoid makes sense in this context. We can do one of three things here:
1. Find a reference that says this is always true and add it to that comment
2. Document that we require moduli to fit this requirement, and check the modulus before verifying
3. Change this single modular subtraction to a while loop (since this routine doesn't have to be constant-time)

The OTBN implementation of computing R^2 will be significantly simpler if we can rely on the modulus being larger than 2^3071.

CC @alphan @felixmiller

**Comment by felixmiller** [comment]
To my knowledge this assumption is correct. A reference is [FIPS 186-4](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf) (p. 53 very top) which states that both p and q have to be equal or greater than `sqrt(2)*2^(nlen/2-1)`, where `nlen `is the targeted key length (here `nlen=3072`). Hence, `p*q >= 2^(nlen-1) = 2^3071`

**Comment by jadephilipoom** [comment]
Perfect, thanks for finding the reference! I'll go ahead and add that note to the comment, and do the same for the OTBN code.
