### ISSUE TITLE
[sw/silicon_creator] Possible speedup for Ibex Montgomery modexp

### ISSUE THREAD

**Issue by jadephilipoom** [lowRISC/opentitan#9073]
Because the Ibex Montgomery implementation computes the constant R^2 on-the-fly rather than storing it, it's possible to save ~1 montgomery multiplication for each verification by transforming the signature to Montgomery form in a different way. Essentially, instead of computing:
```
rr = (R * R) mod M      // R = 2^3072; computed with 3072 modular doublings
sigR = montmul(sig, RR) // = (sig * R) mod M
```
...we can simply do:
```
sigR = (sig * R) mod M  // computed with 3072 modular doublings
```

Normally this wouldn't make sense because you'd compute R^2 once and then use it for many signature verifications, but if we're computing R^2 every time anyway it's very slightly faster. I did some back-of-the-envelope benchmarks by setting the `sigverify_mod_exp_ibex_unittest.c` test to loop 1000 times for each test (for more significant digits). I got ~2750ms for the current version and ~2660ms for the alternative multiply-by-R transform. It's probably not worth diverging from the OTBN implementation and the literature for such a small speedup unless we really need the extra few percentage points of performance, but I thought it might be useful to note it here in case we do find at some point that we need them.

CC @alphan

**Comment by moidx** [comment]
Hi @jadephilipoom, is this still under consideration?

**Comment by jadephilipoom** [comment]
Happy to close it. I think the original analysis holds -- it's very slightly faster but probably not worth it from a code-readability perspective to have such a nonstandard setup that also diverges from the OTBN implementation. I just left the issue in case we were looking for Ibex sigverify speedups someday, but it seems we haven't needed them!

**Comment by jadephilipoom** [comment]
Happy to close it. I think the original analysis holds -- it's very slightly faster but probably not worth it from a code-readability perspective to have such a nonstandard setup that also diverges from the OTBN implementation. I just left the issue in case we were looking for Ibex sigverify speedups someday, but it seems we haven't needed them!
