### ISSUE TITLE
IP Criteria to be included in the top

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#91]
To continue the discussion from the HMAC testplan meeting, I would like to get the feedback what should be the criteria for top module.

I think below three condition should be okay:

1. RTL milestone: D1
2. DV milestone: V1
3. ip.hjson exists and comportable to the spec. (topgen can generate it)

_(Optional)_ software driver

[Mileston doc](https://docs.google.com/document/d/16WDUDT-snBosoQTT1RHJQvYQ8iBOA9bm0givrNPuCQc/edit#bookmark=id.ve3udnqxagyn)

> @sjgitty 
> I don't feel this is finalized yet, and we certainly have designs that are not in V1 status that are successfully in earlgrey today (most notably: spi_device). I would argue strongly that there are reasons to have V0 blocks in earlgrey: it allows SW/FPGA to begin working on these before DV has ramped up (looking forward, if we continue at our current pace, DV will always lag behind.
> 
> I think we do need to come up with a definition, but I don't think it needs to be tied to a V #. For instance, it could be:
> 
> 1. D1
> 2. some sanity verification by designer or DVer proving basic functionality
> 3. some sanity top level test that shows that it doesn't bring down the chip
> 
> I'm just throwing this out there, needs to be more heavily discussed.
> 
> Converting tag to Recreate in OT

**Comment by tjaychen** [comment]
@msfschaffner do you want to take this topic through TC?
I think the conditions defined in the op post of this issue is actually quite reasonable. 
We probably just need to officially close on this.

**Comment by msfschaffner** [comment]
Hm... looks like this discussion is from the time when the definitions of D*/V* were still pretty much in flux.

Our D1 checklist now contains an item called [`IP_INSTANTIABLE`](https://docs.opentitan.org/doc/project/checklist/#ip_instantiable):
```
The unit is able to be instantiated and connected in top level RTL files. The design must compile and elaborate cleanly without errors. The unit must not break top level functionality such as propagating X through TL-UL interfaces, continuously asserting alerts or interrupts, or creating undesired TL-UL transactions.
```

Given that this is a D1 item, requiring V1 as well for inclusion in the top-level is going to be difficult.
However, it may make sense to add a sentence for the hjson part (point 3. from @eunchan's list).

I don't think this has to go through the TC just yet - we can discuss and try to close in the silicon WG meeting.

**Comment by tjaychen** [comment]
Actually maybe V1 isn't the right term... but I think all block levels have this basic stage that can be reached where we prove TL-UL accesses are operational.  I think really taht's the stage we want, so it's more like...V0 in a way. 

WG sounds good too, I think this is just something we can and should close out.

**Comment by msfschaffner** [comment]
Sounds good - I will put it on the agenda for the next meeting.

**Comment by tjaychen** [comment]
just documenting what i believe was agreed upon in the meeting:

1. we won't add another check point for "including in top"
2. there already is an IP_INSTANTIABLE item, and we will likely enhance the documentation for this item to include various other things, some of which are actually V1 items
3. the minimal requirement is likely the block needs to auto-generate the basic CSR testbench and ensure that CSR tests can pass before it can be integrated into the top.

@msfschaffner 
@sriyerg 
let me know if I got this wrong.

**Comment by msfschaffner** [comment]
Indeed, this looks accurate. I will push a PR with proposed doc changes soon so that we can discuss it in the TC also (the meeting today was cancelled due to Easter holidays in the EU, hence we will likely talk about this in 2 weeks from now).

**Comment by msfschaffner** [comment]
We've discussed this in the TC and updated the checklist accordingly.
