### ISSUE TITLE
Handle interrupt storms on the HW side

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#9106]
This is brought up by @tjaychen at #9077 

External host may be able to drive the pin to keep triggering interrupts, such as keep requesting data from spi device when TX fifo is empty, or keep toggling GPIO when edge triggered interrupt is enabled. This may cause SW get stuck at ISR.

SW can disable the interrupt when it's triggered. Or HW can trigger it once to avoid this interrupt storms.

@eunchan @sriyerg @timothytrippel

**Comment by eunchan** [comment]
Related issue #15282

**Comment by eunchan** [comment]
Conclusion is to keep notify via status and SW to decide to mask
