### ISSUE TITLE
[sw/silicon_creator] Group system-wide definitions in a central location

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#9126]
Since the info table is a canonical reference, would it make sense to move it into its own header? 

It seems like it would be nice to have all system canonical references in one place under the silicon_creator folder.

_Originally posted by @moidx in https://github.com/lowRISC/opentitan/pull/9096#pullrequestreview-800418204_

Other potential definitions to consider:
* manifest size and layout
* otp map
* retention ram layout

**Comment by msfschaffner** [comment]
Anything left to do here @moidx @TimEwins @cfrantz ?
