### ISSUE TITLE
[sw/boot_rom] Rename "boot_rom" to "test_rom"

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#9154]
The ROM code in `sw/device/boot_rom/` is used purely for testing purposes, and is not designed to be used as the OT mask ROM. The mask ROM code lives in `sw/device/silicon_creator/mask_rom`. To make this more clear, I think it would help if `sw/device/boot_rom` was renamed and relocated to `sw/device/lib/testing/test_rom`, or something similar.

Thoughts?

**Comment by sriyerg** [comment]
SGTM.

**Comment by tjaychen** [comment]
sounds good to me also.

**Comment by alphan** [comment]
SGTM

**Comment by arunthomas** [comment]
SGTM too. We can queue this up for the next Software WG meeting (if needed).
