### ISSUE TITLE
[entropy_src] counter wipe condition

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9159]
@mwbranstad i debugged #9088 a bit, and the problem appears to be [here](https://github.com/lowRISC/opentitan/pull/9088/files#diff-c6541233ab2eec45c8d6d2e9d7d4b1419a42fc947ee92c7fadb7feae7b9bf936R1195)

It looks like `es_enable` is not used to clear the counter, and this causes a counter value too large issue and one of the states just ends up waiting forever.

**Comment by mwbranstad** [comment]
ugh...thanks for debugging. @cdgori made a review comment that also caught this. After the change, CI does not fail on the two long tests, but now fails on a chip smoke test, even though the unit smoke runs ok.

**Comment by tjaychen** [comment]
can you update the PR? I'll pull it down again and have a look.

**Comment by mwbranstad** [comment]
i did already this morning, should be good to go.

**Comment by tjaychen** [comment]
this should already be resolved now. 
@mwbranstad let me know if you disagree and we can re-open.

**Comment by mwbranstad** [comment]
the issue is fixed as far as i know.
