### ISSUE TITLE
error: could not compile `anyhow` after ninja -C build-out all for most update version.

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#9165]
ninja -C build-out all
error: component download failed for rust-std-x86_64-unknown-linux-gnu: could not rename downloaded file from '/home/nicolast0604/.rustup/downloads/b01011cbb5503c456ecc6a557a38e099994b8497df545c661ce8fd48c5beadc6.partial' to '/home/nicolast0604/.rustup/downloads/b01011cbb5503c456ecc6a557a38e099994b8497df545c661ce8fd48c5beadc6'
error: could not compile `anyhow`

**Comment by tjaychen** [comment]
do you need to do a rust update?

**Comment by nicolast0604** [comment]
My rust is 1.56.1 and I saw the opentitan guide is 1.55.0

is it too new or too old?

By the way, I didn't have problem with the previous git repro.

**Comment by vogelpi** [comment]
I've never seen this problem. Does it still persist @nicolast0604 ? If not, can you please close the issue? Thanks!
