### ISSUE TITLE
Failed to resolve dependencies for lowrisc:systems:chip_earlgrey_cw310:0.1

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#9166]
:~/opentitan$ fusesoc --cores-root . run --flag=fileset_top --target=synth lowrisc:systems:chip_earlgrey_cw310
WARNING: Unknown item virtual in section Root
WARNING: Unknown item virtual in section Root
ERROR: Conflicting requirements:
Requirements: 'lowrisc_systems_chip_earlgrey_cw310 == 0.1-0' <- 'lowrisc_systems_top_earlgrey == 0.1-0' <- 'lowrisc_ip_lc_ctrl >= 0-0' <- 'lowrisc_ip_interfaces_alert_handler_reg >= 0-0'
    +lowrisc_ip_lc_ctrl-0.1-0 was ignored because it depends on missing packages
Requirements: 'lowrisc_systems_chip_earlgrey_cw310 == 0.1-0' <- 'lowrisc_systems_top_earlgrey == 0.1-0' <- 'lowrisc_ip_lc_ctrl >= 0-0'
    lowrisc_systems_top_earlgrey-0.1-0 requires (+lowrisc_ip_lc_ctrl-0.1-0)
Requirements: 'lowrisc_systems_chip_earlgrey_cw310 == 0.1-0' <- 'lowrisc_systems_top_earlgrey == 0.1-0'
    lowrisc_systems_chip_earlgrey_cw310-0.1-0 requires (+lowrisc_systems_top_earlgrey-0.1-0)
Requirements: 'lowrisc_systems_chip_earlgrey_cw310 == 0.1-0'
    Install command rule (+lowrisc_systems_chip_earlgrey_cw310-0.1-0)

Failed to resolve dependencies for lowrisc:systems:chip_earlgrey_cw310:0.1

**Comment by tjaychen** [comment]
this is very odd... if this were an actual issue, no one's CI would pass.
Can you make sure you're on head of tree and try again?

**Comment by rswarbrick** [comment]
Please also check that you have the right version of fusesoc. I think this might be using features that are only on the "ot" branch.

**Comment by tjaychen** [comment]
ahhh, yeah Rupert is probably right.
Did you go through the install instructions? That one should get the right
version of everything installed for you.

**Comment by nicolast0604** [comment]
my fusesoc version is 
1.11.dev57+g1fb8c93

**Comment by tjaychen** [comment]
as rupert mentioned, make sure you follow the instructions and get the ot
specific branch.
https://github.com/lowRISC/opentitan/blob/master/python-requirements.txt#L45

**Comment by nicolast0604** [comment]
Yes, after follow the suggestions it works.
