### ISSUE TITLE
[flash_ctrl] HWIP Technical Specification - Adding JTAG feature

### ISSUE THREAD

**Issue by nikola-miladinovic** [lowRISC/opentitan#9170]
Please add JTAG feature if it is used in Flash Controller. Currently only pins are mentioned.

**Comment by tjaychen** [comment]
the flash jtag feature will not be added.
This is part of the proprietary flash only, and will not be emulated as part of the open source modeling.

From verification perspective, only a connectivity test needs to be done to the boundary of the "prim_flash".
Actual verification of correct jtag behavior should be left to the proprietary simulations.

**Comment by tjaychen** [comment]
actually i should ask, what do you intend to verify if the jtag function is actually there?

**Comment by nikola-miladinovic** [comment]
> actually i should ask, what do you intend to verify if the jtag function is actually there?

@sriyerg : if there is no jtag mux inside design in order to support testing operations of controller or anything else, there is nothing to be tested. Therefore i close this issue.
