### ISSUE TITLE
[flash_ctrl] HWIP Technical Specification - Unclear Flash Protocol Controller Features

### ISSUE THREAD

**Issue by nikola-miladinovic** [lowRISC/opentitan#9171]
I assume following part of Flash Protocol Controller Features needs to be removed since there is no further explanation:
"Features to be added if required
Program verification
may not be required if flash memory supports alternative mechanisms of verification.
Erase verification
may not be required if flash memory supports alternative mechanisms of verification.
Flash redundant pages
Flash may contain additional pages used to remap broken pages for yield recovery.
The storage, loading and security of redundant pages may also be implemented in the physical controller or flash memory."

**Comment by tjaychen** [comment]
yes i will remove these.  These features are going to be directly contained within the flash shim itself and will not be exposed as part of the open source portion of the controller.

**Comment by nikola-miladinovic** [comment]
OK, closing issue.
