### ISSUE TITLE
CW310 board files

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#9173]
If I would like to work CW310 board with Vivado, shall I install the board files?
If yes, where can I get it?

**Comment by m-temp** [comment]
Dublicate of https://github.com/newaetech/cw310-bergen-board/issues/6

**Comment by nicolast0604** [comment]
Hi
My question is that I would like to let Vivado's hardware manager can recognize the CW310 board and let me program the device.
However, so far it shows no hardware target is open and only have localhost(0) status connected.

This is very confusing.
