### ISSUE TITLE
"ipgen.py generate" fails on plic data

### ISSUE THREAD

**Issue by adamjesionowski** [lowRISC/opentitan#9178]
I'm trying to generate an rv_plic peripheral with ipgen.py, but I'm getting an error. My invokation is this:
ipgen.py generate -C opentitan/hw/ip_templates/rv_plic -c opentitan/hw/top_shodan/ip/rv_plic/data/autogen/rv_plic.ipconfig.hjson -o <outputdir>

I get this error:
Traceback (most recent call last):
  File "opentitan/util/ipgen.py", line 148, in <module>
    sys.exit(main())
  File "opentitan/util/ipgen.py", line 134, in main
    args.func(ip_template, args)
  File "opentitan/util/ipgen.py", line 34, in action_generate
    ip_config = IpConfig.from_text(config_text, "the file passed to --config")
  File "opentitan/util/ipgen/lib.py", line 257, in from_text
    return cls.from_raw(
TypeError: from_raw() missing 1 required positional argument: 'where'

Where the ipconfig.hjson is
{
  instance_name: rv_plic
  param_values:
  {
    src: 183
    target: 2
    prio: 7
  }
}

**Comment by mundaym** [comment]
@adamjesionowski Did #9194 fix the issue for you?
