### ISSUE TITLE
Error transferring frame 0x00000000 @             0x00000000.

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#9199]
./util/fpga/cw310_loader.py --bitstream build/lowrisc_systems_chip_earlgrey_cw310_0.1/synth-vivado/lowrisc_systems_chip_earlgrey_cw310_0.1.bit
CW310 Loader: Attemping to find CW310 FPGA Board:
    Using bitstream :build/lowrisc_systems_chip_earlgrey_cw310_0.1/synth-vivado/lowrisc_systems_chip_earlgrey_cw310_0.1.bit
CW310 Board Found:
Loading done.

./util/fpga/cw310_loader.py --firmware build-bin/sw/device/examples/hello_world/hello_world_fpga_cw310.bin
CW310 Loader: Attemping to find CW310 FPGA Board:
    No bitstream specified
CW310 Board Found:
INFO: Programming firmware file: build-bin/sw/device/examples/hello_world/hello_world_fpga_cw310.bin
Programming OpenTitan with "build-bin/sw/device/examples/hello_world/hello_world_fpga_cw310.bin"...
Transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000001 @             0x000007D8.
Error transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000001 @             0x000007D8.
Error transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000001 @             0x000007D8.
Error transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000000 @             0x00000000.

**Comment by m-temp** [comment]
Duplicate of #9200
