### ISSUE TITLE
Error transferring frame 0x00000000 @             0x00000000.

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#9200]
./util/fpga/cw310_loader.py --bitstream build/lowrisc_systems_chip_earlgrey_cw310_0.1/synth-vivado/lowrisc_systems_chip_earlgrey_cw310_0.1.bit --firmware build-bin/sw/device/examples/hello_world/hello_world_fpga_cw310.bin
CW310 Loader: Attemping to find CW310 FPGA Board:
    Using bitstream :build/lowrisc_systems_chip_earlgrey_cw310_0.1/synth-vivado/lowrisc_systems_chip_earlgrey_cw310_0.1.bit
CW310 Board Found:
INFO: Programming firmware file: build-bin/sw/device/examples/hello_world/hello_world_fpga_cw310.bin
Programming OpenTitan with "build-bin/sw/device/examples/hello_world/hello_world_fpga_cw310.bin"...
Transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000001 @             0x000007D8.
Error transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000001 @             0x000007D8.
Error transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000001 @             0x000007D8.
Error transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000001 @             0x000007D8.
Error transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000001 @             0x000007D8.
Error transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000001 @             0x000007D8.
Error transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000001 @             0x000007D8.
Error transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000001 @             0x000007D8.
Error transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000001 @             0x000007D8.
Error transferring frame 0x00000000 @             0x00000000.
Transferring frame 0x00000000 @             0x00000000.

**Comment by m-temp** [comment]
I had similar issues. Try a different usb-port/adapter and make sure that the board is definitely powered up (6 green LEDs). Usb-power might not be enough.

**Comment by nicolast0604** [comment]
I power it with the AC on the top left corner of this board. 
And, after changed the USB port it seems successful in dmesg, however, the hello_world have the above problem still.

**Comment by nicolast0604** [comment]
Correct it, I power it with the DC on the top left corner.

**Comment by m-temp** [comment]
Can you double check the power settings (switches) as described in https://github.com/newaetech/ot-sca/blob/cwhusky-doc/doc/getting_started_bergen.md 
Additionally, the usb-port can still be a problem.

In my case the device showed up in dmesg, and I even could flash the bitstream, but failed for the firmware. On one board the issue was the power supply, on the other the used USB-port/adapter.

**Comment by tjaychen** [comment]
i don't think this link is referenced in the opentitan getting started fpga
guide (even though there is a general description), i wonder if we should
just link it directly.

**Comment by m-temp** [comment]
> i don't think this link is referenced in the opentitan getting started fpga guide (even though there is a general description), i wonder if we should just link it directly.

We should do that, but the link might change soon, as there is a pending PR https://github.com/lowRISC/ot-sca/pull/57
which corresponds to https://github.com/lowRISC/ot-sca/issues/50#issuecomment-957968228

**Comment by jadephilipoom** [comment]
Try pressing `USB RST` button, then reloading the bitstream, then try loading the firmware again? I was having the same error and that fixed it for me.

**Comment by a-will** [comment]
If you're following the FPGA user guide, it doesn't mention the needed argument to set up the PLL on the first run. Add `--set-pll-defaults` if you haven't, else there would be no clock.

I created a PR to fix that: https://github.com/lowRISC/opentitan/pull/8450

**Comment by vogelpi** [comment]
I am closing this issue as the corresponding fix has been merged a while ago already.

**Comment by m-temp** [comment]
I'm facing the same problem now, but with a very specific FPGA build. When flashing a specific version of my custom built (different AES-SBOX) earlgrey version, I'm unable to flash any firmware.  With another FPGA build , I can flash every firmware.

I don't think this AES related, but that something during place and route went wrong and/or something is producing more noise. I will have a deeper look on that (probably) next week, but in the meantime: It might help to use a different FPGA build

**Comment by m-temp** [comment]
I could debug this error further: **The problem was that I somehow missed to rebuild the test_rom**. Thus, I had an outdated/flawed boot_rom and consequently couldn't flash any firmware. Unfortunately, the error message doesn't help to much in this case. I know that it is clearly written in the getting started guide, but well... perhaps it helps other people when googling this error....
