### ISSUE TITLE
[flash_ctrl] Test plan review action items

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9205]
- [ ] re-name diagram to flash protocol controller and flash physical controller
- [ ] Add information about how many times the protocol controller can lose arbitration before it escalates
- [ ] Add information that directed host path can only read and can only access data partition
- [ ] Show the jtag path in block level diagram
- [ ] Show all tlul connections in the block level diagram
- [ ] remove metadata fifo path in the diagram
- [ ] Double check closed source testplan and usage of "high endurance" attribute
- [ ] Add description in the memory protection area that clarifies an "overflow" address will automatically be flagged as an error. 
- [ ] update `number of pages per bank` to `number of data partitions pages per bank`
- [ ] add more / better description to the isolated and secret partitions.
- [ ] add examples on how to calculate the address for a particular bank / page

**Comment by tjaychen** [comment]
@weicaiyang 
@cindychip 
@sriyerg 
@nikola-miladinovic 
FYI

**Comment by nikola-miladinovic** [comment]
Please add details for accessing Flash memory Data and Info Partitions (something like Bank 0 Data Partition starts at address 0x0 and info for other partitions).

**Comment by tjaychen** [comment]
@nikola-miladinovic this is explained in the spec. Basically we show that the address alignments are all the same, it's the info / type select that acts as extra "address" bits. 

Let me know if that part of the doc makes sense.
