### ISSUE TITLE
[rom] Handling of escalation type reset reasons

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9227]
At the moment, when the device resets due to POR, certain things are specifically wiped.
Do we need to do the same for escalation type resets (there are two of them from pwrmgr)?
If yes, it is not easy for software to identify which resets are the escalation resets.  So the hardware should make it clearer exactly which they are.  We would also need a cross module tests top level test to ensure this. 

Secondly, do we need to have discussions on the other reset reasons?
A [documented](https://docs.google.com/document/d/14JMwu1YcJYeyR77Issx4ic25g0xXxjbMGUrMJJokCEs/edit#bookmark=id.myhfki6pemti) was created long ago for this, but it is likely out of date to what the reality is.

**Comment by tjaychen** [comment]
FYI @matutem / @sriyerg  this may result in minor hw changes on how reset reasons are sent from pwrmgr to rstmgr.

**Comment by matutem** [comment]
Assigned myself to track the outcome of this.

**Comment by tjaychen** [comment]
I'll bring this issue up during an upcoming weekly sync, if we are fine with the current behavior i will close this issue.

**Comment by tjaychen** [comment]
regarding the retention sram, it was discussed and the current policy where the key would be lost on any type of reset was largely deemed acceptable. 

However, since the intent is to not rotate keys (forgot to bring-up this point in the meeting), it means on any reset but low power exit we should probably also initialize the retention sram instead of just POR (https://github.com/lowRISC/opentitan/blob/master/sw/device/silicon_creator/mask_rom/mask_rom.c#L125)

**Comment by alphan** [comment]
Discussed this with @cfrantz and @moidx offline and we decided to reset unconditionally on PoR and add an OTP item to configure the mask as needed. Created #12744.
