### ISSUE TITLE
[rom] Empty flash and invalid flash

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9228]
Currently, the ROM enters a shutdown routine if the next stage of code is invalid.
However, invalid does not distinguish between actual invalid (does not verify) vs something that is fully empty.

So this could mean that we may enter shutdown immediately on raw pieces of silicon, and this could potentially impact other routines needed.

It's worth thinking about whether we want to separate these cases, and how to do it.
One thought is that we could explicitly detect a flash empty case, and not enter shutdown if flash is empty. 
This may work well with the new boot-strap idea, which supports open source tooling like flash rom which would in fact allow a full erase.

**Comment by mundaym** [comment]
Anyone with access to the chip can erase the flash so I'm a bit hesitant to allow that alone to change ROM behaviour. I guess we could make it lifecycle dependent (i.e. only shutdown in the PROD, PROD_END and DEV lifecycle states).

**Comment by cfrantz** [comment]
The previous H1 series of chips would print out the hash calculations of the next stage before the jump.  From a observability point of view, seeing hashes printed to the uart (or not) before the shutdown message would let you know whether or not the flash is empty or invalid.

If we don't want the chip to immediately enter shutdown when its in the `RAW`, `TEST` or some other lifecycle states, we should reserve an OTP word for shutdown policy and have the CPU enter `wfi` when the lifecycle state is one of the bringup/test states and the OTP word is unprogrammed.

One other thing to consider: it is possible to keep the ROM in an idle state by asserting bootstrap and then simply not performing the bootstrap protocol.  The ROM will simply wait forever for the protocol to start.

**Comment by tjaychen** [comment]
sorry i should have clarified this better in the original issue. 

The main worry is this line `So this could mean that we may enter shutdown immediately on raw pieces of silicon, and this could potentially impact other routines needed.`.

The basic worry is, on raw silicon, there is "no flash content".  So if the ROM pushes the device into a shut down state, we may not be able to do code injection into the sram for early manufacturing test.  This is one of the cases early on where they do not plan to use the boot-strap protocol.

So there are definitely a variety of ways we can solve this, I just wanted to highlight it first.

@alphan also suggested an OTP word as a potential solution, which is why I linked #9295 for further context.

**Comment by alphan** [comment]
> One other thing to consider: it is possible to keep the ROM in an idle state by asserting bootstrap and then simply not performing the bootstrap protocol. The ROM will simply wait forever for the protocol to start.

This is a very good point but we still need to make sure that mask rom running on raw silicon will not enter shutdown before bootstrap.

**Comment by alphan** [comment]
> The basic worry is, on raw silicon, there is "no flash content". So if the ROM pushes the device into a shut down state, we may not be able to do code injection into the sram for early manufacturing test. This is one of the cases early on where they do not plan to use the boot-strap protocol.

Thanks for capturing this @tjaychen. I'll close this issue since #13111 adds the `ROM_EXEC_EN` OTP item. PLMK if you think we should keep this open. I'll review #9295 separately.

**Comment by tjaychen** [comment]
sounds good.  thanks @alphan!
I think this is good, @moidx / @cfrantz let me know if you think we've missed anything here.
