### ISSUE TITLE
[dv] support for backdoor access to memories that are composed from more than one block in the foundry database

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#9231]
The main RAM open source model is a single block, but in the foundry database the RAM may be composed from a few blocks that require separate backdoor interface.
CC: @tjaychen @ankamate@google.com

**Comment by tjaychen** [comment]
@msfschaffner ahh... this is because of the memory tiling. 
Can the backdoor binding interface access a localparam in the module? 
Because maybe we can expose that information and use it to determine how the backdoor load has to change?

**Comment by tjaychen** [comment]
@cindychip

**Comment by sriyerg** [comment]
We could make the sram mem bkdr util to be a dynamic array and in closed source, set the size to whatever is needed. There may be translation logic needed to select the right array instance based on input address.

I thought we covered this in the meeting?

**Comment by tjaychen** [comment]
as part of meetings today, it was decided these need to be surfaced more
clearly so we can more easily identify what kind of difficulties there are
in enabling foundry sims.

really it just means file issues to track these problems and assign people
to resolve them.

**Comment by sriyerg** [comment]
Right - I thought we had discussed a solution for it already. Anyway,open source PR coming soon.

**Comment by tjaychen** [comment]
sounds good. Thanks Sri.
