### ISSUE TITLE
[sw/exts] Rename/move`exts/common` to `test_rom_ext`.

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#9234]
The flash C runtime, flash linker script, and test interrupt vectors located in `sw/device/exts/common/` are all used only for building / executing on-device tests, including: smoke tests, IP integration tests, and some mask rom func tests.

Similar to #9154, I propose moving this testing "rom_ext" code (i.e., ROM code that lives in flash) to `sw/device/lib/testing/test_rom_ext` to make it more obvious what this code is used for. Additionally I propose renaming the following:

`flash_crt.S` --> `test_rom_ext_start.S`
`flash_link.ld` --> `test_rom_ext.ld`

This organization / naming conventions would align more with the file names used in `sw/device/silicon_creator/rom_ext/` as well.

Thoughts?

**Comment by sriyerg** [comment]
Fine with me.

**Comment by tjaychen** [comment]
i can't completely remember now..either @moidx or I helped to add this initially..but is it really not used anywhere else? I can't remember if the `ld` file was also originally used for tests and just not any longer?

**Comment by timothytrippel** [comment]
<img width="594" alt="Screen Shot 2021-11-15 at 3 26 39 PM" src="https://user-images.githubusercontent.com/5633066/141868682-bd8e88ad-0597-49a0-9926-3172786d1299.png">

From what I can tell, it is only used in examples (i.e. the `hello_world` executables), SCA, chip-level tests (smoke, IP integration, mask rom func, and benchmarks.

**Comment by tjaychen** [comment]
ah that's right. So I guess this used to be the linker description that everything used until @mcy cleaned it all up.
So maybe the answer is that the example files need to update to use the new one.

**Comment by timothytrippel** [comment]
Maybe the example programs should be moved to the `sw/device/silicon_owner/` directory, and refactored to use the real `rom_ext`? (Though this might be broken off to a separate issue.)

**Comment by tjaychen** [comment]
o interesting, so that these can be used with the real software flow you
think?

**Comment by timothytrippel** [comment]
Yeah exactly. There is already a silicon owner app example [here](https://github.com/lowRISC/opentitan/tree/master/sw/device/silicon_owner/bare_metal), so maybe that makes more sense? Additionally, as we bring more IP-integration/system-level use case tests online, this "hello_world" demo may be more useful for the end silicon owner application writer than those looking to understand how to write a test?

**Comment by alphan** [comment]
SGTM. I wonder if it makes more sense to consider the example/demo programs as the 4th stage of the boot flow, i.e. the program that the first owner stage jumps to, instead of 3rd stage, which should include a manifest and be signed, but we can tackle that issue separately.
