### ISSUE TITLE
[reggen/doc] Fix broken multireg links

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#9237]
If multiregs are broken up into multiple registers, the naming changes from `FOO` to `FOO_0`, `FOO_1` etc which can lead to broken links in the documentation and Hjson if the IP is templated and the number of registers top-level dependent (e.g. alert_handler, PLIC).

There are a couple of ways to fix this:
1. We can enforce that even degenerate multiregs have the `_0` suffix. 
This may be a bit ugly, but it would make the naming consistent and fix the linking issue.

1. We can fix the documentation generation logic to recognize these cases.
This is a bit more difficult to do.
I have attempted to implement something like this in #9236 for the IP Hjson link rendering function (it infers this multireg situation by looking at the name and checking whether `FOO_0` and `FOO_1` exist if `FOO` cannot be found).
However, the HUGO shortcode replacement logic does not have this context (it basically can only do an isolated string operation on the name provided in the shortcode).

So it looks like the first option might be the more convenient (and less brittle way forward).

What do you think?

Btwy, we've had related discussions about this format in the past, see e.g. #3006.

**Comment by rswarbrick** [comment]
For more confusion about this topic, see #5216.

Could we do (2) "the other way", by adding an anchor for FOO in the same place as FOO_0? That's probably easier for the shortcodes and the resulting text might look nicer: a multi-reg that breaks into FOO_0, FOO_1, FOO_2 (say) could still be referred to as "FOO" in the documentation.

**Comment by vogelpi** [comment]
@msfschaffner with "degenerate multireg" you mean a multireg with a count just 1? If yes, it sounds perfectly fine to me to just append the `_0` suffix also there. 

Also @rswarbrick 's version of option (2) sounds good to me.

**Comment by msfschaffner** [comment]
This has now been addressed.
