### ISSUE TITLE
[otbn] Should we update the register file on the first cycle of a failed BN.LID?

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#9267]
Suppose you do something like `BN.LID x2, 0(x3++)` and the load sees an ECC error. With the current RTL, we update `x3` on the first cycle and then spot the error on the second. With the ISS, we discard the write to `x3` once we've seen the error, causing a mismatch in the register file at the end.

These need to agree, but we can do it either way: either tweak the design so that we delay the write to `x3` to the second cycle (where it would be squashed by the error) or tweak the ISS so that it allows GPR writes to commit even when an instruction is stalled.

I don't have strong feelings about what's best, and this isn't really visible outside the core (since the register file will be wiped at the end of an operation).

@GregAC: Do you have a preference?
@prajwalaputtappa: FYI

**Comment by GregAC** [comment]
I'd prefer to tweak the ISS to allow the GPR write to commit.

We've already had a few complications with the behaviour here so it'd be preferable to avoid further RTL changes unless there's a clear 'wrong' behaviour it's doing which I don't think is the case here.

Also avoids have an extra set of flops around that need hardening as they'd be an excellent fault injection target!

**Comment by rswarbrick** [comment]
Ok, can do. I was thinking that you wouldn't need the flops because you could just compute the new address on the second cycle but that's wrong because of x1. D'oh!
