### ISSUE TITLE
[rtl/rstmgr] Fix reset consistency checks

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#9269]
The rstmgr_sw_rst test is occasionally causing cnsty_chk_errs[17] to trip. I have attached some waves if that helps. I can reproduce this in HEAD with "rstmgr_sw_rst -s 3612801871", but if you are not at HEAD you could find seeds that trigger it: I am getting failures in 8 out of 50 reseeds.

![image](https://user-images.githubusercontent.com/80294896/142179092-75e8dc08-731f-4056-bb3c-1d9a61790e43.png)

**Comment by tjaychen** [comment]
ah thank you! i will look at this more closely.

**Comment by matutem** [comment]
Tim, we are planning to have more focused tests for the consistency checkers. It would help if these were not parameterized. It seems the MaxSyncDelay parameter is never overriden. Could it become a localparam instead? This makes it easy to turn it back into a parameter if you find a use for changing its value.

**Comment by tjaychen** [comment]
yeah i don't see why that couldn't be made a local parameter. Let me have a closer look to try and remember what I had in mind.
Let me first try to recreate this failure and see what is broken with the logic.

**Comment by tjaychen** [comment]
so this failure seems to be a direct result of fixing #8808. Now the software reset request is held too long.
I need to think a bit about what's the right fix.
