### ISSUE TITLE
[DV process] Does V2S signoff need an in-person review meeting?

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#9271]
Currently, V1/2/3 have a meeting driven review step. We recently added a new intermediate milestone V2S. Should we have a review meeting for it as well? 

Arguments against:
- All V milestones will have a meeting driven review step making it slightly heavy
- Countermeasures will be documented properly in HJSon which will help ensure the testplan for V2S is up-to-date (alleviates the concern if we missed anything)
- DV is already staying on top of countermeasures that can be standardized and run as a separate common test

Arguments for:
- Only a handful of IPs will need it (if desired), so maybe its not a big deal to have a couple of extra review meetings
- Vocalizing the testplan, testing methods, etc. with an audience (i.e., a collaborative development) often results in fresh new ideas to solve verification problems (we are however, doing this in DV meetings already)

**Comment by sriyerg** [comment]
Trending opinion:
- Have a review meeting for blocks that implement a custom countermeasure (example: rstmgr with reset consistency checker)
- Blocks that only have a standardized set of countermeasures can get away with just a PR review

**Comment by msfschaffner** [comment]
We've discussed this in the silicon meeting, and we're generally fine with the trending opinion above.
To add some more detail:
- we're going to use the countermeasure list in the IP Hjson as the reference to do a gap analysis and determine whether additional tests have to be developed as part of V2S. example for such a list:
https://github.com/lowRISC/opentitan/blob/ad632a0c8b5586b310773f0bceff2c794695830a/hw/ip/rom_ctrl/data/rom_ctrl.hjson#L86-L109

- some custom countermeasures may already be tested as part of V2, especially in cases where the custom countermeasure is a very important functional feature of the block (e.g. scrambling). However, there may be coverage gaps in some blocks, and V2S is intended to identify and close them.
- It is allowed to sign off V2 and V2S together if there are no custom countermeasures (i.e., only standardized tests are needed to close coverage).

**Comment by msfschaffner** [comment]
@sriyerg do you have anything to add? Should we close this issue or keep it around?

**Comment by sriyerg** [comment]
We now have testsplans autogenerated from the list of countermeasures for each block, which will help with the DV gap analysis.
Example: https://reports.opentitan.org/hw/top_earlgrey/ip_autogen/alert_handler/dv/latest/results.html

These autogen testplans add V2S testing requirements which will be tracked for V2S closure. Existing or newly written tests need to be mapped to these testpoints appropriately, which will be the focus of the V2S review meeting, if deemed to be required.
