### ISSUE TITLE
[top] Provide list of desired vectors for power estimation

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9297]
- power virus test that simulates maximum instantaneous step. This should include
  - [ ] staggered activation of otbn, aes, kmac/hmac.
        - kmac / aes would need to take turns being fed data
          - kmac activation should be a combination of otp background, key manager background and software
        - for otbn, any signature verification / signing event is sufficient
  - [ ] entropy complex ongoing
        - reseed / update operation ongoing
  - [ ] flash scramble ongoing (ideally both instruction and data, but data should be sufficient for now)
        - instruction scrambling gated by script availability
  - [ ] simultaneous io toggling as defined [here](https://docs.google.com/document/d/1UmJcjeE2ZCT2S9N4YmB9YE8BQY9pv19EWSvZ7_vZWVw/edit?usp=sharing)
        - ideally for digital activity, 3xuart / 2xi2c modules should be activated
          - for first pass simplicity can activate IO portion only for now through GPIO
        - for dedicated pins, focus on SPI device quad activity
        - USB activity should be activated
          -  for first pass simplicity activate IO portion only for now via pin forcing in usbdev.
  - [ ] ongoing cpu activity (icache / sram scrambling both activated)
         - servicing ongoing threads and random read/write data to memory
         - icache needs to be activated, otherwise the system may spend most of its time fetching code
         - flash verification is currently insufficient to turn on icache
  - [ ] background checks enabled wherever possible 
         - rstmgr background checks
         - others?

- low power test that simulates deep sleep state
- low power test that simulates light sleep state
- general system idle that is NOT low power

Make sure to document these test cases in the test plan.

**Comment by tjaychen** [comment]
@zi-v

**Comment by zi-v** [comment]
Thanks!

**Comment by tjaychen** [comment]
@zi-v let me know if there are other scenarios of interest.

**Comment by zi-v** [comment]
For the max instantaneous step, please also consider adding concurrent IO toggling.

**Comment by tjaychen** [comment]
yes that is the plan.

**Comment by zi-v** [comment]
More power scenarios:
- Power up
- Transition from Active to AON
- Transition from AON to Active

**Comment by tjaychen** [comment]
@zi-v are the latter two not covered by transition in and out of low power states? That was my intent.

**Comment by zi-v** [comment]
They are. I was just not clear to me that the above covers it already. I thought it only talk about the static state and wanted to make sure that the transitions are also covered.
