### ISSUE TITLE
[reg] How to respond when destination is in reset or clock gated?

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/opentitan#93]
We don't have this issue yet, but when we get to the point when IP can be in reset or clock gated while the processor is alive, we need to formulate a response so that the processor does not hang. We need to spec out how this is managed.

Requiring the source have a transaction timeout could be a good approach -- it is more likely to terminate cleanly.

We can also place some kind of bus shim in front of destination peripherals. These would basically take the actual 'clk_en' as an input and basically force the modules to error back in the event the clock were manually disabled by software. The reset can be handled similarly, but a natural question will come up on what reset the shim should use relative to the destination iP.

This should be part of our general reset strategy, pointing at @tjaychen for the moment.

**Comment by tjaychen** [comment]
Linking the RFC draft document here
https://docs.google.com/document/d/1KnmIt7vj8vkfqgAIcx6HJo8KH6zirFNF1TxlL5K6Aso/edit?usp=sharing

Comments are very welcome.

**Comment by msfschaffner** [comment]
@tjaychen what is the status on this issue? can we summarize the current handling and close it?

**Comment by tjaychen** [comment]
yes that's right.

**Comment by tjaychen** [comment]
thanks for the reminder! closing.
