### ISSUE TITLE
[rom] Early device boot-strap and external clock

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9315]
Related to #8700 

During early device life cycle when clocks are not yet calibrated (for example the calibration algorithm is still being developed or tweaked), it will be necessary to boot-strap using a stable external clock (since flash may not program / erase correctly without one).

External clock switch through software will be further enhanced in #9294, allowing ROM to switch to an external clock in these situations.

This issue mainly raises this question and explores what options are best suited for ROM in this scenario.

**Comment by tjaychen** [comment]
@zi-v 
i believe this issue is now resolved with `ROM_EXEC_EN`. The idea is that until calibration (of various things), we will not enable ROM to execute or boot strap in general. 

This removes the need to have ROM support boot strap using external clock. 

@alphan, let me know if you agree, if yes we can probably just close this issue.

**Comment by alphan** [comment]
Agreed. @zi-v please feel free to reopen if you think we should revisit this.
