### ISSUE TITLE
[flash_ctrl] Backdoor loading enhancements

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9322]
The flash backdoor load function is at the moment incomplete. As a result, we are not able to enable scrambling in the boot rom because it would work for FPGA but break for verilator / DV.

We need to enhance [this script](https://github.com/lowRISC/opentitan/blob/master/util/design/gen-flash-img.py) to match [this picture](https://docs.opentitan.org/hw/ip/flash_ctrl/doc/#overall-ecc-application).

The main thing that is missing now is a call to `pyfinite` for the field multiply, and then another invocation to `prince` to complete the XEX scrambling scheme.  One additional complication is that the flash scramble key is dependent on collateral stored inside the `otp`.  So the script enhancement needs to take `gen-otp` into account as well.

**Comment by tjaychen** [comment]
@timothytrippel 
@alphan 
@mundaym 
@cfrantz 

FYI

**Comment by tjaychen** [comment]
@sriyerg 
@cindychip 
@weicaiyang 
@matutem 

FYI

**Comment by tjaychen** [comment]
the integrity and reliability ecc's are both there now. Just need to do the actual scramble next.
Hopefully this will not be too painful.

**Comment by rswarbrick** [comment]
For the scrambling, you might be able to nick some stuff from `hw/ip/rom_ctrl/util/scramble_image.py`.

**Comment by tjaychen** [comment]
> For the scrambling, you might be able to nick some stuff from `hw/ip/rom_ctrl/util/scramble_image.py`.

yes i definitely plan to, there are just a few other kinks to work out.
The flash scramble key is device specific, so I need to figure out how to pull the correct contents out of `otp` and mix it with the correct constant from top.  After that I just need to find an appropriate galois field multiplier and HOPEFULLY that will be it.

**Comment by alphan** [comment]
FYI @jon-flatley (since this can end up affecting opentitantool)

**Comment by tjaychen** [comment]
O is opentitantool used for backdoor loading verilator also?

**Comment by timothytrippel** [comment]
No, I believe opentitantool will just be able to create OTP images (from Hjson descriptions). Correct @alphan?

**Comment by alphan** [comment]
> O is opentitantool used for backdoor loading verilator also?

> No, I believe opentitantool will just be able to create OTP images (from Hjson descriptions). Correct @alphan?

Correct, it can create OTP images thanks to @jon-flatley. I'm not sure if we would be interested in handling flash images as well (since we can run verilator tests from bazel). Just wanted to tag since the operation seemed somewhat similar.

**Comment by msfschaffner** [comment]
Has this issue been addressed or is there pending work to be done?

**Comment by tjaychen** [comment]
still pending work :)

**Comment by tjaychen** [comment]
i think we need to face reality and punt this one to M3. It's not going to make M2 but it also is not critical to M2 feature freeze.

**Comment by GregAC** [comment]
Tagged as P1 as we do want to test scrambling in the boot ROM and better to do this sooner rather than later in case it shows up some issues.

**Comment by timothytrippel** [comment]
This will also be needed for the power virus test (#14814) to run in DV, if we want to go the backdoor flash loading route, since once flash-scrambling is turned on by the ROM, the power virus test program in flash will just look like garbage.

**Comment by timothytrippel** [comment]
Task list:

- [x] (potentially) update irreducible polynomial used for prim GF multiplier (#17443)
- [x] refactor the `gen-flash-img.py` script to enable pre-scrambling the flash VMEM via cmd line arg (#174543)
- [ ] wire up `gen-flash-img.py` to Bazel to pass correct flags to scramble the image if the OTP setting is set  (TBD)
