### ISSUE TITLE
[keymgr] Valid-ready protocol violation on KMAC sideload interface

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#9324]
In this scenario, the keymgr is brought into disabled state after a previous valid operation. In disabled state, it writes prng data generated from LFSR into the KMAC interface to wipe it. As KMAC app interface transitions to `StTx` state, it asserts valid. But the LFSR is still enabled from the previous operation, so the `data_rand[0]` which is used for this purpose changes before ready is asserted, causing a protocol violation (previous valid data as seen by KMAC is silently dropped). 
![image](https://user-images.githubusercontent.com/46467186/142735857-8ffbcc17-bf8c-4d3d-b45b-fac81ce31329.png)

We probably don't actually care about losing junk data so the solution might be to disable the assertion check, but it will be good to have a quick discussion on this nevertheless.

This was not uncovered before because `kmac_app_agent_cfg` declared `push_pull_agent_cfg` as a non-rand variable, which made the `ready` delay bounds to be set to 0, so `ready` always remained asserted.

**Comment by sriyerg** [comment]
![image](https://user-images.githubusercontent.com/46467186/142736708-801bbbce-5887-4417-bf84-b7e62979367b.png)

[Better snapshot] 
See highlighted signals.

**Comment by sriyerg** [comment]
To reproduce, fetch updates from PR #9280. The third commit in the PR disables the said assertion check. Drop that commit and run `keymgr_smoke` test.

**Comment by weicaiyang** [comment]
Thanks @sriyerg for finding this issue in the agent.

@tjaychen 
I think we have discussed this before. In StDisabled or StInvalid, keymgr will send kmac with constant changed entropy data. Since we plan to send the junk data, we probably don't need to conform the protocol that the data shouldn't be changed until the ready comes. Especially, when fault is detected or LC turns off in the middle of sending data to KMAC, we want to wipe the data ASAP.

**Comment by tjaychen** [comment]
@weicaiyang yes that is all correct. 
Long term I should probably think about how to make this cleaner... it's true we don't care about the junk data, but it's annoying to have to explicitly disable assertions. 

For now, should I create some kind of signal to indicate we're in this state where we might have to disable things? Or should that be done from test side?

**Comment by weicaiyang** [comment]
> @weicaiyang yes that is all correct. Long term I should probably think about how to make this cleaner... it's true we don't care about the junk data, but it's annoying to have to explicitly disable assertions.
> 
> For now, should I create some kind of signal to indicate we're in this state where we might have to disable things? Or should that be done from test side?

I think I can handle it in the testbench side, since scb has modeled the keymgr state and known when we injected a fault.
