### ISSUE TITLE
In Tree Helper Script for get-toolchain.py Error

### ISSUE THREAD

**Issue by lchang256** [lowRISC/opentitan#934]
I am trying to install the SW toolchain by using the helper script in tree, under /util:

$ ./util/get-toolchain.py

However, I am getting the following error:

Downloading toolchain from https://github.com/lowRISC/lowrisc-toolchains/releases/download/20191101-1/lowrisc-toolchain-gcc-rv32imc-20191101-1.tar.xz
Traceback (most recent call last):
  File "./util/get-toolchain.py", line 169, in <module>
    main()
  File "./util/get-toolchain.py", line 161, in main
    install(archive_file, target_dir)
  File "./util/get-toolchain.py", line 89, in install
    subprocess.run(cmd, check=True)
AttributeError: 'module' object has no attribute 'run'

I am running in Ubuntu 14.04.

Is this a known issue?

How do I get around the error?

Thanks

**Comment by asb** [comment]
Hi @lchang256, thanks for giving OpenTitan a go and thanks for sharing the Linux distribution you're using - that makes it much easier to debug.

Ubuntu 14.04 ships with Python 3.4.x, while our [minimum supported Python version](https://docs.opentitan.org/doc/ug/install_instructions/) is 3.5.2. Ubuntu 14.04 was end-of-lifed at the end of April this year (i.e. no new security updates etc). I'd really recommend upgrading to a newer release.

**Comment by lchang256** [comment]
OK, thanks.
