### ISSUE TITLE
[rstmgr] Length of software reset

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9340]
This is something I didn't realize until very recently. 
The software reset programming model for `rstmgr` is a bit unfriendly.

Software basically has to set the software request bit, and wait and "undetermined" amount of time (related to how fast the reset domain is) for the reset to propagate, before it can disable the reset request.

It seems like it would be a lot cleaner (related to #9269) for this to self clearing by hardware.
Ie, software would set the request, and simply poll on it to become an inactive value, at which point it can assume the reset is complete.

Any opinions on this? Is this a must fix? It's not exactly a bug, but there are some usability problems that in the short term we can get around.

**Comment by tjaychen** [comment]
@cfrantz 
@alphan 
@silvestrst 
@mundaym 
@moidx 
@arunthomas

**Comment by silvestrst** [comment]
```
Software basically has to set the software request bit, and wait and "undetermined" amount of time (related to how fast the reset domain is) for the reset to propagate, before it can disable the reset request.
```

I think from what you are saying current API is probably incorrect? `dif_rstmgr_software_reset`:
```
...
  switch (reset) {
    case kDifRstmgrSoftwareReset:
      rstmgr_software_reset_hold(base_addr, peripheral, true);
      rstmgr_software_reset_hold(base_addr, peripheral, false);
      break;
...
```
The code assumes that you just need to toggle the reset line for peripheral to reset.

**Comment by silvestrst** [comment]
> It seems like it would be a lot cleaner (related to #9269) for this to self clearing by hardware.
Ie, software would set the request, and simply poll on it to become an inactive value, at which point it can assume the reset is complete.

Sounds like a nicer to use interface. Would there be any value for software to still have API to hold reset lines for arbitrary amount of time (perhaps for testing purpose)?

**Comment by tjaychen** [comment]
> > Software basically has to set the software request bit, and wait and "undetermined" amount of time (related to how fast the reset domain is) for the reset to propagate, before it can disable the reset request.
> 
> I think from what you are saying current API is probably incorrect? `dif_rstmgr_software_reset`:
> 
> ```
> ...
>   switch (reset) {
>     case kDifRstmgrSoftwareReset:
>       rstmgr_software_reset_hold(base_addr, peripheral, true);
>       rstmgr_software_reset_hold(base_addr, peripheral, false);
>       break;
> ...
> ```
> 
> The code assumes that you just need to toggle the reset line for peripheral to reset.

yes so i think this would work "most" of the time. Because the amount of time it takes for us to fetch the instruction, program it to true, then program it to false most likely is enough time for the reset to propagate.  Although it is not guaranteed if the ratios change.   However once we enable the icache, this could change, because the instructions might be cached and result in much lower programming latencies (icache is not turned on yet).

**Comment by tjaychen** [comment]
> API to hold reset lines for arbitrary amount of time (perhaps for testing purpose)?

If we go with the approach I am suggesting, we probably wouldn't need it anymore. Because software would set it, and then wait for hardware to clear it.  So there would be no way to "hold" the reset, instead the best software could do is simply assert it again. 

Let me think about this particular point.  Sometimes there is value in being able to "hold" something in reset from software's perspective.  So maybe what I really should do is instead of clearing the original software request, provide another register to indicate the reset is done, and let software decide when to release.

**Comment by tjaychen** [comment]
@matutem it would be good to get your opinions here. I don't want to put too big a burden on DV at this point.

**Comment by matutem** [comment]
There is no test for this reset yet, so no issue.

**Comment by tjaychen** [comment]
does that mean it's okay to change this area? Because this would impact the
sw_reset tests right now wouldn't it..?

**Comment by matutem** [comment]
Wait, we have sw_rst_ctrl_n and reset_req CSRs. It seems you are referring to sw_rst_ctrl_n, in which case this would have a small impact, but this is dealt with in a single task so the change would be simple. As for holding some unit in reset for a longer time, an alternative (for some units) is to gate off the unit's clock, perhaps after resetting it: not the same but similar.

**Comment by tjaychen** [comment]
ah sorry, i should clarify.
It's not the unit having clock that's an issue.  It's more than when
software asserts the reset request, it doesn't know how long it will be
until the reset propagates through rstmgr and to the module.

**Comment by tjaychen** [comment]
@arunthomas @moidx could you guys bring this up in a software forum and see if it's important to fix?

**Comment by matutem** [comment]
It seems SW could not clear this until it comes back from reset, at which point it will get reset again? Seems like a must-fix. Don't worry so much about the DV impact, but I appreciate the intention :)

**Comment by tjaychen** [comment]
no without this, software would basically need to clear, wait for "some" amount of time (we would have to tell them) and then release...  this is specific to the peripheral resets.

**Comment by matutem** [comment]
Sorry, you can discount much of my earlier feedback on this, as I kept thinking of rstmgr reset_req, not sw_rst_ctrl_n.

The RTL puts sw_rst_ctrl_n through a synchronizer and both 0->1 and 1->0 transitions are subject to some delay. rstmgr's clock for the sw_rst_ctrl_n generation is io_div4, which is the slowest one among peripherals that can be software reset... so it seems this logic will work as is, even without adding a call to sleep between transitions.

WDYT?

**Comment by tjaychen** [comment]
ah yes good point!

**Comment by matutem** [comment]
Okay to close this issue?

**Comment by tjaychen** [comment]
that sounds good to me!
