### ISSUE TITLE
[otbn] Pick size of scratchpad and update design/docs/toolchain to match

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#9351]
We need to decide how big the OTBN scratchpad is. At the moment, the design is documented and implemented to have 2kiB of bus-accessible memory and 2kiB of scratchpad. Should we change this? (e.g. to 3kiB bus-accessible; 1kiB of scratchpad).

See discussion starting from @felixmiller's comment here: https://github.com/lowRISC/opentitan/pull/8892#issuecomment-974272263.

Note: Delaying this decision shouldn't have an impact on D2: the design changes to switch to a different layout are minimal.

@felixmiller, @jadephilipoom, @GregAC

**Comment by rswarbrick** [comment]
We're getting ever closer to design freeze and we've sort of defaulted to 50:50.

@felixmiller, @jadephilipoom: Speak now or forever hold your peace :-D

**Comment by jadephilipoom** [comment]
This part of Felix's comment in the earlier thread gives me pause:
> On the other hand: The reason why we came up with this idea initially, are crypto operations where ephemeral keys are generated (mainly ECIES). In any case, the algorithms we would use there would be ECC based, meaning fairly small keys to be hidden in the non-accessibly window. Even for P-521 and if there are multiple keys, 1k of non-accessible space would be enough.

It sounds like we're _probably_ okay with 2kiB but it _might_ be an issue if we've misestimated the input sizes or add a new algorithm that requires a large buffer -- and on the other hand we are pretty confident we have nothing to lose by making the scratchpad smaller. If that's still accurate, I'm more comfortable with a 3kiB/1kiB split.
