### ISSUE TITLE
[hugo] SPI_DEVICE checklist cannot be generated

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#936]
Current master branch, the checklist document for SPI_DEVICE cannot be generated.
hugo build doesn't raise any error while creating docs. Does anyone experience same issue?

**Comment by tjaychen** [comment]
Hmmm I pulled to head about 2 or 3 hours ago and it was okay. Maybe another
recent merge?

**Comment by eunchan** [comment]
Resolved by renaming `hw/ip/spi_device/doc/index.md` to `_index.md` . Thanks @msfschaffner I didn't know that Hugo has this kind of naming rule. :)
