### ISSUE TITLE
RFC: OpenTitan D2S Milestone - Sign-off Process

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9362]
@sriyerg pointed this out and I think it makes sense to enhance the D2S checklist to show all the explicit steps shown in the [presentation](https://docs.google.com/presentation/d/1F8gk-WcxwF-g2mn29A_ko0De8amiyv965Od3FKJCj0U/edit?usp=sharing).

Specifically I think it would make sense to have countermeasures / assets documentation in hjson, security counsel reviewed etc in there.

@msfschaffner what do you think? You've been looking at this longer, so let me know if this is already covered elsewhere and I'm just not aware of it.

**Comment by tjaychen** [comment]
btw, I talked to @moidx a bit about this, and it's actually okay to document both the countermeasure and asset in the open.
Other things we can't, but I think this would be a good start.

**Comment by msfschaffner** [comment]
Yes, this sounds good to me.
I'll add the additional checklist items to the proposal doc.

**Comment by msfschaffner** [comment]
Here is a link to the proposal doc:
https://docs.google.com/document/d/1R1mvFWAUPOsOhuGZDGEcl7VJ-qdkn001eumMdrJi2BA/edit#heading=h.1qmc39dhqd9f

**Comment by rswarbrick** [comment]
I assume this is supposed to be visible to all OT accounts? I just had to request access: maybe the sharing settings need tweaking?

**Comment by msfschaffner** [comment]
Ah, I've only granted access to the TC.
In this case the sharing settings are intended to be on the stricter side.

**Comment by msfschaffner** [comment]
This RFC has been tentatively approved by the TC so that we can test drive the D2S review flow.
It will again be reviewed and finally voted upon in January.

**Comment by msfschaffner** [comment]
This RFC has been approved by the TC today.
Closing this issue since the checklists have been updated accordingly.
