### ISSUE TITLE
[sw,tests] Duplicate KMAC smoketest.

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#9363]
There seems to be a (somewhat) duplicate KMAC smoke test subfoldered in the `dif` directory under the `sw/device/tests` subtree, i.e.:

[`sw/device/tests/dif/dif_kmac_smoketest.c`](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/dif/dif_kmac_smoketest.c)

and 

[`sw/device/tests/kmac_smoketest.c`](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/kmac_smoketest.c)

According the [chip-level test style guide](https://docs.opentitan.org/sw/device/tests/), that was put in place after discussion on this issue (#7976), smoke tests should not be subfoldered under the `dif` sub-directory, as this is slightly confusing since all chip-level tests (smoke, IP integration, and system level scenario tests) should make use of DIFs.

**_Note:_** the functionality of the above two tests is almost identical, but the one in the `dif` subdirectory seems newer, so we should probably move that to the main chip-level test folder (`sw/device/tests/`) and rename to just `kmac_smoktest`, per the [style guide](https://docs.opentitan.org/sw/device/tests/).

Sorry for not catching that earlier! I should probably bring this up again in the next SW WG, since we have had some new people join recently. (@mundaym, @arunthomas)

**Comment by mundaym** [comment]
Sorry, it didn't click that the file was new during the review. This was caused by an old PR (that modified the test at the old location) that was rebased.

@doreis-lowrisc can you merge the changes to `sw/device/tests/dif/dif_kmac_smoketest.c` into `sw/device/tests/kmac_smoketest.c` and then delete `sw/device/tests/dif/dif_kmac_smoketest.c`? Thanks!

**Comment by timothytrippel** [comment]
No worries, thanks @mundaym!
