### ISSUE TITLE
[pinmux/strap_sel] Unable to select lc_ctrl jtag strap in test_locked state

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#9365]
Hi Tim,

Thanks again for helping me understand the tap selection better.
Followed your instruction and I drove the tap selection pin (IOC5 and IOC8) right at the beginning of the simulation, but still not able to see the jtag_lc_tap being selected.

One question I wanted to confirm regarding reset pins in pinmux and pwrmgr:
When pwrmgr comes to its `FastPwrStateStrap` state, the pinmux's reset pin for `tap_strap_q` is still 0.
So I think the value of `tap_strap_d` is not retained during `FastPwrStateStrap`.
Is this expected?

Waveform:
![image](https://user-images.githubusercontent.com/11466553/143102433-d751db8f-5f6f-4e7d-8745-6288fb7b0d4d.png)

Smart ID:
smart:7a9b61ee-e059-45f3-9e46-08133e948529

Way to reproduce: 
New chip level development. I can push a draft PR for that.

Thanks again.
Cindy

**Comment by tjaychen** [comment]
ah it is not, I believe that's a bug. Let me check.
I thought I had moved `pinmux` into a different reset group to avoid this issue, but perhaps I forgot.
