### ISSUE TITLE
[spi_agent] Adding capability of driving csb[1] with intention of connecting to TPM CSB in spi_device implementation

### ISSUE THREAD

**Issue by kosta-kojdic** [lowRISC/opentitan#9377]
We noticed csb is 4 bits wide in spi_agent implementation and csb[0] is used for normal flow.

I propose adding usage of csb[1] with intention of it to be connected inside spi_device for driving TPM transactions (which uses separate CS signal).

Inside spi_agent we don't need to specify in naming it is for TPM, so it remains specification independent. We can add SpiTransAlternateCSB in place of SpiTransNormal, and add similar alternate CSB driving task inside host driver.

We can make spi_host_alternate_csb_seq using this additional item type and use it for TPM transfers. This way we will maintain usage of unified spi interface inside spi_device testbench without need for additional TPM interface.

Please comment on this suggestion, if you are OK with the proposed change we can implement it and do pull request on spi_agent. After it we can use it for TPM sequences inside spi_device.

**Comment by weicaiyang** [comment]
```
  typedef enum {
    SpiTransNormal,    // normal SPI trans
    SpiTransSckNoCsb,  // bad SPI trans with clk but no sb
    SpiTransCsbNoScb   // bad SPI trans with csb but no clk
  } spi_trans_type_e;
```
The propose of this enum is to enable some dummy transfer without clk or csb. We may want to test the dummy transfer for TPM mode as well.

How about we create `bit[3:0] csb_sel` in the cfg and driver drives it the selected csb as configured like `cfg.vif.csb[cfg.csb_sel] <= 0` and we can connect TPM csb with csb[1]. WDYT?

**Comment by kosta-kojdic** [comment]
The idea of using cfg for csb_sel looks great. This way we would keep all of the driver infrastructure intact, only modifications are instead of [0] in driving logic to be [cfg.csb_sel] and we still connect TPM csb with csb[1] as intended (and use only spi interface as intended). I think we will go with this, play a bit in TPM sequences to test it and make pull request. Thanks a lot!

**Comment by weicaiyang** [comment]
sounds good. Thanks

**Comment by kosta-kojdic** [comment]
Just one correction, since we have CSB's in range from 0 to 3, we can have bit[1:0] csb_sel in the cfg.

**Comment by weicaiyang** [comment]
> Just one correction, since we have CSB's in range from 0 to 3, we can have bit[1:0] csb_sel in the cfg.

sounds good. Thanks for the update

**Comment by kosta-kojdic** [comment]
Pull request that implements this was merged, closing this issue.
