### ISSUE TITLE
[sw/silicon_creator] Remove `lifecycle_state_name[]`

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#9429]
We need to update a handful of places (2, I think, mask_rom.c and keymgr_functest.c) where we use `lifecycle_state_name[]`. It looks like this didn't cause any failures though. IMHO we can remove them unless we really want to print the life cycle state in mask rom. @moidx @mundaym @cfrantz WDYT?

_Originally posted by @alphan in https://github.com/lowRISC/opentitan/issues/9319#issuecomment-975951786_

**Comment by mundaym** [comment]
Removing the printf entirely SGTM. We could also print the raw value.

**Comment by alphan** [comment]
It looks like printing the human-readable state name has been useful so far for debugging. So, I'll create a small PR that preserves current functionality. We can remove the printf later when we review error reporting/printfs in general.
