### ISSUE TITLE
Governance : missing import in Technical Charter

### ISSUE THREAD

**Issue by evelynmitchell** [lowRISC/opentitan#943]
In the OpenTitan Technical Charter, the lowRISC Articles of Association are incorporated by reference in section: Compliance with Policies
" This Charter is subject to the lowRISC CIC Articles of Association."

I can't find the lowRISC Articles of Association on the lowRISC site, or in any of the github repositories.

It should be included in the OpenTitan governance documentation repository.

**Comment by asb** [comment]
Hi Evelyn, you can find lowRISC CIC's Articles of Association [on Companies House](https://beta.companieshouse.gov.uk/company/09272283).

**Comment by imphil** [comment]
Thanks for your report. I've opened https://github.com/lowRISC/lowrisc-web/issues/40 to get this content added to the main lowRISC web site, which I think is the best place to put it.

Does that sound like an acceptable solution to you?

**Comment by evelynmitchell** [comment]
Yes. That's a good idea.

Evelyn Mitchell
