### ISSUE TITLE
[lc_ctrl] State error bit of status register not set for forced FSM state

### ISSUE THREAD

**Issue by NigelScales** [lowRISC/opentitan#9431]
It appears that the state error bit of the status register is not set in the case of an invalid FSM state as the result of tampering.
Alerts are not triggered either.

The register description states:
<html>
<body>

STATE_ERROR | This bit is set to 1 if either the controller FSM state or the life cycle state is invalid or has been corrupted as part of a tampering attempt. This error will move the life cycle state automatically to ESCALATE and raise a fatal_state_error alert.
-- | --

</body>
</html>

Looking at the FSM code the transition to InvalidSt can be effected in 2 ways.
1. As the result of any of the state_invalid_error bits being set.
2. Due to an unknown state being detected in the FSM.

Only case 1 sets the state_invalid_error_o which appears to be the trigger for the STATE_ERROR flag being set and alerts generated.

**Comment by NigelScales** [comment]
Added draft PR to reproduce issue:
https://github.com/lowRISC/opentitan/pull/9433

To reproduce issue:
./util/dvsim/dvsim.py hw/ip/lc_ctrl/dv/lc_ctrl_sim_cfg.hjson -i lc_ctrl_state_failure --waves --fixed-seed 1 --max-parallel 1 --run-opts "+max_quit_count=10" -v m --tool xcelium

**Comment by NigelScales** [comment]
tb.lc_ctrl_if.fsm_backdoor_state_write_ev shows when the force is being applied.
The TB reads the FSM state registers then flips some of the bits before forcing the result back.

![image](https://user-images.githubusercontent.com/78102677/144099756-668d40b8-ceb4-4235-acad-ba32a55a562d.png)

**Comment by tjaychen** [comment]
@tjaychen

**Comment by msfschaffner** [comment]
Thanks for reporting this @NigelScales.
There indeed seems to be a discrepancy between docs and actual behavior.
I have corrected this in #9440. PTAL.

**Comment by NigelScales** [comment]
Thanks @msfschaffner I'll try it out in #9433

**Comment by NigelScales** [comment]
@msfschaffner 
It looks like it fixed it.

![image](https://user-images.githubusercontent.com/78102677/144224388-bd8a5cfc-546d-4422-a853-e952092bec6c.png)
