### ISSUE TITLE
[prim] switch to prim_sparse_fsm

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9447]
Follow-on from #9364 
- [x] lc_ctrl (#9474)
- [x] otp_ctrl (#9474)
- [x] alert_handler (#9474)
- [x] entropy_src (#9505)
- [x] edn (#9505)
- [x] csrng (#9505)
- [x] kmac (#9394)
- [x] aes (#9632)
- [x] rom_ctrl (#9625)
- [x] flash_ctrl (https://github.com/lowRISC/opentitan/pull/8230)
- [x] rstmgr (https://github.com/lowRISC/opentitan/pull/10175)
- [x] pwrmgr (https://github.com/lowRISC/opentitan/pull/10175)

**Comment by tjaychen** [comment]
@msfschaffner 
@eunchan 
@cindychip 
@weicaiyang 
@matutem 
@sriyerg 
FYI

**Comment by msfschaffner** [comment]
@vogelpi for AES

**Comment by m-temp** [comment]
@tjaychen kmac: https://github.com/lowRISC/opentitan/pull/9394 has been merged.

**Comment by msfschaffner** [comment]
@tjaychen I believe all blocks above have moved to sparse FSMs by now, right?

**Comment by tjaychen** [comment]
yeah looks like.
