### ISSUE TITLE
[rom_ctrl] Integrity Check in non-PROD LC_STATE

### ISSUE THREAD

**Issue by davebwil** [lowRISC/opentitan#9455]
For the top level test case "chip_sw_rom_ctrl_integrity_check"

The test description states the following should be checked:
"- In non-PROD LC state, the computed digest does not have to match the top 8 words in
  the ROM. Verify that we can successfully power up the chip in this case.
- In PROD LC state, verify that the pwrmgr does not fully power up if the computed
  digest does not match the top 8 words of the ROM."

In the ROM Controller Technical Specification in the section "What does the ROM check do?" there is the following:
"After bringing the ROM controller module out of reset, the power manager must wait until pwrgr_data_o.done is asserted before starting the host processor. In PROD state, it will also check that pwrmgr_data_o.good is On: if not, it will refuse to boot."

This implies that the good signal is only checked in PROD state and therefore the test description makes sense.

After writing some code for the toplevel test it was seen that if there is a backdoor overwrite of the expected digest in the ROM
at the start of the test then it fails to boot even in non-PROD state.

RTL inspection would seem to indicate that rom_ctrl nor pwrmgr take LC_STATE into account when handling the good/done signal.

Is this feature yet to be implemented or is the spec. and test description incorrect?

**Comment by rswarbrick** [comment]
@tjaychen: This is really a question about pwrmgr's behaviour. Can you help?

**Comment by tjaychen** [comment]
@rswarbrick i honestly cannot remember if we settled on whether during non-prod state we should bypass the check.
Do you happen to remember? If we decided this is something we were supposed to do, then the function is definitely missing in pwrmgr at the moment.

**Comment by rswarbrick** [comment]
That's what's documented in the `rom_ctrl` spec as what we expect. But, as I see it, this is a policy decision for pwrmgr. I'd probably suggest this behaviour so that if we screw things up in the ROM for some reason we don't have a completely dead chip :-)

**Comment by tjaychen** [comment]
that sounds good.
Then this is a bug as in I completely forgot this feature :)

**Comment by tjaychen** [comment]
> That's what's documented in the `rom_ctrl` spec as what we expect. But, as I see it, this is a policy decision for pwrmgr. I'd probably suggest this behaviour so that if we screw things up in the ROM for some reason we don't have a completely dead chip :-)

hat sounds good. 
Then this is a bug as in I completely forgot this feature :)

**Comment by tjaychen** [comment]
@matutem 

it looks like this is something that slipped through and I will need to add to pwrmgr.  The addition is very minor, but it will definitely impact coverage.
