### ISSUE TITLE
[tests] plic_all_interrupts failing on verilator

### ISSUE THREAD

**Issue by doreis-lowrisc** [lowRISC/opentitan#9461]
## Problem
The test `plic_all_irqs_test_sim_verilator.elf` is failing on master branch when running in the verilator although it is passing in the CI

## Step by step to reproduce the error:
- Update master branch `git pull --ff-only upstream master`
- Run meson `./meson_init.sh -Af` 
- Build verilator `fusesoc --cores-root . run --flag=fileset_top --target=sim --setup --build lowrisc:dv:chip_verilator_sim`
- Build SW `ninja build-out all`
- Run test 
```
build/lowrisc_dv_chip_verilator_sim_0.1/sim-verilator/Vchip_sim_tb \
--meminit=rom,build-bin/sw/device/boot_rom/boot_rom_sim_verilator.scr.39.vmem \
--meminit=flash,uild-bin/sw/device/tests/plic_all_irqs_test_sim_verilator.elf \
--meminit=otp,build-bin/sw/device/otp_img/otp_img_sim_verilator.vmem 
```
## Error log
```
�I00000 boot_rom.c:54] Version:    opentitan-earlgrey_silver_release_v5-2186-g40b607b77
Build Date: 2021-12-01, 12:12:52

I00001 boot_rom.c:70] Boot ROM initialisation has completed, jump into flash!
IE00000 plic_all_irqs_test.c:159] CHECK-fail: Interrupt from incorrect peripheral: exp = 19, obs = 1
I00001 test_status.c:34] FAIL!
```

I'm not sure if I'm not doing something wrong or my local environment is broken. Then It would be great if someone else test it.

**Comment by doreis-lowrisc** [comment]
@mundaym for visibility

**Comment by sriyerg** [comment]
Yes, it needs to be debugged. I had opened #8656 to track this.

**Comment by mundaym** [comment]
Ah, thanks, sorry for the noise. Closing as a duplicate.
