### ISSUE TITLE
[sram_ctrl] Consider merging INIT with RENEW_SCR_KEY

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#9464]
I'm not sure that there is a software benefit to having separate INIT and RENEW_SCR_KEY fields in the sram_ctrl.CTRL register. It might make sense to merge them to reduce the number of options in the interface.

Low priority but I wanted to flag it in case it makes writing tests easier because there is no need to test both options separately if they are merged.

**Comment by tjaychen** [comment]
i'm not too sure of the dv status now, but i would prefer not to change this if DV has progressed far enough already.
We could for now make it clear in the programmer's model that these should always be done at the same time and thus allow us to waive some potential coverage?

**Comment by msfschaffner** [comment]
Indeed, I would also prefer not touching the CSR interface anymore.

Just noting that a key request always incurs some latency due to EDN and OTP involvement.
Hence, being able to trigger these mechanisms individually may be useful if we ever have a case where the INIT / wiping should start right away.

**Comment by andreaskurth** [comment]
Triaged for `sram_ctrl`. Suggest tagging this https://github.com/lowRISC/opentitan/labels/Type%3AIcebox to clarify (post M2.5) in SW and documentation that the bits are intended to be used together, as discussed above.

**Comment by msfschaffner** [comment]
Since we are using SRAM_CTRL in multiple ways now (e.g., retention, main, mailboxes), their use cases are different.
E.g. there are SRAMs where we intentionally want to trigger only INIT, but without RENEW_SCR_KEY.
Hence I think it makes sense to leave this as-is.
