### ISSUE TITLE
[top,tlul] Breakup top level fabric into multiple components

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#948]
Currently, top level fabric is composed of one component.  When there are many peripherals in a separate clock domain, this creates many crossing points, especially when a host is able to reach a variety of peripherals.

It would be beneficial to breakup the fabric into multiple components that each serve a specific domain; in the future, it may make even more sense to further sub-divide into power or testing domains.  So for now, we should take the basic step and make sure the infrastructure is ready. 

This will likely have DV implications as we would need to verify more than one fabric.

cc @weicaiyang @sriyerg

**Comment by weicaiyang** [comment]
Thanks for the heads-up @tjaychen 
Yes, we have expected more than one fabric, so we also plan to do automation for xbar.
Multi-clock domain is another thing we need to update TB to support.

**Comment by tjaychen** [comment]
i'm hoping to have a look at this soon-ish! so will keep you posted!

**Comment by sjgitty** [comment]
Thanks for raising this. Yes, it will be needed. Not sure when, but
eventually, and maybe soon.
Worth preparing the infrastructure.

**Comment by tjaychen** [comment]
@eunchan 
continuing the discussion from #903 ..

how do you envision the multi-xbar working? The way I looked at it was as follows... let me know what you think.

- we would have multiple xbar_*.hjson files
- tlgen would still generate each individual xbar based on that configuration
- topgen would then stitch the various pieces together in top_*
  - this implies the xbars will sit as individual instantiations at the top level.  I think this is a bit more flexible for now (instead of 1 wrapping instance with all components underneath) since the organization might change again in the future to more clustering. 
  - in this world, as part of the stitching, the xbars really just look like another peripheral with more connecting ports.

Let me know what you think.

@weicaiyang, could you also clarify a bit what you were expecting? For example was DV expecting one monolithic module called 'fabric'? Or you are okay with separate instances as well.

**Comment by weicaiyang** [comment]
@tjaychen 
I plan to generate separate TBs for different flavors of xbar based on xbar_*.hjson. Need to set up regression for each xbar, so one xbar will have one generated TB.
Will use current design script to do that.

**Comment by tjaychen** [comment]
i think this is already done...awhile ago.
Should we close this now @eunchan ?

**Comment by eunchan** [comment]
Yeah. let's close.
