### ISSUE TITLE
[rom] Populate entropy_src health test settings

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9492]
The following is the high level boot flow regarding the entropy complex (courtesy of @moidx).

**High Level Boot Flow - Software** 

- ROM
   - EDN0 in BOOT_REQ_MODE to enable downstream consumers (SRAM scrambling, et al). Done in assembly.
   - Cheap & fast entropy required by software for countermeasures against fault attacks.
   - Periodic expectation checks for critical registers. This may include entropy complex configuration registers.
- ROM_EXT
   - Cheap & fast entropy required by software for countermeasures against attacks.
   - If attestation or ownership transfer (this is a conditional slow boot path):
      - FIPS: entropy_src.conditioner KAT test. (possibly using the FW OVR and ENTOPY_DATA interface).
      - FIPS: csrng KAT test, utilizing the sw instance (e.g. #7505)
      - FIPS: enable entropy_src in FIPS mode, GetHealthTest results.
      - FIPS: crypto operations: csrng software instance and/or EDN1.
   - Periodic expectation checks for critical registers. This may include entropy complex configuration registers. 
- Silicon Owner software (BL0 or Kernel):  Same as ROM_EXT

For the cheap / fast entropy in ROM, there needs to be some additional configuration of entropy_src health test settings.
These should be read out from OTP and programmed into entropy_src.

We will have to define a simple / light-weight scheme to check there is data in OTP and copy over, done in assembly.
When the C-runtime is initialized, we then need to do consistency checks to make sure what's programmed matches what's in OTP.

**Comment by tjaychen** [comment]
@martin-lueker 
@cfrantz 
@moidx 
@cdgori 
@zi-v

**Comment by martin-lueker** [comment]
Thanks for opening this @tjaychen.  If we break this down fully we have three IPs that need to be configured (`entropy_src`, `csrng`, and `edn`), and for these three IP's there is are two portions to this issue (`ROM` and `ROM_EXT`).   I can start by enumerating these here, at least for the ROM. @mwbranstad, please confirm the following.

- `entropy_src`
    1. The following 16-bit register fields need to be populated from OTP:
         `entropy_src.REPCNT_THRESHOLDS.BYPASS_THRESH`,
         `entropy_src.REPCNTS_THRESHOLDS.BYPASS_THRESH`,
         `entropy_src.ADAPTP_HI_THRESHOLDS.BYPASS_THRESH`,
         `entropy_src.ADAPTP_LO_THRESHOLDS.BYPASS_THRESH`,
         `entropy_src.BUCKET_THRESHOLDS.BYPASS_THRESH`,
         `entropy_src.MARKOV_HI_THRESHOLDS.BYPASS_THRESH`,
         `entropy_src.MARKOV_LO_THRESHOLDS.BYPASS_THRESH`,
         `entropy_src.EXTHT_LO_THRESHOLDS.BYPASS_THRESH`,
         `entropy_src.EXTHT_HI_THRESHOLDS.BYPASS_THRESH`,
         `entropy_src.ALERT_THRESHOLD.ALERT_THRESHOLD`,
         `entropy_src.ALERT_THRESHOLD.ALERT_THRESHOLD_INV`
     2. Enable the `entropy_src` by writing `kMultiBitBool4True` to `entropy_src.CONF.ENABLE`
     3. TBD: Are there health check monitors that are needed at boot time?  How should we handle alerts at this point? 
 - CSRNG: Write `kMultiBitBool4True` to `CSRNG.CTRL.ENABLE` (EDN will handle the rest)
 - EDN: Write `kMultiBitBool4True` to `edn.CTRL.EDN_ENABLE`

**Comment by mwbranstad** [comment]
The list fields above look reasonable, except that we may not want to write the EXTHT thresholds since they are currently not used. Also, EDN0 will need to have the BOOT_REQ_MODE field set  (in ROM code). CSRNG will need to have SW_APP_ENABLE and READ_INT_STATE fields enabled in ROM_EXT in order to do KAT.

**Comment by tjaychen** [comment]
thanks all!
@alphan @moidx we will probably want to provision fields for this in the OTP

**Comment by cdgori** [comment]
@mwbranstad / @martin-lueker can you guys comment on:
> Periodic expectation checks for critical registers. This may include entropy complex configuration registers.
- basically which regs would be good to inspect here?

I want to make sure we have an idea of what to inspect/check before the REGWEN is ultimately set.  From this morning's discussion that should be in ROM_EXT, so these same checks should also occur in ROM_EXT up to the point the REGWEN is set.  I would think CONF, ENTROPY_CONTROL, FW_OV_CONTROL are all candidates.

**Comment by martin-lueker** [comment]
Hi @cdgori,
   I'm hesitant to insist on any monitor happening in the boot ROM, for fear we get it wrong (there is a lot we won't know about the RNG as it is an analog component).    We are already putting together a PR to ensure that the settings in established the boot ROM do not get used for fully-qualified entropy.  The IP will go through its minimal boot-grade health checks, but it will not certify anything as "FIPS" until the ROM_EXT gets a chance to update the settings.    Given that the boot grade entropy requirements are more relaxed I for one am not too concerned here.  
   Regarding after that, I'm not sure.    The total fail counts and watermarks could be interesting once we have more experience, but those are only interesting in the context of "We have lots of experience with this silicon and we know what to expect.  
   I'm not sure why you'd want to _monitor_ the CONF, ENTROPY_CONTROL, and FW_ON_CONTROL regs, are you suggesting that we should add them to things to update in the BOOT_ROM and ROM_EXT?  You certainly will want to update those in the ROM_EXT.   (In general though I feel like I would be far more comfortable talking about finalizing the ROM_EXT once we have silicon data _it might even be better to handle that in a separate issue_)   
   It wouldn't hurt to just set all of CONF, MODULE_ENABLE (new reg proposed in #9949), and CONTROL in BOOT_ROM.   
   FW_OV_CONTROL, however, is special.  You can't use that without monitoring, and the whole point is that it is supposed to improve upon the health checks in the event we learn something about RNG behavior that we can't manage with the information we have now pre-silicon.   However using it from the BOOT_ROM doesn't make much sense then.  (Unless you want to consider a respin of the BOOT_ROM only).  If we knew enough today to  plan to use FW_OV_CONTROL, then we could just make better health checks.   So: that's just another potential item for improving fully-qualified entropy in ROM_EXT, if we need it.

**Comment by mwbranstad** [comment]
i thought the original motivation to do periodic checks on ES registers was to save flops and not use the shadow reg feature. Instead, just verify the values written periodically. It seems simple enough to just check all written registers (probably exclude status registers). The scheme could apply to all entropy complex blocks.

**Comment by cdgori** [comment]
Sorry for not replying here long ago, closing out some stuff in my spare time this week ;)

> Hi @cdgori, I'm hesitant to insist on any monitor happening in the boot ROM, for fear we get it wrong (there is a lot we won't know about the RNG as it is an analog component). 

This is fair.

> I'm not sure why you'd want to _monitor_ the CONF, ENTROPY_CONTROL, and FW_ON_CONTROL regs, are you suggesting that we should add them to things to update in the BOOT_ROM and ROM_EXT? 

It's what @tjaychen / @mwbranstad said - we can't assume they are set to the proper values so we need to periodically have a look.  The alternative was to burn gates on shadow reg to detect glitch attempts instantly but we decided that wasn't a good use of resource here, so we need to have software come through and check.  As noted above, OK to defer the monitor task/loop to something well after BOOT_ROM or even ROM_EXT, but we do have to do it somewhere in normal functional mode.
