### ISSUE TITLE
[nmi_gen/alerts] Replace nmi_gen wrapper module with actual escalation endpoints

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#950]
This is related to PR #894. The current system does not have "true" endpoints for the escalation signals and hence an `nmi_gen` wrapper module has been constructed such that these signals can be tested. This module should be replaced by the actual escalation endpoints and countermeasures in the future.

**Comment by tjaychen** [comment]
this is almost possible now with #4611 
The `nmi_gen` don't really have a function anymore other than acting as a stand-in for blocks like `rbox, aon timer` to simulation a module that is capable of requesting resets.

One either one of those modules are integrated, we can officially deprecate nmi_gen.

**Comment by tjaychen** [comment]
`nmi_gen` has now been removed and the escalation goes directly into `pwrmgr` for resets. 
There are also escalations that go directly to `lc_ctrl`.  This issue can be closed.
