### ISSUE TITLE
[dv] mem test enhancements

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#9532]
As discussed with Tim, we can consider to add these 2 enhancements, but these seem not very urgent.

1. Test RO/WO memory from backdoor. Currently we only test memory from front-door for RW type memory in existing automatic mem/csr tests. For RO/WO memory, only error cases (such as writing to RO mem or reading WO mem will result in d_error=1) are covered by tl_error test and we rely on block owners to create the test to verify the other functionality.

2. We don't support excluding a memory in automatic mem/csr tests. If we can test RO memory from backdoor in automatic tests, we need to exclude the RO memory in flash_ctrl, as it will trigger an error if SW reads or writes more than what it's configured.

@tjaychen @sriyerg @cindychip @matutem 

> estimate 16

**Comment by tjaychen** [comment]
thanks for filing the issue Weicai.

**Comment by GregAC** [comment]
estimate range: 8 - 16

**Comment by vogelpi** [comment]
This issue is super old and it doesn't seem relevant anymore. I am thus closing it. Please feel free to reopen it if you disagree @matutem .
