### ISSUE TITLE
[reggen] We are discarding data integrity from windows in reg_top modules

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#9538]
The generated reg_top modules unconditionally use a `tlul_rsp_intg_gen` instance to add response integrity (fine!) and data integrity (oh no!) bits to all responses. Including those that come from memory windows.

This discards the stuff that we thought we were passing through. Oops! See #9537 which describes this happening for `rom_ctrl`. It also happens for (at least) OTBN.

**Comment by rswarbrick** [comment]
@tjaychen, @msfschaffner: I'm going to scramble to sort out the `rom_ctrl` version of this (which currently makes fixing this awkward). But I think we probably need to figure out a nice way to handle it in the `reg_top` modules.

Maybe it's as simple as muxing the `d_user.data_intg` field of `tl_o` between `tl_o_pre` and some newly named output from the integrity generator? Or maybe it would be cleaner to add a `passthru_i` input to `tlul_rsp_intg_gen` which we could set when the data came from a window? Or maybe we should unconditionally pass the data integrity through and add it explicitly on the register side? Not sure what would be better.

**Comment by tjaychen** [comment]
@rswarbrick i commented in one of your PRs.. hehe
This again is an issue of me and documentation... hope to fix soon. 

This option that `otbn` is using in theory should address this on the windowed connections.
https://github.com/lowRISC/opentitan/blob/master/hw/ip/otbn/data/otbn.hjson#L493

Let me know if it resolves what you're seeing.

**Comment by rswarbrick** [comment]
Yeah, this was user error on my part. Thank goodness!
