### ISSUE TITLE
[syn] Check whether synthesis optimization barriers still behave as intended in final netlist

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#9541]
As pointed out by @cdgori when reviewing #9540 , it will be important to check that synthesis optimization barriers still behave as intended in the final netlist. There is always a risk that between the time we've developed them and the tapeout, something in the tooling or RTL is changed that unintentionally removes some of these barriers thereby disabling the countermeasures.

This check can be based on e.g. FI simulation experiments and/or some analysis scripts.

**Comment by msfschaffner** [comment]
@nasahlpa FYI

**Comment by tjaychen** [comment]
yes i believe @msfschaffner has this in the tapeout checklist.  We will need to manually walk over the final synthesized netlist to make sure everything we intend to be there is still there. 

In the past I have not personally done an exhaustive check, but more of a spot check. Shall we start maintaining a doc somewhere (or can it be open) on the things to check? I feel like open should be fine because the RTL makes it pretty clear where we want such behaviors.

**Comment by vogelpi** [comment]
Starting a shared doc would be great. Maybe it's better to be cautious and not start it in the open right away though.

**Comment by tjaychen** [comment]
yeah agreed. We are really close to feature complete, so i think after that we can start creating these check items.

**Comment by tjaychen** [comment]
@arnonsha do you have any thoughts on the best way to close this?
We will not be able to see your final netlist, so does it make sense for us to create a list so that you guys can double check?

**Comment by arnonsha** [comment]
So far I don't think there's a doc describing what needs to be checked, but I believe  @vogelpi idea is the way to go:
_"This check can be based on e.g. FI simulation experiments and/or some analysis scripts.".

Depending on what should be verified, we can think of what is the best way

**Comment by cdgori** [comment]
This was one of the main things I was thinking about in #6369

**Comment by tjaychen** [comment]
given the nature of this issue, it probably automatically needs to be moved to a post M3 world since it will happen after rtl freeze. I'll lower the priority for now.

**Comment by msfschaffner** [comment]
This is part of the generalized tapeout checklist - hence I don't think we need to keep this anymore.
For ES, we did an audit of several different mechanisms to check that critical signals and flops have indeed not been optimized away.
