### ISSUE TITLE
[dv/tlul] Add transmission integrity negative test for passthrough integrity

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9546]
There are several blocks (`flash_ctrl`, `rom_ctrl`, `otbn`, `sram_ctrl`) where transmission integrity should not be generated in the gasket, but instead stored with the memory itself. 

For these test cases, relying on the common transmission integrity test to pass is insufficient, as we do not know the integrity is actually coming from storage or from the gasket. (@weicaiyang please correct me if I am wrong).

Assuming the above is true, it is necessary to add directed test cases to these blocks where we purposely try to deposit incorrect integrity into the memory, either by changing the integrity or the data. (this will be block specific). This failed integrity should then manifest in a tlul error.  If instead the options / configurations are wrong, this error will not manifest as the gasket will re-generate the integrity for the "wrong" data. 

This is related to a lot of confusion observed by @rswarbrick in #9536.  The reggen utility technically has an option to handle cases like this already, but we need to make sure it
1. is actually working as intended
2. correctly turned on by the modules that need it.

**Comment by weicaiyang** [comment]
> For these test cases, relying on the common transmission integrity test to pass is insufficient, as we do not know the integrity is actually coming from storage or from the gasket. (@weicaiyang please correct me if I am wrong).

you're right. Current common integrity test can't verify the case that the data integrity is from storage.

> Assuming the above is true, it is necessary to add directed test cases to these blocks where we purposely try to deposit incorrect integrity into the memory, either by changing the integrity or the data. (this will be block specific). This failed integrity should then manifest in a tlul error. 

Sorry, I need some clarification here. If the data integrity is wrong, the block won't report d_error=1 as data integrity is checked in ibex. Is it right?

IIUC, I'm thinking to create another common test for data integrity that is from storage.
1. inject data integrity error either from front-door or backdoor. (If it's RO mem, only backdoor. If WO, probably need to test separately, not sure if we have WO mem with integrity in storage)
2. issue a read at the same address and check
  a. if inject error from front-door, read value and integrity should match to what we have written. We shouldn't auto correct the integrity and d_error should be 0.
  b. If inject error from backdoor by flipping some of the bits, the new calculated integrity (based read data) should not match to the one from storage. We shouldn't auto correct the integrity and d_error should be 0.

**Comment by tjaychen** [comment]
> > For these test cases, relying on the common transmission integrity test to pass is insufficient, as we do not know the integrity is actually coming from storage or from the gasket. (@weicaiyang please correct me if I am wrong).
> 
> you're right. Current common integrity test can't verify the case that the data integrity is from storage.
> 
> > Assuming the above is true, it is necessary to add directed test cases to these blocks where we purposely try to deposit incorrect integrity into the memory, either by changing the integrity or the data. (this will be block specific). This failed integrity should then manifest in a tlul error.
> 
> Sorry, I need some clarification here. If the data integrity is wrong, the block won't report d_error=1 as data integrity is checked in ibex. Is it right?
> 
wait, i thought the block level default tlul agent had some kind of integrity checking?

> IIUC, I'm thinking to create another common test for data integrity that is from storage.
> 
> 1. inject data integrity error either from front-door or backdoor. (If it's RO mem, only backdoor. If WO, probably need to test separately, not sure if we have WO mem with integrity in storage)
> 2. issue a read at the same address and check
>    a. if inject error from front-door, read value and integrity should match to what we have written. We shouldn't auto correct the integrity and d_error should be 0.
>    b. If inject error from backdoor by flipping some of the bits, the new calculated integrity (based read data) should not match to the one from storage. We shouldn't auto correct the integrity and d_error should be 0.

yes this definitely works too. I think the only thing we need to make sure if the backdoor injection of flipping bits might need to be extended by the block (for example flash) if it is somewhat non-standard.

**Comment by weicaiyang** [comment]
> wait, i thought the block level default tlul agent had some kind of integrity checking?

Yes, by default the ECC integrity should always match with the data if ECC is generated in the gasket. 
Will turn off that check if ECC is stored in the memory. And check the new calculated integrity (based read data) should not match to the one from storage if we inject errors.

> yes this definitely works too. I think the only thing we need to make sure if the backdoor injection of flipping bits might need to be extended by the block (for example flash) if it is somewhat non-standard.

yes, thinking to create an empty virtual function for backdoor injection and each block owner need to extend it to implement the actual backdoor function.

**Comment by tjaychen** [comment]
> > wait, i thought the block level default tlul agent had some kind of integrity checking?
> 
> Yes, by default the ECC integrity should always match with the data if ECC is generated in the gasket. Will turn off that check if ECC is stored in the memory. And check the new calculated integrity (based read data) should not match to the one from storage if we inject errors.
> 
> > yes this definitely works too. I think the only thing we need to make sure if the backdoor injection of flipping bits might need to be extended by the block (for example flash) if it is somewhat non-standard.
> 
> yes, thinking to create an empty virtual function for backdoor injection and each block owner need to extend it to implement the actual backdoor function.

this all sounds great to me, thanks @weicaiyang.
I wonder though if this will end up integrating with `mem_bkdr_util` somewhat, because that already kind of has the integrity format. The only difference for blocks like flash is it has to flip "other" bits too.

**Comment by weicaiyang** [comment]
> this all sounds great to me, thanks @weicaiyang. I wonder though if this will end up integrating with `mem_bkdr_util` somewhat, because that already kind of has the integrity format. The only difference for blocks like flash is it has to flip "other" bits too.

that's very likely to happen. I will try on the sram_ctrl first.

**Comment by weicaiyang** [comment]
Create a checklist to test passthrough integrity
- [ ] sram_ctrl #9871
- [ ] flash_ctrl
- [ ] rom_ctrl
- [ ] otbn

@rswarbrick @prajwalaputtappa @nikola-miladinovic please follow #9871 to create a integrity mem test to ensure that the integrity is stored in the memory and passed directly to CPU.

**Comment by tjaychen** [comment]
just to clarify, `flash_ctrl` does not completely fall into this category. Because flash does not have enough space to store a plain text integrity. So that one is indeed generated on the fly.  However for flash, we need to check this mechanism still with the truncated integrity.

**Comment by weicaiyang** [comment]
> just to clarify, `flash_ctrl` does not completely fall into this category. Because flash does not have enough space to store a plain text integrity. So that one is indeed generated on the fly. However for flash, we need to check this mechanism still with the truncated integrity.

Thanks for the clarification. looks like we need to override the sequence a bit more in order to test flash_ctrl for this passthrough integrity

**Comment by tjaychen** [comment]
@jdonjdon does this test fall into flash block level now?

**Comment by jdonjdon** [comment]
> @jdonjdon does this test fall into flash block level now?

@tjaychen , I will update in this thread after sync up with @weicaiyang

**Comment by jdonjdon** [comment]
@tjaychen , @weicaiyang 
flash has directed test for this.
https://github.com/lowRISC/opentitan/blob/044b8e8cb9f2505d48870dbf697ba06cdfbd5e8d/hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson#L359

Test check whether dut can identify corruption of integrity check value or 
mismatch of regenerated integrity check value with stored 4bit value during read operation.
Upon detecting integrity check fail, dut assert fatal alert.
Also error propagate to upstream two different ways.
1. Ctrl Read
Read data stored to read fifo and op_status.err and err_code.rd_err is asserted
at the end of each operation

2. Host Read
This is similar to the other tlul transactions.
Dut mark tlul response as an error.

So this test checks fatal alert and error detection accordingly per each transaction type.
@weicaiyang please update check list(https://github.com/lowRISC/opentitan/issues/9546#issuecomment-1005137613) for flash_ctrl
as done.

**Comment by weicaiyang** [comment]
Thanks @jdonjdon 
Closing this issue now
