### ISSUE TITLE
[entropy_src] Not absorbing all input data

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#9551]
During startup mode, the entropy_src is supposed to absorb at least two health checks worth of raw entropy and run them all through the SHA3 conditioning block before sending them out to CSRNG.

Based on the system defaults (2048 bit health-check window), this means that the SHA3 block should absorb 4096bits (64 * 64 bit windows) before squeezing out the first seed.

In the smoke test sequence, the raw RNG stream consists of the sequence {4'h0, 4'h1, 4'h2, ... 4'he, 4'hf, 4'h0, ...} etc.  meaning that the input to the SHA3 conditioner should consist of 64 iterations of 0xfedcba9876543210 before digesting the final output hash.

However as the waveform below illustrates, the SHA3 is only receiving 63 inputs to absorb.
This yields the output `384'ha5191393_2ba08e3d_545fc305_740d09dc_76bf2778_c52f588c_e0829689_9a61a9b8_dd2d1e75_b1f120d1_d5459da4_ed013e34` (which is indeed the correct for 63 inputs of this format.)

The correct conditioned output should be `384'h9eb6eebf_1fa66c22_68ebae8c_4799f536_da3f9262_99543daa_40df96af_80eb03cb_fad262e8_b037d9bc_f7b7d0a8_f297d799`

![image](https://user-images.githubusercontent.com/47870387/144948169-0dca107a-f8ed-4429-9ed5-72ca71a9969c.png)

**Comment by martin-lueker** [comment]
To reproduce this error:
1.  Fetch the branch `entropy_src_issue_9551` from my fork (`git@github.com:martin-lueker/opentitan.git`)
2. From within that branch, (and within the opentitan project root directory) run the command:
`./util/dvsim/dvsim.py hw/ip/entropy_src/dv/entropy_src_sim_cfg.hjson -i entropy_src_sha -r 1 -t xcelium --job-prefix="nc run -C ncsim_interactive -Il" -w=shm -s=1 --run-modes set_verbosity_comp_a_uvm_debug`

**Comment by martin-lueker** [comment]
FYI: @rasmus-madsen @senelson7

**Comment by mwbranstad** [comment]
Try out the fix here: https://github.com/mwbranstad/opentitan/tree/esshacnt

**Comment by martin-lueker** [comment]
It works!
