### ISSUE TITLE
[pwm/doc] PWM_EN not described in the documentation

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#9554]
in the RTL each channel has its own enable bit - this is not described in the documentation - nor is it shown in the schematic.
or listed in the interface list:
![image](https://user-images.githubusercontent.com/53917183/145023559-565880c9-cc1e-4ad1-a5da-411b318127b6.png)
![image](https://user-images.githubusercontent.com/53917183/145023601-33a8d4b6-cc33-4a8d-af0a-642dd8a91d23.png)

please document how the edge of `cio_pwm_en_o` relates to the edge of `cio_pwm_o`
also the interface name in the documentation should match the actual name

**Comment by rasmus-madsen** [comment]
I also think there is a mistake in a figure.
I think this pulse should be 3 wide?
![image](https://user-images.githubusercontent.com/53917183/145061558-06a2e08a-395e-44d4-8690-3460d65815c2.png)

**Comment by Muqing-Liu** [comment]
> I also think there is a mistake in a figure. I think this pulse should be 3 wide? ![image](https://user-images.githubusercontent.com/53917183/145061558-06a2e08a-395e-44d4-8690-3460d65815c2.png)

Hi Rasmus, I think this figure is correct, since this is the wrap up condition at the beginning. The phase delay is 15 and the duty cycle is 3, phase delay + duty cycle is larger than 16, so it will wrap up at the beginning, these two wide pulse is the left over from the previous cycle, the pulse for this cycle starts from clk 15.

**Comment by martin-lueker** [comment]
regarding the cio_pwm_en_o output.  I think this is a purely formal output, that should always be high.

**Comment by martin-lueker** [comment]
> > I also think there is a mistake in a figure. I think this pulse should be 3 wide? ![image](https://user-images.githubusercontent.com/53917183/145061558-06a2e08a-395e-44d4-8690-3460d65815c2.png)
> 
> Hi Rasmus, I think this figure is correct, since this is the wrap up condition at the beginning. The phase delay is 15 and the duty cycle is 3, phase delay + duty cycle is larger than 16, so it will wrap up at the beginning, this two wide pulse is the left over from the previous cycle, the pulse for this cycle starts from clk 15.

I agree, the first pulse in the sequence will be shorter because of the wraparound.

**Comment by rasmus-madsen** [comment]
Why do we have an output that is always high (should be removed or documented either way)

**Comment by martin-lueker** [comment]
Because that is what topgen expects for fixed outputs all the comportable IO IPs are like this.

**Comment by rasmus-madsen** [comment]
> Because that is what topgen expects for fixed outputs all the comportable IO IPs are like this.

Cool - that makes it worse I will raise this issue to a broader audience
