### ISSUE TITLE
[rtl/pwrmgr] Fix inconsistent state

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#9561]
I think the fast fsm should never be active when the slow state machine is in low power state. However, when sending random streams of resets and wakeups we get to that state. It appears this is because the fast fsm's reset_ongoing_q variable is not cleared once a reset is processed: the flop for reset_ongoing_q is only reset by the pwrmgr's rst_ni input, which is connected to the rstmgr's rst_por_io_div4_n[DomainAonSel], which is Aon, so reset_ongoing_q will remain on once set until the Aon domain is reset, which doesn't happen after an external reset request is processed. Once the pwrmgr get to this situation it gets wedged.

Here are some waves showing the fast fsm active and the slow fsm in low power.
![pwrmgr_image](https://user-images.githubusercontent.com/80294896/145077404-818260e5-87f5-4866-9bad-3de93a62a96b.png)

**Comment by msfschaffner** [comment]
Hey @matutem, indeed this does not seem right.
It looks like we never clear this variable once we complete a valid reset cycle in the fast FSM.

Can you check whether https://github.com/lowRISC/opentitan/pull/9619 fixes this?

**Comment by tjaychen** [comment]
this looks good to me, thanks for the fix.
