### ISSUE TITLE
comportable IPs has undocumented enable output

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#9567]
it has come to my attention that our comfortable IP blocks all have an enable output, that seems to be undocumented.
it is very briefly mentioned in the com portable IP documentation - but the actual behavior is not described anywhere.
and none are listed in the IP documentation.
so it just shows up in the instantiation in the testbench.

we should somehow document the behavior of this. (or even better get rid of them as they seem useless ? )

@rswarbrick do you know where to direct this issue?

**Comment by rswarbrick** [comment]
Can you give the exact port that you're talking about for an example module? (I can't see an "enable" output port on OTBN, for example, but I suspect I'm misunderstanding you)

**Comment by rasmus-madsen** [comment]
for example 
pwm that would be
`cio_pwm_en_o`
for gpio it is
`cio_gpio_en_o`

looking at the IP documentation these are not mentioned a single time - and as far as I can see they do not behave as I initially expected.

**Comment by rswarbrick** [comment]
Ah, right. Well, it appears that each logical "output" or "inout" port on an IP block yields a pair of SystemVerilog ports on the module, called `cio_foo_o` and `cio_foo_en_o`. These all get wired up to the pinmux and, looking quickly, it seems that they are the same width. The first signal is the thing that should be wired out to the pins and the second is a bitwise output enable.

@msfschaffner: I think you have the deep knowledge of pinmux! Have I got this right and is this documented anywhere?

**Comment by msfschaffner** [comment]
Hey @rasmus-madsen. 
These are the output enable signals for all primary outputs that are connected to the pads (either directly as a DIO or through the pinmux as an MIO).
It allows the IP to tristate an output.
If an IP does not make use of that feature, these signals should just be tied to 1'b1 (always enabled).

**Comment by rasmus-madsen** [comment]
@msfschaffner thanks - but we should document this somewere
