### ISSUE TITLE
[alert_lpg] ping_ok not set when alert init is in progress

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#9588]
Hi Michael,

There might be a timing related issue -  ping_request was sent to alert_receiver when alert init is in progress.
This happens when ping request was sent right after exits "InitReq" state, and we did not see ping_ok goes high.

![image](https://user-images.githubusercontent.com/11466553/145277163-aed9de9e-aaea-4dce-9766-9746affa05f1.png)

Please let me know if the sequence has any error.

Reproduce: with this PR (https://github.com/lowRISC/opentitan/pull/9590) and you can run `dvsim.py prim_alert_sim_cfg.hjson -i prim_sync_alert --reseed 1 --seeds 613311722`

Thanks,
Cindy

**Comment by msfschaffner** [comment]
Hey @cindychip, thanks for catching that one.
The linked PR should address the issue.
