### ISSUE TITLE
[doc] build_docs.py failure on Mac

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#9596]
If the filesystem on Mac is not Apple Filesystem (case sensitive), the `build_docs.py` fails as the repo already has `BUILD` file.

We may revise `build_docs.py` to create docs under other directory (maybe `scratch`?)

**Comment by msfschaffner** [comment]
@HU90m @hcallahan-lowrisc do you know whether this is still relevant or can we close it?

**Comment by HU90m** [comment]
Yep, this can be closed
