### ISSUE TITLE
[spi_device/tpm] Payload Size and Write FIFO Depth in TPM mode

### ISSUE THREAD

**Issue by kosta-kojdic** [lowRISC/opentitan#9602]
We have WrFifoDepth parameter of SPI TPM set at 4. Does this mean we shouldn't issue Write Transactions of payload larger than 4 bytes? In current implementation, if we attempt payload larger than 4 bytes, we have wready_o of the write fifo going to 0 after 4th byte as expected.
Strange thing to me is if we have payload larger than 4 bytes, we have xfer_bytes_q still increasing after 4th byte, until we reach payload size, and we are still in StWrite. After it, state goes to End state. Is it expected to increase xfer_bytes even though wready_o is at 0 and clearly we don't have data written to fifo?

**Comment by eunchan** [comment]
Yep. The SCK side just latches incoming traffic and push to WrFifo. TPM spec does not allow the WAIT in the middle of transaction. Either SW should pop the data before the FIFO becomes full, or let it fill and ignore the rest of the data.

FYI, we can change the FIFO size with compile-time parameter. But it is set to 4 as the TPM uses 4B at most. Spec allows up to 64 B, but there's no usage of that yet as far as I know.

**Comment by kosta-kojdic** [comment]
Thanks for clarifying
