### ISSUE TITLE
[spi_device/tpm] TpmEnableWhenTpmCsbIdle_M assertion failure

### ISSUE THREAD

**Issue by kosta-kojdic** [lowRISC/opentitan#9629]
We have this assertion failing in the TPM Write scenario. In the place where it fails it doesn't look to be any irregular behavior. Please check.

To reproduce, we have PR #9626 

Command:
./util/dvsim/dvsim.py hw/ip/spi_device/dv/spi_device_sim_cfg.hjson -i spi_device_tpm_write --fixed-seed 999 --waves --xprop-off -v h --max-parallel 1

**Comment by eunchan** [comment]
Ah.. sorry. the conditio should be `$rose(cfg_tpm_en)` . I will fix it . Thanks
