### ISSUE TITLE
EDN-Auto Boot Mode

### ISSUE THREAD

**Issue by senelson7** [lowRISC/opentitan#9635]
Currently the GEN command that EDN sends to CSRNG defaults to requesting 0xFFF sets of genbits. This is a parameter so can be set at compile time. I'm proposing this be a register value so it can be set without having to recompile. It will allow for verification of auto_boot_mode in a reasonable amount of time and won't require a system reset to interrupt this command.

**Comment by tjaychen** [comment]
that sounds good to me.
