### ISSUE TITLE
[util] Invoke `make_new_dif.py` from `hw/Makefile`

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#9650]
#9370 added documentation for how to add IRQs to an IP. In this PR, we realized the procedure for doing so would be simpler if we invoked `./util/make_new_dif.py --mode=regen --only=autogen` (to re-autogen the IRQ DIFs) from the [`hw/Makefile`](https://github.com/lowRISC/opentitan/blob/master/hw/Makefile). However, upon a quick analysis, we realized that doing so would mean running `make -C hw` from `REPO_TOP` would invoke clang-format, which we want to avoid since this caused issues that #8909 solved (namely, not everyone has the same version of `clang-format` that is run in CI, and this causes PRs to fail the lint checks in CI).

To solve this, I could either:
1. alter the autogen DIFs to not run clangformat  on the specific section of code that causes different outputs for different versions of clang-format (which so happens to be the `#include`s), or
2. I could remove the call to clang-format altogether from the `util/make_new_dif.py` script, or
3. we could update the version of clang-format used in CI to use that packaged with lowRISC toolchain already.

Filing this issue just to track this small cleanup (i.e., this is not urgent). Other suggestions are welcome.

**Comment by msfschaffner** [comment]
Anything left to do here?
