### ISSUE TITLE
[OTBN] Document/Specify Blanking in OTBN documentation

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#9663]

**Comment by ctopal** [comment]
Hi @GregAC is this considered done because of [this part](https://docs.opentitan.org/hw/ip/otbn/doc/#blanking)? If not, it might be better to have it before starting to the verification of blanking.

**Comment by johngt** [comment]
@ctopal could you coordinate with @GregAC and see if this issue indeed is closed or if there is outstanding effort? If so we can link in to the documentation catch all - https://github.com/lowRISC/ibex/issues/1710
Otherwise it looks like it is resolved and so tagging as closed.
