### ISSUE TITLE
[fusesoc/opentitan] Traceback (most recent call last)

### ISSUE THREAD

**Issue by camaabdo** [lowRISC/opentitan#9670]
I try to run FuseSoC on an IP of the opentitan platform and below the result.
Do you know why I have this error? 
I have however launched the command `pip3 install --user -r python-requirements.txt `at the top

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/55259057/145834588-162df4ae-f0ef-4580-9270-5d2a1747c4ab.png">

**Comment by rswarbrick** [comment]
Are you able to create that directory? (run `mkdir -p /Users/cabd/opentitan/build/lowrisc_dv_chip_verilator_sim_0.1` in a terminal). The `os.makedirs` function that's being called from `edalizer.py`, line 111 is trying to do essentially that.

**Comment by camaabdo** [comment]
Thank you for your answer,
When I try to create this command, this is what I get
<img width="1482" alt="Capture d’écran 2021-12-14 à 15 16 28" src="https://user-images.githubusercontent.com/55259057/146015754-fbc32fb3-f7e3-4747-a99e-f56db386ea1c.png">

**Comment by rswarbrick** [comment]
Looks like you don't have permission to write to that path. This isn't really an OpenTitan problem, but looks like some unfortunate system configuration issue on your end. You'll need to be able to create files and directories to build OpenTitan. I'd suggest trying a different directory, or changing some permissions somewhere (I'm afraid I'm not a Mac user, so can't be more specific).
