### ISSUE TITLE
[dv,xcelium] Simulation does not run after compile/elaboration.

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#9693]
#9679 fixed compile / elaboration issues (described in #4230) when running chip-level sims with dvsim / xcelium. However, now it seems the simulation is never kicked off after.

CC @rasmus-madsen @davebwil

**Comment by timothytrippel** [comment]
CC @NigelScales

**Comment by sriyerg** [comment]
This issue can perhaps be closed? Xcelium tests are working now at the chip level.
