### ISSUE TITLE
[doc] docs.opentitan.org 404 message could be improved

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/opentitan#971]
Currently if you type in an incorrect name under docs.opentitan.org, it gives
a funky 404 that could be improved. I put in `https://docs.opentitan.org/hw/project/`
and got:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>
```

**Comment by HU90m** [comment]
We now have an improved 404 (for the main site). See https://github.com/lowRISC/opentitan/pull/17705
