### ISSUE TITLE
[sw/silicon_creator] flash_ctrl_info_page_t enum names for pages available post-manufacturing.

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#9710]
just a note `kFlashCtrlInfoPageWaferAuthSecret` is only defined as such during manufacturing. I am not sure if we want to call it something else for general use.

_Originally posted by @moidx in https://github.com/lowRISC/opentitan/pull/9680#discussion_r769137036_

Note: This also applies to `kFlashCtrlInfoPageFactoryId`.

**Comment by msfschaffner** [comment]
@moidx @timothytrippel @cfrantz anything left to do here?

**Comment by timothytrippel** [comment]
I think the wafer auth secret page needs to stay as a single purpose page, since it has special access permissions enforced by HW (i.e., only writeable in some LC states and readable in others)
