### ISSUE TITLE
[SYSRST_CTRL] No interrupt is raised when combo detect bat_disable action is set

### ISSUE THREAD

**Issue by patel-madhuri** [lowRISC/opentitan#9714]
The combo interrupt status register reads 0 when the combo detect bat_disable action is set. This register gets updated only when the  COM_OUT_CTL_0.interrupt_0 action is set. Below is the piece of code which shows the register is updated only when interrupt to opentitan action is set: 
  assign combo_bat_disable_pulse = cfg_bat_disable_en_i & combo_det_pulse;
  assign combo_ec_rst_pulse      = cfg_ec_rst_en_i & combo_det_pulse;
  assign combo_gsc_pulse         = cfg_rst_req_en_i & combo_det_pulse;
  assign combo_intr_pulse_o      = cfg_intr_en_i & combo_det_pulse;

  assign {combo_intr_status_o.combo3_h2l.de,
          combo_intr_status_o.combo2_h2l.de,
          combo_intr_status_o.combo1_h2l.de,
          combo_intr_status_o.combo0_h2l.de} = combo_intr_pulse;

  assign sysrst_ctrl_combo_intr_o = |combo_intr_pulse;

This also applies when ec_rst, rst_req actions are set.

**Comment by patel-madhuri** [comment]
Command to run the test
./util/dvsim/dvsim.py hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson -i sysrst_ctrl_combo_detect --waves --tool xcelium --fixed-seed 4028571893

PR9586 can be used to generate the scenario.

**Comment by msfschaffner** [comment]
Indeed, I believe this is not a bug but intended behavior. I.e., if the interrupt is not configured as a combo action, the interrupt status register will not be updated.

**Comment by patel-madhuri** [comment]
Ok got it. In order to check if the other combo action is raised when interrupt is not configured as a combo action can we use below signals from top level: 
1. aon_bat_disable_hw  - To check if bat_disable action is raised after detecting the combos
2. aon_ec_rst_l_hw - To check ec_rst action
3. aon_sysrst_ctrl_rst_req_o - To check rst_req action
4. combo_status_register - To check interrupt action

**Comment by msfschaffner** [comment]
Indeed, signals 1. - 3. can be used to check whether the associated action is triggered or not.
Note however that 1. and 2. go through the output override module - so their value depends on whether the outputs are overridden or inverted.

As for 4.: these CSRs are only set if the interrupt combo action is configured, as far as I can tell from RTL.

**Comment by patel-madhuri** [comment]
I just noticed signals 1 and 2 are local signals to combo detect modules, so we can't use them to check in the tb as these are not brought up at the top level. Is there any other register/signals from the top level which can tell us that bat_disable or ec_rst combo action is set? 

For 4. Can we add this point to specification document?

**Comment by msfschaffner** [comment]
Hey @patel-madhuri,

`aon_bat_disable_hw`, `aon_ec_rst_l_hw` are indeed internal, but they are observable at the `sysrst_ctrl` output as well. I.e., these internal signals go through the override logic and inverter blocks, and are then output via `cio_bat_disable_o` and `cio_ec_rst_l_o`, see below:

![image](https://user-images.githubusercontent.com/41358501/147361307-20eb7d00-0efd-4294-96df-28c3af069605.png)

As for 4., yes I can add it to the CSR description: #9824
