### ISSUE TITLE
Question about flash_ctrl ECC, scrambling and write patterns

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#9729]
In `boot_data.c`, we invalidate the previous entry in a flash info page after writing a new entry. Currently, this is implemented by writing `0` to a previously written 32-bit word in flash (see this [line](https://github.com/lowRISC/opentitan/blob/4f1f5740d1bad29053e7a2a6cdb1b6e3c78d5606/sw/device/silicon_creator/lib/boot_data.c#L236)). Since each entry has a digest, this change results in a digest mismatch, invalidating the entry. This is based on the assumption that unprogrammed bits can be programmed to `0` (assuming the actual flash memory allows this), while the other way around requires an erase.

Enabling ECC and scrambling breaks this simple scheme, as expected, since IIUC these features store some additional data, which is also stored in flash, and the second write is no longer a `1` to `0` transition for all the bits involved. To understand how the current implementation should be modified for ECC and scrambling I performed three simple tests:

1. Double 32-bit write: Just to capture the current implementation, two write transactions to the same 32-bit word address:
   1. Write `0x0a0a0a0a`.
   2. Write `0` to the same address.
2. Non-linear 32-bit write: Write 4 32-bit words in three transactions:
   1. Write `data[0]` to offset `0` (byte offset from the start of the info page).
   2. Write `data[2], data[3]` starting at offset `8`.
   3. Write: `data[1]` to offset `4`.
3. Non-linear 64-bit (flash word size) write: Write 4 32-bit words in two transactions: 
   1. Write `data[2], data[3]` starting at offset `8`.
   2. Write: `data[0], data[1]` starting at offset `0`.

The table below summarizes my findings:

| Case | Without ECC or Scrambling | With ECC | With Scrambling | With ECC & Scrambling |
|-|-|-|-|-|
| Double 32-bit write | Ok | Flash error | Bad data | Flash error | 
| Non-linear 32-bit write | Ok | Flash error | Bad data | Flash error | 
| Non-linear 64-bit write | Ok | Ok | Ok | Ok | 

I was a bit surprised with the results of the second test (writing `data` word-by-word in 4 separate transactions in a linear fashion also produces the same result). SW and flash words have different sizes but I think this is something that could be emphasized more in the flash_ctrl HWIP spec: When ECC and/or scrambling is enabled, SW should not write to a previously written 64-bit flash word. We should also clarify if this is OK or not when ECC and scrambling are disabled. Apologies if this is already in the spec and I missed it.

My current plan is to add a 64-bit aligned 64-bit field to `boot_data_t` that will be skipped during the first write and will be written in a separate transaction for invalidation at a later time. Do you see any problems with this approach?

cc @moidx @cfrantz

**Comment by tjaychen** [comment]
@alphan just to confirm, in the non-linear 32-bit case above, the writes to offset `0` and `4` are probably going to cause an issue, but the write to those starting at offset `8` should be correct right? 

As you say, a write to another previously written flash word will cause an issue, and i can definitely enhance the spec to clarify that.

**Comment by alphan** [comment]
> @alphan just to confirm, in the non-linear 32-bit case above, the writes to offset `0` and `4` are probably going to cause an issue, but the write to those starting at offset `8` should be correct right?

Yes, writing 64-bits in a _single_ transaction starting at offset `8` works.

> As you say, a write to another previously written flash word will cause an issue, and i can definitely enhance the spec to clarify that.

Thanks @tjaychen!

**Comment by tjaychen** [comment]
@alphan can we close this issue now? or is there anything open we have not answered?

**Comment by tjaychen** [comment]
i'll close this for now, but let me know if there's anything pending and we can re-open.
