### ISSUE TITLE
[spi_device] Passthrough to use outclock-ed `addr_swap_en`, `payload_swap_en`

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#9741]
The current data swap logic inside the passthrough module uses `cmd_info` data structure directly.
The `cmd_info` is latched in SPI Input clock when the 8th command is received.

So, STA analyzes the timing path from INPUT clock to SCK output clock. The output delay of the pads is greater than the half clock cycle due to the huge external delay (PCB -> downstream device and return).

The logic shall be latched into SCK output clock.

Reported by @arnonsha 

CC: @tjaychen

**Comment by msfschaffner** [comment]
@eunchan can this issue be updated or closed?
