### ISSUE TITLE
[dv] Cleanup chip-level test point names to better indicate test type.

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#9744]
As indicated in #9717, the chip-level [test plan](https://docs.opentitan.org/hw/top_earlgrey/doc/dv/#testplan) contains a mix of the SW and connectivity test types. All _software_ tests have a test point name that begins with the prefix `chip_sw_`, while those that are not software tests just begin with the prefix `chip_`. Tests that are _not_  software level tests, are _implied_ to be connectivity tests. Making matters worse some connectivity test point names have the suffix `_conn` (e.g., `chip_flash_jtag_conn`), others have the entire word `connectivity` somewhere in the test point name (e.g., `chip_spi_device_connectivity_with_ast`),  and others (like the test point: `chip_rom_ctrl_ast_rom_cfg`) do not have any indication it is a connectivity test in the name. Upon reading the _description_ field for a test point it becomes clear if a test should be a connectivity test or not, but perhaps a common prefix like `chip_fpv_` (since connectivity tests are run with the formal flow) would make this distinction more clear.

**Comment by timothytrippel** [comment]
CC @cindychip @sriyerg @davebwil

Just an FYI (I can make this change). Filing an issue to track.

**Comment by timothytrippel** [comment]
As discussed offline, @sriyerg will make updates to the testpoint names in the testplan to resolve this.

**Comment by sriyerg** [comment]
[Side note] Tests not prefixed with `chip_sw` are not necessarily all connectivity tests. We have SystemVerilog-only tests that keeps the CPU held in suspended animation while our SV-based TL agent actuates the chip pretending to be the CPU.
