### ISSUE TITLE
CI failure due to reg header mismatch

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#975]
Eunchan wrote in https://github.com/lowRISC/opentitan/pull/974#issuecomment-553587153

> The failure comes from the mismatch of the generated register modules. I intentionally omitted GPIO, UART, RV_TIMER registers in previous PR as those IPs were signed off and we didn't discuss how to handle the scripting tool upgrade completely.

@eunchan What's the plan? Back out the change, or follow up with a fix in the next couple of hours?

**Comment by eunchan** [comment]
Plan is to remove the checks for signed off IPs temporary. Will roll back after the versioning strategy is established.

**Comment by asb** [comment]
I think after our recent discussion on versioning, we now want to unfreeze these these generated files. CC @sjgitty.

Though given the initial reported issue is resolved by #977, it may make sense to mark this issue closed and create a new one to track that.

**Comment by sjgitty** [comment]
Yes, let's do that in a separate PR, perhaps after I get the versioning wording updated.

**Comment by eunchan** [comment]
I am closing this issue as IP versioning #1009 is adopted and the signed-off IPs were  updated #1012
