### ISSUE TITLE
[otbn] Verify that software doesn't assume pre-initialized register files

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#9751]
In #9472 we ran into issues related to Vivado not correctly handling non-zero initialization constants for wide register files implemented with FPGA LUTRAM on OTBN. As a result, the ECC checking logic on the bignum RF was firing upon the first read of an improperly initialized wide register, causing a fatal alert. If the register is first written, the initialization doesn't matter. Interestingly simple tests like the randomness test were passing CI whereas more complex tests like the RSA routine did not.

The initialization on FPGA is now fixed. But it's probably worth checking that also these more complex routines don't make any assumptions on the contents of the regfiles after reset. To this end, one could:
1. Again mess up the initialization value of the ECC bits,
2. Launch OTBN and wait for the alert
3. Read out the OTBN instr count (`INSN_CNT` register) from Ibex. This register indicates the number of instructions executed before the alert.
This would allow us to identify possible cases where a register file initialized to zero is expected. This should never be the case.

Alternatively, also other less problematic reasons for the failures could be:
- An instruction somehow ends up in the OTBN pipeline but the pipeline isn't executing. The register file addresses are still forwarded to the regfile and ECC is evaluated.
- An instruction with a different format is executed and the bits in the field indicating the register file address have a different meaning. Nevertheless, the register file is read and ECC is evaluated.
- ...

These cases wouldn't need fixing.

**Comment by vogelpi** [comment]
@rswarbrick @GregAC @msfschaffner

**Comment by andreaskurth** [comment]
> I think @andreaskurth solved this as part of #13192.

Correct; when #13192 gets merged, any read from an uninitialized register will trigger an integrity error. That PR will also fix existing software that assumes pre-initialized registers (certainly SW that gets tested in CI).

**Comment by vogelpi** [comment]
I am closing this issue as #13192 has been merged.
