### ISSUE TITLE
[dv/foundry] Calculations for ROM ECC in foundry database 

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#9766]
The foundry ROM fails due to the following addition in PR #9245:
DV_CHECK_FATAL((this.width < bits_per_subword) || (this.width % bits_per_subword == 0),
"With multiple subwords, mem width must be a multiple of the ECC width")
cc: @tjaychen

**Comment by tjaychen** [comment]
huh... this is odd. I didn't think ROM would have this issue.

**Comment by sha-ron** [comment]
Fixed via PR in the close source database.
