### ISSUE TITLE
[sram] question about escalation

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#9777]
@msfschaffner 
When escalation is set, SRAM will no longer accept any access. If the access is taken just before escalation occurs, sram won't respond with d_valid=1 (see the transaction with source=aa in below waveform).
![Screen Shot 2021-12-20 at 2 05 27 PM](https://user-images.githubusercontent.com/49293026/146839165-cb5a5c6b-e938-410b-9ae0-12d9e9bc0f83.png)

I'm curious if this happens in real chip, will it cause the bus hang? We need a reset to get out of escalation, but is it better to just respond the request with d_error=1, so that SW can still do some other access before the chip gets reset?

**Comment by msfschaffner** [comment]
Hey @weicaiyang - indeed, this is the currently specified behavior, see also [here in the spec](https://docs.opentitan.org/hw/ip/sram_ctrl/doc/index.html#lifecycle-escalation).

I am not sure we should change this. @tjaychen do you see any value in changing this behavior?

**Comment by tjaychen** [comment]
i think this is okay.
@msfschaffner correct me if i'm wrong, but the usual alert escalation path goes interrupt -> nmi -> escalation / scrap -> reset.

So the time for software to respond and do something would have been in the interrupt / nmi group if things are configured that way. Once we get to escalation / scrap, there shouldn't really be any expectation for software to be able to gracefully do anything.

**Comment by weicaiyang** [comment]
Thanks @msfschaffner and @tjaychen. If we don't expect SW to do anything after escalation, the current design makes sense

**Comment by msfschaffner** [comment]
> i think this is okay. @msfschaffner correct me if i'm wrong, but the usual alert escalation path goes interrupt -> nmi -> escalation / scrap -> reset.
> 
> So the time for software to respond and do something would have been in the interrupt / nmi group if things are configured that way. Once we get to escalation / scrap, there shouldn't really be any expectation for software to be able to gracefully do anything.

Yeah exactly.

**Comment by weicaiyang** [comment]
Thanks @msfschaffner for the confirmation. Closing this issue.
