### ISSUE TITLE
JTAG RISCV Driver returns incorrect read data

### ISSUE THREAD

**Issue by NigelScales** [lowRISC/opentitan#9795]
The JTAG RISCV driver returns read data with the upper 2 bits zeroed.
It has shown up during verification of the LC_CTRL JTAG registers.

I've found the cause and fixed it locally as shown below.
task send_csr_dr_req has the wrong size for field dout.

![image](https://user-images.githubusercontent.com/78102677/147089310-0d5ed90f-bfb8-4929-9348-48a28429587a.png)

**Comment by tjaychen** [comment]
@cindychip 
@weicaiyang 
@sha-ron

**Comment by weicaiyang** [comment]
Thanks @NigelScales for finding the issue and the root cause. Can you push your local fix to a PR? Thanks
