### ISSUE TITLE
[sw] Mandate C11

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#981]
The C/C++ style guide does not currently specify a specific version of the C standard to use. It seems prudent to do so.

In the Makefiles, we use `-std=gnu99` which is C99 with non-standard gnu extensions.

The google C++ style guide, which our C/C++ style guide is based on, [mandates not using non-standard extensions](https://google.github.io/styleguide/cppguide.html#C++_Version). I understand the value of this, but also understand the value of some non-standard extensions. It would be nice to know what gnu extensions we are currently using.

We currently mandate C++14 (which I think is reasonable), so it seems reasonable to choose C11 (rather than C17). My understanding is there are no major changes between C11 and C17, only clarifications in some wording.

I welcome feedback on this proposal

**Comment by asb** [comment]
My view: I'm in favour of both moving towards -std=c11 and making the style guide specify that C11 should be used. I think this issue can be used to track both changes, and I expect separate PRs would make sense.

Regarding non-standard extensions: I don't think code should use them when not necessary, but I'm not sure a blanket ban is justified for extensions supported by both Clang and GCC.

**Comment by asb** [comment]
CC @gkelly @mcy @moidx

**Comment by lenary** [comment]
I have no problem with the following nonstandard extensions (all can still be used with `-std=c11`, and are supported by both GCC and clang):
- Inline assembly
- Nonstandard attributes
- Compiler builtins (`__builtin_*`)

I think it is prudent to require that any nonstandard extensions that are used should be supported by both GCC and clang.

I would recommend against other nonstandard extensions until consensus is built that they help more than they hinder.

**Comment by mcy** [comment]
A few comments:
- I am on board with C11, since I assume we don't really care about MSVC support?
- For all non-standard extensions other than inline assembly, I'd like for us to write down some sort of policy for hiding the raw extensions behind macros, e.g., `OT_BUILTIN_MEMCPY` rather than `__builtin_memcpy`. I think that this kind of hygine is important when using extensions.

Even then, we should have a whitelist of attributes and builtins we allow, which I think this hygine requirement will help with.

**Comment by lenary** [comment]
- I agree that things like `__attribute__((section("foo")))` could be hidden behind something like `OT_SECTION("foo")` for portability reasons.
- I think the equivalent for builtins is to define a name not starting `__builtin_*` which just contains a call to the builtin (and so the body can be extended if we port to compilers that don't include that builtin). I do not like wrapping the builtins in `OT_BUILTIN_*` macros.

One advantage of C11 is that a few attributes that opentitan is using are now standardised (`_Noreturn`, `_Alignas`). I don't see the `section`, `interrupt` or `weak` attributes ever being standardised, so that seems a good whitelist to start with (these five are the only attributes used in opentitan at the moment, that I could find).

**Comment by mcy** [comment]
Sure, "macro" or "inline function" is really just an implementation detail: I think we agree on the key point that we don't want random code calling `__builtin_`s

**Comment by lenary** [comment]
Shall I start working on a pull request to the style guide based on this discussion?

**Comment by asb** [comment]
I'm not fully convinced on the benefit of hiding `__builtin_*`. The reality is that we are targeting C + a small set of extensions that are common to GCC and Clang. We could try to hide the builtins behind macros or inline functions, but I feel the explicit use of `__builtin` does convey additional semantic information:
* If I see a `__builtin_clz` I know there's a good chance the compiler has some semantic understanding of the operation, more so than with e.g `ot_builtin_clz`
* The semantics of `__builtin_*` are easily searchable and documented. e.g. `__builtin_constant_p`.

Defining a whitelist feels a bit heavyweight for such a young project. I'd be more comfortable giving a recommendation, perhaps even saying that extensions beyond a certain list shouldn't be used if it can be avoided. We can loop back and tighten up later if experience shows that is doable.
