### ISSUE TITLE
[spi_device] abort_done implementation

### ISSUE THREAD

**Issue by kosta-kojdic** [lowRISC/opentitan#9823]
abort_done is not implemented in the design. Add this functionality.

**Comment by kosta-kojdic** [comment]
@eunchan will this feature be implemented. If so, what is timeline?

**Comment by eunchan** [comment]
I think, this can be P3 item, good to have. So, I probably work on this in next revision or later. Please waive this item.

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. I think this is not necessary for this release and thus correctly labeled https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease.

**Comment by msfschaffner** [comment]
CC @a-will

**Comment by a-will** [comment]
The notion of the device side being able to "abort" anything doesn't make sense to me. It is not in control of timing and software cannot reasonably time the effect of any CSR write here.

Besides, generic mode is being removed. Closing.
