### ISSUE TITLE
[spi_device/passthrough] CMD_INFO slots 0-10 reset values

### ISSUE THREAD

**Issue by kosta-kojdic** [lowRISC/opentitan#9833]
CMD_INFO slots 0 to 10 are reserved for specific commands. If it is the case, why reset values (at least for opcodes) are not set to these command values instead of 0's ? Also, why are they writable?

As it stands now we can have illegal data written to these registers and provoke OnlyOneDatapath_A assertion error.

**Comment by eunchan** [comment]
> 
> CMD_INFO slots 0 to 10 are reserved for specific commands. If it is the case, why reset values (at least for opcodes) are not set to these command values instead of 0's ? Also, why are they writable?
> 
That is due to the multireg feature not allowing arbitrary reset values per register. And the read commands may have different dummy size, and address requirements. So that's why those fields are configurable
> As it stands now we can have illegal data written to these registers and provoke OnlyOneDatapath_A assertion error.
> 
Could you share me the waveform?

**Comment by kosta-kojdic** [comment]
#9834 PR - command:
./util/dvsim/dvsim.py hw/ip/spi_device/dv/spi_device_sim_cfg.hjson -i spi_device_pass_cmd_filtering --fixed-seed 3 --waves --xprop-off -v h --max-parallel 1

**Comment by eunchan** [comment]
Looks like, the programmed opcode is not unique. The logic assumed the programmed opcode should be unique in each cmd slot.

By the way, after introducing the `valid` bit in CMD_INFO slot, I think the cmdparse should see the valid bit also. Let me quickly revise the design to check the validity.

Thanks!

**Comment by kosta-kojdic** [comment]
@eunchan any updates on this issue? Did you make some design revisions?

**Comment by eunchan** [comment]
> 

The pending PR addresses the valid bit issue. But firstly please make sure you programmed the cmd_info slot correctly.

**Comment by kosta-kojdic** [comment]
> > 
> 
> The pending PR addresses the valid bit issue. But firstly please make sure you programmed the cmd_info slot correctly.

By programming CMD info slot correctly, do you mean programming all fixed slots (the ones before the slot I programmed) with proper values?

**Comment by eunchan** [comment]
Yes. Do not  program the same opcode value into two slots. Then the assertion won't fire.

**Comment by kosta-kojdic** [comment]
OK, so if we keep reset values for some slots, even if these slots are not enabled, assertion will fire?

**Comment by eunchan** [comment]
Yes, in the current design. After PR #9875 is merged, it won't.
