### ISSUE TITLE
[spi_device/passthrough] Passthrough mode additional explanations

### ISSUE THREAD

**Issue by kosta-kojdic** [lowRISC/opentitan#9839]
Couple of questions about passthrough mode:

1. Can you clarify the function of passthrough_i and passthrough_o signals? Do we need to drive data to passthrough_i input? What is the relation between them and sdi and sdo? Where we should expect data to go in passthrough mode?
2. In passthrough mode, when we have address bits coming from the input, do we receive LSB or MSB address bits first? If it is LSB, I think this part in address swap is wrong:
assign addr_swap = cfg_addr_mask_i[addrcnt_outclk]
                   ? cfg_addr_value_i[addrcnt_outclk]
                   : host_s_i[0]
because addrcnt counts down, so for lowest bits it will have highest bits from swap register

**Comment by eunchan** [comment]
Sorry for late responses.

> Couple of questions about passthrough mode:
> 
> 1. Can you clarify the function of passthrough_i and passthrough_o signals? Do we need to drive data to passthrough_i input? What is the relation between them and sdi and sdo? Where we should expect data to go in passthrough mode?
>
`passthrough_i` comes from the external flash device (downstream). SPI interface is inout interface. The SPI_DEVICE talks to pinmux unidirectionally. So the downstream interface consists of input/ output of same data line. 

> 2. In passthrough mode, when we have address bits coming from the input, do we receive LSB or MSB address bits first? If it is LSB, I think this part in address swap is wrong:
>    assign addr_swap = cfg_addr_mask_i[addrcnt_outclk]
>    ? cfg_addr_value_i[addrcnt_outclk]
>    : host_s_i[0]
>    because addrcnt counts down, so for lowest bits it will have highest bits from swap register
>
SPI Flash interface comes MSB first.

**Comment by weicaiyang** [comment]
@eunchan 

Kosta also asked the relationship between sdi/sdo and passthrough_i/o.
If I understand correctly, when a request is passthrough, we will observe sdi on passthrough_o and the returned data on passthrough_i will be received on sdo. Is it right? I guess there is no delay and no flip flop between sdi/sdo and passthrough_i/o, right?

Should we use Dual or Quad mode for passthrough? Or it also support single mode?

**Comment by eunchan** [comment]
> @eunchan <https://github.com/eunchan>
> Kosta also asked the relationship between sdi/sdo and passthrough_i/o.
> If I understand correctly, when a request is passthrough, we will observe sdi on passthrough_o and the returned data on passthrough_i will be received on sdo. Is it right? I guess there is no delay and no flip flop between sdi/sdo and passthrough_i/o, right?
> 
Right. They  are just the split signals of `inout` SD. Think about PAD input/output towards the digital logic.
> Should we use Dual or Quad mode for passthrough? Or it also support single mode?
> 
Passthrough supports Single/Dual/ Quad SPI flash commands. For Dual/Quad, only output commands are supported not Dual IO/ Quad IO.

**Comment by weicaiyang** [comment]
> For Dual/Quad, only output commands are supported not Dual IO/ Quad IO.

Sorry, I don't understand this. Output commands are something like read command, which it has to be dual/quad mode, right? Non-output commands are like program/erase, and they don't have returned data, so these can be signal mode? Not sure if I understand it correctly?

**Comment by eunchan** [comment]
> On Jan 6, 2022, at 11:05 AM, weicaiyang ***@***.***> wrote:
> 
> 
> For Dual/Quad, only output commands are supported not Dual IO/ Quad IO.
> 
> Sorry, I don't understand this. Output commands are something like read command, which it has to be dual/quad mode, right? Non-output commands are like program/erase, and they don't have returned data, so these can be signal mode? Not sure if I understand it correctly?
> 
> 
Right. Read command is mostly output command (the device returns data). But it can be IO command also. Dual/ Quad IO commands the host sends address field in two lanes or four lanes and receives the return data in two lanes or four lanes. The output commands the host sends the address field in SD[0] only.

**Comment by weicaiyang** [comment]
> On Jan 6, 2022, at 11:05 AM, weicaiyang ***@***.***> wrote: For Dual/Quad, only output commands are supported not Dual IO/ Quad IO. Sorry, I don't understand this. Output commands are something like read command, which it has to be dual/quad mode, right? Non-output commands are like program/erase, and they don't have returned data, so these can be signal mode? Not sure if I understand it correctly?
> Right. Read command is mostly output command (the device returns data). But it can be IO command also. Dual/ Quad IO commands the host sends address field in two lanes or four lanes and receives the return data in two lanes or four lanes. The output commands the host sends the address field in SD[0] only.

Got it. Thanks @eunchan

**Comment by kosta-kojdic** [comment]
Thanks, I will close this now
