### ISSUE TITLE
[docs] Turn on sitemap generation for docs pages

### ISSUE THREAD

**Issue by gkelly** [lowRISC/opentitan#984]

**Comment by gkelly** [comment]
@vogelpi @sjgitty @towoe

**Comment by vogelpi** [comment]
Thanks @gkelly for creating this issue. I think this would be very useful. 
Right now, it is a bit cumbersome to go back and forth between IP specification and dashboard (for example when comparing IPs and their status). The site map would help in this particular scenario has also other use cases.

**Comment by msfschaffner** [comment]
I believe this has been addressed by now - closing this issue.
