### ISSUE TITLE
[lc_ctrl] Simultaneous mutex claim does not prioritize JTAG 

### ISSUE THREAD

**Issue by NigelScales** [lowRISC/opentitan#9847]
If a mutex claim is issued simultaneously from Tile Link and JTAG, JTAG is not prioritized.
In fact currently **both** are selected.
In the waves it can be seen that when simultaneous requests come then both claim_transition_if registers are set to 0x5a and both transition_regwen registers are set to 1.

To reproduce:
gh pr checkout 9846
./util/dvsim/dvsim.py hw/ip/lc_ctrl/dv/lc_ctrl_sim_cfg.hjson -i lc_ctrl_jtag_priority --fixed-seed 1 -v m --tool xcelium --waves

  

![image](https://user-images.githubusercontent.com/78102677/147746402-ba6c2747-3852-4824-999e-7b6441018019.png)

**Comment by msfschaffner** [comment]
Thanks for reporting this, @NigelScales.
This does not look right - l made a fix for this in #9860.
