### ISSUE TITLE
[lc_ctrl] transition_regwen is not temporally set to 0 during transitions.

### ISSUE THREAD

**Issue by NigelScales** [lowRISC/opentitan#9848]
During the period between writing the transition_cmd register until the status register indicates completion, it's expected that transition_regwen should be 0 and writing to the transition specific registers should be disabled.
This doesn't appear to be the case.
Transition_regwen stays 1 throughout and writing is also enabled throughout.

To reproduce: 
gh pr checkout 9846
./util/dvsim/dvsim.py hw/ip/lc_ctrl/dv/lc_ctrl_sim_cfg.hjson -i lc_ctrl_regwen_during_op --fixed-seed 1  -v m --tool xcelium --waves

![image](https://user-images.githubusercontent.com/78102677/147759394-83dc1077-0705-4359-a8a1-23cde65040f1.png)

**Comment by msfschaffner** [comment]
Thanks @NigelScales.
Looks like a simple 1 char bug ;) (default assignment is 1 instead of 0). 
Fix is in #9860.
