### ISSUE TITLE
[entropy_src, security] Need to prevent generation of FIPS entropy before FIPS thresholds are set.

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#9853]
The `entropy_src` FSM has two modes of entropy "BOOT" and "FIPS".  The health checks for the two modes have different stringency requirements and are configured at different times in the boot process.
1. As indicated in #9492, the boot thresholds are meant to be very light, meant to catch very gross defects in the `entropy_src`.  These must be programmed in _OTP_ memory to allow for the creation of entropy pre-boot.
2. FIPS (or CC) grade entropy requires the addition of more stringent health-check thresholds to make sure that the `entropy_src` outputs achieve maximal entropy at the output of the conditioning block.  The final decision for these thresholds must be reserved for _firmware_, as they may require some knowledge of post silicon tolerances in the RNG.

Furthermore, since the `entropy_src` prohibits the relaxation of thresholds after reset (they can only be strengthened), the default values are always set to their most relaxed values by default.

The current plan (#9492) then requires the entropy source to be enabled by the ROM (using OTP values), while leaving the FIPS thresholds wide open.   Furthermore the transition from BOOT mode to "FIPS" mode is automatic.   This means that any few "FIPS mode" seeds that come out before the ROM_EXT comes on line will be labelled as full-entropy ("FIPS"==1), but without any real health checking.

We need a mechanism to prevent the generation of fully-qualified entropy until all of the "FIPS" health check thresholds have been fully populated.  (If such a mechanism already exists it needs to be called out in the register spec).

**Comment by mwbranstad** [comment]
Judging by the boot sequence in #9492, the case of FIPS entropy generated with "weak" thresholds can easily be avoided with the proper programming sequence. In the ROM phase, ES will be requested by EDN0 for a single seed, assume that only a single csrng gen command will be issued. Once the boot moves to ROM_EXT phase, then all blocks can be re-programmed, and ES will have strong thresholds set. This should work unless the boot sequences changes from the current plan.

**Comment by mwbranstad** [comment]
After reading this issue closer, the above comment does not cover the hole. I am considering a change where the FIPS_ENABLE field is used to control a new boot option. When set, this field will operate in legacy mode. When not set, the boot sequence will complete (if boot_bypass is not set) like always, then the main sm will halt. It will wait until the main enable is cleared. Then once enabled again after FIPS thresholds have been programmed, the main sm will move on to the startup sequence. This allows a two-phase sequencing scheme directed by software. This should ensure that any FIPS tagged seeds are health checked with the correct threshold settings.

**Comment by martin-lueker** [comment]
Couldn't we just put something into to stall the FSM if it gets too far (and all the fifos).  Like in SPI_HOST?

**Comment by mwbranstad** [comment]
The proposal is to do exactly that, stall the FSM optionally.

**Comment by martin-lueker** [comment]
Though your approach works as well of course (and probably leads to a cleaner implementation).  If we go the route of having two separate pathways we should perhaps eliminate the `boot_bypass` switch,  and just always bypass the boot seed if we are starting in FIPS mode.

I would actually like that.  The whole thing would be very clean and simple, and the two pathways would be nicely separated.

The only downside I see is that you would need to update your beautiful state diagram.

**Comment by martin-lueker** [comment]
> The proposal is to do exactly that, stall the FSM optionally.

Oh, I meant a recoverable stall.  Where you can flip a switch and the whole IP just continues as if nothing happened.  Though it requires that _everything_ in the entire pipeline gets a "stall" signal, that can be asserted or deasserted.  That works for SPI_HOST, but your pipeline is much more complex here.  The SPI_HOST approach could lead to madness.  it would probably be better to do something different here.

**Comment by mwbranstad** [comment]
We also need to maintain legacy mode for CI at this point (so the picture can stay). I am more interested in simple (limited) changes that solve the specific problem and maintain any current function. I think this implementation will solve both, but waiting on https://github.com/lowRISC/opentitan/pull/10150 to land first before implementing.

**Comment by martin-lueker** [comment]
Fair enough, but three points:
1. Nobody will _ever_ use `enable_fips && !boot_bypass`
2. I like the idea of a nice intuitive state machine diagram
3. I'm happy to thread the CI to make this change if it means a cleaner design.

**Comment by martin-lueker** [comment]
4. The picture needs some update to communitcate that boot-mode does not continue.

**Comment by martin-lueker** [comment]
Do you intend to try to land #9949 as is, or do you want to rebase that on top of #10150 and amend implement the new scheme in there?

**Comment by martin-lueker** [comment]
Though I see your point.  Having a "BootStall" state or something would be fine.

**Comment by martin-lueker** [comment]
Note: #9949 is only a partial Fix to this issue.  [See the ongoing discussion or how this resolution will continue](https://github.com/lowRISC/opentitan/pull/9949#discussion_r789841304)

**Comment by martin-lueker** [comment]
FYI @msfschaffner

**Comment by msfschaffner** [comment]
@martin-lueker The above PR referenced PRs have been merged. What is the status of this right now?

**Comment by mwbranstad** [comment]
@msfschaffner I can answer this. I believe consensus has been reached (here and possibly some other related issues) so implementation will be done soon. PR in progress.

**Comment by msfschaffner** [comment]
Ok good, thanks. Does this gate D2S?

**Comment by mwbranstad** [comment]
This is not a security based item, but a functional phasing issue. This should not gate D2S.
