### ISSUE TITLE
[doc] consider different style render for `backtick` within docs

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/opentitan#986]
This was item 4 in #723:

style nit: `backtick` content is hard to distinguish from normal font content, I miss the gray background

Perhaps I'm alone in this so I would like to hear other voices too. I find it a bit hard to distinguish between the two fonts as currently rendered, ie:

![Screenshot from 2019-11-14 13-31-42](https://user-images.githubusercontent.com/41092437/68897885-40a32d00-06e3-11ea-8429-b7debd816f7d.png)

**Comment by eunchan** [comment]
Agree. The font is too big personally. I am using `console` class to make it gray background.

**Comment by msfschaffner** [comment]
@HU90m @hcallahan-lowrisc is this still an issue with the recent documentation revamp?

**Comment by HU90m** [comment]
![image](https://github.com/lowRISC/opentitan/assets/45573837/791eb942-014c-4612-a49d-11cbef36466b)

Verbatim text is far clearer in the new style. I think it is safe to close this.
