### ISSUE TITLE
[doc] render SystemVerilog Style Guide?

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/opentitan#988]
This was item 12 in #723 

We have `doc/rm/verilog_coding_style.md`. The goal was to get the one in lowrisc/style-guides rendered somewhere so that we could point to that, but that has not yet been done. I recommend we remove `doc/rm/verilog_coding_style.md` but we have no way to render something from outside. The other option is to vendor it in. Opinions?

**Comment by asb** [comment]
The desired end-point is that all of the style guides are promoted to lowRISC-wide style guides. We can either produce a nicely rendered version on lowrisc.org and link to that or vendor in and render on opentitan.org. I have a slight preference for the former option, but it's a not a particularly strongly held view...

**Comment by towoe** [comment]
I think it makes sense to render it on lowrisc.org and link to it. We also refer to other sites in the C++ so pointing to another site should not be a problem.
Ibex could then also reference style guides if one is desired.

**Comment by sjgitty** [comment]
@asb any updates on the notion of rendering the style guide so that we can deprecate the one in OT repo?

**Comment by imphil** [comment]
I wouldn't invest in custom rendering, the GitHub rendered version at https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md looks readable enough I think?

**Comment by imphil** [comment]
We went for the GH default rendering of the style guide, and removed the existing style guide in https://github.com/lowRISC/opentitan/pull/1733.
