### ISSUE TITLE
[arch,aon] Create a set of target specific AON clock frequency constants

### ISSUE THREAD

**Issue by doreis-lowrisc** [lowRISC/opentitan#9927]
The AON timer doesn't have a constant in `device.h` to hold the clock frequency.
Additionally it seems that the current frequency used for Verilator is the same as the rv_timer (125 kHz) rather than the specified in the documentation (200 kHz).

**Comment by doreis-lowrisc** [comment]
Tagging @silvestrst and @mundaym for visibility

**Comment by silvestrst** [comment]
@sriyerg , just out of curiosity, why the AON clock frequency on verilator is 125kHz, whilst everywhere else its 200kHz?

**Comment by sriyerg** [comment]
> @sriyerg , just out of curiosity, why the AON clock frequency on verilator is 125kHz, whilst everywhere else its 200kHz?

Verilator is a cycle accurate simulator (i.e. single-clock). We mimic async clock domains by integer-dividing a single source clock.
