### ISSUE TITLE
[gpio] modify TB to account for 2 stage sync delay

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#9941]
See #9826 for context.

> estimate 2

**Comment by johngt** [comment]
@msfschaffner / @GregAC - what additional effort is required here? It looks like the PR referenced have been merged in? Please update task desc with outstanding work required.

**Comment by msfschaffner** [comment]
@johngt indeed, the fix only addressed the RTL side. 
We need to make sure the testbench accounts for this delay as well (note: depending on how accurate the timing is tracked on the testbench side, this delay may not matter).

**Comment by msfschaffner** [comment]
Actually, gauging from the GPIO simulation results, it looks like the delay does not affect the testbench results (we're way past 90% except for #17345).

Given that GPIO is tested implicitly in many tests at the top-level and FPGA tests, I think I am ok with deferring this as a cleanup task to after M2.5.

**Comment by msfschaffner** [comment]
The GPIO scoreboard is unfortunately pretty inflexible and would have to be significantly rewritten in order to accommodate the additional synchronizer delay. In addition to that, certain tests would still not be possible if CDC randomization is enabled.

However, since the CDC primiitves are only present on the GPIO input path, and since they do not affect the GPIO functionality other than adding 2-3 cycles of delay, it should be ok if we add a simple test that just makes sure that the CDC primitives are connected correctly.

To that end, #18948 adds a second build mode with CDC primitives enabled.
In that build mode, only the GPIO smoke test is run with relaxed timing in the vseq.
