### ISSUE TITLE
[rtl/clkmgr] Tighten measurement timeout

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#9969]
I created a test that turns off measured clocks to verify the timeout functionality. I found the clock can be off for a couple of AON cycles and no timeout will be generated, even though `ref_en` is active. In contrast, a regular measurement asserts `valid` almost concurrently with the assertion of `ref_en`.

I think this weakens the timeout mechanism, allowing the clock to be shut down for enough time with nothing detecting it. See the waves below. The specific test is still under development, but it will eventually become part of the clkmgr_frequency test.

![Screenshot from 2022-01-10 10-52-25](https://user-images.githubusercontent.com/80294896/148825015-cea22f42-1162-486d-934f-14cd44b32b56.png)

**Comment by tjaychen** [comment]
sounds good.  If i understand correctly, you're saying there are scenarios where the clock is not there but timeout is not asserted?

**Comment by matutem** [comment]
Correct. It seems the logic allows for too much time before it detects a timeout.

**Comment by matutem** [comment]
By the way, the code changes that triggers this behavior are in the ot_launch session that failed to send back a patch. I hope to retrieve it.

**Comment by matutem** [comment]
It seems a timeout could be declared not much later than `valid` would be asserted.
