### ISSUE TITLE
[usbdev] Make sure wakeup and resume time is within spec

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#9972]
We should assess whether the wakeup and resume timing is within the USB spec.
This will probably have to be a chip-level test, since it depends on a variety of system properties and not only on the `usbdev` alone.

This bug is to make sure we don't forget provisioning such a test in our testplans (it might already be there, in which case we can resolve this issue).

See also #9905 for reference.

CC @a-will 

>estimate 16
>remaining 2023-03-23 8

**Comment by vogelpi** [comment]
Thanks for opening the issue. We have an item in the testplan to check the wakeup and resume feature but it doesn't state to measure the timing.

**Comment by msfschaffner** [comment]
Ok, thanks for checking. Can you copy paste the name of the item here?
@kosta-kojdic can we update that item accordingly?

**Comment by tjaychen** [comment]
it should be this one `chip_sw_usb_suspend`. 
The test does not explicitly point out the suspend timing, it describes more the internal mechanism.

We should add a line to indicate this needs to be spec compliant during testing.

**Comment by kosta-kojdic** [comment]
@msfschaffner Can you point me to the test plan you are referring to? For usbdev I am not aware of existing extensive testplan in OpenTitan hjson format.

**Comment by msfschaffner** [comment]
I believe this one is a chip-level integration test: https://docs.opentitan.org/hw/top_earlgrey/doc/dv/

**Comment by msfschaffner** [comment]
@msfschaffner

**Comment by johngt** [comment]
Also tagging @alees24 on this.

**Comment by a-will** [comment]
Agreed that it would be better to have the aon_wake_module handle it. It doesn't seem like a terribly dire situation, but it'd be nice to not have additional software delays added to boot time, however small. :)

Just to put the optimization into perspective: The device has 10 _seconds_ to disconnect the pull-up after VBUS is removed (section 7.2.1), then afterwards, the software part requires at least 2.5 us of having the pull-ups disconnected (the max time allowed before a hub is required by spec to detect disconnection events).

**Comment by alees24** [comment]
From my understanding when we awaken to a 'Disconnect' report from aon/wake we need only remove the pull up for the few microseconds that you mention, to ensure that the hub/host spots it.

It's worth noting that we should probably be doing that anyway, because a break in the VBUS/SENSE signal doesn't necessarily mean that a pull up deassertion has been seen by the host; suppose there's an electrical issue/contact problem on VBUS but not on D+/D-; then we could be under the impression that we've been disconnected, but the host thinks otherwise, and we thus become unresponsive, having returned to the Powered state.

**Comment by moidx** [comment]
@johngt can you update timing estimates on this issue to determine what work is remaining for M2.5.2? Thanks

**Comment by alees24** [comment]
M2.5.2
> estimate 0

**Comment by johngt** [comment]
Per @alees24 comment - closing this issue for this current MS.
Can re-open / create a new issue post the current milestone.
