### ISSUE TITLE
[sw/ottf] Add timing API to the test framework

### ISSUE THREAD

**Issue by ghost** [lowRISC/opentitan#9984]
The test `sw/device/tests/aon_timer_wakeup_irq_test.c` is using rv_timer to compute timing, however it may conflict with the FreeRTOS when`configUSE_PREEMPTION==1` since it also uses the rv_timer. 
To prevent conflict in case the aon timer test need to be executed with preemption:

- An timing API shall be created by the Test framework (reference API in `sw/device/lib/runtime/ibex.h`);
- Refactor `aon_timer_wakeup_irq_test.c` to use this API.

**Comment by doreis-lowrisc** [comment]
Tagging @silvestrst , @mundaym,@sriyerg and @timothytrippel for visibility.

**Comment by msfschaffner** [comment]
@arunthomas this may have to be re-labeled.

**Comment by timothytrippel** [comment]
> @arunthomas this may have to be re-labeled.

Done. I marked as low-priority for now, as this will only be an issue if this test is re-purposed for the power virus test (where concurrency, and therefore FreeRTOS use, is turned on).

**Comment by timothytrippel** [comment]
This is not an issue as we do not run said tests in concurrency mode.
