### ISSUE TITLE
[doc] We don't document what the magic countermeasure names mean

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#9985]
We've got a list of `CM_ASSETS` and `CM_TYPES` in `countermeasures.py` but we don't have a description of what they mean in any openly visible document. We probably should!

**Comment by rswarbrick** [comment]
@msfschaffner for visibility, but you don't necessarily have to be the person to do it! (Also, I wouldn't bother with anything automatic: we can just type out a table manually somewhere and leave a note at the top of the Python code to keep the two in sync)

**Comment by vogelpi** [comment]
I agree that we should do that after the D2S reviews, i.e., when the list of assets and types have stabilized. Right now the descriptions are in a Google doc.

**Comment by rswarbrick** [comment]
Understood, but at the moment we're adding random words to the list in the Python file, which is kind of hard to review :-) I don't see any strong reason not to decide on what we mean now!

**Comment by msfschaffner** [comment]
Documenting this sounds good to me.
This could go into the comportability spec here:
https://github.com/lowRISC/opentitan/blob/master/doc/rm/comportability_specification/index.md#alert-hardware-implementation
